### ISSUE TITLE
Save with formatting

### ISSUE THREAD

**Issue by DoctorRyner** [helix-editor/helix#10024]
Right now there is no way to format and save file in one command, this `w = [":format", ":w"]` doesn't work because it saves before formatter works

**Comment by pascalkuthe** [comment]
that is what the autosave option is for

**Comment by DoctorRyner** [comment]
@pascalkuthe no, I don't need formatting to work on save, I want it to save file when I do formatting

**Comment by kirawi** [comment]
This is essentially a duplicate of https://github.com/helix-editor/helix/issues/9126 for the source issue

**Comment by kirawi** [comment]
This is essentially a duplicate of https://github.com/helix-editor/helix/issues/9126 (just the other way around)
