### ISSUE TITLE
clipboard-yank does not work via ssh 

### ISSUE THREAD

**Issue by qiref** [helix-editor/helix#10027]
### Summary

clipboard-yank does not work when I using helix on item2

when I use Alacritty ,  clipboard-yank is working.

### Reproduction Steps

 

I tried this:

1. ssh remote linux on item2
2. `hx file` and use `clipboard-yank`
3. Nothing happend when `cmd v`

I found this solution, but I used ssh, I hope copy from system clipboard when I closing ssh session.
https://github.com/helix-editor/helix/wiki/Troubleshooting#on-linux

When I switch to alacritty ,  `clipboard-yank` is working, I can use `cmd v` when closing ssh session.

### Helix log

<details><summary>~/.cache/helix/helix.log</summary>

```
No error in `~/.cache/helix/helix.log`  
```

</details>

### Platform

Linux

### Terminal Emulator

item2

### Installation Method

releases page

### Helix Version

helix 23.10 (f6021dd0)

**Comment by kirawi** [comment]
What does hx --health say?

**Comment by qiref** [comment]
> What does hx --health say?

```
$ hx --health
Config file: /root/.config/helix/config.toml
Language file: default
Log file: /root/.cache/helix/helix.log
Runtime directories: /root/.config/helix/runtime;/data/workspace/service/helix-23.10-x86_64-linux/runtime
Clipboard provider: termcode
System clipboard provider: termcode
```

**Comment by archseer** [comment]
> Enable OSC 52 in iterm2
[#](https://jdhao.github.io/2021/01/05/nvim_copy_from_remote_via_osc52/#enable-osc-52-in-iterm2)
>
>  Open preferences, and go to General settings. Turn on the option Applications in terminal may access clipboard. It’s off by default for security reasons.

**Comment by alvin883** [comment]
@qiref I got curious so I tried to repro the issue, I used iTerm v3.4.23 to ssh to linux and used the same helix version, it works fine though. It also output `System clipboard provider: termcode` on the health

Perhaps you haven't enable clipboard terminal access in iTerm? it's under Preferences -> General -> Selection -> _"Applications in terminal may access clipboard"_ and you should check that box
