### ISSUE TITLE
nightfox theme doesn't highlight characters in Amp-like jumping

### ISSUE THREAD

**Issue by tqwewe** [helix-editor/helix#10047]
I've updated to Helix 24.03, but when using Amp-like jumping, the two-letter characters don't get highlighted, so it's quite difficult to determine which letters to press to jump to a section.

**Default Theme**
<img width="530" alt="Screenshot 2024-03-30 at 11 16 13 pm" src="https://github.com/helix-editor/helix/assets/16362377/dbd1238e-4565-4000-b1cc-14575cb825b3">

**Nightfox Theme**
<img width="556" alt="Screenshot 2024-03-30 at 11 15 32 pm" src="https://github.com/helix-editor/helix/assets/16362377/95a18a00-3f37-4e72-b9ae-b5aec5256e88">

**Comment by the-mikedavis** [comment]
nightfox will need to define `"ui.virtual.jump-label"` or `"ui.virtual"` (which is used as a fallback) https://github.com/helix-editor/helix/blob/2cadec0b1182332338a5a1cc3062776f834d8835/runtime/themes/nightfox.toml
