### ISSUE TITLE
keybind not working: delete_selection_noyank, search_prev

### ISSUE THREAD

**Issue by timokoesters** [helix-editor/helix#10050]
### Summary

This should do the same as `?=<enter>`. This works if I replace delete_selection_noyank with delete_selection.

```
"C-l" = [
  ":append-output echo -n =",
  "search_selection",
  "delete_selection_noyank",
  "search_prev",
]

```

The response on matrix was:

> It could be the case that delete_selection_noyankkeeps the register at _ so search_prev tries looking at _ (which is the null register) so it doesn't do anything

https://matrix.to/#/!zMuVRxoqjyxyjSEBXc:matrix.org/$nt9EkBO1jiVDOp1LDJf0hBHk_MmipL6RttvCJMU1-es?via=matrix.org&via=tchncs.de&via=mozilla.org

### Platform

Linux

### Terminal Emulator

Alacritty

### Installation Method

AUR

### Helix Version

helix 23.10

**Comment by the-mikedavis** [comment]
The _noyank commands set the register to `_` but the register isn't reset if the commands are run in a keymap sequence. These functions https://github.com/helix-editor/helix/blob/0da58656958184677b44372f72a922baacfc4940/helix-term/src/commands.rs#L2698-L2710

could be updated to save the value of `cx.register` before `cx.register = Some('_')` and reset `cx.register` to that value after the deletion/change

**Comment by voiceroy** [comment]
Something along these lines?
```rust
fn delete_selection_noyank(cx: &mut Context) {
    let old_register = cx.register;
    cx.register = Some('_');
    delete_selection_impl(cx, Operation::Delete);
    cx.register = old_register;
}

fn change_selection(cx: &mut Context) {
    let old_register = cx.register;
    delete_selection_impl(cx, Operation::Change);
    cx.register = old_register;
}

fn change_selection_noyank(cx: &mut Context) {
    let old_register = cx.register;
    cx.register = Some('_');
    delete_selection_impl(cx, Operation::Change);
    cx.register = old_register;
}

```

**Comment by the-mikedavis** [comment]
On second thought I would prefer we introduce an extra parameter `yank: bool` to `delete_selection_impl`:

```rust
fn delete_selection(cx: &mut Context) {
    delete_selection_impl(cx, Operation::Delete, true);
}

fn delete_selection_noyank(cx: &mut Context) {
    delete_selection_impl(cx, Operation::Delete, false);
}

fn change_selection(cx: &mut Context) {
    delete_selection_impl(cx, Operation::Change, true);
}

fn change_selection_noyank(cx: &mut Context) {
    delete_selection_impl(cx, Operation::Change, false);
}
```

It would mean that we do an unnecessary allocation when you use `"_d` or `"_c"` but it's more explicit and simpler, and also fixes this issue.

**Comment by voiceroy** [comment]
I think
```toml
"C-l" = [
  ":append-output echo -n =",
  "search_selection",
  "delete_selection_noyank",
  "search_prev",
]
```
appends an `=` next to the current character and then selects it, then deletes it without yanking (assuming it's fixed), and then searches for a previous match which would be the same character found at the initial 'run' of this keybind. Whenever the keybind `C-l` is run this would be the process. Hence not going to previous selection as `N` would do after `?=<enter>`.
