### ISSUE TITLE
allow z-c to remain in effect even in normal and insert mode.

### ISSUE THREAD

**Issue by LollipopFt** [helix-editor/helix#1005]
#### Describe your feature request

i was thinking of bufferscroll package typewriter function in sublime text, where the text remained at the centre of the screen as you typed. when pressing enter or when cursor was moved up or down, the text would automatically shift to make the current line at the centre of the screen. the problem is that helix does not implement this as ```align_view_center``` cannot be mapped together with original functionality of "up" key, "move_line_up". will 2 commands be able to be mapped to one key in the future, or will this be allowed in future plugin functionality? thanks!
<details>
<summary>
video of the functionality in sublime text:
</summary>

https://user-images.githubusercontent.com/62802897/140645836-7c92ae05-b7f4-4204-b518-87117ec7d0bb.mp4

</details>

**Comment by EpocSquadron** [comment]
@LollipopFt I think you can approximate this functionality by setting a high enough `scrolloff` in your config. https://docs.helix-editor.com/configuration.html

**Comment by Omnikar** [comment]
> will 2 commands be able to be mapped to one key in the future

#589

**Comment by LollipopFt** [comment]
thanks guys!
