### ISSUE TITLE
allow goto_word to be chainable command

### ISSUE THREAD

**Issue by kujohn** [helix-editor/helix#10092]
Right now, `goto_word` requires input to be completed. Is there a way to chain command so that when I use `goto_word`, it would follow with additional commands?

```
"'" = [
 "goto_word",
 "move_prev_word_start",
 "collapse_selection"
]
```

**Comment by pascalkuthe** [comment]
I don't think that's particular to goto_word. `f` and `t` use the same mechanism

**Comment by pascalkuthe** [comment]
dulpicate of #4013
