### ISSUE TITLE
Ability to add languages without recompiling the editor

### ISSUE THREAD

**Issue by irishgreencitrus** [helix-editor/helix#1012]
I'm wondering if it is possible to add a tree sitter config without recompiling the editor. I can't see this as being possible in the documentation, and without this feature it makes it hard to add new language support.

**Comment by archseer** [comment]
To add a grammar to helix, you only need to add the definition to `languages.toml`, and you need to place the compiled tree-sitter grammar into `runtime/grammars/<name>.so`. So you should be able to use external grammars just fine without recompiling helix, the UX is just not as straightforward.

**Comment by irishgreencitrus** [comment]
> To add a grammar to helix, you only need to add the definition to `languages.toml`, and you need to place the compiled tree-sitter grammar into `runtime/grammars/<name>.so`. So you should be able to use external grammars just fine without recompiling helix, the UX is just not as straightforward.

At least it's possible, I guess.
Is there a guide on how to compile a treesitter module?

**Comment by archseer** [comment]
This should be possible now that the hx cli has a `--grammar` flag for fetching and compiling grammars.
