### ISSUE TITLE
No syntax highlighting for goto_word markers in several themes

### ISSUE THREAD

**Issue by eguiraud** [helix-editor/helix#10135]
### Summary

The new goto_word (`gw`) is fantastic, but the two-letter markers don't get highlighted in some times such as `ayu_dark`:

The file:
![image](https://github.com/helix-editor/helix/assets/10999034/6e95cc09-7dea-463b-b310-4e9c118afb08)

After pressing `gw`:
![image](https://github.com/helix-editor/helix/assets/10999034/4d2864b0-f214-4228-9fe5-4217c9204681)

Same but with the default theme:
![image](https://github.com/helix-editor/helix/assets/10999034/fc3f9fd0-fe0d-456a-98bd-4c48cb38d33c)

### Reproduction Steps

See above.

### Helix log

Logs not needed, I think.

### Platform

Arch Linux

### Terminal Emulator

alacritty

### Installation Method

source

### Helix Version

helix 24.3 (3d6f34c2)

**Comment by pascalkuthe** [comment]
Jump mode was merged close to release so many themes weren't updated yet. We have been merging a lot of ttheme updates the last few days (pretty sure ayu dark was merged recently too for example). You can take the theme from the repo and put it in your config.

I will close this issue since I don't think we need to exhaustively track ebrry the.e here. The themes will be updated by the people using them.

**Comment by hippie68** [comment]
By "people" in this context do you mean regular users using Helix, fixing the (broken) shipped themes in their Helix installation directory (most possibly without ever contributing the fixes on GitHub) or do you mean developers already assigned to specific themes?

I want to understand if you mean the users should fix the themes for themselves.

I found a different bug in the default theme, which is not displaying rulers. I am unsure how to proceed. It seems issues about themes are not wanted? But on the other hand, if it is contributions that are wanted I don't know yet how to fix it for you. And I can't possibly decide for other people which ruler color the default theme is supposed to have.
