### ISSUE TITLE
is "down" a special key?

### ISSUE THREAD

**Issue by LollipopFt** [helix-editor/helix#1013]
![image](https://user-images.githubusercontent.com/62802897/140726960-17c4e670-f5fe-489f-94a5-83c179478461.png)
in your docs, you did not mention anything about the "down" key, i discovered it also worked when i used it in config. i suspect you forget to add it in, should i open a pull request for it?

**Comment by sudormrfbin** [comment]
Down is a normal key similar to the others, I guess it got deleted accidentally from the docs.
