### ISSUE TITLE
add support for autopairs of certain keys

### ISSUE THREAD

**Issue by LollipopFt** [helix-editor/helix#1014]
#### Describe your feature request

allow autopairs of ```"``` and ```'``` keys
personally i think the first one: ```"``` is most commonly used for strings, and should thus be autopaired.
second one: ```'``` can sometimes be used in lifetime annotations i guess, so not necessary to add this one.

**Comment by LollipopFt** [comment]
oops didn't notice this issue: #966

**Comment by LollipopFt** [comment]
oops didn't notice this issue: #992

**Comment by archseer** [comment]
https://github.com/helix-editor/helix/pull/995 solves this, got merged today

**Comment by LollipopFt** [comment]
hi @archseer , this did not seem to be resolved:

https://user-images.githubusercontent.com/62802897/140758409-4523723a-aff8-47ce-a251-8a6140b438c6.mp4
there is still no autopair for ```"```.

**Comment by archseer** [comment]
Ah sorry, I confused auto-pairs and match-brackets.

**Comment by dead10ck** [comment]
If folks don't mind a kind of slow pace, I'd like to take a crack at this and #992. I've been looking over the basics of the code base, and I think I'm at a place now where I could work on this. I just don't have a ton of free time, so it may be days between bits of work.

If anyone sees this and gets impatient, please feel free to go your own way independent of me.
