### ISSUE TITLE
Unusual fill colour behind comments in tmux

### ISSUE THREAD

**Issue by LeonLonsdale** [helix-editor/helix#10155]
### Summary

When using tmux with Helix, for **some themes**, an unusual fill colour is applied to commented text. This is not the case outside of tmux, and the same behaviour does not apply when using vim / neovim within tmux.

### Reproduction Steps

To reproduce, just open helix in tmux and look for/add comments.

Note* I only use JS/TS so I can't confirm if this is the case with other languages.

Here it is in tmux:

<img width="821" alt="Screenshot 2024-04-04 at 13 51 11" src="https://github.com/helix-editor/helix/assets/130412639/5d4bb0d1-a7e7-4d8b-a1aa-2b89310addee">

The same file outside of tmux:

<img width="768" alt="Screenshot 2024-04-04 at 13 51 55" src="https://github.com/helix-editor/helix/assets/130412639/8307abd5-3589-48bd-b11c-d74a50537714">

This is in a TSX file with typescript-language-server installed and in use.

### Platform

macOS

### Terminal Emulator

Wezterm, Warp

### Installation Method

brew

### Helix Version

Helix 24.3 (2cadec0b)

**Comment by the-mikedavis** [comment]
See https://github.com/helix-editor/helix/wiki/Troubleshooting#the-theme-doesnt-look-as-it-should
