### ISSUE TITLE
A flag to open Helix in a read-only mode.

### ISSUE THREAD

**Issue by Oglo12** [helix-editor/helix#10174]
I want to use Helix as my pager for the man command. But I want an option to open Helix in a read-only mode, thus banning the use of the `:w` command all together. I am actually kind of surprised the editor doesn't have this yet!

**Comment by kirawi** [comment]
see https://github.com/helix-editor/helix/pull/7128#issuecomment-1581560237

**Comment by heaths** [comment]
See discussion at https://github.com/helix-editor/helix/discussions/11586

**Comment by the-mikedavis** [comment]
Yeah let's close this in favor of https://github.com/helix-editor/helix/discussions/11586
