### ISSUE TITLE
What about `text suggestion` support?

### ISSUE THREAD

**Issue by adriangalilea** [helix-editor/helix#10258]
I fully understand the decision not to implement copilot...

But! Perhaps the interface of showing text suggestions can be on Helix so LSP's can use it.

<img width="480" alt="ghost suggestion text" src="https://github.com/helix-editor/helix/assets/90320947/cf9626e7-fa24-409a-9d8f-26e64c9bc799">

This is generic enough that maybe is better implemented as a primitive natively on Helix, and would improve the DX drastically of using any completion AI.

_Originally posted by @adriangalilea in https://github.com/helix-editor/helix/discussions/4037#discussioncomment-9012709_

**Comment by pascalkuthe** [comment]
lsp has completions which can support that, we are not adding lsp extensions to core
