### ISSUE TITLE
tree-sitter with musl target

### ISSUE THREAD

**Issue by ath3** [helix-editor/helix#1028]
When i build helix with --target=x86_64-unknown-linux-musl, tree-sitter related things dont seem to work.
There is no syntax highlight and textobject queries.
LSP seems to work.

Content of helix.log:

2021-11-08T23:30:37.722 helix_lsp::transport [ERROR] err <- "[ERROR project_model::workspace] cyclic deps: helix_view(CrateId(167)) -> helix_tui(CrateId(161)), alternative path: helix_tui(CrateId(161)) -> helix_view(CrateId(167))\n"

**Comment by archseer** [comment]
Try `cargo clean` & wipe `runtime/grammars/*`. It's possible the grammars didn't get recompiled with musl.

**Comment by ath3** [comment]
I got the following error message now:

error: failed to run custom build command for `helix-syntax v0.5.0 (/home/ath3/git/helix/helix-syntax)`

Caused by:
  process didn't exit successfully: `/home/ath3/git/helix/target/debug/build/helix-syntax-a80d4d6fcd798bad/build-script-build` (exit status: 101)
  --- stdout
  Build language elixir
  Build language glsl
  Build language protobuf
  Build language cpp
  Build language yaml
  Build language agda
  Build language cmake
  Build language svelte
  Build language css
  Build language latex
  Build language ledger
  Build language go
  Build language java
  Build language lua
  Build language julia
  Build language toml
  Build language nix
  Build language zig
  Build language bash
  Build language c-sharp
  Build language php
  Build language json
  Build language scala
  Build language c
  Build language javascript
  Build language perl
  Build language rust
  Build language python
  Build language vue
  Build language ruby
  Build language swift
  Build language tsq
  Build language html

  --- stderr
  thread '<unnamed>' panicked at 'called `Result::unwrap()` on an `Err` value: Failed to execute C compiler

  Caused by:
      No such file or directory (os error 2)', helix-syntax/build.rs:172:36
  note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
  thread '<unnamed>' panicked at 'called `Result::unwrap()` on an `Err` value: Failed to execute C compiler

  Caused by:
      No such file or directory (os error 2)', helix-syntax/build.rs:172:36
  thread '<unnamed>' panicked at 'called `Result::unwrap()` on an `Err` value: Failed to execute C compiler

  Caused by:
      No such file or directory (os error 2)', helix-syntax/build.rs:172:36
  thread '<unnamed>' panicked at 'called `Result::unwrap()` on an `Err` value: Failed to execute C compiler

  Caused by:
      No such file or directory (os error 2)', helix-syntax/build.rs:172:36
  thread '<unnamed>' panicked at 'called `Result::unwrap()` on an `Err` value: Failed to execute C compiler

  Caused by:
      No such file or directory (os error 2)', helix-syntax/build.rs:172:36
  thread '<unnamed>' panicked at 'called `Result::unwrap()` on an `Err` value: Failed to execute C compiler

  Caused by:
      No such file or directory (os error 2)', helix-syntax/build.rs:172:36
  thread '<unnamed>' panicked at 'called `Result::unwrap()` on an `Err` value: Failed to execute C compiler

  Caused by:
      No such file or directory (os error 2)', helix-syntax/build.rs:172:36
  thread '<unnamed>' panicked at 'called `Result::unwrap()` on an `Err` value: Failed to execute C compiler

  Caused by:
      No such file or directory (os error 2)', helix-syntax/build.rs:172:36
  thread 'thread '<unnamed><unnamed>' panicked at '' panicked at 'called `Result::unwrap()` on an `Err` value: Failed to execute C compiler

  Caused by:
      No such file or directory (os error 2)called `Result::unwrap()` on an `Err` value: Failed to execute C compiler

  Caused by:
      No such file or directory (os error 2)', ', helix-syntax/build.rshelix-syntax/build.rs::172172::3636

  thread '<unnamed>' panicked at 'called `Result::unwrap()` on an `Err` value: Failed to execute C compiler

  Caused by:
      No such file or directory (os error 2)', helix-syntax/build.rs:172:36
  thread '<unnamed>' panicked at 'called `Result::unwrap()` on an `Err` value: Failed to execute C compiler

  Caused by:
      No such file or directory (os error 2)', helix-syntax/build.rs:172:36
  thread '<unnamed>' panicked at 'called `Result::unwrap()` on an `Err` value: Failed to execute C compiler

  Caused by:
      No such file or directory (os error 2)', helix-syntax/build.rs:172:36
  thread '<unnamed>' panicked at 'called `Result::unwrap()` on an `Err` value: Failed to execute C compiler

  Caused by:
      No such file or directory (os error 2)', helix-syntax/build.rs:172:36
  thread '<unnamed>' panicked at 'thread 'called `Result::unwrap()` on an `Err` value: Failed to execute C compiler

  Caused by:
      No such file or directory (os error 2)', <unnamed>helix-syntax/build.rs' panicked at ':called `Result::unwrap()` on an `Err` value: Failed to execute C compiler

  Caused by:
      No such file or directory (os error 2)172', :helix-syntax/build.rs36:
  172:36
  thread '<unnamed>' panicked at 'called `Result::unwrap()` on an `Err` value: Failed to execute C compiler

  Caused by:
      No such file or directory (os error 2)', helix-syntax/build.rs:172:36
  thread '<unnamed>' panicked at 'called `Result::unwrap()` on an `Err` value: Failed to execute C compiler

  Caused by:
      No such file or directory (os error 2)', helix-syntax/build.rs:172:36
  thread '<unnamed>' panicked at 'called `Result::unwrap()` on an `Err` value: Failed to execute C compiler

  Caused by:
      No such file or directory (os error 2)', helix-syntax/build.rs:172:36
  thread '<unnamed>' panicked at 'called `Result::unwrap()` on an `Err` value: Failed to execute C compiler

  Caused by:
      No such file or directory (os error 2)', helix-syntax/build.rs:172:36
  thread '<unnamed>' panicked at 'called `Result::unwrap()` on an `Err` value: Failed to execute C compiler

  Caused by:
      No such file or directory (os error 2)', helix-syntax/build.rs:172:36
  thread '<unnamed>' panicked at 'called `Result::unwrap()` on an `Err` value: Failed to execute C compiler

  Caused by:
      No such file or directory (os error 2)', helix-syntax/build.rs:172:36
  thread '<unnamed>' panicked at 'called `Result::unwrap()` on an `Err` value: Failed to execute C compiler

  Caused by:
      No such file or directory (os error 2)', helix-syntax/build.rs:172:36
  thread '<unnamed>' panicked at 'called `Result::unwrap()` on an `Err` value: Failed to execute C compiler

  Caused by:
      No such file or directory (os error 2)', helix-syntax/build.rs:172:36
  thread '<unnamed>' panicked at 'called `Result::unwrap()` on an `Err` value: Failed to execute C compiler

  Caused by:
      No such file or directory (os error 2)', helix-syntax/build.rs:172:36
  thread '<unnamed>' panicked at 'called `Result::unwrap()` on an `Err` value: Failed to execute C compiler

  Caused by:
      No such file or directory (os error 2)', helix-syntax/build.rs:172:36
  thread '<unnamed>' panicked at 'called `Result::unwrap()` on an `Err` value: Failed to execute C compiler

  Caused by:
      No such file or directory (os error 2)', helix-syntax/build.rs:172:36
  thread '<unnamed>' panicked at 'called `Result::unwrap()` on an `Err` value: Failed to execute C compiler

  Caused by:
      No such file or directory (os error 2)', helix-syntax/build.rs:172:36
  thread '<unnamed>' panicked at 'called `Result::unwrap()` on an `Err` value: Failed to execute C compiler

  Caused by:
      No such file or directory (os error 2)', helix-syntax/build.rs:172:36
  thread '<unnamed>' panicked at 'called `Result::unwrap()` on an `Err` value: Failed to execute C compiler

  Caused by:
      No such file or directory (os error 2)', helix-syntax/build.rs:172:36
  thread '<unnamed>' panicked at 'called `Result::unwrap()` on an `Err` value: Failed to execute C compiler

  Caused by:
      No such file or directory (os error 2)', helix-syntax/build.rs:172:36
  thread '<unnamed>' panicked at 'called `Result::unwrap()` on an `Err` value: Failed to execute C compiler

  Caused by:
      No such file or directory (os error 2)', helix-syntax/build.rs:172:36
  thread '<unnamed>' panicked at 'called `Result::unwrap()` on an `Err` value: Failed to execute C compiler

  Caused by:
      No such file or directory (os error 2)', helix-syntax/build.rs:172:36
  thread 'main' panicked at 'assertion failed: `(left == right)`
    left: `0`,
   right: `33`', helix-syntax/build.rs:201:5
warning: build failed, waiting for other jobs to finish...
error: build failed

**Comment by ath3** [comment]
Can we label this as bug? Unless its working for other people of course.

**Comment by archseer** [comment]
I think you're likely missing some environment variables so `cc-rs` can find the compiler.

**Comment by archseer** [comment]
`CC` etc

**Comment by archseer** [comment]
Possibly missing `musl-gcc`? https://github.com/alexcrichton/cc-rs/issues/105#issue-180622054

**Comment by jlneder** [comment]
I have a similar problem. I am using Void Linux with musl.
I removed the `runtime/grammars` folder, ran `cargo clean`, built helix with `cargo install --path helix-term --target=x86_64-unknown-linux-musl` and copied the runtime folder to `~/.config/helix/runtime`.
Even when i use helix with three v as in `hx -vvv rustfile.rs` the log file in `~/.cache/helix/helix.log` is still empty.
I have no syntax highlight and no LSP support.
I installed tree-sitter, but i guess maybe I'm missing some package or lsp server or something?

**Comment by ath3** [comment]
Yeah, as it stands now, i cant use helix on our rhel8 work machine.
@archseer: would it be possible to offer musl builds for release versions?

**Comment by pickfire** [comment]
My pi uses musl too bad sadly I can't even build some of the dependencies (non-helix) there. If possible I could have tested it there.

**Comment by archseer** [comment]
Looks like https://github.com/helix-editor/helix/issues/1603 is building on musl

**Comment by pascalkuthe** [comment]
Since helix is now packaged for alpine (see https://github.com/helix-editor/helix/issues/1603#issuecomment-1030148271) which ships musl this seems resolved to me.

**Comment by archseer** [comment]
Alpine patches their Rust distribution to pass the extra flag. It's still an issue but should be worked around by the end user. Maybe we could add it to the documentation

**Comment by pascalkuthe** [comment]
I did leave #1603 open as I wasn't 100% sure if that was still the case. I don't think we need to separate issues for this.

However I was able to build and run the latest helix master just fine (including working tree sitter grammars) in the rust alpine linux docker image which installs rustc using rustup (so without any patches). I think https://github.com/rust-lang/rust/pull/40113 fixed this.

**Comment by archseer** [comment]
There was https://github.com/helix-editor/helix/pull/4818 and we discovered https://github.com/gtk-rs/gtk-rs-core/issues/387#issuecomment-977039928 so Alpine patches this: https://git.alpinelinux.org/aports/tree/community/rust/0001-When-linking-statically-on-musl-based-system-also-li.patch

**Comment by pascalkuthe** [comment]
Yeah I just noticed I messed up something I while testing. Sorry about that! I will add an FAQ entry.
