### ISSUE TITLE
`ada_language_server` listed twice

### ISSUE THREAD

**Issue by cloudlena** [helix-editor/helix#10316]
### Summary

When running `hx --health`, `ada_language_server` is listed twice:

The same goes for the documentation https://github.com/helix-editor/helix/blob/cf99615b433fa4708604460e0b2298cf92833960/book/src/generated/lang-support.md?plain=1#L3.

To me, this is quite confusing. Is it correct?

### Reproduction Steps

1. Run `hx --health ada`

### Platform

Linux

### Terminal Emulator

alacritty 

### Installation Method

nixpkgs

### Helix Version

helix 24.03

**Comment by archseer** [comment]
Please submit a PR

**Comment by cloudlena** [comment]
Thanks, @archseer. I'm happy to provide a PR.
However, the issue seems to be that the documentation is generated from https://github.com/helix-editor/helix/blob/master/languages.toml. It only takes the `command` property of the language servers which, in case of `ada` is the same for both options because they only differ in the `args`. I'm not sure how to sustainably propagate that differentiation.

Ideally, it would be done in an automated way but ignoring the `args` for all other language servers to avoid cluttering the docs. What do you think? Do you have any guidance on how to proceed?

**Comment by the-mikedavis** [comment]
Deduplicating the command names seems like the right choice to me here. Or we could switch that column from the name of the binary to the name of the language server. That column predates #2507 which refactored language servers so that they have names in the config

**Comment by timothyhutz** [comment]
As a new Rust Dev, can I take this fix? I'll send you a PR from my fork.

**Comment by timothyhutz** [comment]
Fixed and tested https://github.com/helix-editor/helix/pull/10563
