### ISSUE TITLE
incorrect jump label highlight when non-ascii chars are used

### ISSUE THREAD

**Issue by Iorvethe** [helix-editor/helix#10315]
### Summary

In certain cases, the jump labels on the first line are not highlighted in the jump mode. If the same line is not at the top, the same labels are highlighted.

<details><summary>example.txt</summary>

```
  ← nnsp
first second



































```

</details>

### Reproduction Steps

Here’s a [screencast](https://asciinema.org/a/BbFdehownD9VyiDZ1C2pgU1Qq).

I tried this:

1. `hx example.txt`
2. `ge`
3. `gw`

I expected this to happen:

- The label of the first word of the topmost line to be highlighted. 

Instead, this happened:

- The label was there, but not highlighted, only the text was changed.

### Helix log

No relevant log.

### Platform

Linux

### Terminal Emulator

alacritty 0.13.1 (fe2a3c56)

### Installation Method

source

### Helix Version

24.03-59-g3d72173b

**Comment by pascalkuthe** [comment]
please attach your example.txt file next time you post an issue like this

**Comment by Iorvethe** [comment]
Hi, perhaps you missed it, it’s right below the summary section

**Comment by pascalkuthe** [comment]
a sorry, yeah I didn't see that. I was able to reproduce regardless that is pretty odd. For me it does render a jump label but only for the second char which is even more odd (may be related to my fork tough)

**Comment by Iorvethe** [comment]
I agree, it’s bizarre. I have other files with neither `nnbsp` nor `nbsp` and the issue is also present, but when trying to narrow it to a minimal working example, I ended up with the posted file. I suppose the issue is the same in both cases

**Comment by pascalkuthe** [comment]
Ah I think I found it

**Comment by pascalkuthe** [comment]
its unicode chars in general, I mixed up byte and char range

**Comment by Iorvethe** [comment]
Great!
