### ISSUE TITLE
Syntax highlighting for LDIF is missing

### ISSUE THREAD

**Issue by quanah** [helix-editor/helix#10324]
### Summary

When opening an [RFC2849](https://datatracker.ietf.org/doc/html/rfc2849)LDIF file, syntax highlighting is missing.

### Reproduction Steps

 

I tried this:

1. `hx <file>.ldif`

I expected this to happen:

syntax highlighting

Instead, this happened:

no syntax highlighting

### Helix log

<details><summary>~/.cache/helix/helix.log</summary>

```
please provide a copy of `~/.cache/helix/helix.log` here if possible, you may need to redact some of the lines
```

</details>

### Platform

MacOS

### Terminal Emulator

N/A

### Installation Method

brew

### Helix Version

helix 24.3 (2cadec0b)

**Comment by gabydd** [comment]
https://github.com/kepet19/tree-sitter-ldif

**Comment by quanah** [comment]
tyvm!!
