### ISSUE TITLE
Cannot recognize symbolic links on Windows

### ISSUE THREAD

**Issue by endereyewxy** [helix-editor/helix#10326]
### Summary

File pickers and `:open` cannot recognize symbolic links. `:write` simply overwites them.

### Reproduction Steps

I tried this:

1. Create symbolic linked files:
    ```powershell
    New-Item a.txt
    New-Item -Type SymbolicLink -Target b.txt -Path .\a.txt
    ```
    This should create an empty `a.txt` and a symbolic link `b.txt` under the current working directory.

2. `hx`
3. `:open b.txt`
4. Type something, and then `:write`

I expected this to happen:

As `b.txt` is a symbolic link to `a.txt`, modifications should apply to both files.

Instead, this happened:

The original symbolic link is overwritten, and `b.txt` is now a normal file. `a.txt` remains unchanged. BTW, the file picker won't recognize `b.txt` at the beginning.

### Helix log

Nothing interesting in the logs.

### Platform

Windows

### Terminal Emulator

Windows Terminal

### Installation Method

source

### Helix Version

24.03-121-g35d0ae7c

**Comment by woojiq** [comment]
This may be a regression/side effect of #9330

**Comment by pascalkuthe** [comment]
Not really, normally writes to symolik links are handeled transparently by the OS.

This is a regression caused by #9236. @kirawi I think you need to cannonicalizing before writing the file, same issue would even occur on Linux.
