### ISSUE TITLE
Display aliases in command info box

### ISSUE THREAD

**Issue by cole-h** [helix-editor/helix#1036]
#### Describe your feature request

Just like Kakoune does, it would be nice to display the aliases attached to a command.

Example:

![image](https://user-images.githubusercontent.com/28582702/140857591-4959cb86-b968-4b98-9e8c-2a5ea0670ee5.png)

**Comment by archseer** [comment]
There's an open PR here but it needs some more work: https://github.com/helix-editor/helix/pull/989

**Comment by cole-h** [comment]
Ah, thanks! I looked through the issues, but not open PRs :sweat_smile:

**Comment by the-mikedavis** [comment]
Looks like this has been implemented: https://github.com/helix-editor/helix/pull/989#issuecomment-1046168706

![aliases](https://user-images.githubusercontent.com/21230295/163716556-2f103ce1-9ef4-40cd-a1a0-a50c6d038716.png)
