### ISSUE TITLE
Unsaved scratch buffer shouldn't prevent exiting gracefully

### ISSUE THREAD

**Issue by cole-h** [helix-editor/helix#1037]
### Reproduction steps

1. `hx`
2. Type into the scratch buffer
3. `:q`
4. Observe the inability to exit, with an error of `1 unsaved buffer(s) remaining: ["[scratch]"]`

### Environment

- Platform: Linux
- Helix version: `v0.5.0-60-gded1ac9`

---

Since you can't save a scratch buffer without writing it to a path, an unsaved scratch buffer shouldn't block `:q`.

**Comment by kirawi** [comment]
You can use `:q!` to force quit.

**Comment by sudormrfbin** [comment]
IMO the current behavior should be kept as is, since it doesn't make an empty scratch buffer give an error, and only errors for a dirty scratch buffer. There will be no way to recover any data if we allowed exiting with `:q` on a dirty scratch buffer, whereas you can always use `:q!` to override this.

**Comment by cole-h** [comment]
I guess I subscribe to the belief that one shouldn't store any data they would mind losing in a buffer that's not backed by a file, and that this pseudobuffer shouldn't prevent me from closing the editor.

That said, I can see arguments either way, and indeed `kak` has the behavior I'd expect (the scratch buffer doesn't report that it's modified), while `nvim` has the current `hx` behavior.

**Comment by Omnikar** [comment]
I agree with @sudormrfbin, `:q` shouldn't allow you to lose anything you've typed, and a dirty scratch buffer means that there's stuff in the buffer that will be lost if it isn't saved. `:q` should not allow anything to be lost as such.

**Comment by pickfire** [comment]
> IMO the current behavior should be kept as is, since it doesn't make an empty scratch buffer give an error, and only errors for a dirty scratch buffer. There will be no way to recover any data if we allowed exiting with :q on a dirty scratch buffer, whereas you can always use :q! to override this.

I don't see why we want to special case unsafe scratch buffer, it should behave like how unsafe file should behave, vim and kak does this too IIRC.

**Comment by cole-h** [comment]
I'm going to close this because I've actually been saved by this before. It is jarring when switching from e.g. kakoune, which doesn't do this, but I'm convinced this is the correct and proper behavior.

**Comment by ShalokShalom** [comment]
I suggest to at least give info, how to close it. 

I just ran into this, and it gave me sooo feelings of [this](https://stackoverflow.com/questions/11828270/how-do-i-exit-vim).

Adding a hint hurts nobody.

**Comment by kirawi** [comment]
It's mentioned in 1.2 of the tutor.

**Comment by ShalokShalom** [comment]
I literally ran into it 10 seconds after launching the editor for the first time.😃 

Where is the problem, to display this along with the error that it cant close? 
Is there any issue with that solution?
