### ISSUE TITLE
Helix cannot work because of incorrect config file

### ISSUE THREAD

**Issue by freetz13** [helix-editor/helix#1038]
#### Describe your feature request

If there is an error in config, Helix just won't start. I need to fix its config, but what if Helix is the only editor I can use?

In such case, NeoVim shows an error, then just starts. At least, I can fix the incorrect part of the config.

**Comment by archseer** [comment]
What helix version are you on (you didn't fill the issue template)? This was recently fixed in master. https://github.com/helix-editor/helix/pull/982

**Comment by freetz13** [comment]
> What helix version are you on (you didn't fill the issue template)? This was recently fixed in master. #982

I use 0.4.1 version from community Manjaro repository. I tried to install `helix-git` from AUR, but

```
==> Starting build()...
error: failed to load manifest for workspace member `/home/user/.cache/yay/helix-git/src/helix/helix-core`

Caused by:
  failed to parse manifest at `/home/user/.cache/yay/helix-git/src/helix/helix-core/Cargo.toml`

Caused by:
  feature `edition2021` is required

  The package requires the Cargo feature called `edition2021`, but that feature is not stabilized in this version of Cargo (1.55.0).
  Consider trying a newer version of Cargo (this may require the nightly release).
  See https://doc.rust-lang.org/nightly/cargo/reference/unstable.html#edition-2021 for more information about the status of this feature.
==> ERROR: A failure occurred in build().
    Aborting...
 -> error making: helix-git
```

, so for now I can't test it, sorry.

**Comment by archseer** [comment]
It should build if you update your local Rust installation, `1.56.0` is available in [Extra](https://archlinux.org/packages/extra/x86_64/rust/)
