### ISSUE TITLE
Fetch failing due to moving of `tree-sitter-grammar`

### ISSUE THREAD

**Issue by dalanmiller** [helix-editor/helix#10399]
### Summary

I'm currently unable to fetch the current grammars. They appear to have moved. 

from: https://git.sr.ht/~sfr/tree-sitter-gemini/
to: https://git.sr.ht/~nbsp/tree-sitter-gemini

```
❯ hx -g fetch
Fetching 163 grammars
162 up to date git grammars
Failure 1/1: gemini Git command failed.
Stdout:
Stderr: fatal: unable to access 'https://git.sr.ht/~sfr/tree-sitter-gemini/': The requested URL returned error: 403

Error: 1 grammars failed to fetch
```

### Reproduction Steps

I think anyone can reproduce this by simply trying to fetch the grammar. 

### Helix log

No log present

### Platform

MacOS

### Terminal Emulator

iTerm 

### Installation Method

brew

### Helix Version

helix 23.10 (f6021dd0)

**Comment by pascalkuthe** [comment]
you are building a quite outdated version there. Newer versions have disabled fetching all grammar from source hut due to unreliability issues like this one

**Comment by dalanmiller** [comment]
++ took a look in the code base, upgraded and now all good. Thank you!
