### ISSUE TITLE
"<number> goto [next/previous] buffer" only executes once

### ISSUE THREAD

**Issue by mersenne-twister** [helix-editor/helix#10400]
### Summary

Executing the 'goto next buffer'/'goto previous buffer' command with a number prepended will only move a singe buffer.

### Reproduction Steps

1. open at least 3 buffers.
2. `2gp` while at the farthest right buffer.

Expected Behaviour:
it should move however many times is specified, in this case twice.

Actual Behavior:
it only moved a single buffer left.

### Helix log

<details><summary>~/.cache/helix/helix.log</summary>

```
please provide a copy of `~/.cache/helix/helix.log` here if possible, you may need to redact some of the lines
```

</details>

### Platform

Arch Linux Xorg Xmonad

### Terminal Emulator

alacritty 0.13.2 (bb8ea18e)

### Installation Method

pacman

### Helix Version

helix 24.3

**Comment by pascalkuthe** [comment]
this was previously discussed in #9258. This issue has a better description/more concise and the only part of that issue I actually want to see land so I am closing the other one in favor of this one.

This should be quite trivial to add
