### ISSUE TITLE
More bindings should be accessible as `:` commands

### ISSUE THREAD

**Issue by cole-h** [helix-editor/helix#1045]
#### Describe your feature request

Right now, binds like `C-c` are only accessible through their bindings. Making them accessible in the `:` menu would make it easier to play around with them without having to refer to the keymap document.

**Comment by archseer** [comment]
Somewhat related https://github.com/helix-editor/helix/issues/559

**Comment by the-mikedavis** [comment]
I'm going to close this out because the command picker is merged (#1400) but we can re-open if you have thoughts on exposing more non-typable commands as typable commands as well.
