### ISSUE TITLE
Tweak warning color for gruvbox_light theme 

### ISSUE THREAD

**Issue by Locorock** [helix-editor/helix#10455]
The current behaviour of the theme grubox_light is for the warnings to be written using the orange1 color, when it should be yellow1 instead, according to the original gruvbox vim theme at https://github.com/morhetz/gruvbox. We can see an example on how it should look here: 

![image](https://camo.githubusercontent.com/c4cba075d914d33531eced4b3b9e5a5ccb6762599fa4047264127a1fae8363ce/687474703a2f2f692e696d6775722e636f6d2f5837356e6945612e706e67)
How it currently looks with orange1 as warning:
![grim-2024-apr-16-03_40_22](https://github.com/helix-editor/helix/assets/6536547/cfa7da10-c023-420d-bc33-5c15df452f7b)
and how it would look with `"warning" = { fg = "yellow1" }`:
![grim-2024-apr-16-03_43_47](https://github.com/helix-editor/helix/assets/6536547/12fd31e3-60c5-4aee-a508-141803a8a553)
I know it doesn't look much different but the contrast between error and warning benefits greatly from this change

**Comment by RoloEdits** [comment]
Hmm, `gruvbox_light` inherits from `gruvbox` for most things, including the colors of the diagnostic highlights.

This is what is currently defined:
```toml
"warning" = "orange1"
"error" = "red1"
"info" = "aqua1"
"hint" = "blue1"
```

This is what I found in in the `gruvbox` repo:
```vim
call s:HL('CocErrorHighlight', s:none, s:none, s:undercurl, s:red)
call s:HL('CocWarningHighlight', s:none, s:none, s:undercurl, s:orange)
call s:HL('CocInfoHighlight', s:none, s:none, s:undercurl, s:yellow)
call s:HL('CocHintHighlight', s:none, s:none, s:undercurl, s:blue)
```

From this, the outlier seems to be `info`.

I may be misunderstanding what you mean though.

**Comment by Locorock** [comment]
This seems to be the case for CoC, but oddly enough only for CoC. 
and not for Syntastic:
```
call s:HL('SyntasticError', s:none, s:none, s:undercurl, s:red)
call s:HL('SyntasticWarning', s:none, s:none, s:undercurl, s:yellow)
```
or ALE:
```
call s:HL('ALEError', s:none, s:none, s:undercurl, s:red)
call s:HL('ALEWarning', s:none, s:none, s:undercurl, s:yellow)
call s:HL('ALEInfo', s:none, s:none, s:undercurl, s:blue)
```
and the screenshots clearly show yellow as being used for warnings

**Comment by RoloEdits** [comment]
Huh, weird. Well I guess with the majority using yellow, and stated improved contrast, might as well change them all over to yellow. Let me do a quick check for all the themes and see if the base `gruvbox` can just be changed over and propagated and have an easy single file change, and I can get up a pr for this.
