### ISSUE TITLE
Dedent behavior

### ISSUE THREAD

**Issue by dead10ck** [helix-editor/helix#1046]
#### Describe your feature request

It would be great if helix had dedent behavior similar to other editors. In particular:

* [ ] Hitting `o` to go to a new line auto indents. If you then immediately hit `Esc`, it should delete all of the whitespace and just leave a blank line.
* [x] Similarly, if you hit `o`, and then backspace (i.e. the line contains nothing but whitespace before the cursor), then each backspace should dedent, rather than just delete a single whitespace character (#1120)

**Comment by WindSoilder** [comment]
> Hitting o to go to a new line auto indents. If you then immediately hit Esc, it should delete all of the whitespace and just leave a blank line.

I don't know if it's a good behavior, it sesms that `Esc` is conflict with current `Esc` behavior(switch to normal mode)

**Comment by dead10ck** [comment]
> I don't know if it's a good behavior, it sesms that `Esc` is conflict with current `Esc` behavior(switch to normal mode)

It would do both, i.e. delete all the automatically inserted whitespace and then go back to normal mode. This is the behavior of vim with autoindent.

**Comment by archseer** [comment]
Reverted in c955eaa6cd607621d8be091564b2fd6bf30f54c3, further work needs to be done:

1. pressing `o` on a line with no indentation will open a new line as
   expected, but `esc` will then delete the line altogether

2. the `kill_line` behavior happens after insert mode changes are already
   commited to history, and the kill change isn't committed. pressing `u` after
   this will break highlighting & undo history

**Comment by WindSoilder** [comment]
Emm... It seems that I still have to introduce an attribute in `document` and inject the implementation into `esc_mode`?

**Comment by archseer** [comment]
My recommendation was to move the `last_insert` into `Editor` from `ui:::Editor`. Then you can use that inside `normal_mode` instead.

**Comment by WindSoilder** [comment]
I think this can be closed again..
