### ISSUE TITLE
Emoji rendering issue

### ISSUE THREAD

**Issue by niklasravnsborg** [helix-editor/helix#10546]
By accident, I found that using the keyboard emoji (⌨️) is causing some rendering glitches (see video) in Helix 24.3 on macOS. The letters shift backward unexpectedly, when the line is navigated to by cursor navigation

https://github.com/helix-editor/helix/assets/6717303/f4d5ae20-091d-4b60-8e2e-4b40ac0af6e6

```
// i'm just moving along the line with `L`

👍 test 1
⌨️ test 2
```

**Comment by pascalkuthe** [comment]
Duplicate of #6012. The problem is less that helix is buggy and more that terminals can't agree on a shared definition of width for unicode graphemes.

As a workaround I plan to only render the first codepoint of multi codepoint graphemes
