### ISSUE TITLE
Using LSP to rename could store history

### ISSUE THREAD

**Issue by shaleh** [helix-editor/helix#10560]
When using <space>-r to LSP rename things the previous names used are not remembered. Adding a register here would be more ergonomic. I was just fixing some unit tests in another project and had to rename the same name in multiple function in multiple files. Since there was no shared scope the LSP was not too helpful. Being able to pull up recent renames would make this refactoring work easier. Either the existing ':' used for other history or perhaps another register dedicated to this? I am using semicolon in code locally. Happy to post a tiny PR if we can agree on the register to use.

**Comment by pascalkuthe** [comment]
I discussed this with @the-mikedavis. We don't really want to add an new hardcoded register for every prompt. But it would be useful to add the ability to specify a register with `"` yourself (you can already do that for other prompts that do have a history so it would just be a matter of respecting register even if no default history is specified). That would allow you to hardcode a register in your config and would also allow more ergonomic pasing with `""<space>r`
