### ISSUE TITLE
Consider if default theme should have different cursor colors for insert and normal mode

### ISSUE THREAD

**Issue by matklad** [helix-editor/helix#10568]
In default configuration helix, like vim, only shows the current mode in the modeline. This is poor UX, especially for new users, as, by just looking at the screen where you edit text, it's impossible to say which mode is active. 

A nice solution here is to use different cursor color for different modes. This is available in the, e.g., `ayu_evolve` theme.

I suggest that the default theme also gets this cursor color distinction, as that would be, imo, a big win for usability for new users (or for old users who don't want to bother with config files).

**Comment by pascalkuthe** [comment]
The primary cursor has defines different mode based cursor colors forever. But a while ago we mergef a PR that changed the way the highlight inheritance works (to allow theming the primary cursor different from the other cursors ans support mode dependent highlight at the same time).

This broke the default theme. To fix this we would need to simply copy `ui.cursor.selection` and `ui.cursor.insert` to `ui.cursor.primary.selection` and `ui.cursor.primary.insert`

**Comment by Diogenesoftoronto** [comment]
It seems no one has linked a pr. I am going to try doing this.
