### ISSUE TITLE
does helix not support  Intelephense's premium features?

### ISSUE THREAD

**Issue by dong8yong8** [helix-editor/helix#10623]
does helix not support  Intelephense's premium features?

when i edit php code by helix, i found can not rename symbols, can not go to  implementations

![图片](https://github.com/helix-editor/helix/assets/18693492/07b7d522-96f3-4cc6-bda4-5f32c6f7a2ca)

**Comment by dong8yong8** [comment]
i use helix's lsp default config

![图片](https://github.com/helix-editor/helix/assets/18693492/2ae88c8e-cbf6-436f-8d1b-a8b07734a096)

**Comment by felipebueno** [comment]
I just bought a premium license but I'm still unable to use the premium features on Helix. Did you manage to make it work?

**Comment by felipebueno** [comment]
Hmm never mind... it seems to be working now (not sure why though)

It looks very useful so far
