### ISSUE TITLE
"Normal" mod key in insert mode

### ISSUE THREAD

**Issue by NNBnh** [helix-editor/helix#1064]
We often find ourself want to insert a few characters then quickly moving/editing around over and over... which we have to exhaustingly pressing <kbd>i</kbd>...<kbd>Esc</kbd>, <kbd>i</kbd>...<kbd>Esc</kbd>, <kbd>i</kbd>...<kbd>Esc</kbd>, ...

Both Vim and Kakoune address this issue have a key to escape to normal mode for a single command in insert mode:

From [Kakoune keys doc](https://github.com/mawww/kakoune/blob/master/doc/pages/keys.asciidoc#insert-mode):
> **\<a-;\>, \<a-semicolon\>:** escape to normal mode for a single command.

This approach doesn't improve anything because it's still required 2 keys press (\[ <kbd>Alt</kbd> + <kbd>;</kbd>, *cmd* \] vs \[ <kbd>Esc</kbd>, *cmd*, <kbd>i</kbd> \]) only escape to normal mode for **a single command**. This is helpless when i just want to move to the right 2-3 characters.

Therefore i suggesting a solution that i have been using at my [Vim](https://github.com/NNBnh/bkey-vim), [Kakoune](https://github.com/NNBnh/bmap.kak), Emacs (lost config) nearly-every-keys-remap and really like it:
The simple solution it's having <kbd>Alt</kbd> as a "Normal" mod key in insert mode, user can holding it to access normal mode's commands (\[ <kbd>Alt</kbd> + *cmd* \]).

The "Normal" mod key can be config to any mod keys: <kbd>Alt</kbd>, <kbd>Ctrl</kbd>, <kbd>Shift</kbd> (?!), <kbd>Super</kbd>, <kbd>Meta</kbd>, ... ([List of mod keys](https://unix.stackexchange.com/questions/119212/mod-meta-super-keys#119219)) This is for the GUI Helix #39 's user who want to config every keys...

Yes, i know as mentioned in [keymap brainstorm wiki](https://github.com/helix-editor/helix/wiki/Keymap-brainstorm):

> we prefer not to hold keys (shift, ctrl, alt)

But in this case:

### Example

Cursor at beginning of file, fixing from this:

```
Th diting model is very heavily based on kakoune;
durin development I found myself agreeing with most of kakoune's design decisions.
```

to this:

```
The editing model is very heavily based on kakoune;
during development I found myself agreeing with most of kakoune's design decisions.
```

| Approach | Keys press | Count |
| - | - | - |
| Mode switch approach | <kbd>l</kbd><kbd>l</kbd><kbd>i</kbd>e<kbd>Esc</kbd><kbd>l</kbd><kbd>i</kbd>e<kbd>Esc</kbd><kbd>j</kbd><kbd>l</kbd><kbd>i</kbd>g | 13 |
| Vim and Kakoune approach | <kbd>l</kbd><kbd>l</kbd><kbd>i</kbd>e<kbd>A-;</kbd><kbd>l</kbd>e<kbd>A-;</kbd><kbd>j</kbd><kbd>A-;</kbd><kbd>l</kbd>g | 15 |
| Normal mod key approach | <kbd>l</kbd><kbd>l</kbd><kbd>i</kbd>e<kbd>A-l</kbd>e<kbd>A<kbd>j</kbd><kbd>l</kbd></kbd>g | 11 |

> <kbd>A<kbd>j</kbd><kbd>l</kbd></kbd> = <kbd>Alt down</kbd><kbd>j</kbd><kbd>l</kbd> *{Alt release}* = 3 keys press

This is just a small example, but if we're in a bigger scale situation, the keys press will add up.<br>
The normal mod key is the most elegant approach.

Not to mention:

### Accessibility

Many people just want to find a good terminal-based text editor but doesn't want to be forced using a module workflow of people want to get used to module workflow without feel so confused...
With this feature, user can mimic the non-module workflow by set insert as defaults mode (some how) then use the normal mod key for (as the noob usually call) shortcuts, Helix then slowly but surely introduced them to the amazing module workflow.

And also solved #334.

### Support prompt mode as well

The current prompt's keymap is nothing like normal mode:

| Normal | Prompt | Description |
| - | - | - |
| <kbd>Esc</kbd> | <kbd>Esc</kbd>, <kbd>C-c</kbd> | Close prompt |
| <kbd>b</kbd> | <kbd>A-b</kbd>, <kbd>A-Left</kbd> | Backward a word |
| <kbd>h</kbd> | <kbd>C-b</kbd>, <kbd>Left</kbd> | Backward a char |
| <kbd>e</kbd> | <kbd>A-f</kbd>, <kbd>A-Right</kbd> | Forward a word |
| <kbd>w</kbd> | <kbd>C-f</kbd>, <kbd>Right</kbd> | Forward a char |
| <kbd>g</kbd><kbd>l</kbd> | <kbd>C-e</kbd>, <kbd>End</kbd> | Move prompt end |
| <kbd>g</kbd><kbd>h</kbd> | <kbd>C-a</kbd>, <kbd>Home</kbd> | Move prompt start |
| <kbd>d</kbd> | <kbd>delete</kbd>, <kbd>C-d</kbd> | Delete previous char |
| <kbd>i</kbd> | <kbd>C-p</kbd>, <kbd>Up</kbd> | Select previous history |
| <kbd>k</kbd> | <kbd>C-n</kbd>, <kbd>Down</kbd> | Select next history |

A "Normal" mod key in prompt mode would make the keymap consistent across all mode. Of course many keys that are too complex or lack of practicality will do nothing, any keys that prompt user will do nothing *or* just switch the current prompt to that prompt instead (<kbd>A-/</kbd> in command mode prompt is equivalent to <kbd>Esc</kbd><kbd>/</kbd> which switch to search prompt).

### Drawback

As many can point out: commands map with <kbd>Alt</kbd> won't be able to access via normal mod key. We can improve this by remap all defaults Alt-based commands to other keys which i have attempt [here](https://github.com/helix-editor/helix/issues/1179).

**Comment by Omnikar** [comment]
I don't know about others but I personally like alt keymaps, and don't really find it as much of a hassle to repeatedly switch between normal and insert mode; but this is such a big change that I don't think the classic "make it configurable" would be much of an option, would it?

**Comment by NNBnh** [comment]
After some consideration, I decided to scrap this idea because user could already achieved this by manually remapping even though it took a lot for work. On the bright side, because Helix using `toml` file to config, user could write a script to generate a `toml` file with all keybind remap to <kbd>alt-...</kbd> combo in Insert mode.

**Comment by yashpalgoyal1304** [comment]
- link of update from you: https://github.com/helix-editor/helix/discussions/1211

**Comment by yashpalgoyal1304** [comment]
- yes, this problem is universal lol: https://github.com/helix-editor/helix/issues/3162
