### ISSUE TITLE
Prefix new block comment lines with block comment character

### ISSUE THREAD

**Issue by victorz** [helix-editor/helix#10663]
When I start a new JSDoc comment, e.g., I'm used to having to type only the following in most code editors: `/**<space><ret>`.

The resulting comment structure then becomes this, where `|` is the caret:

```js
/**
 * |
 */
```

I would love for this to be possible in Helix as well. And for it also to keep adding new `*`'s as I press enter, or reach the wrap limit (or at least when I run `:reflow`). (This was happening when I was typing the code for these comments in the GitHub issue text area, even.)

Would also love this for the regular `/*<space><ret>`, to result in:

```js
/* |
 */
```

or maybe

```js
/*
 * |
 */
```

Maybe even typing just `/**<space>` would result in `/** | */`? And similar for `/*<space>`?

It would make writing comments a *lot* smoother in my opinion. I'd be very content with `:reflow` learning this capability, at least.

Let me know what you think, please! And thank you for your time!

**Comment by TornaxO7** [comment]
I think this is connected to https://github.com/helix-editor/helix/issues/1730

**Comment by pascalkuthe** [comment]
Yeah even tough it may not be quite the same thing I think that falls under th e block comment part of that issue
