### ISSUE TITLE
Remove '' and add ⟨⟩ autopairs in Lean

### ISSUE THREAD

**Issue by ashl3y-v** [helix-editor/helix#10680]
Add an auto-pairs section to the lean configuration with ⟨⟩ and without ''
Rationale: ⟨⟩ is very commonly used for pattern matching and essentially always used in a pair, and ' is also very commonly used for denoting "prime" almost never used in a pair. If only using one ' the pairing isn't an issue, but when trying to type two, the pairing creates ''' instead, and the same issue is present when trying to type four, etc.
```
[[language]]
name = "lean"
...

[language.auto-pairs]
'(' = ')'
'{' = '}'
'[' = ']'
'"' = '"'
'`' = '`'
'⟨' = '⟩'
```

**Comment by ashl3y-v** [comment]
Also I should mention that I've tested this and there seem to be no problems with using a 3 byte character for pairs, also see #3964 and #3946.

**Comment by pascalkuthe** [comment]
a small config change like this doesn't need an issue, please open a PR if you want to see this changed

**Comment by ashl3y-v** [comment]
Okay sorry I'm not too familiar with contributing I'll do that
