### ISSUE TITLE
Rust Lsp rust-analyzer failed to work

### ISSUE THREAD

**Issue by rust-kotlin** [helix-editor/helix#10694]
I followed the instructions by the wiki to run `rustup target add rust-analyzer` to install rust-analyzer in my Windows 11 operating system.
But when I opened any rust code project, the lsp just doesn't seem to work and I couldn't get any code suggestions or inlay hints.

The error log looks like this:
❯ cat C:\Users\tom\AppData\Local\helix\helix.log
2024-05-06T17:17:17.482 helix_lsp::transport [ERROR] rust-analyzer err: <- StreamClosed
2024-05-06T19:49:02.149 helix_lsp::transport [ERROR] Tried sending response into a closed channel (id=Num(5)), original request likely timed out

Below are the versions of the softwares.

❯ rust-analyzer --version
rust-analyzer 1.78.0 (9b00956e 2024-04-29)

❯ hx --version
helix 24.3 (2cadec0b)

❯ hx --health rust
Configured language servers:
  ✓ rust-analyzer: C:\Users\tom\.cargo\bin\rust-analyzer.exe
Configured debug adapter: lldb-vscode
Binary for debug adapter: D:\sdk\llvm\bin\lldb-vscode.exe
Configured formatter: None
Highlight queries: ✓
Textobject queries: ✓
Indent queries: ✓

**Comment by rust-kotlin** [comment]
Sorry, actually it was because the first time of rust-analyzer analyzing my project took too much time that I failed to judge it rightly.
And the rectangle in the left below of helix showed me that the lsp is currently loading.

**Comment by TornaxO7** [comment]
I'd recommend to enable the [`display-messages`](https://docs.helix-editor.com/configuration.html#editorlsp-section) so you'll also get some information what the LSP is currently loading/doing.
