### ISSUE TITLE
auto_detect_indent_style detects the wrong indentation

### ISSUE THREAD

**Issue by NomisIV** [helix-editor/helix#10716]
I'm using PureScript for work, and we use 2 spaces for indentation in every PureScript module. However, in some modules - especially the test modules - helix wrongfully decides that 4 spaces would be a better fit given the current formatting.

Here is a minimal code example that illustrates the result:

![image](https://github.com/helix-editor/helix/assets/47303199/19701010-164a-4e4a-b6b8-a80146bbb923)

Note how the first `describe` is "in between" two indentation levels in the 4 space indentation.

This would not be as much of an issue if I could save the file without redetecting the indentation style (maybe this has something to do with auto-format?). More annoyingly is that 2-space indentation is declared as the default for PureScript in languages.toml. It would be very nice if it was possible to disable the auto-detection of indentation style on a language basis.

**Comment by NomisIV** [comment]
I have tried inverting the priority between `auto_detect_indent_style` and the `languages.toml`-file (so that languages.toml has the top priority), on my fork of helix here: https://github.com/NomisIV/helix. This solves my issue, but likely creates others. Any suggestions on a better fix? I'd be happy to help implement this

**Comment by the-mikedavis** [comment]
See https://github.com/helix-editor/helix/issues/9556, I will close in favor of that

The indentation heuristic should probably have minimum limits on it so we don't guess wrong for small files where there isn't enough information to figure out the actual indent scheme
