### ISSUE TITLE
Selected tick/quotation mark is marked as "ui.cursor.match" when editing Python files

### ISSUE THREAD

**Issue by BeneCollyridam** [helix-editor/helix#10723]
### Summary

When editing some Python code I noticed that the `"` under my cursor was hard to read. I dug into it and found out that it is displayed as "ui.cursor.match". This results in a color that is quite similar to my cursor's color in normal mode making it hard to see.

In the attached screenshots you can see how the `"` under the cursor has the same color as the matching bracket (`]`)  

![20240510_11h11m06s_grim](https://github.com/helix-editor/helix/assets/15802915/c297bb9c-c2ab-45ec-bf3a-4c6992f1adc9)
![20240510_11h11m01s_grim](https://github.com/helix-editor/helix/assets/15802915/fb8844bd-9b15-4d5f-9abd-da56ea1ce1d2)

### Platform

Linux

### Terminal Emulator

alacritty 0.13.2

### Installation Method

Nixpkgs unstable

### Helix Version

helix 24.3 (2cadec0b)

**Comment by pascalkuthe** [comment]
This has been fixed on master recently
