### ISSUE TITLE
`goto_file` on selection does not work on relative paths only absolute paths

### ISSUE THREAD

**Issue by scubacabra** [helix-editor/helix#10727]
### Summary

in an alacritty config i am importing files

```
import = [
  "~/.config/alacritty/catppuccin-frappe.toml"
]
```

it appears `goto_file` does not work with relative paths, only absolute ones

### Reproduction Steps

I tried selecting the *relative* file inside the quotes `~/.config/alacritty/catppuccin-frappe.toml`and pressing `gf` - the binding for `goto_file`

I expected to see the file opened in a helix buffer

Instead, it was just a blank buffer.  something went wrong silently, nothing was in the log file i created with `hx --log`

i changed the relative file to an absolute file `/Users/jacobono/.config/alacritty/catppuccin-frappe.toml`

i selected inside the quotes and used the same binding and that file opened in a buffer

### Platform

macos

### Terminal Emulator

alacritty

### Installation Method

source

### Helix Version

23.10

**Comment by kirawi** [comment]
You're using an old version of Heilx. This should be fixed on 24.03 per https://github.com/helix-editor/helix/pull/9065
