### ISSUE TITLE
Don't try to open non-regular files

### ISSUE THREAD

**Issue by mo8it** [helix-editor/helix#10726]
### Summary

Helix should only open regular files. Non regular files like devices and pipes should be rejected.

This can be fixed by checking [`FileType::is_file`](https://doc.rust-lang.org/stable/std/fs/struct.FileType.html#method.is_file).

I can open a PR to fix it :)

### Reproduction Steps

The following command will freeze and continuously eat RAM.

```bash
hx /dev/random
```

The following command just freezes:

```bash
mkfifo pipe
hx pipe
```

### Platform

Relevant on Unix but probably also on Windows

### Helix Version

helix 24.3 (f656b4f3)

**Comment by pascalkuthe** [comment]
That seems mostly correct and match vim but symlinks should still work

**Comment by mo8it** [comment]
`fs::metadata` traverses symlinks so `is_file` would return true.

The weird thing is that not every method returning `Metadata` traverses symlinks. One needs to read its docs. For example, `DirEntry::metadata` does NOT traverse symlinks.

**Comment by dead10ck** [comment]
My first thought was "why?" but yeah, the more I think about it, apart from symlinks that point to regular files or directories, I can't think of a use case where any other file type makes sense. Editing a pipe, character device, block device, etc just doesn't make any sense. We need to be able to read the whole file and write back to it, and no other file type fits this pattern.

**Comment by krish-r** [comment]
I believe this can be closed now since #10733 is merged.

(Off-topic: Congratulations on Rustlings rewrite :))
