### ISSUE TITLE
Writes are interrupted when suspending

### ISSUE THREAD

**Issue by PotatoesFall** [helix-editor/helix#10765]
### Summary

First of all thank you to everybody who has been working on this fantastic editor :heart: 

When I save a file in the editor (usually using Space-W), and then immediately suspend (using C-z), the file is sometimes not written. Only when I then use `fg` to resume helix, is the file saved.

Since suspending is a big part of my workflow, this has messed me up countless times because my recent changes weren't working (because they weren't saved)

It would be awesome if any save actions are still executed even if helix is suspended. Is that possible?

### Reproduction Steps

I tried this:

1. `hx {file}`
1. make changed
1. `:w`
1. `C-z`
1. check if file was saved

I expected this to happen:

File was saved with new changes

Instead, this happened:

File was not saved

### Helix log

<details><summary>~/.cache/helix/helix.log</summary>

```
2024-05-15T17:38:32.021 helix_core::syntax [ERROR] TS parser failed, disabling TS for the current buffer: Err(Cancelled)
```

</details>

### Platform

Fedora Linux 39

### Terminal Emulator

alacritty 0.13.2

### Installation Method

source

### Helix Version

helix 24.3 (2cadec0b)

**Comment by PotatoesFall** [comment]
I think that would be a huge improvement!

One thing to add, I'm pretty sure this is only happening for my `.go` files. On save there is autoformatting (gofmt/goimports) happening, causing a small delay. I was not able to replicate this with a simple text file. I assume that the time taken for autoformatting is long enough for this to happen reliably, while for normal saves it's not a problem.

I think a lot of people are using autoformat on save, and go has a fairly fast toolchain for that. I imagine I'm not the only one with this problem, although I haven't been able to find any other reports of this issue.

**Comment by lpoirothattermann** [comment]
@PotatoesFall can you try my commit, let me know if it's working as expected.
