### ISSUE TITLE
Support .swiftinterface files

### ISSUE THREAD

**Issue by levitatingpineapple** [helix-editor/helix#10763]
# Enhancement

Consider adding `swiftinterface` to recognised `file-types` for swift language.

# Context

`.swiftinterface` files as the name suggests describe an interface of a module. The syntax matches that of the swift, without function bodies. It's fairly common to look through these files since they contain inline documentation.

# Support 

🟢 **Tree-sitter**
- The highlights appear to be working (recovering) well even for +50k lines large files 

🟡 **LSP**
 - Goto definition [was added to sourcekit-lsp](https://github.com/apple/sourcekit-lsp/pull/750) last year 🎉
 - Show docs also works
 - Errors `expected '{'` are still emitted

# Preview

https://github.com/helix-editor/helix/assets/28978251/9bc00937-57b6-4d4f-a6b6-d464d1953343

**Comment by the-mikedavis** [comment]
Feel free to open a PR. The diagnostics issue is a problem on the language server side unless there's some config we can add for the language server to not emit those.

**Comment by levitatingpineapple** [comment]
Merged
