### ISSUE TITLE
The diagnosis and code are intermingled

### ISSUE THREAD

**Issue by liuhq** [helix-editor/helix#10770]
The diagnosis and code are intermingled, resulting in a chaotic layout. As shown below:

![image](https://github.com/helix-editor/helix/assets/48037182/220e4a01-34ec-4545-8c38-718da2556758)

---

Perhaps we could wrap it in a box, or move it closer to the status line?

**Comment by TornaxO7** [comment]
You can wait for https://github.com/helix-editor/helix/pull/6417 but as for the current state there isn't really a fix for this except temporary stopping LSP :(

**Comment by pascalkuthe** [comment]
duplicate of https://github.com/helix-editor/helix/issues/1953
