### ISSUE TITLE
Select object not work when cursor at the close pair

### ISSUE THREAD

**Issue by QiBaobin** [helix-editor/helix#1077]
When the cursor is at the close pair of around object we want to select, it doesn't work. Nothing happens.  

For example, when the cursor is at `]`,  neither`mi[` or `ma[` works.

```rust
pub const PAIRS: &[(char, char)] = &[
    ('(', ')'),
    ('[', ']'),
    ('{', '}'),
    ('<', '>'),
    ('«', '»'),
    ('「', '」'),
    ('（', '）'),
];
_
```

**Comment by archseer** [comment]
\cc @sudormrfbin
