### ISSUE TITLE
Selecting a line in completion pop-up doesn't import elements anymore

### ISSUE THREAD

**Issue by mlemesle** [helix-editor/helix#10781]
### Summary

Hello !

I just realized that when I select an item in the completion pop-up, the element isn't imported after insertion.
I'm almost sure it worked that way and it doesn't now since a few days ago. I know have to write the imports myself or rely on LSP code actions each time, which can be tedious.

I didn't change my configuration file and I do build Helix from master.

Here is an Asciicinema recording with a dead simple example.
[![asciicast](https://asciinema.org/a/womJhnoTlWVfIVqHhuxCMqZYg.svg)](https://asciinema.org/a/womJhnoTlWVfIVqHhuxCMqZYg)

### Reproduction Steps

1. Open a file
2. Write some code that needs import
3. Select the desired line with (use xxx) at the end and press Enter

The element isn't imported

### Helix log

No related logs

### Platform

Linux

### Terminal Emulator

kitty 0.34.1 created by Kovid Goyal

### Installation Method

Built from source

### Helix Version

helix 24.3 (00e9e5ea)

**Comment by kirawi** [comment]
I think this can be closed in favor of https://github.com/helix-editor/helix/issues/10787 which gives a range of commits causing the potential regression
