### ISSUE TITLE
LSP fail to auto-complete the import

### ISSUE THREAD

**Issue by Luv-Ray** [helix-editor/helix#10787]
### Summary

I update my helix from  2209effb to d8701bfd, then this bug happens.

When using TAB to select an item to auto-complete, it may also auto-complete the import (like `use std::sync::Arc`)
![image](https://github.com/helix-editor/helix/assets/111646748/c2c27618-7824-42ac-829d-f746556620e1)
But when I press enter, nothing happens and it didn't auto-complete the import.
![image](https://github.com/helix-editor/helix/assets/111646748/65fca284-f8a4-4dc6-86c4-745c701bc7d5)

Also, when I trying to import the module (like `std::sync`), it works fine. 
![image](https://github.com/helix-editor/helix/assets/111646748/40a08bdc-52a0-4260-8f40-6fea2d6750d5)

I know this looks very much like an LSP error, but it works fine at 2209effb without any LSP change. So I guess it's a helix bug.

### Reproduction Steps

 

I tried this:

1. `hx`
2. input following and press enter behind `Arc`:
```rust
fn main() {
    Arc
}
```

I expected this to happen:
import `use std::sync::Arc` at beginning

Instead, this happened:
nothing happens

### Helix log

<details><summary>~/.cache/helix/helix.log</summary>

```
empty
```

</details>

### Platform

Arch Linux

### Terminal Emulator

warp-terminal v0.2024.05.14.08.01.stable_04

### Installation Method

source

### Helix Version

helix 24.3 (d8701bfd)

**Comment by RoloEdits** [comment]
Seems it started here https://github.com/helix-editor/helix/pull/10539

**Comment by RoloEdits** [comment]
As a quick scout I found that commenting out this early return check brought back the auto-import:

https://github.com/helix-editor/helix/blob/2301430e37a98192de7864faa2d8c1b84860f400/helix-term/src/handlers/completion/resolve.rs#L45-L51

**Comment by Luv-Ray** [comment]
I find that when importing `std::sync` the `item.detail.is_none()` is true, and when importing `std::sync::Arc` it's false and then the function early returned. This explain why importing modules works fine.

Maybe we should remove `needs_resolve` and set `item.resolved` to `true` only after the `ResolveRequest` has been sent.

**Comment by pascalkuthe** [comment]
The imports come from `additionTextEdits` and we checker wehter that I'd none too to determine wether we need to resolve. VSCode has similar logic. It's wasteful to resolve requests that don't need to be resolved.
