### ISSUE TITLE
auto-completing nix examples

### ISSUE THREAD

**Issue by KiaraGrouwstra** [helix-editor/helix#10841]
using Nix LSP `nixd`'s https://github.com/nix-community/nixd/pull/415, [in vscode](https://marketplace.visualstudio.com/items?itemName=jnoortheen.nix-ide) i can auto-complete example values.

in helix however, such suggestions show up as part of an auto-complete suggestion:

![image](https://github.com/helix-editor/helix/assets/3059397/9b44ee6f-8a4f-4104-941c-628cf260bcf4)

... but then when pressing Enter to accept the suggestion, instead such example suggestions appear not included in the accepted auto-completion:

![image](https://github.com/helix-editor/helix/assets/3059397/69d8a1d2-94d4-465a-83a2-ab44dbd32133)

i'm not super familiar with LSP, but i felt like auto-completing such example suggestions might add value as well.

is this perhaps something about that vscode extension not following LSP best practice, or might this be an addition viable for helix as well?

version: `helix 24.3 (2cadec0b)`

**Comment by gabydd** [comment]
this is part of https://github.com/helix-editor/helix/issues/395 and will be fixed by #9801
