### ISSUE TITLE
Version is not always updated when re-building from source

### ISSUE THREAD

**Issue by rcorre** [helix-editor/helix#10855]
### Summary

I'm building helix from source, and noticed that the version reported by `--version` does not quite match the commit I'm building from. 
```
[rrc@rrc-dev helix]$ git rev-parse HEAD
179673568df2a519fae2537fbc0053a64ecf3d8b
[rrc@rrc-dev helix]$ cargo install --path helix-term --locked
  Installing helix-term v24.3.0 (/home/rrc/src/helix/helix-term)
    Updating crates.io index
warning: package `libc v0.2.154` in Cargo.lock is yanked in registry `crates-io`, consider running without --locked
    Finished release [optimized] target(s) in 0.49s
   Replacing /home/rrc/.cargo/bin/hx
    Replaced package `helix-term v24.3.0 (/home/rrc/src/helix/helix-term)` with `helix-term v24.3.0 (/home/rrc/src/helix/helix-term)` (executable `hx`)
[rrc@rrc-dev helix]$ which hx
/home/rrc/.cargo/bin/hx
[rrc@rrc-dev helix]$ hx --version
helix 24.3 (f656b4f3)
```

I do see some files for helix-loader referencing that hash:

```
[rrc@rrc-dev helix]$ rg f656b4f3 -uuu
target/release/hx: binary file matches (found "\0" byte around offset 7)

target/release/deps/helix_loader-a08374f82e769eec.d
14:# env-dep:VERSION_AND_GIT_HASH=24.3 (f656b4f3)
```

I believe what's happening is that `helix-loader` is what defines the version that `helix-term` imports, so if you pull changes that don't include `helix-loader` and rebuild, the version remains unchanged.

```
[rrc@rrc-dev helix]$ rg VERSION_AND_GIT_HASH
helix-loader/build.rs
36:    println!("cargo:rustc-env=VERSION_AND_GIT_HASH={}", version);

helix-loader/src/lib.rs
9:pub const VERSION_AND_GIT_HASH: &str = env!("VERSION_AND_GIT_HASH");

helix-term/src/main.rs
3:use helix_loader::VERSION_AND_GIT_HASH;
73:        VERSION_AND_GIT_HASH,
91:        println!("helix {}", VERSION_AND_GIT_HASH);

helix-lsp/src/client.rs
9:use helix_loader::VERSION_AND_GIT_HASH;
678:                version: Some(String::from(VERSION_AND_GIT_HASH)),
```

### Reproduction Steps

 

I tried this:

1. `hx`

I expected this to happen:

Instead, this happened:

### Helix log

<details><summary>~/.cache/helix/helix.log</summary>

```
please provide a copy of `~/.cache/helix/helix.log` here if possible, you may need to redact some of the lines
```

</details>

### Platform

Linux

### Terminal Emulator

N/A

### Installation Method

source

### Helix Version

179673568df2a519fae2537fbc0053a64ecf3d8b

**Comment by dead10ck** [comment]
I'm not sure this matters very much. This should only happen on local cached builds, and if we "fixed" this so the commit hash was always accurate, then it would cause a ton of unnecessary compile times, since helix-loader sits at the top of the crate dependency tree, so everything underneath it has to get rebuilt too

**Comment by rcorre** [comment]
That's fair. My thinking was that "local cached builds" would be common for those who regularly stay up to date with `main`, and would also represent helix's most active user base in terms of trying new features and reporting bugs, which could lead to confusing bug reports.

It's also a bit confusing as a user, I spent a while installing and uninstalling helix, thinking `cargo install` wasn't actually updating my binary.

**Comment by pascalkuthe** [comment]
we already instruct cargo to rebuild if the HEAD commit changes but I think there is a bug in the logic
