### ISSUE TITLE
Newlines are soft-wrapped to the next line when it is exactly one col past the character limit

### ISSUE THREAD

**Issue by sharpenedblade** [helix-editor/helix#10886]
### Summary

If a line is exactly at the character limit without the newline, then the newline character is wrapped to the next line. This only happens if the whole last "word" is not wrapped so the easiest way to reproduce it is to have a symbol at the character limit (col 80 for me).

### Reproduction Steps

I tried this:

1. `hx`
2. Use `:set-option` to set `soft-wrap.enable true`, `soft-wrap.wrap-at-text-width true`, and `text-width 80`
3. Paste this into the first line and make sure there is a newline after it:
    ```
    Any sentence that ends with a symbol with no spaces preceding it. Something like!
    ```

I expected this to happen:
There should be no newline created by soft-wrapping after the final symbol (the ruler is at col 80)
![image](https://github.com/helix-editor/helix/assets/83884198/cffecd33-2202-4ba0-8b1d-a88b7fcbe478)

Instead, this happened:
There is a new soft-wrapped line that only has a newline in it
![image](https://github.com/helix-editor/helix/assets/83884198/f1599670-5801-4e8b-9d35-bfe610f2620b)

### Helix log

My helix log is empty if I delete it then reproduce this issue

### Platform

macOS

### Terminal Emulator

kitty v0.35.0

### Installation Method

brew

### Helix Version

helix 24.3 (2cadec0b)

**Comment by kirawi** [comment]
This is intentional behavior https://github.com/helix-editor/helix/issues/8973
