### ISSUE TITLE
Working directory is ignored in the fuzzy finder

### ISSUE THREAD

**Issue by thebino** [helix-editor/helix#10890]
### Summary

When I open helix with the working directory option or within a subdirectory, the fuzzy finder will always show all files in the outer git repository instead.

This makes it very hard to work with a large code base

### Reproduction Steps

Create a project structure like that
```shell
├── .git
├── inner1
│   └── test.txt
├── inner2
│   └── test.txt
├── outer1
│   └── test.txt
└── outer2
    └── test.txt
```

I tried this:

1. `hx -w inner1`
2. Open file picker (space + f)

I expected this to happen:

see only files in the `inner1` subdirectory.

Instead, this happened:

see ALL files and directories from the git repo (outer1, outer2, .git)

### Helix log

<details><summary>~/.cache/helix/helix.log</summary>

```
please provide a copy of `~/.cache/helix/helix.log` here if possible, you may need to redact some of the lines
```

</details>

### Platform

macOS

### Terminal Emulator

Alacritty 0.13.2

### Installation Method

brew

### Helix Version

helix 24.3 (2cadec0b)

**Comment by krish-r** [comment]
That's expected.

You can use [`<Space> + F`](https://docs.helix-editor.com/keymap.html?highlight=file_picker_#space-mode) instead for opening file picker at current working directory.
