### ISSUE TITLE
catppuccin themes need to be synced again

### ISSUE THREAD

**Issue by rahji** [helix-editor/helix#10903]
### Summary

I noticed that the syntax highlighting in helix (with a catppuccin theme) was quite different than the same theme in `bat`. One of the catppuccin folks suggested I add the updated theme files to my helix config. It looks a lot better  after updating from github.com/catppuccin/helix. The themes colors were last synced 10 months ago and apparently they have changed since then. This should be a really easy first contribution for someone.

### Reproduction Steps

 

I tried this:

1. `hx` with an html file

I expected this to happen:

Expected catppuccin to look the same as it does on other catppuccin themed software.

Instead, this happened:

The colors were a bit off.

### Helix log

<details><summary>~/.cache/helix/helix.log</summary>

```
please provide a copy of `~/.cache/helix/helix.log` here if possible, you may need to redact some of the lines
```

</details>

### Platform

Windows (WSL)

### Terminal Emulator

Microsoft Terminal

### Installation Method

releases page

### Helix Version

helix 24.4 (2cadec0b)

**Comment by M00NJ** [comment]
It seems they're out of sync again. Bat left, Helix right:
![Image](https://github.com/user-attachments/assets/641c44a5-4fed-46b0-a7cc-6f37ffbf7522)

**Comment by Pierre-Thibault** [comment]
Well, I don't have the same colours from VS Code (left) to Helix (right) for Catppuccin moka.

![Image](https://github.com/user-attachments/assets/cf2ec372-89ed-4d77-9172-4296cd6dacd4)
