### ISSUE TITLE
`gf` can't open directories that start with `~`

### ISSUE THREAD

**Issue by MyApaulogies** [helix-editor/helix#10948]
### Summary

I'm able to `gf` `/home/user/.config/helix` and get a file picker prompt, as well as `~/.config/helix/config.toml`, but when I try it on `~/.config/helix/`, I get an error: `Open file failed: Is a directory (os error 21)`. This bug seems to apply to all directories starting with a ~.

### Reproduction Steps

 

I tried this:

1. `hx`
2. `i`
3. `~/.config/helix`
4. `gf`

I expected the directory to open in a file picker.

Instead, I get the error `Open file failed: Is a directory (os error 21)`.

### Platform

Linux

### Terminal Emulator

Alacritty

### Installation Method

`dnf`

### Helix Version

helix 24.3 (2cadec0b)

**Comment by krish-r** [comment]
I believe this was fixed in #9065

**Comment by MyApaulogies** [comment]
My bad, you're right!

**Comment by MyApaulogies** [comment]
My bad, you're right!

**Comment by the-mikedavis** [comment]
It looks like this works when `gf` is used with a single-width selection but if you select `~/.config/helix` and then use `gf` there is the directory error
