### ISSUE TITLE
Updating `unicode-width` from `0.1.12` to `0.1.13` broke newline rendering

### ISSUE THREAD

**Issue by RoloEdits** [helix-editor/helix#10950]
### Summary

When rebasing onto master I noticed some render issues. I made an identical branch but deleted this #10926 single commit and everything worked fine again.

WIth commit:
![helix-master-broken](https://github.com/helix-editor/helix/assets/12489689/82fd9d7a-bfe1-4abd-bc5a-0498fb0d585c)

Without:
![helix-master-fixed](https://github.com/helix-editor/helix/assets/12489689/09e8cca0-f3ec-4515-ad28-c4176db3ad46)

In looking more into it to see if I cant find what it could be, I was lead by https://github.com/helix-editor/helix/pull/10926/commits/53da38a145f036efc65bf0f8c2a03a8989838e2e to start with `unicode-width`.

There I found an [issue](https://github.com/unicode-rs/unicode-width/issues/55) about breaking semver by one of the maintainers of ratatui, where they also seem to have had rendering [issues](https://github.com/ratatui-org/ratatui/pull/1165). 

There is currently an open issue on how `unicode-width`  should handle line breaks given the recent changes: https://github.com/unicode-rs/unicode-width/issues/60

Connected: https://github.com/helix-editor/helix/issues/6012

### Platform

Windows

### Terminal Emulator

Alacritty

### Installation Method

Source

### Helix Version

Based off of `9c479e6`

**Comment by the-mikedavis** [comment]
I can't reproduce that rendering. What is your language config for Rust?

**Comment by the-mikedavis** [comment]
Ah ok, I can see it while reproducing https://github.com/helix-editor/helix/issues/10948:

* open a scratch buffer
* type `~/.config/helix`
* select that (`x_`)
* `gf`

The error shifts the statusline up.

As you say looks like the issue is that line endings are now width = 1 so we need to check for those graphemes when we render in `Buffer::set_string`
