### ISSUE TITLE
`mr"“`/`mr"”` replaces double quotes with two pairs of the same kind of double quote

### ISSUE THREAD

**Issue by adiabatic** [helix-editor/helix#10966]
### Summary

I added the following to my helix config:

```toml
[editor.auto-pairs]
'(' = ')'
'{' = '}'
'[' = ']'
'"' = '"'
"'" = "'"
'“' = '”'
# ’ is usually an apostrophe
'«' = '»'
'`' = '`'
```

and tried to replace straight double quotes with curly double quotes. However, instead of getting leading and trailing double quotes, I got two of the same kind of whatever I typed in.

I tried this with `mr"«` and `mr"»` and it didn't screw up like this. It worked right for the guillemets.

### Reproduction Steps

 

I tried this:

1. run `hx`.
2. insert `"Do they allow sheep on the airplane?"` into the buffer however you like.
3. Get into normal mode by pressing escape.
4. type `mr"“` (`⎄"<` works, where ⎄ is your Compose key, or type `⌥[` in macOS)

I expected this to happen:

Both the leading and trailing double quotes should be curled differently from each other.

Instead, this happened:

Both the leading and trailing double quotes are curled the same way (in this case, leading).

### Helix log

<details><summary>~/.cache/helix/helix.log</summary>

```
2024-03-22T23:26:40.960 helix_view::editor [ERROR] Failed to initialize the language servers for `source.md` - `marksman` { cannot find binary path }
2024-04-19T00:20:24.456 helix_core::syntax [ERROR] Failed to load tree-sitter parser for language "gemini": Error opening dynamic library "/home/linuxbrew/.linuxbrew/Cellar/helix/24.03/bin/runtime/grammars/gemini.so"
2024-06-14T23:22:03.428 helix_core::syntax [ERROR] Failed to load tree-sitter parser for language "gemini": Error opening dynamic library "/home/linuxbrew/.linuxbrew/Cellar/helix/24.03/bin/runtime/grammars/gemini.so"

```

</details>

### Platform

macOS and Linux (Debian Stable)

### Terminal Emulator

Terminal.app, iTerm2.app, gnome-terminal

### Installation Method

Homebrew (on both macOS _and_ Debian)

### Helix Version

24.3 (Homebrew says `24.03` in both cases, though)

**Comment by the-mikedavis** [comment]
The bracket pairs for matching are controlled by https://github.com/helix-editor/helix/blob/dbacaaddcaa4a9dd39c73d0102d03ea7c24ca647/helix-core/src/match_brackets.rs#L12-L20 rather than auto-pairs config. It should be enough to add the angled brackets to that list to fix this.
