### ISSUE TITLE
Add all commands (including those without keymaps) to documentation

### ISSUE THREAD

**Issue by thomasschafer** [helix-editor/helix#10970]
There are a number of commands ([here](https://github.com/helix-editor/helix/blob/dbacaaddcaa4a9dd39c73d0102d03ea7c24ca647/helix-term/src/commands.rs#L250-L534)) such as `select_line_above` that can be used in custom keymaps but are (as far as I can tell) not formally documented, so the only way to determine which commands can be used is to read the source code or possibly from perusing the changelog. It would be nice to have these commands documented somewhere, e.g. at the end of https://docs.helix-editor.com/keymap.html under a new section that contains all of those commands that are not bound by default to a keymap but that can be used in `config.toml`.

**Comment by kirawi** [comment]
You can see all commands that exist in `space-?`

**Comment by thomasschafer** [comment]
> You can see all commands that exist in `space-?`

I was meaning to have them documented somewhere on the website - I think it's useful to be able to review these outside of the editor. For instance, inside Helix you can see all of the command mode commands by hitting `:` and tabbing through them, but they are also documented at https://docs.helix-editor.com/commands.html

**Comment by adamperkowski** [comment]
Added in #11152
