### ISSUE TITLE
Help with syntax highlighting

### ISSUE THREAD

**Issue by pfr-dev** [helix-editor/helix#1098]
I need some help getting syntax highlighting working. I'm not familiar with this `tree-sitter` business and really have no idea what I'm supposed to do. I think I need an idiots guide to setting syntax highlighting in Helix. 

Thanks!

**Comment by archseer** [comment]
Can you give us some details (you didn't fill out the bug template)? What helix version? What programming language? What file are you trying to load?

**Comment by pfr-dev** [comment]
> Can you give us some details (you didn't fill out the bug template)?

Mostly because it's not a bug, I just need some help

> What helix version? 

v0.5.0

> What programming language? What file are you trying to load? 

This confuses me coming from vim where you just enable syntax highlighting and that's it. I am not a programmer, I'm just a hobbiest who likes colorful code. I'm mostly editing dot-files and configs in C, some in rust and and a handful of common lisp. But I just want _The Kitchen Sink_ syntax highlighting package that does it all. 

> Are you using a package or installing from source? 

I installed form source as per the installation instructions. 

Extra info:
OS - NetBSD
Built on rustc-1.56.1

**Comment by archseer** [comment]
Yeah, Helix highlighting should also work out of the box, as long as you're using a language we support (currently any of the ones listed in https://github.com/helix-editor/helix/blob/master/languages.toml)

if you're not getting syntax highlighting for `C` or `Rust` files, did you follow the install steps:

> Helix also needs its runtime files so make sure to copy or symlink the `runtime/` directory into the config directory (for example `~/.config/helix/runtime` on Linux/macOS). This location can be overriden via the `HELIX_RUNTIME` environment variable.

**Comment by pfr-dev** [comment]
Yeah, I've copied the `runtime/` directory to `~/.config/helix/runtime` yet I still don't get any highlighting. Not even in `bash` or `sh` scripts.

**Comment by kirawi** [comment]
Run Helix via `hx -v` on a file that's supposed to have syntax highlighting; what does it say in your [log](https://github.com/helix-editor/helix/wiki/FAQ#access-the-log-file)?

**Comment by pfr-dev** [comment]
> Run Helix via `hx -v` on a file that's supposed to have syntax highlighting; what does it say in your [log](https://github.com/helix-editor/helix/wiki/FAQ#access-the-log-file)?

```
~/.cache/helix $ cat helix.log
2021-11-17T22:06:24.683 helix_core::syntax [INFO] Error opening dynamic library "/home/dave/.config/helix/runtime/grammars/toml.so"
2021-11-17T22:06:24.683 helix_view::editor [ERROR] Failed to initialize the LSP for `source.toml` { LSP not defined }
```

**Comment by pfr-dev** [comment]
I removed Helix and started from the beginning. It seems to have worked this time. 

Cheers

**Comment by pfr-dev** [comment]
While most syntax highlighting is working now (including `sh` scripts), for some unknown reason my `~/.shrc` does not have syntax highlighting. Is there any syntax highlighting for rc files?

**Comment by sudormrfbin** [comment]
Support for file detection from shebang line landed in master a while ago (#1001), so you'll have to either build from source or wait for v0.6.

**Comment by pfr-dev** [comment]
> Support for file detection from shebang line landed in master a while ago (#1001), so you'll have to either build from source or wait for v0.6.

I did build from source, 11 days ago. Looks like those changes landed before I built `helix`

To be clear, my `~/.shrc` does not begin with a shebang, the very first line is `# .shrc file for sh(1).`

**Comment by sudormrfbin** [comment]
Ah you need  at the very least a proper shebang line like `#!/bin/sh` for it to work, since helix has no other way of detecting file type.

**Comment by pfr-dev** [comment]
> Ah you need at the very least a proper shebang line like `#!/bin/sh` for it to work, since helix has no other way of detecting file type.

I've added the shebang and it does work. I'm just a little unsure whether or not it'll have any unwanted consequences. Anyway, Closing again. 
Cheers

**Comment by koonopek** [comment]
Okey found this in log file?
(Couldn paste screen shot)
![obraz](https://user-images.githubusercontent.com/24699136/183460145-fce933f8-56bf-463e-a6ee-fd9d6032776d.png)

**Comment by archseer** [comment]
Are you building on latest master? Grammars weren't cross-compiled correctly before this change https://github.com/helix-editor/helix/pull/3137/files#diff-a51c059189ef3148ad3623783b405a650987fba714abf1b6c9343d86862c8dc1R323

**Comment by Enforcer007** [comment]
TOML is in the list of supported of languages. Still I was unable to see any highlighting in my toml files.

I installed hx using Cargo and I can't see any app related files in my ~/.config/helix folder. Later I found the helix files are located in ~/tools/helix folder. Then I symlinked the ~/tools/helix folder to ~/.config/helix. Now it started working.

**Comment by Lyreplus** [comment]
Same problem here. I've installed Helix from source on Arch Linux as the readme file says. I've also executed the command `ln -s $PWD/runtime ~/.config/helix/runtime` on my terminal, but nothing. The rust analyzer works but highlighting, text object and indent features don't work, as the command hx --health print. I've also executed "`hx --grammar fetch`" and "`hx --grammar build`", and everything is already built. Any ideas?

**Comment by archseer** [comment]
Why not use the `helix-git` AUR package that builds from source and sets everything up for you?

**Comment by beeb** [comment]
@Lyreplus I have the same problem but I am not on Arch, I'm on Ubuntu from WSL2. Any hints for me? CC @archseer

**Comment by beeb** [comment]
For anyone reading this and having the same problem as @Lyreplus above. For me what worked was to export a variable `export HELIX_RUNTIME="$HOME/helix/runtime"` pointing to the runtime folder inside the git repo that you cloned. It's important to not have a runtime folder inside the `~/.config/helix` folder as well otherwise it didn't work for me.

**Comment by lBenevides** [comment]
@beeb Thanks!!! done that and just worked like magic!

**Comment by beeb** [comment]
> @beeb Thanks!!! done that and just worked like magic!

Nice! Alternatively I think I later also got it working in the end by making a symlink inside `.config/helix` that points to the runtime folder inside the cloned repo, like indicates in the user instructions.

**Comment by jokyv** [comment]
Sometimes my syntax highlighting disappears in an old installation.
I have not figured it out why, but i run a complex setup (at least for me lol)
What always worked for me, is to delete all the grammars saved in the `~/.config/helix` folder.
Then i run again "`hx --grammar fetch`" and "`hx --grammar build`".
That have worked well for me just sometimes I do not remember it when I troubleshoot.
Hence I am posting here for the future me (as this issues comes first when i googled "helix syntax highlight issue"
I hope it might help others too!
