### ISSUE TITLE
:q (quit) command unexpected behaviour (unsaved buffer) with auto-save by delay

### ISSUE THREAD

**Issue by justforcomment** [helix-editor/helix#10991]
### Summary

When you enable autosave by delay, the :q (quit) command does not work as expected, the editor does not allow you to exit, although the changes have already been made to the disk.

At the same time, changes in .toml (may other also) files or files without extension, it works correctly.

On video the expected behavior is shown first, then the problem described.

https://github.com/helix-editor/helix/assets/173177041/c9317884-5e6f-4ffb-abf2-576964cd1178

### Reproduction Steps

 

I tried this:

1. `hx`

I expected this to happen: write change with auto-save, then just quit

Instead, this happened: occurs warning of unsaved buffer

### Helix log

**It is unexpected behaviour only.**

<details><summary>~/.cache/helix/helix.log</summary>

[helix.log](https://github.com/user-attachments/files/15890688/helix.log)

</details>

### Platform

Linux/Devuan

### Terminal Emulator

Kitty

### Installation Method

source

### Helix Version

helix 24.3

**Comment by the-mikedavis** [comment]
This is ultimately the same as https://github.com/helix-editor/helix/issues/11024 but it's very easy to trigger with auto-save. For auto-save in particular an easy solution would be to prevent saving while in insert mode. We would need to trigger the auto-save handler on the mode change hook too though to make sure we save after waiting a while between the last edit and switching between insert and normal modes
