### ISSUE TITLE
Markdoc default LSP should be changed from deprecated to official version

### ISSUE THREAD

**Issue by jasikpark** [helix-editor/helix#11003]
https://www.npmjs.com/package/markdoc-ls has been deprecated and reccomends https://www.npmjs.com/package/@markdoc/language-server.

I believe the default markdoc LSP should be updated and docs should be changed accordingly.

Thx for making such a sweet editor!

**Comment by the-mikedavis** [comment]
Did the name of the binary change? If not then we shouldn't need any change to the language server configuration here: https://github.com/helix-editor/helix/blob/b05ed9bf8518be662490fa669bf8b51b0c683fe9/languages.toml#L53

Feel free to edit the wiki to point to the correct NPM package: https://github.com/helix-editor/helix/wiki/Language-Server-Configurations#markdoc - the wiki is editable without any special permissions

**Comment by jasikpark** [comment]
Updated:

https://github.com/helix-editor/helix/wiki/Language-Server-Configurations#markdoc
