### ISSUE TITLE
Race condition when typing before symbol picker opens

### ISSUE THREAD

**Issue by Awlexus** [helix-editor/helix#11051]
### Summary

I noticed an issue where I would open the symbol picker, start typing before the modal shows up and there were a few missing characters at the start, but it still found the function. Once I had selected the function, the position was properly updated, but when I tried to move with j/k I jumped back to the previous position. I noticed that because the function starts with "s" I entered search mode before the modal was opened. After the modal was closed, search mode was resumed.

### Reproduction Steps

I can reproduce this by doing the following:

1. `hx`
2. Open a file with support for symbol picker
3. Open the symbol picker and press "s" before it can open
4. Select a symbol
5. Try moving with one of the direction keys `h,j,k,l` (The bug can be prevented by pressing ESC here instead)
6. Press ESC

I expected this to happen:
No search started, and the input is sent to the symbol picker

Instead, this happened:
search mode was enabled, search even gets input before the modal opens, and the position is updated wrongly when after exiting search mode

### Platform

macOS

### Terminal Emulator

iTerm

### Installation Method

source

### Helix Version

24.03-228-gb4811f7d

**Comment by the-mikedavis** [comment]
This is the intended behavior - it's not a race condition, the symbol picker is just opened asynchronously and the editor remains responsive while we wait for the response from the language server. We could block on opening the symbol picker but that would make the editor freeze when using language servers that take a long time to respond.
