### ISSUE TITLE
CLI argument to open file with cursor positioned on given line number 

### ISSUE THREAD

**Issue by jdnavarro** [helix-editor/helix#1106]
In kitty there is [a feature](https://sw.kovidgoyal.net/kitty/kittens/hints/) to select and act on arbitrary text. I frequently use it with the `--type=linenum` option to open my editor with the cursor positioned on the reported error.

![kitty_error_jump](https://user-images.githubusercontent.com/215438/141850331-07892344-f3be-4e26-9657-4d95bc2d4bd0.png)

I could get it working with helix if I could pass the line number as an argument when launching it from the shell.
```sh
$ hx +5008 helix-term/src/commands.rs
```

Being able to specify the column number would be nice, but not that important.
```sh
$ hx +5008:15 helix-term/src/commands.rs
```

Vim and Emacs use the `+` sign for the line number argument prefix, but I don't have an opinion about how it should be named, anything will do with me :smirk: 

If this is something that aligns with the overall design of helix and you are willing to accept a PR for this feature, I could give it a try myself.

**Comment by Omnikar** [comment]
@pickfire was working on this at #445
