### ISSUE TITLE
ZIG Incorrect Highlights

### ISSUE THREAD

**Issue by jacknicklenson** [helix-editor/helix#11095]
in zig files some variables & functions are highlight wrongly. In `snazzy` theme (screenshots have my custom snazzy theme but TS highlights same, I didn't change), vars should be light blue, functions should be green. In screenshots, you can see `tree-sitter-highlight-name` output. It detects wrongly.

Helix version: `helix 24.3 (2cadec0b)`
Windows 11

![image](https://github.com/helix-editor/helix/assets/90291236/8055c397-f944-49ce-805a-25250fa6516c)

This is another case:
![image](https://github.com/helix-editor/helix/assets/90291236/de51be00-28df-4ef4-a915-317a58cfc5c9)

**Comment by David-Else** [comment]
Helix uses 3rd party tree-sitter implementations for language highlighting, if there is a problem it almost certainly needs to be fixed at https://github.com/maxxnino/tree-sitter-zig/ , the reference to which version is being used is https://github.com/helix-editor/helix/blob/master/languages.toml#L1348C19-L1348C62

Perhaps using the latest version would fix the bug, this would require submitting a PR, the last time it was updated seems to be Aug 23 https://github.com/helix-editor/helix/pull/7803

**Comment by jacknicklenson** [comment]
okay thx for the reply
