### ISSUE TITLE
Cannot read some highlighted search results without true color

### ISSUE THREAD

**Issue by TJTorola** [helix-editor/helix#11185]
Sometimes, in the search results code preview, the background of the highlight matches the foreground and makes it impossible to read. As compaired to highlighting code in the editor itself which always sets the foreground to a contrasted color, the preview doesn't appear to do that.

![Screenshot 2024-07-15 at 14 26 28](https://github.com/user-attachments/assets/d2ffb143-6db4-4ea2-a217-a9a4a17f41a5)

**Comment by the-mikedavis** [comment]
Which theme is this?

**Comment by TJTorola** [comment]
Actually sorry, I think I missed a point. I don't have true color support in this instance (I thought I had fixed that). This is whatever the default theme, but without true color. When I run it elsewhere that does have true color the problem goes away. Not sure how fixable it is in environments that have limited colors available.

**Comment by TJTorola** [comment]
Seems to be more of an issue with my terminal setup than helix. This probably isn't worth changing anything in helix.
