### ISSUE TITLE
Global search path filter becoming part of the search history

### ISSUE THREAD

**Issue by xJonathanLEI** [helix-editor/helix#11214]
### Summary

With the patch in #11209, now the search history is updated as expected following choosing an entry.

However, as a side effect together with #11212, now doing the search with a path filter means the ` %p xxx` part gets spilled into search history too. So the workflow of "searching for something globally then proceeding to do it locally via `n`" stops working.

Maybe we should extract the "raw query" part and only add that instead? WDYT?

### Reproduction Steps

N/A

### Helix log

N/A

### Platform

Any really

### Terminal Emulator

Any really

### Installation Method

Any really

### Helix Version

helix 24.7 (c9d829a)

**Comment by the-mikedavis** [comment]
Ah yeah, we need to insert the `Picker::primary_query` rather than the whole line

**Comment by makai410** [comment]
I was wondering if providing an opt-in option would be good. I really wanted this feature when I had a long path filter and really didn't want to type it out again.
