### ISSUE TITLE
No longer possible to filter global search results by file name

### ISSUE THREAD

**Issue by xJonathanLEI** [helix-editor/helix#11212]
### Summary

The old global search command used to ask you for the pattern in the prompt, with the picker itself used for filtering files by name. Again submitting as bug as this used to be possible. Please feel free to change the label if appropriate.

This was very useful. Consider a use case like changing a dependency version like for `serde`. You have numerous references to `serde` throughout the project, whereas most of them are irrelevant. It used to be the case that you can search and simply filter by `Cargo.toml` and work on those. This is now no longer doable. (For this specific case you can instead search for `serde =` but that relies on proper formatting so it's not ideal)

I don't have a good solution here until we have multiple inputs on pickers. Can we... (requesting once again)... just bring back the old global search on the side?

### Reproduction Steps

Do a global search and realize you cannot filter by file name anymore.

### Helix log

N/A

### Platform

Any really

### Terminal Emulator

Any really

### Installation Method

Any really

### Helix Version

helix 24.7 (c9d829a2)

**Comment by kirawi** [comment]
You need to do `%p PATH` in the prompt IIRC. You can enclose the queries in quotes if you want to do multiple filters.

**Comment by xJonathanLEI** [comment]
> You need to do `%p PATH` in the prompt IIRC. You can enclose the queries in quotes if you want to do multiple filters.

Oh but then the issue becomes that any trailing whitespaces are now ignored for this to work. There are legit use cases when you'd search with trailing spaces though?

**Comment by the-mikedavis** [comment]
You can use `[ ]` or `\s` and the end of the search query for that
