### ISSUE TITLE
Allow "on"/"off" and "y"/"n" as alternatives to "true"/"false" in settings

### ISSUE THREAD

**Issue by tgross35** [helix-editor/helix#11238]
I think it is more common to think of togglable settings as being "on" or "off" in state, rather than "true" or "false" in condition. It would be nice if the keywords to toggle state accepted a few more options.

For example, it would be nice to toggle auto format settings with "off" or "on", which seems more natural (to me at least, I always type it wrong):

```text
:set auto-format off
:set auto-format on
```

"y"/"n" would also be nice as a shorthand, possibly "yes" and "no" by extension.

(v 24.07)

**Comment by pascalkuthe** [comment]
https://github.com/helix-editor/helix/pull/11249#issuecomment-2254135525
