### ISSUE TITLE
Include current position in jumplist when using "Goto [previous|next] change"

### ISSUE THREAD

**Issue by HungryJoe** [helix-editor/helix#11278]
I use `[g` and `]g` quite a bit, and it would be nice if they saved my current position before jumping so that I could use `Ctrl-o` to get back to it. I'm not sure if this functionality is intended to exist already or not; if it is and y'all want more information from me, just let me know.

P.S. I love this editor, use it as my primary editor for work, and [support y'all on open-collective](https://opencollective.com/sam-kagan) 🙂. I appreciate how the maintainers have handled the "growing pains" over the past year or so as the project has become more popular.

**Comment by knottio** [comment]
What preferably does and doesn't go into the jumplist is probably fairly user-specific. It could be worth having a config setting to set which commands add to the jumplist. That should be a pretty straightforward change, consisting of the config setting, and replacing `push_jump` calls with `if cx.editor.config()... { push_jump(...) }`.

But if it doesn't get implemented (or until it does), anyone that wants this can do this themselves by inserting `push_jump(view, doc);` before `doc.set_selection(view.id, selection);` here:
https://github.com/helix-editor/helix/blob/22c1a4072596df6858baddcad63a281b2e82bd40/helix-term/src/commands.rs#L3709-L3710
It should be easy to keep in sync with upstream.

**Comment by evilwaveforms** [comment]
As an alternative, remapping the command with `save_selection` as the first
command does the job. Downside is that when you press "[" or "]" the popup menu
displays "[Multiple commands]".

in `config.toml`
```
[keys.normal."]"]
g = ["save_selection", "goto_next_change"]

[keys.normal."["]
g = ["save_selection", "goto_prev_change"]
```

**Comment by HungryJoe** [comment]
@evilwaveforms your solution works perfectly, thank you! Given that, I'd consider this issue closed.
