### ISSUE TITLE
does some thing like "set clipboard=unnamed" in vimrc

### ISSUE THREAD

**Issue by 1925381584** [helix-editor/helix#11284]
hi,everybody. does some thing like "set clipboard=unnamed" in vimrc, so that use the system clipboard as default when i copy,cut,and paste. From my experience, I think it's more intuitive to set it this way by default, what do you guys think?

**Comment by the-mikedavis** [comment]
You can remap the yanking and pasting keybindings to use the clipboard instead, see https://github.com/helix-editor/helix/issues/2038#issuecomment-1658847967
