### ISSUE TITLE
`lsp-stop` should stop the lsp without it restarting afterwards. + `lsp-start`

### ISSUE THREAD

**Issue by adriangalilea** [helix-editor/helix#11319]
It goes against user expectations that the lsp runs again after you explicitly asked it to stop with `lsp-stop`.

In low-spec machines the lsp is enabled by default in certain files, and the only solution I found was setting the lsp for each language empty like so:

```
# in order to let my rpi not die from shellcheck
[[language]]
name = "bash"
language-servers = []
```
I think the `lsp-stop` should do what you intutively think it does, stop and not restart by itself, why would you have an `lsp-stop` and `lsp-restart` that virtually do the same thing?

We should have:
`lsp-restart` restarts lsp
`lsp-stop` stops lsp for good(if running)
`lsp-start` starts the lsp(if stopped)

Any reason not to do it this way?

Links:
[As discussed previously...](https://github.com/helix-editor/helix/discussions/10226#discussioncomment-9032987)
[more users having this problem](https://www.reddit.com/r/HelixEditor/comments/116fdp7/how_to_disable_lsp_in_helix/)

**Comment by the-mikedavis** [comment]
`:lsp-stop` does not restart the language server:

https://github.com/helix-editor/helix/blob/f34dca797cf696a19466ab2b3f7e1ca6ffa2bcb7/helix-term/src/commands/typed.rs#L1509-L1536

https://github.com/helix-editor/helix/blob/f34dca797cf696a19466ab2b3f7e1ca6ffa2bcb7/helix-lsp/src/lib.rs#L765-L775

If you can find a case where it does that's definitely a bug.

**Comment by adriangalilea** [comment]
@the-mikedavis then why everyone has that issue?

I installed Helix on a Raspberry Pi Zero, decided to install shellcheck to test it, once I was editing any bash script my Pi would die, I could barely exit, and no matter how many times I did `:lsp-stop` the lsp kept going back on.

So maybe this is unrelated to Helix?

**Comment by the-mikedavis** [comment]
Ah I think I know what's going on. When you open another file we see that the language server isn't running and spawn a new one. That should be a fairly simple fix to the client: `:lsp-stop` would "tombstone" the language server, opening a document would not start a new client when it sees a tombstone but `:lsp-restart` would

**Comment by adriangalilea** [comment]
> Ah I think I know what's going on. When you open another file we see that the language server isn't running and spawn a new one. That should be a fairly simple fix to the client: `:lsp-stop` would "tombstone" the language server, opening a document would not start a new client when it sees a tombstone but `:lsp-restart` would

I was trying to record it, but I'm unable to make the shellcheck process spawn for whatever reason that was causing me all the issues, and the bash-language-server supposedly should use it underneath, but despite it starting, I see no signs of lsp life on my typos :)

Either way I think you are spot on on what you mentioned and that's the likely cause as I was going back and forth to different files(2-3 small ones) and then it would just not respond which would make me have to kill the session and get back in ad infinfitum.
