### ISSUE TITLE
Save cursor position on write / exit

### ISSUE THREAD

**Issue by cole-h** [helix-editor/helix#1133]
#### Describe your feature request

In the same vein as https://gitlab.com/Screwtapello/kakoune-state-save, it would be fantastic if I didn't lose my place in a file every time I have to close and re-open it.

I'm unsure if it should be a plugin (once that's available), or built-in -- it's implemented as a plugin for kakoune, but it's built-in to vim (with the `.` and `"` registers).

**Comment by kirawi** [comment]
Something like #401?

**Comment by cole-h** [comment]
Maybe similar, but I don't care about saving and restoring splits / etc -- only the cursor position.

I suppose this could be considered a step towards that issue, though, since I imagine you'd want to save the cursor position inside those individual splits.

**Comment by archseer** [comment]
Yeah I was intending this with #401 (it needs a better description), I don't care about saving split layouts but we should save file positions, persistent undo history and possibly command history. I have my vim configured in a way that it automatically jumps to last used offset.

The implementation gets a bit tricky when you have multiple open instances running to the same state. See also [neovim's](https://github.com/neovim/neovim/pull/2506) implementation.

**Comment by cole-h** [comment]
Ah, OK. That being the case, I'll gladly close this in favor of that one.

**Comment by kirawi** [comment]
@archseer Not sure I'm educated enough about persistent state to write a good description for it.
