### ISSUE TITLE
clang does not recognize qt-related header files

### ISSUE THREAD

**Issue by 1925381584** [helix-editor/helix#11359]
Hello, everyone. I have compile success a qt program in windows. but it could not find header file about qt. Whose problem is this and is there a solution for it?

system: win10
hx: 24.7

**Comment by pascalkuthe** [comment]
you need to setup a compilation database. Helix doesn't control the LSP and has no concept of a header file, libraries or compilation. This is most likely a config issue on your side (in theory it could be a bug with clangd but very unlikely, definitely not related to helix)
