### ISSUE TITLE
SVN workspace support

### ISSUE THREAD

**Issue by seanbone** [helix-editor/helix#11403]
I'm working on Fortran projects under SVN (I know, right?). The fortls server works a charm, however, with Helix I run in to the issue of workspace root detection. Helix doesn't seem to treat `.svn` folders as workspace-root markers and so by default it uses my home directory (which in turn causes fortls to time out because it's too much stuff).

After a lot of tinkering and looking at verbose logs, I was able to get it to work as desired in one of two ways:
1. Adding an empty `.helix` or `.git` directory to the workspace root. I seem to recall reading about this in the documentation a while ago, but I can't seem to find it any more. Is there a docs page that states exactly how the workspace root is determined by Helix? It would be helpful for this sort of debugging.
2. Using the `roots` option in the Fortran language in `languages.toml`: `roots = [".fortls.json", ".svn"]`. Works, but is limited to the Fortran language.

Neither of these solutions is ideal. It requires extra configuration steps either per language or per repository. As far as I can tell, this is not configurable in a generic way at the moment. Personally, the real strength of Helix over, eg, nvim, is that it "just works" most of the time.

I propose adding `.svn` as a criterion for workspace root detection. I would also be willing to provide a MR if given some pointers as to where in the codebase this happens.

**Comment by kirawi** [comment]
What version of Helix are you using? Svn is already recognized as a default root.

**Comment by kirawi** [comment]
I took a look and I was confusing this with https://github.com/helix-editor/helix/pull/10536.

**Comment by seanbone** [comment]
I'm using a build based on master from a few months ago (I don't have the exact commit hash at hand).
