### ISSUE TITLE
Cannot configure [editor.auto-save] section

### ISSUE THREAD

**Issue by nadapez** [helix-editor/helix#11422]
### Summary

Setting configuration in `config.toml` for `[editor.auto-save]` section does not work.

### Reproduction Steps

 

I tried this:

1. write to config.toml file:
```
[editor.auto-save]
focus-lost = true
```
(the file has only that 2 lines)

2. execute helix

I expected this to happen:

no error

Instead, this happened:

Iget this error:

```
Bad config: invalid type: map, expected a boolean in `auto-save`
```

### Platform

Linux

### Terminal Emulator

Konsole

### Installation Method

pacman

### Helix Version

helix 24.3

**Comment by pascalkuthe** [comment]
This feature was added in the last release. You are still using the previous release.

**Comment by nadapez** [comment]
ok. thanks
