### ISSUE TITLE
flexible way to add a lsp to many languages at once

### ISSUE THREAD

**Issue by jerabaul29** [helix-editor/helix#11440]
Would it be possible to add a way to add a lsp to many languages at once? For example things like a typo correction lsp (https://github.com/tekumara/typos-lsp or similar), snippets as lsp (https://github.com/estin/simple-completion-language-server or similar), llm-based lsp (https://github.com/SilasMarvin/lsp-ai or similar) are useful on many different languages, but it is quite tiredsome to edit the configuration of all the languages by hand and edit / maintain this.

I wonder if it would be useful to provide a few "tools", for example "enable to all" to enable to all file kinds, "enable to all except" to enable to all file kinds except a few ones.

This has overlap / is directly similar to https://github.com/helix-editor/helix/discussions/8850 .

**Comment by kirawi** [comment]
See https://github.com/helix-editor/helix/issues/8853

**Comment by pascalkuthe** [comment]
Yes this falls under the config refactor and is already somewhat possible on the branch I have (but not usable yet).
