### ISSUE TITLE
File autocomplete in :open breaks with symlinks

### ISSUE THREAD

**Issue by zebubull** [helix-editor/helix#11457]
### Summary

Trying to use `../` in `:open` while in a symlinked directory shows autocomplete from the parent directory of the symlink source rather than the symlink. Actually opening the file does not do this and goes to the correct parent directory.

### Reproduction Steps

 

I tried this:

1. `mkdir a`
2. `mkdir b`
3. `touch file_in_root`
4. `cd a`
5. `touch file_in_a`
6. `ln -s ../b link_to_b`
7. `cd link_to_b`
8. `hx`
9. `:open ../`

I expected this to happen:
Receive autocomplete from `a` e.g. `link_to_b/ file_in_a`

Instead, this happened:
Receive autocomplete from the root folder e.g. `a/ b/ file_in_root`

### Helix log

Log was empty

### Platform

Arch Linux

### Terminal Emulator

kitty 0.35.2

### Installation Method

pacman

### Helix Version

helix 24.7

**Comment by pascalkuthe** [comment]
This is not a bug this is simply how symlinks work. If you run `ls ..` instead of opening helix you will find that it prints the same thing helix suggests.
