### ISSUE TITLE
Space / global search feature is broken

### ISSUE THREAD

**Issue by jakubrpawlowski** [helix-editor/helix#11460]
`Space /` global search menu is currently broken when compiling from source:
<img width="1642" alt="image" src="https://github.com/user-attachments/assets/40d450ef-6c2c-4e85-9371-58218affa214">

Last month when compiling from source `Space /` did the following:
<img width="545" alt="image" src="https://github.com/user-attachments/assets/b9a1a318-dc48-4ef8-94ba-bcbe2de46f9c">

**Comment by pascalkuthe** [comment]
this is an intentional change, the global search picker is now interactive. refer to the documentation about pickers https://docs.helix-editor.com/master/pickers.html

**Comment by jakubrpawlowski** [comment]
It's working on 24.07 tag `git clone --branch 24.07 https://github.com/helix-editor/helix.git` so it's only broken on master.

<img width="249" alt="image" src="https://github.com/user-attachments/assets/3f645091-bb44-4ee2-a735-3b80df71c005">

**Comment by pascalkuthe** [comment]
Yes this is a new intentional change thay was merged after the last release. There is no bug here

**Comment by jakubrpawlowski** [comment]
I was now forced to upgrade and I've read this documentation you linked and I still don't understand how I can search for a specific phrase `x` in filename `y`.

It used to be:
`Space /` and you type phrase `x` to search
`Enter` and it takes you to file picker where you can type `y` file name to narrow down to search phrase `x` in those files `y`

How can I do it in newer version of Helix?

**Comment by jakubrpawlowski** [comment]
I found the answer on the site: https://helix-editor-tutorials.com/tutorials/using-helix-global-search/

`Space /` and type `x %p y`
