### ISSUE TITLE
Auto-Complete adds double $ character after choosing a value from the dropdown menu

### ISSUE THREAD

**Issue by leo-unglaub** [helix-editor/helix#11470]
### Summary

Hey,
when you use Helix in a PHP project the LSP autocompletion via `phpactor` is triggered as soon as you type the $ character. Then you get a list of variable names and so on. As soon as you choose one via `<Tab>+<Enter>` or via `<C-n>+<Enter>` it gets added, but with two $ characters.

Expected:
```php
public function client(): BelongsTo
{
	return $this->belongsTo(Device::class);
}
```

What you end up with:
```php
public function client(): BelongsTo
{
	return $$this->belongsTo(Device::class);
}
```

### Helix log

<details><summary>~/.cache/helix/helix.log</summary>

```
2024-08-12T15:02:50.594 helix_lsp::transport [ERROR] phpactor err <- "Starting language server, use -vvv for verbose output\n"
```

</details>

### Platform

Linux desktop 6.10.3-amd64 #1 SMP PREEMPT_DYNAMIC Debian 6.10.3-1 (2024-08-04) x86_64 GNU/Linux

### Terminal Emulator

GNOME Terminal - Version 3.52.2 for GNOME 46 (VTE version 0.77.91 +BIDI +GNUTLS +ICU +SYSTEMD)

### Installation Method

Binary from the release page

### Helix Version

helix 24.7 (079f5442)

**Comment by VasilisManol** [comment]
Workaround in https://github.com/helix-editor/helix/issues/11470

**Comment by kirawi** [comment]
I'm closing this as a duplicate and since it has a solution.
