### ISSUE TITLE
Integration tests

### ISSUE THREAD

**Issue by kirawi** [helix-editor/helix#115]
I'm wondering if it would be practical to have a set of integration tests, especially to test hotkeys & rendering. Having it available for monkeys like me would make it a lot easier to test if everything is running correctly.

**Comment by pickfire** [comment]
The kakoune approach of integration tests is interesting. But I wonder if we can do something like rust compiler sort of ui tests, like using comments? I think this is in @archseer todo. @kirawi are you interested in doing this?

**Comment by kirawi** [comment]
Unfortunately, I'm not very familiar with creating tests, and I will be too busy :(

**Comment by archseer** [comment]
For integration tests, we can probably construct an `Editor` with a single document, wrap it in a `ui::Editor` then call `handle_events` to inject keys.

**Comment by kirawi** [comment]
I'll be creating a testing harness for #228

**Comment by kirawi** [comment]
@archseer Do we still need this issue? I no longer feel as strongly about integration tests specifically.

**Comment by archseer** [comment]
Yes, integration tests are important. Probably even more than the current set of unit tests.

**Comment by dead10ck** [comment]
This was done
