### ISSUE TITLE
"backtab" key (S-tab) does not work when remapped

### ISSUE THREAD

**Issue by rabirabirara** [helix-editor/helix#1150]
### Reproduction steps

In my `config.toml` I have:
```
[keys.insert]
"backtab" = "normal_mode"
``` 
...but pressing "S-tab" does not exit insert mode as I expect.  (I also tried mapping "S-tab", with no luck either.)

In fact, trying to map "backtab" even during normal mode doesn't work.  I added:
```
[keys.normal]
"backtab" = "move_next_word_start"
```
...and nothing happens on "S-tab".  The same is of course true if I map "S-tab" to the command.

Other shift keymaps work.  For example, "S-ret" is working fine.

 

### Environment

- Platform: Windows 10
- Helix version: 0.5.0

</details>

**Comment by archseer** [comment]
I think the problem is that it's trying to map `backtab` without the shift modifier. Does `S-backtab` work?

**Comment by rabirabirara** [comment]
Yup!  It would be nice if there was some kind of note in the docs about mapping this key.  It's really not intuitive.

**Comment by sudormrfbin** [comment]
It makes more sense for `BackTab` to act as shift-tab without the extra `S-BackTab` (I made the same assumption in a refactor a while ago and it had to be reverted - d3def16584f7f35a64ab2bad578436bd13cc18b6). I think we should normalize it like we do for `a` vs `A` internally.

**Comment by archseer** [comment]
Yeah I agree, this should happen here: https://github.com/helix-editor/helix/blob/21143e8d22c13ead8c1835063acb518aa5a42822/helix-term/src/ui/editor.rs#L1161-L1169

**Comment by archseer** [comment]
Similar function in kakoune: https://github.com/mawww/kakoune/blob/d758bbf09b949f0fef88ef3c6762cc55098cdb95/src/keys.cc#L19-L44

**Comment by archseer** [comment]
(Honestly, we should probably hide `backtab` altogether and normalize to `shift-tab`)
