### ISSUE TITLE
Scope/Code-Block Visibility Lines

### ISSUE THREAD

**Issue by LuigiDaBro** [helix-editor/helix#11519]
For larger scopes/blocks a visibility line would make it a lot clearer.  
Here is a little example in the c language:
```c
#include <stdio.h>

int main() {
| printf("Hello, World!");
| /* 
| |* a
| |* lot
| |* of
| |* lines
| |* */
| return 0;
}
```
The bars could be in the line-number color and maybe "light up" when you are in the given block. Lazyvim already has this feature, and I find it quite pleasant.

![Screenshot 2024-08-18 233110](https://github.com/user-attachments/assets/03ae32c2-3536-4bce-93ce-219595fb5646)

**Comment by the-mikedavis** [comment]
You can enable this with the `editor.indent-guides.render` config option: https://docs.helix-editor.com/master/editor.html#editorindent-guides-section
