### ISSUE TITLE
Allow insertion of file paths with autocomplete

### ISSUE THREAD

**Issue by fonskip** [helix-editor/helix#11544]
It would be great to be able to insert/append a file path using tab completion:

- In normal mode, press "@" -> enter the file path you want to insert, with autocomplete
- In normal mode, press "A-@" -> enter the file path you want to append, with autocomplete

Everything needed was already there so I suggested a small change that I will link to this Issue.

**Comment by the-mikedavis** [comment]
This should be covered with completion instead, see https://github.com/helix-editor/helix/issues/1015, https://github.com/helix-editor/helix/pull/2608
