### ISSUE TITLE
Small mistake in build instructions `Note for packager`

### ISSUE THREAD

**Issue by lukeflo** [helix-editor/helix#11557]
I encountered a small flaw in the docs regarding building Helix from source. But since my Rust/Cargo knowledge is very limited, I'm not sure if it is a real bug, just a copy/paste typo, or my misunderstanding. Thus, no big bug report here, but a simple issue.

In the section [Note to packagers](https://docs.helix-editor.com/master/building-from-source.html#note-to-packagers) under point to of the numbered list it is stated that the command `cargo build --profile opt --locked --path helix-term` should be executed to build Helix from source.

But if you run the command (after exporting the needed `HELIX` env variables, of course), yo'll get the following error:

```sh
cargo build --profile opt --locked --path helix-term
error: unexpected argument '--path' found

Usage: cargo build --profile <PROFILE-NAME> --locked

For more information, try '--help'.
```

Also the manpage, invoked with `cargo help build`, does not list `--path` as valid argument for the `build` command.

It might be a copy and paste error since in the initial section the command `cargo install --path helix-term --locked
` is proposed for building Helix from source.

At least, AFAIK, building Helix with `cargo build --profile opt --locked` works just fine without the `--path helix-term` argument.

But as mentioned above, there might be another reason for the `--path` argument with the `build` command, I'm not aware of.

**Comment by the-mikedavis** [comment]
Yep good catch, I believe that's just a copy/paste bug. Feel free to submit a PR. That document lives here: https://github.com/helix-editor/helix/blob/master/book/src/building-from-source.md

**Comment by lukeflo** [comment]
Is that really worth a PR? Someone with write permissions only needs to delete the words `--path helix-term` from the line `cargo build --profile opt --locked --path helix-term`.

**Comment by the-mikedavis** [comment]
Only the author has unrestricted write access, for everything else we need a PR
