### ISSUE TITLE
helix tutor not open when building helix from source

### ISSUE THREAD

**Issue by wingyplus** [helix-editor/helix#1157]
Found when building `hx` from source. If open the tutorial with `hx --tutor` or `:tutor` command inside the `hx`. The tutorial content will not open. After some debugging, I found out that it's trying to open the tutor file at `$HOME/.cargo/bin/runtime/tutor.txt`. 

### Reproduction steps

Run `cargo install --path helix_term` and then run `hx --tutor` or open `hx` and run `:tutor`.

### Environment

- Platform: macOS
- Helix version: helix v0.5.0-145-g72f606e-dirty

### Workarounds

Just set the `HELIX_RUNTIME` to the folder runtime in the source. It's works.

**Comment by leontepe** [comment]
Same error here. Why is this closed?

**Comment by sudormrfbin** [comment]
Did you copy the runtime directory to the [appropriate location](https://docs.helix-editor.com/#build-from-source) ?

> Helix also needs it's runtime files so make sure to copy/symlink the runtime/ directory into the config directory (for example ~/.config/helix/runtime on Linux/macOS). This location can be overriden via the HELIX_RUNTIME environment variable.

**Comment by wingyplus** [comment]
> Same thing here. Why is this closed?

As @sudormrfbin suggestion, you need to copy runtime by yourself. If we want to tackle this issue, it need shellscript or makefile (or something like that) to install binary and copy runtime to proper path.

**Comment by leontepe** [comment]
> Did you copy the runtime directory to the [appropriate location](https://docs.helix-editor.com/#build-from-source) ?
> 
> > Helix also needs it's runtime files so make sure to copy/symlink the runtime/ directory into the config directory (for example ~/.config/helix/runtime on Linux/macOS). This location can be overriden via the HELIX_RUNTIME environment variable.

Didn't do that, no. Works now. Thanks :)

**Comment by holtkampjs** [comment]
I just faced this issue. (in Windows 10)
1. make sure you successfully compiled the repo from source
2. the location where `hx --grammar fetch` or `hx --grammar build` place the `/runtime` directory is where your `HELIX_RUNTIME` currently points to. 
3. copy the runtime directory from the cloned repo to that location or change the `HELIX_RUNTIME` environment variable if you know how to. 
4. then run the `hx --grammar fetch` and `hx --grammar build` commands as instructed. 

I do not yet know how to change the HELIX_RUNTIME environment variable in windows

**Comment by wingyplus** [comment]
@holtkampjs if you’re using powershell, consult this page below. It will help you how to set shell env

https://docs.microsoft.com/en-us/powershell/module/microsoft.powershell.core/about/about_environment_variables

**Comment by Martin15135215** [comment]
So i have the same problem, i did the steps from https://docs.helix-editor.com/install.html#build-from-source

```
git clone https://github.com/helix-editor/helix
cd helix
cargo install --locked --path helix-term
```

and 

`ln -s $PWD/runtime ~/.config/helix/runtime`

then run hx --tutor or open hx and run :tutor


## Environment
Platform: Debian WSL on Windows 10
Helix version: 
```
❯ hx --version
helix 22.12 (051cd786)
```

i installed Rust with this command

`curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh`
