### ISSUE TITLE
LSP health within project

### ISSUE THREAD

**Issue by Mirko-von-Leipzig** [helix-editor/helix#11637]
Is it possible to check rust-analyzers health in the context of the open workspace?

What happens occasionally is that I make an error in a `Cargo.toml` file which causes RA to error out on startup. However this isn't visible within `helix` itself afaict and all I get is a brief `spinner` indicating work being done and then no RA functionality. `editor.lsp.display-messages` is enabled.

**Comment by cotneit** [comment]
Sounds like https://github.com/helix-editor/helix/issues/10972

**Comment by Mirko-von-Leipzig** [comment]
> Sounds like #10972

Thanks! Closing as that covers it more thoroughly.
