### ISSUE TITLE
Helix hangs if `:pipe-to` is used to run `xclip`

### ISSUE THREAD

**Issue by mr6r4y** [helix-editor/helix#11633]
### Summary

Helix hangs indefinitely if `:pipe-t` or `:pipe` is running `xclip` or any program that uses `xclip`.
The system is Ubuntu 22.04 and hellix version is helix 24.7 (079f5442). 

### Reproduction Steps

 

I tried this:

1. `hx`
2. Write and select something
3. `:pipe-to xclip`

I expected this to happen:

Command is executed and Helix is running normally

Instead, this happened:

Helix hangs indefinitely and has to be `kill -9`-ed

![image](https://github.com/user-attachments/assets/52a6f471-8512-4b84-843d-f2393fe9963b)

### Helix log

<details><summary>~/.cache/helix/helix.log</summary>

```
please provide a copy of `~/.cache/helix/helix.log` here if possible, you may need to redact some of the lines
```

</details>

### Platform

Ubuntu 22.04

### Terminal Emulator

kitty 0.35.2 created by Kovid Goyal

### Installation Method

deb

### Helix Version

helix 24.7 (079f5442)

**Comment by mr6r4y** [comment]
Seems the reason is in `xclip` - https://emacs.stackexchange.com/questions/39019/xclip-hangs-shell-command

**Comment by pascalkuthe** [comment]
Yes piping things into xclip is just not how it works. Helix will wait for the pipe command to terminate and since clip doesn't terminate things are working as intended.

Heljx has builtin functionality to properly copy things to clipboard with `<space-y>`
