### ISSUE TITLE
Assembly Highlight Wrong

### ISSUE THREAD

**Issue by GabrielFrigo4** [helix-editor/helix#11674]
### Summary

![image](https://github.com/user-attachments/assets/d4be7a91-f296-46e8-91c8-e68ca9b53f35)

![image](https://github.com/user-attachments/assets/73301c82-8195-42bf-9b53-3e4e7b9e1e51)

It's easy to notice the error, it shouldn't have these characters colored white when there is a comment on the previous line

### Reproduction Steps

 

I tried this:

1. `hx assembly.asm` and type
```asm
; I expected this to happen:

word

; Instead, this happened:
word
```

I expected this to happen:
![image](https://github.com/user-attachments/assets/ce2d57a7-1499-49a2-a1bd-5be73dc09ab1)

Instead, this happened:
![image](https://github.com/user-attachments/assets/171d44a0-cd45-4ce8-ba56-5619aca1f650)

### Helix log

<details><summary>~/.cache/helix/helix.log</summary>

```
please provide a copy of `~/.cache/helix/helix.log` here if possible, you may need to redact some of the lines
```

</details>

### Platform

Windows

### Terminal Emulator

Windows Terminal

### Installation Method

winget

### Helix Version

helix 24.7 (079f5442)

**Comment by Narcha** [comment]
I think helix [uses](https://github.com/helix-editor/helix/blob/5ce77de0dc7106c6f1460d80a3c5a51eaea3108c/languages.toml#L2943-L2953) [this tree-sitter grammar](https://github.com/naclsn/tree-sitter-nasm) for .asm files. Maybe it's better to report the error there?

**Comment by GabrielFrigo4** [comment]
> I think helix [uses](https://github.com/helix-editor/helix/blob/5ce77de0dc7106c6f1460d80a3c5a51eaea3108c/languages.toml#L2943-L2953) [this tree-sitter grammar](https://github.com/naclsn/tree-sitter-nasm) for .asm files. Maybe it's better to report the error there?

I thought there was no tree-sitter for ASM/NASM :)
I'll send this error to them
