### ISSUE TITLE
Grammars: Missing support for proto2

### ISSUE THREAD

**Issue by sdoerner** [helix-editor/helix#11794]
I'm planning to work on this, so feel free to assign (I don't have permissions).

### Current situation:

- Grammar used by Helix is https://github.com/yusdacra/tree-sitter-protobuf at `19c211a01434d9f03efff99f85e19f967591b175`
  - [Queries](https://github.com/helix-editor/helix/tree/master/runtime/queries/protobuf)
- Grammar used by nvim is https://github.com/treywood/tree-sitter-proto (pinned at [current main](https://github.com/nvim-treesitter/nvim-treesitter/blob/fb2d41ec599b68af041f3071ada883718928e279/lockfile.json#L582))

### Problems of current situation:

- no proto2 support (also no support [Editions](https://protobuf.dev/editions/overview/) but this is not supported anywhere so out of scope for now)
- different grammar than nvim leads to fragmentation
- neither of the grammars' feature sets is a superset of the other one --> upstream work needed
- inconsistent language identifier (`proto` vs `protobuf`)

### Plan of action

- [ ] agree with @yusdacra and @treywood on a unification plan. Probably consolidating on treywood/tree-sitter-proto is easier because its [network graph](https://github.com/treywood/tree-sitter-proto/network) is larger (e.g it's used by [nvim-treesitter](https://github.com/nvim-treesitter/nvim-treesitter?tab=readme-ov-file#supported-languages)).
  - [X] reach out to @yusdacra to get agreement for that
  - [X] reach out to @treywood about adding missing features to https://github.com/treywood/tree-sitter-proto
- [x] implement missing features in https://github.com/treywood/tree-sitter-proto
- [ ] get missing features into https://github.com/treywood/tree-sitter-proto master branch - [PR](https://github.com/treywood/tree-sitter-proto/pull/2)
- [ ] switch Helix over to the new grammars (and `proto` identifier)
- [ ] fix [reverse-query-precedence-ordering branch](https://github.com/helix-editor/helix/tree/reverse-query-precedence-ordering) if needed

### Analysis of missing features

Features missing for [highlights.scm](https://github.com/helix-editor/helix/blob/master/runtime/queries/protobuf/highlights.scm):

- missing `mapName`, `extendName`, `fieldName` and `enumVariantName`
- missing `optionName` - this is fixed in the [`fixups` branch](https://github.com/treywood/tree-sitter-proto/tree/fixups) but needs merging into main

Features missing for [indents.scm](https://github.com/helix-editor/helix/blob/master/runtime/queries/protobuf/indents.scm):

- `oneofBody`, `serviceBody` and `rpcBody` are missing. You can use `oneof`, `service` and `rpc` instead, but this probably leads to some regressions. Not sure if there is a severe enough case to block on this. I noticed a difference with declarations like this in `hybrid` indent heuristic, but they actually both misbehave.
  ```
  rpc FooRpc(FooRpcRequest)
      returns (FooRpcResponse) {
    option deadline = 20.0;
  }
  ```

Features missing for [textobjects.scm](https://github.com/helix-editor/helix/blob/master/runtime/queries/protobuf/textobjects.scm):
 - missing `serviceBody`

**Comment by sdoerner** [comment]
@yusdacra @treywood - feel free to comment directly here on the above. Otherwise I'll try to reach out more directly.

**Comment by yusdacra** [comment]
yeah sure, i don't mind unifying work somewhere else. i haven't looked at the grammar in a long while anyway 😅

**Comment by sdoerner** [comment]
Couldn't get in touch with @treywood so far. There is also an [open PR](https://github.com/treywood/tree-sitter-proto/pull/1) without a response after 3 weeks. So upstreaming may be difficult.

My updated plan is now to create a new fork with the following features:
 * based on https://github.com/treywood/tree-sitter-proto/tree/fixups . This should make it easier to eventually merge them back, or to move nvim over to my fork.
 * having a deep look through https://github.com/treywood/tree-sitter-proto/network to find useful additions. Presumably the issues above have already been fixed.

**Comment by sdoerner** [comment]
Created a draft PR for now, to provide some time for feedback from other proto users. Please let me know if you see any issues (in particular @yusdacra, in case you still use protos on the regular).
