### ISSUE TITLE
Keymap refactor

### ISSUE THREAD

**Issue by NNBnh** [helix-editor/helix#1179]
> _This is a follow up update to [this comment](https://github.com/helix-editor/helix/issues/165#issuecomment-965563368)._

I have always looking for a modal terminal editor that use caret style cursors,
Helix currently has implement Gap indexing #376 which mean the caret cursor dream is not far from becoming the reality.

So as Cessen said:

> I'll switch Helix to gap indexing, but keep all current behavior the same and enforce a minimum-1-width range.
>
> Behavioral changes can be a separate discussion...

Let's discuss about refactor the keymap to take advantages of it (and more). Here is my attempt:

## Note

Because of a defined [Helix's goal from `vision.md`](https://github.com/helix-editor/helix/blob/master/docs/vision.md#goals):

> - **We aren't playing code golf:** It's more important for the keymap to be consistent and easy to memorize than it is to save a key stroke or two when editing.

I feel more confident making some brave decision that focus way more on consistency.

Also i found a lot of my idea have been implemented on [Pepper editor](https://github.com/vamolessa/pepper)
so some keys are take inspiration from [it's key bindings](https://github.com/vamolessa/pepper/blob/master/pepper/rc/bindings.md):

> Pepper is heavily inspired by Kakoune's selection based workflow and multiple cursors.
> However its cursors behave like caret ranges instead of block selections.
> That is, the cursor is not a one-char selection but only a visual cue to indicate the caret location.

The final results will look like this:

![Preview](https://user-images.githubusercontent.com/43980777/143607044-986f1942-839b-4f03-804d-c77db2bfd03d.png)

> *[Keyboard layout editor link](http://www.keyboard-layout-editor.com/#/gists/cfd365f36b8aceb6c81f61dad24fa0f0).*

## Current keymap

I thinks the movement will stay pretty much the same except for moving to the end of an object:

Because the implement Gap indexing, moving to the end of an object (e.g: a word) will place the cursor to the right of the last character of the object.

### Text inserts

For consistency, any actions that insert text to the cursor will have the following behaviors:
1. In normal mode, insert text will be place to the left of the cursor _(not the selection)_.
2. In select mode, insert text will replace the selections and not copy/yank it.
3. If a \<n\> number is assigned, the text will be insert \<n\> times.
4. Inserted text will be selected (work with number assign).

Because insert text will replace the selection:

- Remove `change_selection` from <kbd>c</kbd>
- Remove `change_selection_noyank` from <kbd>a-c</kbd>
- Remove `replace_with_yanked` from <kbd>R</kbd>.
  - Move `copy_selection_on_next_line`, `copy_selection_on_prev_line` from <kbd>C</kbd>, <kbd>a-c</kbd> to <kbd>c</kbd>, <kbd>C</kbd>.

Because of the same reason, users don't need to different "insert" and "append" anymore:

- Remove `append_mode` from <kbd>a</kbd>.
  - Unmap `prepend_to_line` from <kbd>I</kbd>.
  - Move `append_to_line` from <kbd>A</kbd> to <kbd>I</kbd>.
- Remove `paste_before` from <kbd>P</kbd>.
  - Rename `paste_after` to `paste`.
- Remove `shell_append_output` from <kbd>a-!</kbd>.

And therefore we should make flipping selections as easy to press as possible:

- Move `flip_selections` from <kbd>a-;</kbd> to <kbd>a</kbd>.

| TODO | Improve `append_to_line` and `prepend_to_line`. |
| ---- | ----------------------------------------------- |

#### Word movement

I found that `move_next_word_start` is just a legacy key that people get used to from Vi.
Where `move_next_word_end` is much more superior in this navigation system,
not to mention it's behavior is consistent with `move_prev_word_start`.
I know this is a controversial decision but [Pepper](https://github.com/vamolessa/pepper/blob/master/pepper/rc/bindings.md#navigation) and literally all non Vim-like editors agree with me on this one:

- Unmap `move_next_word_start`, `move_next_long_word_start` from <kbd>w</kbd>, <kbd>W</kbd>.
- Move `move_next_word_end`, `move_next_long_word_end` from <kbd>e</kbd>, <kbd>E</kbd> to <kbd>w</kbd>, <kbd>W</kbd>.

#### Find and till

> As discussed in ~~#274~~ #510, we will have a much more fast and convenient way to navigate the code.
> In contrast _find_ and _till_ keys will just be a slow clumsy unpredict legacy ways to navigate that took space on keyboard.
> The only advantage of the _find_ and _till_ keys is they can be use when there is multiple cursor,
> but then user can just use the *search* key which way more powerful and consistent:
>
> - ~~Unmap `find_next_char`, `find_prev_char` from <kbd>f</kbd>, <kbd>F</kbd>.~~
> - Unmap `find_till_char`, `till_prev_char` from <kbd>t</kbd>, <kbd>T</kbd>.

But after some consideration from my own experience and listen to @raphCode suggestion:

> Please consider keeping <kbd>f</kbd>, <kbd>F</kbd> since I use these often to jump into the middle of a word with a typo (especially german words can be pretty long). Alternatively, the jump mode could incorporate this workflow by offering multiple jump targets in longer words.

I decided to keep the _find_ keys, but the _till_ keys still need to go in order to make room for the "No Alt-based keys" section.

### Movement behavior

As pointed out in [keymap brainstorm wiki](https://github.com/helix-editor/helix/wiki/Keymap-brainstorm) and #863, Helix currently need a bit more keypress to do some basic action than it's should.
To improve this, i suggest:

In normal mode, all movement keys (<kbd>w</kbd>, <kbd>W</kbd>, <kbd>b</kbd>, <kbd>B</kbd>, <kbd>f</kbd>, <kbd>F</kbd>) and [goto mode key](https://docs.helix-editor.com/keymap.html#goto-mode) should do the following actions in order:
1. Collapse all selections.
2. Enter select mode.
3. Call \<n\> the assigned number, \<n\> == 1 if there is no number being assigned, repeat the movement key \<n\> times (as discussed in #536).
4. Go back to normal mode.

This will make most basic action in Helix have the keypress count as low as in Kakoune.

<details>
<summary>E.g</summary>

Deletes till the end of the line:

| Editor         | Example                                             | Keypress |
| -------------- | --------------------------------------------------- | -------- |
| Vim            | <kbd>D</kbd>                                        | 2        |
| Kakoune        | <kbd>g</kbd> <kbd>l</kbd> <kbd>d</kbd>              | 3        |
| Helix current  | <kbd>v</kbd> <kbd>g</kbd> <kbd>l</kbd> <kbd>d</kbd> | 4        |
| Helix refactor | <kbd>g</kbd> <kbd>l</kbd> <kbd>d</kbd>              | 3        |

</details>

### Changes behavior

In normal mode, if a \<n\> number is assigned, it will have an effect to \<n\> lines or the next \<n\> charaters base on each oporation type:
- Charater type oporations:
  - `replace`
  - `switch_case`
  - `switch_to_lowercase`
  - `switch_to_uppercase`
- Whole line type oporations:
  - `yank`
  - `delete_selection`
  - `delete_selection_noyank`
  - `format_selections`
  - `toggle_comments`

### No Alt-based keys

I have remap nearly every keys on [Vim](https://github.com/NNBnh/bkey-vim), [Kakoune](https://github.com/NNBnh/bmap.kak), [Emacs](https://github.com/NNBnh/.emacs.d)
and i alway include a feature: a "normal" mod key in insert mode (which i explain in more detail at #1064).

To achieve this, we mustn't have any Alt-based keys by defaults.

Plus as mentioned in [keymap brainstorm wiki](https://github.com/helix-editor/helix/wiki/Keymap-brainstorm):

> we prefer not to hold keys (shift, ctrl, alt)

- Move `delete_selection_noyank` from <kbd>a-d</kbd> to <kbd>D</kbd>.
- Move `shell_pipe_to` from <kbd>a-|</kbd> to <kbd>\\</kbd>.
- Move `split_selection_on_newline` from <kbd>a-s</kbd> to <kbd>c-l</kbd>.
- Move `switch_to_uppercase` from <kbd>a-\`</kbd> to <kbd>^</kbd>.
- Move `earlier`, `later` from <kbd>a-u</kbd>, <kbd>a-U</kbd> to <kbd>t</kbd>, <kbd>T</kbd>.
- Move `rotate_selections_forward`, `rotate_selections_backward` from <kbd>)</kbd>, <kbd>(</kbd> to <kbd>L</kbd>,  <kbd>H</kbd>.
  - Move `rotate_selection_contents_forward`, `rotate_selection_contents_backward` from <kbd>a-)</kbd>, <kbd>a-(</kbd> to <kbd>)</kbd>,  <kbd>(</kbd>.

- Move `keep_primary_selection` from <kbd>,</kbd> to <kbd>e</kbd>.
- Move `remove_primary_selection` from <kbd>a-,</kbd> to <kbd>E</kbd>.
- Move `repeat_last_motion` from <kbd>a-.</kbd> to <kbd>,</kbd>.
- Move `remove_selections` from <kbd>a-K</kbd> to <kbd>R</kbd>.

## Future keymap

The following keymaps are in ~~[`TODO.md`](https://github.com/helix-editor/helix/blob/master/TODO.md)~~ [`keys.md`](https://gist.github.com/archseer/0b4f474df3dcfb0b8fef09b5b97f9f79):

- **Normal:**
  - Add `ensure_selections ` (ensure selections are in forward direction) to <kbd>A</kbd>.
  - Add `join_selections_linebreak` (join selected lines and select spaces inserted in place of line breaks) to <kbd>c-j</kbd>.
  - Add `merge_selections` (merge contiguous selections together) to <kbd>M</kbd>.
  - Add `duplicate_selections` (duplicate each selection / generating overlapping selections) to <kbd>+</kbd>.
  - Add `merge_overlap_selections` (merge overlapping selections) to <kbd>-</kbd>.
  - Add `paste_all` (paste every yanked text) to <kbd>P</kbd>.
- **Marks:**
  > *This is currently being discussed in #703 and #943.*
- **Macros:**
  - Add `play_macro` to <kbd>q</kbd>.
  - Add `record_macro` to <kbd>Q</kbd>.
  - Add `stop_record` to <kbd>esc</kbd>.
- **Jumps:**
  - Add `jump_save` (save selection on jumplist) to <kbd>c-s</kbd>.

Because as we stased: "we mustn't have any Alt-based keys by defaults", the following key need some more thought out placement.

| TODO           | Description                                                                                                       |
| -------------- | ----------------------------------------------------------------------------------------------------------------- |
| <kbd>a-&</kbd> | Copy indent, copy the indentation of the main selection (or the count one if a count is given) to all other ones. |
| <kbd>@</kbd>   | Convert tabs to spaces in each selection, uses the buffer tabstop option or the count parameter for tabstop.      |
| <kbd>a-@</kbd> | Convert spaces to tabs in each selection, uses the buffer tabstop option or the count parameter for tabstop.      |

### Paragraph

As explained in #753:

- Add `paragraph_next` to <kbd>}</kbd>.
- Add `paragraph_prev` to <kbd>{</kbd>.

### Jump mode

As discussed in ~~#274~~ #510 (#1162):

- Add `jump_mode` to <kbd>'</kbd>.

**Comment by glyh** [comment]
I think we should keep on mind to put the most frequency keymaps with the easiest to reach key.
For example, I always think the command mod "Shift+;" deserves to be a single keystroke, because it's so frequently used.

**Comment by raphCode** [comment]
I think with the planned plugin system and remapping support we gain with it it should be fairly easy to implement whatever layout. For example, you can make a custom "NNBnh keymap" that is independent of the default helix mapping. See also: https://github.com/helix-editor/helix/issues/165#issuecomment-971757617

I believe that the default mapping of helix probably will not change by your proposal. On the flip side this means you can use more "agressive" remappings which deviate from the mainstream because you don't have to find a compromise with the existing mapping.

**Comment by pickfire** [comment]
I do agree on most of the stuff @NNBnh mentioned (I didn't look closely at every key). To make this contributor friendly it would be better to split this into multiple smaller issues and then use milestones to group them.

Example scope for an issue, change goto mode to select text for those that make sense (E.g. `gh`).

**Comment by NNBnh** [comment]
> To make this contributor friendly it would be better to split this into multiple smaller issues and then use milestones to group them. So even if people disagree, other parts can still continue.

> You can make a custom "NNBnh keymap" that is independent of the default helix mapping.
>
> I believe that the default mapping of helix probably will not change by your proposal. On the flip side this means you can use more "agressive" remappings which deviate from the mainstream because you don't have to find a compromise with the existing mapping.

I have this two on my todo list for a while, but currently doesn't have much time to sort it out. I think it's time to take this into action:
- Current keymap:
  - Caret style cursors: _#TODO I'm creating an issue for this_ (the most important one)
  - ~~Text inserts~~
  - ~~Movement key~~
  - Movement behavior: #536 and #1215
  - ~~Changes behavior~~
  - ~~No Alt-based keys~~ (#1211)
  - Future keymap:
    - Paragraph: #753
    - Jump mode: ~~#274~~ #510 (#1162)

| NOTE | All strikethrough sections are things that can be achievable by remapping if caret style cursors is implemented |
|-|:-|

> You can make a custom "NNBnh keymap" that is independent of the default helix mapping.

I will definitely focus on this next year on [this repo](https://github.com/NNBnh/bmap). Here are some old/outdate idea and implement of this saga:
- [Idea](https://github.com/NNBnh/bkey-old).
- [Vim](https://github.com/NNBnh/bkey-vim).
- [Kakoune](https://github.com/NNBnh/bmap.kak).

Thank you guy for the support and feedback!
