### ISSUE TITLE
add info about installing golangci-lint for golang

### ISSUE THREAD

**Issue by graf0** [helix-editor/helix#11828]
Hi,
For linter in golang to work you need to install not only golangci-lint-langserver, but also golangci-lint - issue is described here: #10807
Would be great to add this line to wiki page Language-Server-Configurations, under description fo Go -> Install tools:

```
go install github.com/golangci/golangci-lint/cmd/golangci-lint@latest # Linter cli
```

This way you make helix a little bit more approchable for go developers.
Bye

**Comment by graf0** [comment]
without this tool hx --health go shows everything green - but when you try to edit .go file you get error in top right corner of editor: `exec: "golangci-lint": executable file not found in $PATH`

**Comment by pascalkuthe** [comment]
Wiki pages are freely editable by anyone so feel free to add somethjng, no need for an issue
