### ISSUE TITLE
Allow overwrite of config file, config directory and languages.toml

### ISSUE THREAD

**Issue by Stupremee** [helix-editor/helix#1182]
#### Describe your feature request

I'm currently packaging Helix into a nice NixOS module similar, but much better IMO, to the Neovim module in Home-Manager.
However, it's currently not possible to overwrite the Config file and other directories (except runtime directory), which doesn't work
well with NixOS as I will write the immutable config into the Nix store and Helix should use that one.

I suggest doing the following:
- Allow overwriting the path to the config file (via CLI or environment variable, like `-u` in Neovim)
  This will not change the config directory, so the `languages.toml` can still be found at `~/.config/helix/languages.toml`
- Allow overwriting the path for the language config (this will just overwrite the path for the `languages.toml` configuration, nothing else)
- Allow overwriting the whole config directory which will change language config and config file location to the new path

I would be ready to open a PR because this is a very important feature for me!

**Comment by archseer** [comment]
`home-manager` should be able to write to the xdg config directory just fine though.

`home-manager.users.<user>.xdg.configFile."helix/helix.config"` etc

**Comment by Stupremee** [comment]
Yes, I know, but I'm not writing  home-manager module.

**Comment by archseer** [comment]
> Neovim module in Home-Manager

Yeah okay, I was going off of this. Well, we lookup the xdg config directory to find the underlying location so you could set XDG_CONFIG_HOME to your desired location?

**Comment by Stupremee** [comment]
Yeah that was badly written 😅
It was meant in API ways so that you can configure Helix using Nix Language. 

Oh that would work too I guess. I will try that. Thank you!

**Comment by the-mikedavis** [comment]
Let's close this out in favor of #1216 which is more focused towards the CLI switch for choosing a config file. #2135 should allow the remaining customization.
