### ISSUE TITLE
Config not being loaded with sudo

### ISSUE THREAD

**Issue by dougg0k** [helix-editor/helix#11831]
Hi,

I am using Arch based OS, and the config doesn't seem to be loaded when using sudo.

Is there anything that can be done for it to work?

---

I've tried both options from here and it didnt work. https://github.com/helix-editor/helix/discussions/4251

---

Tried with an alias, it loads the config, but there is no content of the file.

`alias "sudo helix" = sudo helix --config ~/.config/helix/config.toml`

**Comment by dougg0k** [comment]
Found a way, through an alias.

`alias "sudo helix" = sudo helix --config ~/.config/helix/config.toml`

**Comment by dougg0k** [comment]
I didnt do it right, `SUDO_EDITOR` works, but ideally would be better if done straight to helix.

**Comment by rhogenson** [comment]
Running any text editor as root is a bad idea in general, and especially bad with Helix since the LSP can execute arbitrary code. I recommend using sudoedit which runs the editor as your normal user on a temporary file.
