### ISSUE TITLE
Helix navigation breaks after shell execution failed

### ISSUE THREAD

**Issue by Wang-Ji20** [helix-editor/helix#11853]
### Summary

Helix supports executing shell commands via
> sh \<the shell command\>

If the execution is failed, cursor in the buffer behave strangely. 
1. The topbar disappears if you have it. (I set it to always).
2. The cursor is automatically duplicated to two cursors.
3. when you move the cursor, only the second one moves, and it duplicates whatever character the first cursor is pointing to
4. But if you write and save, no change is actually applied.

### Reproduction Steps

1. create a new file
2. write some text in that file
3. run `sh shakfjhaskljfh` in command mode.
4. move your cursor using hjkl

my config file:

```
theme = "ao"

[editor]
line-number = "relative"
mouse = false
bufferline = "always"

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[editor.file-picker]
hidden = false
```

### Helix log

2024-10-08T15:26:16.125 helix_term::commands [ERROR] Shell error: sh: line 1: hhh: command not found

### Platform

WSL opensuse-tumbleweed

### Terminal Emulator

Windows Terminal

### Installation Method

zypper

### Helix Version

helix 24.7 (079f5442)

**Comment by ngasull** [comment]
I'm facing the same issue when integrating lazygit as suggested here https://github.com/helix-editor/helix/discussions/12045.

It seems that commands can steal mouse from helix and that helix doesn't check that. For now, to work around this case, we can disable and re-enable mouse after interactive commands:
```
:set mouse false
:set mouse true
```

**Comment by TornaxO7** [comment]
I'm on NixOS and I'm using [rio](<https://raphamorim.io/rio/>) and I can't reproduce the issue.

I did the following:
1. Copied the provided config of @Wang-Ji20 in `/tmp/config.toml`
2. `hx --config /tmp/config.toml /tmp/test.txt`
3. Entered some random stuff in the file, then went back to normal mode
4. `:sh random shit goes brrrrrrr`
5. navigate in normal mode
everything worked as expected

**Comment by pascalkuthe** [comment]
Lazgit is a tui (and therefore causiing issues), running any TUI with sh is unsupported and will not work properly. We have absolutely no plan to change that

**Comment by Wang-Ji20** [comment]
> I'm on NixOS and I'm using [rio](https://raphamorim.io/rio/) and I can't reproduce the issue.
> 
> I did the following:
> 
> 1. Copied the provided config of @Wang-Ji20 in `/tmp/config.toml`
> 2. `hx --config /tmp/config.toml /tmp/test.txt`
> 3. Entered some random stuff in the file, then went back to normal mode
> 4. `:sh random shit goes brrrrrrr`
> 5. navigate in normal mode
> 
> everything worked as expected. Maybe it's somehow related to the windows terminal?

Using WezTerm still produces this issue

https://github.com/user-attachments/assets/686a76ba-cb5c-4369-bd64-76b87b6bbb87

And the config does not matter too. Using the default config still has this problem. I will try to understand why it happens.
