### ISSUE TITLE
specify config directory 

### ISSUE THREAD

**Issue by diygcy** [helix-editor/helix#11870]
Hey! How can I specify config directory, not always `~/.config/helix/` maybe conflict with other users.
It's something like zellij with option `--config-dir` and env `ZELLIJ_CONFIG_DIR` :
```
zellij 0.40.1

USAGE:
    zellij [OPTIONS] [SUBCOMMAND]

OPTIONS:
    -c, --config <CONFIG>            Change where zellij looks for the configuration file [env:
                                     ZELLIJ_CONFIG_FILE=]
        --config-dir <CONFIG_DIR>    Change where zellij looks for the configuration directory [env:
                                     ZELLIJ_CONFIG_DIR=]
    -d, --debug                      Specify emitting additional debug information
        --data-dir <DATA_DIR>        Change where zellij looks for plugins
    -h, --help                       Print help information
    -l, --layout <LAYOUT>            Name of a predefined layout inside the layout directory or the
                                     path to a layout file
        --max-panes <MAX_PANES>      Maximum panes on screen, caution: opening more panes will close
                                     old ones
    -s, --session <SESSION>          Specify name of a new session
    -V, --version                    Print version information
   ```

**Comment by TornaxO7** [comment]
> How can I specify config directory, not always `~/.config/helix/` maybe conflict with other users.

May I ask why you think that there could be a conflict? If the other users have their own user account, then the path `~/.config/helix` will be resolved differently.

**Comment by diygcy** [comment]
> > How can I specify config directory, not always `~/.config/helix/` maybe conflict with other users.
> 
> May I ask why you think that there could be a conflict? If the other users have their own user account, then the path `~/.config/helix` will be resolved differently.

In my case, we usually use a single account on a customer machine. Could it be a new feature?

**Comment by sdoerner** [comment]
See https://docs.helix-editor.com/configuration.html 

"
You can use a custom configuration file by specifying it with the -c or --config command line argument, for example hx -c path/to/custom-config.toml.
"

Not sure about how to do this for `languages.toml`.

**Comment by diygcy** [comment]
> This belongs under #10389 - we plan to switch to a scheme config and merge languages.toml and config.toml config, so once the config system is revamped you should be able to specify a different config with just the `-c myconfig.scm` flag.

will it have an env variable for `-c myconfig.scm` ?
