### ISSUE TITLE
adjust searcher heap usage

### ISSUE THREAD

**Issue by mjkpolo** [helix-editor/helix#11887]
It would be nice to change the max heap usage of the searcher in memory constrained environments like a cluster login node (which was killing helix when searching through large projects)

I posted [this](https://www.reddit.com/r/HelixEditor/comments/1g2aa6n/have_to_switch_back_to_nvim_for_memory_usage_on/) on the helix subreddit, and one of the commenters solved my issue and suggested I make a feature request. This is the patch that fixed my issue:

```
diff --git a/helix-term/src/commands.rs b/helix-term/src/commands.rs
index f25e8254..ecfcacfc 100644
--- a/helix-term/src/commands.rs
+++ b/helix-term/src/commands.rs
@@ -2327,6 +2327,7 @@ fn format(&self, current_path: &Self::Data) -> Row {

                 std::thread::spawn(move || {
                     let searcher = SearcherBuilder::new()
+                        .heap_limit(Some(5*1024*1024))
                         .binary_detection(BinaryDetection::quit(b'\x00'))
                         .build();
```

I have never written rust but if someone could point me in the general direction of how to add an options to the `config.toml` file and pass it to the searcher builder I would be be willing to try and add this as a feature.

**Comment by RoloEdits** [comment]
To access a config, you generally need a `Context`, which is usually done with a `cx: &mut Context`. This will give you access to the `cx.editor.config` which you can call `load()` on to get access to the fields.

I will say that the current master might be different than what you had before as the new global search has been added.

**Comment by mjkpolo** [comment]
@RoloEdits thank you, btw, how do I filter by file name, or has that feature been removed with the new global search? Or is it a toggle. I much preferred the old way.

**Comment by RoloEdits** [comment]
This is the commit that added the new picker(which includes the new search) https://github.com/helix-editor/helix/pull/9647

**Comment by mjkpolo** [comment]
@RoloEdits oh thank you!! Filtering by any column is actually really cool and is way better than before
