### ISSUE TITLE
Make gutters more configurable

### ISSUE THREAD

**Issue by dannasessha** [helix-editor/helix#1188]
Following up on #783.
 
Gutters are potentially useful for a variety of purposes, we should make them more configurable.

from [previous comments](https://github.com/helix-editor/helix/pull/783#issuecomment-977903773) : "...if a user wanted to use the column in the editor to have a `git diff` type display ala the vim git gutter plugin, or a `git annotate` type feature to familiarize themselves with the history of a file from a certain perspective, or even possibly being able to manipulate the column directly for some kind of bespoke user-annotation that could be made on the fly."

[and](https://github.com/helix-editor/helix/pull/783#issuecomment-978737241) : "...these types of gutter components give us more flexibility to allow for configuring the gutter (like disabling line numbers) or using different gutters per document (for example getting rid of diagnostics on docs with no LSP) as well as defining new types of gutters in the future (i.e. git gutter)"

**Comment by archseer** [comment]
I was thinking the config could be a `gutters = ["diagnostic", "line_number"]` type array.

**Comment by archseer** [comment]
Then you could have a `gutter.diagnostic` section for any additional config of each component

**Comment by dannasessha** [comment]
Okay, I'll see if I can get something going, thank you for the feedback!

**Comment by wurosh** [comment]
+1 for disabling line numbers as a feature (Or is this possible now? - I wasn't able to find the config option). In an editor which supports jumping to lines this easily they're kind of a waste of space (unless you're screen sharing and talking about the code)

**Comment by the-mikedavis** [comment]
#1967 addressed the configuration part of this.

**Comment by David-Kunz** [comment]
What's still missing in https://github.com/helix-editor/helix/pull/1967 is configuring the features of each gutter (what e.g. `gutter.diagnostic` would allow).

**Comment by pascalkuthe** [comment]
Gutters a re pretty flexible now, this issue is old and too general so I am closing it. If you are missing some specific gutter config open a feature request for that
