### ISSUE TITLE
JSONL highlighting

### ISSUE THREAD

**Issue by FrauElster** [helix-editor/helix#11927]
### Summary

So I found a [PR](https://github.com/helix-editor/helix/pull/11004) in the [Changelog of 24.07.2024](https://github.com/helix-editor/helix/blob/master/CHANGELOG.md) that already implemented it, but my current version 0.157.5 (6192aa14692a24f279888e0b5f781ce204bda57b) does not highlight .jsonl files.

As the mentioned PR somewhat describes, JSONL files should be highlighted like JSON (per line). 
I filed it a bug since it apparently was implemented once but does not work anymore.

### Reproduction Steps

1. write some JSON objects in a test.jsonl file, with each object on one line
2. open it with ZED.

### Platform

macOS

### Terminal Emulator

idk

### Installation Method

brew

### Helix Version

idk

**Comment by TornaxO7** [comment]
I.... don't understand what you would like to report.

> 1. write some JSON objects in a test.jsonl file, with each object on one line
> 2. open it with ZED.

so... you open up the file in ZED and then? Or do you mean `open it with [helix]`?

**Comment by FrauElster** [comment]
I am dumb. Never mind wrong repository. 
Sorry to bother
