### ISSUE TITLE
Support alt/ctrl/shift modifiers in macro-style keybindings

### ISSUE THREAD

**Issue by adamchalmers** [helix-editor/helix#11929]
Macro-style keybindings were added in https://github.com/helix-editor/helix/pull/4709, and I really like them. But I can't figure out how to emit a macro keybinding that presses, say "Alt+o" -- in other keybindings, this is done via "A-o". But I can't use this in macro-style keybindings. For example

```toml
x = "@mi)dA-o"
```

I'd like this to type five keys: "mi)d" then the combined "A-o" i.e. "Alt+o". Instead it treats "A-o" as three separate keys, A then - then o. Is there any way to make a macro-style keybinding emit a modifier+key combination? If not, I think there should be. If so, it should be documented under the [docs](https://docs.helix-editor.com/master/remapping.html) for macro-style keybindings.

**Comment by gabydd** [comment]
Should be ``<A-o>``

**Comment by adamchalmers** [comment]
Thanks, I can open a PR to docs to fix this.
