### ISSUE TITLE
panic: "corsor must be in view"

### ISSUE THREAD

**Issue by brunbjerg** [helix-editor/helix#11926]
### Summary

I sometimes get the error below while working in Helix:

```bash
thread 'main' panicked at helix-term/src/ui/completion.rs:457:14:
cursor must be in view
stack backtrace:
   0: rust_begin_unwind
   1: core::panicking::panic_fmt
   2: core::option::expect_failed
   3: <helix_term::ui::completion::Completion as helix_term::compositor::Component>::render
   4: <helix_term::ui::editor::EditorView as helix_term::compositor::Component>::render
   5: helix_term::application::Application::render::{{closure}}
   6: hx::main_impl::{{closure}}
   7: tokio::runtime::park::CachedParkThread::block_on
   8: tokio::runtime::context::runtime::enter_runtime
   9: tokio::runtime::runtime::Runtime::block_on
  10: hx::main
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
```

### Reproduction Steps

I cannot yet tell exactly what causes it happen. 

I have noticed it frequently occurs when I switch terminals in either tmux or zellij. 

### Helix log

Not available

### Platform

Linux

### Terminal Emulator

Windows Terminal (WSL)

### Installation Method

flake (nixpkgs unstable)

### Helix Version

helix 24.7 (079f5442)

**Comment by rwakulszowa** [comment]
Looks like it's been fixed in https://github.com/helix-editor/helix/commit/3abc07a79e6ddd6a146977648031a9322492f445
I guess you just have to wait for the next release.

**Comment by brunbjerg** [comment]
Perfect! Thank you
