### ISSUE TITLE
General LSP Question for HTML - Code completion is missing (perhaps)

### ISSUE THREAD

**Issue by maitrenageur** [helix-editor/helix#11938]
Hello,

I have installed the LSP `vscode-langservers-extracted` and placed the following lines into `~/.config/helix/language.toml` file:

~~~~
[language-server]
vscode-html-language-server = { command = "vscode-html-language-server", args = ["--stdio"], config = { provideFormatter = true } }

[[language]]
name = "html"
scope = "text.html.basic"
injection-regex = "html"
file-types = ["html", "htm", "shtml", "xhtml", "xht", "jsp", "asp", "aspx", "jshtm", "volt", "rhtml"]
block-comment-tokens = { start = "<!--", end = "-->" }
language-servers = [ "vscode-html-language-server" ]
auto-format = true
indent = { tab-width = 4, unit = " " }
~~~~

The command `hx --health` shows, that html is supported with a green arrow.

My expectation is:
1. If I start to write for example `div` and hit the tab key, that LSP expand it to `<div></div>`.
2. Or if I have a mistake with <di>, that I will get an error message or a hint in front the line.
3. Or a hint in case of a missing clothing tag.

But nothing happen!?

How can I check, that the LSP for HTML is really running, or do I have a wrong understanding about the code completion by Helix?

**Comment by David-Else** [comment]
You don't need to add any lines to your config, `vscode-html-language-server` is the default, you only need to install it.

If you write `<div>` then start the closing tag with `</` it will suggest the auto complete of `</div>` for you, press TAB or CTRL N to select it.

![image](https://github.com/user-attachments/assets/eb1e2d8e-9642-4e52-85cf-ab6f636a7a92)

**Comment by maitrenageur** [comment]
@David-Else Thank you for your explanation.
Yes, it runs. But to be honest a really support is it not for me. But at least I have the certainty that LSP works.
