### ISSUE TITLE
Multi file support and copy and past

### ISSUE THREAD

**Issue by YummyOreo** [helix-editor/helix#1195]
Make it so you can open a dir, and you can switch between files.

Copy, past, cut, ect.

**Comment by archseer** [comment]
There's already a built in file picker? `space+f`

We also support split views and open buffers.

**Comment by YummyOreo** [comment]
Ok, thanks, I'll try this.
Anything on copy and past

**Comment by archseer** [comment]
It's all built-in. I recommend you take a look at [the keymap](https://docs.helix-editor.com/keymap.html) and the [tutorial](https://github.com/helix-editor/helix/blob/master/runtime/tutor.txt).
