### ISSUE TITLE
Helix changes hard links inode on Linux

### ISSUE THREAD

**Issue by kemelzaidan** [helix-editor/helix#11962]
### Summary

I realize that helix changes inode of hard link files on Linux, which is a behavior that does no happen with vim, for example.

### Reproduction Steps

Type the following steps to reproduce:

```sh
$ echo "hello world" > foo
$ cp foo bar
$ ls -li
total 8
381 -rw-r--r-- 1 kemel kemel 12 out 29 15:07 bar
380 -rw-r--r-- 1 kemel kemel 12 out 29 15:07 foo
$ ln foo baz
$ ls -li
total 12
381 -rw-r--r-- 1 kemel kemel 12 out 29 15:07 bar
380 -rw-r--r-- 2 kemel kemel 12 out 29 15:07 baz
380 -rw-r--r-- 2 kemel kemel 12 out 29 15:07 foo
$ cat foo bar baz
hello world
hello world
hello world
$ echo "changed baz" > baz
$ cat foo bar baz
changed baz
hello world
changed baz
```

You see that unlike the copied file, the hard linked `baz` file has the same inode number as `foo` and changing the content of the link does not change the inode number of both files.

```sh
ls -li                                                                                                                   ter 29 out 2024 15:14:19
total 12
381 -rw-r--r-- 1 kemel kemel 12 out 29 15:07 bar
380 -rw-r--r-- 2 kemel kemel 12 out 29 15:14 baz
380 -rw-r--r-- 2 kemel kemel 12 out 29 15:14 foo
```

Now use helix to edit the baz file and save it. I changed the content to "changed baz again".

```sh
$ hx baz
$ cat foo bar baz
changed baz
hello world
changed baz again
$ ls -li
total 12
381 -rw-r--r-- 1 kemel kemel 12 out 29 15:07 bar
428 -rw-r--r-- 1 kemel kemel 18 out 29 15:18 baz
380 -rw-r--r-- 1 kemel kemel 12 out 29 15:14 foo
```
You can see the content of the files are different and the inode number of baz have been changed from 380 to 428 (in my computer). If you repeat this test with vim, for example, you'll see both foo and baz contents will be updated and the inode number of the file will be preserved.

That's what I'll do next:

```sh
$ rm baz
$ cat foo bar
changed baz
hello world
$ ln foo baz
$vim foo
$ cat foo
changed foo
$ cat foo bar baz
changed foo
hello world
changed foo
$ ls -li
total 12
381 -rw-r--r-- 1 kemel kemel 12 out 29 15:07 bar
380 -rw-r--r-- 2 kemel kemel 12 out 29 15:24 baz
380 -rw-r--r-- 2 kemel kemel 12 out 29 15:24 foo
```

### Platform

Linux

### Terminal Emulator

wezterm 20240203-110809-5046fc22

### Installation Method

Archlinux repository

### Helix Version

helix 24.7

**Comment by kirawi** [comment]
This should be fixed on master https://github.com/helix-editor/helix/issues/11279
