### ISSUE TITLE
Support better embedded code in rustdoc

### ISSUE THREAD

**Issue by adsnaider** [helix-editor/helix#11974]
Apologies if this has been opened before, I haven't been able to find this.

# Request

There's little editor support when writing rustdoc comments that specifically embed Rust doctests.

# Wanted Features

1. Continue  the `///` block on new line insert (this is just generally useful for normal comments as well)
2. Ideally figure out the right indentation level based on the code block written
3. Add syntax highlighting

**Comment by the-mikedavis** [comment]
Point 1 was merged the other day in https://github.com/helix-editor/helix/pull/10996 - `<ret>` in insert mode or `o`/`O` in normal mode continue line comments, choosing regular comments or doc comments based on the line being extended. https://github.com/helix-editor/helix/pull/11742 was also merged after the latest release and is a nice QoL improvement for (doc) comments.

2 is covered by the indents bullet in https://github.com/helix-editor/helix/issues/9425. That would need to build off a change to highlight doc comments as markdown: https://github.com/helix-editor/helix/issues/3391. I'll close this in favor of the existing issues
