### ISSUE TITLE
Vite sometimes fails to detect file changes

### ISSUE THREAD

**Issue by aster-void** [helix-editor/helix#11998]
### Summary

Vite sometimes fails to detect file changes.

I suspect the cause is that helix doesn't write to the file directly, but creates a .bck file then rename* it to the original filename. (see `helix-view/src/document.rs :973`)

### Reproduction Steps

 

I tried this:

1. start vite dev
2. change src file

I expected this to happen:
Vite should always respond to file change

Instead, this happened:
Sometimes it fails to detect change

### Helix log

replaying this didn't append anything to the log.

I tested file watching in Chokidar (a file watcher Vite uses), hope this log helps
<details>
<summary> command log of `bun example.js` in chokidar repo</summary>

```
addDir .
add tsconfig.esm.json
add tsconfig.json
add package-lock.json
add README.md
add test.mjs
add .prettierrc.json
add example.js
add handler.js
add package.json
add index.js
add index.d.ts
add handler.d.ts
add LICENSE
addDir src
addDir esm
add src/index.ts
add src/handler.ts
add esm/handler.js
add esm/package.json
add esm/index.js
add esm/index.d.ts
add esm/handler.d.ts
Ready
add SAMPLE
change SAMPLE
add SAMPLEJWqY7G.bck
unlink SAMPLEJWqY7G.bck
add SAMPLEz6r1Sp.bck
unlink SAMPLEz6r1Sp.bck
add SAMPLEFp3gGe.bck
unlink SAMPLEFp3gGe.bck
```
</details>

### Platform

NixOS on WSL

### Terminal Emulator

"Terminal"

### Installation Method

nixpkgs

### Helix Version

helix 24.7 (079f5442)

**Comment by David-Else** [comment]
I had a similar issue with Hugo and submitted a patch for Hugo to fix it, here are the details: https://github.com/gohugoio/hugo/issues/12677

**Comment by aster-void** [comment]
apparently it's file watcher's responsibility to ignore those swap files, thanks! :)

https://github.com/paulmillr/chokidar/pull/1384
