### ISSUE TITLE
respond to terminal paging events?

### ISSUE THREAD

**Issue by KiaraGrouwstra** [helix-editor/helix#12063]
hi there,
i was using keybinds for PageUp-/PageDown-like actions in both helix (`page_up` / `page_down`) as well as my terminal wezterm.
for consistency (+ scarcity of ergonomic keybinds), i thought it would be nice to be able to share one and the same keybind for these.
in wezterm this used their [scrollback](https://wezfurlong.org/wezterm/scrollback.html) - basically changing the viewport position.

this may be a long shot, but i was wondering, would there be any chance helix might be able to respond to such viewport events, potentially saving the user a keybind?

**Comment by pascalkuthe** [comment]
don't think that is possible. A TUI puts the terminal in raw mode. The scrollback is entirely an terminal emulator side feature and disabled in raw mode
