### ISSUE TITLE
Add support for Zenscript (Crafttweaker)

### ISSUE THREAD

**Issue by Zhaith-Izaliel** [helix-editor/helix#12084]
Zenscript is the language used in combination with Crafttweaker to add scripts to modded Minecraft for every modloaders supported by Crafttweaker. It is (without surprise) supported by both VSCode and Intellij IDEA through an extention, you can find here: https://github.com/raylras/zenscript-intelli-sense

I think it could be a great addition to Helix to add support for this language. However, we will have to create a treesitter grammar. As such, you can find the language documentation here: https://docs.blamejared.com/1.21.1/en/getting_started

From the intellisense plugin, I think we could be able to extract the LSP from there, though I am not sure if it is possible since I'm not versed in Kotlin.

Do you think it's a good addition to Helix ?

If I can find the time, I will try to create the treesitter grammar and try to extract and build the lsp to at least see if it's truly possible to integrate that in Helix, though it will take me a lot of time to figure out the details. If you don't think we should add support for zenscript into upstream helix, I'll try to manage a repository for building your own grammar + building the lsp.

**Comment by kirawi** [comment]
We don't generally include lesser-used languages in Helix to avoid increasing the runtime size for packaging.

**Comment by Zhaith-Izaliel** [comment]
I get it, I'll make the grammar and queries myself then x)
