### ISSUE TITLE
Regression: Unknown field: end-of-line-diagnostics on new macOS install of Helix via brew

### ISSUE THREAD

**Issue by aral** [helix-editor/helix#12099]
### Summary

Copied my Helix config over from old Mac (helix 24.7 (38faf74f)) to new (helix 24.7 (079f5442)) and getting the following error on the new one:

```
Bad config: unknown field `end-of-line-diagnostics`, expected one of `scrolloff`, `scroll-lines`, `mouse`, `shell`, `line-number`, `cursorline`, `cursorcolumn`, `gutters`, `middle-click-paste`, `auto-pairs`, `auto-completion`, `auto-format`, `auto-save`, `text-width`, `idle-timeout`, `completion-timeout`, `preview-completion-insert`, `completion-trigger-len`, `completion-replace`, `auto-info`, `file-picker`, `statusline`, `cursor-shape`, `true-color`, `undercurl`, `search`, `lsp`, `terminal`, `rulers`, `whitespace`, `bufferline`, `indent-guides`, `color-modes`, `soft-wrap`, `workspace-lsp-roots`, `default-line-ending`, `insert-final-newline`, `smart-tab`, `popup-border`, `indent-heuristic`, `jump-label-alphabet`

Press <ENTER> to continue with default config
```

The `end-of-line-diagnostics` setting is under `[editor]`.

### Helix log

n/a

### Platform

macOS

### Terminal Emulator

WezTerm

### Installation Method

brew

### Helix Version

helix 24.7 (079f5442)

**Comment by gabydd** [comment]
The commit you are on is from 4 months ago before inline diagnostics was merged, the previous commit you where using was from 21 days which is why the config worked

**Comment by aral** [comment]
Ah, interesting, so Homebrew has an outdated build.

I thought I’d installed it via Homebrew on the old machine but I guess it’s possible installed it from source afterwards and it was shadowing the brew version (?), which I didn’t uninstall.

Hmm, is it worth opening an issue for the Homebrew being outdated somewhere?

**Comment by gabydd** [comment]
It's not outdated we just haven't put out a new release yet, you probably want the homebrew helix --HEAD version

**Comment by aral** [comment]
Ah, that was exactly what I did :) Sorry – been daily driving it for over a year now (from before it was merged into main) so hadn’t realised it hadn’t been released.
