### ISSUE TITLE
Add inverse repeat_last_motion command

### ISSUE THREAD

**Issue by Aqaao** [helix-editor/helix#12092]
https://github.com/helix-editor/helix/discussions/8495

**Comment by the-mikedavis** [comment]
No need to duplicate the discussion, closing in favor of #8495

**Comment by Aqaao** [comment]
> No need to duplicate the discussion, closing in favor of #8495

Is Helix open to accepting PR for this feature?

**Comment by the-mikedavis** [comment]
I'd be interested in a PR for this. I think I left a comment on an older PR (I can't find the link :/) with a suggestion to refactor the `Motion` type in `helix-view/src/editor.rs` to accept a second parameter `Direction`. That would make adding this command easier

**Comment by willbush** [comment]
> I'd be interested in a PR for this. I think I left a comment on an older PR (I can't find the link :/) with a suggestion to refactor the `Motion` type in `helix-view/src/editor.rs` to accept a second parameter `Direction`. That would make adding this command easier

Think this is the link: https://github.com/helix-editor/helix/issues/8761#issuecomment-1803145453

**Comment by Aqaao** [comment]
> > I'd be interested in a PR for this. I think I left a comment on an older PR (I can't find the link :/) with a suggestion to refactor the `Motion` type in `helix-view/src/editor.rs` to accept a second parameter `Direction`. That would make adding this command easier
> 
> Think this is the link: [#8761 (comment)](https://github.com/helix-editor/helix/issues/8761#issuecomment-1803145453)

I have completed prototype for `inverse_repeat_last_motion` feature, but like this issue, it doesn't handle the switching between selection mode and move mode very well.  I might come back to continue working on this feature after resolving the issue.😪

**Comment by Aqaao** [comment]
If anyone is interested in this feature, they can check out this [fork](https://github.com/Aqaao/helix/tree/reverse_motion).
