### ISSUE TITLE
Should Use Tabs for Makefiles by Default

### ISSUE THREAD

**Issue by enkvadrat** [helix-editor/helix#12112]
### Summary

Helix currently inserts spaces instead of tabs when editing `Makefile` files. This causes errors with `make`, as it requires commands to be indented with tabs.

### Reproduction Steps

1. Open a `Makefile` in Helix and add:
   ```makefile
   all:
       echo "Hello"  # Indented with spaces by default
   ```
2. Save and check indentation using:
   ```bash
   cat -T Makefile
   ```
   - Tabs show as `^I`, spaces are invisible.
3. Run `make`:
   ```bash
   make
   ```
   Observe the error:
   ```
   Makefile:2: *** missing separator.  Stop.
   ```

### Platform

Linux

### Terminal Emulator

st

### Installation Method

pacman

### Helix Version

helix 24.7

**Comment by enkvadrat** [comment]
#12109 maybe be related

**Comment by RoloEdits** [comment]
when I have
```makefile
all:echo "Hello"
```
and then put my cursor before `echo` and press return I get the expected tab.

```makefile
all:
	echo "Hello"
```

When I initially tried to replicate I also got the expected tab.

**Comment by pascalkuthe** [comment]
Helix autodetects indentation when opening an existing file so most likely you opened a makefile that already had spaces in it
