### ISSUE TITLE
Resolving misidentified ".conf" Files

### ISSUE THREAD

**Issue by kfatyuip** [helix-editor/helix#12120]
All the ".conf" files are [misidentfied as hocon](https://github.com/helix-editor/helix/blob/master/languages.toml#L3466)

maybe a stricter distinction method is required like neovim [filetype.lua](https://github.com/neovim/neovim/blob/master/runtime/lua/vim/filetype.lua)

**Comment by David-Else** [comment]
This is a big problem. I have verified it is happening.

I looked at the hocon website and it seems the only valid file type is `.conf`, which was pretty short sighted of them.

I can see only 2 solutions:

1. Remove hocon from Helix. Does anyone use it?
2. Add every possible `x.conf` (for example `kitty.conf`) file as a globs for other file types from https://github.com/neovim/neovim/blob/master/runtime/lua/vim/filetype.lua. I started to look at this file and there is a lot of legacy stuff from vim, I am not sure we would want to just copy things blindly from it. This is not a great solution as `.conf` files are meant to default to text files.

`.conf` files are absolutley everywhere and it is wrong to have Helix assume they are obscure hocon files. They should be defaulting to text files. @jpaju do you have any input, I see you added hocon in https://github.com/helix-editor/helix/pull/9203.  Cheers!

**Comment by jpaju** [comment]
Hocon files are used quite lot in JVM (Scala, Kotlin and Java) projects so removing support for them altogether would be a bummer for someone who mainly works with the JVM. Usually in JVM projects, these `.conf` files are placed in `src/main/resources` folder so maybe we could change the existing language configuration to glob for this path and only match `.conf` files under that folder? How would that sound?

**Comment by David-Else** [comment]
> Usually in JVM projects, these .conf files are placed in src/main/resources folder so maybe we could change the existing language configuration to glob for this path and only match .conf files under that folder? How would that sound?

That sounds perfect! Can you make a PR?

**Comment by jpaju** [comment]
Sure! Hopefully I manage find time for that during the weekend
