### ISSUE TITLE
Extending selections using the jumplist

### ISSUE THREAD

**Issue by kaos** [helix-editor/helix#12125]
Helix have a dedicated (minor) mode for extending the selection(s), the [`selection` mode](https://docs.helix-editor.com/keymap.html#select--extend-mode), which turns regular movements and gotos to not only reposition the cursor, but also extend the selection to this new position.

However, jumping is currently _not_ covered as valid repositioning for extending the selection which I think would be useful to have. (As long as the jump is buffer local, i.e. does not jump to a different buffer.)

In order to work effectively with the selection, having more options on how to manage it would be preferable. 

I first started to look into this when I couldn't use `v/` in order to extend my selection, as that is used to add search hits to the selection (with another cursor) rather than extending the current selection.

To solve this, I tried `c-s` to save my current position to the jumplist. Then after searching, `vc-o` to enter selection mode and jumping out to my saved position in the jumplist. Alas, jumps don't extend the selection. (yet?)

This is my primary motivating use case, but I'm sure there a numerous other ways to jump, that could also benefit from being used to extend the selection rather than only moving the cursor. (but only when performed in the `selection` mode.)

N.b. `vgw??` (where `??` is a two-letter label presented in-buffer after hitting `gw`) allows you to go to any labeled point on the current page, which is easily overlooked and quite powerful, but is limited to what is currently in view.

**Comment by kaos** [comment]
(Semi-)Related issues..

There are quite a few open issues relating to the topic of repositioning and selection (the ones I could find with a quick search):

* #1630 -- I think this could be closed, as it works as intended.
* #1570 -- I think this could be closed, as it breaks consistency (`3w` would not be the same as `www`.)
* #5127 -- I think this could be closed, as it works as intended.
* #5672 -- Slightly confused what the proposal is here, and how it would work without being inconsistent/unintuitive.

This https://github.com/helix-editor/helix/issues/165#issuecomment-856591403 highlights the design intent with the selection mode pretty well.

Given the above, I actually find it inconsistent that `w`, `e`, and `b` (and their upper case counterparts) extends the selection in `normal` mode and not just repositions the cursor.

**Comment by the-mikedavis** [comment]
This is the use-case for marks https://github.com/helix-editor/helix/issues/703, closing in favor of that. With marks you can save a selection to a register and then join it to your current selection.
