### ISSUE TITLE
match inside should ignore escaped characters

### ISSUE THREAD

**Issue by jesper-olsen** [helix-editor/helix#12130]
Given this line
`    let s: &str = "Should you get stuck, type \"HELP\" for some general hints." `
If we position the cursor on "get" and type mi" (match inside), my expectation is that helix should select the whole string, ie.
`     Should you get stuck, type \"HELP\" for some general hints.`
what it actually selects is
`    Should you get stuck, type \`

**Comment by woojiq** [comment]
No, why should `mi"` ignore escape characters when you are actually saying "match inside the closest quotes". For intelligent mode (tree-sitter) you should use `mim`. As a workaround use `A-o`.

**Comment by jesper-olsen** [comment]
You can't select the match character with mim - but it does solve my immediate problem (strings in rust), so going to close this one.

**Comment by kirawi** [comment]
`mam` will select quotes I believe.
