### ISSUE TITLE
Add ability to use a specified config/theme

### ISSUE THREAD

**Issue by tmforshaw** [helix-editor/helix#1216]
I'd like to be able to use helix as root user but still keep my config and theme.

In vim you can [pass a config file](https://unix.stackexchange.com/questions/46699/start-vim-as-my-user-with-root-privileges) using the `-u` flag

``` bash
sudo vim -u /home/user/.vimrc /path/to/file.txt
```

Maybe helix could accept a `-c` flag so that any config file can be used.

``` bash
sudo hx -c /home/user/.config/helix/config.toml /path/to/file.txt
```

Thanks for reading :)

**Comment by sudormrfbin** [comment]
For your specific usecase the recommended way would be to use [`sudoedit` after setting `$EDITOR`](https://stackoverflow.com/questions/21488357/use-sudo-with-vimrc) to `hx`.

**Comment by tmforshaw** [comment]
I saw that I could do that, but I don't have sudo installed on my system as I use doas.

If this is the solution then I will use it for now, but I still think this would be a nice feature in the future.

Thanks for your reply

**Comment by NNBnh** [comment]
Good new! [`doasedit`](https://aur.archlinux.org/packages/doasedit) exist.

**Comment by tmforshaw** [comment]
Ah wow, that is good news!

Thanks a lot

**Comment by the-mikedavis** [comment]
The new configuration in https://github.com/helix-editor/helix/pull/2135 should help make this easier to implement: we can have a single switch for the config file and then the config file can point to other configuration files and directories.

**Comment by yuuyins** [comment]
i don't use helix as my primary editor i can't set it to $EDITOR. so having the option --config path/to/config is pretty useful

**Comment by sudormrfbin** [comment]
@yuuyins You could also set [`$SUDO_EDITOR`][1] instead of `$EDITOR`. This doesn't help if you want to use another editor and helix interchangeably with `sudo` though.

[1]: https://www.mankier.com/8/sudo#--edit

**Comment by yuuyins** [comment]
@sudormrfbin that worked thank you!
