### ISSUE TITLE
Incorrect behaviour for adding newline before a line with a comment on it

### ISSUE THREAD

**Issue by NikitaRevenco** [helix-editor/helix#12165]
## Example 1

If you have a comment and your cursor is at |:

```rs
/// this is a comme|nt
```

Pressing `I` then `Enter` will have this effect:

```rs
/// |/// this is a comment
```

While this was expected:

```rs
<newline>
|/// this is a comment
```

## Example 2

Also, if you have that same comment *at the top of the file*:

```rs
/// this is a comm|ent
```

Pressing `O` will have this effect:

```rs
<newline>
/// | /// this is a comment
```

While this was expected

```rs
/// |
/// this is a comment
```

**Comment by TornaxO7** [comment]
Ooof, I think this is introduced from my PR ;-; https://github.com/helix-editor/helix/pull/10996 I can try to create a follow PR for this but currently it's a bit full for me but I can add a fix until the end of next week I think
