### ISSUE TITLE
Links break when URLs wrap

### ISSUE THREAD

**Issue by CubeGame** [helix-editor/helix#12179]
### Summary

When soft wrap is enabled and clickable URLs get wrapped around, their links are split up,
for example consider `[some link](https://example.com/something)` got wrapped around with `something` on a newline, the first part would only go to `https://example.com/` and `something` wouldn't be recognized as a link, or in the case of URLs like with the Wayback machine, if separated then both URLs would go to separate places.

### Reproduction Steps

Type in a URL and have soft-wrap enabled, make the URL be wrapped around to a newline, and test clicking on the links.

### Platform

Linux

### Terminal Emulator

Ptyxis 47.5

### Installation Method

dnf

### Helix Version

helix 24.7 (079f5442)

**Comment by pascalkuthe** [comment]
Nothing we can do about this. This is a fundamental limitation of links in terminals. Your sn use `gf` to open the url instead.

**Comment by benjamb** [comment]
> Nothing we can do about this.

I don't know if this is true, it seems implenting OSC-8 would be an appropriate solution to the problem: https://github.com/helix-editor/helix/issues/14076
