### ISSUE TITLE
Local configuration folder

### ISSUE THREAD

**Issue by jdrouet** [helix-editor/helix#1217]
Hi everyone!
First, thank you for that amazing work!

#### Describe your feature request

I'm working on a big [codebase](https://github.com/vectordotdev/vector) that takes several minutes to build. So I've to disable features in order to make it run faster.
I can do that by passing arguments to `rust-analyzer` in the `languages.toml` config file.
The problem is that it applies for every helix instances.

I'd love to have a `.helix` folder in the project folder with a `languages.toml` file in it to disable features only for the current project.

**Comment by hemedani** [comment]
also, it's good for disabling the typescript language server and enabling deno lsp on deno project.

please document this feature for deno and typescript.
