### ISSUE TITLE
`delete_selection_to_clipboard` command

### ISSUE THREAD

**Issue by NikitaRevenco** [helix-editor/helix#12187]
We have `yank_to_clipboard`, `paste_clipboard_after`, `paste_clipboard_before`, `replace_selections_with_clipboard` but there isn't an alternative for delete. What I'm currently doing to mimic is this:

```nix
          d = [
            "yank_to_clipboard"
            "delete_selection_noyank"
          ];
```

- This isn't ideal because when I delete text it says "Yanked 1 selection to register +" when it would be better if it told me the usual deletion text
- it's better for consistency

This command should just exist, it doesn't need to be mapped by default

**Comment by pascalkuthe** [comment]
https://github.com/helix-editor/helix/pull/12198#issuecomment-2525301829
