### ISSUE TITLE
Consistent naming convention for themes

### ISSUE THREAD

**Issue by NikitaRevenco** [helix-editor/helix#12201]
Some themes are in train-case, while others are in snake_case. I propose to rename all of them to be in train-case, since the typed commands are also in train-case

![image](https://github.com/user-attachments/assets/175f5e1a-3148-47f7-8bc3-49400fcacbdc)

**Comment by the-mikedavis** [comment]
See https://github.com/helix-editor/helix/pull/6561#issuecomment-1493418844

There isn't really any downside to the inconsistency and renaming themes would be a breaking change for any users of a renamed theme
