### ISSUE TITLE
Add keystrokes in macro?

### ISSUE THREAD

**Issue by nednoodlehead** [helix-editor/helix#12209]
Apologies if this exists, I did not find much when searching.

In my config, I can set these macros:
9 = ["select_all", "delete_selection", "paste_clipboard_before"]

However, it does not seem possible to add keystrokes into the macro, for example, if I want to select all instances of "example", I would want to change it to:
9 = ["select_all", "delete_selection", "paste_clipboard_before", "search", "example"]

(keep in mind that paste_clipboard_before has the whole document selected
Now, this fails because "example" is not a command, which makes sense. But is there some way to escape it? Or specify that the next letters are to be inputted and not interpreted as a command?

**Comment by gabydd** [comment]
This can be done with macro keybindings: https://github.com/helix-editor/helix/pull/4709 was merged after the last release so you will have to be using master to use them
