### ISSUE TITLE
add rose_pine_dawn theme

### ISSUE THREAD

**Issue by chunghha** [helix-editor/helix#1227]
Opened https://github.com/helix-editor/helix/pull/1226 to add rose_pine_dawn theme and fix ui.statusline.inactive colors of rose_pine theme.

**Comment by archseer** [comment]
Closed by #1226

**Comment by kirawi** [comment]
Could you add this to https://github.com/helix-editor/helix/wiki/Themes?

**Comment by chunghha** [comment]
@kirawi done.
