### ISSUE TITLE
File Picker is slow for large projects

### ISSUE THREAD

**Issue by yuvaldolev** [helix-editor/helix#1233]
### Reproduction steps

Open a large project's root directory (I used the Rust compiler).
Press `Space + f` to open the File Picker window.
Window shows up after a rather long delay on my machine: ~3 seconds.
In addition, characters are rendered slowly when typed into the picker's search bar.

### Environment

- Platform: macOS
- Helix version: 0.5.0

**Comment by pickfire** [comment]
Currently things are done in asynchronous manner and without batch, might have to write it to do the way ripgrep and skim does, shouldn't block until everything is there.

**Comment by gilescope** [comment]
Speedy on linux when opening the rust compiler. Maybe OS specific?

**Comment by antoyo** [comment]
I don't think it's OS specific.
It takes approximately 2 seconds to show the files in the Rust compiler on Linux with a NVMe SSD and a Ryzen 3900x, which is a bit slow (it's slower than fzf-vim which is near instant, though I believe it behaves differently than the file picker in Helix in that it seems to print the files as soon as they are fetched while Helix seems to wait to have them all before showing them).

**Comment by sudormrfbin** [comment]
Closing this in favor of #1707 which has more updates on the progress of this issue.
