### ISSUE TITLE
Syntax highlighting in the preview pane is laggy when scrolling through files

### ISSUE THREAD

**Issue by python-pk** [helix-editor/helix#12350]
### Summary

When using the file picker in Helix, the preview pane shows significant lag in syntax highlighting when scrolling through files that require syntax highlighting, such as .toml, .rs, and other source files. This behavior impacts usability as the highlighting takes noticeable time to render, causing the UI to feel slow.

![WindowsTerminal_20241227_175059_127](https://github.com/user-attachments/assets/a26073bd-2166-435c-b7eb-8d5f75b70488)

### Reproduction Steps

 

I tried this:

1. Open Helix.
2. Trigger the file picker.
3. Scroll through files with syntax highlighting (e.g., .toml, .rs).
4. Observe the preview pane – the syntax highlighting lags and does not render smoothly.

I expected this to happen:

Immediate rendering with syntax highlighting without any delay.

Instead, this happened:
See point 4.

### Helix log

N/A

</details>

### Platform

Windows

### Terminal Emulator

pwsh.exe (Powershell 7.4.6)

### Installation Method

releases page

### Helix Version

helix 24.7 (079f5442)

**Comment by the-mikedavis** [comment]
The highlighting in the preview is intentionally debounced to avoid wasting resources and making the picker lag when scrolling through options quickly

**Comment by python-pk** [comment]
There is no necessary trade off there. If you compare the with the plugin called telescope in neovim you will see that the whole thing can work extremely fast. 

This is an example from telescope in neovim. There is absolutely no lag. Both picker and preview work very fast.

![WindowsTerminal_20241228_212609_130](https://github.com/user-attachments/assets/f65a69f1-d47b-436d-94b1-afd330417d22)

**Comment by the-mikedavis** [comment]
It is generally quite fast to highlight but it's very wasteful to parse and highlight every options when scrolling through options quickly

**Comment by python-pk** [comment]
I understand.. Thanks.
