### ISSUE TITLE
assertion failed: self.is_char_boundary(n)

### ISSUE THREAD

**Issue by anzhi0708** [helix-editor/helix#1246]
### Reproduction steps

 
I was using a non-default theme.
When I tried to change it back to `default` by typing `:theme `, helix crashed.

Before this happened, I clicked UP / DOWN arrow key 2 to 3 times cuz I forgot that I have to use `TAB` key to switch between options.

~/.cache/helix/helix.log was EMPTY but I do have some screenshots

![image](https://user-images.githubusercontent.com/57821133/145354409-d2ce374e-1d85-4bb8-a550-f242075d1ed1.png)

![image](https://user-images.githubusercontent.com/57821133/145354281-078f86de-0658-431e-b32d-87ab81c7ec07.png)

### Environment

- Platform:  Termux (Android)
- Helix version:  0.5.0

**Comment by archseer** [comment]
Can you produce a full backtrace by running `RUST_BACKTRACE=full`?

**Comment by anzhi0708** [comment]
> Can you produce a full backtrace by running `RUST_BACKTRACE=full`?

I have set it to `full` now. Did not know this before. I’ll try to reproduce the crash and update this issue. Thanks for reply

**Comment by the-mikedavis** [comment]
Let's close this out in favor of #1888 which has more discussion.
