### ISSUE TITLE
Hover page up down hint

### ISSUE THREAD

**Issue by pickfire** [helix-editor/helix#1248]
Currently when hover, there is a box. It can be scrolled down but there are two issues

- it is not cleared when it can be scroll up or down
- it is not discoverable for new users that ctrl-u and ctrl-d is used to scroll the hover box

One idea I have is that we draw `ctrl-u` text if it can be scrolled up and `ctrl-d` text if it can be scrolled down along the border of the box, that way we can reuse the existing border space while making it clear to users when it can be scrolled as well as being beginner friendly. Example,

```
+--------------------+
| ...                |
+------------ ctrl-d +

**Comment by archseer** [comment]
We can just render a scrollbar, like we do for the menu.

**Comment by pickfire** [comment]
We can render a scrollbar but user is likely to not know how to scroll up and down. Not sure about the rest but I don't know about the key to scroll until I saw someone mentioned it.

**Comment by archseer** [comment]
> We can render a scrollbar but user is likely to not know how to scroll up and down. Not sure about the rest but I don't know about the key to scroll until I saw someone mentioned it.

I think it's predictable since we also use those keys in the picker, but we don't point them out anywhere except in the docs. Or how `i` enters insert mode, but there's no documentation text on screen in normal mode to point that out :P 

A scrollbar would make it at least a bit more obvious that scrolling is possible.


> We could show a line `Ctrl-d to scroll down, Ctrl-u to scroll up` in the status message area (similar to `Recording to {register}` message shown when recording a macro).

Yeah that could work

**Comment by Jlll1** [comment]
> > We could show a line `Ctrl-d to scroll down, Ctrl-u to scroll up` in the status message area (similar to `Recording to {register}` message shown when recording a macro).
> 
> Yeah that could work

So, do we want to do that? I think a scrollbar would be sufficient.

**Comment by sheyll** [comment]
> > > We could show a line `Ctrl-d to scroll down, Ctrl-u to scroll up` in the status message area (similar to `Recording to {register}` message shown when recording a macro).
> > 
> > 
> > Yeah that could work
> 
> So, do we want to do that? I think a scrollbar would be sufficient.

As a new Helix user I would really prefer at least the status area message.

But broadening the scope a bit: Helix seems to have this UX idiom of showing pop-ups guiding the user.

For example when pressing `Space` a pop-up appears with what keys a user can now press to complete a command sequence. 

That is really helpful for me. It would be nice if additionally hints like the keys to scroll the pop-up could be displayed in a dedicated message area distinct from the actual message area, which might contain other, more useful information. 

A separate guide/hint area could also be made configurable, so experienced users can disable them.

**Comment by sheyll** [comment]
... also this could be solved by a bunch of "Did You Know?" style hint message displayed in the message area on start-up.

**Comment by pickfire** [comment]
> ... also this could be solved by a bunch of "Did You Know?" style hint message displayed in the message area on start-up.

That works but it gets heavier and heavier to the point that no one reads it next time, something like infobox which shows up where it needs to be is better.

**Comment by willparsons** [comment]
> Maybe we can hide it under a beginner flag
I like the idea of an opt-out extra info system that would help users learn the keybinds, then they can disable this feature when they don't need it anymore.
