### ISSUE TITLE
Optionally show vertical indentation block lines

### ISSUE THREAD

**Issue by sdroege** [helix-editor/helix#1257]
The behaviour would be similar to the vim indentLine plugin, see screenshots here: https://github.com/Yggdroot/indentLine#screenshots

Having this makes it easier to navigate code with small indentation levels (e.g. 2 spaces) and deep indentation.

**Comment by sudormrfbin** [comment]
This is on my todo after #417 is merged :)

**Comment by unrelentingtech** [comment]
Looks like this is #1796 now.

**Comment by sdroege** [comment]
Yes that's exactly what I was thinking of, nice!
