### ISSUE TITLE
Feature Request: Support text alignment based on custom delimiters

### ISSUE THREAD

**Issue by abhigupta912** [helix-editor/helix#1259]
There seems to be support for text alignment in columns as per the following:
https://docs.helix-editor.com/keymap.html?highlight=align#selection-manipulation

However, it would be nice to have a standard way of having text alignment similar to the following:
https://github.com/kg8m/vim-simple-align
https://github.com/RRethy/nvim-align
https://github.com/junegunn/vim-easy-align

**Comment by archseer** [comment]
You can pass a count to left/center/right align: https://github.com/helix-editor/helix/blob/master/helix-term/src/commands.rs#L745-L750

I'm not sure if we should add anything more complicated than that.

**Comment by sudormrfbin** [comment]
I think aligning lines similar to the vim plugins mentioned is already possible with `&`, but the usage is a bit confusing (I've still not figured it out completely) and takes more steps.

**Comment by pascalkuthe** [comment]
This is actually easily possible with multiple cursors. Simply select your match with `s` and hit`&`.

The example in the linked plugin works easily with `%s=&`. We probably just forgot about this issue so I am closing it as it's already possible to achieve this in helix without an additional feature.
