### ISSUE TITLE
Implementing `workspace/configuration`

### ISSUE THREAD

**Issue by nangtrongvuon** [helix-editor/helix#1268]
Some LSP servers such as [the Dart LSP server](https://github.com/dart-lang/sdk/blob/master/pkg/analysis_server/tool/lsp_spec/README.md) requests settings with `workspace/configuration`. Currently there is no way to pass in such settings since helix does not support this yet.

Implementing `workspace/configuration` (and `workspace/didChangeConfiguration`) will allow more LSP settings and changing settings on the fly without restarting the server.

**Comment by kevinsjoberg** [comment]
I stumbled across this as well while integrating the [HTML language server](https://github.com/microsoft/vscode-html-languageservice) with Helix. I managed to get the language server running, but I couldn't enable formatting as it expects me to set `html.format.enable` to `true`. All configuration is done through the [Configuration Request](https://microsoft.github.io/language-server-protocol/specifications/specification-current/#workspace_configuration).

For the HTML language server specifically, there's a lot of configuration available as can be seen [here](https://github.com/sublimelsp/LSP-html/blob/8c4c39fdb7f925e8cca2b263ac2a3ebf3d83ab23/LSP-html.sublime-settings#L12-L123).
