### ISSUE TITLE
Helix hangs when attemtpting to open a Zig file. 

### ISSUE THREAD

**Issue by paoda** [helix-editor/helix#1269]
### Reproduction steps

[![asciicast](https://asciinema.org/a/aG75CICdAxtRhsYFVNu2OQu6P.svg)](https://asciinema.org/a/aG75CICdAxtRhsYFVNu2OQu6P)

### Environment

- Platform: Linux 5.15.7-arch1-1 x86_64 GNU/Linux
- Helix version: helix v0.5.0-235-g94535fa0
- Zig version: 0.9.0-dev.1952+5d1aab72d
- ZLS version: 0.2.0

### Note
I tried having `~./config/helix/languages.toml` contain the following:
```toml
[[language]]
name = "zig"
language-server = {}
```
Surprisingly, Helix still hung when trying to open `src/main.zig`

What Helix was trying to open can be found [here](https://git.musuka.dev/paoda/zig8/src/branch/main/src/main.zig)

`~/.cache/helix/helix.log` is not written to at any point.

**Comment by archseer** [comment]
Looks like https://github.com/maxxnino/tree-sitter-zig/issues/8

**Comment by paoda** [comment]
I tried updating tree-sitter-zig to https://github.com/maxxnino/tree-sitter-zig/commit/cf93353d5682c3e9d8112d448ff24d4de7b2304e which you can see here: https://github.com/paoda/helix/commit/fddcd85d287c71516bb28e2b4f4d5bbf7ba17c45

However, it seems like the upstream issue hasn't been resolved quite yet. 
[![asciicast](https://asciinema.org/a/mOrkD4eL4bKllTKb3oL7b5mLE.svg)](https://asciinema.org/a/mOrkD4eL4bKllTKb3oL7b5mLE)

**Comment by archseer** [comment]
Oh, I'm suggesting you upgrade tree-sitter itself (not the grammar) so that it includes this commit: https://github.com/tree-sitter/tree-sitter/commit/25f64e1eb66bb1ab3eccd4f0b7da543005f3ba79

**Comment by paoda** [comment]
Whoops, my bad. Bumping `tree-sitter` in `helix-core` and `helix-syntax` worked. Thanks for the clarification.

**Comment by archseer** [comment]
So the fix worked? :)
