### ISSUE TITLE
Using `O` on the first line does not move the cursor

### ISSUE THREAD

**Issue by kevinsjoberg** [helix-editor/helix#127]
If you're on the first line in a file and press `O`, it inserts the newline correctly above the current one, but does not move the cursor accordingly.

**Comment by sudormrfbin** [comment]
`o` also seems to work incorrectly when there are multiple cursors:

![command](https://user-images.githubusercontent.com/23398472/122161980-5d3fb200-ce90-11eb-84d7-6758e575f66b.gif)
