### ISSUE TITLE
File navigation history stack

### ISSUE THREAD

**Issue by simonkampe** [helix-editor/helix#1275]
Hi,

I often navigate through code using the LSP goto definition/reference, but I would also like an easy way to navigate back through several files. So I suggest to implement a stack of sorts to keep track of which files was navigated through.

This way one could navigate through several files with e.g. goto_definition and then back through the stack one file at a time (like goto_last_accessed_file but instead of alternating it pops the stack).

I could take a crack at implementing it myself if it seems like a good feature.

**Comment by archseer** [comment]
We track view jumps and they're navigatable via ctrl-i/ctrl-o

**Comment by simonkampe** [comment]
> We track view jumps and they're navigatable via ctrl-i/ctrl-o

Ah, that's what I was looking for. Thank you!

**Comment by pickfire** [comment]
> This way one could navigate through several files with e.g. goto_definition and then back through the stack one file at a time (like goto_last_accessed_file but instead of alternating it pops the stack).

Maybe goto_last_modified file might be useful for you?
