### ISSUE TITLE
Is markdown syntax highlight supposed to be working ? 

### ISSUE THREAD

**Issue by midnightexigent** [helix-editor/helix#1281]
Hi, I saw that markdown grammar was recently added. I still don't have syntax highlighting for markdown files. Is that normal ?

**Comment by dead10ck** [comment]
I noticed this too. I think the queries add their own markup-specific capture groups, so every theme will have to add new highlights for the new groups like was done for the default theme [here](https://github.com/helix-editor/helix/commit/49e067874133e12d10ad3ac0c941438e2d7025e7#diff-a8920076eb4397a674413ad13dd07ee4e360310f895ea202782659b91483ec1cR31)

**Comment by midnightexigent** [comment]
makes sense, thanks
