### ISSUE TITLE
Better editor support for configurations

### ISSUE THREAD

**Issue by bram209** [helix-editor/helix#1282]
Fortunately, language servers exists supporting JSON Scema (draft 7) so that you get rich editor completions on config files.

It would be nice If we could add the following in order to improve the user experience while editing configuration files:

- [ ] Add json language server https://github.com/vscode-langservers/vscode-json-languageserver/
- [ ] Add yaml language server https://github.com/redhat-developer/yaml-language-server
- [ ] Add toml language server https://taplo.tamasfe.dev/lsp/#usage
- [ ] (extra) Experiment with json schema generation for Helix config https://github.com/GREsau/schemars
- [ ] (extra) Experiment with pulling in schemas of LSP settings, to enable autocompletion of LSP configuration in `languages.toml`, similar to https://github.com/tamago324/nlsp-settings.nvim

**Comment by kirawi** [comment]
Completed with the exception of the latter two, for which there seems to be a lack of interest.
