### ISSUE TITLE
Locale-independent keybinds

### ISSUE THREAD

**Issue by eugenesvk** [helix-editor/helix#1301]
Current keybinds depend on your keyboard layout, e.g. `C-s=":w"` only works for latin `s`, but fails when you change keyboard layout to something else
I'd like to be able to set keybinds in a locale-independent way, for example, via a virtual key code
`C-vk53=":w"  #comment: vk53 = physical key with latin s`
(scan codes are another alternative, though they are hardware-dependent, so potentially worse?)

**Comment by archseer** [comment]
Duplicate of https://github.com/helix-editor/helix/issues/133
