### ISSUE TITLE
hx wrapper clashes with hx cargo crate

### ISSUE THREAD

**Issue by almereyda** [helix-editor/helix#1305]
In my system, I have installed the hx cargo crate.

- https://crates.io/crates/hx
- https://github.com/sitkevij/hex

Its binary takes precedence over the hx wrapper provided by the installable package.

Is there a way to assign another name to the binary during build, e.g. `helix`? Then choosing an abbreviated version remains as simple as creating a symlink.

**Comment by almereyda** [comment]
Also see https://github.com/sitkevij/hex/issues/66

**Comment by kirawi** [comment]
#344

**Comment by kirawi** [comment]
You'll probably have to edit this: https://github.com/helix-editor/helix/blob/master/helix-term/Cargo.toml#L20-L22
