### ISSUE TITLE
Panic when trying to insert suggestion from pyright LSP for python

### ISSUE THREAD

**Issue by thomkeh** [helix-editor/helix#131]
I configured helix to use the (pretty popular) [pyright LSP from Microsoft](https://github.com/microsoft/pyright) for Python:

```toml
language-server = { command = "pyright-langserver", args = ["--stdio"] }
```

And it works pretty well in terms of pointing out errors and making suggestions, but when I want to accept a suggestion from the autocomplete by pressing enter, helix panics:

```
thread 'main' panicked at 'not implemented', helix-term/src/ui/completion.rs:121:25
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

And the error is no mystery, as that functionality just doesn't seem to be implemented yet: https://github.com/helix-editor/helix/blob/c5c3ec07f4089d831c88b3edd58bc2b6e8872a72/helix-term/src/ui/completion.rs#L121

I also tried it out with rust and the rust-analyzer LSP and I encounter no problem there. So it must be a difference in the LSP communication.

(I believe this issue is separate from #33 where the LSP gives an error immediately.)

**Comment by archseer** [comment]
I think I added that `unimplemented` there because I wasn't sure if the behavior was correct, and didn't have any LSP I could test against. Would you be willing to give it a shot?

This block:
https://github.com/helix-editor/helix/blob/c5c3ec07f4089d831c88b3edd58bc2b6e8872a72/helix-term/src/ui/completion.rs#L111-L142

To something like this:

```rust
// if more text was entered, remove it
let cursor = doc.selection(view.id).cursor();
if trigger_offset < cursor {
    let remove = Transaction::change(
        doc.text(),
        vec![(trigger_offset, cursor, None)].into_iter(),
    );
    doc.apply(&remove, view.id);
}

let transaction = if let Some(edit) = &item.text_edit {
    let edit = match edit {
        lsp::CompletionTextEdit::Edit(edit) => edit.clone(),
        lsp::CompletionTextEdit::InsertAndReplace(item) => {
            unimplemented!("completion: insert_and_replace {:?}", item)
        }
    };
    util::generate_transaction_from_edits(
        doc.text(),
        vec![edit],
        offset_encoding, // TODO: should probably transcode in Client
    )
} else {
    let text = item.insert_text.as_ref().unwrap_or(&item.label);
    let cursor = doc.selection(view.id).cursor();
    Transaction::change(doc.text(), (cursor, cursor, Some(text.into())))
};


doc.apply(&transaction, view.id);

```
