### ISSUE TITLE
Selection as a outlines/box instead of different fg/bg colors

### ISSUE THREAD

**Issue by eugenesvk** [helix-editor/helix#1310]
Currently all by-word navigation automatically selects words you navigate over, which is to me a bit too visually noisy

One suggestion from [this gist from cessen](https://gist.github.com/cessen/c4c91c2e7eb5b0120fcb91c9b0ebe853)
> I wish there were alternative commands to w and friends that move the cursor by word without making selections. I find the selections really visually distracting.

But then his led me to a broader feature idea, which could also work for all selection, including manual one: what if you could replace the typical selection interface — different foreground/background — with a box, like so (`tion`):

<img width="155" alt="Selection" src="https://user-images.githubusercontent.com/12956286/146730084-5b493042-f427-4059-9f69-4a126827360c.PNG">

- Left `func` is the typical selection style via changing the font foreground/background colors
- Right `tion` is the selection style I'd like (with configurable box line width/style/color that can be reduced to, e.g., thick black dashed underlines with left/right (selection start/end) red borders and no top border or whatever)

**Comment by sudormrfbin** [comment]
Due to terminal limitations this can't be done in current frontend, but maybe once we have a GUI frontend (there's a tracking issue).

**Comment by pickfire** [comment]
Let's close this for now and reopen once we have gui.
