### ISSUE TITLE
GNU Screen support

### ISSUE THREAD

**Issue by 35359595** [helix-editor/helix#1311]
### Reproduction steps

run helix under running gnu screen over ssh session to Ubuntu 20.04 server 

### Environment

- Platform: Linux ( Ubuntu 20.04 x86_64)
- Helix version: helix v0.5.0-186-g371c84f
<details><summary>
2021-12-20T09:59:33.661 helix_view::editor [ERROR] Failed to initialize the LSP for `source.toml` { LSP not defined }
                                                                                                                                                                                             2021-12-20T10:25:53.478 helix_view::editor [ERROR] Failed to initialize the LSP for `source.toml` { LSP not defined }       
</summary>

```
no other entries present for screen session
```

</details>

Without `screen` everything works as expected under same ssh session on same machine.

**Comment by 35359595** [comment]
How it looks under `screen`:
<img width="397" alt="Screen Shot 2021-12-20 at 11 06 44" src="https://user-images.githubusercontent.com/13215338/146750076-963859e6-cf6a-4351-a34a-b85abdcc3294.png">
Regular start on same file:
<img width="397" alt="Screen Shot 2021-12-20 at 11 07 03" src="https://user-images.githubusercontent.com/13215338/146750086-09173f09-5d5a-47cc-b95e-11e8d9de2feb.png">

**Comment by 35359595** [comment]
`.screenrc`

> startup_message off
> split -v
> resize +30
> screen -t 'code' 0
> focus
> screen -t 'test & run' 1
>

**Comment by 35359595** [comment]
Same behavior on local session without SSH.

**Comment by kirawi** [comment]
It looks like GNU Screen doesn't support true color. You'll probably need to use the `base16_terminal` theme.

**Comment by archseer** [comment]
Screen master branch does apparently have truecolor support via a config option: https://github.com/termstandard/colors#multiplexer

Or just use tmux 😏
