### ISSUE TITLE
Extend completion to support language servers which requires an additional "completion item resolve" request

### ISSUE THREAD

**Issue by Gabrielbdd** [helix-editor/helix#1313]
There are some language servers that does not include a "textEdit" nor a "additionalTextEdits" on the response of the "textDocument/completion" request, and because of that, some features like auto importing an unqualified type does not work.

An example of that is the TypeScript language server. 

Reading the LSP documentation, the way of [doing that](https://microsoft.github.io/language-server-protocol/specifications/specification-3-17/#textDocument_completion) is issuing a "completion item resolve" request with the "completion item" selected by the user.

If that helps, the TypeScript language server replies the "documentText/completion" with (simplified, extracted from the logs):
```json
{
    "jsonrpc": "2.0",
    "id": 4,
    "isIncomplete": false,
    "result": {
        "items": [
            {
                "label": "Z_BLOCK",
                "kind": 21,
                "sortText": "￿24",
                "commitCharacters": [
                    ".",
                    ",",
                    "("
                ],
                "data": {
                    "file": "/home/example/index.ts",
                    "line": 4,
                    "offset": 3,
                    "entryNames": [
                        {
                            "name": "Z_BLOCK",
                            "source": "zlib",
                            "data": {
                                "exportName": "Z_BLOCK",
                                "moduleSpecifier": "zlib",
                                "ambientModuleName": "zlib"
                            }
                        }
                    ]
                },
                "detail": "zlib",
                "tags": [
                    1
                ]
            }
        ]
    }
}
```

**Comment by Gabrielbdd** [comment]
I'm pretty new to many things here (Helix, Rust, LSP 😄) but I'm willing to help with that.

I looked at how the current implementation works, and [right here](https://github.com/helix-editor/helix/blob/7438db66ae93c9164fdc29bdf31bd9b8ef861efb/helix-term/src/ui/completion.rs#L157) it applies the "additional edits" on the document.

I'm not sure if that's fine to make the [completionItem/resolve](https://microsoft.github.io/language-server-protocol/specifications/specification-3-17/#completionItem_resolve) request to the language server there, as this file appears to be concerned only with UI logic.

**Comment by matoous** [comment]
I think this would actually happen in the `code_action` command around here ~https://github.com/helix-editor/helix/blob/master/helix-term/src/commands.rs#L3277. You would send the `codeAction` along with the `data` field to the server `codeAction/resolve` route to resolve the actions[^1] and then apply them as it is done now.

---

[^1]: https://microsoft.github.io/language-server-protocol/specifications/specification-current/#textDocument_codeAction

**Comment by Gabrielbdd** [comment]
Hi @matoous , I'm not sure if I understood your idea. I agree that the "**codeAction**/resolve" could be done right where you pointed out. But to solve the problem that I mentioned, the right request to do is the "**completionItem**/resolve", as [said in the docs](https://microsoft.github.io/language-server-protocol/specifications/specification-3-17/#completionItem_resolve). And it looks like its not possible to do that at `code_action`. (But sure, this one also need to be done, I'm sure there are languages that depends on it).

About the solution, "archseer" gave me some direction on the Matrix community about how to do that using "block_on", I will try it and see if that works.

**Comment by matoous** [comment]
🙈 yes, I just mis-read. You are absolutely right.
