### ISSUE TITLE
Add `ensure_selections` key to ensure selections are in forward direction

### ISSUE THREAD

**Issue by NNBnh** [helix-editor/helix#1332]
I'm miss this feature from Kakoune, information on this from [Kakoune's keys docs](https://github.com/mawww/kakoune/blob/master/doc/pages/keys.asciidoc#movement):

> **\<a-:\>**
> ensure selections are in forward direction (cursor after anchor)

**Comment by dead10ck** [comment]
Is `flip_selections` not enough?

**Comment by NNBnh** [comment]
> Is `flip_selections` not enough?

Nope, `ensure_selections` is pretty helpful when we remap key bind or record a macro and want it's behavior to be consistent.

This is also on [Archseer's keys todo list](https://gist.github.com/archseer/0b4f474df3dcfb0b8fef09b5b97f9f79), so I thinks this key deserve to be implemented.
