### ISSUE TITLE
Add more selections manipulation keys

### ISSUE THREAD

**Issue by NNBnh** [helix-editor/helix#1334]
I'm also very miss these features from Kakoune, information on this from [Kakoune's keys docs](https://github.com/mawww/kakoune/blob/master/doc/pages/keys.asciidoc#changes):

> \<a-J\>
> join selected lines and select spaces inserted in place of line breaks
>
> \<a-_\>
> merge contiguous selections together (works across lines as well)

> \<+\>, \<plus\>
> duplicate each selection (generating overlapping selections)
>
> \<a-+\>, \<a-plus\>
> merge overlapping selections

**Comment by dead10ck** [comment]
If I'm not mistaken, overlapping ranges are not allowed, and are automatically merged into one range.

**Comment by NNBnh** [comment]
> If I'm not mistaken, overlapping ranges are not allowed, and are automatically merged into one range.

I'm assuming that you are talking about this part:

> <+>, <plus>
> duplicate each selection (generating overlapping selections)
> <a-+>, <a-plus>
> merge overlapping selections

Yeah, I was thinking the same. I have use Kakoune for over a year and pretty sure that overlapping ranges are automatically merged. But I just found out that Kakoune can generate overlapping selections, and this features is also on [Archseer's keys todo list](https://gist.github.com/archseer/0b4f474df3dcfb0b8fef09b5b97f9f79). So I just add these in for sure...

**Comment by kirawi** [comment]
AFAIK all of these have been implemented by now?

**Comment by kirawi** [comment]
I think the only exception is the overlapping selections part, but that is covered by https://github.com/helix-editor/helix/issues/2298
