### ISSUE TITLE
`ui.cursor.primary` always overrides `ui.cursor.insert`

### ISSUE THREAD

**Issue by bbodi** [helix-editor/helix#1337]
If `ui.cursor.primary` is set in a theme, it always overrides e.g. `ui.cursor.insert`.

E.g. currently in gruvbox theme one can't tell where is the cursor in a selection because it has the same color as the selection:
![image](https://user-images.githubusercontent.com/2362136/147093097-61d8bc68-da8c-4d01-8de0-1b3f441b5159.png)

If I change the `ui.cursor.primary` value of the theme file, the issue is solved:
![image](https://user-images.githubusercontent.com/2362136/147093221-74feecdb-a33d-411a-b176-e77e27541f33.png)

However, I also would like to give `ui.cursor.insert` a different color, so I know if I am in insert mode, but currently it is not possible

**Comment by matoous** [comment]
I am not sure whether the behavior should be changed 🤔 if the theme specifies different cursor colors for insert/normal mode and doesn't set the primary cursor color this will work fine, maybe we should adjust the theme instead? Or am I missing something?

**Comment by bbodi** [comment]
Now it is not possible to set a color to normal mode primary cursor, and a different one for insert mode cursor.

**Comment by matoous** [comment]
But wouldn't that require also having `ui.cursor.primary_select` and `ui.cursor.primary_insert`? What should the precedence be, e.g. if I have `ui.cursor.primary` and `ui.cursor.insert` if we give precedence to `ui.cursor.primary` than you can't distinguish between `select`/`insert` and other modes. If we give precedence to `ui.cursor.insert` than we can't distinguish primary vs. additional selections.

**Comment by oati** [comment]
One solution would be to make `ui.cursor.insert` only apply to the primary cursor when `ui.cursor.primary` is present.

**Comment by oati** [comment]
Going off of that more, since `ui.cursor` is doing nothing when `ui.cursor.primary` is present, why not make `ui.cursor` apply to all non-primary cursors?
