### ISSUE TITLE
Disable auto-pairing for `'` in Rust

### ISSUE THREAD

**Issue by Omnikar** [helix-editor/helix#1347]
Is it possible for auto-pairing for `'` to be disabled for Rust specifically? As it's quite annoying for lifetimes, and IMO adding the closing `'` manually for character literals is much less of a hassle than manually removing the closing `'` for lifetimes.

**Comment by archseer** [comment]
So this was a TODO in the original implementation that @dead10ck removed in https://github.com/helix-editor/helix/commit/94535fa013469abf6e5ab2fa52f3deced9d46de0#diff-50a1c8d85a9ae0f5840c9cf42a8de23831e9fa1c8454573136cdeb2deb0f48ddL50 so I assumed it was resolved? If not we should disable `'`

**Comment by Omnikar** [comment]
> ```
> // TODO: special handling for lifetimes in rust: if preceeded by & or < don't auto close '
> // for example "&'a mut", or "fn<'a>"
> ```

This definitely doesn't encapsulate everywhere where lifetimes can appear. I'd more think that, rather than this sort of incredibly specific special case, auto pairing `'` should be completely disabled for Rust.

**Comment by dead10ck** [comment]
> So this was a TODO in the original implementation that @dead10ck removed in [94535fa#diff-50a1c8d85a9ae0f5840c9cf42a8de23831e9fa1c8454573136cdeb2deb0f48ddL50](https://github.com/helix-editor/helix/commit/94535fa013469abf6e5ab2fa52f3deced9d46de0#diff-50a1c8d85a9ae0f5840c9cf42a8de23831e9fa1c8454573136cdeb2deb0f48ddL50) so I assumed it was resolved? If not we should disable `'`

Ah, I think I deleted that todo by mistake, sorry about that. This problem can't be solved currently without completely disabling auto pairing ' for every language, which would be kind of unfortunate. It's worth noting that there are lots of languages that have single-quoted strings, like Python and bash to name but two; Rust is the only language I know of with this problem.

This issue can only be addressed by #992, which is on my to do list; I've just been trying to order things by my own impression of what would give the best quality of life improvements. I'm currently working on delete removing auto pairs, and I planned on doing the language config stuff after that.

If we wanted a quick and dirty fix, we could make a global auto pairs config option to let people choose what they want to pair globally, and follow it up with the more complicated per language config. Though this would mean quickly introducing and then deprecating a config option.

@archseer what do you think?

**Comment by dead10ck** [comment]
Just as a heads up, I've started work on a global config option like I mentioned above.
