### ISSUE TITLE
Highlighting for log files

### ISSUE THREAD

**Issue by kirawi** [helix-editor/helix#1354]
[VSCode already does this natively,](https://github.com/microsoft/vscode/tree/94c9ea46838a9a619aeafb7e8afd1170c967bb55/extensions/log) and I find it's helpful when looking through huge logs.

**Comment by Tudyx** [comment]
What would be the approach to tackle this? Write a grammar general enough that will work for most of the log files?

**Comment by pascalkuthe** [comment]
You would need to write a Grammer. We don't support regen based highlighting (and don't really plan to in the future either).

**Comment by Tudyx** [comment]
Ok I got something working locally, hopefully I will push an MR soon

![Screenshot from 2023-10-12 15-43-39](https://github.com/helix-editor/helix/assets/56633664/9cd8babd-8307-431c-9462-416cab24a67f)
