### ISSUE TITLE
keybindings with esc do not work (for me)

### ISSUE THREAD

**Issue by adsick** [helix-editor/helix#1368]
I'm started messing up with Helix config and would like to have a way of quickly saving&escaping everything, and I'd like to perform ```Shift-esc```  for that, but this doesn't work for some reason:
![image](https://user-images.githubusercontent.com/24528839/147388486-dce02b0e-0e11-4283-963b-9295c85e9ccd.png)
when I press Shift+esc it simply does nothing.

It could be Gnome intercepting certain key-combinations or it may be something with Alacritty.
Can anyone test this on your system? I've found that ```C-S-esc``` doesn't work either.

OS: Fedora 35

**Comment by NNBnh** [comment]
Similar to #1369, this is a limitation of the terminal. Try `showkey -a` and press <kbd>Esc</kbd> and <kbd>Shift</kbd>+<kbd>Esc</kbd>, they can't be differentiated and both produce this keycode:

```console
$ showkey -a

Press any keys - Ctrl-D will terminate this program

^[ 	27 0033 0x1b
^[ 	27 0033 0x1b
```

Again ,unless Helix support [Kitty terminal's Keyboard handling protocol](https://sw.kovidgoyal.net/kitty/keyboard-protocol), there is nothing we can do to fix this.

**Comment by adsick** [comment]
Yeah, I see. It means the better to input is listening to keyboard events like 'KeyPressed(scancode)' and 'KeyReleased(scancode)', can we do that?
