### ISSUE TITLE
Can't rebind "C-/" (Ctrl + forward slash)

### ISSUE THREAD

**Issue by adsick** [helix-editor/helix#1369]
the config.toml seems valid, but pressing Ctrl + / does nothing, maybe I'm doing something wrong?
```
"C-/" = ["toggle_comments"]
```

**Comment by adsick** [comment]
```Ctrl + c``` works as expected btw

**Comment by matoous** [comment]
I think the config should be
```
[keys.normal]
"C-/" = "toggle_comments"
```
but even with that it doesn't work. I tried using wezterm which doesn't seem to have this key combination binded to anything.

**Comment by NNBnh** [comment]
This is a limitation of the terminal, try `showkey -a` and press <kbd>Ctrl</kbd>+<kbd>/</kbd> and even <kbd>Ctrl</kbd>+<kbd>7</kbd>, they can't be differentiated and both produce this keycode:

```console
$ showkey -a

Press any keys - Ctrl-D will terminate this program

^_ 	31 0037 0x1f
^_ 	31 0037 0x1f
```

Unless Helix support [Kitty terminal's Keyboard handling protocol](https://sw.kovidgoyal.net/kitty/keyboard-protocol), there is nothing we can do to fix this.

**Comment by the-mikedavis** [comment]
Fixed by #4939

**Comment by zicklag** [comment]
If anybody else runs into this, ( I'm running into it on alacritty and gnome-terminal even after building of the latest master ), then you can workaround just by binding to `C-7` instead of `C-/`. Not sure what's going on, but that makes `Ctrl+/` work. 🤷‍♂️

**Comment by AceofSpades5757** [comment]
Can confirm that binding to `C-7` works. `showkey` shows that my terminal isn't eating the key, but `C-7` fixed it for me, so thanks!
