### ISSUE TITLE
File picker doesn't change when working directory changes

### ISSUE THREAD

**Issue by adsick** [helix-editor/helix#1374]
If I open some crate, lets say [pixels](https://github.com/parasyte/pixels) I use built in :cd command to go to 'examples' folder
![image](https://user-images.githubusercontent.com/24528839/147392929-8da15094-ba4e-4337-8903-24ffbc102cc8.png)

and then I open file picker and see that it is still in the root:
![image](https://user-images.githubusercontent.com/24528839/147392922-e2a5651c-7463-4ed1-9230-dc583461b484.png)

**Comment by Triton171** [comment]
The file picker always displays search results from the current "root directory" which is the root folder of your git repository. I'm currently working on [a PR](https://github.com/helix-editor/helix/pull/1066) that prioritizes files in the current directory. When that's done, you'll still see all the files but the files in the 'examples' folder will appear on top. Hopefully that'll make this a non-issue.

**Comment by pickfire** [comment]
Should this still be open? This isn't a bug.

**Comment by adsick** [comment]
Imo there should be config for enabling/disabling that behavior.

**Comment by Triton171** [comment]
I still think that prioritizing files in the current directory is the best way to deal with this. Then, there shouldn't be any need for such a config option.
