### ISSUE TITLE
lsp errors are not being displayed

### ISSUE THREAD

**Issue by adsick** [helix-editor/helix#1376]
You can setup a workspace in a wrong way to see how Helix would react to this and in my case it turns out that it will not inform me about what is wrong.

My rust workspace has two packages with the same name (which is wrong) and when I open it with Helix, Rust analyzer starts to 'fetching data from' and after less than a second it is silent (no error, no status, non-functioning)  

another minor issue is that lsp status messages disappear when performing any action (like moving cursor around) whereas in VSC status bar can hold multiple widgets from multiple sources simultaneously (no need to clear status bar on every new message)

**Comment by matoous** [comment]
Should be easy fix: https://github.com/helix-editor/helix/blob/master/helix-term/src/application.rs#L454

**Comment by adsick** [comment]
but wait, isn't that logging? I meant messages that appear in status bar of the editor. I believe that current "message" bar is kind of a mailbox where every messages are being sent and when there is a new one we empty the previous and put new one in place, it seems to that it is not quihe what we want. I think that there is a lot of place on status bar to fit lsp status widget and maybe we can make it expandable to soo the full lsp message content.

**Comment by matoous** [comment]
Yes, currently there’s log message, ideally we display it in the command part of status line the way we do now for info messages, etc. Once there’s configurable statusline config it could have it’s own field maybe 🤷‍♂️

**Comment by kirawi** [comment]
@pascalkuthe Do we want this?

**Comment by pascalkuthe** [comment]
There is a proper aprt of the spec that RA (and most other lsps) use to show proper error message. We already have a tracking issue for that somewhere so we can probably close this one. I don't think k we should be showing the lsp log messages to the queries since a lot of lsps send intenral logging that really shouldn't be shown to the user there (vscode doesn't show this either iirc)
