### ISSUE TITLE
C env

### ISSUE THREAD

**Issue by liuhangyu** [helix-editor/helix#1382]
### Environment

- Platform: 
- Helix version: 

<details><summary>~/.cache/helix/helix.log</summary>

```
please provide a copy of `~/.cache/helix/helix.log` here if possible, you may need to redact some of the lines
```

</details>

linux ubuntu：
 tail -f ~/.cache/helix/helix.log
2021-12-26T21:04:25.029 helix_view::editor [ERROR] Failed to initialize the LSP for `source.c` { IO Error: No such file or directory (os error 2) }

languages.toml：
[[language]]
name = "rust"
scope = "source.rust"
injection-regex = "rust"
file-types = ["rs"]
roots = []
auto-format = true
comment-token = "//"
language-server = { command = "rust-analyzer" }
indent = { tab-width = 4, unit = "    " }
[language.config]
cargo = { loadOutDirsFromCheck = true }
procMacro = { enable = false }
diagnostics = { disabled = ["unresolved-proc-macro"] }

[[language]]
name = "c"
scope = "source.c"
injection-regex = "c"
file-types = ["c", "h"]
roots = [ ".gitignore" ]
comment-token = "//"
auto-format = false
config = { command = "/usr/local/clangd/bin/clangd", args = ["--enable-config"] }

config.toml：
theme = "monokai"

[editor]
line-number = "absolute"

[lsp]
display-messages = true

tail -f ~/.cache/helix/helix.log
2021-12-26T21:04:25.029 helix_view::editor [ERROR] Failed to initialize the LSP for `source.c` { IO Error: No such file or directory (os error 2) }

**Comment by dead10ck** [comment]
What's the error exactly? It's this a crash? Is LSP just showing you an error? Is this a new file that you haven't saved to a file yet? Please provide more details about the problem.

**Comment by kirawi** [comment]
The log says that it can't find the C LSP in your `$PATH`.

**Comment by liuhangyu** [comment]
Configure scope = "source.c", prompting that the source.c file cannot be found. Actually my project is a bunch of c files with other names

**Comment by liuhangyu** [comment]
Configure scope = "source.c", prompting that the source.c file cannot be found. Actually my project is a bunch of c files with other names

**Comment by liuhangyu** [comment]
/usr/local/clangd/bin/clangd exists

**Comment by archseer** [comment]
But is that in `$PATH`?

What's the output of `which clangd`?

**Comment by kirawi** [comment]
Closing as there's not enough information.
