### ISSUE TITLE
Rust panics when terminal is too small

### ISSUE THREAD

**Issue by k2d222** [helix-editor/helix#1403]
When the terminal gets too small to fit some widget, helix crashes.

### Reproduction steps

* Open helix in a resizable terminal. 
* Open the file picker (`<space> f`)
* Resize the window to about 4 rows or 4 cols
* => crash

Stumbled upon this bug when using hx in a drop-down terminal, which apparently resizes the window when hidden.

### Environment

- Platform: Linux (tested on `gnome-terminal`)
- Helix version: current master branch

**Comment by kirawi** [comment]
😅
\cc @archseer Maybe we should have a test to check for crashes with any of the UI elements on small terminal sizes?

**Comment by archseer** [comment]
I think we need to just ignore out of bound render offsets.

(I personally can't even shrink my window that small so I can't reproduce. Can you at least include a backtrace?)
![pos](https://user-images.githubusercontent.com/1372918/147714706-698e655e-e672-4cb5-ac32-0712bb4e683a.png)

**Comment by kirawi** [comment]
```
thread 'main' panicked at 'index out of bounds: the len is 115 but the index is 161', C:\Users\there\Desktop\helix\
helix-tui\src\buffer.rs:298:17
stack backtrace:
   0: std::panicking::begin_panic_handler
             at /rustc/8f117a77d0880ed59afcc1a19c72ec5c1e44b97c\/library\std\src\panicking.rs:498
```

**Comment by archseer** [comment]
> Should be as simple as `std::cmp::max(1, (row as usize) * (rows as usize))`

Yeah that looks right.

**Comment by kirawi** [comment]
(The original panic was a divide by 0 panic on line 508)

**Comment by k2d222** [comment]
The div by 0 is not the only issue: The `get` and `get_mut` methods for Buffer panic when out of bounds. 

I think it would be safer and more idiomatic to return Option and implement `Index` and `IndexMut` to panic. It would mirror the way Vec works. So whenever you're sure there is no overflow, use subscript operator [] (which has a well-known panic semantic) otherwise perform bound checks with the Option.

https://github.com/helix-editor/helix/blob/a066f59dc87608935ef4a3a3df3edf180c809e11/helix-tui/src/buffer.rs#L165

Another solution would be to always perform the bounds checks and to return a dummy Cell when out of bounds. I dislike this one.
