### ISSUE TITLE
Proposal: A General Purpose Tree Viewer/Editor

### ISSUE THREAD

**Issue by glyh** [helix-editor/helix#1406]
Basically [fern.vim](https://github.com/lambdalisue/fern.vim)

This component should be extensible, and can have different styles(e.g. git-branch like, file-tree like, lisp like)

I'm not quite sure whether this should be built-in, but I'm pretty sure this useful, just like pickers.

Usecases: 
- File explorers for both local and remote machines, like [nerd-tree](https://github.com/preservim/nerdtree)
- undo-trees like [undotree](https://github.com/mbbill/undotree)
- git branches, commits
- symbol-viewers like [symbols-outline.nvim](https://github.com/simrat39/symbols-outline.nvim)
- syntax-tree of current-file like [nvim-treesitter/playground](https://github.com/nvim-treesitter/playground) 
- TOC viewer for markdown
- Structural editing/inspecting for serialized data formats, e.g. JSON, YAML, EDN

**Comment by kirawi** [comment]
I believe there was discussion before about adding a generic tree tui widget.

**Comment by keeslinp** [comment]
#200

**Comment by glyh** [comment]
@kirawi Can you give a link to that issue?

@keeslinp I think this one is different because it's more about UI.

**Comment by kirawi** [comment]
https://github.com/helix-editor/helix/issues/1163

**Comment by glyh** [comment]
OK, I'll close this because this is duplicate.
