### ISSUE TITLE
Proposal: Leveraging Structural Regular Expressions? 

### ISSUE THREAD

**Issue by glyh** [helix-editor/helix#1407]
Current modal is based on selections, and with addtional features, called structural regular expressions, we can improve the expreinces of manipulating selections. 

We can borrow ideas from the [vis editor](https://github.com/martanne/vis), which is based on vi and sam. 

Here is [a video of vis on youtube](https://www.youtube.com/watch?v=y41MyOrPt8Q&ab_channel=FOSDEM), demonstrating its powerful structural regular expression. I think this can somehow not only be applied to text-streams with regex, but also on syntax trees with quires. Also I found that they make Structural Regular Expressions leverage external unix tools, which is convenient. 

FYI, there's some papers related to structural regular expressions: 
- [Structural Regular Expressions](http://doc.cat-v.org/bell_labs/structural_regexps/)
- [A Tutorial for Sam Lang](http://doc.cat-v.org/bell_labs/sam_lang_tutorial/)
- [Vis's man page](https://martanne.github.io/vis/man/vis.1.html)

**Comment by glyh** [comment]
There seems not much to implement:
- Select all matched by patterns
- Select subsets of current selections
- Partition current selections in to finer ones
- Feed to shell, read from shell(Note that this should work on an array of strings rather than a stream)

**Comment by Omnikar** [comment]
> Select all matched by patterns

`%s`

> Select subsets of current selections

`s`

> Partition current selections in to finer ones

`S`

> Pipe to shell, replace by output

`|`, but by "array of strings" do you mean you want it to invoke the shell command once with all the selections, separated by whitespace? The current implementation invokes the shell command once for each selection.

> Permutation, by which I mean selection A B C to B C A

`A-(` and `A-)`

**Comment by glyh** [comment]
Also, there's a slightly difference between the 2 modal, vis did not collapse selections to cursors after exiting the insert mode. I'm not sure which is better.

**Comment by Omnikar** [comment]
> Though, I think it would be good if we can document these.

They are already documented here.  
https://docs.helix-editor.com/keymap.html

Additionally, #997 is being worked on.

**Comment by Omnikar** [comment]
> Skip the next match/add a new selection at next match

Enter select mode (`v`) and then press `n` to add the next match to the selection. Additionally, you can use `(` and `)` to cycle the primary selection to one you want to remove, then use `A-,` to remove it.

**Comment by Omnikar** [comment]
> expand all selections to a higher level in syntax tree

This is not currently bound to any key by default, but you can bind it manually: `expand_selection`.

**Comment by Omnikar** [comment]
> align selections as a table.

`&`. Note that the anchors of the selections have to be aligned, then using `&` will adjust whitespace within the selections in order to align the cursors.  
For example: (`(]` delimits a selection, and the side with `]` is the side with the cursor)
```
(foo ]= 1
(bar_ ]= 2
(baz__ ]= 3
```
Press `&`.
```
(foo   ]= 1
(bar_  ]= 2
(baz__ ]= 3
```

**Comment by glyh** [comment]
Alright, seems like there's nothing to implement, I'm closing this.
![image](https://user-images.githubusercontent.com/12870742/147791390-8525437a-5831-4dc2-9e05-fd46530864d8.png)
