### ISSUE TITLE
Panic `original_doc.len_chars() == self.len`

### ISSUE THREAD

**Issue by wucke13** [helix-editor/helix#1410]
I got the following during editing Rust code, I only recall having pressed `u` multiple times to revert changes.

```
thread 'main' panicked at 'assertion failed: original_doc.len_chars() == self.len', helix-core/src/transaction.rs:275:9
```

I'm using helix 0.5.0

**Comment by pickfire** [comment]
I think we can't really do much here if there is no stack trace or step to reproduce, should it be closed?

**Comment by archseer** [comment]
Needs more info

**Comment by wucke13** [comment]
I haven't encountered this since, so unfortunately I can't provide more info other than that the given source code line assumes an invariant which is untrue in some circumstances

**Comment by TripleDogDare** [comment]
I just encountered this bug. Also without backtrace enabled and unfortunately I haven't been able to reproduce it.
```
$ hx --version
helix 22.08.1 (66276ce6)
```
```
thread 'main' panicked at 'assertion failed: original_doc.len_chars() == self.len', helix-core/src/transaction.rs:265:9
```
I had just performed a `clipboard-paste-after` followed by `u`.

**Comment by DuckDuckWhale** [comment]
Also just encountered this and don't have a reproduction:
```
thread 'main' panicked at 'assertion failed: original_doc.len_chars() == self.len', helix-core/src/transaction.rs:265:9
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
$ hx --version
helix 22.12 (96ff64a8)
```
