### ISSUE TITLE
Multiple Line String Converted To Single Line WIth Zellij

### ISSUE THREAD

**Issue by sstubbs** [helix-editor/helix#1425]
### Reproduction steps
Firstly thank you for this amazing project. I have an issue when using helix in [zellij](https://github.com/zellij-org/zellij)
- Copy a multi line string
- Open zellij 0.23.0
- Open heliix 0.5.0 within it
- Enter insert mode with I
- When pasting from clipboard with control+V there will only be a single line concatenated string
- I don't get this issue when running helix without zellij. I've checked VIM inside zellij and that seems to work fine so I'm not entirely sure whether it's an issue with this project or zellij.

### Environment

- Platform: Ubuntu 21.10
- Helix version: 0.5.0

<details><summary>~/.cache/helix/helix.log</summary>
```
please provide a copy of `~/.cache/helix/helix.log` here if possible, you may need to redact some of the lines
```
</details>
the log is empty

**Comment by dead10ck** [comment]
You should paste from the system clipboard with space + p

**Comment by sstubbs** [comment]
This works perfectly! Thanks a lot. I am so happy there is a finally a real alternative for me to use over vim.
