### ISSUE TITLE
(workspace) symbol picker is limited to the first 128 elements

### ISSUE THREAD

**Issue by poliorcetics** [helix-editor/helix#1437]
After #1041 it is now possible to search for symbols in a whole workspace. Problem is, there are often a lot more symbols than the default (from where) 128 displayed symbols and the list is not updated as I enter text.

### Reproduction steps

 

1. Go to the `helix` repository
2. Open `helix-lsp/src/client.rs`
3. Open the symbol picker `Space+s`
4. There should be aroud 50 symbols (48 on dbaed0b for me)
5. Searching for `workspace_symbols` goes to line 769 for me.
3. Open the workspace symbol picker `Space+Shift+s` (`Space+S`)
4. Search for `workspace_symbols`
5. There is no result and the prompt displays `0/128`

### Environment

- Platform: Linux Ubuntu 21.10 
- Helix version: `v0.5.0-331-gdbaed0b` on `git describe` 

<details><summary>~/.cache/helix/helix.log</summary>

A llittle heavy since I used `-vvv` so I uploaded a file instead

[helix.log](https://github.com/helix-editor/helix/files/7807706/helix.log)

</details>

**Comment by archseer** [comment]
Can you specify what filetype and language server are you using? It's likely that the LSP limits the unfiltered response and returns more results if a query is provided (but we currently don't support that)

**Comment by poliorcetics** [comment]
Sure, I opened a Rust file `helix-lsp/src/client.rs`, with [`rust-analyzer`](https://github.com/rust-analyzer/rust-analyzer) as my language server.

**Comment by Aatroxs** [comment]
I also have the same problem

**Comment by sam-mccall** [comment]
clangd dev here, we also break spec by limiting to 100 results (same as code completion), happy to elaborate if it's helpful.

> According to the LSP spec, an empty string should return all symbols, but since this is computationally expensive it might choose to limit the number of results

Not just computationally expensive on the server, but we can overwhelm clients: "all symbols" can easily be 1M+, and there are clients out there written in vimscript and such...

**Comment by creikey** [comment]
> clangd dev here, we also break spec by limiting to 100 results (same as code completion), happy to elaborate if it's helpful.
> 
> > According to the LSP spec, an empty string should return all symbols, but since this is computationally expensive it might choose to limit the number of results
> 
> Not just computationally expensive on the server, but we can overwhelm clients: "all symbols" can easily be 1M+, and there are clients out there written in vimscript and such...

How should the symbol picker be used then if the symbol search can only query out of 100 symbols? Most workspaces have more than 100 symbols

**Comment by creikey** [comment]
Oh wait I understand now, helix was querying for every single symbol from the LSP and filtering via its own search algorithm. #3110 fixes this
