### ISSUE TITLE
:cd not working on Windows with v0.6

### ISSUE THREAD

**Issue by superlou** [helix-editor/helix#1439]
### Reproduction steps

1. Run `hx` in the command prompt
2. Try to cd to a different folder, e.g. "C:\opt"
3. Receive the error "Couldn't change the current working directory: The system cannot find the file specified. (os error 2)"

![image](https://user-images.githubusercontent.com/709695/148066359-9cb656d4-4757-401e-b7f1-69dcd3aebe5c.png)

The expected behavior (release v0.5) is:

![image](https://user-images.githubusercontent.com/709695/148066574-0cfa9f79-926d-4e64-9cf1-52e8d5448a4f.png)

### Environment

- Platform: Windows 10
- Helix version: v0.6 release (`hx -V` prints "helix")

<details><summary>~/.cache/helix/helix.log</summary>
(C:\Users\lsimons\AppData\Local\helix is empty)
</details>

**Comment by archseer** [comment]
\cc @ath3 could this be due to https://github.com/helix-editor/helix/pull/1389 https://github.com/helix-editor/helix/pull/1231 ?

@superlou can you replicate it on 3307f44ce20a71273614f9b30dafb08822e557a1 ? (One commit before #1231 got merged)

**Comment by superlou** [comment]
Unfortunately, I can't build on a Windows computer: our office Rust version is too old and I use Linux at home. I'll see if I can get our tool-chain updated.

**Comment by archseer** [comment]
@kirawi You are on Windows right? Can you try to narrow it down?

**Comment by kirawi** [comment]
I'm not sure if it's the same issue, but trying to `:open` a directory would give an `unable to open <directory>` error in the status line. Before, I believe it would have opened the file picker?

**Comment by superlou** [comment]
It definitely seems like it's related to Windows vs. Unix style paths. If I do `:cd C:/opt` (note the forward slash) it completes successfully:

![image](https://user-images.githubusercontent.com/709695/148088892-42263faa-99fe-4c94-94c2-74cf8f6f28f7.png)

Also, autocompleting paths on Windows seems to work so long as I use forward slashes.

**Comment by kirawi** [comment]
It seems like it's escaping the backslash, so `C:\\` works while `C:\` doesn't.

**Comment by archseer** [comment]
I thought the fix for #1389 was odd, rather than converting Windows backslashes to slashes, it should patch the shellwords handling to work with backslashes if `cfg(windows)` I think?

**Comment by kirawi** [comment]
Yep, I can do that since I worked with shellwords' source for another project.

**Comment by archseer** [comment]
We don't import shellwords, we have our own implementation.

**Comment by archseer** [comment]
https://github.com/helix-editor/helix/blob/master/helix-core/src/shellwords.rs

**Comment by archseer** [comment]
An easy quickfix for the time being would be revert #1389 and conditionally use `shellwords` if we're not on windows, otherwise just split string on spaces like before.

**Comment by archseer** [comment]
Can someone test the latest master (https://github.com/helix-editor/helix/commit/77677039795811505d8205f4efa082fc598492fc)? I also reverted #1389

**Comment by kirawi** [comment]
Seems like it works, but I notice that typing e.g. `..\` shows 
![Capture2](https://user-images.githubusercontent.com/67773714/148164332-76c2ea52-e693-4cd3-a4ca-872cef852d10.PNG)
instead of
![Capture4](https://user-images.githubusercontent.com/67773714/148164405-356a8e70-5bc3-42d5-be86-597acdb089b2.PNG)

**Comment by archseer** [comment]
Yeah but that was present previously before, I just reverted back to the old behavior. Fixed now in 3e4f8154

**Comment by ChimpSpin** [comment]
Still getting this error if the path contains spaces.

**Comment by ath3** [comment]
I will work on this.
