### ISSUE TITLE
Adding More Tests for Commands & Movement

### ISSUE THREAD

**Issue by kirawi** [helix-editor/helix#144]
I think it would be beneficial to thoroughly test `helix-core/src/movement.rs` & `helix-term/src/commands.rs`. To start, it would probably be most important to test the functions transitively called by hotkeys in `helix-term/src/keymap.rs`. This could also be a good first issue.

**Comment by kevinsjoberg** [comment]
I agree. Not only would it be nice to have it tested, it would serve us well in terms of catching regressions. 🙂

**Comment by kirawi** [comment]
I was thinking of having basic unit tests to check for correct behaviour and that it doesn't panic, and then later on have more complicated integration tests to address #115 and basically be more exhaustive, include combos, etc. However, I think this and that should be considered separate issues,

**Comment by pickfire** [comment]
kakoune have nice integration tests, we could do some macros for these.

**Comment by PabloMansanet** [comment]
I'm happy to write a few of these, as it tends to be what I do when I'm wrapping my head around a codebase anyway :). Feel free to assign me if nobody else is on this.

**Comment by kirawi** [comment]
Can this be considered completed or do we want to improve our test coverage further in this specific portion of Helix?

**Comment by archseer** [comment]
We extensively covered movement but I'd still like to cover other commands.

**Comment by archseer** [comment]
This is covered by #115
