### ISSUE TITLE
Document the external libraries necessary for building helix

### ISSUE THREAD

**Issue by cinerea0** [helix-editor/helix#1443]
#### Describe your feature request

I've just encountered the same error described in #773 and #1223. However, since I'm using Void Linux instead of Fedora, the solutions there are useless to me. It would be useful if the external libraries and programs required to build helix were listed somewhere so that Linux users can install the precisely what they need.

**Comment by archseer** [comment]
There are no external dependencies other than a C compiler that's usually provided by your distribution (`build-tools` or similar, the disparity between distros is precisely why hard to document.)

For Void Linux, see https://www.reddit.com/r/voidlinux/comments/bge4tz/help_with_c_compilation_musl/

**Comment by cinerea0** [comment]
The environment where I'm trying to build helix already has gcc available. I assumed that the build failure was due to not having some library available. If that's not the case, I'll open a bug report.
