### ISSUE TITLE
How long takes generally for helix to update the packages?

### ISSUE THREAD

**Issue by norman784** [helix-editor/helix#1450]
In my case I'm curious about Homebrew, but it seems that it takes a while for helix to be updated, is there a better way to have  the editor up to date?

Also does the helix team update some package distribution system directly? (example is Macports/Homebrew updated directly by the team?)

**Comment by archseer** [comment]
We have our own tap that I forgot to update until now, it should be up to date now: https://github.com/helix-editor/homebrew-helix/commit/719f09c53e107fb5d6f6a0670ffb66bc581fff32

Generally it depends on the distribution since we don't have control over downstream packaging.

**Comment by norman784** [comment]
Cool, thanks!
