### ISSUE TITLE
impossible to build helix from tar.gz

### ISSUE THREAD

**Issue by Pungolo** [helix-editor/helix#1451]
hello. if you use the source 
https://github.com/helix-editor/helix/archive/refs/tags/v0.6.0.tar.gz
the build fails because the required submodules are not found with the files in the helix-syntax directory.

is it possible to upload a complete source archive?

**Comment by WindSoilder** [comment]
For now it's impossible because of this github issue: https://github.com/dear-github/dear-github/issues/214

**Comment by oblalex** [comment]
The same is true for building from git repo: `build.rs` explicitly tries to build several languages which are not present in `languages` dir.

Commenting out `tsx` and `ocaml-interface` allows to finish the build successfully.

 https://github.com/helix-editor/helix/blob/a8fd33ac012a79069ef1409503a2edcf3a585153/helix-syntax/build.rs#L203-L206

![image](https://user-images.githubusercontent.com/904705/148454988-4509cf86-f912-4efd-a885-7ec9b6e9f68b.png)
![image](https://user-images.githubusercontent.com/904705/148455296-cd3b980b-c6ac-49ef-b473-61a5d0780816.png)

**Comment by kirawi** [comment]
`tsx` is defined in https://github.com/tree-sitter/tree-sitter-typescript/tree/master/tsx
`ocaml-interface` is defined in https://github.com/tree-sitter/tree-sitter-ocaml/tree/master/interface

**Comment by Pungolo** [comment]
The submodules you request are already taken in ebuld.

I can’t reproduce issue, in my two setup works fine. Please post a build log

Cordiali Saluti
Degni Luciano

Il 9 gen 2022, 23:47 +0100, Kirawi ***@***.***>, ha scritto:

**Comment by sudormrfbin** [comment]
I think this can be closed now since we don't use submodules now and have #1659 ?

**Comment by the-mikedavis** [comment]
Yep with #1659, the submodules are gone and the cargo build is able to fetch and build tree-sitter grammars. #1875 was also just merged that will mean the next release will have a `helix-VERSION-source.tar.xz` which includes the source plus the grammar repositories already fetched.
