### ISSUE TITLE
Intrusive Diagnostics

### ISSUE THREAD

**Issue by k2d222** [helix-editor/helix#1462]
Diagnostics appear on top of the code.

Diagnostics are always drawn from the top-right corner, with a max witdth of 100 chars and word wrapping.

I'm not sure what the best solution to this problem is, here are a few ideas:

 - just draw code over diagnostics (code has higher priority)
 - add a `show / hide diagnostics` command
 - ellipsize diagnostics and make a popup to show longer version
 - wrap diagnostics when conflicting with a line of code
 - Show diagnostics in a box after timeout, similar to the snippets / signature help box

(see this c++ code where STL template diagnostics are particularly verbose)
![Screenshot from 2022-01-08 17-04-06](https://user-images.githubusercontent.com/16296136/148651247-72451a19-fd02-45d5-92ee-6a5aa04f28d8.png)

**Comment by kirawi** [comment]
Would https://github.com/helix-editor/helix/pull/1445 fix it for you?

**Comment by archseer** [comment]
No it wouldn't, it's orthogonal :P

**Comment by archseer** [comment]
There's two features that would be nice:

- A config option that allows disabling the diagnostics overlay
- Something like https://github.com/emacs-lsp/lsp-ui/blob/21ce926eedd41ef305c2d89412506ce59b1a7eac/lsp-ui-sideline.el#L216-L230 that considers where the last code character on the line is

**Comment by dariooddenino** [comment]
I have a similar need.

Purescript errors can be VERY long when there's a row type error. They get truncated and right aligned with the current diagnstics, making them almost useless.

Ideally I'd like to be able to:
- display a diagnostic message on a scrollable popup
- open the message on a new temporary buffer so that I can use it as a permanent reference while fixing the code

**Comment by pathwave** [comment]
To add to this when I get a error message on saving the file, the error message gets put on whatever line I am on and it keeps staying relative to the view. Moving around in the code makes part of the error message disappear (where it intersects with code) making me end up with random red letters all over the place.

Maybe for that kind of errors it would be best if they disappeared after a certain time, or when the user performs an action.

I will post some screenshots when I have time

**Comment by ngraham20** [comment]
+1 for the temporary buffer idea

**Comment by ngraham20** [comment]
Virtual Text #417 along with Soft Wrap #136 would also do it, as then, the virtual text could just be placed above or below the error line as virtually wrapped lines

**Comment by aspizu** [comment]
can you do it like vscode does it with a problems pane

**Comment by manan-gup** [comment]
Having the same issue where the diagnostic message covers the code that I'm trying to edit. Is there any workaround till this is fixed?

P.S. Stopped using VS Code a few months ago and tried a few flavours of NeoVim distros and then Helix. I have to say that I'm loving the Helix experience.

**Comment by eliasboegel** [comment]
In my opinion, the way neovim and [lspsaga.nvim](https://github.com/glepnir/lspsaga.nvim) do it is quite nice:

- There is some space and visual markers before showing one diagnostics message inline, a dot or square or similar, one per diagnostic in that line. The color of the markers and text indicates the diagnostic type(s). (Not too different from current behaviour, except for the separation)
- On jumping to a diagnostic, a small pop up opens, showing the diagnostics of this line in full-text separated from each other.

![image](https://user-images.githubusercontent.com/62483075/214631395-800b368c-2902-47d9-9cd9-3a63d4bf14fe.png)
![image](https://user-images.githubusercontent.com/62483075/214631460-76597011-e0d9-4182-a39d-97ae3dd271fb.png)

In my opinion, the inline diagnostics are still quite clean, but also noticeable - more importantly, there is a clear separation between code and diagnostic, while not covering up any code. When the full diagnostic text is necessary, (i.e. when jumping through diagnostics), the full text is displayed in a pop up clearly separated from the text.

**Comment by dogunbound** [comment]
+1 for simply drawing over the diagnostics, but only if a cursor is on the same line as the diagnostic.

**Comment by cemalokten** [comment]
How about displaying error/warning messages in the status bar when the cursor is on top of the issue? It's keeps the errors out of the way but are there for when you need them. I had it setup like this previously while using ALE in Neovim and it worked well. Currently dealing with this sort of thing half way through typing:

![Screenshot 2023-01-31 at 12 25 59](https://user-images.githubusercontent.com/60609268/215762247-4c938dae-9a0d-4cd3-9e56-e94ae9be7f35.png)

**Comment by 0rphee** [comment]
is this feature in the works? as i understand, virtual text is already supported through #5420

anyway, i'm just want to get rid off those awful lsp messages haha!

**Comment by kirawi** [comment]
https://github.com/helix-editor/helix/pull/6059

**Comment by Teddy-94** [comment]
Until #6059 / #6417 could there be a setting to allow hiding the diagnostics message that is in the top right corner? Maybe I missed it but I couldnt find it in the docs...

**Comment by gfarrell** [comment]
Also coming here to say that this makes editing in small windows (or many splits) really difficult. Half the time I can't see the code because the LSP errors hide what I'm editing.

In nvim the errors disappear while you're in insert mode (IME at least, I didn't used to think about it because they were never intrusive in neovim), which is one option, but another is just to change where they are displayed (I cannot find a setting for this in the docs).

This is the main thing marring the (otherwise great) helix experience for me.

**Comment by 0ihsan** [comment]
workaround: disable diagnostics feature

~/.config/helix/languages.toml
```toml
[[language]]
name = "c"
language-servers = [{name = "clangd", except-features=["diagnostics"]}]
```

**Comment by vxgxbxnd** [comment]
> Until #6059 lands, it seems to me the quick fix is to simply render the diagnostic messages at the bottom of the pane instead of the top. You can always shift up the view center (`zz`) to get cursor out of the way of something on the bottom, where the inverse is not true.

How are you rendering the diagnostics at the bottom instead of the top? I can't find a reference to changing placement.

**Comment by kemelzaidan** [comment]
https://github.com/helix-editor/helix/discussions/11096

**Comment by LnxgpI0k** [comment]
Just to clarify, is there a way to disable ALL displayed diagnostics? No top-right diagnostics, specifically.
