### ISSUE TITLE
Make page down/page up work in file picker

### ISSUE THREAD

**Issue by hahanein** [helix-editor/helix#1467]
Currently when opening the file picker, `page up`/`page down`/`ctrl`+`d`/`ctrl`+`u` all move the cursor to the first line on the first page.

It'd be nice if those really moved you page by page in the appropriate direction.

**Comment by schoenenberg** [comment]
It looks like this is already done. Only PR missing @hahanein?

**Comment by hahanein** [comment]
@schoenenberg This version is pretty much a hack.

The proper way'd be using callback_fn as I understand. But there seems to be quite a bit of work to be done to get this to work that I haven't yet managed.
