### ISSUE TITLE
Update to newest tree-sitter-rust

### ISSUE THREAD

**Issue by poliorcetics** [helix-editor/helix#1473]
Now that https://github.com/tree-sitter/tree-sitter-rust/pull/99 has been merged, updating to the most recent tree-sitter-rust commit would allow us to highlight doc comments differently from normal comments in Rust files

**Comment by archseer** [comment]
Yeah I was thinking this should use `comment.block.documentation` or `comment.documentation`. Do you want to open a PR? :) Should be an easy change but I can only get to it tomorrow morning

**Comment by archseer** [comment]
The upstream PR was reverted because of some issues, looks like we'll need to wait a bit longer.

**Comment by poliorcetics** [comment]
I think this is out-of-date now, closing

**Comment by archseer** [comment]
It's still blocked: https://github.com/tree-sitter/tree-sitter-rust/pull/128
