### ISSUE TITLE
Trying to map semicolon to colon in normal mode

### ISSUE THREAD

**Issue by mogenson** [helix-editor/helix#1478]
I'm trying to map semicolon to colon in normal mode so I can press a single key, without shift, and begin typing a command. It's a muscle memory built up from years of vim/kakoune. Based on the [book](https://github.com/helix-editor/helix/blob/master/book/src/remapping.md), it seems like I should be able to use the string `"semicolon"` in place of the character `;` for the config.

### Reproduction steps

The following config.toml
```
[keys.normal]
"semicolon" = ":"
```
Results in the startup error:
```
Bad config: data did not match any variant of untagged enum KeyTrie for key `keys.normal` at line 1 column 1
Press <ENTER> to continue with default config
```
 

### Environment

- Platform: Linux and MacOS
- Helix version: 0.6.0 from nix-pkgs

<details><summary>~/.cache/helix/helix.log</summary>

```
2022-01-10T21:36:31.102 helix_view::editor [ERROR] Failed to initialize the LSP for `source.toml` { LSP not defined }
```

</details>

**Comment by python128** [comment]
I'm pretty sure that the format of the config.toml is as such:
```toml
# key/value = command, not default command

[keys.normal]
"semicolon" = "command_mode" # Not ":"
```

You had given the default command key("`:`"), instead you should give the command name(of source code. `"command_mode"`)

**Comment by mogenson** [comment]
That works perfectly! Thanks for the help.

**Comment by j-james** [comment]
Note: starting with 22.08, it appears that you need to specify `";"` instead of `semicolon`.
