### ISSUE TITLE
Allow disabling wrap around for search_prev/search_next

### ISSUE THREAD

**Issue by eugenesvk** [helix-editor/helix#1489]
Currently `search_prev` and `search_next` command "wrap around" the file when they reach the 1st/last match
I'd like to be able to add an option for these commands to just stop at the 1st/last match

**Comment by archseer** [comment]
Sounds good, I'd add it as a `wrap-around` setting in editor config. We might want to move it into a new subsection `[editor.search]` together with `smart-case`.

**Comment by eugenesvk** [comment]
Thank you, that'd work for me as I don't like this behavior and would be fine with a global setting
(not sure if anyone would want to be able to bind/use both types of commands, thus requiring this config to be per keybind/command, but they can speak for themselves :) )
