### ISSUE TITLE
Word jumps ignore newlines in Normal mode

### ISSUE THREAD

**Issue by eugenesvk** [helix-editor/helix#1497]
I understand that Helix has a different text editing "philosophy", part of which is that you select first, delete later, but I'm just trying a few keybinds with familiar behavior from other editors for at least some  compatibility and encountered this strange behavior:

So if I bind `delete_word_forward` to e.g. <kbd>^</kbd><kbd>Delete</kbd> in Normal mode I get this weird behavior

```
↓ cursor is on the next empty line. Invoking delete_word_forward deletes 'some' below WITHOUT moving the cursor



some text
```

Ok, fine, I'll auto-select a word first via a `move_next_word_end` command, then `delete_selection`:

```
↓ cursor is on the next empty line. Invoking ["move_next_word_end","delete_selection"] ignores newlines, moves the cursor to 'some' below and deletes it



some text
```

Is there a way not to ignore newlines in a single by-word command? Or is the Helixy way to enter the `select_mode` and then jump by words?

**Comment by dead10ck** [comment]
Does `extend_next_word_end` work?

**Comment by eugenesvk** [comment]
Seems to work, thanks a bunch!
