### ISSUE TITLE
Undo doesn't work if Insert mode isn't invoked (for some commands)

### ISSUE THREAD

**Issue by eugenesvk** [helix-editor/helix#1500]
I've noticed that if I use `delete_char_forward`/`delete_char_backward` in Normal mode then `undo` doesn't undo this operation (although I see an extra `+` in the status bar).
But if I just enter and exit the Insert mode, undo starts working fine
Can these commands be added to the "undo stack" right away as well?

(think there might be other commands, but I don't remember now)

**Comment by archseer** [comment]
Hmm I see why this is happening: those commands are under the insert module so they don't commit the changes after applying them (exiting insert mode commits them altogether).

I think we'll want to remove `doc.append_changes_to_history` from commands and instead do this as a step after executing a command (in `ui/editor.rs`) if `mode != insert`.
