### ISSUE TITLE
Support for block comments

### ISSUE THREAD

**Issue by k2d222** [helix-editor/helix#1505]
Add support for block comments. (line comment support per language was added in #463)

There are multiple use-cases for this:
 - Many languages don't support line comments but do support block comments, e.g. `html`/`xml`, `css`, old `c`, `ocaml`. the `toggle_comments` command could fallback to a multi-line comment.
 - Some users / codebases prefer line comments. That preference could be set in `languages.toml`.
 - A comment textobject could be interesting too, to select whole comments or comment out selections.

**Comment by mikkelfj** [comment]
On a related note - I won't make a new issue for this:

The :reflow command can reformat a selected part of a C block comment of the following style (in my limited testing), but unlike Vim, adding a newline while editing the comment will not add ` * ` at the line start, which is rather tedious.

```
/*
 * foo
 * bar
 */
 ```

**Comment by the-mikedavis** [comment]
That's https://github.com/helix-editor/helix/issues/1730

**Comment by Elias-Graf** [comment]
Is there currently no way to toggle comments in languages like CSS, HTML? I'm (currently) not even talking about having separate shortcuts for block comments, would just be nice if it worked at all in such languages.

**Comment by the-mikedavis** [comment]
Correct, this issue covers adding support for toggling block comments

**Comment by gabydd** [comment]
this could be potentially fixed with #4718: [heres a video of it in action](https://asciinema.org/a/kkAUgOnELliqhspIUl4Umiy9q), its still a draft though and needs a bit of work
