### ISSUE TITLE
Control key not working

### ISSUE THREAD

**Issue by GooseDeveloper** [helix-editor/helix#1534]
### Summary

The left control modifier is ignored, making keybinds such as <kbd>Backspace</kbd> impossible.

### Reproduction steps

**Key Sequence:**
- <kbd>Control</kbd> + <kbd>H</kbd>
- <kbd>Backspace</kbd>

**AsciiNema Recording:**
https://asciinema.org/a/jNycCnr7SjGYepKBLFkO1Dlc1
 

### Environment

- Platform: `Linux` 
- Helix version: `helix 0.5.0` 

### Note

- This is not an issue in the TTY
- This also affects Helix in command mode

**Comment by archseer** [comment]
What terminal emulator?

**Comment by GooseDeveloper** [comment]
> What terminal emulator?

XTerm(370). It's notorious for not being very intuitive and needing some configuration, but I've set the following:
```
xterm*foreground: white
xterm*background: black
xterm*metaSendsEscape:  true
xterm*selectToClipboard: true
xterm*scrollTtyOutput: false
```
Perhaps this has something to do with `metaSendsEscape` or a similar option?

**Comment by dead10ck** [comment]
Did you try a different terminal?

**Comment by GooseDeveloper** [comment]
I'm trying `kitty` now...

**Comment by GooseDeveloper** [comment]
> Did you try a different terminal?

No... The Linux Console works fine, so I imagine this is an XTerm issue. I might check some subreddits for terminal-specific support. Thanks :)

P.S. Sorry for the late reply

**Comment by dead10ck** [comment]
Cool, can this be closed then?
