### ISSUE TITLE
Ability to hide the help popups

### ISSUE THREAD

**Issue by nhynes** [helix-editor/helix#1538]
If I already know the commands (or simply want to consult the docs when necessary), I'd prefer not to see distracting help popups.

**Comment by Omnikar** [comment]
<img width="325" alt="image" src="https://user-images.githubusercontent.com/79615262/150083076-7032f60f-66ee-4a1e-9d5f-e65c0c4f14e5.png">

Assuming you mean these, this is already implemented:
```toml
[editor]
auto-info = false
```

**Comment by nhynes** [comment]
Ah, thanks. I didn't even know what to call the things. I searched the issues for `(help|command) (popup|box|menu)` , read through the docs and code, but I wouldn't have thought to look for "info box". Hopefully this issue will help others with similar lack of naming creativity!
