### ISSUE TITLE
Way to execute shell commands

### ISSUE THREAD

**Issue by IsotoxalDev** [helix-editor/helix#1541]
There are times when one wants execute shell commands in a text editor. Vim achieves this by taking !commands as commands for executing in shell. example:  ```:!pandoc '%' --pdf-engine=xelatex -o ~/Documents/out.pdf &<cr><cr>```. This is extremely convinient as i don't have to open a separate terminal to do this command. the % in the command refers to the current file

**Comment by sudormrfbin** [comment]
Does https://docs.helix-editor.com/keymap.html#shell fit your needs ?

**Comment by IsotoxalDev** [comment]
> Does https://docs.helix-editor.com/keymap.html#shell fit your needs ?

No. It executes the command and pastes the output. There are commands that needs to be run in background or it needs to run and the output needs to be shown on a separate buffer or window.

**Comment by dead10ck** [comment]
> No. It executes the command and pastes the output. There are commands that needs to be run in background or it needs to run and the output needs to be shown on a separate buffer or window.

I'm curious what commands you're running where you need to see the output, but wouldn't be better served just by running it in another terminal window/pane/tab?

**Comment by IsotoxalDev** [comment]
i want to run a pandoc command which converts the markdown file i am editing into a pdf. I don't have a need to see the output. But i want to execute commands in a keymap. In vim i have mapped space+p as a way to compile my markdown file to a pdf. i don't want to open an external terminal to run just the command to run this simple command. I have zathura on the side of my screen. I use a wm with master and stack layout so having an external terminal reduces my zathura's real estate. Having a output right there is just a convinience.
A way to run a command with `|` or `alt-|` or `!` or `alt-!` to be configured using the toml files is not there.
![2022-01-23-205013_1920x1080_scrot](https://user-images.githubusercontent.com/62714538/150685697-8e1860db-a870-48d4-add2-282b6fe591d8.png)

**Comment by kirawi** [comment]
Should be easy to create such a command via https://github.com/helix-editor/helix/blob/4044c70eb2d23402629d58d0e8904815abd68dc7/helix-term/src/commands.rs#L6015-L6051

**Comment by hayashikun** [comment]
Running with `alt-|` ignores output and `$` also does not insert text so that what you want to do is possible, isn't it?
But it would be nice to have a keymap to just run shell command, ignoring output. (e.g. `#`, `^`, `ctrl-|` ??)

**Comment by IsotoxalDev** [comment]
It is sure possible to run commands. but I want to bind a shell command to a keymap

**Comment by hayashikun** [comment]
By adding a command (e.g. `:shell`) like the commands used in command mode (https://docs.helix-editor.com/commands.html), we can define a keymap that runs a shell command in `config.toml`.
Is my understanding correct?

**Comment by kirawi** [comment]
I'm pretty sure.

**Comment by IsotoxalDev** [comment]
Ye!!!. That PR looks good

**Comment by IsotoxalDev** [comment]
As PR #1682 has been merged. This Issue can be closed.
