### ISSUE TITLE
Picker won't scroll down when it hits the bottom

### ISSUE THREAD

**Issue by hahanein** [helix-editor/helix#1544]
The Picker doesn't scroll when the cursor hits the bottom.

This bug seems to have been introduced with f5b0821860940782567a0baa17280aef04f845e3

### Reproduction steps

1. Open File Picker in sufficiently large workspace
2. Try to move the cursor past the last entry visible in the list

### Environment

- Platform: Linux
- Terminal emulator: foot
- Helix version: v0.5.0

**Comment by kirawi** [comment]
Closed by #1567
