### ISSUE TITLE
`:change-current-directory` does not autocomplete for symlinks to directories

### ISSUE THREAD

**Issue by hyperupcall** [helix-editor/helix#1548]
### Reproduction steps

- Open `helix`
- Use `:change-current-directory` and see that completions do not show for symlinks to directories. (If you manually type the symlink (ex. `Docs` in the screencast below), Helix will change the directory correctly)

[![asciicast](https://asciinema.org/a/VZUFuDVMjGxDEcnoPYc6BKE55.svg)](https://asciinema.org/a/VZUFuDVMjGxDEcnoPYc6BKE55)

### Environment

- Platform: Linux
- Terminal emulator: Kitty 
- Helix version: `helix 0.5.0`

<details><summary>~/.cache/helix/helix.log</summary>
EMPTY
</details>

**Comment by MatthieuBarthel** [comment]
There is also no completion for symlinked directories in the fuzzy finder, I think it is related so I won't create another issue.
