### ISSUE TITLE
investigate replacing the submodules system for grammars

### ISSUE THREAD

**Issue by the-mikedavis** [helix-editor/helix#1549]
Tree-sitter grammars are currently all added to the project as git submodules. There are quite a few supported languages now, so it ends up being very expensive to clone helix.

It may make sense to have a separate CLI to do fetching and grammar compilation in the future, but for now it looks like a nice and small increment to switch submodules out for a script like [this one](https://github.com/tree-sitter/tree-sitter/blob/master/script/fetch-fixtures) in tree-sitter itself. A shallow clone for each grammar would be faster.

There are also some packaging methods that have a hard time with submodules which a script may improve. See [void-packages#33881](https://github.com/void-linux/void-packages/issues/33881) and #1448.

**Comment by the-mikedavis** [comment]
I'm interested in experimenting with this as my time allows. If others have ideas or want to beat me to the punch, feel free :slightly_smiling_face:

**Comment by kbknapp** [comment]
To add to this, I've been having an issue recently where the submodules say they're updated, but don't actually clone any of the data.  This causes the build script in `helix-syntax` to fail. But it's frustrating when it's only a few of the grammars, so you're left looking through manually trying to find which dirs didn't clone, delete them, re `submodule update`, etc. A script would probably be a far less error prone way to solve this.
