### ISSUE TITLE
Visual bug

### ISSUE THREAD

**Issue by kirawi** [helix-editor/helix#1561]
![Capture2](https://user-images.githubusercontent.com/67773714/150648428-292c2789-5f19-43f6-9663-05d8488bec75.PNG)
The bug seems to be caused by line 388, as deleting it fixes the bug (after refreshing the screen).
https://github.com/helix-editor/helix/blob/b8cafee9f5399ffddcaebffe256035bc888eeaa7/helix-view/src/view.rs#L388

### Reproduction steps

Open `helix-view\src\view.rs`
`385` + `G`
Scroll down

### Environment

- Platform: Windows
- Terminal emulator: Alacritty
- Helix version: helix v0.5.0-395-g0b55b21f

**Comment by kirawi** [comment]
I'm guessing it's a unicode/grapheme rendering issue?

**Comment by archseer** [comment]
Renders just fine for me both here and in helix. Could be a Windows issue, or specific to your font

**Comment by kirawi** [comment]
Possibly? I'll investigate this further, since I'm seeing it happen in Powershell where it's the default font.
