### ISSUE TITLE
File completion crash with ISO-8859-9 (?) filename

### ISSUE THREAD

**Issue by apraga** [helix-editor/helix#1569]
I have this weird folder on my computer named `.fo\Xc3nts`. Python tells me it's encoded in ISO-8859-9.
```
>>> import os
>>> import chardet
>>> for n in os.listdir('.'):
...     chardet.detect(os.fsencode(n))
...
{'encoding': 'ISO-8859-9', 'confidence': 0.5725665064625581, 'language': 'Turkish'}
```

### Reproduction steps
Helix crash when trying to complete the list of folders with this weird (using `:o`). 

<details><summary>Backtrace</summary>

```
thread 'main' panicked at 'called `Option::unwrap()` on a `None` value', helix-term/src/ui/mod.rs:338:39
stack backtrace:
   0: rust_begin_unwind
   1: core::panicking::panic_fmt
   2: core::panicking::panic
   3: <core::iter::adapters::filter::Filter<I,P> as core::iter::traits::iterator::Iterator>::next
   4: <alloc::vec::Vec<T> as alloc::vec::spec_from_iter::SpecFromIter<T,I>>::from_iter
   5: helix_term::ui::completers::filename
   6: helix_term::commands::command_mode::{{closure}}
   7: helix_term::ui::prompt::Prompt::insert_char
   8: <helix_term::ui::prompt::Prompt as helix_term::compositor::Component>::handle_event
   9: helix_term::compositor::Compositor::handle_event
  10: helix_term::application::Application::handle_terminal_events
  11: helix_term::application::Application::run::{{closure}}
  12: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
  13: tokio::park::thread::CachedParkThread::block_on
  14: tokio::runtime::thread_pool::ThreadPool::block_on
  15: tokio::runtime::Runtime::block_on
  16: hx::main
```

</details>
 

### Environment

- Platform: FreeBSD 
- Terminal emulator: st
- Helix version: 0.6.0

<details><summary>~/.cache/helix/helix.log</summary>
```
2022-01-23T15:33:40.391 helix_view::editor [ERROR] Failed to initialize the LSP for `source.md` { LSP not defined }
2022-01-23T15:38:13.286 helix_view::editor [ERROR] Failed to initialize the LSP for `source.md` { LSP not defined }
2022-01-23T15:40:23.272 helix_view::editor [ERROR] Failed to initialize the LSP for `source.md` { LSP not defined }
```

</details>

**Comment by kirawi** [comment]
@archseer Assuming this is indeed an issue with encoding, would we have to switch to using something like [OsString](https://doc.rust-lang.org/stable/std/ffi/struct.OsString.html)?

**Comment by kirawi** [comment]
By the way, I think you're missing part of the backtrace. For example, it should start with:
```
thread 'main' panicked at 'range start index 2 out of range for slice of length 0', library\std\src\path.rs:713:24
stack backtrace:
```

**Comment by apraga** [comment]
@kirawi Indeed. I've updated the bug report, thanks.

**Comment by dead10ck** [comment]
I think the code base makes a lot of assumptions in its behavior about Unicode. I can't speak for @archseer, but I don't know if it's in our interest to support every file encoding natively. There are tools to convert file encodings. Although it might be good if it showed an error message instead of panicking.

**Comment by kirawi** [comment]
We support different file encodings, in this case it's a file path encoding :P

**Comment by archseer** [comment]
Relevant line: https://github.com/helix-editor/helix/blob/ed03be1450edd35738e5fa141dd08bb5a8326003/helix-term/src/ui/mod.rs#L334

We could call https://doc.rust-lang.org/std/path/struct.Path.html#method.to_string_lossy on the path, or skip such paths

**Comment by archseer** [comment]
> Python tells me it's encoded in ISO-8859-9.

It could be an invalid string, the detection confidence level is only `0.57` (unless your language is Turkish)

**Comment by apraga** [comment]
> It could be an invalid string, the detection confidence level is only `0.57` (unless your language is Turkish)
That is possible as my language is not Turkish ! I reported anyway so that the error could be dealt with appropriately :)
