### ISSUE TITLE
Indent closing braces

### ISSUE THREAD

**Issue by ghost** [helix-editor/helix#1572]
### Reproduction steps

 
- <kbd>Tab</kbd>
- `{`
- <kbd>Enter</kbd>

### Result

```
// expected
  {
  
  }

// actual
  {
  
}
```

### Environment

- Platform: Linux 
- Terminal emulator: `urxvt` :smile: 
- Helix version: `0.5.0` 

<details><summary>~/.cache/helix/helix.log</summary>

```
please provide a copy of `~/.cache/helix/helix.log` here if possible, you may need to redact some of the lines
```

</details>

### Note

I've only observed this issue in plain text and C buffers

**Comment by kirawi** [comment]
Indentation works as expected now
