### ISSUE TITLE
Select_register command should provide visual feedback

### ISSUE THREAD

**Issue by eugenesvk** [helix-editor/helix#1585]
`select_register` command should provide visual feedback (e.g., via a status bar message) after a register is selected
For example, executing `select_register` then pressing <kbd>5</kbd> should print "register 5 is selected" or something

**Comment by archseer** [comment]
We do print count & pending keys in the bottom right (i.e. `33` before pressing `g` will show up) but looks like we don't do that yet for the register (printing `"@` for example)

https://github.com/helix-editor/helix/blob/333c2949c2b036f8aafa77be2286eb3c135ea269/helix-term/src/ui/editor.rs#L1121-L1128

There's also https://github.com/helix-editor/helix/pull/980 that will make register selection a bit nicer.

**Comment by archseer** [comment]
(Prior art, kakoune renders this as `reg=@` on the statusline, whereas pending keys render as `param=33`
