### ISSUE TITLE
Auto closing brackets doesn't always move the cursor in between them

### ISSUE THREAD

**Issue by eugenesvk** [helix-editor/helix#1586]
Currently the auto closing brackets feature isn't consistent in moving the cursor in between of the brackets after inserting them
It seems to fail after you move a cursor down or press <kbd>Enter</kbd> — then all the brackets continue to be  paired, but then the cursor isn't moved in between them. After some left/right cursor movement (while still in Insert mode) the old behavior seems to start to kick back in
<kbd>End</kbd> also seems to break the cursor movement behavior

I think this should be consistent — the bracket pairing should always move the cursor if it auto-pairs the brackets

Or is there some more intricate logic where it shouldn't always be like that?

**Comment by archseer** [comment]
Hmm, can you provide an asciinema recording? It's likely some interaction with moving around in insert mode -- it was initially completely unsupported but added based on user demands.

**Comment by eugenesvk** [comment]
![Helix0 6@Windows10](https://user-images.githubusercontent.com/12956286/151358514-e28cf383-61a5-4aff-b62b-362556e9b3ed.gif)
Here is a screencast:

- 8s it fails on an emtpy buffer (`hx` command) without any movement just on the first insert
- 16s then it works fine on a new line after exiting insert and entering it again
- 25s then it fails again after a couple of movements within the same insert session as in the previous item

I renamed my config, so this is using the default config

**Comment by CptPotato** [comment]
What version of helix and which OS are you running?

This looks like a duplicate of #1436

**Comment by eugenesvk** [comment]
Helix 0.6 on Windows 10 (though macOS has the same issue)
Strangely though this works fine on an empty line right after I enter the insert mode (example 2 above), though moving around doesn't seem to matter as I can't reproduce it elsewhere but at the end of a line, so it's very likely a duplicate of your issue indeed
