### ISSUE TITLE
Add tabout of paired brackets

### ISSUE THREAD

**Issue by eugenesvk** [helix-editor/helix#1587]
There is already a great description of this feature that I miss in Helix in this [discussion](https://github.com/helix-editor/helix/discussions/1209), excerpted below, so I'm just following the suggestion of creating a feature request based on that

> Tabout actually takes you out of `'' or "" or () ...` in insert mode. For
> example if you want to write `print("something");` then in simpler steps:
> - First you write `print`
> - Then you write `(` which get auto-paired to `()`
> - Now your current state is `print(|)`(`|` represents cursor position)
> - You write `"`: `print("|")`(`|` represents cursor position)
> - Now you type `something`: `print("something|")`(`|` represents cursor position)
> - Notice that you are in insert mode, at the end of `something` and you have to
> move beyond `")`. Here you can either get into normal mode, go to the end, get
> in insert mode and type `;` to complete the task or you can type `")` which will take you to the end so you can type `;` to complete the task.
> - Instead of the two ways given above you can just press `tab` twice at
> `print("something|")`(`|` represents cursor position) to move to the end
> `print("something")|`, still in insert mode to type `;` and complete the task.

**Comment by hzb-ykpcx** [comment]
I have the same need.

**Comment by kirawi** [comment]
This was implemented by https://github.com/helix-editor/helix/pull/4443
