### ISSUE TITLE
Surround replace should provide visual feedback on select/replace

### ISSUE THREAD

**Issue by eugenesvk** [helix-editor/helix#1589]
Currently `surround_replace` operates silently and doesn't tell you that it selected / failed to select that one char around

Let's say we have `(text_in_parethensis)` and the cursor is in the middle

I think it might be worth adding some visual feedback in the status bar like so:
- execute `surround_replace`
- press `(` <br> status bar output: `replacing ( with ...`, also would also be nice if the `()` are now highlighted
- press `[` <br> status bar output: `replaced ( with [`

Currently if there is no match the command is not aborted and still waits for the replacement, think that is a good idea to avoid mistakenly invoking a command bound to the replacement char, but at least it should show a warning that `( not found` or something?

**Comment by alevinval** [comment]
If we would like to see this happen, I can work on that, it would look something like that:

<details>
<summary>Current experience</summary>

https://github.com/helix-editor/helix/assets/1598610/03aaccc5-2237-469e-933f-820b74dd2984
</details>

<details>
<summary>Proposed experience</summary>

https://github.com/helix-editor/helix/assets/1598610/44e891fa-d6d7-4a5f-b009-ee10f556f063
</details>

1. Add textual feedback to the status line
2. Update selection with temporary selection to highlight the extent of the operation, and when the operation is done, restore the original selection.

**Comment by the-mikedavis** [comment]
When this issue was created there was no feedback at all when doing a surround replace. (Try running the 22.03.1 release). Since then the pseudotext display in the bottom right corner has been fixed for the surround keys (https://github.com/helix-editor/helix/pull/4077), so I think this issue could be closed. Showing the command progress in the statusline is too noisy IMO.

**Comment by eugenesvk** [comment]
Statusline migh be too noisy, but this 

> also would also be nice if the () are now highlighted

isn't, and it's also matches the Helix philosophy of acting on selection, so it makes sense to select surrounded items before replacing them

(also, the bottom right corner is too far away from your focus to convey this info)

**Comment by alevinval** [comment]
It seems reasonable to select the positions that are about to be changed, I've opened this PR with a WIP implementation:
https://github.com/helix-editor/helix/pull/7588/files

**Comment by the-mikedavis** [comment]
Closed by #7588
