### ISSUE TITLE
Allow pasting multi cursor multi line yank with only one cursor selection

### ISSUE THREAD

**Issue by eugenesvk** [helix-editor/helix#1591]
Let's say I do the following set of operations to move a few lines with `X` from one file to another
- find all the lines that contain `X` with `select_all` then `select_regex X`
- select the full lines with newlines with `extend_to_line_bounds` 
- yank them in some register with `select_register 1` and `yank`
- open a new buffer with `:new`

Now, how to actually insert all these new lines?
I know of only one way — you need to also extend selection to the same number of lines as you've yanked earlier (to have as many cursors), then you can use `replace_with_yanked` (after selecting the same register) to paste while avoiding unnecessary newlines

However, this is inconvenient as I have to remember the __number of selections__ and also create enough new lines
In some other editors supporting multiple cursors like Sublime I don't have to do that and can just paste with only a __single cursor__ — all the lines get pasted in a nice contiguous block.
Now, if I need to be more precise, I can also create as many cursors in the new file, then the yanked cursors will match the new ones and get inserted there (though if I make a mistake and create an incorrect amount of cursors, then the whole multiline yanked text will be inserted multiple times — once per each cursor)

Is there a way to make pasting in Helix just as smart and __not require multiple selections__ to paste multiple selections? I'm not sure the current behavior of pasting only the first line of a multiline yank if only one cursor exists is more useful

(or maybe there is an I just missed the necessary commands)

P.S.
It seems that the `yank_joined_to_clipboard` command operates the way I want — you don't need to create the same number of cursor selections, but then it doesn't work on registers, only the system clipboard, and registers are a cool feature of Helix.
A `yank_joined_to_register` command would work, though as I mentioned above I think making the paste command paste a "joined" block when only one cursor selection exists is a better default

**Comment by pascalkuthe** [comment]
Closing as yanked joined exists now and there is already https://github.com/helix-editor/helix/issues/1333 for a joined paste command (don't think that should be the default but it could be bound to c-p)
