### ISSUE TITLE
Markdown highlighting issues

### ISSUE THREAD

**Issue by CptPotato** [helix-editor/helix#1597]
These are a few problems I've encountered with the markdown syntax highlighting while updating the `everforest` theme:

1. lists appear to use `punctuation` for the leading `-`/`*`/`1.`/etc. I expected them to use `markup.list` instead.
   - if `markup.list` isn't used for lists, what is it used for?

2. there is only a single color for all headings, some themes might expect one per level (#1618):
   ![image](https://user-images.githubusercontent.com/3957610/151530857-02e288ed-c9ba-4ff3-886d-b1f125a7d4a8.png)

3. changing the theme sometimes causes the list color to be different:
   ![image](https://user-images.githubusercontent.com/3957610/151531868-8e21d170-0c63-4142-b731-0b6c3541f7ca.png)
   - after reloading the theme a few times, sometimes it's red (left) `#e67e80`, sometimes it's orange (right) `#e69875`
   - the corresponding theme keys seem to be `punctuation` and `special`
   - edit: looks like this might be the same problem as 1.

**Comment by archseer** [comment]
> * after reloading the theme a few times, sometimes it's red (left) `#e67e80`, sometimes it's orange (right) `#e69875`

Can you reproduce on commit 83bde1004d596740a7bb63ec7fe2271734492f59 (right before incremental changes?) I had a similar issue with `TODO`/`FIXME` comment highlights when working on the incremental branch but I thought I fixed it.

**Comment by archseer** [comment]
> 2\. there is only a single color for all headings, some themes might expect one per level:

This might be doable with some changes to the queries. Right now we just match against `atx_heading`, but we'd need to match `(atx_heading (atx_h2_marker) (heading_context @style))` etc

**Comment by CptPotato** [comment]
> Can you reproduce on commit [83bde10](https://github.com/helix-editor/helix/commit/83bde1004d596740a7bb63ec7fe2271734492f59) (right before incremental changes?) I had a similar issue with `TODO`/`FIXME` comment highlights when working on the incremental branch but I thought I fixed it.

I'm getting the same behavior on that commit, too. 😕

---

> This might be doable with some changes to the queries. Right now we just match against `atx_heading`, but we'd need to match `(atx_heading (atx_h2_marker) (heading_context @style))` etc

Looks like it's pretty simple. Works pretty much as you suggested (except for the missing theme keys, obviously):

```
(setext_heading (heading_content) @markup.heading.h1 (setext_h1_underline) @markup.heading.marker)
(setext_heading (heading_content) @markup.heading.h2 (setext_h2_underline) @markup.heading.marker)

(atx_heading (atx_h1_marker) @markup.heading.marker (heading_content) @markup.heading.h1)
(atx_heading (atx_h2_marker) @markup.heading.marker (heading_content) @markup.heading.h2)
(atx_heading (atx_h3_marker) @markup.heading.marker (heading_content) @markup.heading.h3)
(atx_heading (atx_h4_marker) @markup.heading.marker (heading_content) @markup.heading.h4)
(atx_heading (atx_h5_marker) @markup.heading.marker (heading_content) @markup.heading.h5)
```

Though, I'm not sure how overriding styles works, i.e. have `"markup.heading" = "#..."` replace all the above.

**Comment by archseer** [comment]
We always use the most specific style, so if you have `markup.heading.h1` defined it will use that, then fall back to `markup.heading` and finally `markup`.

If it works, can you go ahead and make a PR? We can use `markup.heading.1` since that seems to be what other editors used (I did a quick search for "markup.heading" on github, e.g. https://github.com/ukyo/md-anywhere/blob/5eaf5d49fc005353370fe233fc44c8a2364e2f59/ace/mode/_test/tokens_markdown.json#L1-L29)

**Comment by CptPotato** [comment]
Yes, I'll take a look at it soon!
Thanks for clarifying.

**Comment by the-mikedavis** [comment]
I think `markup.list` would make sense for lists. We may even want to go further and use `markup.list.marker` for the `-`/`*`/`1.` and `markup.list.item` for the text of the item.
