### ISSUE TITLE
`gi` should move to/select to first non-whitespace character on the line

### ISSUE THREAD

**Issue by archseer** [helix-editor/helix#163]
Use `find_first_non_whitespace_char2` on `helix_core` to find the position.

https://github.com/helix-editor/helix/blob/9821beb5c4b36f7c34ae6a5cb014b3eb68b9233a/helix-core/src/lib.rs#L21-L31

Function can be further simplified with `char.is_whitespace` & `.find`

**Comment by wojciechkepka** [comment]
Isn't `gi` used for `goto_implementation`?

**Comment by archseer** [comment]
True, we need to find a different key for this one. Maybe `g0`/`gs` = " go start"?

**Comment by kevinsjoberg** [comment]
In Vim `0` is used for start of line while `^` is used for first non-white space. Would it make sense to have `gl` be first non whitespace char and `gs` start of line?

**Comment by wojciechkepka** [comment]
I think `gs` for "real" start of the line aka. first non-whitespace character makes sense. I like the current `gh` and `gl` bindings as they suggest going left and right the same as `h` and `l`.

**Comment by wojciechkepka** [comment]
I submitted the initial PR, if we decide to use a different keybinding I can update accordingly.
