### ISSUE TITLE
Adding confirmation message on save

### ISSUE THREAD

**Issue by premell** [helix-editor/helix#1633]
When saving there is no confirmation that it actually succeeded: 
Helix: 
![image](https://user-images.githubusercontent.com/65544203/153033770-60f4ff4e-2702-43ca-9fbf-18dd84df0186.png)
nvim:
![image](https://user-images.githubusercontent.com/65544203/153034270-29e77c4c-063e-4ba5-8ada-b446c86703e3.png)

PS: This is such a small thing that I wasnt sure if I should even make an issue. However it might be a good issue, also there might be more places where messages would be nice

**Comment by EricCrosson** [comment]
I ran into this a while back, was confused when I tried saving a read-only file. Everything looked good (or at least the same), there was no error (which probably deserves a second issue) but it was confusing when I checked `git status` and found no modifications.

I only learned that I had no write permissions when I tried making the same edit in vim and saw the error on save.

**Comment by sudormrfbin** [comment]
> I ran into this a while back, was confused when I tried saving a read-only file. Everything looked good (or at least the same), there was no error (which probably deserves a separate issue) but it was confusing when I checked `git status` and found no modifications.
> 
> I only learned that I had no write permissions when I tried making the same edit in vim and saw the error on save.

Tracked in #1575.
