### ISSUE TITLE
Add a `:buffer_close_all` command to close all buffers

### ISSUE THREAD

**Issue by jdrouet** [helix-editor/helix#1637]
The current `:buffer_close` (or `:bc`) is a nice command to close a buffer but when many buffers are opened, it can become a bit long to close them all. Closing `helix` completely could be a solution but, in my case, the `rust-analyzer` context get lost and reopening it and analyzing the codebase can take... several minutes...

#### Describe your feature request

Simply adding `:buffer_close_all` command (or `:bca`) to close all the buffers without loosing the `rust-analyzer` context.

**Comment by EpocSquadron** [comment]
It might also be nice to have a "close all but current buffer".

**Comment by EpocSquadron** [comment]
#1593 also partially addresses this.

**Comment by EpocSquadron** [comment]
I think the above merge closes this.
