### ISSUE TITLE
Helix crashes when invoking file picker

### ISSUE THREAD

**Issue by MartinDrees** [helix-editor/helix#1646]
### Reproduction steps
Helix crashes for me on a fresh installation without configuration when invoking the file picker (with `space+f`):
```thread 'main' panicked at 'called `Option::unwrap()` on a `None` value', helix-term/src/ui/mod.rs:161:18```

It also crashes immediately when running `hx .` from the home directory, but not when running `hx [folder]` from the home directory. Confusingly, `hx .` in `~/folder` leads to a crash again.

### Environment

- Platform: Linux
- Terminal emulator:  Kitty (but also on others)
- Helix version: helix 0.6.0 (1bcb624a)

**Comment by kirawi** [comment]
The lines in question are: https://github.com/helix-editor/helix/blob/1bcb624ae65273cad13a3a65c567e0850fb0c9ed/helix-term/src/ui/mod.rs#L158-L162

**Comment by MartinDrees** [comment]
What do you mean exactly? If I run helix inside `env -i bash --norc --noprofile` (without any configurations), it still crashes. If I run `helix [folder]` the proper files are found.

**Comment by kirawi** [comment]
The file name is probably not encoded in UTF-8.

**Comment by MartinDrees** [comment]
Which file name? Helix is already crashing when invoking the file picker, not after choosing. There is not one single file involved here. And if all searched files would not be encoded in UTF-8, why should `helix [folder]` work?
