### ISSUE TITLE
Apple Silicon arm64 release

### ISSUE THREAD

**Issue by chromer030** [helix-editor/helix#1647]
#### Describe your feature request

Please provide binary for macOS arm64, likes provided for Linux arm64.
Thanks.

**Comment by archseer** [comment]
I've tried but I couldn't get the CI build working, it requires cross-compilation since there's no M1 github action runners. Might be resolved once helix is available on homebrew.

If you or anyone can get a working CI configuration I'd be open to accept the change though.

**Comment by jdahm** [comment]
As a datapoint, I currently get an error when building the helix nix flake on my M1 mac.
```
error: a 'aarch64-linux' with features {} is required to build '/nix/store/l4r33m9ys148295f3djjys1hf1vxpvap-crates-io-aho-corasick-0.7.18.drv', but I am a 'aarch64-darwin' with features {benchmark, big-parallel, nixos-test}
       … while realising the context of path '/nix/store/46bk939yfxqfpcr2z246pc8kgpynrnhm-nzkj99qdd3mcyasq7hgm1mc3ah43pk9l-source-crate2nix'
```

Will investigate when I find time.

**Comment by the-mikedavis** [comment]
We might be able to use that to run a custom github actions runner. It wasn't initially supported for a while (https://github.com/actions/runner/commit/088caf5337bf82591743aa02245edf5e12f63fa3) but it looks like actions/runner got M1 support recently: https://github.com/actions/runner/commit/d7694774a4f6d0700a3184fed78b6a12f85c5e7e

**Comment by archseer** [comment]
@yvt Would you mind opening up a PR? We can conditionally skip the test runs since it's tested on the regular build at least.

**Comment by yvt** [comment]
> Would you mind opening up a PR?

Done in #3137
