### ISSUE TITLE
Ctrl key no longer works on when using Windows Command Prompt

### ISSUE THREAD

**Issue by bootradev** [helix-editor/helix#1654]
First occurs in commit https://github.com/helix-editor/helix/commit/23553bd37c5e936c022faa70bef346448a36d6a2
It appears related to updating the crossterm dependency.

### Reproduction steps

Ctrl doesn't work, observe trying to move using Ctrl-D or Ctrl-U, or trying to create a new split using Ctrl-W, Ctrl-V

### Environment

- Platform: Windows
- Terminal emulator: Command Prompt
- Helix version: v0.5.0-463-g23553bd3

No output is written to helix.log

**Comment by archseer** [comment]
\cc @superlou @WindSoilder

**Comment by superlou** [comment]
I'm trying to get the event-read example in crossterm running in the latest crossterm master, but I'm hitting build issues with wepoll. With crossterm 0.22 and [the PR](https://github.com/crossterm-rs/crossterm/pull/619), I was definitely able to see ctrl at the crossterm level before.

**Comment by archseer** [comment]
@CptPotato Hey, sorry to ping you like this. You're running Windows, right? Could you test the crossterm example?

I'd like to determine if we broke crossterm or if this is a helix issue.

**Comment by WindSoilder** [comment]
Sorry for lately reply, I can reproduce this issue well, and I've verify that it works normally in crossterm 0.22..

I've verify `event-read example`, when I type `ctrl-d`, crossterm parse it as `ctrl-D`...  which causes broken..

**Comment by archseer** [comment]
We need to double check https://github.com/crossterm-rs/crossterm/pull/619 then

**Comment by CptPotato** [comment]
> @CptPotato Hey, sorry to ping you like this. You're running Windows, right? Could you test the crossterm example?
> 
> I'd like to determine if we broke crossterm or if this is a helix issue.

No worries, happy to give it a shot:

Looks like I'm getting the same issue. Key bindings that use <kbd>Ctrl</kbd> don't work anymore in helix. As @WindSoilder also pointed out, running crossterm's `event-read` example shows upper case versions of the key pressed when using the <kbd>Ctrl</kbd> modifier, so it seems like a crossterm issue.

Note that not all keys behave like this. For example, <kbd>Ctrl</kbd> + <kbd>m</kbd> is interpreted as `KeyEvent { code: Enter, modifiers: NONE }`, <kbd>Ctrl</kbd> + <kbd>7</kbd> is `KeyEvent { code: Char('_'), modifiers: SHIFT | CONTROL }`, etc.

**Comment by superlou** [comment]
I'm on WIndows 10 Pro, 10.0.19044.
On the current crossterm master, for ctrl+m, I get: `Event: Key(KeyEvent { code: Char('M'), modifiers: CONTROL })`
Lowercase "m" by itself gives `Event: Key(KeyEvent { code: Char('m'), modifiers: NONE })`.

I have the same behavior on the original `windows_key_logic` branch, so I guess it wasn't something that showed up after our commits. @WindSoilder, sorry. I should have noticed this earlier.

**Comment by WindSoilder** [comment]
Sorry for introducing a new bug like this, I make a PR to fix this issue: https://github.com/crossterm-rs/crossterm/pull/629
