### ISSUE TITLE
Issue using helix as git editor

### ISSUE THREAD

**Issue by CptPotato** [helix-editor/helix#1663]
I've been having issues with setting helix as my git editor on one of my machines. Whenever git opens the editor, helix throws an error while parsing the config file and exits:

```
$ git commit
hint: Waiting for your editor to close the file... Error: No command named 'extend_to_line_bounds' for key `keys.normal.x` at line 18 column 1
error: There was a problem with the editor 'hx'.
Please supply the message using either -m or -F option.
```

Interestingly, the same helix config using the same commit (current master) on the same OS (Win10 x64) works when being built on a different machine. Transferring the working binary to the "faulty" machine also works, so something causes the binary being different.

It might have something to do with not checking out all language submodules on the machine where I encounter the error. Other than that I don't see what would change the binary.

Edit: after building with all submodules checked out, the result was the same 😕

**Comment by dead10ck** [comment]
Did you verify that the git hash is the same on both machines? Check git remotes?

**Comment by the-mikedavis** [comment]
I'm not sure how this works on Windows but it sounds like there might be multiple versions of helix on the machine and git tries to open the old one?

```
which -a helix
```

might tell you more on unix but I don't know what the go to is on Windows

**Comment by CptPotato** [comment]
> I'm not sure how this works on Windows but it sounds like there might be multiple versions of helix on the machine and git tries to open the old one?
> 
> ```
> which -a helix
> ```
> 
> might tell you more on unix but I don't know what the go to is on Windows

That's exactly what happened. I somehow had left a "manual" installation in my personal bin folder on top of the actual one installed though cargo 🤦
The `which` command that comes with git on windows worked like a charm.

Thanks!
