### ISSUE TITLE
base16_default_dark theme hover menu item text same color as background

### ISSUE THREAD

**Issue by david-crespo** [helix-editor/helix#1665]
Tried another theme and it was fine so it just seems like a bug in the theme.

### Reproduction steps

Just type in insert mode and get to period where autocomplete pops up. Got the issue in both Rust and TypeScript.

<img width="805" alt="Screen Shot 2022-02-14 at 12 01 32 PM" src="https://user-images.githubusercontent.com/3612203/153910991-e70fbec4-7d43-48b2-b529-7a0f45dda799.png">

<img width="283" alt="image" src="https://user-images.githubusercontent.com/3612203/153911122-d2881ec5-4760-443c-b4d3-7277ca991aa8.png">

### Environment

- Platform: macOS
- Terminal emulator: iTerm 
- Helix version: version only says `helix`. I installed from homebrew on Feb 14, 2022

There's nothing in the log file.

**Comment by archseer** [comment]
\cc @NNBnh
