### ISSUE TITLE
Align selection

### ISSUE THREAD

**Issue by schoenenberg** [helix-editor/helix#1670]
Hi,

I am currently writing a table in markdown and wanted to try out the `&` in selection mode (`align_selection`). So I did a multi-cursor select and tried to run the command, but nothing happend.

Also I didn't find some docs about it. Can you please explain to me how to use it? I am also willing to document this afterwards in the Helix docs.

Thank you very much!

Best regards,
Maximilian

**Comment by QiBaobin** [comment]
Please refer to  [this](https://github.com/helix-editor/helix/pull/1101#issuecomment-968464122)

**Comment by archseer** [comment]
I think `&` is a bit buggy and doesn't quite match kakoune behaviour. I've seen some user reports but I can't find it right now. Here's an example of it misaligning lines:

https://asciinema.org/a/QZlpWUeZGbTEr4PDsUfKaivIn

Doing the same thing in kakoune:

https://asciinema.org/a/klLjDWuPHnfYA96VHMxFZnzYE

I also don't quite understand the difference between `1&`/`2&`/`3&`

**Comment by QiBaobin** [comment]
It didn't consider different spaces/tabs, maybe other cases. Let me change the code and just mirror the kakoune logic anyway so that  kakoune users would be familiar with it at the first place.

**Comment by archseer** [comment]
You need to make a bunch of selections without also selecting the empty space.

https://github.com/helix-editor/helix/pull/1101#issuecomment-968464122

**Comment by archseer** [comment]
For example, type a bunch of words on multiple lines, select all the lines.

`s\w+<Enter>` then `&`. `&` works by inserting enough spaces to make all the cursors align in each column

**Comment by schoenenberg** [comment]
And for some reason it extends the selection to the next line after the `&`..
https://asciinema.org/a/Swi73Ao2yhODbUkympTDot3GJ

**Comment by archseer** [comment]
> I think I understand now what it is doing.. But it feels kind of weird, because the existing spaces are not reused: https://asciinema.org/a/iheaLvJJhB4H2ekLXcvq6MEjg

Yes #1675 has addressed that

**Comment by kirawi** [comment]
Closing due to the discussion above.
