### ISSUE TITLE
AltGr does not work in `select` mode on Windows 10

### ISSUE THREAD

**Issue by KlasMvW** [helix-editor/helix#1680]
### Reproduction steps

* Start Helix
* Enter select mode through keystroke `s`
* type `AltGr+4` (to type a $ sign common in regular expression). No `$` sign is entered in the select window.

 

### Environment

- Platform: Windows 10
- Terminal emulator: command prompt
- Helix version: 0.6.0

</details>

**Comment by archseer** [comment]
https://github.com/helix-editor/helix/issues/595
