### ISSUE TITLE
Home/End don't work under Zellij?

### ISSUE THREAD

**Issue by colemickens** [helix-editor/helix#1694]
Home and End keys don't work under Zellij. They work fine with Neovim under Zellij, however.

I'm using a very recent build from master (the version string in the nix-built binary is wrong so it's hard to say).

Another user seems to note  this was an issue specific to helix: https://github.com/zellij-org/zellij/issues/496#issuecomment-993641925

(I'm on NixOS/Linux)

**Comment by sudormrfbin** [comment]
I can't reproduce with helix afec5448 and zellij `0.18.1`, so this could be some kind of config problem ? The linked post also mentions 

> The `cat` thing produces `^[[H^[[F` for me without zellij, but `^[OH^[OF` when I'm using zellij.

which seems to indicate that it produces the correct sequence _without_ zelllij.
