### ISSUE TITLE
flake.nix should propagate python to helix now that there is Debug Adapter support

### ISSUE THREAD

**Issue by colemickens** [helix-editor/helix#1698]
It seems like Debug Adapter support can utilize python for extra functionality. It would be nice if this were just automatically taken care of for the users of the Nix package. (Or offer a way for a user to extend helix with a default/custom python env)

**Comment by archseer** [comment]
Helix itself doesn't use python so this is probably for CodeLLDB?

**Comment by colemickens** [comment]
Huh, yeah, it must have been! Very happy to hear it, sorry for the noise.
