### ISSUE TITLE
flake.nix: we should report a more accurate version string in --version

### ISSUE THREAD

**Issue by colemickens** [helix-editor/helix#1700]
Hello.

I'm running `hx` from the flake and want to be a good bug reported and include my version string. However, I know right now that the tip-flake-built hx doesn't report the correct version.

Depending on how the app is written, this can be easy (patch a constant) or hard (patch a constant and then find out that clap is ignoring the constant and reaching in the cargo metadata anyway).

**Comment by archseer** [comment]
It reads the git sha, then falls back to only using the package version here: https://github.com/helix-editor/helix/blob/e1a92fd3998aca2a313d4cbf0aca3157eca0b53f/helix-term/build.rs#L5-L15

But that will work incorrectly if building outside of the helix repository but inside a package workspace (e.g. nixpkgs or alpine's git repository) so we need to include https://github.com/tree-sitter/tree-sitter/blob/af00782dfdad02f766a76058e8631cb4edf5d894/cli/build.rs#L36-L81

We could modify `build.rs` so it first looks for a `HELIX_GIT_HASH` then tries to parse `git rev-head`? Then we can inject that variable during a Nix build.

**Comment by the-mikedavis** [comment]
Now with the 22.03 release:

```
$ nix run nixpkgs#helix -- -V
helix 22.03 (d4e45fd4)
```

🎉 

(see https://github.com/helix-editor/helix/pull/1875)

**Comment by the-mikedavis** [comment]
We can't include the git sha in the flake output because of how Nix builds. It's either in a bare directory or not in a git directory at all, so `git rev-parse HEAD` fails.
