### ISSUE TITLE
goto_file_impl doesn't seem to use path relative to current working directory

### ISSUE THREAD

**Issue by chrisboyce** [helix-editor/helix#1701]
When using the "files in selection" goto command, the selected file path is treated as relative to what helix-term determines as the "root" rather than the current working directory, even if helix is launched within the subdirectory. Judging from #1374, it looks like this method for determining the root directory is the intended behavior, so I'm not sure whether this would be classified as a bug or a feature request.

**Comment by chrisboyce** [comment]
To add some context to this, I'm working on a Markdown file which references another Markdown file via the link syntax, `[Link Title](../some_possibly_relative_file.md)`. I suppose from an editor point of view, it does not know how the final Markdown file may be rendered, and thus may not know what path to use when resolving the `some_possibly_relative_file.md` to a system file path. This may be better solved on the LSP side of things, so I'll close this issue.

**Comment by sudormrfbin** [comment]
For `gf` particularly it should be using path relative to the current file, and since LSP isn't involved in this at all it would be better to keep this issue open.

**Comment by remisphere** [comment]
Could'nt this be parametrized per language ?
In LaTeX at least, which I reckon is a bit niche, including other _tex_ files is done relative to the root document.
