### ISSUE TITLE
zj/zk doesn't work same logic with zt/zc/zb

### ISSUE THREAD

**Issue by jiegliu** [helix-editor/helix#1727]
### Environment

- Platform: Windows
- Terminal emulator:  powershell
- Helix version: 0.6.0

as `zt` move the line to a position of top of screen, as zc/zb did the same

`zj` don't move the line to next line of screen,  in helix of 0.6.0, line go up!! windows view go down!
also `zk` has same issue, goes opposite direction.

helix is well known as **consistency** and **reasonableness**, even sometimes sacrificing efficiency.

 i wonder where i did wrong or is it a bug?

or why use 2 models over 1 model to produce same result? is that worth or just a waste gaining nothing?

as `j` move cursor down, `zt` move line upmost, how could `zj` act different to move line up?

there already has a view windows operations with `Ctrl` with `u`, `d`, `f`, `b`, they look same, they work same in moving on screen up/down by harf or whole page.

and `zt`, `zj` look same, work different on different models: `line`, `screen`? Is it neccesary?

why not add `Ctrl-n` and `Ctrl-p` into normal mode if u like manipulate view down/up by a line?

the `Ctrl-n` or `Ctrl-p` is empty now in normal mode.

if it is not conflict with others, why keep the compatibility as a mess by default? rust is not c, helix is not vim.

**Comment by archseer** [comment]
`zj` scrolls the view downwards. If you hold `j` long enough to reach the edge of the screen it will also scroll in the same direction.


> or why use 2 models over 1 model to produce same result? is that worth or just a waste gaining nothing?

Yes, of course it's worth it. It allows you to make small adjustments to the view as opposed to `zt`/`zc`/`zb`.

**Comment by archseer** [comment]
https://github.com/mawww/kakoune/blob/master/doc/pages/keys.asciidoc#view-commands

**Comment by jiegliu** [comment]
```
for a real-world paper(text): we can eye down or head down to look down the content of text
    if the text is short this way worked OK;
    if the text is too long, we need use hand to up the paper(text).
for a virtual/screen paper/text/doc: we can still eye down or head down to look down the content of text
    if the text is short this way worked OK;
    if the text is too long, there are two models:
        1. move screen down ixed logical text
        2. move logical 2D text on fixed screen.
both way will move the content text on screen.

in GUI, ur eye or attention or thinking in moving scroll bar down! so u won't care care the content is up in same time!

but in terminal, helix has no scrollbar, we have to focus on text what we are watching on. we can give a direct target/need: `i wanna see down more info of **text**` so `zj` same to this logic ` i wanna see next line info of **text**`.and `Ctrl-u/d/f/b` are same even they start of Ctrl over z : `i wanna see up/down/forward/backward by a harf or a whole page of **text**`, but `zt`, `zb`, `zc` are not same logic, each of them doesn't mean `I wanna see top/bottom/center of text`.

here weird things happened: the guys look different work in same model, the guys in same format `zj,zk,zt,zb,zc` are using different model.

here is my suggestion.
1. `zt, zb, zc, zj, zk, zh, zl` is `imperative programming` which represent process: put the current line to top/center/bottom/up/down, like definition body{} of function, -> the processing/translation/details itself
2. `Ctrl u/d/f/b/n/p` is `functional programming` which represent target/y/output/produced/result: go up/down/forward/backward/next/previous by a page/line/half page,  like output of function

finally, the look-same things work in same model/logic, which won't puzzle brain.
 
plus, `j` move cursor down, which is like Inperative programming, it's main purpose is for down the cursor. if meet edge of bottom of screen, the screen will up text a line automatically for do u a help, it's a side-effect, not main-purpose. like we delete a char, delete is the main purpose, the latter chars moved left after cursor is an auto-job/pleasure of editor.

if `zj` is move down window, then how explain `zt` ? move current line to top of window? use 2 models? both move window and move 2D text using same format?

helix has been so powerful by u genius guys, i don't wanna see such a great thing suffer any little dust/ash on it.

**Comment by pickfire** [comment]
I do think it looks weird at first with the same keys on kakoune but I don't have any idea on how it can be done better, this seemed to be good enough already. `g` part is consistent but `z` part is mainly view related. If any the infobox already does explains what it does.

**Comment by jiegliu** [comment]
> `zt`/`zc`/`zb` are consistent with `gt`/`gc`/`gb`. Just because the keys are grouped under `g` or `z` does not mean they have to all work the same way.
> 
> As for the scroll direction, that's a [preference](https://ux.stackexchange.com/questions/99686/the-best-scroll-direction-apple-v-s-windows) and you are free to remap `zj`/`zk` to reverse the direction.

again, if it is set by default like what i suggested,  we use less models amount, and more consistency.
`z` is about view it in a position. which `zt` view it top `zj` view it down
`Ctrl` is about view a direction. which `Ctrl-u` view up, `Ctrl-h` view left

also , in this patter, `zt` is consistent with `zj`  by `z` which mean view moving, also consistent with `gt` by  `t` which mean position.

simplicity, consistency by default, if the consistency is defined by users not by default as it can be, why don't we define everything in emacs.

in impl of helix of this part, it is not that much consistency, it's partial consistency, why not be better, since it is 0.6.0, not 1.6.0.

not everything, every aspects of design of kakoune is perfect and can't be better. why not let it be better in helix by default

**Comment by archseer** [comment]
`z` is about view **manipulation**. `Ctrl` is just a general modifier, we also have `Ctrl-w`, `Ctrl-s` etc. that have nothing to do with scrolling.

**Comment by jiegliu** [comment]
> `z` is about view **manipulation**. `Ctrl` is just a general modifier, we also have `Ctrl-w`, `Ctrl-s` etc. that have nothing to do with scrolling.

as i said, there are 2 models of scroll virtual document on screen:
1. move document
2. move screen

helix wanna use 1 word view to made two different operation into one `view` mode
it is cool to do this thing and letting users be away with details
but helix use `z?` and `Ctrl` to move view instead of one pattern.

then user's have to think why use two naming pattern to do one view operation.

and then, finally, the usage of `move document over screen` like move it to where and `move screen over document` like view down/forward are both needed.

if the two models are both needed, how can we don't use 2 models and use 3 models to make a `z?` command is different model with a another `z?` command
needed,

**Comment by jiegliu** [comment]
> `z` is about view **manipulation**. `Ctrl` is just a general modifier, we also have `Ctrl-w`, `Ctrl-s` etc. that have nothing to do with scrolling.

also, we define model better for our goal, not because it it here. if so, we need use `int` `double` `long long int` in rust instead of  `i32, i64, i128`.

for the goal `view`, we need both model `move document to  somewhere of screen` and `move screen to somewhere of document`, like `move line to top of screen, and `move screen forward a page`.

right? so `gt` is same logic to latter one, which move my focus to somewhere, not move document, just by accident, this focus/eye moving is in screen, so no need scrolling doc or scrolling screen.

again, don't invent a new model since here we have more simple model, and the new model spent more consistency and gaining same thing to original models

the original models are simple, move document or move my eye to ensure my eye is on something to some content.

**Comment by jiegliu** [comment]
well, i just find onething, the opposite of moving document, all operation can be classify into one class: functional programming, 
`Ctrl u/d/f/b/n/p` is `i wanna see somewhere`  where doc out of screen.
`h/j/k/l` by a cell(1 x 1), `g h/j/k/l` by a screen(x * y) where doc in the screen. but now missed the `gj/gk`, instead of `gj/gk`, inconsitent key `gh` `gl` are working with `gt` `gb`. and the middle point of `row` is missing while middle point of `column`, `gc` exist, and also `zc` is exist to view it center, and `zm` is here, but `gm` is not in `consistency`

**Comment by jiegliu** [comment]
i'll put many inconsistency design over this issue. 

`Ctrl-A` and `Ctrl-E` exist for two ends of horizontal dimension of showed text of 2D screen in insert mode.
and don't work in normal mode.

reserve these dual keys for what? human need remember `Ctrl-A` can't work in normal mode but in insert mode.
instead, using `gh` is `Ctrl-A` in normal mode. well, what's the pros? if we can use `Ctrl-A` in every mode, we can save `gh` and `gl` for other functions, like moving windows around. since we don't use `gj` `gk` for vertical moving, why import  half part of `hjkl` to represent go somewhere? is this consistent? and ez to reason why? or just a unnecessary memory for human brain.

> Editing is focused on being easy to reason with, even if it takes a keystroke or two more than Vim or Kakoune.

for most part of helix, designs are awesome, but where is here? the issue part, so i only list inconsistent part.

**Comment by LollipopFt** [comment]
@jiegliu i'm new here, so this is just my two cents:
> we need use `int` `double` `long long int` in rust instead of `i32`, `i64`, `i128`

you do realise that this is brought about by the rust lang itself, and has nothing to do with helix right?
> naming these operations with c commands. if u wanna delete char/word, u use cc, cw? and add char/word, using cc, cw, and replace a char/word cc, cw? and sometime cc mean a deletion, sometimes cw means a replacement

ok, i generally don't agree with their 'move cursor and select word' thing with `w` and `b`, it _is_ different from kakoune and vim. so if you had selected the word, seen from the highlight, `c` _will_ delete the selection, so all i can say is look out for the highlight. however, i don't get what you mean by `cc` and `cw`. when i tested it, `cc` just deleted the selection and added the letter `c`, same with `cw`, so i have no idea what you mean.
> why `gh` don't choose the selection? and need an extra `v` to choose?

if you mean select, `v` is needed to select as i don't think people would like to be constantly selecting large portions of text as they move the cursor around, although this differs from `b` and `w`.
> even `hjkl` is not consistency, `h` backward by a char or backward by a cell of horizontal dimension of 2D logical text, `l` forward, then how `j` is not backward by a cell of vertical dimension of 2D logical text. instead, it won't go up, it go down. it is put here as down, only reason is that our finger on j is more flexible/agile and ez to tap over the finger on k.

`hjkl` is very consistent. it is the default in both vim and kakoune, so naturally it is consistent to have this keybinding in helix too. they give you the option to change keybindings anyway.

...i feel as if you know all this though, and i am just getting whooshed.

**Comment by jiegliu** [comment]
1. i put that example for showing that what exist is not always good, even worse.
2. i put that example for showing that even  naming different things into one same pattern, they are still not not same model or even huge difference. and not ez to reason with.
3. emacs/bash Ctrl u/k is existed in helix, so you think it's not common need for select in line and yank?
4. we human has english word to memory keys' meaning e.g. u up d down f forward, and hjkl is consistent with qwerty and vi, which is existed experience usually.  different memory tool.  i show this to say, even it is bad/inconsistent design, since we adapted the env, its hard to change and no need to change

so if possible, be asood as early time.
view only has 2 models, move doc, or view where.
zt, move focused content to top of screen, is in former model. which actually serve for our goal: view bottom after focused content. if in this model, naming it zb.
zj, move focused content down, is n former model. which actually serve or our goal: view up. if in this model, naming it zk.
u can use any one model to achieve the same goal, the former one or the latter one. it doesn't matter to choose which one, but dont mix them together and choose only one model.e.g. little endian and big endian

**Comment by pickfire** [comment]
`Ctrl` was suggested here, but I don't think these methods are used as often to warrant a change to `Ctrl`, that would just waste our `Ctrl` key, I don't see any other better place to put it. (I didn't read the long essay)

I think the issue here is there doesn't seemed to be any better place to put it other than `z`. I will be closing it for now since there is not a clear solution to this, unless you have a better idea other than `Ctrl` then you can reopen the issue.
