### ISSUE TITLE
Partially load the config even when there is an error

### ISSUE THREAD

**Issue by antoyo** [helix-editor/helix#1732]
Hi.

#### Describe your feature request

It would be nice if the config could ignore the errors and continue loading the settings that work.
For instance, if I write `heme` instead of `theme`, helix will show the following error:
```
Bad config: unknown field `heme`, expected one of `theme`, `lsp`, `keys`, `editor` at line 1 column 1
Press <ENTER> to continue with default config
```
but it won't continue loading the other settings, which is inconvenient because you lose your key bindings for instance.

**Comment by pascalkuthe** [comment]
I am closing this according to the discussion in https://github.com/helix-editor/helix/pull/1814.

The TOML config is a stopgap solution that should be kept simple. It will be superseded by a script-based config in the future where partial evaluation is not practical anyway.
