### ISSUE TITLE
Markdown documentation is not shown correctly

### ISSUE THREAD

**Issue by poliorcetics** [helix-editor/helix#1740]
### Reproduction steps

 

Rust file:

```rust
fn main() {
    let a = u32::from_le_bytes([1, 2, 3, 4]);
    dbg!(a);
}
```

You need `rust-analyzer` running, to provide docs. 

Go on `from_le_bytes`, enter `Space+k` too look at the documentation.

Expected: same documentation as https://doc.rust-lang.org/std/primitive.u32.html#method.from_le_bytes

What I got:

![image](https://user-images.githubusercontent.com/7951708/156586674-f76f6f86-02e2-473a-a2b9-02c6642ac6ca.png)

With default theme too:

![image](https://user-images.githubusercontent.com/7951708/156586849-831b8abe-0b5c-46cb-bf0c-4459069d9d80.png)

### Environment

- Platform: Linux 
- Terminal emulator: Kitty
- Helix version: `helix 0.6.0 (0ff3e3ea)` (commit: 0ff3e3ea) 

<details><summary>~/.cache/helix/helix.log</summary>

```
please provide a copy of `~/.cache/helix/helix.log` here if possible, you may need to redact some of the lines
```

</details>

**Comment by sudormrfbin** [comment]
I get the same docs in vscode (and neovim too):

![Screenshot_2022-03-03_21-08-42](https://user-images.githubusercontent.com/23398472/156598279-48c0959c-ade6-4942-bd72-9e0bea6fb64c.png)

Seems like a rust-analyzer issue.

**Comment by poliorcetics** [comment]
Not an helix bug, closing
