### ISSUE TITLE
Failed to execute C compiler

### ISSUE THREAD

**Issue by Dispersia** [helix-editor/helix#1742]
### Environment

- Platform: windows 10, wsl Ubuntu 18.04.6 LTS
- Terminal emulator: command prompt (windows)
- Helix version: latest master

 I receive the exception in the title, however I have verified that i have clang-14, and gcc both installed correctly, and both are able to compile c/c++. I have aliased clang-14 and clang++-14 to just clang and clang++ to see if that would help, but it unfortunately didn't solve it. What needs to be installed along with it?

 I have installed build-essential, which is typically containing all the tools along with it.

didn't mean to create it as a bug ticket - sorry that label can be removed

**Comment by archseer** [comment]
Are the compilers located in $PATH or specified under the `CC` env var? Can you post the whole error message?

**Comment by Dispersia** [comment]
Sorry, had to wait to get back to office.

Full error
`--- stderr
  thread '<unnamed>' panicked at 'called `Result::unwrap()` on an `Err` value: Failed to execute C compiler

  Caused by:
      No such file or directory (os error 2)', helix-syntax/build.rs:172:36
  note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
  thread '<unnamed>' panicked at 'called `Result::unwrap()` on an `Err` value: Failed to execute C compiler

  Caused by:
      No such file or directory (os error 2)', helix-syntax/build.rs:172:36
  thread '<unnamed>' panicked at 'called `Result::unwrap()` on an `Err` value: Failed to execute C compiler

  Caused by:
      No such file or directory (os error 2)', helix-syntax/build.rs:172:36
  thread '<unnamed>' panicked at 'called `Result::unwrap()` on an `Err` value: Failed to execute C compiler

  Caused by:
      No such file or directory (os error 2)', helix-syntax/build.rs:172:36
  thread '<unnamed>' panicked at 'called `Result::unwrap()` on an `Err` value: Failed to execute C compiler

  Caused by:
      No such file or directory (os error 2)', helix-syntax/build.rs:172:36
  thread '<unnamed>' panicked at 'called `Result::unwrap()` on an `Err` value: Failed to execute C compiler

  Caused by:
      No such file or directory (os error 2)', helix-syntax/build.rs:172:36
  thread '<unnamed>' panicked at 'called `Result::unwrap()` on an `Err` value: Failed to execute C compiler

  Caused by:
      No such file or directory (os error 2)', helix-syntax/build.rs:172:36
  thread '<unnamed>' panicked at 'called `Result::unwrap()` on an `Err` value: Failed to execute C compiler

  Caused by:
      No such file or directory (os error 2)', helix-syntax/build.rs:172:36
  thread 'main' panicked at 'assertion failed: `(left == right)`
    left: `50`,
   right: `58`', helix-syntax/build.rs:200:5`

gcc, g++, clang, clang++, clang-14, and clang-14++ are all in path.

I tried exporting each as CC and unfortunately it didn't seem to change anything

**Comment by jdahm** [comment]
I'm also getting this tonight when executing `cargo build` in the development shell.

**Comment by archseer** [comment]
The issue here isn't that it failed to find a compiler, but that some folders are missing. Did you recursively clone all the submodules?

**Comment by archseer** [comment]
The grammars now don't use submodules anymore, can you pull then run the build per https://github.com/helix-editor/helix#installation ? (`hx --grammar fetch && hx --grammar build`)

**Comment by Dispersia** [comment]
I did get submodules recursively, but I can't build helix-term, so I won't be able to run the command there. It did work on one PC to do it, but when I get back to my comp I'll check if the folders are actually empty or not (even though it did work on a different comp)

**Comment by pickfire** [comment]
Which commit are you in now?

**Comment by Dispersia** [comment]
Ah sorry, I didn't realize you meant to pull, i just deleted the old and re cloned and followed the instructions and everything built correctly. Thanks!

**Comment by baitwo02** [comment]
i am in win11 and use scoop installed gcc cmake make helix, when i execute:
`hx --grammar build`
it returns `Failed to execute C/C++ compiler`
btw, i user nushell
