### ISSUE TITLE
Trouble getting syntax highlighting 

### ISSUE THREAD

**Issue by wush303** [helix-editor/helix#1748]
**Description**
When opening a haskell file there is no syntax highlighting and the haskell language server does not seem to run.
HLS works fine when running `haskell-language-server-wrapper` from terminal.
In my config i have `display-messages = true`.
It also indents with 4 spaces instead of the 2 spaces specified in the languages.toml, which might indicate there is something wrong with language.toml for haskell?

This issue only happens when opening .hs files. When opening other file formats, it works flawlessly. 
I tested with python or rust files.

Can anyone help me?

**Comment by the-mikedavis** [comment]
Which version of helix are you running? Haskell was re-enabled in https://github.com/helix-editor/helix/pull/1520 which was merged after the last release (0.6.0). You'll need to build from source in order to use haskell syntax highlighting (or await the next release)

**Comment by wush303** [comment]
Yes you were completely right. After installing from source it works perfectly. Thanks for the help!

**Comment by Max0nyshchenko** [comment]
@wush303 Can you provide some example with helix LSP, I've installed helix lsp by ghcup, added language to languages.toml but cannot get it to work anyway, still have "Language server not active for current buffer" issue.

Here is my languages.toml

[[language]]
name = "haskell"
scope = "source.haskell"
injection-regex = "haskell"
file-types = ["hs"]
roots = []
auto-format = false
comment-token = "--"
language-server = { command = "haskell-language-server-wrapper", args = ["--lsp"] }
indent = { tab-width = 2, unit = " " }

HLS working from terminal. But cannot get it to work with .hs files

**Comment by wush303** [comment]
@Max0nyshchenko  I didn't add anything to the languages.toml and relied on the default one.
I installed hls via ghcup as you. What ultimately ended up fixing my issue was just building helix from source and installing hls.

**Comment by Max0nyshchenko** [comment]
@wush303 Thx, deleting languages.toml did the thing.
