### ISSUE TITLE
write-quit-all can hang when multiple files are opened

### ISSUE THREAD

**Issue by antoyo** [helix-editor/helix#1759]
### Reproduction steps

 * Download these two files:
   * https://gist.github.com/antoyo/0a5cf7c2578ee9dbbcd585b84511682a
   * https://gist.github.com/antoyo/2187862df59fe383fddf3b778ed46039
 * Open them both using `helix gcc_asm gcc_asm2`.
 * Run the command: `:write-quit-all`.

You'll notice that the TUI hangs and helix uses 100% CPU.
I let it ran for over 5 minutes.

### Environment

- Platform: Linux
- Terminal emulator: Alacritty
- Helix version: helix v0.6.0

<details><summary>~/.cache/helix/helix.log</summary>

Nothing relevant

</details>

**Comment by matszczygiel** [comment]
I also noticed that issue.

**Comment by the-mikedavis** [comment]
I believe this was the same problem as https://github.com/helix-editor/helix/issues/3975. I don't see this behavior anymore; I think it was fixed by #2267
