### ISSUE TITLE
Add helix package on AUR, built from source, from github releases

### ISSUE THREAD

**Issue by gbaranski** [helix-editor/helix#176]
Hi, what do you think about that? AFAIK that's how most AUR packages work, for example [ncspot](https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=ncspot).

**Comment by archseer** [comment]
There's already two: helix-bin that provides the binary release, and helix-git that compiles from source.

**Comment by wojciechkepka** [comment]
There should be a third one that compiles release from a source named `helix`, that's what usually happens:
- `{name}-bin` for prebuilt binary
- `{name}-git` for the latest master branch built from the source
- '{name}' for latest release built from source

**Comment by wojciechkepka** [comment]
I actually wanted to add the `helix` package to AUR but I noticed that the source packages from GitHub releases don't contain all the syntax submodules in `helix-syntax`.

**Comment by wojciechkepka** [comment]
I uploaded a package that checks out the correct tag and builds it from source as `helix`. I'm unable to verify if it works currently as I don't have access to my Arch Linux workstation, but I'll check it out later today and fix it up if it's required.

If you perhaps get a chance to check it out let me know if it builds properly.

https://aur.archlinux.org/packages/helix/

**Comment by gbaranski** [comment]
@pickfire publishing package on AUR don't  
require any verification. 
@wojciechkepka thanks for publishing, I will check if it works in few hours. I think it would be better to change `sources` in PKGBUILD to
```
https://github.com/helix-editor/helix/archive/v${pkgver}.zip
```
And then remove manual `git checkout` in `prepare` function. [ncspot](https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=ncspot#n17) is nice example of making use of that.

**Comment by wojciechkepka** [comment]
> @pickfire publishing package on AUR don't
> require any verification.
> @wojciechkepka thanks for publishing, I will check if it works in few hours. I think it would be better to change `sources` in PKGBUILD to
> 
> ```
> https://github.com/helix-editor/helix/archive/v${pkgver}.zip
> ```
> 
> And then remove manual `git checkout` in `prepare` function. [ncspot](https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=ncspot#n17) is nice example of making use of that.

As i mentioned, the packaged zip sources don't contain the syntax submodules needed for the build, thats why I decided to still use git checkout with appropriate tag.

**Comment by gbaranski** [comment]
> > @wojciechkepka thanks for publishing, I will check if it works in few hours. I think it would be better to change `sources` in PKGBUILD to
> > ```
> > https://github.com/helix-editor/helix/archive/v${pkgver}.zip
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > And then remove manual `git checkout` in `prepare` function. [ncspot](https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=ncspot#n17) is nice example of making use of that.
> 
> As i mentioned, the packaged zip sources don't contain the syntax submodules needed for the build, thats why I decided to still use git checkout with appropriate tag.

Ah okay, I misunderstood. `helix` package failed to build for me, 
```
==> Starting prepare()...
fatal: A branch named 'master' already exists.
==> ERROR: A failure occurred in prepare().
    Aborting...
error: failed to build 'helix-0.0.10-1':
:: Packages failed to build: helix-0.0.10-1
```
 I think `-b` flag should be removed in [PKGBUILD prepare](https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=helix#n22)

**Comment by wojciechkepka** [comment]
> I think `-b` flag should be removed in [PKGBUILD prepare](https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=helix#n22)

That's right, I updated the `PKGBUILD`. Tested on my machine and should work now.

**Comment by gbaranski** [comment]
Works for me aswell, thanks.
