### ISSUE TITLE
write-quit-all will write files without any changes

### ISSUE THREAD

**Issue by antoyo** [helix-editor/helix#1760]
### Reproduction steps

 * Open a file that doesn't exists: `helix new_file`.
 * Use the command `:write-quit-all`.

The file will be created while I would expect the file to not be created because no changes were made (vim's behavior).
I believe the file should not be created because that's convenient to users that have a mapping to `:write-quit-all`.

Using `:write` alone should probably still create the file though (vim's behavior).

### Environment

- Platform: Linux
- Terminal emulator: Alacritty
- Helix version: helix v0.6.0

<details><summary>~/.cache/helix/helix.log</summary>

Nothing

</details>

**Comment by matoous** [comment]
This was fixed as a by-product of: https://github.com/helix-editor/helix/pull/1444.

**Comment by antoyo** [comment]
Indeed. Thanks!
