### ISSUE TITLE
Make `]o` (comment textobject) something else

### ISSUE THREAD

**Issue by pickfire** [helix-editor/helix#1764]
Only problem with # is that it is a shifted key usually, making it harder to quickly use, and breaks the pattern of using a letter for the other textobjects. That said, maybe we open an issue for further discussion?

_Originally posted by @EpocSquadron in https://github.com/helix-editor/helix/pull/1605#discussion_r820367709_

The issue with `]o` is that it in not intuitive, `o` does not have any link to comment, maybe `#` will work better I guess, but if we want more consistency, maybe we can change `ctrl-c` to `#`, which makes it similar to other languages. Alternatively `/` could be used I think.

**Comment by EpocSquadron** [comment]
Just to fill in, `o` was chosen because it is the second letter, and `m` was already taken. `t` or `n` are also in the word, but feel more likely to be needed for something else.

**Comment by pickfire** [comment]
What about `/`?

**Comment by EpocSquadron** [comment]
IMO same problem as #, it's used as a delimiter for regexes in many languages, and had the meaning of relating to search elsewhere. Between the two I would pick #. I still think a letter is the best option though.

**Comment by EpocSquadron** [comment]
Another possibility might be too reclaim c for comment, then change the class textobject to something like s for struct, or something.

**Comment by pickfire** [comment]
I wonder what @sudormrfbin think about these since he did the keys for class.

**Comment by sudormrfbin** [comment]
I personally like the current keybinds, both `]o` for comment and `]c` for class. `o` doesn't seem too bad for comment since it's the second letter, and there's always the infobox to help you along if you forget the correct key ;)

**Comment by jeyj0** [comment]
Personally, I would be for reclaiming `c` for comment. Comments exist in pretty much every programming language, and it's pretty common to interact with them (at least for me).

**Comment by zyansheep** [comment]
One advantage to `o` is that it is close to the `[` key, making it a one-handed chord. `[c` is a little bit slower to hit, especially if you wanna spam [o[o[o[o[o[o[o[o to skip between comments fast. Not sure how major of a use-case this is though...

Try this on your keyboard to see which one is faster: `[o[o[o[o[o[o[o[o` vs `[c[c[c[c[c[c[c[c[c[c`

**Comment by jeyj0** [comment]
1. If you need to "spam" a key combination, you should probably have used another way to move instead
2. This argumentation depends on a default layout. For me, `[c` is one-handed, while `[o` isn't. "Location" of keys should rarely be a factor, in my opiniot
