### ISSUE TITLE
Find_next_char and siblings should not select

### ISSUE THREAD

**Issue by dbekasow** [helix-editor/helix#1772]
I am confused when it comes to using the f, F, t, T keys. From the documentation I read that the cursor should jump to the char by executing the function "find_x_char". However, currently the text is selected at the same time. In my opinion this would be a vf x .

Kakoune explicitly talks about select. This is easy to understand. My question is: does Helix want to take over the functionality of Kakoune and is "find" actually "select". Or is the additional selection a bug?

**Comment by the-mikedavis** [comment]
I think this is a bug in the documentation: afaik these should behave the same as they do in Kakoune, except with `vf<x>` and `vt<x>` extending an existing selection like Kakoune's `F<x>` and `T<x>`.

**Comment by the-mikedavis** [comment]
No I think that's a good point - we should probably use the same language as Kakoune for the sake of consistency. Would you be interested in opening a PR?

The command descriptions are [here](https://github.com/helix-editor/helix/blob/194b09fbc1edb2d0ccdadc53ec0893f61dbded8e/helix-term/src/commands.rs#L239-L244) and the [keymap docs](https://github.com/helix-editor/helix/blob/194b09fbc1edb2d0ccdadc53ec0893f61dbded8e/book/src/keymap.md?plain=1#L24-L27) should probably be updated as well.

**Comment by debekas** [comment]
> No I think that's a good point - we should probably use the same language as Kakoune for the sake of consistency. Would you be interested in opening a PR?

Yes :+1:

**Comment by pascalkuthe** [comment]
Closing since #1776 was closed
