### ISSUE TITLE
Helix hangs when opening Zig files

### ISSUE THREAD

**Issue by nekodjin** [helix-editor/helix#1800]
### Reproduction steps

Open a `.zig` file.
[asciicast](https://asciinema.org/a/476243)

### Environment

- Platform: WSL2/Arch
- Terminal emulator: N/A
- Helix version: 0.6.0 from Arch community/ repo

### Misc.

This happens both when invoking helix with a command-line argument and when using the `:o` command. The former is an annoyance as I can escape with Ctrl-C; the latter is properly problematic as there is no escape method I am aware of save exiting the entire tab in WinTerm.

**Comment by the-mikedavis** [comment]
this looks like https://github.com/helix-editor/helix/issues/1269

I can reproduce this with `helix-0.6.0` from nixpkgs, even when doing `hx foo.zig` when `foo.zig` does not yet exist. I don't see a hang when building from today's master though. Is there a `helix-git` option in the arch repos? If not, you may need to build from source or await the next release.

**Comment by nekodjin** [comment]
There is a `helix-git` option in the AUR; I can confirm that it edits zig files just fine.
