### ISSUE TITLE
Keymaps of `|` and `Alt-|` not showing up correctly in the book

### ISSUE THREAD

**Issue by feathecutie** [helix-editor/helix#1808]
The keymaps of `|` and `Alt-|` don't show up correctly in the book, seems like mdBook parses the `|` as a table seperator even though it's in a code block.
Simple escaping with `\|` doesn't seem to help; when I tried that, both letters (`\` and `|`) show up instead of just the escaped `|`.
I didn't find any other simple solution to this, so this might also be unintended behaviour of mdBook, not sure

**Comment by archseer** [comment]
@EpocSquadron looks like this was broken here https://github.com/helix-editor/helix/commit/e8cc7ace759c2aaf3a14257a5c48e0f8a960d4cd#diff-46423c6b7f16676c926dfbaca17d3be56f937ac5838bb2f62e327a114f08d05eL89-L90

**Comment by EpocSquadron** [comment]
> @EpocSquadron looks like this was broken here [e8cc7ac#diff-46423c6b7f16676c926dfbaca17d3be56f937ac5838bb2f62e327a114f08d05eL89-L90](https://github.com/helix-editor/helix/commit/e8cc7ace759c2aaf3a14257a5c48e0f8a960d4cd#diff-46423c6b7f16676c926dfbaca17d3be56f937ac5838bb2f62e327a114f08d05eL89-L90)

Sorry about that! I guess the `|` was being interpreted as a table separator there, I had thought it was just done with manual code tags by accident.
