### ISSUE TITLE
Crash when opening elixir files

### ISSUE THREAD

**Issue by VitorTrin** [helix-editor/helix#181]
Version: helix 0.0.10 (using both helix-bin and helix-git from aur)

How to reproduce: Open elixir file

Result:

```
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: QueryError { row: 139, column: 2, offset: 3621, message: "remote_identifier", kind: NodeType }', helix-core/src/syntax.rs:166:22
```

**Comment by archseer** [comment]
@IceDragon200 looks like some of the syntax queries are invalid

**Comment by IceDragon200** [comment]
Strange it worked originally, I'll look into it

**Comment by archseer** [comment]
https://github.com/ananthakumaran/tree-sitter-elixir/commits/master/queries/highlights.scm

**Comment by IceDragon200** [comment]
Okay copying the queries from the latest tree fixed the problem, I'll open a PR shortly with it
