### ISSUE TITLE
Wrong parenthesis matching

### ISSUE THREAD

**Issue by jeyj0** [helix-editor/helix#1815]
### Reproduction steps

Save the following contents into a file ending is `.hs` (haskell):

```haskell

        applyNoFilter = ("", [])
        applyPropertyKindFilter
            :: forall e name
             . ( Enum e
               , Show e
               , ToField e
               , KnownSymbol name
               )
            => Proxy name -> [e] -> (a, b)
```

The round parenthesis `)` that is on its own line does not match with the correct opening one in an earlier line, but instead with the very last one for some reason. Same for its actually matching opening parenthesis.

 

Here's an asciinema illustrating the behavior: https://asciinema.org/a/bFbojsv8bM8jjHpOB1kz5FixF

### Environment

- Platform: Linux (NixOS)
- Terminal emulator: alacritty
- Helix version: v0.5.0-887-gc0dbd6dc 

<details><summary>~/.cache/helix/helix.log</summary>

```
please provide a copy of `~/.cache/helix/helix.log` here if possible, you may need to redact some of the lines
```

</details>

**Comment by pascalkuthe** [comment]
This was fixed by #7242
