### ISSUE TITLE
Document the `--health` command

### ISSUE THREAD

**Issue by EricCrosson** [helix-editor/helix#1822]
PR https://github.com/helix-editor/helix/pull/1669 introduced the `hx --health` command, which I used tonight to help a friend diagnose LSP on his machine. It works to great effect! But I had to look at the PR to find the [following information](https://github.com/helix-editor/helix/pull/1669#issuecomment-1055290287) about the color-coded output:

> (red for not found, green for found, yellow for no configuration)

and noticed the `--health` command isn't documented on the web documentation anywhere. 

I took a quick look to see if I could add this documentation myself but couldn't come up with a strong opinion on where it should live.

**Comment by sudormrfbin** [comment]
We could add a separate troubleshooting section and mention it there, with a link to it from the installation section. It's also possible to run `hx --health LANG` to see diagnostics for a particular language, whereas `hx --health` is meant to give a bird's eye view of everything.

**Comment by EricCrosson** [comment]
Closed by #2357 -- thanks @RobWalt!
