### ISSUE TITLE
panick while exessively hitting tab with `theme` in the commandline 

### ISSUE THREAD

**Issue by wucke13** [helix-editor/helix#1823]
thread 'main' panicked at 'assertion failed: self.is_char_boundary(n)', /build/rustc-1.57.0-src/library/alloc/src/string.rs:1714:29

### Reproduction steps

Not easily reproducible

### Environment

- Platform: Linux
- Terminal emulator: Alacritty 0.10.0
- Helix version: hx 0.6.0

**Comment by sudormrfbin** [comment]
Do you have any custom themes in the config directory ? What's the output of `ls -1 ~/.config/helix/runtime/themes/` ?

**Comment by wucke13** [comment]
> Do you have any custom themes in the config directory ?

No, this was with a vanilla setup, not even `.config/helix` existed.

> What's the output of ls -1 ~/.config/helix/runtime/themes/ ?

Unfortunately not very insightful:

`"/home/$USER/.config/helix/runtime/themes": No such file or directory (os error 2)`

**Comment by archseer** [comment]
Duplicate of #1888
