### ISSUE TITLE
Support for LSP Code Actions

### ISSUE THREAD

**Issue by gbaranski** [helix-editor/helix#183]
- [x] Document edits #478
- [x] Document operations 29e684941389f949491efe4d9807a0edd1facee3
- [x] Workspace changes 29e684941389f949491efe4d9807a0edd1facee3
- [x] Code action command #1304

**Comment by matoous** [comment]
> Code action command(example needed)

added in https://github.com/helix-editor/helix/pull/1304

>  Workspace changes(example needed)

I think we should create separate issue for this one, there's plenty of LSP calls for workspaces and it will require a lot of work.

>  Document operations(example needed)

I am not sure what this one means, would you please remember?

**Comment by gbaranski** [comment]
> > Code action command(example needed)
> 
> added in #1304
> 
> > Workspace changes(example needed)
> 
> I think we should create separate issue for this one, there's plenty of LSP calls for workspaces and it will require a lot of work.
> 
> > Document operations(example needed)
> 
> I am not sure what this one means, would you please remember?

I've updated the original comment, it looks like everything is done, let me know if I'm missing something.
