### ISSUE TITLE
More scopes for theme-ing + Fix request

### ISSUE THREAD

**Issue by ZuixAlias** [helix-editor/helix#1831]
Maybe add more scopes for detailed/ a bit better theming...hehe.

[ FIX REQUEST (For C#, not sure of other lang right now) ]
As shown in the picture, 
- Some function names are not rendered with correct color (ones that contain the language inbuilt data types before them) and inside the function, the called function names also don't have colors
- `keyword.control` colors are not applied to C# (not sure for other langs, for rust they have correct color)

There could be more, i will update as i explore helix, lol.

![view](https://user-images.githubusercontent.com/96847142/158915644-c1e7a482-30aa-422b-ade9-d40a4b2cedf5.png)

**Comment by archseer** [comment]
This is all up to the highlighting queries for each language. You can make improvements to https://github.com/helix-editor/helix/blob/master/runtime/queries/c-sharp/highlights.scm

**Comment by archseer** [comment]
For example some languages just use `keyword` and don't offer `keyword.control`

**Comment by archseer** [comment]
You also didn't specify what helix version you're running. There was a recent PR: https://github.com/helix-editor/helix/pull/1795

**Comment by ZuixAlias** [comment]
Ohh! That solves it!
I am using v0.6.0
You see, i am new to github, so i am not sure how to get that version 😅 (I am guessing i need to build helix from source?) (I tried but build fails with some header file not found error)

**Comment by archseer** [comment]
`hx -v` will show you the current version

**Comment by archseer** [comment]
Closed by #1795
