### ISSUE TITLE
`OmniSharp` language server usage help needed

### ISSUE THREAD

**Issue by ZuixAlias** [helix-editor/helix#1832]
I have `OmniSharp` added to my path...helix also has lsp config prefigured, so the server should run when a project/.cs is opened in helix right?
I am unable to figure out how to use it, can someone please help me...
(I want to know how get the auto-complete working...everything else is optional)

**Comment by archseer** [comment]
https://github.com/helix-editor/helix/wiki/Troubleshooting

**Comment by ZuixAlias** [comment]
Okay, now `OmniSharp` runs with hx but does not work...the log says `request timed out`...any idea?

**Comment by 0rphee** [comment]
@ZuixAlias hey! how did you get it working? I cant manage to do it myself... How did you install omnisharp?

**Comment by ZuixAlias** [comment]
I don't use it anymore but it was easy to setup, i think you just need to :
- Add the folder containing the omnisharp binary to your environment path
- Add language config for helix (it may not be needed since helix prefers omnisharp by default) :
```
[[language]]
name = "c-sharp"
language-server.command = "OmniSharp"
```
I can't remember anything else that i might have done...this should do it though.

**Comment by 0rphee** [comment]
Oh, but you're on windows right? i'm on macos...
