### ISSUE TITLE
Slow performance when editing initial git commit message

### ISSUE THREAD

**Issue by slinlee** [helix-editor/helix#1836]
### Summary

I have noticed that when I create a new git project, editing the message for the first commit in helix is extremely slow. It locks for seconds at a time between keystrokes before anything appears on screen.

### Reproduction Steps

I tried this:

Create a project
1. `mkdir hardhat`
2. `cd hardhat`
3. `npm init --yes`
4. `npm install --save=dev hardhat`
5. `echo "node_modules" > .gitignore
6. `git init`
7. `git add *`
8. `git commit -av`  <- assumes `hx` is set as the default git editor

I expected this to happen:

- When editing the commit message for the first commit, I expect helix to be fast and responsive, as usual.

Instead, this happened:

- Editing the message is extremely laggy. It takes seconds for characters to appear in insert mode. 

### Platform

Linux

### Terminal Emulator

'Terminal' on ChromeOS

### Helix Version

v0.5.0-887-gc0dbd6dc

**Comment by the-mikedavis** [comment]
I suspect the `package-lock.json` is pretty large for this first commit, right? Highlighting for verbose commits (`git commit -v`) can be horribly laggy when there are many lines changed. I updated tree-sitter-git-commit with a fix that is very snappy even on commits with thousands of lines changed. It should make its way into the next release. In the meantime, you can avoid the slow performance by not using the `-v` flag when you know a commit will be very large.
