### ISSUE TITLE
panic when piping `hx --health` through `head`

### ISSUE THREAD

**Issue by the-mikedavis** [helix-editor/helix#1841]
### Summary

Piping `hx --health` through `head` gives a panic. I'm not sure if it's something to do with my terminal (kitty). Piping through `less` works perfectly, even with colors.

### Reproduction Steps

[![asciicast](https://asciinema.org/a/sZaajKhddtmyh5EEBsIxUxmFU.svg)](https://asciinema.org/a/sZaajKhddtmyh5EEBsIxUxmFU)

```
$ hx --health | head -n 10
```

### Helix log

N/A: no log lines were produced.

<details><summary>But here's the backtrace...</summary>

```
thread 'main' panicked at 'failed printing to stdout: Broken pipe (os error 32)', library/std/src/io/stdio.rs:1187:9
stack backtrace:
   0:     0x560d47de313c - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::h3e2b509ce2ce6007
   1:     0x560d4773a1ac - core::fmt::write::h753c7571fa063ecb
   2:     0x560d47ddb565 - std::io::Write::write_fmt::h2815c0519c99ba09
   3:     0x560d47de62e5 - std::panicking::default_hook::{{closure}}::h78d3e6cf97fc623d
   4:     0x560d47de5f63 - std::panicking::default_hook::hda898f8d3ad1a5ae
   5:     0x560d47de696c - std::panicking::rust_panic_with_hook::h1a5ea2d6c23051aa
   6:     0x560d47de665a - std::panicking::begin_panic_handler::{{closure}}::h07f549390938b73f
   7:     0x560d47de3664 - std::sys_common::backtrace::__rust_end_short_backtrace::h5ec3758a92cfb00d
   8:     0x560d47de63bd - rust_begin_unwind
   9:     0x560d476c1d01 - core::panicking::panic_fmt::h3a79a6a99affe1d5
  10:     0x560d47dda7d1 - std::io::stdio::_print::h4dabb72d0b79d2de
  11:     0x560d47bba8d5 - helix_term::health::languages_all::h64ed386eb51c8a24
  12:     0x560d47c84923 - <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll::h45a31bbdd9e955af
  13:     0x560d47c543ce - tokio::park::thread::CachedParkThread::block_on::h8bfc4daa5e5d5900
  14:     0x560d47cbc559 - tokio::runtime::thread_pool::ThreadPool::block_on::hfbbc83b50318e9de
  15:     0x560d47c81e83 - tokio::runtime::Runtime::block_on::hdab0bdfd50a45238
  16:     0x560d47c52eaa - hx::main::h7b50b857af503774
  17:     0x560d47c55fe3 - std::sys_common::backtrace::__rust_begin_short_backtrace::ha19c1e7ad046c834
  18:     0x560d47c68c8d - std::rt::lang_start::{{closure}}::ha7afa477cb4d71de
  19:     0x560d47de279e - std::rt::lang_start_internal::h52e73755f77c7dd9
  20:     0x560d47c562e2 - main
  21:     0x7fb18ef68790 - __libc_start_main
  22:     0x560d476f041a - _start
  23:                0x0 - <unknown>
```

</details>

### Platform

Linux (NixOS 21.11)

### Terminal Emulator

kitty 0.23.1

### Helix Version

master at 533cca7195b5ab36e0a1fa4863d00f6c11cb41b9

**Comment by dead10ck** [comment]
@sudormrfbin looks like rather than using `println!` we'll have to handle writing to stdout ourselves and explicitly handle a broken pipe error to just quit without error.

**Comment by sudormrfbin** [comment]
If anyone wants to take this up, [here](https://stackoverflow.com/a/65760807/7115678) is an SO post describing the current behavior and how to fix it, and these are the functions where the diagnostics are printed:

https://github.com/helix-editor/helix/blob/bee05dd32a685b58015514492525673b1b568b0d/helix-term/src/health.rs#L43-L219

The functions will have to return an `io::Result<()>` and all the `println!()` calls will have to be replaced by `writeln!()?`, and then in the calling code `io::ErrorKind::BrokenPipe` will have to be handled.

**Comment by npate012** [comment]
I would like to attempt to fix this. Thanks.

**Comment by sudormrfbin** [comment]
@npate012 Go for it !

**Comment by npate012** [comment]
I have created #1876 for this. I hope it looks good. Thanks.
