### ISSUE TITLE
Cursor not following + Possible random `undo` in `Insert Mode` crash + Version check issue

### ISSUE THREAD

**Issue by ZuixAlias** [helix-editor/helix#1842]
### Summary

[ CURSOR ISSUE ]
I have set a key bind to delete a word at a time and there is this issue with the cursor : [cursor_issue.mp4](https://mega.nz/file/Rhkz3A4L#N-b7g63s9S54reKxmQ7H7dEMtvqgISEqGP9ZzXvM7po)

[ UNDO CRASH ISSUE ]
I also set a keybind (`Ctrl + Z`) to undo whenever possible for Insert Mode and Normal Mode., undoing lead to a crash once in a while (twice or thrice) when experimenting with keybinds...though it seems fine now (i removed undo from normal mode) i will update here with proper log info if i encounter it again...(the log info that is attached may not be related because i messed up the timing)

[ VERSION CHECK ISSUE ]
Also uisng `hx -V` in `CMD/ Windows Terminal/ etc...` just outputs `helix` (When run as Admin + Non-Admin both)...

![version](https://user-images.githubusercontent.com/96847142/159098921-66404fc8-ce6d-47e8-993b-3c6f4581c0fa.png)

### Helix log

<details><summary>~/.cache/helix/helix.log</summary>
```
helix_term::application [WARN] unhandled window/showMessage: ShowMessageParams { typ: Error, message: "overly long loop turn: 362.7477ms" }
2022-03-19T03:12:12.121 helix_lsp::transport [ERROR] <- Server error: content modified
2022-03-19T03:12:12.326 helix_lsp::transport [ERROR] <- Server error: content modified
2022-03-19T03:12:12.863 helix_lsp::transport [ERROR] <- Server error: content modified
2022-03-19T03:12:12.864 helix_term::application [WARN] unhandled window/showMessage: ShowMessageParams { typ: Error, message: "overly long loop turn: 148.6602ms" }
```
</details>

### Platform

Windows

### Terminal Emulator

Windows Command Processor (CMD)

### Helix Version

helix 0.6.0

**Comment by kirawi** [comment]
Can't reproduce on the latest version.
