### ISSUE TITLE
`helix-git` AUR package compilation errors

### ISSUE THREAD

**Issue by Anomalocaridid** [helix-editor/helix#1846]
### Summary

When I try to update the helix-git AUR package, I get the below compilation errors.

```
error: there is no argument named `library_path`
  --> helix-loader/src/grammar.rs:66:65
   |
66 |         .with_context(|| format!("Error opening dynamic library {library_path:?}"))?;
   |                                                                 ^^^^^^^^^^^^^^^^

error: there is no argument named `language_fn_name`
  --> helix-loader/src/grammar.rs:71:61
   |
71 |             .with_context(|| format!("Failed to load symbol {language_fn_name}"))?;
   |                                                             ^^^^^^^^^^^^^^^^^^

error: there is no argument named `action`
   --> helix-loader/src/grammar.rs:136:59
    |
136 |         .map(|err| err.with_context(|| format!("Failed to {action} some grammar(s)")))
    |                                                           ^^^^^^^^

error: there is no argument named `grammar_dir`
   --> helix-loader/src/grammar.rs:241:43
    |
241 |         format!("Failed to read directory {grammar_dir:?}. Did you use 'hx --grammar fetch'?")
    |                                           ^^^^^^^^^^^^^^^

error: there is no argument named `grammar_dir`
   --> helix-loader/src/grammar.rs:246:24
    |
246 |             "Directory {grammar_dir:?} is empty. Did you use 'hx --grammar fetch'?"
    |                        ^^^^^^^^^^^^^^^

error: could not compile  due to 5 previous error
```

### Reproduction Steps

 

I tried this:

1. Install helix-git using an AUR helper such as Paru

I expected this to happen:
Installing helix-git successfully

Instead, this happened:
There were compilation errors

### Helix log

<details><summary>~/.cache/helix/helix.log</summary>

```
N/A
```

</details>

### Platform

EndeavourOS Linux Sway Edition

### Terminal Emulator

wezterm 20220319-074134-7fc7201a

### Helix Version

helix-git-r1822.a1e64815-1

**Comment by the-mikedavis** [comment]
This is a rust feature from 1.58 ([changelog](https://github.com/rust-lang/rust/blob/8d60bf427a4b055f464122062e76b3ec34d4f8ba/RELEASES.md?plain=1#L206)). The AUR package will need to ensure it is using a more recent rust version.

**Comment by Anomalocaridid** [comment]
I was not aware a specific version of Rust was required. It turns out I just had to run "rustup update."
