### ISSUE TITLE
Add option to only show files from the dir where helix was launched in filepicker

### ISSUE THREAD

**Issue by jaredramirez** [helix-editor/helix#1860]
Hey there,

One of my projects is setup as a monorepo, with a directory structure like:
```
.
├── .git
├── README.md
├── api
├── web
└── mobile
```

When I work in this project, I generally `cd` into whatever dir I'm working in, then launch `helix` from there. This works fine, but when I launch the filepicker (`space, f`), helix searches all files in the entire repo. This can make it a bit confusing and I sometimes end up opening the wrong file with a similar name in another directory by mistake. It would be very helpful if there was an option in the config I could specify to only show files from the directory that helix was launched from!

Thanks for the great editor!

**Comment by archseer** [comment]
#1600

**Comment by jaredramirez** [comment]
Oops missed that PR, I'll close this. Thanks!
