### ISSUE TITLE
Helix crashes when using `solc` LSP for Solidity

### ISSUE THREAD

**Issue by slinlee** [helix-editor/helix#1861]
### Summary

While writing a solidity file, Helix suddenly exits with the message below:

```
$ hx Auth.sol
thread 'main' panicked at 'internal error: entered unreachable code: Invalid { id: Null }', /home/slin/code/helix/helix-term/src/application.rs:804:18
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

This could be from a bug from my integration #1848 or because Solidity LSP support is still in development. Either way, it would be better if the `unreachable code` error didn't crash the entire application.

### Reproduction Steps

While writing a .sol file, it will crash. I will try some more to see if there is a dependable way to make it crash, but it happened to me within 10 lines of code.

### Platform

Linux

### Terminal Emulator

chrome os

### Helix Version

v0.5.0-911-g3e78b8fd

**Comment by archseer** [comment]
Hmm interesting. I'll patch this quickly by turning this into a log

**Comment by archseer** [comment]
https://github.com/helix-editor/helix/commit/919ac7ba15ed8443c80429d0e439074b611e231c

Can you also run `hx` with the `-v` flag so that LSP traffic is logged to the log file? I'd be interested in seeing what tripped it up.

**Comment by slinlee** [comment]
> [919ac7b](https://github.com/helix-editor/helix/commit/919ac7ba15ed8443c80429d0e439074b611e231c)
> 
> Can you also run `hx` with the `-v` flag so that LSP traffic is logged to the log file? I'd be interested in seeing what tripped it up.

@archseer Sorry I haven't had time to really dig deeper. Here's an update:

- After building with your patch, helix hasn't crashed again, as expected.
- I also switched from solc nightly to solc latest.

When I have some free time I might come back to investigate, but for now I'm able to get work done using Helix which is awesome. Should we close this issue?

**Comment by archseer** [comment]
Sounds good :)
