### ISSUE TITLE
does not print version

### ISSUE THREAD

**Issue by adsick** [helix-editor/helix#1869]
### Summary

summary

### Reproduction Steps

 

I tried this:

1. `hx --version`

I expected this to happen:
prints 'helix 0.6.0'

Instead, this happened:
simply 'helix'

### Helix log

<details><summary>~/.cache/helix/helix.log</summary>

```
please provide a copy of `~/.cache/helix/helix.log` here if possible, you may need to redact some of the lines
```

</details>

### Platform

Fedora Linux 35

### Terminal Emulator

Alacritty

### Helix Version

lol

**Comment by archseer** [comment]
How did you build helix?

**Comment by adsick** [comment]
> How did you build helix?

```

**Comment by archseer** [comment]
Pretty sure this was fixed by https://github.com/helix-editor/helix/commit/d3221b03a2b3ee5acc68066f34c4e56e2d05ce94
