### ISSUE TITLE
Blank screen after SIGCONT

### ISSUE THREAD

**Issue by shnarazk** [helix-editor/helix#1877]
### Summary

After 85264a861aeda7a002dda548403258620e914b57, `hx` stops redrawing screen after SIGCONT. The current `Application::handle_signals` calls `Terminal::autoresize` indirectly instead of `Compositer::resize`. But `autoresize` does nothing if the actual size is equal to the stored one. So redrawing is skipped.
I think we need to call `Terminal::resize` after all or to call `Terminal::clear` directly.

### Reproduction Steps

 

I tried this:

1. `hx`
1. C-z (suspend)
1. `fg`

I expected the screen was resumed.
Instead, it got blank.

### Platform

macOS

### Terminal Emulator

tmux 4.1 on Terminal

### Helix Version

helix 0.6.0 (6e7c2873)

**Comment by archseer** [comment]
Thanks, reverting that change!
