### ISSUE TITLE
Can't build tree-sitter grammar

### ISSUE THREAD

**Issue by merlinshabaj** [helix-editor/helix#1887]
When running: 
```
hx --grammar fetch
``` 
After already having completed all the other steps of installation, 
it throws this error:
```sh
Error: could not parse arguments

Caused by:
    unexpected double dash argument: --grammar
```

**Comment by the-mikedavis** [comment]
Do you already have an older version of helix installed? What does `which -a hx` say? Also: what platform are you running on and are you building from the latest source?

**Comment by archseer** [comment]
Give us an output of `hx --version`

**Comment by archseer** [comment]
Does `hx -g fetch` also fail?

**Comment by merlinshabaj** [comment]
`hx -g fetch` did also fail.

But apparently I wasn't on the master branch. I reinstalled the path and now it is working.
Thanks for the quick responses.
