### ISSUE TITLE
Add telecope-like list of lsp-diagnostics 

### ISSUE THREAD

**Issue by hirschenberger** [helix-editor/helix#1891]
In Lunarvim I love the feature to have a telescope list of lsp diagnostics (also clippy remarks) where I can simply skim through and fix issues here and there. (see screenshot)

![image](https://user-images.githubusercontent.com/1053180/160871995-e81c7ea0-fff4-4d60-924f-d1774dc1e20a.png)

**Comment by archseer** [comment]
Good idea, shouldn't be too hard to add either.

**Comment by hirschenberger** [comment]
Maybe I try to implement it myself. 
@archseer Can you maybe give me some hints how and where to start?

**Comment by archseer** [comment]
Take a look at how FilePicker is used in the code (it's just a picker with a file preview), i.e. https://github.com/helix-editor/helix/blob/deb7ee6595644accf88e0232aefe419d6f757365/helix-term/src/commands/lsp.rs#L74

A new command has to be added that builds a FilePicker from doc.diagnostics()

**Comment by hirschenberger** [comment]
I'm working on it with hx. Nice way to learn the editor.

So I create two functions: `diagnostics_picker` and `workspace_diagnostics_picker`

**Comment by sudormrfbin** [comment]
Does the LSP spec provide a way to get diagnostics for the whole workspace ?

**Comment by hirschenberger** [comment]
LSP seems to send diagnostic messages for all file, hx just filters them on receive for open documents.

**Comment by nour-dev** [comment]
hi, will this be added to 22.08 release ?

**Comment by the-mikedavis** [comment]
Yep. Anything merged into master that hasn't since been reverted (nothing comes to mind) will be included in the next release.
