### ISSUE TITLE
Documentation request: document how to install language server support

### ISSUE THREAD

**Issue by aral** [helix-editor/helix#1893]
## How I thought it would work

I install Helix and LSP support would automatically be installed for me for supported languages.

## Why I thought that

The output from the installation process makes it look like language support is being fetched and built for a number of languages. I didn’t see it mentioned that this does _not_ include LSP/autocomplete support.

## How it should work

I would still expect LSP support to be automatically installed for common languages. Barring that…

## Suggested documentation

Autocomplete does not work by default in Helix as language servers are not automatically installed. Please follow the guides to install the language server for the supported languages:

1. TypeScript
2. …

e.g., TypeScript

Requires Node.js/npm (minimum version?)

1. Install typescript-language-server:

```shell
npm install -g typescript-language-server
```

2. Install typescript:

```shell
npm install -g typescript
```

**Comment by David-Else** [comment]
All the information required has already been compiled here: https://github.com/neovim/nvim-lspconfig/blob/master/doc/server_configurations.md

I had a quick go at extracting the default language servers used by Helix, removing the redundant information regarding the Neovim setup, and reformatting it. It would take quite a while to create the entire document, so please can I get some feedback if this would be useful.

There is no point in duplicating the Neovim peoples' excellent work, but simply linking to the Neovim docs would make things far too complex and annoying. Most of it is not relevant to Helix users.

Each link under LSP goes direct to the instructions, here is what I have so far as an example:

## how-to-install-default-language-servers.md

The following are the default Helix language servers. To use them you must install them manually following the instructions below.

| Language   | LSP                             |
| ---------- | ------------------------------- |
| bash       | [bashls](#bashls)               |
| c          | [clangd](#clangd)               |
| c-sharp    | OmniSharp                       |
| cmake      | cmake-language-server           |
| cpp        | clangd                          |
| dart       | dart                            |
| dockerfile | docker-langserver               |
| elixir     | elixir-ls                       |
| elm        | elm-language-server             |
| go         | gopls                           |
| haskell    | haskell-language-server-wrappe… |
| hcl        | terraform-ls                    |
| javascript | typescript-language-server      |
| julia      | julia                           |
| kotlin     | kotlin-language-server          |
| lean       | lean                            |
| mint       | mint                            |
| nix        | rnix-lsp                        |
| prolog     | swipl                           |
| python     | pylsp                           |
| racket     | racket                          |
| rescript   | rescript-language-server        |
| ruby       | solargraph                      |
| rust       | rust-analyzer                   |
| scala      | metals                          |
| solidity   | solc                            |
| svelte     | svelteserver                    |
| tsx        | typescript-language-server      |
| typescript | typescript-language-server      |
| zig        | zls                             |


## bashls

https://github.com/mads-hartmann/bash-language-server

`bash-language-server` can be installed via `npm`:

```sh
npm i -g bash-language-server
```

Language server for bash, written using tree sitter in typescript.

## clangd

https://clangd.llvm.org/installation.html

**NOTE:** Clang >= 9 is recommended! See [this issue for more](https://github.com/neovim/nvim-lsp/issues/23).

clangd relies on a [JSON compilation database](https://clang.llvm.org/docs/JSONCompilationDatabase.html) specified
as compile_commands.json or, for simpler projects, a compile_flags.txt.
For details on how to automatically generate one using CMake look [here](https://cmake.org/cmake/help/latest/variable/CMAKE_EXPORT_COMPILE_COMMANDS.html). Alternatively, you can use [Bear](https://github.com/rizsotto/Bear).

**Comment by the-mikedavis** [comment]
Ah, wonderful! I think a [new Wiki page](https://github.com/helix-editor/helix/wiki/_new) would be good for this so it's easy to compile and keep up to date gradually, and multiple people can contribute easily. Would you like to set this up @David-Else? What you have here looks like a good start. For the list of default language servers, we should link to https://docs.helix-editor.com/lang-support.html or point people towards `hx --health` so it's automatically kept up to date. I would also add a note saying that operating-system level package managers (brew, chocolatey, linux package managers) tend to carry language servers as well.

**Comment by David-Else** [comment]
@the-mikedavis Yes, I will sort it out. The Wiki has an automatic table of contents, so it should be easy for users to go straight to the language server they want to install. I will leave out the current table and point to the page you linked. I will credit the original `nvim-lspconfig` site for the content too. 

Should this list of default language servers be for the latest release version of helix, or include language servers that may be in the master branch? (not that there are any at the moment, but I want to make that clear for people who might update the WIKI)

I had a look at https://pkgs.org/search/?q=lsp and could not find many language servers of note. Did you have any in mind? I don't know much about brew or chocolatey, would there be advantages to using them if it were also on something like NPM?

**Comment by the-mikedavis** [comment]
Oh hmm I suppose I'm a bit spoiled by Nix - it tends to have just about everything. Nixpkgs has rust-analyzer ([here](https://search.nixos.org/packages?channel=21.11&from=0&size=50&sort=relevance&type=packages&query=rust-analyzer)), as do the arch repos ([here](https://archlinux.org/packages/community/x86_64/rust-analyzer/)). If I look around for a less common LSP like `elixir-ls` I don't see much in the linux repos though. I'm mostly interested in a small note maybe at the top of that wiki that points out that an OS level package manager is potentially an option, so it's up to the user how they'd like to install. (Personally I would never install a global package through NPM instead of Nix since it's very easy to replicate global package state and configuration across machines with Nix.)

For default language servers docs on the master branch: https://docs.helix-editor.com/master/lang-support.html (note the `master` part: we publish docs there on pushes to master and separately for the releases). That would be an advantage of pointing to `hx --health` instead though: it will show the default language servers for whatever version of helix one has installed.

**Comment by the-mikedavis** [comment]
Looks great! Thanks for putting this all together @David-Else!
