### ISSUE TITLE
HTML and CSS language server support

### ISSUE THREAD

**Issue by aral** [helix-editor/helix#1895]
Adding HTML and CSS language server support should be quite easy.

In _languages.toml_:

## HTML

```toml
language-server = { command = "html-languageserver", args = ["--stdio"], language-id="html"}
```

## CSS

```toml
language-server = { command = "css-languageserver", args = ["--stdio"], language-id="html"}
```

And the language server installation commands are:

## HTML

```shell
npm install --global vscode-html-languageserver-bin
```

## CSS

```shell
npm install --global vscode-css-languageserver-bin
```

Happy to prepare a pull request for the _languages.toml_ file if you’d like.

**Comment by sudormrfbin** [comment]
A PR will be very much welcome :)

**Comment by David-Else** [comment]
https://www.npmjs.com/package/vscode-langservers-extracted

**Comment by David-Else** [comment]
This has been closed by https://github.com/helix-editor/helix/pull/2025 and https://github.com/helix-editor/helix/pull/2018 (and JSON has been added too)
