### ISSUE TITLE
Support column highlighting

### ISSUE THREAD

**Issue by greg-enbala** [helix-editor/helix#1897]
Support highlighting specific columns.

You can see in this screenshot of kakoune that I have columns 80, 100, and the column under the active cursor highlited:

<img width="1107" alt="Screen Shot 2022-03-30 at 7 14 21 PM" src="https://user-images.githubusercontent.com/66078183/160956691-aab8836b-34fc-403e-82b8-8d19fe36ac0d.png">

I use the column under the cursor to align what I'm currently working on with things above and below it. I use the columns at 80 and 100 to see where my code sits in relation to those columns.

**Comment by the-mikedavis** [comment]
Implemented in https://github.com/helix-editor/helix/pull/2060 (released in 22.05)
