### ISSUE TITLE
Selecting with mouse says it yanked to system clipboard but doesn’t

### ISSUE THREAD

**Issue by aral** [helix-editor/helix#1901]
### Summary

When you make a selection using the mouse, Helix shows you the _yanked main selection to system clipboard_ message but it does not actually do it.

If you manually yank to system clipboard (<kbd>space</kbd> <kbd>Y</kbd>) after making a selection, it works.

### Reproduction Steps

1. Select some text in an open buffer using your mouse.
2. Notice the message _yanked main selection to system clipboard_  is displayed in Helix.
3. Paste it into a different app on your system.

## What should happen

The selected text should be pasted.

## What actually happens

The selected text is not pasted. (Whatever was on the system clipboard previously is.)

## Workaround

Manually yank the selection to the system clipboard after selecting it with the mouse using <kbd>space</kbd> <kbd>Y</kbd>.

### Helix log

No relevant entries found in log (no errors/warnings).

### Platform

Linux (elementary OS 6; based on Ubuntu)

### Terminal Emulator

Terminal (elementary OS)

### Helix Version

22.03-7-gc18de0e8

**Comment by archseer** [comment]
Selecting with mouse usually yanks into a different clipboard -- I forgot what it's called but it's the one that's used when pasting with the middle click on the mouse.

**Comment by aral** [comment]
Thanks, @archseer, it’s currently confusing because the same message is displayed for two different clipboards.

Suggestions:

- Make selecting with the mouse yank into the system clipboard (what the message currently says it does)
- Change the message so it tells you where it is actually yanked to (and, ideally, that you have to use the middle mouse button to paste it)

Which would you think is best? (I’d likely go with the first as it seems less confusing to me. It would actually be least confusing if there the middle mouse button clipboard and the system clipboard were merged so that only the latter was used.)

**Comment by the-mikedavis** [comment]
Let's close this in favor of https://github.com/helix-editor/helix/issues/2615 which has more discussion on the same lines.
