### ISSUE TITLE
Specifying labels for usermodes in configs?

### ISSUE THREAD

**Issue by leeola** [helix-editor/helix#1909]
Usermodes (called KeyTrie in source i think?) as i'm defining it is the grouping of commands. Just like the Space mode, but defined by the user. It appears users can create these by just nesting mappings. Ala `space.l = { k = "foo" }`. However in doing so, `space.l` doesn't have a label. Worse yet, if you make a second user mode, eg `space.q = { f = "bar" }`, they are shown in the same help slot, since apparently it's grouped by label/name - even though they're two distinct maps.

So, it would be nice if the user had a way to specify this group name from the configuration file. [Looking at the source](https://github.com/helix-editor/helix/blob/master/helix-term/src/keymap.rs#L31-L44) this doesn't seem possible, as the label gets a `Default::default()` based name.

Not sure what syntax to propose in the configuration, perhaps a reserved field? `space.q = { name = "My Usermode", f = "bar" }` would seem reasonably natural.

Thoughts?

**Comment by gasacchi** [comment]
i also curious about this, nested keymap doesn't have label on it.
is there any way  to add name / label? 
it is good to have good documentation for custom keymaps

**Comment by the-mikedavis** [comment]
Not currently - this issue covers adding that ability

**Comment by gf3** [comment]
[kakoune allows users to specify modes by name](https://github.com/mawww/kakoune/blob/master/doc/pages/modes.asciidoc) _and then_ optionally bind a key to it. this is particularly useful for plugin authors who wish to provide a user mode without overriding any keybindings

here's an example: https://github.com/Delapouite/kakoune-user-modes/blob/3d3e3a8c072734d5ac2e10be9a7749bcae87a960/user-modes.kak
