### ISSUE TITLE
`K` documentation overflow

### ISSUE THREAD

**Issue by kirawi** [helix-editor/helix#191]
![Capture](https://user-images.githubusercontent.com/67773714/121287071-e5312500-c8ae-11eb-81d9-2e3433003463.PNG)

This happens when the terminal is smaller than the documentation popup. We should probably also add some scrolling functionality for the popup.

**Comment by pickfire** [comment]
> This happens when the terminal is smaller than the documentation popup. We should probably also add some scrolling functionality for the popup.

I wonder what keys we can use to scroll the popup?

**Comment by archseer** [comment]
It currently scrolls using ctrl-u/d, but it's possible to scroll past the end: https://github.com/helix-editor/helix/blob/b20e4a108cd890afa6cdf83656856fc2157a8e84/helix-term/src/ui/popup.rs#L83-L97

**Comment by kirawi** [comment]
Can no longer replicate, I have no idea why it happened in the first place, possibly a glitch when building.
