### ISSUE TITLE
Bash/Zsh syntax highlighting

### ISSUE THREAD

**Issue by joezak11** [helix-editor/helix#1914]
### Summary

I opened a zsh plugin and noticed that the highlighting was messed up
```zsh
#                                   v
0="${ZERO:-${${0:#$ZSH_ARGZERO}:-${(%):-%N}}}"
```
if I remove the `%` character in `(%)` the string is highlighted correctly but with that character the start quote gets ignored and anything after the second quote is highlighted as a string.
this also affects bash files as it seems there is no zsh specific configuration by default.

### Reproduction Steps

 

I tried this:

1. `hx any.zsh`
2. make a string with `"${(%)}"` or other special characters except `#`, `$`, or `&`

I expected this to happen:
to highlight the string normally even if it is invalid (although in this case it isn't).

Instead, this happened:
the start quote is ignored and the end quote is parsed as a start qoute

### Platform

Linux

### Terminal Emulator

wezterm 20220319-142410-0fcdea07

### Helix Version

helix 22.05-dev (a9635659)

**Comment by archseer** [comment]
Can you try bumping the tree-sitter-bash version and fetch/rebuild grammars? We're a bit behind the latest. If you still get the same issue consider reporting it upstream at https://github.com/tree-sitter/tree-sitter-bash

**Comment by joezak11** [comment]
it does work after updating tree-sitter-bash

**Comment by the-mikedavis** [comment]
Would you mind submitting a PR with the update? You'll need to update the revision here: https://github.com/helix-editor/helix/blob/85c23b31deb73d71bb38264485d728665f151d4a/languages.toml#L405

And make a small modification to `runtime/queries/bash/highlights.scm`: [tree-sitter/tree-sitter-bash@`tree-sitter:a8eb5cb...tree-sitter:275effd`#diff-d485a982e4](https://github.com/tree-sitter/tree-sitter-bash/compare/tree-sitter:a8eb5cb...tree-sitter:275effd#diff-d485a982e458ef8da2cc203585065b7542665cb80b78d230b1e8f77ea25825d4)
