### ISSUE TITLE
Commands for buffer navigation

### ISSUE THREAD

**Issue by Darksecond** [helix-editor/helix#1926]
I would love to see a set of commands for buffer navigation, like in vim. 
Specifically something like `buffer_next` and `buffer_previous` which can be aliased to `:bn` and `:bp`.
They would allow the user to switch buffers without having to go through the <space>b menu.

**Comment by sudormrfbin** [comment]
There's `gn` and `gp` for next and previous buffer, so it's just a matter of adding the typable commands (defined in https://github.com/helix-editor/helix/blob/master/helix-term/src/commands/typed.rs) which utilize already existing functions:

https://github.com/helix-editor/helix/blob/d15c875214d2147bf9bdf03ef3445752476d14b3/helix-term/src/commands.rs#L636-L667

**Comment by David-Kunz** [comment]
Hi @Darksecond and @sudormrfbin,

I've just created a [PR](https://github.com/helix-editor/helix/pull/1940) to add the typed commands `buffer-next` and `buffer-previous`.

Best regards,
David
