### ISSUE TITLE
Paragraph movement doesn't work if paragraphs are separated by more than one blank line

### ISSUE THREAD

**Issue by sudormrfbin** [helix-editor/helix#1928]
### Summary

`]p` stops at the line just above the paragraph when it has multiple blank lines before it.

### Reproduction Steps

Start with the following text and place the cursor on the first line.

```
text


after two blank lines

more text
```

Press `]p` a couple of times. It first moves to the blank line just before `after two blank lines`, but doesn't move anymore with `]p`. Manually moving the cursor to `after` and then hitting `]p` two times correctly moves the cursor first to before `more text` and then subsequently to the end of `more text`.

### Platform

Linux

### Terminal Emulator

Kitty

### Helix Version

ec21de08446656b9012c39db2db3d02c7ce3dc9c

/cc @pickfire

**Comment by bolshoytoster** [comment]
@sudormrfbin can you see if this works:
```diff
diff --git a/helix-core/src/movement.rs b/helix-core/src/movement.rs
index 3f3ffa3..cd2a6c9 100644
--- a/helix-core/src/movement.rs
+++ b/helix-core/src/movement.rs
@@ -205,17 +205,18 @@ pub fn move_next_paragraph(
     let next_line_empty = rope_is_line_ending(slice.line(line.saturating_sub(1)));
     let curr_empty_to_line = curr_line_empty && !next_line_empty;
 
-    // skip character after paragraph boundary
-    if curr_empty_to_line && last_char {
-        line += 1;
-    }
     let mut lines = slice.lines_at(line).map(rope_is_line_ending).peekable();
     for _ in 0..count {
         while lines.next_if(|&e| !e).is_some() {
             line += 1;
         }
-        while lines.next_if(|&e| e).is_some() {
-            line += 1;
+        if last_char {
+            while lines.next_if(|&e| e).is_some() {
+                line += 1;
+            }
+            while lines.next_if(|&e| !e).is_some() {
+                line += 1;
+            }
         }
     }
     let head = slice.line_to_char(line);
```
If it does I can open a PR.

**Comment by pickfire** [comment]
It create another issue where it only stops before the next paragraph.
