### ISSUE TITLE
Goto next diagnostic error?

### ISSUE THREAD

**Issue by leeola** [helix-editor/helix#1929]
Would Helix be interested in a "Goto next diag error" command? Similar to `goto_next_diag`, but instead it goes specifically to an error severity.

I whipped up [an example](https://github.com/leeola/helix/commit/90a46ee18661736e4719257c64caea041bc5010d). Curious if ya'll are interested or not. A couple nitpicks with the idea/linked-code i have, for discussion sake:

1. A specific error variant of this command feels... verbose and repetitive. A parameterized version of it which can be configured to go to a specific severity could support all variations of this idea. ie go to any diag, go to warning diags, go to error diags, etc. Though i'm not clear if Helix commands can be parameterized like that? Eg `key = goto_next_diag(error)` in config.toml. 
2. The above code needs tests. Not sure how to test that in this repo yet.
3.  The `doc.diagnostics().last()` (and first) fallback should also filter to the desired severity.

Appreciate any thoughts :)

**Comment by leeola** [comment]
Some minor improvements to the branch: https://github.com/leeola/helix/tree/22.03-diag-next-err

Perhaps i should just PR it. :shrug:

**Comment by EpocSquadron** [comment]
I do highly recommend a PR, you're very likely to get some eyes on it and constructive feedback. I could easily see this being merged once the kinks are worked out.
