### ISSUE TITLE
Python auto indent not working

### ISSUE THREAD

**Issue by willparsons** [helix-editor/helix#1935]
### Summary

When making a new line it is not auto-indenting.

### Reproduction Steps

 

I tried this:

*  Make a new line in a function

I expected this to happen:
* Automatically indent the line

Instead, this happened:
* Nothing

### Platform

Ubuntu WSL

### Terminal Emulator

windows terminal  1.11.3471.0

### Helix Version

22.03

**Comment by kirawi** [comment]
Which language is this with?

**Comment by kirawi** [comment]
This might be a dupe of https://github.com/helix-editor/helix/issues/763
