### ISSUE TITLE
A way to modify the speed at which the cursor moves up, down, left and right

### ISSUE THREAD

**Issue by iCraft85** [helix-editor/helix#1941]
#### Describe your feature request

So I find when I press **k**, **j**, **h** and **l** the cursor takes a lot of time to reach where I want to get to so I was suggesting that a option can be added to modify the speeds of each of these to allow more customisation and also increase productivity (cuz generally I spending lots of time just waiting for the cursor to reach where I want it)

So for the actual config options maybe they can be something like this `scroll-speed = 5`. 

This should be a generic value which would apply to all of the methods of scrolling, I am not sure what kinda value 5 can be but maybe it can represent how lines will be covered in 1 second

Another 4 options can be added which would give a custom speed for each of the directions for example `scroll-speed-left`

Additionally to this the scroll speed might be too fast for fine adjustments I suggest that there is a keybind which changes the speed whilst its pressed, so basically when you press for example shift it may make the cursor move slower or faster depending on what has been set in the config.

**Comment by archseer** [comment]
Key repeat speed is dependent on your terminal though.

In a modal editor you shouldn't be relying solely on hjkl for navigation, it should only be used for short distances.

Use gh/gl to jump to the start and end of the line, or w/b/e to jump by word. You can also jump to a specific letter via f/t. For vertical navigation there's ctrl-u/ctrl-d.

**Comment by iCraft85** [comment]
Oh ok

**Comment by sudormrfbin** [comment]
Some systems have the repeat rate set very low, and if you're on linux it can be set using `xset`: https://wiki.archlinux.org/title/Xorg/Keyboard_configuration#Using_xset.

**Comment by iCraft85** [comment]
I am unfortunately on macos but ill try changing the key repeat
