### ISSUE TITLE
Provide some way to create a keymap that pipes the selection to a specific shell command

### ISSUE THREAD

**Issue by thomkeh** [helix-editor/helix#1943]
I can map a key to `shell_pipe` like this:
```toml
[keys.normal]
C-s = "shell_pipe"
```
but I cannot specify any arguments to `shell_pipe`. I think there are many ways to solve this problem. One solution would be #1383, but the easiest would probably be to add a new _typable command_ `:pipe` that I can then map:
```toml
[keys.normal]
C-s = ":pipe black -"
```

The use case is piping the content of the file to a [formatter](https://github.com/psf/black) (and then saving it). So:
```toml
[keys.normal]
C-s = ["select_all", "??solution to this issue?? black -", "collapse_selection", ":w"]
```

**Comment by sudormrfbin** [comment]
The helper for the all the shell commands is here:

https://github.com/helix-editor/helix/blob/8b91ecde40e95a8ba956881c95da60adbf98abb6/helix-term/src/commands.rs#L4248-L4309

But it also has the code for displaying the prompt interleaved with it, so the code for execution of a given command and replacing the buffer contents will have to extracted out, for example:

```rust
fn shell(cx: &mut Context, cmd: &str, behavior: ShellBehavior) {
    let pipe = match behavior {
        ShellBehavior::Replace | ShellBehavior::Ignore => true,
        ShellBehavior::Insert | ShellBehavior::Append => false,
    };

    let config = cx.editor.config();
    let shell = &config.shell;

    let (view, doc) = current!(cx.editor);
    let selection = doc.selection(view.id);

    let mut changes = Vec::with_capacity(selection.len());
    // ....
}

fn shell_prompt(cx: &mut Context, prompt: Cow<'static, str>, behavior: ShellBehavior) {
    ui::prompt(
        cx,
        prompt,
        Some('|'),
        ui::completers::none,
        move |cx, input: &str, event: PromptEvent| {
            if event != PromptEvent::Validate {
                return;
            }
            if input.is_empty() {
                return;
            }

            shell(cx, input, behavior)
        })
}
```

You might have to replace `cx` with `cx.editor` in some places.

**Comment by DeviousStoat** [comment]
I found myself needing this as well. And since it didn't seem too hard for a first PR, I took a stab at it https://github.com/helix-editor/helix/pull/1972

**Comment by David-Else** [comment]
@DeviousStoat This looks amazing!

The problems I ran into using external formatters in Neovim were:

1. If they failed then the buffer would fill up with the error message replacing my document
2.  The cursor would go to the start of the document

It would be great if these two problems could be avoided in Helix.

I expect number 2 was just a Vim thing, but can your PR recognise an error and abort with a message?

I am really hoping to get Prettier working in Helix for all the different file types it can act on, that would be amazing! We would need a way to turn off LSP formatting on a server by server basis. For example, the TypeScript Language Server formatting sucks, but you could use Prettier instead.

PS https://dprint.dev/ is written in Rust and copies a lot of Prettier functionality.

**Comment by DeviousStoat** [comment]
Hey @David-Else!
I am very new to helix so others would probably give more accurate answers but from what I experienced, the `shell_pipe` command doesn't do anything if the shell command returned a non zero error code and it simply writes `Command failed` in the status bar. Since this `:pipe` command uses the same function, I think it works the same. Do you have an example where it didn't work like that for you?

Another improvement might be to print the stderr content to the status bar though because for now I think it is only logged and it just prints `Command failed`, so we have no idea what went wrong I think.

**Comment by sudormrfbin** [comment]
> We would need a way to turn off LSP formatting on a server by server basis.

`auto-format` option controls this:

```toml
# in <config_dir>/helix/languages.toml (same directory as config.toml)

[[language]]
name = "rust"
auto-format = false
```

**Comment by the-mikedavis** [comment]
Closed by #1972.

Example:

```toml
# <config_dir>/helix/config.toml
[keys.normal]
"=" = ":pipe fmt -w 80"
```

is my stop-gap until the reflow command lands.

**Comment by David-Else** [comment]
Can [this](https://github.com/helix-editor/helix/pull/1972) be used for Prettier somehow? https://prettier.io/docs/en/cli.html

**Comment by the-mikedavis** [comment]
The only trouble with prettier would be specifying the language since it supports multiple. If I wanted to bind a key to format json:

```toml
[keys.normal]
"=" = ":pipe prettier --parser json"
```

Then I can say `%=` in a json document to format the whole buffer.

But there isn't a way to pass in the buffer's language currently. I believe in vim and kakoune you can do it with something like environment variables.

**Comment by the-mikedavis** [comment]
There isn't a workaround for this. If I use prettier I call out to it in a separate shell.
