### ISSUE TITLE
LSP diagnostic is too long if the current window is so narrow

### ISSUE THREAD

**Issue by Zaplae** [helix-editor/helix#1953]
![image](https://user-images.githubusercontent.com/98511527/161481174-e53ab721-7eb4-432f-bd75-0f00812c205f.png)

When the diagnostic displays:

![image](https://user-images.githubusercontent.com/98511527/161481219-6570eb96-109e-46e1-815d-8765060298d2.png)

**Comment by Zaplae** [comment]
Maybe providing some shortcuts or commands to toggle `display diagnostic` is helpful  
(just hide text, not tips before line numbers)

**Comment by lukepighetti** [comment]
Just ran into this myself. It's very difficult to read the LSP diagnostic. Would be nice if there was a background or border applied to it

### Without LSP diagnostic

<img width="650" alt="Screen Shot 2022-04-26 at 2 46 52 PM" src="https://user-images.githubusercontent.com/666539/165370667-852dc63b-57c8-4fd5-ae16-da838d8bc272.png">

### With LSP diagnostic
<img width="637" alt="Screen Shot 2022-04-26 at 2 46 58 PM" src="https://user-images.githubusercontent.com/666539/165370628-ac9fea58-9586-4d92-b028-e989f82fe90a.png">

**Comment by FinnPerry** [comment]
+1 for some kind of border or coloured background. Depending on the color theme it can be impossible to distinguish where the file contents ends and the diagnostic starts.

**Comment by 0rphee** [comment]
I'd love to have a popup window like when entering "Space mode".
<img width="634" alt="Screen Shot 2022-07-11 at 5 35 58 p m" src="https://user-images.githubusercontent.com/79347623/178370201-644a0d57-f380-4da9-a09a-bbc4bfc424ec.png">
<img width="1380" alt="Screen Shot 2022-07-11 at 5 33 54 p m" src="https://user-images.githubusercontent.com/79347623/178370203-b26f2f58-b99c-4265-8399-a13be75a098f.png">

**Comment by jakehl** [comment]
I'm not sure this should be labelled enhancement - I would consider that the diagnostics rendering over code to be a bug. Especially so when the code you're trying to fix is obscured by the message.

**Comment by gabydd** [comment]
Honestly I think this is the best issue: https://github.com/helix-editor/helix/issues/1462 (not labelled bug but it could be)

**Comment by pascalkuthe** [comment]
It's labeled an enhancement because the code behaves as intended, it's just that other UI options might yield better results. This is sort of an edgecase in terms of labelling but the label won't change the way this issue is treated so it doesn't matter too much.

I closed all other issues except this one and #1462.
#1462 is specifically about intrusive diagnostics so I think it made sense to keep one separate issue to also explore alternative solutions like a popup mentinoed above.
