### ISSUE TITLE
`%` selects the entire file but doesn't move to `select` mode. 

### ISSUE THREAD

**Issue by xanderjakeq** [helix-editor/helix#1958]
I remapped `:clipboard-yank` which I assume works only in select mode.

i expected my remap to work with `%` but `select_all` stays in `normal` mode.

**Comment by the-mikedavis** [comment]
`:clipboard-yank` yanks the current selection but you do not need to be in select mode in order to have a selection. You can check this by opening a file, pressing `%` and then running `:clipboard-yank`.

What does the remapping look like?

**Comment by xanderjakeq** [comment]
```
[keys.select]
"C-x" = ":clipboard-yank"
```
This is my remap. So it doesn't work on `normal` mode.
if `%` selects then wouldn't it consistent for `hx` to move to `select` mode?

**Comment by the-mikedavis** [comment]
Selection mode is really for extending selections. For example, I can press `w` to select the next word and then if I want to also select the word following that one, I would use `v` to enter selection mode and `w` to extend the existing selection to include the next word. Usually you only want to go into selection mode if you already have a selection you mean to change.

**Comment by xanderjakeq** [comment]
I see, is there a way I could use my remap after `%` selecting? If not, no big deal, not that often I'd copy the whole file anyway xD, but would just be nice to have.

**Comment by the-mikedavis** [comment]
Since `%` leaves you in normal mode, you can use that remap in `keys.normal`:

```toml
[keys.normal]
"C-x" = ":clipboard-yank"
# or remap '%' to select everything _and_ yank for example
"%" = ["select_all", ":clipboard-yank"] 
```

But I think the default set of keybindings to do this isn't too bad either: <kbd>%</kbd><kbd>space</kbd><kbd>y</kbd> (<kbd>space</kbd><kbd>y</kbd> is the default keymap for `:clipboard-yank`).

**Comment by xanderjakeq** [comment]
cool!! thanks.
