### ISSUE TITLE
Behaviour difference between Ctrl+V paste and middle-click paste on elementary OS terminal

### ISSUE THREAD

**Issue by aral** [helix-editor/helix#1963]
### Summary

Middle-click paste performs as it should. Ctrl+V paste messes up the pasted text (in insert mode).

#### I tried this:

1. `hx`
2. Copy https://raw.githubusercontent.com/fatso83/dotfiles/master/utils/scripts/inotify-consumers
3. Paste using Ctrl + V in insert mode.

#### I expected this to happen:

It should paste exactly as copied.

#### Instead, this happened:

It pasted with incorrect indentation.

![Screenshot from 2022-04-05 11-44-51@2x](https://user-images.githubusercontent.com/41798/161738096-50d7e3a5-e1a6-4fa8-9b4f-c20d80d0fb32.png)

#### Workaround:

Use middle-click paste.

![Screenshot from 2022-04-05 11-47-18@2x](https://user-images.githubusercontent.com/41798/161738068-e84fc143-b8ff-487c-b073-6ca0e7bddae3.png)

### Helix log

Nothing pertinent from the run.

<details><summary>~/.cache/helix/helix.log</summary>
…
2022-04-05T11:34:04.959 helix_view::theme [WARN] Theme: invalid style attribute: modifier
2022-04-05T11:34:04.980 helix_view::editor [ERROR] Failed to initialize the LSP for `source.fish` { LSP not defined }
</details>

### Platform

Linux (elementary OS 6; based on Ubuntu)

### Terminal Emulator

io.elementary.t

### Helix Version

helix 22.03 (c18de0e8)

**Comment by archseer** [comment]
https://github.com/helix-editor/helix/issues/1021#issuecomment-963353157

Use space+p to paste from clipboard.
