### ISSUE TITLE
Add Swift language support

### ISSUE THREAD

**Issue by d12bb** [helix-editor/helix#1964]

**Comment by archseer** [comment]
Grammar is https://github.com/alex-pinkus/tree-sitter-swift, someone just needs to go over and fix up the highlighting queries

**Comment by archseer** [comment]
Hmm: https://github.com/alex-pinkus/tree-sitter-swift#where-is-your-parserc

If we supported http sources rather than git you could fetch it from the latest github actions build

**Comment by d12bb** [comment]
> Currently the work-around that we have for this is to fork the repository and check in the generated C files

Have to admit I don't really want to do that, I'd 100 % forget/procrastinate updating that, letting it get out of date …
Maybe I'll find time to automate updating the fork, then of course I can contribute support for Helix myself.

**Comment by the-mikedavis** [comment]
Closed by #2033
