### ISSUE TITLE
Give warnings and errors when building from source on powershell. (Windows 10) resulting into fail build.

### ISSUE THREAD

**Issue by reiend** [helix-editor/helix#1973]
Windows 10
Powershell 7.2.2
With gcc and g++ installed(MingW). installed using choco intall
rust was installed using choco install rust

To replicate the issue.
use windows 10
use powershell
install rust via choco install rust 
install mingw via choco install
git clone https://github.com/helix-editor/helix
cd helix
cargo install --path helix-term

the warning and errors will occur on building[208-214]
see image below

![image](https://user-images.githubusercontent.com/93508511/161929064-f94ef131-7717-4b07-acc7-16c43bef01b7.png)
![image](https://user-images.githubusercontent.com/93508511/161929678-49ff964e-e0a0-48ac-8712-ea57189984cc.png)
![image](https://user-images.githubusercontent.com/93508511/161929727-bd60222f-3b31-432c-8ce2-791f18b5da82.png)
![image](https://user-images.githubusercontent.com/93508511/161929793-d7d51364-44bf-4094-b1c0-f38004e2f46f.png)

**Comment by the-mikedavis** [comment]
```
C:\Devs\OpenSource\helix\runtime\grammars/sources\json\src\parser.c
```

looks like there's be a hard-coded `/`. Will take a look in a bit.

**Comment by reiend** [comment]
thanks for making a fix @the-mikedavis , but it still throws warnings and errors.  
I tried building different source from the commit history  one from april - december . but none of them works.
it always gives me the same error "Failed to run custom build for helix-term v....."

**Comment by reiend** [comment]
this is the last source that I build from history 
https://github.com/helix-editor/helix/tree/7438db66ae93c9164fdc29bdf31bd9b8ef861efb
will try to build more.

**Comment by reiend** [comment]
@the-mikedavis did I miss something from the installation? I'm starting to think the issue exist on my end.

**Comment by the-mikedavis** [comment]
What versions of `gcc` and `g++` do you have installed?

**Comment by reiend** [comment]
> What versions of `gcc` and `g++` do you have installed?

g++, gcc  - 11.2.0
rustc -         1.59.0

**Comment by reiend** [comment]
I try to build one from November - June  2021  still no luck.
it still throwing the same error. "Failed to run custom build for helix-term v....."
but the difference this time is it doesn't give me any warnings about an unused function.

**Comment by the-mikedavis** [comment]
I believe what's failing is the compilation command for tree-sitter gramamrs ([here](https://github.com/helix-editor/helix/blob/b5efb9d66cfb582eec0b96174d856c8f7e43d82c/helix-loader/src/grammar.rs#L312-L324)). Maybe the windows build is missing a flag?

**Comment by reiend** [comment]
I'm sorry @the-mikedavis, I can't help you with the code. but now that you mentioned it. at the end it specifically mentioned that it can't find the directory for the tree-sitter. base on my recent build from source from November - June 2021. it mention something about installing things recursively, submodules and empty directory.

![image](https://user-images.githubusercontent.com/93508511/162485902-c04568f4-fd85-4e9d-85cb-dd6bc3f74b1e.png)

**Comment by the-mikedavis** [comment]
Yeah a while back we were using [git submodules](https://git-scm.com/book/en/v2/Git-Tools-Submodules) for tree-sitter repositories. For old revisions you'll need to use `git submodule update --init --recursive` to make sure they're checked out before building.

**Comment by reiend** [comment]
@the-mikedavis  Just an update. still failing when you build it from source using native windows, so I tried different approaches (still throwing the tree-sitter error).

building it using wsl2 (ubuntu 20.04) went just find however when you change the theme :theme <theme> it throws an error about theme not supported required true color something like that.

installing it using scoop was so smooth, I encountered no issues at all.

**Comment by the-mikedavis** [comment]
Oh curious, I wonder if this is just a problem with compatibility with MinGW then 🤔 

It sounds like on the wsl2/ubuntu setup you'll need to add a config to force true-color support: https://docs.helix-editor.com/configuration.html

```toml
[editor]
true-color = true
```

**Comment by reiend** [comment]
> 

I forgot to mention that I use MinGW too on wsl2/ubuntu for gcc/g++.
if that's the case, it seems weird that it works correctly.

oh my bad. I didn't finish reading the 0.4 Configuration part docs.

**Comment by Antonio-Bennett** [comment]
I'm getting this error on WSL2 latest version of rustic installed.

**Comment by reiend** [comment]
> I'm getting this error on WSL2 latest version of rustic installed.

@Antonio-Bennett  make sure you have gcc/g++ compiler on wsl2.

**Comment by Antonio-Bennett** [comment]
@reiend i do :( not sure why it started happening because it worked before then I switched to set it up with my forked repo and after it stopped working completely even with the main repo. Using homebrew rn but it doesn't get latest changes quickly

**Comment by reiend** [comment]
> @reiend i do :( not sure why it started happening because it worked before then I switched to set it up with my forked repo and after it stopped working completely even with the main repo. Using homebrew rn but it doesn't get latest changes quickly

**Comment by reiend** [comment]
> @reiend i do :( not sure why it started happening because it worked before then I switched to set it up with my forked repo and after it stopped working completely even with the main repo. Using homebrew rn but it doesn't get latest changes quickly

weird.

I tried building it again on native windows but still give the same error above.

**Comment by reiend** [comment]
@Antonio-Bennett  you can try installing via scoop, downsides is, it doesn't have the latest commits

**Comment by Antonio-Bennett** [comment]
@reiend what's the difference to just continuing to use homebrew? I get to stay in wsl with homebrew though

**Comment by reiend** [comment]
> @reiend what's the difference to just continuing to use homebrew? I get to stay in wsl with homebrew though

what is the helix version on homebrew?

**Comment by reiend** [comment]
> @reiend did you try `cargo clean` yet?

@slinlee I didn't, I'll try this out, thanks.

**Comment by Antonio-Bennett** [comment]
Tried `cargo clean` still same error for me also tried doing `git submodule update --force --init --recursive --depth 1 --jobs 8` before running `cargo install`

**Comment by reiend** [comment]
same It didn't work.

**Comment by crokenx** [comment]
Hi, I'm with the same errors from treesitter.

**Comment by kirawi** [comment]
Are all of you using GCC? I use `clang` and I'm able to compile normally, and I think MSVC worked too.

**Comment by crokenx** [comment]
Ok I try something new.

I was trying to run rustlings exercises and rust keep saying that I have to install vs 2019 or vs 2022, I downloaded the installer for vs 2022 and selected the c++ tools, try the rustlings watch command and everything start working just fine, next I went to helix files and run the again the commands, "cargo install --path helix-term" to be exactly, and it works, hx command is now in my path I can continue with the normal installation of helix. As @kirawi noted I was trying with GCC. I don't why but there's the problem with all of this.

**Comment by Antonio-Bennett** [comment]
Hmm seems to be using clang and still getting this error  
![image](https://user-images.githubusercontent.com/31296212/165677490-2dca6fa6-d187-477f-a712-de122f4fc15d.png)

**Comment by crokenx** [comment]
> Hmm seems to be using clang and still getting this error ![image](https://user-images.githubusercontent.com/31296212/165677490-2dca6fa6-d187-477f-a712-de122f4fc15d.png)

I didn't use clang, I installed c++ tools with the help of vs 2022.

**Comment by txtyb** [comment]
It seems that although we are using MingW, the compiler still received arguments in MSVC style. 
Temperory workaround: delete [these lines](https://github.com/helix-editor/helix/blob/567e71fbbcc047119675691a05e7c16b865e8be1/helix-loader/src/grammar.rs#L323-L336), and then `cargo install --path helix-term`.

**Comment by kirawi** [comment]
We could try having separate arguments for an MingW toolchain.
