### ISSUE TITLE
Typo on website

### ISSUE THREAD

**Issue by declancm** [helix-editor/helix#1980]
![image](https://user-images.githubusercontent.com/90937622/161962337-f5ddae19-f6dd-41d3-961f-cc25455b526c.png)

On the helix website within the 'keymaps' tab, i think the text for `delete_char_forward` should read "Delete next char". Hopefully this is the correct place to post this issue 😬

**Comment by the-mikedavis** [comment]
Ah actually it looks like that typo is still present in the Insert Mode docs.
