### ISSUE TITLE
Shrink selection to line bounds

### ISSUE THREAD

**Issue by Zoybean** [helix-editor/helix#2002]
#### Describe your feature request
The `X` key extends each selection so that if either end is within a line, it is moved to the next line-end to fully contain the line. I would like a command that shrinks each selection in the same way, such that if either end of the selection is within a line, it is moved back to the next line-end, such that the line is no longer contained. e.g. (using `[` and `]` to delimit the selection):
```
In publishing [and graphic design,
Lorem ipsum is a placeholder text
commonly used to demonstrate the visual form of a document or a typeface
without relying on meaningful content.
Lorem ipsum] may be used as a placeholder before the final copy is available.
```
Becomes
```
In publishing and graphic design,
[Lorem ipsum is a placeholder text
commonly used to demonstrate the visual form of a document or a typeface
without relying on meaningful content.]
Lorem ipsum may be used as a placeholder before the final copy is available.
```
In the case where a cursor's selection does not fully contain any lines, that cursor and selection would be removed.
In the case where no selections fully contain any lines, instead of removing all cursors, the primary cursor would remain, as if the user pressed `;,`.
In the case where the selection already only contains full lines, this would necessarily have no effect (e.g. repeatedly invoking this command, or after pressing `X`). Similarly, `X` would have no effect following this command.

#### Motivation
My motivating use case is manually indenting code between matched delimiters.
If I have the following,
```rs
    fn foo() {
    a;
    b;
    c;
    }
```
And I want this:
```rs
    fn foo() {
        a;
        b;
        c;
    }
```
I might use `mi{>` to select the lines in the function body and indent the selected lines; but the resulting selection also includes the whitespace next to the opening and closing delimiters. Here I'm using `[` and `]` to outline the selection:
```rs
    fn foo() {[
    a;
    b;
    c;
    ]}
```
This is also an issue if I use `Alt-k` to select the body, as this includes both delimiters.
This means I need to do some more fiddly work to manually shrink both sides of the selection. If I had a command that shrinks the selection to only full lines, this would be trivial (using `mi`, `ma`, or `Alt-k`).
(Of course, I know rustfmt will indent everything nicely for me, but I'm not always doing this in rust. Sometimes it'll just be a plain txt file)

#### Problems / Questions
What key to use for this command? I would like to use `x` if it weren't already taken, for symmetry with `X`. `-` seems to not be bound, but seems like it may be good to keep unbound in case it is used for negative numbers with motions.

**Comment by the-mikedavis** [comment]
Fixed by #2450
