### ISSUE TITLE
Code Completion Not Working

### ISSUE THREAD

**Issue by nessun-dorma** [helix-editor/helix#2006]
### Summary

I am using Alacritty as the Default Terminal and I noticed that Code Completion is not working for Javascript files as well for Elixir FIles

### Platform

Windows

### Terminal Emulator

Alacritty

### Helix Version

22.03

**Comment by David-Else** [comment]
Did you install the relevant language server? https://github.com/helix-editor/helix/wiki/How-to-install-the-default-language-servers

**Comment by David-Else** [comment]
```
Binary for language server: Not found in $PATH
```
You have no language server installed, you need to follow the wiki instructions for the language servers you require.

**Comment by nessun-dorma** [comment]
I've installed ElixirLS. How to update the Path ??

**Comment by David-Else** [comment]
I looked at the instructions and it says:
```
unzip elixir-ls.zip -d /path/to/elixir-ls
```
So why not extract to somewhere that is already in your `$PATH`? I don't know what OS you are on, but on Linux I would use `/usr/local/bin`.

**Comment by nessun-dorma** [comment]
I am on Windows 11. I am a bit lost in here can you guide me ??

**Comment by nessun-dorma** [comment]
![image](https://user-images.githubusercontent.com/96528048/162251601-cbd47ba4-1754-430e-b3a4-5e06aa484047.png)
This is my Path Tree
I've included elixir-ls in there but Helix is not recognizing it

**Comment by David-Else** [comment]
Delete Windows and install Linux! :)

**Comment by nessun-dorma** [comment]
Can someone provide me a detailed guide on how to configure helix with elixir-ls

**Comment by the-mikedavis** [comment]
There isn't any configuration to do, it just needs to be installed. What does that `C:\LServers\elixir-ls\` have in it for files?

It looks like elixir-ls has a kinda weird packaging method where the zip file from the releases page has a `language_server.sh` (or `language_server.bat` for Windows) file that acts as the executable. You might need to copy that to `elixir-ls` so that shows up in the path.

**Comment by archseer** [comment]
> I've included elixir-ls in there but Helix is not recognizing it

You need to log out and log in again for $PATH changes to take effect.

**Comment by samuelmanzanera** [comment]
Hi.
I have the same issue, I'm on Mac.
Even by changing the command in the languages.toml
```toml
language-server = { command = "~/Documents/code/elixir/elixir-ls/language_server.sh" }
```

Any way to resolve it ?

**Comment by archseer** [comment]
I'm not sure ~ gets resolved correctly? Do you have any logs?

**Comment by idmitrievsky** [comment]
@the-mikedavis I added this step with renaming to the wiki section about `elixir-ls` 👍

**Comment by kirawi** [comment]
Closing as this isn't a bug with Helix itself.
