### ISSUE TITLE
discoverability window / autoinfo

### ISSUE THREAD

**Issue by nrdxp** [helix-editor/helix#201]
I have been using Kakoune now for a few years. I'm hoping I can fully switch to helix once it gets just a bit further along as I really love the integrated tree-sitter and lsp support. Hopefully I can contribute along the way, as my Rust isn't too bad. One of the features I really miss so far though is the little tooltip that pops up to help you remember certain actions you may not do every day.

It's also fully programmable so you can make your own little menu's for custom actions.

![image](https://user-images.githubusercontent.com/34083928/121398094-37eff880-c912-11eb-9b4c-6f3e8def2f28.png)

**Comment by pickfire** [comment]
I was looking into this. Probably the next thing I do but I am also looking an the API for this, at least kakoune seemed to duplicate quite some stuff. At the same time I am aiming for the rustdoc keys to be generated as well.

**Comment by archseer** [comment]
Resolved by #412
