### ISSUE TITLE
Missing syntax highlighting in windows

### ISSUE THREAD

**Issue by elferherrera** [helix-editor/helix#2012]
### Summary

The syntax highlighting is missing in windows. I have installed helix using cargo install. I created a soft link to the repo runtime folder in my AppData/roaming/helix. I checked with the --health flag and everything has a tick. However the syntax highlighting is not working

### Reproduction Steps

 

I tried this:

1. `hx`

I expected this to happen:

Instead, this happened:

### Helix log

<details><summary>~/.cache/helix/helix.log</summary>

```
please provide a copy of `~/.cache/helix/helix.log` here if possible, you may need to redact some of the lines
```

</details>

### Platform

windows

### Terminal Emulator

windows terminal 

### Helix Version

main branch

**Comment by kirawi** [comment]
Would you be able to elaborate on the reproduction steps? It's a little too vague 😅

**Comment by archseer** [comment]
What language are you trying to highlight? Do you get any errors in the log file if you start hx with the -v flag?

**Comment by elferherrera** [comment]
Sorry the instructions are a bit lacky, but that is all I have. I just open helix and I see no syntax highlighting.

Im working with rust. I am attaching my log file. I didnt find anything weird

[helix.log](https://github.com/helix-editor/helix/files/8448748/helix.log)

**Comment by CptPotato** [comment]
You might have to fetch & build the grammars:

```sh
hx --grammar fetch
hx --grammar build
```

**Comment by elferherrera** [comment]
sorry about this one, I was sure I fetched and built the grammar. This fixes the issue.
