### ISSUE TITLE
Go: Extra { and ( being created when pasting

### ISSUE THREAD

**Issue by mizzunet** [helix-editor/helix#2015]
### Summary
Extra end pairing being created for { and ( when pasting text having these start pairing.

### Reproduction Steps

 

I tried this:

1. `hx main.go`
2. Paste both
```
type item struct {
	StoryURL  string
}
```
```
type item struct (
	StoryURL  string
)
```

I expected this to happen:
Paste it normaly.

Instead, this happened:
See that it becomes,
```
type item struct {
	StoryURL  string
}
}
```
```
type item struct (
	StoryURL  string
)
)
```

### Helix log

<details><summary>~/.cache/helix/helix.log</summary>

```
󰅂 cat .cache/helix/helix.log 
2022-04-08T13:55:37.895 helix_view::editor [ERROR] Failed to initialize the LSP for `source.go` { cannot find binary path }
```

</details>

### Platform

Linux

### Terminal Emulator

foot

### Helix Version

 22.03

**Comment by CptPotato** [comment]
Do you paste using <kbd>Space</kbd><kbd>P</kbd> / <kbd>Space</kbd><kbd>p</kbd>?

**Comment by mizzunet** [comment]
> Do you paste using SpaceP / Spacep?

No. I paste the text in insert mode by Ctrl+Shift+V.

I just tried Space P/p. No issue with it.

**Comment by the-mikedavis** [comment]
See https://github.com/helix-editor/helix/issues/1021#issuecomment-963353157

Until the linked crossterm PR is merged, space-p is the go-to for pasting from clipboard.
