### ISSUE TITLE
LSP completions only affect first selection in multiple selection

### ISSUE THREAD

**Issue by aral** [helix-editor/helix#2016]
### Summary

If you have multiple selections, language completion only affects the first one.

### Reproduction Steps

Create a simple JS file and ensure JS LSP is installed.

```js
const be

console.log('to', foo, 'or not to', foo)
```

1. <kbd>g</kbd><kbd>3</kbd><kbd>g</kbd> (goto line 3)
2. <kbd>x</kbd> (select line)
3. <kbd>s</kbd> + `foo` <kbd>return</kbd> (select both `foo` instances)
4. <kbd>c</kbd> (change)
5. <kbd>b</kbd> <kbd>ctrl</kbd> <kbd>x</kbd> (autocomplete: select “be” constant – note: <kbd>tab</kbd> doesn’t seem to work with a two-letter autocompletion. Note: behaviour is the same if you use <kbd>tab</kbd> with a longer completion.)

## What should happen

Both `foo` instances should autocomplete to `be`:

```js
const be

console.log('to', be, 'or not to', be)
```

## What actually happens

Only the first `foo` autocompletes to `be`:

```js
const be

console.log('to', be, 'or not to', b)
```

### Helix log

n/a

### Platform

Linux (elementary OS 6; based on Ubuntu)

### Terminal Emulator

io.elementary.t

### Helix Version

helix 22.05-dev (2d4f94eb)

**Comment by aral** [comment]
@crdpa I just ran into it again myself. This is something that you can easily find yourself wanting to do quite often. It’s one of those things that I realise has made me quite tense when using Helix with multiple selections as I’m not entirely sure when it’s going to garble what I’m doing (the other is the auto completion of quotes not acting intelligently #2400) :)

**Comment by aral** [comment]
@the-mikedavis Sure. I just thought it might help folks if it was more visible as it’s such a common thing.

**Comment by aral** [comment]
PS. Above copy/pasted from the Wiki which uses asciidoc. Not sure why when markdown is used everywhere else. Don’t have time to look into converting it now.

**Comment by the-mikedavis** [comment]
Yeah we should probably convert the faq to markdown at some point to be consistent. I'll give the comment an edit and see if I can fix the display

**Comment by mtoohey31** [comment]
I've made an attempt at fixing this here: https://github.com/mtoohey31/helix/tree/feat/multi-selection-autocomplete. It seems to work, but I'm pretty sure I've made some unsafe assuptions about what the different offsets might be, so I don't think it's ready for a PR yet. Maybe someone who's more familiar with this code can use my attempt as a starting point.

**Comment by gf3** [comment]
just in case it's helpful here's an asciinema of the issue → https://asciinema.org/a/523860

**Comment by Jasha10** [comment]
The FAQ says "Note: If you use LSP autocomplete, only the first match will be auto-completed. If you want to auto-complete all matches, you currently have to [use this workaround](https://github.com/helix-editor/helix/issues/2016#issuecomment-1136920354)." Now that this issue is closed, can the FAQ can be updated?

**Comment by the-mikedavis** [comment]
Yep, I just pushed a change to remove that note 👍
