### ISSUE TITLE
LSP completions are case sensitive; add option to have them be case insensitive

### ISSUE THREAD

**Issue by aral** [helix-editor/helix#2017]
### Summary

LSP completions are case sensitive at the moment. It would be nice to have the option to make them case insensitive.

### Reproduction Steps

In the following example:

```js
const FOO

console.log(fo)
```

pressing <kbd>tab</kbd> after `fo` results in:

![Screenshot from 2022-04-08 11-35-06@2x](https://user-images.githubusercontent.com/41798/162419586-afa9b799-21cb-4875-acf4-e9dc989f60cb.png)

(FOO is not shown.)

## Why is this important?

Because it is more ergonomic not to have to press <kbd>shift</kbd> all the time.

## Suggested implementation

Either:

1. Make case-insensitive auto-completion the default, or
2. Make case-insensitive auto-completion a setting (this could make use of the already existing `smart-case` setting)

### Platform

Linux

### Terminal Emulator

io.elementary.t

### Helix Version

helix 22.05-dev (2d4f94eb)

**Comment by aral** [comment]
Sorry, I can’t remove the bug label. This is an enhancement request, not a bug.

**Comment by the-mikedavis** [comment]
I'm curious how other editors do this. I assume this would be something the language server would handle itself when figuring out what completions are available, but maybe we can handle it on the client side by figuring out permutations of the text for snake-case, camel-case, shout-case, etc.

**Comment by aral** [comment]
@the-mikedavis Not sure. I’m currently using the TypeScript LSP from VSCode but I think this might be the one that hasn’t been updated in a while. Someone mentioned a version that’s actively extracted from VSCode so I’ll try and see if the case sensitivity behaviour is inherited from the LSP or not and report back.

I know that in VSCode the completions are case insensitive (at least by default, I never felt the need to change that).

**Comment by votagus** [comment]
I'm coding in typescript now and suffering from this, where should I look to even try to improve this.
