### ISSUE TITLE
Moving around in insert mode triggers LSP completions; it shouldn’t

### ISSUE THREAD

**Issue by aral** [helix-editor/helix#2027]
### Summary

LSP completions should only be triggered while typing, not when moving around in LSP mode. Otherwise, it is very easy to corrupt code when using the up/down arrows to move between lines.

### Reproduction Steps

For easier reproduction, set `idle-timeout` to `0` in your _config.toml_:

```toml
[editor]
idle-timeout = 0
```

Then, with the following basic JS example:

```js
// Hello, World!
console.log('Hello, world')
```

1. Go to line 2 (<kbd>g2g</kbd>)
2. Enter insert mode (<kbd>i</kbd>)
3. Press the right-arrow key three times then press the up-arrow key to get to the comment on line 1.

## What should happen

The completion dialogue should not show and you should find yourself on line 1. The code on line 2 should remain unchanged.

## What actually happens

The completion dialog shows and pressing the up arrow inserts the `continue` completion in the middle of the `console` keyword so you end up with:

```js
// Hello, World!
continuensole.log('Hello, world')
```

### Helix log

n/a

### Platform

Linux (elementary OS 6; based on Ubuntu)

### Terminal Emulator

io.elementary.t

### Helix Version

helix 22.05-dev (2d4f94eb)

**Comment by sudormrfbin** [comment]
Previous discussion: https://github.com/helix-editor/helix/issues/1381.

**Comment by aral** [comment]
Given https://github.com/helix-editor/helix/issues/2580 if this cannot be fixed natively within the design of Helix, perhaps the thing to do is to concede that insert mode only works on a single line and to force the editor to exit into normal mode whenever the person navigates to a different line using the up/down arrow keys.

While this will require people to constantly go back and forth between insert and normal mode, this does appear to be the expectation from what I’ve been reading from the responses and by making it automatic, Helix would at least avoid the code corruptions that can result from moving between lines using the arrow keys in insert mode.

The other way to avoid the corruptions would be to make <kbd>tab</kbd> and <kbd>shift-tab</kbd> be the only ways to navigate the autocompletion drop downs. Come to think of it, this might be the better solution.

**Comment by archseer** [comment]
You shouldn't set `idle-timeout` to `0`: `idle-timeout` is used in other areas than just autocompletion, i.e. https://github.com/helix-editor/helix/commit/a85e3862988933953d1c0e7435969604d3722959

Setting it to `0` isn't recommended since you'll keep re-triggering various behaviors _immediately_ and waste a lot of CPU cycles. Even setting it to something as low as `2` or `5` would be better.

This same issue is present in kakoune. They offer an insert mode keybind: `<c-o>: disable automatic completion for this insert session` which could be used to disable completion before moving around.

**Comment by p1gp1g** [comment]
@aral : What do you think of the solution suggested in #4144 : a setting to ignore arrows to enter in the pop ups. So you can do `tab` then arrows to pick a suggestion (or only tabs)?

I am asking because I have supposed you had the same issue and this may help. But I may have wrongly supposed :)

**Comment by NukeManDan** [comment]
> Helix is a modal editor. You are not supposed to move in insert mode. Normal mode is intended for movement.

Although "correct" that doesn't help fix a common issue that many run into. If this is the stance of Helix, I think the arrow keys should be _disabled_ for movement in insert mode. Thus forcing you to use it "right". 

A better solution would be to change the insert LSP suggestions to be selected by something other than arrow keys or perhaps via `C+<arrow>` or `A+<arrows>` so insert navigation is _possible_ without this footgun IMHO.

**Comment by kirawi** [comment]
> If this is the stance of Helix, I think the arrow keys should be disabled for movement in insert mode.

It _was_ removed (https://github.com/helix-editor/helix/pull/3671), but there were a lot of people who expected at least a basic level of movement so we compromised (https://github.com/helix-editor/helix/pull/3915).

**Comment by kirawi** [comment]
Also see the linked PR that will close this: https://github.com/helix-editor/helix/pull/8021
