### ISSUE TITLE
Close buffer without closing split

### ISSUE THREAD

**Issue by CptPotato** [helix-editor/helix#2034]
As mentioned in #1902, closing a buffer in helix closes all splits that currently display that buffer aswell. As there are no suggestions in the discussion it seems like there aren't any workarounds right now, hence I'm creating this feature request.

The behavior that makes the most sense to me is going backwards through the jump list until a different buffer was found and jumping there. (basically clone the jump list, filter out the current buffer and go to the end if it's not empty).
If the buffer was the last in the jump list, either close the split or open a new scratch buffer (this would be similar to the behavior without splits).

---

This this way of handling `:bc` also extends to cases where there's only one window open:
Currently, if you close a buffer with only a single window, the first buffer in the picker is opened at the top of the file.

This is a bit cumbersome in this scenario for example:

1. while coding I jump to the type defininition of some library (<kbd>g</kbd> <kbd>d</kbd>)
2. once I'm done looking at the library source, I close the buffer as I don't need it anymore (`:bc`)
3. now I'm not back at where I was at step 1. I also can't <kbd>Ctrl</kbd> <kbd>o</kbd> to jump back, as the window was basically completely reset (jump list is gone)

---

Related: Discussed in https://github.com/helix-editor/helix/discussions/1902

<div type='discussions-op-text'>

<sup>Originally posted by **CptPotato** March 31, 2022</sup>
I often use a vertical split when jumping between two documents a lot. But whenever I close a buffer I have to reopen the split.

Is it currently possible to close a buffer but keep the split open?</div>

**Comment by archseer** [comment]
I agree that the current behavior isn't ideal, but we'd need to think about the various mappings a bit more. Ctrl-w mode should then have a way to explicitly close the view 

> once I'm done looking at the library source, I close the buffer as I don't need it anymore (:bc)

Couldn't you just ctrl-i back? I usually jump to definition, then backtrack via ctrl-o in the same split.

**Comment by CptPotato** [comment]
Yup, using `Ctrl + i` works for me in that specific case. I prefer to keep the list of open buffers clean with only the files I'm working on, but in the meantime I'll stick with just jumping back.

**Comment by matoous** [comment]
Should be closed by: https://github.com/helix-editor/helix/pull/1397
