### ISSUE TITLE
There should be no pause on switching to normal mode with escape

### ISSUE THREAD

**Issue by thomas-profitt** [helix-editor/helix#2039]
In Vim (or at least in Neovim), just like in Helix and Kakoune, when I'm in insert mode and I press escape, there's a pause before the editor enters normal mode.

In Helix, I can double-tap escape to return to normal mode quickly, but in Neovim, it starts listening for normal mode commands immediately after I hit escape, before it actually enters normal mode, so if I want to return to normal mode, save a file and quit, I use `<Esc>:wq`, with no pause. In Helix, I have to either `<Esc><long pause>:wq` or `<Esc><Esc>:wq`, and double-tapping a key with my pinky takes longer and requires more effort than tapping it once.

**Comment by the-mikedavis** [comment]
Are you using helix within tmux? And which terminal emulator are you using?

For me (helix within kitty, no tmux), there is no delay between hitting escape and switching to normal mode.

**Comment by thomas-profitt** [comment]
Ah! This is indeed tmux's doing, I forgot about this part of tmux!

Now I only wonder how it is that Neovim works around it. Is it sane for Helix to implement the same workaround? Should Helix document it and suggest reconfiguring tmux?

**Comment by the-mikedavis** [comment]
Ah I just found this in the nvim FAQ https://github.com/neovim/neovim/wiki/FAQ#esc-in-tmux-or-gnu-screen-is-delayed

A similar entry in our FAQ (https://github.com/helix-editor/helix/wiki/FAQ) would be welcome, would you like to add it?

**Comment by thomas-profitt** [comment]
Yes, I've added it to my todo list and I'll link the PR to this issue.

**Comment by thomas-profitt** [comment]
Closed by https://github.com/helix-editor/helix/wiki/Troubleshooting#when-using-tmux-or-screen-there-is-a-delay-after-hitting-escape-before-its-registered
