### ISSUE TITLE
Using a scripting language

### ISSUE THREAD

**Issue by elferherrera** [helix-editor/helix#2047]
I have been using helix for my development for the past week and I'm loving it. Thanks a lot for the effort. 

During my usage I have noticed that the lack of a script language may affect the project in the long term. Im thinking how successful nvim is thanks to its integration with Lua. I know that the team has decided to use wasm as the plugin language, which would enable to use anything that can be compiled to wasm. However, that may hinders the development of plugins. So, I was wondering if besides wasm, would you like to consider using a scripting language? and also, what do you feel about using Nushell for it? I think both can be good fit.

**Comment by the-mikedavis** [comment]
There is some discussion of scripting languages which would be usable with the wasm plugin model in #122.

A scripting-language alternative to the wasm plugin system has been discussed on the matrix a bit. I can't speak for everyone but IIRC the thoughts around it were that we would only like to support scripting languages through the wasm plugin system. An alternative plugin/scripting system would be similarly cumbersome to implement as the wasm plugin system (which is already a **large** effort) and then if both are implemented, the plugin/scripting ecosystem would most likely end up divided between the two approaches.

So for now I will close this out as wontfix, but if other maintainers think I'm out of line: please reopen. We can swing back around to this ticket in the future if the motivation for the wasm plugin system changes (unlikely but you never know).
