### ISSUE TITLE
Freeze when 'Alt-C' is pressed and there are no above lines as long as the current selection

### ISSUE THREAD

**Issue by n0s4** [helix-editor/helix#2048]
### Summary

When I press `A-C` (`copy_selection_on_prev_line`) where the line above the cursor is shorter than the current selection on the current line.

helix freezes and it's CPU usage shoots to 25% (an entire core), no keypress does anything.

When I inevitably shut down my terminal, 'x-terminal-emulator' shoots momentarily to 100% CPU usage on my system monitor, and promptly disappears.

This does not happen with normal `C` (`copy_selection_on_next_line`) which works as expected.

### Reproduction Steps

 

I have a text file with the following content
```
This is a short line
This is a longer line
```
with the cursor on the bottom line, I press the following keys:

`x`, `A-C`

That's it.

### Helix log

<details><summary>~/.cache/helix/helix.log</summary>

```
[helix.log](https://github.com/helix-editor/helix/files/8456705/helix.log)
```

</details>

### Platform

Linux

### Terminal Emulator

Alacritty 0.10.1-rc1

### Helix Version

22.03-50-gd37369c1

**Comment by n0s4** [comment]
I just now found that `A-c` doesn't look to the above line, but searches up for a line long enough to match the length of the current selection. Helix only freezes when there are no above lines long enough. I have changed the issue title accordingly

**Comment by thlsrms** [comment]
I just started learning Helix and faced the same problem.

After a little investigation I found that this line doesn't check the upper bounds of the file, I think.
https://github.com/helix-editor/helix/blob/0c05447d49103e96fc21910d336bdc75ab96338d/helix-term/src/commands.rs#L1441

So this actually fixed it for me:
```rust
if anchor_row >= text.len_lines()
    || head_row >= text.len_lines()
    || anchor_row < 1
    || head_row < 1
{
    break;
}
```
Without this check the `offset` didn't stop growing inside the while loop and the cpu usage got stuck at 25%.

I'm kinda new to rust so I might have missed something else.

**Comment by pascalkuthe** [comment]
can't reproduce anymore on latest version
