### ISSUE TITLE
Support custom LSP

### ISSUE THREAD

**Issue by Joe-Davidson1802** [helix-editor/helix#205]
I want to use helix but I can't seem to customise the LSPs. 
The language is https://github.com/a-h/templ and contains it's own lsp under the command `templ lsp`, I tried adding an entry in my own languages.toml but it seems there is an enum that stops you from adding your own entry.

**Comment by pickfire** [comment]
Oh, seemed like you can't right now.

https://github.com/helix-editor/helix/blob/59f94d13b8d61ce338ecf4957c6b4ad945021009/helix-syntax/src/lib.rs#L66-L92

This requires support to use custom language name.

**Comment by archseer** [comment]
Yeah, we need to be able to define languages in `languages.toml` without binding them to tree-sitter.

**Comment by archseer** [comment]
With `languages.toml` no longer being tied to a tree sitter grammar, you should be able to define a custom language declaration now.
