### ISSUE TITLE
Error while "Building From Source"

### ISSUE THREAD

**Issue by beyourahi** [helix-editor/helix#2050]
### While building from source I'm getting this error:

```
error: failed to parse manifest at `/home/rahi/helix/helix-term/Cargo.toml`

Caused by:
  failed to parse the `edition` key

Caused by:
  this version of Cargo is older than the `2021` edition, and only supports `2015` and `2018` editions.

```

### What do I do now?

**Comment by David-Else** [comment]
You need to use at least Rust 1.59 I think, I suggest you update the toolchain.

**Comment by the-mikedavis** [comment]
IIRC our current MSRV is 1.57 (although in some recent history we have accidentally bumped up to 1.58). This version of rust looks much older.

**Comment by sudormrfbin** [comment]
If you installed rust via rustup, `rustup update stable` and then building again should work.
