### ISSUE TITLE
Default config, No highlighting on JSX.

### ISSUE THREAD

**Issue by reiend** [helix-editor/helix#2057]
I haven't override anything. This is the default config.
left window is a tsx file.
right is a jsx file

hx --health shows that highlighting was found.
why does jsx doesn't have one?

![image](https://user-images.githubusercontent.com/93508511/162611858-aef7827d-adf1-492d-ab1e-d536ba204372.png)

**Comment by David-Else** [comment]
Are you using the latest master? There was a fix since `22.03` came out: https://github.com/helix-editor/helix/pull/1921

**Comment by reiend** [comment]
> Are you using the latest master? There was a fix since `22.03` came out: #1921

yes I am. @David-Else.  thanks for the link.

**Comment by reiend** [comment]
Thanks again @David-Else.
Closing this now.
