### ISSUE TITLE
"Bad language config" using default languages.toml

### ISSUE THREAD

**Issue by sullyj3** [helix-editor/helix#2058]
### Summary

The default languages.toml doesn't load correctly

### Reproduction Steps

 

I tried this:

The [language support documentation page](https://docs.helix-editor.com/lang-support.html) links to the default [languages.toml](https://github.com/helix-editor/helix/blob/master/languages.toml). When I place this file in ~/.config/helix/langauges.toml and run `hx`, 

### I expected this to happen:
default langauges.toml loads correctly

### Instead, this happened:

```
Bad language config: unknown field `grammar`, expected `language`
Press <ENTER> to continue with default language config
```

### Helix log

<details><summary>~/.cache/helix/helix.log</summary>

```
2022-03-27T11:36:23.817 helix_view::editor [ERROR] Failed to initialize the LSP for `source.md` { LSP not defined }
2022-03-27T11:36:31.725 helix_view::editor [ERROR] Failed to initialize the LSP for `source.md` { LSP not defined }
2022-03-27T22:24:18.307 helix_view::editor [ERROR] Failed to initialize the LSP for `source.nix` { IO Error: No such file or directory (os error 2) }
2022-03-27T22:26:48.354 helix_view::editor [ERROR] Failed to initialize the LSP for `source.nix` { IO Error: No such file or directory (os error 2) }
2022-03-27T22:26:48.354 helix_view::editor [ERROR] Failed to initialize the LSP for `source.nix` { IO Error: No such file or directory (os error 2) }
2022-04-10T18:20:08.796 helix_view::editor [ERROR] Failed to initialize the LSP for `source.toml` { LSP not defined }
2022-04-10T18:20:49.807 helix_view::editor [ERROR] Failed to initialize the LSP for `source.toml` { LSP not defined }
2022-04-10T20:01:19.803 helix_view::editor [ERROR] Failed to initialize the LSP for `source.toml` { LSP not defined }
2022-04-10T20:05:05.024 helix_view::editor [ERROR] Failed to initialize the LSP for `source.toml` { LSP not defined }
2022-04-10T20:08:32.494 helix_view::editor [ERROR] Failed to initialize the LSP for `source.toml` { LSP not defined }
```

</details>

### Platform

Linux 

### Terminal Emulator

alacritty

### Helix Version

I believe 22.03 (from nixpkgs unstable, using `nix-shell -p helix`)
Though I'm not 100%, since `hx -V` just gives "helix"

**Comment by David-Else** [comment]
You don't need to copy `languages.toml`, this file name is only used in the config directory if you want to override a default, for example:
`languages.toml`
```
[[language]]
name = "markdown"
language-server = { command = "ltex-ls" }
file-types = ["md"]
scope = "source.markdown"
roots = []
```

**Comment by sudormrfbin** [comment]
The link for the default language file in the docs point to master when the docs itself is for the latest released version, hence the error is due to the mismatch.

**Comment by sullyj3** [comment]
Oh, I assumed I had to do something more because haskell language server didn't seem to be doing anything out of the box.

In any case, I tried the language.toml from the 22.03 tag and got the same result

**Comment by sullyj3** [comment]
Separately, how would I go about debugging why a language server isn't doing anything if I get rid of languages.toml? I'm not seeing anything about it in the docs, and nothing lsp related seems to show up in the log with `-vvv`

**Comment by the-mikedavis** [comment]
It looks like you're on an old version. It must be a channel that's out of date.

```
$ nix run nixpkgs#helix -- --version
helix                                                   # was a packaging bug in the 0.6.0 release
$ nix run nixpkgs/nixos-unstable#helix -- --version
helix 22.03 (d4e45fd4)                                  # hx -V was fixed in 22.03
```

**Comment by David-Else** [comment]
@the-mikedavis If this page is meant to only reflect the current release it would be a good idea to add that information. Otherwise it is quite out of date now. It seems a mirror of the `helix --health` output, is generate with a tool or by hand?

**Comment by the-mikedavis** [comment]
That gets generated by `cargo xtask docgen` and we have the CI set up to give an :x: when it's out of date, so it should be up to date on every commit. That particular page is the current release's documentation though - the master docs for that page is [here](https://docs.helix-editor.com/master/lang-support.html).

**Comment by the-mikedavis** [comment]
> Separately, how would I go about debugging why a language server isn't doing anything if I get rid of languages.toml?

Usually the logs (`-vvv` most verbose as you say) are a good way to debug LSP related issues - it'll log the requests/responses between the client and server.

The default `languages.toml` is actually baked into `hx` and your custom `languages.toml` (which you can create at `~/.config/helix/languages.toml`) has its TOML merged in. So if I wanted to disable language-server auto-format for Rust, I could say:

```toml
# ~/.config/helix/languages.toml
[[language]]
name = "rust"
auto-format = false
```

for example.

**Comment by David-Else** [comment]
> That gets generated by `cargo xtask docgen` and we have the CI set up to give an x when it's out of date, so it should be up to date on every commit. That particular page is the current release's documentation though - the master docs for that page is [here](https://docs.helix-editor.com/master/lang-support.html).

This is valuable information, would be great if you could integrate it somehow to https://docs.helix-editor.com/lang-support.html

**Comment by the-mikedavis** [comment]
I rewrote that doc's notes on the language config in #2065. The difference between master and release docs seems to be a pretty consistent problem so I added #2064 and will probably take a look at that soon. The `cargo xtask docgen` stuff I think is more of an implementation detail that you shouldn't have to care about unless you're adding a new language upstream, and for that we have the adding languages guide (also touched by #2065).

**Comment by sullyj3** [comment]
It's not that my channel's out of date
```
⮞ cat ~/.nix-channels
https://github.com/nix-community/home-manager/archive/master.tar.gz home-manager
https://nixos.org/channels/nixpkgs-unstable nixpkgs

⮞ nix-channel --update; and nix-shell -p helix --run 'hx -V'
unpacking channels...
helix

⮞ nix run nixpkgs/nixos-unstable#helix -- --version
helix 22.03 (d4e45fd4)
```

But there's definitely something screwy going on with my nix installation or something I'm not understanding. In any case, that's not related to helix and it's for me to figure out I guess, so I'll close
