### ISSUE TITLE
Bug: Syntax highlighting breaks in rust file

### ISSUE THREAD

**Issue by ahkrr** [helix-editor/helix#206]
Helix was build with the current git/master branch.

https://user-images.githubusercontent.com/44893716/121489961-e3618180-c9d4-11eb-9d18-ca709bcc4392.mp4

I have noticed that in some of my code, methods get highlighted with the color for variables.
In this case, `TokenStream::form_iter` and `.set_span` should also be green. 

![hx_syn](https://user-images.githubusercontent.com/44893716/121489989-e78d9f00-c9d4-11eb-86e3-35c8a6ede979.png)

I tried to look into the issue and ended up in `helix-core/src/syntax.rs +1309` `HighlightIter::next`. 
At this point I have no desire to try to understand whats going on in there and where the problem could be originating form.
I ende my search at `layer.captures`.

I tried the default theme.toml and it also breaks, but it is less legible (in my opinion).

**Comment by archseer** [comment]
For the video, I've noticed that and I think it's an issue with multiple cursors, the edits sent to tree sitter aren't generated with the right offsets for subsequent cursors:

https://github.com/helix-editor/helix/blob/aebdef8257173b31df77ae02bb23ec2abfd07e5c/helix-core/src/syntax.rs#L541-L652

(note, that TODO might be easier to address now that `transaction.changes_iter()` exists.)

---

For the second example can you give me a copy-pastable example so I can inspect it on https://tree-sitter.github.io/tree-sitter/playground ? I suspect we might be taking the wrong scope out here, it could be that `spans.last()` fixes it:

https://github.com/helix-editor/helix/blob/aebdef8257173b31df77ae02bb23ec2abfd07e5c/helix-term/src/ui/editor.rs#L154-L167

The best behavior might be to iter over all the scopes and merge styles.

**Comment by ahkrr** [comment]
The image is from some toy-code of mine that is from here [byte-match](https://github.com/ahkrr/byte-match.git).
It is only a single file 117 lines. The example is at the end of `src/lib.rs`

**Comment by archseer** [comment]
Ah okay, I see it now, `vec!` is a macro invocation and everything inside it just gets parsed as identifiers since it's possible it's not valid rust code. I think there was an issue open on tree-sitter-rust about it, I'd prefer if a parse was at least attempted.

**Comment by ahkrr** [comment]
"{" @punctuation.bracket                    
"}" @punctuation.bracket                    
"," @punctuation.delimiter                  
":" @punctuation.delimiter                  
                                            
(identifier) @variable                      

I added these in my own `rust/highlights.scm`
If someone does this black and white trick on their own stuff, they will see more uncategorized things.
Should these rules or a some variation of them be introduced into the official `rust/highlights.scm`?

**Comment by archseer** [comment]
We likely want to port some of these punctuation/operator rules: https://github.com/nvim-treesitter/nvim-treesitter/blob/3b516c8e2b29dc2f8bfa5425a1b9369496918884/queries/rust/highlights.scm#L213

I probably never noticed because I don't highlight those. We do definitely accept these types of query improvements to `runtime/` because the upstream tree-sitter files were very barebones.

**Comment by archseer** [comment]
Resolved by #430
