### ISSUE TITLE
Commenting not working correctly on Multicursor.

### ISSUE THREAD

**Issue by reiend** [helix-editor/helix#2062]
I'm not sure if this is intended but, I think It would be a nice feature to have.

### Issue
![comments](https://user-images.githubusercontent.com/93508511/162623332-c6e4615b-b27f-44e9-8060-6da65e440be4.gif)

### Expected result
![comment_expected](https://user-images.githubusercontent.com/93508511/162623571-6d387cc3-9aa0-4c2e-9aff-37809afee728.gif)

### Platform
Windows 10, Powershell

### Helix Version
helix 20.03

**Comment by the-mikedavis** [comment]
Fixed by https://github.com/helix-editor/helix/pull/1882
