### ISSUE TITLE
Unable to set extra features for rust in LSP

### ISSUE THREAD

**Issue by elferherrera** [helix-editor/helix#2063]
### Summary

It is unclear in the language section of the Helix book how to configure the `language.toml` file to allow extra features for rust analyzer. It seems that it is only doing analysis on `default`. 

### Reproduction Steps

I tried this:

```
language-server.features = ["dataframe"] 
```

but it didnt work

### Platform

windows

### Terminal Emulator

windows terminal

### Helix Version

latest main

**Comment by kirawi** [comment]
I think you're looking for something like this:
https://github.com/helix-editor/helix/blob/34766e242ab0a059c8313b068b98d275e2a879b8/languages.toml#L11-L14

**Comment by elferherrera** [comment]
Thanks for the suggestion. I was looking for something more like this

```
  7     server = {
    6         autostart = true,
    5         -- standalone file support
    4         -- setting it to false may improve startup time
    3         standalone = false,
    2         -- on_attach is a callback called when the language server attachs to the buffer
    1         on_attach = on_attach,
  185         cmd = { "rust-analyzer" },
    1         filetypes = { "rust" },
    2         settings = {
    3             -- to enable rust-analyzer settings visit:
    4             -- https://github.com/rust-analyzer/rust-analyzer/blob/master/docs/user/generated_config.adoc
    5             ["rust-analyzer"] = {
    6                 -- enable clippy on save
    7                 checkOnSave = {
    8                     command = "check"
    9                 },
   10                 cargo = {
   11                     features = {"dataframe"}
   12                 },
   13             }
   14         }
```

**Comment by sudormrfbin** [comment]
In your languages.toml:

```toml
[[language]]
name = "rust"

[language.config]
checkOnSave = { command = "check" } 
cargo = { features = ["dataframe"] }
```
Everything under the `settings["rust-analyzer"]` key in nvim (which is a lua table) goes under `language.config` in helix (which is TOML). Note that the first two lines are important to identify for which language the config is defined.

**Comment by elferherrera** [comment]
Perfect. Just what I needed

**Comment by jgardona** [comment]
> In your languages.toml:
> 
> ```toml
> [[language]]
> name = "rust"
> 
> [language.config]
> checkOnSave = { command = "check" } 
> cargo = { features = ["dataframe"] }
> ```
> 
> Everything under the `settings["rust-analyzer"]` key in nvim (which is a lua table) goes under `language.config` key in helix (which is TOML). Note that the first two lines are important to identify the language for which the config is defined.

there is no field config
```
Bad language config: unknown field `config`, expected one of `name`, `language-id`, `scope`, `file-types`, `shebangs`, `roots`, `comment-token`, `text-width`, `soft-wrap`, `auto-format`, `formatter`, `diagnostic-severity`, `grammar`, `injection-regex`, `language-servers`, `indent`, `debugger`, `auto-pairs`, `rulers`, `workspace-lsp-roots`
in `language`
```

**Comment by kirawi** [comment]
The format changed in `23.10`. Try
```toml
[language-server.rust-analyzer.config]
# ...
```
