### ISSUE TITLE
Add a command to open the file picker in the current directory

### ISSUE THREAD

**Issue by oati** [helix-editor/helix#2068]
#### Describe your feature request

Right now, it seems like the file picker sets its root directory to the git repository of the project.
In large projects, I often want to work only within some subdirectory of the git repo.
So, a command like `<space>c` for "open file picker in the current directory" might be useful.

**Comment by the-mikedavis** [comment]
This was actually just merged a few hours ago! https://github.com/helix-editor/helix/pull/1600

The new binding is <kbd>space</kbd><kbd>F</kbd>.
