### ISSUE TITLE
typescript-language-server removes all formatting on write

### ISSUE THREAD

**Issue by atog** [helix-editor/helix#207]
I'm running Helix from master and configured the [typescript-language-server](https://github.com/theia-ide/typescript-language-server) for JavaScript. It looks like it's working correctly (I get nice error messages and warnings) but upon writing it removes all formatting.

Not sure whether this is a bug or a misconfiguration.

**Comment by archseer** [comment]
It's https://github.com/helix-editor/helix/issues/53, we call `:format` on save which leverages the LSP. Should be configurable in `languages.toml` and disabled for everything except `rust` and `go` I think.
