### ISSUE TITLE
Flatpak package

### ISSUE THREAD

**Issue by the-mikedavis** [helix-editor/helix#2076]
### Discussed in https://github.com/helix-editor/helix/discussions/1968

<div type='discussions-op-text'>

<sup>Originally posted by **martincalveira** April  5, 2022</sup>
Hi!

Is it on the roadmap to create an Appimage or Flatpak package? 

Thank you.</div>

**Comment by mtoohey31** [comment]
I can try to put together an AppImage. I'm new to both AppImages and Flatpaks but I'm happy to learn. Based on some quick research, AppImage seems like it may be the better choice since it's more self-contained. If anyone with more experience with these things has an opinion though, please weigh in!

**Comment by sudormrfbin** [comment]
AppImages don't require any kind of installer, and I've found that aspect of it useful when using Neovim's AppImages. "Make it executable and run" is quite easy to do. I haven't used Flatpak so not much opinions there.

**Comment by mtoohey31** [comment]
AppImages seem to require a `.desktop` entry, so maybe I can close #1073 while I'm at it, but they also seem to require a png icon. As far as I can tell, this project doesn't have an icon yet, right?

**Comment by the-mikedavis** [comment]
#283 has a brainstorm and there are a bunch of good ideas there but nothing chosen yet

**Comment by David-Else** [comment]
If you (somehow) embed the right metadata in the Appimage then you can use https://github.com/AppImage/AppImageUpdate to auto update the appimage, pretty cool!

It is still alpha software, but I am sure it will be fully working soon and it would be amazing to get auto-updating nightly releases at the press of a button :)

**Comment by mtoohey31** [comment]
> If you (somehow) embed the right metadata in the Appimage then you can use https://github.com/AppImage/AppImageUpdate to auto update it, pretty cool!

I take it you're referring to [this part of the spec](https://github.com/AppImage/AppImageSpec/blob/master/draft.md#update-information)? It seems like supporting that is pretty simple with the linuxdeploy appimage, I'll see what I can do!

**Comment by snoopdouglas** [comment]
I'd like a Flatpak if possible. It's always really useful to have the option of an AppImage, but I like being able to update all of my apps from one place (ie. `flatpak` CLI, or the GNOME Software Center).

**Comment by gabydd** [comment]
Just fyi on https://github.com/blt-r/helix-flatpak/blob/main/com.helix_editor.Helix.yml#L4 should this be 22.12 instead of 22.08

**Comment by blt-r** [comment]
> Just fyi on https://github.com/blt-r/helix-flatpak/blob/main/com.helix_editor.Helix.yml#L4 should this be 22.12 instead of 22.08

No, 22.08 is version of `org.freedesktop.Sdk`, not the version of Helix

**Comment by gabydd** [comment]
Oh makes sense sorry about that

**Comment by blt-r** [comment]
Helix is now [available on FlatHub ](https://flathub.org/apps/details/com.helix_editor.Helix).
Some things about this package:
- Your config will be in `~/.var/app/com.helix_editor.Helix/config/helix`
- To use language servers installed on host system you will have to invoke them with `flatpak-spawn --host`.
  For example:
  ```toml
  [[language]]
  name = "rust"
  language-server = { command = "flatpak-spawn", args = ["--host", "rust-analyzer"] }
  ```

**Comment by the-mikedavis** [comment]
Awesome, thank you!

**Comment by ZennMystic** [comment]
see base help with like Dart and Rust... And some other stuff and not clear on....

Could someone please help and guide me though a complete for C/C++ (and bash scrips maybe?)
I installed via flatpak and installed clangd and its in my path.. But I get red x when I do hx health check thing...
I total lost on howto to setup to work

please help?

Oh yes I am on Debian 12 x64

**Comment by blt-r** [comment]
The flatpak is running inside of a container, which means it doesn't integrate with your host system and can't access executables installed on it. If you want helix to be integrated into your host system it's better to install it as a native package.

If you want to set up helix flatpak to work with clangd you need to install flatpak sdk extension. There are instructions on how to do that in [this file](https://github.com/flathub/com.helix_editor.Helix/blob/master/HELIX_FIRST_RUN.md). You were supposed to see that file the first time you ran helix, but maybe you opened another file so that one was in a different buffer.

**Comment by ZennMystic** [comment]
Yea ok thank you... But I totally lost... I do not know rust nor I'm in interested in.. But I still have to install cargo to use Helix? I is not understands what I have to do with flatpak to use Helix either.
clangd is native but Helix was flatpak.
Is place I could post for help?

**Comment by blt-r** [comment]
You don't need cargo to install helix. Read through that file, it explains how to add sdk extensions for different languages. To get clangd you will need llvm16 sdk extension.

Or find a way to install helix natively, so you can use clangd installed on your host system.
