### ISSUE TITLE
Characters involving 'alt-gr' (for example: |, {, [, @ ) cannot be typed in normal mode on several keyboard layouts.

### ISSUE THREAD

**Issue by Natr1x** [helix-editor/helix#2080]
### Summary

Some keyboard layouts (such as a standard Swedish one) holds down 'alt-gr' (Alt Graph) when type several important character.

This works in insert mode but not in normal mode or any of the minor modes where the inputs are seemingly ignored.

For me (who uses a Swedish keyboard) it means I cannot type any of these characters: `@ £ $ { [ ] } \ |`
which as you can probably imagine is a problem if I want to for example select all whitespace `\s`, pipe to shell with `|`, or open a nested file on a windows file system `:o <directory>\<file>`.

### Edit!

This does not seem to be a problem when building and running Wsl2 Ubuntu

### Reproduction Steps

I tried this (in PowerShell 7.2.2):

1. Ran `hx tutor.txt` to open the tutor.txt file
2. Pressed `/` to search using regex
3. Pressed `<AltGraph>+\` together. On a Swedish keyboard the scancodes are 'E0 38' and '0C' respectively.

I expected this to happen:

A `\` character to be inserted.

Instead, this happened:

Nothing happened.

### Helix log

<details><summary>~/.cache/helix/helix.log</summary>

</details>

The logs did not contain any relevant lines. But this may be more due to perhaps helix not working properly in windows because I don't think I properly managed to increase the log level.

### Platform

Windows 10 Pro 21H2, 19044.1586, Windows Feature Experience Pack 120.2212.4170.0

### Terminal Emulator

Windows Terminal Version: 1.12.10732.0, also tested with powershell 7.2.2's built in terminal and vscodes integrated terminal.

### Helix Version

22.03-69-g7cb6e07b

**Comment by CptPotato** [comment]
Related: #595
