### ISSUE TITLE
Unable to change theme

### ISSUE THREAD

**Issue by hdquemada** [helix-editor/helix#2087]
I have installed helix on three machines:
Macbook Pro 2018 running monterey
Macbook Pro 2014 running big sur
Macbook Pro 2011 running Ubuntu 20.4

for MacOS I am using the native terminal
for Ubuntu, I am using GNOME terminal

Mac OS installations give me this error message when trying to apply themes:
unsupported theme: theme requires true color support

the linux installation has no problem.

I have installed helix both as a brew package, and building from source (uninstalling brew before building from source), and the problem exists either way.

Thanks for advice on how to solve this issue.

**Comment by the-mikedavis** [comment]
The regular macos terminal lacks true color support, so true-color themes can't be used with it: https://github.com/helix-editor/helix/wiki/Troubleshooting#rendering-issues-on-macos-terminal

iTerm2, Kitty, Alacritty, and WezTerm are all good alternatives on macos that support true-color.

**Comment by hdquemada** [comment]
Thanks! I will give those a try.
---
Hector
