### ISSUE TITLE
configurable keybindings

### ISSUE THREAD

**Issue by robinvd** [helix-editor/helix#209]
Currently i think all keybindings are hardcoded in keymap.rs. It would be nice to be able to configure this either through commands (vim/kak) or maybe a simple toml file

**Comment by wojciechkepka** [comment]
I wanted to open the exact same issue just now :P I guess you were first. I wanted `^` and `$` keybindings like in vim so I submitted #210, perhaps this could solve the problem.

**Comment by PabloMansanet** [comment]
Happy to pick this up as discussed @archseer

**Comment by archseer** [comment]
I think this is now resolved.
