### ISSUE TITLE
Why do I need sudo to install grammars?

### ISSUE THREAD

**Issue by maxtremblay** [helix-editor/helix#2091]
### Summary

When I run `hx --grammar fetch`, I get an error related to permission. I can do it with `sudo`, but this seems a bit weird to me. At least, it is not documented.

### Reproduction Steps

 

I tried this:

1. `hx --grammar fetch`

I expected this to happen:

Successfully fetching all grammar sources.

Instead, this happened:

```
...

Error: Failed to fetch some grammar(s)

Caused by:
    0: Could not create grammar directory "/usr/share/helix/runtime/grammars/sources/rust"
    1: Permission denied (os error 13)
```

Note that the last value in the path, `rust` in the example, is arbitrary, and I get other languages depending on which one fail first. 

### Helix log

The log file is empty.

### Platform

Fedora 35

### Terminal Emulator

alacritty 0.10.1

### Helix Version

helix 22.03 (d4e45fd4)

**Comment by archseer** [comment]
You shouldn't need to `sudo` (and I don't recommend it), but in this case your package is installed into `/usr/share` so we're not able to upgrade those grammars. I guess there needs to be some notion of "system" runtime provided by the package vs user runtime in `~/.config/helix/runtim`
