### ISSUE TITLE
Fuzzy search on file contents

### ISSUE THREAD

**Issue by robbienohra** [helix-editor/helix#2095]
#### Describe your feature request

I may be missing something, I know there is the `global-search` command, and fuzzy search against file names, but is there no fuzzy search against file _contents_? If so I'd be happy to get pointed in the right direction, otherwise this seems like a no-brainer feature, it's annoying otherwise to have to manually re-enter a global search each time and then fuzzy search on the file names.

**Comment by archseer** [comment]
See https://github.com/helix-editor/helix/issues/1283#issuecomment-1008831852=

**Comment by archseer** [comment]
Also https://github.com/helix-editor/helix/issues/196

**Comment by robbienohra** [comment]
ah thanks!
