### ISSUE TITLE
Helix selects texts following mouse cursor automatically

### ISSUE THREAD

**Issue by poliorcetics** [helix-editor/helix#2102]
### Summary

I have a document in helix:

```
a
b
c
d
e<cursor is here>
f
g
h
```

When my mouse goes over `helix`, the test is selected automatically from the cursor to the mouse pointer, both when the mouse is above and below.

This does not happen in `vim` or `noevim`.

I tried with master https://github.com/helix-editor/helix/commit/764adbdcf6f0a5615d1ddd3abb7ed7b9cf0f2d92 but also with the 10 oldest commits and nothing changed.

It was not happening yesterday so I think this is due to the [kitty 0.25.0 update](https://sw.kovidgoyal.net/kitty/changelog/#id1) now correctly sending some events that helix does not handle correctly on its side

### Platform

macOS

### Terminal Emulator

kitty 0.25.0

### Helix Version

helix master https://github.com/helix-editor/helix/commit/764adbdcf6f0a5615d1ddd3abb7ed7b9cf0f2d92

**Comment by poliorcetics** [comment]
I confirm this happens on helix's side:

setting `[editor] mouse = false` makes the problem go away

**Comment by arjpar** [comment]
I can confirm I'm facing the same issue in Kitty using GNOME (Wayland) on Linux (EndeavourOS/Arch).

**Comment by archseer** [comment]
It could also be kitty sending wrong/different events, given this works on other terminals.

Can you `log::info!("event = {:?}",  event)` here and do some diagnosing: https://github.com/helix-editor/helix/blob/master/helix-term/src/ui/editor.rs#L958=

My guess is kitty now sends drag events for movement. https://github.com/helix-editor/helix/blob/master/helix-term/src/ui/editor.rs#L1015-L1034=

**Comment by argentite** [comment]
It seems to have been fixed at https://github.com/kovidgoyal/kitty/commit/55b21b741ebc45453f089c962ec46feff394c0e4 . It works correctly on latest nightly build of kitty for me.

**Comment by poliorcetics** [comment]
This was fixed with the last release (or previous) release of kitty, I forgot to close earlier sorry !
