### ISSUE TITLE
Visual feedback when there are multiple selections

### ISSUE THREAD

**Issue by n0s4** [helix-editor/helix#2103]
#### Describe your feature request

There are a couple issues already asking for visual feedback in some situations:
- #2045
- #2044

However I was doing some renaming (`%s...c`) in a file and forgot to close with `,`. I didn't realise I had another dozen selections elswhere in the file for minutes, where I had to undo everything due to the damage the other cursors had caused.

Maybe changing the colour of (a section of?) the status bar to make it more noticeable would help, e.g change the colour in the left mode indicator section depending on mode, change colour of the No. of selections section if you have multiple selections, etc.

**Comment by Ordoviz** [comment]
We could show an indicator for each selection in the scrollbar (like Google Chrome does for Ctrl+F) as demonstrated in mawww/kakoune#2727.

**Comment by pascalkuthe** [comment]
I think this was reasonably addressed by  #4682

**Comment by sshilovsky** [comment]
An alternative way to address this would be to let the user to undo the changes sequentially, then clear up the selections (`,`) and then reapply the edits undone, but just to the current selection(s).
