### ISSUE TITLE
Short-term way to show hidden files for the current "open file" operation

### ISSUE THREAD

**Issue by CBenoit** [helix-editor/helix#2106]
> Some short-term way to show hidden files for the current "open file" operation would be nice to have! Not having hidden files mess up the search result is the correct thing in 95% of the searches I do, so I am reluctant to change the default. It would be awfully convenient to be able to just toggle the "hidden" setting for the one search I am doing in the last 5%.

_Originally posted by @hunger in https://github.com/helix-editor/helix/discussions/1820#discussioncomment-2403515_

Just thought it would be useful to track this in a new issue.

**Comment by pascalkuthe** [comment]
You can do this with negative matches. For example `!/. !^.` hides all hidden files from the picker
