### ISSUE TITLE
Misbehaving bracket-matching highlighting in rust lang

### ISSUE THREAD

**Issue by workingj** [helix-editor/helix#2110]
### Summary

misbehaving highlighting of bracket pairs and auto-pairs with rust 
![simplescreenrecorder](https://user-images.githubusercontent.com/19818596/163439361-575ab93a-795c-4752-afba-8855228b5ba3.gif)
 

### Reproduction Steps

Writing Rust and moving through a string of a println! statement.

### Platform

Linux

### Terminal Emulator

GNOME Terminal 3.38.1

### Helix Version

helix 22.05-dev (764adbdc)

**Comment by n0s4** [comment]
Have you change anything in the `editor.auto-pairs` section of you config.toml?

**Comment by workingJ** [comment]
No .
I did add and completely remove theses settings.

`[language.auto-pairs]
'(' = ')'
'{' = '}'
'[' = ']'
'"' = '"'
'`' = '`'
`
but in both cases still the same behavior. 
does anyone else encounter the same behavior ?

**Comment by anzhi0708** [comment]
I just tried 
`‘(‘ = ‘ ‘`
It worked and added NO extra SPACE

**Comment by the-mikedavis** [comment]
Does this affect the auto-pairs, i.e. the automatic insertion of closing `)`, `"`, and `}`, or just the bracket-matching highlighting? Typing out a rust file with just

```rust
println!("\nSECTION 5: {:->60}\n", " Mutex ");
```

works correctly for me. (I can reproduce the bracket-matching highlight though.)

**Comment by workingJ** [comment]
The auto-pairs are not effected, only the highlighting of pairs.
Through your comment i realized the issue heading is misleading,
so ill change that now for clarification.

**Comment by pascalkuthe** [comment]
this was fixed by  #7242 (I missed that)
