### ISSUE TITLE
[Suggestion] Make `<n> x` select `n` lines below the current line

### ISSUE THREAD

**Issue by wnmrmr** [helix-editor/helix#2112]
## Present behavior
`<n> x` selects the current line and the `n-1` lines below it

## Proposed behavior
`<n> x` selects the current line and the `n` lines below it

`x` selects the current lines and a line below if the current lines are already selected

## Motivation
With relative line numbers, I think the proposed behavior is more intuitive (making ~~it comparable to  `<n> j/k`~~ selection expansion more comprehensive)

Disclaimer: Kakoune has the present behavior and I haven't looked very deep for its reason, but in my mind the proposed behavior makes more sense

**Comment by sudormrfbin** [comment]
When I'm selecting lines I'm thinking of the total number of lines to select, as in "select 2 lines", which pairs nicely with the current behavior. Also making it follow `j`/`k` doesn't feel intuitive to me at all: you can't move up/down to the current line, whereas you _can_ select the current line. If `j` moves one line down, I expect `2j` to move two lines down. If `x` selects one line, I expect `2x` to select two lines.

**Comment by wnmrmr** [comment]
That makes sense! A better argument for it would be the behavior when expanding the current selection (`2x` would expand the selection by 1 line, which actually was my main motivation for opening this)

**Comment by wnmrmr** [comment]
Closing due to lack of interest. If anyone wants to try out the behavior there is the PR.

**Comment by youngmit** [comment]
I still think that there's something to this. On the one hand, e.g. `5 x` selecting 5 lines, including the one under the cursor makes intuitive sense. And by that logic, doing `N x` from no existing selection not including the Nth line _from_ the cursor seems reasonable. Things get a little weird when you _already have a line selected_, though. Say I already have a line selected (`x`), then try to extend my selection (e.g., `2x`), I would expect for the selection to expand by 2 lines. Currently this only extends by one! Really, if there is already a whole line selected, subsequent `[count] x`s should extend the selection by `count`, not `count-1`. This is especially bizarre when you try extending by one or two lines; `x 1 x` and `x 2 x` result in the same selection, which seems super weird to me.

Am i missing something?

**Comment by martinbundgaard** [comment]
@youngmit I agree completely. Also, I think the current behavior really fails to leverage the power of relative line numbers. Coming from a decade of daily vim usage, I routinely delete stuff going up and down by simply looking at the relative line number and deleting by that number in the relevant direction.

I genuinely love almost every aspect of helix - apart from the, I think inferior, selection control. The easy, but involved, solution would be to implement a vim-mode, but I think minor adjustments to the current behavior, possibly as an option, could work wonders to improve the lives of people coming from vim. Introduce a way to select up or down by a count compatible with relative line numbers, and I, for one, would be happy to adjust my other habits.
