### ISSUE TITLE
Improve runtime path search

### ISSUE THREAD

**Issue by archseer** [helix-editor/helix#212]
We should also look at `config_dir/runtime` if present. This would make setup easier for binary release users since they can just link/copy the runtime folder into the config dir.

Additionally, if running via `cargo run` it should detect that and also pick up the directory in git root.

This should likely be done in a `once_cell::sync::Lazy` to only do the resolution once.

**Comment by pickfire** [comment]
If anyone want can take up this task, maybe once I am free then I do this.
