### ISSUE TITLE
Scrolling inside of the tooltip

### ISSUE THREAD

**Issue by EricHenry** [helix-editor/helix#2121]
Hi there!

I couldn't find it inside the documentation. I press `space-k` to be able to see documentation of some type. However I cannot find a way to focus on the tool tip to be able to scroll inside of it. Is that currently possible?

**Comment by kirawi** [comment]
https://docs.helix-editor.com/keymap.html#popup

**Comment by KronosTheLate** [comment]
The keybindings "Ctrl-u" and "Ctrl-d" do nothing for me. Just to make sure we are discussing the same thing, below is a screenshot of the situation. I want to scroll in the rightmost tooltip window.
![image](https://github.com/helix-editor/helix/assets/61620837/c0628494-08b6-4fb6-a7d1-01a78a9693b6)

**Comment by the-mikedavis** [comment]
That's https://github.com/helix-editor/helix/issues/3062

**Comment by KronosTheLate** [comment]
Right it is. Sorry about that.

**Comment by sommerper** [comment]
Is it possible to rebind those? I don't know what mode I'm in when the tooltip shows.
