### ISSUE TITLE
Object selection mode

### ISSUE THREAD

**Issue by archseer** [helix-editor/helix#213]
We want something similar to [kakoune's object selection mode](https://github.com/mawww/kakoune/blob/master/doc/pages/keys.asciidoc#object-selection) so we can do things like `alt-i"` to select inside double quotes. The key for these modes still needs to be determined, I don't particularly like `<alt-i>` and `<alt-a>`.

Some of this will be subsumed by structural matching via tree-sitter, but it would still be good to have a plain implementation that works everywhere.

Note: some of the functions from https://github.com/helix-editor/helix/pull/193 might be useful for implementation

**Comment by sudormrfbin** [comment]
Just a heads up, I've started working on this; will submit a draft PR after I get something minimal up and running.
