### ISSUE TITLE
Copy/paste from system clipboard does not work on WSL2

### ISSUE THREAD

**Issue by patrick-kidger** [helix-editor/helix#2132]
### Summary

As title. I don't see any obvious way to copy or paste from the Windows 10 clipboard when using Helix on Windows Subsystem for Linux (WSL) 2.

### Reproduction Steps

When pasting:
1. Start from the usual Windows 10 desktop.
2. Open a terminal for WSL2.
3. `hx`
4. Copy something on Windows 10.
5. `i` insert mode
6. Attempt to paste it in. (In my case, right click.) Nothing happens.

Conversely, when selecting text inside Helix, I get the message "yanked main selection to system clipboard", but it cannot be pasted from the Windows environment. I assume it only gets as far as the wrapped Ubuntu.

In contrast Vim seems to handle this seamlessly. (Ironically I actually had to use Vim to copy-paste my `config.toml` in #2131.)

### Platform

Windows WSL2, Ubuntu 20.04

### Terminal Emulator

Hmm, whatever the WSL2 default is. Sorry!

### Helix Version

`git describe`: 22.03-89-g450f3489; `hx -V`: helix 22.05-dev (450f3489)

**Comment by the-mikedavis** [comment]
Do the yank-to-system-clipboard and paste-from-system-clipboard commands work? <kbd>Space</kbd><kbd>y</kbd> to yank and <kbd>Space</kbd><kbd>p</kbd> to paste.

**Comment by patrick-kidger** [comment]
Nope; save behaviour as above.

They clearly get saved to some clipboard -- presumably the Ubuntu one -- as this yank/paste works within just Helix itself.

**Comment by NotTheDr01ds** [comment]
This *does* work in Windows 10/WSL2, but requires additional user configuration.

[`clipboard.rs`](https://github.com/helix-editor/helix/blob/master/helix-view/src/clipboard.rs) has several "system clipboard" checks, all of which will fail under WSL/Windows 10 without additional configuration:

1. `WAYLAND_DISPLAY` variable set and `wl-copy`/`wl-paste` available.
2. `DISPLAY` variable set and `xclip` available.
3. `win32yank.exe` available (only in source at the moment; not released)

Windows 10 WSL does not support X11/Wayland out-of-the-box.

This can be configured to work in several different ways:

* Under Windows 11, WSL supports X11 and Wayland with clipboard integration.  Simply install `xclip` OR `wl-clipboard` packages and <kbd>Space</kbd>+<kbd>y</kbd> and <kbd>Space</kbd>+<kbd>p</kbd> will copy to/paste from the Windows clipboard (as well as the X11 or Wayland clipboard).

* Under Windows 10, you will need to install a third-party X server that supports Windows clipboard integration.  [VcXsrv](https://sourceforge.net/projects/vcxsrv/) is one.  To configure:
    1.  Install `xclip` in WSL
    1.  Run XLaunch (the VcXsrv launcher) in Windows.  Any mode can be used such as *"Multiple Windows"* or *"Fullscreen"*.
    1. Keep the *"Clipboard"* option selected.
    3. Select *"Disable Access Control"*
    4. Set your `DISPLAY` correctly.  In WSL2, that's typically `export DISPLAY="$(hostname).local:0"`.
    5. Launch Helix and clipboard integration should work as described above.

* As an alternative under Windows 10, you can also:
    1. Build Helix from source
    2. Build or install [win32yank.exe](https://github.com/equalsraf/win32yank)
    3. Launch Helix and clipboard integration should work as described above.

Believe it or not, I've just tested all three of these approaches.

**Comment by nekodjin** [comment]
Am I correct in thinking that
> 3. `win32yank.exe` available (only in source at the moment; not released, see **Reintroduce win32yank as a clipboard provider on Linux for WSL2 + Windows 10**#1912)
means that, there is already something in motion that will fix this issue? In other words, should we just sit still and wait patiently for it to be fixed?

**Comment by NotTheDr01ds** [comment]
@nekodjin Well, sort of.  All three options have external dependencies, but the one with the fewest dependencies for Windows 10 involves either building from source or waiting patiently, yes.

Side note -- Looking at the source, I *think* it's possible to implement the system clipboard on WSL in a way that "just works" with a standard Windows 10/11 installation with *no* additional dependencies.  But that's going to require an additional code change if so.

**Comment by kirawi** [comment]
Addressed by #1912

**Comment by einarpersson** [comment]
> Addressed by #1912

I have an issues currently where I am able to copy _from_ helix to system (Win10) but not the other way around. I just installed helix on my Ubuntu distro under WSL2 (latest version). Any ideas on how I can troubleshoot? Any command I can run to get info for you to troubleshoot?

Running latest WSL2 (which has support for running GUIs natively etc), do I need to install any extra dependency or is it supposed to work out-of-the-box?

**Comment by kirawi** [comment]
Yeah, you need to install win32yank in both environments.

**Comment by einarpersson** [comment]
> win32yank

Ok, thank you! This should probably be added to the [installation instructions](https://docs.helix-editor.com/install.html) 

### However:
Should I install it in WSL or on the Windows side?
[This issue](https://github.com/equalsraf/win32yank/issues/9) seems to suggest that it currently has to be installed on windows (eg. by using [scoop](https://scoop.sh/#/apps?q=win32yank&s=0&d=1&o=true)) but [this reddit comment](https://www.reddit.com/r/neovim/comments/10nfjjd/comment/j75ds20) seems to suggest that doing so adds a latency.

--

I went ahead and installed `scoop`, installed `win32yank` with it, and restarted.

Now pasting from system clipboard works in Helix, but as described above there is a **latency of 2-3 seconds** for just a single line of text.

**Comment by kirawi** [comment]
It's unclear if there is a better solution. https://github.com/neovim/neovim/wiki/FAQ#how-to-use-the-windows-clipboard-from-wsl suggests that if Helix is also installed in WSL, you can install `win32yank` in it.

**Comment by wraiford** [comment]
In researching this, I also came across the currently still open #7219. Installed `wl-clipboard` via

```
sudo apt install wl-clipboard
```

fixed the issue for me.

**Comment by devesnosy** [comment]
wl-clipboard is nice and all

but also if someone can introduce powershell.exe based clipbaord provider it would be nice

since in WSL2 Windows 11 at least it supports running powershell.exe 

To read stdin into clipbaord
` powershell.exe -c "Read-Host | Set-Clipboard"`


To print clipbaord to stdout
`powershell.exe -c "Get-Clipboard"`

**Comment by devesnosy** [comment]
I have to also add that currently Ubuntu 24.04 has issues with wayland, to fix them

you need to clone this repo and run the commands described in its readme
https://github.com/viruscamp/wslg-links
