### ISSUE TITLE
How to set auto-format command?

### ISSUE THREAD

**Issue by marlonmp** [helix-editor/helix#2139]
## Hi :wave:

I'm new using helix, and I would like know if I can do something like this:

![image](https://user-images.githubusercontent.com/76027579/163689439-32000bb0-2c92-4541-8f23-8ff6813d009a.png)

**gopls** works perfectly, but the `gopls format` command doesn't remove the unused packages like `goimporst` does.

**Comment by kirawi** [comment]
`auto-format` is just a true/false key for using LSP formatting.

**Comment by thomkeh** [comment]
Now with #1972 merged, you can map `:pipe goimport` to some keyboard combination. It won't be format-on-save but still better than typing out the command every time.
