### ISSUE TITLE
Equivalent to `D` and `C`?

### ISSUE THREAD

**Issue by lucypero** [helix-editor/helix#2151]
I often use `C` and `D` in vim. I find it really useful. how should I do this in Helix?

**Comment by n0s4** [comment]
`vgl` `d`/`c`

`vgl` selects to the end of the line and then `c` to change or `d` for delete. If you want to remap these, [The docs](https://docs.helix-editor.com/remapping.html) has a good section on key remapping, however `C` is already used for multiple cursors, so you have to work around that.

I'd also suggest you join the [matrix room](https://matrix.to/#/#helix-editor:matrix.org) which is a good place for help and troubleshooting :) .

**Comment by lucypero** [comment]
Thank you.
