### ISSUE TITLE
Snapcraft support

### ISSUE THREAD

**Issue by ivan770** [helix-editor/helix#2171]
Hi!

It would be awesome if there were official builds of Helix on [Snap Store](https://snapcraft.io).
Providing support for snaps would allow Helix to be installed much more easily on many different platforms,
including those that currently require building from source (`armhf` builds for Raspberry Pi as an example).

[Zola](https://github.com/getzola/zola/blob/master/snapcraft.yaml) is a pretty good example of a Rust app packaged for Snap Store.

**Comment by pascalkuthe** [comment]
Closing in favor of https://github.com/helix-editor/helix/issues/7545
