### ISSUE TITLE
Incorrect merge of languages configuration leads to errors on startup

### ISSUE THREAD

**Issue by poliorcetics** [helix-editor/helix#2188]
### Summary

```
$ hx languages.toml
Bad language config: missing field `scope` for key `language`
Press <ENTER> to continue with default language config
```

Probably came up after #2145 ? ~~I'm trying to test it~~ Reverting fixes the problem

### Reproduction Steps

My `languages.toml`:

```
[[language]]
name = "rust"

[language.config]
assist.importGranularity = "module"
```

then do:
```
$ cd $HOME/.config/helix/
$ hx language.toml
Bad language config: missing field `scope` for key `language`
Press <ENTER> to continue with default language config
```

Commenting out the whole `languages.toml` and repeating the steps does not raise the error.

### Platform

macOS

### Terminal Emulator

kitty 0.25.0

### Helix Version

https://github.com/helix-editor/helix/commit/1525e3c6c846fc3dc4d4a68768105762f5abb376

**Comment by archseer** [comment]
Reverted c8cfd0b1a0da071618a9efc71ac5735d6147a0ca for now

**Comment by poliorcetics** [comment]
I can confirm this fixes the problem

**Comment by the-mikedavis** [comment]
Let's close this out in favor of the original toml merging issue (#100) since the revert.

**Comment by LeoniePhiline** [comment]
For the Googlers:

The error "Bad language config: missing field `scope` for key `language`" also occurs if you add an invalid/incomplete language to your `languages.toml`.

E.g. the following will trigger this message:

```
# Copy-pasted from "json" language, because prettier provides a "json5" parser - but the language config is incomplete.
# `scope` and other required fields are missing from the "json5" language configuration.
[[language]]
name = "json5"
formatter = { command = 'prettier', args = ["--parser", "json5"] }
```
