### ISSUE TITLE
Autocomplete popup should scale when names are too long

### ISSUE THREAD

**Issue by wojciechkepka** [helix-editor/helix#220]
Currently it crops the names making it unusable with longer names.

![image](https://user-images.githubusercontent.com/46892771/121646445-a0b3ae00-ca95-11eb-93bb-de5e9d30da6a.png)

**Comment by archseer** [comment]
This is a side effect of the `Table` implementation we inherited from `tui`, it expects a `max_width` then uses constraints to calculate the width of each row:

https://github.com/helix-editor/helix/blob/69fe46a122f728b4bb6cb218fd410544097b0dcd/helix-tui/src/widgets/table.rs#L265-L329

I think this makes sense for certain views, but we need to have an alternative implementation that bases the column width based on the longest item width in that column (Note: has to take into effect _all_ items, not just the ones on screen) and then uses that as the requested width (not bound by some `max_width`).
