### ISSUE TITLE
how to map `miw*n` in config file ?

### ISSUE THREAD

**Issue by ttys3** [helix-editor/helix#2209]
I want to map `*` to  `miw*n` (search current cursor word, just like vim).

something like `"*" = ["match_brackets", "select_textobject_inner", "w", "search_selection"]` not work.

**Comment by the-mikedavis** [comment]
I'm not sure this is possible with the current keybinding format. It may require #1383

**Comment by the-mikedavis** [comment]
Yeah, let's close this in favor of macro key-bindings #1383
