### ISSUE TITLE
Support reading current config value

### ISSUE THREAD

**Issue by dasBurdock** [helix-editor/helix#2218]
I would expect this to work like vim's `:set value?`. 

Personally, I think this is a horrible syntax for discoverability. Even as a vim user I would recommend having this only alias to something more sensible like `:get-option value`

**Comment by the-mikedavis** [comment]
I agree with `:get-option` (and `:get` for short). The `?` syntax is pretty strange.

**Comment by dasBurdock** [comment]
@the-mikedavis See PR https://github.com/helix-editor/helix/pull/2231
