### ISSUE TITLE
Popup command help box support more than one line.

### ISSUE THREAD

**Issue by pickfire** [helix-editor/helix#222]
https://github.com/helix-editor/helix/pull/194#discussion_r649316469
```rust
                                                                                             
 Jump back to an earlier point in edit history.                                              
                                                                                             
:earlier <cursor>
```
Seemed like it can't be more than one line. It would be helpful to extend it.

**Comment by archseer** [comment]
Closed by https://github.com/helix-editor/helix/commit/2af04325d83cd0141400951252574666cffdf1af and https://github.com/helix-editor/helix/commit/c7b326be047a42f6a58146b0de049d48568e397f
