### ISSUE TITLE
How do I donate to this project?

### ISSUE THREAD

**Issue by dalanmiller** [helix-editor/helix#2220]
I'd love to donate to this project / support it monetarily. 

How may I do so? What kind of support does the project need?

**Comment by archseer** [comment]
I've set up an Open Collective here: https://opencollective.com/helix-editor

Still need to hook it up properly on Github / add Github Sponsors.

Consider a donation as token of appreciation though: we use GitHub's infrastructure for CI so I personally don't have any associated costs apart from the domain fees. **The best way to contribute to Helix development is through code.** If you'd like to make a difference I urge you to donate to [Internet Archive](https://archive.org/donate) instead!

**Comment by dalanmiller** [comment]
Thanks @archseer I see that this is setup now => https://opencollective.com/helix-editor

**Comment by Randalix** [comment]
Why is this money not beeing used? $4,303.20 USD raised, but nothing spend?

**Comment by archseer** [comment]
What would you like me to spend it on? As stated in https://github.com/helix-editor/helix/issues/2220#issuecomment-1120742849 this is more of a donation/backup fund (no different than [rust-analyzer still holding funds](https://opencollective.com/rust-analyzer)). Is there a problem with saving the funds until we can put it to good use?

**Comment by Randalix** [comment]
> What would you like me to spend it on? 
I would expect that the money helps development of helix. What are you saving for?
Pay developers. Could be bounties for issues or earnings, if someone works a week or two full time on helix.
I consider donating money, but why would I if it is like a savings account, without any goal, in times of inflation and does not have any impact on the development?

**Comment by haikyuu** [comment]
> The best way to contribute to Helix development is through code.

I totally agree. I love the way this project is active, and that people who contribute use helix daily. I think it's way more valuable than (any amount of) money. It's because features that make it are usually important enough that a user would spend the time to build them himself.
 
I've yet to contribute code because I've never written Rust before. But I will definitely learn enough Rust just to contribute back a couple of features I have in mind :)

**Comment by archseer** [comment]
> but why would I

exactly, you don't have to! A donation is a tip to developers with no strings attached. I've spent countless hours (over a few years) to build a code editor you get to use. If that's not satisfactory then consider donating to the [Internet Archive](https://archive.org/donate) instead. Statements like these are precisely why I waited this long to set up donations in the first place.

> bounties

You'll probably get more out of it by starting a bounty on the issues you care about yourself.

**Comment by pascalkuthe** [comment]
> A donation is a tip to developers with no strings attached. 

I always assumed that these donations would just be a token of appreciation just like you described.
As a sort of thank you for all your hard work on helix and go to your personal bank account. Considering the time/effort you spend on helix that would be well deserved.

**Comment by Randalix** [comment]
Ups, I did not want to offend you.  I'm sorry if I did. I know you spend a lot of time with this project, and I really like to say thank you! 
My intention was constructive. If you think saving the money is a good idea, then I'm fine with it.

**Comment by Randalix** [comment]
> > A donation is a tip to developers with no strings attached.
> 
> I always assumed that these donations would just be a token of appreciation just like you described. As a sort of thank you for all your hard work on helix and go to your personal bank account. Considering the time/effort you spend on helix that would be well deserved.

Yeah, that's pretty much what I thought. You could have a nice vaccation with it and it's fine. That's what I meant by pay the developers.
It's just the saving thing which is not my cup of tea.

**Comment by janos-r** [comment]
I agree that it would be nice to see some way how this would get to the pockets of individual devs. Something like a top3 contributors of the month or someting like that...
