### ISSUE TITLE
How to set the syntax (or grammar) for current opened R file?

### ISSUE THREAD

**Issue by ipstone** [helix-editor/helix#2229]
Hello, I am trying to use helix with R (https://www.r-project.org/ ), but opening a R script file, there's no syntax highlighting, also the syntax tree based navigation doesn't seem working. 

I am wondering whether we already have R language support, and if not, is there a way to add the R language support.
Ultimately, I would like to have something similar to nvim-R (https://github.com/jalvesaq/Nvim-R )to work with helix.

Thanks!

- ipstone

**Comment by the-mikedavis** [comment]
Which version of helix are you running (`hx -V`)? And what does `hx --health r` say?

**Comment by the-mikedavis** [comment]
Syntax highlighting was added recently https://github.com/helix-editor/helix/pull/1998 (after the 22.03 release)

**Comment by ipstone** [comment]
Thanks @the-mikedavis - verified, my version was 22.03 (which is the current mac os x brew install). After compiling to the latest source, things works fine on m1 mac.
