### ISSUE TITLE
Support interactive grep in global search UI

### ISSUE THREAD

**Issue by dasBurdock** [helix-editor/helix#2233]
I believe using the FilePicker UI for global_search isn't as ergonomic as interactively editing the grep regex. In addition, it prevents extending the picker with substitution syntax. 

I imagine supporting something like `live_grep` by inverting the dialog, creating a FilePicker with two dialogs, or maybe just using a `:picker-filter {regex}` command. 

`live_grep` example: https://github.com/nvim-telescope/telescope.nvim

**Comment by the-mikedavis** [comment]
Duplicate of https://github.com/helix-editor/helix/issues/196
