### ISSUE TITLE
Bracketed paste

### ISSUE THREAD

**Issue by the-mikedavis** [helix-editor/helix#2239]
Pasting with your operating system's paste functionality (Ctrl-v or Cmd-v) is wonky:

- it's slow (https://github.com/helix-editor/helix/issues/1021)
- it inserts extra brackets if you have `auto-pair` on (https://github.com/helix-editor/helix/issues/2015)
- indentation is wrong (https://github.com/helix-editor/helix/issues/2268)

See also

- https://github.com/helix-editor/helix/issues/1484
- https://github.com/helix-editor/helix/issues/1652
- https://github.com/helix-editor/helix/issues/1963
- https://github.com/helix-editor/helix/issues/2236#issuecomment-1107454850

This happens because crossterm does not yet support bracketed paste, so when you paste with OS paste, helix receives each character as if you had typed it yourself. We await a PR upstream in crossterm: https://github.com/crossterm-rs/crossterm/pull/557.

Until bracketed paste is supported, use `Space-p` to paste from the system clipboard.

**Comment by theowenyoung** [comment]
When I use a remote server, then I can only use ctrl-v to paste the local clipboard, how to handle this case?

**Comment by the-mikedavis** [comment]
Yanking to system clipboard across SSH is covered by: https://github.com/helix-editor/helix/issues/247 rather than bracketed paste

**Comment by mbratch** [comment]
It's more than just wonky. It just doesn't work. I can copy and paste using the typical, basic ways to and from any other application... except helix. Whether helix is in insert mode or not, it doesn't work.

I do most of my work over an ssh connection to my Linux box. Copy/paste doesn't work there.

**Comment by the-mikedavis** [comment]
That's covered by #247 and not bracketed paste. Bracketed paste support is implemented, merged, and released in v22.08.1.
