### ISSUE TITLE
Crashing helix in mouse mode leaves terminal in bad state

### ISSUE THREAD

**Issue by Zoybean** [helix-editor/helix#2250]
### Summary

While mouse was enabled, crashed helix.
In the terminal afterward, moving the mouse caused a spam of keycodes to the terminal
![image](https://user-images.githubusercontent.com/24929040/164982078-8d939ba0-8217-4fb1-837c-d6bce6f4a2c5.png)

### Reproduction Steps

I tried this:

1. Set mouse mode in `config.toml`
2. Start helix
3. Crash helix eg using `kill`

I expected this to happen:

- Terminal is left in the same state as before running helix

Instead, this happened:

- Terminal is left in a state where it responds to mouse movements by typing junk

### Platform

Linux (Ubuntu on WSL)

### Terminal Emulator

Windows Terminal Version: 1.12.10982.0

### Helix Version

22.03-121-g6de2e763

**Comment by eduardorittner** [comment]
Shouldn't this issue be closed due to #7236?
