### ISSUE TITLE
Colors don't look right on macOS Terminal.app

### ISSUE THREAD

**Issue by lukepighetti** [helix-editor/helix#2256]
It looks like the colors are not quite right on macOS terminal. I didn't have this issue with other CLI code editors. If I'm not understanding some part of setup, please feel free to close this issue. Thank you.

## Reproduction

```
brew tap helix-editor/helix
brew install helix
hx
```

## Result

<img width="750" alt="Screen Shot 2022-04-24 at 6 08 18 PM" src="https://user-images.githubusercontent.com/666539/164998755-51137ca4-8a7f-4980-8e00-bc29a05334c7.png">

## Expected

<img width="750" alt="Screen Shot 2022-04-24 at 6 06 58 PM" src="https://user-images.githubusercontent.com/666539/164998736-1a9e12f6-3396-4f22-8904-52aafea1db76.png">

**Comment by kirawi** [comment]
https://github.com/helix-editor/helix/wiki/Troubleshooting#rendering-issues-on-macos-terminal

**Comment by lukepighetti** [comment]
Is it within scope to provide a working experience out-of-the-box for terminals that don't have the same color support as terminals like iTerm2 / Kitty?

**Comment by kirawi** [comment]
It's not really possible, but there are a few themes out of the box that don't require true-color. They should start with `base16_` I think.

**Comment by lukepighetti** [comment]
@kirawi I created this PR to add a note about this in the documentation https://github.com/helix-editor/helix/pull/2258

**Comment by tgross35** [comment]
For anyone who runs into this: in addition to the workaround (using iTerm2 or a base16 theme), please submit feedback to Apple asking for True Color support. Feedback can be submitted here: https://www.apple.com/feedback/macos.html and it is probably good to link to the canonical reference on the subject: https://github.com/termstandard/colors

Apple is always a bit slow to move on things like this but some extra poking certainly can't hurt.

**Comment by frankleigh** [comment]
Try Ghostty. Also worth mentioning on Beta Macos 26 it works fine in Terminal.
