### ISSUE TITLE
Make :write recursively create parent folders by default

### ISSUE THREAD

**Issue by lukepighetti** [helix-editor/helix#2259]
## Reproduction

- `hx /tmp/path/to/deep/file.txt`
- write some text
- :write

Error: `Async job failed: can't save file, parent directory does not exist`

## Expected Result

Create all the parent folders automatically. This mirrors the expected behavior from IDE editors like VSCode.

**Comment by the-mikedavis** [comment]
This is the behavior of the new `:write!` command: https://github.com/helix-editor/helix/pull/1839

**Comment by lukepighetti** [comment]
Thanks for the fast triage, out of curiosity, any reason why a new command was created?

**Comment by archseer** [comment]
See https://github.com/helix-editor/helix/pull/1839#issuecomment-1084210835=

> expected behavior from IDE editors

This isn't common by default in editors like nvim, kakoune or emacs though.

**Comment by archseer** [comment]
The `:command` vs `:command!`  are sort of similar to `command` vs `sudo command` in the shell
