### ISSUE TITLE
"Language server not active for current buffer" on python

### ISSUE THREAD

**Issue by quchunguang** [helix-editor/helix#2260]
OS: Mac OS (current)
version installed from brew

1. open a .py file.
2. press `g` `d` for goto the defination of a function.
3. it shows "Language server not active for current buffer".

**Comment by the-mikedavis** [comment]
What does `hx --health python` say? Have you installed pylsp? https://github.com/helix-editor/helix/wiki/How-to-install-the-default-language-servers#pylsp

**Comment by dasBurdock** [comment]
My guess is that you either don't have access to the language server or the executable is broken in some way (IE: you installed the linux package on MacOS) 

`hx --health` doesn't actually do any sanity checks with the language server. So you might find it shows an LSP as green when the executable isn't actually working.

**Comment by the-mikedavis** [comment]
The python Debug Adapter hasn't been tested with Helix yet so it hasn't been configured. DAP is only used for debug mode (`space+d`) so you shouldn't need it unless you're looking to debug programs. In that case you can try integrating https://github.com/microsoft/debugpy but note that DAP support is experimental in Helix and there aren't any docs yet.

**Comment by quchunguang** [comment]
> The python Debug Adapter hasn't been tested with Helix yet so it hasn't been configured. DAP is only used for debug mode (`space+d`) so you shouldn't need it unless you're looking to debug programs. In that case you can try integrating https://github.com/microsoft/debugpy but note that DAP support is experimental in Helix and there aren't any docs yet.

thanks, i'll try that.
