### ISSUE TITLE
Order buffers by last accessed and then alphabetically 

### ISSUE THREAD

**Issue by stjepangolemac** [helix-editor/helix#2281]
When I open the buffer picker I'd like to see them ordered primarily by the last access time and only then alphabetically.

That would allow me to quickly switch between two buffers by doing `space + b, enter`.

**Comment by archseer** [comment]
> That would allow me to quickly switch between two buffers by doing `space + b, enter`.

Try `ga` (alternate buffer)

**Comment by stjepangolemac** [comment]
Ah nice, didn't see that one. Thanks!

It might still make sense to think about the ordering as per the suggestion? IMO it's a much smaller issue now but I believe the probability for a buffer to be accessed next does correlate with the last access time.

**Comment by pascalkuthe** [comment]
This was adressed by  #2980
