### ISSUE TITLE
Setting rulers has no effect for most theme since they use the background color as default

### ISSUE THREAD

**Issue by poliorcetics** [helix-editor/helix#2283]
Commit: 3d3145d5

Here with the gruvbox theme:

<img width="1501" alt="Screenshot 2022-04-26 at 10 47 46" src="https://user-images.githubusercontent.com/7951708/165260910-e381ea08-200a-43bf-8b46-9fc751ec4ada.png">

Here with the autumn theme:

<img width="1058" alt="Screenshot 2022-04-26 at 10 48 20" src="https://user-images.githubusercontent.com/7951708/165261028-97107752-454f-42fc-8a05-dcb98f2aace8.png">

**Comment by the-mikedavis** [comment]
It looks like only `autumn`, `pop-dark`, and `dark_plus` have `ui.virtual.ruler` themed at the moment. Other themes will need the key added.

**Comment by poliorcetics** [comment]
This is not really a bug and has since been fixed for lots of themes, closing
