### ISSUE TITLE
`:clipboard-paste-before` appears to work the same as `:clipboard-paste-after`

### ISSUE THREAD

**Issue by Paveloom** [helix-editor/helix#2284]
### Summary

Contents of the clipboard always get pasted after the current selection(s).

### Reproduction Steps

Try to use these commands.

### Helix log

Reproducing this issue doesn't emit relevant log messages.

### Platform

Linux

### Terminal Emulator

GNOME Terminal 3.42.2 using VTE 0.66.2 +BIDI +GNUTLS +ICU +SYSTEMD

### Helix Version

helix 22.05-dev (b65fb0f6)

**Comment by the-mikedavis** [comment]
Ah this is curious, it only affects the typable commands but not the non-typable ones (even if invoked through the command palette).
