### ISSUE TITLE
Goto references returns duplicates  

### ISSUE THREAD

**Issue by BadBastion** [helix-editor/helix#2286]
### Summary

Goto references (LSP) are currently returning duplicates.

I need to do some digging if this bug is originating from the LSP, but I think we should be able to remove duplicates from the the `FilePickers` options when created. 
<img width="960" alt="Screen Shot 2022-04-26 at 8 24 55 AM" src="https://user-images.githubusercontent.com/9969763/165336025-dd124dd0-cc12-47e3-a86c-ff81ce075c23.png">
 

### Reproduction Steps

I found this when using goto ref on the `Modifier` bitmask in helix's repo 

### Helix log

Nothing relevant logged for LSP 

### Platform

MacOs

### Terminal Emulator

N/A

### Helix Version

22.05-dev (6de2e763)

**Comment by pascalkuthe** [comment]
this was fixed upstream in https://github.com/rust-lang/rust-analyzer/pull/13571
