### ISSUE TITLE
Theme is broken in  gtk4 terminal

### ISSUE THREAD

**Issue by Mofiqul** [helix-editor/helix#2292]
Theme is not working on GTK4 terminal 
The terminal I am using is https://gitlab.gnome.org/raggesilver/terminal/-/tree/main
![Screenshot from 2022-04-27 00-57-56](https://user-images.githubusercontent.com/23612580/165378521-08fcf36e-fc92-499e-afad-8b045afb7853.png)

**Comment by the-mikedavis** [comment]
You may have to force true color support in your `~/.config/helix/config.toml`:

```toml
[editor]
true-color = true
```

https://docs.helix-editor.com/configuration.html#editor-section

**Comment by the-mikedavis** [comment]
See also https://github.com/helix-editor/helix/issues/1271

**Comment by Mofiqul** [comment]
With  `true-color = true` It works fine.
