### ISSUE TITLE
homebrew tap private?

### ISSUE THREAD

**Issue by jedahan** [helix-editor/helix#23]
`brew tap helix-editor/helix` expects the homebrew tap to resolve to `https://github.com/helix-editor/homebrew-helix`, but I cannot see that repository.

**Comment by archseer** [comment]
There is no tap defined yet :/ I could use some help setting one up https://github.com/helix-editor/helix/issues/9

**Comment by chadlavi** [comment]
You should really remove this from your installation docs if it's not actually available yet. I've been trying to troubleshoot why this isn't working for me for a little bit now. 

I know there's a little "TODO" line in there, but it's completely unclear that the TODO means "this is not actually available," it looks like it's just a placeholder for some copy in the docs page.

**Comment by archseer** [comment]
Sorry about that, you should be able to just extract and run the latest [binary release](https://github.com/helix-editor/helix/releases) for now. I'll look into adding a tap today.
