### ISSUE TITLE
change-directory tab completion matches longer words

### ISSUE THREAD

**Issue by lukepighetti** [helix-editor/helix#2300]
When trying to change directory,

Given a folder that contains `video_player` and `video_player_android`

Typing `vide` `Tab` autocompletes to `video_player_android`

Expected autocompleting to `video_player`

https://user-images.githubusercontent.com/666539/165515465-09df4d50-7cdd-4173-b028-35bcc29e91ee.mov

**Comment by pascalkuthe** [comment]
Likely fixed by switching to nucleo (which sorts by length if the core is equal)
