### ISSUE TITLE
Add v (vlang) language support

### ISSUE THREAD

**Issue by titinho** [helix-editor/helix#2309]
Here you can find the LSP and the tree-sitter support: https://github.com/vlang/vls

**Comment by mkatychev** [comment]
Heads up, I'm getting this when starting vls with helix:
```
helix_lsp [ERROR] failed to initialize language server: failed to parse: invalid type: 
    boolean `false`, expected struct DocumentLinkOptions
```
There's a `DocumentLinkOptions` in `vls` but it seems to be returning a boolean instead
https://github.com/vlang/vls/blob/60eecea34687e7dfb641c35f4461413ce94c4d98/lsp/document_link.v#L3-L5

I wish helix would allow reading from a TCP/Unix socket for the json RPC, that would make it easier to debug.
