### ISSUE TITLE
Search for an OR of all word selections when using *

### ISSUE THREAD

**Issue by MilanVasko** [helix-editor/helix#2312]
Hi, this is probably the feature I miss most from Kakoune, I think it's super useful.
I'm not sure if I've expressed it well enough in the title, so let me try to elaborate with an example.

Let's say we have the following file, with the cursor placed at the beginning (the letter `a`):
```
abc
def
```
If I press `Ce*` in Helix, the search register will be set to `def`.

If I do the same thing in Kakoune, the search register will contain `\babc\b|\bdef\b`.

I would like to have the same behavior in Helix.

**Comment by colaxdev** [comment]
You can do this without *

**Comment by MilanVasko** [comment]
@colaxdev Can you please elaborate?

The only way that I know of is to write such a search query myself - which is not ideal, since I have to type everything manually.

This issue is about the convenience of being able to search for everything that I currently have selected with the push of a button.
