### ISSUE TITLE
Ability to see all available keybindings in any context

### ISSUE THREAD

**Issue by lukepighetti** [helix-editor/helix#2316]
It would be nice if there was a keystroke that would always show every possible available keybinding in any possible context

**Comment by sudormrfbin** [comment]
There's the command palette (`space + ?`)

**Comment by lukepighetti** [comment]
I'm looking for a guide to currently available keybindings, the purpose being to increase discoverability of key paths

**Comment by colaxdev** [comment]
Search in the source code or in the website

**Comment by lukepighetti** [comment]
I'm going to close this in favor of improving `hx --tutor` https://github.com/helix-editor/helix/issues/506
