### ISSUE TITLE
How to add my own auto-completion source?

### ISSUE THREAD

**Issue by milanglacier** [helix-editor/helix#2318]
#### Describe your feature request

It seems that currently only `lsp` provides auto-completion source.
Buf similar to `nvim-cmp`, I would love to see we can provide more completion source, especially words in buffer. This is very useful when writing markdown file.

I would love to try to make contributions, but I am not sure where's the entry point of hacking auto completion module.

**Comment by the-mikedavis** [comment]
Custom completion sources have an issue here https://github.com/helix-editor/helix/issues/1015 which is mostly scoped towards keywords. More advanced completion providers would probably be scoped as plugins https://github.com/helix-editor/helix/issues/122
