### ISSUE TITLE
Improving pasting

### ISSUE THREAD

**Issue by elferherrera** [helix-editor/helix#2319]
I havent checked helix code, but Im guessing that when doing a paste every single event is processed making pasting very slow. It also would explain why you get extra brackets after pasting.

We used to have the same issue in Reedline. To correct that, the engine has a poll wait time that checks if several events happened at the same time. This happens in this [line](https://github.com/nushell/reedline/blob/main/src/engine.rs#L414). When there are more events than it is humanly possible to generate (a paste) then ignore all checks and just write the text to the buffer. 

Im wondering if something similar could be done for helix?

**Comment by archseer** [comment]
https://github.com/helix-editor/helix/issues/2239
