### ISSUE TITLE
Whitespace character for phantom line at end of file is that of "space", but doesn't really exist

### ISSUE THREAD

**Issue by EpocSquadron** [helix-editor/helix#2328]
### Summary

If you have a final newline at the end of the file, as is often standard to do, you will find that you can move your cursor past the newline character on to the next line. This is a bit of an illusion for convenience, as there is no actual character at that position, but makes it possible to use equivalently `a` or `i` to begin entering new characters on the line-after-end.

With visible whitespace on, moving the cursor to that phantom not-character shows the whitespace symbol for a space, even though it is not in fact a space. We should probably clean this up with a special-case whitespace character for "null" or some-such. Perhaps `␀`, the unicode character for null. We could also go with `~` as this is the character in the gutter to help distinguish this phantom line already.

### Reproduction Steps

1. Configure helix to show visible whitespace
2. Open `hx` without any arguments
3. Observe that the scratch buffer consists of exactly one newline character, located on the first line
4. Move the cursor to the next line with `j`
5. Observe that the whitespace character for this non-existent character is that for space

![image](https://user-images.githubusercontent.com/414963/165994893-b50ea7d4-99ca-4dc1-a498-86047806a454.png)

### Helix log

N/A

### Platform

Linux

### Terminal Emulator

wezterm 20220427-144728-efcc4b48

### Helix Version

helix 22.05-dev (477b88e9)

**Comment by the-mikedavis** [comment]
Oh whoops I thought I fixed this (https://github.com/helix-editor/helix/commit/45fd800925c7a9e2c9fa56c7259a6548689e67c8) but I see it happening on latest too. I'll take a look

**Comment by EpocSquadron** [comment]
Looks like the commit isn't on any branch according to GitHub, did it get rebased out by accident?

**Comment by the-mikedavis** [comment]
Oh I see what went wrong 😅. PR in 5!
