### ISSUE TITLE
Question: Toggle LSP Code Completion

### ISSUE THREAD

**Issue by arjpar** [helix-editor/helix#2333]
Hi, I'm wondering how to toggle LSP code completion? For example on VSCode I can use `Ctrl + Space` to toggle intellisense/code completion, what is the equivalent keybinding in Helix? I tried looking in the documentation, but couldn't find any key mapping. Apologies in advance if it does exist in the documentation and I overlooked it!

**Comment by thomkeh** [comment]
Should be ctrl-x according to the docs: https://docs.helix-editor.com/keymap.html#insert-mode

**Comment by arjpar** [comment]
@thomkeh that worked, thank you! I'm going to close the issue now.
