### ISSUE TITLE
The command 'hx' doesn't work on Arch Linux package

### ISSUE THREAD

**Issue by Callum-Irving** [helix-editor/helix#2335]
### Summary

I installed Helix for the first time today and the first thing I noticed is that it wouldn't launch with the command `hx`.

I looked at the [PKGBUILD](https://github.com/archlinux/svntogit-community/blob/packages/helix/trunk/PKGBUILD) and it appears that the cause of this is that the binary `hx` is being put in lib instead of bin.

### Reproduction Steps

Install Helix using `pacman -S helix` then run the command `hx`.

Expected behaviour: Helix launches.

Actual behaviour: `hx: not found`.

### Helix log

Not applicable.

### Platform

Arch Linux

### Terminal Emulator

Alacritty

### Helix Version

helix 22.03

**Comment by Zaplae** [comment]
try `helix`?

**Comment by archseer** [comment]
The install script from the package explains this and suggests you add an alias: https://github.com/archlinux/svntogit-community/blob/packages/helix/trunk/helix.install

Sadly there's already [a package in the community repo](https://archlinux.org/packages/community/x86_64/hex/) that predates us and uses the `hx` name so the Arch maintainer decided to rename the binary.

We don't have any control over how distributions package helix but you can start a discussion [downstream](https://bugs.archlinux.org/)

**Comment by Callum-Irving** [comment]
Thanks @archseer. I guess that makes sense.
