### ISSUE TITLE
Feature request: The Ability to be able to hide certain folders.

### ISSUE THREAD

**Issue by BenjaminLee-boop** [helix-editor/helix#2338]
#### Feature Request: The Ability to be able to hide certain folders from the helix file picker.

Hello Everyone,
I'm a javascript developer and would love the option to be able to hide the "Node modules" folder from the file picker.  I feel like this feature could benefit the community by being able to have certain hidden folders that don't need to be modified during dev.

**Comment by archseer** [comment]
You can either add a `.gitignore` (recommended if part of a git project anyway)  or a `.ignore` file.

https://docs.rs/ignore/latest/ignore/struct.WalkBuilder.html#ignore-rules

**Comment by BenjaminLee-boop** [comment]
> You can either add a `.gitignore` (recommended if part of a git project anyway) or a `.ignore` file.
> 
> https://docs.rs/ignore/latest/ignore/struct.WalkBuilder.html#ignore-rules

Awsome this works,

**Comment by bfg-coding** [comment]
This seems to not to work for me on Version 23.03

OS:  Pop-OS 
Terminal: Alacritty


![Screenshot from 2023-04-12 09-38-24](https://user-images.githubusercontent.com/11151592/231509503-60a72ec7-9f08-424f-8be0-aefa35218ba7.png)

**Comment by IAmSegfault** [comment]
I also tried doing this on Pop-OS using version 23.03 with gnome-terminal just now, and can confirm that adding a folder to .gitignore does nothing.

![image](https://user-images.githubusercontent.com/3222988/231599581-e4521baa-d1f4-421a-935c-a6cb07fd471f.png)

**Comment by the-mikedavis** [comment]
This is https://github.com/helix-editor/helix/issues/6698

**Comment by galearez** [comment]
@IAmSegfault @bfg-coding based on my own experience, this usually happens when I haven't initialized a git repo, so I solve it by running `git init` on the root of the project. Could this be the case?

**Comment by IAmSegfault** [comment]
I decided to go back to visual studio code for the time being, but I can give it a quick check later today as I work on a project 🙂

**Comment by IAmSegfault** [comment]
Ok that looks like it did fix the issue. My rust projects had their own `.git` folders, but the root workspace folder did not. Running `git init` on the workspace folder resolved the problem.
