### ISSUE TITLE
Possibility to align selection by symbol

### ISSUE THREAD

**Issue by colaxdev** [helix-editor/helix#2341]
# Idea

Align selection by symbol:

```zig
const Helix = enum {
    Super, // Cool
    Very, // Fast
}
```

**TO:**

```zig
const Helix = enum {
    Super, // Cool
    Very,  // Fast
}
```

**Comment by archseer** [comment]
You can do this via `&`: https://asciinema.org/a/mxAeELHoe0CXPZQ3HtIOGcPwV

I selected the line range, pressed `s`, then input `//` `Enter` to select the two comments. Finally `&` aligns the cursors on both lines.

**Comment by colaxdev** [comment]
Oh thanks ! :+1:
