### ISSUE TITLE
Link to Wiki on documentation page

### ISSUE THREAD

**Issue by aral** [helix-editor/helix#2346]
Currently, the Wiki is the only place that has information on how to install various language servers (see #350).

The documentation page doesn’t have a link to this information. (See )

## Suggested implementation

Replace:

```
See the [usage](https://docs.helix-editor.com/usage.html) section for a quick overview of the editor, [keymap](https://docs.helix-editor.com/keymap.html) section for all available keybindings and the [configuration](https://docs.helix-editor.com/configuration.html) section for defining custom keybindings, setting themes, etc.
```

With:

```
See [usage](https://docs.helix-editor.com/usage.html) for a quick overview of the editor, [keymap](https://docs.helix-editor.com/keymap.html) for all available keybindings and [configuration](https://docs.helix-editor.com/configuration.html) for defining custom keybindings, setting themes, etc. For everything else (e.g., how to install supported language servers), see the [Helix Wiki](https://github.com/helix-editor/helix/wiki).
```

**Comment by the-mikedavis** [comment]
Recently the README got a link to it (specifically the language servers part): https://github.com/helix-editor/helix/blob/2c60798b00cc9b8efc9fdbec304a7ea04d11de4c/README.md?plain=1#L65-L67

That info would probably fit here as well: https://github.com/helix-editor/helix/blob/2c60798b00cc9b8efc9fdbec304a7ea04d11de4c/book/src/install.md

and in the landing page as you say: https://github.com/helix-editor/helix/blob/2c60798b00cc9b8efc9fdbec304a7ea04d11de4c/book/src/title-page.md

Would you like to make a PR?
