### ISSUE TITLE
C-i not working

### ISSUE THREAD

**Issue by MAST1999** [helix-editor/helix#2350]
### Summary

I was going through the tutorial and when I got to the jumplist chapter and tried using `C-i` it did not work even though `C-o` worked fine.

I built it from the source yesterday.

### Reproduction Steps

I tried To add the keymap manually to the config but it still didn't work.

I expected after using the `C-i` to jump forward in the jumplist.

Instead, the cursor didn't move, and I also tried having multiple jumps saved and it didn't make a difference.

### Helix log

<details><summary>~/.cache/helix/helix.log</summary>

```
2022-05-01T00:07:35.792 helix_view::theme [WARN] Theme: malformed hexcode: form
2022-05-01T00:07:35.793 helix_view::theme [WARN] Theme: malformed hexcode: fg
```

</details>

### Platform

Windows

### Terminal Emulator

Windows Terminal Version: 1.12.10983.0

### Helix Version

helix 22.05-dev (21487d13)

**Comment by the-mikedavis** [comment]
Some other program might be intercepting the `C-i` input. Could you try with another terminal emulator like Alacritty, Kitty, or WezTerm? Maybe the windows terminal is intercepting `C-i`?

**Comment by MAST1999** [comment]
@the-mikedavis Ok, will get back to you.

**Comment by MAST1999** [comment]
Hey @the-mikedavis I check in Alacritty and it was working there.

So I ended up looking through the shortcuts in windows terminal but couldn't find any shortcuts that were using `C-i`. Do you have any Idea what might be causing this?

**Comment by colaxdev** [comment]
You can maybe just remove the shortcut from your terminal config. If it doesn't work, you should use another terminal emulator.

**Comment by the-mikedavis** [comment]
I'm not sure what windows terminal is using `C-i` for. It may be configurable in some settings panel though?

**Comment by Dispersia** [comment]
i use windows terminal for basically all of my dev and I haven't experienced this, what shell are you actually using in windows terminal though? I tried powershell, cmd dev tools (from VS) and regular command prompt, and none of them experienced that behavior. Do you have a pre-load script that runs by chance?

**Comment by MAST1999** [comment]
I just have `oh-my-posh` as a theme engine and I don't have pre-load scripts @Dispersia
I tried removing `oh-my-posh` and I still had the problem
I'm using PowerShell 7.2.3
Is there a way to find where the `C-i` is being interrupted... it's really annoying...

**Comment by MAST1999** [comment]
It seems there is a problem with my setup so I'm closing this issue from now.

if I find out why this is happening I will post an update here.

Thanks to everyone for commenting.
