### ISSUE TITLE
File expansion in commands

### ISSUE THREAD

**Issue by domaspoliakas** [helix-editor/helix#2351]
Hello!

It would be nice to be able to expand the current file path in commands, something like what % does in vim.

**Comment by colaxdev** [comment]
You can add it yourself easily if you want but I think it can be useful only if a vimscript like config language is added, for example for WASM based plugins

**Comment by poliorcetics** [comment]
This has been done now: use `<c-r>` when typing a command, e.g: `:cd <c-r>%<c-w>` will change directory to the parent of the current file.

**Comment by the-mikedavis** [comment]
As @poliorcetics says you can use `C-r` and the `%` special register when using a prompt interactively. I will close this in favor of https://github.com/helix-editor/helix/issues/3134 which would allow something similar when binding commands in config
