### ISSUE TITLE
Separate args and description of words in the hint box

### ISSUE THREAD

**Issue by colaxdev** [helix-editor/helix#2358]
# Idea

Separate args and description by a line for example

**Comment by the-mikedavis** [comment]
What do you mean by hint box?

Like the popup when you hit space in normal mode?:

![popup](https://user-images.githubusercontent.com/21230295/166150117-f41946fb-239c-4a2e-a0ea-d85e676fc17a.png)

**Comment by colaxdev** [comment]
@the-mikedavis No, the hint when you hit <space+k> on a item

**Comment by the-mikedavis** [comment]
This depends on what the language server returns - Helix is just rendering the markdown. For example rust-analyzer adds a `---` between the function head and the docs.

![2358](https://user-images.githubusercontent.com/21230295/166164165-95cbbc02-26bc-41d7-a586-b3ce28d75236.png)

And the lsp message for this taken from the log:

```json
{
  "contents": {
    "kind": "markdown",
    "value": "\n```rust\ncore::fmt::Formatter\n```\n\n```rust\npub fn write_fmt(&mut self, fmt: Arguments<'_>) -> Result\n```\n\n---\n\nWrites some formatted information into this instance.\n\n# Examples\n\n```rust\nuse std::fmt;\n\nstruct Foo(i32);\n\nimpl fmt::Display for Foo {\n    fn fmt(&self, formatter: &mut fmt::Formatter) -> fmt::Result {\n        formatter.write_fmt(format_args!(\"Foo {}\", self.0))\n    }\n}\n\nassert_eq!(&format!(\"{}\", Foo(-1)), \"Foo -1\");\nassert_eq!(&format!(\"{:0>8}\", Foo(2)), \"Foo 2\");\n```"
  },
  "range": {
    "end": { "character": 19, "line": 34 },
    "start": { "character": 10, "line": 34 }
  }
}
```

**Comment by kirawi** [comment]
Closing since this isn't fixable.
