### ISSUE TITLE
Update the documentation

### ISSUE THREAD

**Issue by colaxdev** [helix-editor/helix#2361]
# Idea

Just **UPDATE** the website

**Comment by colaxdev** [comment]
And add more documentation *

**Comment by the-mikedavis** [comment]
Can you be more specific? What's out of date? What other documentation would you like to see?

You can propose changes to the documentation by editing the book here: https://github.com/helix-editor/helix/tree/master/book/src and sending pull requests. If you're looking for the most up to date docs you can see the master version of the book by adding `/master` the beginning of the URL like so: https://docs.helix-editor.com/master/configuration.html

**Comment by archseer** [comment]
Feel free to contribute more docs
