### ISSUE TITLE
Run selected command in a file

### ISSUE THREAD

**Issue by lebakasable** [helix-editor/helix#2363]
# Idea

The file: 
```zig
const helix = enum {
    Super, // echo "helix is the best"
    Cool,
}
```

Select command then clic a button then execute command. Simple, fast and efficient!

**Comment by the-mikedavis** [comment]
IMO, the way this should work:

* select some text in the buffer that contains a command
* yank it to a register
* paste from a register (https://github.com/helix-editor/helix/issues/1512) into the command entry, whether it's `|`, `Alt-|`, or https://github.com/helix-editor/helix/pull/1682 and then run it
