### ISSUE TITLE
Clear keymap (not no_op)

### ISSUE THREAD

**Issue by Abdillah** [helix-editor/helix#2364]
#### Describe your feature request
Since `select mode` is echoing `normal mode`, several key that is set in `select mode` is obstructing the keys to pass into normal mode. We can try to remap the key, but the original key is not cleared. I tried several way to put `0` and `""` (empty string) but it is invalid.

Please provide a mechanism to clear a keymap, especially the one already added by default.

**Comment by the-mikedavis** [comment]
The select keymap uses the normal mode keymap as a base but it is actually a distinct keymap (see [here](https://github.com/helix-editor/helix/blob/166818359030cd1649327160c9020d943a8de244/helix-term/src/keymap/default.rs#L288-L315) in the source).

If I wanted to unset the keymap for `n` in select mode for example, I would say:

```toml
# ~/.config/helix/config.toml
[keys.select]
n = "no_op"
```

**Comment by Abdillah** [comment]
Ah, so echoing doesn't mean that it falls back to normal, but the select mode default is corresponded to normal mode.
Thanks.
