### ISSUE TITLE
(Question) What would be the right way to use linters?

### ISSUE THREAD

**Issue by ValJed** [helix-editor/helix#2385]
First thanks for your work, Helix is a really good tool. 

I think that what I need is not possible as long as helix has no plugin support but I wanted to ask because I'm really not familiar with how it should/could work.

I mainly work with JS, and I was wondering if configuring a linter server (in my case eslint) in parallel of the language-server is possible. I looked the whole default `languages.toml` configuration and I don't think something similar is doable yet.

I suppose it's about the grammar section and it would work with the tree sitter somehow?

Thanks in advance!

**Comment by the-mikedavis** [comment]
If the linting server talks in LSP, this could be addressed by #1396. Without that, it's likely that a plugin is the correct way to integrate it.

Tree-sitter parses the syntax tree and Helix can query into the syntax tree, so it's suitable for features like syntax highlighting or determining textobjects (for example, go to the next function) but not integrating a linter.

**Comment by ValJed** [comment]
Thanks this is exactly what I'm looking for.
Closing this one.
