### ISSUE TITLE
Javascript code completion

### ISSUE THREAD

**Issue by mke21** [helix-editor/helix#2386]
Hi,

I installed helix on manjaro using the latest binary on the release page (22.3). I copied the runtime folder into ~/.config/helix. Code completion for python works fine. For javascript, however this is another matter and it does not work. I did install the typescript-language-server. Syntax highlighting seems to be working. Is there something I should be doing to get this to run? See below the `hx --health` output on my system.

```
$ hx --health javascript
Configured language server: typescript-language-server
Binary for language server: /usr/bin/typescript-language-server
Configured debug adapter:
Binary for debug adapter: Not found in $PATH
Highlight queries: Found
Textobject queries: Not found
Indent queries: Found
```

**Comment by the-mikedavis** [comment]
Can you try running helix in verbose mode `hx -vv` and checking the log file (https://github.com/helix-editor/helix/wiki/FAQ#access-the-log-file)? That will show the communication between helix and the language server.

**Comment by mke21** [comment]
Thanks for that, that made things quite a bit clearer. It appeared to be the language server itself that was at fault and could not initialize, so no fault of helix. Thank you for the quick reply and for the editor that already looks quite impressive at this early stage.

**Comment by MossabDiae** [comment]
Thank you @the-mikedavis, I was able to find this error code in logs:
`helix_lsp::transport [ERROR] <- InternalError: Request initialize failed with message: Could not find a valid TypeScript installation. Please ensure that the "typescript" dependency is installed in the workspace or that a valid `tsserver.path` is specified. Exiting.`

**Solution** was simply installing typescript using npm  `npm install typescript -g`
