### ISSUE TITLE
Handling indentation style

### ISSUE THREAD

**Issue by cessen** [helix-editor/helix#239]
Currently Helix appears to depend purely on predefined indentation styles per language.  For example, Rust files are always assumed to have 4-space indentation.  Although many languages have an accepted indentation style that's usually used, there are also many that do not.  And even for the ones that do, there are always projects that deviate from that out of preference.

Consider the following situation:

I find a Python project that I want to contribute to.  I clone the repo, and start editing the files.  However, this particular project does not follow PEP-8 style guidelines, and instead of indenting with 4 spaces it indents everything with 2 spaces.  I now have to fight *against* Helix at every turn to stay consistent with the project's coding style.

Because of situations like that, IMO it's really critical for indentation style (tabs vs space, and if spaces how many) to be a per-buffer setting, and ideally be auto-detected from the contents of the file on load when possible.  (Per-language settings are still a reasonable fallback, though.)

Thoughts?

**Comment by kirawi** [comment]
In VSCode, you have the choice between global and workspace-specific settings, allowing you to configure for a particular project without messing up everything else. Additionally, it also offers the choice between auto-detecting or manually choosing your indentation style. Personally, I would like this but I'm up for other options.

**Comment by robinvd** [comment]
Im a lot of the projects that a work on there is a .editorconfig. This could also be (one of the) options

**Comment by archseer** [comment]
I think this makes sense, it was another one of those things I didn't deal with since I didn't have to (Rust always uses 4 spaces)

The easiest way to proceed would be to turn these methods into fields on Document:

https://github.com/helix-editor/helix/blob/9baf1ecc90117710e785467f59a99ee119f50c73/helix-view/src/document.rs#L502-L518

We can then do detection in Document::load as well as add some :commands for setting these. 

EditorConfig: I'm a fan and would like to support this but we would need to write a parser since it's using the INI format and might not be fully valid toml.

**Comment by cessen** [comment]
@archseer:
Awesome.  I realize I keep half-assedly volunteering for stuff, but I think this would be a good first issue for me to tackle.  The scope is relatively small, and it looks like it will touch on a good variety of Helix's components to help me get familiar with the code base.

Mind if I take this on?

> Im a lot of the projects that a work on there is a .editorconfig.

Yeah, for sure.  I think it makes sense to have a series of fall-backs.  The priority of each approach in that fallback list can be another discussion, but I definitely think supporting things like .editorconfig as well makes sense.

> In VSCode, you have the choice between global and workspace-specific settings, allowing you to configure for a particular project without messing up everything else.

I'm relatively indifferent to whether Helix has a concept of projects/workspaces/whatever in the first place, but if it does get (or already have?) something like that, then definitely that's another good level to support indentation settings at.

**Comment by kirawi** [comment]
> @archseer:
> Awesome. I realize I keep half-assedly volunteering for stuff, but I think this would be a good first issue for me to tackle. The scope is relatively small, and it looks like it will touch on a good variety of Helix's components to help me get familiar with the code base.
> 
> Mind if I take this on?
> 
> > Im a lot of the projects that a work on there is a .editorconfig.
> 
> Yeah, for sure. I think it makes sense to have a series of fall-backs. The priority of each approach in that fallback list can be another discussion, but I definitely think supporting things like .editorconfig as well makes sense.
> 
> > In VSCode, you have the choice between global and workspace-specific settings, allowing you to configure for a particular project without messing up everything else.
> 
> I'm relatively indifferent to whether Helix has a concept of projects/workspaces/whatever in the first place, but if it does get (or already have?) something like that, then definitely that's another good level to support indentation settings at.

I think the idea of an `editorconfig` is the same as VSCode's workspace, as that's basically what it's doing.

**Comment by kirawi** [comment]
We could use https://crates.io/crates/config

**Comment by archseer** [comment]
> I think the idea of an `editorconfig` is the same as VSCode's workspace, as that's basically what it's doing.

Well VSCode spaces are a bit more than that, I like `editorconfig` since it's checked into source control and it's editor agnostic.

**Comment by cessen** [comment]
I've started a draft PR for this in #245.  My intention with this PR is to only address the following:

* Make indentation style a per-document setting.
* Display the current indentation style of the document in the info line.
* Add a command to manually set a document's indentation style.
* Auto-detect a file's indentation style from its actual contents on load, falling back to a language-based default when confidence is low.

For now I'm not addressing .editorconfig etc.  That can be a separate discussion and PR.

**Comment by Siilwyn** [comment]
Would it be an idea to create a separate issue for EditorConfig support? Out of the box support would be superb! Can't imagine creating projects without it.

**Comment by cessen** [comment]
@Siilwyn I think a separate issue for that would be great, yeah.  I'm definitely in support of that, but I think this issue is better focused on the auto-detect part of it.  So feel free to open a new issue.

**Comment by cessen** [comment]
Implemented in #245 and #269.  I'll open a separate issue for .editorconfig, since it doesn't look like anyone else has yet.

**Comment by Siilwyn** [comment]
Ah sorry forgot about it for a bit. Thanks!

**Comment by cessen** [comment]
No worries! :-)
