### ISSUE TITLE
Auto import with Go not working

### ISSUE THREAD

**Issue by crdpa** [helix-editor/helix#2394]
### Summary

With kakoune i have auto import working on save with the following config:

    hook global BufWritePre .*[.]go %{
        try %{ lsp-code-action-sync '^Organize Imports$' }
        lsp-formatting-sync
    }

Is there anything similar in Helix?

### Platform

Linux

### Terminal Emulator

foot

### Helix Version

helix 22.03

**Comment by archseer** [comment]
Duplicate of #1565
