### ISSUE TITLE
Add support to ignore .svn folder

### ISSUE THREAD

**Issue by Bashe** [helix-editor/helix#2406]
Can you extend the ignore support to include ".svn" as well in addition to ".git" Actually when I think, maybe also ".hg"?

Thanks in advance!

**Comment by archseer** [comment]
You can add those in your global `.ignore` file. https://docs.rs/ignore/0.1.6/ignore/struct.WalkBuilder.html#ignore-rules

**Comment by kirawi** [comment]
If there's an effort made into supporting it, maybe it would be better to add it to `ignore`.

**Comment by simrankedia** [comment]
@pascalkuthe I have raised a quick fix for the bug, kindly let me know if this is the required change. Thanks

**Comment by simrankedia** [comment]
@pascalkuthe  Raised another PR - let me know if you have any feedback, thanks.
