### ISSUE TITLE
Documentation is misleading about runtime path on Windows

### ISSUE THREAD

**Issue by drocha87** [helix-editor/helix#2407]
### Summary

In the documentation says that after compiling and installing helix, we must copy the `runtime` to `%AppData%/helix/runtime`.

But running the command `:config-open` opens the configuration in `%AppData%/Roaming/helix/config.toml`. 

So after the installation the right path to put the `runtime` is in `%AppData%/Roaming/helix/runtime`

```txt
OS Name:                   Microsoft Windows 11 Pro
OS Version:                10.0.22000 N/A Build 22000
OS Manufacturer:           Microsoft Corporation
```
As you guys are using the package [etcetera](https://github.com/arzg/etcetera) to guess the configuration directory, just to validate my point about the strategy they use.

```rust
impl super::BaseStrategy for Windows {
    type CreationError = crate::HomeDirError;

    fn new() -> Result<Self, Self::CreationError> {
        Ok(Self {
            appdata: crate::home_dir()?.join("AppData/"),
        })
    }

    fn config_dir(&self) -> PathBuf {
        self.appdata.join("Roaming/")
    }

    fn data_dir(&self) -> PathBuf {
        self.appdata.join("Roaming/")
    }

    fn cache_dir(&self) -> PathBuf {
        self.appdata.join("Local/")
    }
}
```

### Platform

Windows 11

### Terminal Emulator

windows terminal

### Helix Version

helix 22.05-dev (fc617968)

**Comment by kirawi** [comment]
`%APPDATA%` should point to `AppData/Roaming`

**Comment by drocha87** [comment]
> `%AppData%` should point to `AppData/Roaming`

OMG you right, I didn't pay attention that `%AppData%` is an env variable.  I'm using powershell I forgot that in cmd an env variable is surrounded `%`.
