### ISSUE TITLE
Undoing change in insert mode does nothing when first opening the file

### ISSUE THREAD

**Issue by joezak11** [helix-editor/helix#2409]
### Summary

using the following configuration
```toml
[keys.insert]
C-z = "undo"
```
editing a file without going to normal mode prints `Already at oldest change` if I go to normal mode and go back to insert mode I can undo

### Reproduction Steps

 

I tried this:

1. `hx`
2. enter insert mode
3. type anything
4. press `Ctrl-z`

I expected this to happen:
to undo the changes
Instead, this happened:
I get `Already at oldest change`

### Platform

Linux

### Terminal Emulator

alacritty 0.8.0-dev (3ed0430)

### Helix Version

helix 22.05-dev (fc617968)

**Comment by joezak11** [comment]
I see. Are there any plans for changing that behavior? neovim works as expected, I'm not sure how they implement it, though. could be time based or event based with a debounse or something.

**Comment by the-mikedavis** [comment]
There's been some discussion about more granular or automatic undo checkpoints in insert mode based on a timeout or a number of words typed but many of us agree that it's better to be explicit about the checkpoints (i.e. use `C-s` or switch to normal mode) or else you end up having to hit `u` (or `C-z` in this case) an unpredictable number of times to go back to the last explicit checkpoint.

See https://github.com/helix-editor/helix/issues/1583#issuecomment-1022812303
