### ISSUE TITLE
"Why?" On README.md

### ISSUE THREAD

**Issue by LamprosPitsillos** [helix-editor/helix#241]
Would love if someone edited the readme to point out why should people use helix. What does helix offer that kakouna/vim doesn't? 
Thanks!

**Comment by pickfire** [comment]
I think we can do this in the wiki. So we don't need to manually edit it one by one the differences.

**Comment by digital-carver** [comment]
A request for someone who knows the editor to update the wiki - the Kakoune section of the above linked page is still empty. (The vision document linked from [the other issue](https://github.com/helix-editor/helix/issues/905) doesn't mention any concrete goals either (though the batteries included approach *maybe* hints at one of the differences from kakoune).

**Comment by pickfire** [comment]
I added a main differences from kakoune, I think I will close this issue for now since anyone can go and edit the wiki.

If anyone still have (specific) question, feel free to open a discussion.
