### ISSUE TITLE
Keybind to add cursors on both ends of a selection

### ISSUE THREAD

**Issue by ghost** [helix-editor/helix#2413]
It would be nice to have a feature of "surrounding cursors".

Kind of like a fusion of `ms` (surround add) and `C` (spawn cursor below).

I think this would also fit Helix's overall philosophy of embracing multiple cursors.

**Comment by EpocSquadron** [comment]
Can you be a little more specific? Are you looking to select only the surrounding braces but nothing between? This is the default behavior in normal mode if you use `mm` with the cursor on one of the braces, but I could see cases where you would want to select only braces while the current selection is between them.

**Comment by sudormrfbin** [comment]
I've changed the title to be a bit more descriptive, hopefully still describing what you meant.

**Comment by stonewareslord** [comment]
Would this type of implementation work for you? I have been working on Kakoune's (`<a-S>`)[https://github.com/mawww/kakoune/blob/master/doc/pages/keys.asciidoc] keybinding

Orig:
![image](https://user-images.githubusercontent.com/7482347/203182017-6d49f8f3-8679-45e5-a3ba-4814acb3beab.png)

After `<A-S>`:
![image](https://user-images.githubusercontent.com/7482347/203182044-00a5b605-72f2-43f0-bca0-4ba0c122bba9.png)

Then you could grab your whole object with `ma(` and select the `()` with `<A-S>`

Code: https://github.com/helix-editor/helix/compare/master...stonewareslord:feature/select-head-and-anchor?expand=1
