### ISSUE TITLE
Some themes highlight keyword and error in the same way

### ISSUE THREAD

**Issue by fvacek** [helix-editor/helix#2421]
### Summary

For example `monokai-*` define `red` color for the `keyword` and for `error`

### Reproduction Steps

![image](https://user-images.githubusercontent.com/4949019/167216914-3f7626ca-8311-45d2-b74c-0aff8bf1ab63.png)

error should be visually different than the key, for example like this:
![image](https://user-images.githubusercontent.com/4949019/167217137-7fec712e-b29f-4413-bdf6-b0aed320fd7e.png)

### Platform

Linux

### Terminal Emulator

Tilix

### Helix Version

22.03-168-g16681835

**Comment by pascalkuthe** [comment]
This was fixed by #2433 we just forgot to close this
