### ISSUE TITLE
Better default keybinds for scrolling in pickers

### ISSUE THREAD

**Issue by n0s4** [helix-editor/helix#2428]
In any picker, it seems that the only way to scroll through items is with the arrow keys which is a bit bothersome and goes against the ergonomic style of the editor. I'd like there to be a default keymap to `C-j/k` or `A-j/k`.

This would be solved if picker commands were re-mappable, killing two birds with one stone, but I still think a default bind like the ones mentioned before would be appropriate.

**Comment by the-mikedavis** [comment]
`C-j`/`C-k` was removed from the picker a while back: https://github.com/helix-editor/helix/pull/1792

`C-n` and `C-p` can be used to go to next and previous

**Comment by n0s4** [comment]
Woops.. missed that somehow, thanks.
