### ISSUE TITLE
Persistent workspace file tree (similar to VSCode)

### ISSUE THREAD

**Issue by tqwewe** [helix-editor/helix#2438]
Coming from VSCode to Helix, it would be nice to have a persistent file tree panel for the current workspace/working directory.
The biggest benefit of this is to easily view which files have errors in a rust project.

Alternatively, what's the recommended way of viewing which files have errors from Rust Analyzer in helix editor? Or should I have another terminal tab open and manually run `cargo check` each time to see which files aren't working correctly?

**Comment by the-mikedavis** [comment]
There's a PR for a workspace-wide diagnostics picker that should make it very easy to get a view of files with errors: https://github.com/helix-editor/helix/pull/2013

File tree has an overall issue here: #200. See also https://github.com/helix-editor/helix/pull/2377
