### ISSUE TITLE
How to get equivalent of kakoune's `m/M` command?

### ISSUE THREAD

**Issue by augustebaum** [helix-editor/helix#2439]
I'm struggling to make a mapping that works like `m` or `M` in kakoune, i.e. select to/around the next bracket pair (regardless of the kind of pair). I like the way kakoune did it because in many cases I don't care which kind of pair it is (paren, square bracket, curly bracket). Is there a way to do this using the current config system?

I know the TOML config is temporary.

**Comment by the-mikedavis** [comment]
https://github.com/helix-editor/helix/pull/1946 was merged recently which allows you to jump to the closest surrounding pair with `mim`/`mam`. It jumps to the matching pair you're already inside of though which might not match kakoune's `m`. Does https://github.com/helix-editor/helix/issues/1974 cover the behavior you're looking for?

**Comment by augustebaum** [comment]
#1946 is a great improvement in my opinion. I'm on the latest Homebrew version (22.03) so I didn't know this was a thing. Is there a way to get the `master` version from Homebrew?
However, I'm still not sure how I could remap, e.g., `M` to `mam` in my config.

**Comment by the-mikedavis** [comment]
https://github.com/helix-editor/homebrew-helix/pull/7 was just merged in the tap which allows building from head which looks like it builds from master.

I'm not sure it's possible to remap `mam` since I think it's implemented with some special handling. See also #1383 which would allow rebinding it
