### ISSUE TITLE
Time taken for mode switch from INSERT to NORMAL

### ISSUE THREAD

**Issue by pretentious7** [helix-editor/helix#2441]
Hello,

I'm not sure if there's a configuration option I'm missing, but I couldn't find it in the docs. How do I make the little pause between mode switch from insert to normal go away? It takes about ~50ms or so I'd guess, and it's really annoying cause I queue up things for after ESC, which execute immediately in INSERT mode.

Thank you.

**Comment by the-mikedavis** [comment]
Are you using tmux? https://github.com/helix-editor/helix/wiki/Troubleshooting#when-using-tmux-or-screen-there-is-a-delay-after-hitting-escape-before-its-registered

**Comment by pretentious7** [comment]
Yes, sorry, my bad.
