### ISSUE TITLE
Mouse not working (Windows + Alacritty)

### ISSUE THREAD

**Issue by cdecompilador** [helix-editor/helix#2446]
### Summary

Mouse not working

### Reproduction Steps

Running helix inside alacritty and trying to scroll/select

### Helix log

Nothing related to mouse

### Platform

Windows

### Terminal Emulator

Alacritty

### Helix Version

helix 22.05-dev (ae19aaf1)

**Comment by the-mikedavis** [comment]
Does the mouse work on other terminals (like Kitty or WezTerm)?

**Comment by cdecompilador** [comment]
On WezTerm it does not work also, but surprinsingly it works on cmd, its weird as far as I know both use conhost

**Comment by cdecompilador** [comment]
have you tried alacritty?

**Comment by cdecompilador** [comment]
Ok I've tried other terminals and I don't know why the first time I tried Wezterm it didn't worked, It's just alacritty as far as I know, so it might be an issue on alacritty or on crossterm.

Refer to this on crossterm: [#664](https://github.com/crossterm-rs/crossterm/issues/664)

**Comment by TimonPost** [comment]
I could not reproduce it myself. So if someone can look at #664 and see if it is still relevant that would be nice.

**Comment by cdecompilador** [comment]
Its related to windows (and a possible solution is on hands of crossterm or alacritty) so I'll close this
