### ISSUE TITLE
Add "pre-key" for inserting without auto-indentation

### ISSUE THREAD

**Issue by crdpa** [helix-editor/helix#2456]
In kakoune if i want to insert some copied code that is already formatted and i didn't want to trigger the auto-indentation i would type "\\" before entering insert mode. I can't find anything similar in Helix.

I use it all the time with html files and the auto-indentation compounds without this possibility.

**Comment by the-mikedavis** [comment]
Are you pasting in the copied code? You should use <kbd>space</kbd><kbd>p</bkd> when pasting from the system clipboard. See #2239

**Comment by crdpa** [comment]
> Are you pasting in the copied code? You should use spacep when pasting from the system clipboard. See #2239

Thanks. That works! Sorry for not noticing.
I tried with Ctrl+Shift+V which results in the behaviour i mentioned and I can avoid with the pre-key in kakoune.
