### ISSUE TITLE
master seems broken: error[E0277]: `ErrorKind` doesn't implement `std::fmt::Display`

### ISSUE THREAD

**Issue by nebiros** [helix-editor/helix#2460]
### Summary

from `cargo install --path helix-term`, latest commit at date: `7b287f63 Blaž Hrastnik 13 hours ago - nix: update flake dependencies`

```
   Compiling helix-view v0.6.0 (/Users/juan.alvarez/Library/Caches/Homebrew/helix--git/helix-view)
error[E0277]: `ErrorKind` doesn't implement `std::fmt::Display`
   --> helix-view/src/handlers/dap.rs:305:81
    |
305 | ...                   e => panic!("Error to start debug console: {}", e),
    |                                                                       ^ `ErrorKind` cannot be formatted with the default formatter
    |
    = help: the trait `std::fmt::Display` is not implemented for `ErrorKind`
    = note: in format strings you may be able to use `{:?}` (or {:#?} for pretty-print) instead
    = note: this error originates in the macro `$crate::const_format_args` (in Nightly builds, run with -Z macro-backtrace for more info)

For more information about this error, try `rustc --explain E0277`.
error: could not compile `helix-view` due to previous error
warning: build failed, waiting for other jobs to finish...
error: failed to compile `helix-term v0.6.0 (/Users/juan.alvarez/Library/Caches/Homebrew/helix--git/helix-term)`, intermediate artifacts can be found at `/Users/juan.alvarez/Library/Caches/Homebrew/helix--git/target`
```

### Reproduction Steps

 

I tried this:

1. `cargo install --path helix-term`

I expected this to happen:

Compile and install

Instead, this happened:

```
   Compiling helix-view v0.6.0 (/Users/juan.alvarez/Library/Caches/Homebrew/helix--git/helix-view)
error[E0277]: `ErrorKind` doesn't implement `std::fmt::Display`
   --> helix-view/src/handlers/dap.rs:305:81
    |
305 | ...                   e => panic!("Error to start debug console: {}", e),
    |                                                                       ^ `ErrorKind` cannot be formatted with the default formatter
    |
    = help: the trait `std::fmt::Display` is not implemented for `ErrorKind`
    = note: in format strings you may be able to use `{:?}` (or {:#?} for pretty-print) instead
    = note: this error originates in the macro `$crate::const_format_args` (in Nightly builds, run with -Z macro-backtrace for more info)

For more information about this error, try `rustc --explain E0277`.
error: could not compile `helix-view` due to previous error
warning: build failed, waiting for other jobs to finish...
error: failed to compile `helix-term v0.6.0 (/Users/juan.alvarez/Library/Caches/Homebrew/helix--git/helix-term)`, intermediate artifacts can be found at `/Users/juan.alvarez/Library/Caches/Homebrew/helix--git/target`
```

### Platform

macOS

### Terminal Emulator

iTern2

### Helix Version

22.03-207-g7b287f63

**Comment by the-mikedavis** [comment]
1.60 was released in early april (2022-04-07) but brew may be behind on packaging it. See also https://www.whatrustisit.com/

In general we've been try to target 1.57-1.58 because distributions that package helix take some time to update their rust version. We may want to revert/alter https://github.com/helix-editor/helix/commit/7ae6cad52ed001a903577e30fb71e346fd831af7 which introduced the display for `ErrorKind` behavior so we can build on older rust versions. (cc: @archseer)

**Comment by nebiros** [comment]
> 1.60 was released in early april (2022-04-07) but brew may be behind on packaging it. See also https://www.whatrustisit.com/
> 
> In general we've been try to target 1.57-1.58 because distributions that package helix take some time to update their rust version. We may want to revert/alter [7ae6cad](https://github.com/helix-editor/helix/commit/7ae6cad52ed001a903577e30fb71e346fd831af7) which introduced the display for `ErrorKind` behavior so we can build on older rust versions. (cc: @archseer)

Seems like rust 1.60 is broken at homebrew, https://github.com/Homebrew/homebrew-core/pull/98823

**Comment by ipstone** [comment]
For the moment, I switched to commit 5c2570582bdacf7ac, things compile fine on M1 mac.

**Comment by nebiros** [comment]
> For the moment, I switched to commit [5c25705](https://github.com/helix-editor/helix/commit/5c2570582bdacf7acebf1bf4cab90699b98ecc67), things compile fine on M1 mac ... but somehow file syntax is not working ...

yeah, but is a homebrew issue, you can use asdf and install latest rust stable version from there, guess it will work
