### ISSUE TITLE
Reduce bloat (tree-sitter sources, multriple shared libraries, rust stdlib)

### ISSUE THREAD

**Issue by cdecompilador** [helix-editor/helix#2462]
The editor itself is pretty lightweight, ~16MB, but its "runtime" is massive, 0.6 GB, if instead of retaining the tree-sitter sources by default and building a lot of independent dlls/so (which contains the rustlib statically linked so its size use to be big), we could have a single dll/so and check if a function for that language exists at runtime or maybe link all those shared libraries dynamically with the rust stdlib (as far as I know is possible, but has some low level issues, so some unsafe code may break with an update). For the tree-sitter sources I'd recomend just tracking the repo link + version (tag/rev/whatever) on a json and when checking updates just check if the repo has a new (tag/rev/whatever)

It's just that I like lightweight things, and an editor should not occupy more than 20MB in my opinion

**Comment by kirawi** [comment]
I'm not sure I quite understand. The tree-sitter shared object files are just C/C++ compiled, and as of `22.03` w/ #1659 you can select which grammars to build (with all of them being the default).

**Comment by cdecompilador** [comment]
Ah I didn't knew that, I entered on one source and saw a `Cargo.toml` and the first thing I thought was "those many stdlibs may take a lot of space"

Then if the source folders deletion and track of the already compiled version feature is fine, should I start a new issue and close this?

**Comment by archseer** [comment]
It's up to you to clean up `runtime/grammars/sources` if you're building by hand, the same way it's up to you to run `cargo clean` when you're building cargo projects. Most users **don't build from source** and use a precompiled package.

The latest release is 7MB as .tar.xz: https://github.com/helix-editor/helix/releases/tag/22.03
Installed Arch package is 64MB with all the grammars: https://archlinux.org/packages/community/x86_64/helix/
