### ISSUE TITLE
Scrolling above the starting window causes visual glitches

### ISSUE THREAD

**Issue by leimath** [helix-editor/helix#2466]
### Summary

When hx is launched and scrolled passed up the screen with resizing causes drawing visual glitches. 

Unrelated but a similar issue is encountered with vim (windows binary version) as well.

### Reproduction Steps

 

I tried this:

1. Launch `hx` in a small window.
2. Resize the window to max
3. scroll above/up.

Instead, this happened:

Text glitches like: 

![image](https://user-images.githubusercontent.com/96306150/168295398-eb9b608b-0ded-4e01-a3c6-9e00bf2be1fb.png)

</details>

### Platform

Windows 10 Home Version 10.0.19044 Build 19044

### Terminal Emulator

Windows Terminal Preview Version: 1.13.10983.0 / Windows Terminal (1.11.3471.0)

### Helix Version

helix 22.03 (d4e45fd4)

**Comment by kirawi** [comment]
Are you able to replicate using another terminal emulator, e.g. Alacritty or wezterm?

**Comment by leimath** [comment]
This is fixed in/by [Windows Terminal Preview v1.14.1432.0](https://github.com/microsoft/terminal/releases/tag/v1.14.1432.0), upcoming release. Hence I am closing the issue.
