### ISSUE TITLE
Sometimes when hx is started, syntax highlighting is incomplete

### ISSUE THREAD

**Issue by thomas-profitt** [helix-editor/helix#2484]
### Summary

When running `hx` repeatedly to open the same file, ~4 out of every 10 sessions will start with incorrect syntax highlighting:
![Screenshot_2022-05-16_14-29-53](https://user-images.githubusercontent.com/13843293/168678766-3adbb4ed-2221-4509-b7b3-3e6b5acb3057.png)

I've seen this happen with both `.rb` and `.ex` files. I expect it happens with other file types too, but don't know if I've noticed it.

In a `hx` session that started with this bug, `:open`-ing a new file, even a file of a different language, does not fix the highlighting. Nor does running `:set-language`, `:theme`, or anything else I tried. `hx` must be restarted.

### Reproduction Steps

I tried this:

`hx whatever.rb`,  `hx whatever.rb`,  `hx whatever.rb`,  `hx whatever.rb`,  `hx whatever.rb`, either in sequence or in separate terminal emulator windows

I expected this to happen:

Each of the 5 `hx` invocations starts Helix, with the same color theme, and they all look the same.

Instead, this happened:

One or more of the running `hx` sessions doesn't correctly highlight these specific parts of the code. Each time the bug happens, it's these same parts that aren't properly highlighted.

### Helix log

(whether a `hx` session starts with this bug or not, log output is the same for me.)

### Platform

Linux (amd64)

### Terminal Emulator

Affects both gnome-terminal and cool-retro-term

### Helix Version

helix 22.05-dev (cc68fa85)

**Comment by the-mikedavis** [comment]
I think it might have something to do with the fallback behavior for themes but I haven't investigated much - I have also seen this happening with Elixir files.

**Comment by archseer** [comment]
I suspect it could be the query analysis inside tree-sitter being non-deterministic somehow. I've seen this with `TODO` comment highlights in typescript where it would highlight them incorrectly sometimes
