### ISSUE TITLE
The documentation popup does not scroll correctly.

### ISSUE THREAD

**Issue by axdank** [helix-editor/helix#2488]
The popup of the documentation does not scroll correctly, it is not proportional when scrolling down and up, for example to scroll to the end `( Ctrl + d ) x 3`, and to scroll back up `( Ctrl + u ) x 6`.

When scrolling down, some lines of documentation are lost, so you have to scroll down and back up again to see them.

https://user-images.githubusercontent.com/55039048/168697627-65871924-6b04-4ad6-a6f4-bfbe355a8d5e.mp4

**Comment by sudormrfbin** [comment]
Duplicate of #2148.

**Comment by anshul-bharat** [comment]
I am using helix version 20.03 on windows terminal.
I cannot scroll the function documentation popup. There are not scrollbars. For this reason, i don't use helix as my main editor.
