### ISSUE TITLE
Crashed

### ISSUE THREAD

**Issue by metacortexplus** [helix-editor/helix#2493]
### Summary

```
thread 'main' panicked at 'assertion failed: self.is_char_boundary(n)', /rustc/9d1b2106e23b1abd32fce1f17267604a5102f57a/library/alloc/src/string.rs:1718:29
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

```

### Reproduction Steps

1. `:theme`
2. spacebar
3. arrow up (previously entered command)
4. TAB

### Helix log

<details><summary>~/.cache/helix/helix.log</summary>

```
2022-05-17T15:36:49.125 helix_view::editor [ERROR] Failed to initialize the LSP for `source.js` { cannot find binary path }

```

</details>

### Platform

Fedora 36

### Terminal Emulator

Gnome Terminal (Version 3.44.0 for GNOME 42)

### Helix Version

helix 22.03 (d4e45fd4)

**Comment by the-mikedavis** [comment]
Duplicate of https://github.com/helix-editor/helix/issues/1888
