### ISSUE TITLE
Problem with Helix when using on Debian under WSL2

### ISSUE THREAD

**Issue by fnfontana** [helix-editor/helix#2495]
Hello! I've installed Helix on Windows using Chocolatey, and I like it so much!!
Currently, I'm using VS Code for coding, and I have decided to experiment using a terminal based editor, I never have adapted well to VIM... And the Helix was an awesome experience to me!

Then I have installed it on my WSL2 running a Debian distro following [these steps](https://github.com/helix-editor/helix).
But on WSL the layout is appearing weird for me, maybe I have done something wrong...

It's everything black and white, no colors like on Windows.
When I go to select theme option and set it to default, it prompts: `Unsupported theme: theme requires true color support.`

I'm relatively new to Linux, but I know that my terminal supports true color since I've used it with another TUIs via SSH.
I also have tested it on another terminals applications, like Alacritty, Windows Terminal and so on, it's giving the same message.

Furthermore, I think that could be a misconfiguration on WSL...
Do I have to set up a configuration to enable _true color_ on it? 
Or maybe I have to uninstall it and try to install again using _brew_?

**Comment by the-mikedavis** [comment]
I'm not sure there's a go-to package for Debian yet. AppImage was added recently that should build on the next release #2089 and there's a PR to set up snaps https://github.com/helix-editor/helix/pull/2180 but I don't think there's anything you can just pull from aptitude at the moment. You may be able to use the linux binary from the releases page: https://github.com/helix-editor/helix/releases/tag/22.03

You'll want to unset `HELIX_RUNTIME` if you set it and use `cargo uninstall` to remove the binary.
