### ISSUE TITLE
Panic when trying to run heilx on non-existent file

### ISSUE THREAD

**Issue by cojis** [helix-editor/helix#25]
Running `hx` on a non-existent file (to create it) will panic on osx. File has to be created before `hx` can open/edit

```
hx test.go
---
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: No such file or directory (os error 2)', helix-term/src/main.rs:117:46
```

**Comment by IceDragon200** [comment]
@cojis Latest versions of helix no longer panic, but it still does error instead of opening an empty buffer, there is a PR open to have it behave like that however
