### ISSUE TITLE
Make copy/paste work with all clipboards by default (to quote Steve Krug, “don’t make me think!”) :)

### ISSUE THREAD

**Issue by aral** [helix-editor/helix#2502]
Currently, there are (as I understand it, which isn’t saying much) four clipboards:

  - Clipboard
  - Primary clipboard
  - System clipboard
  - Primary system clipboard

And here’s what I want to do: cut/copy and paste text.

Things I don’t want to (nor should I have to) care about: which clipboard I’m copying into and which clipboard works where and when.

Basically, the default functionality should be that if you cut/copy some text in Helix, you should be able to paste it anywhere (in Helix, in a different tab in your terminal, into your browser…)

Right now I can’t do that.

Ah, that text I “yanked” in Helix, I want to paste it into my browser… oops! So I have to go back, select it again, make sure I yank it to the correct clipboard, etc.

I really love so much about Helix but if anything makes me go back to using a regular editor I think it will be this.

(And I’m not saying don’t have all those clipboards for all the professional clipboard users out there. I’m just saying make the default something that works everywhere and keep the others for people who are working towards their PhDs in clipboard management.) :)

**Comment by aral** [comment]
For anyone else that’s confused by this, the closest you can get to this functionality is to always use the yank to clipboard (<kbd>space<kbd><kbd>shift</kbd><kbd>y</kbd>) and paste from clipboard (<kbd>space<kbd><kbd>shift</kbd><kbd>p</kbd>) shortcuts.

(Not the “yank to clipboard” ones – <kbd>y</kbd> and <kbd>p</kbd>.)

**Comment by augustebaum** [comment]
It would indeed be nice to have the option to set the default register as the system clipboard, like in vim where you can do (I think?):
```
set clipboard=unnamed
```
Right now I'm alternating between the two so I always forget the `space`; it's annoying.
Thanks for the attention!

**Comment by pickfire** [comment]
> I guess I would expect the simpler shortcuts (y and p) to exhibit this behaviour by default. Having the simpler ones work everywhere would be a nice usability win.

If override primary then yeah, but if override clipboard then I don't think it is a good idea, but still I prefer vim behavior where `"+` goes to clipboard, it was discussed previously but the integration with multiple cursors wasn't that good so it wasn't implemented, I still think it is a good to have given that multiple cursors aren't always used.
