### ISSUE TITLE
`Show docs` doesn't work as expected with some selections

### ISSUE THREAD

**Issue by heliostatic** [helix-editor/helix#2509]
While requesting documentation for `match`, with the cursor on the `m` of match `Some([m]atch`, the documentation shown is for `Some`. With the cursor on `a`, the documentation shown is for `match`:

https://user-images.githubusercontent.com/70898/169386069-efaf8157-0f77-4c94-b6dc-4c0d88af704c.mp4

**Comment by Zaechus** [comment]
I don't think this bug exists anymore. I tested `<space>k` on the same spot, and it works as intended:

![image](https://user-images.githubusercontent.com/19353212/226027179-f12261b2-3f37-4437-b125-838d86d1ece9.png)

**Comment by gabydd** [comment]
can't know for sure but it may have been an issue with rust-analyzer that's been fixed, I think this can definitely be closed.
