### ISSUE TITLE
Add "Eclipse JDT Language Server" as the default lsp server for Java

### ISSUE THREAD

**Issue by Thomas-Jack** [helix-editor/helix#2510]
#### Change languages.toml to include the Eclipse JDT Language Server as the default server.
```diff
[[language]]
name = "java"
scope = "source.java"
injection-regex = "java"
file-types = ["java"]
roots = ["pom.xml"]
+ language-server = { command = "jdtls" }
indent = { tab-width = 4, unit = "    " }
```
#### Change the wiki to direct users to installation instructions for Eclipse JDT Language Server

```markdown
## Eclipse JDT Language Server

https://github.com/eclipse/eclipse.jdt.ls

Installation instructions can be found on the [projects README](https://github.com/eclipse/eclipse.jdt.ls)
On MacOS installation can also be done via `brew install jdtls`
 ```

**Comment by the-mikedavis** [comment]
These changes look good - would you like to submit a PR for the languages.toml change and then update the wiki when that's merged?

**Comment by KingTheGuy** [comment]
i keep getting this lsp error at the start of java files.
"App.java is a non-project file, only syntax errors are reported"
in the same project i tried using vscode and neovim with "jdtls" but those seem to be working fine with no errors.
thoughts?

**Comment by Thomas-Jack** [comment]
Done

**Comment by s1ck** [comment]
@Thomas-Jack 
I'm using helix mainly for writing Rust but I was playing a little with helix and Java using `jdtls` since I want to get away from full-blown IDEs. While I see that the LSP is working and giving hints, the code actions don't really work for me. For example, if I implement an interface, it correctly suggests implementing the missing methods, but nothing happens when I select the code action. Is there maybe additional configuration necessary?

**Comment by Damjan94** [comment]
I am having the same problem. They have an open [issue](https://github.com/eclipse/eclipse.jdt.ls/issues/376) about it, and it doesn't look like they'll fix it....

**Comment by Ordoviz** [comment]
> i keep getting this lsp error at the start of java files. "App.java is a non-project file, only syntax errors are reported"

@KingTheGuy I had the same error and fixed it by adding following minimal [`pom.xml`](https://maven.apache.org/guides/introduction/introduction-to-the-pom.html) file to the project root:

```xml
<project>
    <modelVersion>4.0.0</modelVersion>
    <groupId>com.mycompany.app</groupId>
    <artifactId>my-app</artifactId>
    <version>1</version>
    <build>
        <sourceDirectory>${project.basedir}/src</sourceDirectory>
    </build>
</project>
```

Also make sure you don't have any `.git` folders in `src/`.

**Comment by KingTheGuy** [comment]
> > i keep getting this lsp error at the start of java files. "App.java is a non-project file, only syntax errors are reported"
> 
> @KingTheGuy I had the same error and fixed it by adding following minimal [`pom.xml`](https://maven.apache.org/guides/introduction/introduction-to-the-pom.html) file to the project root:
> 
> ```
> <project>
>     <modelVersion>4.0.0</modelVersion>
>     <groupId>com.mycompany.app</groupId>
>     <artifactId>my-app</artifactId>
>     <version>1</version>
>     <build>
>         <sourceDirectory>${project.basedir}/src</sourceDirectory>
>     </build>
> </project>
> ```
> 
> Also make sure you don't have any `.git` folders in `src/`.

i actaully ended "fixing" my issues.
```
[[language]]
name = "java"
scope = "source.java"
injection-regex = "java"
file-types = ["java"]
roots = ["build.xml", "pom.xml", "settings.gradle", "settings.gradle.kts"]
indent = { tab-width = 2, unit = "    " }
# jdtl is a python script provided by JDTLS, and must be on $PATH
language-server = { command = "jdtls", args = [ 
  "-configuration", "/home/boots/.cache/jdtls/config",
  "-data", "/home/boots/.cache/jdtls/workspace",
  ]}
```
the "-configuration" "-data" are the key parts here. someone in helix's matrix chat helped me with it. what they did was basically copy the config that nvim-lspconfig has, those key parts that i mentioned.

**Comment by YoungHaKim7** [comment]
https://github.com/eruizc-dev/jdtls-launcher


```bash
git clone https://github.com/eruizc-dev/jdtls-launcher.git 
Cloning into 'jdtls-launcher'...
remote: Enumerating objects: 241, done.
remote: Counting objects: 100% (85/85), done.
remote: Compressing objects: 100% (52/52), done.
remote: Total 241 (delta 43), reused 50 (delta 28), pack-reused 156
Receiving objects: 100% (241/241), 48.74 KiB | 9.75 MiB/s, done.
Resolving deltas: 100% (125/125), done.


$ cd jdtls-launcher 

 
$ ls
CONTRIBUTING.md  install.sh  jdtls-launcher.sh  LICENSE  README.md


$ ./install.sh 
INFO: Downloading JDTLS-LAUNCHER
-#O=#   #     #
INFO: Extracting JDTLS-LAUNCHER
INFO: Creating symlink at /home/gy/.local/bin/jdtls
Installing jdtls...
jdt-language-server-1.28.0-202309221544 is going to be installed
########################################################################################################################### 100.0%########################################################################################################################### 100.0%
Installing lombok...
########################################################################################################################### 100.0%
Lombok installation succesfull
JDTLS installation succesfull
INFO: Installation successful
INFO: Ensure /home/gy/.local/bin is in path
```

end

**Comment by allaboutevemirolive** [comment]
In my case,
1. I installed `JDTLS` with @YoungHaKim7 's suggestion
2. Locate `JDTLS` in this path: 
```
/home/username/.local/bin/jdtls
```
3. Add `JDTLS` to my `PATH` in `~/.bashrc`
```
export PATH="$PATH:/home/username/.local/bin"
```
4. **NO NEED** to modify `~/.config/helix/languages.toml`

P/S: I'm sure there is a more clean way to do this without forking [jdtls-launcher](https://github.com/eruizc-dev/jdtls-launcher).
