### ISSUE TITLE
Picker separator below input line lacks a theme key

### ISSUE THREAD

**Issue by kyrime** [helix-editor/helix#2522]
Currently, the picker separator is hardcoded to the default theme's `comet` color (purplish). The relevant code is at [https://github.com/helix-editor/helix/blob/master/helix-term/src/ui/picker.rs#L590](https://github.com/helix-editor/helix/blob/master/helix-term/src/ui/picker.rs#L590).

![image](https://user-images.githubusercontent.com/15171148/169584988-4ac3cdd9-92ae-4013-b17e-14e711ea2546.png)

**Comment by the-mikedavis** [comment]
We should be able to replace that line:

https://github.com/helix-editor/helix/blob/e8e252648f0287ccd503c59ea2c1fd7a155dafb5/helix-term/src/ui/picker.rs#L590

with something like:

```rust
let sep_style = cx.editor.theme.get("ui.text.separator");
```

and add the new scope to the default theme here:

https://github.com/helix-editor/helix/blob/e8e252648f0287ccd503c59ea2c1fd7a155dafb5/theme.toml#L54-L56

as comet.

The scope name might need some bike-shedding. Would you like to open a PR?

**Comment by kyrime** [comment]
The key name/scope is the reason I didn't open a PR, haha. Since the borders of the picker use `ui.background` as their key I was thinking it should be `ui.background.separator` to draw a reasonable default for all the other themes, but then I thought `ui.background` isn't the most descriptive name for borders in the first place and decided to just leave it to someone more familiar with the theme key names. I'll open a PR.

**Comment by the-mikedavis** [comment]
Hmm yeah I'm not sure what the best scope name for this would be either 😅

What do others think?
