### ISSUE TITLE
how can i enable syntax highlighting for react, redux and other frameworks, packages are available on npm

### ISSUE THREAD

**Issue by urtheaman** [helix-editor/helix#2537]
syntax highlighting packages are available on npm registry. how can i use them in helix?

**Comment by archseer** [comment]
What packages? We don't use NPM. https://docs.helix-editor.com/guides/adding_languages.html

We already highlight JS/TS/JSX/TSX, what's missing? If you'd like to improve the highlighting queries, you can edit https://github.com/helix-editor/helix/tree/master/runtime/queries/jsx

**Comment by urtheaman** [comment]
yeah added languages.toml and it's working, but auto-completion isn't working.
