### ISSUE TITLE
ctrl+down to scroll faster and find some code using ctrl+f shortcuts

### ISSUE THREAD

**Issue by urtheaman** [helix-editor/helix#2540]
i think most of the developers use vs code and switching from that ease and comfort is counter-productive. instead of learning new shortcuts, it'd be awesome if we keep the same shortcuts throughout all editors. it's not about being unique. it's about serving the same purpose.

how can i set vs code commands in config.toml. can't find anything.

**Comment by archseer** [comment]
> most of the developers use vs code

That maybe the case, but this is a modal editor with a completely different way of text editing: It's more Vim than VS Code. In order to use it effectively, you'll need to learn new keybindings.

Key remapping is documented here: https://docs.helix-editor.com/remapping.html

**Comment by urtheaman** [comment]
@archseer isn't there a way to change keybindings?

**Comment by archseer** [comment]
I suggest you use a local config, we want to keep the current bindings.

**Comment by urtheaman** [comment]
i meant as a template or second option, no change to the current bindings.
