### ISSUE TITLE
Odd errors with JavaScript language server

### ISSUE THREAD

**Issue by aral** [helix-editor/helix#2547]
### Summary

Just noticed some odd errors with the JavaScript language server. Not sure what’s causing them. If I quit Helix and restart the errors go away until I add more code to the file. Not sure how to reproduce but here’s the code that’s causing it for me.

![Screenshot from 2022-05-23 16-36-23](https://user-images.githubusercontent.com/41798/169856124-189ebe62-3858-484b-b947-59008ec4d74c.png)

```js
import tapMonkey from '../index.js'
import assert from 'assert'
import strip from 'strip-ansi'

// Test handler tests
tapMonkey.quiet = false
tapMonkey.testHandler({name: 'mock'})
console.log(tapMonkey.spinner)
tapMonkey.spinner.stop()

// General tests

assert(tapMonkey.spinner._spinner.interval === 300, 'spinner internal is as expected')
assert(tapMonkey.spinner._spinner.frames[0] === '  🙈 ', 'animation frame 1 is correct')
assert(tapMonkey.spinner._spinner.frames[1] === '  🙈 ', 'animation frame 2 is correct')
assert(tapMonkey.spinner._spinner.frames[2] === '  🙉 ', 'animation frame 3 is correct')
assert(tapMonkey.spinner._spinner.frames[3] === '  🙊 ', 'animation frame 4 is correct')

assert(strip(tapMonkey.spinner.text).includes('Running mock tests'), 'test name is displayed correctly')

console.log('All tests passed.')
process.exit()
```

### Helix log

<details><summary>~/.cache/helix/helix.log</summary>

No pertinent details found in log.

</details>

### Platform

Linux (Fedora Silverblue 36)

### Terminal Emulator

GNOME Console

### Helix Version

helix 22.05-dev (8df8ff27)

**Comment by the-mikedavis** [comment]
Is this reproducible in another editor?

I expect that it's a bug in the language server upstream unless helix isn't sending it some information it needs.
