### ISSUE TITLE
Helix crash report

### ISSUE THREAD

**Issue by aral** [helix-editor/helix#2559]
### Summary

Helix crashed following a <kbd>v</kbd> command:

```
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: 
Char index out of bounds: char index 5848, Rope/RopeSlice char length 5121', 
/var/home/aral/.cargo/registry/src/github.com-1ecc6299db9ec823/ropey-1.4.1/src/slice.rs:349:41
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

### Reproduction Steps

n/a (not sure what combination of actions caused the crash)

### Helix log

Nothing in the log file from around the time of the crash.

### Platform

Linux (Fedora Silverblue 36)

### Terminal Emulator

GNOME Console

### Helix Version

helix 22.05-dev (8df8ff27)

**Comment by the-mikedavis** [comment]
Without the backtrace part within the helix codebase and/or reproduction steps I don't think this can be debugged: the method pointed to in the backtrace is `char_to_byte` https://github.com/cessen/ropey/blob/d9c841b2ef4ae7ea97c13a99fc26b36ae14ebe12/src/slice.rs#L347-L350. It would be hard to pin-point which use of `char_to_byte` triggers this.

We could probably recommend in the from-source installation instructions setting RUST_BACKTRACE but setting it automatically would be unexpected from a rust program. IMO reproduction steps are more important than a backtrace: the backtrace can inform where you can look to debug but you can't confirm you've fixed the bug unless you can run the reproduction steps without the panic.
