### ISSUE TITLE
Trim leading space in file picker search

### ISSUE THREAD

**Issue by aral** [helix-editor/helix#2564]
Leading space in the file picker search can be trimmed to improve the experience.

e.g., your project structure:

```
some-file.js
```

Search box:

```
 some
```

Will not match _some-file.js_ due to the leading space (which could have been accidentally entered). Since leading spaces are not allowed in file names, they can be trimmed to provide a better experience in this edge case.

__Priority:__ low.

**Comment by archseer** [comment]
The search is fuzzy though: ` test` could mean I'm trying to match `my test.txt`.

**Comment by the-mikedavis** [comment]
Hmm yeah you may want to search for a space follow by a suffix. There is related discussion in https://github.com/helix-editor/helix/issues/2290 of handling spaces in the picker.

**Comment by kirawi** [comment]
https://github.com/helix-editor/helix/pull/2585#issuecomment-1146783060
> Closing since this is intentional behaviour
