### ISSUE TITLE
Mapping to 0 (zero)

### ISSUE THREAD

**Issue by Froloket64** [helix-editor/helix#2566]
I'm coming from Vim, so I felt like 0 for `goto_line_start` is just much more natural to me. But I tried remapping to it (see attached config file) and other numbers and no results.
I believe it might be due to numbers being reserved to repeat the action following them (e.g. `3j`), but 0 just won't do anything in this scenario anyway. If I have time, I'll look through the source and try to verify it and maybe issue a **Pull request**

**Comment by the-mikedavis** [comment]
This is implemented on master: https://github.com/helix-editor/helix/pull/2174

but it isn't in 22.03 release.
