### ISSUE TITLE
Add command to display all key mappings and commands

### ISSUE THREAD

**Issue by e-ivkov** [helix-editor/helix#2573]
## Feature Request
It would be handy to have a `:keymap` and maybe a separate `:commands` to display all the current key mappings and supported commands in the helix. 

## Advantages
This will speed up the workflow for users as they will not have to switch from helix to browser to check the mapping and will also provide better offline support.

## Current State
Currently key mappings can be viewed in the [book](https://docs.helix-editor.com/) online.
Also entering minor modes - helix shows a short reference for their keys

**Comment by the-mikedavis** [comment]
I think the command palette (`space ?`) could meet this need in the long-run with some improvments like adding documentation on the right-hand side of the picker (which could include the command name).

One very small change that could work for this is to treat the keymap docs (https://github.com/helix-editor/helix/blob/7160e745f72e5d742e19fecf9a7e78f32e5b34da/book/src/keymap.md) like the tutor file (https://github.com/helix-editor/helix/blob/7160e745f72e5d742e19fecf9a7e78f32e5b34da/runtime/tutor.txt) so the command would open a buffer for that document. This could actually currently be accomplished in a hacky way by creating a custom command for it:

```toml
[keys.normal]
space = { K = ":open path/to/keymap.md" }
```

**Comment by e-ivkov** [comment]
Yes, `space ?` pretty much does it. Thank you! The only thing it needs is it to include the command name indeed.

I was thinking of taking this issue. So which way do you think should I we go? Should we first add `space = { K = ":open path/to/keymap.md" }` to helix? Or extend the `space` command?

**Comment by e-ivkov** [comment]
I will try to add a new keymap to the source to open the `md` file for now - it seems like a quicker way to start.

**Comment by e-ivkov** [comment]
@the-mikedavis I opened a PR for this - feel free to review when you will have time!

**Comment by e-ivkov** [comment]
The PR was closed in favor of improving the `space ?` command, probably it can be done as part of this issue.

**Comment by kirawi** [comment]
`space-?` looks to now have this behavior. Closing as resolved.
