### ISSUE TITLE
Highlighting custom characters

### ISSUE THREAD

**Issue by Jomy10** [helix-editor/helix#2575]
#### Describe your feature request

It would be nice if we could add highlighting for certain characters in any file type (so they would be highlighted in every programming language).

**Why would this be useful?**
I accidentally type a non-breaking space a lot, and errors regarding this character could be easily prevented if there was a visual separation from non-breaking spaces and regular spaces.

**Comment by the-mikedavis** [comment]
Visible whitespace has been merged https://github.com/helix-editor/helix/pull/1802 but isn't in the latest release yet. This follow-up PR added support for non-breaking space: https://github.com/helix-editor/helix/pull/2322. With these you could configure rendering just for non-breaking space like so:

```toml
[editor.whitespace.render]
nbsp = "all"
```

**Comment by Jomy10** [comment]
Didn't find those while searching. Awesome to see this has already been updated.

I'll be waiting for the next release then.

**Comment by mandarvaze** [comment]
I have the latest release, but unable to use `[editor.whitespace]`
I opened issue #2614
