### ISSUE TITLE
Autocompletion error: words do not get replaced correctly (JavaScript)

### ISSUE THREAD

**Issue by aral** [helix-editor/helix#2580]
### Summary

Just ran into an odd autocompletion error in a JavaScript file.

### Reproduction Steps

The steps:

Selecting word to change:

![Screenshot from 2022-05-27 10-34-48](https://user-images.githubusercontent.com/41798/170673681-3bb9a635-acbb-4f2f-8d93-09b109d73dbf.png)

Starting to change it:

![Screenshot from 2022-05-27 10-34-55](https://user-images.githubusercontent.com/41798/170673729-2cec6b80-a048-497b-9d69-018ac9ca7b25.png)

Getting autocompletion:

![Screenshot from 2022-05-27 10-35-04](https://user-images.githubusercontent.com/41798/170673757-20cb2413-19fd-4fe9-8c87-741270431718.png)

Tabbing through the options, all is well with the first few until I get to:

![Screenshot from 2022-05-27 10-35-19](https://user-images.githubusercontent.com/41798/170673806-2651ec3a-8b12-4d8b-9d94-b887293d1064.png)

Notice that the original `fi` is not replaced with the completion. Rather the completion is erroneously added to it. 

Since this is a field, the beginning of the completion string – which includes the `.this` reference – differs from beginning of the variable name as I started writing it. I’m assuming the string replacement logic in Helix has to be updated to take this case into consideration.

Finally, the corruption remains after using <kbd>enter</kbd> to finalise the completion:

![Screenshot from 2022-05-27 10-35-24](https://user-images.githubusercontent.com/41798/170674062-594016a7-6ef3-4f1a-9291-69e0a9ffe672.png)

### Helix log

No entries in the log from around this time.

### Platform

Linux (Fedora Silverblue 36)

### Terminal Emulator

GNOME Console

### Helix Version

helix 22.05-dev (8df8ff27)

**Comment by aral** [comment]
I just realised that is a more generic issue where the autocompletion replacement is corrupted unless you start the autocompletion at the very start of the word.

I’m in the middle of a word:

![Screenshot from 2022-05-27 10-50-58](https://user-images.githubusercontent.com/41798/170676553-c9565345-8884-4e69-960f-40d433ccef47.png)

I enter insert mode and I get autocompletions:

![Screenshot from 2022-05-27 10-51-03](https://user-images.githubusercontent.com/41798/170676607-7ee11b20-b887-4e50-aa6f-360edc9d5b1a.png)

I select an autocompletion:

![Screenshot from 2022-05-27 10-51-07](https://user-images.githubusercontent.com/41798/170676672-ca88784f-1103-486a-b17e-d15aa9a594a9.png)

Instead of replacing `addFile` with `addEventListener`, the completion term is inserted at the cursor position, resulting in the corrupted `addEventListenerFile` completion.

Finally, as before, the corruption remains when you finalise the completion:

![Screenshot from 2022-05-27 10-51-12](https://user-images.githubusercontent.com/41798/170676955-73c4d2ec-dd13-43a1-9404-19a15942bf62.png)

**Comment by aral** [comment]
Related https://github.com/helix-editor/helix/issues/2027: this also explains the odd corruptions I see when I forget and move around in insert mode. Because of this, I’ve basically started using insert mode only for single lines whenever possible and keep coming in and out of normal mode even when initially writing a contiguous piece of code as at least then I get granular undo to quickly fix autocomplete corruption errors should I forget an navigate in insert mode again.

I do feel this needs a better solution.

**Comment by the-mikedavis** [comment]
This may be fixed by #1819

**Comment by pascalkuthe** [comment]
I am pretty sure this was mostly fixed by recent improvements to completion handling (although your second comment is not a but just how completions work, for servers that support it completions replace can now be configured but not all do).

I think the remaining cases are covered by #2027 so I am closing this issue in favor of that one
