### ISSUE TITLE
Usability enhancement (status line): place file status indicator before file name not after it

### ISSUE THREAD

**Issue by aral** [helix-editor/helix#2582]
A quick glace at the status line should be all it takes to reassure yourself of the current state of the buffer. Keeping common elements in the same place spatially can help with that.

Currently, the file status is shown after the file name which means that it will appear in different locations based on how long the path for the current file is.

e.g.,

```
NOR    ~/.config/helix/config.toml [+]
```

vs

```
NOR    ~/Projects/some-project/src/some-directory/some-other-directory/wow-this-is-a-long-directory-name/my-lovely.js [+]
```

Helix trains you to look at the lower left corner for the current editing state. Any other important state should be kept as close to this position as possible so the person doesn’t have to potentially scan a long line from left to right to get a state update.

## Proposed solution

Move the file state indicator from after the file name to before it:

```
NOR    [+] ~/.config/helix/config.toml
```

And no matter how long the path is, a quick glance to the lower left of the screen will tell us the current state.

```
NOR    [+] ~/Projects/some-project/src/some-directory/some-other-directory/wow-this-is-a-long-directory-name/my-lovely.js
```

**Comment by aral** [comment]
Related: https://github.com/helix-editor/helix/issues/2254

**Comment by the-mikedavis** [comment]
I think this would best be solved by https://github.com/helix-editor/helix/issues/708 (see also #2434). Ideally the status indicator should take up the same amount of space when a file is modified and not so there isn't a visual 'jump' when a file goes from unmodified to modified

**Comment by kirawi** [comment]
#708 is resolved. There is now #4686 for the modification element.
