### ISSUE TITLE
Vim like word based completion

### ISSUE THREAD

**Issue by jeremycostanzo** [helix-editor/helix#2586]
#### Describe your feature request

I tried switching from nvim to helix, but when editing my config file, I noticed that it was not possible to use this vim feature (`C-x` doesn't do anything).

This is quite annoying because there are some functions that I called often, such as `extend_line`.

On the second time I call it, I'd do it with `ex<C-p>` in vim, but here I either need to type the full thing, or bother to go and yank the word.

The lack of this feature is the main reason why I cannot use vscode's vim mode or fully switch to helix, because I find it extremely useful for editing text inside of strings or non code files.

#### What it should do

Typing `<prefix>C-p` starts word based completion with any word that has the same prefix in all opened buffers, sorted by the ones that are closer before the (highest?) cursor.

Typing `<prefix>C-n` starts word based completion with any word that has the same prefix in all opened buffers, sorted by the ones that are closer after the (lowest?) cursor.

It wouldn't have to be `C-p` or `C-n` of course, it is just the standard in Vim.

**Comment by the-mikedavis** [comment]
This falls under https://github.com/helix-editor/helix/issues/1015 but I think it's good to have an issue that focus specifically on word-based completion rather than file-path for example. See also https://github.com/helix-editor/helix/pull/2403

**Comment by jeremycostanzo** [comment]
Oh you are right, I didn't find the issue that you mentioned.

But indeed, closing this one would be a good first step :+1: .

**Comment by the-mikedavis** [comment]
Ah whoops I didn't notice https://github.com/helix-editor/helix/issues/1063
