### ISSUE TITLE
Initial Theme Missing

### ISSUE THREAD

**Issue by yashsf08** [helix-editor/helix#2595]
I remember using a theme called "Dracula_at_night" one month back, apparently it is removed in the update. Pardon me for being specific but I still like the dark version dracula theme.

**Comment by kirawi** [comment]
There is `dracula_at_night`, is that what you meant?

**Comment by yashsf08** [comment]
Exactly! and I'm using helix 22.03 (d4e45fd4).

**Comment by the-mikedavis** [comment]
`dracula_at_night` was added after the 22.03 release and is included in 22.05: https://github.com/helix-editor/helix/pull/2008

**Comment by yashsf08** [comment]
Thanks you!!!
