### ISSUE TITLE
hx --grammar build failure

### ISSUE THREAD

**Issue by voroskoi** [helix-editor/helix#2596]
### Summary

I got this error while compiling from source, skipped with exporting `HELIX_DISABLE_AUTO_GRAMMAR_BUILD`.

The error is not helping me at all, no idea what to check.

### Reproduction Steps

 

I tried this:

1. `hx --grammar build`

I expected this to happen: Builds the grammars

Instead, this happened:
```
[I] ⋊> ~ on master ⨯ hx --grammar build
Grammar 'toml' is already built.
Grammar 'fish' is already built.
Grammar 'c' is already built.
Grammar 'cpp' is already built.
Grammar 'go' is already built.
Grammar 'javascript' is already built.
Grammar 'typescript' is already built.
Grammar 'zig' is already built.
Grammar 'yaml' is already built.
Grammar 'comment' is already built.
Grammar 'markdown' is already built.
Building grammar 'bash'
Grammar 'org' is already built.
Building grammar 'scheme'
Grammar 'json' is already built.
Error: Failed to build some grammar(s)

Caused by:
    0: Failed to execute C compiler
    1: No such file or directory (os error 2)
```

### Helix log

<details><summary>~/.cache/helix/helix.log</summary>

```
please provide a copy of `~/.cache/helix/helix.log` here if possible, you may need to redact some of the lines
```

</details>

### Platform

Linux

### Terminal Emulator

tmux

### Helix Version

22.05 - a106341fd73b1be3d42353ee154d0612b7bfceba

**Comment by the-mikedavis** [comment]
You may need to fetch any new grammars with `hx --grammar fetch` before running `hx --grammar build`.

**Comment by voroskoi** [comment]
Sorry, forgot to mention that `hx --grammar fetch` works fine, so I did run that already. And I have a C compiler (gcc) installed.

**Comment by the-mikedavis** [comment]
Do you have a C++ compiler installed as well, like g++?

Removing `~/.config/helix/runtime/grammars/*` and `hx -g fetch` and `hx -g build` again is worth a try to see if it's a transient failure.

**Comment by voroskoi** [comment]
I was missing the cpp compiler. Sorry, somehow I was sure that tree-sitter grammars use pure c and the error message also says c compiler.
Thanks for Your time!

**Comment by the-mikedavis** [comment]
To make it even more confusing, it's _usually_ just C but some grammars choose to use C++ for the external scanner 😄

There some room for improvement with that error message as you say, I'll make a PR 👍
