### ISSUE TITLE
Failing build v0.0.6 / master / rustc 1.47.0

### ISSUE THREAD

**Issue by adam-zethraeus** [helix-editor/helix#26]
Running: `cargo install --path helix-term`
after: `git clone --recurse-submodules --shallow-submodules -j8 https://github.com/helix-editor/helix`
on an: x86 mac
with: rustc 1.47.0

```

   Compiling jobserver v0.1.22
error[E0658]: unions with non-`Copy` fields are unstable
  --> /Users/adam.zethraeus/.cargo/registry/src/github.com-1ecc6299db9ec823/slotmap-1.0.3/src/basic.rs:19:1
   |
19 | / union SlotUnion<T> {
20 | |     value: ManuallyDrop<T>,
21 | |     next_free: u32,
22 | | }
   | |_^
   |
   = note: see issue #55149 <https://github.com/rust-lang/rust/issues/55149> for more information

error[E0658]: unions with non-`Copy` fields are unstable
  --> /Users/adam.zethraeus/.cargo/registry/src/github.com-1ecc6299db9ec823/slotmap-1.0.3/src/hop.rs:39:1
   |
39 | / union SlotUnion<T> {
40 | |     value: ManuallyDrop<T>,
41 | |     free: FreeListEntry,
42 | | }
   | |_^
   |
   = note: see issue #55149 <https://github.com/rust-lang/rust/issues/55149> for more information

   Compiling unicode-normalization v0.1.18
   Compiling quote v1.0.9
error: aborting due to 2 previous errors

For more information about this error, try `rustc --explain E0658`.
The following warnings were emitted during compilation

```

**Comment by matu3ba** [comment]
git clone --recurse-submodules --shallow-submodules -j8 https://github.com/helix-editor/helix
and
cargo build --release 
work for me.
`cargo install --path helix-term` as well.

This should be `x86 mac` related. Can you search for the according upstream repository and file a bug there?

**Comment by aedrax** [comment]
Same issue here, but running on WSL 2 Ubuntu 20.04
my cargo version is `1.46.0` and rustc version is `1.47.0`

**Comment by aedrax** [comment]
updating my rust install fixed the build
cargo `1.52.0`
rustc `1.52.1`

**Comment by IceDragon200** [comment]
Only the latest stable rustc is supported, seeing as this was resolved by updating the toolchain, I believe I can close this issue now.

Furthermore, the issue was in one of the dependencies of helix, rather than helix itself, I think it would be best to file a report their to get backwards compatibility with older toolchains if needed.
