### ISSUE TITLE
New commands: `add_cursor_search_next`, `add_cursor_search_prev`

### ISSUE THREAD

**Issue by adaszko** [helix-editor/helix#2604]
Hi 👋 .  Here's a proposal for making the use of multiple cursors a little less stateful/modal (and thus more i-see-one-the-screen-what-is-happening-at-each-stage type of thing), diverging a little from what Kakoune does towards the direction of VSCode.

**The editing task this addition is supposed to help with**: replacing multiple (but crucially, not necessarily all) occurrences of a search phrase within a single buffer.

**Current solution**:
1. Select multiple lines to search within with `x`.
2. Type `s`
3. Type the search phrase
4. Operate on text using multiple cursors created.

**The proposed new solution**: 
1. Select a phrase to search
2. Type `*` to copy the selection the `/` register.
3. Call the newly-added `add_cursor_search_next` command that does two things atomically: (1) Adds a new cursor at the current cursor position, and (2) Jumps to the next occurance of the search phrase.  So it's similar to what `n` does, except that prior to jumping, it adds a new cursor too.

Note that unlike with the current solution, it's possible to skip some occurrences of the search phrase simply by pressing `n`, instead of `add_cursor_search_next`.

For completeness, a corresponding command for searching backwards could be added: `add_cursor_search_next`.  They could be assigned to `<Alt-n>` and `<Alt-p>` keys.

I'd appreciate any feedback.  Cheers!

**Comment by kirawi** [comment]
If you enter visual mode `v`, you should be able to get a new selection per each `n`.

**Comment by the-mikedavis** [comment]
See also https://github.com/helix-editor/helix/issues/2499 which covers skipping as well

**Comment by adaszko** [comment]
> If you enter visual mode `v`, you should be able to get a new selection per each `n`.

Wow, That's so simple I haven't thought of it 😅 

> See also https://github.com/helix-editor/helix/issues/2499 which covers skipping as well

```
[keys.select]
"A-n" = "search_next"
"A-N" = "search_prev"
```

Did it for me.  Thank you a ton 😃
