### ISSUE TITLE
Also ship *built* runtimes as source tarball for each release

### ISSUE THREAD

**Issue by uncomfyhalomacro** [helix-editor/helix#2609]
Hello!

So I packaged helix for openSUSE and have noticed that it is difficult to do it unless I do some hacky workarounds. This is because of the way openSUSE Build Service works, during buildtime it cannot access the internet so I have to add this in the rpm spec:

```spec
%build
export RUSTFLAGS="%{rustflags}"

# We must disable fetching and building the treesitter grammars because this is a limitation with OBS cargo-packaging for now
export HELIX_DISABLE_AUTO_GRAMMAR_BUILD=true
cargo build --locked --offline --release
```

Is it possible if helix can also ship already built runtimes or are there any possible solutions to this like when it cannot find any runtimes, it will auto create or something probably in `~/.config/helix/runtime`?

**Comment by the-mikedavis** [comment]
The source tarball attached to the GitHub release `helix-<tag>-source.tar.xz` contains a runtime directory with the grammar sources pre-downloaded. The build for Helix will recognize that the grammar sources are at the correct revisions and will not reach out over the network. You may need to set `HELIX_RUNTIME` to point at the `runtime/` directory of that source tarball but you do not need to set `HELIX_DISABLE_AUTO_GRAMMAR_BUILD`.

The Nix build in nixpkgs uses this strategy and it ends up being a very boring rust build: https://github.com/nixos/nixpkgs/blob/19be7a4d73382ca0170c75f01213ac5853bc7889/pkgs/applications/editors/helix/default.nix

**Comment by uncomfyhalomacro** [comment]
Thanks for letting me know that it is possible @the-mikedavis ! I will update the rpm spec accordingly. CLOSING!
