### ISSUE TITLE
Comment / Uncomment with multiline comments

### ISSUE THREAD

**Issue by zyansheep** [helix-editor/helix#2613]
#### Describe your feature request

Currently the comment system works like:
```rust
let thing = 3;
```
```rust
// let thing = 3;
```

Switching from vscode, I try to uncomment:
```rust
/* let db = namespace.store(ser);
fs::File::create(file).unwrap(); */
```
```rust
// /* let db = namespace.store(ser);
// fs::File::create(file).unwrap(); */
```
But it doesn't uncomment correctly...

Should there be multiple commenting options for multiline vs singleline comments? maybe something like `C-S-c` for multiline?

**Comment by the-mikedavis** [comment]
Duplicate of https://github.com/helix-editor/helix/issues/1505

**Comment by zyansheep** [comment]
Woh I am blind, thanks for quick reply!
