### ISSUE TITLE
error `Bad config: unknown field whitespace`  when using `editor.whitespace` in config.toml

### ISSUE THREAD

**Issue by mandarvaze** [helix-editor/helix#2614]
### Summary

I get error `Bad config: unknown field whitespace` when I specify `editor.whitespace.characters` in `config.toml`

### Reproduction Steps

I'm referring to [this section](https://docs.helix-editor.com/configuration.html#editorwhitespace-section) of the documentation. Accordingly, I've added the following to my `config.toml`

```shell
mandar in ~/.config/helix took 1m2s
➜ cat config.toml
theme = "onedark"

[editor]
line-number = "relative"

[editor.whitespace]
render = "all"

[editor.whitespace.characters]
space = "·"
nbsp = "⍽"
tab = "→"
newline = "⏎"
```

But whenever I start helix I get  the following error:

```shell
mandar in ~/.config/helix
➜ hx config.toml
Bad config: unknown field `whitespace`, expected one of `scrolloff`, `scroll-lines`, `mouse`, `shell`, `line-number`, `middle-click-paste`, `auto-pairs`, `auto-completion`, `idle-timeout`, `completion-trigger-len`, `auto-info`, `file-picker`, `cursor-shape`, `true-color`, `search`, `lsp` for key `editor` at line 9 column 1
```

I expected this to happen:

helix starts without error, and space, newline are rendered using the characters specified in the `config.toml` 

Instead, this happened:

I get the error

```
Bad config: unknown field `whitespace`, expected one of `scrolloff`, `scroll-lines`, `mouse`, `shell`, `line-number`, `middle-click-paste`, `auto-pairs`, `auto-completion`, `idle-timeout`, `completion-trigger-len`, `auto-info`, `file-picker`, `cursor-shape`, `true-color`, `search`, `lsp` for key `editor` at line 9 column 1
```

### Helix log

<details><summary>~/.cache/helix/helix.log</summary>

```
mandar in ~/.config/helix took 3s
➜ cat ~/.cache/helix/helix.log
2022-05-30T21:46:36.908 helix_view::editor [ERROR] Failed to initialize the LSP for `source.toml` { LSP not defined }
```

</details>

### Platform

macOS

### Terminal Emulator

Alacritty

### Helix Version

helix 22.03 (d4e45fd4)

**Comment by the-mikedavis** [comment]
Visible whitespace and its configuration #1802 was added after the 22.03 release and is in 22.05

**Comment by mandarvaze** [comment]
@the-mikedavis Wow! That was quick.
I updated to 22.05, and now works as expected.
Sorry for the unnecessary noise 😢
