### ISSUE TITLE
Improve clipboard yanking messages

### ISSUE THREAD

**Issue by 01mf02** [helix-editor/helix#2615]
### Summary

When selecting some text with the mouse, the message "yanked main selection to system clipboard" appears at the bottom, yet the clipboard does not seem to contain the selected text.

### Reproduction Steps

 

I tried this:

1. `hx`
2. Type "Hello".
3. Select "Hello" with the mouse.
4. Open a GTK application such as Mousepad or Firefox, and paste with middle mouse button or CTRL-V (tried both).

I expected this to happen:

The text "Hello" should appear in the GTK application.

Instead, this happened:

Some previously selected text appears in the GTK application.

### Helix log

Nothing interesting here.

### Platform

Linux

### Terminal Emulator

xfce4-terminal 0.8.10

### Helix Version

22.05-10-g370a16d0

**Comment by the-mikedavis** [comment]
Does this only happen when using the mouse? Does <kbd>Space</kbd><kbd>y</kbd> work to copy a selection to the system clipboard?

**Comment by 01mf02** [comment]
This happens both with mouse and <kbd>Space</kbd> <kbd>y</kbd>.

I found the culprit in the meanwhile: In [`helix-view/src/clipboard.rs`](https://github.com/helix-editor/helix/blob/77ff8d355051ef567c7998b226e28ba436c2e230/helix-view/src/clipboard.rs#L86), Helix checks for the existence of several tools, such as `xsel` and `xclip` to use for clipboard operations. If none of these tools is available, then a `NopProvider` is used which provides a Helix-specific clipboard, but this can be hardly called a "system clipboard".
Therefore, I find the message "yanked main selection to system clipboard" misleading.

I see several ways to improve the current situation:

* The error message in [helix-term/src/commands.rs](https://github.com/helix-editor/helix/blob/77ff8d355051ef567c7998b226e28ba436c2e230/helix-term/src/commands.rs#L3081) could be triggered when no clipboard tool is found. One way to achieve this would be to make the `NopProvider` always fail instead of always succeed.
* The message "yanked main selection to system clipboard" could be changed to something like "yanked main selection to Helix clipboard (install a clipboard tool to use system clipboard)" when no clipboard tool is found.

**Comment by the-mikedavis** [comment]
Yeah improving that error message would be great. I think I would prefer that the system clipboard commands fail when the contents can't be copied so it's more noticeable. What do others think?

**Comment by archseer** [comment]
Agreed!

**Comment by sudormrfbin** [comment]
Selecting with the mouse copies text to the secondary clipboard in Linux, which doesn't exist in Windows. We could copy to the clipboard for windows in this case, but that would probably be too disruptive - the secondary clipboard in Linux doesn't override the contents of a normal ctrl+c made in some other application, while in Windows (due to a lack of multiple clipboards) it will.

**Comment by DuckDuckWhale** [comment]
The distinction between mouse select and <space>y isn't very clear:
- Mouse: `yanked main selection to system clipboard`
- Space + y: `joined and yanked 1 selection(s) to system clipboard`

It is not clear from this prompt that one of them goes to the middle click clipboard yet the other one goes to the normal (Ctrl+C/V) clipboard. Does anyone know what's the correct term for not only X (which I know are clipboard and primary) but also Wayland? (Maybe with Windows also being supported, we just call them "system clipboard" and "system selection clipboard"? Also, the `joined and yanked 1 selections(s)` is unnecessary. Simply `yanked selection to system clipboard` would do.

**Comment by jquesada2016** [comment]
Copying to system clipboard via space+y does not work on Windows through WSL.

**Comment by the-mikedavis** [comment]
https://github.com/helix-editor/helix/issues/2132

**Comment by jquesada2016** [comment]
@the-mikedavis thank you VERY much for the referral!

**Comment by amitbeka** [comment]
cross-posting here:

I've started working on this, learning Rust as I go 😅 
Adding this to the healthcheck now, then I'll look into the error message in-app: #3271

**Comment by shaded-enmity** [comment]
I'm using `helix 22.08.1 (66276ce6)` on mac + iterm2, when I select text with mouse it says `yanked main selection to system clipboard` but the actual text is not in the clipboard/any register. Using <kbd>space</kbd> + <kbd>Y</kbd> prints the same message but actually works as expected.

**Comment by ngraham20** [comment]
Running on RHEL 8 here, and space + y yanks to system clipboard, but the mouse select does not. `hx --health` shows using xclip.

**Comment by me-tantaroth** [comment]
Hi i am trying to use space + Y to be able to copy text from helix to main clipboard but it doesn't, try to paste the text outside helix but it doesn't work.
I have xclip installed on a Chrome OS with debian 10 VM

$ hx --health

Config file: default
Language file: default
Log file: /home/myuser/.cache/helix/helix.log
Runtime directory: /home/myuser/.config/helix/runtime
Clipboard provider: xclip
System clipboard provider: xclip

**Comment by Ashvith10** [comment]
Okay, this is something I've encountered as well, and it works after install xclip. I've also tried this with wl-clipboard, and it works fine.

**Comment by nexovec** [comment]
When I select the entire document with % and then try to yank to system clipboard, helix freezes.
When I select a line with x and then try to yank to system clipboard, nothing gets yanked.

**Comment by b0okle** [comment]
@nexovec Install xclip if you're on x11, or wl-clipboard if you're on wayland.

**Comment by andreaskrath** [comment]
Is this issue still relevant?

Given that there is the [`termcode`](https://github.com/helix-editor/helix/pull/3220) fallback provider for clipboard that is turned on by [default](https://github.com/helix-editor/helix/pull/8925/files#diff-acdd23cb5bf8d9902ce0cc92f9e8b96a73726c795c868db700701a6ee9d06952R18) this should not really be an issue anymore.

Unless you consider support for custom compilations part of the scope of this issue I guess.

**Comment by the-mikedavis** [comment]
Yeah we now have the OSC52 provider as a fallback and the message was adjusted slightly to say which clipboard you're yanking to in https://github.com/helix-editor/helix/pull/4275. We also bubble up errors from the clipboard providers so if one fails (non-zero exit code) that should show in the UI. Configuration for clipboard provider is covered by https://github.com/helix-editor/helix/issues/8826 and I think the other comments in this thread have been about debugging environments (i.e. needing to install the right clipboard tool) so I will close this out.
