### ISSUE TITLE
Opening a directory should change directory

### ISSUE THREAD

**Issue by cjohansson** [helix-editor/helix#2617]
#### Describe your feature request

Background: I would like the ability to quickly switch working directory, I feel like helix just like vim/vi/neovim places too much emphasis on where I was in the shell when I initially started the editor. I would like to be able to have a helix session on for the entire day / days and switch filesystem contexts as needed. (Ideally I would to like have different current working directories for different buffers but that is another feature request.)

When opening a directory with the command `:open` the current working directory should change to the specified location and the file picker for the directory should be displayed. At the moment I get a OS error and the specified path is cleared.

This would be similar to how Emacs does C-x C-f and then pressing C-d in a directory to enter dired-mode for the specified directory

**Comment by kirawi** [comment]
You can use `:cd` to change the working directory.

**Comment by weakphish** [comment]
I'd like to give this a shot, if that's okay?

**Comment by the-mikedavis** [comment]
The file picker popping up when you `:open` a directory seems like a nice win (see also https://github.com/helix-editor/helix/issues/2558), I'd say go for it 🙂

In my opinion `:open` shouldn't also `:cd` you though, I would prefer those be separate operations

**Comment by weakphish** [comment]
@the-mikedavis would you mind assigning the issue to me? Thanks!

**Comment by the-mikedavis** [comment]
Could you add a comment to the issue you'd like to work on? GitHub only lets me assign members and issue participants (author or commenters)

**Comment by alexxbb** [comment]
I'd very much like to see this implemented in Helix. I use `:e .` in Vim all the time to quickly inspect different folder in my project.

**Comment by pascalkuthe** [comment]
Opening a directory with `:o` was implemented in  #2707. I don't think we will change the cwd so I will close this.
