### ISSUE TITLE
No warning when editing a readonly file

### ISSUE THREAD

**Issue by Visne** [helix-editor/helix#2627]
When opening a file you are not allowed to edit, no indication is given that this is the case. Also, when you start editing, there is no warning either. And then if you do `:wq`, Helix closes without issues. This means that you can think you have edited a file, without ever realizing that the file is readonly and nothing has changed.

Vim on the other hand has `[readonly]` in the bottom bar when opening the file, gives a red colored warning when starting editing, and when `:wq` is tried an error is shown and the editor remains open.

**Comment by the-mikedavis** [comment]
The `:wq` not failing: https://github.com/helix-editor/helix/issues/1575

A read-only indicator in the status-line would be a nice addition I think 👍
