### ISSUE TITLE
Fish shell completion errors

### ISSUE THREAD

**Issue by antoyo** [helix-editor/helix#2628]
### Summary

When typing `helix src/<TAB>` in the fish shell, it outputs the following error:
```
fish: Unknown command 'hx --health'
/usr/share/fish/vendor_completions.d/helix.fish (line 1):
hx --health |tail -n '+7' |awk '{print $1}' |sed 's/\x1b\[[0-9;]*m//g'
^
in command substitution
	called on line 4 of file /usr/share/fish/vendor_completions.d/helix.fish
from sourcing file /usr/share/fish/vendor_completions.d/helix.fish
in command substitution
/usr/share/fish/vendor_completions.d/helix.fish (line 4): Unknown command
set -l langs (hx --health |tail -n '+7' |awk '{print $1}' |sed 's/\x1b\[[0-9;]*m//g')
             ^
from sourcing file /usr/share/fish/vendor_completions.d/helix.fish
in command substitution
```

### Reproduction Steps

I tried this:

1. `helix src/<TAB>`

I expected this to happen:

It should complete normally.

Instead, this happened:

It output the error posted above.

### Helix log

Nothing.

### Platform

Linux

### Terminal Emulator

Alacritty 0.10.1

### Helix Version

22.05

**Comment by sudormrfbin** [comment]
I suppose you installed helix from the Arch repos which has the binary named as `helix` instead of `hx` because of name collisions. The completion script uses the original binary name of `hx` while it's been installed as `helix` by your package manager.

**Comment by antoyo** [comment]
Indeed. What would be the solution to this problem?

**Comment by the-mikedavis** [comment]
I think the arch package should be renaming `hx`->`helix` in the completion files since it's renaming the binary

**Comment by archseer** [comment]
\cc @orhun
