### ISSUE TITLE
Statusline text should use ui.statusline fg color

### ISSUE THREAD

**Issue by DrZingo** [helix-editor/helix#263]
The statusline text is now colored with ui.text and ui.text.focus. It should probably use ui.statusline fg (bg works, fg does nothing now) for inactive, and ui.text.focus fg for active window.

### Reproduction steps
Open a file
Split v/h
Active statusline is now colored with ui.text.focus (fg). Inactive statusline is colored with ui.text (fg)

### Environment
Arch linux
hx --version: helix 0.2.0

![image](https://user-images.githubusercontent.com/6590732/121939109-e8179400-cd4c-11eb-8800-d429a23eafe6.png)

**Comment by sudormrfbin** [comment]
I think introducing a new attribute like `ui.statusline.inactive` paired with proper application of `ui.statusline` would enable granular and explicit configuration of the colors (I grappled with the active and inactive statusline colors for some time trying to add the onedark theme).
