### ISSUE TITLE
Syntax highlighting bug in JSDoc comments

### ISSUE THREAD

**Issue by aral** [helix-editor/helix#2648]
### Summary

The syntax highlighting in JSDoc comments messes up after an `@param` declaration.

![image](https://user-images.githubusercontent.com/41798/171630614-b57f05cb-a4a9-44ff-aad7-93194d9a15dd.png)

### Reproduction Steps

n/a (just create a JSDoc comment).

### Helix log

n/a

### Platform

Linux (Fedora Silverblue 36)

### Terminal Emulator

GNOME Console

### Helix Version

helix 22.05 (fc8c4883)

**Comment by the-mikedavis** [comment]
Actually I'm not sure where jsdoc highlights are currently coming from in general - we might be falling back to tree-sitter-comment. We should be able to pull in https://github.com/tree-sitter/tree-sitter-jsdoc to improve them. We already have the injection for it: https://github.com/helix-editor/helix/blob/4f3d0a77064aac18cc4386df5c43c312c3b03f69/runtime/queries/javascript/injections.scm#L25-L28

**Comment by sudormrfbin** [comment]
Closed by #2650.
