### ISSUE TITLE
Command to view full LSP documentation for item under cursor.

### ISSUE THREAD

**Issue by n0s4** [helix-editor/helix#2662]
`space-k` is pretty helpful when editing, but it is limited to how much of the documentation can fit on screen:

![hx-cutting-doc](https://user-images.githubusercontent.com/96927121/171879216-8c1d8a6f-2727-41d3-8079-13a75f64dda8.png)

As you can see, the `examples` section is chopped off. This isn't an issue as you just want a brief description but is annoying when you have to go and find documentation elsewhere or `gd` into some other source code to read the doc comments (at least in rust's case), which doesn't offer the markdown highlighting. 

What I had in mind is a seperate command (`space-K`?) that grabs the full documentation and opens a new scratch buffer with markdown highlighting so you can look through it.

**Comment by the-mikedavis** [comment]
`C-d` and `C-u` can be used to scroll in the popup so you can see the full docs when they're long

Opening up a (read-only?) scratch buffer to view the markdown in full could be kinda handy though - it might be nice to have a full buffer for a particularly long piece of documentation. On the other hand, you can usually goto-definition and read the inline docs if they exist

**Comment by n0s4** [comment]
Wow, that's great. I don't like going to read inline docs very much, it's harder to read and takes a minute to go up to the start of the docs. I don't really need to have that proposal anymore so I'll close this.

**Comment by CyberFlaw** [comment]
Hey, guys, the solution works great on `space+k`, but however, I'm trying to do the same in `<C+x>` autocomplete. Whenever I press `Tab`, I can find a section of docs, but I'm unable to scroll or collapse the menu.

![lsp issue](https://user-images.githubusercontent.com/53346567/214920361-5b3ebb58-3990-4db3-8a43-f30082eb9733.png)

So I'm curious if are there any ways to scroll through the definition.
