### ISSUE TITLE
Repeating `miwc` acts as simple change `c`

### ISSUE THREAD

**Issue by edio** [helix-editor/helix#2667]
### Summary

`miwc<input>` replaces a word surrounding the cursor with user's input.

Using repeat action (`.`) should be equivalent to the same `miwc` sequence. However `.` is equivalent to `c<input>` instead

### Reproduction Steps

I tried this:

1. put the cursor an a word
```
the word
     ^
```
2. in `NOR` mode `miwcbird`, observe
```
the bird
```

3. move the cursor a different word
```
the bird
 ^
```
4. press `.`

I expected this to happen:
```
bird bird
```

Instead, this happened:
```
tbirde bird
```

### Platform

Linux

### Terminal Emulator

konsole

### Helix Version

helix 22.05 (27609f50)

**Comment by n0s4** [comment]
I don't think this is a bug. `.` repeats last *action* (`c`). `A-.` repeats last selection (`miw`). 

Maybe we could consider mapping `.` to repeat last selection and action? That would mean we would have to choose between repeating selection or action as the default for `A-.` and also what to bind to the other one (maybe `C-. `?) so I'm not sure that would even be worth it.

**Comment by edio** [comment]
Ugh, I expected the behavior of vim. Apologies for the confusion.

I guess this could be moved to the keybindings discussion then. Feel free to close please.
