### ISSUE TITLE
Can't seem to get themes working properly.

### ISSUE THREAD

**Issue by amoghyermalkar123** [helix-editor/helix#2671]
This is my theme file in `~/.config/helix/themes/bogster.toml`

```
"ui.background" = { fg = "foreground", bg = "background" }
"ui.cursor" =  { fg = "background", bg = "orange", modifiers = ["dim"] }
"ui.cursor.match" = { fg = "green", modifiers = ["underlined"] }
"ui.cursor.primary" = { fg = "background", bg = "cyan", modifier = ["dim"] }
"ui.help" = { fg = "foreground", bg = "background_dark" }
"ui.linenr" = { fg = "comment" }
"ui.linenr.selected" = { fg = "foreground" }
"ui.menu" = { fg = "foreground", bg = "background_dark" }
"ui.menu.selected" = { fg = "cyan", bg = "background_dark" }
"ui.popup" = { fg = "foreground", bg = "background_dark" }
"ui.selection" = { bg = "secondary_highlight" }
"ui.selection.primary" = { bg = "primary_highlight" }
"ui.statusline" = { fg = "foreground", bg = "background_dark" }
"ui.statusline.inactive" = { fg = "comment", bg = "background_dark" }
"ui.text" = { fg = "foreground" }
"ui.text.focus" = { fg = "cyan" }
"ui.window" = { fg = "foreground" }
"ui.virtual" = { fg = "comment" }

"error" = { fg = "red" }
"warning" = { fg = "cyan" }

"markup.heading" = { fg = "purple", modifiers = ["bold"] }
"markup.list" = "cyan"
"markup.bold" = { fg = "orange", modifiers = ["bold"] }
"markup.italic" = { fg = "yellow", modifiers = ["italic"] }
"markup.link.url" = "cyan"
"markup.link.text" = "pink"
"markup.quote" = { fg = "yellow", modifiers = ["italic"] }
"markup.raw" = { fg = "foreground" }

[palette]
background = "#282a36"
background_dark = "#21222c"
primary_highlight = "#800049"
secondary_highlight = "#4d4f66"
foreground = "#f8f8f2"
comment = "#6272a4"
red = "#ff5555"
orange = "#ffb86c"
yellow = "#f1fa8c"
green = "#50fa7b"
purple = "#bd93f9"
cyan = "#8be9fd"
pink = "#ff79c6"
```

When I use this theme, all I can see is the background color changing. There is no syntax highlighting. Am I missing something here?

**Comment by n0s4** [comment]
You've missed out all the syntax related scopes. Refer to https://docs.helix-editor.com/themes.html#syntax-highlighting

**Comment by amoghyermalkar123** [comment]
Hey, I've updated the config file to include this as well - 
```
"comment" = { fg = "comment" }
"constant" = { fg = "purple" }
"constant.character.escape" = { fg = "pink" }
"function" = { fg = "green" }
"keyword" = { fg = "pink" }
"operator" = { fg = "pink" }
"punctuation" = { fg = "foreground" }
"string" = { fg = "yellow" }
"string.regexp" = { fg = "red" }
"tag" = { fg = "pink" }
"type" = { fg = "cyan", modifiers = ["italic"] }
"type.enum.variant" = { fg = "foreground", modifiers = ["italic"] }
"variable" = { fg = "foreground" }
"variable.builtin" = { fg = "cyan", modifiers = ["italic"] }
"variable.parameter" = { fg ="orange", modifiers = ["italic"] }

"diff.plus" = { fg = "green" }
"diff.delta" = { fg = "orange" }
"diff.minus" = { fg = "red" }
```
But still does not seem to work.

**Comment by n0s4** [comment]
And it is working with other included themes?

**Comment by amoghyermalkar123** [comment]
None of the themes I've tried have worked, all of the basically change the background color

**Comment by amoghyermalkar123** [comment]
For now, this is what the file looks like, (you can see somethings being highlighted, though they are not consistent)
![Screenshot from 2022-06-04 17-11-03](https://user-images.githubusercontent.com/24986018/171997413-9c348683-bb55-45cd-b5c5-bc4eb37b6f5b.png)

**Comment by n0s4** [comment]
Have you ran `hx --grammar fetch` and `hx --grammar build`? Also if you have built from source you need to copy/symlink the `runtime` dir in the repo to your config location: `cp path/to/helix/runtime ~/.config/helix/`

**Comment by n0s4** [comment]
> For now, this is what the file looks like, (you can see somethings being highlighted, though they are not consistent)
> 
> 

Those highlights are Lsp diagnostics I think. Hovering them should show you a message in the top right.

**Comment by amoghyermalkar123** [comment]
Hey! thanks alot!! It's working after I copied the runtime dir in the mentioned folder. Had missed out on that :)
Closing issue, thanks again!

PS - after struggling alot with vim, i found helix just at the right time. Even without all the fancy colors i just got working, i was having a pleasant time using helix.
