### ISSUE TITLE
Helix changes terminal cursor style

### ISSUE THREAD

**Issue by GandelXIV** [helix-editor/helix#2684]
### Summary

After quitting helix my terminal cursor changes from `Beam` (my default) to `Block` (helix default). I had the same issue of vim but i fixed it by adding `set guicursor=` to my `.vimrc`. However, i could not find a way to do that in helix.

### Reproduction Steps

1. Open helix
2. Exit
3. Cursor style has changed

### Platform

Linux

### Terminal Emulator

Alacritty

### Helix Version

helix 22.05

**Comment by DivergentClouds** [comment]
I found the [problem line](https://github.com/helix-editor/helix/blob/55b45ec4a4cb958b241a93cc7c3f4e499379890e/helix-term/src/application.rs#L791).

The escape code written to the terminal to reset the cursor (`\x1B[2 q` ) instead sets the cursor to be a static block. 

[The specification](https://invisible-island.net/xterm/ctlseqs/ctlseqs.html#h3-Functions-using-CSI-_-ordered-by-the-final-character_s_) defines the cursor set sequence as follows:

```
CSI Ps SP q
          Set cursor style (DECSCUSR), VT520.
            Ps = 0  ⇒  blinking block.
            Ps = 1  ⇒  blinking block (default).
            Ps = 2  ⇒  steady block.
            Ps = 3  ⇒  blinking underline.
            Ps = 4  ⇒  steady underline.
            Ps = 5  ⇒  blinking bar, xterm.
            Ps = 6  ⇒  steady bar, xterm.
```

`CSI` is `ESC [`.
`SP` is space.

The simplest solution is probably to get the terminfo on program start and restore it on program end. I'd submit a PR but I don't know Rust.

**Comment by archseer** [comment]
Leaving this open since we'll probably be adding terminfo soon (@sudormrfbin needs it in another PR)
