### ISSUE TITLE
Implement soft and hard line breaks in markdown rendering

### ISSUE THREAD

**Issue by Frojdholm** [helix-editor/helix#2686]
While this was noticed in the info box I think this is a general problem with the markdown rendering. Currently when rendering markdown soft and hard line breaks (`Event::SoftBreak` and `Event::HardBreak`) are converted to single spaces. This causes problems in for example the python argparse documentation where the list of arguments is not recognized as a markdown list.

![python-list](https://user-images.githubusercontent.com/3251566/172249219-c5ac0993-e296-40cc-91e9-34fc872f44e2.png)

By implementing soft and hard line breaks (#2687) we can get something that is much easier to read.

![python-list-fixed](https://user-images.githubusercontent.com/3251566/172249361-5eb0b39d-38a4-4436-87b5-b351b0184bf1.png)

I think this might be the problem in #808 as well. Code that would deal with the soft/hard breaks have been commented out since `helix-term/src/ui/markdown.rs` was created so maybe I'm unaware of some issue with doing this.

**Comment by archseer** [comment]
This is the same as https://github.com/helix-editor/helix/issues/808 yep
