### ISSUE TITLE
Question: why helix keep (neo)vim command style 

### ISSUE THREAD

**Issue by y1rn** [helix-editor/helix#2696]
as subject, why not use vscode  like popup command input, any command can easy to reach with fuzzy search.

I'm vscode user and interesting in terminal IDE

**Comment by premell** [comment]
Hmm this is actually a quite good idea, however I think it would be more of an alternative to the regular command prompt. But I do think its a very good addition. 

For work I use netbrains Rider and they also have a fuzzy searches that pretty much searches through everything. It can take you to files in your project, editor settings and commands. So you can type eg "colorscheme", "keybindings" or "plugins" to go to the relevant settings or you can type "split" and get alternatives how to split the window. 

Here are some images for reference/inspiration

![image](https://user-images.githubusercontent.com/65544203/172312285-3fc155e2-7b99-492a-8501-2e94b09b0bf1.png)

![image](https://user-images.githubusercontent.com/65544203/172312038-1a089190-f224-4baf-9dd7-692f63044e69.png)

![image](https://user-images.githubusercontent.com/65544203/172311990-45db227c-d749-4e23-a1a3-b5bc9a257530.png)

![image](https://user-images.githubusercontent.com/65544203/172311925-b8f2ab49-3906-403b-8ff4-f341695069ca.png)


Now you'd have to think how you'd want to have in the menu, but I definitely think that fuzzy finding commands would be a godsend

**Comment by y1rn** [comment]
> Isn't this pretty much what the command picker does? ( Space ? )
> 
> ![image](https://user-images.githubusercontent.com/3957610/172341348-d5929bae-b1d1-4849-a198-d6c77408e6f0.png)
> 
> Files and symbols are not reachable from it, but I actually prefer it that way. Having separate pickers narrows down the search quite a bit. (i.e. if I'm looking for a file, I don't need to see symbols or commands)

how about prefixed with ```>``` as command mode .  vscode popup input support ```>``` ```:``` ```@``` ```#```  and each one can be entry by single short cut. I feel that's great, many functionality integrate into one input, keep similar user experience.

**Comment by y1rn** [comment]
> Maybe this would be a good fit for a plugin in the future?

hope helix provide can good layout and user experience on base functionality.
