### ISSUE TITLE
Clicking past the end of a line triggers yank

### ISSUE THREAD

**Issue by CptPotato** [helix-editor/helix#2699]
### Summary

When clicking past the end of a line, helix yanks the text as if I clicked and dragged.

This also seems to happen when clicking other positions in the terminal, such as the gutter (although in that case the cursor position remains unchanged). I suspect that this happens whenever a click doesn't land on a character from the document.

### Reproduction Steps

- open helix
- click anywhere on the first line or the status line
  - helix reports: `yanked main selection to system clipboard`

### Helix log

Nothing helpful is logged

### Platform

Windows

### Terminal Emulator

wezterm, cmd, powershell

### Helix Version

helix 22.05 (built from master `4a27e2d9`)

**Comment by the-mikedavis** [comment]
I haven't tested it out yet but I bet it's this block: https://github.com/helix-editor/helix/blob/e0532771cc3503afcbfb5cd5d45b8c57462587f9/helix-term/src/ui/editor.rs#L1086-L1104
