### ISSUE TITLE
Show stderr when `:sh` command fails

### ISSUE THREAD

**Issue by joegm** [helix-editor/helix#2700]
If I try to, say, `cargo run` in helix and the command fails I am not given any description why. Why can't helix show the stderr output in the same way as it shows stdout when the command succeeds?

Could we also make it possible to show stderr when the command does not fail? `cargo check` for instance prints its output to stderr so is not accessible from inside Helix.

**Comment by the-mikedavis** [comment]
It looks like the stderr is not totally discarded, just kicked out to the log file: https://github.com/helix-editor/helix/blob/4a27e2d93846f3b66ab0dc225e65d2fb869463f3/helix-term/src/commands.rs#L4381-L4383. I'm not sure there's a good way to display it in the UI currently: it could be put in-line with the stdout input styled red but that wouldn't be a trivial change looking at how `run_shell_command` and `shell_impl` are implemented.

In general I think a dedicated terminal would fit this workflow better, either through tmux/screen/zellij or #1976. There are some cases where you will want to see the full error message of `cargo check` for some extended time, or run a long-running command async that fit better in a terminal pane than in a popup within helix.

**Comment by i3elj** [comment]
A horizontal split with a scratch buffer similar to what log does could be a good approach
