### ISSUE TITLE
Improve match argument

### ISSUE THREAD

**Issue by otavioschwanck** [helix-editor/helix#2701]
Some cases, the argument doesn't works.

Example:

on TSX:

```typescript
<Component value={123} />
```

The `value={123}` should be an argument.

On a function:

```javascript
function myFunc(argA, argB) {}
```

`arg A` and `, argB` should be an argument.

On ruby the same.

In ruby, we have some parameters like:

validates :name, presence: true

`:name` and `, presence: true` should be arguments.

**Comment by the-mikedavis** [comment]
Are you referring to the argument/parameter textobjects? https://docs.helix-editor.com/usage.html#textobjects

Some languages like tsx don't have a `textobjects.scm` tree-sitter query file yet. Other languages like ruby [have one](https://github.com/helix-editor/helix/blob/4a27e2d93846f3b66ab0dc225e65d2fb869463f3/runtime/queries/ruby/textobjects.scm) but it could be expanded. For example:

```scm
(argument_list (_) @parameter.inside)
```

could be added to capture `:name` and `presence: true` as arguments. There are some docs on textobjects queries [here](https://docs.helix-editor.com/guides/textobject.html).

A PR to improve the textobject queries for any language would definitely be welcome!

**Comment by kirawi** [comment]
Closing as this is a broad issue and relatively difficult to search for.
