### ISSUE TITLE
catppuccin theme is mispelled

### ISSUE THREAD

**Issue by its-danny** [helix-editor/helix#2712]
The theme in helix is called [catpucin](https://github.com/helix-editor/helix/blob/master/runtime/themes/catpuccin.toml), which should be [catppuccin](https://github.com/catppuccin/catppuccin). Both because that's the name, but also the [wiki link](https://github.com/helix-editor/helix/wiki/Themes#catppuccin) is broken since it tries to link to the correct name.

**Comment by sudormrfbin** [comment]
A PR to rename the theme file would be welcome!

**Comment by its-danny** [comment]
@sudormrfbin will do, just like opening issues before creating random PRs.
