### ISSUE TITLE
Hitting `A-o` stacks up "deselects" even though there is nothing more to select.

### ISSUE THREAD

**Issue by helmesjo** [helix-editor/helix#2714]
### Summary

Hitting `A-o` stacks up "deselects" even though there is nothing more to select.

### Reproduction Steps
1. Open a file.
2. Keep hitting A-o until whole file selected.
3. At this moment, as many times as you keep hitting A-o (everything is already selected, so nothing happens visually), the same amount of times you need to hit A-i to "undo" it before you start seeing things deselect (it basically buffers up, even though there is nothing else to select).

### Helix log

<details><summary>~/.cache/helix/helix.log</summary>

It generates no log output.

</details>

### Platform

Linux

### Terminal Emulator

Alacritty

### Helix Version

20.05

**Comment by the-mikedavis** [comment]
This should be a small fix: we just need to check if `current_selection` is the `.last()` of the `view.object_selections` vector, and if it is, don't `.push` the `current_selection`

https://github.com/helix-editor/helix/blob/567e71fbbcc047119675691a05e7c16b865e8be1/helix-term/src/commands.rs#L3774-L3775
