### ISSUE TITLE
Any good tutorial

### ISSUE THREAD

**Issue by iamgabrielsoft** [helix-editor/helix#2726]
is there a comprehensive tutorial on how to use the vim editor?

i had issue while saving my rust file, is there is any please help out

**Comment by n0s4** [comment]
The vim editor? This is not vim, did you mean to say helix?

If so, `hx --tutor` or `:tutor` from inside the editor opens a tutor document. It's not exactly comprehensive but it gives you a good starting point. Also look to [the docs](https://docs.helix-editor.com/keymap.html) for reference.

**Comment by iamgabrielsoft** [comment]
yeah thanks, i meant helix.

Am using ubuntu with current version and this does not work, instead i open a tutor file when i run the command

**Comment by n0s4** [comment]
Yes its meant to open the tutor file, it's a text based tutorial inspired  by vimtutor. As for the debugger you either don't have it installed or its not in your $PATH.
