### ISSUE TITLE
rust-analyzer doesn't work, fails to load workspace

### ISSUE THREAD

**Issue by vvzen** [helix-editor/helix#2732]
### Summary

I am working a project that has got lots of different programming languages in it.

What's below is a simplification, but it's a basically a fully dockerized suite of services, so there's bash files, Dockerfiles, some python, etc..
```bash
.
├── ci-scripts
│   ├── before_script.sh
│   └── deploy_images.sh
├── docker-compose.yml
└── workers
    ├── python
    │   └── example_consumer.py
    └── rust
        └── rabbitmq-consumer
            ├── Cargo.lock
            ├── Cargo.toml
            └── src
                └── main.rs
```

I am running helix by `cd`ing all the way to `rabbitmq-consumer`, and then running `hx src/main.rs`.

Sadly, despite the health check passing fine for rust, I'm getting no help/errors/etc. when typing in a Rust source file.
I have installed `rust-analyzer` in a different place, since in working environment and I need this dev setup to work across multiple machines. `/job/comms/pipeline/dev/myuser/opt/bin/` is in my `PATH`.
```bash
hx --health rust
Configured language server: rust-analyzer
Binary for language server: /job/comms/pipeline/dev/myuser/opt/bin/rust-analyzer
Configured debug adapter: lldb-vscode
Binary for debug adapter: Not found in $PATH
Highlight queries: ✔
Textobject queries: ✔
Indent queries: ✔
```

### Reproduction Steps

 

I tried this:

1. `hx src/main.rs`

I expected this to happen: the `rust-analyzer` worked and helped me with error reporting while typing in helix.

Instead, this happened: nothing

### Helix log

If I look at `~/.cache/helix/helix.log`, I see:

<details><summary>~/.cache/helix/helix.log</summary>

```bash
2022-06-09T22:56:09.689 helix_lsp::transport [ERROR] err <- "[ERROR rust_analyzer::lsp_utils] rust-analyzer failed to load workspace: Failed to read json file /net/rust-project.json: No such file or directory (os error 2)\n"
2022-06-09T22:56:09.689 helix_lsp::transport [ERROR] err <- "\n"
2022-06-09T22:56:09.689 helix_term::application [WARN] unhandled window/showMessage: ShowMessageParams { typ: Error, message: "rust-analyzer failed to load workspace: Failed to read json file /net/rust-project.json: No such file or directory (os error 2)\n" }
```

</details>

I am not sure why it's looking for a `rust-project.json` file in `/net/`. In my case,`/net/` is a storage mount (using autofs) where my home folder is mounted (`/net/homes`).

### Platform

CentOS Linux release 7.9.2009 (Core)

### Terminal Emulator

iterm2 - but I'm ssh-ing to another machine

### Helix Version

helix 22.05

**Comment by sbromberger** [comment]
I've gone through the helix codebase and there's no string matching `rust-project` anywhere. Are you sure there's not something external  (environment variable, config file, alias, ...) influencing your `rust-analyzer`?

**Comment by sbromberger** [comment]
Ah, looking [here](https://rust-analyzer.github.io/manual.html#configuration), it appears that this is a rust-analyzer config option. Perhaps this will help:

> There are three ways to feed rust-project.json to rust-analyzer:
>
> Place rust-project.json file at the root of the project, and rust-analyzer will discover it.
>
> Specify "rust-analyzer.linkedProjects": [ "path/to/rust-project.json" ] in the settings (and make sure that your LSP client sends settings as a part of initialize request).
>
> Specify "rust-analyzer.linkedProjects": [ { "roots": […​], "crates": […​] }] inline.

**Comment by gabydd** [comment]
this issue is also fixed by https://github.com/helix-editor/helix/pull/5748

you can make a ``.helix/config.toml`` in the repo and set ``editor.workspace-lsp-roots = ["workers/rust/rabbitmq-consumer"]`` for helix to give ``rust-analyzer`` the correct root
