### ISSUE TITLE
rust-analyzer reports only syntax error.

### ISSUE THREAD

**Issue by hzb-ykpcx** [helix-editor/helix#2734]
<img width="1136" alt="Screen Shot 2022-06-10 at 13 21 16" src="https://user-images.githubusercontent.com/52552971/172996007-d7c17dd1-1bb8-4bcd-8b2a-ee6b83119515.png">
it will only report syntax error as the picture shows. When I open the file, the red errors signs in line 2 and line 3 appear for 1 second and then disappear, and meanwhile there seems to be a loading logo in the lower left corner. See the video below.

https://user-images.githubusercontent.com/52552971/172997535-ad817385-75f0-4a32-8914-26ac8312ea74.mov

.

**Comment by kirawi** [comment]
This might just be how `rust-analyzer` works, where it fails on syntax first so gives up on evaluating further.

**Comment by hzb-ykpcx** [comment]
> This might just be how `rust-analyzer` works, where it fails on syntax first so gives up on evaluating further.
No, if there are no syntax errors, there are no errors reported.

**Comment by archseer** [comment]
We show whatever errors rust-analyzer reports. Might be better to open this issue upstream
