### ISSUE TITLE
Feature Request: Sticky Header Mode

### ISSUE THREAD

**Issue by heliostatic** [helix-editor/helix#2740]
Just saw this in XCode 14. Interesting way to show code structure.

https://twitter.com/a_grebenyuk/status/1534359760308424711

https://user-images.githubusercontent.com/70898/173101256-11d2ee02-070e-4f46-b93a-f9b9244797ed.mp4

**Comment by heliostatic** [comment]
Ah indeed @the-mikedavis , nvim has a plug for this using tree-sitter contexts: https://github.com/nvim-treesitter/nvim-treesitter-context

**Comment by archseer** [comment]
Duplicate of https://github.com/helix-editor/helix/issues/396 ?
