### ISSUE TITLE
Outputting Terminal Color Codes to stdin on exit

### ISSUE THREAD

**Issue by canadiannomad** [helix-editor/helix#2742]
### Summary

When I load a file in helix, and exit, sometimes helix will pause for 4-5 seconds at the ":w
This isn't consistent, but certainly happens frequently for me.
I'm on a MacBook Air 12.3.1 using iTerm2 .. I built helix from master with rustc 1.63.0-nightly
This has happened on earlier versions as well.

### Reproduction Steps

1. `hx file.rs`
2. Make change
3. `:wq<enter>`
<img width="638" alt="Screen Shot 2022-06-10 at 14 31 23" src="https://user-images.githubusercontent.com/236513/173140717-e274ae3a-5295-451f-b959-72281ab8c383.png">
4. Wait 4-5 seconds... (correction 21+ seconds)
<img width="638" alt="Screen Shot 2022-06-10 at 14 31 23" src="https://user-images.githubusercontent.com/236513/173140717-e274ae3a-5295-451f-b959-72281ab8c383.png">
5. Screen finally clears and bell sounds and can see
(Different every time)
<img width="215" alt="Screen Shot 2022-06-10 at 14 47 57" src="https://user-images.githubusercontent.com/236513/173140820-241ace1b-6826-4487-afa8-de163cb286af.png">
<img width="1280" alt="Screen Shot 2022-06-10 at 14 35 32" src="https://user-images.githubusercontent.com/236513/173140824-f9943217-2b70-4d04-b869-86a5000f5083.png">
or something similar in the terminal sitting at the bash prompt.

### Helix log
[helix.txt](https://github.com/helix-editor/helix/files/8881992/helix.txt)

### Platform

macOS 12.3.1

### Terminal Emulator

iTerm2 Build 3.5.0beta5

### Helix Version

helix 22.05 (fc666db6)

**Comment by canadiannomad** [comment]
Correction, sometimes it sits there waiting to exit for 21+ seconds on an empty file... When it does decide to wait, at all, then is always outputs those character codes.

**Comment by the-mikedavis** [comment]
I think this is https://github.com/helix-editor/helix/issues/2059 but I haven't seen the terminal code part before.

**Comment by anzhi0708** [comment]
> I think this is #2059 but I haven't seen the terminal code part before.

:3 Hi, 2059 author here, I confirm this issue

**Comment by dead10ck** [comment]
This is probably a combination of #2059 and #2863. The latter was fixed in #4081 and the former is a duplicate, so I'm going to close this. Feel free to say if you disagree.
