### ISSUE TITLE
Bar cursor-shape does not propagate to all selections in multicursor environment

### ISSUE THREAD

**Issue by Ryneqq** [helix-editor/helix#2744]
### Summary

As in title, i like to use bar cursor shape for insert mode but for multicursor only main selection has this property applied. I also checked and set as bar for normal mode also produce same behavior. 

### Reproduction Steps

* set this configuration
[editor.cursor-shape]
insert = "bar"
normal = "bar"

* Open non empty file
* Select multiple words with `%,s,<word>,"ret"`  You can also press `i` to enter insert mode

### Helix log

Non breaking

### Platform

Linux

### Terminal Emulator

Alacritty

### Helix Version

helix 22.05 (370a16d0)

**Comment by n0s4** [comment]
I believe this is because you cannot actually have multiple cursors in a terminal, Helix simulates it by changing the styling of the characters under the other cursors.

**Comment by Ryneqq** [comment]
I am not TUI expert, do you think is it possible to render different style selection according to different cursor-shape options?

**Comment by n0s4** [comment]
AFAIK you can't render a bar or underline cursor that'd look decent with just terminal styling. You could try to do something with Unicode characters but it would look hacky. It's just a limitation of terminals that you might have to get used to. On the upside it does make it clearer which is the primary selection :sweat_smile:. Perhaps someone with more knowledge could come up with a workaround.

**Comment by archseer** [comment]
This is a terminal limitation so there's nothing we can do here
