### ISSUE TITLE
support binary file reads.

### ISSUE THREAD

**Issue by LollipopFt** [helix-editor/helix#2748]
#### Describe your feature request
currently, helix does not support reading of binary files such as `.exe` and `.ch8`. the only editor i know which does this is sublime text (sorry for the comparison), but i do want functionality like `hexdump`. thank you!

**Comment by LollipopFt** [comment]
looks like #1306, i would definitely want this. should i close this issue?

**Comment by the-mikedavis** [comment]
Yeah let's close this in favor of #1306
