### ISSUE TITLE
JSON language server command is wrong

### ISSUE THREAD

**Issue by tytouf** [helix-editor/helix#2761]
### Summary

I believe the default JSON language server is wrong. File languages.toml defines the command as "vscode-json-language-server" while the npm is named vscode-json-languageserver.

By changing the command to the correct executable, I get notified of syntax errors as expected when editing a JSON file.

### Reproduction Steps

 

I tried this:

1. `hx --health`

I expected this to happen:
json                               ✔ vscode-json-languageserver       None                               ✔                                  ✘                                  ✔                                  

Instead, this happened:
json                               ✘ vscode-json-language-server       None                               ✔                                  ✘                                  ✔                                  

### Helix log

<details><summary>~/.cache/helix/helix.log</summary>

```
please provide a copy of `~/.cache/helix/helix.log` here if possible, you may need to redact some of the lines
```

</details>

### Platform

Linux

### Terminal Emulator

gnome-terminal

### Helix Version

helix 22.05 (d7bd4416)

**Comment by the-mikedavis** [comment]
See https://github.com/helix-editor/helix/pull/2749

**Comment by tytouf** [comment]
Oops, did try to look for previous issues but must have kept the is:open tag. Sorry for the noise.
