### ISSUE TITLE
format command is not working with JSON 

### ISSUE THREAD

**Issue by tytouf** [helix-editor/helix#2762]
### Summary

After fixing the language server command for JSON, syntax errors are correctly showed but formatting and auto-format is not working even though the languages.toml file defined the config object with "provideFormatter" as true.

### Reproduction Steps

 

I tried this:

1. `hx a_json_file.json`

[a_json_file.json.log](https://github.com/helix-editor/helix/files/8894793/a_json_file.json.log)

I expected this to happen:

on command :format or file save, the file would be automatically formatted, with a new line added after the first brace, indentation of the object property and new line before the last brace.

Instead, this happened:

Nothing happened.

### Helix log

<details><summary>~/.cache/helix/helix.log</summary>

```
please provide a copy of `~/.cache/helix/helix.log` here if possible, you may need to redact some of the lines
```

</details>

### Platform

Linux

### Terminal Emulator

gnome-terminal

### Helix Version

helix 22.05 (d7bd4416)

**Comment by the-mikedavis** [comment]
Formatting works for me out-of-the-box with `vscode-json-language-server` installed (from the extracted package https://github.com/helix-editor/helix/wiki/How-to-install-the-default-language-servers#jsonls). Can you give that a try? If that doesn't work, be sure to run in verbose mode (`hx -vv file.json`) and post the log https://github.com/helix-editor/helix/wiki/FAQ#access-the-log-file so we can see the communication between helix and the language server

**Comment by tytouf** [comment]
I confirmed it works fine with language server from "npm i vscode-langservers-extracted"

**Comment by tytouf** [comment]
Thanks, sorry for the trouble.

**Comment by MossabDiae** [comment]
Sorry to revive an old thread but this is an important note in case someone landed here in the future:
If the `format` command is still not working even after you install the language server via `npm install -g vscode-langservers-extracted` make sure to **run Helix with file name** included, that is:

- `helix` -> past JSON -> `set-language json` -> `format` : **this will not work ❌**.
- `helix temp.json` -> past JSON -> `format` : **this will work ✅**

I'm observing this in `helix 23.03`
