### ISSUE TITLE
Panic when current directory is in a network share that gets disconnected

### ISSUE THREAD

**Issue by danielkeller** [helix-editor/helix#2765]
### Summary

I had helix open with its working directory in a network share. The share disconnected, and Helix panicked with the message
```
thread 'main' panicked at 'couldn't determine current directory: Os { code: 107, kind: NotConnected, message:
"Transport endpoint is not connected" }', helix-core/src/path.rs:86:45
```
This is sort of inconvenient because my network share times out automatically and then I lose my windows.

### Helix log

```
[nothing interesting in here]
```

### Platform

Debian Linux

### Terminal Emulator

Tilix 1.9.4

### Helix Version

22.05-53-ga766b32e

**Comment by the-mikedavis** [comment]
This falls under https://github.com/helix-editor/helix/issues/2527, let's close in favor of that issue
