### ISSUE TITLE
Support for qml

### ISSUE THREAD

**Issue by vvzen** [helix-editor/helix#2771]
```bash
$ hx --health qml
Language 'qml' not found
```

As always, thanks for this awesome project. I truly mean it since it has changed the way I work! :D

It would be amazing if we had support for highlighting qml files inside Helix. QtQml (https://doc.qt.io/qt-6/qtqml-documents-topic.html) is a nice framework by Qt that allows for building UIs using (mostly) a declarative approach. The .qml files hosts the description of the UI, with a little bit of logic tied only to the UX/UI side of things.

Is this something that would be easy to add?
According to this: https://bugreports.qt.io/browse/QTBUG-68406, QtQml now offers a language server (`qmlls`) 

I'd be happy to take a stab at it, in my free time, if that helps.
Thanks!

Valerio

**Comment by the-mikedavis** [comment]
The main thing for adding support is finding a good tree-sitter grammar if one exists (sometimes there isn't one and you'd need to write it yourself 😬)

For QML I see:

* https://github.com/rschiang/tree-sitter-qml
* https://github.com/yuja/tree-sitter-qmljs
* https://github.com/otherJL0/tree-sitter-qml
* https://github.com/rdpbecker/tree-sitter-qml

Of those, yuja's looks the most complete and it has some queries to get started with for highlights.

If you'd like, you can give this a try following https://docs.helix-editor.com/master/guides/adding_languages.html
