### ISSUE TITLE
Bookmarks to quickly visit code segments and files

### ISSUE THREAD

**Issue by marvinamari** [helix-editor/helix#2789]
The ability to create shortcuts between different parts of a code base you are actively working on, similar to the bookmarks feature of a Visual Studio, or Jetbrains IDE.

**Comment by the-mikedavis** [comment]
There's a similar feature implemented called the jumplist. You can save your selections to the jumplist with `C-s`, jump back with `C-o` and jump forward with `C-i`. Some operations like goto-definition automatically save to the jumplist. With a picker or tree for the jumplist #2664 you could effectively use it as a bookmark list. Does this cover the use-cases you're looking for?

**Comment by marvinamari** [comment]
Hi Mike!
I actually haven't seen the jump list in the docs, I will look it up. I think that should work for now so I will close this issue. Thank you so much!

**Comment by lukepighetti** [comment]
> There's a similar feature implemented called the jumplist. You can save your selections to the jumplist with `C-s`, jump back with `C-o` and jump forward with `C-i`. Some operations like goto-definition automatically save to the jumplist. With a picker or tree for the jumplist #2664 you could effectively use it as a bookmark list. Does this cover the use-cases you're looking for?

I don't think this is working quite as expected for the bookmark use case

Let's say you go

a.js -> b.js -> c.js -> d.js (save with `C-s`)
`C-o`, `C-o`, `C-o`, now you're back at a.js and your jumplist contains a.js, b.js, c.js, d.js

If you now jump to foo.js, your jumplist is a.js, foo.js

The file you 'saved' to the jumplist, d.js is gone
