### ISSUE TITLE
Delay on switching from Insert Mode to Normal Mode

### ISSUE THREAD

**Issue by transtrike** [helix-editor/helix#2795]
I'm not sure this is by design, but exiting from INS mode to NOR takes usually `upwards of a second`. 
That might not seem like a big deal, but when you have something quick to type and save it, pressing the ESC usually doesn't exit INS mode in time, if at all, and pairing it with quick combination of `<ESC>:wq` writes `:wq` to the file, rather then saving it and exiting. 
Furthermore, pressing `<ESC>` and then any key quickly afterwards seems to not register the `<ESC>` key at all. 
This happens 100% of the time and is quite annoying.

OS: Arch
Build command: `cargo compile -r; cargo install --path helix-term`
`hx --version` yields: `helix 22.05 (3bd55455)`

**Comment by kirawi** [comment]
https://github.com/helix-editor/helix/wiki/Troubleshooting#when-using-tmux-or-screen-there-is-a-delay-after-hitting-escape-before-its-registered

**Comment by transtrike** [comment]
Thanks. Removing the `<ESC>` key sequence from tmux resolved the issue.
