### ISSUE TITLE
Bitwise leftshift assignment operator not syntax highlighted in Rust

### ISSUE THREAD

**Issue by LollipopFt** [helix-editor/helix#2804]
### Summary

![image](https://user-images.githubusercontent.com/62802897/174443996-8143ccf5-957d-4cec-a32f-35a8b7e65190.png)
as can be seen in my code, `>>=` (top right) is highlighted correctly, but `<<=` (bottom right) is not. that's all, thanks.

### Platform

Windows

### Terminal Emulator

Windows Terminal Preview 1.14.1451.0

### Helix Version

helix 22.05 (27609f50)

**Comment by sudormrfbin** [comment]
Seems like a slip up in the query file:

https://github.com/helix-editor/helix/blob/7983c71752e2443266ecc65581f3a980696cc294/runtime/queries/rust/highlights.scm#L312-L314

Only `>>=` is in the list of operators; adding `<<=` should fix the issue.
