### ISSUE TITLE
'Docs for symbol' on the closing parenthesis shows last argument instead of function docs

### ISSUE THREAD

**Issue by Houkime** [helix-editor/helix#2810]
#### Expected: 
`space+k` opening the function doc popup when cursor is on function call parentheses or inside them.
#### What actually happens:
![screen](https://user-images.githubusercontent.com/32805122/174483412-e6c2ee35-49d0-4a46-9938-6aab34ca6695.png)
![screen](https://user-images.githubusercontent.com/32805122/174483633-d84f0398-eb28-49ee-8304-aaea98fab47a.png)
#### Why important:
Prevents easy lookup of function args while filling in the call.

**Comment by the-mikedavis** [comment]
Which language server is this? Hover on parens gives the function documentation with rust-analyzer. We only show in hover what the language server gives so this should most likely be reported upstream to tha language server repo.

**Comment by Houkime** [comment]
this is `rust-analyzer 0.0.0 (366bd7242 2022-06-12)`

**Comment by Houkime** [comment]
ok, after more investigation, this is a bit more nuanced.

a proper function call with all args in place, first parenthesis
![screen](https://user-images.githubusercontent.com/32805122/174486796-99b12516-2006-48cc-8e87-5d97053c791f.png)
the same call, last parenthesis (look, it shows the argument, not the function)
![screen](https://user-images.githubusercontent.com/32805122/174486914-3a159c40-6af0-4697-ac67-4f7dfd5865a1.png)
the empty call, first parenthesis works as needed
![screen](https://user-images.githubusercontent.com/32805122/174487044-60ba7e62-8254-4c1c-9df7-428465eb5cde.png)
but the LAST parenthesis does not.
![screen](https://user-images.githubusercontent.com/32805122/174487111-fcaec51a-b120-4768-9f40-0f75b6d2e553.png)

**Comment by the-mikedavis** [comment]
Does that `draw_circle()` line need a trailing semicolon to finish the statement? This behavior might be produced by invalid syntax.

**Comment by Houkime** [comment]
> Does that `draw_circle()` line need a trailing semicolon to finish the statement? This behavior might be produced by invalid syntax.

![screen](https://user-images.githubusercontent.com/32805122/174487767-3fa5862b-b0df-4317-8304-d09cf673522b.png)

Semicolon does not change anything.


These `()` are Rust's `void`. See, when the last parenthesis is inspected on the healthy call of `clear_background`, it shows info about the `DARKGRAY` color, ie, about the argument inserted into that call.  If we paste something into this last call to `draw_circle`, see what happens:

![screen](https://user-images.githubusercontent.com/32805122/174488073-ae01fcde-e3b1-4862-bd47-c80fac78bbf6.png)

**Comment by Houkime** [comment]
kak-lsp (written in Rust) has lsp-auto-lsp-signature-help-enable which covers filling in long function calls.
https://github.com/kak-lsp/kak-lsp

**Comment by sudormrfbin** [comment]
Signature help is being worked on in #1755.

**Comment by the-mikedavis** [comment]
The parens appear to be expected behavior from rust-analyzer: it's showing the return type of the call when hovering the trailing paren. There's an issue for signature help (plus the pr) https://github.com/helix-editor/helix/issues/1331 so let's close this in favor of that issue
