### ISSUE TITLE
Increment and decrement text objects

### ISSUE THREAD

**Issue by zim0369** [helix-editor/helix#2815]
### Summary

If a number isn't solely present then the increment & decrement operators don't even work.
```
1px 2 px
```
I was just editing a CSS file and first of all I have to place my cursor over the number and then use the increment or decrement operation. And if the word is alphanumeric then I have to place spaces around the number then place my cursor back on the number and now the increment and decrement operations work. I'm not sure if that's how it's intended to work but my complain about increment and decrement operation was quite old. In almost 90% of the cases I have a non-numeric character along with the number I'd like to increment.

Is this supposed to be fixed? I've tried it in helix from Arch as well as the one I built from source.

### Platform

linux

### Terminal Emulator

alacritty

### Helix Version

helix 22.05-dev (595213ca)

**Comment by pascalkuthe** [comment]
This was fixed in  #4123 by requiring the user ti select the number manually instead of auto detecting
