### ISSUE TITLE
Panic when entering Unicode in command prompt

### ISSUE THREAD

**Issue by CBenoit** [helix-editor/helix#282]
Hi! Another Unicode panic :wave: 

### Reproduction steps

Type `:éé`

### Environment

- Platform: Linux
- Helix version: commit 6fb2d2679dc6

### Output

```
$ hx
thread 'main' panicked at 'assertion failed: self.is_char_boundary(idx)', /home/auroden/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/alloc/src/string.rs:1351:9
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

**Comment by archseer** [comment]
Okay, this is a dumb one, String::insert indexes by byte position.

https://github.com/helix-editor/helix/blob/14db2cc68b3e9911f64e675c32800f8cc7b2a5ed/helix-term/src/ui/prompt.rs#L56

Need to use `let (pos, _) = .char_indices().nth(pos).unwrap()`
