### ISSUE TITLE
autopairs for ```(triple backticks) should be added.

### ISSUE THREAD

**Issue by zim0369** [helix-editor/helix#2821]
autopairs for single backtick(\`) and triple backticks(\`\`\`)
```
` -> `|`
``` -> ```|```
```
`|` represents cursor

**Comment by n0s4** [comment]
Single backtick autopairs is acheivable with configuration:
```toml
[editor.auto-pairs]
'(' = ')'
'[' = ']'
'{' = '}'
'"' = '"'
"'" = "'"
'`' = '`'
```

Triple backtick would require autopairing of multi-character pairs, not currently possible.

**Comment by the-mikedavis** [comment]
Autopairs for backtics only makes sense in languages where backtick closes backtick like markdown (a counter-example is EDoc where single-quote closes backtick). These can be added to the `languages.toml` like here for rust: https://github.com/helix-editor/helix/blob/ad15e7b5e8918e1521683c7f5c63d77e00c58023/languages.toml#L15-L20. Would you like to submit a PR?

**Comment by zim0369** [comment]
@the-mikedavis Sorry, I would be unable to submit a PR due to the lack of skills.

**Comment by dead10ck** [comment]
Is this actionable? Or should we close it?

**Comment by the-mikedavis** [comment]
I'm surprised we didn't already have a tracking issue for multiple-character auto-pairs. Let's close in favor of https://github.com/helix-editor/helix/issues/4035 which should this.
