### ISSUE TITLE
Ability to switch to plain vim bindings

### ISSUE THREAD

**Issue by zim0369** [helix-editor/helix#2826]
I like helix editor more for it's features other than the bindings like performance, more inbuilt stuff, etc.

What if a person like me wants to use helix but doesn't like the bindings and wishes helix had only vim bindings?

A feature to switch to plain vim bindings and commands would be cool.

**Comment by sudormrfbin** [comment]
This is pretty much a wontfix: https://github.com/helix-editor/helix/discussions/1511#discussioncomment-2517661.
