### ISSUE TITLE
prioritize gutter diagnostics

### ISSUE THREAD

**Issue by sbromberger** [helix-editor/helix#2827]
#### Describe your feature request

Right now if there are multiple issues of different severity on a given line, it is possible that a less-severe (_i.e._, `warning`) gutter icon overrides a more severe (_i.e._, `error`) icon. It would be nice if the highest-severity issue could be displayed. Here's an example:
<img width="524" alt="error" src="https://user-images.githubusercontent.com/941359/174501636-60d10f99-86f1-4418-9e41-7f0d5e5f44f3.png">

On line 11, there are two errors and one warning (the suggestion to borrow). The gutter icon briefly flashed a red dot, but then the yellow dot overwrote the red dot. It'd be better if the red dot persisted because that is probably something that should take a higher precedence.

**Comment by the-mikedavis** [comment]
I agree these should be prioritized by severity 👍

The relevant source for this is in [`helix_term::ui::editor::EditorView::render_diagnostics`](https://github.com/helix-editor/helix/blob/ad15e7b5e8918e1521683c7f5c63d77e00c58023/helix-term/src/ui/editor.rs#L600-L652) if you'd like to give it a try
