### ISSUE TITLE
How to remap keys into the 'space' mode?

### ISSUE THREAD

**Issue by ipstone** [helix-editor/helix#2841]
Hello, 
Coming from vim, I usually remap` <space>`+z to :quit - 
is there a way to do so in helix?

I tried to add the following in config.toml , but helix would not accept it:
```
[keys.space]
z = 'quit'
```

Appreciate help/ideas. Thanks

**Comment by the-mikedavis** [comment]
This should do the trick:

```toml
[keys.normal.space]
z = ":quit"
```
