### ISSUE TITLE
[windows] crash during selection

### ISSUE THREAD

**Issue by JackMordaunt** [helix-editor/helix#2850]
### Summary

Got this somewhat randomly `vgl` line selection:

```
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Line index out of bounds: line index 41, Rope/RopeSlice line count 1', C:\Users\runneradmin\.cargo\registry\src\github.com-1ecc6299db9ec823\ropey-1.4.1\src\slice.rs:424:41
```

### Reproduction Steps

I was doing `vgl` to select a line in a Go project. 

### Helix log

`fd helix.log` doesn't find anything for me (on Windows). 

### Platform

Windows

### Terminal Emulator

alacritty 0.10.1 (2844606)

### Helix Version

helix 22.05 (27609f50)

**Comment by the-mikedavis** [comment]
For the log file: https://github.com/helix-editor/helix/wiki/FAQ#access-the-log-file

Do you have the Go language server installed? This might have been triggered by a language server message - can you reproduce this running in verbose mode (`-v`) and also give a full backtrace (set the `RUST_BACKTRACE` env var to `full)?

**Comment by pascalkuthe** [comment]
I will close this for now as this issue has no reproduction case and is very stale. If you run into this again and can provide a reproduction case feel free to reopon
