### ISSUE TITLE
helix-editor cannot build on windows

### ISSUE THREAD

**Issue by LollipopFt** [helix-editor/helix#2858]
### Summary

`cargo` gives this error:
```rust
error: failed to run custom build command for `helix-term v0.6.0 (C:\Users\lollipopft\hlx\helix-term)`

Caused by:
  process didn't exit successfully: `C:\Users\lollipopft\hlx\target\release\build\helix-term-5f7ecc4d527c3042\build-script-build` (exit code: 101)
  --- stderr
  thread 'main' panicked at 'Failed to fetch tree-sitter grammars: Failed to fetch some grammar(s)

  Caused by:
      program not found', helix-term\build.rs:21:26
  note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
warning: build failed, waiting for other jobs to finish...
```

### Reproduction Steps

 

I tried this:

1. `hx`

I expected this to happen:

Instead, this happened:

### Platform

Windows

### Terminal Emulator

cmd.exe

### Helix Version

commit 8c86cd56cb90cab495e2a8eac90cadc2954abf10

**Comment by pppKin** [comment]
Any idea which grammar was not fetched? I can build latest master just fine; You might wanna specify only a few languages in your config (`~\AppData\Roaming\helix\languages.toml`)
for example:
```
use-grammars = { only = [ "rust", "c" ] }
```
instead of fetching over 60 grammars that you don't need.

**Comment by the-mikedavis** [comment]
It looks like the builder is having a hard time finding `git` - is it installed and in PATH?
