### ISSUE TITLE
:wq! messes up the terminal

### ISSUE THREAD

**Issue by Pistahh** [helix-editor/helix#2863]
### Summary

When I try to edit something I have no permissions for and try to save and exit with `:wq!`, it exits the editor but leaves the terminal in a messed up state:
![image](https://user-images.githubusercontent.com/9561441/175241346-4aa2638f-18e4-41b7-b0e5-ecdf806efa46.png)

for reference, this is how it should look like:

![image](https://user-images.githubusercontent.com/9561441/175241517-982c1baf-bffb-482c-9392-bf1de542fbda.png)

I use zsh and my prompt is set up by https://github.com/Pistahh/dot-zsh/blob/master/.zsh.d/prompt

### Reproduction Steps

 

I tried this:

1. `hx /etc/hosts` as non-root (so no write permissions)
2. modified it
3. tried to save and exit with `:wq!`

I expected this to happen:

  terminal is not messed up

Instead, this happened:

  terminal is messed up

### Platform

Linux, zsh. 

### Terminal Emulator

issue happens both in terminator and Windows Terminal

### Helix Version

helix 22.05 (c107f4ea)

**Comment by sbromberger** [comment]
I think I've narrowed it down to needing to reset `isig` (`stty isig`) on exit.

**Comment by dead10ck** [comment]
I believe this was fixed with #4801
