### ISSUE TITLE
[OSX][brew] Feature request: make case insensitive autocompletion default for brew installs

### ISSUE THREAD

**Issue by q30a** [helix-editor/helix#2867]
#### Make case insensitive autocompletion default for brew installs
I have installed helix as described on helix-editor.com:
```
brew tap helix-editor/helix
brew install helix
```
Also, my system has case insensitive completion configured:
I can do `cd d[tab]` and it returns `cd Desktop`
I can do `vim d[tab]` and it returns `vim Dockerfile`
However, I can't do `hx d[tab]`, only `hx D[tab]` returns `hx Dockerfile`

The shell I'm using is zsh

**Comment by the-mikedavis** [comment]
Completions live here: https://github.com/helix-editor/helix/tree/master/contrib/completion

We might just be missing a flag/option or two that enables case insensitive file completion

**Comment by d12bb** [comment]
I quickly searched ZSH's man pages, and it seems `_files` (the built-in helper function used to complete files) doesn't accept any argument regarding case sensitivity. I don't use ZSH myself, but a quick search makes me think your `zstyle` configuration is to blame here, see [StackOverflow](https://stackoverflow.com/questions/24226685/have-zsh-return-case-insensitive-auto-complete-matches-but-prefer-exact-matches).

Unfortunately I can't test it, as I use Fish and can't get ZSH completion to work at all currently, don't remember how I did it when I first created these completion files to test them :D

**Comment by q30a** [comment]
Thanks for reminding me about this issue @d12bb. You are most likely right as now I can't reproduce what I described originally on another mac.

With this in mind, the issue is rejected.
