### ISSUE TITLE
:wq! on a readonly file messes up terminal

### ISSUE THREAD

**Issue by sbromberger** [helix-editor/helix#2879]
### Summary

Using a current master build, editing a read-only file. After `:wq!`, helix exits after printing a message (presumably to stderr), but then the terminal is now unusable:

### Reproduction Steps

 

https://asciinema.org/a/ozdi9SR4LFNV8G75zBXXju0tT

### Helix log

<details><summary>~/.cache/helix/helix.log</summary>

```
please provide a copy of `~/.cache/helix/helix.log` here if possible, you may need to redact some of the lines
```

</details>

### Platform

Linux

### Terminal Emulator

blink.sh + mosh + tmux

### Helix Version

22.05-162-g08062b7c

**Comment by sbromberger** [comment]
More info: looks like helix doesn't restore `isig` when it terminates this way. Manually doing `stty isig` fixes the problem.

**Comment by the-mikedavis** [comment]
Duplicate of https://github.com/helix-editor/helix/issues/2863
