### ISSUE TITLE
Improve output of tree-sitter-subtree

### ISSUE THREAD

**Issue by zetashift** [helix-editor/helix#2880]
#### Describe your feature request
Current output of `:tree-sitter-subtree`

![image](https://user-images.githubusercontent.com/1857826/175812184-e71aa1e4-3afd-49a9-8914-7b374b53f873.png)

This reads fine for small code snippets, but for big blocks it gets kind of unreadable.
A way of improving this, from `the-mikedavis` from helix Matrix chat:

```
we could format these like tree-sitter parse pretty easily, i.e. break lines and do indentation
```

**Comment by fisherdarling** [comment]
I'll work on this :) I think I have a pretty simple implementation.
