### ISSUE TITLE
Doc: clipboard prompts

### ISSUE THREAD

**Issue by DuckDuckWhale** [helix-editor/helix#2885]
The distinction between mouse select and <space>y isn't very clear:
- Mouse: `yanked main selection to system clipboard`
- Space + y: `joined and yanked 1 selection(s) to system clipboard`

It is not clear from this prompt that one of them goes to the middle click clipboard yet the other one goes to the normal (Ctrl+C/V) clipboard. Also, the `joined and yanked 1 selections(s)` is unnecessary. Simply `yanked selection to system clipboard` would do.

**Comment by the-mikedavis** [comment]
Duplicate of https://github.com/helix-editor/helix/issues/2615
