### ISSUE TITLE
Question: how to turn on warnings in C with clangd?

### ISSUE THREAD

**Issue by DuckDuckWhale** [helix-editor/helix#2886]
Try compiling the following program:

```
#include <stdio.h>

int main() {
	int a;
	return 0;
}
```

It gives no warnings in helix yet `clang -Wall` gives an unused variable warning. How do I tell helix to show warnings?

**Comment by Julpikar** [comment]
add -Wall to compile_flags.txt in root folder project [https://clangd.llvm.org/config#compileflags]().

**Comment by DuckDuckWhale** [comment]
Thanks! For future reference, the relevant docs for helix is at https://github.com/helix-editor/helix/wiki/How-to-install-the-default-language-servers#clangd
