### ISSUE TITLE
Semantic syntax highlighting

### ISSUE THREAD

**Issue by poliorcetics** [helix-editor/helix#2888]
#### Describe your feature request

For Rust, rust-analyzer allows highlighting `unsafe` calls through semantic highlighting, and doc comments as well. I saw the old PR saying semantic highlighting was slow so this could be made an optional thing, per-language (and so per-language-server), so that fast LSPs could provide it while not slowing everything else.

**Comment by archseer** [comment]
https://github.com/helix-editor/helix/issues/814
