### ISSUE TITLE
config.toml autocomplete

### ISSUE THREAD

**Issue by 0xfMel** [helix-editor/helix#2894]
Would be convenient to have autocomplete built-in for the helix config.toml file, suggest keys, valid values, sections, etc.

**Comment by the-mikedavis** [comment]
It may be easy to add this by writing a schema for the config file: https://github.com/helix-editor/helix/pull/2302#issuecomment-1111182560

**Comment by the-mikedavis** [comment]
See https://github.com/helix-editor/helix/issues/3901#issuecomment-1737898373
