### ISSUE TITLE
Delayed outputs from background processes overlap editor UI

### ISSUE THREAD

**Issue by anzhi0708** [helix-editor/helix#2911]
### Summary

![截屏2022-06-29 下午6 32 41](https://user-images.githubusercontent.com/57821133/176404260-44c308ee-a8a7-452f-bca9-14f0d2c7a4c4.png)

Run a process in the background, then open helix immediately.

Delayed outputs will be shown inside of the editor (not the actual buff, but the UI, the file content was not overwritten)

### Reproduction Steps

```
# test.py

import time

time.sleep(3)
print("Hi!")
```

```
# zsh
python3 test.py &
hx
```

### Platform

macOS

### Terminal Emulator

iTerm2

### Helix Version

helix 22.05 (27609f50)

**Comment by archseer** [comment]
I'm not sure there's anything we can do here? This is a terminal behaviour, we have no influence over background processes that output to stdout.

**Comment by anzhi0708** [comment]
> I'm not sure there's anything we can do here? This is a terminal behaviour, we have no influence over background processes that output to stdout.

You are right, ```vim``` has the same behave.
