### ISSUE TITLE
add info about binding to mac specific modifier keys

### ISSUE THREAD

**Issue by adsick** [helix-editor/helix#2913]
[documentation](https://docs.helix-editor.com/remapping.html)
describes modifier keys in terms of classic "Control, Alt, Shift" trinity, but mac has "Command, Option, Shift" (and Control which I don't want to use), how to deal with it? maybe add a note about it in the documentation?

I want to have Command-x bindings, not Control-x.

**Comment by the-mikedavis** [comment]
Command modifiers are not supported because they're not supported upstream in crossterm: https://github.com/crossterm-rs/crossterm/issues/389

Support for command could most likely be added with a GUI but otherwise awaits that issue upstream.

**Comment by groves** [comment]
Command can be exposed with [Kitty's keyboard protocol](https://sw.kovidgoyal.net/kitty/keyboard-protocol/#modifiers). That's started being added in https://github.com/crossterm-rs/crossterm/pull/691. Once that lands, I think we could build on it for additional modifiers.

**Comment by restfuladi** [comment]
When using alacritty, `command+s` shows `select:`. I'd love to know how it's doing that so I can remap it to `:write`.

**Comment by kee-oth** [comment]
> Command can be exposed with [Kitty's keyboard protocol](https://sw.kovidgoyal.net/kitty/keyboard-protocol/#modifiers). That's started being added in [crossterm-rs/crossterm#691](https://github.com/crossterm-rs/crossterm/pull/691). Once that lands, I think we could build on it for additional modifiers.

@groves Just pinging that the linked PR has been merged as I am interested in this as well. Thanks!

**Comment by peredwardsson** [comment]
Also interested. Editor looks great, but using Mac + nordic keyboard makes it a little awkward.

**Comment by justaskz** [comment]
Are there any updates?

I tried to remap keys using kitty:
When `Cmd+KEY` is pressed, kitty sends `Ctrl+KEY` hex code as text. However it does not work. And there is no way to debug it.

Does anyone have any success in making Command key working?

**Comment by danillos** [comment]
@justaskz one example with Kitty that I did to save with `cmd+s`

```
# Kitty config

map cmd+S send_text all \x13
```

```
# Helix Config

[keys.normal]
'C-s' = ':w!'
```


`\x13` = `control+s` you can see [more here](https://donsnotes.com/tech/charsets/ascii.html) 
Kitty accepts [unicode](https://www.rapidtables.com/code/text/unicode-characters.html) too.

**Comment by the-mikedavis** [comment]
This will be closed by https://github.com/helix-editor/helix/pull/6592

**Comment by justaskz** [comment]
@danillos thank you, it works now!!

I took wrong config example from somewhere `map cmd+s send_text normal,application \x13` and it did not work

**Comment by LeeeSe** [comment]
if you use alacritty，Bind cmd + s to ctrl + s and use it with helix's key bindings

~/.config/alacritty/alacritty.yaml
```yaml
import = ["/Users/ls/.config/alacritty/themes/themes/tokyo-night.toml"]
live_config_reload = true

[font]
# AppleFontSmoothing = true
size = 14.0

[font.normal]
family = "JetBrainsMono Nerd Font"
style = "Regular"

[[keyboard.bindings]]
chars = "\u0013"
key = "S"
mods = "Command"

```

~/.config/helix/config.toml
```toml
theme = "tokyonight"

[editor]
middle-click-paste = false
auto-save = true

[editor.file-picker]
hidden = false


[editor.lsp]
display-messages = true
display-inlay-hints	= true

[editor.cursor-shape]
normal = "block"
insert = "bar"

[keys.normal]
C-s = ":w"
```
