### ISSUE TITLE
Keybindings that require AltGr modifiers don't work on Windows

### ISSUE THREAD

**Issue by CptPotato** [helix-editor/helix#2914]
### Summary

*as mentioned in [#595 (comment)](https://github.com/helix-editor/helix/issues/595#issuecomment-1169747548)*

Keybinds that use characters which require the <kbd>AltGr</kbd> modifier don't seem to work on windows. Entering these characters normally as text, however, works as expected with the fixes made to address #595.

One example is the pipe command `|` on some European keyboard layouts.
For reference, crossterm's `event-read` example registers the key as:
`Event: Key(KeyEvent { code: Char('|'), modifiers: CONTROL | ALT })`

Another thing to note is that on linux the same keybind works for me (with the same keyboard layout).

**Edit:** I just tested it on linux: Characters that are written with the <kbd>AltGr</kbd> modifier do not include the ˋCONTROLˋ and ˋALTˋ modifier-flags in crossterm, which is probably the cause of this issue.

### Helix log

Nothing of interest.

### Platform

Windows

### Terminal Emulator

Wezterm (nightly), Cmd, Powershell, ConEmu

### Helix Version

built from current master `22.05-159-gbf1db737`

**Comment by yashpalgoyal1304** [comment]
hey, so, helix is working for you on wezterm on windows?? I am facing problems with it

**Comment by yashpalgoyal1304** [comment]
ahw right... i am using `bash`, but just tried `wezterm` --> `cmd` --> `hx` ; still showed the same gibberish

**Comment by pascalkuthe** [comment]
Closing favor of #7129 since that has more details
