### ISSUE TITLE
yank to system clipboard not working in zorin os 16

### ISSUE THREAD

**Issue by hzb-ykpcx** [helix-editor/helix#2937]
zorin os 16 is based on ubuntu and uses gnome as the desktop. after I enter space+y and ctrl-v in other applications, I get only the things copied before.

**Comment by the-mikedavis** [comment]
Do you have a clipboard provider installed? https://github.com/helix-editor/helix/wiki/Troubleshooting#on-linux

**Comment by hzb-ykpcx** [comment]
thx
