### ISSUE TITLE
`x` selects two lines when the first is blank

### ISSUE THREAD

**Issue by sbromberger** [helix-editor/helix#2941]
### Summary

I didn't know how to search this so apologies if this is a duplicate.

If you use `o` to insert a line below existing text, then `esc` to get back to normal mode, then move the cursor to the blank line and hit `x`, the blank line and the following line are selected.

### Reproduction Steps

https://asciinema.org/a/ckIoEGFJGx037Sp9cDxlPuk2a

I expected just the blank line to be highlighted.

### Platform

linux

### Terminal Emulator

blink + tmux + mosh + ssh

### Helix Version

22.05-232-g51c65603

**Comment by the-mikedavis** [comment]
This is the intended behavior of `x`: when you're on that blank line, your cursor is already selecting the full line so `x`'s behavior of selecting the next line kicks in. Use `X` to extend the selection only the to the current line.

**Comment by sbromberger** [comment]
Oh, sorry. That seems counterintuitive, but I guess I'll get used to it.
