### ISSUE TITLE
helix 22.05 (e58d28a9) crash on opening the Markdown file in Artixlinux under WSL2

### ISSUE THREAD

**Issue by siddharthagudgunti** [helix-editor/helix#2955]
### Summary

hx built from source master

Tried to open the README.md file from wezterm (20220627-202826-f1c53495) on an ArtixLinux in WSL2. Note that, the issue is **not** observed on an Ubuntu (20.04).

### Reproduction Steps

Tried to open the README.md file from wezterm (20220627-202826-f1c53495) on an ArtixLinux in WSL2. Note that, the issue is not observed on an Ubuntu (20.04).

> 
> helix on  master via 🦀 v1.61.0
> ❯ RUST_BACKTRACE=full hx -v README.md
> thread 'main' panicked at 'Could not parse queries for language "markdown". Are your grammars out of sync? Try running 'hx --grammar fetch' and 'hx --grammar build'. This query could not be parsed: QueryError { row: 53, column: 1, offset: 1455, message: "fenced_code_block_delimiter", kind: NodeType }', helix-core/src/syntax.rs:379:43
> stack backtrace:
>    0:     0x563d079accd4 - std::backtrace_rs::backtrace::libunwind::trace::h22893a5306c091b4
>                                at /rustc/fe5b13d681f25ee6474be29d748c65adcd91f69e/library/std/src/../../backtrace/src/backtrace/libunwind.rs:93:5
>    1:     0x563d079accd4 - std::backtrace_rs::backtrace::trace_unsynchronized::h29c3bc6f9e91819d
>                                at /rustc/fe5b13d681f25ee6474be29d748c65adcd91f69e/library/std/src/../../backtrace/src/backtrace/mod.rs:66:5
>    2:     0x563d079accd4 - std::sys_common::backtrace::_print_fmt::he497d8a0ec903793
>                                at /rustc/fe5b13d681f25ee6474be29d748c65adcd91f69e/library/std/src/sys_common/backtrace.rs:66:5
>    3:     0x563d079accd4 - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::h9c2a9d2774d81873
>                                at /rustc/fe5b13d681f25ee6474be29d748c65adcd91f69e/library/std/src/sys_common/backtrace.rs:45:22
>    4:     0x563d0722494c - core::fmt::write::hba4337c43d992f49
>                                at /rustc/fe5b13d681f25ee6474be29d748c65adcd91f69e/library/core/src/fmt/mod.rs:1194:17
>    5:     0x563d079a6745 - std::io::Write::write_fmt::heb73de6e02cfabed
>                                at /rustc/fe5b13d681f25ee6474be29d748c65adcd91f69e/library/std/src/io/mod.rs:1655:15
>    6:     0x563d079aeb7e - std::sys_common::backtrace::_print::h63c8b24acdd8e8ce
>                                at /rustc/fe5b13d681f25ee6474be29d748c65adcd91f69e/library/std/src/sys_common/backtrace.rs:48:5
>    7:     0x563d079aeb7e - std::sys_common::backtrace::print::h426700d6240cdcc2
>                                at /rustc/fe5b13d681f25ee6474be29d748c65adcd91f69e/library/std/src/sys_common/backtrace.rs:35:9
>    8:     0x563d079aeb7e - std::panicking::default_hook::{{closure}}::hc9a76eed0b18f82b
>                                at /rustc/fe5b13d681f25ee6474be29d748c65adcd91f69e/library/std/src/panicking.rs:295:22
>    9:     0x563d079ae8ad - std::panicking::default_hook::h2e88d02087fae196
>                                at /rustc/fe5b13d681f25ee6474be29d748c65adcd91f69e/library/std/src/panicking.rs:314:9
>   10:     0x563d079af125 - std::panicking::rust_panic_with_hook::habfdcc2e90f9fd4c
>                                at /rustc/fe5b13d681f25ee6474be29d748c65adcd91f69e/library/std/src/panicking.rs:698:17
>   11:     0x563d079af034 - std::panicking::begin_panic_handler::{{closure}}::he054b2a83a51d2cd
>                                at /rustc/fe5b13d681f25ee6474be29d748c65adcd91f69e/library/std/src/panicking.rs:588:13
>   12:     0x563d079ad204 - std::sys_common::backtrace::__rust_end_short_backtrace::ha48b94ab49b30915
>                                at /rustc/fe5b13d681f25ee6474be29d748c65adcd91f69e/library/std/src/sys_common/backtrace.rs:138:18
>   13:     0x563d079aed9d - rust_begin_unwind
>                                at /rustc/fe5b13d681f25ee6474be29d748c65adcd91f69e/library/std/src/panicking.rs:584:5
>   14:     0x563d071a3d43 - core::panicking::panic_fmt::h366d3a309ae17c94
>                                at /rustc/fe5b13d681f25ee6474be29d748c65adcd91f69e/library/core/src/panicking.rs:143:14
>   15:     0x563d072ea810 - helix_core::syntax::LanguageConfiguration::initialize_highlight::ha180dcdf1d07cd64
>   16:     0x563d072e02b1 - once_cell::imp::OnceCell<T>::initialize::{{closure}}::ha710bf074f39e404
>   17:     0x563d078be90a - once_cell::imp::initialize_or_wait::h705117847e33506e
>   18:     0x563d071a8b9e - once_cell::imp::OnceCell<T>::initialize::hf3d60ea89e455349
>   19:     0x563d077a8bef - helix_view::document::Document::set_language::h9127812df3be4ad4
>   20:     0x563d077a7cae - helix_view::document::Document::open::hc81eee956b7d4d51
>   21:     0x563d0778b1f1 - helix_view::editor::Editor::open::hc98d4b011465eb5d
>   22:     0x563d0755f658 - helix_term::application::Application::new::h916f07dfbc565a3d
>   23:     0x563d0784ed82 - <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll::h0b68a4590368667f
>   24:     0x563d07816142 - std::thread::local::LocalKey<T>::with::h7f75ca17458268be
>   25:     0x563d07813e68 - tokio::park::thread::CachedParkThread::block_on::h73b5bf49c604a18d
>   26:     0x563d07872193 - tokio::runtime::thread_pool::ThreadPool::block_on::h3813ebbcdc8082e1
>   27:     0x563d0784bfae - tokio::runtime::Runtime::block_on::h074c89a243ebc896
>   28:     0x563d0780abbd - hx::main::h8effa18f40c45b19
>   29:     0x563d07815da3 - std::sys_common::backtrace::__rust_begin_short_backtrace::h32f1bd0059947450
>   30:     0x563d0783df2d - std::rt::lang_start::{{closure}}::hda19a0224177a339
>   31:     0x563d079a0fdb - core::ops::function::impls::<impl core::ops::function::FnOnce<A> for &F>::call_once::had4f69b3aefb47a8
>                                at /rustc/fe5b13d681f25ee6474be29d748c65adcd91f69e/library/core/src/ops/function.rs:259:13
>   32:     0x563d079a0fdb - std::panicking::try::do_call::hf2ad5355fcafe775
>                                at /rustc/fe5b13d681f25ee6474be29d748c65adcd91f69e/library/std/src/panicking.rs:492:40
>   33:     0x563d079a0fdb - std::panicking::try::h0a63ac363423e61e
>                                at /rustc/fe5b13d681f25ee6474be29d748c65adcd91f69e/library/std/src/panicking.rs:456:19
>   34:     0x563d079a0fdb - std::panic::catch_unwind::h18088edcecb8693a
>                                at /rustc/fe5b13d681f25ee6474be29d748c65adcd91f69e/library/std/src/panic.rs:137:14
>   35:     0x563d079a0fdb - std::rt::lang_start_internal::{{closure}}::ha7dad166dc711761
>                                at /rustc/fe5b13d681f25ee6474be29d748c65adcd91f69e/library/std/src/rt.rs:128:48
>   36:     0x563d079a0fdb - std::panicking::try::do_call::hda0c61bf3a57d6e6
>                                at /rustc/fe5b13d681f25ee6474be29d748c65adcd91f69e/library/std/src/panicking.rs:492:40
>   37:     0x563d079a0fdb - std::panicking::try::hbc940e68560040a9
>                                at /rustc/fe5b13d681f25ee6474be29d748c65adcd91f69e/library/std/src/panicking.rs:456:19
>   38:     0x563d079a0fdb - std::panic::catch_unwind::haed0df2aeb3fa368
>                                at /rustc/fe5b13d681f25ee6474be29d748c65adcd91f69e/library/std/src/panic.rs:137:14
>   39:     0x563d079a0fdb - std::rt::lang_start_internal::h9c06694362b5b80c
>                                at /rustc/fe5b13d681f25ee6474be29d748c65adcd91f69e/library/std/src/rt.rs:128:20
>   40:     0x563d0780acc2 - main
>   41:     0x7efeade54310 - __libc_start_call_main
>   42:     0x7efeade543c1 - __libc_start_main@GLIBC_2.2.5
>   43:     0x563d071da0d5 - _start
>   44:                0x0 - <unknown>
> 
> 

### Helix log

<details><summary>~/.cache/helix/helix.log</summary>

```
❯ bat ~/.cache/helix/helix.log
───────┬─────────────────────────────────────────────────────────────────────────
       │ File: /home/siddug/.cache/helix/helix.log   <EMPTY>
───────┴─────────────────────────────────────────────────────────────────────────

please provide a copy of `~/.cache/helix/helix.log` here if possible, you may need to redact some of the lines
```
The log file is not created.
</details>

### Platform

WSL2 ArtixLinux

### Terminal Emulator

wezterm 20220627-202826-f1c53495

### Helix Version

helix 22.05 (e58d28a9)

**Comment by archseer** [comment]
Did you follow the instructions?

>  Are your grammars out of sync? Try running 'hx --grammar fetch' and 'hx --grammar build'.

**Comment by siddharthagudgunti** [comment]
> Did you follow the instructions?
> 
> > Are your grammars out of sync? Try running 'hx --grammar fetch' and 'hx --grammar build'.

Have already done. As I symlink, hx -g fech and build always show all good.

**Comment by siddharthagudgunti** [comment]
OK. This recalled that helix-syntax stuff you informed me in Matrix chat @archseer .... So went ahead and did following steps:
1. removed all .so files in runtime/grammer folder.
2. hx -g fetch
3. hx -g build

Now, no crash.  

Not sure,  why this happened though. On Ubuntu machine, some .so files(tsq,git-commit,erlang,elvish & markdown) were rebuilt, but the same did not happen on Artix Linux (only elvish was rebuilt). 
Does `git pull` or `cargo install --path helix-term` behaves differently on different Linux?

**Comment by siddharthagudgunti** [comment]
re-occurrence of https://github.com/helix-editor/helix/issues/960 ... Closing.
