### ISSUE TITLE
Space/newline characters are copied when selected

### ISSUE THREAD

**Issue by poliorcetics** [helix-editor/helix#2957]
### Summary

When displayed, the space/tabs/newline/nbsp characters interfere with URL recognition, OS copy/paste:

URL recognition take into account the newline character:

![Screenshot 2022-07-04 at 15 14 53](https://user-images.githubusercontent.com/7951708/177162377-f90b3601-232a-4c73-967e-b89db98150eb.png)

OS copy then paste (not with `space + y` but with `Command + C` on macOS) also gets them:

First copying

![Screenshot 2022-07-04 at 15 17 32](https://user-images.githubusercontent.com/7951708/177162831-08a6de07-5b27-4e18-8423-298a61324419.png)

Then pasting

![Screenshot 2022-07-04 at 15 17 46](https://user-images.githubusercontent.com/7951708/177162875-071a8c19-b074-4a6a-89ed-31407f87c20f.png)

### Reproduction Steps

I tried this:

1. `hx`
2. `:set-option whitespace.render all`
3. `:set-option mouse false`
4. Write `// See https://gitlab.company.com/company/project/-/issues/42`, add newline, exit insert mode
5. Click on URL, it will take the newline character
6. Copy `/ See http` with the OS select and copy (with mouse and `Command + C`)
7. Paste somewhere else

I expected this to happen:

The virtual characters are not copied

Instead, this happened:

The virtual characters are copied

### Helix log

<details><summary>~/.cache/helix/helix.log</summary>

```
please provide a copy of `~/.cache/helix/helix.log` here if possible, you may need to redact some of the lines
```

</details>

### Platform

macOS

### Terminal Emulator

kitty 0.25.2

### Helix Version

helix 22.05 (e58d28a9)

**Comment by kirawi** [comment]
You can use `space` `y` to copy instead.

**Comment by kovidgoyal** [comment]
Sure you can fix it using OSC 8 to mark hyperlinks.

**Comment by kirawi** [comment]
https://github.com/helix-editor/helix/issues/1472
