### ISSUE TITLE
writing 'let %' in nickel file crashes helix (Segmentation Fault)

### ISSUE THREAD

**Issue by Philipp-M** [helix-editor/helix#2979]
### Summary

I think the title sums it up already,

Additionally to the Reproduction Steps, it also crashes, when opening a file with the content `let %`

### Reproduction Steps

 

I tried this:

1. `hx test.ncl`
2. go to insert mode and write `let %`
3. crash (Segmentation Fault)

I expected this to happen:
no crash
Instead, this happened:
crash

### Helix log

Nothing interesting here even with `-vvvv`

### Platform

NixOS

### Terminal Emulator

xterm, alacritty

### Helix Version

22.05-218-gb6122110

**Comment by the-mikedavis** [comment]
Most minimally to reproduce this with the tree-sitter CLI:

```
$ echo "let %" > test.ncl
$ tree-sitter parse test.ncl
```

This is a bug either in the grammar or (more likely in my experience) in the [external scanner](https://github.com/nickel-lang/tree-sitter-nickel/blob/9a502ea2e774df3d743a48310bb40e1cc097c86e/src/scanner.cc). I'll open up an issue upstream
