### ISSUE TITLE
Can't position row by hx file:[row]

### ISSUE THREAD

**Issue by theowenyoung** [helix-editor/helix#2989]
### Summary

From usage, I tried to open the file with `hx test.txt:150`, but the cursor was still positioned to line 1.

```
USAGE:
    hx [FLAGS] [files]...

ARGS:
    <files>...    Sets the input file to use, position can also be specified via file[:row[:col]]
```

### Reproduction Steps

 

I tried this:

1. `hx test.txt:150`

I expected this to happen:

The cursor is positioned to line 50

Instead, this happened:

The cursor is positioned to line 0

### Helix log

no error log.

### Platform

macOS

### Terminal Emulator

Alacritty

### Helix Version

230ba264bf78d9b4ecd42440f0cbb20529f9c235

**Comment by the-mikedavis** [comment]
Fixed by https://github.com/helix-editor/helix/pull/3073
