### ISSUE TITLE
Background of selected, partially visible tabs is un-highlighted

### ISSUE THREAD

**Issue by mtoohey31** [helix-editor/helix#2992]
### Summary

The background highlighting of the selected range doesn't extend all the way to the left as it should when tabs are partially displayed as the leftmost visible character.

![screenshot](https://user-images.githubusercontent.com/36740602/177673492-b482fc19-184f-4bd9-9c5a-67d4ef108e92.png)

Notice how, in the screenshot above, the background of the leftmost character is not highlighted, even though the partially visible tab that occupies that space is part of the selection.

It's definitely an edge case, but it might be more noticeable with especially wide tab widths and small windows. 

### Reproduction Steps

 

I tried this:

1. `hx`
2. Position the view so a selected tab is partially visible.

I expected this to happen:

The background of the partially visible tab is highlighted, just like the rest of the selection.

Instead, this happened:

The background isn't highlighted.

### Platform

Linux

### Terminal Emulator

kitty 0.25.2

### Helix Version

b61221107068160c241858a530f6fa4144566122

**Comment by the-mikedavis** [comment]
Can you paste that part of the file? I'm confused what is tabs and what is spaces. Does this happen when not using indent-guides?

**Comment by mtoohey31** [comment]
I don't have the exact same text any more because I've refactored that code, but you can reproduce the same issue using an empty file of any language that uses tab indentation:

1. Open helix
2. `:set-language go`
3. Insert a tab then a bunch of repeated characters; enough to completely fill the screen horizontally
4. Move to the start of the line on top of the tab and enter visual mode
5. Start moving the character to the right while still in visual mode. As soon as the view moves to the left for the first time, the highlighting for the background of the selected tab will disappear, even though 3 of its characters are still visible. I would expect that the background of the partial tab would still be highlighted.

**Comment by A-Walrus** [comment]
This issue also affects other wide graphemes, such as `Ideographic Space "　"`
