### ISSUE TITLE
hx freezes with 100% CPU use editing a specific Elm file

### ISSUE THREAD

**Issue by jhbrown-veradept** [helix-editor/helix#2997]
### Summary

Problem:  hx freezes with 100% CPU use when I try to edit a specific Elm file.  I have to kill the process manually.

### Reproduction Steps

1.  Save the Elm code below to a file named Bogus.elm.  
2.  Invoke `hx Bogus.elm`   
3. Press `i` to enter insert mode
4. Type  a few characters.  `hx` will freeze.

(I have reduced the original file to this self-contained demo file.  Reducing the file complexity further seems to make the freezing problem go away.)

```
module Bogus exposing (..)

import NotRealThing as El


type alias Model =
    { state : State
    }


type State
    = State (Result Err Data)


view shared model =
    case model.state of
        State outcome ->
            case outcome of
                Ok _ ->
                    [ El.text "Success!" ]

                Err (SubErr SubErrType) ->
                    [ El.text "Specific failure already in use" ]

                Err e ->
                    [ El.text "general failure" ]
```

### Helix log

Log from running with `-vvv` attached
[helix.log](https://github.com/helix-editor/helix/files/9066151/helix.log)

### Platform

MacOS 12.4 (21F79)  Mac M1  Arm

### Terminal Emulator

iterm2 3.4.16, and Mac Terminal  2.12.7 (445)

### Helix Version

22.05-218-gb6122110

**Comment by jhbrown-veradept** [comment]
elm-language-server version info:
```
 npm ls -g
npm WARN config global `--global`, `--local` are deprecated. Use `--location=global` instead.
/Users/jhbrown/.nvm/versions/node/v16.15.1/lib
├── @elm-tooling/elm-language-server@2.4.1
├── corepack@0.10.0
└── npm@8.11.0
```

**Comment by SiriusStarr** [comment]
Cannot replicate this with `helix 22.05 (27609f50)`, can replicate with master; currently git bisecting, but my computer builds very slowly...  :laughing:

**Comment by SiriusStarr** [comment]
Okay, bisect done, this was introduced by bumping `tree-sitter` in fd644ccfa24b8141c1b8ea32349a0844fe7c884a

**Comment by SiriusStarr** [comment]
Poking around upstream, another bisect shows that tree-sitter/tree-sitter@d223a81b5064587af3a5f61f52d519670ba8995f (between v0.20.7 and v0.20.8) breaks 3 tests in https://github.com/elm-tooling/tree-sitter-elm so it's possible that that is the offending commit, though I haven't been able to find any sort of infinite loop or anything playing around with `tree-sitter` outside of helix.

**Comment by archseer** [comment]
I'd recommend also opening an issue upstream and link to this tracking issue.
