### ISSUE TITLE
Enable Font Ligatures

### ISSUE THREAD

**Issue by littlecastrum** [helix-editor/helix#3018]
#### Request
Currently there is no way to enable ligatures for monospaced fonts with them

**Comment by the-mikedavis** [comment]
FTR, this is something controlled in the terminal emulator. For example, you can configure ligature behavior in Kitty (https://sw.kovidgoyal.net/kitty/conf/?highlight=disable_ligatures#opt-kitty.disable_ligatures). You also need a font that supports ligatures, for example JetBrains Mono or Hasklig.
