### ISSUE TITLE
Split goto-number functionality from increment/decrement into a textobject

### ISSUE THREAD

**Issue by the-mikedavis** [helix-editor/helix#3028]
Increment (`C-a`) and decrement (`C-d`) currently move forward to the next number on their line if the cursor is not already over a number.

It would fit better with the select-then-act paradigm to split the motion and action behaviors. `C-a` and `C-d` can continue to increment and decrement but should not move the cursor. Increment/decrement should only act on the current selections. A new textobject `]n`/`[n`/`min`/`man` could replace the motion.

The new textobject could use tree-sitter queries to find number specific to the current language and/or could use a default naive implementation like what we have in increment/decrement now. (Falling back to a naive implementation would only work if we can easily detect that a query does not have any `number.inside`/`number.around` captures. I think that should be possible to figure out without running the query.)

**Comment by pascalkuthe** [comment]
This was addressed by  #4123 I think?

**Comment by the-mikedavis** [comment]
I was thinking at the time that we might want new textobjects to make jumping to numbers easier. But with macro keybinding and possibly also https://github.com/helix-editor/helix/issues/5672, new textobjects aren't necessary. So yep I consider this resolved :+1:
