### ISSUE TITLE
The file picker list does not update the count on up ad down movement. 

### ISSUE THREAD

**Issue by grv07** [helix-editor/helix#3036]
The file picker list does not update the count on up ad down movement. 

It will be beneficial to know where I am when scrolling a large number of files.
It does not update the counter it always remains the same 234/234 in the right size of the search panel.

**Comment by sudormrfbin** [comment]
The count shows: `number of files filtered` / `total files without the filter`. Type something in the picker and observe how the first number changes -- that shows the number of files that the current search query has filtered out.
