### ISSUE TITLE
Background Image | Wallpaper

### ISSUE THREAD

**Issue by RqndomHax** [helix-editor/helix#3059]
#### Describe your feature request

Hey !
It'd be cool to have the ability to set a background-image on supported terminals (like kitty).

Like on IntelliJ:
![intellij_example](https://user-images.githubusercontent.com/24386960/178700897-1462e9d6-0d51-4d93-8d41-47f04b582a84.png)

Here is an example of what it'd be on helix:
![helix_example](https://user-images.githubusercontent.com/24386960/178712970-e370ece6-59ec-443c-b779-1e02957d7f1b.png)

**Comment by RqndomHax** [comment]
Kitty can draw images in the terminal,

Yeah I guess I'll use transparent background in that case,

Thanks;

**Comment by bluebrown** [comment]
@CptPotato, commenting out doesn't pair well when trying to overwrite a pallet. There should be a color named `none` or `transparent` that we can use for overwrites.

**Comment by CptPotato** [comment]
> @CptPotato, commenting out doesn't pair well when trying to overwrite a pallet. Imo, there should be a color named `none` or `transparent` that we can use for overwrites.

That's not a bad idea. Feel free to create an issue for this feature if there doesn't exist one already.

**Comment by gabydd** [comment]
With the inherits you can set ``ui.background = {}`` and then there won't be a background, this could probably be documented somewhere

**Comment by freepicheep** [comment]
Thanks, @gabydd! The background was so annoying since I use a translucent terminal.

**Comment by Hachikoi-the-creator** [comment]
sorry if I sound ignorant, but couldn't make it work.
How would the configuration be in my `config.toml` to have by background transparent?
currently have onedark as a theme

**Comment by Hachikoi-the-creator** [comment]
nvm found it! (leaving instructions in case someone needs them)

inside `.config/helix `
- `$ mkdir themes`
- then there either copy the code from a theme you like : https://github.com/helix-editor/helix/wiki/Themes#available-themes
- copy the code in another file ex: `touch themes/oneDarker.toml`
- change `"ui.background": { }`
- select it like any other theme in your `config.toml` ex: `theme = "oneDarker"`

**Comment by melMass** [comment]
You actually don't need to copy the theme, you can create a simple override theme that `inherit` the main theme: https://docs.helix-editor.com/themes.html#inheritance
