### ISSUE TITLE
Pop-up documentation should not block the view to the cursor

### ISSUE THREAD

**Issue by malte-v** [helix-editor/helix#307]
![hx](https://user-images.githubusercontent.com/34393802/122598581-4e622680-d06d-11eb-800a-13adc51823d5.png)
That should make the issue clear. I can't see what I'm editing because the documentation is in the way.

**Comment by pickfire** [comment]
I see this issue in kakoune quite often, so most of the time I just disable the popup because of this.

**Comment by archseer** [comment]
Yeah I was planning on placing the docs above if they get too close to the prompt. (Easy reasoning would be if the cursor is past the middle of the view: https://github.com/nvim-lua/completion-nvim/commit/f09936740c8b10e27aca8e68ea2de76e9b268657#diff-13ac7f54ec22903ec9e2cd8a4874aceed4b78ece9e479d165d68631ecf4a3373R205)

Another option is a popup next to the completion, similar to compe (https://github.com/hrsh7th/nvim-compe#demo) but I find that harder to read than a pane at the top/bottom.
