### ISSUE TITLE
Show diagnostics when anywhere on its line

### ISSUE THREAD

**Issue by diktomat** [helix-editor/helix#3078]
Currently Helix only shows LSP diagnostics when the cursor is on the specific characters the diagnostic is for. Sometimes this can be hard to find, sometimes the characters are not even underlined, like in my demo below with a one character diagnostic. Helix should (maybe optionally) show diagnostics if the cursor is anywhere on the line, not just on the specific characters.

[![asciicast](https://asciinema.org/a/508750.svg)](https://asciinema.org/a/508750?t=5)

**Comment by sudormrfbin** [comment]
For finding the exact position of the error you can use `]d` and `]d`.

**Comment by archseer** [comment]
We used to default to anywhere on the line but what if there's multiple diagnostics on a single line?

**Comment by d12bb** [comment]
> We used to default to anywhere on the line but what if there's multiple diagnostics on a single line?

This can already happen, like Rust has error and hint often for the same part of the same line. They are just shown one message per line:
<img width="594" alt="image" src="https://user-images.githubusercontent.com/16717303/179218122-ea20bc91-e27b-4624-93c5-16503c357293.png">

**Comment by Yevgnen** [comment]
That's what I'm missing in `lsp-ui` of Emacs.

**Comment by erasin** [comment]
#6059
