### ISSUE TITLE
Better descriptive config option names for `editor.file-picker`

### ISSUE THREAD

**Issue by sudormrfbin** [helix-editor/helix#3086]
The current sub-config key names for the `editor.file-picker` table are confusing, so here are some proposed alternate names:

| Old key name | Proposed key name            | Description                                                                                            | Default |
|--           |--                             |--                                                                                                      |---------|
|`hidden`     |`ignore-hidden-files`          | Enables ignoring hidden files.                                                                         | true |
|`parents`    |`read-ignore-from-parent-dir`  | Enables reading ignore files from parent directories.                                                  | true |
|`ignore`     |`read-ignore`                  | Enables reading `.ignore` files.                                                                       | true |
|`git-ignore` |`read-gitignore`               | Enables reading `.gitignore` files.                                                                    | true |
|`git-global` |`read-global-gitignore`        | Enables reading global .gitignore, whose path is specified in git's config: `core.excludefile` option. | true |
|`git-exclude`|`read-git-exclude`             | Enables reading `.git/info/exclude` files.                                                             | true |
|`max-depth`  |`recurse-max-depth`            | Set with an integer value for maximum depth to recurse.                                                | Defaults to `None`. |

Another option would be to put all the `read-*` booleans into a `ignore-rules` table that would turn something like this:

```toml
[editor.file-picker]
read-ignore = true
read-gitignore = true
read-git-exclude = false
```

into

```toml
[editor.file-picker.ignore-rules]
ignore-file = true
gitignore = true
git-exclude = false
```

This would ofcourse be a breaking change, so printing a helpful error about the deprecation with old config files will be also nice to have.

**Comment by archseer** [comment]
Since the toml config is not intended to be around forever, is it worth introducing a breaking change? I've wanted to change some other keys too, but held off since it's just an annoyance to the end user.

**Comment by sudormrfbin** [comment]
Ah makes sense, in that case lets close this issue.

**Comment by ThinkChaos** [comment]
I ended up here because I also got quite confused by this.

Is there an issue or something used to track the post TOML config?  
This should be linked there to not forget :)
