### ISSUE TITLE
Support `textDocument/prepareRename`

### ISSUE THREAD

**Issue by archseer** [helix-editor/helix#3093]
There's a textDocument/prepareRename if the server supports it. https://microsoft.github.io/language-server-protocol/specifications/lsp/3.17/specification/#textDocument_prepareRename

It will return the offsets of the string we're renaming: https://github.com/emacs-lsp/lsp-mode/blob/6157b3dde2c56f734a0789225240c521acdf2c7c/lsp-mode.el#L5849-L5871=

**Comment by artempyanykh** [comment]
+1 to this. Renaming in [Marksman](https://github.com/artempyanykh/marksman) is really painful without the client doing `prepareRename` because the symbols can contain whitespace and all sorts of punctuation.
