### ISSUE TITLE
Not getting autocomplete suggestions.

### ISSUE THREAD

**Issue by udhaybegyall** [helix-editor/helix#3094]
I am not getting any autocomplete suggestions. As far as I know LSP is built in so I don't know what's the problem.

Language: Rust

OS: Windows 11

**Comment by udhaybegyall** [comment]
Configured language server: rust-analyzer
Binary for language server: C:\Users\username\.cargo\bin\rust-analyzer.EXE
Configured debug adapter: lldb-vscode
Binary for debug adapter: Not found in $PATH
Highlight queries: ✔
Textobject queries: ✔
Indent queries: ✔

This is the status.

It is working in main file but not on the other files in same project.

> 1. Is `hx --health rust` working correctly?
> 2. The language server only works, if you open helix with the folder containing you project. Single files don't work.

**Comment by ChrHorn** [comment]
Ok LS seems to work.

You have to open Helix with `hx <ProjectFolder>` or `hx .` if you are in the same directory. Then it should work for the whole project.

**Comment by udhaybegyall** [comment]
Nope It's still the same. Doesn't work.

**Comment by kirawi** [comment]
Is this after opening a Rust file? There should be some logs about the LSP.

**Comment by sudormrfbin** [comment]
> It is working in main file but not on the other files in same project.

Is there a diagnostic on the first line of those files with the text `File not included in module tree`? Equivalently, are those file declared as part of the project with a `mod filename` line in `main.rs` or `lib.rs`? Also see https://github.com/helix-editor/helix/issues/2046#issuecomment-1094042269.

**Comment by udhaybegyall** [comment]
> > It is working in main file but not on the other files in same project.
> 
> Is there a diagnostic on the first line of those files with the text `File not included in module tree`? Alternatively, are those file declared as part of the project with a `mod filename` line in `main.rs` or `lib.rs`? Without a `mod filename` declaration completion and other features won't work in rust-analyzer -- see [#2046 (comment)](https://github.com/helix-editor/helix/issues/2046#issuecomment-1094042269).

Yeah I didn't include the module in main file as I was using it as standalone file. It works now. Thanks
