### ISSUE TITLE
Elements in the status line are not separated, leading to a very cluttered result

### ISSUE THREAD

**Issue by poliorcetics** [helix-editor/helix#3106]
### Summary

![Screenshot 2022-07-19 at 12 17 44](https://user-images.githubusercontent.com/7951708/179727672-fcc0b4ab-21d1-45f2-a47f-9a03d8cadc05.png)

My status line config to reproduce is:

```
[editor.statusline]
left = ["mode", "spinner", "diagnostics", "file-name"]
```

### Platform

macOS

### Terminal Emulator

kitty 0.25.2

### Helix Version

https://github.com/helix-editor/helix/commit/791bf7e50a19bcf7612788deb7514847089cb976

**Comment by archseer** [comment]
I think we could use a custom spacer element maybe, or some type of config? With a simple, single background color statusline the extra padding introduces too much space.

**Comment by the-mikedavis** [comment]
Fixed by https://github.com/helix-editor/helix/pull/3165
