### ISSUE TITLE
Padding is now using gutter's color

### ISSUE THREAD

**Issue by kchibisov** [helix-editor/helix#3111]
### Summary

After e8214fb1e6009d44a4b7094c6e5297a19f18f549 the padding is now colored, which looks visually awful, since it's not really a padding anymore given that it closely visually attaches to line number.

An example of how it looks.

![picture](https://user-images.githubusercontent.com/27620401/179826911-db855a51-52f9-40f8-949e-a0b1057acffa.png)

The solution would be to use either a background color or provide a distinct color for it(using background color likely makes the most sense).

### Platform

Linux

### Terminal Emulator

alacritty

### Helix Version

helix 22.05 (791bf7e5)

**Comment by archseer** [comment]
@pickfire

**Comment by pickfire** [comment]
@kchibisov Thanks for reporting this. Which theme are you using? I tried both onedark and default theme, it doesn't seemed to have this issue.

**Comment by kchibisov** [comment]
Try base16-default-dark. But you can go through the themes(they live update) and you'll find themes that look differently with and without your patch I ve mentined.

**Comment by archseer** [comment]
Let's do this: If `gutters.is_empty!` then automatically apply a 1 char margin and remove the spacer after the line number. That way the space between the view and the code isn't a gutter component but instead a margin. A `spacer` can then still be used to apply space inside the gutter, between different components.
