### ISSUE TITLE
Syntax highlighting is weird for Rust match on enum with data

### ISSUE THREAD

**Issue by A-Walrus** [helix-editor/helix#3121]
### Summary

The syntax highlighting is weird in this example, `Some` is in white, while `None` is green (monokai theme).
![image](https://user-images.githubusercontent.com/58790821/180004906-95d2d341-ab5a-4444-9970-2c7b914021d0.png)

### Reproduction Steps

 

I tried this:

1. `hx`
2. write some code with match, like this: 
```
fn main() {
    let opt = Some(5);
    match opt {
        Some(a) => {}
        None => {}
    }
}

```
I expected this to happen:
Both `Some` and `None` are highlighted in the same way.

Instead, this happened:
`Some` is white, while `None` is green

### Helix log

<details><summary>~/.cache/helix/helix.log</summary>

```
please provide a copy of `~/.cache/helix/helix.log` here if possible, you may need to redact some of the lines
```

</details>

### Platform

Linux

### Terminal Emulator

Kitty, Alacritty

### Helix Version

helix 22.05

**Comment by erasin** [comment]
maybe the theme configuration problem，
cd `~/.config/helix` make `themes` folder ,copy your theme from `runtime/themes/`, and check content 

```toml
"constructor" = { fg = "green" }
```
reload hx or input command `:config-reload`
