### ISSUE TITLE
An `extend_*` version of every `move_*` or `goto_*` command.

### ISSUE THREAD

**Issue by perlinm** [helix-editor/helix#3122]
#### Describe your feature request

The following exist: `extend_char_[left/right]`, `extend_line_[up/down]`, `extend_to_line_[start/end]`, as well as the `extend_next_word_[start/end]`.

What happened to, for example, `extend_to_[prev/next]_paragraph`?  I use this sort of text selection ubiquitously.

**Comment by perlinm** [comment]
Nevermind.  Looks like `goto_*` commands select text as the cursor moves (in `select_mode`), while `move_*` commands have `extend_*` version.  I'm not sure the way this all works makes sense to me, but I can configure `helix` to do what I want, so I'll close this issue.

**Comment by eugenesvk** [comment]
How did you configure to move to the start/end of a paragraph without selection? There is no `move_prev_paragraph`

**Comment by perlinm** [comment]
@eugenesvk sorry I saw your question but could not answer at the time, and then forgot about it!

You can compose commands, for example: `A-e = ["goto_next_paragraph", "collapse_selection"]`.

**Comment by eugenesvk** [comment]
No worries and thanks for the tip! (I've meanwhile opened an issue https://github.com/helix-editor/helix/issues/6604 asking for some consistency as it's a bit confusing)
