### ISSUE TITLE
Add syntax highlighting support for Powershell scripts

### ISSUE THREAD

**Issue by lucypero** [helix-editor/helix#3123]
#### Describe your feature request

*Edit:* The following tree-sitter grammar doesn't work:
Treesitter: https://github.com/powershell/tree-sitter-powershell

**Comment by AceofSpades5757** [comment]
That package looks... empty

**Comment by AceofSpades5757** [comment]
I wasn't able to get it to work either. I'm not even sure why and I'm not sure if we'll ever know why.

**Comment by lucypero** [comment]
> I wasn't able to get it to work either. I'm not even sure why and I'm not sure if we'll ever know why.

I am trying with a fork I made of the tree-sitter grammar. I think I'll make it work soon.

**Comment by AceofSpades5757** [comment]
I created an issue with them. Hopefully, they'll get it sorted as well.

https://github.com/PowerShell/tree-sitter-PowerShell/issues/8

**Comment by the-mikedavis** [comment]
It looks like that grammar is a work-in-progress based on the TODOs in the README, and it has a generation failure on the latest `tree-sitter-cli` as you noted. That project most likely needs some contributions to be more complete, or a new attempt (that one looks a bit dated).

**Comment by AceofSpades5757** [comment]
It almost looks abandoned, although I'd be a bit surprised seeing as it should be the "official" one.

**Comment by lucypero** [comment]
So, I started adding highlight queries on my fork, then I realized that the parser parsed my powershell file all wrong. Someone probably should start to do the grammar from scratch. This one is just broken. I might do it one day.

**Comment by lucypero** [comment]
[This PDF](https://manning-content.s3.amazonaws.com/download/2/4aee82f-9192-4e50-941f-4bfde960b998/AppCexcerpt.pdf) describes the PowerShell grammar. This will be very helpful when making the tree-sitter grammar.

**Comment by Joe-Zer0** [comment]
This looks like an active LSP for PowerShell - https://github.com/PowerShell/vscode-powershell.  But I'm unsure how to install it use it with Helix.

**Comment by daephx** [comment]
> This looks like an active LSP for PowerShell - https://github.com/PowerShell/vscode-powershell. But I'm unsure how to install it use it with Helix.

I don't recall if it has semantic highlighting but I've used it in neovim. The repo states in the first few paragraphs of the README that the vscode extension is basically a wrapper for [PowerShellEditorServices](https://github.com/PowerShell/PowerShellEditorServices) if that helps you search for helix specific references.

**Comment by Joe-Zer0** [comment]
Thanks. I've spent a few hours searching for "helix powershell".  Unfortunately, this thread is about the only thing that comes up. Up till now all the LSP's I needed have been available through npm, cargo, pip. So getting this thing installed will be the first step.

**Comment by Joe-Zer0** [comment]
@lrottach - Thank you, that's exactly what I needed!
I also found this - https://github.com/PProvost/vim-ps1 - which looks like it could be helpful in configuring syntax highlighting.  But I'm in too far over my head to do anything with it.

**Comment by LucasWagler** [comment]
The tree-sitter site now mentions [this grammar](https://github.com/airbus-cert/tree-sitter-powershell) from Airbus CERT.
