### ISSUE TITLE
Key input not working on master branch

### ISSUE THREAD

**Issue by wojciechkepka** [helix-editor/helix#313]
I made a fresh clone of helix and input doesn't work. One get's completely locked out and has to kill the process from another terminal.

**Comment by wojciechkepka** [comment]
I just verified and it stopped working as of ca806d4

**Comment by sudormrfbin** [comment]
> I just verified and it stopped working as of [ca806d4](https://github.com/helix-editor/helix/commit/ca806d4f852e934651132fc9570a6110e30f646d)

I can't reproduce this; is there anything specific to be done ?

**Comment by wojciechkepka** [comment]
Hmm, I think its cause by my settings. I have:
```toml
[keys.normal]
S-v = "select_line"
```
in my `config.toml`, when I deleted it everything works as expected.

**Comment by pickfire** [comment]
Ah, I know why. Because currently if config keys exists it overrides all the keys.

**Comment by archseer** [comment]
Reverted the commit.

**Comment by pickfire** [comment]
Fix in https://github.com/helix-editor/helix/pull/345, need to do this since I need it for autoinfo, I was planning to delay it but it hit me T_T
