### ISSUE TITLE
Piping large amounts of text into head causes Broken pipe (os error 32)

### ISSUE THREAD

**Issue by A-Walrus** [helix-editor/helix#3133]
### Summary

Might be related to #3127 
Piping large amounts of text into `head` causes a broken pipe, 
Smaller amounts of text work.

(I don't think piping into `head` within a text editor is particularly useful, but this might be a problem when piping other commands as well...)

### Reproduction Steps

 

I tried this:

1. `hx`
2. open a large text file, ie [frankenstein](https://raw.githubusercontent.com/asweigart/codebreaker/master/frankenstein.txt)
3. select a lot of text, (doesn't have to be the entire file)
4. use the pipe command `|` and pipe it into head

I expected this to happen:
Only the first ten lines remain

Instead, this happened:
File doesn't change, error message `Broken pipe (os error 32)`

### Helix log

<details><summary>~/.cache/helix/helix.log</summary>

```
please provide a copy of `~/.cache/helix/helix.log` here if possible, you may need to redact some of the lines
```

</details>

### Platform

Linux

### Terminal Emulator

Kitty

### Helix Version

helix 22.05

**Comment by MDeiml** [comment]
My guess is that this happens, because we write the entire file to `stdin` before reading `stdout`.

**Comment by MDeiml** [comment]
See https://github.com/helix-editor/helix/blob/76756f0e5de2cb5e753fb49933ba47f2386c4701/helix-term/src/commands.rs#L4429

**Comment by AceofSpades5757** [comment]
Confirmed this issue on Windows as well: `The pipe has been ended. (os error 109)`

**Comment by AceofSpades5757** [comment]
Assuming that #3180 pull request looks good, it should resolve this.
