### ISSUE TITLE
Paste from clipboard doesn't work over SSH

### ISSUE THREAD

**Issue by enkodr** [helix-editor/helix#3144]
### Summary

Pasting from the clipboard works over SSH in insert mode with the standard OS terminal paste (CTRL+Shift+P) but doesn't work with the shortcuts Space+P or Space+p.

I'm also using Helix inside the machine that I'm accessing through SSH.

### Reproduction Steps

 

I tried this:

1. `ssh user@host`
2. `hx`
3. `Space+p`

I expected this to happen:
The text that was on the clipboard would appear in the document.

Instead, this happened:
Nothing happened.

### Helix log

<details><summary>~/.cache/helix/helix.log</summary>

```
The are no logs related with the paste
```

</details>

### Platform

Linux on both host and server

### Terminal Emulator

Gnome terminal

### Helix Version

helix 22.05 (19e51c82)

**Comment by archseer** [comment]
https://github.com/helix-editor/helix/issues/247

**Comment by mbratch** [comment]
> Pasting from the clipboard works over SSH in insert mode with the standard OS terminal paste (CTRL+Shift+P)

This doesn't work for me. I'm using putty to do ssh from Windows to my linux machine. I have not yet found a command which allows me to copy (from) or paste (into) a helix edit session whether in insert mode or not.

**Comment by dkonsoul** [comment]
A bit late to the party, but I am facing the same issue. Copy-pasting using control-c control-v or right clicking while on windows, connected via ssh to my linux machine either over putty or cygwin did not work inside helix editor.

While I did not find a solution to copy text from helix, I was able to paste inside helix, using shift-insert. (The equivalent control-insert to copy, did not work).
