### ISSUE TITLE
Indent attributes and methods of class on the symbol picker

### ISSUE THREAD

**Issue by seongs1024** [helix-editor/helix#3152]
## Current symbol picker looks like

![image](https://user-images.githubusercontent.com/56729421/180469258-001e4c0c-2fa4-4616-8ed8-e07e1708be77.png)

All of symbols are displayed on the same level on the symbol picker.
e.g.

```
ProgressBar
progress
Gauge
range
done
main
```

## Feature request:
it might be able to look better if attributes and methods will be indented.
e.g.
```
ProgressBar
    progress
Gauge
    range
    done
main
```

**Comment by sudormrfbin** [comment]
That would effectively be a symbol tree; a tree widget is being worked on in #2377, until then https://github.com/helix-editor/helix/pull/2452 might be of relevance.

**Comment by seongs1024** [comment]
Awesome, I'm looking forward it.
Thank you!
