### ISSUE TITLE
Support `Alt+<key>` to act as `ESC <key>` (ref: Emacs/Neovim/Iterm2)

### ISSUE THREAD

**Issue by goyalyashpal** [helix-editor/helix#3162]
### Details
* `alt` + `key` or say `Alt-<key>` in insert mode should perform the
* ... equivalent of `esc` > `key` or say `Esc <key>` i.e. `esc` to exit, then `key`
* ... if `alt` + `key` "does not have an insert-mode mapping."

Examples from `nvim`:
| from insert mode      |                                       |               |
| --------------------- | ------------------------------------- | ------------- |
| enter command mode    | `esc` > colon (`shift` + `semicolon`) | `alt` + colon |
| move to start of line | `esc` > `0`                           | `alt` + `0`   |
| move to end of line   | `esc` > $ (`shift` + `4`)             | `alt` + $     |

* \> means then i.e. leave the previous key
* \+ means keep previous key pressed
* note: in nvim, it doesn't return to insert mode, and stays in command mode after this action too

### Reference:

Question for achieving this via config: https://github.com/helix-editor/helix/issues/3162#issuecomment-1339666582

Quoting/citations for this behaviour from other editors
* Emacs: https://github.com/helix-editor/helix/issues/3162#issuecomment-1328184104 
* Neovim: https://github.com/helix-editor/helix/issues/3162#issuecomment-1365866453
* Iterm2: https://github.com/helix-editor/helix/issues/3162#issuecomment-1399958131

### Title and Summaries:

alternate rephrasals of the issue:
* Support Alt key-chords to act like ESC (ref: Neovim/Emacs)
* Support Alt key-chords to act like Esc
* Provide "Meta character" support for the two-character sequences starting with ESC like Nvim/emacs
* alt modifier to function as a modifier to escape edit mode similar to neovim

**Comment by the-mikedavis** [comment]
I'm not sure we get enough events from crossterm to implement this: alt and shift are both modifiers so I don't think we get a KeyEvent for them being pressed/held in conjunction

**Comment by sudormrfbin** [comment]
I don't think neovim has this shortcut either? It does have `ctrl-[` which works because it gets interpreted as Escape, similar to how `ctrl-i` gets interpreted as Tab.

**Comment by yashpalgoyal1304** [comment]
> I don't think neovim has this shortcut either

umh, maybe it just uses alt for that.

anyways, the instance is that: inside nvim, say i am in edit mode, then either i do: `esc` > `⇑;` (i.e. `:`) or i do `alt + ⇑;` both have same effect of landing me to the command mode

**Comment by yashpalgoyal1304** [comment]
i retried `nvim` today to get a refresher. so: 
* pressing alt doesn't do anything on its own
* rather `alt` acts as a modifier with other key combinations, i.e. `alt` + `key`
* what it does when used in insert mode is that it exits insert mode, and performs the action of the `key`
* as compared to the normal procedure of `esc` to exit, then to press the corresponding `key`

| from insert mode      |                                       |               |
| --------------------- | ------------------------------------- | ------------- |
| enter command mode    | `esc` > colon (`shift` + `semicolon`) | `alt` + colon |
| move to start of line | `esc` > `0`                           | `alt` + `0`   |
| move to end of line   | `esc` > $ (`shift` + `4`)             | `alt` + $     |

* \> means then i.e. leave the previous key
* \+ means keep previous key pressed
* note: it stays in command mode after this action too

**Comment by yashpalgoyal1304** [comment]
i have added my clarifications in the description, sorry for the confusion created earlier.

offtopic Prasies:
* thanks a lot for making the system clipboard to work out of the box. 
* and also showing the popup completion lists when in command mode, or i guess it shows up in normal mode too (like in the bottom right corner when i press `[` or `]`)
* nice to know that the bash's emacs styled shortcuts work in the command mode 😆 

very few issues remain so far: 
* no option for soft-wrap??
* this above issue
* it doesn't launch when using via msys2's bash

**Comment by yashpalgoyal1304** [comment]
ping

**Comment by the-mikedavis** [comment]
Please don't ping :)

The keys in the description can be bound with config:

```toml
# ~/.config/helix/config.toml
[keys.insert]
"A-:" = "command_mode"
"A-0" = "goto_line_start"
"A-$" = "goto_line_end"
```

**Comment by yashpalgoyal1304** [comment]
> Please don't ping :)

umh, sorry, what?

**Comment by yashpalgoyal1304** [comment]
> Please don't ping :)

umh, sorry, what?

**Comment by geometryolife** [comment]
This is the keymap I use most to move the cursor position in edit mode.

![289B7CD6-2A97-4EF8-8F2D-89753BFEDB43](https://user-images.githubusercontent.com/54882546/197370907-ae5b04b3-70d3-4254-a47f-0ba6d01c315e.jpeg)

**Comment by yashpalgoyal1304** [comment]
* while i have been searching for this today for https://github.com/TeamNewPipe/NewPipe/pull/9471, 
* I found via [emacs notation] manual --> [User Input] that the duality of ESC and Alt key behaviour i was describing is actually the norm as quoted below:
* by duality, i mean that is: 
`ESC <key>` (escape then key) is equivalent to `M-<key>` (hold alt while key)
* notice the space vs hyphen:
    * space means `leave then press`, 
    * hyphen means `hold while pressing`


[emacs notation]: https://www.emacswiki.org/emacs/EmacsKeyNotation
[User Input]: http://www.emacswiki.org/info-ref?find=User%20Input
[User Input (GNU Emacs Manual)]: https://www.gnu.org/software/emacs/manual/html_node/emacs/User-Input.html
[highlighted link]: https://www.gnu.org/software/emacs/manual/html_node/emacs/User-Input.html#:~:text=Meta%20characters%20using%20two%2dcharacter%20sequences%20starting%20with%20ESC

Refer/quote: 
[User Input (GNU Emacs Manual)] - list/bulleting is mine:

> * You can also type Meta characters using two-character sequences starting with ESC ([highlighted link]). 
> * Thus, you can enter M-a by typing ESC a. 
> * You can enter C-M-a (holding down both Ctrl and Alt, then pressing a) by typing ESC C-a. 
> * Unlike Meta, ESC is entered as a separate character. You don’t hold down ESC while typing the next character; instead, press ESC and release it, then enter the next character. 
> * This feature is useful on certain text terminals where the Meta key does not function reliably.

**Comment by yashpalgoyal1304** [comment]
> The keys in the description can be bound with config:
\- @ the-mikedavis https://github.com/helix-editor/helix/issues/3162#issuecomment-1287805037

```toml
# ~/.config/helix/config.toml
[keys.insert]
"A-:" = "command_mode"
```

is there some way for me to set this "Meta character/modifier" scheme as a substitute for all the two-character sequences starting with ESC, or will I have to add the shortcuts in the configuration for every one of them??

**Comment by yashpalgoyal1304** [comment]
hey, i can't understand this, can someone explain it to me? i was watching a video about helix, and it says the following.  i asked back there, but didn't get any response.

> use this esc binding
there are three ways to 'escape' in helix, this makes it one way. it's a great keybinding for beginners


```toml
# ~/.config/helix/config.toml
[keys.normal]
esc = ["collapse_selection", "keep_primary_selection"]
```

**Comment by yashpalgoyal1304** [comment]
> I don't think neovim has this shortcut either?
>
> \- @ _sudo rm rf bin_ at https://github.com/helix-editor/helix/issues/3162#issuecomment-1195149552

aah yes, found it:

```
1. Special keys						*ins-special-keys*

... MORE ...

char		action	~
-----------------------------------------------------------------------
... MORE ...
						*i_META* *i_ALT*
		ALT (|META|) may act like <Esc> if the chord is not mapped.
		For example <A-x> acts like <Esc>x if <A-x> does not have an
		insert-mode mapping.
```

```
ALT (META) key-chords always work in Nvim
 ...
 Nvim 0.3 mimics the Vim behavior while still fully supporting ALT mappings. See `:help i_ALT`.
```

trail: found via following links from helix's documentation itself 😆

* https://github.com/neovim/neovim/blob/4aec442b5af5a1a7c3aa47626fee09452117575e/runtime/doc/insert.txt#L41-L44
* <-- `help :i_ALT` < `nvim`
* <-- Neovim FAQ: [`esc`-in-tmux]
* <-- Helix Troubleshooting: [hitting-escape]
* <-- helix README.MD


[`esc`-in-tmux]: https://github.com/neovim/neovim/wiki/FAQ#esc-in-tmux-or-gnu-screen-is-delayed
[hitting-escape]: https://github.com/helix-editor/helix/wiki/Troubleshooting#when-using-tmux-or-screen-there-is-a-delay-after-hitting-escape-before-its-registered

**Comment by yashpalgoyal1304** [comment]
third reference: Iterm2 (again, found from helix documentaion itself)

> Ensure that you have mapped the Option key to `ESC+` ...
\- https://github.com/helix-editor/helix/wiki/FAQ#alt--key-combinations-do-not-work-on-macos-iterm2

> I'd like to be able to skip words in the terminal with Option + Left Arrow/Right Arrow
\- iTerm2 cheat sheet: https://gist.github.com/squarism/ae3613daf5c01a98ba3a?permalink_comment_id=3409831#gistcomment-3409831
\- "Mac OS Terminal Tips with iTerm2" - [LcelO7XErdA](https://www.youtube.com/watch?v=LcelO7XErdA)

**Comment by goyalyashpal** [comment]
hey helix team members! can you please add just this one feature?? i humbly request you to please consider this 😢

**Comment by goyalyashpal** [comment]
* everything is a niche part-1:
#6551 #7519 
* lol, seems same as Bram Moolenaar with vim

**Comment by pascalkuthe** [comment]
you can map this if you want but we are not going to change the default map
