### ISSUE TITLE
Dockerfile syntax

### ISSUE THREAD

**Issue by hholst80** [helix-editor/helix#3166]
### Summary

HERE document parsing does not work

Example

```Dockerfile
FROM ubuntu:20.04
RUN <<EOF
  apt-get update
  apt-get install tree
EOF
RUN tree /tmp
```

The last line will not color correctly.

### Platform

Linux

### Terminal Emulator

xterm-256color

### Helix Version

helix 22.05 (27609f50)

**Comment by amitbeka** [comment]
Validated this on the most recent version: helix 22.05 (dfc31e74)

**Comment by amitbeka** [comment]
It is an upstream bug in the treesitter grammar itself, unfortunately: https://github.com/camdencheek/tree-sitter-dockerfile/issues/4

**Comment by hholst80** [comment]
I might have been wrong about what exactly is causing the problem. Maybe it is the RUN options rather than the HERE document: Screenshot here:

![image](https://user-images.githubusercontent.com/6200749/180614965-038fb192-667c-4268-a7d0-ec5f542d4959.png)

**Comment by hholst80** [comment]
There is a workaround, but I think its brittle and ugly to have to use the backslashes all over

![image](https://user-images.githubusercontent.com/6200749/180615037-d323d588-46ae-43bf-a88c-7a60bde87d36.png)

**Comment by amitbeka** [comment]
There is no heredoc in this screenshot, so the problem doesn't exist. If you mean to use backslashes and `&&` instead of a heredoc -- yeah that's always possible, I'm very used to it.

**Comment by danielrode** [comment]
> It is an upstream bug in the treesitter grammar itself, unfortunately: [camdencheek/tree-sitter-dockerfile#4](https://github.com/camdencheek/tree-sitter-dockerfile/issues/4)

Looks like this was fixed upstream a couple months ago. When will these changes land in Helix?

**Comment by tangowithfoxtrot** [comment]
It seems that there have been fixes for this that were merged, but they don't seem to be applied in the latest version of Helix? I'm kind of confused about the status of this issue.

If the fixes are not applied, is there a way that I can apply them myself in my config files?
