### ISSUE TITLE
Wiki page "Keymap brainstorm" has incorrect image

### ISSUE THREAD

**Issue by Zentropivity** [helix-editor/helix#3199]
On the [Keymap brainstorm](https://github.com/helix-editor/helix/wiki/Keymap-brainstorm) wiki page, the current keymap image is incorrect:  
in the Defaults section there is another `W` key instead of an `E`.

**Comment by Zentropivity** [comment]
![image](https://user-images.githubusercontent.com/73995561/181180268-51fa9d37-7f1c-4109-bd59-0bb1c5bc54cd.png)

**Comment by the-mikedavis** [comment]
I think we don't use that page as much as we used to - it was meant to be a community-editable collection of thoughts on the keymap. It might make sense to transfer over the existing content there to the keymap discussion issue? #165
