### ISSUE TITLE
Enable key bindings for `Prompt`s (such as `search:` and `select:`)

### ISSUE THREAD

**Issue by perlinm** [helix-editor/helix#3205]
#### Describe your feature request

I often want to search for or select text that I have stored in my clipboard, so a keybinding to `paste_*` would be nice (although I realize that this might not play nicely with `select_regex`).  I also often type something into `search:` or `select:` only to find that I made a 1-character typo 7 characters ago; it would be nice to go back with `move_char_left` (without the mouse or arrow keys...) to fix the typo.

**Comment by AceofSpades5757** [comment]
It sounds like you're requesting the ability to remap keys in the `Prompt` mode, correct? There are already some key maps available, like _Select previous history_, but it would be nice to be able to remap these.

[Helix Editor - Keymap](https://docs.helix-editor.com/keymap.html#prompt)

[Helix Editor - Keymap (master)](https://docs.helix-editor.com/master/keymap.html#prompt)

**Comment by perlinm** [comment]
Ah.  Yes, I would like the ability to remap these (and to add other keybindings) :slightly_smiling_face:
