### ISSUE TITLE
Accessibility Improvement - High Contrast Theme

### ISSUE THREAD

**Issue by jquesada2016** [helix-editor/helix#3217]
#### Describe your feature request

As a legally blind developer, one most often needs to create a custom theme in order to see everything. I believe it would be a really good idea to include a default high contrast theme for both dark and light modes out of the box. For dark mode, VS Code's default high contrast theme is very good, as is Android Studio/IDEA's. For light mode, Windows ships with a light high contrast theme which is also excellent.

**Comment by GreasySlug** [comment]
I created #3238, and could anyone help me, please?
