### ISSUE TITLE
Show pseudo-pending text for `ms`/`mr`/`md` commands

### ISSUE THREAD

**Issue by AceofSpades5757** [helix-editor/helix#3223]
#### Describe your feature request

Add contextual pop-ups, just like when the `Match` box pops up after pressing `m` for when Helix is waiting for the input to the next command, like `Surround delete`.

So, after a user presses `m` and then `d` to do a surround delete, it would be nice to have another box either show their available options, or at least give some instructions on what to do next. This could also help with more advanced subcontexts, such as if there was a regex surround delete.

![image](https://user-images.githubusercontent.com/10341888/181428593-28f6edcf-0feb-40c6-bc84-ebbcbe5560b3.png)

**Comment by the-mikedavis** [comment]
Surround-delete works on the character pressed after `md`. There isn't any need to add future expressive power to surround-delete; you can use sub-selections (`s`) to achieve anything you would want with a regex or special characters.

**Comment by AceofSpades5757** [comment]
@the-mikedavis Thanks. Instead of a pop-up, some sort of indicator would be nice to show that Helix is waiting for additional input to finish the command.

**Comment by AceofSpades5757** [comment]
What about the keys, on the bottom-right of the window, staying until either an input, or canceling?

This is what it looks like after hitting `m` to open the Match context menu. 

![image](https://user-images.githubusercontent.com/10341888/183778865-453fe3fb-d624-4c26-b347-baa8c91875cc.png)

This character(s) is removed when pressing things like `d` for surround delete, or `r` for replace. It would be nice to leave these keys there to indicate that the user is still in the middle of a key sequence.

![image](https://user-images.githubusercontent.com/10341888/183779279-9cd20184-ae47-4767-880b-259a1ab9e1e3.png)

**Comment by the-mikedavis** [comment]
Pseudo-pending seems appropriate for this, especially since we use it elsewhere with `m` commands 👍

If you'd like to take a shot at this, the field is `pseudo_pending: Option<String>` and you can find an example usage in `helix_term::commands::select_textobject`.

**Comment by AceofSpades5757** [comment]
I'll take a crack at it.
