### ISSUE TITLE
html indent spacing

### ISSUE THREAD

**Issue by 7flash** [helix-editor/helix#3225]
When typing html tags it does automatically insert incorrect spaces.

![image](https://user-images.githubusercontent.com/4569866/181491407-6b80a12f-5629-4b7c-b9ab-1c2d0e1cc3c0.png)

Then manually edited to expected result.

![image](https://user-images.githubusercontent.com/4569866/181491614-3a1e9c47-5572-4246-a6df-a143e8898372.png)

**Comment by 7flash** [comment]
How to make it formatting html correctly? Like on second screenshot (expected), instead of first one (current behaviour)

**Comment by the-mikedavis** [comment]
Which version are you using? The indentation mechanism was overhauled after the 22.05 release and I don't think the above indents occur anymore.

**Comment by 7flash** [comment]
Just installed 22.05 
![Uploading image.png…]()

**Comment by 7flash** [comment]
Where could I find windows build of later version?

**Comment by the-mikedavis** [comment]
You can build from source: https://docs.helix-editor.com/master/install.html

The 22.07 (July 2022) release should be out in the next few days however.

**Comment by the-mikedavis** [comment]
Oh actually the indentation rework was released in 22.05.

This looks like https://github.com/helix-editor/helix/issues/2236

Did you paste in the html with ctrl-v / cmd-v or type it in manually?

**Comment by 7flash** [comment]
Typing manually.
