### ISSUE TITLE
Add option to change cursor shape on mode change

### ISSUE THREAD

**Issue by sudormrfbin** [helix-editor/helix#323]
An option similar to neovim's `'guicursor'` is something I miss, which can for example change the cursor to bar for insert and back to block on normal and selection mode.

**Comment by archseer** [comment]
This is a terminal limitation: it only has one cursor so we can only change shape of the primary selection. I had that initially but removed it for the sake of consistency.

**Comment by sudormrfbin** [comment]
It's a very easy way to be aware of the mode you're in, and we could mention in the docs that only the primary selection's cursor will change. Also a question: will the primary cursor always be visible in the screen, even with multiple selections ?

**Comment by teenjuna** [comment]
I agree with @sudormrfbin. This is actually a very useful feature that I also miss. However, perhaps we might think of another way to help the user quickly understand in which mode he currently is without looking on the bottom left or trying to type something. Even changing the color of the mode's indicator will enable the user to use his peripheral vision and understand the mode faster.

**Comment by pickfire** [comment]
I tried this, currently it's broken. Although it did change the style, it breaks IME input, try typing in some japanese text then you know what I am saying, but it works fine for ascii.

**Comment by DrZingo** [comment]
I have different shapes and different color on my cursor in vim. `blue block` = normal, `green bar` = insert, `red underscore` = replace. But I find it more useful to have different colors in the statusbar for each mode.
![image](https://user-images.githubusercontent.com/6590732/123001428-031f7f00-d3b1-11eb-9819-f5ef47b7ae2c.png)
![image](https://user-images.githubusercontent.com/6590732/123001451-0c105080-d3b1-11eb-87bd-531324dba47d.png)
![image](https://user-images.githubusercontent.com/6590732/123001494-16cae580-d3b1-11eb-8a3c-0b8db0d13a84.png)

**Comment by pickfire** [comment]
I tested again, seemed to work with IME. But the color is a bit weird, maybe need to have different theme.

**Comment by sudormrfbin** [comment]
I'm going to take a stab at this and see how it turns out.

**Comment by pickfire** [comment]
@sudormrfbin I did test this locally and work. But I think you might want to change the theming along with this, it looks ugly if you only change the cursor shape based on mode. I think we should have sort of a new mode for replace so we can use the `_` cursor.

One more issue I have when I tested it out is only the main cursor will change shape but other cursors is the same block shape, which looks ugly. Not sure how to fix it.

**Comment by sudormrfbin** [comment]
@pickfire Yeah the theming looks weird with it so I made some changes (in the rendering code itself):

![command](https://user-images.githubusercontent.com/23398472/123509019-bc6fa480-d690-11eb-9739-aad0830ba2ae.gif)

- Selections are not _rendered_ when in insert mode - they are shown again after exiting insert mode (IMO this should've been the default, selections in insert mode look distracting) 
- Cursor styling is removed for the primary cursor only in insert mode when it's bar (otherwise a `bg = "#ffffff"` will look like a block cursor and bar cursor combined)

> One more issue I have when I tested it out is only the main cursor will change shape but other cursors is the same block shape, which looks inconsistent and made it ugly. Not sure how to fix it.

We can't do anything here since it's a limitation of the terminal itself, so the best thing we can try is to change the primary cursor to a bar and make the others look like a block cursor.

**Comment by pickfire** [comment]
I wonder if there's sort of hack we can do to display a bar. Maybe we just replace the last character with a bar for all other cursors?

**Comment by sudormrfbin** [comment]
Replacing seems a bit too drastic and hacky, and there were some discussions (that were abandoned) in https://github.com/kovidgoyal/kitty/issues/720 and https://github.com/mawww/kakoune/issues/2194 regarding an xterm extension for supporting multiple cursors.

**Comment by pickfire** [comment]
i wonder @Kethku would be interested in this.

**Comment by archseer** [comment]
> One more issue I have when I tested it out is only the main cursor will change shape but other cursors is the same block shape, which looks inconsistent and made it ugly. Not sure how to fix it.

This was discussed earlier in this thread, it's a terminal limitation sadly. I had the shape changes built in but later removed them.

**Comment by bestouff** [comment]
Really in nvim the three shapes of cursor to tell which mode is the current one without having to look at the status bar (and find the cursor position back, which is uneasy on big terminals) are very ergonomic. It's a big loss.

**Comment by bestouff** [comment]
Moreover: the terminal often changes the cursor on focus entering/exiting (hover) the terminal. One more ergonomic feature lost with "hand-made" cursors.  
Maybe do like in (n)vim in ctrl-V mode, where multiple lines are selected but the terminal cursor is still part of one line:
![select](https://user-images.githubusercontent.com/1163188/143264815-5ce59f8a-426b-48d7-8dbe-486bdddd6068.png)

**Comment by sudormrfbin** [comment]
#1154 uses the real terminal cursor as the primary cursor and draws the other cursors, so that problem would be solved.
