### ISSUE TITLE
Syntax highlighting sometimes broken when started

### ISSUE THREAD

**Issue by Philipp-M** [helix-editor/helix#3230]
### Summary

Sometimes the highlight queries seem to be broken (tested with typescript):

Broken (note the `@type` highlighting for `const` or `type`, although, I've checked none of the `@type` queries should match `const` or `type`):

![syntax_highlighting_issue](https://user-images.githubusercontent.com/9267430/181586796-8affe252-0d38-4524-9240-ae9a5584388c.png)

Correct:

![syntax_highlighting_issue_correct](https://user-images.githubusercontent.com/9267430/181586817-dcc0d745-14e2-4617-872e-e11d63fd51d3.png)

Seems to happen roughly 50% of the time.

This may be related or even a duplicate to/of https://github.com/helix-editor/helix/issues/2484

Tested with this script:

```typescript
const constant = "const";

namespace some.namespace {
  function something() {}
}

declare namespace GreetingLib.Options {
  // Refer to via GreetingLib.Options.Log
  interface Log {
    verbose?: boolean;
  }
  interface Alert {
    modal: boolean;
    title?: string;
    color?: string;
  }
}
type MyGreeter = () => number;

type GreetingLike = string | (() => string) | MyGreeter;
declare function greet(g: GreetingLike): void;
``` 

### Reproduction Steps

Start helix with the script above

### Platform

Linux

### Terminal Emulator

alacritty

### Helix Version

22.05-324-g681c0a91

**Comment by the-mikedavis** [comment]
Yeah, this is most likely another reproduction case of https://github.com/helix-editor/helix/issues/2484

See also https://github.com/helix-editor/helix/issues/2986
