### ISSUE TITLE
Overwrite smart-case during search

### ISSUE THREAD

**Issue by jacksonludwig** [helix-editor/helix#3235]
#### Describe your feature request

In vim, having `\c` somewhere in your search will disable smart case for that search only. I did not notice any equivalent behavior yet in helix and think it would be a good addition at some point.

Thanks.

**Comment by kirawi** [comment]
https://docs.rs/regex/latest/regex/#grouping-and-flags
`(?i)` should make it case insensitive

**Comment by the-mikedavis** [comment]
It looks like `(?-i)` will make it case-sensitive

**Comment by jacksonludwig** [comment]
Thanks! Just saw that `?-i` is insensitive as well.

**Comment by sudormrfbin** [comment]
A link to the regex crate's documentation in the helix book would be a good addition.

**Comment by sudormrfbin** [comment]
A link to the regex crate's documentation in the helix book would be a good addition.
