### ISSUE TITLE
Pipe only preloads your last command once

### ISSUE THREAD

**Issue by EricCrosson** [helix-editor/helix#3246]
## What I did

1. open `hx`
1. press `|` and type a command, say `fmt -72`
1. press `|` again (this preloads as a default command, the last command I ran (`fmt -72`)). Hit enter
1. press `|` again

## What I Expected to Happen

The `pipe` prompt would again preload as a default command the last command I ran, which was the preloaded `fmt -72`

## What Actually Happens

The `pipe` prompt has no preloaded text (possibly because I didn't type anything before I hit `enter` last time!)

### Reproduction Steps

https://asciinema.org/a/ZcpjTOOH3p1v9TEgtzPnu2dSe

### Helix log

n/a

### Platform

Linux (Ubuntu 22)

### Terminal Emulator

kitty

### Helix Version

26501afe

**Comment by the-mikedavis** [comment]
It looks like this happens for all prompts, for example with search as well.

https://github.com/helix-editor/helix/blob/a8b123fe177d8cd7f5a610a0a50c16c9f64069bd/helix-term/src/ui/prompt.rs#L528-L547

We should probably check that `self.line` is not empty before pushing it to the history register.
