### ISSUE TITLE
clipboard-paste-* doesn't paste

### ISSUE THREAD

**Issue by adsnaider** [helix-editor/helix#3251]
### Summary

I copy something outside of the editor into my clipboard. When I try to paste it using the clipboard-paste-after command (or before), nothing happens.

For the record, using C-Shift-v on insert mode seems to paste, however, the paste is very wonky as it is very slow and indentation is usually ruined.

### Reproduction Steps

 

I tried this:

1. `hx`
2. Copy something to clipboard outside of helix
3. `:clipboard-paste-after` -> nothing happens
4. `primary-clipboard-paste-after` -> nothing happens

I expected this to happen:

Text to be pasted into the buffer.

Instead, this happened:

Nothing...

### Helix log

There's no logging information.

### Platform

Linux

### Terminal Emulator

gnome-terminal

### Helix Version

helix 22.05 (27609f50)

**Comment by kirawi** [comment]
> For the record, using C-Shift-v on insert mode seems to paste, however, the paste is very wonky as it is very slow and indentation is usually ruined.

You're encountering #2239.

As for the pasting not working, [you might be missing a supported clipboard provider.](https://github.com/helix-editor/helix/wiki/Troubleshooting#on-linux)

**Comment by adsnaider** [comment]
Oh wow. Thank you. Things work well after installing xclip. I'm not sure if this is possible but it would be nice if helix displayed an error message that gives some info and links to that site.

**Comment by kirawi** [comment]
I've opened #3254
