### ISSUE TITLE
Prompt user to install a clipboard provider if one is not detected

### ISSUE THREAD

**Issue by kirawi** [helix-editor/helix#3254]
If a supported clipboard provider is not installed on the system, then it would be nice to prompt the user to install one of the supported providers for the OS.

**Comment by the-mikedavis** [comment]
There has been some prior discussion on this also talking about improving some of the messages for where selections are saved to (system clipboard, system selection clipboard) https://github.com/helix-editor/helix/issues/2615

**Comment by amitbeka** [comment]
I've started working on this, learning Rust as I go 😅 
Adding this to the healthcheck now, then I'll look into the error message in-app: #3271

**Comment by kirawi** [comment]
Closed by https://github.com/helix-editor/helix/pull/3271
