### ISSUE TITLE
Add theme variants

### ISSUE THREAD

**Issue by d12bb** [helix-editor/helix#3258]
## Proposal

Lots of themes have multiple variants (light/dark, hard/soft contrast, …). These are currently completely separate themes. I propose to support multiple variants inside one and the same theme, maybe like this:

```toml
# all the scopes ...

[palette_dark]
# dark variant

[palette_light]
# light variant
```

- Color names would be the same in all palettes.
- The first palette could be used as default when no variant is specified, or set to light/dark based on terminal background.
- In setting theme, base and variant could either be separated by whitespace (`:theme <base> <variant>`) or, to be compatible with current configs, by underscore (`:theme <base>_<variant>`). Lookup for underscore could be:
    1. Is there a theme named exactly this? Use it.
    2. Is there a theme named matching the requested string till the last underscore with a variant from last underscore to end? Use it.
    3. Else? Error.

## Pros
- Would get rid of duplication in the scopes section, as that's the same for all variants and wouldn't have to exist multiple times anymore.
- Would enable automatic switch light/dark based on terminal background. For example, Terminal.app on Mac uses system dark-mode setting for its own background (though I doubt anyone uses Terminal.app :D).
- Would make the `:theme` autocompletion menu shorter and clearer.
- Would make it more obvious to the user what are completely different themes and what are variants.

## Cons
- More complex.
- Low priority.
- Not all cases covered, some variants may require different scope settings.

**Comment by ChrHorn** [comment]
I like this idea. Theme variants are getting more common and are a bit of a pain to maintain with the current system. I would propose something like this:

```toml
[palette.default]
...
[palette.variant1]
...
[palette.variant2]
...
```
`palette.default` would replace the current `palette`, so this would be breaking for themes, but only in a minor way. Then just default to the `default` palette so it's not breaking for user configs. 

The light/dark switching (if implemented) should be done in the user config file. Don't think we should use the theme file for that.

**Comment by d12bb** [comment]
> `palette.default` would replace the current `palette`, so this would be breaking for themes, but only in a minor way. Then just default to the `default` palette so it's not breaking for user configs.

Default should only be a pointer though. Else a theme would either have variants default and light instead of dark and light or have one variant duplicated as default.

> The light/dark switching (if implemented) should be done in the user config file. Don't think we should use the theme file for that.

Of course, that was just an example of how this could be leveraged, not another suggested theme syntax extension.

**Comment by the-mikedavis** [comment]
IMO variants should be covered by theme extensions https://github.com/helix-editor/helix/issues/1469. A built-in concept for variants could be considered later when we have a more expressive config language (the TOML config system is temporary and will be replaced with something more powerful in the long-run).

**Comment by d12bb** [comment]
> IMO variants should be covered by theme extensions ~#1469~ #2454. A built-in concept for variants could be considered later when we have a more expressive config language.

Didn't see that one when searching before creating this issue. #2454 looks like a really nice proposal, covering variants among other things!

> (the TOML config system is temporary and will be replaced with something more powerful in the long-run)

I like TOML 🤷‍♂️
