### ISSUE TITLE
Clarify modes

### ISSUE THREAD

**Issue by teenjuna** [helix-editor/helix#327]
Looking at documentation, I see mentions of 7 mods:
- Normal
- Select
- Insert
- Goto
- Command
- View
- Window
- Space

However, only the first three are the items of the `Mode` enum. And that's understandable: why should `Goto`, `View`, `Window` and `Space` be considered modes? They look more like prefixes for groups of shortcuts. I'm not yet very familiar with the code base, so I don't know if I'm right here. Anyway, I find current naming very confusing.

The `Command` is different. I can surely see it being a mode. But is it?

**Comment by sudormrfbin** [comment]
Everything except the first three are indeed just prefixes. Maybe calling them "key layers" or something will be better.

**Comment by pickfire** [comment]
Yup, it's not really a mode but it is being called mode. "key layers" is better but not a lot better. I wonder what kakoune and doom emacs called them.

**Comment by teenjuna** [comment]
Perhaps "shortcut prefixes" or "action prefixes" will do?

**Comment by pickfire** [comment]
Maybe everyone can suggest a few and after I am done with the autoinfo box then I am going to use the one that has most thumbs up.

I suggest "keys".

**Comment by archseer** [comment]
I don't think you should pay attention to the enum, that's only for tracking major modes that are persistent and you need to use ESC to exit. Goto/view/window/space are all transient modes or submodes (of normal mode) that you enter for a single keypress to access some subset of functionality. Command mode is also a "mode" but it's somewhat special since it doesn't need to sit on the document.

**Comment by python128** [comment]
I would also like to keep the same word `mode` as you need to type <esc> to exit out of that `mode`.

**Comment by archseer** [comment]
I don't think there's anything actionable here, the way modes are laid out in the code is an implementation detail we don't want documented. The user docs can just keep treating every sub-mode as a mode.
