### ISSUE TITLE
How to select multiple words in sequence?

### ISSUE THREAD

**Issue by tapyu** [helix-editor/helix#3270]
I am afraid of being an obvious questions since it is pretty basic, but I have done the `helix` tutor and couldn't make out how to select `n` words in a row. For instance, in vim, `d3w` deletes the three next words. However, in `helix`, if I type `3w`, only the last word is selected. How to select the next three words to delete them?

if it is really not in the `helix` tutor, I suggest putting there.

Best regard.

**Comment by kirawi** [comment]
`v3w`

**Comment by tapyu** [comment]
@kirawi  This is not in the tutor, right? It must be there...

**Comment by kirawi** [comment]
It's there on master at least: https://github.com/helix-editor/helix/blob/e405e88c86ecf98ff432e7b95a0147ca3de97e3a/runtime/tutor.txt#L309-L324

**Comment by tapyu** [comment]
@kirawi For me this item does not exist.

![image](https://user-images.githubusercontent.com/22801918/183780938-eb1f48d5-fed0-413b-b81d-52843e7d9dbd.png)

I think it a version issue, mine is `helix 22.05`, thank you anyway :)

**Comment by a-berg** [comment]
in emac's Meow, you use numerics (1, 2, etc) to extend the selection to next word (or 2 words, etc). I find this way of working much more in the vein of "select first then decide what to do" than having to remember there's a visual mode and do the "vim thing" of first deciding how many words then using the verb.

just 2cts, not trying to push anything.
