### ISSUE TITLE
Cannot open file at line number

### ISSUE THREAD

**Issue by MyIsaak** [helix-editor/helix#3277]
When I run 
```bash
hx src/main.rs:30
```
Helix doesn't open the file at the line number 30. Instead it always opens at the top. 

This is useful for opening files from stack traces (specifiying the line number). Could this please be added?

**Comment by the-mikedavis** [comment]
What version are you running? This was recently fixed https://github.com/helix-editor/helix/issues/2989

**Comment by MyIsaak** [comment]
My bad. Updated to the latest version and now it works. Thanks!
