### ISSUE TITLE
set-option to list doesn't work

### ISSUE THREAD

**Issue by A-Walrus** [helix-editor/helix#3278]
### Summary

When trying to set an option to a list, for example setting `gutters` to `["line-numbers"]` it doesn't work.

### Reproduction Steps

 

I tried this:

1. `hx`
2. `:set-option gutters ["line-numbers"]`

I expected this to happen:
`gutters` option is set to `["line-numbers"]`

Instead, this happened:
Error: ```Bad arguments. Usage: `:set key field` ```

### Helix log

<details><summary>~/.cache/helix/helix.log</summary>

```
please provide a copy of `~/.cache/helix/helix.log` here if possible, you may need to redact some of the lines
```

</details>

### Platform

Linux

### Terminal Emulator

Kitty

### Helix Version

helix 22.05, also 22.05-336-g9f4802e1

**Comment by the-mikedavis** [comment]
Looks like https://github.com/helix-editor/helix/issues/2206?

**Comment by A-Walrus** [comment]
Duplicate of #2206
