### ISSUE TITLE
New commands `shrink_line_above` and `shrink_line_below`

### ISSUE THREAD

**Issue by s0LA1337** [helix-editor/helix#3279]
I have checked whether such an issue already exists, however haven't found anything.
If it's a duplicate, i am sorry.

#### Describe your feature request
Basically the reversed behaviour of `extend_line_above` and `extend_line_below`.
The current behaviour seems rather inconsistent (having to go to visual mode and then manually unselecting. on `extend_line_above` this behaviour isn't even possible), so i that's why i have this proposal.

on `shrink_line_above`, the line of the topmost selection will be unselected.
on `shrink_line_below` the line of the bottommost selection wil be unselected.

**Comment by the-mikedavis** [comment]
Using these to undo `extend_line_below` and `extend_line_above` is better accomplished by #1596

On the one hand I could see myself using these commands (or a `shrink_line` version like https://github.com/helix-editor/helix/pull/3046) but on the other it seems like a needless optimization on "`hjkl` in select-mode followed by `X`." With the addition of these commands we'd basically have the line-wise select-mode from vim.

> on `extend_line_above` this behaviour isn't even possible

Flip the selection with `A-;` and then use `hjkl` in select mode

> The current behaviour seems rather inconsistent

A bit of a nitpick: something cannot be inconsistent without differing from a baseline behavior. What is the current behavior inconsistent with respect to? IMO it would be inconsistent to have special handling for newlines.

**Comment by s0LA1337** [comment]
> Using these to undo `extend_line_below` and `extend_line_above` is better accomplished by #1596
> 
> On the one hand I could see myself using these commands (or a `shrink_line` version like #3046) but on the other it seems like a needless optimization on "`hjkl` in select-mode followed by `X`." With the addition of these commands we'd basically have the line-wise select-mode from vim.
Soft undo sounds like something, that'd help in this case.

> A bit of a nitpick: something cannot be inconsistent without differing from a baseline behavior. What is the current behavior inconsistent with respect to? IMO it would be inconsistent to have special handling for newlines.
Well i see the inconsistency in e.g. that we have only one direction of doing something with newlines (namely: only extending), i see the incosistency as selections should IMO be bi-directional. But that's just _my_ opinion.
I would be rather fine with just the soft-undo, i think this would already be a great addition.

**Comment by someone-aka-sum1** [comment]
This is not completed. Please reopen the issue.

**Comment by noahfraiture** [comment]
Hello it would be great to have this feature and it hasn't been completed at all. Is there plan ?

**Comment by chtenb** [comment]
Not exactly what was asked here, but do these commands help you achieve what you want? https://github.com/helix-editor/helix/pull/9080#issuecomment-2008964831

**Comment by someone-aka-sum1** [comment]
@chtenb I'm a newbie and am having a hard time grokking all that, but whatever the reason was for introducing `extend_line_above` and `extend_line_below`, the same should be valid for `shrink_line_above` and `shrink_line_below`. Either the functionality can't be achieved with existing commands, or it can be achieved only in a very convoluted manner.

The semantics of both actions change depending on where the caret is (at the start of the selection or its end). There's also a difference between shrinking a selection and moving a caret: Shrinking can only deselect, while moving the caret can go past the be beginning/end of the selection, making an edge of a selection the beginning of an entirely different one.

**Comment by chtenb** [comment]
`extend_line_above` et al are older than `select_line_below`/`select_line_above`. People, including myself, had trouble with how `extend_line_above` works and found that it did not accomodate a convenient editing flow for working with line range selections. This is why `select_line_below`/`select_line_above` were introduced in the PR I linked. I'm not saying that `shrink_line_above` are a bad idea, I'm just mentioning that there are other commands available that people use to work with line range selections, which seems to be a problem you are trying to solve. 

> I'm a newbie and am having a hard time grokking all that

If you're having trouble understanding how to use  `select_line_below`/`select_line_above`, feel free to create a new discussion with a question and ping me. I'm happy to help out if you have any questions about these specific commands.

**Comment by someone-aka-sum1** [comment]
These have two different behaviors: `select_line_above` starts from the caret position, `extend_line_above` starts from the start of the selection. In other words, depending on the caret position (and whether more than one line is selected) `select_line_above` behaves either like `extend_line_above` or the missing `shrink_line_below`. I think it is convenient to... well, extend selection, without having to move the caret. Even if you dislike these semantics of the existing commands, please permit others to like them. And if they're here to stay, so it's logical to have their `shrink...` counterparts.

**Comment by noahfraiture** [comment]
I'm a bit late but even if it's not perfect, it's great, thank you !
