### ISSUE TITLE
Initial scratch buffer is discarded when non-empty and unmodified

### ISSUE THREAD

**Issue by the-mikedavis** [helix-editor/helix#3305]
### Summary

The initial scratch buffer created when opening `hx` without a filename may be erroneously closed when navigated away from. This is expected behavior when the scratch buffer is empty and unmodified but it can occur when the scratch buffer is non-empty and unmodified by piping in initial text.

https://github.com/helix-editor/helix/discussions/3118

### Reproduction Steps

Fill the initial scratch buffer with files for example

```
find . -name \*.md | hx
```

Then use `gf` to open up one of those buffers. The buffer picker (`Space-b`) then shows

If you leave some modifications in the scratch buffer before using `gf` then the scratch buffer stays open.

(This is not reproducible on macos because piping in is not currently supported https://github.com/helix-editor/helix/blob/69f84e25165d62d0f38bcc80bf9108f9c0802cad/helix-term/src/application.rs#L197)

### Platform

Linux (NixOS 21.11)

### Terminal Emulator

Kitty 0.25.2

### Helix Version

22.05-351-g69f84e25

**Comment by tamakiii** [comment]
I'd like to use this feature too, but as an alternative, process substitution works.
```sh
hx <(find . -name \*.md)
```
