### ISSUE TITLE
`hx --grammar fetch` fails when using Helix built with Nix

### ISSUE THREAD

**Issue by AumyF** [helix-editor/helix#3310]
### Summary

`helix --grammar fetch` fails when using Helix built with Nix, since its runtime directory is set in Nix store which is not writable.

### Reproduction Steps

1. `nix shell github:helix-editor/helix`
2. `hx --grammar fetch`

### Helix log

```
Error: Failed to fetch some grammar(s)

Caused by:
    0: Could not create grammar directory "/nix/store/5znz3zwidqndnqa54ibhv1yfgxd5xmip-helix-runtime/grammars/sources/protobuf"
    1: Permission denied (os error 13)
```

### Platform

Arch Linux

### Terminal Emulator

foot 1.12.1

### Helix Version

helix 22.05

**Comment by archseer** [comment]
There's a previous issue for this but it was closed: https://github.com/helix-editor/helix/issues/2091#issuecomment-1097472407

**Comment by the-mikedavis** [comment]
You don't need to use `hx -g fetch` when using the Nix flake, grammars are fetched and built by nix when building `hx`. The runtime for nix is in the store which is immutable, so `hx -g fetch
` and `hx -g build` fail.

I don't think there's an issue for it yet but like archseer says in the linked commit, we want to treat the runtime directory from installation (usually into `/usr` but `/nix/store` for nix) as immutable and have `~/.config/helix` or other XDG dirs act as overrides like it does currently for configuration files like `languages.toml`

**Comment by tgharib** [comment]
`hx --health` to confirm highlighting (from treesitter) is working

**Comment by the-mikedavis** [comment]
I'll close this out as expected behavior but I've opened up #3346 describing how we'd like to do this in the long-run. With a solution to that, `hx -g fetch`/`hx -g build` should act on `~/.config/helix/runtime` rather than the Nix store.
