### ISSUE TITLE
Cannot open file picker via file_picker keymap command

### ISSUE THREAD

**Issue by JulianDicken** [helix-editor/helix#3320]
### Summary

May be missing something but I cannot get the filepicker to open via a shortcut. 
Neither
```
[keys.normal]
"C-space" = "file_picker"
```
Nor
```
[keys.normal]
"C-space" = ["space_mode", "file_picker"]
```
(fails with data did not match any variant of untagged enum KeyTrie for key keys.normal)

seem to work.

### Reproduction Steps

Simply editing the config.toml should do the trick. 
Happens on two machines of mine

### Helix log

[helix.log](https://github.com/helix-editor/helix/files/9254200/helix.log)

### Platform

Windows 11

### Terminal Emulator

Alacritty

### Helix Version

helix 22.05

**Comment by the-mikedavis** [comment]
The

```toml
[keys.normal]
"C-space" = "file_picker"
```

keybind should work fine. It works correctly for me on linux with Kitty 0.25.2.

Your terminal emulator may be confusing `C-space` with some other keycode or your OS could be stealing the input thinking its a system-wide shortcut. You can try out [crossterm](https://github.com/crossterm-rs/crossterm)'s `event-read` example (`cargo run --example event-read`) to see what crossterm thinks you're entering when you hit `C-space`.

**Comment by JulianDicken** [comment]
Seems to be the C-space combo. If I want to use space for the file picker I need to bind space to no op, which makes sense. 
Seems to be an upstream issue though and since I'm on windows I cannot be bothered to find out details. Gonna be rebinding to something else, but I can confirm this is a C-space issue.
