### ISSUE TITLE
Add highlighting for assembler (.s)

### ISSUE THREAD

**Issue by kchibisov** [helix-editor/helix#3329]
Would need a tree-sitter grammar for that.

**Comment by PictElm** [comment]
If I may; a problem with assembly 'language' suport is *which*?
I have a [tree-sitter-nasm](https://github.com/PictElm/tree-sitter-nasm) which I used a fair amount for nasm assembly, but it probably won't handle eg. gas syntax well...

**Comment by kchibisov** [comment]
I mainly see gas, since that's what everything dumps by default... Would be nice to have some primitive highlighting for both of them.

**Comment by A-Walrus** [comment]
It would also be nice to use the asm tree sitter for inline assembly in languages such as Rust, C/C++ ...

**Comment by kchibisov** [comment]
I'm pretty sure that you can't do that with rust, given that its syntax is a bit different from what I remember or has a different more usable for form compared to C/C++.

**Comment by A-Walrus** [comment]
Yeah you're right, it has a different syntax:
```rust
unsafe {
    asm!(
        "mov {tmp}, {x}",
        "shl {tmp}, 1",
        "shl {x}, 2",
        "add {x}, {tmp}",
        x = inout(reg) x,
        tmp = out(reg) _,
    );
}
```
I suppose a tree-sitter parser for rust-inline-assembly could be written and used, but that's a separate feature.

**Comment by jtepe** [comment]
> If I may; a problem with assembly 'language' suport is _which_? I have a [tree-sitter-nasm](https://github.com/PictElm/tree-sitter-nasm) which I used a fair amount for nasm assembly, but it probably won't handle eg. gas syntax well...

I would be highly interested in having nasm support. IIRC, it's also highly used out there. Separate gas support would also be nice.

**Comment by the-mikedavis** [comment]
Yep only nasm is currently supported. I think a new issue for gas is perferrable
