### ISSUE TITLE
How do you keep LSP server's stdin channel open?

### ISSUE THREAD

**Issue by shanmukhateja** [helix-editor/helix#3336]
Hi, 

I am building an IDE in Rust [here](https://github.com/shanmukhateja/mystudio-ide/) and currently trying to add LSP support.

I am failing to keep stdin channel open for LSP server after first access.

> This is not a Helix bug or feature request.

### Problem

The `stdin.take()` leaves `None` after first access and subsequent access cause panics. I am using `std::process::Command` for spawning the LSP server binary (in my case, its `rust-analyzer`).

I seem to be panicing [here](https://github.com/shanmukhateja/mystudio-ide/blob/lsp/lsp/src/sender.rs#L13). It works when I send `initialize` request but soon after I try to reply with `initialized` and it panics (trying to unwrap `None` value) 

### Tokio

I noticed your LSP crate uses tokio.rs however I am not using it mainly because it is very huge library (to my eyes) and as a Rust beginner, it is confusing and *scary*. The IDE project is my way to learn Rust by building something. 

I understand this is an unusual request so I request you to please not close this issue. I am looking for directions to solve this problem.

Any help would be very really appreciated.

Thanks in advance :-)

**Comment by archseer** [comment]
You need to keep the stdin object after taking it via `stdin.take()`. You drop it at the end of the function so it gets closed.
