### ISSUE TITLE
Immediately show the output of a command line (run with `:sh`) while it is running

### ISSUE THREAD

**Issue by jcornaz** [helix-editor/helix#3337]
I find the `:sh` command not very practical, because nothing happens until the command is completely executed.

For example, if I run `:sh cargo test` on a rust project, helix will be frozen until the tests are done (which can take a couple of minutes if the project was not yet compiled).

#### Describe your feature request

I would prefer a behavior similar to `vim` and `nvim` (`:!`) which immediately shows the command-line output while the command is running, so that I can already read and analyze the command line output, without having to wait until it is done.

**Comment by the-mikedavis** [comment]
> I find the `:sh` command not very practical

Yeah, `:sh` is not meant to be a general replacement for #1976. It's meant as a stop-gap so you can at least run some shell commands especially as part of custom key-bindings.

IMO it's out of scope to try to make running shell commands with Helix very usable, especially for things like builds and tests like with cargo. It's solved elegantly by #1976 or maybe BSP (https://github.com/helix-editor/helix/issues/2934#issuecomment-1172407658) and until then you should use a separate window/pane/split/etc in your terminal emulator/multiplexor.

**Comment by jcornaz** [comment]
Ah yes actually #1976 is more or less what I had in mind. I just didn't find the issue sorry. I close this in favor of #1976.
