### ISSUE TITLE
Treat runtime files from installation as immutable

### ISSUE THREAD

**Issue by the-mikedavis** [helix-editor/helix#3346]
We should treat the grammar sources, compiled parsers, and queries produced while building Helix as immutable defaults which can be overridden with the existence of files in `~/.config/helix/runtime`. Effectively, `$HELIX_RUNTIME` should act like `$PATH` in unix.

Except when installing from source, these files almost always end up in some `/usr` directory that needs sudo to edit (which you probably shouldn't do). With Nix, these end up in the store which is immutable so you need to build from source to modify queries or themes locally. Instead you should just be able to override files in your `~/.config/helix/runtime` directory.

See https://github.com/helix-editor/helix/issues/3310#issuecomment-1203875141
See https://github.com/helix-editor/helix/issues/2091#issuecomment-1097472407

**Comment by amtoine** [comment]
as in #4128, i have this very issue :open_mouth: 

from the Arch main repositories, `helix` comes installed with all its grammar in `/var/lib/helix/runtime/` which needs `sudo` privileges to do anything...
thus `hx --grammar fetch/build` does not work and `sudo helix --grammar fetch/build` has to be used :confused: 

always using `~/.config/helix/runtime/` and `$HELIX_RUNTIME` would be amazing :star_struck:

**Comment by amtoine** [comment]
hello there :yum: 

- **is anyone working on this somewhere?** :open_mouth: 
- **is there any chance i can help?**
i do not know where to start really, but i'd like to see such feature in `helix`.
that would be amazing to avoid messing around with `sudo` :star_struck: 

cheers :wave:

**Comment by domust** [comment]
Hi there,

I would also love to have this feature in `helix`.

Currently I'm trying to add a new language to `helix` while implementing `tree-sitter` grammar for it as well,
but I can't test it on my machine since I'm using NixOS.

If anyone could give me any pointers, I would try to help implementing this feature.

**Comment by paul-scott** [comment]
I had a look at this. What we could do is change `helix_loader::runtime_dir` and have it return a Vec of directories in a particular priority. I thought it was going to be an easy fix but unfortunately it is used in 10 places across 4 sub-crates so would take a little bit of tinkering. In addition / alternatively we could write a public function that, given a relative path, searches for the full path of the first file found according to the runtime directory priority (or else an error). This would make it easier for the call sites.

By the way, does anyone know why `RUNTIME_DIR` (lazy static call to `runtime_dir`) is used only for the `helix_loader::grammar::load_runtime_file` method, while `runtime_dir` is used dynamically in all other call sites?

One thing that is a bit inconsistent with this proposal is that the themes live under `RUNTIME_DIR/themes`, but local user themes are currently being found in `~/.config/helix/themes`,  not `~/.config/helix/runtime/themes`. So either that would have to be changed for consistencies sake, or kept in for backwards compatibility.

**Comment by amtoine** [comment]
> I had a look at this. What we could do is change `helix_loader::runtime_dir` [...] while `runtime_dir` is used dynamically in all other call sites?
> 
do not know the code base to answer all this :eyes: 

> One thing that is a bit inconsistent with this proposal is that the themes live under `RUNTIME_DIR/themes`, but local user themes are currently being found in `~/.config/helix/themes`, not `~/.config/helix/runtime/themes`. So either that would have to be changed for consistencies sake, or kept in for backwards compatibility.
>
maybe `helix` could look for both?
making `~/.config/helix/runtime/themes/` the new default for consistency and `~/.config/helix/themes/` the second fallback directory if the former does not exist, for backwards compatibility :yum:
