### ISSUE TITLE
Non-rebindable `C-space` binding in pickers is problematic on MacOS

### ISSUE THREAD

**Issue by Omnikar** [helix-editor/helix#3352]
On MacOS, ctrl-space is a system binding to switch keyboard layouts. As a result, the ["filter options" binding in pickers](https://docs.helix-editor.com/keymap.html#picker) is inaccessible via the default keybind on MacOS. Since rebinding is not currently available for picker bindings, this action becomes completely inaccessible.

**Comment by the-mikedavis** [comment]
The C-space keyboard shortcut reclaimed and works for me on Kitty on macos after disabling the shortcut:

System Preferences > Keyboard > Shortcuts > Input Sources and then uncheck the boxes C-Space and C-Option-Space.

**Comment by hzb-ykpcx** [comment]
I'm used to the C-Space shortcut in macOS and I guess the some other Mac users are used to it too. It would be better if we can modify the shortcuts in pickers ourselves or at least the C-space one.
