### ISSUE TITLE
[Feature request] View full documentation

### ISSUE THREAD

**Issue by TheAwiteb** [helix-editor/helix#3356]
When i press `space+k` will show the function documentation, but it is not displayed in full.

**For example [`filter`](https://doc.rust-lang.org/std/iter/trait.Iterator.html#method.filter) documentation**
full documentation 👆
> <a href="https://user-images.githubusercontent.com/59842932/183412812-8d6c8166-ccbe-43ad-bb1b-2c914ab6faec.png"> <img src="https://user-images.githubusercontent.com/59842932/183412812-8d6c8166-ccbe-43ad-bb1b-2c914ab6faec.png" width="400" /> </a>

**Comment by the-mikedavis** [comment]
The full documentation is available but some documentation is too long to show in the popup given the size of the view. You can use `C-d` to scroll down and `C-u` to scroll up in the documentation popup.

**Comment by TheAwiteb** [comment]
I didn't know I could scroll it, thanks 🙏🏻
