### ISSUE TITLE
auto-indentation issue: extra tabs for some reason (unable to reproduce)

### ISSUE THREAD

**Issue by adsick** [helix-editor/helix#3358]
### Summary

for some reason additional tabs appear when I consequently pushed enter in insert mode. See video to understand.

### Reproduction Steps

 

I tried this:

1. `hx`

2. edited a rust document
~~3. tried 'C', it added a cursor, damn sux...~~
4. 'x' to select current line
5. 'c' to edit it
6. it deleted newline character and I am on the start of the next line with code not enjoying it
7. I do some manual indentation
8. I push enter a few times and see it adds one more ident for every enter press.
[Screencast from 08-08-22 21:43:09.webm](https://user-images.githubusercontent.com/24528839/183493740-522b5e3c-f56e-40d9-b2be-b39037dafda5.webm)

I expected this to happen:
constant indentation
Instead, this happened:
arithmetically growing indentation

### Platform

Linux

### Terminal Emulator

alacritty

### Helix Version

helix 22.05 (bf6f7042)

**Comment by the-mikedavis** [comment]
I can reproduce this if I remove Rust's indents query file `runtime/queries/rust/indents.scm` and edit inside a similar struct. That was added back in https://github.com/helix-editor/helix/pull/1562: you need to copy the `runtime/` directory from the repo to your `~/.confix/helix/runtime` or ideally [use a symlink](https://github.com/helix-editor/helix/blob/3e11017ade8b25e580b20dab5187374fa3338bae/README.md?plain=1#L48-L55). `hx --health rust` should give a checkmark for "Indent queries".

> tried 'C', it added a cursor, damn sux...
> ...
> it deleted newline character and I am on the start of the next line with code not enjoying it

This isn't productive to the discussion. Please refrain from snippy commentary in the future.

Also, being a vim clone is explicity out of scope for this project. If you prefer vim's behavior, please just use vim.

**Comment by adsick** [comment]
thanks for the respond

> Also, being a vim clone is explicity out of scope for this project.

I know that, but I am sure that 'change current line' functionality is far more common than using multicursor. I bet a lot people never use multiple cursors.

and no there is no need to get very opinionated because after all the best we can do is to give users the ability to customize keybinding to fit whatever style they want.

> Please refrain from snippy commentary in the future.

sorry for that

> If you prefer vim's behavior, please just use vim.

I just complaned about single keybinding
