### ISSUE TITLE
Key Remapping hjkl ~~> jkl; Fails in multiple ways in Normal & Select mode

### ISSUE THREAD

**Issue by ethanmsl** [helix-editor/helix#3367]
### Summary

[**Note**: I'm posting this as it indicates a bug not because I have an issue with it, specifically.  I am no longer using the shifted mapping, but the fact that shifted mapping fails so inconsistently is, ofc, notable]

Remap: (`hjkl`~~>`jkl;` && `;` ~~>`h`) 
A config.toml with notes and images of same with failed remappings highlighted is attached.
The nature of the failures is not consistent.
Sometimes the hjkl behavior is retained.
Sometimes no effect is produced.
Sometimes it's for one direction and not another where as sometimes its for all directions.
And 'Visual' mode no longer highlights with direct arrow movement keys.

<img width="755" alt="keys normal - with  failures noted" src="https://user-images.githubusercontent.com/33399972/183618923-6a1f2f02-1c81-4542-b7f7-a2cd67861bb1.png">
<img width="849" alt="keys select - with failures noted" src="https://user-images.githubusercontent.com/33399972/183618938-00473a2f-3e02-4409-9d3e-ba479b92be4f.png">

Example failing config.toml file (Note: remove the `.txt` at the end -- had to postpend that to get github to load it & and of course remove the description pre- `config.toml`)
[failing_key_remapping-config.toml.txt](https://github.com/helix-editor/helix/files/9289319/failing_key_remapping-config.toml.txt)

### Reproduction Steps

 

Highlighted and annottated remapping images attached.
The `config.toml` file also attached so one can just switch that in and drive it themself.

### Helix log

<details><summary>~/.cache/helix/helix.log</summary>

```
please provide a copy of `~/.cache/helix/helix.log` here if possible, you may need to redact some of the lines
```

</details>
[share-helix.log](https://github.com/helix-editor/helix/files/9289445/share-helix.log)

### Platform

macOS 12.5

### Terminal Emulator

iTerm_2 3.4.15 && wezterm 20220624-141144-bd1b7c5d

### Helix Version

helix 22.05 (27609f50)

**Comment by Woolworths** [comment]
While we're on the topic, I have found it impossible to remap `.` (the dot). It just will not map to what I set it to.

**Comment by the-mikedavis** [comment]
Repeat last insert `.` is a separate issue: https://github.com/helix-editor/helix/issues/1488

For most of these, this is a limitation of TOML. Each successive table is overwriting the last instead of being merged.

You have to use a single table for all sub-keys:

```toml
[keys.normal]
z = { k = "scroll_down", l = "scroll_up" }
```

Or use:

```toml
[keys.normal.z]
k = "scroll_down"
l = "scroll_up"
```

For the "doesn't work (doesn't select text, but does move)" ones, this is expected behavior. Use `extend_*` commands (extend_char_left/extend_line_down/extend_line_up/extend_char_right) instead of `move_*` to keep the selection as you move.

**Comment by ethanmsl** [comment]
Made those changes and everything works.  So this was a TOML-syntax (+ one bit of Helix-semantics) issue.
Thanks.

Very unfortunate (read: ugly) that TOML inline tables can't have new lines -- forcing single huge lines instead of readable blocks.  But that's a [TOML limitation](https://github.com/toml-lang/toml/issues/516) apparently. 

Changed, working config for reference for others that might run into similar problems:

<img width="1765" alt="keys normal - with changes noted" src="https://user-images.githubusercontent.com/33399972/183662553-9dd8d86a-fd1d-4a77-a77b-f2f66c857c22.png">
<img width="1748" alt="keys select - with changes noted" src="https://user-images.githubusercontent.com/33399972/183662594-0b901f4c-bbbe-4834-85d7-cd575844b9c9.png">

[updated_working_key_remapping-config.toml.txt](https://github.com/helix-editor/helix/files/9291093/updated_working_key_remapping-config.toml.txt)
