### ISSUE TITLE
Running a shell command breaks terminal sequences

### ISSUE THREAD

**Issue by CptPotato** [helix-editor/helix#3374]
### Summary

After running a shell command some inputs don't work anymore.

I ran into these two:

- mouse input has no effect
- <kbd>Ctrl</kbd><kbd>C</kbd> sends a keyboard interrupt and kills helix, instead of toggling a comment

It's worth noting that `:pipe` does not cause this broken behavior.

### Reproduction Steps

- run helix
- `:sh echo hi`
- try using the mouse or toggling a comment (<kbd>Ctrl</kbd><kbd>C</kbd>)

### Helix log

nothing of interest

### Platform

Windows 10 x64

### Terminal Emulator

wezterm (nightly)

### Helix Version

helix 22.05 (3e11017a)

**Comment by AceofSpades5757** [comment]
It looks like this may be the culprit. But not sure why we lose some input control.

3121353c6ab2fbc5fced28f075c7fc45b53b661e

**Comment by the-mikedavis** [comment]
This may be Windows specific; I can't reproduce on linux.

**Comment by archseer** [comment]
Hope #3379 fixes the issue, let me know if we need to reopen! Thanks to @AceofSpades5757 for the quick fix 🎉
