### ISSUE TITLE
freeze on attempt to open a markdown document

### ISSUE THREAD

**Issue by adsick** [helix-editor/helix#3375]
### Summary

Helix freezes when I try to open a plane .md file.
logs do show nothing if I use Ctrl-c escape, could you please advice me something to detect the reason?

![image](https://user-images.githubusercontent.com/24528839/183678303-e01ee474-d772-45c3-85b5-5c506cf6242c.png)

### Reproduction Steps

I tried this:

1. `hx somefile.md`

I expected this to happen:
a markdown file opened

Instead, this happened:
everything froze with no logs

### Helix log

<details><summary>~/.cache/helix/helix.log</summary>

```
please provide a copy of `~/.cache/helix/helix.log` here if possible, you may need to redact some of the lines
```

</details>

### Platform

Linux

### Terminal Emulator

alacritty 0.10.1

### Helix Version

helix 22.05 (bf6f7042)

**Comment by David-Else** [comment]
I recommend you try the latest version if you are compiling it yourself, there have been markdown changes since your version: https://github.com/helix-editor/helix/pull/3108

**Comment by adsick** [comment]
idk, I'm on latest master (triple checked) looks like helix -V displays the wrong commit (or I am doing something wrong)
![image](https://user-images.githubusercontent.com/24528839/183776219-51360931-1740-4db2-8ace-3f07429e2514.png)

**Comment by adsick** [comment]
nvm, I had some older helix installed by hand

**Comment by adsick** [comment]
hooray, it works!
