### ISSUE TITLE
can't use Ctrl-s in the config file

### ISSUE THREAD

**Issue by adsick** [helix-editor/helix#3377]
I have a binding

```
[keys.insert]
C-s = ["normal_mode", ":w", "insert_mode"]
```
strange thing, but saving with C-s works for .rs files, but doesn't for .toml ones (specifically the config)

**Comment by AceofSpades5757** [comment]
It looks like it _does_ save, but won't remove the `[+]` to indicate that the file has changed. When I edit any file, including the config files, I'll hit `C-s` (control+s) to save it and re-enter insert mode. Then, if I `:q!` to quit without saving and edit the file again I can see my changes were saved.

**Comment by AceofSpades5757** [comment]
Btw, I noticed issues with your binding depending on if you're using `insert_mode`, by using `i`, or `append_mode`, by using `a`, since `append_mode` will start a selection. I tried to resolve this using `collapse_selection`, to remove the selection entirely, but wasn't able to. Hope you haven't had any issues with this as well.

**Comment by adsick** [comment]
idk, but I would better have an ability to bind such things directly, without need to build workarounds (switching modes back and forth)

**Comment by Omnikar** [comment]
> I have a binding
> 
> ```
> [keys.insert]
> C-s = ["normal_mode", ":w", "insert_mode"]
> ```
> 
> strange thing, but saving with C-s works for .rs files, but doesn't for .toml ones (specifically the config)

I don't know exactly what's going on with this issue, but for this specific purpose, the switch back to normal mode is unnecessary; you can just bind `C-s = ":w"` directly and it'll work even though it's in insert mode, since you're binding it directly to the command.

**Comment by AceofSpades5757** [comment]
> > I have a binding
> > ```
> > [keys.insert]
> > C-s = ["normal_mode", ":w", "insert_mode"]
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > strange thing, but saving with C-s works for .rs files, but doesn't for .toml ones (specifically the config)
> 
> I don't know exactly what's going on with this issue, but for this specific purpose, the switch back to normal mode is unnecessary; you can just bind `C-s = ":w"` directly and it'll work even though it's in insert mode, since you're binding it directly to the command.

Oh, that's cool. I didn't realize key bindings worked that way. Thanks!

The `[+]` still shouldn't be there using that key binding.

**Comment by Omnikar** [comment]
I tested it out myself and using `C-s = ":w"` to save my `config.toml` worked just fine and made the `[+]` disappear.

**Comment by adsick** [comment]
> > > I have a binding
> > > ```
> > > [keys.insert]
> > > C-s = ["normal_mode", ":w", "insert_mode"]
> > > ```
> > > 
> > > 
> > >     
> > >       
> > >     
> > > 
> > >       
> > >     
> > > 
> > >     
> > >   
> > > strange thing, but saving with C-s works for .rs files, but doesn't for .toml ones (specifically the config)
> > 
> > 
> > I don't know exactly what's going on with this issue, but for this specific purpose, the switch back to normal mode is unnecessary; you can just bind `C-s = ":w"` directly and it'll work even though it's in insert mode, since you're binding it directly to the command.
> 
> Oh, that's cool. I didn't realize key bindings worked that way. Thanks!
> 
> The `[+]` still shouldn't be there using that key binding.

same, will try it tomorrow. thx, @Omnikar

**Comment by adsick** [comment]
yep, it works. nice.
