### ISSUE TITLE
Opening theme.toml with taplo shows errors

### ISSUE THREAD

**Issue by A-Walrus** [helix-editor/helix#3383]
### Summary

When opening the `theme.toml` file with helix and the `taplo` lsp, a ton of errors appear:
![image](https://user-images.githubusercontent.com/58790821/183905923-f9e45fe0-0e70-4373-9b07-67e5d37c7c9b.png)

This is because `taplo` uses [the json schema store](https://www.schemastore.org/json/) for schemas. (This is useful, for example, to detect errors in `Cargo.toml`). The json schema store has a schema for `theme.json` ([schema](https://raw.githubusercontent.com/WordPress/gutenberg/trunk/schemas/json/theme.json)) which comes from WordPress and has nothing to do with helix. This schema is incorrectly used for helix's `theme.toml` file.

### Reproduction Steps

 

I tried this:

1. Have taplo lsp installed
2. cd to your helix repo
3. `hx theme.toml`

I expected this to happen:
No errors show

Instead, this happened:
Many errors appear

### Helix log

<details><summary>~/.cache/helix/helix.log</summary>

```
please provide a copy of `~/.cache/helix/helix.log` here if possible, you may need to redact some of the lines
```

</details>

### Platform

Linux

### Terminal Emulator

Kitty

### Helix Version

helix 22.05

**Comment by the-mikedavis** [comment]
Is there a way for us to write a schema for themes which would override the theme.json one? Ideally we could do the same for `config.toml` to add auto-complete (https://github.com/helix-editor/helix/issues/2894)

Alternatively it would be nice if we could configure this behavior in the args passed to taplo in languages.toml. I think it's a little assumptive of taplo to automatically consider all `theme.toml` files to be wordpress themes.

**Comment by A-Walrus** [comment]
[taplo documentation on devolping schemas](https://taplo.tamasfe.dev/configuration/developing-schemas.html)
[and using schemas](https://taplo.tamasfe.dev/configuration/using-schemas.html)

**Comment by dead10ck** [comment]
Closing in favor of #3901. Thanks for your report!
