### ISSUE TITLE
Improve rendering of `<code>` tags in documentation

### ISSUE THREAD

**Issue by A-Walrus** [helix-editor/helix#3411]
#### Describe your feature request
Documentation, at least for rust, can contain `<code>` tags, for example the documentation for `into()` from the standard library. The tags themselves should not be shown, and the text within should be shown the same as text within "\`":
![image](https://user-images.githubusercontent.com/58790821/184478064-f2026445-4a16-4c02-a181-2a663cb102e1.png)
The `<code>` and `</code>` tags should not be shown and the text within them should be styled the same as the `U::from(self)` from above.

**Comment by the-mikedavis** [comment]
Markdown rendering for things like doc popups is handled here: https://github.com/helix-editor/helix/blob/8deaebde26a5ab2a51e8124828ba042641a1558f/helix-term/src/ui/markdown.rs#L181-L299

For this snippet, the events in that loop look like

```rs
Start(CodeBlock(Fenced(Borrowed("rust"))))
Text(Borrowed("core::convert\n"))
End(CodeBlock(Fenced(Borrowed("rust"))))
Start(CodeBlock(Fenced(Borrowed("rust"))))
Text(Borrowed("fn into(self) -> U\n"))
End(CodeBlock(Fenced(Borrowed("rust"))))
Rule
Start(Paragraph)
Text(Borrowed("Calls "))
Code(Borrowed("U::from(self)"))
Text(Borrowed("."))
End(Paragraph)
Start(Paragraph)
Text(Borrowed("That is, this conversion is whatever the implementation of"))
SoftBreak
Html(Borrowed("<code>"))
SoftBreak
Start(Link(Inline, Borrowed("https://doc.rust-lang.org/nightly/core/convert/trait.From.html"), Borrowed("")))
Text(Borrowed("From"))
End(Link(Inline, Borrowed("https://doc.rust-lang.org/nightly/core/convert/trait.From.html"), Borrowed("")))
Text(Borrowed("<T"))
Text(Borrowed("> for U"))
Html(Borrowed("</code>"))
Text(Borrowed(" chooses to do."))
End(Paragraph)
```
