### ISSUE TITLE
extend_line_above ignores count

### ISSUE THREAD

**Issue by dead10ck** [helix-editor/helix#3416]
It looks like when `extend_line_above` is selecting the new line range, it takes the count into account for extending below, but above just hardcodes subtracting 1.

https://github.com/helix-editor/helix/blob/8deaebde26a5ab2a51e8124828ba042641a1558f/helix-term/src/commands.rs#L1954-L1982

**Comment by QiBaobin** [comment]
I fixed it in the https://github.com/helix-editor/helix/pull/3046 : https://github.com/helix-editor/helix/pull/3046/files , if need, I separated this part to another PR.
