### ISSUE TITLE
Cursor type kept when quit back to terminal

### ISSUE THREAD

**Issue by Yevgnen** [helix-editor/helix#3417]
### Summary

When `:quit` is bind to `SPC z`, the cursor is changed when quit back to terminal using this key binding. 

### Reproduction Steps

 

I tried this:

Add

```
[editor.cursor-shape]
normal = "block"
insert = "bar"
select = "underline"

[keys.normal.space]
z = ":quit"
```

to helix config.

1.  Run `hx` in a `kitty` or `iterm2` terminal with bar cursor.
2.  Press `SPC z`.

I expected this to happen:

The cursor changes back to bar style in the terminal.

Instead, this happened:

The cursor becomes a box.

### Platform

macOS

### Terminal Emulator

kitty 0.24.4 created by Kovid Goyal

### Helix Version

helix 22.05 (21f2affa)

**Comment by the-mikedavis** [comment]
Duplicate of https://github.com/helix-editor/helix/issues/2684
