### ISSUE TITLE
Tab padding character?

### ISSUE THREAD

**Issue by m-kru** [helix-editor/helix#3427]
Is it possible to set tab padding character? https://docs.helix-editor.com/configuration.html#editorwhitespace-section does not mention it.
By the way what is `nbsp`? Maybe it would be nice to add some comment in the line to explain it.

**Comment by the-mikedavis** [comment]
Only the space, newline, tab, and nbsp can be rendered currently. Which is the tab padding character? U+0080?

NBSP is https://en.wikipedia.org/wiki/Non-breaking_space. It's used most often when writing HTML.

**Comment by m-kru** [comment]
I guess there is no standard tab padding character. People use different characters for this purpose.

**Comment by the-mikedavis** [comment]
I don't understand - is the tab padding character a character in a file or something displayed when a file has a tab in it?

You can customize the latter with the `editor.whitespace.characters.tab` configuration you linked. For example I have mine bound to rightwards triangle (`▸`)

![tab](https://user-images.githubusercontent.com/21230295/184549588-7f7a2cd2-0a4a-4d0e-9b8b-69bc95942fb3.png)

**Comment by m-kru** [comment]
![image](https://user-images.githubusercontent.com/26227737/184550368-83aee08a-5264-45a9-bd0e-726c2f67234d.png)
In Kakoune I use centered dots.  Single character length is always 1, however the tab is usually configured to be longer, hence some character to pad the tab character.

**Comment by n0s4** [comment]
Do you mean adding virtual whitespace to change tab length? Virtual whitespace is a WIP but you can configure the tab length.

**Comment by m-kru** [comment]
No. The tab character is a single character. However, the tab is usually set to be longer than single character. In @the-mikedavis screenshot you can see there is a little arrow and then nothing. In my screenshot there is a little arrow and 3 dots. It is all about how the tab is displayed.

**Comment by the-mikedavis** [comment]
Currently this isn't possible: the tab setting in `editor.whitespace.characters` must be deserializable to a `char`. We pad the tab character with spaces here: https://github.com/helix-editor/helix/blob/8a757954728b52ec92843388049dcaea60db8e3c/helix-term/src/ui/editor.rs#L397-L399

which could be replaced either with a new padding character or the `tab` setting could be a string that gets truncated to the tab-width.
