### ISSUE TITLE
Either spin up a Discord server or github 'discussions' cause there's noone to ask a noob question

### ISSUE THREAD

**Issue by Niedzwiedzw** [helix-editor/helix#343]
Either spin up a Discord server or github 'discussions' cause there's noone to ask a noob question

**Comment by kellytk** [comment]
Please refer to the [Getting help](https://github.com/helix-editor/helix#getting-help) section of the README.  

Matrix has the advantage of not being as proprietary and user-hostile as Discord is.  Enabling GitHub Discussions is probably a good idea.

**Comment by archseer** [comment]
Exactly, I think Matrix is now accessible through gitter too.

**Comment by sudormrfbin** [comment]
We should probably enable discussions too. It will give a better overview of questions rather than issues people will have, and it's easily searchable through github too.

**Comment by CBenoit** [comment]
For instant communication, Matrix is enough IMO (no Discord). However, GitHub discussions or a discourse board like [users.rust-lang.org](https://users.rust-lang.org/), [discuss.kakoune.com](https://discuss.kakoune.com/) or [neovim.discourse.group](https://neovim.discourse.group/) sounds useful to me as well. I'm not sure we need that immediately, but at some point I think it's worth it.

**Comment by Kethku** [comment]
I've found github discussions to be valuable for neovide because it allows people to chat in an unstructured way and I don't feel pressure to close the discussions that show up there. Also there is a feature which lets you transform an issue into a discussion which is great if you want to enable discussion but don't want it to clutter the issues.

I highly recommend it.

**Comment by archseer** [comment]
I turned on github discussions, would like to transition to an external discourse board some day though.

**Comment by Marcuss2** [comment]
I kinda hate to comment on a closed issue, but there seems to be a problem with the matrix room:
When you join, you have no way of gaining permission to send messages.

**Comment by archseer** [comment]
@Marcuss2 are you using a client without Matrix Space support? `#helix-community` is a meta room that contains subrooms. Some clients aren't able to see the directory yet.

> make sure to join #helix-editor:matrix.org if you're on a client that doesn't support Matrix Spaces yet

**Comment by Marcuss2** [comment]
@archseer Sorry, I did not realize that was a thing, maybe put it in the #helix-community description, so people without Matrix Space support can see it?

**Comment by archseer** [comment]
It's both in the Readme as well as the community room description :)

**Comment by Marcuss2** [comment]
> It's both in the Readme as well as the community room description :)

The community room description only contains "A post-modern text editor | Invite link: https://matrix.to/#/#helix-community:matrix.org"
