### ISSUE TITLE
Hover gets cut off after 24 lines for command 'Show docs for item under cursor"

### ISSUE THREAD

**Issue by leonqadirie** [helix-editor/helix#3430]
### Summary
Space + k shows a max. of 24 lines and then cuts off the rest.

### Reproduction
With LSP installed, invoke Space + k on an item under cursor that has somewhat larger docs (e.g., `main` in Rust's `#[tokio::main]`, or actix-web's `HttpServer` c.f. screenshot).

### What I expect
Being shown the whole doc - or at least as much as still 'nicely' fits the screen.

### What I'd additionally love to see
* making the hover 'scrollable' if docs really don't fit the hover
* vertical line-separation based on empty lines, cf. screenshot

### What happens
Due to a seemingly fixed max. width and height, the docs are cut off after 24 lines (for me)

### Screenshots
* **Helix**
![screenshot_hx_cutoff](https://user-images.githubusercontent.com/39130739/184535378-c2eaa0a0-6c96-4a75-b777-3c05c87bb1ee.png)
* **My expectations**
![nvim_full](https://user-images.githubusercontent.com/39130739/184535379-ac63d048-428c-4c45-8d31-0b3b050f2d3f.png)

--
### Setup:
* [latest master as of 14th of August 2022](https://github.com/helix-editor/helix/tree/8deaebde26a5ab2a51e8124828ba042641a1558f)
* kitty/Alacritty etc.
* macOS 12.5

**Comment by n0s4** [comment]
You can use `C-d/u` to scroll down/up the popups. I agree the sizing is sometimes a bit strange.

**Comment by leonqadirie** [comment]
> You can use `C-d/u` to scroll down/up the popups. I agree the sizing is sometimes a bit strange.

Thank you, that is already helpful!
Then it might be more of an enhancement issue indeed.

**Comment by the-mikedavis** [comment]
There's an issue for improving the UI to hint that you can scroll: https://github.com/helix-editor/helix/issues/1248
