### ISSUE TITLE
A- is not explained in the tutor.

### ISSUE THREAD

**Issue by m-kru** [helix-editor/helix#3431]
The first occurrence of `A-` is in line number 370 of the tutorial [helix 22.05 (8deaebde)].

![image](https://user-images.githubusercontent.com/26227737/184536372-55cf409e-3305-412c-af42-b4b81cfad7e4.png)

I find it a little bit enigmatic. What does `A-` represent? It is not explained anywhere within the tutorial.

**Comment by n0s4** [comment]
`A-x` stands for `Alt-x` - holding down Alt while pressing x. It's clarified later at line 557 but yeah, it should be explained fully here. Then we can change all the other appearances of `Alt-` to `A-` in the rest of the tutor for consistency.

**Comment by m-kru** [comment]
So `A-` is simply `Alt`?

**Comment by m-kru** [comment]
Ok, then I have no idea how the selections flipping is supposed to work. I do not see any effect when I press `Alt`, neither with single selection nor with multiple selections.

**Comment by n0s4** [comment]
Oh. The `;` is part of the key. Type `;` while holding `Alt` on a wide selection and the cursor should flip from one side to the other. I see where the confusion comes from.

**Comment by m-kru** [comment]
Ohh, `;` is part of the command ...
