### ISSUE TITLE
Auto-save

### ISSUE THREAD

**Issue by onion108** [helix-editor/helix#3451]
So, hmm, I found that it's hard to write Rust on Helix, because the `rust-analyzer` won't give me the informations about borrow checking, ownership and many other things unless I save my file. In VSCode I can enable the auto-save so it's OK for me, but in helix I can't find a way to enable auto-save. It's really inconvenient to type `<ESC> :w <Return> i` after typing each line of the code. I think it's necessary for `helix-editor` to offer an option to enable/disable auto-save. Thanks a lot.

**Comment by Omnikar** [comment]
In the meantime, you could bind saving the file to a keybind while in insert mode. For example, you can use `Ctrl-s` to save while in insert mode using this binding in your `config.toml`:
```toml
[keys.insert]
"C-s" = ":w"
```

**Comment by AceofSpades5757** [comment]
What would you want to trigger the auto-save? Some amount of idle time?

**Comment by willparsons** [comment]
iirc rust-analyzer plans to add on the fly diagnostics (no idea when)

**Comment by archseer** [comment]
https://github.com/helix-editor/helix/pull/3178

**Comment by onion108** [comment]
> In the meantime, you could bind saving the file to a keybind while in insert mode. For example, you can use `Ctrl-s` to save while in insert mode using this binding in your `config.toml` (accessible via `:config-open`):
> 
> ```toml
> [keys.insert]
> "C-s" = ":w"
> ```

well, it looks not working for me

**Comment by onion108** [comment]
> What would you want to trigger the auto-save? Some amount of idle time?

just like what vscode does

**Comment by archseer** [comment]
Some of us never used vscode so you'll have to elaborate.

**Comment by kirawi** [comment]
https://code.visualstudio.com/docs/editor/codebasics#_save-auto-save

Looks like there are different auto save modes.

**Comment by onion108** [comment]
> https://code.visualstudio.com/docs/editor/codebasics#_save-auto-save
> 
> Looks like there are different auto save modes.

`afterDelay`, i mean

**Comment by TobTobXX** [comment]
> What would you want to trigger the auto-save? Some amount of idle time?

Something that worked well for me in nivm is on reentering normal mode. This means that it gets saved after basically every change.

**Comment by AfoHT** [comment]
In addition to what @TobTobXX suggested, which also was part of how I had nvim setup, I propose that also changing to a different split or buffer might be a good time to save the buffer that was moved away from.

I guess that maps closely to the vscode `onFocusChange`

**Comment by sourcefrog** [comment]
> > In the meantime, you could bind saving the file to a keybind while in insert mode. For example, you can use `Ctrl-s` to save while in insert mode using this binding in your `config.toml` (accessible via `:config-open`):
> > ```toml
> > [keys.insert]
> > "C-s" = ":w"
> > ```
> 
> well, it looks not working for me

For me, with `helix 22.08.1 (66276ce6)`, this *does* work but it *looks like* it doesn't, because it doesn't clear the "modified" bit in the buffer list or the `[+]` in the status line. 

However if you cat the file from another terminal you'll see your changes actually were saved.

This might be #2192.

**Comment by onion108** [comment]
> 

oh really? I'm going to have a try.

**Comment by 6lj6** [comment]
Hurry up guys, I lost lots of records on a note about helix using helix within a broken down of a laptop.

**Comment by gabydd** [comment]
Just FYI there is an autosave on focus lost setting you can turn on which will save the document when your cursor is outside the terminal(sorry if you already know about this)

```
[editor]
auto-save = true
```

**Comment by ChemicalXandco** [comment]
#5303 solves this
