### ISSUE TITLE
Swift tree-sitter grammar is out of date

### ISSUE THREAD

**Issue by alex-pinkus** [helix-editor/helix#3452]
A while back, [we discussed an approach](https://github.com/alex-pinkus/tree-sitter-swift/issues/149) that would allow Helix to consume the Swift grammar directly from my repository rather than the [fork it currently uses](https://github.com/helix-editor/helix/blob/d192d597535e50d3ce4a29fbd4dc13cb92320ea5/languages.toml#L1237). The end result (which has worked pretty well in my repo) is that my [`with-generated-files` branch](https://github.com/alex-pinkus/tree-sitter-swift/tree/with-generated-files) gets updates every time a new release is published, which allows (for instance) the `CodeEditTextView` to consume that branch using the prebuilt grammar from SwiftPM.

I notice that you haven't yet switched! I don't have a problem with that, but you should know that since then there have been quite a few [very useful improvements](https://github.com/alex-pinkus/tree-sitter-swift/compare/0.2.0...0.3.1), such as:
* Significantly improving query load time by simplifying pattern match logic
* Fixing some parsing bugs with binary expressions and function calls
* Supporting edge cases that source code editors often care about, like files that end in a comment or without a newline.

Switching should now be as easy as just using rev [`77c6312c8438f4dbaa0350cec92b3d6dd3d74a66 `](https://github.com/alex-pinkus/tree-sitter-swift/commit/77c6312c8438f4dbaa0350cec92b3d6dd3d74a66), the latest commit on `with-generated-files`. I would offer to do it myself but I haven't ramped up on building Helix so I wouldn't be able to do a sanity check after trying it out.

**Comment by the-mikedavis** [comment]
Sweet! I see the new revision being at least twice as fast as what we have pinned for query analysis in debug builds 🚀

Switching to the new branch must've fell through the cracks, I could've sworn there was a PR 😅

I'll make one now and update the queries as well
