### ISSUE TITLE
Helix crashes when opening a markdown file

### ISSUE THREAD

**Issue by MAST1999** [helix-editor/helix#3466]
### Summary

I open a `README.md` in the project and it crashes.

Can't share the `README.md` here but if needed I can try to change it to share here.

### Reproduction Steps

I tried this:

1. `hx ./`
2. In the file picker open a markdown file

I expected this to happen:
Markdown file to be opened.

Instead, this happened:
Helix crashed.

### Helix log

<details><summary>~/.cache/helix/helix.log</summary>

```
I cleared the helix.log and reproduced the error and check the helix.log file but it was empty.
```

</details>

Backtrace: 
```
thread 'main' panicked at 'Could not parse queries for language "markdown". Are your grammars out of sync? Try running 'hx --grammar fetch' and 'hx --grammar build'. This query could not be parsed: QueryError { row: 0, column: 17, offset: 17, message: "heading_content", kind: NodeType }', helix-core/src/syntax.rs:377:43
stack backtrace:
   0: rust_begin_unwind
             at /rustc/fe5b13d681f25ee6474be29d748c65adcd91f69e/library/std/src/panicking.rs:584:5
   1: core::panicking::panic_fmt
             at /rustc/fe5b13d681f25ee6474be29d748c65adcd91f69e/library/core/src/panicking.rs:143:14
   2: helix_core::syntax::LanguageConfiguration::initialize_highlight
   3: once_cell::imp::OnceCell<T>::initialize::{{closure}}
   4: once_cell::imp::initialize_or_wait
   5: once_cell::imp::OnceCell<T>::initialize
   6: helix_view::document::Document::set_language
   7: helix_view::document::Document::open
   8: helix_view::editor::Editor::open
   9: helix_term::ui::file_picker::{{closure}}
  10: <helix_term::ui::picker::FilePicker<T> as helix_term::compositor::Component>::handle_event
  11: <helix_term::ui::overlay::Overlay<T> as helix_term::compositor::Component>::handle_event
  12: helix_term::compositor::Compositor::handle_event
  13: helix_term::application::Application::handle_terminal_events
  14: helix_term::application::Application::event_loop_until_idle::{{closure}}
  15: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
  16: std::thread::local::LocalKey<T>::with
  17: tokio::park::thread::CachedParkThread::block_on
  18: tokio::runtime::thread_pool::ThreadPool::block_on
  19: tokio::runtime::Runtime::block_on
  20: hx::main
```

### Platform

Linux

### Terminal Emulator

Konsole Version 22.04.3

### Helix Version

22.05-405-g7711db3a

**Comment by archseer** [comment]
> 22.05-405-g7711db3a

I can't find `g7711db3a` anywhere in git

**Comment by MAST1999** [comment]
Hmm, I guess using `hx --version` is better then.
![image](https://user-images.githubusercontent.com/48868969/185087842-9e5f2c08-2b0d-42b8-a35d-f0d0f7b7e2ba.png)

helix 22.05 (7711db3a)

**Comment by the-mikedavis** [comment]
This happens when the queries in your runtime directory are incompatible with the version of the markdown parser (which was updated recently). You'll want to blow away your `~/.config/helix/runtime`, [link the one from this repository](https://github.com/helix-editor/helix/blob/7711db3a3af8f7ca156c8c71ae4b7ea2dd02d96f/README.md?plain=1#L48-L55), and run `hx -g fetch` and `hx -g build`

**Comment by MAST1999** [comment]
Thanks, @the-mikedavis 
That fixed it, can we put something like this in a FAQ or common troubleshooting methods so others can find it without making a bug report?

**Comment by the-mikedavis** [comment]
Yeah, this comes up somewhat often and having a wiki section on it in the troubleshooting page seems appropriate. I'll type that up now 👍
