### ISSUE TITLE
Error: rust: undefined method `on_arm' for #<Resource:0x00007ff97b41d080>

### ISSUE THREAD

**Issue by crivion** [helix-editor/helix#3474]
### Summary

Can't install using homebrew and intel mac

### Reproduction Steps

Running:
1) brew tap helix-editor/helix
good, then 
2) brew install helix

produces:
Error: rust: undefined method `on_arm' for #<Resource:0x00007ff97b41d080>

on intel mac

### Helix log

<details><summary>~/.cache/helix/helix.log</summary>

```
please provide a copy of `~/.cache/helix/helix.log` here if possible, you may need to redact some of the lines
```

</details>

### Platform

macOS Big Sur

### Terminal Emulator

iTerm2

### Helix Version

latest

**Comment by archseer** [comment]
Are you using the latest homebrew? We don't actually use `on_arm` anywhere in our formula. Try removing the tap and using the homebrew formula that was recently merged upstream, we might remove the tap altogether.

**Comment by crivion** [comment]
Homebrew 3.4.3-38-g02b0a45

Homebrew/homebrew-core (git revision 8dc01dbd03a; last commit 2022-08-18)
Homebrew/homebrew-cask (git revision 8703025552; last commit 2022-08-18)

PS: ended up building from source via cargo and i managed to get it up and running
