### ISSUE TITLE
Kill LSP gracefully

### ISSUE THREAD

**Issue by dead10ck** [helix-editor/helix#3482]
https://github.com/helix-editor/helix/blob/master/helix-lsp/src/client.rs#L62

It seems [`kill_on_drop` sends a SIGKILL](https://docs.rs/tokio/latest/tokio/process/struct.Child.html#method.kill) which is kind of aggressive, and could cause corruption. It's occurring to me that this may be why rust-analyzer has to reindex everything every time it runs. It also looks like there isn't a way to send a SIGTERM through the built-in tokio API. It looks like [we'd have to add platform-specific code to handle this properly](https://stackoverflow.com/questions/49210815/how-do-i-send-a-signal-to-a-child-subprocess).

_Originally posted by @dead10ck in https://github.com/helix-editor/helix/pull/3435#discussion_r950349542_

**Comment by mangas** [comment]
https://docs.rs/nix/latest/nix/ may have some useful stuff for this

**Comment by pascalkuthe** [comment]
Pretty sure this is fixed now wooth us giving lsps a ti.eout to close before force closing them

**Comment by dead10ck** [comment]
Are LS's supposed to terminate themselves? Or is it common to have to send them a SIGTERM?

**Comment by pascalkuthe** [comment]
There is a multiphase shutdown but in the end they are supposed to do it kn their own https://microsoft.github.io/language-server-protocol/specifications/lsp/3.17/specification/#exit

I think we have a timeout that waits for them to shutdown if they don't we kill
