### ISSUE TITLE
[REQUEST] Line cursor

### ISSUE THREAD

**Issue by CloudyWhale** [helix-editor/helix#3483]
#### Describe your feature request
I would like the line styled cursor in matrix kinda like in vim/nvim
Vim/Nvim in insert mode
![image](https://user-images.githubusercontent.com/83542885/185719301-2361f282-0e5b-4c8c-916f-46c7d774888f.png)
Helix in insert mode:
![image](https://user-images.githubusercontent.com/83542885/185719341-17b34e36-59ee-4351-bd89-f9acecf77214.png)

**Comment by kirawi** [comment]
You have to configure it: https://docs.helix-editor.com/configuration.html#editorcursor-shape-section
