### ISSUE TITLE
Bracket matching wrong on Nix

### ISSUE THREAD

**Issue by A-Walrus** [helix-editor/helix#3487]
### Summary

With this code snippet: 
```nix
{
  services.xserver.screenSection = ''
    Option  "metamodes" "nvidia-auto-select +0+0 {ForceFullCompositionPipeline=On}"
    Option  "AllowIndirectGLXProtocol" "off"
    Option  "TripleBuffer" "on"
  '';
}
```
The wrong matching bracket is highlighted, and gone to with `mm`
![image](https://user-images.githubusercontent.com/58790821/185755715-ceb51562-12c0-4845-8eba-a06456604785.png)

Possibly related:
#3357 
#3432 

### Reproduction Steps

 

I tried this:

1. `hx test.nix` (file containing above snippet)
2. cursor on one of the double quotes in lines 3-5

I expected this to happen:
Either:

- no matching bracket is highlighted (because we are within a string so nix syntax doesn't apply), or
- The correct matching quote is highlighted

Instead, this happened:
The closing quote for the nix multi-line string is highlighted, despite being a single quote and not a double.

### Helix log

<details><summary>~/.cache/helix/helix.log</summary>

```
please provide a copy of `~/.cache/helix/helix.log` here if possible, you may need to redact some of the lines
```

</details>

### Platform

Linux - Nixos

### Terminal Emulator

Gnome console

### Helix Version

helix 22.05 (27609f50)

**Comment by sohnryang** [comment]
Looks like tree-sitter-nix is not granular enough to provide bracket matching. The above code's `''...''` part is marked as `indented_string_expression`, which makes it impossible for helix to match correctly. The tree-sitter tree has no information whatsoever regarding contents of the string expression.

**Comment by nrdxp** [comment]
#3594 might help a bit with this, at least in the case where the string contains a language with a tree-sitter parser known to helix.

**Comment by A-Walrus** [comment]
> The above code's `''...''` part is marked as `indented_string_expression`, which makes it impossible for helix to match correctly. The tree-sitter tree has no information whatsoever regarding contents of the string expression.

That's true but doesn't fully explain the behavior. According to that explanation, there is no reason for helix to highlight any matching quotes in this case, especially not a different quote than the one the cursor is on (single vs double)

**Comment by nrdxp** [comment]
Actually, scratch that, Helix doesn't seem to use language injection for text objects yet, only syntax highlighting.

**Comment by pascalkuthe** [comment]
This was fixed by https://github.com/helix-editor/helix/pull/7242
