### ISSUE TITLE
Show diagnostic infomation in picker

### ISSUE THREAD

**Issue by Jedsek** [helix-editor/helix#3493]
See title, just like gutter

**Comment by Jedsek** [comment]
It is useful when opening a picker

**Comment by matoous** [comment]
You can do `space+g` to open picker for file diagnostics and `space+G` for workspace diagnostics. Is that would you mean?

<img width="1440" alt="Screenshot 2022-08-21 at 22 36 38" src="https://user-images.githubusercontent.com/15747583/185809908-3dfe16d6-b818-4a1c-8f20-2bf5e7b4ccab.png">

**Comment by Jedsek** [comment]
Oh, sorry, I am in 22.05.
Expecting release :)
