### ISSUE TITLE
App crash on `ctrl-v`

### ISSUE THREAD

**Issue by koalazub** [helix-editor/helix#3514]
### Summary

Helix will crash when pasting from the system clipboard using `ctrl + v`

Note: Did not use `space + p`

### Reproduction Steps

- Open `helix` 
- `ctrl + v`
https://user-images.githubusercontent.com/7111524/186080718-eec1cb26-ba41-465a-91ae-6768ea531399.mp4

### Helix log

<details><summary>~/.cache/helix/helix.log</summary>

[helix.log](https://github.com/helix-editor/helix/files/9399733/helix.log)

</details>

### Platform

Windows 11

### Terminal Emulator

Alacritty 0.10.0

### Helix Version

helix 22.05 (dd2b9e55)

### Extra notes

built from source on `master`

**Comment by koalazub** [comment]
> This might be Windows 11 specific.
> 
> I can't reproduce on Win 10 both with and without WSL. (using Wezterm)
Are you building from source?

I updated my issue to state that I did build from source

**Comment by uncomfyhalomacro** [comment]
I have a feeling that wezterm and helix have the keybind for CTRL+v but I haven't touched Windows for a month so not sure
