### ISSUE TITLE
Macros that do line indenting with < or > fails with 'Invalid macro'

### ISSUE THREAD

**Issue by bcspragu** [helix-editor/helix#3538]
### Summary

Recording a macro that contains a < or > indenting action fails with `Invalid macro: Unmatched '>'` or `Invalid macro: '>' expected`

### Reproduction Steps

I tried this:

1. `hx`
2. Add some text
3. `Q>Q`, e.g. record a macro that indents
4. Try running it with `q`, you'll get the above error

[![asciicast](https://asciinema.org/a/GNUjqO4fzZEgy7uADk9G6Urkz.svg)](https://asciinema.org/a/GNUjqO4fzZEgy7uADk9G6Urkz)

I expected this to happen: The macro should run. In the example case, this means indenting the line again when pressing `q`

Instead, this happened: The aforementioned error occurred.

### Helix log

There wasn't any interesting output in the logs

### Platform

Linux

### Terminal Emulator

st 0.8.4

### Helix Version

helix 22.05 (0a221485) (e.g. basically HEAD)

**Comment by Omnikar** [comment]
This is because `<` and `>` are used as delimiters of multicharacter key names in macros (e.g. `<esc>`). `<lt>` and `<gt>` already exist to represent `<` and `>`, but we need to make sure those keypresses are actually recorded as such in order to fix this bug.
