### ISSUE TITLE
`.toml` file wont start taplo language server, `the LSP is not part of this build`

### ISSUE THREAD

**Issue by David-Else** [helix-editor/helix#3555]
### Summary

I have installed `sudo npm install -g @taplo/cli`, and it seems to work
![Screenshot from 2022-08-26 22-58-02](https://user-images.githubusercontent.com/12832280/186996275-c313fcbf-2f57-4ab6-9df1-d181bb5f07bc.png)
:
```
$ taplo --version
taplo 0.6.9
```

### Reproduction Steps

Load any `.toml` file, there is no language server loaded.
- `space k` gives `no language server available on this buffer`
- the log says `the LSP is not part of this build'
- `format` does nothing

(I tried adding a `.taplo.toml` file and making the directory a `.git` repo)

### Helix log

``` 
2022-08-26T22:52:17.427 helix_lsp::transport [ERROR] err <- "ERROR operation failed error=the LSP is not part of this build, please consult the documentation about enabling the functionality\n"
  2022-08-26T22:52:17.438 helix_lsp::transport [ERROR] err: <- StreamClosed
  2022-08-26T22:52:17.438 helix_lsp::transport [ERROR] err: <- StreamClosed
  2022-08-26T22:52:28.034 helix_term::application [ERROR] Timed out waiting for language servers to shutdown
```

### Platform

Linux

### Terminal Emulator

Kitty

### Helix Version

helix 22.05 (45add73f)

**Comment by the-mikedavis** [comment]
Looks like taplo has separated a minimal build and a build that includes the language server: https://taplo.tamasfe.dev/cli/installation/binary.html#full-build

**Comment by David-Else** [comment]
Cheers, I can't get the full build `taplo-full-x86_64-unknown-linux-gnu.tar.gz` to work on my system and have opened a bug report on their repo. I assume if I can getting it running it will work out of the box and will close the issue.

**Comment by janos-r** [comment]
> Looks like taplo has separated a minimal build and a build that includes the language server: https://taplo.tamasfe.dev/cli/installation/binary.html#full-build

Thank you, after using this full binary it works!
It was still necessary to add the `formatter = { command = "taplo", args = ["format", "-"] }` though
