### ISSUE TITLE
Nightly builds CI

### ISSUE THREAD

**Issue by kirawi** [helix-editor/helix#358]

**Comment by kirawi** [comment]
I'm working on this right now.

**Comment by CBenoit** [comment]
It has been removed to improve CI times: d9b2f6feacb08f3b902deafcffb6b64059afee35

**Comment by kirawi** [comment]
I mean nightly builds of Helix, not rust.

**Comment by CBenoit** [comment]
Oh okay, my bad.

**Comment by kirawi** [comment]
Closed as the change was undesirable.
