### ISSUE TITLE
Directories with lots of inodes grind completion to a crawl in prompt

### ISSUE THREAD

**Issue by nrdxp** [helix-editor/helix#3604]
### Summary

When completing a directory with a large quanity of files and folders in the prompt, say with `:o`, if the directory in question has thousands of inodes, as does the `/nix/store` when using Nix, for example, typing becomes extremely laggy and difficult. Even pasting text takes a long time, and worse, makes helix unresponsive until finished.

I would guess that the entire directory is being crawled on each keystroke and that's why it takes so long.

### Reproduction Steps

The following asciinema shows a text being pasted into the prompt directly from the system clipboard:
https://asciinema.org/a/kV7WxOfdvmFxNwEUsPzQPDogT

### Helix log

No relevant log segment

### Platform

Linux

### Terminal Emulator

kitty 0.25.2

### Helix Version

22.05

**Comment by archseer** [comment]
Yep, there's no caching of any sorts, this runs every time completion is fetched: https://github.com/helix-editor/helix/blob/d2cec25395e01ded0977c1314e377cb24186c6c5/helix-term/src/ui/mod.rs#L383-L483

If would be good to limit to a subset of entries, but we'd need a way to start scanning from a certain "page" onwards

**Comment by archseer** [comment]
I think https://github.com/helix-editor/helix/blob/d2cec25395e01ded0977c1314e377cb24186c6c5/helix-term/src/ui/mod.rs#L416 should be removed since we're not recursively resolving. I also get decent performance after `:o /nix/store/` since the kernel will cache these types of lookups.

**Comment by archseer** [comment]
I think the problem here is that you're actually pasting on `22.05` where bracketed paste didn't exist yet. (https://github.com/helix-editor/helix/pull/3233) Can you try latest master?

**Comment by archseer** [comment]
https://github.com/helix-editor/helix/commit/8a4fbf6daf980b08de83e936c4a2b4bf8beaa2d4 https://github.com/helix-editor/helix/commit/e77b7d147cd03c4e7d7835993317150428b083ca

**Comment by nrdxp** [comment]
Thanks, it works as expected :pray:
