### ISSUE TITLE
Inconsistencies when selecting closest surrounding pair to cursor

### ISSUE THREAD

**Issue by icholy** [helix-editor/helix#3615]
### Summary

The `mam` command seems broken.

### Reproduction Steps

* `mam` has no effect here. I expected it to select the `[ ... ]` pair.

![image](https://user-images.githubusercontent.com/943597/187702208-e009e31e-35e1-4b00-b6cc-e3e838d21e19.png)

* `mam` has no effect here. I expected it to select the `[ ... ]` pair.

![image](https://user-images.githubusercontent.com/943597/187702301-c2dddbfc-56d1-4c3a-833a-52e74c9754a8.png)

* `mam` selects the parent `[ ... ]` pair. I expected to select the `{ ... }` pair.

![image](https://user-images.githubusercontent.com/943597/187702522-2898724e-3801-4ad2-91fb-3211e1036fe0.png)

* `mam` selects the `{ ... }` pair. This seems correct.

![image](https://user-images.githubusercontent.com/943597/187702966-d2e5e2d8-0a74-4e1a-bf8a-a1fe79639f2b.png)

### Platform

Linux

### Terminal Emulator

alacritty 0.9.0

### Helix Version

helix 22.05 (83f177d2)

**Comment by archseer** [comment]
This is intentional, it's supposed to select the next outer pair? I think you're looking for `vmm`

**Comment by icholy** [comment]
@archseer then why does the last example not select the surrounding `[ ... ]` ?

**Comment by the-mikedavis** [comment]
Looks like there might be an off-by-one: `mam` on a closing pair surrounds that pair instead of the parent

**Comment by morlinbrot** [comment]
> This is intentional, it's supposed to select the next outer pair? I think you're looking for vmm

Is it possible to discuss changing this default behaviour? At least to me, this feels very unintuitive. Sure, you can use `vmm` when on a pair but now I have to commit two different things to muscle memory, one for *in*, one for *on* the pair.

I think it would be more intutitive to make `mim`/`mam` always select, no matter if on opener, closer or inside the pair.
