### ISSUE TITLE
Theme preview doesn't return theme to normal when navigating command history

### ISSUE THREAD

**Issue by Omnikar** [helix-editor/helix#3620]
### Summary

The theme preview when using `:theme` will keep the previewed theme if you switch away from the command using history navigation.

### Reproduction Steps

1. Enter any (not necessarily valid) command, that is not a `:theme` command, such as `:abc<ret>`.
2. Type `:theme ` and hover the completion over a theme other than the currently selected one, thus previewing it.
3. Press the up arrow key, causing the command to switch to the one entered in step 1.
4. Press `<esc>`, exiting the command prompt.

The previewed theme will persist after the command is switched away from using the up arrow key.

### Helix log

Nothing relevant

### Platform

MacOS

### Terminal Emulator

iTerm2 v3.4.16

### Helix Version

Helix 22.08

**Comment by jharrilim** [comment]
I can make the following changes in a PR, but the gist of it is we need to:

1. Ensure that history navigation aborts the previous command. This can be done by changing

https://github.com/helix-editor/helix/blob/ec28b2b5ccf162e9df550e59a28e043d51796621/helix-term/src/ui/prompt.rs#L564-L575

to:

```rust
            ctrl!('p') | key!(Up) => {
                if let Some(register) = self.history_register {
                    (self.callback_fn)(cx, &self.line, PromptEvent::Abort);
                    let register = cx.editor.registers.get_mut(register);
                    self.change_history(register.read(), CompletionDirection::Backward);
                    (self.callback_fn)(cx, &self.line, PromptEvent::Update);
                }
            }
            ctrl!('n') | key!(Down) => {
                if let Some(register) = self.history_register {
                    (self.callback_fn)(cx, &self.line, PromptEvent::Abort);
                    let register = cx.editor.registers.get_mut(register);
                    self.change_history(register.read(), CompletionDirection::Forward);
                    (self.callback_fn)(cx, &self.line, PromptEvent::Update);
                }
            }
```

2. We need to ensure the completion items are updated too. This can be done by using the following code in the above functions after `change_history`:

https://github.com/helix-editor/helix/blob/ec28b2b5ccf162e9df550e59a28e043d51796621/helix-term/src/ui/prompt.rs#L590-L615

---

Unrelated to the issue above but discovered along the way: The preview isn't rolled back if you hold backspace and then enter a new command.

eg.

1. type `:theme acme`
2. hold backspace until it's just `:`
3. type `:open README.md` and press enter


This requires a change in this part:

https://github.com/helix-editor/helix/blob/ec28b2b5ccf162e9df550e59a28e043d51796621/helix-term/src/commands/typed.rs#L717-L726

to:

```rust
        PromptEvent::Update => {
            if args.is_empty() {
                cx.editor.unset_theme_preview();
            } else if let Some(theme_name) = args.first() {
                if let Ok(theme) = cx.editor.theme_loader.load(theme_name) {
                    if !(true_color || theme.is_16_color()) {
                        bail!("Unsupported theme: theme requires true color support");
                    }
                    cx.editor.set_theme_preview(theme);
                };
            };
        }
```
