### ISSUE TITLE
Improve vi emulation

### ISSUE THREAD

**Issue by kallisti5** [helix-editor/helix#3623]
Some pretty basic vi keystroke are missing from the "vi like" user interface.

**basic**
* dd - cut current line into clipboard

**advanced**
* d1l , d1w - cut 1 letter into clipboard, cut 1 word into clipboard
* [visual block mode](https://github.com/helix-editor/helix/discussions/1824) - ctl + v to edit multiple lines at once (handy for mass-commenting code blocks, etc)

**Comment by kallisti5** [comment]
I'm opening this understanding helix shouldn't be a 1:1 vi replacement, but the above are really handy and muscle memory for a lot of folks.

**Comment by kallisti5** [comment]
I was pointed to https://raw.githubusercontent.com/LGUG2Z/helix-vim/master/config.toml which fills in a *bunch* of vi compatibility gaps.

Ya'll should make these standard :-)

**Comment by archseer** [comment]
Visual block mode: Use v to select a range, then shift-x (X) to expand to a block.

Kakoune style bindings are fundamentally different in that commands simply act on selections and there's no operator pending mode like in vim (where the editor enters a waiting state when you press `d` to figure out exactly **what** you're deleting). We can't really support that without a rewrite.

https://github.com/helix-editor/helix/wiki/Migrating-from-Vim

I'd urge you to try and adapt your muscle memory: it's a bit painful at first but it's a lot more consistent:

`dd`: `xd` select line then delete selection
`d1l`: `d` delete selection
`d1w`: `wd` select word then delete selection

Maybe vim could instead emulate kakoune to make it easier for users to switch :P
