### ISSUE TITLE
'o' not working correctly on windows 10

### ISSUE THREAD

**Issue by janhrastnik** [helix-editor/helix#363]
I assume 'o' is breaking because of the Crlf line ending on windows.

### Reproduction steps

In the included gif I open a new file, then press 'o', then 'a', 'a', 'a'.
![newline6](https://user-images.githubusercontent.com/25058758/123178078-c8881600-d486-11eb-89f1-3253ff94b343.gif)

### Environment

Windows 10

**Comment by cessen** [comment]
Yeah, that looks like probably a CRLF bug.  I'll take a look.

**Comment by cessen** [comment]
Tracked down the bug.  Working on a fix now.

**Comment by cessen** [comment]
Mostly fixed.  One case left I have to figure out.  I've gotta head out for something, but I'll resume the fix when I get back.

**Comment by cessen** [comment]
Made a PR with the fix.
