### ISSUE TITLE
space + F show entire workspace files

### ISSUE THREAD

**Issue by nour-dev** [helix-editor/helix#3651]
### Summary

  when I click `space+F` the filepicker show the workspace directory (git project). not only current working directory files.
   and when I try to check the `CWD` from commands even when I opened file in sub directories. it shows the workspace directory (project root with git repo). 

### Reproduction Steps

 

I tried this:

1. `hx` in project with git repo
2. I opened file in `plans/subproject/file.md`
3. when I tried to list CWD files `subproject` directory by click `space+F`

I expected to see only files in the `subproject` directory.

Instead, I saw all the root project files.

### Platform

Linux

### Terminal Emulator

kitty

### Helix Version

helix 22.08.1 (66276ce6)

**Comment by the-mikedavis** [comment]
This is the expected behavior: `hx` in the root of the repo sets the CWD to the root of the repo. You can check the CWD with `:pwd` and use `hx plans/subproject` or `:cd plans/subproject` to change the CWD to some other directory.

Opening a document doesn't automatically change the CWD. https://github.com/helix-editor/helix/issues/2056 covers that behavior.

**Comment by nour-dev** [comment]
> This is the expected behavior: `hx` in the root of the repo sets the CWD to the root of the repo. You can check the CWD with `:pwd` and use `hx plans/subproject` or `:cd plans/subproject` to change the CWD to some other directory.
> 
> Opening a document doesn't automatically change the CWD. #2056 covers that behavior.

yes . using `:cd plans/sub` worked. but is there any way to change `cwd`based on current active buffer ?

**Comment by the-mikedavis** [comment]
> but is there any way to change `cwd` based on current active buffer ?

That's what #2056 covers
