### ISSUE TITLE
JSON formatter removing new lines

### ISSUE THREAD

**Issue by willparsons** [helix-editor/helix#3656]
Is there any way to disable this? Is it an editor or formatter setting?

**Comment by David-Else** [comment]
It is in the language server I assume, the default settings for JSON are in `languages.toml`:
```
 [[language]]
  name = "json"  
  scope = "source.json"
  injection-regex = "json"
  file-types = ["json"]
  roots = []
  language-server = { command = "vscode-json-language-server", args = ["--stdio"] }
  auto-format = true
  config = { "provideFormatter" = true }
  indent = { tab-width = 2, unit = "  " }
```
You can add your own config settings to it in the `config = {}` section.

You could turn off auto format on save by making your own `languages.toml` in your config dir:
```
[[language]]
  name = "json"  
  auto-format = false
```
I use Prettier instead, npm install it globally:
```
[[language]]
name = "json"
formatter = { command = 'prettier', args = ["--parser", "json"] }
```
No problem with that. Don't know why the default formatter is removing new lines, maybe it thinks it is a good idea.

**Comment by willparsons** [comment]
Thanks for the reply @David-Else. Prettier would probably be the easiest thing to adopt here but out of curiosity how could I find what config parameters `vscode-json-language-server` takes? iirc it's not easy to find.

**Comment by David-Else** [comment]
I had a look about, and you are right, it is not easy to find! I think if you want to compete your mission the answer will be inside: https://github.com/microsoft/vscode/blob/c8bd5b211acd8055a81654dcf40367f422bc22e0/extensions/json-language-features/server/src/jsonServer.ts

**Comment by willparsons** [comment]
Looking [here](https://github.com/microsoft/vscode/tree/main/extensions/json-language-features/server) it seems that the server supports this [formatting feature](https://microsoft.github.io/language-server-protocol/specifications/lsp/3.17/specification/#textDocument_rangeFormatting) which can take `options`  which has a `insertFinalNewline` member. I'm going to see if somehow I can pass it down through config but this seems like they really want people to just keep it in VSCode 👎🏻

**Comment by willparsons** [comment]
Ok so I found in the server code that it takes some settings, one of which is `keepLines`.

```toml
config = { "provideFormatter" = true, "json" = { "keepLines" = { "enable" = true } } }
```

**Comment by David-Else** [comment]
Nice find! It might be cool to add that info to the WIKI https://github.com/helix-editor/helix/wiki/How-to-install-the-default-language-servers or a link to the available options.

**Comment by willparsons** [comment]
I added a link to the settings interface in the wiki, hopefully then its easy to check if any changes have been made on JSONLS side.
