### ISSUE TITLE
No files show up in file picker

### ISSUE THREAD

**Issue by iio7** [helix-editor/helix#3662]
### Summary

The file picker shows no files in any directory.

### Reproduction Steps

```
$ echo "Hello" > hello.txt
$ echo "Foo" > foo.txt
$ echo "# Bar" > bar.md
$ nvim hello.txt
```

Using `:e` and TAB in Neovim, just as an example, displays the files that Neovim can see and open.

![Screenshot from 2022-09-03 03-20-40](https://user-images.githubusercontent.com/12476695/188250433-8d239eb6-71c6-4756-a50f-7a9297d2b0c6.png)

Doing the same in Helix gives an empty list:

```
$ helix hello.txt
```
![Screenshot from 2022-09-03 03-23-06](https://user-images.githubusercontent.com/12476695/188250565-3820585e-0eef-4ced-b3e8-8765dcba2071.png)

![Screenshot from 2022-09-03 03-23-23](https://user-images.githubusercontent.com/12476695/188250571-b85b319f-5ce6-465f-8984-6d7ade640d47.png)

No files are displayed for selection.

### Helix log

I have nothing in ~/.cache/helix/helix.log`, the file is there, but it is empty.

### Platform

Arch Linux 5.19.6-arch1-1

### Terminal Emulator

XTerm(372)

### Helix Version

helix 22.08.1

**Comment by kirawi** [comment]
Are you able to open these files via `:o`?

**Comment by iio7** [comment]
> Are you able to open these files via `:o`?

Yes, but I cannot press TAB or anything to see the files prior to opening, I need to know in advance the exact filename and location in order to use `:o`.

**Comment by archseer** [comment]
Do you have a ignore/git ignore file? Could also be a global one

**Comment by iio7** [comment]
> Do you have a ignore/git ignore file? Could also be a global one

Yes, indeed. I have just disabled reading `.gitignore` and it works now. I didn't know about that option.

Thanks.
