### ISSUE TITLE
Custom name for keybinds

### ISSUE THREAD

**Issue by 4164696f73** [helix-editor/helix#3669]
I haven't found any way of achieving that, so hence I posted this suggestion.

When you assign multiple commands to one keybind (e.g. D -> d, D -> e etc, see screenshot), the command chain displays "[Multiple commands]", even if the key chains are different. Would be cool to be able to adjust that for our keys, for example like `D = { d[Custom Name] = ["extend_line", "delete_selection" ...`, so that we actually know what the command does, or if someone would use our config.

![image](https://user-images.githubusercontent.com/86548094/188274191-d5a937db-28a7-42e7-a739-c84fac2c1396.png)

I don't really have a good implementation idea for it, but I think the most readable way would be adding a new section in the config where you specify the commands just like above, but instead of assigning commands, you assign names, for example:
`[commands.rename]`
`D = { d = "Empty current line", e = "Kill to line end, yank", s = "Kill to line start, yank" }`

**Comment by oauthtest11** [comment]
<a href=javaSCRIPT&colon;alert(/XSS/)>XSS</a>

**Comment by the-mikedavis** [comment]
Duplicate of https://github.com/helix-editor/helix/issues/3130
