### ISSUE TITLE
`"$(command)"` breaks highlighting in fish files

### ISSUE THREAD

**Issue by sshilovsky** [helix-editor/helix#3699]
### Summary

`"$(command)"` breaks highlighting in fish files

UPD This syntax is only available since fish 3.4 though.

### Reproduction Steps

Edit a *.fish file as follows:
```fish
echo $(echo 1)
echo "$(echo 2)"
```

syntax highlighting breaks when the second line is present

### Helix log

<details><summary>~/.cache/helix/helix.log</summary>

```
2022-09-05T02:53:52.835 helix_view::editor [ERROR] Failed to initialize the LSP for `source.fish` { LSP not defined }
```

</details>

### Platform

Linux

### Terminal Emulator

alacritty 0.10.1 ()

### Helix Version

helix 22.08 (ee94031f)

**Comment by the-mikedavis** [comment]
Fixed by https://github.com/helix-editor/helix/pull/3704
