### ISSUE TITLE
C-backspace = "delete_word_backward" doesn't work, should be fixed in Crossterm 0.25

### ISSUE THREAD

**Issue by David-Else** [helix-editor/helix#3725]
### Summary

In my config:
```
C-backspace = "delete_word_backward"
```
Does nothing in Kitty and Gnome Terminal. Crossterm 0.25 added functional key codes from the Kitty keyboard protocol https://github.com/crossterm-rs/crossterm/releases/tag/0.25 , so it should at least work for Kitty. @groves I think they need to be enabled?

(Works in Neovim with `vim.keymap.set('i', '<C-H>', '<C-W>')`)

### Platform

Linux

### Terminal Emulator

Kitty

### Helix Version

22.08.1

**Comment by archseer** [comment]
Should be easy to do:
```rust
use std::io::{Write, stdout};
use crossterm::execute;
use crossterm::event::{
    KeyboardEnhancementFlags,
    PushKeyboardEnhancementFlags,
    PopKeyboardEnhancementFlags
};

let mut stdout = stdout();

execute!(
    stdout,
    PushKeyboardEnhancementFlags(
        KeyboardEnhancementFlags::DISAMBIGUATE_ESCAPE_CODES
    )
);

// ...

execute!(stdout, PopKeyboardEnhancementFlags);
```

But not sure if crossterm does all the detection needed for progressive enhancement: https://sw.kovidgoyal.net/kitty/keyboard-protocol/#detection-of-support-for-this-protocol

**Comment by David-Else** [comment]
@archseer Great news! Afraid I have only just began my Rust journey, could you implement it? :)
