### ISSUE TITLE
Specify custom injections in `.config/helix`

### ISSUE THREAD

**Issue by 414owen** [helix-editor/helix#3732]
I have `helix 22.08 (ee94031f)` installed from `nixpkgs`.

Helix doesn't seem to load `injections.scm` from `~/.config/helix/runtime/queries/haskell`, or anywhere similar (I ran `strace` to see where it looks).

It would be great to be able to specify custom injections, for example, I'd like to be able to highlight the sql in my haskell, and the bash in my nix.

I guess the more general enhancement would be `load locally specified runtime files, and merge them with the global versions`?

**Comment by archseer** [comment]
It currently reads queries from a single runtime path, but I think we should support multiple: it should look into `HELIX_RUNTIME`, as well as `~/.config/helix/runtime` for files.

**Comment by the-mikedavis** [comment]
Yeah this would be more sane behavior. I think this falls under https://github.com/helix-editor/helix/issues/3346 so I'll close in favor of that one
