### ISSUE TITLE
Panic when closing split window

### ISSUE THREAD

**Issue by robem** [helix-editor/helix#3747]
### Summary

I have a vertically split window that I'm closing with <Ctrl-w><q> at which point it panics.

```
thread 'main' panicked at 'invalid HopSlotMap key used', helix-view/src/tree.rs:288:20
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

### Reproduction Steps

1. Run `hx`
2. `<Ctrl-w><v>`
3. `<Ctrl-w><q>` -> Panic

### Helix log

_Empty_

### Platform

Linux

### Terminal Emulator

st

### Helix Version

helix 22.08 (ec28b2b5)

**Comment by the-mikedavis** [comment]
Duplicate of https://github.com/helix-editor/helix/issues/3626
