### ISSUE TITLE
Ctrl-z in nushell sends the terminal into an unusable state.

### ISSUE THREAD

**Issue by cyanic-selkie** [helix-editor/helix#3761]
### Summary

Nushell doesn't have moving processes to background/foreground implemented yet and therefore Ctrl-z shouldn't do anything - this is how other software I tried behaves.

However, helix seemingly "exits" and leaves the terminal in an unusable state. Furthermore, killing the terminal leaves the helix process running in the background.

I tried testing this on alacritty with both nushell and bash. Everything works as expected in bash where background/foreground is implemented.

### Reproduction Steps

 

I tried this:

1. `nu`
2. `hx`
3. Ctrl-z

I expected this to happen:
Nothing.

Instead, this happened:
Helix seemingly "exited" and left the terminal in an unusable state. Killing the terminal left the helix process running in the background.

### Helix log

<details><summary>~/.cache/helix/helix.log</summary>
        empty
</details>

### Platform

Linux

### Terminal Emulator

alacritty 0.10.1-2

### Helix Version

helix 22.08.1 (59f7b07c)

**Comment by the-mikedavis** [comment]
This might be fixed by https://github.com/helix-editor/helix/pull/3322 or https://github.com/helix-editor/helix/pull/3546

Could you try suspending from nushell with either of those?

**Comment by cyanic-selkie** [comment]
Indeed, #3322 works. Hitting Ctrl-Z triggers the following message in the statusline: "Suspend is not supported by this terminal."

#3646 has no effect.

**Comment by the-mikedavis** [comment]
Ah, seems like nushell has the same suspend behavior as elvish then. Let's close this in favor of https://github.com/helix-editor/helix/issues/3321
