### ISSUE TITLE
hx --tutor or :tutor don't work when hx is symlink

### ISSUE THREAD

**Issue by bnoordhuis** [helix-editor/helix#3768]
### Summary

The tutor doesn't work when hx is invoked through a symlink. The real path works.

### Reproduction Steps

 

I tried this:

1. download and untar helix to $HOME/opt/helix
2. `cd $HOME/bin && ln -s ../opt/helix/hx` (~/bin is on the PATH)
3. `hx --tutor`

I expected this to happen:

See the tutorial. :-)

Instead, this happened:

Nothing. Empty buffer.

### Helix log

No log file was written.

### Platform

macOS

### Terminal Emulator

Terminal.app

### Helix Version

helix 22.08.1 (66276ce6)

**Comment by the-mikedavis** [comment]
Does syntax highlighting work either when `hx` is a symlink? I think the symlink is breaking the detection of the runtime directory. You can set an explicit `$HELIX_RUNTIME` environment variable to the runtime directory path to fix it.

The tutor is loaded from the runtime directory: https://github.com/helix-editor/helix/blob/fae9203c3efd4dee4ac0234090ab9c3163c3e4f7/helix-term/src/application.rs#L160-L163

**Comment by bnoordhuis** [comment]
Syntax highlighting indeed doesn't work.

I believe runtime_dir() ultimately falls back to `std::env::current_exe()`? Can I suggest running that through `std::fs::canonicalize()` to get the real path?

(I can try putting together a PR sometime next week.)

**Comment by 9glenda** [comment]
On my nixos install helix is also a symlink (like on every nixos install) and the tutor works
here info about my symlink:
```
[glenda@nixos:~]$ ls -lah $(which hx)
lrwxrwxrwx 1 root root 62 Jan  1  1970 /run/current-system/sw/bin/hx -> /nix/store/skpa4rd1h3s23b1h1v6y5rn58vq1zd5i-helix-22.08/bin/hx
```
If there are any issues with helix being a symlink nixos users will always suffer from them.

**Comment by the-mikedavis** [comment]
Nix builds set the `HELIX_RUNTIME` environment variable ([nixpkgs](https://github.com/NixOS/nixpkgs/blob/1cea3c2362ef8af81d4e66898336094b3f9710ee/pkgs/applications/editors/helix/default.nix#L28), this repo's [flake](https://github.com/helix-editor/helix/blob/ec81ec1e8d26e3a99ed713b79381a77daf817d34/flake.nix#L142))

**Comment by rayhem** [comment]
I'm not sure if this is the same issue or just the same symptom because I'm super new to Helix, but I followed the [build-from-source instructions](https://docs.helix-editor.com/install.html?highlight=Build#build-from-source) on a Debian 11 machine (clone repo & `$ cargo install --path helix-term`, helix version d14de277) and I've not gotten `hx --tutor` to do anything meaningful. I've tried running both with and without links to helix, as well as running the executable directly with both relative and absolute pathing and the application only ever shows me an empty buffer.

**Comment by the-mikedavis** [comment]
If you installed from source, you need to link the runtime directory: https://github.com/helix-editor/helix/blob/d14de277092d7eab555ea2abc1435101d12e308c/README.md#L60-L67
