### ISSUE TITLE
Arrow keys not working in insert mode.

### ISSUE THREAD

**Issue by SamuelMcGowan** [helix-editor/helix#3770]
### Summary

I'm going through the tutorial and it says that I can use the arrow keys to move the cursor while in insert mode, but they don't do anything for me. They work fine in normal mode, and moving the cursor with the mouse works fine.

### Reproduction Steps

Press any arrow key while in insert mode.

### Helix log

```
2022-09-09T22:29:14.569 helix_view::editor [ERROR] Failed to initialize the LSP for `source.toml` { cannot find binary path }
```

### Platform

Linux (Pop OS)

### Terminal Emulator

kitty 0.21.2

### Helix Version

helix 22.08.1 (fae9203c)

**Comment by CamilleMo** [comment]
I had the same bug installing from the master branch today. The last release is working fine though

**Comment by the-mikedavis** [comment]
This is expected after https://github.com/helix-editor/helix/pull/3671
