### ISSUE TITLE
Add the ability to ignore some file extensions in the fuzzy search

### ISSUE THREAD

**Issue by jvoisin** [helix-editor/helix#3778]
When dealing with web-related codebases, it's not uncommon to have a ton of pictures in the source folders. It would be nice to be able to tell Helix to not show files ending with `.png`, `.jpg`, `.min.js`, `.o`, `.pdf`, … in its configuration file.

**Comment by archseer** [comment]
You can configure it by adding a .gitignore/.ignore file.
