### ISSUE TITLE
Cannot move cursor with arrow keys in insert mode.

### ISSUE THREAD

**Issue by fvacek** [helix-editor/helix#3787]
### Summary

Cannot move cursor with arrow keys in insert mode.

### Reproduction Steps

I tried this:

1. `hx`
2. `i` `foo`
3. `left-arrow` to move cursor back

I expected this to happen:
1. the cursor advance one step to the left

Instead, this happened:
1. nothing happened

### Helix log

<details><summary>~/.cache/helix/helix.log</summary>

```
nothing
```

</details>

### Platform

Linux

### Terminal Emulator

Konsole, Tilix

### Helix Version

a15420ed1c3b46df0dade6ec6d05a0e4b26e06e0

**Comment by the-mikedavis** [comment]
Duplicate of https://github.com/helix-editor/helix/issues/3762
