### ISSUE TITLE
error helix_shortcode.php:24

### ISSUE THREAD

**Issue by Twin02Daddy** [helix-editor/helix#3800]
Joomla 3.10.11 - PHP 8.0 - Helix 2.0.11 - JCE editor PRO 2.9.18

asort(): Argument #1 ($array) must be of type array, null given

plugins/editors-xtd/helix_shortcode/helix_shortcode.php:24

**Comment by sudormrfbin** [comment]
You might want to post to https://github.com/JoomShaper/Helix-Joomla instead, this is not the correct repo :)
