### ISSUE TITLE
Use `deno lsp` when opening a project with `deno.jsonc?`

### ISSUE THREAD

**Issue by wojpawlik** [helix-editor/helix#3804]

**Comment by sambigelow** [comment]
It looks like [this documentation on using deno](https://github.com/helix-editor/helix/wiki/How-to-install-the-default-language-servers#deno) could get you pretty close to what you want. I think you'd just have to add `deno.jsonc` to the root.

**Comment by wojpawlik** [comment]
Awesome link! It should be added to https://docs.helix-editor.com/languages.html. And ideally upstreamed to https://github.com/helix-editor/helix/blob/master/languages.toml, once I figure what to do with repos with both `package.json` and `deno.json`...

**Comment by dead10ck** [comment]
It looks like all of these currently have a default LS already. Glad there's a solution for you 🙂
