### ISSUE TITLE
Add a recents file picker similar to lunarvim

### ISSUE THREAD

**Issue by evccyr** [helix-editor/helix#3812]
There's a recents file picker in LunarVim(open with `<space>sr`). It is basically one of telescopes picker. I'm not sure which [one of these](https://github.com/nvim-telescope/telescope.nvim#vim-pickers) but I've posted a picture in [this discussion](https://github.com/helix-editor/helix/discussions/3809)

**Comment by zim0369** [comment]
When I open that picker it shows me a fuzzy list of files that I've ever opened in my editor

**Comment by pascalkuthe** [comment]
This is a duplicate of #2179 (which is both older and has additional discussion) so I am closing this in favor of that
