### ISSUE TITLE
Warnings are highlighted as tips in tsx files

### ISSUE THREAD

**Issue by DoctorRyner** [helix-editor/helix#3822]
### Summary

This should be yellow instead of being white
<img width="1280" alt="Bildschirmfoto 2022-09-12 um 20 08 51" src="https://user-images.githubusercontent.com/24430919/189703187-ad61870b-1416-4e5c-bbac-2d7ad1d3b157.png">

### Platform

macOS

### Terminal Emulator

The latest iTerm 2

### Helix Version

22.08.1

**Comment by sudormrfbin** [comment]
Which theme are you using? The theme needs a `diagnostic.warning` key defined to color them properly.

**Comment by DoctorRyner** [comment]
I know, I use my custom version of dark_plus theme and warnings are yellow in Rust but they are displayed with a tip color in tsx

**Comment by DoctorRyner** [comment]
<img width="1280" alt="Bildschirmfoto 2022-09-12 um 21 27 26" src="https://user-images.githubusercontent.com/24430919/189718213-b4b76fa2-2d6d-4c2c-95cd-0907e22f37d4.png">

**Comment by sudormrfbin** [comment]
Maybe the language server is not reporting it as warning? Warnings and errors have their total count displayed in the status line and the tsx file doesn't have it, so I'm guessing the language server itself it simply reporting it as an info or hint level diagnostic.

**Comment by DoctorRyner** [comment]
Hm, it seems so

**Comment by sudormrfbin** [comment]
Seems like you can add the [`compilerOptions.noUnusedLocals`][1] option in your [`tsconfig.json`][2] to make it a hard error.

[1]: https://www.typescriptlang.org/tsconfig#noUnusedLocals
[2]: https://www.typescriptlang.org/docs/handbook/tsconfig-json.html

**Comment by DoctorRyner** [comment]
Hmmm, it's the same behaviour as in the VS Code, I'm closing the issue then
<img width="716" alt="Bildschirmfoto 2022-09-12 um 22 40 35" src="https://user-images.githubusercontent.com/24430919/189731238-bf997559-328c-48a0-952e-96607843cf74.png">
