### ISSUE TITLE
Highlight long lines

### ISSUE THREAD

**Issue by asim215** [helix-editor/helix#3831]
Hello. Does helix have any setting for set highlight long lines? I want to set it to 80 characters. It does exist in SpaceVim. See screenshot example:

![highlight_long_lines](https://user-images.githubusercontent.com/7127165/189845604-76f2118d-fe0d-4df6-a200-e7053462df45.png)

**Comment by Ordoviz** [comment]
Add `rulers = [80]` to the `[editor]` section in your [config file](https://docs.helix-editor.com/configuration.html). In the future, ask questions like this on Matrix or [GitHub discussions](https://github.com/helix-editor/helix/discussions).

**Comment by asim215** [comment]
> Add `rulers = [80]` to the `[editor]` section in your [config file](https://docs.helix-editor.com/configuration.html). In the future, ask questions like this on Matrix or [GitHub discussions](https://github.com/helix-editor/helix/discussions).

Sorry, I will. Thank you.
