### ISSUE TITLE
Add support for D

### ISSUE THREAD

**Issue by gdamore** [helix-editor/helix#3832]
There is an LSP server called serve-d, but for whatever reason I had very little luck in getting it to work with Helix.

It would be nice if this worked more or less out of the box.

A tree-sitter grammar is here: https://github.com/CyberShadow/tree-sitter-d

**Comment by willcab** [comment]
could you provide more information on what steps you tried?

**Comment by gdamore** [comment]
I am working on an improved tree-sitter grammar for D.  It is sort of working, but not ready for prime time yet.  Stay tuned.

it would be ok to assign this bug to me.

**Comment by gdamore** [comment]
I've got the draft grammar up now -- https://github.com/gdamore/tree-sitter-d --- this seems to work pretty well with Helix.
