### ISSUE TITLE
visually distinct active tab and file(edited) status indicators

### ISSUE THREAD

**Issue by zim0369** [helix-editor/helix#3833]
![tabline](https://user-images.githubusercontent.com/85027668/189888964-dedb264a-2090-4cfb-ad04-28999c7d56fb.png)

In the above tabline from neovim you might be able to see a thin blue vertical line at the start of the active tab.
That is too thin for it's purpose but having a similar indicator or an underline under the active tab would be perceptible for quick grasp.

Regarding the "file edited" status which is shown using `[ + ]`, could be replaced with something else that's again visually distinct and brighter.

**Comment by sudormrfbin** [comment]
The style of the active buffer can be configured with the `ui.bufferline.active` theme key and the background is controlled for other tabs are configured with `ui.bufferline.background`. Seems like this went undocumented in #2759 (\cc @aaron404).

**Comment by kirawi** [comment]
Fixed by https://github.com/helix-editor/helix/pull/3690

**Comment by zim0369** [comment]
not sure what #3690 exactly tries to fix but half of this issue could be fixed by choosing better bufferline colors as I did in [this PR](3881)
