### ISSUE TITLE
Remove backspace, delete, etc., bindings from insert mode for consistency

### ISSUE THREAD

**Issue by aral** [helix-editor/helix#3861]
Further to #3671, if we’re going to stick with insert mode being for insertion only, the following bindings should also be removed from insert mode for consistency:

  - Backspace
  - Delete
  - Delete previous word
  - Delete next word
  - Delete to start of line
  - Delete to end of line

(The other option, of course, is to revert #3671. Either way, the interface provided should be consistent.)

**Comment by the-mikedavis** [comment]
I don't see these bindings as inconsistent with the removals of #3671. #3671 covers navigation/movement while these are deletion actions.

**Comment by aral** [comment]
@the-mikedavis Deletion in _insert_ mode? We have deletion commands already (mapped to `d`). If our design constraint is that people should not be bringing their non-modal habits with them, these should go to. The modal way to do it, surely, is to exit insert mode and use the delete command.

**Comment by dead10ck** [comment]
@aral you're taking the terms too literally. "insert mode" is for editing text. Inserting characters and deleting them. The reasons that navigation were removed were detailed in the PR's discussion. Take a closer read of the comments there.

**Comment by David-Else** [comment]
Removing delete in insert mode would be madness.

When touch typing it is best practice to delete the entire last word if you make a mistake to improve muscle memory. Having to enter normal mode to do that would not be workable.

**Comment by archseer** [comment]
There's a "selection mode" and a "text editing mode". We could rename them but INS reads a lot better than TXE.

**Comment by archseer** [comment]
If you're trying to start a discussion about reintroducing those mappings then please do so instead of making a snarky issue :)

**Comment by YangtseSu** [comment]
> @aral you're taking the terms too literally. "insert mode" is for editing text. Inserting characters and deleting them. The reasons that navigation were removed were detailed in the PR's discussion. Take a closer read of the comments there.

Helix is designed to work well with modal editing.
"insert mode" should be insert only.  You can enter normal mode and delete characters with d, after disabling deletion in "insert mode".

**Comment by aral** [comment]
> If you're trying to start a discussion about reintroducing those mappings then please do so instead of making a snarky issue :)

Done (https://github.com/helix-editor/helix/discussions/3865), but please understand this isn’t (an overly) ;) snarky issue. There _is_ an inconsistency being introduced by this.

**Comment by archseer** [comment]
@YangtseSu Your tone isn't helping this discussion.
