### ISSUE TITLE
Previous selections like vim's `gv`

### ISSUE THREAD

**Issue by zim0369** [helix-editor/helix#3868]
If I have to bring up my previous selection in helix I wish I'd saved it with `C-s`. In vim it is as simple as `gv`.

A similar thing would be more convenient rather than having to save selections.

**Comment by the-mikedavis** [comment]
This would be covered by https://github.com/helix-editor/helix/issues/1596

**Comment by zim0369** [comment]
I couldn't understand if that was exactly similar to vim's `gv`. If it is then please feel free to close.
