### ISSUE TITLE
Add command names to command palette

### ISSUE THREAD

**Issue by taupiqueur** [helix-editor/helix#3870]

**Comment by A-Walrus** [comment]
Could you please add a description explaining what exactly you mean?

**Comment by Dessertion** [comment]
I just ran into this exact issue; for example, the `:` command to reload the user's Helix config is `:config-reload` and its description when you hover over it is `Refresh user config.`

However, when using the command palette, `:config-reload` only shows up if you search relevant terms in `Refresh user config.` -- notably, this means that searching `reload` will not show the `:config-reload` command. The command palette also does not name the exact command that one could input manually via `:`. 

@taupiqueur is likely suggesting something akin to Emacs's consult.el, which displays the name of the command, the key shortcuts associated with it, and a short description of said command.

**Comment by nuid32** [comment]
You mean something like that?

![command_palette](https://user-images.githubusercontent.com/91177333/193462487-8789f4d6-524f-4939-a186-93be9527f952.png)
