### ISSUE TITLE
Add indicators for offscreen selections

### ISSUE THREAD

**Issue by taupiqueur** [helix-editor/helix#3873]
Implementation reference: https://github.com/71/dance/blob/master/src/state/editors.ts#:~:text=_updateOffscreenSelectionsIndicators

**Comment by Ordoviz** [comment]
IMHO this is the best solution for #2103, we just need to find a good place to show these indicators in the TUI. See also #3534

**Comment by kirawi** [comment]
Duplicate of https://github.com/helix-editor/helix/issues/2103
