### ISSUE TITLE
can't install helix

### ISSUE THREAD

**Issue by tasuren** [helix-editor/helix#389]
rustc and cargo version : 1.53.0
I can't install helix
This error says `warning: slotmap requires rustc => 1.49.0` but I use 1.53.0
What should I do to fix this error?

```rust
error[E0658]: unions with non-`Copy` fields are unstable
  --> /root/.cargo/registry/src/github.com-1ecc6299db9ec823/slotmap-1.0.3/src/basic.rs:19:1
   |
19 | / union SlotUnion<T> {
20 | |     value: ManuallyDrop<T>,
21 | |     next_free: u32,
22 | | }
   | |_^
   |
   = note: see issue #55149 <https://github.com/rust-lang/rust/issues/55149> for more information

error[E0658]: unions with non-`Copy` fields are unstable
  --> /root/.cargo/registry/src/github.com-1ecc6299db9ec823/slotmap-1.0.3/src/hop.rs:39:1
   |
39 | / union SlotUnion<T> {
40 | |     value: ManuallyDrop<T>,
41 | |     free: FreeListEntry,
42 | | }
   | |_^
   |
   = note: see issue #55149 <https://github.com/rust-lang/rust/issues/55149> for more information

error: aborting due to 2 previous errors

For more information about this error, try `rustc --explain E0658`.
The following warnings were emitted during compilation:

warning: slotmap requires rustc => 1.49.0

error: could not compile `slotmap`.

To learn more, run the command again with --verbose.
warning: build failed, waiting for other jobs to finish...
error: failed to compile `helix-term v0.3.0 (/media/tasuren/HDDドライブ3-2TB/Ubuntu共有フォルダー/tmp/helix/helix-term)`, intermediate artifacts can be found at `/media/tasuren/HDDドライブ3-2TB/Ubuntu共有フォルダー/tmp/helix/target`

Caused by:
  build failed
```

**Comment by Apppppppple** [comment]
`rustc --explain E0658`:
If you're using a stable or a beta version of rustc, you won't be able to use
any unstable features. In order to do so, please switch to a nightly version of
rustc (by using [rustup]).

**Comment by pickfire** [comment]
Can you please post your `rustup --show` and `cargo -V`? Can you also try `cargo clean && cargo install --path helix-term`? Sometimes rust lately I see caching issues such that `cargo check` works but `cargo run` does not (bug filled in rust).

**Comment by archseer** [comment]
I think it's finding your system installed `cargo`/`rustc` instead of your rustup one. Besides `cargo -V`, I'd also check `which cargo`

**Comment by pickfire** [comment]
Is this still an issue?

**Comment by tasuren** [comment]
I'm sorry for the delay in replying.
As a result of my research, I found out that when I used sudo to run the installation, it used Rust in a different location.
I apologize for the inconvenience.
