### ISSUE TITLE
bufferline is unknown field

### ISSUE THREAD

**Issue by notwidow** [helix-editor/helix#3892]
Hi, according to the helix config guide on helix-edtior.com the 2nd last option in editor section is bufferline having 3 values. but helix says bufferline is unknown field.
in editor section.
** Steps to reproduce **
in config.toml 
```ruby
[editor]
bufferline = 'always'
```
upon reloading gives error ``` bufferline is unknown field...```

**Comment by the-mikedavis** [comment]
What version are you running?

Bufferline was merged after the 22.08.1 release. https://docs.helix-editor.com/master/configuration.html follows master and https://docs.helix-editor.com/configuration.html follows the latest release.

**Comment by notwidow** [comment]
> What version are you running?
> 
> Bufferline was merged after the 22.08.1 release. https://docs.helix-editor.com/master/configuration.html follows master and https://docs.helix-editor.com/configuration.html follows the latest release.

helix 22.08.1

**Comment by notwidow** [comment]
> What version are you running?
> 
> Bufferline was merged after the 22.08.1 release. https://docs.helix-editor.com/master/configuration.html follows master and https://docs.helix-editor.com/configuration.html follows the latest release.

i did pacman -S helix in arch rolling

**Comment by the-mikedavis** [comment]
You will need to build from source or use a package that follows master in order to use bufferline. `helix-git` in the AUR follows master https://aur.archlinux.org/packages/helix-git

**Comment by notwidow** [comment]
> You will need to build from source or use a package that follows master in order to use bufferline. `helix-git` in the AUR follows master https://aur.archlinux.org/packages/helix-git

okay and in the next update it will be added to the rolling one also?

**Comment by the-mikedavis** [comment]
Yep, the next release will include bufferline

**Comment by notwidow** [comment]
> Yep, the next release will include bufferline

okay thank you .. but can you tell me whi statusline does not show spinner ?
i setted spinner option in left next to mode option but it does not show.. and i have color-modes = true statusline mode have no colors..

**Comment by the-mikedavis** [comment]
The spinner is shown when receiving LSP progress messages from a language server. You will need a language server configured and installed. Also, not all language servers send progress messages, so even if the language server is active the spinner may not show. Rust-analyzer sends progress messages and shows the spinner.

**Comment by notwidow** [comment]
> The spinner is shown when receiving LSP progress messages from a language server. You will need a language server configured and installed. Also, not all language servers send progress messages, so even if the language server is active the spinner may not show. Rust-analyzer sends progress messages and shows the spinner.

okay and i don't use lsp so ..thanks  and what about color-modes  = true not displaying in colored

**Comment by the-mikedavis** [comment]
That may depend on the theme you're using. A theme needs to color `ui.statusline.insert`, `ui.statusline.normal`, and `ui.statusline.select` for color-modes to have a visual effect. Whichever theme you're using may not define those

**Comment by notwidow** [comment]
> That may depend on the theme you're using. A theme needs to color `ui.statusline.insert`, `ui.statusline.normal`, and `ui.statusline.select` for color-modes to have a visual effect. Whichever theme you're using may not define those

i use tokyonight. and yes i checked all the themes... tokyonight is my fav theme in all...and tokyonight does not support it. only a few have highlight ( catppuccin, onedark, night_owl, noctis, milora, dracula , solarized , penumbra+ nord  and rose_pine themes have support )
