### ISSUE TITLE
reopen: option for ignoring filetypes

### ISSUE THREAD

**Issue by notwidow** [helix-editor/helix#3894]
Hi, i previosly opened an issue for option to ignore filetypes we want. and since it was closed without a proper solution i am reopening again.
file-picker shows binary files when ``` space followed by f or F ```
an option for ignoring certain filetypes is needed ... there are many many files in an operating system which are not for editing so we cannot move them to gitignore files or others... 
![b0](https://user-images.githubusercontent.com/112823418/190918914-6bdda640-cf2e-49cd-b76a-f47177be4498.png)
![b1](https://user-images.githubusercontent.com/112823418/190918924-949d1b4a-d1a4-4d0d-a9c2-93f788375b83.png)

**Comment by the-mikedavis** [comment]
https://github.com/helix-editor/helix/issues/3889 was converted to a discussion: https://github.com/helix-editor/helix/discussions/3891

As that discussion covers, the proper way to ignore file-types is with a `.ignore` file. If you're looking specifically to hide binary files, https://github.com/helix-editor/helix/issues/1306 would cover that
