### ISSUE TITLE
Elixir: Auto-expand do-blocks

### ISSUE THREAD

**Issue by leonqadirie** [helix-editor/helix#3899]
In Elixir I'd love to have Helix expand `def foo(bar) do` + `[Enter]` to

```elixir
def foo(bar) do
  [Cursor]
end
```
Currently it only inserts a newline. Any pointers on how to contribute this?

**Comment by archseer** [comment]
I think lsp snippets would support this expansion.

**Comment by leonqadirie** [comment]
Ok, thanks a lot, will investigate!

**Comment by dead10ck** [comment]
Closing in favor of #394
