### ISSUE TITLE
Tcl grammar

### ISSUE THREAD

**Issue by spindlebink** [helix-editor/helix#3909]
There's a [Tcl tree-sitter](https://sr.ht/~cdrozak/tree-sitter-tcl/) on Sourcehut that's under fairly active development, although I don't know whether it's feature-complete.

**Comment by spindlebink** [comment]
I'm giving this a shot to see how complete the implementation is, but building the grammars is reporting `Failed to execute C/C++ compiler` on `hx --grammar build`, despite my having gcc/++ and clang/++ both in my `$PATH` and `CC` set. If there's an obvious first thing to try I'd prefer not to start a new report. Any ideas?

**Comment by the-mikedavis** [comment]
That grammar repository may not be possible to add without some extra work. It looks like it uses mercurial for VCS instead of git and currently we can only fetch grammars with git or local sources. You may need to create a git mirror

**Comment by spindlebink** [comment]
Yep, somebody already made one [here](https://github.com/nawordar/tree-sitter-tcl) for that very reason.

**Comment by pascalkuthe** [comment]
Closed by  #9837
