### ISSUE TITLE
Freeze on `:wq` a `.key` file, `<C-s>` works fine though

### ISSUE THREAD

**Issue by AndyJado** [helix-editor/helix#3911]
## desc
I tested on different files but it seems only works on [this one](https://fairygold.coding.net/p/banner/d/dyna-repo/git/tree/master/src/model.key)

---
## Reproduce

0. hx model.key
1. kkjkjkjkjjjj
2. :wq

freeze.
---

**Comment by pascalkuthe** [comment]
Closing this issue as stale, as the problem can not be reproduced without the test file (can not be accessed with the provided link) and no further details were peovided. If you are still having this problem upload the file to githubs pastepin service and reopen this issue
