### ISSUE TITLE
Syntax highlighting wrong for one character constants in Rust

### ISSUE THREAD

**Issue by A-Walrus** [helix-editor/helix#3922]
### Summary

Constants with one character names are incorrectly highlighted in Rust 
They both have the same tree-sitter scopes: 
Definition: `scopes: ["source_file", "const_item", "identifier"] `
Usage:  `scopes: ["source_file", "function_item", "block", "let_declaration", "identifier"]`

![image](https://user-images.githubusercontent.com/58790821/191497887-9a0e428a-ec94-4b81-b8c1-a2a1ded6818a.png)

```rust
const NUM: usize = 5;
const N: usize = 4;

fn f() {
    let a = N;
    let b = NUM;
}

```

### Reproduction Steps

 

I tried this:

1. `hx file.rs` file with code from above

I expected this to happen:
one letter constant "N" is highlighted the same as other constants

Instead, this happened:
It is highlighted the same as a "type_identifier"

### Helix log

Nothing

### Platform

Linux

### Terminal Emulator

Gnome console

### Helix Version

22.08.1

**Comment by the-mikedavis** [comment]
https://github.com/helix-editor/helix/blob/5467c65f8224049405498d65f54c3e3f8e4ec6c3/runtime/queries/rust/highlights.scm#L185-L186

That `+` should probably be a `*`, eh?

**Comment by A-Walrus** [comment]
> That `+` should probably be a `*`, eh?

I think so.

There is also the question of what to do when people don't conform to the naming standard.
Should:
`fn CAPITALIZED()` be highlighted as a function or constant (currently it looks like a constant)
same with `const lowercase: usize = 0` should it be highlighted as a constant or a variable (currently looks like variable)

both of these cases can be detected with a treesitter query:
```scheme
(const_item
  name: (identifier) @constant
)
```
for constants, and a similar one for functions

**Comment by gavincrawford** [comment]
I'm pretty sure the fix recommended by @the-mikedavis works for this case.

**Comment by the-mikedavis** [comment]
It's possible to only highlight constants with

```scm
(const_item name: (identifier) @constant)
```

as you say but then you need to use locals tracking to highlight further uses of those const variables correctly. That has problems of its own (#1151) but also it becomes difficult to highlight constants across files:

```rs
use helix_core::surround::PAIRS;

log::info!("{:?}", PAIRS);
```

would be ambiguous. It's something that could probably be done correctly with enough smartness - maybe stackgraphs. I think that highlighting constants only by naming conventions works well enough though.
