### ISSUE TITLE
Add keys to skim through occurrences in search mode

### ISSUE THREAD

**Issue by taupiqueur** [helix-editor/helix#3928]
Reference: https://vimhelp.org/options.txt.html#%27incsearch%27

**Comment by n0s4** [comment]
Is this just <kbd>n</kbd>/<kbd>N</kbd>, or do you mean cycling through them while searching?

**Comment by Omnikar** [comment]
> Is this just n/N, or do you mean cycling through them while searching?

See https://matrix.to/#/!zMuVRxoqjyxyjSEBXc:matrix.org/$8jRjSwtkbLRDoMHXSR0FfQVLP-ZZtmnPUOpzightecs?via=matrix.org&via=mozilla.org&via=tchncs.de

**Comment by pascalkuthe** [comment]
Closing in favor of https://github.com/helix-editor/helix/issues/4798
