### ISSUE TITLE
Tutor: what does `A-;` command mean?

### ISSUE THREAD

**Issue by zjp-CN** [helix-editor/helix#3937]
https://github.com/helix-editor/helix/blob/6e168b5099c31d0681e3486d177a14d04dde4c20/runtime/tutor#L370

Is anything in helix equivalent to `o` in vim's visual mode, which means `Go to Other end of highlighted (selected) text`?

**Comment by A-Walrus** [comment]
`A-;` (A is alt) is Helix's equivalent to vim's `o`.
Selections in helix have an anchor and a head (cursor). `A-;` Switches between them, flipping the direction of the selection ie moving the cursor to the other end.
<https://asciinema.org/a/RqvyauWkeq2uk8hvMhFNat4ah>

**Comment by zjp-CN** [comment]
Thank you! That's what I'm looking for :)
