### ISSUE TITLE
Add git branch name to statusline

### ISSUE THREAD

**Issue by David-Else** [helix-editor/helix#3949]
When https://github.com/helix-editor/helix/pull/3890 lands I assume it will be easy to get the name of the current branch? Can we then get it in the status-line like this Neovim example:

![Screenshot from 2022-09-23 13-51-40](https://user-images.githubusercontent.com/12832280/191964251-4853160e-7a76-41fd-9ca3-e081c0913084.png)

I think it would look good in a little box, like in the screenshot.

**Comment by pascalkuthe** [comment]
The implementation should be pretty straight forward.
I will send a PR once #3890 lands.

**Comment by David-Else** [comment]
Done with https://github.com/helix-editor/helix/pull/5682 :)
