### ISSUE TITLE
Lsp restart command spawn multiple procces for every call

### ISSUE THREAD

**Issue by axdank** [helix-editor/helix#3968]
### Summary

The new lsp restart command does not shut down the current server, so one process is left hanging, and a new one is executed.
Opening the editor for the first time: 3 processes
![imagen](https://user-images.githubusercontent.com/55039048/192166360-c72dc07a-e172-4bc6-b78d-e4e7c6fb657c.png)

Running lsp-restart for the first time: 6 processes
![imagen](https://user-images.githubusercontent.com/55039048/192166390-3f16ba94-b494-44c5-8b87-0bd831ee28c9.png)

Running lsp-restart for the second time: 9 processes
![imagen](https://user-images.githubusercontent.com/55039048/192166449-6d4b98e8-3723-4de8-814c-279f8dc206a2.png)

### Reproduction Steps

1. Open helix
2. Open the rust project and run the lsp-restart command once.
3. run lsp-restart a second time

### Helix log

not relevant

### Platform

Windows

### Terminal Emulator

wezterm 20220908-191626-25cd05a8

### Helix Version

helix 22.08.1 (e8f0886)

**Comment by dead10ck** [comment]
Interesting, this must be a Windows specific bug. This did not happen during testing on Linux.

**Comment by kirawi** [comment]
It's not clear to me where the old process is dropped in #3435.

**Comment by dead10ck** [comment]
> It's not clear to me where the old process is dropped in #3435.

This was discussed in the PR: https://github.com/helix-editor/helix/pull/3435#discussion_r949293934

It gets killed when the client gets dropped.

**Comment by dead10ck** [comment]
cc @mangas

**Comment by kirawi** [comment]
[According to the `tokio` documentation:](https://docs.rs/tokio/latest/tokio/process/struct.Command.html#caveats)

> On Unix platforms processes must be “reaped” by their parent process after they have exited in order to release all OS resources. A child process which has exited, but has not yet been reaped by its parent is considered a “zombie” process. Such processes continue to count against limits imposed by the system, and having too many zombie processes present can prevent additional processes from being spawned.
> 
> Although issuing a kill signal to the child process is a synchronous operation, the resulting zombie process cannot be .awaited inside of the destructor to avoid blocking other tasks. The tokio runtime will, on a best-effort basis, attempt to reap and clean up such processes in the background, but makes no additional guarantees are made with regards how quickly or how often this procedure will take place.
> 
> If stronger guarantees are required, it is recommended to avoid dropping a [Child](https://docs.rs/tokio/latest/tokio/process/struct.Child.html) handle where possible, and instead utilize child.wait().await or child.kill().await where possible.

**Comment by dead10ck** [comment]
Nice find. We should probably add a `kill` method to our LSP client then and incorporate it into the normal shutdown process. This is relevant for #3482. According to [the LSP spec](https://microsoft.github.io/language-server-protocol/specifications/lsp/3.17/specification/#shutdown), the normal process is to send a `shutdown` request, and then a `exit` request, which it looks like we do:

https://github.com/helix-editor/helix/blob/98dd9c4f2bf71e9afb72f61af9d45100fda0526e/helix-lsp/src/client.rs#L394-L400

So it looks like normally, the process should exit on its own after these two requests. However, it's conspicuously absent from the spec what should happen if the `shutdown` request fails. Probably what we can do is check the child process after the exit request and kill if it it's still alive for whatever reason.
