### ISSUE TITLE
Broken syntax highlighting in WGSL

### ISSUE THREAD

**Issue by Chickenkeeper** [helix-editor/helix#3982]
### Summary

WGSL code currently generates enormous amounts of erroneous error highlights.

![whole lotta red](https://user-images.githubusercontent.com/6290295/192326091-2f5434d0-058d-42ad-bf3f-1f5627af394c.png)

I suspect this may be because of the recent changes to the WGSL syntax. The version of tree-sitter-wgsl that the latest release of Helix uses had been updated to reflect the changes, but Helix's WGSL grammar hasn't been updated since months before the changes were introduced. Also WGSL code written with the old syntax is still highlighted as it was when wgsl support was first added (#1166).

I think it's worth noting that WGSL syntax highlighting has always been incomplete, but it was at least usable.

### Platform

Windows

### Terminal Emulator

PowerShell

### Helix Version

helix 22.08.1 (66276ce6)

**Comment by dead10ck** [comment]
This should actually be pretty easy to fix, if you'd like to give it a try. You can copy the latest commit hash and paste it here:

https://github.com/helix-editor/helix/blob/98dd9c4f2bf71e9afb72f61af9d45100fda0526e/languages.toml#L851

Then `hx --grammar fetch` and `hx --grammar build`.

**Comment by Chickenkeeper** [comment]
> This should actually be pretty easy to fix, if you'd like to give it a try. You can copy the latest commit hash and paste it here:
> 
> https://github.com/helix-editor/helix/blob/98dd9c4f2bf71e9afb72f61af9d45100fda0526e/languages.toml#L851
> 
> Then `hx --grammar fetch` and `hx --grammar build`.

Thanks. I've been learning more about language support in Helix and I've got a fix now. I'll post a PR soon.

**Comment by Chickenkeeper** [comment]
This issue's been solved by #3996, so it can be closed now.
