### ISSUE TITLE
`:config-open <file>` to open files like "languages.toml"

### ISSUE THREAD

**Issue by zim0369** [helix-editor/helix#4014]
There's no command to open the "languages.toml" file.

Extending `:config-open` to open the "languages.toml" or any config files that might be linked to helix in the future.

This way `:config-open` alone would open "config.toml" and `:config-open languages.toml` would open the "languages.toml" file and so on....

**Comment by the-mikedavis** [comment]
Duplicate of https://github.com/helix-editor/helix/issues/3495
