### ISSUE TITLE
Add cursorcolumn

### ISSUE THREAD

**Issue by zim0369** [helix-editor/helix#4015]
Similar to vim's cursor column.

**EDIT:** Cursor column is similar to cursor line. The only difference is that the cursor column is vertical.
This blog describes them both https://medium.com/@venumadhav888/highlighting-cursor-line-and-column-in-vi-editor-d5584b8d2eca

**Comment by JakeHL** [comment]
It will probably be useful to describe the feature in your issue for people who may not have used vim .

**Comment by A-Walrus** [comment]
Related #3218

**Comment by poliorcetics** [comment]
One default of `cursorcolumn` in Vim/Neovim is that it's very heavy on repaints on slower/charged systems. That may be a code-problem with how it's implemented, but I suspect it's not

**Comment by zim0369** [comment]
> One default of `cursorcolumn` in Vim/Neovim is that it's very heavy on repaints on slower/charged systems. That may be a code-problem with how it's implemented, but I suspect it's not

As much as I've used vim/neovim, I've never needed the cursor column constantly. I think only being able to quickly toggle it with a key press(held down) would be better. Let's say `s` is used for that then only holding down `s` should bring up the cursor column, while releasing it should make it disappear. This would be a nice default since it has redrawing issues and it is only needed when the user needs to check if any number of characters on different lines are in the same column.

**Comment by gasacchi** [comment]
i think cursor column is quite use full, with combination with cursor line we can easily locate the cursor. that just how i used when using neovim.
this is also solved by using bright cursor bg like red.
but again it nice to have it in helix 😄
