### ISSUE TITLE
macOS: Terminal profiles and especially Homebrew, editor is just about unusable

### ISSUE THREAD

**Issue by AddictArts** [helix-editor/helix#4017]
### Summary

Using Terminal on macOS the Helix theme makes the editor unusable with the Homebrew profile.

### Reproduction Steps

Open a Terminal new window using Homebrew, in fact many of the Terminal profiles have low contrast making the default almost unusable.

A high contrast theme like Grass is reasonable. 

**Open Helix in an existing shell of Terminal that was already open, not a new one**

### Platform

macOS

### Terminal Emulator

Terminal

### Helix Version

helix 22.08.1 (66276ce6)

**Comment by AddictArts** [comment]
Ideally when this happens there would be an easy switch to high contrast, versus wading through themes, learning how to config Helix to get something usable. I don't have config down and wanted to give it a go.

**Comment by the-mikedavis** [comment]
The default Terminal.app doesn't support true-color which can throw off how the rendering looks: https://github.com/helix-editor/helix/wiki/Troubleshooting#rendering-issues-on-macos-terminal, https://github.com/helix-editor/helix/wiki/Terminal-Support#terminalapp

**Comment by AddictArts** [comment]
@the-mikedavis thanks, didn't know that, bummer.
