### ISSUE TITLE
Crash on space during startup

### ISSUE THREAD

**Issue by Zoybean** [helix-editor/helix#4046]
### Summary

Invoking helix and then very quickly pressing space occasionally causes it to crash. I discovered this from attempting to use `space` `p` on startup. When attempting to gather data for this issue, most of the time I ran it it would succeed, but it appears to crash consistently if `space` is pressed ASAP after `enter` when invoking `hx` from the terminal.

Error message:
```
thread 'main' panicked at 'Unexpected INPUT_RECORD EventType: 0', C:\Users\runneradmin\.cargo\registry\src\github.com-1ecc6299db9ec823\crossterm_winapi-0.9.0\src\structs\input.rs:324:21
```

With `RUST_BACKTRACE=full`:
```
stack backtrace:
   0:     0x7ff7d3182ad4 - <unknown>
   1:     0x7ff7d28be4ea - <unknown>
   2:     0x7ff7d317ab19 - <unknown>
   3:     0x7ff7d31864bb - <unknown>
   4:     0x7ff7d3186155 - <unknown>
   5:     0x7ff7d3186bd2 - <unknown>
   6:     0x7ff7d3186973 - <unknown>
   7:     0x7ff7d3184047 - <unknown>
   8:     0x7ff7d318662f - <unknown>
   9:     0x7ff7d321e0d5 - <unknown>
  10:     0x7ff7d28d5f60 - <unknown>
  11:     0x7ff7d28cf04c - <unknown>
  12:     0x7ff7d28cada8 - <unknown>
  13:     0x7ff7d28c7409 - <unknown>
  14:     0x7ff7d28d50fa - <unknown>
  15:     0x7ff7d3030905 - <unknown>
  16:     0x7ff7d2fff978 - <unknown>
  17:     0x7ff7d301cfe0 - <unknown>
  18:     0x7ff7d2ff0054 - <unknown>
  19:     0x7ff7d2fda75b - <unknown>
  20:     0x7ff7d302e75b - <unknown>
  21:     0x7ff7d2ff2a34 - <unknown>
  22:     0x7ff7d2fe4a26 - <unknown>
  23:     0x7ff7d3011fdc - <unknown>
  24:     0x7ff7d3173c98 - <unknown>
  25:     0x7ff7d2ff2bd7 - <unknown>
  26:     0x7ff7d321825c - <unknown>
  27:     0x7ffcc60f84d4 - BaseThreadInitThunk
  28:     0x7ffcc68c1791 - RtlUserThreadStart
```

### Reproduction Steps

 

I tried this:

1. `hx`
2. press space after invoking `hx` but before helix starts

I expected this to happen:

Helix loads and has the space-menu open

Instead, this happened:

Helix crashes, sometimes briefly displaying the UI first

### Helix log

No pertinent log entries even with `-vvv`

### Platform

Windows 10

### Terminal Emulator

ConEmu 160914 [64]

### Helix Version

helix 22.08.1 (66276ce6)

**Comment by the-mikedavis** [comment]
This might be Windows-only, I can't reproduce on Linux. Based on the error message it looks like it might be a bug upstream in crossterm too.

**Comment by CptPotato** [comment]
FWIW I don't seem to be able to reproduce this using on Windows 10 (built from current master).

Though, I've only tried on a rather beefy machine where helix' startup is practically instantaneous.

**Comment by the-mikedavis** [comment]
This may be a problem only with ConEmu, similar to (or maybe the same as) https://github.com/helix-editor/helix/issues/2490

**Comment by Zoybean** [comment]
Using the latest version of ConEmu, I can't seem to reproduce this issue. Given this was seemingly caused by the same root issue as #2490, I think it's fair to close this off as well.
