### ISSUE TITLE
Key not shown in corner for find commands

### ISSUE THREAD

**Issue by Omnikar** [helix-editor/helix#4050]
The `f`, `t`, `F`, and `T` commands do not display the key in the lower right corner when they are pending input.

**Comment by the-mikedavis** [comment]
This is similar to https://github.com/helix-editor/helix/issues/3223: those commands just need pseudo_pending text.

**Comment by mbStavola** [comment]
I'd like to take this!

Also, just curious, is helix also participating in Hacktoberfest? It seems the project has participated before, but I don't see any labels this year.
