### ISSUE TITLE
Repeat action with `.` repeats too much when insert mode entered from select mode

### ISSUE THREAD

**Issue by spagy** [helix-editor/helix#4055]
### Summary

When I use `.` to repeat an action, everything is repeated since I last _explicitly_ entered insert mode. This gives the wrong behaviour when entering insert mode from select mode (e.g., `vc`).

### Reproduction Steps

I tried this:

1. Enter insert mode with `i`
2. Type something `aoeu`
3. Enter normal mode with `<ESC>`
4. Go back to the start of the line `gh`
5. Select the first character `v`
6. Change the character to something else (going from selection mode to insert mode) `c1`
7. Go back to normal mode with `<ESC>`
8. Repeat the action with `.`

I expected this to happen:
only the most recent action (e.g., changing the selected character to something else) sholud be repeated

Instead, this happened:
all the text from the insertion on lines 1-3 are also repeated

Or put differently, opening a blank buffer in helix and typing `iaoeu<ESC>ghvc1<ESC>.` should result in a buffer that has the text `11eu` but instead it has the text `1aoeu1oeu`.

### Platform

linux

### Terminal Emulator

kitty

### Helix Version

helix 22.08.1 (66276ce6)

**Comment by the-mikedavis** [comment]
We only set the `last_insert` field on the change from Normal to Insert mode: https://github.com/helix-editor/helix/blob/60aa7d360777331753ae4735f8fd4ea96012d4fd/helix-term/src/ui/editor.rs#L841-L851

In this case we enter Insert mode directly from Select mode so the insert isn't saved.

**Comment by soloturn** [comment]
how would you save it @the-mikedavis ?

**Comment by the-mikedavis** [comment]
Actually this was fixed a while back. Now we just check that the old mode isn't insert mode: https://github.com/helix-editor/helix/blob/61818996c63cb752afb817259a90108f884db1cb/helix-term/src/ui/editor.rs#L883-L888
