### ISSUE TITLE
[question] How to map `#` to enter comman line mode?

### ISSUE THREAD

**Issue by MaxVerevkin** [helix-editor/helix#406]
By default, to enter command line mode I have to press `:` https://github.com/helix-editor/helix/blob/37f0b9ee159c13a8bc225b28219dfc485f4393a2/helix-term/src/keymap.rs#L52

but I'd like to use `#` instead. I've tried 

```toml
[keys.normal]
# = "command_line"
```

but it obviously doesn't work since `#` just comments the line.

**Comment by sudormrfbin** [comment]
You can quote it using `""`:

```toml
[keys.normal]
"#" = "command_mode"
```

Also the actual command names are just a bit below the comments:

https://github.com/helix-editor/helix/blob/37f0b9ee159c13a8bc225b28219dfc485f4393a2/helix-term/src/keymap.rs#L189-L193

**Comment by MaxVerevkin** [comment]
@sudormrfbin Thanks, it works
