### ISSUE TITLE
Unexpected behaviour with find_till_char when on last character of a non-empty line

### ISSUE THREAD

**Issue by peter9477** [helix-editor/helix#4065]
### Summary

Using `t` (find_till_char) with `Enter` when on the last character of a line behaves unexpectedly. If on a line where the following line is completely empty it appears to work, but if the following line is non-empty then it actually selects until the end of that line, not the one you're on. 

### Reproduction Steps

Using this example:
```
line1
line2

line4
x
line6
```

Place cursor on 1 and `t` `Enter` and you select up to 2. Place cursor on 2 and it selects just the 2 (as expected). Cursor on line 3 and it selects till 4 (also as expected). Cursor on 4 behaves (incorrectly?) like 1. Cursor on 5 (i.e. the x) selects till 6 (also not 

### Platform

Linux

### Terminal Emulator

putty

### Helix Version

22.08.1-125-g5b5f1bd3

**Comment by peter9477** [comment]
Note that while what I might consider "expected" may not be the actual intended behaviour, if you go through my test cases I'm pretty sure you'll agree there's some sort of inconsistency going on, so something unexpected in any case. Surely how it behaves on a given line should not be affected by the contents of the following line.

**Comment by Omnikar** [comment]
There doesn't seem to be any inconsistent behaviour here; if we think of the newlines as any other character and view the example as one line:
Place cursor on `1`.
```
line[1]⏎line2⏎⏎line4⏎x⏎line6⏎
```
`t⏎` extends the selection until the second `⏎`.
```
line(1⏎line2]⏎⏎line4⏎x⏎line6⏎
```
Place the cursor on `2`.
```
line1⏎line[2]⏎⏎line4⏎x⏎line6⏎
```
`t⏎` extends the selection until the third `⏎`.
```
line1⏎line(2⏎]⏎line4⏎x⏎line6⏎
```
Place the cursor on the third line, on the third `⏎`.
```
line1⏎line2⏎[⏎]line4⏎x⏎line6⏎
```
`t⏎` extends the selection until the fourth `⏎`.
```
line1⏎line2⏎(⏎line4]⏎x⏎line6⏎
```
Place the cursor on `4`.
```
line1⏎line2⏎⏎line[4]⏎x⏎line6⏎
```
`t⏎` extends the selection until the fifth `⏎`.
```
line1⏎line2⏎⏎line(4⏎x]⏎line6⏎
```
Place the cursor on `x`.
```
line1⏎line2⏎⏎line4⏎[x]⏎line6⏎
```
`t⏎` extends the selection until the last `⏎`.
```
line1⏎line2⏎⏎line4⏎(x⏎line6]⏎
```

**Comment by the-mikedavis** [comment]
The part of this I thought was buggy: `t`'s behavior is a little different than how it works with Kakoune, specifically:

```
line#[1|]#
line2

```

in Helix gives

```
line#[1
line2|]#

```

where in Kakoune it gives

```
line#[1|]#
line2

```

Helix moves to the next next instance if the next instance follows immediately and Kakoune does not (see [this block](https://github.com/helix-editor/helix/blob/6caa7a7f566e67c50537014b3e97fa8e65a8b7b3/helix-term/src/commands.rs#L1176-L1179)).

It looks like this is an intentional difference though: https://github.com/helix-editor/helix/pull/891#discussion_r735089786.

So @Omnikar's explanation is spot-on 👍

**Comment by peter9477** [comment]
Thanks guys.  The fundamental problem here was me continuing to think of the "find till" selection as directly involving the character (in this case newline) rather than selecting *up to* the character, and not paying close attention to the subtle difference between when it selects the current line's newline because it's selecting *up to* the newline on the following blank line.  Turning on `render.newline = "all"` made this much clearer and I accept that what it does is in fact consistent.
