### ISSUE TITLE
hx creates zombie process on exit

### ISSUE THREAD

**Issue by eye-wave** [helix-editor/helix#4068]
### Summary

When closing typescript project, new instance of tsserver.js is not killed properly and still running in the background.
(each one of those takes up to 1GB of ram)

### Steps to reproduce
https://user-images.githubusercontent.com/89079979/193459766-58b45321-dc71-467c-9442-e29b2e9bc2c5.mp4

### Helix log
```
2022-10-02T16:22:38.522 helix_view::editor [ERROR] Failed to initialize the LSP for `source.json` { cannot find binary path }
```

### Platform
Pop!_OS 22.04 LTS x86_64

### Terminal Emulator
kitty 0.21.2

### Helix Version
22.08.1-120-g8a7a6e4c

### Other Software versions
node v18.0.0
npm 8.19.2
typescript-language-server 2.0.0

**Comment by pascalkuthe** [comment]
Can not reproduce this on master (atlwast from the limited reproduction case here). This issue was for a very old helix version so may be fixed jn the meantime. If.not open anew issue with detailed reproduction case
