### ISSUE TITLE
Error message not clear?

### ISSUE THREAD

**Issue by matthiasdebernardini** [helix-editor/helix#4108]
<img width="1728" alt="image" src="https://user-images.githubusercontent.com/32387851/194076591-e60573f0-4382-4596-ba2a-1d9b9b9f61fa.png">

I am trying to remap the keys so that my colemak layout plays nice in the homerow. My homerow is "neio".

The error message is 
"Bad config: data did not match any variant of untagged enum KeyTrie for key `keys.normal` at line 8 column 1"

I don't understand what the issue is, can anyone help?

Many thanks

**Comment by matthiasdebernardini** [comment]
```[editor]
line-number = "relative"
cursor-shape = { insert = "bar" }
whitespace.render = "all"
whitespace.characters = { space = " ", tab = "▏", newline = "¬" }

# Keymap for the Colemak layout and Kakoune habits (who needs a select mode)
[keys.normal]
e = "move_line_down"
i = "move_line_up"
o = "move_char_right"
j = "insert"
l = "move_next_word_end"
k = "search_next"
h = "open_below"
```

**Comment by the-mikedavis** [comment]
`"insert"` should be `"insert_mode"`.

The error messages have been improved on master: https://github.com/helix-editor/helix/pull/3931
