### ISSUE TITLE
CodeLens placement issues

### ISSUE THREAD

**Issue by cidit** [helix-editor/helix#4119]
the code lens feedback is too far to the right to be useful, and i have no clue how to bring it closer to the left

![Screenshot from 2022-10-05 23-25-11](https://user-images.githubusercontent.com/44065673/194207333-c8731505-59b8-4e2c-903b-444751d901d1.png)

**Comment by sudormrfbin** [comment]
Related: #1462, #2553.

**Comment by pascalkuthe** [comment]
I think this is a duplicate of  either #1953 or #1462 as just moving the diagnostic to the left woudln't work as it would interfere with the document text so either a popup or some kind of intrusive diagnostic would be required, 
I don't think it makes sense to track this separately and it's better to keep discussion focused into a single issue so I am closing this in favor of those other two issues. If you don't think this is right and would rather see this tracked separately feel free to reopen.
