### ISSUE TITLE
golang autocompletion does not replace the partial word

### ISSUE THREAD

**Issue by sbromberger** [helix-editor/helix#4131]
### Summary

Possibly related:
- #2580
- #2027

When completing a word with gopls, after selecting the completion term, the already-typed text does not get replaced. Therefore, completing `str` with `string` results in `strstring`.

go 1.19.2
gopls 0.9.5

### Reproduction Steps

https://asciinema.org/a/nsZSjqqLLgm17ZYqstbpEtVJA

### Helix log

<details><summary>~/.cache/helix/helix.log</summary>

```
2022-10-06T17:10:34.453 helix_lsp::transport [ERROR] <- ServerError(0): 4:21: expected type, found newline
2022-10-06T17:10:34.454 helix_view::document [WARN] LSP formatting failed: protocol error: ServerError(0): 4:21: expected type, found newline                                                         
2022-10-06T17:10:34.717 helix_lsp::transport [ERROR] err: <- StreamClosed
```

</details>

### Platform

linux

### Terminal Emulator

tmux

### Helix Version

helix 22.08.1 (7e74e935)

**Comment by xbol0** [comment]
Right, when complete `func TestFoo` will become `func TestFoo(t *testing.T)TestFoo`.

**Comment by sbromberger** [comment]
@the-mikedavis - #1819 doesn't fix this problem, at least in my testing. (I added a comment there.)

**Comment by archseer** [comment]
Seems to be an upstream issue https://github.com/helix-editor/helix/pull/5487#issuecomment-1378240975

**Comment by archseer** [comment]
Should be fixed upstream now https://github.com/golang/go/issues/57480
