### ISSUE TITLE
strings highlighting is not right in nushell scripts

### ISSUE THREAD

**Issue by amtoine** [helix-editor/helix#4162]
### Summary

hello there :wave: :yum: 

i just have a syntax hightlighting issue with some `nushell` code :thinking: 

below is a screenshot of what is happening :+1: 

:green_circle: the syntax hightlighting is right
:large_blue_circle: it starts to shift around the `"\nLOG:"` string of characters
:red_circle: it is not right anymore and everything looks like a string, except strings themselves
:orange_circle: the file is correctly identified as a `nushell` script

![helix-nu-hightlight](https://user-images.githubusercontent.com/44101798/194762134-cf90fefb-4313-4636-8414-6b4d90a63154.png)

### Reproduction Steps

 
1. go to [`functions.nu`](https://github.com/goatfiles/dotfiles/blob/main/.config/nushell/scripts/functions.nu#76) around the line with `export def-env vcfg`

I expect the _string_ highlight to stop at the end of `"\nLOG:"`

Instead, it continues to the bottom of the file, i.e. the strings and the rest are inverted :open_mouth: 

### Helix log

nothing relevant to report from `~/.cache/helix/helix.log`

### Platform

Linux 5.19.10-arch1-1

### Terminal Emulator

alacritty 0.10.1 ()

### Helix Version

(22.08.1-165-g4d4be0e8)

**Comment by gavincrawford** [comment]
This appears to be an issue with the grammar itself, provided by [this](https://github.com/LhKipp/tree-sitter-nu) repo. In this file specifically, it may have something to do with `def-env`, which isn't included as a keyword in the query for Nu. See here:
https://github.com/helix-editor/helix/blob/9b7f349f5c9b2699faead8c7f6feabbd7fd1cba9/runtime/queries/nu/highlights.scm#L29-L35

**Comment by amtoine** [comment]
> This appears to be an issue with the grammar itself, provided by [this](https://github.com/LhKipp/tree-sitter-nu) repo. In this file specifically, it may have something to do with `def-env`, which isn't included as a keyword in the query for Nu.
>
ooh yes i see it :open_mouth: 

i tried to modify my `~/.config/helix/runtime/queries/nu/highlights.scm` by writing
```scm
[
 "if"
 "else"
 "let"
 "def"
 "export"
 "def-env"
] @keyword
```
but then the hightlighting is completely gone :thinking: 

i'm new to `tree-sitter` and grammar integration to an IDE :confused: 
**should [tree-sitter-nu/highlights.scm](https://github.com/LhKipp/tree-sitter-nu/blob/main/queries/highlights.scm) be directly modified?**
**and then we should run `hx --grammar fetch; hx --grammar build`?**

**Comment by the-mikedavis** [comment]
This can't be solved just by modifying the highlights - the syntax tree has an ERROR node indicating that the parser failed to parse some of the code successfully. This will need to be fixed upstream in https://github.com/LhKipp/tree-sitter-nu

**Comment by amtoine** [comment]
> This can't be solved just by modifying the highlights - the syntax tree has an ERROR node indicating that the parser failed to parse some of the code successfully. This will need to be fixed upstream in https://github.com/LhKipp/tree-sitter-nu
>
okok i see :thinking: 
i guess i'll see that with the upstream then :relieved:

**Comment by amtoine** [comment]
there it is :muscle:

**Comment by amtoine** [comment]
according the @LhKipp, https://github.com/LhKipp/tree-sitter-nu/issues/3 has been fixed :+1:
