### ISSUE TITLE
Highlighting issue with macro in rust

### ISSUE THREAD

**Issue by irevoire** [helix-editor/helix#4205]
Hello, I've had this bug on Linux & macOS and for almost one year now on every version of helix thus. I thought maybe no one ever noticed it :thinking: 
And I wasn't able to find any issues mentioning it.

Basically, when writing code in a proc_macro attributes, the syntax highlighting just stop working.

Here is a simple and not-that-severe example;
```rust
#[derive(Debug, thiserror::Error)]
pub enum MeilisearchHttpError {
    #[error("A Content-Type header is missing. Accepted values for the Content-Type header are: {}",
            .0.iter().map(|s| format!("`{}`", s)).collect::<Vec<_>>().join(", "))]
    MissingContentType(Vec<String>),
    #[error(
        "The Content-Type `{0}` is invalid. Accepted values for the Content-Type header are: {}",
        .1.iter().map(|s| format!("`{}`", s)).collect::<Vec<_>>().join(", ")
    )]
    InvalidContentType(String, Vec<String>),
    #[error("Document `{0}` not found.")]
    DocumentNotFound(String),
}
```

And here is how it is highlighted;
![image](https://user-images.githubusercontent.com/7032172/195124167-81420268-86a5-43bc-8ea1-8ca86a958352.png)
Notice the `.0.iter() ...` things in white. And the next `error` attribute becomes white as well.

The other thing I found that's more severe is this one;
```rust
#[derive(Debug, thiserror::Error)]
pub enum Other {
    #[error("Invalid syntax for the filter parameter: `expected {}, found: {1}`.", .0.join(", "))]
    InvalidExpression(&'static [&'static str], Value),
}
```

It shows everything below as a string;
![image](https://user-images.githubusercontent.com/7032172/195124753-91c49119-13ed-4c6c-a4df-9a9959f777cf.png)

**Comment by the-mikedavis** [comment]
What version are you on? I see these examples being parsed correctly on master. The last update to tree-sitter-rust in https://github.com/helix-editor/helix/commit/03f0ef93ac6da58963b32034fd4681e428867d2a included changes in that parser which refactored how attributes are parsed.

**Comment by ybnesm** [comment]
@irevoire do you still have this problem? If not, close the issue.

**Comment by irevoire** [comment]
Ooops sorry, I completely missed your message @the-mikedavis, I'm going to download the latest version and retry let me a few minutes!

**Comment by irevoire** [comment]
It's fixed on the latest version; nice!
Thanks, everyone and sorry again for the delay :see_no_evil:
