### ISSUE TITLE
Set up debugger for Javascript/Typescript

### ISSUE THREAD

**Issue by MAST1999** [helix-editor/helix#4214]
I was trying to set up the debugger for Javascript/Typescript and found this pull #574 and the example using the vscode debugger. Still, when I wanted to do it I found that the files in the debugger of vscode had changed drastically and I couldn't figure out how to set it up correctly.

Can you give me some help setting it up and maybe add it to the debugger wiki?

**Comment by MAST1999** [comment]
I looked around for the `nodeDebug.js` file used in the pull request but didn't find it.

Is it in a different extension than [here](https://github.com/microsoft/vscode-js-debug)?

I also checked using all the files inside the new vscode-js-debug extension to see if any of them worked, but none worked.

```
adapter  ui                                     bootloader.bundle.js              diagnosticTool.bundle.js  hash.bundle.js       watchdog.bundle.js
dap      25b0f220a897d7433728f6f34169bdbf.node  bootloader.bundle.js.LICENSE.txt  extension.js              mappings.wasm        watchdog.bundle.js.LICENSE.txt
targets  binder.nls.metadata.json               chromehash_bg.wasm                extension.js.LICENSE.txt  terminateProcess.sh
```

There was no JavaScript file inside the other folders (there were only JSON files in them).

**Comment by MAST1999** [comment]
OK then, I guess I'll keep an eye out for that issue.

Thanks!

**Comment by jasonwilliams** [comment]
Hey @MAST1999 looks like there's now some support for this?
https://github.com/microsoft/vscode-js-debug/issues/926#issuecomment-1741635736

**Comment by jasonwilliams** [comment]
I don't know what it would take to make this work but it could be worth re-opening this issue now it looks possible

**Comment by Enqueued** [comment]
Would love to see some update on this. I really like using Helix and getting a TS debugger working would be another step toward removing vscode for me.

**Comment by jasonwilliams** [comment]
Theres now a PR for this [here](https://github.com/helix-editor/helix/pull/13403)

**Comment by jasonwilliams** [comment]
You can now test this on the latest release https://github.com/helix-editor/helix/blob/master/CHANGELOG.md#2507-2025-07-15
