### ISSUE TITLE
Shortcut to insert unicode characters

### ISSUE THREAD

**Issue by filipdutescu** [helix-editor/helix#4216]
# Description

Similar functionality to Vim's insert mode `C-v` shortcut which lets you insert unicode characters by writing its corresponding code (ie `u1234`).

# Motivation

I find myself frequently missing it and needing to search for the character online and find somewhere to copy it from.

# Alternatives

Have not really thought of any so far.

**Comment by the-mikedavis** [comment]
Duplicate of https://github.com/helix-editor/helix/issues/1438
