### ISSUE TITLE
Support `scroll_down` command at the end of a file

### ISSUE THREAD

**Issue by aleksanderkrauze** [helix-editor/helix#4219]
In contrast to vim's `<C-e>` in helix `scroll_down` will stop when the end of the file is reached. This makes moving the end of a file higher in the terminal not possible using this method. I know that it can be done using `align_view_top`, but this requires changing one motion to another.

I propose aligning helix's behavior to vim's. I will try providing a PR for that.

**Comment by pascalkuthe** [comment]
Tgis was accidentialmy fixed by #5420 but #6966 is about restoring that behavior so we have two conflicting issues now. We should either decide to keep the current behavior or decide to fix #6966. Slightly leaning towards keeping the current behavior for simplicity. You can always scroll back up.

**Comment by pascalkuthe** [comment]
Pl we decided to keep this so this was fixing by #5420
