### ISSUE TITLE
The reload operation takes up a lot of memory until the computer freezes

### ISSUE THREAD

**Issue by xpeng2333** [helix-editor/helix#4228]
### Summary

Opening a file with a size of 500M, executing the reload operation will take up much more memory than the file size and keep increasing until all the memory is used up

### Reproduction Steps

 

I tried this:

1. `hx 1.txt` 
2.  `reload`
I expected this to happen:
reload 1.txt
Instead, this happened:
hx used up all memory

### Helix log

<details><summary>~/.cache/helix/helix.log</summary>

```
please provide a copy of `~/.cache/helix/helix.log` here if possible, you may need to redact some of the lines
```

</details>

### Platform

macOS

### Terminal Emulator

zsh 5.8.1

### Helix Version

helix 22.08.1

**Comment by the-mikedavis** [comment]
It isn't an infinite amount of memory but it is quite a lot: for a text file with ~503MB, I see around 21GB of memory usage.

It looks like `helix_core::diff::compare_ropes` is the culprit for the increased CPU usage at least, and probably the increased memory usage too:

![flamegraph](https://user-images.githubusercontent.com/21230295/195395039-41d368a5-6482-44cf-8407-c2a392730e0b.png)

**Comment by kirawi** [comment]
I'm assuming that this is because of the timeout. After 1 second, all diff operations turn into insertions and deletions as a fast path.

**Comment by xpeng2333** [comment]
Thanks for your reply. It seems that I misunderstood the reload operation. I thought it was just reopening the file.

**Comment by kirawi** [comment]
The [rsync algorithm](https://github.com/dropbox/fast_rsync) is an option for more efficient reloading as well.
