### ISSUE TITLE
Loading indicator

### ISSUE THREAD

**Issue by lukepighetti** [helix-editor/helix#4235]
If you try to make an LSP request (such as `goto references`) that takes a long time, there's no visual indication that there is loading occurring. It would be nice if there was a (non-blocking, cancelable 🤞) indicator to show that something is currently loading.

**Comment by sudormrfbin** [comment]
The statusline spinner could be reused for this, and it's already used for showing LSP init progress and will fit right in. Maybe a statusline message too if it takes too long based on an idle timer.

**Comment by the-mikedavis** [comment]
Duplicate of https://github.com/helix-editor/helix/issues/1060
