### ISSUE TITLE
Cannot play a macro that involves > and < keystrokes

### ISSUE THREAD

**Issue by Zoybean** [helix-editor/helix#4239]
### Summary

Recording a macro which involves typing `>` or `<` causes them to be encoded unescaped in the macro's register, however `>` and `<` are special characters in macros, so attempting to play back the macro fails, e.g. with `Invalid key code` or `Unmatched '>'`

### Reproduction Steps

 

I tried this:

1. `hx`
2. `Q`
3. `i` `>` `<esc>`
4. `Q`
5. `q`

I expected this to happen:

a `>` is inserted into the buffer upon pressing `q`

Instead, this happened:

`Invalid macro: Unmatched '>'`

### Helix log

no relevant log entries

### Platform

Linux (Ubuntu on WSL on Windows)

### Terminal Emulator

Windows Terminal Version: 1.15.2712.0

### Helix Version

22.08.1-207-g5077ce76

**Comment by Omnikar** [comment]
This was fixed by #3556, before 22.08.1, so I'm not sure why you're still experiencing it. I just tested and it worked as expected.

**Comment by Zoybean** [comment]
That may be my mistake, I found it on an earlier version and then thought to update and try again, I possibly made a mistake in updating.

**Comment by Zoybean** [comment]
Yep, I pulled the newer changes but forgot to reinstall. Confirmed it no longer occurs in the new version
