### ISSUE TITLE
Unable to complete tutorial on mac

### ISSUE THREAD

**Issue by PurpleBooth** [helix-editor/helix#4240]
### Summary

The tutorial's intructions no longer work when you get down to section 5.5.

Note: ⌥+s prints a sharp s (ß, z.B. for straße or other german words) on a Mac keyboard.

### Reproduction Steps

 

I tried this:

1. `hx`
2. `:tutor`

I expected this to happen:

To be able to complete the tutorial

Instead, this happened:

Splitting selection into new lines does nothing.

### Helix log

<details><summary>~/.cache/helix/helix.log</summary>
cat $HOME/.cache/helix/helix.log
[bat error]: '/Users/billie/.cache/helix/helix.log': No such file or directory (os error 2)
</details>

### Platform

macOS (GB keyboard)

### Terminal Emulator

kitty 0.26.3 created by Kovid Goyal

### Helix Version

helix 22.08.1 (66276ce6)

**Comment by Omnikar** [comment]
You'll need to configure your terminal emulator to use the option key as a modifier.

**Comment by PurpleBooth** [comment]
I am a little confused, what this means, could you explain further?

I enabled the key mapping printing in `kitty +kitten show_key -m kitty`, and I can see the correct events

```
Press any keys - Ctrl+C or Ctrl+D will terminate
ENTER RELEASE 
CSI 13 ; 1 : 3 u

Alt+LEFT_ALT PRESS 
CSI 57443 ; 3 u

Alt+s PRESS 
CSI 115 ; 3 u

Alt+s RELEASE 
CSI 115 ; 3 : 3 u

LEFT_ALT RELEASE 
CSI 57443 ; 1 : 3 u

```

**Comment by Omnikar** [comment]
I don't know how it works in kitty but in iTerm2 I had to change this option from "Normal".
<img width="329" alt="image" src="https://user-images.githubusercontent.com/79615262/195517706-9a2fe9c5-05ca-460b-b0c5-2231ea6458a2.png">

**Comment by PurpleBooth** [comment]
Ah ok, kitty uses a different protocol to iterm, so this doesn't apply to kitty from my understanding

**Comment by Omnikar** [comment]
Oh, looks like you just need to set `macos_option_as_alt` in your kitty config to `left`, `right`, or `both`.

**Comment by PurpleBooth** [comment]
Ah done and that worked! Perfect!

**Comment by mikkelfj** [comment]
FWIW, new user: "MacOS Iterm2 + helix + alt + b" in insert mode inserts a symbol instead of moving back a word, Emacs style. Helix 0.22.
