### ISSUE TITLE
How can I open a bash terminal inside a window?

### ISSUE THREAD

**Issue by igorluppi** [helix-editor/helix#4248]
Something useful from nvim is the terminal inside a window, such as:

`:vsplit term:// bash <CR>i`

This cmd opens a terminal inside a vsplit window, that I can close after I finish what I need using `C-d`. How can I run use terminal in helix?
PS: I know that :sh exists, however I'd like a terminal to run cmds as much as I need to, not only a single run.

**Comment by igorluppi** [comment]
Also, `:sh bash` breaks helix

**Comment by A-Walrus** [comment]
Duplicate of #3524.
Currently Helix doesn't have any way of having an integrated, interactive terminal.

**Comment by the-mikedavis** [comment]
Also see #1976
