### ISSUE TITLE
Emacs style bindings in insert mode does not work in WSL2

### ISSUE THREAD

**Issue by o8vm** [helix-editor/helix#4249]
### Summary

Emacs style bindings in insert mode does not work in WSL2, for example, Ctrl-b causes "b" to be typed. Others are the same.

### Reproduction Steps

I tried this:

Ubutu WSL2(WindowsTerminal.exe):

1. cargo install --path helix-term
2. `hx test`
3. press `i` into insert mode & press Ctrl-b, b to be typed

### Helix log

<details><summary>~/.cache/helix/helix.log</summary>

```
2022-10-13T22:00:30.712 helix_view::editor [ERROR] Failed to initialize the LSP for `source.toml` { cannot find binary path }
2022-10-13T22:01:11.639 helix_view::editor [ERROR] Failed to initialize the LSP for `source.toml` { cannot find binary path }
2022-10-13T22:04:31.647 helix_view::editor [ERROR] Failed to initialize the LSP for `source.toml` { cannot find binary path }
```

</details>

### Platform

WSL2

### Terminal Emulator

WindowsTerminal 1.15.2713.0

### Helix Version

helix 22.08.1 (5077ce76)

**Comment by the-mikedavis** [comment]
Most readline-like bindings have been removed on master:

* https://docs.helix-editor.com/master/keymap.html#insert-mode
* https://github.com/helix-editor/helix/pull/3671
* https://github.com/helix-editor/helix/discussions/3865
* https://github.com/helix-editor/helix/pull/3915

You can add bindings to your config to restore the ones you use:

```toml
[keys.insert]
C-b = "move_char_left"
```

**Comment by o8vm** [comment]
Thank you!
