### ISSUE TITLE
Windows Installation Instructions

### ISSUE THREAD

**Issue by xgpt** [helix-editor/helix#4253]
### Summary

The https://docs.helix-editor.com/install.html page, is lacking clear installation instructions for Windows users. Additionally there is no standard Windows installation package.

### Reproduction Steps

 

I tried this:

1. `hx`

I expected this to happen:

Instead, this happened:

### Helix log

<details><summary>~/.cache/helix/helix.log</summary>

```
please provide a copy of `~/.cache/helix/helix.log` here if possible, you may need to redact some of the lines
```

</details>

### Platform

Windows

### Terminal Emulator

website

### Helix Version

website

**Comment by archseer** [comment]
Both Chocolatey and Scoop packages are listed. You can use either depending on your preferred package manager.

**Comment by CptPotato** [comment]
I guess it's worth mentioning in the docs since Linux and OSX are listed as well.

I could make a PR for this.

**Comment by the-mikedavis** [comment]
A small section like the one for OSX that points to the chocolatey & scoop packages as well as the package in the latest release would be good 👍
