### ISSUE TITLE
Crash on undo

### ISSUE THREAD

**Issue by pathwave** [helix-editor/helix#4258]
### Reproduction Steps

start hx
go insert and type anything
undo
go insert and type anything

thread 'main' panicked at 'Position 2 is out of range for changeset len 1!', helix-core/src/transaction.rs:397:13
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

**Comment by the-mikedavis** [comment]
What version are you using?

**Comment by the-mikedavis** [comment]
Looks like https://github.com/helix-editor/helix/issues/4226

**Comment by pathwave** [comment]
Yeah I was a few commits behind, Nice to see it fixed already!
