### ISSUE TITLE
Toggle to enforce a newline at the end of a document

### ISSUE THREAD

**Issue by vdccc** [helix-editor/helix#4274]
I suggest adding a toggle `eol` to enforce a newline at the end of a document.

**Comment by kuanyinglu** [comment]
I wonder if editorconfig can help enforce it? [#279](https://github.com/helix-editor/helix/issues/279)

**Comment by etienne-k** [comment]
It might be worth mentioning that this is also already unconditionally enforced by [rustfmt](https://github.com/rust-lang/rustfmt/commit/0c5f5082dcaf19944abc17d8b2275a6dc35a0e9b) (`:fmt?`). So if #279 is implemented/merged, we'd have at least 2 features which enforce this, and this new option would be a third one...

**Comment by tosti007** [comment]
> this new option would be a third one

I think that there are quite a few cases where such option would provide value, being any where rustfmt or editorconfig isn't available/applicable/redundant.

An example would be editing a simple text file, or a simple script whete I don't want to add an entire editorconfig.

**Comment by Boscop** [comment]
Yes. It would also nice to have a config setting that specifies whether helix should insert a newline at end of file if none exists whenever saving a file (regardless of which language the file is in).

**Comment by djpowers** [comment]
I think this would be a great addition as well. It looks like there was a pull request linked above that seemed almost ready to merge that has since been closed. Any way that could be reopened to continue the work?

**Comment by gabydd** [comment]
As it was closed, it's probably better for someone to open a new pr to continue the work. Unless the original author comes back and wants to finish it, but in the meantime it should be ok for someone else to pick it up.
