### ISSUE TITLE
List of mwes that panic

### ISSUE THREAD

**Issue by ammkrn** [helix-editor/helix#43]
These are minimal working examples of inputs after `hx` that cause a panic, tested on ubuntu and macOS.

`j, b`

`j, w`

`j, e`

`j, f, f`

`d, f, f`

`d, f, n`

`i, a, esc, b, w`

`i, a, esc, b, e`

and someone else brought up `d, d`.

I tried making the calls to `slice.char(_)` safe in the various`helix-core::movement` functions, but that caused off by ones in `coords_at_pos` and something in the compositor, I'm not sure if it's because of bad indexing elsewhere, or if my "fixes" aren't obeying rules about the anchor/head points for `Range`. Others have also noted that it seems like you can move down one more line than you would be able to in IE kakoune, but that doesn't seem to explain the `d, d` or `b` cases.

Just poking around, there seems to be a lot of interaction with ropey via partial functions which may not be ideal in the long run. It's a bummer that ropey doesn't seem to offer total versions of the indexing functions.

Cool project by the way, I wish you the best of luck.

**Comment by archseer** [comment]
I think I addressed some of these in the latest push, it's mostly of by one errors or missing bounds checks -- I agree that having a safe indexing wrapper would be useful as well.

**Comment by ammkrn** [comment]
Thanks. It looks like the remaining ones are `d, d`, `i, a, esc, b, w` and `i, a, esc, b, e`. If the ropey maintainers are interested in having an api extension that doesn't panic, I'll see about adding one.

**Comment by archseer** [comment]
After https://github.com/helix-editor/helix/commit/f4560cb68a24276789e8cdda918fc1ba705889de just `dd` left :)

**Comment by ammkrn** [comment]
Right on. The ropey maintainer(s) agreed to accept the api extension, I'm waiting for them to review the initial implementation. I'll @ mention you if/when it gets pulled into master.

**Comment by heliostatic** [comment]
Fantastic! Just came to report this (with backtrace) but delighted to see it will be fixed upstream.

**Comment by cessen** [comment]
Re: non-panicking version of Ropey's functions

@ammkrn and I have been discussing this in https://github.com/cessen/ropey/issues/39.  @archseer: if you could join the discussion over there, as the primary author of Helix, I'd really appreciate it!

**Comment by jbaa** [comment]
I believe the issue with `dd` was fixed with #90.

**Comment by ammkrn** [comment]
@jbaa  Seems like it to me. Since the ropey api discussion is happening there, I'll go ahead and close this. Thanks!
