### ISSUE TITLE
p pastes nothing but xclip works correctly

### ISSUE THREAD

**Issue by hgl** [helix-editor/helix#4305]
### Summary

When I press `p` in normal mode, nothing is pasted, but manually running `xclip -o -selection clipboard` in the terminal correctly outputs the content in the clipboard.

`~/.cache/helix/helix.log` is empty.

How could I debug what went wrong?

### Reproduction Steps

See summary.

### Helix log

<details><summary>~/.cache/helix/helix.log</summary>

Nothing was written to the log

</details>

### Platform

Linux (NixOS unstable)

### Terminal Emulator

kitty 0.25.2

### Helix Version

helix 22.08.1 (66276ce6)

**Comment by Ordoviz** [comment]
`p` pastes from Helix's clipboard; use `space p` to paste from the system clipboard. `hx --health` will show you whether Helix recognizes your xclip.

**Comment by hgl** [comment]
Ah, I misunderstood how `p` works. Thanks for the heads up. I think I need to give the doc a more thorough read.

**Comment by hgl** [comment]
Ah, I misunderstood how `p` works. Thanks for the heads up. I think I need to give the doc a more thorough read.

**Comment by hgl** [comment]
Looks like I can't close the issue myself.
