### ISSUE TITLE
Feature request: text-based auto-completion

### ISSUE THREAD

**Issue by xJonathanLEI** [helix-editor/helix#4326]
I'm trying to daily drive with Helix but find myself missing the (current buffer / opened buffers) text-based auto-completion feature from neovim a lot.

The best thing about text-based (vs. LSP) auto-completion is that it's super fast and has no dependency. It can be very helpful when:

- the LSP is not installed (or not supported)
- I just wanna make a quick edit, and don't want to wait for the LSP to initialize (especially ones with slow startups like `rust-analyzer`?)
- even when the LSP _is_ initialized, sometimes it takes a while to reflect code changes, and it's faster to just get text-based suggestions if I'm familiar with the codebase I'm editing

Lacking this feature, I have to do a lot of _find-yank-replace_ instead of just typing out the first letters and selecting from the suggestions. This is especially bad in dynamic languages since a typo may not be detected until runtime, making the user more cautious and always opt for _find-yank-replace_.

I'm pretty certain this has been requested (or even already implemented) before, but I can't find anything relevant from the issues. Sorry for spamming if that's the case. Would love a pointer to the relevant issue. Thanks!

**Comment by Omnikar** [comment]
#1063

**Comment by xJonathanLEI** [comment]
Ah "lexical" is the keyword. Thanks!
