### ISSUE TITLE
XML Syntax highlighting not working out of the box

### ISSUE THREAD

**Issue by bravo2zero** [helix-editor/helix#4331]
As title says, fresh brew installation of Helix, XML syntax highlighting is missing and XML is not showing up in "set-language" hints.

❯ hx --version
helix 22.08.1 (66276ce6)

MacOS 12.6

**Comment by the-mikedavis** [comment]
XML is not yet supported. See https://github.com/helix-editor/helix/issues/3479#issuecomment-1221323100
