### ISSUE TITLE
Clarify installation instructions when building from source when HELIX_RUNTIME is set.

### ISSUE THREAD

**Issue by gdtroszak** [helix-editor/helix#4336]
The [current instructions for building from source](https://github.com/helix-editor/helix#installation) are correct when the `HELIX_RUNTIME` variable is not set. However, when `HELIX_RUNTIME` is set prior to running `cargo install --path helix-term` the grammar libraries are placed in `$HELIX_RUNTIME/grammars`, which causes the subsequent instructions for symlinking the runtime directory to be incorrect.

Running `ln -s $PWD/runtime $HELIX_RUNTIME` as the instructions suggest results in this incorrect directory structure in `HELIX_RUNTIME`.

```
$HELIX_RUNTIME
|-- grammars  # generated during install
|-- runtime   # incorrect symlink
```

Ultimately I had to symlink everything in `helix/runtime` except `grammars` to get this to work.

```
# Run from helix repo.
ln -s $PWD/runtime/queries $HELIX_RUNTIME
ln -s $PWD/runtime/themes $HELIX_RUNTIME
ln -s $PWD/runtime/tutor $HELIX_RUNTIME
```

This isn't a huge deal, but it may be good to call this behavior out in the installation documentation? I'm happy to do so if I'm not mistaken in my findings and others believe this would be helpful.

**Comment by the-mikedavis** [comment]
If you use the `HELIX_RUNTIME` env var, you don't need to use a symlink. The `HELIX_RUNTIME` env var should point to the location of the `runtime` directory

**Comment by gdtroszak** [comment]
Sure. I guess the somewhat unexpected thing was that the grammars were generated in `HELIX_RUNTIME` when running `cargo install --path helix-term`, and so the env var (minimally) impacts _building_ helix instead of just running it.

It sounds like if `HELIX_RUNTIME` is set prior to building from source you should do one of two things:

1. Set it to `{HELIX_REPO_DIR}/runtime` (if you plan on keeping the repo around).
2. `mkdir -p $HELIX_RUNTIME && cp -r {HELIX_REPO_DIR}/runtime/* $HELIX_RUNTIME` then run `cargo install --path helix-term` (if you don't want to use the default runtime location and plan on removing the repo after install).

**Comment by the-mikedavis** [comment]
Right yep, HELIX_RUNTIME affects the runtime directory during build.

The first option is the intended usage afaik and that's similar to how you would use HELIX_RUNTIME if you installed by downloading one of the pre-built binaries from https://github.com/helix-editor/helix/releases - you would point HELIX_RUNTIME at the `runtime` directory in that archive

**Comment by gdtroszak** [comment]
👍 Mind if I take a stab at clarifying this a bit more in the README and [docs](https://github.com/helix-editor/helix/blob/master/book/src/install.md#build-from-source)?

**Comment by the-mikedavis** [comment]
Yep have at it 👍
