### ISSUE TITLE
Reuse injection and locals layers in syntax tree

### ISSUE THREAD

**Issue by kirawi** [helix-editor/helix#434]
Need to figure out a way to retain the layers and match them up during incremental parses. Currently they're completely recalculated each incremental update, which is fine with small amounts of injection-queryable code, but not as fine with larger quantities, which would be common in HTML for instance.

**Comment by kirawi** [comment]
A slight bug because we don't retain layers: if the beginning of an injection quarriable section of code is out-of-view, it does not get appropriately highlighted.

**Comment by kirawi** [comment]
This also occurs with `locals.scm`.

**Comment by archseer** [comment]
Incremental rendering has been merged
