### ISSUE TITLE
Expose an overlay in `flake.nix`

### ISSUE THREAD

**Issue by leungbk** [helix-editor/helix#4343]
It would be nice if the `flake.nix` exposed an overlay defining the bleeding-edge `helix`. This would permit clean composition into a personal configuration without otherwise changing existing Helix-related configuration.

Example: https://github.com/oxalica/nil/commit/4c77fa90ef238f81c2c801db66b1d56140551ecc

**Comment by s0LA1337** [comment]
i am not quite sure if i understand it correct, but:
by adding `github.com:helix-editor/helix/master` as a flake input, you could essentially overwrite the package in the home-manager options for helix like so:
```nix
{ helix-master, pkgs, ... }:

programs.helix = {
	enable = true;
	package = helix-master.packages."x86_64-linux".default;
	# your config here: ...
};
```

at least that's how i do it (well sort of)
i have a personal forked branch which adds some open pull requests. :)

This may or may not be a proper way of doing it, but at least by doing that you have access to the 'bleeding edge' :)

**Comment by leungbk** [comment]
Your way is good too, it's just that if my proposed change is implemented, the end user has an even easier time of it, by simply adding the overlay into their `flake.nix` without having to additionally drill the `helix` flake input into their `home.nix`.

**Comment by oati** [comment]
Couldn't you just trivially define your own overlay?

From my config:
```nix
final: prev: { inherit (flakes.helix.packages.${system}) helix; }
```
