### ISSUE TITLE
Publish to winget

### ISSUE THREAD

**Issue by lwbt** [helix-editor/helix#4344]
In https://github.com/helix-editor/helix/issues/277 it was initially considered to publish to winget, but it was put on hold. _»At this time installers must either be MSIX, MSI or .exe application installers.«_

It looks like the limitation does not exist anymore: https://github.com/microsoft/winget-cli/pull/2500

Could you please consider again to offer a winget package? Having Neovim available right from the start whenever I need to touch Windows is a life saver. Helix or Kakoune sound very interesting.

**Comment by SmiteWindows** [comment]
https://github.com/microsoft/winget-cli/releases/tag/v1.4.3531

**Comment by kirawi** [comment]
Closed by https://github.com/microsoft/winget-pkgs/pull/101377
