### ISSUE TITLE
Mouse clicks in file selection list

### ISSUE THREAD

**Issue by gdamore** [helix-editor/helix#4373]
(This might be construed reasonably as a bug.)

If I click in the file selection (say from "space-f"), what happens is the cursor in the buffer underneath is moved.

What I would reasonably expect is that this moves cursor in the selection in the file list to the file name I clicked on. 

For bonus points, it would be cool if double-clicking actually just selected the item (same as advancing to it and pressing enter).

**Comment by the-mikedavis** [comment]
Duplicate of https://github.com/helix-editor/helix/issues/2235
