### ISSUE TITLE
How to close/clear the popup of the command `:run-shell-command`

### ISSUE THREAD

**Issue by geometryolife** [helix-editor/helix#4377]
![981B4C81-F707-4FCE-BC69-AD942FAF3005](https://user-images.githubusercontent.com/54882546/196836502-1c2694ed-6889-4f7d-a634-86145f0a5b1b.jpeg)

**Comment by Omnikar** [comment]
`<esc>`

**Comment by geometryolife** [comment]
> <esc>

Thanks
