### ISSUE TITLE
Support config line ending in config.toml?

### ISSUE THREAD

**Issue by wsw0108** [helix-editor/helix#4378]
### Discussed in https://github.com/helix-editor/helix/discussions/3945

<div type='discussions-op-text'>

<sup>Originally posted by **wsw0108** September 23, 2022</sup>
When open new file with `:o file` under Windows, the line ending is `CRLF` which is not I wanted.
Does there has a way to specify line ending in config file?</div>

**Comment by CptPotato** [comment]
I'll give this a shot soon.
