### ISSUE TITLE
multi cursors did not disappear

### ISSUE THREAD

**Issue by y1rn** [helix-editor/helix#439]
### Reproduction steps
NOR mode
- case 1
  - 'v' and select some lines
  - 's' and input something match more then one
  - 'enter'
  - 'esc'
- case 2 
  - '%'
  - 's'  and input something match more then one
  - 'enter'

after that press 'hjkl', multi cursors are move at the same time and press 'esc' cannot exit.
i m not sure is that are bugs or not.

### Environment

- Platform: Linux arm 5.10.0-0.bpo.7-arm64 #1 SMP Debian 5.10.40-1~bpo10+1 (2021-06-04) aarch64 GNU/Linux
- Helix version: helix 0.3.0

**Comment by python128** [comment]
To keep primary selection, you have to type `<space><space>`.
`Esc` key doesn't work for this. If you want, you can configure the same in your config.toml

`<space><space>`
The first <space> starts [Space](https://docs.helix-editor.com/keymap.html#space-mode) Mode.
The second <space> Keeps only the primary selection.

**Comment by pickfire** [comment]
I think `<esc>` cannot be allowed to clear multi-cursors because we can't know whether user want to exit the mode or some other stuff or exit multi-cursors, is it possible?

**Comment by y1rn** [comment]
but why allow move multiple cursors after regex selection

**Comment by python128** [comment]
> I think `<esc>` cannot be allowed to clear multi-cursors because we can't know whether user want to exit the mode or some other stuff or exit multi-cursors, is it possible?

True.. We may want to exit the `insert` mode after typing(changing) some words, but don't want to remove the selections.

**Comment by archseer** [comment]
> but why allow move multiple cursors after regex selection

Because it's a core editing primitive. Maybe you make a regex based split selection, do a change, then decide to jump to the start of all these lines and do some more editing there. It's a feature, not a bug :) 

I think `esc` could clear the selection in normal mode potentially, but I would like to postpone that until there's a "repeat last selection" feature in case you accidentally clear a selection.

**Comment by y1rn** [comment]
![Animation](https://user-images.githubusercontent.com/70128797/125604802-9a6c4f83-e706-4963-93a4-edbcd2f47f3a.gif)

**Comment by archseer** [comment]
It's a feature. You can select by "fmt" then www to edit inside the brackets. If you want to drop the extra cursors, space+space.

**Comment by pickfire** [comment]
I wonder if `space+space` is too troublesome to type, is it possible to give it like `alt+;`? Or something else but not `space`?

**Comment by archseer** [comment]
> I wonder if `space+space` is too troublesome to type, is it possible to give it like `alt+;`? Or something else but not `space`?

It's just space in kakoune but we had to move it. I think it should be a different key. Probably just an extra behavior of ESC in normal mode.

**Comment by y1rn** [comment]
in my opinion，exiting is troublesome and cursors moving out of 'fmt' is useless.
