### ISSUE TITLE
Global search for selected text

### ISSUE THREAD

**Issue by lukepighetti** [helix-editor/helix#4394]
It would be nice if there was an easy way to global search for selected text, the current method is `y[space]/C-r"[Enter]`

Perhaps if text is selected when you type `[space]/` it will be available to search? Open to ideas.

**Comment by the-mikedavis** [comment]
Global search will use the `/` register as a default. Instead of yanking and pasting from the `"` register, you can use `*` to save the current selection to the `/` register then `<space>/<ret>` will search for that selection.

**Comment by lukepighetti** [comment]
Works for me
