### ISSUE TITLE
mac os syntax highlighting issue

### ISSUE THREAD

**Issue by y1rn** [helix-editor/helix#440]
![Screen Shot 2021-07-13 at 9 22 48 PM](https://user-images.githubusercontent.com/70128797/125460457-2d29c90a-5481-4c3c-bbef-9d9c06146419.png)

hx install on remote vps, windows terminal on win11 syntax highlighting work well

### Environment

- Platform: Linux arm 5.10.0-0.bpo.7-arm64 access with intel mac os terminal
- Helix version: Helix version: helix 0.3.0

**Comment by archseer** [comment]
Did you enable truecolor support? I'm assuming this is some sort of a termcap/terminfo issue, not a helix bug.

**Comment by y1rn** [comment]
![Screen Shot 2021-07-13 at 10 29 41 PM](https://user-images.githubusercontent.com/70128797/125470262-12335134-73f9-4915-84fc-e145a462df67.png) 
neovim work well. terminal version is Version 2.10 (433) whit xterm-265color

**Comment by archseer** [comment]
Yeah, it's not just 256 colors, it's true color: https://gist.github.com/XVilka/8346728

There's a test in there to confirm if your terminal supports it. We should probably support 16/256 color themes in the future.

**Comment by y1rn** [comment]
thx, is ok with other terminal
