### ISSUE TITLE
hxdiff (Helix as Difftool)

### ISSUE THREAD

**Issue by s0LA1337** [helix-editor/helix#4401]
I am unsure whether this enhancement request does already exist, when i searched for it, i didn't find anything.

Anyway, i think it would be a great addition to helix if there'd be some kind of merge mode (like vimdiff / nvimdiff).

**Comment by archseer** [comment]
Duplicate of https://github.com/helix-editor/helix/issues/405 ?

**Comment by s0LA1337** [comment]
> Duplicate of #405 ?

yup. Thanks did not find it.
