### ISSUE TITLE
Cli ux proposal: recursively autofind file on start

### ISSUE THREAD

**Issue by adsick** [helix-editor/helix#4402]
First things first, it should not be the default behavior, but opt-in instead. You will need to turn it on in the config.

imagine cd-ing to some project root dir and running `helix main.rs`, it will create a new buffer since there is no main.rs in root of the project. I would like helix to start searching for main.rs in subdirs of the root and 
* if found - open it
* if found several times - list all of them in picker
* if not found - create in current dir
I believe it may improve ux for those who would like to use it that way, but this behavior should not be the default.

**Comment by adsick** [comment]
obviously if the file is present in the current dir there wouldn't be any difference

**Comment by CptPotato** [comment]
What I like to do is `hx .` so helix starts up with the file picker opened in the current directory.

Then, searching `main` or whichever file I'm looking for will usually find it straight away.

**Comment by ksandvik** [comment]
Just tested, hx . opens up the file picker as first action.

**Comment by dead10ck** [comment]
This seems pretty niche to build in.

1. Helix isn't just used for programming Rust projects
1. Even in Rust projects, not all have a `main.rs`.
1. This could easily be a shell one liner, e.g. `hx **/main.rs || hx main.rs`
1. You could just `hx .` as previously suggested
