### ISSUE TITLE
Alias `insert-output` from `io`

### ISSUE THREAD

**Issue by lukepighetti** [helix-editor/helix#4407]
Would be nice to quickly fire off `:insert-output` with `:io`

**Comment by Omnikar** [comment]
Forgive me if I'm wrong, but isn't `:insert-output` equivalent to `!`?

**Comment by Bruce-Hopkins** [comment]
I'm looking to contribute to this project. Can I be assigned the issue?

**Comment by lukepighetti** [comment]
@the-mikedavis @Omnikar makes a good point here. Should we close this?

**Comment by geometryolife** [comment]
I don’t think it’s necessary to add aliases, because it is convenient to run `insert-output` and `append-output` with `!` and `A-!`.

**Comment by the-mikedavis** [comment]
Hmm yeah, let's close this. In general, aliasing would be improved by https://github.com/helix-editor/helix/issues/582 or this case could be covered by https://github.com/helix-editor/helix/issues/4423. But key-rebinding or using the existing `!`/`A-!` would be more convenient here.
