### ISSUE TITLE
Provide keyboard mapping schema that isn't based on vi or vim

### ISSUE THREAD

**Issue by airtonix** [helix-editor/helix#4410]
For us normal peasants please give us a normal keyboard mapping scheme that's able to handle schemes like vscode and sublime text has.

**Comment by dead10ck** [comment]
It's really unclear what you're asking for. If you just want different key mappings, you can configure them yourself. If you want to contribute meaningful discussion about the default mappings, you can join the discussion in #165. If you mean you want a modeless editor where you want insert mode all the time, arrow keys, etc, then see https://github.com/helix-editor/helix/pull/3671. Helix is not VSCode or Sublime. Those are fine editors, but helix is not trying to be a drop in replacement for them.

**Comment by the-mikedavis** [comment]
Modal editing is part of Helix's vision (see [here](https://github.com/helix-editor/helix/blob/d7d0d5ffb79b6f2e09c6ab8af6e112c41e6f73e8/docs/vision.md?plain=1#L17)) and we aren't interested in supporting multiple paradigms (see [here](https://github.com/helix-editor/helix/blob/d7d0d5ffb79b6f2e09c6ab8af6e112c41e6f73e8/docs/vision.md?plain=1#L11)).

You may be able to build something non-modal by rebinding keys in insert mode but it isn't possible to entirely eliminate modes from Helix. I would encourage you to run through the tutor and try to get a feel for how Helix works and see if you end up liking it.
