### ISSUE TITLE
had issue when open a new file

### ISSUE THREAD

**Issue by kabirz** [helix-editor/helix#442]
lsp and language grammar not work when open a new file, and save it, show `cannot write a buffer without a filename`

**Comment by archseer** [comment]
`:w filename.txt`

**Comment by kabirz** [comment]
dose it mean edit a new file must like this:
```
touch file.txt
hx file.txt
```
??
or 
```
hx
:w file.txt
```

**Comment by pickfire** [comment]
Yeah, I think we should keep the filename when `hx new-file`.

**Comment by kabirz** [comment]
maybe #228 causes it. Previous  is good.
