### ISSUE TITLE
New elements for statusline

### ISSUE THREAD

**Issue by superDuperCyberTechno** [helix-editor/helix#4434]
I'd like to propose 2 new elements for the statusline:
* Total lines in current file
* The absolute path for the current file

**Comment by Chickenkeeper** [comment]
'Total lines in current file' was already added a little bit ago, if you build from source you can access it via the `total-line-numbers` element described in [the latest docs](https://docs.helix-editor.com/master/configuration.html). But absolute path could still be useful

**Comment by superDuperCyberTechno** [comment]
Nice, thanks. I assume this will be part of the next release?

**Comment by Chickenkeeper** [comment]
Yes, I think whatever's in the `master` branch becomes part of the next release
