### ISSUE TITLE
Exchange Keymaps

### ISSUE THREAD

**Issue by knpwrs** [helix-editor/helix#4442]
One of my most-used plugins other than vim-surround is [vim-exchange](https://github.com/tommcdo/vim-exchange). Essentially you can exchange the contents of any two motions without having to jump back and forth. E.g., `cxiw` on one word followed by `.` on another will swap those two words. `cxt, w cxt)` swaps the order of two parameters in a two-parameter function (to use a contrived example to demonstrate multiple motions).

Exchange mappings in helix would be great!

**Comment by Chickenkeeper** [comment]
This can be done by selecting the two words you want to swap and pressing `Alt-(` or `Alt-)` to `rotate_selection_contents_backward` or `rotate_selection_contents_forward` respectively

**Comment by knpwrs** [comment]
Awesome, that works! I'm looking at the docs for selection manipulation and wondering if there's a way to manipulate individual selections instead of all of the selections at once.

**Comment by Chickenkeeper** [comment]
I don't think so. You can change which selection is the primary one, and remove individual selections from a group of selections, but you can't adjust the primary selection without potentially affecting the others.
