### ISSUE TITLE
Line count gutter doesn't exceed 5 characters

### ISSUE THREAD

**Issue by lukepighetti** [helix-editor/helix#4469]
<img width="326" alt="Screen Shot 2022-10-25 at 7 59 31 PM" src="https://user-images.githubusercontent.com/666539/197903773-aaa8ba69-e345-49a1-aa5b-037d62fd9e4c.png">

This is line 2,499,998 and what's displayed is `24999`

**Comment by the-mikedavis** [comment]
Duplicate of https://github.com/helix-editor/helix/issues/2583
