### ISSUE TITLE
Add support for KDL files

### ISSUE THREAD

**Issue by luccahuguet** [helix-editor/helix#4479]
KDL is similar to YAML or TOML, and used by important projects such as Zellij, a terminal multiplexer.

This issue might depend on KDL LSP support being implemented https://github.com/tjhancocks/kdl/issues/50

**Comment by selvmaya** [comment]
> This issue might depend on KDL LSP support being implemented [tjhancocks/kdl#50](https://github.com/tjhancocks/kdl/issues/50)

This reference seems wrong. That KDL is some other language (see [this](https://github.com/tjhancocks/kdl/blob/master/Documentation/Introduction.md)), and not the document language used by Zellij as mentioned.

This is the project you want to look at instead:
https://github.com/kdl-org/kdl

**Comment by luccahuguet** [comment]
> > This issue might depend on KDL LSP support being implemented [tjhancocks/kdl#50](https://github.com/tjhancocks/kdl/issues/50)
> 
> This reference seems wrong. That KDL is some other language (see [this](https://github.com/tjhancocks/kdl/blob/master/Documentation/Introduction.md)), and not the document language used by Zellij as mentioned.
> 
> This is the project you want to look at instead: https://github.com/kdl-org/kdl

thanks, I edited my text
