### ISSUE TITLE
Jumplist has Duplicate Entries

### ISSUE THREAD

**Issue by ngraham20** [helix-editor/helix#4488]
When using the Jumplist panel to navigate the jumplist, duplicate entries quickly emerge and are difficult to get rid of as there is no "delete selection from jumplist" command

To reproduce:
1. Open a file and put the cursor someplace on the file.
2. ctrl+s to add the character to the jumplist
3. add another character
4. and another
5. now start using the jumplist rapidly. You will quickly notice multiple duplicate entries on the jumplist

**Comment by ngraham20** [comment]
OH This is not a real issue, the difference is which character(s) I have highlighted, I had not understood that it was jumping to a particular selection, not a particular line.

**Comment by ngraham20** [comment]
Still though, I do have duplicate entries that build up while jumping around using the jumplist panel. I do not understand what I'm doing to cause this though

**Comment by the-mikedavis** [comment]
This is the expected behavior: the jumplist is analagous to history in a browser and this case is like following a link from page A to page B and back to page A, and so on. The jumplist prevents sequential duplicate entries since they aren't useful but duplicates in overall history can be useful.

**Comment by ngraham20** [comment]
Hmm, I think I'm starting to understand its usecase then. I wonder then if it would be useful to have a list of unique jumplist items to scroll through separately like the buffer list? Frequently, my usecase for the jumplist picker is to scroll through the list of unique jumps I've made recently as a way to visually jump around my documents. This breaks quickly when the jumplist doesn't dedup completely

**Comment by the-mikedavis** [comment]
If the jumplist picker were deduplicated by default then it might be confusing because it would hide parts of the history. Maybe a key in the picker to deduplicate items could work but I don't know how useful that would be for pickers in general since other pickers are deduplicated by default
