### ISSUE TITLE
Auto-indent when replace with newline

### ISSUE THREAD

**Issue by Multirious** [helix-editor/helix#4503]
I'm having this one annoyance where when I replace space with newline. I always expected it to automatically indent the next line due to vscode vim (I'm not sure if it's a thing in vim too). I could do `di<enter>` but replace with newline will be a little faster and my liking. I'm suggesting that there's an option to toggle auto-indent when replacing with newline.

**Comment by pascalkuthe** [comment]
this is intentional and I don't think we will change this. You can use `c<ret><esc>` if you want autoindentation. Having dedicated keys for both is nice and doesn't need a config option and is more consistent.
