### ISSUE TITLE
Make pressing x on an empty line select one line only

### ISSUE THREAD

**Issue by Multirious** [helix-editor/helix#4506]
Pressing `x` on an empty line will cause you to also select the next one.
Probably because
> Select current line, if already selected, extend to next line

When the line is empty, you will select the newline... which mean you're going to select the next one.
I don't know if this is an intended feature, but anyways I hate it. It's not intuitive and breaking my muscle memory.

Edit: Seems like this is a me thing. It's already selected so why press x? So like when I need to do something with the line I kept pressing `x` which also cause me to do that with the empty line. But the empty line is already selected by helix/kakoune philosophy. So it's really doing things with my muscle memory on whole line editing. I might close this if it's just unnecessary to update the key.

**Comment by the-mikedavis** [comment]
Yep this is the expected behavior. You may want to use `X` which only selects the current line and does not extend.
