### ISSUE TITLE
Helix editor ignores standard Linux mouse click paste of text

### ISSUE THREAD

**Issue by mbratch** [helix-editor/helix#4511]
### Summary

All other programs under Linux seem to understand that if I copy text from one application or window, I can paste it in another with a simple mouse click. I thought this was basically a standard under Linux (at least it's worked this way for the many years and many versions of Linux I've used).

Helix is different. When I select text it doesn't automatically copy as it does in any other program (such as vim or a basic text editor or a browser), and when I try to paste from another app using a mouse click while in insert mode in helix, it ignores it.

How can I get this to work in helix? I did do some research and installed xclip, but I'm not sure how to engage it. There are some commands in helix in command mode for pasting from the clipboard but these don't do anything.

Thank you, and apologies for the basic issue. I'm sure it's pilot error on my part.

### Platform

Linux

### Terminal Emulator

putty

### Helix Version

22.08.1

**Comment by the-mikedavis** [comment]
What does `hx --health | head` say for the "Clipboard provider"?

Selecting text with the mouse should automatically copy it. If you're using X then `xsel` or `xclip` should work as clipboard providers but if you're using Wayland then you'll need `wl-clipboard` (`wl-copy`/`wl-paste`)

**Comment by mbratch** [comment]
> What does `hx --health | head` say for the "Clipboard provider"?
> 
> Selecting text with the mouse should automatically copy it. If you're using X then `xsel` or `xclip` should work as clipboard providers but if you're using Wayland then you'll need `wl-clipboard` (`wl-copy`/`wl-paste`)

Hm. It says there isn't a clipboard provider installed but I do have xclip installed and it's in my path. I don't know if I am using Wayland. I generally just remote to my machine with putty (ssh). All of the other programs, including vim, seem to understand the basic copy/paste rules except helix.

I installed wp-clipboard but it still says there's no provider installed.

**Comment by the-mikedavis** [comment]
Ah, if it's over an ssh connection, this may need OSC52 in order to be supported. #3220

**Comment by the-mikedavis** [comment]
#3220 was just merged so this should be working now if your terminal supports OSC52 (I think putty does but I haven't tried it)

**Comment by pascalkuthe** [comment]
This should have been fixed by #3220 so I am closing this issue.
If the problem persists feel free to reopen this issue.
