### ISSUE TITLE
Split lines in normal mode (opposite of `Shift + J`)

### ISSUE THREAD

**Issue by fillipe-gsm** [helix-editor/helix#4541]
For merging multiple lines there is the `J` keymap. For instance, if I have

```python
def my_function(
    variable: int
) -> int:
```
if my cursor is on the first line I can press `J` twice and get

```python
def my_function(variable: int) -> int:
```

all of this in normal mode. 
But for the opposite I have to move the cursor right before `variable`, go to Insert mode, press the return key, go back to Normal mode, and repeat. This gets tedious really quickly on multiple formatting.

On Vim and Neovim I managed to map `Ctrl + j` to the `<nl>` command, but any other combination on normal mode should be fine. 
Is it possible to do the same with Helix?

Edit: replace `Shift + j` with simply `J`.

**Comment by the-mikedavis** [comment]
What is `<nl>` in Vim? It inserts a newline?

Macro key-bindings would be a solution for this - you could bind a key to enter insert mode, add a newline, and go back to normal mode https://github.com/helix-editor/helix/issues/1383

**Comment by fillipe-gsm** [comment]
Thanks for the quick response.
So instead of an actual macro key-binding I follow your suggestion and added a new key mapping:

```toml
# config.toml
[keys.normal]
C-j = ["insert_mode", "insert_newline", "normal_mode"]
```
so I can now add line breaks in specific points without leaving normal mode.

Thank you once more!
