### ISSUE TITLE
Helix stops when run hx ... in the editor

### ISSUE THREAD

**Issue by tsugumi-sys** [helix-editor/helix#4552]
## Problem

Helix stops completely when run command `:sh hx` in the editor.

### Reproduction Steps

 

I tried this:

1. `hx` (open editor)
2. `:sh hx` (run command in editor)

I expected this to happen: Raising an error.

Instead, this happened: 

~Helix completely stops.~

1. I can quit if I type `:q<ret>` immediately. But while typing `:q`, the helix view is not changing.
2. I cannot quit if I type other keys.

### Helix log

I tried `hx -v(vv)` and no log generated in log file (`:log-open`).

<details><summary>~/.cache/helix/helix.log</summary>

```
please provide a copy of `~/.cache/helix/helix.log` here if possible, you may need to redact some of the lines
```

</details>

### Platform

Windows (WSL2 Ubuntu)

### Terminal Emulator

Windows Terminal

### Helix Version

helix 22.08.1 (fee5db16)

**Comment by the-mikedavis** [comment]
I'm not sure if Windows has the same behavior but on unix, Helix is successfully spawned within Helix: you can press `:q<ret>` to quit that child instance. `:sh` doesn't show stdout until the command is complete and it is taking over stdin from the parent Helix process.

`:sh` is meant for non-interactive commands though - a full embedded terminal is discussed in #1976

**Comment by ygabuev** [comment]
I am observing the same issue on Linux (5.19.13-arch1-1), helix 22.08.1, foot 1.13.1. Entering `:sh helix` freezes the view. Pressing `:q<ret>` unfreezes it, but a bunch of ugly characters appear
![image](https://user-images.githubusercontent.com/12871516/199282524-666531d2-1f88-406c-80af-53058e083fde.png)
