### ISSUE TITLE
Improve keymap hashmap performance

### ISSUE THREAD

**Issue by Bruce-Hopkins** [helix-editor/helix#4555]
Don't get me wrong, in my usage of Helix, it's been blazing fast. So far I haven't seen many performance issues. 

But I did notice that the hashmap used for the keymap is the `std::Hashmap`. The [docs of std::hashmap](https://doc.rust-lang.org/std/collections/struct.HashMap.html) state:

> By default, HashMap uses a hashing algorithm selected to provide resistance against HashDoS attacks.

DoS attacks aren't something the editor would ever have to worry about. Furthermore, the DoS prevention algorithm makes the hashmap slower. 

We should use [fvn hashmaps](https://docs.rs/fnv/latest/fnv/) which performs better since it doesn't use DoS prevention algorithms. The fnv hash is also optimized for small inputs, perfect for our usage.

This is a small improvement. I doubt the performance difference will be noticeable, but switching to fnv hash whenever we can, seems like a good idea overall for the project.

**Comment by archseer** [comment]
Yes, I've done this initially then ripped out the extra crates a couple of years back. Helix uses very few hashmaps and these are accessed a few times per operation, not thousands of times.

Performance optimizations only make sense when you can benchmark the change beforehand and determine that there's a meaningful difference by the optimization ([In fact switching to a faster hashmap can destroy deserialization performance](https://morestina.net/blog/1843/the-stable-hashmap-trap), as this recent article shows). On a regular flamegraph trace of `hx` execution you can barely even see the hashing operations.

> small inputs

`fnv` works great for small keys like IDs, but we do also index full file paths/URIs.

**Comment by Bruce-Hopkins** [comment]
Thanks for the reply!

> Performance optimizations only make sense when you can benchmark the change beforehand and determine that there's a meaningful difference by the optimization

I can agree with that. Right now there's no noticeable need for optimization.

> ([In fact switching to a faster hashmap can destroy deserialization performance](https://morestina.net/blog/1843/the-stable-hashmap-trap), as this recent article shows). On a regular flamegraph trace of hx execution you can barely even see the hashing operations.

I didn't know about that. Thanks for the info!

It looks like there's no need to change hashmaps then.
