### ISSUE TITLE
Completion not working with commands if no parameter was passed to them

### ISSUE THREAD

**Issue by seshotake** [helix-editor/helix#4563]
### Summary

Completion not working in command mode if there is not parameter 

Also I noticed that if use alias `:o` completion works  without parameter but instead the space between them was deleted

![using-alias](https://user-images.githubusercontent.com/116971836/199372522-37309725-e046-45c5-94ed-2ded5e89a410.png)

when selected:
![selected](https://user-images.githubusercontent.com/116971836/199372900-15c30c5b-f1af-4a8d-a939-2d3547af8c0f.png)

### Reproduction Steps

I tried this:

1. `:open` or `:theme`

I expected this to happen: show completions

Instead, this happened: nothing shown

### Platform

Linux

### Terminal Emulator

zellij

### Helix Version

helix 22.08.1 (c803ef87)

**Comment by archseer** [comment]
Could be a regression from https://github.com/helix-editor/helix/pull/4316

\cc @mitsuhiko
