### ISSUE TITLE
Add a `--language` flag for forcing the language on the first buffer

### ISSUE THREAD

**Issue by xJonathanLEI** [helix-editor/helix#4564]
It would be really nice to have a `--language` flag to force set the language option for the first buffer. It's gonna be very helpful for doing something like:

```console
$ curl "https://xxxx.json" | hx --language json
```

Not sure about the implication on LSP, but at least you get syntax highlighting and formatter support, which is very nice already.

**Comment by archseer** [comment]
Can't you just use `:set-language` afterwards? We're trying to keep the set of CLI flags deliberately small since this is an interactive TUI program

**Comment by xJonathanLEI** [comment]
Yes that does the same thing really, but having a CLI option allows aliasing (e.g. `alias hxj="hx --language json`). I proposed this flag because I remember seeing this exact approach on some editor (though I can't recall which one it is right now), and found it useful for piping.

That said, if it's against the design philosophy, then I can totally live with it. Closing this now.

**Comment by xJonathanLEI** [comment]
Though this is rejected, I still find the feature useful and implemented that on my own fork. Works like a charm:

```console
$ curl "https://xxxxxx" | hx --lang json
```

It works for all intial buffers, not just stdin.

For anyone who stumbles across this thread looking for the same feature, I have a [branch](https://github.com/xJonathanLEI/helix/tree/dev/lang_flag) on my fork that you can cherry-pick.

**Comment by Rudxain** [comment]
This feature is useful for things like:
```sh
zcat /usr/share/doc/bash-completion/README.md.gz | hx --lang markdown
```
