### ISSUE TITLE
Missing syntax highlighting (opensuse tumbleweed)

### ISSUE THREAD

**Issue by musicwei** [helix-editor/helix#4565]
### Summary

missing syntax highlighting ,helix --grammar fetch & build checked.runtime/grammars folder contains the associated compiled tree-sitter grammar for the language.

![image](https://user-images.githubusercontent.com/18691873/199418026-1bae5ea0-a031-4972-b56f-815ac588eb7d.png)

### Reproduction Steps

 

I tried this:

1. `hx`

I expected this to happen:

Instead, this happened:

### Helix log

<details><summary>~/.cache/helix/helix.log</summary>

```
please provide a copy of `~/.cache/helix/helix.log` here if possible, you may need to redact some of the lines
```

</details>

### Platform

linux

### Terminal Emulator

wezterm 20220905-102802-7d4b8249

### Helix Version

helix 22.08.1

**Comment by chopfitzroy** [comment]
I ran into this issue, you need to install `helix-runtime` as well.

See comments at bottom of this page for more info: https://build.opensuse.org/package/show/openSUSE:Factory/helix

Note you might need to remove `~/.config/helix/runtime` for it to take effect.

**Comment by musicwei** [comment]
> I ran into this issue, you need to install `helix-runtime` as well.
> 
> See comments at bottom of this page for more info: https://build.opensuse.org/package/show/openSUSE:Factory/helix
> 
> Note you might need to remove `~/.config/helix/runtime` for it to take effect.

this works thanks😀
