### ISSUE TITLE
Keymap for Vertical selection similar to Kakoune 'C' and 'alt+C'

### ISSUE THREAD

**Issue by siddharthagudgunti** [helix-editor/helix#457]
#### Describe your feature request
At present we don't have a way to select (or keep extending column selection vertically UP/DOWN) just single column. This is implemented in Kakoune with `C` and `alt+C` key combination.
The `extend_line_up/down` selects whole line when going UP/DOWN by line. I see already `extend_char_left/right`.
Similarly if we have `extend_char_up/down`, it may be able to address vertical selections.

**Comment by archseer** [comment]
Fixed by #462
