### ISSUE TITLE
bump up the tree-sitter for nushell

### ISSUE THREAD

**Issue by amtoine** [helix-editor/helix#4577]
helloe there :wave: :yum: 

this is related to https://github.com/helix-editor/helix/issues/4162 and https://github.com/LhKipp/tree-sitter-nu/issues/3 :+1: 

## the original issue
as stated in the two issues above, i had a highlighting problem in `nushell` source files, apparently with strings...
according to @LhKipp, this problem has been fixed on [LhKipp/tree-sitter-nu/main](https://github.com/LhKipp/tree-sitter-nu/commits/main) in [`695e3ec7`](https://github.com/LhKipp/tree-sitter-nu/commit/695e3ec794c74fb5a9bf4259128dff5fba6c0d71)..[`eb95bdac`](https://github.com/LhKipp/tree-sitter-nu/commit/eb95bdac3abd73ef47e53f19c63e74a31405ebd2)

## my feature request
as can be seen in [languages.toml#L1417](https://github.com/helix-editor/helix/blob/master/languages.toml#L1417), `helix` uses the old `db4e990b78824c8abef3618e0f93b7fe1e8f4c0d` revision of `tree-sitter-nu` :open_mouth:

i would love to test the new `tree-sitter-nu` in some `nushell` source files :star_struck: 

**is it as straightforward as opening a PR with the latest revision?**
**what about the "verified commits"?**

cheers :wink:

**Comment by amtoine** [comment]
i've tried the fix and it works by applying
```diff
diff --git a/.config/helix/languages.toml b/.config/helix/languages.toml
index 94313dc..e168fe5 100644
--- a/.config/helix/languages.toml
+++ b/.config/helix/languages.toml
@@ -7,3 +7,16 @@ roots = []
 comment-token = "(*"
 indent = { tab-width = 4, unit = "  " }
 grammar = "pascal"
+
+[[language]]
+name = "nu"
+scope = "source.nu"
+injection-regex = "nu"
+file-types = ["nu"]
+roots = []
+comment-token = "#"
+indent = { tab-width = 2, unit = "  " }
+
+[[grammar]]
+name = "nu"
+source = { git = "https://github.com/LhKipp/tree-sitter-nu", rev = "eb95bdac3abd73ef47e53f19c63e74a31405ebd2" }
\ No newline at end of file
```
and then running
```bash
> hx --grammar fetch
Fetching 114 grammars
113 up to date git grammars
1 updated grammars
	nu now on eb95bdac3abd73ef47e53f19c63e74a31405ebd2
> hx --grammar build
Building 114 grammars
113 grammars already built
1 grammars built now
	["nu"]
```

i'm only concerned with the "verified" commits but, apart from that, **would you be open to a PR from me?** :yum:

**Comment by archseer** [comment]
Yes, please open a PR :)

**Comment by amtoine** [comment]
> Yes, please open a PR :)
>
hang on, i'm on it :smirk:
