### ISSUE TITLE
`r<ret>` does not indent properly

### ISSUE THREAD

**Issue by emilyyyylime** [helix-editor/helix#4611]
I find myself using `c<ret><esc>` instead, but I think it would make sense for the current behaviour to be changed

**Comment by the-mikedavis** [comment]
This is the expected behavior: `r` is a naive replace with no extra effects. For example it also does not insert auto-paris when you use `r(`

**Comment by Itay123TheKing** [comment]
@the-mikedavis Sorry, I worded my original title in a weird way; I know this is the expected behaviour currently, I meant this as a suggestion for change in the behaviour

**Comment by pascalkuthe** [comment]
I think it should stay this way. I purposefully use r<ret> if I don't want autoindent. Autoindent really.only seems useful while.inserting text (it's an entirely insert mode concept.since trailing indents get stripped when exiting insertmode)
