### ISSUE TITLE
Feature request: selected character count

### ISSUE THREAD

**Issue by xJonathanLEI** [helix-editor/helix#4624]
When dealing with hashes (in hex) and big decimal numbers, I frequently find myself selecting the whole thing in vim just to check if the length is correct, thanks to the vim feature that shows how many chars you've selected.

Currently Helix is only able to show the number of _selections_. It would be nice to also have the option to display the number of characters.

**Comment by xJonathanLEI** [comment]
My current workaround is to put my cursor right _before_ the text I'm interested in, then press the desired length followed by `l` to see if the cursor lands on the last character. It kind of works for my case but not when you want to _measure_ the length of some text.

**Comment by Siiiimon** [comment]
Hi all!
I'd like to tackle this issue if that's fine with everyone 😄

**Comment by wes-adams** [comment]
@Siiiimon - sorry
this is  my first ever attempt at contributing. i didn't realize that we should claim work before starting.

**Comment by wes-adams** [comment]
the linter pointed out my poor coding style

pushed 2nd attempt

**Comment by Siiiimon** [comment]
no worries!

**Comment by wes-adams** [comment]
@Siiiimon - thanks for the feedback - i'll definitely be implementing your suggestions

i am stuck on one thing though:
how do i link my new `config.toml` setting to the actual logic in source?
```
config.toml
. . . 
[editor.statusline]
left = ["mode", "spinner"]
center = ["file-name", "primary-selection-length"]
right = ["diagnostics", "selections", "position", "file-encoding", "file-line-ending", "file-type"]
. . . 
```
```
> hx
Bad config: unknown variant `primary-selection-length`, expected one of `mode`, `spinner`, `file-name`, `file-encoding`, `file-line-ending`, `file-type`, `diagnostics`, `selections`, `position`, `separator`, `position-percentage`, `total-line-numbers`, `spacer` for key `editor.statusline.center` at line 16 column 1
Press <ENTER> to continue with default config
```
![Screenshot from 2022-11-10 09-41-57](https://user-images.githubusercontent.com/7883354/201121197-72220ccf-4beb-4d77-8331-76e1a7e693f2.png)
