### ISSUE TITLE
Select inside view

### ISSUE THREAD

**Issue by Itay123TheKing** [helix-editor/helix#4641]
Do you think it would make sense to have a command (e.g. `^`, seeing as it's close to `%`) to select everything currently visible on the screen? this would allow for e.g. `s`electing only what you can see.

Actually now that I think about it `s` is basically the only command that works inside the current selection isn't it?

Also would this be a problem to implement? I'd imagine the part that has to do with editing doesn't know much about the rendering (which it would need to to know the screen top and bottom)

**Comment by the-mikedavis** [comment]
This could be implemented with existing commands with something like:

```toml
[keys.normal]
"^" = ["goto_window_top", "select_mode", "goto_window_bottom", "extend_to_line_bounds"]
```

Though to select the entire visible screen you would need to `:set scrolloff 0` which I suppose could be done as part of the command.

> Actually now that I think about it `s` is basically the only command that works inside the current selection isn't it?

There's also `S` and https://github.com/helix-editor/helix/issues/3007 would add another.

> I'd imagine the part that has to do with editing doesn't know much about the rendering (which it would need to to know the screen top and bottom)

`View` has an `offset` and `area` which is used by `helix_term::commands::goto_window` to calculate where to move to.

But I don't think this needs a new command, the above binding seems to work well enough.
