### ISSUE TITLE
[macOS] OmniSharp (c-sharp lsp) not found/working properly even when in $PATH 

### ISSUE THREAD

**Issue by 0rphee** [helix-editor/helix#4645]
### Summary

Quoting from https://github.com/OmniSharp/omnisharp-roslyn/issues/2440#issue-1345194101

> **Steps to Reproduce**
> 
>     1. Download the latest (1.39.1) release for Apple Silicon (https://github.com/OmniSharp/omnisharp-roslyn/releases/download/v1.39.1/omnisharp-osx-arm64-net6.0.zip)
> 
>     2. Extract the .zip file, e.g. into `~/Downloads/omnisharp-osx-arm64-net6.0`
> 
>     3. `chmod +x ~/Downloads/omnisharp-osx-arm64-net6.0/OmniSharp`
> 
>     4. Attempt to run the app `./Downloads/omnisharp-osx-arm64-net6.0/OmniSharp`
> 
> 
> **Expected Behaviour** The app starts.
> 
> **Actual Behaviour** The app fails to start with the following message:
> 
> > "OmniSharp" can’t be opened because Apple cannot check it for malicious software.
> > This software needs to be updated. Contact the developer for more information.
> 
> <img alt="Screenshot 2022-08-20 at 16 36 13" width="372" src="https://user-images.githubusercontent.com/1206172/185754876-0974b7cd-c404-481a-bbb3-178b3e94ea66.png">
> 
> The HTTP build (https://github.com/OmniSharp/omnisharp-roslyn/releases/download/v1.39.1/omnisharp.http-osx-arm64-net6.0.zip) suffers the same problem.
> 
> To be brutally honest I'm not even sure if these steps are the correct / expected way of running the app as there is zero documentation that I can find on either running the app standalone, or using the C# library in an existing app.

This is what happens if we try to use the lsp, because as this https://github.com/OmniSharp/omnisharp-roslyn/issues/2440#issuecomment-1221905800 comment explains, we need to use `dotnet OmniSharp.dll` to use the lsp, as there's no OmniSharp executable.

However, as I found out changing my custom `languages.toml`, and changing: 
`language-server = { command = "OmniSharp", args = [ "--languageserver" ] }` to
`language-server = { command = "dotnet OmniSharp.dll", args = [ "--languageserver" ] }` or
`language-server = { command = "dotnet", args = [ "path/to/OmniSharp.dll", "--languageserver" ] }`
 it seems that, in the first alternative, helix looks for `dotnet OmniSharp.dll` as-is, obviously, without finding it in $PATH, and in the second solution, it just doesn't do it (don't know why).

To solve this, I created a shell script named `OmniSharp` and put it in my $PATH.
```
#!/bin/zsh

dotnet "my/path/to/OmniSharp.dll" --languageserver
```
while leaving my languages.toml config for c-sharp like this: `language-server = { command = "OmniSharp" }`.

### Reproduction Steps

 

I tried this:

1. install OmniSharp
2. add it to $PATH
3. open a _.cs file

I expected this to happen:
OmniSharp working
Instead, this happened:
OmniSharp doesn't work

### Helix log

<details><summary>~/.cache/helix/helix.log</summary>

```
please provide a copy of `~/.cache/helix/helix.log` here if possible, you may need to redact some of the lines
```

</details>

### Platform

macOS

### Terminal Emulator

Alacritty Version 0.11.0 (1)

### Helix Version

22.08.1-374-g3881fef3

**Comment by archseer** [comment]
> please provide a copy of `~/.cache/helix/helix.log` here if possible

**Comment by archseer** [comment]
@CptPotato how did you set up OmniSharp?

**Comment by the-mikedavis** [comment]
The Wiki doesn't need permissions to edit - feel free to add more installation notes for what you found for OmniSharp 👍

**Comment by 0rphee** [comment]
Alright, I updated the instructions in the Wiki, I'll close this then!
