### ISSUE TITLE
Statusbar separator and mode colors not working

### ISSUE THREAD

**Issue by dahmc** [helix-editor/helix#4660]
### Summary

2 issues with the status bar:

1. I can't get the separator to show
2. I can't get the mode to show in different colors 

### Reproduction Steps

 

I tried this:

Link the runtime files.

Theme extended with
```
inherits = "gruvbox"

ui.statusline.separator = { bg = "gray1", fg = "fg1" }
```

Config:
```
theme = "gruvbox_custom"

[editor.statusline]
left = ["mode", "spinner"]
center = ["file-name"]
right = ["diagnostics", "selections", "position", "file-encoding", "file-line-ending", "file-type"]
separator = "│"
```

I expected this to happen:
1. Separator showing up
2. Normal mode, Insert mode, and select mode have different background colors

Instead, this happened:
<img width="1084" alt="CleanShot 2022-11-08 at 20 44 38@2x" src="https://user-images.githubusercontent.com/75008413/200661386-f1deb009-431d-49d5-bf03-fc2fdf985dca.png">
![image](https://user-images.githubusercontent.com/75008413/200661456-f31b4f02-89c5-4bab-8422-5c8364afd143.png)

No separator showing, and no mode background showing.
 
For example, gruvbox has this defined:
```
"ui.statusline.normal" = { fg = "fg1", bg = "bg2" }
"ui.statusline.insert" = { fg = "fg1", bg = "blue0" }
"ui.statusline.select" = { fg = "fg1", bg = "orange0" }
"ui.statusline.inactive" = { fg = "fg4", bg = "bg1" }
```

But it's not an issue with this theme. It is the same with any other theme, or with the stock one without any config.

Also tried different separators.

I could swear the mode colors used to work some time ago, but I tested quickly with latest release and have the same issue.

### Platform

macOS 12.6.1

### Terminal Emulator

kitty 0.26.5

### Helix Version

22.08.1-401-g188aff05

**Comment by the-mikedavis** [comment]
For color-modes, you have to set the `editor.color-modes` option to `true`.

For the separator, `editor.statusline.separator` controls which character is used as a separator. Then the `"separator"` statusline element can be added wherever you like, for example:

```toml
[editor.statusline]
left = ["mode", "separator", "spinner"]
```

**Comment by dahmc** [comment]
@the-mikedavis Thanks a lot for the explanation, that wasn't clear for me.

Works like a charm now!
