### ISSUE TITLE
Rust's new let else statement breaks indentation

### ISSUE THREAD

**Issue by AlexNomadrg** [helix-editor/helix#4665]
### Summary

It seems like the new `let else` statement breaks line indentation in helix

Video demonstrating the issue: https://youtu.be/g8-J9skWjqI

### Reproduction Steps

 

I tried this:

1. `hx`

I expected this to happen:

Instead, this happened:

### Helix log
<details><summary>~/.cache/helix/helix.log</summary>

```
2022-11-09T02:16:27.405 helix_view::editor [ERROR] Failed to initialize the LSP for `source.toml` { cannot find binary path }
2022-11-09T02:17:01.071 helix_view::editor [ERROR] Failed to initialize the LSP for `source.toml` { cannot find binary path }
```

</details>

### Platform

Linux

### Terminal Emulator

kitty 0.26.4

### Helix Version

helix 22.08.1

**Comment by the-mikedavis** [comment]
This was recently added upstream so we just need to update tree-sitter-rust https://github.com/tree-sitter/tree-sitter-rust/pull/162

**Comment by archseer** [comment]
Closed by https://github.com/helix-editor/helix/pull/4717
