### ISSUE TITLE
Golang:  The prompt information of the function and the prompt information of the parameter conflict

### ISSUE THREAD

**Issue by wanglong001** [helix-editor/helix#4669]
![image](https://user-images.githubusercontent.com/14817376/200722059-291c5811-5951-487a-9fe3-8da16ea15880.png)

**It even obscures what is typed**

It can be done a little more humane：
When entering parameters, you can remove the prompt information of the function,
When you enter comma, the function prompt information will come out again

This can be better to use, hope to improve this user experience

**Comment by archseer** [comment]
This is because there's no space above. We display one above and one below if possible

**Comment by pascalkuthe** [comment]
Closing in favor of #5827
