### ISSUE TITLE
Open folders cause errors

### ISSUE THREAD

**Issue by eleijonmarck** [helix-editor/helix#47]
I would like to navigate the directory, sort of like NERDTree in vim.

Is this possible?
Also is it possible to open folder?

I run:
```
❯ ~/Downloads/helix-v0.0.7-x86_64-linux/hx .
```

To open the current folder and its files. But i get:

```
❯ ~/Downloads/helix-v0.0.7-x86_64-linux/hx .
Error: unable to create new appliction

Caused by:
    Is a directory (os error 21)
```

**Comment by kevinsjoberg** [comment]
`hx` will be in the context of the current directory by default, so I don't believe the `.` is necessary. To my knowledge, there's no built-in file browser as of yet. You can navigate within the current folder using `<space>f` though.

**Comment by eleijonmarck** [comment]
i see. It looks as though it only open one file.

Good to get the shortcuts in place.

**Comment by wojciechkepka** [comment]
I think it would still be wortth it to support opening other directories. It could enter the file_viewer with root set to the directory specified by user if the argument is a directory. Now it errors out:
❯ hx /tmp/
Error: unable to create new appliction

Caused by:
    Is a directory (os error 21)

**Comment by kevinsjoberg** [comment]
@wojciechkepka are you proposing that running `hx .` would open the editor, with the file picker open? E.g., something like this:

<img width="2672" alt="Screenshot 2021-06-02 at 12 12 37" src="https://user-images.githubusercontent.com/503025/120463073-d375ec00-c39b-11eb-83e9-f8842f4d2c65.png">

I kind of like that idea, but it should probably be its own issue. 🙂

**Comment by wojciechkepka** [comment]
Thats indeed what I'm suggesting, and the root of the picker should be set to the directory that the user invoked `hx` with.

**Comment by wojciechkepka** [comment]
I opened #51 to track this feature.
