### ISSUE TITLE
Outdated typescript grammar

### ISSUE THREAD

**Issue by gabydd** [helix-editor/helix#4702]
The current typescript grammar is missing some fixes that are available on the latest grammar. Specifically template literal types had some issues being parsed that messed with highlighting that was fixed in: [https://github.com/tree-sitter/tree-sitter-typescript/pull/188](https://github.com/tree-sitter/tree-sitter-typescript/pull/188).

I will create a pr for this (already have it fixed in a local branch) but I was wondering what are the guidelines for upgrading grammar? Should I update to the latest master or only to the commit that fixes the template literal type highlighting problem I had?

**Comment by kirawi** [comment]
You can update to the latest stable commit, which seems to be 082da44a5263599186dadafd2c974c19f3a73d28

**Comment by gabydd** [comment]
Thanks @kirawi this issue is resolved with #4703
