### ISSUE TITLE
Crash when continuing down a partially filled completion window

### ISSUE THREAD

**Issue by luctius** [helix-editor/helix#472]
Using master (585d6f8)

[Asciinema video](https://asciinema.org/a/BFCo0dXVZGhy9Dta5ODRTUQBs)

thread 'main' panicked at 'index out of bounds: the len is 11 but the index is 11', helix-tui/src/widgets/table.rs:356:44
stack backtrace:
   0:     0x55679ad675e0 - std::backtrace_rs::backtrace::libunwind::trace::ha5edb8ba5c6b7a6c
                               at /rustc/53cb7b09b00cbea8754ffb78e7e3cb521cb8af4b/library/std/src/../../backtrace/src/backtrace/libunwind.rs:90:5
   1:     0x55679ad675e0 - std::backtrace_rs::backtrace::trace_unsynchronized::h0de86d320a827db2
                               at /rustc/53cb7b09b00cbea8754ffb78e7e3cb521cb8af4b/library/std/src/../../backtrace/src/backtrace/mod.rs:66:5
   2:     0x55679ad675e0 - std::sys_common::backtrace::_print_fmt::h97b9ad6f0a1380ff
                               at /rustc/53cb7b09b00cbea8754ffb78e7e3cb521cb8af4b/library/std/src/sys_common/backtrace.rs:67:5
   3:     0x55679ad675e0 - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::h14be7eb08f97fe80
                               at /rustc/53cb7b09b00cbea8754ffb78e7e3cb521cb8af4b/library/std/src/sys_common/backtrace.rs:46:22
   4:     0x55679ad8e06f - core::fmt::write::h2ca8877d3e0e52de
                               at /rustc/53cb7b09b00cbea8754ffb78e7e3cb521cb8af4b/library/core/src/fmt/mod.rs:1094:17
   5:     0x55679ad62935 - std::io::Write::write_fmt::h64f5987220b618f4
                               at /rustc/53cb7b09b00cbea8754ffb78e7e3cb521cb8af4b/library/std/src/io/mod.rs:1584:15
   6:     0x55679ad698eb - std::sys_common::backtrace::_print::h7f1a4097308f2e0a
                               at /rustc/53cb7b09b00cbea8754ffb78e7e3cb521cb8af4b/library/std/src/sys_common/backtrace.rs:49:5
   7:     0x55679ad698eb - std::sys_common::backtrace::print::h1f799fc2ca7f5035
                               at /rustc/53cb7b09b00cbea8754ffb78e7e3cb521cb8af4b/library/std/src/sys_common/backtrace.rs:36:9
   8:     0x55679ad698eb - std::panicking::default_hook::{{closure}}::hf38436e8a3ce1071
                               at /rustc/53cb7b09b00cbea8754ffb78e7e3cb521cb8af4b/library/std/src/panicking.rs:208:50
   9:     0x55679ad693bd - std::panicking::default_hook::he2f8f3fae11ed1dd
                               at /rustc/53cb7b09b00cbea8754ffb78e7e3cb521cb8af4b/library/std/src/panicking.rs:225:9
  10:     0x55679a94498c - helix_term::application::Application::run::{{closure}}::{{closure}}::hf0d2a83f3742784e
  11:     0x55679ad69f20 - std::panicking::rust_panic_with_hook::h79a18548bd90c7d4
                               at /rustc/53cb7b09b00cbea8754ffb78e7e3cb521cb8af4b/library/std/src/panicking.rs:595:17
  12:     0x55679ad69a97 - std::panicking::begin_panic_handler::{{closure}}::h212a72cc08e25126
                               at /rustc/53cb7b09b00cbea8754ffb78e7e3cb521cb8af4b/library/std/src/panicking.rs:497:13
  13:     0x55679ad67a7c - std::sys_common::backtrace::__rust_end_short_backtrace::hbd6897dd42bc0fcd
                               at /rustc/53cb7b09b00cbea8754ffb78e7e3cb521cb8af4b/library/std/src/sys_common/backtrace.rs:141:18
  14:     0x55679ad699f9 - rust_begin_unwind
                               at /rustc/53cb7b09b00cbea8754ffb78e7e3cb521cb8af4b/library/std/src/panicking.rs:493:5
  15:     0x55679a91a201 - core::panicking::panic_fmt::h77ecd04e9b1dd84d
                               at /rustc/53cb7b09b00cbea8754ffb78e7e3cb521cb8af4b/library/core/src/panicking.rs:92:14
  16:     0x55679a91a1c2 - core::panicking::panic_bounds_check::hab5cb3227e3c0b2e
                               at /rustc/53cb7b09b00cbea8754ffb78e7e3cb521cb8af4b/library/core/src/panicking.rs:69:5
  17:     0x55679aab23ef - helix_tui::widgets::table::Table::render_table::h1631635f730c8152
  18:     0x55679a9fe652 - <helix_term::ui::menu::Menu<T> as helix_term::compositor::Component>::render::h6a3ce9ac1f725063
  19:     0x55679aa5d472 - <helix_term::ui::completion::Completion as helix_term::compositor::Component>::render::h1162e55dcc6fe83d
  20:     0x55679aa0a764 - helix_term::compositor::Compositor::render::ha015045ef032ca56
  21:     0x55679aa0a403 - helix_term::application::Application::handle_terminal_events::hf937f8c4490d8bcb
  22:     0x55679a94b53d - <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll::h938af37a7e1a22b0
  23:     0x55679a95171a - tokio::runtime::enter::Enter::block_on::h697bbfb6477f2ca7
  24:     0x55679a934a22 - tokio::runtime::Runtime::block_on::hdba2ee36e6a16787
  25:     0x55679a92d05c - hx::main::h8d894075ec5d63a1
  26:     0x55679a929703 - std::sys_common::backtrace::__rust_begin_short_backtrace::h772509547d080544
  27:     0x55679a92d1ad - std::rt::lang_start::{{closure}}::h878cb162e366272b
  28:     0x55679ad6a2fa - core::ops::function::impls::<impl core::ops::function::FnOnce<A> for &F>::call_once::hc4354216bf39217c
                               at /rustc/53cb7b09b00cbea8754ffb78e7e3cb521cb8af4b/library/core/src/ops/function.rs:259:13
  29:     0x55679ad6a2fa - std::panicking::try::do_call::hb68eb312780385cf
                               at /rustc/53cb7b09b00cbea8754ffb78e7e3cb521cb8af4b/library/std/src/panicking.rs:379:40
  30:     0x55679ad6a2fa - std::panicking::try::h22b8e08595060b8b
                               at /rustc/53cb7b09b00cbea8754ffb78e7e3cb521cb8af4b/library/std/src/panicking.rs:343:19
  31:     0x55679ad6a2fa - std::panic::catch_unwind::hc64f1a6a0e71b1fc
                               at /rustc/53cb7b09b00cbea8754ffb78e7e3cb521cb8af4b/library/std/src/panic.rs:431:14
  32:     0x55679ad6a2fa - std::rt::lang_start_internal::h4461fc58637f04f8
                               at /rustc/53cb7b09b00cbea8754ffb78e7e3cb521cb8af4b/library/std/src/rt.rs:34:21
  33:     0x55679a92d192 - main
  34:     0x7facb09c6565 - __libc_start_main
  35:     0x55679a91a99e - _start
  36:                0x0 - <unknown>

**Comment by kirawi** [comment]
Can you try running it with a debug version of Helix?

**Comment by archseer** [comment]
Both move_up/down use the full options length instead of the filtered matches len: https://github.com/helix-editor/helix/blob/17f9dfce7ef3e1cfffe58979d78e42cceec5918d/helix-term/src/ui/menu.rs#L91-L102

Should be a quick fix
