### ISSUE TITLE
Enhancement: add keyboard shortcut to close buffer from buffer picker

### ISSUE THREAD

**Issue by lukepighetti** [helix-editor/helix#4730]
When there are multiple buffers open, if you type `space b` you are shown a list of buffers. From this window, it would be nice to have a keyboard shortcut to close a buffer. 

Currently you have to open the buffer and type `:bc` and then `space b` again

**Comment by the-mikedavis** [comment]
Duplicate of https://github.com/helix-editor/helix/issues/1593
