### ISSUE TITLE
Uncommenting lines that are commented without a space deletes an extra character

### ISSUE THREAD

**Issue by Omnikar** [helix-editor/helix#474]
### Reproduction steps
1. Comment a line of code without a space after the comment token, e.g., `//comment`.
2. Use the `C-c` shortcut to uncomment the line.
3. An extra character is deleted, causing the line to become `omment`.

**Comment by archseer** [comment]
There's a TODO for this in the code: https://github.com/helix-editor/helix/blob/17f9dfce7ef3e1cfffe58979d78e42cceec5918d/helix-core/src/comment.rs#L68

**Comment by Omnikar** [comment]
Hm, I wonder if I could try and implement this and open a PR?
