### ISSUE TITLE
Typo In Docs

### ISSUE THREAD

**Issue by bcatalfo** [helix-editor/helix#4749]
According to the docs

> Helix also needs it's runtime files so make sure to copy/symlink the runtime/ directory into the config directory (for example ~/.config/helix/runtime on Linux/macOS). 

"it's" is a contraction of "it is", this should be "its" instead.

**Comment by the-mikedavis** [comment]
Good catch, please submit a PR!

**Comment by Stonks3141** [comment]
This was fixed in #4165 but doesn't seem to be on the website yet.

**Comment by the-mikedavis** [comment]
Ah yep this was fixed. https://docs.helix-editor.com/master/install.html is the link to the docs for master where this is fixed, https://docs.helix-editor.com/install.html shows the docs for the latest release
