### ISSUE TITLE
`ayu`-Themes cursor has the same color as selection

### ISSUE THREAD

**Issue by philipgiuliani** [helix-editor/helix#4754]
I've just installed the `helix` master branch and noticed that the cursor in the `ayu`-Themes have the same color as the text/background in the selection mode. This causes the cursor to get invisible.

## Master (Commit 652497bdd613d2854f63a1e99e9625a21a007389)
Cursor on `,`: 
![Screenshot 2022-11-15 at 09 28 08](https://user-images.githubusercontent.com/5446019/201868865-be9253b5-40e4-4762-bc63-498d51423613.png)

Cursor after the `,`:
![Screenshot 2022-11-15 at 09 28 15](https://user-images.githubusercontent.com/5446019/201868899-d26c627f-7231-4112-9a4e-5c328c4034f0.png)

## Version 22.8.1
In the previous version, the cursor was always visible with the orange background:
![Screenshot 2022-11-15 at 09 32 05](https://user-images.githubusercontent.com/5446019/201869321-520b8773-2440-4622-a486-d2e082bd2447.png)

**Comment by philipgiuliani** [comment]
@enkodr I saw you have recently updated the ayu themes: https://github.com/helix-editor/helix/pull/4662

You have any idea how to change this? ☺️

**Comment by enkodr** [comment]
I've introduced this change `"ui.cursor" = { modifiers = ["reversed"] }` that introduced this.

A new [PR](https://github.com/helix-editor/helix/pull/4764) to fix this was created.

**Comment by pascalkuthe** [comment]
closing as this was fixed by #4764
