### ISSUE TITLE
Fix flaky write integration tests

### ISSUE THREAD

**Issue by dead10ck** [helix-editor/helix#4763]
_Originally reported by @dxtr85 in https://github.com/helix-editor/helix/issues/4758#issuecomment-1315412309_

There are some issues with the write failure tests failing to set an error status during integration tests. We should figure out how to make this more reliable. @archseer thinks it's a timing related issue. Examples:

* https://github.com/helix-editor/helix/actions/runs/3466655272/jobs/5790735329
* https://github.com/helix-editor/helix/actions/runs/3465015319/jobs/5787247568

**Comment by pascalkuthe** [comment]
Is this still a problem?

**Comment by dead10ck** [comment]
Not that I'm aware of. I'll close and we can reopen if it comes up again.
