### ISSUE TITLE
Different cursor types in different modes

### ISSUE THREAD

**Issue by mWalrus** [helix-editor/helix#477]
I would like to have an underline cursor in insert mode. Is there a way to do this? I have looked through the documentation and tried around in the config file but i can't find anything that works.

**Comment by sudormrfbin** [comment]
Previous discussion here: #323

**Comment by cessen** [comment]
Looks like a duplicate, then, right?

**Comment by pickfire** [comment]
It is possible to change it through code right but a bit buggy which is why we didn't do it.
