### ISSUE TITLE
Helix crash with :reflow on some file

### ISSUE THREAD

**Issue by nakrule** [helix-editor/helix#4775]
### Summary

Helix crash when I use `:reflow 100` on a whole markdown file (all lines selected in visual mode).

Error:

```
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Line index out of bounds: line index 50, Rope/RopeSlice line count 42', /Users/brew/Library/Caches/Homebrew/cargo_cache/registry/src/github.com-1ecc6299db9ec823/ropey-1.5.0/src/slice.rs:424:41
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

This does not happend with every files I tried. I included a download link to one that will reproduce the bug.

### Reproduction Steps

I tried this:

1. Download the following file: https://pastebin.com/e3Ryjrrw 
2. Open the file with Helix 
3. Select all lines with `gg` and then `vge`
4. Use `:reflow 100`
5. helix crash

### Platform

macOS

### Terminal Emulator

iTerm

### Helix Version

helix 22.08.1 (66276ce6)

**Comment by David-Else** [comment]
Your file works on the master branch using Linux, could you try and compile from master and see if it is fixed for you?

**Comment by zen3ger** [comment]
Not the author, but I did the repro tests on `helix 22.08.1 (0e23e4f8)` and I did not observed the crash.

**Comment by the-mikedavis** [comment]
This was fixed in https://github.com/helix-editor/helix/pull/3733
