### ISSUE TITLE
Line wrapping in Markdown and code files

### ISSUE THREAD

**Issue by tahir-hassan** [helix-editor/helix#4788]
Hi, 

how do I have helix automatically break a line to be 80 characters in length or so (without selecting a line and doing `:reflow 80`)?

Also is there any option to soft-wrap lines or hard wrap lines automatically?  Is this being planned in a future release?

How does one edit markdown files?

**Comment by archseer** [comment]
https://github.com/helix-editor/helix/issues/136 https://github.com/helix-editor/helix/issues/2274

**Comment by tahir-hassan** [comment]
Yeah, looking at the documentation, the closest I have got to is using `mip` to select the paragraph I am on, and then doing `:reflow`, but then this is a hard-wrap.

**Comment by dam5h** [comment]
I took a look at these other 2 issues, it appears that one would need soft wrap to sanely edit markdown.  Or is there a workaround via config that can leverage the 2 space rule in markdown to make editing markdown a little easier?
