### ISSUE TITLE
Failed to initialize logging on read-only HOME

### ISSUE THREAD

**Issue by mennthor** [helix-editor/helix#48]
I'm on Debian Jessie but the `HOME` is read-only atm.
So I set `CARGO_HOME` to a writable location and installed helix from source as specified in the README.
The `runtime` folder was copied to `$CARGO_HOME/bin`.
I tested this setup on another machine (OSX) with writable home and it works properly there.
On the Debian however, I get
```
Error: failed to initialize logging

Caused by:
    Read-only file system (os error 30)
```
when starting `hx`.

**Comment by archseer** [comment]
Good point, we should probably log into `config_dir()` (usually `~/.config/helix`)

https://github.com/helix-editor/helix/blob/c67e31830dda2858d9e4728387920b13eb5a01e4/helix-core/src/lib.rs#L59-L66

**Comment by wojciechkepka** [comment]
Changing the path to `config_dir` still doesn't resolve the issue of `$HOME` being read-only. I'm wondering if perhaps the result of  `setup_logging` should be ignored so users can still operate without the logging mechanism?

**Comment by archseer** [comment]
I reopened this since it doesn't fully resolve your issue; is `~/.config/``~/.local/` etc. completely unwritable? I find that a bit surprising.

**Comment by pickfire** [comment]
The weirdest thing I find is it logs (at first to home, then to ~/.config which it shouldn't) by default, I thought log should be opt-in? If not we can just log to /tmp right?

**Comment by mennthor** [comment]
Is `config_dir` settable via ENVVAR? Then I could choose a suitable path myself.
And yes, all of `~` is read-only atm (I had to reroute basically all settings, vim, pip, jupyter, etc.).

**Comment by pickfire** [comment]
What if we do like `-u <config>` or `-u none`? `none` to disable config.

**Comment by cp9ev** [comment]
it's just the log function, we shouldn't just disable the config. Maybe we can make it /tmp by default  or  spare, and when the log file unwriteable , the editor should be useable, and  don't  forget the warning info

**Comment by archseer** [comment]
We follow the [XDG specification](https://specifications.freedesktop.org/basedir-spec/basedir-spec-latest.html) on Linux/macOS, so if you set `XDG_CACHE_HOME` it'll look for a `helix` folder there. I think that should be the preferred solution, since that way you're able to fix all applications that rely on XDG.

I think we don't need a separate flag to disable this because we'll be leveraging the cache even more in the future (to store :command history, /search history, persist undo states & document positions across restarts etc)

**Comment by mennthor** [comment]
> We follow the [XDG specification](https://specifications.freedesktop.org/basedir-spec/basedir-spec-latest.html) on Linux/macOS, so if you set `XDG_CACHE_HOME` it'll look for a `helix` folder there.

Not sure I get that correctly. I already have `XDG_CACHE_HOME`, `XDG_STATE_HOME` and `XDG_CACHE_HOME` set to writable and existing directories (and also added a `helix` folder in each, just to be sure), but the logging error is still there.
Am I overlooking a setting / flag I need to give at startup?

**Comment by archseer** [comment]
This is on the latest release (0.0.10), and the error is still "Read-only file system"? It's supposed to log to `XDG_CACHE_HOME/helix/helix.log` now.

**Comment by mennthor** [comment]
Sorry, that was my fault. It does indeed log to `XDG_CACHE_HOME/helix/helix.log` now.
Thanks :)

**Comment by pickfire** [comment]
@mennthor Ah, no. Thanks for sending in the issue request. It was only since 0.0.10 doing that but 0.0.9 doesn't have this.

**Comment by Siilwyn** [comment]
Maybe it would be nice to use the new [`XDG_STATE_HOME`](https://specifications.freedesktop.org/basedir-spec/latest/ar01s03.html) for this.
