### ISSUE TITLE
Add an empty `rustfmt.toml` to the project root

### ISSUE THREAD

**Issue by Omnikar** [helix-editor/helix#480]
I think the fact that the project uses the default settings of rustfmt should be explicitly indicated by having an empty `rustfmt.toml` file in the project root. This also ensures that if someone has an alternate rustfmt configuration in their home directory, it is overridden while they work on Helix.

**Comment by pickfire** [comment]
So it wouldn't be overridden if helix have an empty rustfmt.toml?

**Comment by archseer** [comment]
This is standard practice: https://www.reddit.com/r/rust/comments/9jl6a9/pro_tip_if_you_use_cargo_fmtrustfmt_use_a/

I agree it should be added.
