### ISSUE TITLE
Cannot save to non existing file

### ISSUE THREAD

**Issue by gbaranski** [helix-editor/helix#481]
### Reproduction steps

 
[![asciicast](https://asciinema.org/a/WtSoq6ROqdIh1utF0SRKnxqum.svg)](https://asciinema.org/a/WtSoq6ROqdIh1utF0SRKnxqum)

1. Run `hx` on non existing file, e.g `hx /tmp/some-new-file`
2. Type random text
3. Try to save
4. `cannot write a buffer without a filename` error is received

In my opinion it should be done like in vim/neovim, where file gets created while saving if it didn't exist

### Environment

- Platform: Linux
- Helix version: 0.3.0

<details><summary>~/.cache/helix/helix.log</summary>
Nothing interesting found in the logs(ran with TRACE log level)
</details>

**Comment by gbaranski** [comment]
nevermind, that's already fixed on `master`

**Comment by pickfire** [comment]
@archseer Should we do a patch release for this fix?
