### ISSUE TITLE
Extend how to do key remapping in the docs, in particular how to do keybindings for the minor modes

### ISSUE THREAD

**Issue by Kenneth-Mata** [helix-editor/helix#4811]
i tried a few combinations to bind  ``space space`` to 'write' without much success, also ,in some parts around the issues here there's space.ret, while in others and the docs it mentions enclosing especial keys in " ".

**Comment by divarvel** [comment]
This was improved a bit in https://github.com/helix-editor/helix/pull/5552 (an explicit note in the "key remapping" page. I can also do that in the "keymap" page, in the minor modes paragraphs.
