### ISSUE TITLE
LSP not looking for the right binary name for omnisharp (Linux)

### ISSUE THREAD

**Issue by Nellousan** [helix-editor/helix#4812]
Helix version: 22.08.1
OS: EndeavourOS (Arch based)

Hello,

When using Helix for C#, it looks for a binary named `OmniSharp` in the `$PATH`. But when installing OmniSharp on linux (idk for windows), the binary is more commonly named `omnisharp` (without capitals), so Helix isn't able to find it after installation. (Edit: Just to be clear, `omnisharp` was indeed in my $PATH  after installation from the package manager.)

It took me a while to understand that the `Configured language server:` field when doing `hx --health` is not only the name of the configured LSP server but also the exact name of the executable Helix is looking for. The problem is solved by making a simple symlink but it took me some time to figure out the solution.

I don't know if it is intentional or not(maybe on windows the omnisharp binary is capitalized idk) but this could be improved i think.

(first issue here sorry if i did anything wrong)

**Comment by archseer** [comment]
https://github.com/helix-editor/helix/issues/4645

Wiki was recently updated with new instructions

**Comment by hellodhruvin** [comment]
Where exactly do I find the OmniSharp.dll file?

![image](https://user-images.githubusercontent.com/108544119/207256076-fc1b16b4-6aa1-4c57-bb31-1ab56cae255a.png)

/usr/bin/omnisharp executes Omnisharp.exe with mono.

How would it be possible to setup omnisharp with helix?

Os: Arch Linux
Package: [omnisharp-roslyn-bin](https://aur.archlinux.org/packages/omnisharp-roslyn-bin)

**Comment by Nellousan** [comment]
I fixed it by making a symlink `/usr/bin/OmniSharp` pointing to `/usr/bin/omnisharp`, but you should be able to fix it [via the config file](https://github.com/helix-editor/helix/wiki/How-to-install-the-default-language-servers#omnisharp).

It is not specified on the wiki how to fix for linux specifically but **i assume** something that looks like this should work:
```
[[language]]
name = "c-sharp"
language-server.command = "omnisharp"
```

**Comment by hellodhruvin** [comment]
I tried that method as the first thing because on running fd I knew which
file it should be. On doing ps -ef I also found that the process is running
but I get no autocomplete and even when I quit helix it says waiting for
lsp to shutdown or something. Let me know what log files and stuff do I
need and how to obtain them.
