### ISSUE TITLE
Bad language config: invalid type: map, expected a string for key `language.file-types` 

### ISSUE THREAD

**Issue by kalidzo** [helix-editor/helix#4814]
### Summary

I found a bug in the 1079th line.

### Reproduction Steps

 

I tried this:

1. `hx`

I expected this to happen:

Instead, this happened:

### Helix log

<details><summary>~/.cache/helix/helix.log</summary>

```
please provide a copy of `~/.cache/helix/helix.log` here if possible, you may need to redact some of the lines
```

</details>

### Platform

Arch linux

### Terminal Emulator

fish

### Helix Version

22.08.1

**Comment by archseer** [comment]
You're using an older version of the editor, `languages.toml` on `master`works fine with the code on `master`.

**Comment by the-mikedavis** [comment]
Duplicate of https://github.com/helix-editor/helix/issues/4516

**Comment by kalidzo** [comment]
oh, sorry)
