### ISSUE TITLE
Widen criteria for "jumps"

### ISSUE THREAD

**Issue by seanwarman** [helix-editor/helix#4815]
Many movements aren't considered "jumps". For example "]<ch>" movements or pressing "%" to select the whole file.

After these commands I'd expect to be able to jump the cursor back to my previous position (which is closer to Vim's functionality).

I would even argue to define more movements as jumps than Vim does. For example cursor movements that include counts like "20k" or "3w", could actually be really useful.

**Comment by the-mikedavis** [comment]
You can accomplish this manually by using `C-s`, or automatically by changing any command you want to add a jumplist entry to include the `push_selection` command. For example:

```toml
# ~/.config/helix/config.toml
[keys.normal]
"%" = ["select_all", "push_selection"]
```

The jumplist is meant to be a replacement for https://github.com/helix-editor/helix/issues/1596

**Comment by seanwarman** [comment]
That's brilliant! Thanks.

**Comment by seanwarman** [comment]
In the version of helix I have I had to replace `"push_selection"` for `"save_selection"` for this to work.

```toml
# ~/.config/helix/config.toml
[keys.normal]
"%" = ["select_all", "save_selection"]
```

**Comment by thomasschafer** [comment]
I know this is a closed issue, but I find myself also wanting more movements to push to the jumplist, such as pretty much any commands prefixed with `m` or `[`/`]`. Would we consider adding a config option to widen the jump criteria in this way? The alternative seems to be to add a massive number of keymaps to my config which just add `save_selection` alongside the existing command, but I would imagine that sufficiently many people would prefer a widened criteria (more similar to that of vim) to make it a desirable feature to add.
