### ISSUE TITLE
Odd behaviour + panic when using forward delete key at the end of a file

### ISSUE THREAD

**Issue by Omnikar** [helix-editor/helix#482]
### Reproduction steps
1. Enter insert mode at the very end of a file.
2. Press the forward delete key. The cursor becomes invisible.
3. Exit insert mode.
4. Press `d`. Helix panics and crashes.
Additional note: If, after exiting insert mode, you move the cursor up one line, it will no longer be allowed to move to the last line. However, you can access the last line again by deleting the line break before it. From here, moving the cursor to the very end and pressing `d` will cause the panic.

**Comment by Omnikar** [comment]
I feel like this might be because the forward delete key is deleting the line break at the end of the file?

**Comment by kirawi** [comment]
@cessen Probably fixed in #376

**Comment by cessen** [comment]
> @cessen Probably fixed in #376 

Yup, just tested.  It's fixed in #376.

**Comment by archseer** [comment]
Resolved by #376
