### ISSUE TITLE
vls lang server not working correctly, html autocomplete inside vue files not working

### ISSUE THREAD

**Issue by cpt-n3mo** [helix-editor/helix#4820]
it seems that comments and auto complete are not working properly inside vue files

comments are prepended  with `//` inside html  template
html tags are not auto completing at all 

inside script tag autocomplete seems to be working..

not sure if this is a bug or if this is a setting or something else.

kind regards.

**Comment by the-mikedavis** [comment]
> comments are prepended with // inside html template

Comments are done by helix and not the language server. Block comment support will be needed to do this #1505

> html tags are not auto completing at all

HTML tags are most likely driven through LSP snippets which we don't implement / enable yet #395
