### ISSUE TITLE
Diff buffer support

### ISSUE THREAD

**Issue by seanwarman** [helix-editor/helix#4826]
Yes please!

Note, this isn't a request to simply see `git diff` output in a buffer (which I'm guessing you can probably already do) but to diff any buffer against any other buffer and see the diff colours update as you edit them.

This feature (`:diffthis`) is really useful in Vim for comparing arbitrary data, for example if you've got a huge log output and you want to compare it with another one in detail.

**Comment by archseer** [comment]
This is https://github.com/helix-editor/helix/issues/405 but the issue had a hard to find name.
