### ISSUE TITLE
rust-analyzer magic completions not working in helix

### ISSUE THREAD

**Issue by itaseskii** [helix-editor/helix#4831]
Hello,

I'm trying to start using helix as my default editor when programming with Rust but unfortunately some of the auto completion features are not working as expected.

Going by the following rust-analyzer manual https://rust-analyzer.github.io/manual.html#magic-completions the rust-analyzer should be able to autocomplete functions with `()`, generic types with `<>` and allow for postfix completions i.e `expr.match → match expr {}`.

Executing `hx --health rust` the setup seems fine.

```
Configured language server: rust-analyzer
Binary for language server: /home/itaseski/.local/bin/rust-analyzer
Configured debug adapter: lldb-vscode
Binary for debug adapter: Not found in $PATH
Highlight queries: ✓
Textobject queries: ✓
Indent queries: ✓

```

Is this a missing feature, bug or issue with my own environment? If needed, I'm happy to provide a fix with some initial guidance.

Environment:
Linux Debian "bullseye" 11
Helix Editor 22.08.1
rust-analyzer latest

Regards, Ivica.

**Comment by the-mikedavis** [comment]
These are done with LSP snippets which are not yet implemented (though there's some ongoing work) https://github.com/helix-editor/helix/issues/395. I'll close in favor of that issue

**Comment by itaseskii** [comment]
Hey @the-mikedavis are snippets also needed for basic autocompletion of functions and generics using `()` and `<>` respectively?

**Comment by the-mikedavis** [comment]
Yep, those are snippets as well. Snippets allow you to specify where exactly the cursor should move to. Non-snippet completion items are basically a chunk of text to insert and then the cursor goes at the end.
