### ISSUE TITLE
File picker recurses to parent folders on second opening in git-based projects

### ISSUE THREAD

**Issue by aral** [helix-editor/helix#4835]
### Summary

If I launch Helix Editor on a subfolder of a git-based project, _the second time_ open the file picker, it erroneously shows me files not just from that subfolder (and its subfolders) but also from its parent folders, all the way up to the git root.

### Reproduction Steps

1. Create a folder called _test_ and a subfolder inside it called _subfolder_. Create a text file called _in-test-folder.txt_ in the _test_ folder and _in-subfolder.txt_ in _subfolder_ as shown below:

    ![Screenshot from 2022-11-21 12-03-08](https://user-images.githubusercontent.com/41798/203049238-f983024a-51de-4b70-ac13-2cacf0c5f951.png)

2. Enter the subfolder and launch Helix from there (`cd subfolder && hx .`) 

    Note the File Picker appears and, correctly, shows you only the contents of the subfolder as shown below:

    ![Screenshot from 2022-11-21 12-01-41](https://user-images.githubusercontent.com/41798/203050127-fd6cb0f2-74c6-4d83-8094-76ae5756ca21.png)

3. Press <kbd>esc</kbd> to close the File Picker and then <kbd>space</kbd> <kbd>f</kbd> to re-open it a second time.

    Note the File Picker appears and, correctly, shows you only the contents of the subfolder as shown below:

4. Now quit Helix editor and switch back to the parent `test` folder and initialise a git repository there: `git init`. Your project should now look something like this:

    ![Screenshot from 2022-11-21 12-03-31](https://user-images.githubusercontent.com/41798/203051195-a052ec09-67cc-4d31-b10d-b23f5431741b.png)

5. Enter the subfolder and launch Helix from there again (`cd subfolder && hx .`) 

    Note the File Picker appears and, correctly, shows you only the contents of the subfolder as shown below:

![Screenshot from 2022-11-21 12-01-41](https://user-images.githubusercontent.com/41798/203050127-fd6cb0f2-74c6-4d83-8094-76ae5756ca21.png)

6. Press <kbd>esc</kbd> to close the File Picker and then <kbd>space</kbd> <kbd>f</kbd> to re-open it a second time.

## What should happen:

The File Picker should show only the contents of the subfolder, as before.

![Screenshot from 2022-11-21 12-01-41](https://user-images.githubusercontent.com/41798/203050127-fd6cb0f2-74c6-4d83-8094-76ae5756ca21.png)

## What actually happens:

The File Picker shows the contents of the subfolder and its parent folder(s), all the way up to the git root (in this case, just one level and one extra file. In real-world scenarios, it can be the difference between seeing a hanful of files and, possibles, tens or hundreds of thousands of them and it makes working with the File Picker very difficult in those cases).

![Screenshot from 2022-11-21 12-02-01](https://user-images.githubusercontent.com/41798/203051070-2939c2b4-1bca-43e0-afe0-96693de976de.png)

### Helix log

<details><summary>~/.cache/helix/helix.log</summary>

```
No relevant log entries found.
```

</details>

### Platform

Linux (Fedora Silverblue 37)

### Terminal Emulator

Black Box

### Helix Version

helix 22.08.1 (0b2bb061)

**Comment by pascalkuthe** [comment]
Closing this as the behaviour is intended
