### ISSUE TITLE
[easily reproductable] `hx $(hx hello.txt)` cause ICE

### ISSUE THREAD

**Issue by AndyJado** [helix-editor/helix#4836]
### Summary

a accident where <Ctlr-c> won't work, caused seesion lock dead I guess?

really trivial to reproduce!!

### Reproduction Steps

 

```sh
mkdir temp-dir && cd temp-dir

echo 'a bug report' > bug.txt

hx $(hx bug.txt)
```

### Platform

macOS

### Terminal Emulator

alacritty

### Helix Version

helix 22.08.1 (66276ce6)

**Comment by archseer** [comment]
ICE = internal compiler error. I think you mean a freeze or a deadlock. You're spawning an interactive helix instance as a part of input, so yeah this freezes, awaiting for process termination.
