### ISSUE TITLE
Panic when pressing PrintScreen key

### ISSUE THREAD

**Issue by Dopplerian** [helix-editor/helix#4838]
### Summary

Editor just crashes when I press the PrintScreen key.

I've tried this with other terminal emulators and it only seems to happen with kitty.

### Reproduction Steps

 

I tried this:

1. `hx`
2. Pressing PrintScreen key

And it exits with this error message:

`thread 'main' panicked at 'internal error: entered unreachable code: Shouldn't get this key without enabling DISAMBIGUATE_ESCAPE_CODES in crossterm', helix-view/src/keyboard.rs:158:40`

### Platform

Linux

### Terminal Emulator

kitty 0.26.5

### Helix Version

helix 22.08.1

**Comment by the-mikedavis** [comment]
Duplicate of https://github.com/helix-editor/helix/issues/4125
