### ISSUE TITLE
Triple tick/quotes are autoclosed to 4

### ISSUE THREAD

**Issue by aalu1418** [helix-editor/helix#4839]
### Summary

This occurred while working with markdown, so I'm not sure if it also shows up in other file types. 

When trying to use three ticks ` for a code block in markdown, the third tick is treated as a pair and a 4th tick is automatically added. It's not a huge issue, just a UX thing where the user needs to remove the 4th tick.

### Reproduction Steps

I tried this:

1. Opened a markdown file
2. Tried to use three ticks `

I expected this to happen:
```
Expected: ```
```

Instead, this happened:
```
Actual: ````
```

### Platform

Linux

### Terminal Emulator

xterm-256color + zshell

### Helix Version

helix 22.08.1

**Comment by the-mikedavis** [comment]
This is because we only support single-character auto-pairing currently: https://github.com/helix-editor/helix/issues/4035. I will close this in favor of that issue
