### ISSUE TITLE
`:reload` command marks file as changed/unsaved

### ISSUE THREAD

**Issue by Omnikar** [helix-editor/helix#484]
Title is self explanatory; files are marked as edited/unsaved after using the `:reload` command.

**Comment by kirawi** [comment]
Note: It's possible to reload a file under a different encoding by first `:encoding` and then `:reload`. This needs to be accounted for.

**Comment by cessen** [comment]
Even if it's reloaded with a different encoding, I think the correct thing is to mark it as unedited.  It's not a modification of the on-disk text data, it's just a reinterpretation of it.
