### ISSUE TITLE
Write without formatting

### ISSUE THREAD

**Issue by lukepighetti** [helix-editor/helix#4853]
Would be nice to have a command palette item to write a file without auto formatting first.

Sometimes you need to edit a "hand crafted" file and need to skip formatting, but want auto-formatting to be the behavior 99.999% of the time.

**Comment by QiBaobin** [comment]
Before the change, you can use `:set-language text` before `:w` to disable auto formatting.

**Comment by pascalkuthe** [comment]
This doesn't require a separate command as mentioned in https://github.com/helix-editor/helix/pull/4909#issuecomment-1329848943 and by @QiBaobin. You can even bind this to a hotkey (and in the future to a typable command).

Therefore I am closing this issue

**Comment by janos-r** [comment]
I agree it would be useful. Just from a UX perspective. Something like wnf Write no format. Currently you have to set auto-format false, and than reenable. It's not so bad, but would be nice to have a dedicated command.
