### ISSUE TITLE
DLang support

### ISSUE THREAD

**Issue by AssertionBit** [helix-editor/helix#4868]
Hi there. While working with helix on my projects, I noticed, that there tons of language supports, but there is no support for [dlang](https://dlang.org). I was surprised, that there is no idea or something like that for this language. Maybe, we need to add it to default language support?

**Comment by AssertionBit** [comment]
I saw [this page. in wiki](https://docs.helix-editor.com/languages.html). I understand, that I may config it personally for myself, but just suggesting to include in default lang support.

**Comment by archseer** [comment]
It was merged in https://github.com/helix-editor/helix/pull/4372 but isn't available in a stable release yet
