### ISSUE TITLE
Search cannot be submitted when last character is `/`

### ISSUE THREAD

**Issue by Omnikar** [helix-editor/helix#487]
### Reproduction steps
1. Press `/` to enter search mode.
2. Type a search which ends with `/`.
3. Press enter. Search mode will not be exited.

**Comment by archseer** [comment]
You need to escape the `/` since it's a special regex character.

**Comment by archseer** [comment]
Hmm, escaping doesn't seem to work either. I'll need to do some testing locally

**Comment by archseer** [comment]
It's a side effect of the code that was added for file path completion, it would accept a directory completion on enter... 

https://github.com/helix-editor/helix/blob/25103833b2dc5d6edf1beca396fa838294fc114a/helix-term/src/ui/prompt.rs#L466-L468
