### ISSUE TITLE
Ctrl-i doesn't do anything with clangd

### ISSUE THREAD

**Issue by creikey** [helix-editor/helix#4874]
### Summary

The keymap says it should jump forward on the jumplist, but it doesn't

### Reproduction Steps

Type this into helix:
```c
int test() { return 5; }

int main() {
  test();
}
```

1. Put cursor over the call to test();
2. Type `gd`, cursor jumps to `test()`
3. Press `Ctrl-o`, cursor jumps back to the call to test correctly.
4. `Ctrl-i` now should jump forward again in the jump list but it doesn't

### Helix log

<details><summary>~/.cache/helix/helix.log</summary>

```
2022-11-23T23:09:20.549 helix_lsp::transport [ERROR] err <- "I[23:09:20.549] <-- textDocument/definition(28)\r\n"
2022-11-23T23:09:20.550 helix_lsp::transport [ERROR] err <- "I[23:09:20.549] --> reply:textDocument/definition(28) 0 ms\r\n"```

</details>


### Platform

Windows 11

### Terminal Emulator

Windows Terminal

### Helix Version

7e99087fa36fd49b350311ebdbc3b9338794746b

**Comment by archseer** [comment]
https://github.com/helix-editor/helix/issues/4864#issuecomment-1325598084

**Comment by creikey** [comment]
> [#4864 (comment)](https://github.com/helix-editor/helix/issues/4864#issuecomment-1325598084)

This would be very strange as the same example works fine with neovim

**Comment by CptPotato** [comment]
It indeed is very strange but I can confirm that <kbd>Ctrl</kbd><kbd>i</kbd> works in neovim regardless of my terminal emulator configuration. In helix I have to change the config according to the comment linked above.

It's possible that <kbd>Ctrl</kbd><kbd>i</kbd> sends a different input to the terminal application by default (I think it's `Tab`) and neovim has a mapping for that which performs the same action as <kbd>Ctrl</kbd><kbd>i</kbd>. At least on my machine <kbd>Tab</kbd> as well as <kbd>Ctrl</kbd><kbd>i</kbd> both jump forward in neovim.

**Comment by creikey** [comment]
> It indeed is very strange but I can confirm that Ctrli works in neovim regardless of my terminal emulator configuration. In helix I have to change the config according to the comment linked above.
> 
> It's possible that Ctrli sends a different input to the terminal application by default (I think it's `Tab`) and neovim has a mapping for that which performs the same action as Ctrli. At least on my machine Tab as well as Ctrli both jump forward in neovim.

Wow, tab works as ctrl i for some reason! Lets me go forward after ctrl o in helix. Thanks!
