### ISSUE TITLE
fails to build for powerpc-unknown-linux-gnu

### ISSUE THREAD

**Issue by OldWorldOrdr** [helix-editor/helix#4880]
AtomicU64 is not defined on that arch.

I tried fixing it for myself by manually changing all of them to AtomicU32, but then i get illegal hardware instruction when i try to run it.  I have no idea what I'm doing so I can't do much more then that

**Comment by archseer** [comment]
For reference, what device are you trying to run this on? I thought PowerPC was a dead architecture.

There's a single AtomicU64 you should be able to replace with a AtomicU32 here: https://github.com/helix-editor/helix/blob/9059c65a5385f6d3cc0bc7f6e3f835ae542635a5/helix-lsp/src/client.rs#L32

I don't own a device to test this on so you'll need to provide more details on the error (with RUST_BACKTRACE if possible). It's probably SIMD instructions somewhere.

**Comment by OldWorldOrdr** [comment]
@archseer powerpc IS a dead arch (except in some servers).  I'm trying to run on very old hardware (older then me) an iMac G4

**Comment by OldWorldOrdr** [comment]
`RUST_BACKTRACE=1 ./hx` gives illegal hardware instruction.

**Comment by gabydd** [comment]
seems like you can use`RUSTFLAGS="-Ctarget-cpu=e500"` got it from [https://github.com/rust-lang/rust/issues/96394](here)

**Comment by pascalkuthe** [comment]
It seems like the solution by @gabydd should fix this so I am closing this issue.
If you are still having problems you can reopen the issue.
