### ISSUE TITLE
Crash opening jumplist picker

### ISSUE THREAD

**Issue by mainos1** [helix-editor/helix#4895]
### Summary

If the cursor is at the last line, then go using search to another line and delete the line, opening the jumplist picker causes a panic with message: 
thread 'main' panicked at 'Attempt to slice past end of RopeSlice: slice end

I am using Windows 10 with "windows terminal" - windows powershell v6

### Reproduction Steps

1.  open file 
2.  go to the last line 
3.  using search go to another line 
4.  try to open the jumplist picker
5.  the program panics 

open a file 
1. g10g
2. o
3. test
4. <Esc>
5. ge
6. /test
7. x
8. d
9. <space> j
10.  panics

### Platform

Windows 10

### Terminal Emulator

windows Terminal

### Helix Version

helix 22.08.1 (66276ce6)

**Comment by archseer** [comment]
This has been since fixed in `master`.
