### ISSUE TITLE
Preselect a first matched command in the suggestion list

### ISSUE THREAD

**Issue by zummenix** [helix-editor/helix#4897]
When I start typing a command, for example `:tut` the suggestion list correctly shows the list of matched commands and `tutor` is the first. At this point I'd like to stop typing and just hit `<ret>` to open the tutor. But current behaviour is a little annoying – first I need to hit `<tab>` to select the first item in the suggestion list and then `<ret>`.

**Comment by the-mikedavis** [comment]
Duplicate of https://github.com/helix-editor/helix/issues/582
