### ISSUE TITLE
Add a command to merge consecutive selections

### ISSUE THREAD

**Issue by taupiqueur** [helix-editor/helix#4914]

**Comment by Ordoviz** [comment]
In Kakoune, this command is bound to <kbd>alt</kbd>+<kbd>_</kbd>, but I never used it.

**Comment by DylanBulfin** [comment]
https://github.com/helix-editor/helix/pull/5047 pr to add this command

**Comment by DylanBulfin** [comment]
#5047 PR to add this command

**Comment by the-mikedavis** [comment]
Closed by #5047

**Comment by tahir-hassan** [comment]
I am a new user of Helix.

Given I have two cursors in SELECT mode, when I move the cursors and the selections overlap, the selection merges and I end up with one cursor.

What is the point of `merge_consecutive_selections`  then? What is it supposed to do?

**Comment by DylanBulfin** [comment]
`merge_consecutive_selections` came directly from Kakoune and was added to Helix first, while `merge_selections` was added later (#7053) and afaik doesn't have an analogue in Kakoune. So I guess `merge_consecutive_selections` exists more for historical reasons now than practical ones.
