### ISSUE TITLE
Global Rename takes over a minute to reflect the changes made in the codebase

### ISSUE THREAD

**Issue by koalazub** [helix-editor/helix#4918]
### Summary

Global search takes over a minute to update local history

### Reproduction Steps

- Open codebase
- Delete specific block of code(maybe something with a keyword that you remember and only exists in 2 places to home in on)
- Run global search with keyword

Expected:

For it not to show up

*Notes*

I performed the following to try and remedy:
- write-all before running the search again using `wa!`
- Reload source file using `:reload`

### Platform

Ubuntu: Ubuntu 22.10

### Terminal Emulator

alacritty 0.12.0-dev (c5ae05e8)

### Helix Version

helix 22.08.1 (583c2a54)

**Comment by pascalkuthe** [comment]
I can not reproduce this, potentially the formatter failed. In any case #5652 shkykd fix such problems
