### ISSUE TITLE
Make the suggestion from history in prompt greyed out until activated

### ISSUE THREAD

**Issue by xJonathanLEI** [helix-editor/helix#4920]
Currently the history suggestion in prompts use the same color as any other text (it uses `ui.text`):

![image](https://user-images.githubusercontent.com/19556359/204214290-397d58b5-ac9a-428a-8580-56d4c90b50ce.png)

It can confuse new users as the cursor is place at the beginning of the seemingly active text. Even for experienced users it might not be immediately obvious whether the text is active or not (can only tell from he cursor position).

I suggest we use an alternative color when showing the suggestion. If this is desired, what color should we use? I would suggest using `comment`.

If this gets approved I will submit a PR. Thanks!

**Comment by xJonathanLEI** [comment]
Or should a new theme key be created for this? Btw this is how it looks like using `comment` on the default theme:

![image](https://user-images.githubusercontent.com/19556359/204215360-6e2bf763-8e76-4e28-b9c1-21139b336ffb.png)

**Comment by xJonathanLEI** [comment]
Hmm or maybe I should just submit the PR first and let the discussion happen that together with the review process?

**Comment by xJonathanLEI** [comment]
How about a new theme key `ui.prompt.suggestion`?

**Comment by gabydd** [comment]
Maybe ``ui.prompt.completion`` your idea is good as well

**Comment by xJonathanLEI** [comment]
_archseer_ suggested `ui.text.inactive` to be added and used here. Proceeding with that for the PR.
