### ISSUE TITLE
Togglable logging

### ISSUE THREAD

**Issue by kirawi** [helix-editor/helix#493]
A command to enable logging (`hx -v`) during runtime.

**Comment by pickfire** [comment]
What is your usecase?

**Comment by kirawi** [comment]
So if I'm in a buggy state that I don't know how to reproduce, I can record what is happening. Not sure if this is really needed in hindsight.

**Comment by archseer** [comment]
I'd prefer to drop this. If something breaks you usually want to close the editor, turn on logging then re-record to see what exactly caused the bug. Recording _after_ the cause isn't as useful.
