### ISSUE TITLE
Rendering issue/glitches with files containing emojis on Windows

### ISSUE THREAD

**Issue by fnuttens** [helix-editor/helix#4932]
### Summary

Hi!

I noticed some glitches when manipulating buffers containing emojis on Windows (Windows Terminal - also visible my WSL distro, and Cmd):
- in some cases, emojis take up 2x less space, which has the effect of shifting all other characters on the line
- sometimes the emojis are replaced by "square" characters
- some parts of the line are replaced by a black background

Here are two screenshots that should speak for themselves:

<img width="500" alt="glitches" src="https://user-images.githubusercontent.com/8812165/204540584-cf60fd47-cebc-4131-b4b0-8201cc653369.PNG">

<img width="500" alt="glitches2" src="https://user-images.githubusercontent.com/8812165/204540706-e414eb8b-0752-4eb6-a33f-8fbcfc77930f.PNG">

If needed, I will gladly make a recording of this, as the glitches are really correlated to the cursor's movements.

### Reproduction Steps

The problem is replicable with any buffer containing at least one emoji. You just have to move the cursor on the same line to see all the following characters shift as the emoji itself changes in size.

### Helix log

No log produced.

### Platform

Windows

### Terminal Emulator

Windows Terminal, Cmd

### Helix Version

helix 22.08.1 (66276ce6)

**Comment by CptPotato** [comment]
I can kind of reproduce this, though it looks a bit different on wezterm. I'll see if I can reproduce on linux as well but at at least on windows it happens regardless of line endings.

For reference, I used this text:

```
🖋️🖋️
🖋️🖋️
```

Moving around the cursor results in duplicates and seemingly broken diffing. You can see the light blue cell of the cursor appears multiple times in the screenshot, even though there's just one single width cursor. Emojis after the cursor are shifted left and extend into the gutter.

![image](https://user-images.githubusercontent.com/3957610/205883580-c3f48b99-7da7-4f49-8d7e-8f694d334c51.png)
<sup>*(don't mind the hidden line numbers)*</sup>

It seems like helix (or something) expects the emoji to be two cells wide, while the terminal displays it as 1 cell. This isn't the case for all emojis though. `🦀` is 2 cells wide and works fine.

Neovim looks similarly broken, i.e. characters appearing where they shouldn't be on lines with the `🖋️` emoji, while `🦀` appears fine. It doesn't have the diffing issues but that might be down to more aggressive redrawing of cells.

**Comment by kirawi** [comment]
https://github.com/unicode-rs/unicode-width/issues/4#issuecomment-549906181

**Comment by pascalkuthe** [comment]
Closing in favor of https://github.com/helix-editor/helix/issues/6012
