### ISSUE TITLE
Comment in html file

### ISSUE THREAD

**Issue by benzen** [helix-editor/helix#4944]
### Summary

The way comment (C-c) are produced should be adapted with the lang of the current file.

### Reproduction Steps

 

1. `hx some-file.html`
2 select some lines with v- arrow down
3 press C-c

comment are made with '//' instead of 

### Platform

macos

### Terminal Emulator

iterm 2

### Helix Version

helix 22.08.1 (66276ce6)

**Comment by gabydd** [comment]
This would be fixed by: #4718

**Comment by the-mikedavis** [comment]
This is covered by https://github.com/helix-editor/helix/issues/1505
