### ISSUE TITLE
Add bufferline

### ISSUE THREAD

**Issue by gbaranski** [helix-editor/helix#497]
List of opened buffers on the top, that would help workinng on multiple files at the same time, without using C-o and C-i, or opening file search every time.

Neovim(https://github.com/akinsho/nvim-bufferline.lua)
![111992693-9c6a9b00-8b0d-11eb-8c39-19db58583061](https://user-images.githubusercontent.com/34353640/126870562-732323de-bba5-4421-aed4-7f6bd3566845.gif)

VSCode:
![preview-tab](https://user-images.githubusercontent.com/34353640/126878894-d0fea40a-6cd0-4dff-8e62-e5e65781d80b.png)

**Comment by kirawi** [comment]
Duplicate of #475

**Comment by kirawi** [comment]
On second thought, this seems more descriptive than the aforementioned issue. Reopening it for now.

**Comment by aaron404** [comment]
I have an initial implementation here, looking for feedback.
https://github.com/helix-editor/helix/pull/2759
