### ISSUE TITLE
diff.plus, diff.minus and diff.delta theme keys need updating for many themes for git gutters

### ISSUE THREAD

**Issue by David-Else** [helix-editor/helix#4972]
Since git gutters landed https://github.com/helix-editor/helix/pull/3890 many themes need the diff colors updating, I have taken screen shots of the ones I consider in obvious need of attention, but appreciate some changes may be subjective.

*EDIT There is also `"diff.delta.moved"` to consider, I missed that, I am not sure if it is needed?
*EDIT Theme authors, a new release of Helix is planned this weekend, so please make any changes you want ASAP :)

- [ ] emacs
- [x] flatwhite
- [x] kanagawa
- [x] serika_light
- [x] acme
- [x] nord_light
- [x] hex_steel
- [x] hex_toxic
- [x] zenburn
- [x] doom_acario_dark

## Correct Example
Here is an example of `dark_plus` (VS Code theme) which has been [updated specifically](https://github.com/helix-editor/helix/pull/4661/files) for https://github.com/helix-editor/helix/pull/3890:

![dark_plus_correct](https://user-images.githubusercontent.com/12832280/205325917-725d3317-ba97-4e55-b50e-a0eeb4e54a58.png)

## Need Attention

There follows screen shots of those that seem in need of updates, there maybe more, this is just my opinion. I have tried to add a ping to the authors:

@Yevgnen 
![Screenshot from 2022-12-02 14-57-48](https://user-images.githubusercontent.com/12832280/205325955-c83d4204-43cd-4d11-bbef-9429c37afa06.png)

**Comment by theli-ua** [comment]
Is there a way to style gutter symbols separately from patch/diff highlighting?

**Comment by David-Else** [comment]
@theli-ua No, afraid not, these theme keys were only meant for diff gutters.

**Comment by Rinnray** [comment]
There we go, Doom Acario have gotten a change.

**Comment by pascalkuthe** [comment]
Thanks @David-Else for going trough the effort of putting this list together!

**Comment by AlexanderBrevig** [comment]
I'll have a look soon. Should maybe be added to the linter if it's not already?

**Comment by David-Else** [comment]
The linter could check the keys exists, and that they are different, but many of the problems have been caused by a bad choice of colors as there were no diff gutters for visual inspection.

**Comment by VuiMuich** [comment]
Realised it took actually less then anticipated, as the diffs were there and just the color choice was bad...

**Comment by AlexanderBrevig** [comment]
I've made a PR for `flatwhite` #5036 and a PR for adding the `diff` to themelint #5037

**Comment by David-Else** [comment]
@AlexanderBrevig  [22.12](https://github.com/helix-editor/helix/releases/tag/22.12) came out, you just missed the boat for the `flatwhite`update getting in it. Great you updated the themelint!

**Comment by David-Else** [comment]
@Yevgnen Are you able to update the emacs theme in the near future?

Could anyone else maybe fix it? It would be nice to close this issue.
