### ISSUE TITLE
insert auto-completion suggestions when tabbing list of suggestions

### ISSUE THREAD

**Issue by gbaranski** [helix-editor/helix#498]
This is default behavior in some of Neovim plugins, it removes need for confirming with enter.

https://user-images.githubusercontent.com/34353640/126881322-be5f8615-06e6-415a-b184-37d271cb9ed0.mp4

**Comment by pickfire** [comment]
I don't see any difference in the video.

**Comment by gbaranski** [comment]
> I don't see any difference in the video.

That's the current behavior in Helix

https://user-images.githubusercontent.com/34353640/126893993-5ef4e6d9-0948-47f7-90c5-5ceab057a959.mp4

When I tab the options, they don't get automatically inserted like they were ENTER'ed

**Comment by archseer** [comment]
I'll attempt to add this next, I think the problem I had when I last attempted this was keeping the LSP in sync since a completion change needed to replace and insert new text (I only emitted updates to LSP when leaving insert mode, but now we do so continuously).
