### ISSUE TITLE
new diff signs don't work if line endings are crlf

### ISSUE THREAD

**Issue by PORTALSURFER** [helix-editor/helix#4989]
### Summary

the new diff signs feature #3890 colors the entire file using the diff.delta markers on windows where files by default will use crlf line endings.
changing the line endings to lf "fixes" the issue.

### Reproduction Steps

 

I tried this:

1. `hx`
2. open a file with code which is tracked by a git repo

I expected this to happen:
![image](https://user-images.githubusercontent.com/41680373/205443383-d9ca9fc9-488d-43ec-bf40-4f365a7b9b1d.png)

Instead, this happened:
![image](https://user-images.githubusercontent.com/41680373/205443364-78207808-2c81-46a8-af0b-5fa612f98def.png)

### Platform

windows

### Terminal Emulator

windows terminal

### Helix Version

helix 22.08.1 (ee010c49)

**Comment by pascalkuthe** [comment]
Are you using `core.autocrlf=true`? That settings causes git to checkout files with `CRLF` on windows but the objects inside the commits have `LF` endings . I guess we would need to respect that setting when obtaining the object from git.

Is there already support for that in gitoxide @Byron

**Comment by Byron** [comment]
That's the work of filters, which in this case simply change the line ending style upon checkout and addition to the object database.

`gitoxide` unfortunately doesn't have support for applying filters yet, so a fix for this on the side of `hx` isn't immediately possible. However, I believe this will be implemented within the next 6 months or earlier.

In future, one would be able to obtain the object data and pass it through the configured filters to obtain the buffer that `git` would write to disk, so one compares apples to apples again when diffing.

**Comment by pascalkuthe** [comment]
Thanks for elaborating @Byron. I will be implementing a simole workaround for CRLF in helix (but not support for.gitattrivutes)  for the next release. That can be removed when upstream support lands

**Comment by kirawi** [comment]
An immediate workaround is `:set-line-ending lf`

**Comment by pascalkuthe** [comment]
#4995 will fix most cases
