### ISSUE TITLE
Syntax highlighting for NASM/Assembly

### ISSUE THREAD

**Issue by 0xhiro** [helix-editor/helix#5018]
How do i get syntax highlighting for assembly code?

**Comment by kirawi** [comment]
You can look at https://docs.helix-editor.com/guides/adding_languages.html
There is also already a tree-sitter grammar at https://github.com/bearcove/tree-sitter-x86asm

**Comment by Ordoviz** [comment]
Duplicate of #3329

**Comment by 0xhiro** [comment]
I'm not very familiar with what a tree-sitter is and grammer etc. Please explain.

**Comment by the-mikedavis** [comment]
You can read more about tree-sitter here: https://tree-sitter.github.io/tree-sitter/

We use "grammar" to mean the repository that has the `grammar.js` rules that generate a tree-sitter parser.

Also see the guide that Kirawi linked: https://docs.helix-editor.com/guides/adding_languages.html

**Comment by 0xhiro** [comment]
A step by step process for adding it will be helpful. It all looks confusing and vague without examples. Even the linked tree-sitter repository gives no clue on how to get things working.
