### ISSUE TITLE
Document how to collapse multiple cursors

### ISSUE THREAD

**Issue by mankinskin** [helix-editor/helix#502]
Hi, is there a way to collapse multiple cursors after selecting multiple pieces using `s` in a selection?
![Peek 2021-07-25 13-53](https://user-images.githubusercontent.com/20745737/126898036-f7631f6a-6b83-490e-9c0b-ba9cdbd6b33f.gif)

what I did here was `v`, move down, `s`, type "response", Enter, `ms)`, `u`, move around.

Is there a key to collapse the multiple cursors into one, like the top one? I know of `;` but that doesn't do it.

**Comment by sudormrfbin** [comment]
`<space> <space>` should do the trick.

**Comment by pickfire** [comment]
I think we should have a tutorial like vimtutor for these additional functionalities.

**Comment by mankinskin** [comment]
@pickfire I don't think that is needed, I never really used the vimtutor either. I think a complete documentation and something like an extensive FAQ you can search would help the most.
