### ISSUE TITLE
R language server got errors.

### ISSUE THREAD

**Issue by vvxin** [helix-editor/helix#5023]
Fresh Helix installation on WSL2.

then install R and R/languageserver package.

but got the bottom error and the function description stays there on top.  No auto-completion for user variables.

![image](https://user-images.githubusercontent.com/15047983/205951481-c9554066-3f90-41a3-98ff-1f0b53b82192.png)

I googled that error message but got no clue.  Any help, thanks!

**Comment by archseer** [comment]
This was also a problem with some other language server if I remember correctly

**Comment by vvxin** [comment]
Thanks @dgkf 
The GitHub version of REditorSupport
/languageserver now works fine with Helix.
