### ISSUE TITLE
python wrong indentation on `try:`

### ISSUE THREAD

**Issue by rumpelsepp** [helix-editor/helix#5045]
### Summary

In python, the indentation is wrong when you use `try`.

![image](https://user-images.githubusercontent.com/1961699/206213626-83d9f943-4d13-4dcc-b15a-862afa81728b.png)

Line 2 should be indented by one more level.

### Reproduction Steps

Type `try:` and press enter.

### Helix log

Not relevant.

### Platform

Linux

### Terminal Emulator

gnome-console

### Helix Version

96ff64a84a4948b0aa85a453276cb0091fb9c792

**Comment by rumpelsepp** [comment]
This also applies for `if FOO:`

**Comment by thomkeh** [comment]
I think this is being discussed in #763

**Comment by archseer** [comment]
Fixed by #5332
