### ISSUE TITLE
Helix segfaulting in fuzzy finder

### ISSUE THREAD

**Issue by bhansconnect** [helix-editor/helix#5057]
### Summary

Helix is segfaulting while I am using the fuzzy finder for files. It does not always do this, but happens pretty commonly. It may be related to the number of files with a search term, but I really am not sure. It seems to only happen with certain searches that match a large number of files. For example, `roc` crashes, but if I type `roct` fast enough, it does not crash. `roc` matches 1242/1720 files, while `roct` select 615/1720 files. 

### Reproduction Steps

I tried this:

1. `git clone git@github.com:roc-lang/roc.git`
2. `cd roc`
3. `hx .`
4. type `roc` and wait (can take maybe 5 seconds, but seems pretty consistent)
5. helix segfaults

I expected this to happen:
Helix should not segfault and I should be able to select a file.

Instead, this happened:
Helix segfaulted.

### Helix log

`hx -v .` does not give any logs. `hx -vvv .` was too long to post here, so I made a gist: https://gist.github.com/bhansconnect/5b9b81972d4f51a19a8d7afad87c9c70

### Platform

M1 macOS v12.3.1

### Terminal Emulator

kitty 0.26.5

### Helix Version

helix 22.12 (96ff64a8)

**Comment by kirawi** [comment]
It looks like it crashes after the idle timer, so I'm guessing it's something with the compiled tree-sitter grammar for the language you're working with. Those are written in C.

**Comment by bhansconnect** [comment]
Hm. Yeah, that seems correct. It's an issue with the markdown treesitter I guess.

When I search `roc` the first file is [roc-for-elm-programmers.md](https://github.com/roc-lang/roc/blob/cdefaa4be926764892d28a8ce75a500f671e1719/roc-for-elm-programmers.md). If I remove that file, helix doesn't segfault.

Yeah, and helix can't open that file in general, it immediately segfaults. Does that mean this bug should be filed with the markdown tree sitter implementation? If so, any tips for testing/filing the bug?

**Comment by the-mikedavis** [comment]
This is probably another instance of https://github.com/helix-editor/helix/issues/3745

**Comment by bhansconnect** [comment]
Yep, this is definitely a duplicate of #3745. If I delete the word `elm` from the file, it works just fine.
