### ISSUE TITLE
Ques: terminal inside helix?

### ISSUE THREAD

**Issue by sou-chon** [helix-editor/helix#5068]
Hi, I am wondering how to spin up a terminal inside helix, sort of like the terminal mode in neovim? I like it because for example when I get compilation error I can follow the errored file by using `goto` on the file path. I see you can run shell commands in helix but there doesn't seem to be a full fledge terminal / shell?

**Comment by archseer** [comment]
https://github.com/helix-editor/helix/issues/1976
