### ISSUE TITLE
Can no longer move cursor while in insert mode

### ISSUE THREAD

**Issue by akivajgordon** [helix-editor/helix#5074]
### Summary

I just upgraded to v22.12 (I believe from v22.08). Now when I am in insert mode and press <kbd>Ctrl</kbd>-<kbd>f</kbd> or <kbd>Ctrl</kbd>-<kbd>b</kbd>, it just inserts an `f` or a `b` respectively, instead of the previous behavior where it would move my cursor to the right or left while in insert mode.

In terms of impact, it means that I now have to either use the arrow keys or exit insert mode to move my cursor in normal mode before returning to insert mode.

### Reproduction Steps

* Insert text into a buffer
* while in insert mode, press <kbd>Ctrl</kbd>-<kbd>f</kbd> and <kbd>Ctrl</kbd>-<kbd>b</kbd>
* observe that the characters `f` and `b` are written to the buffer at the cursor location.

Expected result is that the cursor would move left and right while staying in insert mode.

### Helix log

<details><summary>~/.cache/helix/helix.log</summary>

```
please provide a copy of `~/.cache/helix/helix.log` here if possible, you may need to redact some of the lines
```

</details>

### Platform

macOS

### Terminal Emulator

Terminal.app Version 2.13 (447)

### Helix Version

helix 22.12 (96ff64a8)

**Comment by kirawi** [comment]
https://github.com/helix-editor/helix/pull/4424#issuecomment-1287998239
