### ISSUE TITLE
bash: wrong indent with bash functions

### ISSUE THREAD

**Issue by rumpelsepp** [helix-editor/helix#5087]
### Summary

In bash, the indentation is wrong when you define functions.

Line 2 should be indented by one more level.

![image](https://user-images.githubusercontent.com/1961699/206720479-a22f16df-6ff8-43ef-abae-4a3d626b563b.png)

### Reproduction Steps

Define a function and use `o`.

### Helix log

Not relevant.

### Platform

Linux

### Terminal Emulator

gnome-console

### Helix Version

96ff64a84a4948b0aa85a453276cb0091fb9c792

**Comment by archseer** [comment]
`bash` has no indentation queries defined yet: https://github.com/helix-editor/helix/tree/master/runtime/queries/bash

If you're interested it shouldn't be too hard to contribute https://docs.helix-editor.com/guides/indent.html
