### ISSUE TITLE
Build releases with cargo auditable

### ISSUE THREAD

**Issue by DuckDuckWhale** [helix-editor/helix#5098]
Currently `cargo audit bin hx` on `helix 22.08.1 (07d31572)` reports:
`warning: hx was not built with 'cargo auditable', the report will be incomplete (96 dependencies recovered)`

It would be nice to build with `cargo audit build -r` for a complete list of dependencies, allowing an accurate audit report.

**Comment by pascalkuthe** [comment]
Helix maintains it's `Cargo.lock` inside sourcecontrol. Therefore you can always audi all dependencies by looking at the `Cargo.lock` of the `release` tag. `hx --version` even shows you the exact `git` a build was created from so I don't think this is necessary.

**Comment by DuckDuckWhale** [comment]
That is true. One can certainly clone the repo, checkout that commit, and run `cargo audit`. But I think the appeal of this use case is more about the convenience and the ability to automate, making it possible to directly run `cargo audit` on the executable instead of going through the whole process every time, possibly even in a script for all Rust executables recursively. So while not necessary, I do think it's still nice to have as an enhancement.

**Comment by pascalkuthe** [comment]
I am closing this as it makes the build more.complex without adding anything that can't already be achieved by examining the --version output and the Cargo.lock in the repo. If users work in eviorments where cargo auditable is required for compliance reasons (if those exist) it's easy enough to build helix with that yourself
