### ISSUE TITLE
Feature: Open file picker by default when the specified path is a directory

### ISSUE THREAD

**Issue by wojciechkepka** [helix-editor/helix#51]
I would like to see the contents of a directory when opening `hx` with a path to directory like:
```
hx /tmp
```

Shows me file picker with the contents of `/tmp`.

I would like to give a try at implementing this.

**Comment by archseer** [comment]
I like this idea, but I wonder what the behavior should be if several files/folders are listed, i.e. `hx /tmp log.txt`

**Comment by wojciechkepka** [comment]
That's also what I currently stumbled upon. I'm wondering how to handle this with what there is available now.

**Comment by archseer** [comment]
You should be able to reuse the file picker code here: https://github.com/helix-editor/helix/blob/2719a35123e2b4000a0b2b863c929dd2824fff9a/helix-term/src/commands.rs#L1083-L1085

You would need to construct it if necessary, and `compositor.push` it right after the editor here:
https://github.com/helix-editor/helix/blob/2719a35123e2b4000a0b2b863c929dd2824fff9a/helix-term/src/application.rs#L48-L56

**Comment by wojciechkepka** [comment]
Already got that figured out, I'm wondering what to do with the extra arguments aftrer initial directory path like `hx /tmp some_file` - what to do about `some_file` there. Perhaps all extra files should be opened as splits?

**Comment by wojciechkepka** [comment]
And also what to do when there are more than one directories like:
```
hx /tmp /home some_file
```

**Comment by wojciechkepka** [comment]
I added initial changes in #59

**Comment by archseer** [comment]
Closed by #59

**Comment by Aitanuqui** [comment]
Is it possible to disable this? I would like to open the file explorer in my project instead.
