### ISSUE TITLE
AMP like Jump Mode

### ISSUE THREAD

**Issue by yerlaser** [helix-editor/helix#510]
Amp Editor (https://amp.rs/docs/usage/) has a very sweet jump mode.
Since it's also written in Rust and open source, would it be a crime to suggest to peek into the code and steal some ideas from it?

**Comment by sudormrfbin** [comment]
Previous discussion: #274

**Comment by yerlaser** [comment]
Thanks, yes, it's related, but I would still keep this open because:

1) AMP's jump mode is different than the likes of EasyMotion and AceJump. In AMP, you don't need to type search character before highlighting appears. Once the shortcut is pressed, all visible words are highlighted with two character tags. User then needs to type the needed tag and jump to that position. So, this is one step shorter and it makes a big difference really. It's so fast and becomes so natural that one almost forgets about other ways to navigate code.

2) Since AMP is written in Rust and open source, certain ideas could potentially be easier to port than other solutions.

**Comment by zim0369** [comment]
hop.nvim built-in :fire:

**Comment by clord** [comment]
Last time I gave helix a solid chance, a good jump mechanism like hop.vim was all I really missed. 

It'd be even better to have a jump-to-treesitter-node mode that can visually jump to significant types of nodes, like parents, siblings, and children. Usually my eye is already where I want to go, so being able to bring up a two-char jump code is killer. Maybe a jump mode wou all of these navigations 🤔

**Comment by jabbalaci** [comment]
What is the status of this enhancement idea? This thing is awesome in Amp, I'd love to see it in Helix too.

**Comment by yerlaser** [comment]
There are two pull requests with differing implementations, but they are not being reviewed for some reason :(

**Comment by dead10ck** [comment]
The maintainers only have so much spare time. We have to prioritize. You may notice, as of this writing, there are 283 pull requests open

**Comment by yerlaser** [comment]
> 

I know, and I respect that.
