### ISSUE TITLE
Update tree-sitter-scheme

### ISSUE THREAD

**Issue by 6cdh** [helix-editor/helix#5125]
Hello, I'm the author of tree-sitter-scheme. I saw some people said it's big and give some information of Helix.
It's unexpected. It was big as its naive implementation, but it was optimized for size and speed after that.

I figured out Helix used outdated tree-sitter-scheme that earlier than the optimization. With the latest version,
run with `cargo build --release`, it's 106KB, not that bad.

**Comment by archseer** [comment]
Thanks! Fixed here https://github.com/helix-editor/helix/commit/bae890d8faa993333d81e662b6f0a6bc5e921a92
