### ISSUE TITLE
Connect to language server via port

### ISSUE THREAD

**Issue by jaredramirez** [helix-editor/helix#5134]
Hey there!

1st off, thanks for the great editor! I've been using helix as my daily driver for a few months and love it.

I'm trying use the [Unison language server](https://github.com/unisonweb/unison/blob/trunk/docs/language-server.markdown) but it only support connecting to it through a port, not through stdio. Does helix support this? If so, how? Or if not, is this something it can eventually do?

**Comment by kirawi** [comment]
You can use the same method used for Godot: https://github.com/helix-editor/helix/wiki/How-to-install-the-default-language-servers#gdscript

**Comment by jaredramirez** [comment]
Awesome, it works! Thank you for the prompt reply!
