### ISSUE TITLE
How to configure to attach a rust lsp client for single file

### ISSUE THREAD

**Issue by lost22git** [helix-editor/helix#5142]

**Comment by kirawi** [comment]
It's not supported https://github.com/rust-lang/rust-analyzer/issues/6388

**Comment by anstadnik** [comment]
It is though https://github.com/rust-lang/rust-analyzer/pull/8955

**Comment by rcorre** [comment]
@anstadnik how do you actually use the feature you linked? The PR doesn't explain it, and it doesn't seem to work out-of-the-box (running `rust-analyzer 1 (af40101841 2024-01-07)`)

**Comment by anstadnik** [comment]
I used https://github.com/simrat39/rust-tools.nvim, which supports the standalone feature. I'm not the developer, so I can't tell you how it uses the feature.

**Comment by rcorre** [comment]
Ah, I'd assumed you had it working in Helix

**Comment by the-mikedavis** [comment]
You can use rust-analyzer with non-cargo projects like single files but you need to tell rust-analyzer about the project with a `rust-project.json` file: https://rust-analyzer.github.io/manual.html#non-cargo-based-projects

**Comment by chaoky** [comment]
you could use `rust-project.json` before that pr, this what using that feature looks like in neovim:
```lua
local lsp_conf = require('lspconfig')

lsp_conf.rust_analyzer.setup {
    -- Other setup stuff
    -- ...

    -- To be able to start rust-analyzer at all a root_dir is needed,
    -- I added a star match for testing purposes to match on any file
    -- This could be an lspconfig/Neovim only issue
    root_dir = lsp_conf.util.root_pattern("*"),

    -- LSP Client needs to know the detached files ahead of time on
    -- initialization and pass them to the r-a on startup
    init_options = { detachedFiles = { "/tmp/file.rs" } }
}
```
from: https://github.com/rust-lang/rust-analyzer/issues/14318#issuecomment-1668504908
