### ISSUE TITLE
Unexpected completion behavior

### ISSUE THREAD

**Issue by emsquid** [helix-editor/helix#5150]
### Summary

When I am using completion in Helix, choosing an item from completion gives me a weird result 

### Reproduction Steps

 

I tried this:

1. write a variable/function name

I expected this to happen:
Completion give me the right variable name when I pick it

Instead, this happened:
Some letters are duplicated

See this exemple recording in python (it happens in many other situations):
https://user-images.githubusercontent.com/76693837/207450888-63f55268-d354-44fb-b608-996a57219b89.mov

### Helix log

<details><summary>~/.cache/helix/helix.log</summary>

```
please provide a copy of `~/.cache/helix/helix.log` here if possible, you may need to redact some of the lines
```

</details>

### Platform

macOs

### Terminal Emulator

kitty

### Helix Version

helix 22.12 (96ff64a8)

**Comment by the-mikedavis** [comment]
Duplicate of https://github.com/helix-editor/helix/issues/4851
