### ISSUE TITLE
Changing mode from INS to NOR using Escape key is slow

### ISSUE THREAD

**Issue by plewis110** [helix-editor/helix#5151]
### Summary

I have an optimized build of the current `master` branch running on a 16 core, 100GB ram x86-64 machine and am seeing latency when I type the `Esc` key to go from the `INS` mode to the `NOR` mode.

When I am running Vanilla VIM this operation is immediate and I can immediately start typing movement keys (`h`, `j`, `k`, `l`), but with Helix I'm finding the `Esc` keypress is getting lost by the editor and pressing the movement keys after that is being used in the `INS` mode to insert those characters.

### Reproduction Steps

 

I tried this:

1. `hx file.json`
2. `i` - to go to `INS` mode
3. typed some chars
4. `Esc` - to go to `NOR` mode
5. immediately pressed `k` to go up a line

I expected this to happen:

6. the mode to go to `NOR` and the cursor to go up a line

Instead, this happened:

6. `k` character was inserted and mode remained in `INS`

### Helix log

<details><summary>~/.cache/helix/helix.log</summary>

```
please provide a copy of `~/.cache/helix/helix.log` here if possible, you may need to redact some of the lines
```

</details>

### Platform

Linux

### Terminal Emulator

zsh 5.4.1 (x86_64-unknown-linux-gnu) running in tmux 3.3a

### Helix Version

22.12-25-g0f2ae35a

**Comment by the-mikedavis** [comment]
https://github.com/helix-editor/helix/wiki/Troubleshooting#when-using-tmux-or-screen-there-is-a-delay-after-hitting-escape-before-its-registered

**Comment by IsaccBarker** [comment]
I don't have this issue using (Neo)Vim or Nano as an example... is there a reason why it's particularly an issue with Helix?

**Comment by IsaccBarker** [comment]
Nevermind, I just tested it and I do. I just didn't notice it for the year I was using (Neo)Vim, and only started noticing it when I switched to Helix today.

**Comment by webdev23** [comment]
To summarize, add in `~/.tmux.conf`

`set -sg escape-time 0`
