### ISSUE TITLE
Support of the `helix` in the` xplr`

### ISSUE THREAD

**Issue by volopivoshenko** [helix-editor/helix#5154]
### Summary

Hi 👋🏻

I was trying to use `helix` from the [`xplr`](https://github.com/sayanarijit/xplr), I am using `helix` as the default editor. But unfortunately, it keeps crashing with errors. I am not sure if it's the issue from the `helix` side or the `xplr` side.

Obviously, with `vim` and `nano`, everything works fine.

Thanks!

### Reproduction Steps

 

I tried this:

1. Set `helix` as the default editor in `.zshrc`

```
export EDITOR=hx
export VISUAL="$EDITOR"
```

2. I run `xplr` and run the command to open the file in the editor.
3. It failed with an error (full log attached).

### Helix log

thread 'main' panicked at 'reader source not set', /Users/brew/Library/Caches/Homebrew/cargo_cache/registry/src/github.com-1ecc6299db9ec823/crossterm-0.25.0/src/event/read.rs:38:9
stack backtrace:
   0:        0x10b13daf7 - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::h9515a3bdbd0baca0
   1:        0x10a81851a - core::fmt::write::hfb97b04d44bdb4d8
   2:        0x10b1205dc - std::io::Write::write_fmt::h686d9784d8415cb9
   3:        0x10b1248cf - std::panicking::default_hook::{{closure}}::ha298777f08731ac8
   4:        0x10b12426b - std::panicking::default_hook::hb5f65353eb4f3d66
   5:        0x10b124f92 - std::panicking::rust_panic_with_hook::he911070515b336d8
   6:        0x10b13de04 - std::panicking::begin_panic_handler::{{closure}}::h752456daaf48f28e
   7:        0x10b13dc38 - std::sys_common::backtrace::__rust_end_short_backtrace::hc10b12502582d9b6
   8:        0x10b124ac2 - _rust_begin_unwind
   9:        0x10b1da983 - core::panicking::panic_fmt::hc606b9962be5fb74
  10:        0x10a81432b - core::panicking::panic_display::h0e3da8917e76b83a
  11:        0x10a8142dc - core::panicking::panic_str::h7969729f8e5cea52
  12:        0x10b1da819 - core::option::expect_failed::h6b6f0584324e64e9
  13:        0x10a82b1ce - <crossterm::event::stream::EventStream as core::default::Default>::default::h23710dd5d197c744
  14:        0x10af8c0dd - <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll::h9c5b2f8d611c5d66
  15:        0x10afc82e9 - tokio::runtime::park::CachedParkThread::block_on::h39b99a375fe28290
  16:        0x10afe97ba - tokio::runtime::runtime::Runtime::block_on::h236318fe46d18d0d
  17:        0x10af8f92e - hx::main::hdd1995e220cff06c
  18:        0x10afcf596 - std::sys_common::backtrace::__rust_begin_short_backtrace::hdf7da06abce52d23
  19:        0x10afdfbfc - std::rt::lang_start::{{closure}}::hafbe08d58c551f8e
  20:        0x10b11fd4c - std::rt::lang_start_internal::h7de129d052efa930
  21:        0x10af8fa2f - _main

### Platform

macOS

### Terminal Emulator

iTerm2

### Helix Version

helix 22.12 (96ff64a8)

**Comment by matoous** [comment]
As far as I understand the underlying issue is the same as in: https://github.com/helix-editor/helix/issues/2111

**Comment by volopivoshenko** [comment]
Thanks, @matoous 🙂 It helped!
