### ISSUE TITLE
inherit does not work with base16_theme

### ISSUE THREAD

**Issue by plewis110** [helix-editor/helix#5156]
### Summary

I'm following the [docs guide](https://docs.helix-editor.com/themes.html?highlight=ruler#inheritance) and created a new theme file `mytheme.toml` and placed it at `~/.config/helix/themes/mytheme.toml`:

```toml
# ~/.config/helix/themes/mytheme.toml
inherits = "base16_theme"

ui.virtual.ruler = { fg = "grey", bg = "grey" }
```

Running `:theme mytheme` in `hx myfile.json` results in this output:

```
Theme does not exist
```

I've tried running `cargo xtask themelint ~/.config/helix/themes/mytheme` but the output doesn't make sense since I expect the default theme to be correct:

```
/home/user/.config/helix/themes/mytheme: missing `fg` or `bg` for `ui.selection`
/home/user/.config/helix/themes/mytheme: missing `fg` or `bg` for `ui.selection.primary`
/home/user/.config/helix/themes/mytheme: `ui.selection` and `ui.selection.primary` cannot be equal
/home/user/.config/helix/themes/mytheme: missing `fg` for `ui.text`
/home/user/.config/helix/themes/mytheme: missing `bg` for `ui.background`
/home/user/.config/helix/themes/mytheme: missing `fg` and `bg` for `ui.statusline`
/home/user/.config/helix/themes/mytheme: missing `fg` and `bg` for `ui.statusline.inactive`
/home/user/.config/helix/themes/mytheme: missing `fg` or `bg` for `ui.statusline.normal`
/home/user/.config/helix/themes/mytheme: missing `fg` or `bg` for `ui.statusline.insert`
/home/user/.config/helix/themes/mytheme: missing `fg` or `bg` for `ui.statusline.select`
/home/user/.config/helix/themes/mytheme: `ui.statusline.normal` and `ui.statusline.insert` cannot be equal
/home/user/.config/helix/themes/mytheme: `ui.statusline.normal` and `ui.statusline.select` cannot be equal
/home/user/.config/helix/themes/mytheme: missing `bg` for `ui.cursorline.primary`
/home/user/.config/helix/themes/mytheme: missing `fg` for `ui.virtual.whitespace`
/home/user/.config/helix/themes/mytheme: missing `fg` or `bg` for `ui.virtual.indent-guide`
/home/user/.config/helix/themes/mytheme: missing `fg` or `bg` for `ui.virtual.ruler`
/home/user/.config/helix/themes/mytheme: missing `fg` and `bg` for `ui.menu`
/home/user/.config/helix/themes/mytheme: missing `fg` and `bg` for `ui.help`
/home/user/.config/helix/themes/mytheme: missing `bg` for `ui.popup`
/home/user/.config/helix/themes/mytheme: missing `fg` or `bg` for `ui.window`
/home/user/.config/helix/themes/mytheme: missing `bg` for `ui.cursor.primary`
/home/user/.config/helix/themes/mytheme: missing `fg` or `bg` for `ui.cursor.match`
Error: "/home/user/.config/helix/themes/mytheme has issues"
```

All I want is to change the default color of the rulers since it is set to an obnoxious red by default. I picked `base16_theme` as the `inherits` because it is the output of running `:theme` in the editor. I'm working on a clone of the repo from yesterday. Please see below for the exact git commit.

### Reproduction Steps

 

I tried this:

1. `hx`

I expected this to happen:

Instead, this happened:

### Helix log

<details><summary>~/.cache/helix/helix.log</summary>

```
please provide a copy of `~/.cache/helix/helix.log` here if possible, you may need to redact some of the lines
```

</details>

### Platform

Linux

### Terminal Emulator

zsh 5.4.1 (x86_64-unknown-linux-gnu) running in tmux 3.3a

### Helix Version

22.12-25-g0f2ae35a

**Comment by kirawi** [comment]
Is your runtime linked correctly? Are you able to see the other themes in `:theme`?

**Comment by the-mikedavis** [comment]
I can reproduce this. It looks like it's not currently possible to use the base16 or true-color default themes with inherits since their TOML doesn't end up in the runtime directory.

**Comment by plewis110** [comment]
> Is your runtime linked correctly? Are you able to see the other themes in `:theme`?

Yeah, all the themes are there and I can switch between them.

**Comment by hunterliao29** [comment]
> I can reproduce this. It looks like it's not currently possible to use the base16 or true-color default themes with inherits since their TOML doesn't end up in the runtime directory.

I opened a pull request that fix this issue by getting TOML from by byte array. but I am not sure if this is a good way to do it.
maybe just put copy of default themes in runtime?
