### ISSUE TITLE
Allow max number of files used by file_picker to be configurable

### ISSUE THREAD

**Issue by nstinus** [helix-editor/helix#5157]
It is currently an undocumented hard coded value. Allowing it to be configurable has the benefit of documenting it and allowing users to set a greater value. Perhaps with a warning that bad performance could be expected?

https://github.com/helix-editor/helix/blob/012fc12f97f4e8e0fc38af351388e41e8bc142d8/helix-term/src/ui/mod.rs#L214

**Comment by pascalkuthe** [comment]
This was adreased by #7814, there is no limit anymore, files are streamed into the picker in the background now (and the matcher ks fast enough to handle millions of files)
