### ISSUE TITLE
Nix flake doesn't build

### ISSUE THREAD

**Issue by ocharles** [helix-editor/helix#5162]
### Summary

I use the bleeding edge `HEAD` build of Helix by using the Nix flake. As of this morning, it seems to have stopped building.

### Reproduction Steps

Run

```
nix profile install github:helix-editor/helix
```

This fails with:

```
++ command cargo build --profile release --package helix-term --message-format json-render-diagnostics
   Compiling helix-loader v0.6.0 (/build/helix-source/helix-loader)
   Compiling tree-sitter v0.20.9
   Compiling helix-term v0.6.0 (/build/helix-source/helix-term)
   Compiling helix-core v0.6.0 (/build/helix-source/helix-core)
   Compiling helix-dap v0.6.0 (/build/helix-source/helix-dap)
   Compiling helix-lsp v0.6.0 (/build/helix-source/helix-lsp)
   Compiling helix-vcs v0.6.0 (/build/helix-source/helix-vcs)
   Compiling helix-view v0.6.0 (/build/helix-source/helix-view)
   Compiling helix-tui v0.6.0 (/build/helix-source/helix-tui)
error[E0425]: cannot find function `goto_pos` in this scope
    --> helix-term/src/commands.rs:2882:13
     |
2882 |             goto_pos(editor, pos)
     |             ^^^^^^^^ not found in this scope

error[E0282]: type annotations needed
    --> helix-term/src/commands/typed.rs:1821:54
     |
1821 |         let call: job::Callback = Box::new(|_editor, compositor| {
     |                                                      ^^^^^^^^^^ consider giving this closure parameter a type
     |
     = note: type must be known at this point

error[E0308]: mismatched types
    --> helix-term/src/commands/typed.rs:1821:35
     |
1821 |           let call: job::Callback = Box::new(|_editor, compositor| {
     |  ___________________-------------___^
     | |                   |
     | |                   expected due to this
1822 | |             compositor.clear().expect("unable to redraw");
1823 | |         });
     | |__________^ expected enum `job::Callback`, found struct `Box`
     |
     = note: expected enum `job::Callback`
              found struct `Box<_>`
help: consider unboxing the value
     |
1821 |         let call: job::Callback = *Box::new(|_editor, compositor| {
     |                                   +
help: try wrapping the expression in a variant of `job::Callback`
     |
1821 ~         let call: job::Callback = job::Callback::EditorCompositor(Box::new(|_editor, compositor| {
1822 |             compositor.clear().expect("unable to redraw");
1823 ~         }));
     |
1821 ~         let call: job::Callback = job::Callback::Editor(Box::new(|_editor, compositor| {
1822 |             compositor.clear().expect("unable to redraw");
1823 ~         }));
     |

error[E0609]: no field `terminal` on type `&mut compositor::Compositor`
   --> helix-term/src/compositor.rs:202:14
    |
202 |         self.terminal.clear()
    |              ^^^^^^^^ unknown field
    |
    = note: available fields are: `layers`, `area`, `last_picker`

Some errors have detailed explanations: E0282, E0308, E0425, E0609.
For more information about an error, try `rustc --explain E0282`.
error: could not compile `helix-term` due to 4 previous errors
warning: build failed, waiting for other jobs to finish...
```

### Helix log

Not relevant.

### Platform

NixOS

### Terminal Emulator

Kitty

### Helix Version

f916915b53fa6fedd3f9106bcf58163083cc052e

**Comment by ocharles** [comment]
I've actually seen that CI is failing. I wonder if it's worth turning on mandatory status checks for merges to master? I'll leave that decision to maintainers.

**Comment by archseer** [comment]
Status checks are mandatory, but we don't have a bors type setup that would try to rebase and run against latest master. Fixed in https://github.com/helix-editor/helix/commit/ec9aa6690244bccefac24037c9f7a659816bffdd

**Comment by ocharles** [comment]
Got it. Thanks @archseer!

**Comment by the-mikedavis** [comment]
The feature is in limited access beta currently but merge queues would be a nice way to avoid failures like this

https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/incorporating-changes-from-a-pull-request/merging-a-pull-request-with-a-merge-queue

**Comment by ocharles** [comment]
I mentioned on Matrix that you also might want to consider mergify.io. It's free for open source, and I've had a lot of success with it at work. I know that at least [Haskell Cabal](https://github.com/haskell/cabal/blob/master/.github/mergify.yml) and [Dhall](https://github.com/dhall-lang/dhall-haskell/blob/master/.mergify.yml) are also using it

**Comment by ocharles** [comment]
Actually, isn't it just a case of enabling the second checkbox here?

![image](https://user-images.githubusercontent.com/20878/207928027-e2a7fad3-d846-4532-9b81-3bda272e4db3.png)

**Comment by the-mikedavis** [comment]
That requires the branch to be up to date in order to merge but doesn't automatically rebase it if it's out of date as far as I know. It would prevent failures like this but would also make merging really annoying to do - we would have to pull down the branch and rebase it and force push for any out of date PRs, and PRs get out-of-date quickly since master moves a lot.

I use mergify at work as well (though only for the backporting feature). It's an option but a GitHub feature for this would be preferable: like with bors you end up interacting with a bot rather than the github UI which is a bit worse, and mergify does some kinda hacky stuff to rebase the PRs (it impersonates someone with write and branch-protection-breaking access in order to force push). Also I'm not sure if it allows you to choose the merge style and we don't only use one style: some merges are squashes and others are rebases.
