### ISSUE TITLE
Auto-complete corrupts when trying to wrap code in function call

### ISSUE THREAD

**Issue by aral** [helix-editor/helix#5163]
### Summary

Auto-complete can corrupt code.

### Reproduction Steps

Say I’m returning a value:

![Screenshot from 2022-12-15 10-38-06](https://user-images.githubusercontent.com/41798/207838161-e679ba6e-b744-4912-8893-c47460b7528e.png)

Now, I want to wrap that value in a function call (e.g., `encodeUriComponent()`… so I press <kbd>i</kbd> and enter insert mode and start typing the function name. <kbd>e</kbd><kbd>n</kbd>…

![Screenshot from 2022-12-15 10-38-20](https://user-images.githubusercontent.com/41798/207838267-744464dd-0c8c-4776-9436-8d98caee28e3.png)

So far, so good. I see the auto-completions appear and so I go to select the one I want:

![Screenshot from 2022-12-15 10-38-27](https://user-images.githubusercontent.com/41798/207838514-e1b08152-91dc-440b-a39f-ded936fc93c4.png)

However, instead of getting `encodeUriComponent|value`, I get `encodeUriComponen|t` and my code is corrupted.

_(| = cursor)_

### Helix log

n/a

### Platform

Linux (Fedora Silverblue 37)

### Terminal Emulator

Black Box

### Helix Version

helix 22.12 (0f2ae35a)

**Comment by the-mikedavis** [comment]
I think this is related to https://github.com/helix-editor/helix/issues/4851 and fixed by #1819

**Comment by archseer** [comment]
Should be fixed by https://github.com/helix-editor/helix/pull/6173
