### ISSUE TITLE
Cycling not having visual markers?

### ISSUE THREAD

**Issue by EpixMan** [helix-editor/helix#5171]
### Summary

upon trying tutor mode and reaching chapter 10.1 I noticed that "(" and ")" functions are not working as expected

### Reproduction Steps

Just a beginner here, so I will start with posting the chapter itself
```=================================================================
=              10.1 CYCLING AND REMOVING SELECIONS              =
=================================================================

 Type ) and ( to cycle the primary selection forward and backward
 through selections respectively.

 Type A-, to remove the primary selection.

 1. Move the cursor to the line below marked -->.
 2. Select both lines with xx or 2x.
 3. Type s to select, type "would" and enter.
 4. Use ( and ) to cycle the primary selection and remove the
    very second "would" with A-, .
 5. Type c "wood" to change the remaining "would"s to "wood".

 --> How much would would a wouldchuck chuck
 --> if a wouldchuck could chuck would?

 Note: Additionally, A-( and A-) cycle the *contents* of the
       selections as well.
```

I tried this:

1. `hx -tutor`
2. Reached the chapter
3. Did what I think is exactly asked for in the chapter

I expected this to happen:
Seeing a colored change for which "would" word  I am choosing

Instead, this happened:
Not seeing any visible changes, but I know it is working from the line counter on bottom right

### Helix log

Nothing significant in catch

### Platform

Fedora

### Terminal Emulator

alacritty 0.10.1

### Helix Version

helix 22.08.1 (66276ce6)

**Comment by the-mikedavis** [comment]
This is https://github.com/helix-editor/helix/issues/3842#issuecomment-1270597054

You can try different themes. The theme you're using doesn't distinguish the primary and secondary cursors.

**Comment by EpixMan** [comment]
Thanks for info!
Is it possible to change the default theme to make it able to distinguish primary and secondary cursors ?

**Comment by the-mikedavis** [comment]
Yeah ideally the default theme should have different colors for primary cursors

**Comment by doublethink13** [comment]
Why was this closed? I still have the same problem almost a year later :slightly_smiling_face: 

I'd prefer to keep the default theme because I really enjoy it :sweat_smile: 

```bash
$ hx --version
helix 23.10 (f6021dd0)
```

**Comment by the-mikedavis** [comment]
It's a duplicate, the issue is tracked in #3842
