### ISSUE TITLE
Opening a CLI terminal program like lazygit breaks the theme

### ISSUE THREAD

**Issue by otavioschwanck** [helix-editor/helix#5173]
### Summary

Running :sh lazygit breaks the theme after going back

### Reproduction Steps

Just run :sh lazygit

### Helix log

<details><summary>~/.cache/helix/helix.log</summary>

```
please provide a copy of `~/.cache/helix/helix.log` here if possible, you may need to redact some of the lines
```

</details>

### Platform

Mac

### Terminal Emulator

Tmux

### Helix Version

Latest

**Comment by gabydd** [comment]
Helix currently doesn't have an integrated terminal see https://github.com/helix-editor/helix/issues/1976

**Comment by the-mikedavis** [comment]
Yeah, `:sh` is meant for one-off commands especially in keybindings. Running interactive programs is covered by #1976
