### ISSUE TITLE
Unable to update helix on fedora

### ISSUE THREAD

**Issue by bxffour** [helix-editor/helix#5179]
### Summary

Apparently helix requires a dependency called '/usr/bin/-S and nothing provides it so it breaks every time.
![Screenshot from 2022-12-16 02-38-36](https://user-images.githubusercontent.com/78100976/208009319-74277541-cdbc-4ad4-a89f-cd7898287c37.png)

### Reproduction Steps

 

I tried this:

1. `hx`

I expected this to happen:

Instead, this happened:

### Helix log

<details><summary>~/.cache/helix/helix.log</summary>

```
please provide a copy of `~/.cache/helix/helix.log` here if possible, you may need to redact some of the lines
```

</details>

### Platform

Linux

### Terminal Emulator

zsh

### Helix Version

22.08.1

**Comment by pascalkuthe** [comment]
The fedora copr package is not officially maintained by us (in fact no repo packages are) so this is an issue with the fedora copr package (@VarLad) and not helix itself
