### ISSUE TITLE
SQL highlighting fails for `INSERT ... SET`, `INSERT ... VALUES` with multiple records, and `GROUP_CONCAT` with `SEPARATOR`

### ISSUE THREAD

**Issue by LeoniePhiline** [helix-editor/helix#5186]
### Summary

**_Example SQL:_**

`INSERT INTO ... SET ...` syntax:

```sql
INSERT INTO some_table
  field = "String does not get highlight in INSERT SET syntax";
```

helix 22.12: String value does not get highlight:

![image](https://user-images.githubusercontent.com/22329650/208198460-1717581d-2cb4-4497-8a18-f2e81dffaddf.png)

`INSERT INTO ... (...) VALUES (...)` syntax with multiple values records:

```sql
INSERT INTO some_table
  (field)
VALUES
  ("String value"),
  ("String value");
```

helix 22.12: Values of second record do not get highlight:

![image](https://user-images.githubusercontent.com/22329650/208145728-14550424-215e-4e2e-9ddf-2892e415cddf.png)

`GROUP_CONCAT` with `SEPARATOR`:

```sql
SELECT GROUP_CONCAT(uid SEPARATOR ",") 
FROM some_table 
GROUP BY some_field;

SELECT GROUP_CONCAT(uid SEPARATOR ",") 
FROM some_table 
GROUP BY some_field;
```

helix 22.12: Separator string appears to not be expected (only `","` should be yellow):

![image](https://user-images.githubusercontent.com/22329650/208147195-9b9adb5e-0df7-4c7c-95f2-a39a8b532c9f.png)

Theme for all screenshots: `monokai_pro_spectrum`

### Reproduction Steps

 

**I tried this:**

Typed the above SQL queries (MySQL dialect) into helix.

Alternatively, copy-paste and use `:set-language sql` or write to an `*.sql` file.

**I expected this to happen:**

Proper highlighting (see GitHub highlight above).

**Instead, this happened:**

Erratic highlighting (see helix screenshots above).

### Helix log

(nothing relevant in the helix log)

### Platform

openSUSE Tumbleweed

### Terminal Emulator

konsole

### Helix Version

22.12

**Comment by archseer** [comment]
I'd start by upgrading https://github.com/DerekStride/tree-sitter-sql to the latest revision. If that doesn't fix it it'll need to be reported upstream

**Comment by pascalkuthe** [comment]
#5071 is possibly related. Although the issue itself is very different the issue was solved by upgrading the parser. Perhaohs that helps here aswell as the current version is known to be buggy

**Comment by LeoniePhiline** [comment]
Notably, like mentioned in #5071 I also experienced terrible input delays (hangs in insert mode) while working on an SQL file of only a few kilobytes. (Containing variants of the mis-highlighted syntax extracted above.)

**Comment by LeoniePhiline** [comment]
I tested with helix latest master and updated tree-sitter-sql to latet master as well (+ grammar fetch & build).
However, this lead to no improvements.

I reported the issue upstream at https://github.com/DerekStride/tree-sitter-sql/issues/67

**Comment by LeoniePhiline** [comment]
There is another weird behavior. Do you guys see this as a possible helix bug? The effect is unstable and highlighting switches between correct and incorrect just by e.g. adding white space characters or doing other non-syntax editing.

I described it in https://github.com/DerekStride/tree-sitter-sql/issues/67#issuecomment-1398812867
