### ISSUE TITLE
How do I add clangd as a binary file to the language server?

### ISSUE THREAD

**Issue by MubinMuhammad** [helix-editor/helix#5202]
I have added "clangd" to "command" in my languages.toml file:
![20221218_11h17m26s_grim](https://user-images.githubusercontent.com/101094719/208283126-6000f9ad-491f-4f67-90b7-160487f74d17.png)

And I have put the clangd binary to the `/usr/local/bin`. Is it correct?

**Comment by gabydd** [comment]
No need to add the command part clangd is already configured in the default ``languages.toml`` and should work out of the box if installed and in your PATH for future reference though it would be ``language-server = { command = "clangd" }``

**Comment by MubinMuhammad** [comment]
But, I am doing to because clangd is in version 14.0.6 (I user Arch Linux) and the package manager didn't update clang. So, I have downloaded clangd from the github releases. And now I have connect it with Helix.

**Comment by gabydd** [comment]
can you check if clangd works by removing the command part of you ``config.toml`` and then opening a c++ file and checking if ``<space>k`` works when your cursor is over a variable or function?

**Comment by MubinMuhammad** [comment]
I got the fix. I had to uninstall clang & just had to move the clang binary file to `/usr/local/bin` and  clang lib files to the `/usr/local/lib` from the github and that seems to fix it and remove the language-server line in the languages.toml file.
