### ISSUE TITLE
Editor just froze while trying to open specific file 

### ISSUE THREAD

**Issue by sioodmy** [helix-editor/helix#5212]
### Summary

Helix freezes when trying to open [this file](https://git.sioodmy.dev/sioodmy/dotfiles/src/branch/main/modules/home/waybar/default.nix)

### Reproduction Steps

 

I tried this:

1. `hx`
2. `space f`
3. select [this file](https://git.sioodmy.dev/sioodmy/dotfiles/src/branch/main/modules/home/waybar/default.nix)

I expected this to happen:
file should open duh
Instead, this happened:
my editor just froze 

### Helix log

<details><summary>~/.cache/helix/helix.log</summary>

```
please provide a copy of `~/.cache/helix/helix.log` here if possible, you may need to redact some of the lines
```
its not giving any log output
</details>

### Platform

Linux (NixOS)

### Terminal Emulator

Foot

### Helix Version

helix 22.08.1

**Comment by the-mikedavis** [comment]
Looks like this is another instance of https://github.com/helix-editor/helix/issues/4862 (the bash tree-sitter parser is stuck in `ts_parser__recover`). I'll close in favor of that issue.
