### ISSUE TITLE
Better diagnostics highlighting for Dracula theme

### ISSUE THREAD

**Issue by Chirikumbrah** [helix-editor/helix#5214]
No more ugly solid orange highlightings, just curly underlines like in the "Dark Plus" theme:)
Please add this lines to the `dracula.toml`:

 `
 ​"diagnostic.error".underline​ = { ​color​ = ​"​red​"​, ​style​ = ​"​curl​"​ } 
 ​"diagnostic".underline​ = { ​color​ = ​"​orange​"​, ​style​ = ​"​curl​"​ }
`

**Comment by archseer** [comment]
Open a pull request.
