### ISSUE TITLE
Extend pickers key mappings for the navigation

### ISSUE THREAD

**Issue by vasylnakvasiuk** [helix-editor/helix#5232]
When I'm using autocompletion popup, I can navigate forward and backward by:

1. `Tab`/`Shift-Tab`
2. `Ctrl-N`/`Ctrl-P`
3. `Ctrl-J`/`Ctrl-K`

But with file picker (or any other pickers) `Ctrl-J`/`Ctrl-K` (home finger positions on keyboard) are not working for the navigation.
Would be very useful to have these 2 additional key mappings.

**Comment by the-mikedavis** [comment]
The C-j/C-k bindings may be removed by default from the completion menu: https://github.com/helix-editor/helix/pull/5070

They were removed from the picker keymap as well: https://github.com/helix-editor/helix/pull/1792

Ideally this would be covered by the ability to remap keys for pickers (I think we have an issue for this but I can't find it).

**Comment by kirawi** [comment]
https://github.com/helix-editor/helix/issues/2757
I think https://github.com/helix-editor/helix/pull/4522 could be reused for that.

**Comment by vasylnakvasiuk** [comment]
Duplicate of https://github.com/helix-editor/helix/issues/2766, https://github.com/helix-editor/helix/issues/2000.
