### ISSUE TITLE
Feature request: Match next object on line if none under cursor

### ISSUE THREAD

**Issue by dxmh** [helix-editor/helix#5248]
Currently, in order to use the Match commands like `mi` and `ma`, the cursor needs to be on/within the object you're trying to match. 

It would be nice if the cursor would jump to the next match if there is no match under the cursor. 

This would provide an enhanced user experience, consistent with how [vim-surround](https://github.com/tpope/vim-surround) behaves, and consistent with how Helix can increment/decrement numbers without being under the cursor (since https://github.com/helix-editor/helix/pull/1778).

Example of desired behaviour, shown in vim using [vim-surround](https://github.com/tpope/vim-surround), when the cursor is at the start of the line, `vi"` visually selects inside the quotes: 

![vim](https://user-images.githubusercontent.com/60922914/208917082-cfb97bc0-43c9-4336-992d-fcd3846115b1.gif)

Example of current behaviour in Helix, when the cursor is at the start of the line, `mi"` does not match inside the quotes:

![helix0](https://user-images.githubusercontent.com/60922914/208917101-dbf7c0b2-5681-4f7e-9099-61b9c8015c92.gif)

**Comment by Ordoviz** [comment]
This request was rejected in #3871 because Helix's keybindings favor predictability over terseness.

**Comment by dxmh** [comment]
Ah, thank you for pointing that out @Ordoviz. I wasn't aware of #3871.

@the-mikedavis also mentioned on the Matrix space:

> There's a PR working to remove that behavior from C-a/C-x https://github.com/helix-editor/helix/pull/4123. Jumping to the next object really complicates the behavior when you're using multiple selections and complicates the code a bunch. In general you can use textobjects like `]f` to jump to the next textobject instead of this automatic jumping behavior
