### ISSUE TITLE
`f`, `t`, `F`, and `T` no longer select

### ISSUE THREAD

**Issue by Omnikar** [helix-editor/helix#527]

**Comment by sj4nes** [comment]
I'm seeing this as well.  The cursor moves to the target but the selection does not drop the anchor.

**Comment by cessen** [comment]
This might be my fault with #376.  What's the expected behavior with those commands?  Is it supposed to leave the anchor in place?

**Comment by Omnikar** [comment]
It seems that it did stop working after #376 was merged. The expected behaviour is that it selects from the original cursor position to the new position, including both.

**Comment by cessen** [comment]
Okay, cool.  I'll fix that.

**Comment by cessen** [comment]
Hmm.  So, in the commands it looks like there are both extending and non-extending variants of those commands:
https://github.com/helix-editor/helix/blob/3fda350494449bf5909a0b47f9e2f593fbe615ad/helix-term/src/commands.rs#L693-L763

Previously I think they were all extending, which didn't make sense (that just meant each command had a duplicate with a different name).  So I fixed that.  But I guess in the default keymap normal mode binds to the non-extending commands, and select mode binds to the extending commands.  I think that makes sense?

**Comment by cessen** [comment]
Ah, investigating further, it looks like my "fix" missed the intent.  The extend variants preserve the anchor, whereas the non-extend versions select from where the head was to the next matching char.

I'll make a PR to fix my "fix" shortly.

**Comment by sj4nes** [comment]
🎉 works for me.
