### ISSUE TITLE
xx works ok; x2x works err

### ISSUE THREAD

**Issue by 6lj6** [helix-editor/helix#5270]
In the doc, it said: 

> x | Select current line, if already selected, extend to next line

but
1. x + x, works ok
2. x + 2x, works err, it didn't select 3 lines, it did select 2 lines.
3. 3x, works ok.
4. 2x + 2x, works err, it didn't select 4 lines, it did select 3 lines.

### Platform
Debian 12 testing, Konsole, helix 22.12 (bdeefbfb)

**Comment by gabydd** [comment]
nice catch I think this brings up some issues in the logic of extend_line

end is set to being the endline + count
https://github.com/helix-editor/helix/blob/24c3b00d10858a02c6c1c351a7509e204c2bc647/helix-term/src/commands.rs#L2063

and end is checked when we want to see if the line is selected but when count is more then one then ``range.to()`` won't match even if the whole line is selected
https://github.com/helix-editor/helix/blob/24c3b00d10858a02c6c1c351a7509e204c2bc647/helix-term/src/commands.rs#L2069

it then goes into this else block
https://github.com/helix-editor/helix/blob/24c3b00d10858a02c6c1c351a7509e204c2bc647/helix-term/src/commands.rs#L2077-L2081
where the end of the selection will be one line less then it should be (keep in mind this case is important for when a line isn't fully selected cause you need to select the line and then you can select more so it should be one line less then count)

---

this is a pretty easy fix, I can definitely make a pr for it but it's definitely a place where someone who is interested in contributing but doesn't know where to start could start(I am willing to help on element or github if you have any trouble)

though this seems similar to #2112 fixing this actually shouldn't have the problems brought up there

**Comment by sou-chon** [comment]
I am interested in having a go if no one else is!

**Comment by 6lj6** [comment]
Since I am a new user of helix and rust, it is not possible to merge my code to master of helix, for now.

The reason I file this issue is for logging a record, cuz I see that there is a keymap discussion, so the function of <kbd>x</kbd> may be overridden.  

From now, It acts like a selection mode when x works with x, but it acts like a motion when x works with w. An mixture of 2 patterns, which is weird.

**Comment by gabydd** [comment]
> I am interested in having a go if no one else is!

was on a plane and got bored so decided to fix this I'll submit the pr in a couple minutes
