### ISSUE TITLE
:dq => Discard and Quit

### ISSUE THREAD

**Issue by 6lj6** [helix-editor/helix#5271]
> <kbd>:wq</kbd> => Write changes and Quit

What if <kbd>:dq</kbd> => Discard changes and Quit ?

* If we have <kbd>:dq</kbd>, then
    1. it is more consistent with <kbd>:wq</kbd>
    2. it is brain-friendly, first we discard changes, then we quit Helix. consistent with time logic.
    3. it is more memorable, Discard, Quit.
    4. it is small, consumes 2 keys( :q! consumes an extra Shift), LESS IS MORE!
    6. it reminds you that how you handle the changes!
    7. it is more friendly to new users.
* On the opposite, the <kbd>:q!</kbd>
    1. it is not consistent with <kbd>:wq</kbd>
    2. it is brain-fucker, quit! quit! quit!
        1. once this concept occurs in my brain, it made users unpeaceful, we need calm down to code, not a hurry.
        2. It need you to think more: the changes is discarded!
    3. it is not memorable, a another new pattern:  xyz!
    4. it is a big waste, it consumes an extra Shift, help our painful tired fingers.
    6. it hide the facts that you discarded changes( which is really risky)
    7. it add the difficulty to new users to memory an extra weird command.
---

A more detailed logical process
```
software
    to be
        hx
        hx FILE
    not to be
        :q
            if no change => :q
            if change, its quit need handle text's change
                discard change => :dq
                write change => :wq
```

**Comment by dead10ck** [comment]
To me, `:dq` would make it less obvious that you're doing a potentially destructive command. The `!` is a really obvious visual indicator that what you're about to do requires extra thought.

Also many users come from vim, and familiarity helps new users transition.

**Comment by 6lj6** [comment]
! is an exclamation, it works for its former word, which in this case is quit.

It means Quit! Quit! I wanna Quit!  Stop warning me just quit! A strong and angry order about the action Quit itself.

It's hard for me to  link this strong feeling to destructive operation Discard...

Oh I even forget that how much I paid for quitting helix——I Discard the changes I just made!

Anyway, thanks your sharing of a different view.

**Comment by 6lj6** [comment]
2 points updated:
1. At the beginning, I used :q! , then I tried to :qw, failed!
2. Write the changes is also an risky operation, that means you lost the old text. So if :wq is not :qw, then how :dq is missing.

**Comment by dead10ck** [comment]
Sorry, I'm having a hard time understanding you. Thanks for your suggestion, but I'm going to close this.

**Comment by 6lj6** [comment]
Clean up the trash in your mind, you will then realize what is better.

With you tyrant, helix won't go further.

I listed reasons in many aspects, and you close it by your willing without strong reasons.

That's great, bye

**Comment by archseer** [comment]
Political party? You might be on the wrong website, this is Github, a website for open source code project development.

I'm sorry we rejected your proposal but verbal abuse is not okay. Being rude is only going to make it less likely I look at the issue at all.

**Comment by 6lj6** [comment]
He dare to abuse the rights closing a reasonable issue by personal willing, that's called what is rude.

And fight back on unreasonable behavior is called Justice.

You mixed up the closing issue and closing issue by willing, that's two things.

Also, you are a freeman, you can talk or not, you can leave or not, you can look at the issue or not. It's your rights.
