### ISSUE TITLE
Python autocomplete inside of function

### ISSUE THREAD

**Issue by jonas-w** [helix-editor/helix#5275]
### Summary

Can't really tell if it really is a problem with helix or just a configuration problem. (Sorry in advance if it isn't a helix issue)

Basically when I'm inside of a function and write something inside of it for example:
```python
# Cursor location is "|"
print(urllib.|)
```
i only see the docstring for `print`, although i want to have autocompletion for `urllib`.

Thanks

## In helix with pylsp default config:
[![asciicast](https://asciinema.org/a/547671.svg)](https://asciinema.org/a/547671)

## For comparison in lvim with pylsp default config (only installed for this):
[![asciicast](https://asciinema.org/a/547673.svg)](https://asciinema.org/a/547673)

### Platform

Archlinux

### Terminal Emulator

foot

### Helix Version

helix 22.12

**Comment by the-mikedavis** [comment]
I wonder if the signature help popup is covering the completion menu? If you hit C-c it will dismiss the signature help popup

**Comment by jonas-w** [comment]
@the-mikedavis that seems to be the problem. But after every autocompletion it pops up again, kind of annyoing. Is the placement something that can be configured or what would be the best way to solve this issue?

**Comment by the-mikedavis** [comment]
There's an issue discussing this: https://github.com/helix-editor/helix/issues/3821

I'll close in favor of that issue

**Comment by jonas-w** [comment]
Oh sorry for the dupe, thank you!
