### ISSUE TITLE
Kanagawa theme does not follow the original creators guidelines

### ISSUE THREAD

**Issue by linuscm** [helix-editor/helix#5280]
Implementation of proper colors for git diffs are of course missing, as it is a new feature, however there are a few other things such as:

- The model ":" suggestion menu using the same color as the background, and general menus using the wrong colors
- indent-lines not using sumiInk4 (#54546D)
- Cursor line having no background color, making it harder to see which line you are currently on (should use sumiInk3 #363646)

**Comment by leonqadirie** [comment]
Coincidentally, I opened a related PR (#5273) just some hours ago.
Will add the indent-guides to it.

**Disclaimer:**
@zetashift explicitly stated this was not a 1:1 port, so their interpretations of the theme might differ.

**Comment by linuscm** [comment]
Oh yeah i'm well aware saw it in the comments, but some choices just feel a bit off like the lack of a cursorline bg color and somewhat hard to see cursor.

Really just a small issue and only bring it up due some acquaintances having the same issue, It might be better to leave certain self interpretation/preferences up to adjustments within your own config

**Comment by leonqadirie** [comment]
TBF when the theme was ported there was no cursorline yet I think.

Most of my additions/changes incl. the cursor should be in line with the original.
Feel free to check my PR, feedback regarding the menu colors would be great.

**Comment by linuscm** [comment]
Ah ok fair enough, gonna look at it further later, but from a first glance your PR looks like it makes some good adjustments and basically fixes the main issues i have myself 👍
