### ISSUE TITLE
Add an example for WORDs to the tutor

### ISSUE THREAD

**Issue by matklad** [helix-editor/helix#5284]
https://github.com/helix-editor/helix/pull/5247 split off "WORDS and words" section inn thee tutor:

https://github.com/helix-editor/helix/blob/1af76b738dd5bdae14b025d07d3001c4ad23e071/runtime/tutor#L265-L286

It would be great to add some example here!

**Comment by woojiq** [comment]
@the-mikedavis maybe it needs to be closed since the pr with the changes was merged?
