### ISSUE TITLE
Async formatting

### ISSUE THREAD

**Issue by kevinsjoberg** [helix-editor/helix#53]
Whenever I save a file (`:write`) with LSP enabled (e.g., [solargraph](https://solargraph.org) for Ruby or [rust-analyzer](https://rust-analyzer.github.io) for Rust) the editor halts for 1-2 seconds until finally finishing. This behaviour isn't present when LSP is disabled.

**Comment by archseer** [comment]
This is because we try to `:format` via the LSP before saving. I was afraid this would be an issue on a slower language server (you can also notice it before rust-analyzer fully boots up). Need to handle that better, probably by making it opt-in per language.

**Comment by kevinsjoberg** [comment]
Would it be possible to format the code asynchronously? It's kind of unexpected that it's a synchronous operation blocking the UI.

If not, I think it makes sense for you to be able to opt out. 👍

**Comment by archseer** [comment]
I think you would likely run into issues if formatting took a while to run async while you made further text edits.

I'll add a config option to enable it only for certain languages.

**Comment by kevinsjoberg** [comment]
Yeah, I guess it depends. I've seen it done both ways. If done asynchronously, one could discard the formatting if the buffer changed in between saving the file and the action actually completing.

**Comment by jneem** [comment]
I think it does make sense to discard the formatting in that case, but one annoying thing is that you want the formatting to be saved. I guess you'd need to:

1. make a clone of the document synchronously (cheap, because Ropes clone cheaply)
2. spawn a "format" task that computes the formatting changes, then spawns a "save" task and returns the formatting changes
3. the "save" task applies the formatting changes to the cloned document and then saves it
4. the main task gets the formatting changes from the format task and applies them as long as the document hasn't changed.

I could try implementing that if it sounds reasonable.

**Comment by pickfire** [comment]
Same noticeable delay when I press `gd` waiting for lsp. It doesn't automatically do the task even though lsp starts up. Should have sort of queuing mechanism.

**Comment by jneem** [comment]
Is there no interest in the async formatting version? I like auto-format on save, but I'd also like it not to block the editor...

**Comment by archseer** [comment]
Sorry about that, I missed the comment! I think some of this overlaps with https://github.com/helix-editor/helix/pull/177#issuecomment-857300740

I'd be interested in this, but the `async` aspects of `helix-term` still need some work. It's hard to keep a reference in a spawned task without blocking, you'd probably need some sort of a callback mechanism similar to how the `LspCallbacks` hack works (you keep a `DocumentId`, the callback gives you a `&mut Editor` that can be used to look up the doc again).

**Comment by archseer** [comment]
> Same noticeable delay when I press `gd` waiting for lsp. It doesn't automatically do the task even though lsp starts up. Should have sort of queuing mechanism.

This is because rust-analyzer takes some time to index before it starts responding to queries. `workDone` events from LSP will give us a way to cancel these types of queries, at the moment we time out after `2s` and then discard the data once received later.

**Comment by archseer** [comment]
#285 now solves this, thanks to @jneem for the implementation!
