### ISSUE TITLE
Restart language server when changing document language

### ISSUE THREAD

**Issue by the-mikedavis** [helix-editor/helix#5300]
`Document::set_language` currently only changes the syntax and highlighting parts of a document. If the language server configuration or binary changed, the language server is not terminated or restarted. For example, `:set-language text` on a rust file running rust-analyzer will not close the rust-analyzer session - you will still see completion and diagnostics.

Unless the language server configuration is the same before and after, `Document::set_language` should close the open language server (if any) and start the new language server for the new configuration.

(In the long-run, we may also want to look into using [`didChangeConfiguration`](https://microsoft.github.io/language-server-protocol/specifications/lsp/3.17/specification/#workspace_didChangeConfiguration) for language servers that support it. [ref](https://github.com/helix-editor/helix/pull/5239#issuecomment-1364671287))

**Comment by the-mikedavis** [comment]
`Document::set_language` should also probably call `Document::detect_indent_and_line_ending` since those values can change when the `Document.language` field changes

**Comment by pascalkuthe** [comment]
I think this can be closed, see https://github.com/helix-editor/helix/pull/8949#issuecomment-1847824522
