### ISSUE TITLE
:open commands starting on current file directory

### ISSUE THREAD

**Issue by otavioschwanck** [helix-editor/helix#5301]
Like find-files for emacs.  Instead of starting on the :pwd, starts on the current file directory.  Awesome to quick change to files in same directory / create new files.

**Comment by the-mikedavis** [comment]
There's a similar issue for a file picker that uses the buffer's directory https://github.com/helix-editor/helix/issues/3052

**Comment by scajanus** [comment]
In vim, I quite often use `:e %:h`, but it seems helix doesn't have anything similar yet?

**Comment by bcspragu** [comment]
Another vote for this. In my config, I have

```toml
'space' = { c = 'file_picker_in_current_buffer_directory' }
```

which I use all the time. I'd love to be able to either create a file directly from the file picker (e.g. all the options in the menu become directories and I select one, then enter a file name), or just have an `:open` variant that opens/creates relative to the current buffer's directory.

If either of these are approaches are desirable, I can attempt to implement one

**Comment by pascalkuthe** [comment]
https://github.com/helix-editor/helix/issues/5301
