### ISSUE TITLE
Many themes fail to show selection cycling in the Helix tutorial

### ISSUE THREAD

**Issue by x448** [helix-editor/helix#5305]
### Summary

In the Helix tutorial, section "10.1 CYCLING AND REMOVING SELECTIONS" some themes create the impression of Helix being buggy or the user doing something wrong because nothing happens visually when following instructions to press `(` or `)` key.

Themes that work:
- dark_plus
- emacs

Themes that fail to visually indicate selection changing:
- acme (light)
- ayu_light
- ayu_dark
- default
- and many others...

### Reproduction Steps

 

I tried this:

1. `hx --tutor`
2.  follow instructions in section 10.1 CYCLING AND REMOVING SELECTIONS

I expected this to happen:

Pressing `(` or `)` key should show selection changing.

Instead, this happened:

Pressing `(` or `)` key doesn't visually show selection changing (in many themes like ayu_light, ayu_dark, or default).

Workaround is to use dark_plus or emacs theme and avoid other themes that don't work.  New users and reviewers may get the impression Helix is buggy or that they're doing something wrong.

### Helix log

<details><summary>~/.cache/helix/helix.log</summary>

```
please provide a copy of `~/.cache/helix/helix.log` here if possible, you may need to redact some of the lines
```

</details>

### Platform

Debian "bullseye" in Windows 11 WSL2

### Terminal Emulator

Windows 11 Terminal

### Helix Version

helix 22.12 (1af76b73)

**Comment by the-mikedavis** [comment]
This is discussed in https://github.com/helix-editor/helix/issues/3842 and https://github.com/helix-editor/helix/issues/1833
