### ISSUE TITLE
`editor.bufferline = "multiple"` should be default

### ISSUE THREAD

**Issue by yashpalgoyal1304** [helix-editor/helix#5316]
> > It could be nice to have an option that, similarly to some other editors, only shows the bufferline when there is more than one buffer to display in it.
> 
> That seems like good default behavior without needing a config option.
>
> \- @ _sudo rm rf bin_ at https://github.com/helix-editor/helix/pull/2759#issuecomment-1154153168

* i came here to say exactly that, `multiple` should be default?!
* i'd be interested in posting a pr for this if that's wanted

### Reference:

* https://github.com/helix-editor/helix/blob/ebaf01924dd0e6251535d88ec0a2a00e88680d6b/book/src/configuration.md?plain=1#L58
* Front-end facing site:  [`[editor]` Section][editor]

<details>

Key | Description | Default
-- | -- | --
[`bufferline`] | Renders a line at the top of the editor displaying <br/> open buffers. Can be `always`, `never` or <br/> `multiple` (only shown if more than one buffer is in use) | `never`

</details>

[editor]: https://docs.helix-editor.com/configuration.html#editor-section
[`bufferline`]: https://docs.helix-editor.com/configuration.html#:~:text=%5B%5D-,bufferline,-Renders%20a%20line
      

[changelog]: https://github.com/helix-editor/helix/blob/master/CHANGELOG.md#2212-2022-12-06
[Wrapping up]: https://helix-editor.com/news/release-22-12-highlights/#wrapping-up
[Release 22.12 Highlights]: https://helix-editor.com/news/release-22-12-highlights/

**Comment by univerz** [comment]
https://github.com/helix-editor/helix/pull/2759#issuecomment-1165473906

**Comment by yashpalgoyal1304** [comment]
> it encourages the wrong workflow (treat views == tabs), it's just a less featureful version of space+b buffer list
> I understand people are used to sublime/vscode-like tabs.
> 
> @ archseer at https://github.com/helix-editor/helix/pull/2759#issuecomment-1165473906

* so, helix doesn't have tabs then? 

* i have see at least one more TUI editor which had tabs feature enabled (iirc, by default)... 
* forget sublime/vscode, even the Turbo-C had tabs afair

**Comment by the-mikedavis** [comment]
Tabs are covered in https://github.com/helix-editor/helix/issues/2295. The bufferline is a way to display all currently open buffers but tabs allow you to have different sets of open buffers.

**Comment by yashpalgoyal1304** [comment]
as i am not much proficient in helix at the moment, i am closing this for the moment. 

if i still feel its need after i become good in helix, then i'll reopen.


meanwhile, if someone else wants to reopen this, feel free.

**Comment by yashpalgoyal1304** [comment]
ohwww, so, unsaved buffers are discarded???

like i was in a buffer? i opened a new buffer via say `:tutor`, then i `gp` to go to previous buffer... the `[scratch]` buffer corresponding to tutor is now gone...

is that expected?

**Comment by yashpalgoyal1304** [comment]
i retried, and no, the previous buffer is staying there. 

but i am sure it was getting dumped...

i am thinking it is a bug. but can't reproduce it consistently

**Comment by yashpalgoyal1304** [comment]
i think it's the unmodified buffer that gets dropped...



https://user-images.githubusercontent.com/19423063/216427885-18f0cbc5-4d57-4b85-a538-440cb1dc01c8.mp4

**Comment by yashpalgoyal1304** [comment]
This https://github.com/helix-editor/helix/discussions/5257 _might_ help me understand difference between buffers and tabs a bit more

**Comment by gabydd** [comment]
Some definition first a buffer is the underlying representation of a file(which is called a document in the code), there is one buffer per file which but there can be multiple different windows(views in code) which are the vsplits and hsplits, these can look at the same buffer and lets you have different positions and selections for the same file

This thing though is specific to the scratch buffers where if they haven't been edited they get removed when you switch the buffer in the window to a buffer that is not the unmodified scratch buffer, the tutor is basically a special scratch buffer and as you didn't modify it, it got removed when switching to a different buffer.

**Comment by sgon00** [comment]
+1

**Comment by yashpalgoyal1304** [comment]
hi @sgon00 
yes, to us newcomers to helix, bufferlines seem to be like tabs. But they are not... see the just above well documentation by @ gabydd in how buffers work - clearly u won't expect that to happen with tabs, right :smiley:. This is also mentioned by @ archseer in the comment which i am quoting below.

> it encourages the wrong workflow (treat views == tabs), it's just a less featureful version of space+b buffer list. But I understand people are used to tabs.
>
> \- @ archseer at https://github.com/helix-editor/helix/pull/2759#issuecomment-1165473906
\- @ univerz at https://github.com/helix-editor/helix/issues/5316#issuecomment-1367633294

**Comment by sgon00** [comment]
Hi @yashpalgoyal1304 
Thank you very much for your reply, but I completely disagree with you. Who cares about the differences btw buffers and tabs? At least, I don't care. Whatever you call it, I just want to see an opened editors/tabs/buffers, that's all. If they are different, that's fine. As an end user, I don't care. When I take a picture with a phone, all I care is the result of the picture and I don't care what the model of the phone camera is as an end user. Developers suggest to use `SPACE+b`, regardless that is two buttons action, I want to see them all the time. SPACE+b will not show them all the time, but `bufferline = "multiple"` can. That's the difference. I don't care what model of camera inside my phone is, all I care is the picture result is good. All I want is a list on the top, I don't care what that list is called and what that list is.

> hi @sgon00 yes, to us newcomers to helix, bufferlines seem to be like tabs. But they are not... see the just above well documentation by @ gabydd in how buffers work - clearly u won't expect that to happen with tabs, right smiley. This is also mentioned by @ archseer in the comment which i am quoting below.
> 
> > it encourages the wrong workflow (treat views == tabs), it's just a less featureful version of space+b buffer list. But I understand people are used to tabs.
> > - @ archseer at [#2759 (comment)](https://github.com/helix-editor/helix/pull/2759#issuecomment-1165473906)
> > - @ univerz at [#5316 (comment)](https://github.com/helix-editor/helix/issues/5316#issuecomment-1367633294)

**Comment by yashpalgoyal1304** [comment]
yes, it's perfectly fine. I don't care about it either haha :smiley:

the thing is, the tab feature is not there yet. when the tabs will arrive, sure we can have discussions on having the tab bar enabled by default.

devs have a point of not enabling the buffer bar by default - as if it's enabled by default, they'll have to see users like you and me complaining about buffers not working well etc. etc... and they'll have to clarify it again and again.
