### ISSUE TITLE
Better Global Search

### ISSUE THREAD

**Issue by happysmile12321** [helix-editor/helix#5323]
The goal of global search is search some contents in project and jump to that file that location and then edit, this is the basic of use of global search. 
As for me, the only needs for me to use global search is I came to a new project, which I couldn't have many time to familier with that.I am a frontend developer,so I prefer to search in the new project the text that  the project show me,this is happended usually.
So use lot function's is for me, that I have some requirement for the global search.
1. It can search multiple lines.
2. It can remember what I input last when I twice call it.
3. It have a list view that I can just jump to it.
As your guys effort, 3 is perfect achived, but 1 and 2 is not.
the reason I want 2 is when I searched content, perhaps in my project,there are so many repeat content in a lot of file(usually happend, cannot be avoid.), the global search UI window is not enough to show what I want to see, I  prefer want to jump into it to see if this is wanted file, then if I found I don't want to edit this file, I perhaps want to enter global search window again and chose the next file to check if it is the file I want edit.This requirement is happend very frequently when you not familier with the project very much, usually It happend to the real work.
so I want to see a better enhancer to global search in this project.

**Comment by the-mikedavis** [comment]
Is this covered by https://github.com/helix-editor/helix/issues/196?

You can re-open the last picker (file picker, buffer picker, global search, etc.) with `<space>'`

**Comment by happysmile12321** [comment]
yes,that's it.Thanks.
