### ISSUE TITLE
Allow multiple language servers for a language

### ISSUE THREAD

**Issue by arendjr** [helix-editor/helix#5336]
I am not sure if what I’m asking for is already possible, but in order to configure the Rome language server (https://rome.tools) for TypeScript correctly, I think Helix needs to provide a way to configure multiple language servers to be used for a single language.

Rome actually does provide instructions on how to configure their language server with Helix: https://github.com/rome/tools/blob/main/editors/helix/manual.md

But after following those instructions, standard TypeScript functionality such as “goto definition” doesn’t work anymore, presumably because Helix doesn’t understand it should *also* still use the regular TS language server.

Related issue as reported against Rome: https://github.com/rome/tools/issues/4107#issuecomment-1367312352

**Comment by archseer** [comment]
https://github.com/helix-editor/helix/pull/2507

**Comment by arendjr** [comment]
Just my luck, thanks! :D
