### ISSUE TITLE
:sh tab completion cycles through directory names only, not file names or program names

### ISSUE THREAD

**Issue by pbnj** [helix-editor/helix#5338]
### Summary

Typing `:sh` followed by <kbd>tab</kbd>, helix shows and cycles through directory names only; it does not show files or cycle through them and it does not cycle through program names.

Here is a GIF demo:
- `:open` shows the current files & folders available
- `:sh` only sees folders
- A common use-case is to `:sh <program> <file_or_folder>` but lack of tab completion for program names and file names cripples the `:sh` feature.

![out](https://user-images.githubusercontent.com/6811830/209994710-b56d3905-aa65-438c-9d5a-3a708e2d1f6b.gif)

### Reproduction Steps

In helix:

- `:sh <tab>`

### Helix log

N/A

### Platform

macos

### Terminal Emulator

terminal.app, chrome secure shell

### Helix Version

helix 22.12 (96ff64a8)

**Comment by the-mikedavis** [comment]
It's currently configured to use the directory completer: https://github.com/helix-editor/helix/blob/63dcaae1b9083396fb3faaef9eaa2421f7e48fb9/helix-term/src/commands/typed.rs#L2341

I'm not sure why that completer is used vs the filename completer though (`completers::filename`)

**Comment by flaviu-toader** [comment]
What would be the expected behavior here? I would imagine also a completer that looks through things the user has in their `$PATH` to be useful.
