### ISSUE TITLE
Please allow the autocomplete popup box to execute the first suggestion with an "ret" press

### ISSUE THREAD

**Issue by effinsky** [helix-editor/helix#5343]
Hello -- seems like a simple quality of life change for those who, like I, are used to going up and down popups with j and k or <C-j> and <C-k> and accepting options with a press of "ret". This goes for navigating menus in general but I have personally found it a bit jarring to be unable to do this. If possible, please add :)

**Comment by the-mikedavis** [comment]
This behavior was removed in https://github.com/helix-editor/helix/pull/1704. If ret accepts the first item in the completion menu, you can't insert newlines while the completion menu is open. This makes editing very unpredictable for some languages.

I think the ideal way to fix this might be to allow menu keybindings to be configurable.

**Comment by effinsky** [comment]
Absolutely -- I wouldn't say even make this default if folks don't want that. Perhaps just include a config option. In my bvim cmp opt I just have this little bit. Never had trouble with this combination: 

<img width="737" alt="Screenshot 2022-12-30 at 19 28 13" src="https://user-images.githubusercontent.com/54535543/210101611-080d3e09-0bf4-4a8c-9cc4-07af72eb35ba.png">

**Comment by mnpqraven** [comment]
I second this, having a way to automatically choose the first autocomplete option would be a great boon to people who were already using that function in neovim. But if `ret` becomes problematic as a default, how about enabling [picker commands](https://docs.helix-editor.com/keymap.html#picker) as normal commands so people can bind them in the config for example:
```
[key.insert]
C-o = ["next_entry", "select_entry"]
```
This way you would be able to select the first autocomplete when hitting Ctrl O

**Comment by pascalkuthe** [comment]
We actually went the other way here. You can select the first item by just hitting tab once (or c-n) at that point you can just keep typing. 

I don't see us adding a soecical config flag or similar. If you want a different mapping you have to wait for #5505

**Comment by tommasoclini** [comment]
Are we going to get a config flag for this? It's really annoying to have to press tab for the first suggestion.
