### ISSUE TITLE
Make diagnostics messages use curly unerline in built-in themes

### ISSUE THREAD

**Issue by blt-r** [helix-editor/helix#5361]
Currently many of the built-in themes have something like:
```toml
diagnostic = { modifiers = ["underlined"] }

error = "red"
warning = "yellow"
info = "sky"
hint = "teal"
``` 

I think it would be better to replace it with:
```toml
"diagnostic.hint" = { underline = { color = "teal", style = "curl" } }
"diagnostic.info" = { underline = { color = "sky", style = "curl" } }
"diagnostic.warning" = { underline = { color = "yellow", style = "curl" } }
"diagnostic.error" = { underline = { color = "red", style = "curl" } }

error = "red"
warning = "yellow"
info = "sky"
hint = "teal"
```

Just use curly underline for all of them and use the same color they are using for `error`, `warning`, `info`, and `hint` properties. That's what default theme is doing and it should be pretty easy to do. 

I think it should be done to all themes that  are underlining their diagnostics messages.

**Comment by archseer** [comment]
Some themes had this fixed, but most of them pre-date curly underline support.
