### ISSUE TITLE
Support views in Prisma schema language files

### ISSUE THREAD

**Issue by pimeys** [helix-editor/helix#5385]
We'll be adding the minimal support for a new top level keyword `view` in the next version ([tracking issue](https://github.com/prisma/prisma/issues/17114)).

The LSP will handle the validation and all, but we should have proper syntax highlighting for the following kind of constructs:

```prisma
view Foo {
  val Int @unique
}
```

They work exactly like models, so I think in the end this is adding one more keyword to the tree-sitter file.

**Comment by the-mikedavis** [comment]
This should be posted to the tree-sitter grammar repository https://github.com/victorhqc/tree-sitter-prisma. This will need changes to `grammar.js` in that repository

**Comment by pimeys** [comment]
Created an issue: https://github.com/victorhqc/tree-sitter-prisma/issues/40

**Comment by victorhqc** [comment]
👋 a new version was published, now the reference to `tree-sitter-prisma` should be updated in helix
