### ISSUE TITLE
Page up / Page down in file picker

### ISSUE THREAD

**Issue by bcatalfo** [helix-editor/helix#5391]
### Summary

When I press space + f to enter the file pick and then use ctrl u ctrl d or pageup pagedown to try and preview the next page of the file it takes me to a different file instead of taking me to the next page of the current file in the preview.

### Reproduction Steps

I am new to ascinema. I tried to get it to show my keypresses but it wouldn't. https://asciinema.org/a/nLLWS3OiEAyMxWuEQF9J2pd4E

### Platform

Linux (Endeavour OS)

### Terminal Emulator

alacritty

### Helix Version

helix 22.12 (1af76b73)

**Comment by the-mikedavis** [comment]
This is expected: PageUp/C-u and PageDown/C-d page the picker results rather than the preview.

Adding a way to scroll the picker preview is covered in https://github.com/helix-editor/helix/issues/4102
