### ISSUE TITLE
Auto-completion doesn't work with multiple cursors

### ISSUE THREAD

**Issue by Ne0nWinds** [helix-editor/helix#5392]
https://user-images.githubusercontent.com/36315399/210473803-fe4f7d11-200d-4851-a859-09be7735295f.mp4

It seems like auto-completion only works on the main cursor. In the example of the video I provided, I think it'd be more intuitive if `GL_ELEMENT_ARRAY_BUFFER` was auto-completed on both lines instead of just one

**Comment by kirawi** [comment]
What version are you using? This was fixed in 22.12
