### ISSUE TITLE
Consider using ruff-lsp instead of pylsp as the default language server for Python

### ISSUE THREAD

**Issue by schneiderfelipe** [helix-editor/helix#5399]
It's my view that [ruff-lsp](https://github.com/charliermarsh/ruff-lsp) can provide a nicer user experience than [pylsp](https://github.com/python-lsp/python-lsp-server) mostly because [ruff](https://github.com/charliermarsh/ruff) is very fast (written in Rust), so why not [switch to it by default](https://github.com/helix-editor/helix/blob/0dbee9590baed10bef3c6c32420b8a5802204657/languages.toml#L475-L485)? [Configuration for Helix is available here](https://github.com/charliermarsh/ruff-lsp#example-helix).

**Comment by kirawi** [comment]
Never heard about ruff before, cool!

**Comment by Ordoviz** [comment]
It's not yet time to switch to ruff-lsp: it lacks basic features (such as "goto definition") and [is meant to be used alongside another LSP](https://github.com/charliermarsh/ruff-lsp/issues/23). Also, pylsp recently gained support for ruff via [a plugin](https://github.com/python-lsp/python-lsp-ruff).

**Comment by thomkeh** [comment]
To me, [pyright](https://github.com/microsoft/pyright) is the obvious choice given that it's the default in VSCode. It's also the default in nvim-lspconfig: https://github.com/neovim/nvim-lspconfig#quickstart

**Comment by the-mikedavis** [comment]
Adding alternate language server configs to the language server installation wiki seems like an easy win for this: https://github.com/helix-editor/helix/wiki/How-to-install-the-default-language-servers

For a similar case there's a [deno config](https://github.com/helix-editor/helix/wiki/How-to-install-the-default-language-servers#deno) mentioned even though typescript-language-server is the default for JS/TS languages

**Comment by schneiderfelipe** [comment]
> Adding alternate language server configs to the language server installation wiki seems like an easy win for this: https://github.com/helix-editor/helix/wiki/How-to-install-the-default-language-servers

Excellent! [I just did it](https://github.com/helix-editor/helix/wiki/How-to-install-the-default-language-servers#ruff).

> It's not yet time to switch to ruff-lsp: it lacks basic features (such as "goto definition") and [is meant to be used alongside another LSP](https://github.com/charliermarsh/ruff-lsp/issues/23). Also, pylsp recently gained support for ruff via [a plugin](https://github.com/python-lsp/python-lsp-ruff).

I'll add some instructions on how to use [python-lsp/python-lsp-ruff](https://github.com/python-lsp/python-lsp-ruff) as well soon.
