### ISSUE TITLE
Option to cycle through signature help signatures

### ISSUE THREAD

**Issue by Kenneth-Mata** [helix-editor/helix#5403]
I'm using omnisharp and i get the documentation popup which shows the documentation for the main implementation of the method but there doesn't seem to be a way to cycle through the different overloads. 

![2023-01-04_14-18](https://user-images.githubusercontent.com/92641443/210612921-2ae35989-2ca4-4908-9a58-828b49ab0f85.png)

**Comment by the-mikedavis** [comment]
Ah interesting, I bet those are keybindings to cycle through the signatures list: https://microsoft.github.io/language-server-protocol/specifications/lsp/3.17/specification/#signatureHelp

That would also be useful for languages with variadic functions where you might want to see a signature for a function with higher arity

**Comment by Kenneth-Mata** [comment]
Was curious how is this one going, today i happened to be looking at neovim and instead of cycling through the different signatures, they just call the full list and [display it](https://github.com/neovim/neovim/pull/11920)

**Comment by jabcross** [comment]
It works fine on VSCode with clangd, giving you the ability to cycle through the implementations. Is this currently in the roadmap? I am interested in implementing this, as it's one of the only sticking points preventing me from adopting helix for my C++ work.

**Comment by Armando-CodeCafe** [comment]
Bumping this because in csharp this is quite a hassle to constantly have to google the documentation of certain functions just to find out the overloads
