### ISSUE TITLE
Reduce theme coloring delay in picker preview

### ISSUE THREAD

**Issue by NickCondron** [helix-editor/helix#5409]
There is a slight delay before the theme/highlighting is applied to the preview in the picker.

Helix version: 22.12

https://user-images.githubusercontent.com/10557166/210699053-ea5f1236-0ab0-449a-846a-384b198a184d.mp4

**Comment by kirawi** [comment]
This is managed by the `idle-timer` in your config

**Comment by NickCondron** [comment]
> This is managed by the `idle-timer` in your config: https://docs.helix-editor.com/configuration.html

Ok, but why should `idle-timeout` be controlling the highlight delay? `idle-timeout` seems to be for handling user commands. What if I want to increase my `idle-timeout` for input leniency, but I still want immediate highlighting in the picker?
