### ISSUE TITLE
Cannot map Ctrl-Shift-<letter>

### ISSUE THREAD

**Issue by Plasma-Vortex** [helix-editor/helix#5422]
### Summary

I would like to create a shortcut for `Ctrl-Shift-J`. I've tried adding

```
[keys.normal]
"C-J" = "insert_mode"
"C-S-j" = "insert_mode"
"C-S-J" = "insert_mode"
```
to my `config.toml` file, but none of these seem to work.

Other key combinations like `Alt-Shift-J` and `Ctrl-j` seem to work fine in helix, just not `Ctrl-Shift-<letter>`. I've reproduced this issue with multiple letters (J, K, Z) and multiple terminals (Kitty, Alacritty, Konsole).

`Ctrl-Shift-<letter>` is properly detected by other applications on my computer (e.g. firefox), so my keyboard seems to be working fine.

### Reproduction Steps

I tried this:

1. Add the above key mappings to `config.toml`
2. Open helix with any file (or no file)
3. Press `Ctrl-Shift-J`

I expected this to happen:
Helix switches to insert mode

Instead, this happened:
Nothing happens (asciinema recording: https://asciinema.org/a/RLdAHrib8PNWg3dWuSnnhDjKc)

### Helix log

No new messages were logged in `~/.cache/helix/helix.log` while performing the steps above.

### Platform

Linux

### Terminal Emulator

kitty 0.26.5

### Helix Version

helix 22.12 (installed from Arch Linux repositories)

**Comment by the-mikedavis** [comment]
This is from the limitations of default terminal keyboard input. We will need to implement+enable the enhanced keyboard protocol to be able to parse these keys accurately (#4939)

I will close in favor of https://github.com/helix-editor/helix/issues/1085 which tracks this
