### ISSUE TITLE
Close parentheses after autocomplete and fix overlapping documentation? from autocomplete

### ISSUE THREAD

**Issue by sudokit** [helix-editor/helix#5430]
![image](https://user-images.githubusercontent.com/64897647/211040232-eb6c4f62-aadc-4f73-ac38-708786da9709.png)
not sure if this is a bug or something on my end

**Comment by archseer** [comment]
Based on the screen size there doesn't seem to be a position that would have those two popups not overlap.

**Comment by sudokit** [comment]
I just screenshotted those two popups. Ill send the full screenshot later!

**Comment by sudokit** [comment]
Sorry forgot all about this. 
![image](https://user-images.githubusercontent.com/64897647/213218813-9148b727-fce3-4586-be9e-c886ecac0dcb.png)
heres an image and i think there is quit enough space for the popup. And like in vscode, it would be cool if it at least popped on top of the documentation!

**Comment by the-mikedavis** [comment]
That's the same as https://github.com/helix-editor/helix/issues/3821

I'll close in favor of that issue
