### ISSUE TITLE
Compilation error

### ISSUE THREAD

**Issue by carstein** [helix-editor/helix#5432]
### Summary

Currently the project does not compile because of the 'ignore v0.4.19'  package - this package requires 'scoped_threads' - an unstable feature that only stabilized in Rust 1.63. Unfortunatelly the rust-toolchain.toml overrides the current version down to 1.61. That causes the compilation to fail.

This can be fixed by bumping version up to at least 1.63.0

### Reproduction Steps

$ git clone https://github.com/helix-editor/helix helix
$ cd helix
$ cargo install --path helix-term 

### Platform

Linux

### Terminal Emulator

gnome-terminal

### Helix Version

22.12-95-gf2fff9b9

**Comment by the-mikedavis** [comment]
`ignore` is currently locked at 0.4.18: https://github.com/helix-editor/helix/blob/f2fff9b9c95759385dbb5c84846ec35c9159d215/Cargo.lock#L1353-L1355

**Comment by carstein** [comment]
And yet ...
   Compiling grep-searcher v0.1.11
   Compiling ignore v0.4.19
   Compiling grep-regex v0.1.11

**Comment by carstein** [comment]
After reading some more - cargo install by default ignores Cargo.lock - you can force the behaviour by running it with --locked

**Comment by the-mikedavis** [comment]
Oh interesting, I'm surprised that cargo behaves that way. The docs for installation from source should include the `--locked` flag to prevent this snag. Would you like to submit a PR?

**Comment by carstein** [comment]
Done: https://github.com/helix-editor/helix/pull/5438

**Comment by pascalkuthe** [comment]
The next firefox release wil happen on 2023/1/17 so we can raise the MSRV to 1.63 soon to fix this problem (although encouraging the use of `--locked` is still good regardless)
