### ISSUE TITLE
Accept `+num` flag for opening at line number

### ISSUE THREAD

**Issue by d12bb** [helix-editor/helix#5437]
Lots of editors (including the heavyweights Vim and Emacs) accept a `+num` flag for opening a file at the line number specified by `num`. I know Helix can do this by appending `:num` to the file name, but both muscle memory and other applications (like the `v` command in less) rely on the plus syntax, so I suggest just adding it as a second option.

**Comment by Paul-J-Barrett** [comment]
Note in helix the +number opens another buffer. I put bufferline="multiple" to see what was gong on. There was two buffers +11 and Cargo.toml the file I was viewing with less. Also of course the Cargo.toml was in the second buffer so it was not visible by default and I was looking at empty file for +11.

Also of note is that + by itself is to open file and place cursor on last line of file.
