### ISSUE TITLE
Ctrl-C does not close debug menu

### ISSUE THREAD

**Issue by jlebon** [helix-editor/helix#5439]
### Summary

Space-g opens the debug menu, but unlike all other menus/popups, Ctrl-C does not close it. Esc closes it.

### Reproduction Steps

 

I tried this:

1. `hx`
2. Space-g
3. Ctrl-C

I expected this to happen:

The debug menu closes.

Instead, this happened:

The debug menu does not close.

### Platform

Linux

### Terminal Emulator

tmux inside GNOME Terminal

### Helix Version

22.12

**Comment by archseer** [comment]
Yes, debug mode is a sticky mode similar to `Z` or `v`. These are always closed with `esc`.
