### ISSUE TITLE
Helix crashes when lacking space to show popups

### ISSUE THREAD

**Issue by pathwave** [helix-editor/helix#5448]
### Summary

There is two different panics happening, not quite sure what triggers the first one but I think its related to how much content
is being shown in the popup window. I sometimes got the second panic message when doing the first reproduction steps.

### Reproduction Steps

First crash trigger:

1. Start helix and run command "Show docs under cursor"
2. Resize terminal window height smaller and smaller
3. Helix crashes with:
thread 'main' panicked at 'index out of bounds: the len is 3276 but the index is 3482', helix-tui\src\buffer.rs:513:33
stack backtrace:
   0: std::panicking::begin_panic_handler
             at /rustc/fe5b13d681f25ee6474be29d748c65adcd91f69e\/library\std\src\panicking.rs:584
   1: core::panicking::panic_fmt
             at /rustc/fe5b13d681f25ee6474be29d748c65adcd91f69e\/library\core\src\panicking.rs:143
   2: core::panicking::panic_bounds_check
             at /rustc/fe5b13d681f25ee6474be29d748c65adcd91f69e\/library\core\src\panicking.rs:84
   3: helix_tui::buffer::Buffer::clear_with
   4: <helix_term::ui::popup::Popup<T> as helix_term::compositor::Component>::render
   5: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
   6: hx::main_impl::{{closure}}
   7: tokio::runtime::park::CachedParkThread::block_on
   8: tokio::runtime::scheduler::multi_thread::MultiThread::block_on
   9: hx::setup_logging

Second crash trigger:

1. Start helix and make the terminal window height 4 lines or smaller.
2. Run command "Show docs under cursor"
3. Helix crashes with: 
thread 'main' panicked at 'Component needs required_size implemented in order to be embedded in a popup', helix-term\src\ui\popup.rs:209:14
stack backtrace:
   0: std::panicking::begin_panic_handler
             at /rustc/fe5b13d681f25ee6474be29d748c65adcd91f69e\/library\std\src\panicking.rs:584
   1: core::panicking::panic_fmt
             at /rustc/fe5b13d681f25ee6474be29d748c65adcd91f69e\/library\core\src\panicking.rs:143
   2: core::panicking::panic_display<str>
             at /rustc/fe5b13d681f25ee6474be29d748c65adcd91f69e\/library\core\src\panicking.rs:72
   3: core::panicking::panic_str
             at /rustc/fe5b13d681f25ee6474be29d748c65adcd91f69e\/library\core\src\panicking.rs:56
   4: core::option::expect_failed
             at /rustc/fe5b13d681f25ee6474be29d748c65adcd91f69e\/library\core\src\option.rs:1874
   5: <helix_term::ui::popup::Popup<T> as helix_term::compositor::Component>::required_size
   6: helix_term::compositor::Compositor::replace_or_push
   7: core::ops::function::FnOnce::call_once{{vtable.shim}}
   8: helix_term::job::Jobs::handle_callback
   9: hx::main_impl::{{closure}}
  10: tokio::runtime::park::CachedParkThread::block_on
  11: tokio::runtime::scheduler::multi_thread::MultiThread::block_on
  12: hx::setup_logging

### Platform

Windows

### Terminal Emulator

Windows terminal

### Helix Version

22.12-101-ga39a2ce9

**Comment by catdevnull** [comment]
this just crashed my editor losing a bunch of changes i was making, pls merge!

**Comment by pascalkuthe** [comment]
Seems this was fixed by  #6109 and we forgot to li k it after the original PR got closed
