### ISSUE TITLE
Comments in JSX files

### ISSUE THREAD

**Issue by nxy7** [helix-editor/helix#5453]
I don't think you can use comments in JSX files right now. JSX files use different syntax in return type, but whole file is treated as JS, because of this JSX elements are commented with // instead of {/\* content \*/}
Currently:
<img width="582" alt="image" src="https://user-images.githubusercontent.com/32909532/211212439-843b90b7-d6c9-4fcf-9f7a-8d30caf45f6b.png">
JSX style comments:
<img width="602" alt="image" src="https://user-images.githubusercontent.com/32909532/211212677-112e8e96-71ed-4b8e-9f8d-b31b5d20feab.png">

I didn't see any issue open for that yet. JSX is big part of today's software development and I think it would be nice if it was supported out of the box.

**Comment by gabydd** [comment]
Currently we don't have block comments see #1505
