### ISSUE TITLE
Glitching when texts contain some Unicode symbols

### ISSUE THREAD

**Issue by Hapenia-Lans** [helix-editor/helix#5502]
![bug](https://user-images.githubusercontent.com/93276898/211772287-5a53ba3f-9122-49d2-a689-595aa9db6442.gif)

the code snippet:

```rust
if ui.button("🗙").clicked() {
    self.mark_as_delete = Some(i);
}
```

**Comment by the-mikedavis** [comment]
What terminal are you using? I can't reproduce this with kitty 0.26.2

**Comment by Hapenia-Lans** [comment]
Microsoft Terminal in Windows 11 22H2

**Comment by kirawi** [comment]
This may be a bug with Microsoft Terminal. It's notoriously been a bit buggy.

**Comment by CptPotato** [comment]
This might be #4932

**Comment by kirawi** [comment]
Perhaps it's related, but according to Unicode it isn't an emoji: https://util.unicode.org/UnicodeJsps/character.jsp?a=1F5D9

**Comment by pascalkuthe** [comment]
Closing in favor of https://github.com/helix-editor/helix/issues/6012
