### ISSUE TITLE
[Enhancement] show all changes

### ISSUE THREAD

**Issue by lukepighetti** [helix-editor/helix#5504]
Currently we can see git diff hunks and navigate to them with `[g` and `[G`

I would like to also have a split view picker similar to `space-f` and `space-F` to view these changes across a file or the workspace

My suggestion would be to bind `space-g` and `space-G` to this feature, where the text to search is the contents of the hunk collapsed to one line with leading, trailing, and multiple whitespace removed

Then I would suggest rebinding debug to `space-e`

**Comment by pascalkuthe** [comment]
Duplicate of #5362,

See for a first implementation altough I think it needs some design work to work well as a picker.
I would especially like to see the workspace version of this (which would also included unopened files)

**Comment by pascalkuthe** [comment]
I mistyped and forgot to link the PR. See #5472 for an initial implementation

**Comment by ipochi** [comment]
```
[keys.normal.space]
v = ":sh git diff -U0 -- %{buffer_name} | awk -v l=%{cursor_line} '/^@@/ { if (found) exit; match($0, /\\+[0-9]+(,[0-9]+)?/); s=substr($0,RSTART+1,RLENGTH-1); split(s,a,\",\"); start=a[1]; count=(a[2] ? a[2] : 1); end=start+count-1; found=(l>=start && l<=end); if (found) print; next } found { print }'"
```

add this your helix config. If you are on the colored lines shown by helix then  "space + v" will show you the diff as an overlay
