### ISSUE TITLE
Open file on line/col

### ISSUE THREAD

**Issue by sh7dm** [helix-editor/helix#551]
#### Describe your feature request
Helix should parse file open commands and params like `src/main.rs:15:8` for opening files on specific place. This can be convenient to fix errors reported by tools, since user won't need to find that place manually, `:o /path/to/file:line:col` would be enough to get right to the needed file location.

URI's are probably great thing to handle as well, maybe in another PR to avoid chaos.

I can take any of those two once it's considered to be a useful feature.

**Comment by sudormrfbin** [comment]
#445 is a take on this.

**Comment by sh7dm** [comment]
Oh, great! Definitely a useful feature.

**Comment by pickfire** [comment]
Ah, I realized someone else wanted the same feature as me. I will gladly push the PR. There is just bug left such that if multiple file/pos is specified, only the first one would work, the rest does not work, not quite sure how to fix it yet.

**Comment by sh7dm** [comment]
I can take a look at the code if you want and when I have time.
