### ISSUE TITLE
Change channel to 1.66 or stable

### ISSUE THREAD

**Issue by DrunkRandomWalker** [helix-editor/helix#5512]
https://github.com/helix-editor/helix/blob/c988bd9629145b5a337498937a70af555bfa6159/rust-toolchain.toml#L2

1.61 cause a problem in the compilation 

Should change to 1.66

**Comment by the-mikedavis** [comment]
See https://github.com/helix-editor/helix/pull/5485#issuecomment-1377146566

Use `cargo install --locked --path helix-term` for installing from source
