### ISSUE TITLE
Build From Source Section On Website Missing `--locked` Flag

### ISSUE THREAD

**Issue by sellithy** [helix-editor/helix#5515]
Installing from source in the repo's README correctly has the `--locked` flag but the [website ](https://docs.helix-editor.com/install.html)doesn't.

**Comment by gabydd** [comment]
It actually does but it's only in the master docs at the moment https://docs.helix-editor.com/master/install.html

**Comment by gabydd** [comment]
Good reminder to backport it to the stable docs though
