### ISSUE TITLE
Column heading of `hx --health languages` invisible on light terminal theme

### ISSUE THREAD

**Issue by BurNiinTRee** [helix-editor/helix#5516]
### Summary

Running `hx --health languages` on GNOME Terminal with the default light theme doesn't show the column names, only an empty line before printing the rest, rendering the checkmarks fairly useless if you don't already know what they mean.

Trying to select the line doesn't help, only by changing to the dark terminal theme was I able to read the column names.

### Reproduction Steps

 

I tried this:

1. `hx --health languages`

I expected this to happen:

Instead, this happened:

### Helix log

<details><summary>~/.cache/helix/helix.log</summary>

```
please provide a copy of `~/.cache/helix/helix.log` here if possible, you may need to redact some of the lines
```

</details>

### Platform

Linux

### Terminal Emulator

GNOME Terminal

### Helix Version

helix 22.12 (96ff64a8)

**Comment by woojiq** [comment]
Can you send screenshots? I tried two light themes and one system light theme and in all cases the color of the column names was visible.

**Comment by Pound-Hash** [comment]
I checked #6335 and I don't see how to fix this.

I'm also on a light background (foot terminal) because I'm colorblind, and I can't see the headers either.
