### ISSUE TITLE
Show errors on startup

### ISSUE THREAD

**Issue by woojiq** [helix-editor/helix#5521]
### Summary

Not sure if this is expected behavior, but when I open the rust file (didn't test the others), no errors are displayed. I need to save the file and then the errors will be visible. I know this is typical _rust-analyzer_ behavior when you write your code and need to save the file to find errors. Is it the same for opening a file?

__languages.toml__
``` toml
[[language]]
name = "rust"
```

P.S. I don't know whose side this problem is (helix, rust-analyzer, mine).

### Reproduction Steps

1. `cargo new testerror`
2. paste this to `main.rs`:
``` rust
fn main() {
    sadsfda;
    println!("Hello, world!");
}
```
3. open file again and wait a few seconds
4. Helix does not show the error in the second line
5. Save file
6. An error is displayed

### Platform

Linux

### Terminal Emulator

Alacritty 0.11.0

### Helix Version

helix 22.12 (2412f7c8)

**Comment by the-mikedavis** [comment]
This is rust-analyzer's behavior as far as I know. Do you see diagnostics in other editors on startup?

**Comment by woojiq** [comment]
Ah, yeah. This is typical rust analyzer behavior, I also tried in vscode (my bad, I didn't check it before opening issue). I guess I thought it was a helix issue because I never exited the vscode editor when there were errors. So every time vscode was opened it was out of error. And I didn't pay attention to lsp.

Ill try to simulate insta save after loading document for my fork (to understand helix codebase better). Would be smth like this:
``` rust
tokio::spawn(language_server.text_document_did_open(...)
...
text_document_did_save(doc.identifier(), doc.text())
```
