### ISSUE TITLE
Implement window/showMessage in LSP client

### ISSUE THREAD

**Issue by ayoub-benali** [helix-editor/helix#5524]
Currently Helix is simply logging a warning here: 
https://github.com/helix-editor/helix/blob/b6331394a3f341ad21f8fad3e6e0b93becda9ce5/helix-term/src/application.rs#L821

while Scala's language server [Metals](https://scalameta.org/metals/) make use of it. You can see it in the [spec](https://microsoft.github.io/language-server-protocol/specifications/lsp/3.17/specification/#window_showMessage).

I saw that there was some work by @matoous in https://github.com/helix-editor/helix/pull/1445 but it is dropped. So I want first to get some ideas on how handle this message. 
Is bellow the status line for example a good place like the progress messages? should it be configurable and off by default like `display-messages`  ?

**Comment by sigmaSd** [comment]
https://github.com/v-analyzer/v-analyzer also uses it
