### ISSUE TITLE
Command to switch to named buffer

### ISSUE THREAD

**Issue by caelia** [helix-editor/helix#5525]
When there are more than 2 or 3 buffers open, it quickly becomes unwieldy to go to another open buffer by means of :buffer-previous or :buffer-next. I suggest we should have something like :goto-buffer <name> or :switch-to-buffer <name>.

**Comment by akabinds** [comment]
There is already a PR open for this (#4756), which allows you to go to a buffer based on its index. On your first point, you can easily set a custom keybinding to make going to the next or previous buffer more ergonomic.

**Comment by the-mikedavis** [comment]
The buffer picker `<space>b` is meant for switching between buffers when there are many open

**Comment by caelia** [comment]
> The buffer picker `<space>b` is meant for switching between buffers when there are many open

Oh, I see. I looked for something like that in the docs and didn't find it. But I think it will do quite nicely for me. Thanks!

**Comment by caelia** [comment]
Oh, buffer picker? I see. I looked for something like that in the docs, but didn't find it. I think that will work fine for me. Thanks!
