### ISSUE TITLE
Diagnostic blocks the codes

### ISSUE THREAD

**Issue by DrunkRandomWalker** [helix-editor/helix#5564]
Sometimes the diagnostic covers some part of the codes that need to change.
Is there a way to move the diagnostic to the bottom?
![image](https://user-images.githubusercontent.com/83610610/212940540-b33058dd-b674-4568-b60e-bd17a6467ee9.png)

**Comment by the-mikedavis** [comment]
Duplicate of https://github.com/helix-editor/helix/issues/1462
