### ISSUE TITLE
VS Code like command palette to search for commands and keybinds

### ISSUE THREAD

**Issue by sudormrfbin** [helix-editor/helix#559]
VS Code has a [command palette](https://code.visualstudio.com/docs/getstarted/userinterface#_command-palette) that allows searching for commands and keybindings by their description and executing them:

![vs code command palette](https://code.visualstudio.com/assets/docs/getstarted/userinterface/commands.png)

I've found this to be very useful when acquainting myself with the editor, since I don't have to try and remember every single keybinding, nor do I have to continuously switch to a documentation page to figure out how to do something (for the most part). It also helps immensely with discoverability since all possible key mappings are laid out and you're bound to stumble into something useful sooner or later.

VS Code allows executing entries from the command palette itself, I'm not sure whether that should be supported, since most commands aren't free standing and need further or previous input.

This shouldn't be too hard since we already have short descriptions for both editor commands (keybindings) and typable commands, and a picker to search through them.

**Comment by sudormrfbin** [comment]
I wrote a plugin, [cheatsheet.nvim](https://github.com/sudormrfbin/cheatsheet.nvim), that attempts to bring this concept to neovim by having short files that describe a set of commands. Even though I don't use it _all_ the time (like I imagined I would ha ha), when I need it I'm quite thankful for it. In the future it can also serve as a good way for plugin commands and keybindings to be more accessible to end users.

**Comment by pickfire** [comment]
I don't think merging them would be a good idea because of how a modal editor work. vscode is always in insert mode like emacs so it's fine for them to have it, but model editor you would not want to type them out. I think it would be better if we show the infobox when we press a key like F1 in any part.

**Comment by sudormrfbin** [comment]
The idea isn't to merge the infobox with this; the infobox and the command palette are completely different in what they perform and are _complementary_.

The infobox is useful to guide your keypresses as you type, for example if you know that all the goto commands are under `g` but don't know the exact keymap for goto references, you can press `g` and look it up in the infobox.

But if you know nothing about the keymap to invoke (or if you've simply forgotten it), you will either have to go read the docs or do trial and error. This is where the command palette can be useful -- you can search for a keymap by it's _description_ and don't have to worry about memorizing a plethora of keys.

And executing the commands from the palette would probably not be feasible because of modes, but that's not the primary function I hope to achieve with this anyway (though that would be a nice addition).

**Comment by pickfire** [comment]
Hmm, any idea what keybind it should use?

**Comment by archseer** [comment]
`Space+?` could work, since `?` is already a common shortcut on websites (try it here on github and you'll get a popup).

If we want to actually make these executable, then maybe `Ctrl+Space` (it reminds me of `Cmd+Space` to bring up Spotlight on macOS)

**Comment by pickfire** [comment]
So I guess every command now will need to have description and default key specified there?

**Comment by sudormrfbin** [comment]
We can simply get that information from the keymap itself by recursively traversing it (the mode is at the top level, keys and descriptions are at the bottom level of the keymap tree).

**Comment by Cons-Cat** [comment]
> We can simply get that information from the keymap itself by recursively traversing it (the mode is at the top level, keys and descriptions are at the bottom level of the keymap tree).

What about commands that aren't bound to the keymap? In VS Code and Emacs, Ctrl+Shift+P and M-x respectively are the only way to access the vast majority of commands (at least by default), and plugins for them and many other editors often choose not to provide default key bindings for new commands.

**Comment by sudormrfbin** [comment]
We can merge the unbound commands to the command list after the recursive traversal parsing and show all of them. Also commands without default keybinds are a prime use case for executing commands from the palette, though that would need extra information like the mode it is supposed to work in.

**Comment by heliostatic** [comment]
Although it's a GUI, Obsidian handles the command palette in a modal editor well -- commands are mode specific, and keybindings are shown when they exist. 

The `:Commands` command in https://github.com/junegunn/fzf.vim#commands is also great.

https://user-images.githubusercontent.com/70898/134790416-2ee0caa1-ff5f-4ec1-8623-ef70bc021ff6.mp4

**Comment by kirawi** [comment]
We can probably reuse the existing picker for this.

**Comment by matoous** [comment]
Going to take a look at this one if no one has started working on it already.

**Comment by sudormrfbin** [comment]
I started working on this a few months back but hit a roadblock with not being able to access the keymap outside of `helix-term`. The proper solution to that was to move components and keymaps to `helix-view` which I tackled in #711, but other PRs took up my time.

**Comment by archseer** [comment]
If you're just building a picker in `helix-term` (inside a Command), isn't that enough? I forgot how @Omnikar handled it in the `:help` PR

**Comment by Omnikar** [comment]
Accessing the keymaps from the `:help` command function has not been handled as of now.
