### ISSUE TITLE
Provide appstream metadata file.

### ISSUE THREAD

**Issue by blt-r** [helix-editor/helix#5624]
Currently the flatpak package of the Helix uses a basic `.appdata.xml` file written by the packager (me). Ideally that file should be provided by the app itself. Not only that is the best practice for flathub, that will mean that other packages will be able to use it as well. For example if it will be added to `archlinux-appstream-data` then software stores on arch linux would be able to recognize it. 

Currently on archlinux in `gnome-software` if you search for "Helix" two things will come up:
![Screenshot from 2023-01-21 23-36-52](https://user-images.githubusercontent.com/63462729/213884205-014d8ad4-7fe6-40bf-91fc-bc1d942ac0d0.png)

One is the version from arch repositories that gets all the info from `.desktop` file:
![Screenshot from 2023-01-21 23-36-56](https://user-images.githubusercontent.com/63462729/213884215-15798fe5-de67-4514-a143-6e8c70e37c04.png)

And the other from flathub with the `.appdata.xml` that I wrote:
![Screenshot from 2023-01-21 23-40-07](https://user-images.githubusercontent.com/63462729/213884295-5d57debb-185a-4ed0-ac8e-f3090b89903d.png)

If all packages would all use `.appdata.xml` file, software stores could understand that it is the same package. Also current page for native version of the package doesn't have much. No screenshots, not much description, and no licensing information (gnome software marks it as proprietary for that reason). Providing the appstream manifest would also allow you to add more stuff like release notes. (now when I'm looking at it this manifest is really minimal, I could easily add more links, keywords, categories, the video)

We can start by just copying the [manifest I wrote](https://github.com/flathub/com.helix_editor.Helix/blob/1d4c673457588007d585eaa376c81e7df28bf79c/helix.appdata.xml) into `./contrib/Helix.appdata.xml` and put `Helix.desktop` instead of the flatpak-specific `com.helix_editor.Helix.desktop`. Also probably replace the license for the metadata file with the one used for this repo.

**Comment by pascalkuthe** [comment]
This sounds reasonable to me. Since you arleardy worked om this you could look into sending a PR if you feel up to it

**Comment by pascalkuthe** [comment]
I am closing this as  #5643 was already merged and the issues just didn't get picked up by github automatically
