### ISSUE TITLE
Different LSP root from project root

### ISSUE THREAD

**Issue by keirlawson** [helix-editor/helix#5642]
So far as I can work out Helix treats the project root as the root of the git project for the purposes of firing up language servers.  However when dealing with a monorepo often the root of the git project is not the folder I wish the language server to consider the root. Is there a way to change this?

**Comment by pascalkuthe** [comment]
See  #4439

**Comment by the-mikedavis** [comment]
Yeah we have #4439 and https://github.com/helix-editor/helix/discussions/5617 to discuss this. I'll close in favor of those
