### ISSUE TITLE
config-reload fails to change mouse configuration state

### ISSUE THREAD

**Issue by dogunbound** [helix-editor/helix#5648]
### Summary

config-reload does not change the mouse configuration state after modifying the config.toml

### Reproduction Steps

Steps to reproduce:

1. Run `helix`
2. run `:config-open`
3. modify the `editor.mouse` from `true` to `false` or `false` to `true` depending on your current configuration.
4. run `:config-reload`

You will notice that the mouse state doesn't actually change.
You need to exit helix and open helix for the configuration to take place.

### Helix log

[helix.log](https://github.com/helix-editor/helix/files/10481756/helix.log)

### Platform

Linux

### Terminal Emulator

konsole

### Helix Version

22.12

**Comment by gabydd** [comment]
thanks for opening up this issue:

this is where we disable mouse: https://github.com/helix-editor/helix/blob/17acadb305bebfef094e4fcc9ba1e6fda6159c3b/helix-term/src/application.rs#L1051-L1053

we need to either disable or enable mouse support the same way here: https://github.com/helix-editor/helix/blob/17acadb305bebfef094e4fcc9ba1e6fda6159c3b/helix-term/src/application.rs#L433
