### ISSUE TITLE
Rust-Analyzer action `inline macro` doesn't produce valid code

### ISSUE THREAD

**Issue by d4h0** [helix-editor/helix#5667]
### Summary

Rust-Analyzer action `inline macro` doesn't produce valid code.

### Reproduction Steps

Create a Rust project with a file with the following content:

```rust
macro_rules! test {
    () => {
        let foo = 42;
        println!("{foo}");
    };
}

fn main() {
    test!();
}
```

Move the cursor to `test!` in the `main` function, press `Space` and `a` to open the code action menu. Now select `inline macro`.

The macro will be expanded to `letfoo=42;println!("{foo}");;`, which isn't valid Rust.

(Rust-Analyzer version: `rust-analyzer 1 (ff4d55e48 2023-01-15)`, however that's probably not relevant here)

### Helix log

N/A, I believe (let me know if that is a false assumption)

### Platform

Linux

### Terminal Emulator

alacritty 0.11.0 (8dbaa0bb)

### Helix Version

helix-term 22.12 (64ec0256)

**Comment by pascalkuthe** [comment]
This is an upstream bug. The same problem occurs in vscode.
Seems similar to https://github.com/rust-lang/rust-analyzer/issues/12860. Best to open a bug report about this in the rust-analyzer repo
