### ISSUE TITLE
make splits closeable without closing all buffers

### ISSUE THREAD

**Issue by Anonym234** [helix-editor/helix#5673]
if a split is opened (via for example `:hsplit-new`) a way to close it should be added. Maybe I'm dumb, but the only way I found required closing all open buffers (using `:bc` repeatedly until the split closes).

**Comment by pascalkuthe** [comment]
Why doesn't `:q` work for you?

**Comment by tuyentv96** [comment]
I think you could try `space-w-q`

**Comment by Anonym234** [comment]
thank you guys. apparently I'm dumb xD
