### ISSUE TITLE
Gutters configuration broken

### ISSUE THREAD

**Issue by non-descriptive** [helix-editor/helix#5694]
### Summary

Gutter parameters started to yield errors and ignore config parameters.
Removing spaces like was suggested in #2206 doesn't work. 

### Reproduction Steps

I've update helix to `22.12 (22b3d3d6)` 

### Helix log

there's no data in helix.log written considering the issue
This yielded on start
```
Bad config: TOML parse error at line 9, column 12
  |
9 | gutters = ["diagnostic", "line_number"]
  |            ^^^^^^^^^^^^
invalid type: string "diagnostic", expected a borrowed string

```
Same text pops on `:config-reload`, but it doesn't fit into a terminal and cut after `borr`

### Platform

Windows

### Terminal Emulator

Windows Terminal

### Helix Version

helix 22.12 (22b3d3d6)

**Comment by the-mikedavis** [comment]
The gutter elements should be plural and use kebab-case: `["diagnostics", "line-numbers"]`. That's not the bug here though: this needs the same change from https://github.com/helix-editor/helix/commit/e83ce7224063afc52d44f9c2b68e3c5a03412f5c for https://github.com/helix-editor/helix/blob/22b3d3d6367f2e559a7193172bd1dba03b864bd3/helix-view/src/editor.rs#L128 because of the update to the `toml` dependency

As a workaround you can use `gutters.layout = ["diagnostics", "line-numbers"]`

**Comment by non-descriptive** [comment]
I've got my settings from [site docs](https://docs.helix-editor.com/) and they error the same way.

**Comment by the-mikedavis** [comment]
Where do you see `diagnostic` and `line_number` in the docs? I see them listed correctly in the release docs https://docs.helix-editor.com/configuration.html#editor-section and the master docs https://docs.helix-editor.com/master/configuration.html#editorgutters-section

**Comment by non-descriptive** [comment]
No, workaround also yields error about strings borrow.
Initially I used only things I found in the docs, and when started looking for potential opened issues I found 2206 and tried keys from it - unkebabed `line_numbers` and plural `diagnostics`. Result is the same as for workaround and it's not about invalid keys or something, as you see. When the keys for anything were invalid it explicitly wrote about it with suggestions.

**Comment by pokkos** [comment]
@non-descriptive Can you try again with the current mainline and the correct key values as stated in the documentation (plural, kebab-case)?

**Comment by non-descriptive** [comment]
Works fine with correct values. Invalid values messages yield parsing error as well as suggestion.
```
Bad config: TOML parse error at line 9, column 11
  |
9 | gutters = [
  |           ^^^^^^^^^^^^
Gutter type can only be `diagnostics` or `line-numbers`.
```
Before update it was just suggestion about proper values. It's probably should be reported as separate issue.
