### ISSUE TITLE
line-ending

### ISSUE THREAD

**Issue by Devil666face** [helix-editor/helix#5698]
### Summary

[editor]
line-ending = "lf"
Does't work

[keys.normal]
"A-e" = ":line-edning lf"
This is too does't work

### Platform

Windows

### Terminal Emulator

wezterm 20221119-145034-49b9839f

### Helix Version

helix 22.12 (96ff64a8)

**Comment by CptPotato** [comment]
I think you have a typo there: line-e**dn**ing

This one works fine for me:

```toml
[keys.normal]
"A-e" = ":line-ending lf"
```

If you're looking for a way to set the default line ending for new documents, there's an open PR: #5621

**Comment by Devil666face** [comment]
Oh, sorry.
Yes, it is work, but why this doesn't work?
[editor]
line-ending = "lf"

**Comment by CptPotato** [comment]
> Oh, sorry. Yes, it is work, but why this doesn't work?
> 
> ```toml
> [editor]
> line-ending = "lf"
> ```

It doesn't work because the `line-ending` setting does not exist, see https://docs.helix-editor.com/configuration.html#editor-section.
