### ISSUE TITLE
:cd , :open etc don't work for files and folders with spaces in them

### ISSUE THREAD

**Issue by kaleidawave** [helix-editor/helix#5699]
Title says it all really, `:cd my folder` considers it to be two arguments. It should parse arguments with quotations as literals so include spaces (similar to how it does in terminal). At the moment `:open 'my file'` is currently parsed as opening `'my` and `file'`

**Comment by gabydd** [comment]
You need to escape the space in the folder name so it would be ``:cd my\ folder``

**Comment by the-mikedavis** [comment]
Are you running on windows? Both `:cd` and `:open` work for me with directories/files with spaces in their names if I use `"` or `'` quotes or escape the spaces with `\`.

**Comment by kaleidawave** [comment]
Ah just updated Helix and looks like this was fixed since (my old version) 22.05 🎉
