### ISSUE TITLE
Invalid hexcodes in several themes `emacs`, `monokai_aqua`, `papercolor-light` (Should be checked in CI at theme PRs?)

### ISSUE THREAD

**Issue by LeoniePhiline** [helix-editor/helix#5709]
Reproduction:

1. Open two terminals side by side
2. In one terminal, watch the hx log: `tail -f ~/.cache/helix/helix.log`
3. In the other terminal, open `hx`
4. Type `:theme`
5. Use the `Tab` key to go through all themes and observe the log.

# Theme `emacs`

```
helix_view::theme [WARN] Theme: malformed hexcode: highlight
```

# Theme `monokai_aqua`

```
helix_view::theme [WARN] Theme: malformed hexcode: light-black
helix_view::theme [WARN] Theme: malformed hexcode: light-black
helix_view::theme [WARN] Theme: malformed hexcode: purple
```

# Theme `papercolor-light`

```
helix_view::theme [WARN] Theme: malformed hexcode: indent
```

Note: Logging the affected theme's name could be helpful! _(Edit: But looking at the code, it seems unwieldy to carry the theme name around as much as would be necessary to log it in case of parsing errors.)_

---

I assume this should be checked in CI via `xtask`.

**Comment by sarsapar1lla** [comment]
Does this issue still require attention? If so, happy to take a look at it
