### ISSUE TITLE
Can not compile Helix with the `rust-toolchain.toml` file (channel = "1.61.0")

### ISSUE THREAD

**Issue by alexsunxl** [helix-editor/helix#5715]
I use `cargo install --path helix-term` compile the project's root, And I got this error:

```
error[E0658]: use of unstable library feature 'bool_to_option'
  --> /home/aa/.cargo/registry/src/github.com-1ecc6299db9ec823/git-tempfile-3.0.1/src/fs/remove_dir.rs:54:63
   |
54 |                     Some(parent) => (parent != self.boundary).then_some(parent),
   |                                                               ^^^^^^^^^
   |
   = note: see issue #80967 <https://github.com/rust-lang/rust/issues/80967> for more information

error[E0658]: use of unstable library feature 'scoped_threads'
    --> /home/aa/.cargo/registry/src/github.com-1ecc6299db9ec823/ignore-0.4.20/src/walk.rs:1285:9
     |
1285 |         std::thread::scope(|s| {
     |         ^^^^^^^^^^^^^^^^^^
     |
     = note: see issue #93203 <https://github.com/rust-lang/rust/issues/93203> for more information
```

I know the `scoped_threads` is a std feature in rustc 1.63.

So I change the `rust-toolchain.toml` file's  channel = "1.61.0" ===>  channel = "stable" 
And then I complie again, it's OK.

I don't know why use the toolchain file lock the rustc version, so just post this issue

**Comment by gabydd** [comment]
as the [install instructions](https://github.com/helix-editor/helix#installation) suggest you should use the ``--locked`` flag when doing the ``cargo install``

**Comment by alexsunxl** [comment]
> as the [install instructions](https://github.com/helix-editor/helix#installation) suggest you should use the `--locked` flag when doing the `cargo install`

Thanks.

This readme flag seem to be added latest, I used a history build command,so meet the error. And I have not notice this yet. sorry for that.
