### ISSUE TITLE
global dot and hidden files/directories include for file picker

### ISSUE THREAD

**Issue by bindsdev** [helix-editor/helix#5724]
Currently, the `hidden` key under the `editor.file-picker` section for configuration is defaulted to `true`, which enables hiding dot and hidden files from being shown in the file picker. But, this can be inconvenient at times. There are dot and hidden files/directories that can be important to a project (such as `.gitattributes`, `.gitignore`, `.github/`, etc) that should be included in the file picker by default. This would prevent one from having to set `hidden` to `false` and have all dot and hidden files shown, which might not be desired by the individual. The common and important ones, such as the ones listed above, should be included in the file picker out of the box. If an individual wants to opt out of hiding other dot and hidden files/directories, there could be a key `include-hidden`, under the `editor.file-picker` section, that takes a list of other dot and hidden files/directories to include in the file picker.

**Comment by KenCox94** [comment]
will work on this today!

**Comment by king-11** [comment]
hey @KenCox94 are you still working on it?

**Comment by KenCox94** [comment]
@king-11 
yes will complete this week

**Comment by bindsdev** [comment]
> hey @KenCox94 are you still working on it?

I think the PR is just waiting on review.

**Comment by king-11** [comment]
The CI errors seem to be because of cargo fmt

**Comment by Mordeaux** [comment]
I made a PR on @KenCox94 's branch that's just a single commit from running `cargo fmt`. Should get CI to pass.

**Comment by pascalkuthe** [comment]
This is covered by #7423 (with negative ignore patterns both globally and pre workspace). I don't see us adding anything more purpose-built than that

**Comment by theperiscope** [comment]
I'm a new to Helix, and it took me forever to figure out that `hidden = true` is actually _hiding_ the dot files I was looking for, and how @bindsdev  phrased his initial message helped me realize the mistake. I do think it is obfuscated that `hidden = false` makes dot files _visible_. Can it be improved?
