### ISSUE TITLE
Group matches by file in global search

### ISSUE THREAD

**Issue by keirlawson** [helix-editor/helix#5730]
I find it difficult to parse results of a global search when there are a lot of them with multiple matches per file.  I think the results would be a bit easier to grok if there was a clear grouping of matches into files (by indenting them beneath the filename?).  The lack of legibility drove me (temporarily) back to VS code as its search view clearly separates results from different files.

**Comment by CptPotato** [comment]
(This has parallels to #4243)

**Comment by pascalkuthe** [comment]
I added a comment to #4243 so we remeber that such improvements would also be nice for other pickers. I am closing this issue in favor of that issue so that we don't have multiple issue tracking essentially the same feature request.
