### ISSUE TITLE
Text rendering error

### ISSUE THREAD

**Issue by shengliawa** [helix-editor/helix#5753]
### Summary

When I move the cursor up at the end of the file.
A lot of cursors appear suddenly and the text obviously renders incorrectly
![E$_3IKK572%8KKB{}ZCOOPJ](https://user-images.githubusercontent.com/51014812/215792242-b7ef4add-c59a-4d53-ac70-8208341be981.png)

### Reproduction Steps

 

I tried this:

1. `hx`

I expected this to happen:
Font rendering is normal
Instead, this happened:
![E$_3IKK572%8KKB{}ZCOOPJ](https://user-images.githubusercontent.com/51014812/215793638-3e967b59-91e6-4c62-aadc-6fdafb6e9a6b.png)

### Helix log

<details><summary>~/.cache/helix/helix.log</summary>

``` log
2023-01-31T17:12:01.648 helix_view::editor [ERROR] editor error: LSP not defined for the current document
2023-01-31T17:14:21.673 helix_view::editor [ERROR] editor error: no such command: 'fomat'
2023-01-31T18:57:48.061 helix_view::editor [ERROR] Failed to initialize the LSP for `source.toml` { cannot find binary path }
2023-01-31T19:16:16.044 helix_view::editor [ERROR] Failed to initialize the LSP for `source.md` { cannot find binary path }
2023-01-31T19:18:12.198 helix_view::editor [ERROR] Failed to initialize the LSP for `source.md` { cannot find binary path }
2023-01-31T19:20:34.788 helix_view::editor [ERROR] editor error: 1 unsaved buffer(s) remaining: ["[scratch]"]
2023-01-31T19:21:32.108 helix_view::editor [ERROR] Failed to initialize the LSP for `source.md` { cannot find binary path }
2023-01-31T21:50:39.258 helix_view::editor [ERROR] Failed to initialize the LSP for `source.rust` { cannot find binary path }
2023-01-31T22:12:24.896 helix_view::editor [ERROR] Failed to initialize the LSP for `source.md` { cannot find binary path }
2023-01-31T22:40:23.650 helix_view::editor [ERROR] Failed to initialize the LSP for `source.md` { cannot find binary path }
2023-01-31T22:41:01.429 helix_view::editor [ERROR] Failed to initialize the LSP for `source.md` { cannot find binary path }

```

</details>

### Platform

Windows

### Terminal Emulator

Original PowerShell 7.3.2

### Helix Version

helix 22.12 (96ff64a8)

**Comment by pascalkuthe** [comment]
Could you upload the file where this happens? That would help a lot with debugging the issue. Also just to clarify: You have placed the cursor at the end of the file and then press `k` once?

**Comment by shengliawa** [comment]
[index.md](https://github.com/helix-editor/helix/files/10547662/index.md)
This is the file.I did press k to move the cursor up.

**Comment by CptPotato** [comment]
I cannot reproduce this using Wezterm, Cmd or Powershell on Windows 10. I'm using a somewhat recent commit from `master`.

**Comment by LeoniePhiline** [comment]
I also can **not** reproduce this using Konsole on OpenSUSE Tumbleweed, using 447909e4d0b865a1177babe2214536979fdbeb7c, which is the `master` `HEAD` from yesterday.

# My repro steps:

## Option 1 - last char of last line:

1. `hx /path/to/index.md`
2. <kbd>g</kbd> <kbd>e</kbd>
3. <kbd>g</kbd> <kbd>l</kbd>
4. <kbd>k</kbd> (once, then multiple times - nothing out of the ordinary happens)
5. <kbd>:</kbd> <kbd>q</kbd> <kbd>Enter</kbd>

## Option 2 - **past** the last char of last line:

1. `hx /path/to/index.md`
2. <kbd>g</kbd> <kbd>e</kbd>
3. <kbd>g</kbd> <kbd>l</kbd>
4. _Added:_ <kbd>l</kbd>
5. <kbd>k</kbd> (once, then multiple times - nothing out of the ordinary happens)
6. <kbd>:</kbd> <kbd>q</kbd> <kbd>Enter</kbd>

@shengliawa Could you try with the latest `master`?

**Comment by shengliawa** [comment]
I compiled the version from master.  helix `22.12 `4eca4b30.
It always has problems when I move the cursor around.
![图片](https://user-images.githubusercontent.com/51014812/215915950-19002227-5e9d-4c90-93ed-05f15c27786c.png)
![图片](https://user-images.githubusercontent.com/51014812/215916062-ea52bf1d-45e7-4d53-aaf9-3406348ea501.png)
They should be like this.
![图片](https://user-images.githubusercontent.com/51014812/215916793-8fad5490-5407-4729-b577-c4968ab17766.png)
![图片](https://user-images.githubusercontent.com/51014812/215916835-cb8b7b92-a157-4cf5-8681-e8e307abd721.png)
**
![图片](https://user-images.githubusercontent.com/51014812/215916113-5e618636-48a7-4624-b8ac-3cee032269c4.png)

**Comment by shengliawa** [comment]
https://github.com/shengliawa/shengliawa.github.io/blob/main/helix.mp4
This is the screen recording

**Comment by shengliawa** [comment]
https://raw.githubusercontent.com/shengliawa/shengliawa.github.io/main/helix.mp4
This is the screen recording.

**Comment by kirawi** [comment]
I experience this on my Windows machine with Alacritty, but I never filed a bug report assuming it was an issue with the terminal.

Additional behavior I experience:

![Capture](https://user-images.githubusercontent.com/67773714/215953821-923e6540-3de8-4cde-b9ea-aced3b4fe521.PNG)

The text below the English is not empty, it's just not rendered until insert mode is exited.

**Comment by shengliawa** [comment]
OK, Helix's font rendering is normal under `WezTerm`,Thank you.
@kirawi

**Comment by LeoniePhiline** [comment]
I could imagine this should be noted in the `README.md` or the documentation? 

A PR adding a heads-up for Windows users of CJK languages, and a recommendation to use Wezterm could potentially help many others.

**Comment by gabydd** [comment]
There is actually a terminal support page on the wiki https://github.com/helix-editor/helix/wiki/Terminal-Support so a note could be added there

**Comment by LeoniePhiline** [comment]
I added a note: https://github.com/helix-editor/helix/wiki/Terminal-Support/_compare/5412a09bd46ed5aa3edc9cb0f98e8a888be4eb1d...55b5772122526693a9af5f120f95c4adba71f63f
