### ISSUE TITLE
Add configuration for MSBuild files

### ISSUE THREAD

**Issue by adam-becker** [helix-editor/helix#5754]
Currently, opening any MSBuild project file results in the default `text` language being used. At the least, the `xml` language should be used to gain proper highlighting. The file extensions I'm aware of are `.csproj`, `.fsproj`, `.vbproj`, and `.proj`.

It is, of course possible to work around this with `:lang xml` each time you open the file, and maybe other ways. However, I believe helix should provide this out of the box.

**Comment by sudormrfbin** [comment]
A PR for this would be definitely welcome, you can consult https://docs.helix-editor.com/master/languages.html on adding a new language entry. Re-using the `xml` grammar is a good starting point, and it can replaced with a dedicated tree-sitter grammar if it becomes available.

**Comment by adam-becker** [comment]
Related for XML support: https://github.com/eclipse/lemminx

This could bridge the gap for MSBuild project files, since a schema exists for them. I'm not sure if the schema is meant to be inferred or how that works, but that could be helpful.
