### ISSUE TITLE
Allow to position status line on the top

### ISSUE THREAD

**Issue by sporto** [helix-editor/helix#5758]
When I want to duplicate a buffer I cannot see the path of the current buffer anymore:

I see the path of the current buffer in the status line

![Screenshot at Feb 01 08-36-58](https://user-images.githubusercontent.com/1005498/215889744-0618dee4-9470-4768-8597-927d41e14339.png)

Then when I type `:w` I cannot see the path of the buffer anymore as it is obscured by the popup.

![Screenshot at Feb 01 08-37-43](https://user-images.githubusercontent.com/1005498/215889882-01741c6f-4b07-4065-8951-0b635e36bfde.png)

I would like to keep the path of the buffer visible, so I can copy part of the path.

So having an option to position the status line at the top would be great for this. So it is always visible.

**Comment by CptPotato** [comment]
> I would like to keep the path of the buffer visible, so I can copy part of the path.

If your goal is to copy/paste the path up to the parent directory, #3134 *might* help you once implemented. However there hasn't been much development on this issue in a while.

**Comment by yashpalgoyal1304** [comment]
alternates:
1. put status line on top of the completion suggestiion popup....
2. put the command line above the status line

an example of this point 1. above can be seen from `micro` editor:


https://user-images.githubusercontent.com/19423063/216253766-95b2c3aa-8f67-4f6d-978e-61c5d64a3b31.mp4

**Comment by yashpalgoyal1304** [comment]
just to confirm, the 2nd alternate suggested above (put command line above status line) would also solve the _problem_ underlined in the description without actually implementing the _solution_ given in title...

so, would u still consider this solved or is only the proposed solution your focus??

**Comment by sporto** [comment]
> so, would u still consider this solved or is only the proposed solution your focus??

Yes, that is all I need, for the status bar not be obscured

**Comment by Fl1tzi** [comment]
Hi. While trying to do this I think it's actually not ideal.

If you have the prompt with the suggestions, the bar will look weird when it overflows over the popup and it would also move a lot, which I think makes it harder to use. So I came up with the idea to actually put the statusline under the prompt. The statusline would stay static and will be easy to see and you also don't get distracted by the suggestions. That is at least what I think would be the best option.

Would you also consider this?

**Comment by yashpalgoyal1304** [comment]
> So I came up with the idea to actually put the statusline under the prompt. The statusline would stay static

hi @Fl1tzi , yes this was already suggested (quoting below). thanks a lot for trying out and sharing the screenshot.

> 2. put the command line above the status line
>
> \- https://github.com/helix-editor/helix/issues/5758#issuecomment-1413240534

> ... 2nd alternate suggested above (put command line above status line) ...
>
> \- https://github.com/helix-editor/helix/issues/5758#issuecomment-1413949780

**Comment by Fl1tzi** [comment]
Oh wow. Sorry.... xD

**Comment by Fl1tzi** [comment]
Should this be an extra config setting? What key should it have if so?

**Comment by yashpalgoyal1304** [comment]
- i dont _think_ it will make sense for it to be configurable
- the new placement better be hard coded as is the current placement.... 
- status above cmdline works in vim due to its lack of feedback, and hence, increases the contrast between the buffer text and cmdline...
But having popups, that's not the case with helix now, so, i can see no reason for keeping status line above (if there is, please share 😃).
- just a small ghost line can be added to increase separation if wanted by team
- but i can see ppl wanting to customise every bit without _any specific reason_ which i aint a fan of.

**Comment by yashpalgoyal1304** [comment]
oh and also, in ur screenshot, one more suggestion is to make the line above (i.e commandline) to switch colors with line below (status line) so that color wise it stays same as before - this will ensure the contrast.

**Comment by Fl1tzi** [comment]
Wouldn't theme editors need to do this? The keys would then be reversed?

**Comment by yashpalgoyal1304** [comment]
ahw 😱 thats a valid concern

**Comment by yashpalgoyal1304** [comment]
but to be practical... it would be half an hour of work doing for all the themes currently distibuted with helix... 

it will be problem only for the themes not officially distributed. umh, i should refrain from saying anything further 😅

**Comment by yashpalgoyal1304** [comment]
hey @Fl1tzi would u create a merge request 😃  ? (aka pull r.)

**Comment by Fl1tzi** [comment]
After I resolve the issue of the status outputs being on the statusline, I will. I am not experienced with the source code yet so let me know how if you know how to move it from the bottom.

**Comment by yashpalgoyal1304** [comment]
> status outputs being on the statusline

umh what? can u rephrase or annotate in screenshot?

**Comment by Fl1tzi** [comment]
Already fixed it. The status messages (when an error happens or you get something returned) are not handled by the prompt itself and therefore were still at the last line. Was just a small fix.

**Comment by mslot** [comment]
> Already fixed it. The status messages (when an error happens or you get something returned) are not handled by the prompt itself and therefore were still at the last line. Was just a small fix.

So this can be closed?

**Comment by Fl1tzi** [comment]
No. It was related to the issue I mentioned above while doing this issue. If #5882 is merged or closed this can also probably be closed.

**Comment by pascalkuthe** [comment]
I don't think we will be going forward with this, see https://github.com/helix-editor/helix/pull/7635#issuecomment-1636878824
