### ISSUE TITLE
Wrong binaries in runtime/grammars for aarch64 package

### ISSUE THREAD

**Issue by appelgriebsch** [helix-editor/helix#577]
Hey,

I downloaded the prebuild binaries for helix-0.4.0 from your GH release page and noticed that the syntax-highlighting feature is no longer working with that.
When investigating I figured that the dynamic linked libraries in runtime/grammars are all build for x64_86 CPU architecture even though I downloaded the aarch64 package, so I assume something might be wrong with the build script / setup....?!

```
file ~/Downloads/helix-v0.4.0-aarch64-linux/runtime/grammars/javascript.so 
[...]/Downloads/helix-v0.4.0-aarch64-linux/runtime/grammars/javascript.so: ELF 64-bit LSB shared object, x86-64, version 1 (SYSV), dynamically linked, BuildID[sha1]=1958acc8edee31aa2465c2c0f62f8cb61222fa01, with debug_info, not stripped
```

**Comment by archseer** [comment]
Good catch.. Maybe the target isn't getting set correctly: https://docs.rs/cc/1.0.69/cc/struct.Build.html#method.target

https://github.com/helix-editor/helix/blob/416720134424402d02f081e6f0e4e29bbc630e1e/helix-syntax/build.rs#L68

**Comment by archseer** [comment]
tree-sitter internals would configure this: https://github.com/tree-sitter/tree-sitter/blob/0fea8c02ee50756a0c493ccc30a0b9749b3bab59/cli/loader/src/lib.rs#L330

**Comment by archseer** [comment]
CARGO_CFG_TARGET_ARCH seems to be what we want

**Comment by appelgriebsch** [comment]
Not sure how the build of the libraries are triggered, but eventually this helper can be useful: https://github.com/rust-embedded/cross

**Comment by kirawi** [comment]
> Not sure how the build of the libraries are triggered, but eventually this helper can be useful: https://github.com/rust-embedded/cross

It's triggered in the aforementioned `build.rs` file, and is triggered if the compiled language (`<lang>.so`) is missing from `runtime/grammars`.

**Comment by archseer** [comment]
Yeah we already use `cross`. It was a bit simpler than that, the tests before release would compile for the host machine, and the grammars would also compile in that step. Then when we compiled the release, they would get detected and skipped. https://github.com/helix-editor/helix/commit/dbd1f11311e72658f81ad50ea500c2710c766fd8

**Comment by archseer** [comment]
> file toml.so
> toml.so: ELF 64-bit LSB shared object, ARM aarch64, version 1 (SYSV), dynamically linked, BuildID[sha1]=36ab51cf8d57254a34f477925be56b4fb5754c77, with debug_info, not stripped

Looks correct now :)
