### ISSUE TITLE
Bad language config: missing field `command` for key `language.language-server`

### ISSUE THREAD

**Issue by yashpalgoyal1304** [helix-editor/helix#5771]
### Summary

- I downloaded `helix 22.12 (96ff64a8)` the prebuilt .zip binary recently, extracted and launched it from there.
- It showed the error given below
- No such error is shown when launching `helix 22.05 (27609f50)`
- I have never touched any language config file for helix whatsoever

This error is also shown when doing `hx --health` for the newer one.

### Reproduction Steps

 

I tried this, and this happened:

```console
# helix 22.12 (96ff64a8)

$ hx
Bad language config: missing field `command` for key `language.language-server`
Press <ENTER> to continue with default language config

<ENTER --> helix launched>

$ hx --health
Config file: 
... MORE ...

Error parsing user language config: missing field `command` for key `language.language-server`
Using default language config
Language        LSP              DAP                   ...
... MORE ...
```

I expected this to happen:

```console
# helix-term 22.05 (27609f50)

$ hx

<helix launches>

$ hx --health
Config file:
... MORE ...

Language        LSP              DAP                   ...
... MORE ...
```

### Helix log

<details><summary>~/.cache/helix/helix.log</summary>

please provide a copy of `~/.cache/helix/helix.log` here if possible, you may need to redact some of the lines

```
2023-01-22T04:50:44.217 helix_view::editor [ERROR] Failed to initialize the LSP for `source.toml` { cannot find binary path }
2023-02-01T21:22:55.785 helix_view::editor [ERROR] Failed to initialize the LSP for `source.toml` { cannot find binary path }
2023-02-01T23:12:38.686 helix_view::editor [ERROR] Failed to initialize the LSP for `source.toml` { cannot find binary path }
2023-02-01T23:14:59.684 helix_view::editor [ERROR] editor error: Register [@] empty
2023-02-01T23:15:01.284 helix_view::editor [ERROR] editor error: Register [@] empty
2023-02-01T23:15:01.542 helix_view::editor [ERROR] editor error: Register [@] empty
2023-02-01T23:15:01.724 helix_view::editor [ERROR] editor error: Register [@] empty
```

</details>

### Platform

Windows 10 20h2

### Terminal Emulator

wezterm 20221119-145034-49b9839f

### Helix Version

helix 22.12 (96ff64a8) and helix 22.05 (27609f50)

**Comment by gabydd** [comment]
What is in your languages.toml?

**Comment by yashpalgoyal1304** [comment]
This seems similar to:
* https://github.com/helix-editor/helix/issues/2058
<tt>Bad language config: unknown field `grammar`, expected `language`</tt>
* https://github.com/helix-editor/helix/issues/4516
<tt>Bad language config: invalid type: map, expected a string for key 'language.file-types'</tt>

**Comment by yashpalgoyal1304** [comment]
```toml
# in %AppData%\helix\language.toml
# 2023-01-01

[[language]]
name ="cpp"
language-server = { args = ["--query-driver=C:/msys64/mingw64/bin/g++.exe"] }
```

**Comment by yashpalgoyal1304** [comment]
oh i had recently uninstalled the g++, does that have smth to do with this? If so, why did v22.05 didn't issue any warning too?

**Comment by gabydd** [comment]
Well it's a pretty big upgrade from 22.05 to 22.12 so I am not exactly sure what changed. As the language-server needs a command to run, its invalid to not provide one which is why an error is shown so the user can fix it in their config. the solution here is to either add back the command part or comment out/remove the language-server section.

**Comment by yashpalgoyal1304** [comment]
i have deleted that file as i am not coding in cpp at the moment. will see someday later, but for the moment, it's fixed.

thanks :smiley:
