### ISSUE TITLE
code completion popup doesn't have margins

### ISSUE THREAD

**Issue by yashpalgoyal1304** [helix-editor/helix#5775]
... at least in the showcase video on homepage

Hi! 
I was watching the helix video at homepage, and noticed that the completion suggestions cling to the left border of popup which makes it hard to differentiate from the sourrounding code.

Is what's shown in video still the case? 
I am just starting with helix and devt; so, couldn't verify it myself...

![helix code completion popup no margin vivaldi_9VePslIb6S](https://user-images.githubusercontent.com/19423063/216138444-8aa4a811-3b97-4206-9318-be8826f78f84.png)

![helix LSP help popup correct margin vivaldi_b1G2LyElVx](https://user-images.githubusercontent.com/19423063/216138464-97773c75-9f4f-4d1e-b666-2847de085f32.png)

**Comment by gabydd** [comment]
![image](https://user-images.githubusercontent.com/82682503/216141947-deed604e-f265-4e36-83bc-70fe64c47231.png)

there definitely is padding in the autocomplete, it might not of shown up correctly cause of the recording or an older helix version, I think the current padding is good though as you can see in the screenshot

**Comment by the-mikedavis** [comment]
The left-margin for completion menus change was part of 22.08 (https://github.com/helix-editor/helix/pull/2728) and I think this video was recorded a while before that.

There have been a bunch of other UI improvements like that we now apply syntax highlighting in hover popups (second screenshot). It would be nice to make a new asciinema recording for the site at some point that shows off newer features. I'll open an issue over in [helix-editor/website](https://github.com/helix-editor/website).

**Comment by yashpalgoyal1304** [comment]
> The scroll bar always looked a little odd to me because it's rather thin and not aligned to the right.
\- @ CptPotato at https://github.com/helix-editor/helix/pull/2728#issuecomment-1152034487

yeah, the scrollbar on the screenshot shared by @ gabydd is also much much better. glad to see both these fixed :)
