### ISSUE TITLE
python syntax highlighting not working

### ISSUE THREAD

**Issue by ivanGuerreschi** [helix-editor/helix#5781]
### Summary

syntax highlighting not working when i open a file in python

### Reproduction Steps

 

I tried this:

1. `hx hello.py`

I expected this to happen: syntax highlighting working for python file

Instead, this happened: syntax highlighting not working

### Helix log

<details><summary>~/.cache/helix/helix.log</summary>

2023-02-02T10:44:47.164 helix_core::syntax [ERROR] Failed to load tree-sitter parser for language "python": Error opening dynamic library "/h>
2023-02-02T10:44:47.165 helix_view::editor [ERROR] Failed to initialize the LSP for `source.python` { cannot find binary path }
```

```

</details>

### Platform

Linux Ubuntu 22.04.1 LTS

### Terminal Emulator

wezterm 20221119-145034-49b9839f

### Helix Version

helix 22.12 (96ff64a8)

**Comment by CptPotato** [comment]
Have you tried fetching and building your grammar files?

Check the [docs](https://docs.helix-editor.com/master/install.html#finishing-up-the-installation) for reference.

**Comment by ivanGuerreschi** [comment]
Yes
hx --grammar fetch
Fetching 123 grammars
123 up to date git grammars

hx --grammar build
Building 123 grammars
123 grammars already built

c and rust syntax highlighting work.
I also tested ruby and perl files and the syntax highlighting doesn't work like in python

**Comment by ivanGuerreschi** [comment]
I have deleting all files and folders of Helix and recompiling, it I have the same errors, it works again with c, c++ rust but not python or ruby.

**Comment by ivanGuerreschi** [comment]
Ok solved by installing the helix-22.12-x86_64-linux.tar.xz release, thanks for the help
