### ISSUE TITLE
Config option - Auto save yanks to registers, e.g 1-9

### ISSUE THREAD

**Issue by StratilJakub** [helix-editor/helix#5783]
This feature / config option would enable saving yanks into registers e.g. 1-9 (history) in addition to default registers (", ...) and it would cycle through these registers.

Often when making changes I don't premeditate all the possible future edits I will do next and often I would need the register state just a couple of edits ago.

I understand this might be very subjective request and that there are external clipboard managers, but that's pretty much another "context switch" - another key-binds etc.

Thanks for your time.

**Comment by askreet** [comment]
I'm interested in picking this up if there's some consensus around adding it. My instinct would be not to make it optional at first, seems generally useful, but that might be my vim bias showing. I'm also wondering if we'd want it shown in the register preview window or not.

**Comment by StratilJakub** [comment]
I considered it should be optional, because someone might have their usual workflow so that they save to register manually and then it would be bad experience if those registers would be automatically replaced.

Also I would say it is quite important those registers are shown in the preview, because if it's auto save, then you will have to actively think of what saved under which register. But I would guess it is a default behaviour, if something is saved under register, then it is available in the preview.

I could also try creating PR eventually, but I am Rust beginner, so it would have higher chance to succeed from someone more experienced. :)

**Comment by pascalkuthe** [comment]
Closing this in favor of https://github.com/helix-editor/helix/issues/6900. The two feature request are basically the same thing with slightly different execution.

We will be using registers 1-9 for regex captures in the future so I open to keep the other issue open instead.
