### ISSUE TITLE
Wrong highlight of wrap in the documentation

### ISSUE THREAD

**Issue by cd-a** [helix-editor/helix#5799]
### Summary

On current master docs, the wrapping section has wrong highlighting:

https://docs.helix-editor.com/master/configuration.html?highlight=wrap#editorsoft-wrap-section

Every instance of `wrap` is highlighted, even outside of the code section.

<img width="819" alt="CleanShot 2023-02-03 at 06 36 55@2x" src="https://user-images.githubusercontent.com/75008413/216521098-91eddebb-e1aa-4190-bb8e-0133b345f048.png">

### Platform

macOS 13.2

### Terminal Emulator

n/a

### Helix Version

n/a

**Comment by CptPotato** [comment]
This is actually the search keyword highlighting `?highlight=wrap`. The problem is only present in the `Colibri (default)` theme.

**Comment by woojiq** [comment]
Can be closed.
