### ISSUE TITLE
Partial aucomplete available for rust

### ISSUE THREAD

**Issue by lunfel** [helix-editor/helix#5800]
### Summary

When I compare autocomplete between Helix and PHPStorm (IntelliJ IDE with Rust extension), I have more autocomplete suggestions with PHPStorm then with Helix.

I am trying to learn to use Helix and Rust by doing advent-of-code with Rust and Helix. When I was working on a challenge I was working with BufReader in Rust, and noticed that it seemed to be missing some methods. So I booted the same code in PHPStorm and to my surprise it had more suggestions than in Helix.

I have looked in the existing issues and I maybe this is related to https://github.com/helix-editor/helix/issues/4831? Are the other completions not showing up considered snippets?

### Reproduction Steps

 

Using this Rust code

```
use std::{
    fs::File,
    io::BufReader,
};

fn main() {
    let file = File::open("input.txt").expect("Count not find input.txt file");

    let buffer = BufReader::new(file);

    buffer.<try autocomplete here>
}
```

I tried this:

1. `hx`
2. Paste the Rust code provided above
3. Save file
4. Move cursor to <try autocomplete here>
5. Notice the provided autocomplete suggestions

I expected this to happen:
Here is the list of methods that can be seen in PHPStorm. I would expect the same result list of suggested methods in Helix
![autocomplete-phpstorm](https://user-images.githubusercontent.com/1844873/216521441-5f42df45-fb2e-4616-a623-cfd1407fa7a7.png)

Instead, this happened:
![autocomplete-helix](https://user-images.githubusercontent.com/1844873/216521528-a21f2f9b-bfe3-4a42-a34a-5063734602ba.png)

### Helix log

<details><summary>~/.cache/helix/helix.log</summary>

```
Nothing relevant to the case
```

</details>

<details><summary>hx --health rust</summary>

```
hx --health rust
Configured language server: rust-analyzer
Binary for language server: /home/mathieu/.cargo/bin/rust-analyzer
Configured debug adapter: lldb-vscode
Binary for debug adapter: Not found in $PATH
Highlight queries: ✓
Textobject queries: ✓
Indent queries: ✓
```

</details>

### Platform

Ubuntu 20.04.5 LTS

### Terminal Emulator

Tilix version: 1.9.1 / VTE version: 0.60 / GTK Version: 3.24.20

### Helix Version

helix 22.12 (96ff64a8)

**Comment by CptPotato** [comment]
If I remember correctly, the IntelliJ IDE uses it's own language integration instead of using the rust-analyzer LSP.

**Comment by ymgyt** [comment]
According to the Intellij Rust plugin [FAQ](https://plugins.jetbrains.com/plugin/8182-rust/docs/rust-faq.html#use-rls-racer-rustanalyzer)

> Does the plugin use RLS, Racer, or Rust Analyzer?﻿

> The plugin’s language analysis is implemented from scratch, leveraging the [IntelliJ Platform](https://www.jetbrains.com/opensource/idea/) infrastructure for incremental analysis and indexing. However, IntelliJ Rust shares some code for procedural macros expansion with [rust-analyzer](https://github.com/rust-analyzer/rust-analyzer).

**Comment by lunfel** [comment]
For the sake of completeness, I have the "[Rust](https://plugins.jetbrains.com/plugin/8182-rust)" plugin for PHPStorm. Currently at version 0.4.187.5175-223

**Comment by CptPotato** [comment]
I don't think there's anything that can bo done here. If you prefer JetBrains' language implementation you can only get it using their editor.

If there are specific completions you are missing, you might have more luck checking rust-analyzers repository/issues.

**Comment by lunfel** [comment]
Ok thanks for the help. I am pretty sure there is something off because it barely bring any value to use it in this state. But I understand that it is not a problem with Helix per say, but maybe somehting to do with my configuration of the lsp or the lsp itself.

Thanks for the quick replies. Helix community is pretty awesome!

**Comment by pascalkuthe** [comment]
Having worked with both extensively: Both rust analyzer and intellij have their advantages, they are both pretty competent and pretty close.

The difference in this case is that only RA shows associated items and traits that are in scope but not trait items of traits that are not in scope. When you start typing it also shows method of traits that would need to be imported. The intend is to prevent performance overhead of looking up all implemented traits and to not clutter the import list with items that are less optimal. This is IMO a better default, not sure if it can be configured.

**Comment by lunfel** [comment]
Oh you are right! In my case I was looking for `.lines()` autocomplete. When there is nothing entered, we don't see it, but if we start narrowing the search, it will show up. It will show up when I will have typed `line` (along with `read_line` method). But if I have BufRead in scope, then it will show up as an autocomplete without any initial chars.

I will check if it can be configured, because I am still new to Rust and I find it hard to "discover" methods when I code. Thanks for all the help!
