### ISSUE TITLE
Incorrect underlining of errors and wrong results from code action

### ISSUE THREAD

**Issue by David-Else** [helix-editor/helix#5809]
### Summary

I think this came from the @pascalkuthe softwrap undated as I have not seen it before, but it is possible it is the language server at fault.

### Reproduction Steps

Create this markdown file:
```markdown
> 💡 If you are using the musl-libc instead of glibc the following environment variable must be set during the build
> to ensure tree sitter grammars can be loaded correctly:
```
Use ltex-ls to spell check:
```
[[language]]
name = "markdown"
max-line-length = 80
language-server = { command = "ltex-ls" }
```
NOTE: Softwrap is turned off.

and it looks like this, the underlines are shifted ahead a character, note this never usually happens:
![Screenshot from 2023-02-03 17-08-36](https://user-images.githubusercontent.com/12832280/216664363-e33107d6-9191-4c2e-9b4b-423709f85dfe.png)

Make the correction:
![Screenshot from 2023-02-03 17-10-52](https://user-images.githubusercontent.com/12832280/216664753-7ffcf07b-de68-4719-9445-99b01edb1428.png)

It fails to replace the word:
![Screenshot from 2023-02-03 17-11-21](https://user-images.githubusercontent.com/12832280/216664878-e171f286-c235-47ef-a8d3-b19f07abe5a1.png)

### Platform

Linux

### Terminal Emulator

Kitty

### Helix Version

https://github.com/helix-editor/helix/commit/30412366be411335b7e2600e9b4178355c27da15

**Comment by pascalkuthe** [comment]
This is fixed by #5711, yet another issue for that. This problem exists eversince LSP support was added to helix tough so not a new problem. You just probably havent' used emojis yet :D
