### ISSUE TITLE
Instruction for Powershell to create a symbolic link is incorrect

### ISSUE THREAD

**Issue by comiluv** [helix-editor/helix#5818]
### Summary

I got ```c1xx: fatal error C1083: Cannot open source file: '\\scanner.cc': No such file or directory``` errors similar to #4183 because symlink was not created using the Powershell command provided in the README.md
It should be a directory junction instead of a symlink. So correct Powershell command is ```New-Item -ItemType Junction -Target "fullpath_to_runtime" -Path "$Env:AppData\helix\runtime"```

### Reproduction Steps

n/a

### Helix log

n/a

### Platform

Windows 11

### Terminal Emulator

Windows Terminal

### Helix Version

helix 22.12 (7b46a6ca)

**Comment by archseer** [comment]
Please open a PR
