### ISSUE TITLE
Create a new named buffer using `:new ...`

### ISSUE THREAD

**Issue by CptPotato** [helix-editor/helix#5867]
The `:new` command currently doesn't handle parameters that you pass to it. 

I think this is confusing in cases where you want to create a new document `:new foo.rs` and then save it using `:w` (helix reports an error "Can't save with no path set!" instead). In contrast to that, `:open foo.rs` actually has this behavior when the file does not exist, even though technically it's not "opening" a file.

In my opinion `:new foo.rs` should either work like `:open foo.rs` or provide an error message if parameters are passed. Another possibility is merging both into one command (implementation) where zero arguments creates a new scratch buffer and one or more would function like `:open`.

Initially discussed in #5865

**Comment by pascalkuthe** [comment]
You can use :open for that see discussion in #6668
