### ISSUE TITLE
Certain characters cutoff in rust comments when using onedarker theme

### ISSUE THREAD

**Issue by freych** [helix-editor/helix#5875]
### Summary

When using helix I noticed that if I type a comment sometimes the last character of a highlighted word like TODO here will be cutoff on the upper right. I have attached an image showing the behavior.  

Let me know if I am just doing something wrong to trigger this, it seems related to the theme.

Thank you!

![Screenshot_20230207_055211](https://user-images.githubusercontent.com/15348699/217385961-b3ec83af-ea6c-4420-a921-ebe3fa86b34a.png)

### Reproduction Steps

I installed Helix by cloning the repo and following the direction to build it.

I am using the onedarker theme and when I disable it the issue goes away since the 'TODO' isn't italicized or colored anymore.
![Screenshot_20230207_060703](https://user-images.githubusercontent.com/15348699/217387276-5479696b-1b32-4c07-a53b-73ca265335d1.png)

My config file:
theme = "onedarker"

[editor]
true-color = true
line-number = "absolute"
mouse = false
auto-pairs = true # defaults to `true`
bufferline = "always"
color-modes = true
auto-save = true

[editor.cursor-shape]
insert = "bar"

### Helix log

[helix.log](https://github.com/helix-editor/helix/files/10680087/helix.log)

### Platform

WSL

### Terminal Emulator

Windows Terminal 1.15.3466.0

### Helix Version

helix 22.12 (64ec0256)

**Comment by the-mikedavis** [comment]
It looks like it gets cut off on the border of a highlight for italic text. Can you try another terminal emulator like Alacritty, Wezterm or Kitty? I think this is a terminal emulator rendering issue rather than a Helix issue

**Comment by freych** [comment]
I tried nushell in Microsoft Terminal and its working perfectly. I guess it an issue with the default wsl terminal.

You can close the issue, and thanks again!
