### ISSUE TITLE
Tutor doesn't show up

### ISSUE THREAD

**Issue by ClementNerma** [helix-editor/helix#5876]
### Summary

So, maybe I'm dumb, but on latest version I can't seem to open the tutor.
Weither I use `:tutor` or run `hx --tutor`, absolutely nothing happens.

### Reproduction Steps

Run hx with `--tutor` or use `:tutor`

### Helix log

<details><summary>~/.cache/helix/helix.log</summary>

```
<EMPTY> (0 byte)
```

</details>

### Platform

WSL on Windows 11

### Terminal Emulator

Windows Terminal

### Helix Version

helix 22.12 (96ff64a8)

**Comment by the-mikedavis** [comment]
You need to set up the runtime directory: https://github.com/helix-editor/helix/blob/c704701714236f9de9fdb03823b6adb9227be744/README.md#L60-L96

How did you install? Build from source, a package manager, or one of the binaries from https://github.com/helix-editor/helix/releases/latest?

**Comment by ClementNerma** [comment]
Thanks! I'm going to try that.
It was from the release page ([helix-22.12-x86_64-linux.tar.xz](https://github.com/helix-editor/helix/releases/download/22.12/helix-22.12-x86_64-linux.tar.xz))

**Comment by ClementNerma** [comment]
Maybe it could be an idea to show an error message if the runtime directory isn't available, instead of silently failing?

**Comment by the-mikedavis** [comment]
There's a PR along those lines: https://github.com/helix-editor/helix/pull/5076

Explaining what the runtime directory is and how to fix it takes a fair amount of text though so we're waiting on support for in-editor longer form documentation (#997)
