### ISSUE TITLE
for future vscode code extension, headless mode {feature request}

### ISSUE THREAD

**Issue by mu-us61** [helix-editor/helix#5880]
hello vim has 2 main extension in vscode , so neovim one says in his description it is more than an emulation , it uses headless mode of nvim so that means I guess you can use with additional nvim extensions , I think vscode helix extension is also important it provides more smooth transaction to helix step by step , people getting used to it on vscode , so it would be nice to have a headless helix extension for vs code

**Comment by archseer** [comment]
Duplicate of https://github.com/helix-editor/helix/issues/312
