### ISSUE TITLE
Visual minimalism

### ISSUE THREAD

**Issue by zuixalias** [helix-editor/helix#5884]
Please add options to disable gui elements wherever possible, mainly :
- Disable minor mode popups
- Disable commands popup (the view containing suggestions for available commands when `:` is pressed)
- Disable text highlight when navigating in Normal Mode (this doesn't seems sensible so leave it maybe)

**Comment by vwkd** [comment]
As for the first, you can disable infoboxes in the config ([`auto-info`](https://docs.helix-editor.com/configuration.html#editor-section)). As for the third, not sure if it's helpful but you could take a look at the themes. Some color the selection barely visible, maybe that's what your looking for. Maybe someone in the [Matrix chat](https://matrix.to/#/#helix-community:matrix.org) can answer more.
