### ISSUE TITLE
Allow for default mode setting

### ISSUE THREAD

**Issue by ShalokShalom** [helix-editor/helix#5896]
Hi lovely folks 🌷 

I am currently looking for a setting, that allows me to specify the mode, at which I like Helix to launch with. It seems like basically one of the more fundamental features to me, while I can see that this is obviously not the case for everyone else. 

Could we introduce such a thing, pretty please 😊

**Comment by askreet** [comment]
By mode do you mean e.g. normal mode? What mode would you want to launch in besides normal?

**Comment by archseer** [comment]
See https://github.com/helix-editor/helix/pull/3366

**Comment by gabydd** [comment]
Oh it was a pr I knew I saw this somewhere but I couldn't find it

**Comment by ShalokShalom** [comment]
I commented on the PR
