### ISSUE TITLE
Suggest how to close the editor with unsafed scratch 

### ISSUE THREAD

**Issue by ShalokShalom** [helix-editor/helix#5899]
Hi folks 🌞 

When the editor is trying to be closed, while a scratch is still unsaved, does the editor refuse to close with Ctrl + w q, which is the default way newcomer would exit it. 

Also !quit does not work, obviously. 

This is fine. 👍🏻 
And it is also fine, to explain a newcomer, how to close the editor when they want. 😄 

The behavior has been discussed in https://github.com/helix-editor/helix/issues/1037 and I think its fine, as it is. 

Can we please add 

**If you are sure, that you want to close anyway, use :q! (close) or :x (save and close)**
to the error message that appears, when they are trying to close it? 😄

**Comment by pascalkuthe** [comment]
Improving an error message is simple, you can open a PR

**Comment by ShalokShalom** [comment]
No, thanks.
