### ISSUE TITLE
Cross compiling does not work

### ISSUE THREAD

**Issue by MrAdityaAlok** [helix-editor/helix#590]
When I cross-compiled it on ubuntu for Termux(Android), I do not know why but the grammer libs is not used, ie. no syntax highlighting. But when I compile natively in termux everything works fine.

So, I needed help in finding where could be the problem..... maybe something in build which need to be patched for android....?

EDIT: This happens for every arch (aarch64, arm, x86_64 and i686) so maybe some dependency I missed...

*Termux official build system uses cross-compilation, so it is only the option to get it into official repo*

**Comment by kirawi** [comment]
https://github.com/helix-editor/helix/wiki/Troubleshooting#missing-syntax-highlighting?

**Comment by archseer** [comment]
What exact command do you use for cross compiling? Did you compile for your system beforehand?

There was a similar issue in https://github.com/helix-editor/helix/issues/577 where it would detect old shared libraries and wouldn't rebuild them.

Try wiping all the grammars and helix-syntax:

```
rm runtime/grammars/*
cargo clean -p helix-syntax
```

Then cross compiling again. If you inspect one of those shared libraries (i.e. `file runtime/grammars/toml.so`) it should show the correct architecture:

(example when I cross compiled to aarch64)

```
file toml.so
toml.so: ELF 64-bit LSB shared object, ARM aarch64, version 1 (SYSV), dynamically linked, BuildID[sha1]=36ab51cf8d57254a34f477925be56b4fb5754c77, with debug_info, not stripped
```

**Comment by MrAdityaAlok** [comment]
@archseer 

> What exact command do you use for cross compiling? 

`cargo build --target aarch64-linux-android --release` (*and yes, I have tools for aarch64 android installed using rustup*)

> If you inspect one of those shared libraries (i.e. file runtime/grammars/toml.so) it should show the correct architecture

Yes it is for aarch64

I found something strange when I inspected the shared lib using [`nm`](https://linux.die.net/man/1/nm) tool. Libs built on device natively(i.e on Android in termux) had symbols  but cross-compiled libs had no symbols.

Native build:
```
0000000000002dd8 a _DYNAMIC
0000000000002ff8 a _GLOBAL_OFFSET_TABLE_
00000000000014d0 r __GNU_EH_FRAME_HDR
0000000000000974 t __atexit_handler_wrapper
0000000000003828 B __bss_end__
0000000000003810 B __bss_start
0000000000003810 B __bss_start__
                 U __cxa_atexit@LIBC
                 U __cxa_finalize@LIBC
0000000000002dd0 d __dso_handle
0000000000002dd0 d __dso_handle_const
000000000000096c t __emutls_unregister_key
0000000000003828 B __end__
0000000000000960 t __on_dlclose
0000000000000970 t __on_dlclose_late
                 U __register_atfork@LIBC
0000000000003828 B _bss_end__
0000000000003810 D _edata
0000000000003828 B _end
0000000000000980 t atexit
0000000000001594 r ndk_build_number
0000000000001554 r ndk_version
000000000000153c r note_android_ident
0000000000001550 r note_data
00000000000015d4 r note_end
0000000000001548 r note_name
000000000000099c t pthread_atfork
00000000000009a8 T tree_sitter_json
0000000000003000 d tree_sitter_json.language
0000000000003812 b ts_alias_sequences
00000000000013c0 r ts_field_map_entries
00000000000013b8 r ts_field_map_slices
0000000000003468 d ts_field_names
00000000000009b4 t ts_lex
0000000000003790 d ts_lex_modes
0000000000003810 b ts_non_terminal_alias_map
0000000000003510 d ts_parse_actions
00000000000034b0 d ts_parse_table
00000000000030e0 d ts_small_parse_table
0000000000003330 d ts_small_parse_table_map
0000000000003480 d ts_symbol_map
00000000000013c8 r ts_symbol_metadata
00000000000033a8 d ts_symbol_names
```
Cross-compiled:
```
$ nm runtime/grammars/json.so
nm: runtime/grammars/json.so: no symbols
```

I do not known why this happens.

**Comment by archseer** [comment]
I think if you cross compile you need to use the architecture appropriate `nm` (for ARM that's `arm-none-eabi-nm` for example)? What's the filesize on the crosscompiled one?

**Comment by MrAdityaAlok** [comment]
> I think if you cross compile you need to use the architecture appropriate `nm` (for ARM that's `arm-none-eabi-nm` for example)? 

Yes my `nm` is alias to architecture specific `aarch64-linux-android-nm` 

What's the filesize on the crosscompiled one?

Cross-compiled: `12K     ./json.so`
Native: `24K     ./json.so`


Do build use `libc++ static`? I think so by looking at output of `ldd`. If it is the case then it need to be patched, Android has `libc++ static` in ndk-multilib, and please tell me where I need to  patch it.

**Comment by archseer** [comment]
I don't think so, it's all dynamically linked for me:
```
 └─ ldd toml.so
	linux-vdso.so.1 (0x00007ffc6a731000)
	libstdc++.so.6 => /nix/store/9jsfqb2f8229hly49vdsyyhn3nb0j98a-devshell-dir/lib/libstdc++.so.6 (0x00007fe8d1fab000)
	libm.so.6 => /nix/store/j5p0j1w27aqdzncpw73k95byvhh5prw2-glibc-2.33-47/lib/libm.so.6 (0x00007fe8d1e6a000)
	libgcc_s.so.1 => /nix/store/9jsfqb2f8229hly49vdsyyhn3nb0j98a-devshell-dir/lib/libgcc_s.so.1 (0x00007fe8d1e50000)
	libc.so.6 => /nix/store/j5p0j1w27aqdzncpw73k95byvhh5prw2-glibc-2.33-47/lib/libc.so.6 (0x00007fe8d1c8b000)
	/nix/store/cvr0kjg2q7z2wwhjblx6c73rv422k8cm-glibc-2.33-47/lib64/ld-linux-x86-64.so.2 (0x00007fe8d218c000)
```

Here's the actual build process all the grammars go through: https://github.com/helix-editor/helix/blob/a2cd9cce9d2fb809daff89716810ec2b8192ffa0/helix-syntax/build.rs#L90-L110

**Comment by MrAdityaAlok** [comment]
@archseer thank you ! For all your help. Issue is fixed now. `hx` binary was not able to find `libc++_shared.so`

**Comment by archseer** [comment]
Glad it helped! Thanks for maintaining the Termux package! 🎉

**Comment by jmascarua** [comment]
Just to add for posterity that using *cross* works like a charm.

* Install cross
  `cargo install cross`
* Cross compile helix
  `cross build --release --target armv7-unknown-linux-gnueabihf`

and that is amazing.
