### ISSUE TITLE
Choose filetype using file extension rather than filename (in this edge case)

### ISSUE THREAD

**Issue by David-Else** [helix-editor/helix#5901]
Try renaming a shell script to `md`, it will open as a Markdown file?! I would have imagined a `.md` would be needed to make this happen.

**Comment by gabydd** [comment]
There is some discussion similar to this here https://github.com/helix-editor/helix/issues/5869#issuecomment-1420875698

**Comment by the-mikedavis** [comment]
This is the same behavior as in #5869, I'll close in favor of that issue
