### ISSUE TITLE
documentation is not hidden automatiically after end typing of the code need manual esc

### ISSUE THREAD

**Issue by victororlyk** [helix-editor/helix#5906]
### Summary

docs poup is not closed automatically when i type outside of that block code. Which may result in not being able to see what you type when you work at the top of the file, or popyp is big enough

https://user-images.githubusercontent.com/33072590/218174736-fd988cc7-c356-4f8f-9664-1fb5c8509658.mov

### Reproduction Steps

 

I tried this:

1. `hx .` in rust project
2. at the top of any file start typing
```rust
pub fn some() -> Result<()> {
let i  = 
```
I expected this to happen:
when i start typing `{ ` so i am out of Result block it should stop showing docs for Result

Instead, this happened:
I need to click `esc` to close docs popup

### Helix log

<details><summary>~/.cache/helix/helix.log</summary>

```
please provide a copy of `~/.cache/helix/helix.log` here if possible, you may need to redact some of the lines
```

</details>

### Platform

macOS

### Terminal Emulator

alacritty

### Helix Version

helix 22.12 (96ff64a8)

**Comment by pascalkuthe** [comment]
I can reproduce this, the popup disappears after deleting some text tough. It's fairly persistent and even sticks around when other documentation popups from a new autocompletion are shown.

**Comment by woojiq** [comment]
https://github.com/helix-editor/helix/blob/d52b790379ffc5646409a9972e0a4e70bcc8a981/helix-term/src/commands.rs#L3411-L3414
```diff
- let close_triggers = &[')', ';', '.'];
+ let close_triggers = &[')', ';', '.', '>'];
```
This is the only change that needs to be made :smiley:. I tested manually and it works. But I'm wondering if there are languages where the signature help is closed with `}`, `]` or some other character not mentioned above?

**Comment by pascalkuthe** [comment]
that's more of a bandaid, all that does it closing the signature help on `>` we need a more robust way of closing the signature help

**Comment by woojiq** [comment]
Rust-analyzer defines the trigger symbols here: https://github.com/rust-lang/rust-analyzer/blob/3759c41d3c6966eb3aa18ad5916c0da65ff19641/crates/rust-analyzer/src/caps.rs#L55C1-L55C1
```rust
trigger_characters: Some(vec!["(".to_string(), ",".to_string(), "<".to_string()]),
```
I see a solution where we take this list of trigger characters from lsp and matching it with the corresponding closing characters (`(` -> `)`; `<` -> `>` etc). The second list is our `close_triggers`. Sounds good, right :disappointed_relieved:?

**Comment by pascalkuthe** [comment]
that would be an improvement but doesn't close this issue, signature help doesn't have to be triggered by trigger chars and can occur elsewhere. To fix this issue we would need to rerequest the signature help whenever the document contents change (and the signature help is virible) That's what vs code does too. We might want to debounce this a bit , and the implementation is in essence quite similar to what I will add for completions in the future (using a generailezed event system/debouncer) and should likely wait for those changes.
