### ISSUE TITLE
Pasting to system clipboard doesn't work.

### ISSUE THREAD

**Issue by jacob-emery** [helix-editor/helix#5915]
### Summary

I tried to select some text and copy it to the system clipboard, however it doesn't work on NixOS (under Wayland).

### Reproduction Steps

 

I tried this:

1. Selected some text
2. Press <Space>+y

I expected this to happen:
Text ought to be copied to system clipboard. 

Instead, this happened:
Nothing got copied to system clipboard.

### Helix log

<details><summary>~/.cache/helix/helix.log</summary>

```
2023-02-05T17:56:52.364 helix_view::clipboard::provider [WARN] No clipboard provider found! Yanking and pasting will be internal to Helix
```

</details>

### Platform

NixOS

### Terminal Emulator

GNOME Terminal, GNOME BlackBox

### Helix Version

helix 22.12

**Comment by David-Else** [comment]
> Press +y

You do mean space + y?

On RHEL and Fedora there is a some default built in Wayland clipboard that works out of the box, you might need to install a Wayland clipboard if you don't have one. Try:
```
hx --health | grep clipboard
```

**Comment by manuel-plavsic** [comment]
Thanks for your prompt answer. I meant space + y, yes.

I just found out that it only doesn't work with sudo.

```
> hx --health | grep clipboard
System clipboard provider: wl-paste+wl-copy

> sudo hx --health | grep clipboard
System clipboard provider: termcode
```

The package `wl-clipboard` is installed for all users, so I don't know why I am getting this.

**Comment by manuel-plavsic** [comment]
Is there a way to edit system files using `hs` instead of `sudo hs` and then save them with root privileges?

**Comment by jacob-emery** [comment]
Thanks for your prompt answer. I meant space + y, yes.

I just found out that it only doesn't work with sudo.

```
> hx --health | grep clipboard
System clipboard provider: wl-paste+wl-copy

> sudo hx --health | grep clipboard
System clipboard provider: termcode
```

The package `wl-clipboard` is installed for all users, so I don't know why I am getting this.

Or is there a way to edit system files using `hs` instead of `sudo hs` and then save them with root privileges?

**Comment by David-Else** [comment]
I am afraid I don't know the answers to your questions, but there are a lot of NixOS users here, so I am sure someone can help you soon.

**Comment by David-Else** [comment]
> Or is there a way to edit system files using hs instead of sudo hs and then save them with root privileges?

Use sudoedit:

```
export SUDO_EDITOR="/home/username/.cargo/bin/hx"
```

**Comment by jacob-emery** [comment]
I had some issues getting the environment variables to be recognized by NixOS. They now work. Copy paste now works with `sudoedit`. Thank you @David-Else
