### ISSUE TITLE
Directory-wide configuration

### ISSUE THREAD

**Issue by fnuttens** [helix-editor/helix#5919]
## Current behavior

I am not aware of such a local configuration feature at the moment. It is possible to specify a custom config file when launching helix but it completely overrides the main configuration (`~/.config/helix/config.toml`).

## Feature description

It would be so cool that helix search for a local configuration (such as `./.hx/config.toml`) and use it to override only the parameters that are mentioned. I believe that is exactly what other popular editors do, like VSCode.

## Motivation

There are many reasons one might need a local configuration.  
My last example is this: I started doing the [Ruby Koans](https://github.com/edgecase/ruby_koans), and for this I need to edit the files located in the `koans` folder (generated by a rake command). This folder is marked in the `.gitignore` file, which makes sense from a maintainer point of view.

By default the helix file picker will ignore files according to `.gitignore`, which also makes sense for the majority of cases.  
Without a local configuration however, I need to type the command `:set-option file-picker.git-ignore false` every time I open helix in this directory.

**Comment by pascalkuthe** [comment]
This feature is added in #5748.

With that PR it is possible to add `.helix/config.toml` at the root of your workspace/git repo which overwrites existing config options.

**Comment by fnuttens** [comment]
Brilliant, thank you guys! And sorry, I should have looked in the PRs before creating this issue.

**Comment by yashpalgoyal1304** [comment]
> And sorry, I should have looked in the PRs before creating this issue.

umh, it's actually good that u created this non-duplicate issue - as most ppl (including me) only look at one place - that is that issues....
