### ISSUE TITLE
Increment and Decrement Behavior When No Number Under Selection

### ISSUE THREAD

**Issue by Aesthetikx** [helix-editor/helix#5928]
While going through the tutor, I came across "Note: If there isn't a number under the selection the cursor will jump to the next number in the line and act on it". On master, this does not appear to be the case, so it is either a bug or the tutor text should be updated.

**Comment by the-mikedavis** [comment]
That behavior was intentionally removed in #4123 but it looks like we forgot to update the tutor. That line is here: https://github.com/helix-editor/helix/blob/3b301a9d1d832d304ff109aa9f5eee025789b3e8/runtime/tutor#L833-L834

Would you like to open a PR to fix this? We should remove those two lines (and replace them with blank lines to keep the number of rows in each section the same).

**Comment by Aesthetikx** [comment]
Well, I guess I'm a contributor now! First real world usage of helix.
