### ISSUE TITLE
Helix not running in Windows Server Core

### ISSUE THREAD

**Issue by zcobol** [helix-editor/helix#5935]
### Summary

Add `helix` to Windows Server Core w/out `Desktop Experience` installed. Editor  is not launching.

### Reproduction Steps

 

I tried this:

I expected this to happen:

Instead, this happened:

### Helix log

<details><summary>~/.cache/helix/helix.log</summary>

</details>

### Platform

Windows

### Terminal Emulator

conhost

### Helix Version

latest helix release

**Comment by pascalkuthe** [comment]
You need to provide more detail here. Nonw of the devs use windows server core. What happens when you try to launch helix? Is there an error message?. 

Please try to fill in all steps of the bug report template in more detail.

**Comment by pascalkuthe** [comment]
C
