### ISSUE TITLE
Use helix logo as icon for the `hx` executable 😋 

### ISSUE THREAD

**Issue by goyalyashpal** [helix-editor/helix#5940]
### Helix logo as icon file
* Is the icon file (not png image) for the new helix logo shared anywhere here on github repo or in the binary?
* as i found that [shortcut suggestion] to be _really_ effective, 
* and having the nice helix logo as the icon will be aweome.

[shortcut suggestion]: https://github.com/helix-editor/helix/issues/39#issuecomment-1418562617

### Proposal
* Can that icon be put on the `hx` executable file too? 
* I know that TUI exe files don't have any icon (and understandably too) but i'd say it doesn't hurt to have it there or does it?

in hx 22.12 the icon for exe is this:  ![doublecmd_VPMBhqyHf3](https://user-images.githubusercontent.com/19423063/218294311-747976cb-9bf6-4d6a-ad88-d1d7e3392513.png)

### Screenshots

<img src="https://user-images.githubusercontent.com/19423063/218294795-946214dc-753e-4b87-94ff-1999ec606da5.png" width=500px/>

<img src="https://user-images.githubusercontent.com/19423063/218294727-8e4e4312-d89e-43cc-a6e1-48a1193d7637.png" width=550px/>

**Comment by yashpalgoyal1304** [comment]
- I tried changing the icon for that shortcut file, but it still shows the wezterm icon in the start menu.
- wezterm - that's the program which is the shortcut points to...

So, it may not be possible to use the icon to shortcut after all - even despite using it for the .exe file.

**Comment by yashpalgoyal1304** [comment]
Anyways: for those interested: 
- here's the .ico file in square proportions i created using GIMP
- It's 24 bit with alpha (i.e. the alpha is one bit) not 32-bit.

It looks really nice. really, so many people pitched in and the gradual blooming of the ideas for logo was nice to see.

- @ DrZingo 's https://github.com/helix-editor/helix/issues/283#issuecomment-864398370
- @ rscircus 's https://github.com/helix-editor/helix/issues/283#issuecomment-1019585608
- @ oati 's https://github.com/helix-editor/helix/issues/283#issuecomment-1114074064 - which brought these all together
- @ jakehl 's revisions after there: https://github.com/helix-editor/helix/issues/283#issuecomment-1119103281

![image](https://user-images.githubusercontent.com/19423063/218296969-308f04c4-54a7-4986-bc62-bfb0c28b666c.png)

Github wasn't allowing .ico files, so, i renamed to .png. Rename it back to .ico to use this:

[helix-logo](https://user-images.githubusercontent.com/19423063/218297679-90d1688d-c22e-466c-b51b-dd335e22e2ca.png)

**Comment by yashpalgoyal1304** [comment]
Here was some resources i found to add icons to executables:
- how-do-i-set-the-icon-for-my-application-in-visual-studio-2008
https://stackoverflow.com/questions/320677/
- how-to-add-an-icon-of-my-own-to-a-python-program
https://stackoverflow.com/questions/16782047/
- ddg 🔍 : [how to give icons to executables](https://duckduckgo.com/?q=how+to+give+icons+to+executables&t=vivaldi&ia=web)

**Comment by NewtonChutney** [comment]
> So, it may not be possible to use the icon to shortcut after all - even despite using it for the .exe file.

Hey @goyalyashpal though the shortcut is out of scope of this project, I think the exe file produced ought to have this icon embedded in it.. could you reopen this issue?

**Comment by archseer** [comment]
The icon isn't showing up for you because your shortcut is calling wezterm which is then running helix (so wezterm is the program getting started). You can change the icon manually on your end but there's nothing else we can do. The icon is used in flatpak and some other packages from what I remember.

**Comment by goyalyashpal** [comment]
@NewtonChutney does above addresses ur concern? be sure to inform - as i had already closed the issue on my end & have opened up only for u.

**Comment by NewtonChutney** [comment]
> > So, it may not be possible to use the icon to shortcut after all - even despite using it for the .exe file.
> 
> Hey @goyalyashpal though the shortcut is out of scope of this project, I think the exe file produced ought to have this icon embedded in it.. could you reopen this issue?
> There would be cases where hx.exe is directly pinned to start.. or launched in Win+R dialog box

@archseer the main exe file in Windows doesn't have an icon.. 
Could that be fixed? When pinned to start, or set as a profile in Windows Terminal, we could use the inbuilt icon if it had one..

**Comment by NewtonChutney** [comment]
> @NewtonChutney does above addresses ur concern? be sure to inform - as i had already closed the issue on my end & have opened up only for u.

Nope, @archseer meant about the shortcut. . But not the executable.. 😅

**Comment by NewtonChutney** [comment]
> ### Helix logo as icon file
> * Is the icon file (not png image) for the new helix logo shared anywhere here on github repo or in the binary?

> ### Proposal
> * Can that icon be put on the `hx` executable file too? 

The proposal is legit not only for shortcuts.. Would be my rebuttal.. 🫠

**Comment by archseer** [comment]
hx is a terminal application and won't work if started directly I assume.

**Comment by NewtonChutney** [comment]
> hx is a terminal application and won't work if started directly I assume.

😅 It does.. (gets opened in WT, instead of conhost) 
I use it to traverse into my ssh config file everytime from the run dialog (win+r)

**Comment by NewtonChutney** [comment]
Looks like this would better suit helix's build than nushell's wix toolset
https://github.com/mxre/winres
