### ISSUE TITLE
Unable to type characters with AltGr modifier

### ISSUE THREAD

**Issue by CptPotato** [helix-editor/helix#595]
As of helix 0.4.0 I'm unable to type any characters that require the <kbd>AltGr</kbd> modifier key.
This appears to be a regression somewhere between version 0.3.0 and 0.4.0 of helix.

### Environment

- Platform: Win10 x64
- Helix version: 0.4.0/0.4.1 (from Github releases)

**Comment by CptPotato** [comment]
It appears that the fix for prompts in [`5cee3b6` (l. 530-537)](https://github.com/helix-editor/helix/commit/5cee3b634d3763dfdb0312d1dc58f6ebcfccb4bf#diff-910b0deb36d6f016258fafae83ea994d924230f49ab46dce71ff326a4a06e3efR530-R537) doesn't work as expected.
To be more precise, <kbd>AltGr</kbd> seems to be interpreted as <kbd>Ctrl</kbd> + <kbd>Alt</kbd> and won't pass the check in [`prompt.rs:534`](https://github.com/helix-editor/helix/commit/5cee3b634d3763dfdb0312d1dc58f6ebcfccb4bf#diff-910b0deb36d6f016258fafae83ea994d924230f49ab46dce71ff326a4a06e3efR534).

I tested it with the following change and I'm now getting the "correct" behaviour. This might need more thought, however... I'm not sure if this breaks other input combinations sequences.

```rust
/* ... */

    } if !modifiers.contains(KeyModifiers::CONTROL)
        || (modifiers.contains(KeyModifiers::CONTROL | KeyModifiers::ALT)) =>
    {
        self.insert_char(c);
        (self.callback_fn)(cx, &self.line, PromptEvent::Update);
    }

/* ... */
```

**Comment by CptPotato** [comment]
@archseer sorry for pinging but I want to mention again that this issue isn't fully fixed, see my previous comment.

Maybe it's better to keep the issue open for now?

**Comment by archseer** [comment]
Sorry, I somehow completely missed the last message! Reopening and will take a look at the patch.

**Comment by KlasMvW** [comment]
Is there a plan for a patch for this? I understand if Windows is not a priority platform but Helix is a such a great editor and the only select-based editor for Windows AFAIK. The AltGr characters are essential for regex so it would be nice to have it fixed.

**Comment by CptPotato** [comment]
This might also be a crossterm issue, depending on what the expected behavior is.

For example, on a german keyboard layout <kbd>AltGr</kbd> + <kbd>q</kbd> is used to type `@`.
However, crossterm reports this as:

```rust
KeyEvent { code: Char('@'), modifiers: CONTROL | ALT }
```

So on top of the "resolved" character `@` there's the additional <kbd>Ctrl</kbd> + <kbd>Alt</kbd> modifiers that interfere with how helix handles the inputs in the prompt component.

**Comment by archseer** [comment]
Hmm, looks like `ctrl` + `alt` sequence has special meaning as `alt gr`: https://devblogs.microsoft.com/oldnewthing/20040329-00/?p=40003

**Comment by archseer** [comment]
Sorry for the great delay on this, I've removed the limitation on the prompt.

**Comment by CptPotato** [comment]
> Sorry for the great delay on this, I've removed the limitation on the prompt.

No worries. I can confirm that it works correctly now 👍

**Comment by mscofield0** [comment]
helix 22.05 (27609f50)
I'm still having issues in the newer versions.
