### ISSUE TITLE
Better highlight breakpoints and current line at which execution is paused at

### ISSUE THREAD

**Issue by filipdutescu** [helix-editor/helix#5952]
# Description

Currently, breakpoints do not use a conventional symbol, such as the classic filled red circle. The current line at which execution is paused at is also not properly shown. This makes debugging at least somewhat more challenging than it should probably be. 

# Proposal

1. Change the current symbol to the aforementioned conventional one
2. Add new theme highlights for breakpoint and current line colors
3. Highlight the current line at which debugging is stopped at 

# UI mockup
![image](https://user-images.githubusercontent.com/46979062/218331603-f906a601-568f-41a6-8a46-67a0ec696fa7.png)

**Comment by pascalkuthe** [comment]
I think this would be quite easy to accomplish by:
Right now in `helix-term/src/ui/editor.rs:114` the highlight is set to:
``` rust
let style = theme.get("ui.highlight");
```

I think all you would need to do is use a custom theme key here like `ui.highlight.breakpoint` and add it to a couple of themes. That would be a very uncontroversial change.

Regarding the gutter I think #5371 could provide a means to customize the exact icon.

In a TUI our hands are a bit bound with the styling of the icon. 
The red circle is already used for diagnostic errors and it doesn't look as nice as in your mockup because its quite a bit smaller:
![image](https://user-images.githubusercontent.com/61850714/218332638-0a1008a4-95c7-478d-bd71-8e58c408d94a.png)

You could consider experimenting whether setting this to bold or using a different icon works better

**Comment by filipdutescu** [comment]
I used the NerdFonts `na-fa-circle` icon in my mockups.

![image](https://user-images.githubusercontent.com/46979062/218332783-e97cc82d-99a1-41d6-8b34-4e65d695744d.png)

We could probably use that (togglable/customizable of course, since maybe not everyone has nerdfonts). Would you say this change is dependent on #5371 then?

**Comment by pascalkuthe** [comment]
If you want to use a nerdfont symbol this would depend on #2869 instead.

In general we would not be using nerdfont icons by default to ensure helix can be rendered everywhere with just default fonts. Although we could just keep the current icons for now (I think the red hihglight already goes a long way) and only change the icon for use with nerdfonts once #2869 lands

**Comment by filipdutescu** [comment]
I could substitute it for a `B` in the meantime I guess. Is there any resource on how to find default icons? Or how where those already existing chosen?

**Comment by filipdutescu** [comment]
Let's make it with the current available icons for now and when #2869 lands we can explore adding nerdfont icons.

**Comment by archseer** [comment]
You can just use the same dot we use for diagnostics

**Comment by archseer** [comment]
Rather than a dot, a triangle seems a lot more fitting 
![image](https://user-images.githubusercontent.com/1372918/218357161-9e647f19-4592-40a1-9c2a-4c2acf3b4a2f.png)

`▶` and `▷` taken from https://en.wikipedia.org/wiki/Geometric_Shapes_(Unicode_block)

**Comment by archseer** [comment]
I'd prefer a lighter highlight than red, which is why I picked the existing `ui.highlight` color. Some more design ideas here: https://emacs-lsp.github.io/dap-mode/page/gallery/

**Comment by filipdutescu** [comment]
> You can just use the same dot we use for diagnostics

Precisely what I did for the current implementation. I would like to offer, in the future, the possibility of user-defined icons, probably by means of nerdfonts.

> Rather than a dot, a triangle seems a lot more fitting 
> ![image](https://user-images.githubusercontent.com/1372918/218357161-9e647f19-4592-40a1-9c2a-4c2acf3b4a2f.png)
> 
> `▶` and `▷` taken from https://en.wikipedia.org/wiki/Geometric_Shapes_(Unicode_block)

I assume you mean for the current line at which execution is paused at. If so, I agree, this would be a good improvement, but I think the only way to do it is to override the breakpoint icon with the triangle one, right?

**Comment by filipdutescu** [comment]
> I'd prefer a lighter highlight than red, which is why I picked the existing `ui.highlight` color. Some more design ideas here: https://emacs-lsp.github.io/dap-mode/page/gallery/

Will modify the default theme according to your preference then. Thanks for letting me know, I used that colour as it is what I am accustomed to.

**Comment by CptPotato** [comment]
> In general we would not be using nerdfont icons by default to ensure helix can be rendered everywhere with just default fonts. Although we could just keep the current icons for now (I think the red hihglight already goes a long way) and only change the icon for use with nerdfonts once #2869 lands

Here are some unicode options:

![image](https://user-images.githubusercontent.com/3957610/218438773-bc05d38b-3bd0-4db5-a772-a54da9104919.png)
([or more](https://www.alt-codes.net/circle-symbols))

**Comment by filipdutescu** [comment]
After a lot of discussion, the redesigned UI/theme will look like this (default theme for reference):

![image](https://user-images.githubusercontent.com/46979062/220769255-c315095d-3aa8-4487-a536-99e178f0add8.png)

**Comment by filipdutescu** [comment]
After talking some more with @archseer, we landed on this colour for the debug highlight, which I find beautiful:

![image](https://user-images.githubusercontent.com/46979062/224115869-3facec21-dd2f-473c-805c-9199ccff722d.png)
