### ISSUE TITLE
Rust syntax highlighting colors enum variants differently (depending on kind of the wariant)

### ISSUE THREAD

**Issue by quomatz** [helix-editor/helix#5953]
### Summary

When using values of the Option enum:

- `Some` get colored differently than
- `None`
![Screenshot](https://user-images.githubusercontent.com/84818106/218331795-2e523b44-d511-4655-85df-3e3805ba9252.png)

### Reproduction Steps

 

I tried this:

1. Wrote different enum variants- `None`, `Some`, `Ok`...

I expected this to happen:

Each variant would be colored in the same color.

Instead, this happened:

They are collored differently

### Platform

Windows

### Terminal Emulator

Windows Terminal Version: 1.16.10262.0

### Helix Version

22.12-223-g9c98043c

**Comment by the-mikedavis** [comment]
See https://github.com/helix-editor/helix/issues/3121

**Comment by quomatz** [comment]
@the-mikedavis The `constructor` item didn't change the color here, but the `type` color did.
The `None` has the same color as types, while it should have the `type.enum.variant` color, right?
By the way, the theme I'm using is Jellybeans.

**Comment by quomatz** [comment]
Closing as a child of  #5589.
Needs LSP highlighting to work.
