### ISSUE TITLE
Go to references produce wrong highlights

### ISSUE THREAD

**Issue by DuckDuckWhale** [helix-editor/helix#5961]
### Summary

Only the right portion of the line highlight in go to references are highlighted. This worked in last stable release but not current master.

### Reproduction Steps

1. `hx` in Helix
2. Go to a variable and `gr`

I expected this to happen:

Whole line or just this variable is highlighted

Instead, this happened:

Highlight starts one space after the line, or when line wraps highlights also whitespaces in the middle of the wrap

### Platform

Ubuntu 22.10

### Terminal Emulator

Version 3.46.2 for GNOME 43

### Helix Version

helix 22.12 (a4751db8)

**Comment by the-mikedavis** [comment]
Could you provide an asciinema recording or video or gif? I'm not sure I understand the issue you're seeing.

Also the logs when running in verbose mode (`hx -v`) would be helpful since this has to do with LSP interaction: https://github.com/helix-editor/helix/wiki/FAQ#access-the-log-file

**Comment by the-mikedavis** [comment]
This might be unrelated to what you're seeing but I see in the code used by goto-definition/references/etc. that we use a point selection: https://github.com/helix-editor/helix/blob/2bebc5042e5e50a6cd7691f3590184c4499376a7/helix-term/src/commands/lsp.rs#L206

We could use a selection on the item's range like we do for diagnostics (#4713)

**Comment by DuckDuckWhale** [comment]
Upon closer inspection, this appears to be a theming issue:

Stable Monokai:
![Stable Monokai](https://user-images.githubusercontent.com/28813824/218549434-044a3a4a-abd2-4190-b58f-8ae0f62a49a7.png)

Master Monokai (with line wrapping):
![Master Monokai](https://user-images.githubusercontent.com/28813824/218549559-77453871-5771-4f22-8682-90a568ebe41d.png)

Master Monokai Pro:
![Master Monokai Pro](https://user-images.githubusercontent.com/28813824/218549614-f9daaeee-abcd-43b2-b522-17c81e06ef52.png)

**Comment by pascalkuthe** [comment]
I have a pretty good idea what is causing this and how to fix it. Will look into it later this week
