### ISSUE TITLE
Helix panics on `goto_window_center` when lines fill less than half the screen

### ISSUE THREAD

**Issue by iobtl** [helix-editor/helix#5965]
### Summary

Helix panics when trying to go to center of window (when less than half the screen populated)

https://user-images.githubusercontent.com/59901837/218481825-c1091c7d-c317-43a0-b9d0-72b3c5076253.mov

### Reproduction Steps

 

I tried this:

1. `RUST_BACKTRACE=1 hx`
2. Navigate to some file (https://github.com/helix-editor/helix/blob/master/helix-term/src/ui/picker.rs in this example)
3. `ge`
4. `zt`
5. `gc`

I expected this to happen:

Probably something similar to `align_view_center`

Instead, this happened:

`hx` panics and crashes.

### Helix log

<details><summary>~/.cache/helix/helix.log</summary>

`helix.log` only has a bunch of LSP messages, but here is the backtrace, which seems to be clear enough where the problem is:
```
thread 'main' panicked at 'assertion failed: min <= max', /rustc/4b91a6ea7258a947e59c6522cd5898e7c0a6a88f/library/core/src/cmp.rs:846:9
stack backtrace:
   0: _rust_begin_unwind
   1: core::panicking::panic_fmt
   2: core::panicking::panic
   3: helix_term::commands::goto_window
   4: helix_term::ui::editor::EditorView::handle_keymap_event::{{closure}}
   5: helix_term::ui::editor::EditorView::handle_keymap_event
   6: <helix_term::ui::editor::EditorView as helix_term::compositor::Component>::handle_event
   7: helix_term::compositor::Compositor::handle_event
   8: helix_term::application::Application::event_loop_until_idle::{{closure}}
   9: helix_term::application::Application::run::{{closure}}
  10: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
  11: hx::main
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
```

</details>

### Platform

macOS

### Terminal Emulator

alacritty 0.10.1 (2844606)

### Helix Version

22.12-262-g2bebc504

**Comment by iobtl** [comment]
I encountered this bug when remapping `C-d = ["half_page_down", "goto_window_center"]` and doing `ge, C-d, C-d`, which crashes the program (similar to the video)

**Comment by pascalkuthe** [comment]
can reproduce, I will look into this since I work on this code last, thanks for reporting :+1:

**Comment by iobtl** [comment]
Sounds good!
