### ISSUE TITLE
Simple bracket matching doesn't work

### ISSUE THREAD

**Issue by donaldcallen** [helix-editor/helix#5985]
### Summary

Bracket matching does not work.

### Reproduction Steps

 

I tried this:

1. With the cursor on the left bracket of the line
```
{foobar}
```
I pressed 'mm'

I expected this to happen: move to matching bracket

Instead, this happened: nothing

The same problem occurs if you start with the cursor on the right bracket. I also tried parens with the same result.

### Helix log

<details><summary>~/.cache/helix/helix.log</summary>

```
2023-02-14T08:27:46.069 helix_term::application [WARN] failed to load theme `base16_terminal` - No such file or directory (os error 2)
```

</details>
This is the only line in the log relevant to the session in which I tried the bracket-matching experiment.

### Platform

FreeBSD 13.1

### Terminal Emulator

st

### Helix Version

22.12-262-g2bebc504

**Comment by wes-adams** [comment]
in the documentation, this feature is marked as requiring a tree-sitter grammar for the filetype. 

![Screenshot from 2023-02-14 14-11-41](https://user-images.githubusercontent.com/7883354/218834320-ea200da1-c8d6-4d7c-9d0a-54c9525d57d5.png)

![Screenshot from 2023-02-14 14-12-11](https://user-images.githubusercontent.com/7883354/218834466-2f5b7d9a-f3f6-4a0c-81cd-a09088877765.png)

i suspect that you'd have no problems if you tried this in a programming language source file.

---

it might make sense to expand on this issue to request added coverage for non source code files?

**Comment by donaldcallen** [comment]
void panic(Char *message)
{
    fputs(message, stderr);
    exit(EXIT_FAILURE);
}

The above excerpt is from an application of mine. The filename is common.c.
mm with the cursor on either bracket does nothing.

**Comment by wes-adams** [comment]
this feature works for me in C.
try `$ hx --health c` to see if you have enabled support for C

**Comment by donaldcallen** [comment]
It was me -- symlink to the runtime wasn't quite right. Thanks for the help.
