### ISSUE TITLE
different behaviour on x button

### ISSUE THREAD

**Issue by fastfading** [helix-editor/helix#6013]
<img width="457" alt="image" src="https://user-images.githubusercontent.com/8351732/219232055-1d0b5189-73ea-472f-ad9f-0ef42a84ffd0.png">
x button  is suppose to select current line.
but when there is only  \n  in current line
x button  select 2 line  .  
this will  confuse  users

**Comment by fastfading** [comment]
<img width="668" alt="image" src="https://user-images.githubusercontent.com/8351732/219243059-97364bdf-8a66-46e6-b7be-c81dfb75b5a8.png">

<img width="654" alt="image" src="https://user-images.githubusercontent.com/8351732/219242723-24efbee5-0698-4612-ad4c-d0537a21cf1e.png">
another small issue is 
when press  x   it should be in SEL  mode .
But it shows  both NOR and SEL mode

**Comment by pascalkuthe** [comment]
This behavior is intentional. `x` has nothing to do with select mode it only selects multiple lines on repeated key presses. It dies not cause all movements to extend the selection like select mode does.

**Comment by fastfading** [comment]
how about 
x button is suppose to select current line. but when there is only \n in current line x button select 2 line . this will confuse users

**Comment by the-mikedavis** [comment]
That behavior is intentional too - `x` extends to the line bounds and if the selection is already at the line bounds then it extends to the line below. When you have a single-character selection on an empty line (on the end-of-line character), that selection is already at the line bounds.

You might prefer this rebinding in your config:

```toml
[keys.normal]
x = "extend_to_line_bounds"
X = "extend_line_below"
```

`extend_to_line_bounds` behaves like `extend_line_below` but doesn't extend to the next line if it is already at the line bounds. It does nothing instead

**Comment by fastfading** [comment]
this does not sovle the problem 
we expect  
x    select current line 
xx  select  current line and below line 

this configure change x only to select current line 
[keys.normal]
x = "extend_to_line_bounds"
X = "extend_line_below"

"x extends to the line bounds and if the selection is already at the line bounds then it extends to the line below."
check the image below ,  cursor is at the line bounds ,  it only select current line .
<img width="581" alt="image" src="https://user-images.githubusercontent.com/8351732/219529593-100eff58-dc1b-4f35-b413-c80f21009953.png">

this behaviour is different to an empty line

**Comment by fastfading** [comment]
x button is suppose to select current line. but when there is only \n in current line x button select 2 line 
and this is very different to vim  . 
in vim 
V  only select current line  no matter if it is an empty line
2V  select  2 line 

in hx 
x  or  1x select 1  or  2 line

**Comment by the-mikedavis** [comment]
This is a duplicate of https://github.com/helix-editor/helix/issues/3077. You can use/merge https://github.com/helix-editor/helix/pull/4847 in a fork but that change makes `x` on an empty line do nothing the first time it is pressed which I think is worse behavior.
