### ISSUE TITLE
SEL mode and  NOR mode are not  obvious

### ISSUE THREAD

**Issue by fastfading** [helix-editor/helix#6014]
<img width="668" alt="image" src="https://user-images.githubusercontent.com/8351732/219243720-80e207d0-4f52-42d6-a986-b32d6d28afe5.png">
I am not aware which mode am I in  when I edit 

or even more .
as touch pad  is widely used   and  most vi like tool support mouse
I am wondering if vi mode should exist any more 

can it be change to vscode mode ?  I found it is more easy to use .
default is in edit mode 
all navigation and selection  could use trackpad

when you want to perform a cmd
use <leader_key> + cmd
like  
ctrl-s  save 
ctrl-m w  select word
ctrl-m wa  select word and surrounding

it is more easy to understand

**Comment by pascalkuthe** [comment]
Helix has always been and will always remain a modal editor.

Take a look at the vision document https://github.com/helix-editor/helix/blob/master/docs/vision.md. There are mamy different editor paradigms. Helixes approach works very well for it's users and if you give it a try might work well for you too.

Helix does have mkuse support altough it needs to be enabled and supported by the terminal emulator

**Comment by fastfading** [comment]
<img width="563" alt="image" src="https://user-images.githubusercontent.com/8351732/219249877-3299eec9-e8f7-4a22-ac02-6934ec5a2999.png">

<img width="547" alt="image" src="https://user-images.githubusercontent.com/8351732/219249899-7325844a-1b26-4bf3-a9ce-868b19ee40b5.png">
the cursor is a litlte darker  in insert mode .
not very obvious

change we change it to other colors  in insert mode 
so it will be more obvious

**Comment by fastfading** [comment]
<img width="555" alt="image" src="https://user-images.githubusercontent.com/8351732/219257408-64876fbf-7ed6-4e27-b5c1-f8974df8d2e6.png">
this is neovim in insert mode

**Comment by gabydd** [comment]
You can have that in helix as well:

```toml
[editor.cursor-shape]
insert = "bar"
```
See https://docs.helix-editor.com/master/configuration.html#configuration for further reference

**Comment by kirawi** [comment]
You can also change the statusline color according to the mode.
