### ISSUE TITLE
Helix installation fails to compile.

### ISSUE THREAD

**Issue by nathan-guiard** [helix-editor/helix#6020]
### Summary

Hello, when trying to install helix with the source code, I came across several issues. The first one was that a dependency needed rustc version 1.64 but your `rust-toolchain.toml` file imposes rustc version 1.63 (or so i guess i dont really know how it works).
Anyway after changing the `channel` line on this file to match the needed version, the code failed to compile with this error:

PS: I updated my rustc and cargo version just before

### Reproduction Steps

 

I tried this:

1. `cargo install --locked --path helix-term`

This happened:

```  Installing helix-term v0.6.0 (/home/nguiard/.helix/helix-term)
    Updating crates.io index
error: failed to compile `helix-term v0.6.0 (/home/nguiard/.helix/helix-term)`, intermediate artifacts can be found at `/home/nguiard/.helix/target`

Caused by:
  package `git-traverse v0.22.1` cannot be built because it requires rustc 1.64 or newer, while the currently active rustc version is 1.63.0
```

So i modified the 2nd line of the `rust-toolchain,toml` file from `channel = "1.63.0"` to `channel = "1.64.0"`

And retried to do:

1, `cargo install --locked --path helix-term`

But i got this:
```
   Compiling git-repository v0.32.0
error[E0063]: missing field `expected_checksum` in initializer of `git_index::decode::Options`
  --> /home/xxx/.cargo/registry/src/github.com-1ecc6299db9ec823/git-repository-0.32.0/src/repository/worktree.rs:80:13
   |
80 |             git_index::decode::Options {
   |          
```

### Platform

Linux

### Terminal Emulator

xterm-256color

### Helix Version

none

**Comment by the-mikedavis** [comment]
Did you run `cargo update` before building? Or are you on a custom branch? The dependencies are currently locked in a way that Helix can be built from rust 1.63 and the `--locked` flag for `cargo install` should force cargo to respect the locked dependency versions. For example, git traverse is currently locked at `0.22.0` rather than `0.22.1`: https://github.com/helix-editor/helix/blob/78a1e2db6035b326d7536fbd0fb60f9fc586d978/Cargo.lock#L990-L992

The CI checks against rust 1.63 and it looks good on the current master: https://github.com/helix-editor/helix/actions/runs/4195153301/jobs/7274288159

**Comment by nathan-guiard** [comment]
I ran cargo update but the problem was not fixed. I checked the Cargo.lock file but the version on it is 0.22.1, i tried to change it to 0.22.0 but i got a conflict error

**Comment by nathan-guiard** [comment]
I re-cloned the project and it worked fine. I don't really know why. Thanks :)

**Comment by pascalkuthe** [comment]
`cargo update` causes the problem instead of fixing it. `git reset --hard` or `git checkout Cargo.lock` would have fixed the problem too.

I am closing this issue as its not actually an issue that occurs with an umodified git checout

**Comment by RmStorm** [comment]
I had this issue to but it was because I was running without `--locked` :see_no_evil: . For any others that might come across this issue... `cargo install --locked --path helix-term` is correct!

**Comment by makoojogit** [comment]
No it is not correct. I did everything suggested above and still see this message - error: failed to compile `helix-term v0.6.0
