### ISSUE TITLE
Buffer file preview does not work on files opened with alt-return in picker until they are actually opened first

### ISSUE THREAD

**Issue by David-Else** [helix-editor/helix#6026]
### Summary

Buffer file preview does not work on files opened with alt-return in picker until they are actually opened first.

![Screenshot from 2023-02-17 11-56-04](https://user-images.githubusercontent.com/12832280/219648155-3b583e02-4888-4256-9262-0d803984a0cc.png)
![Screenshot from 2023-02-17 11-56-28](https://user-images.githubusercontent.com/12832280/219648163-58700d8f-6a3d-4bf2-b10a-1256dcd3cf18.png)

### Reproduction Steps

Open more than one file using `alt return` in the file picker. Now open the buffer picker, only files that have been actually opened have a preview. I would expect them to all have a preview available the same as if I had opened them individually.

### Helix log

na

### Platform

Linux

### Terminal Emulator

Kitty

### Helix Version

helix 22.12 (715c4b24)

**Comment by askreet** [comment]
I can't reproduce this on the same version -- how are you opening the files exactly? For me, selecting a file in space-f and entering alt-enter for multiple files loads the highlight queries and shows the preview. Then leaving that picker and using space-b to enter the buffer picker the same previews are already loaded.

**Comment by David-Else** [comment]
@askreet I tried again, and now it suddenly works. I did not update Helix, so this must be an intermittent bug. It would be best to leave this issue open in case anyone finds a method to reliably reproduce it.

**Comment by dead10ck** [comment]
We try to keep issues actionable so we know what issues can actually be worked on. 🙂 If anyone can reproduce this, please feel free to reopen.

**Comment by Diorgeles** [comment]
I have the same problem in the latest version :( 
- happens when closing ":q" a buffer that was opened with <Enter>
- does not happen when closing ":q" a buffer that was opened with <Alt-enter>
