### ISSUE TITLE
yank into register and system clipboard at the same time

### ISSUE THREAD

**Issue by fastfading** [helix-editor/helix#6039]
when press  y   
yank text into register and system clipboard at the same time

and there seems to be a error.  
on mac 13 iterm2   
when you select a word by touchpad.   
it shows "yanked main selection to primary clipboard ",  but  actually  not in the system clip board or register

Clipboard provider: pbpaste+pbcopy
System clipboard provider: pbpaste+pbcopy

**Comment by Abdillah** [comment]
This is also true when combining both yank into one shortcut,

```
C = [ "yank", "yank_main_selection_to_clipboard" ]
```

Only `yank` operation takes place although the message subsequently display both operation.

**Comment by the-mikedavis** [comment]
I can't reproduce that. That binding works fine for me locally: the current primary selection ends up on the clipboard and all selections end up on the `"` register (which you can see by pressing `"` in normal mode). Does `yank_main_selection_to_clipboard` work outside of that binding for you?

**Comment by Abdillah** [comment]
Oh it is! 
Sorry, I'm not recheck my recollection (or the issue is not what I mentioned above).
I hope it was pre-23.10 and now has been fixed.

If that is the case, I think there's no strong reason to implement this issue.
