### ISSUE TITLE
Opening cmd freezes helix

### ISSUE THREAD

**Issue by Cerabbite** [helix-editor/helix#6040]
### Summary

When starting cmd from hx command-shell helix freezes. This means that I cannot interact withit anymore and when resizing the window it results into this:
![image](https://user-images.githubusercontent.com/98265679/219873011-c1e49fe9-89f7-4021-ba4a-72c25569d24e.png)

I mostly run Helix.exe, but I tested it and the same error occurs when running it from cmd Version 10.0.22621.1265 and WezTerm-20221119-145034-49b9839f

### Reproduction Steps

 

I tried this:

1. Start Helix
2. :sh start cmd.exe

I expected this to happen:
Open cmd.exe

Instead, this happened:
It opened cmd.exe
But now helix is frozen.

### Platform

Windows

### Terminal Emulator

WezTerm-20221119-145034-49b9839f

### Helix Version

helix 22.12 (96ff64a8)

**Comment by kirawi** [comment]
`:sh` is not meant to be interactive.
