### ISSUE TITLE
gruvbox theme has weird comment reverse-video in tmux

### ISSUE THREAD

**Issue by icefoxen** [helix-editor/helix#6048]
### Summary

When running Helix in a bare terminal (sakura 3.8.6) you get this:

![image](https://user-images.githubusercontent.com/1335133/219883691-f6f1ed03-a5b7-440a-ae7e-14f5947c6e78.png)

When running it inside tmux (3.3a) you get this:

![image](https://user-images.githubusercontent.com/1335133/219883698-0d4908ba-6098-4545-934c-a9ab55f0c2fc.png)

Setting the $TERM variable from tmux's `screen-color256` to sakura's `xterm-color256` doesn't seem to change this.

Not really sure whether this is a bug in Helix, tmux, sakura, or all/none of the above.  I notice mainly because vim also has a "gruvbox" theme and doesn't seem to do this.  In terminal and in tmux you either way get:

![image](https://user-images.githubusercontent.com/1335133/219883756-0933e7f6-2a48-4e04-8d19-1147f4d3ba2d.png)

### Reproduction Steps

https://asciinema.org/a/sPnac3cXdNrrdJl9d0qZHwdRj

### Helix log

<details><summary>~/.cache/helix/helix.log</summary>

```
2023-02-18T14:10:40.402 helix_view::editor [ERROR] Failed to initialize the LSP for `source.rust` { cannot find binary path }
```

(I don't have `rust-analyzer` installed on this system.)

</details>

### Platform

Linux

### Terminal Emulator

sakura 3.8.6

### Helix Version

helix 22.12 (c332b168)

**Comment by kirawi** [comment]
https://github.com/helix-editor/helix/issues/3099

**Comment by icefoxen** [comment]
Thanks, that was the issue.  ...well, that and a slightly cursed tmux setup that didn't reload the terminal setting when I told it to.  All good now!
