### ISSUE TITLE
Helix not recognizing runtime on Ubuntu WSL2

### ISSUE THREAD

**Issue by atbarry** [helix-editor/helix#6106]
After following the [installation tutorial](https://docs.helix-editor.com/install.html) I ran into an issue where highlighting and themes were not working. 
I tried symlink, copying the runtime folder into the `.config/helix` directory and changing the environment variable, none of which has worked.
This is what my directory looks like and the output of `hx --health`

![image](https://user-images.githubusercontent.com/88946161/221390527-5e376df7-d93f-4fa9-86ab-1f31a50da337.png)

**Comment by kirawi** [comment]
Your runtime folder is empty though. It's missing the `themes` and `queries` folders.

**Comment by atbarry** [comment]
Not sure why those folders were missing but I recloned the repository and added those folders. After checking the health

![image](https://user-images.githubusercontent.com/88946161/221394324-5a785390-d2b2-469f-bf8a-54331826be03.png)

Highlighting still did not work after that, but after a fresh install it finally works!
Thanks!
