### ISSUE TITLE
Rust highlighting doesn't work

### ISSUE THREAD

**Issue by nuid32** [helix-editor/helix#6112]
### Summary

After helix reinstallation (cargo install --locked --path helix-term) .rs files highlight isn't working.
Grammars fetch and build didn't help.

### Reproduction Steps

 

I tried this:

1. `hx helix-term/src/main.rs`

I expected this to happen:

**Nice syntax highlight**

Instead, this happened:

**No nice syntax highlight**

### Helix log

<details><summary>~/.cache/helix/helix.log</summary>

```
helix_core::syntax [ERROR] Could not parse queries for language "rust". Are your grammars out of sync? Try running 'hx --grammar fetch' and 'hx --grammar build'. This query could not be parsed: QueryError { row: 282, column: 1, offset: 4751, message: "attribute", kind: NodeType }
helix_lsp::transport [ERROR] err <- "[ERROR project_model::workspace] cyclic deps: helix_view(CrateId(115)) -> helix_tui(CrateId(108)), alternative path: helix_tui(CrateId(108)) -> helix_view(CrateId(115))\n"
helix_lsp::transport [ERROR] err <- "[ERROR project_model::workspace] cyclic deps: helix_view(CrateId(115)) -> helix_tui(CrateId(108)), alternative path: helix_tui(CrateId(108)) -> helix_view(CrateId(115))\n"
```

</details>

### Platform

Artix Linux x86_64

### Terminal Emulator

alacritty 0.11.0 (8dbaa0bb)

### Helix Version

helix 22.12 (98a3d469)

**Comment by kirawi** [comment]
Thanks for opening an issue. What does `hx --health` say?

**Comment by nuid32** [comment]
```
$ hx --health rust
Configured language server: /home/void/.cargo/bin/rust-analyzer
Binary for language server: /home/void/.cargo/bin/rust-analyzer
Configured debug adapter: lldb-vscode
Binary for debug adapter: /usr/bin/lldb-vscode
Highlight queries: ✓
Textobject queries: ✓
Indent queries: ✓
```

**Comment by xiuxiu62** [comment]
Same here, after updating tree sitter grammars (obviously included a rust grammar update).
Checked on void linux and windows 11.

**Comment by xiuxiu62** [comment]
ah I was on an old version of helix, just rebuilt and rust highlighting is working for me

**Comment by nuid32** [comment]
Helix binary from Artix installed by pacman and using same runtime directory is working as supposed

**Comment by nuid32** [comment]
After switching to built from source helix there is one more line appears in log after opening .rs file in helix

**Comment by kirawi** [comment]
It looks like your queries are out of date. You should update them from source.

**Comment by nuid32** [comment]
I copied runtime dir from helix repository, if that's what you mean

**Comment by kirawi** [comment]
From when? There was a breaking change to them a few months ago.

**Comment by nuid32** [comment]
From the last commit

**Comment by kirawi** [comment]
Do you have a custom `languages.toml` that specifies an older Rust grammar revision?

**Comment by nuid32** [comment]
Yes, I had. I updated my language.toml, fetched and built grammars and it works now. Thank you very much

**Comment by kirawi** [comment]
You don't have to copy-paste the entire `languages.toml`. It'll automatically merge your changes with the defaults.
