### ISSUE TITLE
multi-second lags while typing filenames after :o on slow filesystems.

### ISSUE THREAD

**Issue by mro** [helix-editor/helix#6114]
IMO the name expansion should not block the UI.

First raised at https://matrix.to/#/!zMuVRxoqjyxyjSEBXc:matrix.org/$gm2aCY2n4iUO0DWhYA2xlGmp6MIUM9BV6Tk34aByL8U?via=matrix.org&via=mozilla.org&via=envs.net

**Comment by mro** [comment]
the filesystem being a `sshfs` mounted directory, network bandwidth 12MBit downstream.

**Comment by kirawi** [comment]
Related: https://github.com/helix-editor/helix/issues/1987

**Comment by mro** [comment]
@kirawi yes, or just once while typing.
