### ISSUE TITLE
typing twice.

### ISSUE THREAD

**Issue by leedonhyun** [helix-editor/helix#6133]
### Summary

hi.
keyboard keys being entered twice each time the key is pressed
![Animation](https://user-images.githubusercontent.com/8449892/221852889-d22bb242-efc0-44c8-af99-dd234f59a9ff.gif)

### Reproduction Steps

 

I tried this:

1. `hx`

I expected this to happen:

Instead, this happened:

### Helix log

<details><summary>~/.cache/helix/helix.log</summary>

```
please provide a copy of `~/.cache/helix/helix.log` here if possible, you may need to redact some of the lines
```

</details>

### Platform

window

### Terminal Emulator

PowerShell 7.3.2

### Helix Version

helix 22.12 (8dab8a0a)

**Comment by markus-bauer** [comment]
Perhaps someone didn't implement the changes in the new crossterm correctly:
https://github.com/crossterm-rs/crossterm/issues/752

AFAIK, crossterm will now report events for press and release:
https://github.com/crossterm-rs/crossterm/pull/745

**Comment by soenkekrusche** [comment]
I just built hx from source and this kinda drives me away. Does an older build fix this? Or do we have to pick an older crossterm dependency when building?

**Comment by markus-bauer** [comment]
@soenkekrusche 

I really haven't looked into this, it was just a suspicion.
If this is indeed the source of the problem, then it was introduced in crossterm 0.26: https://github.com/crossterm-rs/crossterm/releases/tag/0.26

**Comment by David-Else** [comment]
@soenkekrusche The commit to use Crossterm 0.26.x was only pushed 10 hours ago, just build from the last commit before which is a976786a4fa013150ec1b59ae55276361e61340f . I am sure it will be fixed very soon, don't get driven away!

Here is my install script that uses a specific commit, you can see how it works:
```sh
    mkdir -p "$helix_src_folder"
    git clone https://github.com/helix-editor/helix "$helix_src_folder"
    git -C "$helix_src_folder" checkout 715c4b24d94c9e2fa70d5d59ce658b89fbde0392 # hand picked stable point
    cargo install --locked --path "$helix_src_folder"/helix-term
    ...
```

**Comment by the-mikedavis** [comment]
Could you give #6139 (a8c0705a5b891da6f3172c07d6ca349b64a2407b) a try? You can `cargo run` on that branch so that you don't have to compile the editor in release mode.

**Comment by soenkekrusche** [comment]
> Could you give #6139 ([a8c0705](https://github.com/helix-editor/helix/commit/a8c0705a5b891da6f3172c07d6ca349b64a2407b)) a try? You can `cargo run` on that branch so that you don't have to compile the editor in release mode.

No more duplicate symbols when typing, built the branch with cargo v 1.63, tested on cmd and powershell 🙂

**Comment by leedonhyun** [comment]
> Could you give #6139 ([a8c0705](https://github.com/helix-editor/helix/commit/a8c0705a5b891da6f3172c07d6ca349b64a2407b)) a try? You can `cargo run` on that branch so that you don't have to compile the editor in release mode.

Thank you.

**Comment by kirawi** [comment]
Let's keep this open until the PR gets merged.
