### ISSUE TITLE
Can't map commands to “C-ret" "S-ret" "C-m" 

### ISSUE THREAD

**Issue by pzzxqj** [helix-editor/helix#6137]
### Summary

I try to some key remapping below, but not working.
```toml
[keys.insert]
C-ret = "open_below"
"S-ret" = "open_above"
"C-m" = "open_below"
```

### Reproduction Steps

1. :config-open
2. write config
3. :config-reload

### Platform

Linux

### Terminal Emulator

konsole

### Helix Version

helix 22.12 (8dab8a0a)

**Comment by the-mikedavis** [comment]
The escape sequences the terminal uses to describe these events are ambiguous with the default way that key events are reported. #4939 supports accepting events from an enhanced keyboard protocol but this only works if your terminal supports the enhanced keyboard protocol. I don't think it's implemented in Konsole (https://sw.kovidgoyal.net/kitty/keyboard-protocol/#comprehensive-keyboard-handling-in-terminals) but you can check by running in verbose mode with `hx -vv`. The log file should have a line that says "The enhanced keyboard protocol is supported on this terminal" or "The enhanced keyboard protocol is not supported on this terminal".

If it isn't supported for Konsole, you will need to use a terminal emulator that supports the protocol to be able to use these bindings.

**Comment by pzzxqj** [comment]
Thank your suggestion, I'm trying a new terminal, kitty. Now it's OK.

I see that `Ctrl+m`  act like `Enter` in insert mode. Key mapping for `Ctrl+m` also not working. Is it special key sequence?
I don't exactly get it.

**Comment by the-mikedavis** [comment]
There isn't a special case for C-m in the codebase as far as I know. I would expect C-m to act like enter if you are using the keybinding in the issue description though:

```toml
[keys.insert]
C-m = "open_below"
```

With that binding, C-m in insert mode should act like `o` does in normal mode.

You can also try a rebinding like

```toml
[keys.normal]
C-m = "toggle_comments"
```

which should make C-m act like C-c in normal mode - it will toggle comments for the currently selected lines

**Comment by pzzxqj** [comment]
It is not working as your description. C-m always equates to enter.

**Comment by pzzxqj** [comment]
append reply, it doesn't work in konsole.

**Comment by the-mikedavis** [comment]
Oh I see, yeah that's expected behavior in Konsole or any terminal emulator that doesn't support the keyboard enhancement protocol. The escape sequence for C-m is the same as Enter. There are a bunch of other ambiguous key combinations like C-backspace being the same as C-h.

**Comment by pzzxqj** [comment]
It's mean that the action of C-m  is decided by terminal?

**Comment by the-mikedavis** [comment]
For all the terminal emulators that I know of, C-m sends the same escape sequence as Enter. You can tell C-m and Enter apart if the terminal and the app (Helix in this case) enable and use the enhanced keyboard protocol but otherwise they look the same.

**Comment by pzzxqj** [comment]
It is very useful for me, thank you
