### ISSUE TITLE
Cycling selections does not work with tmux on macos

### ISSUE THREAD

**Issue by klingtnet** [helix-editor/helix#6138]
I'm currently working through the tutor and everything worked fine, except for cycling through selections in section 10.1 when in iterm2 and tmux.  ~~I first thought it might be `tmux`, but it doesn't matter if I'm in a `tmux` session or not.  Cycling through selections using `(`, `)` works when `hx` was ran from the default macos terminal, though.~~
This might not be a helix bug, but I didn't know where to ask.  Also, there is no shortkey for `(`, or `)` defined in `iterm`, as far as I know.

Update:  It also fails to work in the default macos terminal when I'm in a `tmux` session, so `tmux` might be the problem here.  However, I don't know why it consumes `(`, `)`, because I can still type those characters.

Update 2:  `tmux` is not the problem here, it turned out that some themes are not indicating the active selection.

**Comment by PusztaiMate** [comment]
Same for me on popOS/tmux/gnome terminal
Using the default theme

**Comment by askreet** [comment]
It appears the default theme is included in that list. I didn't know about the `(` and `)` bindings for changing selections, but it seems entirely useless without a way to distinguish which is highlighted.

**Comment by klingtnet** [comment]
@the-mikedavis Please excuse the late reply.  It actually works with the `darcula` theme, but not with the default and  `ayu_light`.  I tried to execute the same keystrokes with the default theme and it works as well, just the active selection is not indicated.

Not sure why it seemed with the default theme and without tmux though, but I couldn't properly reproduce that.  So `tmux` is not the problem here.

**Comment by the-mikedavis** [comment]
Ah ok, it seems like this is #3842 then, I will close in favor of that issue
