### ISSUE TITLE
Update Vlang in the languages.toml

### ISSUE THREAD

**Issue by AnthonySmithDev** [helix-editor/helix#6140]
**Also accepts the ".vsh" extension:**
https://github.com/vlang/v/blob/master/doc/docs.md#cross-platform-shell-scripts-in-v

**On the line of code:** 
https://github.com/helix-editor/helix/blob/8dab8a0a039fe1f3dd98fc62ac97d2f1c089793a/languages.toml#L1617

**Comment by the-mikedavis** [comment]
Please open a PR 👍
