### ISSUE TITLE
String search jumps off-screen

### ISSUE THREAD

**Issue by bcspragu** [helix-editor/helix#6141]
### Summary

I just built a new version of Helix at HEAD (https://github.com/helix-editor/helix/commit/8dab8a0a039fe1f3dd98fc62ac97d2f1c089793a) and the behavior of search (i.e. `/` then `n`) has broken such that the cursor and entry are always one-line off the bottom of the screen. I don't know what the previous behavior was (e.g. center of screen, bottom of screen), but it definitely wasn't this.

As a workaround I just type `nzz` to center the (otherwise not-visible) result.

### Reproduction Steps

Should be readily reproducible, just search for a known string outside the current viewport.

### Helix log

Not including this for now, can include if deemed helpful

### Platform

Linux

### Terminal Emulator

alacritty / tmux

### Helix Version

helix 22.12 (8dab8a0a)

**Comment by pascalkuthe** [comment]
Do you have your scroff set to `0`? I can reproduce the problem in that case but not otherwise. I think the refactor of the positioning code in #5420 simply as an off by 1 error here for the scroll-off at the bottom of the screen

**Comment by bcspragu** [comment]
> Do you have your scroff set to `0`?

Yup, this was exactly the issue, not sure why I had that set in the first place, thanks!

**Comment by pascalkuthe** [comment]
I would like to keep this open since it's still a regression that was unintentional. I will send a fix later
