### ISSUE TITLE
Option to disable waiting for LSP servers to terminate

### ISSUE THREAD

**Issue by alxpettit** [helix-editor/helix#6146]
On my machine, I use `ra-multiplex` as a wrapper around `rust-analyzer`. This introduces an intermediate client-server protocol that allows all Rust analysis to be done by a single server instance, and allows it to stay in memory -- reducing the amount of duplicate analysis that needs to be done over long coding sessions, where I may be swapping between IDEs and projects (many of which share the same crates).

The problem is that Helix waits until timeout for the LSP to close, so it ends up staying open for several seconds more, messing up workflow. I cloned the repo and disabled the code that performs the wait, and it seems not to cause any zombie processes or other problems. It'd be cool if there was an option to do this, in the mainline code!

**Comment by kirawi** [comment]
https://github.com/helix-editor/helix/pull/5266

**Comment by alxpettit** [comment]
Oh, whoops
