### ISSUE TITLE
Weird behavior when forking helix to background

### ISSUE THREAD

**Issue by mWalrus** [helix-editor/helix#6149]
### Summary

Helix behaves weird when forking the process to the background (`Ctrl+Z`) and sending it to the foreground (`fg`) on Linux on latest git version.

### Reproduction Steps

 

I tried this:

1. `hx`
2. `Ctrl+Z`
3. `fg`

I expected this to happen:
It should fork the helix process to the background when I `Ctrl+Z` and resume the process when I send it to the foreground with `fg`.

Instead, this happened:
When trying to fork to the background, nothing happens the first time. The second time it works as expected.

When trying to send it to the foreground, it clears the terminal window on the first attempt. When trying again it brings the editor back, but it takes a second or two for the TUI to display.

If I quit helix after this, `^[[?6c` is present in my terminal after my terminal prompt, which seems to have been produced after the second attempt to resume the process.

### Helix log

Nothing since I updated.

### Platform

Arch Linux

### Terminal Emulator

Alacritty

### Helix Version

helix 22.12 (c082ef28)

**Comment by santiagovrancovich** [comment]
I'm having the same issue, i would also like to add that i've tested it with gnome-console and tty, the issue persists, but the string of character left behid is different in each instance, with gnome-console is ` 65;1;9c` and with the tty is just `6c`

**Comment by the-mikedavis** [comment]
It looks like the query to check keyboard enhancement protocol support times out and fails causing the lag and failure to restore the terminal. We should cache the value for keyboard enhancement support when we first query it instead of re-checking it anyways and that will fix this

**Comment by mWalrus** [comment]
This mostly works now although there are still some issues. The escape sequence characters are sometimes still present in the terminal after `C-z`, and resuming the process again is still slow (around 2+ seconds).

**Comment by the-mikedavis** [comment]
Ah yeah I can reproduce that. It doesn't happen every time but sometimes continuing the process leads to the same lockup. #6160 should solve this consistently but a proper fix is also necessary upstream in crossterm.

**Comment by gyreas** [comment]
I get this issue too even tho enhanced keyboard protocol is enabled (and works fine?) And runs in Kitty.
