### ISSUE TITLE
Clipboard paste problems

### ISSUE THREAD

**Issue by leedonhyun** [helix-editor/helix#6151]
### Summary

hi.
If i copy from the clipboard, it will be pasted strangely.

Press ctrl + ins in insert mode.

![clipboard](https://user-images.githubusercontent.com/8449892/222142561-7d8d838e-d274-4738-9838-6ea9ba2442e7.gif)

### Reproduction Steps

 

I tried this:

1. `hx`

I expected this to happen:

Instead, this happened:

### Helix log

<details><summary>~/.cache/helix/helix.log</summary>

```
please provide a copy of `~/.cache/helix/helix.log` here if possible, you may need to redact some of the lines
```

</details>

### Platform

windows

### Terminal Emulator

powershell

### Helix Version

helix 22.12 (8dab8a0a)

**Comment by CptPotato** [comment]
Pasting in the terminal usually gets interpreted as individual key presses (so the editor automatically inserts matching brackets as if you were typing them by hand).

To paste from clipboard use <kbd>space</kbd><kbd>P</kbd> / <kbd>space</kbd><kbd>p</kbd>.

**Comment by leedonhyun** [comment]
Thank you.

**Comment by dead10ck** [comment]
Helix supports bracketed paste since https://github.com/helix-editor/helix/pull/3233, but the terminal emulator must also support it for it to work.
