### ISSUE TITLE
Use a different color for the current cursor in a multicursor selection

### ISSUE THREAD

**Issue by gyreas** [helix-editor/helix#6152]
It's difficult to work with multiple cursors when they have the same color; unless one is watching the position indicator, there's no way to know the primary cursor.

Steps to reproduce issue
1. Using the `:tutor` example on the `cycling and removing selections` section with the cursor on "h":

>  --> How muc`h` would would a wouldchuck chuck
>  --> if a wouldchuck could chuck would?

2. Typing 2x or xx, followed by s, then "would" and enter should produce: 

>  --> How much `would` `would` a `would`chuck chuck
>  --> if a `would`chuck could chuck `would`?

The issue should be apparent at this point.

3. Typing ) or (   a random number of times and looking at the text provides no clues which cursor is the primary one.

**Comment by kirawi** [comment]
Whether secondary cursors are highlighted differently depends on the theme you're using. Many of them color them the same.

**Comment by gyreas** [comment]
Yeah, and it's not very helpful that way. I want to suggest that the functionality should be upped:
1. The currently selected cursor should be colored differently.
2. Any selected cursor can be independently move.
3. A way to toggle 2.

PS: I tried using it for different themes, got the same result

**Comment by gabydd** [comment]
This specific issue is: https://github.com/helix-editor/helix/issues/3842 parts 2 and 3 of this is what marks can solve https://github.com/helix-editor/helix/pull/3720

**Comment by archseer** [comment]
Closing since it's a duplicate
