### ISSUE TITLE
No syntax highlighting on .graphqls files

### ISSUE THREAD

**Issue by neilyio** [helix-editor/helix#6153]
### Summary

`.graphqls` is a common file extension for GraphQL files. I'm finding that while `.graphql` files feature proper syntax highlighting, `.graphqls` files do not.

### Reproduction Steps

Open any GraphQL file with a `.graphqls` extension.

### Platform

macOS

### Terminal Emulator

Alacritty

### Helix Version

helix 22.12 (96ff64a8)

**Comment by archseer** [comment]
PR welcome!

**Comment by neilyio** [comment]
Amazing response time. I will seriously consider working towards being able to contribute to this project.Thanks for addressing.On Mar 2, 2023, at 7:59 AM, Michael Davis ***@***.***> wrote:﻿
Closed #6153 as completed via #6159.
