### ISSUE TITLE
bash indentation keeps on indenting when detected indent doesnt match default

### ISSUE THREAD

**Issue by faithanalog** [helix-editor/helix#6178]
### Summary

When editing a file with auto-detected indentation different from default, the auto-indent seems to like, double apply?

### Reproduction Steps

Use a stock helix config. Note that helix defaults to 2-space indents with bash scripts.

Open an existing bash file that already has 4-space indents, so helix auto-detects this.

On an empty line, insert a non-space character.
Start a new line. Hit tab to indent. Insert a non-space character.
Start a new line. Now you get double indentation. If you insert a character and hit enter again you get quad indentation. Repeat for exponential amusement.

Exact key sequence, from an empty line in normal mode

`ih<Enter><Tab>h<Enter>h<Enter>h<Enter>h<Enter>`

You'll get something that looks a bit like this

```
h
    h
        h
                h
                                h
                                                                h
```

And if I set 

```
indent = { tab-width = 4, unit = "    " }
```

and open the same file, then the problem magically goes away.

### Platform

Linux

### Terminal Emulator

foot

### Helix Version

helix 22.12

**Comment by pascalkuthe** [comment]
I can not reproduce this on the latest master. Could you try with the latest master and check if you can reproduce with that?

If the problem persists it would help greatly if you could provide an example file that reproduces the problem

**Comment by faithanalog** [comment]
Good news, I also cannot reproduce this on latest master! Guess it's just a 22.12 thing.
