### ISSUE TITLE
A problem with "less"

### ISSUE THREAD

**Issue by 0Ahmed-0** [helix-editor/helix#6195]
## When pressing "v" in "less" helix opens with two buffers(the first is empty, the second is the file)

-I tried this on different Linux based OSs, helix builds, shells

-helix.log is made on the fly with full verbosity and since I wasn't using helix directly I made a wrapper file ...
"RUST_BACKTRACE=full /usr/lib/helix/hx -vvv ${@}"

### Reproduction Steps

 

I tried this:
less ${file}; pressed "v" to open the file in helix

I expected this to happen:
The file being opened in helix

Instead, this happened:
Helix opened with two buffers(also in helix.log says "Loaded 2 files"), the second being the actual file, the first one is empty and having a name "+{N}" where {N} is the actual file lines number(but doesn't go beyond 18).

### Helix log

[helix.log](https://github.com/helix-editor/helix/files/10892763/helix.log)

### Platform

Linux Arch 6.2.1-arch1-1 #1 SMP PREEMPT_DYNAMIC Sun, 26 Feb 2023 03:39:23 +0000 x86_64 GNU/Linux

### Terminal Emulator

alacritty 0.11.0 (8dbaa0bb)

### Helix Version

helix 22.12 (96ff64a8)

**Comment by the-mikedavis** [comment]
To be compatible with less's `v` command we need to support opening files at line N when helix is called like `hx +N <file>`. This is covered by https://github.com/helix-editor/helix/issues/5437 so I will close in favor of that
