### ISSUE TITLE
Add configuration option to "forcefully" toggle undercurl when not detected.

### ISSUE THREAD

**Issue by filipdutescu** [helix-editor/helix#6196]
# Description

Due to the way some distributions and package managers package the `TermInfo` file of various emulators, it is possible to have a false negative reading in Helix that the used emulator does not support undercurls. Even if it actually does (for example, Alacritty in ArchLinux shows as not supporting undercurls, when it acutally does).

# Proposal

A configuration option could be added to "force" Helix to use undercurls even if its automated detection mechanism says they are not supported.

**Comment by pascalkuthe** [comment]
The necessary configuration should be part of the normal editor configuration and passed to `CrossTermBackend::new` and overwrite the autodetected value there https://github.com/helix-editor/helix/blob/39d5fb0e593b0da1bf6e2659c67a7914edcd75a6/helix-tui/src/backend/crossterm.rs#L61

**Comment by the-mikedavis** [comment]
We have a special case for WezTerm for the same term-info-installation reasons: https://github.com/helix-editor/helix/commit/98c121c9fc9d9dbc058120ede9700c0e0bbc5551

We could add one for Alacritty too since it has been supported for some time now https://github.com/alacritty/alacritty/pull/5837

**Comment by filipdutescu** [comment]
@pascalkuthe mentioned it might be better to handle it this way since it increases burden on us adding more and more exceptions.

**Comment by pascalkuthe** [comment]
> We have a special case for WezTerm for the same term-info-installation reasons: [98c121c](https://github.com/helix-editor/helix/commit/98c121c9fc9d9dbc058120ede9700c0e0bbc5551)
> 
> We could add one for Alacritty too since it has been supported for some time now [alacritty/alacritty#5837](https://github.com/alacritty/alacritty/pull/5837)

just to note: Alacritty is detected just fine on every distro I tried but archlinux. They have packaged the wrong terminfo file.

That's why sort of suggested adding an overwrite here because it doesn't seem sustainable to hardcode every emulator here by hand where any distro has ever messed up the terminfo file (even worse how do you deal with `ssh`...)

**Comment by the-mikedavis** [comment]
It's a little hacky but you could also set the `VTE_VERSION` environment variable to `5102` as a workaround without changing the Helix codebase.

A config option is probably fine for this though, we have a similar one for forcing true-color when the detection fails.
