### ISSUE TITLE
Auto completing trait functions do not generate closing curly brace.

### ISSUE THREAD

**Issue by dogunbound** [helix-editor/helix#6200]
### Summary

https://user-images.githubusercontent.com/64436119/223125749-5f307dbc-5c6c-42e1-9147-f32d3ce25dc3.mp4

Probably duplicate, but could not find the issue.

### Reproduction Steps

min reproducible:
```rust
trait MyTrait {
    fn my_func(i: i32) -> Option<()>;
}

struct MyStruct;

impl MyTrait for MyStruct {}

fn main() {}
```

Try auto generating `my_func` in the `impl MyTrait for MyStruct` as I did in the video.

### Helix log

[helix.log](https://github.com/helix-editor/helix/files/10898750/helix.log)

### Platform

Linux

### Terminal Emulator

Konsole

### Helix Version

22.12

**Comment by pascalkuthe** [comment]
I remeber there being a previous bug report for this but I can't find the issue, cc @dead10ck this falls under autopairs I think?

**Comment by AlexanderBrevig** [comment]
Probably not relevant but I noticed `<space> a` and then `Implement missing members` works and provides this;

```rust
    fn my_func(i: i32) -> Option<()> {
        todo!()
    }
```

Maybe the LSP answers with a newline and it's somehow lost?

Just a wild guess/intuition that's probably wrong. FWIW the bug happens on my system too.

**Comment by pascalkuthe** [comment]
See what I wrote on matrix matrix:

> Autopairs only get activated when you actually type the bracket and not by arbitrary transactions (like the ones send from the LSP). Currently RA doesn't send the bracket itself because helix doesn't support snippets, with snippet support (which will land [soon](https://github.com/helix-editor/helix/pull/5864)). Once we support snippets RA will send the bracket and helix won't need to insert it

There is an existing issue for completions not triggering autpairs but I can't find it.

**Comment by the-mikedavis** [comment]
Snippets (#5864) will solve this. When snippets are enabled we get this completion item for the trait function:

```json
{
  "label": "fn my_func(..)",
  "kind": 3,
  "deprecated": false,
  "preselect": true,
  "sortText": "ffffffee",
  "filterText": "fn my_func",
  "insertTextFormat": 2,
  "textEdit": {
    "newText": "fn my_func(i: i32) -> Option<()> {\n    $0\n}",
    "insert": {
      "start": { "line": 650, "character": 4 },
      "end": { "line": 650, "character": 6 }
    },
    "replace": {
      "start": { "line": 650, "character": 4 },
      "end": { "line": 650, "character": 6 }
    }
  },
  "additionalTextEdits": []
}
```

Typically language servers don't send function parentheses or brackets for completion items unless snippets are enabled because you need snippets in order to tell the editor where to put the cursor (between the parens/brackets in most cases).

**Comment by the-mikedavis** [comment]
Do other editors run auto-pairs logic on completion text? With snippets I don't think we should need to and in my experience it's already an edge-case to need auto-pairs for completions with snippet support disabled

**Comment by pascalkuthe** [comment]
> Do other editors run auto-pairs logic on completion text? With snippets I don't think we should need to and in my experience it's already an edge-case to need auto-pairs for completions with snippet support disabled

I am not sure it's definitively an edge-case and probably not critical. I just remembered there being an issue about this before and know it's the cause of this issue. Snippets definitely are the better fix tough.
