### ISSUE TITLE
On reload, show path to file(s) that "can't be found"

### ISSUE THREAD

**Issue by helmesjo** [helix-editor/helix#6222]
A small but helpful fix. When working with many buffers open and jumping between branches, the natural thing is to first do eg. a `reload-all`. Problem is, if any of the buffers open point to a file that no longer exists, helix just show this:

![image](https://user-images.githubusercontent.com/2501070/223539513-93484e4f-f83d-4eb9-bea6-cbb7213a6ccc.png)

This is not particularly informative, and usually the quickest "fix" is to just exit and restart helix. It might as well also show which file(s) failed to reload.

**Comment by pickfire** [comment]
Should be fixed by https://github.com/helix-editor/helix/pull/6274
