### ISSUE TITLE
Wrapping long lines

### ISSUE THREAD

**Issue by sparrisable** [helix-editor/helix#623]
Is it possible to wrap long lines in helix? (something like "Toggle Word Wrap Alt+Z editor.action.toggleWordWrap" in Visual Studio Code)
If not, I would use such a feature if you decide to add it.

**Comment by archseer** [comment]
Kind of cool but kakoune wraps text by piping to the Unix `fmt` utility: https://github.com/mawww/kakoune/wiki/Wrapping#semi-automatically-breaking-lines-at-a-fixed-width

**Comment by archseer** [comment]
I think we can implement it as a native command. It should support detecting and wrapping comments correctly.

**Comment by cessen** [comment]
This is talking about hard wrapping, not soft wrapping (issue #136 already exists for that), right?  It's not immediately clear to me from the description.

**Comment by sparrisable** [comment]
I realize now that I actually mean soft wrapping but I did not realize that there where already an issue for that, sorry.
I am happy to see that issue #136  already exists, sorry for the confusion.

**Comment by cessen** [comment]
@sparrisable: no worries!  I'll close this as duplicate then.

I think I'll open another issue for a "hard-wrap selected text" feature, though.  Because I think that would also be useful, and is a lot smaller-scope than soft wrapping.

**Comment by cessen** [comment]
Here's the new issue for hard-wrapping: #625
