### ISSUE TITLE
Moving problem with soft-wrap enable and relative line number

### ISSUE THREAD

**Issue by zhuyk6** [helix-editor/helix#6247]
If I set soft-wrap enable and set relative line number, when I want move the cursor cross a soft-wrap line, it will not behave as I want.
For example, the cursor is on line 1 and I want to goto line 5 which is 4 line below line 1. When I press "4j", it will not goto line 5 but the line 3. 

![Screenshot_20230310_213801](https://user-images.githubusercontent.com/11555462/224330577-32550154-488e-44b1-85b7-5d8a264f4ddd.png)
![Screenshot_20230310_213817](https://user-images.githubusercontent.com/11555462/224330589-3af4a27a-a427-477f-8ef8-3280815912e4.png)

This is because the soft-wrap line will consume one down-movement "j". But I think it should behave as "what I see" (this is the reason why I use relative line number). I suggest that helix should do special checking when entering "nj" or "nk", not just repeat "j" or "k" $n$ times. Maybe use absolute movement, just goto line $m' = m \pm n$  where $m$ and $m'$ mean absolute line number.

**Comment by pascalkuthe** [comment]
This is on purpose and was discussed in the softwrap PR. You can use the `gj`/`gk` bindings for line wise movement
