### ISSUE TITLE
ElixirLS `do`-completion inserts wrong indentation

### ISSUE THREAD

**Issue by leonqadirie** [helix-editor/helix#6255]
### Summary

Following the discussions in #5864 and #6224 - completing Elixir's `do` still messes up indentation on my end, originating from ElixirLS  returning offsets without completions.

### Reproduction Steps

 

I tried this:

1. `hx`
2. Navigate to any .ex file
3. Enter `def test do`
4. Apply the `do` completion

I expected this to happen:
```elixir
def test do
  |
end
```
Instead, this happened:

```elixir
def test do
           |
         end
```

### Platform

macOS

### Terminal Emulator

Kitty/Alacritty

### Helix Version

22.12-383-g98415f28

**Comment by pascalkuthe** [comment]
this actually... seems kind of correct given how the code was intended. Snippets are generated so newlines are indented to match the start position (which is do here). However now I tested in vscode and it seems vscode doesn't behave the same.
It seems VScode uses the indentation at the start of the line rather the start of the snipet from my experimentation. This makes sense to me. In that case snippet lines would just act like pressing enter normally would in helix.

In that case we should TS based indent queries here. 

I will try to find out how exactly vscode handles this first

**Comment by pascalkuthe** [comment]
Fixing this was quite easy, I posed https://github.com/helix-editor/helix/pull/6263.  My comment about TS was rubbish, just needed to keep the indentation of the current line (VScode does the same so LS expect that and will add additional indentation themselves)
