### ISSUE TITLE
Symbol Picker jumps to the closing bracket of a function in Go

### ISSUE THREAD

**Issue by heliostatic** [helix-editor/helix#626]
When jumping to a function definition in a go file, the symbol picker jumps to the closing bracket of the function. I assume this is not the intended behavior, but if it is, I'd love an option to change it to go to the function definition.

https://user-images.githubusercontent.com/70898/130123697-4a4de583-2853-4753-896b-f5772be4af5a.mp4

**Comment by archseer** [comment]
It selects the entire symbol with a selection. I guess we could flip the selection so that the cursor is on the first line?

**Comment by heliostatic** [comment]
> It selects the entire symbol with a selection. I guess we could flip the selection so that the cursor is on the first line?

I guess that was my expectation, but 🤷‍♀️

**Comment by kirawi** [comment]
I agree, that makes more sense to me.
