### ISSUE TITLE
Indentation level is calculated incorrectly for lines mixing tabs and spaces

### ISSUE THREAD

**Issue by pascalkuthe** [helix-editor/helix#6262]
Indentation of existing lines is calculated with (`helix_core::indent`):

``` rust
pub fn indent_level_for_line(line: RopeSlice, tab_width: usize, indent_width: usize) -> usize {
    let mut len = 0;
    for ch in line.chars() {
        match ch {
            '\t' => len += tab_width,
            ' ' => len += 1,
            _ => break,
        }
    }

    len / indent_width
}
```

This works for lines that are purely indented with spaces or tabs (so almost always) but in the edge-case that a lines is indented with a mix of tabs and spaces (for some ungodly reason) then the result is incorrect because the width of a tab differs in that case. The fix is simple: use `helix_core::graphemes::tab_width` to calculate the tab width instead in the function mentioned above.

CC @Triton171 (in case I missed something)

**Comment by Proful** [comment]
I faced this issue recently. Had to convert tab to spaces manually.

**Comment by pascalkuthe** [comment]
the fix is quite easy I basically desribed exactly what to do so if you are interested in this it should be quite easy for you to open a  PR.
