### ISSUE TITLE
Support multiple languages with same LSP server instance

### ISSUE THREAD

**Issue by ayoub-benali** [helix-editor/helix#6284]
This a follow up to the discussion in https://github.com/helix-editor/helix/pull/5707:
[Metals](https://scalameta.org/metals) supports both Scala and Java and in order to do that in Helix one can do one of the two things:
- A: Add `java` in the `file-types` in the scala config entry. But then scala's syntax highlighting would be used by Helix for java files which is wrong
- B: Do the reverse and change java's config to use Metals as a language server, but this would spawn a separate language server just for java which is also wrong

This problem happens also for other ecosystems where one language server supports multiple languages like Kotlin + Java or Javascript + typescript, etc.

One solution could be to allow the decoupling of the language sever and the syntax highlighting via the config file, so that for the case A, one could enable Java for Metals but Helix would use java's syntax highlighting and leave the LSP to the configured server. 

Is there a better way to fix this problem ?

**Comment by pascalkuthe** [comment]
This is actually already covered by #2507. Right now we keep one lsp instance per language around (well one per workspace too but that's for some servers unrelated). With that PR potentially multiple lsps could.be used per language so now there is just one instance per LSP server (which can be used across multiple languages).

**Comment by ayoub-benali** [comment]
Ah sorry for the potentiel duplicate, my understanding of https://github.com/helix-editor/helix/pull/2507 was that it would allow running multiple LSP servers for the same workspace. This issue is about the opposite, when a workspace mixes langues, use the same LSP server if it is supports them. Is that case covered as well ?

**Comment by Danacus** [comment]
I believe this issue may also be fixed by #2507, since it allows you to define multiple languages that use the same instance of a language server. For example, you could add `language-servers = [ "metals" ]` to both the `java` and `scala` languages, such that the same instance of `metals` is used for both languages. This is also mentioned as a side-effect in the PR:

> Another side-effect/difference that comes with this PR, is that only one language server instance is started if different languages use the same language server.

I believe this is exactly what you need, right?

**Comment by ayoub-benali** [comment]
thanks for clarifiying @Danacus, I will clause this issue then
