### ISSUE TITLE
Update themelint to include newly added theme.keys

### ISSUE THREAD

**Issue by workingj** [helix-editor/helix#6291]
I ran `cargo xtask themelint` on pop-dark and no issues where reported.
But if i don't err the following keys where newly added
```
ui.highlight.frameline
ui.debug
ui.virtual.inlay-hint
```
i can look in to it if its not already in the works..

**Comment by archseer** [comment]
These are mostly optional though? `ui.highlight` and `ui.virtual` being the fallback. `ui.debug` could use a value

**Comment by workingj** [comment]
this issue can be closed i think
