### ISSUE TITLE
Whitespace inside LSP hints should not render

### ISSUE THREAD

**Issue by EpocSquadron** [helix-editor/helix#6297]
The new inlay hints functionality introduced in #5934 interacts in an interesting way with the whitespace rendering functionality. That is to say, if you have `whitespace.render = "all"` set, you will see that spaces within the inlay hints themselves -- either spacing around the hint or between characters within it -- are displayed as any other whitespace in the document. Here's a screenshot:

![image](https://user-images.githubusercontent.com/414963/224775225-ca82b8fc-093b-4982-bdc4-c125c660c824.png)

To me this is not intuitively correct, because the inlay hints are virtual text that are not part of the real document. I rely on the whitespace rendering to provide information on the characters that are part of the document that I can't see, to help understand how motions and selections will behave before I use them. Displaying them within the inlay hint is neither informative nor helpful in that goal.

Further problematic is the spacing after the inlay hints is not rendered with a background to make it obvious it is part of the inlay hint and not a real space in the document. This makes it downright misleading to render the inlay hint whitespace. Here is the above example with inlay hints off, so you can see the difference:

![image](https://user-images.githubusercontent.com/414963/224775777-c0ae57f6-62a0-43da-8be9-2b0fa08f72c9.png)

**Comment by erasin** [comment]
The theme onelight/onedark_local I'm using, whitespace is not noise to code. Most format tool can handle excess white space.


onelight
![WX20230314-155532](https://user-images.githubusercontent.com/716514/224948244-7657ba22-8bd1-475a-885a-1cd134ccd245.png)

[onedark_local](https://github.com/erasin/helix-config/blob/main/themes/onedark_local.toml)
![WX20230314-155511](https://user-images.githubusercontent.com/716514/224948257-711ee2ab-fc88-4cb3-bb19-a3a8e5f0b66a.png)
