### ISSUE TITLE
On linux the editor freezes on clipboard interactions (via xsel)

### ISSUE THREAD

**Issue by timbod7** [helix-editor/helix#630]
### Reproduction steps

1. With a file open, press `x(space)y`
2. The editor freezes and is then unresponsive to any subsequent key presses

### Environment

- Platform: ubuntu linux 20.04, `xsel` command line tool installed and on $PATH, `xclip` tool not installed.
- Helix version: latest master  (f60b549fb7c21ff92fe635729198555d704e5f93)

The file `$HOME/.cache/helix/helix.log` is created, but empty.

### Workaround

Installing `xclip` avoids the problem.

**Comment by archseer** [comment]
I think `--nodetach` shouldn't be specified here: https://github.com/helix-editor/helix/blob/f60b549fb7c21ff92fe635729198555d704e5f93/helix-view/src/clipboard.rs#L87

Had to fix a similar issue with wl-copy: https://github.com/helix-editor/helix/commit/994ff4b2694044c60b69265cb176d0e5c608cf49
