### ISSUE TITLE
`hx --grammar build` fails with clang

### ISSUE THREAD

**Issue by yuxuanchen1997** [helix-editor/helix#6300]
### Summary

When installing from source, I noticed that many language grammars aren't built. There's no error coming out of `cargo install --locked --path helix-term` either. Further investigation showed that hundreds of the .so files in runtime/grammars are missing.

I then discovered that running `hx --grammar build` returns the following error:
error: invalid argument '-std=c++11' not allowed with 'C'

I realized that this is a clang specific error. I unblocked with setting environment variable `CC=gcc` `CXX=g++` to the grammar build command and was able to get the grammars building. 

My clang version:
```
% clang --version
clang version 15.0.0 (Red Hat 15.0.0-1.module_el8.8.0+1224+64629835)
Target: x86_64-redhat-linux-gnu
Thread model: posix
InstalledDir: /usr/bin
```

Rust version:
rustc 1.67.1-dev (d5a82bbd2 2023-02-07) (built from a source tarball)

### Reproduction Steps

On RHEL 8
```
git clone https://github.com/helix-editor/helix
cd helix
cargo install --locked --path helix-term
```
no errors. 

then check the runtime/grammars folder. Only 30+ instead of 100+ grammars showed up. 

```
hx --grammar fetch
hx --grammar build
```
gives a log spew of C compiler warnings/errors including 
```
error: invalid argument '-std=c++11' not allowed with 'C'

        Failure 95/101: Parser compilation failed.
Stdout:
Stderr: /home/ych/.config/helix/runtime/grammars/sources/yaml/src/scanner.cc:619:10: warning: variable 'is_cur_wsp' set but not used [-Wunused-but-set-variable]
    bool is_cur_wsp = is_wsp(cur_chr);
         ^
1 warning generated.
error: invalid argument '-std=c++11' not allowed with 'C'

        Failure 96/101: Parser compilation failed.
Stdout:
Stderr: error: invalid argument '-std=c++11' not allowed with 'C'

        Failure 97/101: Parser compilation failed.
Stdout:
```

### Platform

Linux

### Terminal Emulator

alacritty

### Helix Version

helix 22.12 (98415f28)

**Comment by archseer** [comment]
This seems to me like you're either missing the C compiler or trying to use the C compiler as C++. I'm using clang just fine locally.

Maybe you're missing this step? https://github.com/helix-editor/helix/issues/1223#issuecomment-984720861

**Comment by archseer** [comment]
We don't set that flag at all: https://github.com/helix-editor/helix/blob/3e03a1a99bc66a9b04dc293b9aa277ca4b7becae/helix-loader/src/grammar.rs#L452-L477

**Comment by yuxuanchen1997** [comment]
That indeed seems bizzare. I could dig a little further with my setup. Since I am unblocked and convinced that this is a peculiar issue with my setup, I am closing this issue. Thanks for the help anyway.
