### ISSUE TITLE
Implement LSP window/showMessage request

### ISSUE THREAD

**Issue by RmStorm** [helix-editor/helix#6321]
Helix currently does not support LSP's [window/showMessage](https://microsoft.github.io/language-server-protocol/specifications/lsp/3.17/specification/#window_showMessage), I think it would be nice to have! The only way to send messages to users from within a language server is the [Work Done Progress](https://microsoft.github.io/language-server-protocol/specifications/lsp/3.17/specification/#workDoneProgress) mechanism but that is overkill for simpler notifications.

**Comment by pascalkuthe** [comment]
See  #5535

**Comment by pascalkuthe** [comment]
Ah there is actually already an issue for this:  #5524
