### ISSUE TITLE
Highlighting in tokyonight theme

### ISSUE THREAD

**Issue by danjenson** [helix-editor/helix#6330]
### Summary

First off, thank you for all of this amazing work! I've just switched but found that my favorite theme, the tokyonight theme, has some weird highlighting.

![image](https://user-images.githubusercontent.com/4793438/225545416-2f103638-8a1b-49f6-bccf-df21277393be.png)

How can I get rid of the highlighting?

### Platform

Void Linux

### Terminal Emulator

Alacritty

### Helix Version

helix 22.12

**Comment by the-mikedavis** [comment]
Are you using tmux? It looks like the italics modifier is being misinterpreted by the terminal emulator although Alacritty should certainly support it.

**Comment by the-mikedavis** [comment]
See https://github.com/helix-editor/helix/issues/3099#issuecomment-1188322182
