### ISSUE TITLE
Cursor hard to see with fleet_dark theme when cursor is positioned over whitespaces

### ISSUE THREAD

**Issue by DSeeLP** [helix-editor/helix#6332]
### Summary

#6324 changed the color of `ui.virtual` from `Gray 80` to `Gray 20` which makes the cursor hard to find when positioned over whitespaces.
Gray 20 (Current)           |  Gray 80 (Previous)
:-------------------------:|:-------------------------:
![grafik](https://user-images.githubusercontent.com/46624152/225636837-1e7ea7a3-57b1-45dc-92c6-20f4a67d7d29.png) |![grafik](https://user-images.githubusercontent.com/46624152/225637321-e8994dca-eadf-4f8e-8f31-bc6d9aa39510.png)

The cursor wasn't moved between both screenshots.

### Platform

Fedora 37

### Terminal Emulator

kitty 0.26.5

### Helix Version

22.12-433-g63c23d4b

**Comment by kirawi** [comment]
Closed by https://github.com/helix-editor/helix/pull/6375
