### ISSUE TITLE
Thematic break highlighting

### ISSUE THREAD

**Issue by JustinLovinger** [helix-editor/helix#6380]
Thematic breaks for markup, such as `---` in Markdown, <https://spec.commonmark.org/0.30/#thematic-breaks>, should have syntax highlighting.

**Comment by the-mikedavis** [comment]
Those can be themed with `punctuation.special` on master: https://github.com/helix-editor/helix/blob/05e7862e8fc34e2e4dd745f9dc95c1b1ab0dc20f/runtime/queries/markdown/highlights.scm#L42

**Comment by JustinLovinger** [comment]
Huh, it seems strange that only this one aspect of markup is not part of the `markup` scope.
