### ISSUE TITLE
block yank and paste bug.

### ISSUE THREAD

**Issue by TinyProbe** [helix-editor/helix#6383]
### Summary

asd
zxc

Select this (2, 3) block and delete with yank.
And paste before cursor.

zxc
zxc

Shouldn't it be like this?

asd
zxc

If not, i'm sorry. And let me know how do i do as that.

### Helix log

nothing appeared to this action.

### Platform

macbook air m2 (latest update)

### Terminal Emulator

kitty (latest update)

### Helix Version

helix 22.12 (96ff64a8)

**Comment by the-mikedavis** [comment]
What is the (2, 3) block? I don't understand what you are selecting.

If you select the first line with `x` (`extend_line_below`) and then use `d` (`delete_selection`) to yank delete the line, pressing `P` (`paste_before`) should leave the buffer unchanged:

```
asd
zxc
```

The same should happen if you select the second line instead.

**Comment by TinyProbe** [comment]
**asd**
**zxc**

(0, 0) .. (2, 3)
Oh. I mean select 0, 1, 2 column using to two multi line cursor.
Delete with yank on that state.
And paste before cursor with still keep multi line cursor.
It will to be this.

**zxc**
**zxc**

but i wanna it to be this:

**asd**
**zxc**

Please how do i do?

**Comment by gabydd** [comment]
Bit confused here could you add the exact keys you would press to replicate this behaviour starting from the a in asd

**Comment by askreet** [comment]
It might be useful to record your session with https://asciinema.org/ and describe what you're pressing and what you expect to happen.

**Comment by TinyProbe** [comment]
asd
zxc

Start from 'a'.

shift + c : "copy_selection_on_next_line"
l : "move_char_right"
l : "move_char_right"
x : [ "yank_main_selection_to_clipboard", "delete_selection_noyank" ]
P : "paste_clipboard_before"

**Comment by gabydd** [comment]
Ah that's because you are only yanking the main selection, if you use ``"yank"`` plus ``"paste_before"`` instead it should work because those commands use of the built-in registers that store text per selection where as your os clipboard has no information about the helix multiple selections

**Comment by TinyProbe** [comment]
I understand.
