### ISSUE TITLE
Goto previous change not work in the markdown file 

### ISSUE THREAD

**Issue by linc01** [helix-editor/helix#6399]
Hello,

Here is the issue: `[g` and  `[G` not work in the markdown file `.md`,  the error message is `Diff is not available in current buffer`. 

`[D` ,  `[d`, and `g.`  work fine. 

Meanwhile, all Goto key mappings work fine in the rust file.

**Comment by pascalkuthe** [comment]
`]g` and `[g` work based on the diff gutter so if you don't see a diff gutter then these won't work either. The reason for that is likely that the file you are editing was not yet committed to a git repository.

**Comment by linc01** [comment]
Thanks @pascalkuthe , are there alternatives of these key mappings of go to function without git commintted? I can use`C-o` for the current file, but it won't work after I close it.
