### ISSUE TITLE
How about change text_style from `ui.text.focus` to `ui.text` in `ui's Info` Component

### ISSUE THREAD

**Issue by cossonleo** [helix-editor/helix#641]
I think info text is normal text. There is no reason use `ui.text.focus`.

**Comment by archseer** [comment]
I think we could change it, or maybe add `ui.info` with fallback to `ui.text`? I used `ui.text.focus` since it stands out a bit more than just plain text on the default theme.

**Comment by cossonleo** [comment]
> I think we could change it, or maybe add `ui.info` with fallback to `ui.text`? I used `ui.text.focus` since it stands out a bit more than just plain text on the default theme.

I open a PR #643
