### ISSUE TITLE
Build failed on CentOS 8

### ISSUE THREAD

**Issue by mayagamer** [helix-editor/helix#642]
I tried to install Helix Editor, but failed while compiling.
Here is the output:

> $ cargo install --path helix-term
>   Installing helix-term v0.4.1 (/home/sheldon/helix/helix-term)
>     Updating crates.io index
>    Compiling serde_derive v1.0.128
>    Compiling thiserror-impl v1.0.26
>    Compiling tokio-macros v1.3.0
>    Compiling serde_repr v0.1.7
>    Compiling tokio v1.10.0
>    Compiling helix-syntax v0.4.1 (/home/sheldon/helix/helix-syntax)
> error: failed to run custom build command for `helix-syntax v0.4.1 (/home/sheldon/helix/helix-syntax)`
> 
> Caused by:
>   process didn't exit successfully: `/home/sheldon/helix/target/release/build/helix-syntax-fe20531f19d8f089/build-script-build` (exit status: 101)
>   --- stdout
>   Build language agda
>   Build language bash
>   Build language c
>   Build language c-sharp
>   Build language cpp
>   Build language css
>   Build language elixir
>   Build language go
>   Build language html
>   Build language java
>   Build language javascript
>   Build language json
>   Build language julia
>   Build language latex
>   Build language ledger
>   Build language nix
>   Build language php
>   Build language protobuf
>   Build language python
>   Build language ruby
>   Build language rust
>   Build language scala
>   Build language swift
>   Build language toml
> 
>   --- stderr
>   thread '<unnamed>' panicked at 'called `Result::unwrap()` on an `Err` value: Failed to execute C compiler
> 
>   Caused by:
>       No such file or directory (os error 2)', helix-syntax/build.rs:173:36
>   note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
>   thread '<unnamed>' panicked at 'called `Result::unwrap()` on an `Err` value: Failed to execute C compiler
> 
>   Caused by:
>       No such file or directory (os error 2)', helix-syntax/build.rs:173:36
>   thread '<unnamed>' panicked at 'called `Result::unwrap()` on an `Err` value: Failed to execute C compiler
> 
>   Caused by:
>       No such file or directory (os error 2)', helix-syntax/build.rs:173:36
>   thread '<unnamed>' panicked at 'called `Result::unwrap()` on an `Err` value: Failed to execute C compiler
> 
>   Caused by:
>       No such file or directory (os error 2)', helix-syntax/build.rs:173:36
>   thread '<unnamed>' panicked at 'called `Result::unwrap()` on an `Err` value: Failed to execute C compiler
> 
>   Caused by:
>       No such file or directory (os error 2)', helix-syntax/build.rs:173:36
>   thread '<unnamed>' panicked at 'called `Result::unwrap()` on an `Err` value: Failed to execute C compiler
> 
>   Caused by:
>       No such file or directory (os error 2)', helix-syntax/build.rs:173:36
>   thread '<unnamed>' panicked at 'called `Result::unwrap()` on an `Err` value: Failed to execute C compiler
> 
>   Caused by:
>       No such file or directory (os error 2)', helix-syntax/build.rs:173:36
>   thread '<unnamed>' panicked at 'called `Result::unwrap()` on an `Err` value: Failed to execute C compiler
> 
>   Caused by:
>       No such file or directory (os error 2)', helix-syntax/build.rs:173:36
>   thread '<unnamed>' panicked at 'called `Result::unwrap()` on an `Err` value: Failed to execute C compiler
> 
>   Caused by:
>       No such file or directory (os error 2)', helix-syntax/build.rs:173:36
>   thread '<unnamed>' panicked at 'called `Result::unwrap()` on an `Err` value: Failed to execute C compiler
> 
>   Caused by:
>       No such file or directory (os error 2)', helix-syntax/build.rs:173:36
>   thread '<unnamed>' panicked at 'called `Result::unwrap()` on an `Err` value: Failed to execute C compiler
> 
>   Caused by:
>       No such file or directory (os error 2)', helix-syntax/build.rs:173:36
>   thread '<unnamed>' panicked at 'called `Result::unwrap()` on an `Err` value: Failed to execute C compiler
> 
>   Caused by:
>       No such file or directory (os error 2)', helix-syntax/build.rs:173:36
>   thread '<unnamed>' panicked at 'called `Result::unwrap()` on an `Err` value: Failed to execute C compiler
> 
>   Caused by:
>       No such file or directory (os error 2)', helix-syntax/build.rs:173:36
>   thread '<unnamed>' panicked at 'called `Result::unwrap()` on an `Err` value: Failed to execute C compiler
> 
>   Caused by:
>       No such file or directory (os error 2)', helix-syntax/build.rs:173:36
>   thread '<unnamed>' panicked at 'called `Result::unwrap()` on an `Err` value: Failed to execute C compiler
> 
>   Caused by:
>       No such file or directory (os error 2)', helix-syntax/build.rs:173:36
>   thread '<unnamed>' panicked at 'called `Result::unwrap()` on an `Err` value: Failed to execute C compiler
> 
>   Caused by:
>       No such file or directory (os error 2)', helix-syntax/build.rs:173:36
>   thread '<unnamed>' panicked at 'called `Result::unwrap()` on an `Err` value: Failed to execute C compiler
> 
>   Caused by:
>       No such file or directory (os error 2)', helix-syntax/build.rs:173:36
>   thread '<unnamed>' panicked at 'called `Result::unwrap()` on an `Err` value: Failed to execute C compiler
> 
>   Caused by:
>       No such file or directory (os error 2)', helix-syntax/build.rs:173:36
>   thread '<unnamed>' panicked at 'called `Result::unwrap()` on an `Err` value: Failed to execute C compiler
> 
>   Caused by:
>       No such file or directory (os error 2)', helix-syntax/build.rs:173:36
>   thread '<unnamed>' panicked at 'called `Result::unwrap()` on an `Err` value: Failed to execute C compiler
> 
>   Caused by:
>       No such file or directory (os error 2)', helix-syntax/build.rs:173:36
>   thread '<unnamed>' panicked at 'called `Result::unwrap()` on an `Err` value: Failed to execute C compiler
> 
>   Caused by:
>       No such file or directory (os error 2)', helix-syntax/build.rs:173:36
>   thread '<unnamed>' panicked at 'called `Result::unwrap()` on an `Err` value: Failed to execute C compiler
> 
>   Caused by:
>       No such file or directory (os error 2)', helix-syntax/build.rs:173:36
>   thread '<unnamed>' panicked at 'called `Result::unwrap()` on an `Err` value: Failed to execute C compiler
> 
>   Caused by:
>       No such file or directory (os error 2)', helix-syntax/build.rs:173:36
>   thread '<unnamed>' panicked at 'called `Result::unwrap()` on an `Err` value: Failed to execute C compiler
> 
>   Caused by:
>       No such file or directory (os error 2)', helix-syntax/build.rs:173:36
>   thread 'main' panicked at 'assertion failed: `(left == right)`
>     left: `0`,
>    right: `24`', helix-syntax/build.rs:201:5
> warning: build failed, waiting for other jobs to finish...
> error: failed to compile `helix-term v0.4.1 (/home/sheldon/helix/helix-term)`, intermediate artifacts can be found at `/home/sheldon/helix/target`
> 
> Caused by:
>   build failed

Anyway to fix t this?

**Comment by archseer** [comment]
Do you have a C compiler installed? Is `cc` in your `PATH`? If not you'll need to set the `CC` environment variable to point to your compiler.

**Comment by mayagamer** [comment]
I thought it comes with centos, but turns out it doesn't. So I just installed gcc and problem solved. Thank you!
