### ISSUE TITLE
Config option to allow hiding cursors when editor focus is lost

### ISSUE THREAD

**Issue by xJonathanLEI** [helix-editor/helix#6420]
Similar to the `auto-save` option, we could have another option (`auto-hide-cursors`?) that makes the editor hide the cursors when focus is lost. When using a terminal multiplexer like `tmux`, hiding the cursors makes it easier to tell which pane the user is actually focused on.

Would love to work on the PR.

**Comment by gabydd** [comment]
Possible duplicate of https://github.com/helix-editor/helix/issues/1187

**Comment by xJonathanLEI** [comment]
Thanks! Closing as duplicate.
