### ISSUE TITLE
does not recognize git global `core.autocrlf = input` settings on windows, causing diff gutter problems

### ISSUE THREAD

**Issue by toymil** [helix-editor/helix#6467]
### Summary

On Windows, when `core.autocrlf` is set to `input` in `~/.gitconfig`, and both the local file and in-repo file have `lf` line ending, helix diff gutter will show every line as changed; as if helix is diffing a `crlf` version of the file* vs the `lf` local file.

Note: set `core.autocrlf = input` in **repo `.git/config`** does work  
*: possibly as a result of the default `core.autocrlf = true` doing checkout `lf` to `crlf` conversion

### Reproduction Steps

1. start with clean git config
2. run `git config --global core.autocrlf input` (this writes to `~/.gitconfig`)
3. make a new git repo, put one multi-line file with `lf` line ending, git add & commit this file
4. open the file with helix, see it showing diff on every line
5. now if we do _any_ of the following two, the diff goes away
    - set `autocrlf = input` locally with `git config core.autocrlf input` (writes to `.git/config`)
    - convert the local on disk file to `crlf` line ending

### Platform

Windows

### Terminal Emulator

Windows Terminal 1.16.10261.0

### Helix Version

helix 22.12 (96ff64a8)

**Comment by toymil** [comment]
this is the global git config:
```
$ git config --list --show-scope --show-origin
system  file:C:/Users/foobar/scoop/apps/git/2.40.0.windows.1/etc/gitconfig      core.symlinks=false
system  file:C:/Users/foobar/scoop/apps/git/2.40.0.windows.1/etc/gitconfig      core.autocrlf=true
system  file:C:/Users/foobar/scoop/apps/git/2.40.0.windows.1/etc/gitconfig      core.fscache=true
system  file:C:/Users/foobar/scoop/apps/git/2.40.0.windows.1/etc/gitconfig      color.interactive=true
system  file:C:/Users/foobar/scoop/apps/git/2.40.0.windows.1/etc/gitconfig      color.ui=auto
system  file:C:/Users/foobar/scoop/apps/git/2.40.0.windows.1/etc/gitconfig      help.format=html
system  file:C:/Users/foobar/scoop/apps/git/2.40.0.windows.1/etc/gitconfig      diff.astextplain.textconv=astextplain
system  file:C:/Users/foobar/scoop/apps/git/2.40.0.windows.1/etc/gitconfig      rebase.autosquash=true
system  file:C:/Users/foobar/scoop/apps/git/2.40.0.windows.1/etc/gitconfig      filter.lfs.clean=git-lfs clean -- %f
system  file:C:/Users/foobar/scoop/apps/git/2.40.0.windows.1/etc/gitconfig      filter.lfs.smudge=git-lfs smudge -- %f
system  file:C:/Users/foobar/scoop/apps/git/2.40.0.windows.1/etc/gitconfig      filter.lfs.process=git-lfs filter-process
system  file:C:/Users/foobar/scoop/apps/git/2.40.0.windows.1/etc/gitconfig      filter.lfs.required=true
system  file:C:/Users/foobar/scoop/apps/git/2.40.0.windows.1/etc/gitconfig      credential.helper=helper-selector
global  file:C:/Users/foobar/.gitconfig core.autocrlf=input
global  file:C:/Users/foobar/.gitconfig user.email=you@example.com
global  file:C:/Users/foobar/.gitconfig user.name=Your Name
```

**Comment by Byron** [comment]
I just validated that the order of configuration files read in `gitoxide` is correct and that does seem to be the case. The following example uses `credential.helper` as key to illustrate:

```
gitoxide ( main) [$]
❯ cargo run --bin gix -- config credential  | bat -l ini
    Finished dev [unoptimized + debuginfo] target(s) in 0.35s
     Running `target/debug/gix config credential`
───────┬─────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
       │ STDIN
───────┼─────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
   1   │ # From '/Applications/Xcode.app/Contents/Developer/usr/share/git-core/gitconfig' (GitInstallation)
   2   │ [credential]
   3   │     helper = osxkeychain
   4   │
   5   │ # From '/Users/byron/.gitconfig' (User)
   6   │ [credential]
   7   │     helper = foobar
   8   │
───────┴─────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
```

This means that overrides would be happening in the correct order and asking for `credential.helper` would yield `foobar` as one might expect.

When looking [the code handling `core.autocrlf`](https://github.com/helix-editor/helix/blob/5b3dd6a678ba138ea21d7d5dd8d3c8a53c7a6d3b/helix-vcs/src/git.rs#L82-L85) we see that it doesn't handle `"input"` specifically, because `"input"` would end up being false which seems to match the documentation of `core.autocrlf`.

**The bug description indicates that `helix` internally converts to CRLF endings which means its config would not see the global options at all. As we know the order is correct, I wonder if maybe `gitoxide` doesn't find the global options on windows?**

@toymil Could you install `gix` via `cargo install gitoxide` and run `gix config core`? This will provide a list of all configuration files that affect the core section. It is my guess that `gitoxide` uses another global location.

In the mean time, I will dig into this further.

**Comment by toymil** [comment]
@Byron It seems like `gitoxide` did not read my global config at all:

```
$ cargo run --bin gix -- config core
   Compiling gitoxide v0.24.0 (C:\Users\foobar\s\gitoxide)
    Finished dev [unoptimized + debuginfo] target(s) in 2m 22s
     Running `target\debug\gix.exe config core`
# From 'C:/Users/foobar/scoop/apps/git/2.40.0.windows.1/etc/gitconfig' (GitInstallation)
[core]
        symlinks = false
        autocrlf = true
        fscache = true

# From '.\.git\config' (Local)
[core]
        repositoryformatversion = 0
        filemode = false
        bare = false
        logallrefupdates = true
        symlinks = false
        ignorecase = true
```

```
$ cargo run -p gix --example crlf
   Compiling gix v0.43.0 (C:\Users\foobar\s\gitoxide\gix)
    Finished dev [unoptimized + debuginfo] target(s) in 1m 09s
     Running `target\debug\examples\crlf.exe`
[gix\examples\crlf.rs:50] &config =

[core]
        symlinks = false
        autocrlf = true
        fscache = true

[core]
        repositoryformatversion = 0
        filemode = false
        bare = false
        logallrefupdates = true
        symlinks = false
        ignorecase = true
[remote "origin"]
        url = https://github.com/Byron/gitoxide.git
        fetch = +refs/heads/main:refs/remotes/origin/main

[gix\examples\crlf.rs:51] config.strings_by_key("core.autocrlf") = Some(
    [
        "true",
    ],
)
[gix\examples\crlf.rs:52] config.boolean("core.autocrlf") = Some(
    true,
)
[gix\examples\crlf.rs:53] config.boolean("core.autocrlf").unwrap_or(false) = true
```

```
$ git config --list --show-scope --show-origin
system  file:C:/Users/foobar/scoop/apps/git/2.40.0.windows.1/etc/gitconfig core.symlinks=false
system  file:C:/Users/foobar/scoop/apps/git/2.40.0.windows.1/etc/gitconfig core.autocrlf=true
system  file:C:/Users/foobar/scoop/apps/git/2.40.0.windows.1/etc/gitconfig core.fscache=true
global  file:C:/Users/foobar/.gitconfig    core.autocrlf=input
local   file:.git/config        core.repositoryformatversion=0
local   file:.git/config        core.filemode=false
local   file:.git/config        core.bare=false
local   file:.git/config        core.logallrefupdates=true
local   file:.git/config        core.symlinks=false
local   file:.git/config        core.ignorecase=true
local   file:.git/config        remote.origin.url=https://github.com/Byron/gitoxide.git
local   file:.git/config        remote.origin.fetch=+refs/heads/main:refs/remotes/origin/main
```

Can the detail of local git installation somehow affect this?  I installed it from `scoop`.

**Comment by Byron** [comment]
Thanks for your help! We are getting closer! First of all I think that I should make logging available so in the few cases where *configuration is skipped* due to permission or read errors we can at least observe what happened.

That said, since the location of the global config seems known (i.e. `C:\Users\byron\.gitconfig`) maybe it can't read the file? Hmm, but then again, `git` can read the file just fine and so should `gix`.

I am still puzzled about this, and will see if files are silently skipped somewhere and if this can be changed to be less silent so we get a clue.

**Comment by Byron** [comment]
What a great intuition - that could really be it! On my VM, `$HOME` is set, but I am using a bash prompt. Maybe from the `cmd.exe` prompt all is different.

And it only took a moment to verify that in `bash` as well as powershell $HOME is set, but in `cmd.exe` `echo %HOME%` yields nothing. 

That's probably it, and I will see how git manages to resolve the home directory in this case.

**Comment by toymil** [comment]
`HOME` as an env var actually is not set anywhere on windows.

The `$HOME` in powershell is just a special case where microsoft is _trying_ to make posh more familiar to other shell users while making everything worse and confusing.  To access env var in posh you use `$env:<var name>`, e.g. there is `$env:Path` but no `$PATH`; so there is no `$env:HOME` since `HOME` is not set as an env var.

Moreover, the `$HOME` _variable_ in posh is not used by `std::env::{var, var_os}` to resolve env var, even when the binary is executed from within posh.

**Comment by pascalkuthe** [comment]
Git uses %USERPROFILE% I think but it also checks %APPDATA% If I rember right

**Comment by Byron** [comment]
With the fix being upstreamed soon and the pending release of `helix` tomorrow, the TTL of this issue won't be long, especially since I could verify that a missing `HOME` causes the observed behaviour without the fix, while working fine with it 🎉.
