### ISSUE TITLE
:log-open does not respect --log flag

### ISSUE THREAD

**Issue by rcorre** [helix-editor/helix#6469]
### Summary

When running `hx --log /tmp/helix.log`, the `:log-open` command opens `~/.cache/helix/helix.log`, not `/tmp/helix.log`

### Reproduction Steps

 

I tried this:

1. `hx --log /tmp/helix.log`
2. `:log-open`

I expected this to happen:

Opens /tmp/helix.log

Instead, this happened:

Opens default log location

### Helix log

<details><summary>~/.cache/helix/helix.log</summary>

```
please provide a copy of `~/.cache/helix/helix.log` here if possible, you may need to redact some of the lines
```

</details>
[helix.log](https://github.com/helix-editor/helix/files/11088995/helix.log)

### Platform

Linux

### Terminal Emulator

st 0.8.5

### Helix Version

22.12-405-gd458ddd0

**Comment by pascalkuthe** [comment]
Fixed by  #7573
