### ISSUE TITLE
Allow unix style paths on Windows

### ISSUE THREAD

**Issue by JackMordaunt** [helix-editor/helix#6484]
When picking files on Windows I'm constantly frustrated that I have to use backslash `\` to pick files. 

I think it would trivial to support both styles in the file picker. The moment you type `/` the fuzzy searching just chokes and matches nothing.

**Comment by helmesjo** [comment]
That makes two of us: #5414

**Comment by the-mikedavis** [comment]
Duplicate of https://github.com/helix-editor/helix/issues/5414
