### ISSUE TITLE
rust-analyzer doesn't work most of the time on 23.03

### ISSUE THREAD

**Issue by 0x00A** [helix-editor/helix#6505]
### Summary

After updating to 23.03 today, I noticed that rust-analyzer doesn't work with helix most of the time, go-to definition, doc for item under cursor etc. rarely works, then you restart helix or do `:lsp-restart`  and it works or doesn't. This is not the case with 22.12 which I have used daily since it was released. I tested again with the 22.12 and it works as expected each time.

### Reproduction Steps

```
# src/main.rs

fn main() {
    let _ = foo(32);
}

pub fn foo(n: i32) -> i32 {
    n
}
```

1. `hx src/main.rs`
2. move to `foo`
3. \<space\>k

I expected this to happen:

popup with the relevant info
```
foo

pub fn foo(n: i32) -> i32
```
Instead, this happened:

Nothing

### Helix log

broken: [helix 23.03.log](https://github.com/helix-editor/helix/files/11124287/helix.23.03.log)
working [helix 22.12.log](https://github.com/helix-editor/helix/files/11124289/helix.22.12.log)

### Platform

Windows 10 22H2 (19045.2728)

### Terminal Emulator

Windows Terminal Version: 1.16.10261.0, wezterm 20221120-093910-0bf36e5a

### Helix Version

helix 23.03 (3cf03723)

**Comment by yudjinn** [comment]
Just tried this out on 23.03, no issues. Followed full reproduction steps and the expected result is what I receive. I know this doesnt resolve your issue, but it does seem to be an issue with your environment in some way

**Comment by 0x00A** [comment]
> Just tried this out on 23.03, no issues. Followed full reproduction steps and the expected result is what I receive. I know this doesnt resolve your issue, but it does seem to be an issue with your environment in some way

I dug little deeper and I found the following:
```
cd C:\
cargo new Uppercase
cd Uppercase
hx
```
rust-analyzer works as expected on both 23.03 and 22.12


However
```
cd C:\
cargo new Uppercase
cd uppercase  <--- notice the lowercase first character
hx
```
rust-analyzer only works on 22.12

On windows paths are not case sensitive so `Uppercase` and `uppercase` are the same directory.

**Comment by 0x00A** [comment]
Accidentally closed.

**Comment by 0x00A** [comment]
Accidentally closed.

**Comment by pascalkuthe** [comment]
I have some ideas of what might be causing this. Could just post the logs for the reproduction case in the `uppercase` directory and the `Uppercase` directory?

**Comment by 0x00A** [comment]
> I have some ideas of what might be causing this. Could just post the logs for the reproduction case in the `uppercase` directory and the `Uppercase` directory so I have a direct comparison? My guess is that this is a RA bug

with `cd uppercase` [broken_uppercase_helix.log](https://github.com/helix-editor/helix/files/11125155/broken_uppercase_helix.log)
with `cd Uppercase` [working_Uppercase_helix.log](https://github.com/helix-editor/helix/files/11125157/working_Uppercase_helix.log)

**Comment by 0x00A** [comment]
Broken `cd uppercase` [broken_cd_uppercase.log](https://github.com/helix-editor/helix/files/11125206/broken_cd_uppercase.log)
Working `cd Uppercase` [working_cd_Uppercase_helix.log](https://github.com/helix-editor/helix/files/11125207/working_cd_Uppercase_helix.log)

**Comment by pascalkuthe** [comment]
Ah I think we are missing canonicalization in the workspace detection, I will look into a fix.
Possibly regressed by #5748

**Comment by pascalkuthe** [comment]
If I guessed correctly than #6517 should fix this. Could you test again @0x00A I don't use windows

**Comment by 0x00A** [comment]
helix 23.03 (5e75d331) works as expected.
