### ISSUE TITLE
Curly Underlines Don't Work in `zellij`

### ISSUE THREAD

**Issue by aidandenlinger** [helix-editor/helix#6510]
### Summary

When updating to helix 23.03, all the themes were updated to use curly underlines for diagnostic warnings in #5419. These curly underlines are not working when running helix inside of [zellij](https://github.com/zellij-org/zellij), a terminal multiplexer.

My config.toml is blank.

For the time being this is resolvable by copying the theme file, undoing #5419, and using that theme instead when using helix in zellij. Ideally the curly underlines would be displayed, or at least they would not be by default in terminals where they are broken. Not sure if this is a helix or zellij issue.

Running in alacritty by itself:
![image](https://user-images.githubusercontent.com/47428697/229199322-1d46646f-cf4d-4593-98fd-094dde358a9d.png)

Inside of a zellij session in alacritty:
![image](https://user-images.githubusercontent.com/47428697/229199475-1ac98aef-626c-425d-98a2-a4b1b56bdd1b.png)

### Reproduction Steps

 

I tried this:

1. Opened alacritty and opened a zellij session
  - Note: zellij can be quickly downloaded and run with the terminal command at <https://zellij.dev/>
2. Opened a project with a diagnostic warning (easy way: create a new rust project with cargo init, remove the `!` from println to get a warning)

I expected this to happen:

- Curly underlines to appear under the warning

Instead, this happened:

- No underline. The warning is still there and the message appears in the top right when I'm viewing the warning, but no underlines.

### Helix log

<details><summary>~/.cache/helix/helix.log</summary>

(There's nothing of substance in the log, it's just some vcs warnings because this is a est repo)
```
2023-03-31T11:30:30.277 helix_vcs [ERROR] PeelToCommit(
    Unborn {
        name: FullName(
            "refs/heads/main",
        ),
    },
)
2023-03-31T11:30:30.277 helix_vcs [ERROR] failed to open diff base for /home/user/Documents/mytest/src/main.rs
2023-03-31T11:30:30.277 helix_vcs [ERROR] PeelToCommit(
    Unborn {
        name: FullName(
            "refs/heads/main",
        ),
    },
)
2023-03-31T11:30:30.277 helix_vcs [ERROR] failed to obtain current head name for /home/user/Documents/mytest/src/main.rs

```

</details>

### Platform

Linux

### Terminal Emulator

zellij 0.35.2, running in alacritty 0.12.0

### Helix Version

helix 23.03 (3cf03723)

**Comment by pascalkuthe** [comment]
zellij likely changes `$TERM` and therefore makes it impossible to automatically detect the correct terminfo support. You can instead manually enable undercurl support by setting `undercurl = true` in your config (or temporarily with `:set undercurl true`)

**Comment by aidandenlinger** [comment]
Thank you for the quick response! I wrote this issue before looking closely at zellij - this seems to be an issue on their side (zellij-org/zellij#1594, PR at zellij-org/zellij#2018). I'll close this since this isn't anything wrong with helix.

**Comment by danillos** [comment]
There a PR to fix it in Zellij https://github.com/zellij-org/zellij/pull/2918
