### ISSUE TITLE
Configuration option for overriding background color

### ISSUE THREAD

**Issue by and-reas-se** [helix-editor/helix#6516]
Hi,

I'm trying out this editor for the first time today, trying to configure it to my liking. I'm trying to find a theme I like. The problem is I don't like any of them because the background colors are not pure black. I don't know why it's popular in design circles to make themes with background color that is close to, but not quite, black. But to me, a regular lowly user, it's super annoying. It makes it so I can't focus on the foreground and makes my eyes tired.

(Also some monitor types will turn off the backlight of a pixel if it's pure black, and it seems advantageous to be able to take advantage of that.)

Anyways, I could copy all the theme files into my config, rename every single one of them, edit just the background color of every single one to be pure black, and then go trough them to find one I like. I could probably even make a script to automate that process. But that seems like an unnecessary amount of work.

My feature request is therefore some way to override the background color in the main config. Be it black_background = true, or background_color = "black", or a generic way of overriding any property in a theme. I don't care. But please save my eyes from a slow death.

**Comment by archseer** [comment]
You can already create a new theme, inherit from an existing theme and override the background color.
