### ISSUE TITLE
"Go To Implementation" Not working with basic C++ project

### ISSUE THREAD

**Issue by John-Boccio** [helix-editor/helix#6518]
### Summary

I have a basic C++ project that I was using to try out helix and I can't seem to get "Go To Implementation" to work, or it is broken.

Meson generates a compile_commands.json file. I symlink that to the top level directory since meson requires a builddir (`ln -s builddir/compile_commands.json .`) and then run `hx .`, open `main.cpp`, and I am not able to use go to implementation on `ExampleClass`.

The code is attached in the zip file. To setup the project, run the following from the CPPExperiments directory:
```
meson setup builddir
ln -s builddir/compile_commands.json .
```

Here are the versions of my tools:
```
hx --version
helix 23.03 (3cf03723)
```

```
clangd --version
Homebrew clangd version 14.0.6
Features: mac+xpc
Platform: x86_64-apple-darwin22.3.0
```

```
hx --health | grep cpp
cpp                                    ✓ clangd                               ✓ lldb-vscode                          ✓                                      ✓                                      ✓
```

I can see that clangd is running when helix is open:
```
~ ps -ef | grep clangd
  501 48178 48176   0  1:30PM ttys000    0:00.22 /usr/local/opt/llvm/bin/clangd
```

[CPPExperiments.zip](https://github.com/helix-editor/helix/files/11125678/CPPExperiments.zip)

### Reproduction Steps

Run `hx .`, open `main.cpp`, try to perform "Go To Implementation" (`g-i`) while hovering over `ExampleClass`. It fails to jump to the `ExampleClass.cpp` file.

### Helix log

[helix.log](https://github.com/helix-editor/helix/files/11125701/helix.log)

### Platform

MacOS

### Terminal Emulator

iTerm2

### Helix Version

helix 23.03 (3cf03723)

**Comment by the-mikedavis** [comment]
The log looks fine, in particular:

```
2023-03-31T13:19:59.208 helix_lsp::transport [INFO] -> {"jsonrpc":"2.0","method":"textDocument/implementation","params":{"position":{"character":2,"line":6},"textDocument":{"uri":"file:///Users/johnboccio/Development/CPPExperiments/main.cpp"}},"id":1}
2023-03-31T13:19:59.211 helix_lsp::transport [INFO] <- {"id":1,"jsonrpc":"2.0","result":[]}
```

The language server is responding saying that there is no implementation to jump to. Goto definition (`gd`) works for me on ExampleClass

**Comment by John-Boccio** [comment]
> The log looks fine, in particular:
> 
> ```
> 2023-03-31T13:19:59.208 helix_lsp::transport [INFO] -> {"jsonrpc":"2.0","method":"textDocument/implementation","params":{"position":{"character":2,"line":6},"textDocument":{"uri":"file:///Users/johnboccio/Development/CPPExperiments/main.cpp"}},"id":1}
> 2023-03-31T13:19:59.211 helix_lsp::transport [INFO] <- {"id":1,"jsonrpc":"2.0","result":[]}
> ```
> 
> The language server is responding saying that there is no implementation to jump to. Goto definition (`gd`) works for me on ExampleClass

Thanks for taking a look, go to definition works for me as well. "Go to implementation" (`gi`) does not seem to be working though.

**Comment by the-mikedavis** [comment]
Do these reproduction steps work differently in other editors? `gi` is working as intended here: when the language server sends us an empty list of locations `[]` there is nothing to jump to

**Comment by helmesjo** [comment]
Do you compile with `clang` as well (that is, does `compile_commands.json` contain build commands generated by `clang` or eg. `gcc`)? Eg. if building with `gcc` and `-std=c++23` `clang` (and `clangd`) does not yet recognize this and defaults back to some older standard breaking most of the LSP server.

If that's the case, either find+replace all `c++23` with `c++2b`, or add this to a `.clangd` file in your project root:
```
CompileFlags:
  Remove:
  - '-std=c++23'
  Add:
  - '-std=c++2b'
```

then `:lsp-restart`

**Comment by John-Boccio** [comment]
You're right, @the-mikedavis. I guess I assumed go to implementation should work, but it doesn't appear to be working in any other editors as well. Interesting... hopping around with go to definition does work though.

To answer you question @helmesjo, I was using clang:
```
➜  CPPExperiments c++ --version
Apple clang version 14.0.0 (clang-1400.0.29.202)
Target: x86_64-apple-darwin22.3.0
Thread model: posix
InstalledDir: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin
```

My `compile_commands.json` is using `c++` is its commands. But replacing `c++` with `c++2b` didn't seem to make `gi` work either. I think going to implementation just isn't what I thought it was. Honestly, I am still not sure what it is supposed to be used for.

Closing this out as I believe the correct thing to do is use go to definition.

**Comment by John-Boccio** [comment]
And thank you for taking a look at this and helping!
