### ISSUE TITLE
"Select next sibling" does not honor select mode.

### ISSUE THREAD

**Issue by askreet** [helix-editor/helix#6535]
### Summary

I'm not sure if this is intended behavior, but it feels inconsistent with other available commands.

Given a piece of code like:

```rust
struct Foo {
    id: usize,
}

impl Foo {
    // some fns
}
```

### I tried this:

With my cursor anywhere within the definition of the `Foo` struct.
* `A-o` until I have selected the struct definition.
* `v`
* `A-n`

### I expected this to happen:

My selection to expand to the end of the implementation of `Foo`.

### Instead, this happened:

My selection changed to the implementation of `Foo`.

### Helix log

<details><summary>~/.cache/helix/helix.log</summary>
N/A.
</details>

### Platform

Windows native and WSL at the moment

### Terminal Emulator

Windows Terminal

### Helix Version

custom build

**Comment by the-mikedavis** [comment]
Duplicate of https://github.com/helix-editor/helix/issues/1999
