### ISSUE TITLE
Mouse=false ignored in wezterm in 23.03

### ISSUE THREAD

**Issue by jpambrun** [helix-editor/helix#6536]
### Summary

`mouse=false` is no longer honored in 22.03 when using wezterm. Still is in Windows's Terminal.

Could this be related to the new "Enhanced keyboard protocol" support? 

### Reproduction Steps

I tried this:

1. set `mouse=false`
2. open hx in wezterm, notice mouse is **enabled**
3. open hx in windows terminal, notice mouse is **disable**
4. set `moues=true`, 
4. open hx in wezterm, notice mouse is **enabled**
5. open hx in windows terminal, notice mouse is **enabled**

I expected this to happen:
mouse setting to be honored regardless of the terminal emulator

Instead, this happened:
not honored in wezterm

### Platform

Windows, in wsl

### Terminal Emulator

wezterm 20230326-111934-3666303c

### Helix Version

helix 23.03 (3cf03723)

**Comment by jpambrun** [comment]
Well, while I could reproduce 100% consistently in a wezterm session, I noticed in another term that moving the mouse printed escape codes on the bash prompt. Restarting wezterm fixed both issues for now. I am wondering how it got into this state. Some interaction between hx and wezterm?

**Comment by kirawi** [comment]
Closing as an indeterminable bug.
