### ISSUE TITLE
Can't add triple quotes auto-pairs

### ISSUE THREAD

**Issue by MrRobotMan** [helix-editor/helix#6544]
I am trying to add """ """ and ''' ''' for python auto-pairs. When I try to set it in languages.toml I get this error:

> Bad language config: data did not match any variant of untagged enum AutoPairConfig in `language.auto-pairs`
> Press <ENTER> to continue with default language config

```
[language.auto-pairs]
'(' = ')'
'{' = '}'
'[' = ']'
'"' = '"'
"'" = "'"
'`' = '`'
'"""' = '"""'
```

**Comment by the-mikedavis** [comment]
Multi-character auto-pairs are not currently supported: https://github.com/helix-editor/helix/issues/4035
