### ISSUE TITLE
`:<enter>` writes to disk

### ISSUE THREAD

**Issue by helmesjo** [helix-editor/helix#6548]
### Summary

I never noticed this before, so can't say if it's new in `23.03`, but just opening the command prompt `:` and hitting enter writes the buffer to disk.

Seems kind of "dangerous" I guess, so I'm just guessing it's not supposed to be some default behavior.

### Reproduction Steps

**I tried this:**

1. `hx`
2. Open a new buffer and make some arbitrary change.
3. Open command prompt and hit enter (`:<enter>`), without `w`.

**I expected this to happen:**
Nothing.
**Instead, this happened:**
Writes changes to disk.

### Helix log

<details><summary>~/.cache/helix/helix.log</summary>

```
please provide a copy of `~/.cache/helix/helix.log` here if possible, you may need to redact some of the lines
```

</details>

### Platform

Linux

### Terminal Emulator

fish

### Helix Version

helix 23.03

**Comment by kirawi** [comment]
I'm not able to reproduce this. Are you perhaps encountering the auto-fill?

**Comment by helmesjo** [comment]
Puh, you are correct. My theme did not make that obvious at all. False alarm then.
