### ISSUE TITLE
Themes should all use _ or all use - in their names

### ISSUE THREAD

**Issue by sourproton** [helix-editor/helix#6553]
There is this inconsistency where some themes use `_` in their names, like `ayu_dark`, while others use `-`, like `adwaita-dark`.

For consistency purposes and better user experience, I think they should all use one of the two options.

Possible solution: change all `-` to `_`.

**Comment by pickfire** [comment]
> This is a breaking change for any configs that use these themes. I don't think the consistency is worth breaking all of those configs -- @the-mikedavis 

Or maybe we can do like docs.rs to automatically swap to the counter part if it isn't found.

**Comment by tqwewe** [comment]
I wish this could be fixed, it's a pretty simple thing to change and the inconsistencies are a little annoying for me with OCD lol
