### ISSUE TITLE
"Esc" --> "Space" ignores the "Space" in tmux on MacOS

### ISSUE THREAD

**Issue by adam-bates** [helix-editor/helix#6556]
### Summary

Whenever I hit the "space" key within maybe ~500ms of hitting the "esc" key, then the "space" key is ignored.

I am on MacOS, and I use tmux. This bug does not occur when I am not in tmux. But no matter which terminal emulator I am using, if I am inside a tmux session, this bug occurs. But the bug is specific to Helix, it does not occur when I use vim or neovim or any other text editor.

I use neovim day-to-day, but I'm looking at helix to see if I can move over. In neovim, "space" is my <leader> so I regularly use "esc" then "space" to go to normal mode then execute some command.

I have updated to the latest versions of tmux and helix and the issue still persists. Neither of my configs are touching the esc key.

---

P.S. I tried adding a keybinding to help me fix this, something like:
```toml
[keys.normal]
esc = { esc = "normal_mode", space = "space_mode" }
```

I don't mind hitting "esc" twice as I usually hit it a bunch anyways, but apparently there is no such thing as "space_mode", and as far as I can tell there's no way for me to customize how it is opened?

### Reproduction Steps

I tried this:

1. Open a file in helix
2. Go into insert mode
3. `"esc"`
4. Within about ~500ms `"space"`

I expected this to happen:

From insert mode I should be moved to normal mode, then the space mode options should open up.

Instead, this happened:

From insert mode I am moved to normal mode. I need to press space again to open space mode options.

### Helix log

No logs printed when going through this sequence.

### Platform

macOS

### Terminal Emulator

Alacritty 0.11, tmux 3.3a

### Helix Version

helix 23.03 (3cf03723)

**Comment by the-mikedavis** [comment]
https://github.com/helix-editor/helix/wiki/Troubleshooting#when-using-tmux-or-screen-there-is-a-delay-after-hitting-escape-before-its-registered
