### ISSUE TITLE
Wrong line on goto_reference

### ISSUE THREAD

**Issue by sillent** [helix-editor/helix#6558]
### Summary

Hello,

The result of `goto_reference` gives an incorrect line number for the file it points to
<img width="1579" alt="Снимок экрана 2023-04-02 в 19 47 36" src="https://user-images.githubusercontent.com/2312584/229367371-ba8dcab0-53a5-45ed-863a-639435b280d8.png">

The problem is solving with this patch
```
   1   │ diff --git a/helix-term/src/commands/lsp.rs b/helix-term/src/commands/lsp.rs
   2   │ index f8e83a46..78dbc0be 100644
   3   │ --- a/helix-term/src/commands/lsp.rs
   4   │ +++ b/helix-term/src/commands/lsp.rs
   5   │ @@ -81,7 +81,7 @@ fn format(&self, cwdir: &Self::Data) -> Row {
   6   │
   7   │          // Most commonly, this will not allocate, especially on Unix systems where the root prefix
   8   │          // is a simple `/` and not `C:\` (with whatever drive letter)
   9   │ -        write!(&mut res, ":{}", self.range.start.line)
  10   │ +        write!(&mut res, ":{}", self.range.start.line + 1)
  11   │              .expect("Will only failed if allocating fail");
  12   │          res.into()
  13   │      }
```

### Reproduction Steps

Open project, place cursor on symbol/function/method in normal mode and press `g-r` 

### Platform

macOs

### Terminal Emulator

iTerm2

### Helix Version

helix 23.03 (3cf03723)

**Comment by the-mikedavis** [comment]
Good catch! Please open up a PR with that change
