### ISSUE TITLE
Support for more modifiers with progressive keyboard enhancement protocol

### ISSUE THREAD

**Issue by eugenesvk** [helix-editor/helix#6582]
Now that Helix has progressive keyboard enhancement protocol implemented, and that protocol supports extra modifiers beyond Control/Shift/Alt, would be great if Helix also allowed using those extra modifiers in key bindings

**Comment by the-mikedavis** [comment]
https://sw.kovidgoyal.net/kitty/keyboard-protocol/#modifiers

IMO the only other one worth supporting is Super. It's a fairly small change to support this, I'll post a PR

**Comment by eugenesvk** [comment]
Thank you
Some create an artificial 'hyper' key by using simultaneous 4 right-side modifiers. Am I correct that with the added support for Super this would also work in this protocol now that all 4 modifiers (although there is no difference between right and left at the moment per https://github.com/helix-editor/helix/discussions/6479)?

(I understand that the Hyper/Meta in the spec are separate keys)
