### ISSUE TITLE
Jump to line from file picker

### ISSUE THREAD

**Issue by mcdoker18** [helix-editor/helix#6610]
Allow to specify line and column number in the search line of file finder.
If user provides the line number then the file preview and selected file will be opened on that particular line.

The main usecase is copy paste file path and line output from linter or tests and than to open the file in specific place in one click. 

The example from IDEA https://www.jetbrains.com/webstorm/guide/tips/jump-to-file-line/

Formats: 
* <search_text>:<line_number>
* <search_text>:<line_number>:<column_number>

where line_number and column_number are positive numbers.

This is backward incompatible change, so maybe we should provide a config option.

**Comment by the-mikedavis** [comment]
You can specify row/column positions when opening files with `:open`

**Comment by mcdoker18** [comment]
> You can specify row/column positions when opening files with `:open`

Thanks! The open command covers my use cases.
