### ISSUE TITLE
Shell commands not running in the foreground

### ISSUE THREAD

**Issue by dlip** [helix-editor/helix#6615]
### Summary

When running a shell command on 23.03, helix stays in foreground and 'fights' with the command for input priority. 22.11 is fine. It happens in alacritty and kitty. eg. `:sh lazygit`

![image](https://user-images.githubusercontent.com/283316/230257024-dafcb610-4e36-4657-b283-8db217e8692a.png)

### Reproduction Steps

 

I tried this:

1.  `:sh lazygit`

I expected this to happen:

To use lazygit, then return to helix after quitting

Instead, this happened:

Helix and lazygit were active simultaneously

### Helix log

Nothing of interest here

### Platform

Linux

### Terminal Emulator

alacritty/kitty

### Helix Version

23.03

**Comment by dlip** [comment]
I have tracked down the issue to pr #6373 @pascalkuthe suggests:
> There is no reason for :sh to block the editor as it doesn't insert any text into the buffer.

But i think here is a valid use case, do you agree?

**Comment by David-Else** [comment]
If you are using Kitty, I recommend using LazyGit in another window, here is my solution: https://github.com/David-Else/kitty-terminal-project-launcher

**Comment by pascalkuthe** [comment]
> I have tracked down the issue to pr #6373 @pascalkuthe suggests:
> 
> > There is no reason for :sh to block the editor as it doesn't insert any text into the buffer.
> 
> But i think here is a valid use case, do you agree?

I don't think that's what `:sh` was ever really intended for. `:sh` is intended to quickly run a command and have the output popup in a window. Helix has not built-in terminal emulation so usually tuis don't work at all with `:sh`. I am not sure why lazygit worked previously but I suspect it did some trickery with suspend signals.

You can either do `c-zlazygit` or use something like kitty/zellij/termux as @David-Else mentioned.

**Comment by the-mikedavis** [comment]
Yeah, `:sh` is meant for non-interactive commands. Interactive commands and especially ones that take over the full terminal should be executed in a separate terminal or in the same terminal but suspending Helix first (`C-z`). This could be supported in-editor in the future with #1976

**Comment by dlip** [comment]
Fair enough, I set up a layout tabs in zellij, its almost as good but I can't automatically `reload-all` upon returning
![image](https://user-images.githubusercontent.com/283316/230515999-3cd8a663-054a-4ae7-8cdd-395ff2b04555.png)
