### ISSUE TITLE
Go to Definition not working anymore in SUBST or network mapped drives in Windows

### ISSUE THREAD

**Issue by jesusmgg** [helix-editor/helix#6634]
### Summary

My setup is: c:/users/jesus/projects folder mapped to J: drive letter.

Previously (version 22.12), g-d would find and follow definitions with that setup. Currently it fails with `sInternalError: url is not a file` if the mapping is done with SUBST or with `helix_view::editor [ERROR] editor error: No definition found.` if the drive is a network map.

### Reproduction Steps

In any windows terminal:
1. `subst j: c:/jesus/project_folder`
2. `j:`
3. `hx .`
4. try to g-d any type

### Helix log

<details><summary>~/.cache/helix/helix.log</summary>

```
# Network map
2023-04-06T16:20:41.246 helix_view::editor [ERROR] editor error: Async job failed: protocol error: InternalError: url is not a file
2023-04-06T16:20:52.865 helix_lsp::transport [ERROR] err: <- StreamClosed

# SUBST map
2023-04-06T16:24:36.152 helix_view::editor [ERROR] editor error: No definition found.
```

</details>

### Platform

Windows

### Terminal Emulator

Any

### Helix Version

helix 23.03

**Comment by the-mikedavis** [comment]
This is most likely a duplicate of https://github.com/helix-editor/helix/issues/6505 which was fixed in https://github.com/helix-editor/helix/pull/6517. Could you try building from the latest master and confirming that this is fixed?

**Comment by jesusmgg** [comment]
Confirmed, building and installing from master works.
