### ISSUE TITLE
Add narrow no-break space to `editor.whitespace`

### ISSUE THREAD

**Issue by Iorvethe** [helix-editor/helix#6640]
On the bépo keyboard layout, the narrow no-break space [1] is very easy to inadvertently type and having it as highlighted would be very helpful to avoid hard-to-track compile errors.

[1] https://symbl.cc/en/202F/

**Comment by archseer** [comment]
Is this is the same character as `&nbsp` in HTML?

**Comment by Iorvethe** [comment]
I believe it’s a different character, namely the `&nnbsp;` one.

**Comment by quentin-bettoum** [comment]
I would also like to have it highlighted. I will attempt a PR.
