### ISSUE TITLE
Theme preview doesn't return theme to normal when delete name with Alt-Backspace

### ISSUE THREAD

**Issue by h1t** [helix-editor/helix#6669]
### Summary

The theme preview when using :theme will keep the previewed theme if you delete name of theme using Alt-Backspace keys.
But if you delete name of theme by repeating Backspace key, then previewed theme return to normal.

### Reproduction Steps

 

I tried this:

1. `hx`

I expected this to happen:

Instead, this happened:

### Helix log

<details><summary>~/.cache/helix/helix.log</summary>

```
please provide a copy of `~/.cache/helix/helix.log` here if possible, you may need to redact some of the lines
```

</details>

### Platform

macOS

### Terminal Emulator

alacritty 0.12.0 (5a72819)

### Helix Version

23.03-29-g3dd715a1

**Comment by the-mikedavis** [comment]
We should call the prompt's update callback for all of these keymaps that change the prompt's line the same way as we currently do for regular `Backspace`: https://github.com/helix-editor/helix/blob/76825c7b661f4526856627bf1e34f024088f3fda/helix-term/src/ui/prompt.rs#L513-L522
