### ISSUE TITLE
`insert_at_line_end` behaves differently from `append_mode` when canceled 

### ISSUE THREAD

**Issue by templateK** [helix-editor/helix#6683]
### Summary

When insert_mode canceled, the cursor goes back to it's original position except 
when the mode started with `insert_at_line_end`. I consider this is inconsistent behavior.

### Reproduction Steps

cursor position marked with `^`

edit file:
```
foo
  ^
```

After `insert_at_line_end` and cancel the command without inserting anything.
```
foo
   ^
```

Whereas the _insert mode_ initiated by`append_mode`, the cursor comes right back to its original position after cancelling the command without insert anything.
```
foo
  ^
```

### Platform

macOS

### Terminal Emulator

kitty 0.26.3

### Helix Version

helix 22.12 (6a323c0b)

**Comment by the-mikedavis** [comment]
This is the intended behavior. `insert_at_line_end` is an insertion the same way as `insert_mode`. `append_mode` is a special way of entering insert mode that extends all selections by any inserted text as you type.

**Comment by templateK** [comment]
I can't imagine the benefit or intention of this behavior but if this is indeed intended one, then I think it's ok close this issue.
