### ISSUE TITLE
Sudden crash due to panic

### ISSUE THREAD

**Issue by mamins1376** [helix-editor/helix#6684]
### Summary

Was working normally but suddenly this `panic` happened. I do not know the cause or am able to reproduce the error.

```
thread 'main' panicked at 'Attempt to slice past end of RopeSlice: slice end 4182, RopeSlice length 1066', /build/.cargo/registry/src/github.com-1ecc6299db9ec823/ropey-1.5.1-alpha/src/slice.rs:656:9
```

### Helix log

<details><summary>relevant part of ~/.cache/helix/helix.log</summary>

```
2023-04-10T12:51:15.310 helix_lsp::transport [ERROR] err <- "I[12:51:15.310] <-- textDocument/hover(2646)\n"
2023-04-10T12:51:15.313 helix_lsp::transport [ERROR] err <- "I[12:51:15.313] --> reply:textDocument/hover(2646) 2 ms\n"
```

</details>

### Platform

[Arch] Linux btw ;)

### Terminal Emulator

sakura 3.8.6-1

### Helix Version

helix 22.12

**Comment by the-mikedavis** [comment]
Without reproduction steps or a backtrace this won't be possible to debug. If you opened the jumplist just before the crash, this might be https://github.com/helix-editor/helix/issues/6628

**Comment by pascalkuthe** [comment]
Closing as this is not actionable. If you run into.this again and have a backtrace or reproduction case feel free to reopeon or open a new issue
