### ISSUE TITLE
Ctrl-u and Ctrl-d not scrolling preview in picker

### ISSUE THREAD

**Issue by sourproton** [helix-editor/helix#6689]
### Summary

The [docs](https://docs.helix-editor.com/keymap.html#picker) state that, in picker mode, `PageUp` and `Ctrl-u` work as `Page up` while `PageDown` and `Ctrl-d` work as `Page down`.

This is not the behavior I see in my installation.

These shorcuts don't scroll the file preview, but jump multiple files in the picker upwards or downwards, like pressing `Up` or `Down` multiple times.

I'm on archlinux with helix being installed via pacman.

### Reproduction Steps

 

I tried this:

1. `hx`
2. `Ctrl-f`
3. `Ctrl-d` in a file that didn't fit entirely in the preview

I expected this to happen:

Scroll of the preview

Instead, this happened:

The picker went to select 4 files downwards

### Platform

Linux

### Terminal Emulator

alacritty

### Helix Version

helix 23.03

**Comment by the-mikedavis** [comment]
There isn't a way to scroll the preview in a picker currently, that's covered by https://github.com/helix-editor/helix/issues/4102. Page up/Page down in the docs is saying that C-u/C-d page through the options
