### ISSUE TITLE
Make move_visual_line_* commands with <count> move by actual line, instead of visual line

### ISSUE THREAD

**Issue by antoyo** [helix-editor/helix#6696]
Hi.
I'm not sure exactly how I achieved this setup in vim, but when I do `j`, it moves by 1 visual line, while when I do `<count>j`, it moves by actual lines.
I find this convenient because I usually care about relative line numbers only when I use a count.

Perhaps a generic solution to this problem would be to allow different commands to be set depending on whether a count is used or not, but this could be confusing.

Thanks.

**Comment by 6lj6** [comment]
Good idea, this feature need the configSystem to be more customizable. 

Make everything customizable, both in static config file and dynamic switch operation!

**Comment by pascalkuthe** [comment]
I missed this back when this was created.  I don't plan to add this to core, see https://github.com/helix-editor/helix/wiki/FAQ#can-the-jk-bindings-be-changed-to-ignore-soft-wrapping-when-using-a-count-like-3j
