### ISSUE TITLE
Arrow key mappings

### ISSUE THREAD

**Issue by itzmjauz** [helix-editor/helix#67]
In both Kakoune and Vim arrow keys are usually mapped to moving the cursor. 

I understand this might be a design choice.

A non-elegant implementation: [github.com/itzmjauz/helix](https://github.com/itzmjauz/helix/commit/1a2d9bac6b8e1b4a0ceeba07dbfa8d26317f303f)

**Comment by archseer** [comment]
Sounds reasonable, go ahead and make a PR!

**Comment by Cthutu** [comment]
Yes please, I can't stand using HJKL (the only thing about vim I don't like).  This PR would be an excellent addition.

**Comment by itzmjauz** [comment]
@archseer I've been playing around with helix a bit more;
I've personally also added Home/End key bindings ( Similar mappings to ^ and $ )

Additionally these key bindings also allow movement while in insert mode ( primary reason I use them sometimes ).

If that sounds fine too I guess ill create 2 PR's, one for the extra key mapping one for the insert extension.

**Comment by Cthutu** [comment]
Unfortunately, the PR does not work for insert mode, only normal mode.

**Comment by itzmjauz** [comment]
> Unfortunately, the PR does not work for insert mode, only normal mode.

Hi, that is correct, the insert mode extension is in a separate pull request, but needs some more research because of underlying issues, I myself have not yet encountered these so I cannot give further detail.

Current arrow keymaps work for normal mode and extend mode.

You could opt to build helix yourself, and pull : https://github.com/itzmjauz/helix/tree/insert-mode-keymap-extension into the master branch before doing so. (You could also just copy keymap.rs: https://github.com/itzmjauz/helix/blob/insert-mode-keymap-extension/helix-term/src/keymap.rs over your own)
This will give you arrow keys and home-end keys navigation in insert mode.
