### ISSUE TITLE
permit [keys.normal.ä] as config.toml table headers

### ISSUE THREAD

**Issue by soloturn** [helix-editor/helix#6704]
### Summary

permit keymapp of characters reachable from international keyboards as config toml table headers, like é, ö. tried to remap ```[``` to ```ü``` as the key has ```[``` behind ```altgr``` and ```ü``` unmodified:
```
[keys.normal.ü]
d = ["goto_prev_diag"]
D = ["goto_first_diag"]
```

```
❯ hx  ~/.config/helix/config.toml
Bad config: TOML parse error at line 15, column 13
   |
15 | [keys.normal.ü]
   |             ^
invalid table header
expected `.`, `]`

Press <ENTER> to continue with default config

```

### Platform

Linux

### Terminal Emulator

xfce terminal

### Helix Version

helix 23.03

**Comment by soloturn** [comment]
#5046 might solve this one.

**Comment by Iorvethe** [comment]
I think that you can do this by surrounding the faulty characters with `"` like so:

```toml
[keys.normal."ü"]
"è" = ["goto_prev_diag"]
"È" = ["goto_first_diag"]
```

**Comment by the-mikedavis** [comment]
This is a TOML limitation. Quoting as mentioned above is the way to use these keys in config
