### ISSUE TITLE
Helix is not added to $PATH through winget

### ISSUE THREAD

**Issue by Vxlnce** [helix-editor/helix#6705]
### Summary

Not sure if here or winget is the correct place for this but the path winget places in the environment variables is incorrect. For me it was placed in `C:\Users\Username\AppData\Local\Microsoft\WinGet\Packages\Helix.Helix_Microsoft.Winget.Source_8wekyb3d8bbwe` but the executable is placed in  `C:\Users\bilzt\AppData\Local\Microsoft\WinGet\Packages\Helix.Helix_Microsoft.Winget.Source_8wekyb3d8bbwe\helix-23.03-x86_64-windows` so when you type `hx` into the terminal it won't find it. I'm happy to make the change but am not familiar with winget configuration so do not know where to make the change.

### Reproduction Steps

I tried this:

1. `winget install helix.helix`
2. `hx`
3. `command not found`
I expected this to happen:
1. `winget install helix.helix`
2. `hx`
3. Helix opens

### Platform

Windows

### Terminal Emulator

Windows Terminal

### Helix Version

23.03

**Comment by the-mikedavis** [comment]
You should open this up against winget, we don't maintain the winget package

**Comment by Vxlnce** [comment]
No worries, thank you for your time. :)
