### ISSUE TITLE
Global indentation option

### ISSUE THREAD

**Issue by godalming123** [helix-editor/helix#6709]
Their do not appear to be any options on indentations in the wiki and I would like to always use tabs instead of spaces and display tabs as 4 spaces

**Comment by CptPotato** [comment]
Indentation can be specified per language in the language configuration ([see docs](https://docs.helix-editor.com/master/languages.html#language-configuration)).

I'm not sure if there is a way to set this globally, yet.

**Comment by gabydd** [comment]
Duplicate of https://github.com/helix-editor/helix/issues/3159
