### ISSUE TITLE
Color escape codes in strings

### ISSUE THREAD

**Issue by antoyo** [helix-editor/helix#6712]
Hi.
It would be convenient to color escape characters like `\n` in strings.
It seems it's already colored for some languages (like Rust), but not others (like C++).
Thanks.

**Comment by the-mikedavis** [comment]
That comes from this stanza in the rust highlights: https://github.com/helix-editor/helix/blob/b9b4ed5c6c68e8c2c744e779b5c4d1c148a60f47/runtime/queries/rust/highlights.scm#L16

The C/C++ tree-sitter grammars parse the same `escape_sequence` rule, so it should work to add that same stanza to `runtime/queries/c/highlights.scm` for both C and C++

**Comment by FarzinVatani** [comment]
Hey @the-mikedavis,

Could you assign this issue to me?
