### ISSUE TITLE
Hint when execute run shell command inserting

### ISSUE THREAD

**Issue by Renkai** [helix-editor/helix#6717]
When we use `:sh`, we can get hint like directory and file names, but when we execute `!`(Run shell command, inserting output before each selection), we don't have this feature, can we let it has this feature as also?

**Comment by the-mikedavis** [comment]
The shell commands open a prompt with no completion: https://github.com/helix-editor/helix/blob/d5fec302c9fc6a6e334a0d518c6d10f7dbeb26a7/helix-term/src/commands.rs#L5197-L5202

That could be changed to the filename completer to match `:run-shell-command`: https://github.com/helix-editor/helix/blob/d5fec302c9fc6a6e334a0d518c6d10f7dbeb26a7/helix-term/src/commands/typed.rs#L2707-L2713
