### ISSUE TITLE
No access to system clipboard

### ISSUE THREAD

**Issue by Zoybean** [helix-editor/helix#6718]
### Summary

On linux mint, It seems like helix can't access the system clipboard. Commands that use the system clipboard do use some clipboard within an instance of helix, but it is not the system clipboard.

### Reproduction Steps

 

I tried this:

1. copy something into system clipboard (highlight in terminal, or ctrl-c in some gui applications)
2. `hx`
3. ` p`

I expected this to happen:

- helix pastes the copied text

Instead, this happened:

- nothing is pasted

### Helix log

n/a

### Platform

Linux

### Terminal Emulator

GNOME terminal

### Helix Version

23.03-47-gd5fec302

**Comment by archseer** [comment]
https://github.com/helix-editor/helix/wiki/Troubleshooting#on-linux

**Comment by Zoybean** [comment]
Ah, I searched open bugs but forgot to check the readme.
Linking #2615 as it addresses the rest of this for me
