### ISSUE TITLE
Helix icon missing on COPR repo

### ISSUE THREAD

**Issue by Ashvith10** [helix-editor/helix#6720]
The new update for Helix (v23.03) brings a desktop icon, but it has missing icon.
![Screenshot from 2023-04-10 20-51-55](https://user-images.githubusercontent.com/113123021/231358617-115a562c-e89f-41c5-b296-a6582a7a0950.png)

**Comment by archseer** [comment]
We don't maintain the package. \cc @VarLad ?

**Comment by VarLad** [comment]
@Ashvith10 I've updated the COPR. 
Lets close this and continue the discussion in https://gitlab.com/VarLad/rpm-specs/-/issues/11
Also, I already gave the link to the specfile repo in COPR page (in Contact) but I'll make that more explicit I guess. All issues regarding package (for the COPR) are to be made at the above linked repo
