### ISSUE TITLE
Project-specific config can't unset `formatter`

### ISSUE THREAD

**Issue by benjamineskola** [helix-editor/helix#6723]
If I have a per-user `languages.toml` that sets a `formatter`, then it doesn't appear that there's any way to unset it on the project level.

I could set `formatter = { command = "cat" }` or something similarly no-op, but that's not actually equivalent to being unset — since if it's unset and there's an LSP configured that supports formatting, the LSP will be used, but if I set `formatter` to a no-op it won't be.

I wonder if there should be an `unset`/`undef`/`null` value that indicates to use the default setting.

Right now it appears that the only options are either never to set a formatter globally, or never to use LSP-provided formatting on a per-project level.

**Comment by gabydd** [comment]
ah that would be a nice way to unset it, I wonder if it is possible with serde, maybe with some custom deserialization

**Comment by KMikeeU** [comment]
Interesting, toml serde has no apparent way to unset an Option except for not including it in the toml. Perhaps the unit type `()` could be used?

**Comment by the-mikedavis** [comment]
You should be able to set `formatter = { command = "" }`. We don't use the external formatter if the binary can't be found.

**Comment by pascalkuthe** [comment]
(Closing as per comment above)
