### ISSUE TITLE
Panic when Edits the current line in the $EDITOR program

### ISSUE THREAD

**Issue by Renkai** [helix-editor/helix#6734]
### Summary

After I set `hx` as the default editor in `zsh`, I got panic when trying to edit the command with [ctrl-x ctrl-e](https://unix.stackexchange.com/questions/696136/what-exactly-handles-the-ctrlx-shortcut-family-e-g-ctrlx-ctrle-in-linux-te#:~:text=Ctrl%20x%20Ctrl%20e%20%3A%20Edits,or%20variable%20assignments%20found%20there.)

### Reproduction Steps

 

I tried this:

1.  export EDITOR='hx' in `~/.zshrc`
2. ctrl-x ctrl-e in my terminal

I expected this to happen:
Helix opened, put what I already typed in the terminal into buffer.

Instead, this happened:
```
➜  ~ thread 'main' panicked at 'reader source not set', /Users/brew/Library/Caches/Homebrew/cargo_cache/registry/src/github.com-1ecc6299db9ec823/crossterm-0.26.1/src/event/read.rs:38:30
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

### Helix log

<details><summary>~/.cache/helix/helix.log</summary>

```
2023-04-13T13:34:40.867 helix_vcs [ERROR] Error {
    context: "failed to open git repo",
    source: Discover(
        NoGitRepository {
            path: "/private/tmp",
        },
    ),
}
2023-04-13T13:34:40.867 helix_vcs [ERROR] failed to open diff base for /private/tmp/zshtIXKYX
2023-04-13T13:34:40.867 helix_vcs [ERROR] Error {
    context: "failed to open git repo",
    source: Discover(
        NoGitRepository {
            path: "/private/tmp",
        },
    ),
}
2023-04-13T13:34:40.867 helix_vcs [ERROR] failed to obtain current head name for /private/tmp/zshtIXKYX```

</details>


### Platform

macOS

### Terminal Emulator

wezterm

### Helix Version

helix 23.03

**Comment by archseer** [comment]
Probably the tty issue on macOS: https://github.com/helix-editor/helix/pull/5468
