### ISSUE TITLE
There should be an error when formating fails

### ISSUE THREAD

**Issue by godalming123** [helix-editor/helix#6736]
### Summary

If I format a document that does not have a LSP installed for its language nothing happens

### Reproduction Steps

**I tried this:**
1. `:format`

**I expected this to happen:**
The editor tells me that their is no language server installed for this language and possibly shows me a guide to install a language server

**Instead, this happened:**
Nothing happend

### Helix log

<details><summary>~/.cache/helix/helix.log</summary>

```
2023-04-13T10:38:25.338 helix_view::editor [ERROR] Failed to initialize the LSP for `source.python` { cannot find binary path }
```

</details>

### Platform

Linux

### Terminal Emulator

alacritty

### Helix Version

helix 23.03

**Comment by FedericoCeratto** [comment]
This is especially important when auto-format on save is enabled. When the formatting fails there is no way to notice it.
