### ISSUE TITLE
do not exit helix on pressing C-q with unwritten or discarded changes

### ISSUE THREAD

**Issue by matu3ba** [helix-editor/helix#674]
losing uncommitted changes is bad.

**Comment by archseer** [comment]
`C-q` is not a mapping present in helix, maybe that comes from your tmux config?

**Comment by Omnikar** [comment]
They're probably talking about `C-w q`/`C-w C-q`.

**Comment by vv9k** [comment]
I submitted some changes in #694. Let me know what do you think of this approach. Perhaps the error message could be improved.
