### ISSUE TITLE
File (and directory) name completion

### ISSUE THREAD

**Issue by vp2177** [helix-editor/helix#6745]
In _NeoVim_ at least, one can type, let's say `/usr/<C-x C-f>`, and get filename/directory-name completion, even in a `.txt` file:
![Screenshot from 2023-04-13 16-39-31](https://user-images.githubusercontent.com/451903/231812524-129fb4ee-5667-40e0-8507-8efa96227d28.png)

In _Helix_, there is no such feature that I could find (tried <kbd>C-x</kbd>). I think it would be very useful.

**Comment by the-mikedavis** [comment]
This falls under https://github.com/helix-editor/helix/issues/1015. Also see https://github.com/helix-editor/helix/pull/2608
