### ISSUE TITLE
Tree sitter dockerfile: Error on `USER 1000:100`

### ISSUE THREAD

**Issue by LeoniePhiline** [helix-editor/helix#6797]
### Summary

`USER 1000:100` breaks dockerfile tree parsing:

![grafik](https://user-images.githubusercontent.com/22329650/232632328-e8a523d2-e64c-4084-a365-465606f1bcf7.png)

Scopes:

![grafik](https://user-images.githubusercontent.com/22329650/232632363-7a2445c3-62c1-46ac-b505-bd8f4f34d937.png)

### Reproduction Steps

 

I tried this:

1. `hx`
2. `:lang dockerfile`
3. paste snippet:

```dockerfile
FROM alpine:latest

USER 1000

RUN set -eux
```

I expected this to happen:

Perfect syntax highlighting.

Instead, this happened:

`USER` breaks highlight:

![grafik](https://user-images.githubusercontent.com/22329650/232632549-3bb124f9-62a3-471e-9402-b46cfcac83af.png)

`:tree-sitter-scopes` shows `ERROR`.

### Helix log

Nothing relevant.

### Platform

OpenSUSE Tumbleweed - Linux

### Terminal Emulator

Konsole

### Helix Version

helix 4cdba7cccdd6a9fe5fbb3d15c9db3edc147b7a90

**Comment by A-Walrus** [comment]
Looks like an upstream issue in [tree-sitter-dockerfile](https://github.com/camdencheek/tree-sitter-dockerfile)

**Comment by LeoniePhiline** [comment]
We just need to update. 
The issue was fixed in March 2022 in https://github.com/camdencheek/tree-sitter-dockerfile/commit/71ac1e88805ba0f1826051be9148cb3fde70321c

We reference a commit from 2021.
