### ISSUE TITLE
Windows 10 build has malfunctioning view

### ISSUE THREAD

**Issue by Cthutu** [helix-editor/helix#68]
It seems that the first line is not rendered, and the status bar is rendered at the wrong place too.  

![image](https://user-images.githubusercontent.com/348614/120537162-dfce6900-c3dc-11eb-9478-de2bb2cc8817.png)

**Comment by IceDragon200** [comment]
Could you specify the terminal emulator being used, did you try a different terminal under windows to see if the problem persists?

**Comment by Kethku** [comment]
using pwsh or cmd on windows 10 doesn't reproduce this error for me.

**Comment by wangbyby** [comment]
I can not open it.
Error like this:
```txt
PS C:\Users\123\Downloads\helix-v0.0.6-x86_64-windows> .\hx.exe
thread 'main' panicked at 'index out of bounds: the len is 3451 but the index is 3451', helix-tui\src\buffer.rs:185:14
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

**Comment by archseer** [comment]
@wangbyby Download a newer release (0.0.9)

**Comment by Cthutu** [comment]
> Could you specify the terminal emulator being used, did you try a different terminal under windows to see if the problem persists?

Yes, I use cmder. But that should be compatible with CMD.

**Comment by Cthutu** [comment]
OK, it seems to work on CMD, although ':' doesn't work so there's no way to quit Helix that I can find (it's even harder than Vim to do that lol).  On ConEmu (which is used by cmder) it doesn't display properly.  I wonder what the difference is.  Vim works find on both types of console.

**Comment by janhrastnik** [comment]
#79 should fix ':' not working. I'll take a look at the display issue in cmder.

**Comment by Cthutu** [comment]
I tried running it on the Windows build of Alacritty and the display did not work for that.  Not sure about Alacritty on other OSes.

**Comment by janhrastnik** [comment]
ConEmu and alacritty (win 10) work fine for me. In cmder I get the same issue as above. Resetting the settings to the default ConEmu settings doesn't fix it. I'm guessing its got something to do with how clink is implemented in cmder.

**Comment by Cthutu** [comment]
Interesting that it works for you - I wonder why.  This is the screenshot from opening up a file in Helix within Alacritty:
![image](https://user-images.githubusercontent.com/348614/120816149-66538980-c548-11eb-8e42-04968d01c2d1.png)

I built Alacritty from the latest source.

**Comment by janhrastnik** [comment]
I do notice some black bars on every other line appear during resizing but they disappear once you stop resizing the window.
![image](https://user-images.githubusercontent.com/25058758/120823664-efbe8800-c557-11eb-9c9d-178aaa851063.png)
I'm using the 0.8.0 portable version. It seems it's not loading newlines on my end because of CR-LF.
