### ISSUE TITLE
Reference to non-existent `soft-wrap.wrap_at_text_width` option in docs

### ISSUE THREAD

**Issue by augustebaum** [helix-editor/helix#6803]
The docs for the `editor.text-width` option (https://docs.helix-editor.com/configuration.html?highlight=editor#editor-section) refer to the other option: `soft-wrap.wrap_at_text_width`. It should be `soft-wrap.wrap-at-text-width`. Could there be a way to dynamically link to the option itself to avoid desynchronization?

**Comment by Mordeaux** [comment]
I'm new around here, so I'm not sure what the process is, but I think this can be closed now, correct?

**Comment by the-mikedavis** [comment]
Yep this is fixed now. I didn't notice when merging but the PR wasn't linked to the issue so it didn't close it automatically. For future reference, you can use a few keywords to automatically link PRs to issues so they're closed when the PR is merged: https://docs.github.com/en/get-started/writing-on-github/working-with-advanced-formatting/using-keywords-in-issues-and-pull-requests#linking-a-pull-request-to-an-issue (I'm surprised "solves" isn't in that list actually 🤔)

**Comment by Mordeaux** [comment]
@the-mikedavis ah thank you!
