### ISSUE TITLE
Soft wrap messes count based line navigation

### ISSUE THREAD

**Issue by rkshthrmsh** [helix-editor/helix#6819]
### Summary

Count based line navigation such as `10j` or `10k` to jump 10 lines down or up in normal mode does not work as expected while using soft wrap. I suspect that soft wrapped lines are being used in the count computation for the navigation. As a result, the jump always lands short of where it is expected to go.

### Reproduction Steps

With soft wrap enabled (with default text-width(80)), and with the cursor at `1:1` (top left) in a file such as the one below, `2j` takes the cursor to text within the first line instead of the first blank line after the text line.
```
# Band Gap
Band gap is the minimum energy required to excite an electron in the valence band to a state in the conduction band where it can participate in conduction[[Band Gap#^Ref-1|[1]]]. An important parameter in band theory is Fermi Level which is the chemical potential at $T=0$ or can also be understood as the top of the available electron energy levels at that temperature. The position of the Fermi level in relation to the conduction band determines the electrical properties of the substance.


![[Pasted image 20220912143526.png]]
```

### Platform

macOS

### Terminal Emulator

warp

### Helix Version

helix 23.03 (3cf03723)

**Comment by pascalkuthe** [comment]
This is intentional you can use `gk`/`gj` for line wise navigation. Since this was asked recently in the matrix, here is my response from there.

>  I dont intent to change this. Hellix tends to prefer explicit/consistent/unspurising behavior over convenience. For heavily softwrapped text (like a long markdown paragraph) the visual line wise motions are quite useful.
Once we have a plugin system people could write a custom command that calls the other built-in command when there is a count but I think as a built-in this is better as is. If we change the behavior to be implicit here people that prefer relative visual movement can never recover the current behaviour with a custom script/config

**Comment by rkshthrmsh** [comment]
Thanks for the context @pascalkuthe. However, I'm unsure if your answer adresses the issue highlighted here. 

The default behavior does not seem explicit/consistent/unspurising, especially when using relative line numbers. Many people use this feature for the ability to quickly jump between parts of the code using the relative numbers. The default behavior seems quite inconsistent since the jump lands many lines short of the intended location.

I understand using `gj` and `gk`for navigating within the soft wrapped files though.
