### ISSUE TITLE
Displaying Colour codes when showing output of a shell command instead of colours.

### ISSUE THREAD

**Issue by iamevie** [helix-editor/helix#6830]
![Untitled](https://user-images.githubusercontent.com/99840003/233390993-2e6fd438-fb7e-4109-b1e3-e86a91d573dc.png)

I recently found out, that if a shell command returns colour codes to well colour the output, these codes will be displayed instead of just displaying the colour.

Kind regards :)

**Comment by the-mikedavis** [comment]
IMO interpreting terminal escape codes is out of scope for `:run-shell-command`. This should fall under https://github.com/helix-editor/helix/issues/1976

**Comment by kirawi** [comment]
Closing in favor of #1976.

**Comment by miranquil** [comment]
Hey dude, sorry for disturbing. If I may, could you please share your background image of your terminal?
