### ISSUE TITLE
Remapping C-i and C-o not working

### ISSUE THREAD

**Issue by yusuphgammut** [helix-editor/helix#6833]
### Summary

Hi team. I've got used to invert the behavior of `Ctrl-i` and `Ctrl-o` keys. For me it's just a bit easier to memorize "i" as going backwards and "o" as going forward. However, when I add the remapping to my `config.toml` file the jumps stop working altogether. This is what I'm adding: 

```toml
[keys.normal]
C-i = "jump_backward"
C-o = "jump_forward"
```

I've revisited the documentation and everything seems to be right, so I think this can be a bug.

### Reproduction Steps

1. Use Helix latest version.
2. Add the configs described above.

I expected this to happen:
Jump backwards in the jump list when pressing `Ctrl-i`.
Jump forward in the jump list when pressing `Ctrl-o`

Instead, this happened:
Nothing happens. No jumps visible.

### Helix log

The only thing that gets logged when pressing `Ctrl-i` or `Ctrl-o` (using `-vvv`) is this:

``` txt
2023-04-20T12:21:26.012 helix_view::document [DEBUG] id 2 modified - last saved: 0, current: 0
2023-04-20T12:21:26.411 helix_term::application [DEBUG] received editor event: IdleTimer
```

### Platform

macOS

### Terminal Emulator

Alacritty

### Helix Version

helix 23.03 (b336cd76)

**Comment by the-mikedavis** [comment]
`C-i` sends the keycode for `tab` unless the terminal emulator supports the enhanced keyboard protocol (alacritty doesn't: https://github.com/helix-editor/helix/wiki/Terminal-Support#enhanced-keyboard-protocol). You should be able to rebind `tab` in `keys.normal` instead, or use Kitty or WezTerm with the [`enable_kitty_keyboard`](https://wezfurlong.org/wezterm/config/lua/config/enable_kitty_keyboard.html) option set to `true`.

**Comment by yusuphgammut** [comment]
You're right, I added `"tab" = "jump_backward"` and it works now. I think I had a similar issue back then when I was configuring vim and totally forgot about it. Thanks @the-mikedavis .
