### ISSUE TITLE
Add extend_to_first_nonwhitespace

### ISSUE THREAD

**Issue by phaazon** [helix-editor/helix#6836]
Kakoune has this nice extend-based workflow that is _almost_ entirely reproducible in Helix. It’s nice because it’s consistent:

- `w` select next word; `W` extends next word.
- `f(` select up to next `(`; `F(` extends up to next `(`.
- `gh` goes to the line start; `Gh` extends up to the line start.
- `gi` goes to the first nonwhitespace character; `Gi` extends up to the first nonwhitespace character.

Helix can do all of that already… except `Gi`, since it doesn’t have `extend_to_first_nonwhitespace`  (but it does have `extend_to_line_start`!).

I suggest adding `extend_to_first_nonwhitespace`, and I might work on it if no one else is already working on it.

**Comment by Redempt** [comment]
wouldn't `vW` do this?

**Comment by phaazon** [comment]
No, because using `v` means going in `select` mode first.

**Comment by ghc0** [comment]
So what's this for?

**Comment by ghc0** [comment]
> * `f(` select up to next `(`; `F(` extends up to next `(`.

`f/F`, `t/T` is more consistent with `/?` => forward/backward operations in 1-D char[].

As for the fn of `extends to`, I suggest merge the `expand` and `match` mode and redesign the whole logic, it's sometimes weird.
