### ISSUE TITLE
outdated

### ISSUE THREAD

**Issue by ghc0** [helix-editor/helix#6849]
outdated

**Comment by GeekPro101** [comment]
Do you mean column numbers at the top of the screen? or simply something displaying what your column number is?

If the second one - on the default install of Helix at the bottom right it's the number after the colon (the 9 below):
![image](https://user-images.githubusercontent.com/14115426/233827347-4058d22f-c590-4a76-97c4-11e39c267d3b.png)

Its location can be customed using 'position' in the statusline section of the config https://docs.helix-editor.com/configuration.html

**Comment by ghc0** [comment]
Thanks for your picture, it's more powerful than words. Here is my picture:
![image](https://user-images.githubusercontent.com/130418928/233829607-5ac04363-5ea1-4576-b566-79c5db60b56f.png)

**Comment by GeekPro101** [comment]
I see what you mean, thanks for explaining

**Comment by the-mikedavis** [comment]
You can jump to line `123` with `:123<ret>`. We could extend this to support the syntax you can already use on the command line. For example `hx README.md:14:10` jumps to line 14 column 10. So `:123:456<ret>` would jump to line 123 column 456 and maybe `::456` would jump to column 456 on the current line.

**Comment by ghc0** [comment]
Hi mike! I have lots of design willing to talk to you!

The method you mentioned is some kind of partial solution. Yeah, its another handful tool for absolute column number positioning, like GPS.

What I wanna express in this issue, since there shows the relative line number to help me use `8j` directly to the position in vertical DIMENTION, if I wanna change particular position of relative column(horizontal DIMENTION) => `13l` sounds better than `::13`, what do you think?

**Comment by ghc0** [comment]
@the-mikedavis This issue is about the second DIMENSION ruler of screen according to the first DIMENSION of screen: "line number".

Please file your complete different new issue by your own. If you don't know what is exact it is, I can teach you. Don't be so impolite to change this issue by your personal willing. Please
