### ISSUE TITLE
LSP Inline hints not displaying

### ISSUE THREAD

**Issue by Eliascm17** [helix-editor/helix#6868]
### Summary

I am hoping there is something wrong on my end but for whatever reason inline hints aren't being shown anymore despite setting the flag to be true in the `config.toml`. I've repeatedly ran the `lsp-restart` and `config-reload` commands and rust analyzer seems to be indexing the crate info for the workspace but it seems as if it gets stuck when it gets to 98%. Some help to resolve this would be great.

**Note:** I also tried getting inline hints within vscode but it seems I'm not getting hints there either so this could just be a rust analyzer bug. I could also be completely missing something lol 

MacOS: 13.3.1
Helix: 23.03

<img width="382" alt="image" src="https://user-images.githubusercontent.com/20745708/234073037-7dedb775-ec3f-44b3-b7d0-7e6a8a23e9c8.png">
<img width="456" alt="image" src="https://user-images.githubusercontent.com/20745708/234073091-ee0cf8f4-71e6-436b-8fc7-7d5a6d70f054.png">
<img width="564" alt="image" src="https://user-images.githubusercontent.com/20745708/234073136-1dd1ce2c-eb30-4bd5-8d04-2163b1ec6947.png">

### Reproduction Steps

I tried this:

1. `hx` in my current workspace
2. navigate to any `*.rs` file within the workspace
3. I see that rust analyzer is indexing crate info but doesn't display it in my editor for that file

I expected this to happen: Inline hints from rust analyzer 

Instead, this happened: no inline hints

### Helix log

<details><summary>~/.cache/helix/helix.log</summary>

```
2023-04-24T13:20:00.809 helix_lsp::transport [ERROR] err: <- StreamClosed
```

</details>

### Platform

MaxOS

### Terminal Emulator

Iterm2

### Helix Version

23.03 (3cf03723)

**Comment by pascalkuthe** [comment]
This is a rust analyzer bug relates to your specific project. Usually if its reproducible in vscode and related to the LSP it's not a helix issue. You should try to report this upstream to the rust-analyzer repo directly.

**Comment by Eliascm17** [comment]
Yeah I just realized this as I opened a new project directory and instantly got inline hints. Thank you!
