### ISSUE TITLE
Can I use default terminal colors?

### ISSUE THREAD

**Issue by Siilwyn** [helix-editor/helix#687]
#### Describe your feature request

It would be great to be able to use default terminal colors, I've set a nice 16 color palette in my terminal which e.g. vim follow however it seems that helix uses a custom theme by default. Even if not by default it would be nice to be able to change a setting to allow this behaviour.

**Comment by coxackie** [comment]
that would be awesome. I have set up alacritty exactly how I like it, and would like to keep the same colour scheme for helix.

**Comment by sudormrfbin** [comment]
The 16 color palette is [already defined in the code](https://github.com/helix-editor/helix/blob/f9375f449c8b7bbf792c88b89903fe38d524f2e5/helix-view/src/graphics.rs#L217-L237), we just need a proper way to map it from the theme config file to the actual theme (currently everything is parsed as a hex value).

**Comment by archseer** [comment]
We can use color names: `'blue'`, `light-blue` etc

**Comment by sudormrfbin** [comment]
I'll take a stab at it then :)
