### ISSUE TITLE
toggle-whitespace command and associated keymap

### ISSUE THREAD

**Issue by siddharthagudgunti** [helix-editor/helix#688]
#### Describe your feature request

Similar to vim's 'set list!' and kakoune's show-whitespace, helps to quick check the line-endings, tabs, spaces etc.

**Comment by siddharthagudgunti** [comment]
There may be co-relation between this and #1068

**Comment by the-mikedavis** [comment]
with #1802 merged: `:set whitespace.render all` and `:set whitespace.render none`
