### ISSUE TITLE
Share the system clipboard by default.

### ISSUE THREAD

**Issue by buddhiko1** [helix-editor/helix#6894]
Hello,

Recently I have been thinking about switching from Neovim to Helix, and I really like Helix. Thanks to all the contributors for their hard work. I have some experience in interaction design, and I want to share my opinion on the cut/paste function.

If there's one badly designed feature of Vim, it's definitely the cut/paste functionality. Cut/paste is a frequently used operation, and defaulting to not sharing the system clipboard is the easiest way to create barriers to this operation. Unfortunately, helix inherits this default setting from Vim. Of course, we can configure it ourselves, but it takes considerable time and effort, whether in Vim or Helix.

The following is my own configuration.
```
[keys.normal]
"y" = "yank_joined_to_clipboard"
"Y" = ["extend_line_below", "yank_joined_to_clipboard"]
"p" = "paste_clipboard_after"
"d" = "delete_selection"
"D" = ["extend_line_below", "delete_selection"]

[keys.select]
"y" = "yank_joined_to_clipboard"
"p" = "paste_clipboard_after"
"d" = ["yank_joined_to_clipboard","delete_selection"]
```

There are five types of cut/paste operations:
A. Across instances:
   1. Editor -> Other app.
   2. Other app -> Editor.
   3. Editor instance 1 -> Editor instance 2.  

B. Within the same instance:

   4. File A -> File B
   5. File A -> File A

If the system clipboard is shared, all of these operations can be smoothly executed just like any other software. 
If it is set to not share the system clipboard by default, scenarios 1/2/3 cannot be executed smoothly.

Are there any benefits to defaulting to not sharing the system clipboard? I can't think of any. 

The downsides, however, are obvious:
1. It requires users to spend time and effort configuring it, which is not easy if you've ever tried it.
2. It requires three additional shortcut keys. Using so many shortcut keys for a simple everyday operation is itself a problem.
3. It unnecessarily breaks down a simple operation that conventionally happens in one step into two stages.

**Comment by ghc0** [comment]
It's your issue, it's not the issue of Helix. 

Read the lovely doc and you'll find that "space y/p" is for sharing the system clipboard.  => https://docs.helix-editor.com/keymap.html

Make your reply more concise next time, thank you.

**Comment by David-Else** [comment]
> Are there any benefits to defaulting to not sharing the system clipboard? I can't think of any.

The only thing I can think of is that the user needs to install a clipboard provider like `xclip`, so it technically adds another dependency... but in the real world they are going to need to do this anyway as who doesn't use Helix with other apps?

Seems like a great idea, would be interested in who is against it and why. @ghc0 Not sure what you are saying.
