### ISSUE TITLE
Add a way to extend `file-types` key in languages.toml

### ISSUE THREAD

**Issue by benjamineskola** [helix-editor/helix#6896]
Currently if I want to add a new filetype pattern for a language it seems that I have to duplicate the entire existing `file-type` setting from the base `languages.toml` into `~/.config/helix/languages.toml` and then add my own in addition to that. That seems less than ideal: some filetypes have a relatively long list to begin with which clutters the user config, and if the base setting is changed in a future version the user config needs to be updated each time. I'd like instead to be able to specify new extensions while retaining the ones set in the base config.

Merging the two lists would be one way. However there's obviously a downside in simply appending to the list, as a user might also want to set the list in order to override the base setting (i.e., remove something that exists in the base config's list). I'm not sure how common that latter situation might be.

Otherwise perhaps an `additional-file-types` key that would be merged into the `file-types`?

**Comment by pascalkuthe** [comment]
closing in favor of #10389
