### ISSUE TITLE
Resizing a bunch causes index out of bounds

### ISSUE THREAD

**Issue by Kethku** [helix-editor/helix#69]
![image](https://user-images.githubusercontent.com/3323631/120551984-86017b00-c3ab-11eb-909f-41ca7f0c8ecd.png)

**Comment by IceDragon200** [comment]
Was that with or without actual content in the buffer?

**Comment by Kethku** [comment]
crashes reliably with or without.

**Comment by RLHerbert** [comment]
I get the (exact, as far as I can tell) same crash when repeating an insert with "."

**Comment by Kethku** [comment]
I can't repro that. Both going into insert mode and holding '.' and leaving insert mode and repeating that insert by holding '.' from normal mode do not reproduce the problem for me.

**Comment by RLHerbert** [comment]
> I get the (exact, as far as I can tell) same crash when repeating an insert with "."

Actually, I get a number slightly smaller than u16::MAX for the index.

> I can't repro that. Both going into insert mode and holding '.' and leaving insert mode and repeating that insert by holding '.' from normal mode do not reproduce the problem for me.

Sorry, meant replace, not insert.

**Comment by Kethku** [comment]
I don't understand. Do you have a minimal set of keystrokes that repro?

**Comment by IceDragon200** [comment]
Strange I couldn't reproduce either problems, I use arch linux and and i3wm

**Comment by Kethku** [comment]
My issue is from windows. Is there a way to log terminal events out?

**Comment by RLHerbert** [comment]
Open file -> shift+r -> "asd" -> normal mode -> '.'  ~10-20 times.

Seems to depend on the length of the buffer at the time(?). On WSL Ubuntu.

**Comment by RLHerbert** [comment]
> Actually, I get a number slightly smaller than u16::MAX for the index.

```
❯ RUST_BACKTRACE=1 hx src/main.rs
thread 'main' panicked at 'index out of bounds: the len is 4992 but the index is 65523', helix-tui/src/buffer.rs:185:14
stack backtrace:
   0: rust_begin_unwind
             at /rustc/625d5a693e4697bcafdd34fd1a38c281acabb8e9/library/std/src/panicking.rs:515:5
   1: core::panicking::panic_fmt
             at /rustc/625d5a693e4697bcafdd34fd1a38c281acabb8e9/library/core/src/panicking.rs:92:14
   2: core::panicking::panic_bounds_check
             at /rustc/625d5a693e4697bcafdd34fd1a38c281acabb8e9/library/core/src/panicking.rs:69:5
   3: helix_tui::buffer::Buffer::set_style
   4: <hx::ui::editor::EditorView as hx::compositor::Component>::render
   5: hx::compositor::Compositor::render
   6: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
   7: tokio::park::thread::CachedParkThread::block_on
   8: tokio::runtime::thread_pool::ThreadPool::block_on
   9: tokio::runtime::Runtime::block_on
  10: hx::main
```

**Comment by IceDragon200** [comment]
I got something similar:
```
thread 'main' panicked at 'attempt to subtract with overflow', helix-view/src/view.rs:147:19
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```
I was running it in dev

**Comment by RLHerbert** [comment]
Well, it's not shift+r, it's just 'a'/insert after selection. It actually doesn't seem to have to do with repeat at all. I'm getting this bug whenever the buffer length hits ~~about 93 characters~~ exceeds the terminal width. 

Testing on 0.0.8.

**Comment by archseer** [comment]
If rapidly resizing the terminal, the view tree's sizing would fall out of sync and point out of bounds. c0332bd935bb7c016278d43a526e588558a0cab1 together with #70 should fix it
