### ISSUE TITLE
Keymaps with multiple config updating commands effectively only apply the last config update/command

### ISSUE THREAD

**Issue by dejaypiii** [helix-editor/helix#6906]
If a keymap applies multiple config updating commands (e.g. set-option, toggle-option) than effectively only the last command/update gets applied.

As an example:

[keys.normal]
"#" = [":set-option whitespace.render all", ":set-option lsp.display-inlay-hints true"]

Behaviour:
On pressing "#" Helix iterates the commands and issues update events for both options to the config.
After completion it will display inlay hints but still render none of the whitespaces.
I guess in this case subsequent config updates override the updates of the previous commands.

Should it be possible to use such keymaps?

**Comment by pascalkuthe** [comment]
this will be adressed by #8853 since that will entirely change the config system and the way setting config values work
