### ISSUE TITLE
More helpful error message(s) with invalid configuration in languages.toml

### ISSUE THREAD

**Issue by Jachdich** [helix-editor/helix#6908]
When adding a new language to the `languages.toml` file, I forgot to include the `rev` tag in the source of a grammar and got this error message when running `helix --grammar fetch`:

    Error: data did not match any variant of untagged enum GrammarSource for key `grammar.source`

I've seen more cryptic errors in the past so I'll add any more that I come across. It would be very helpful to make it clearer, but I understand it's probably not a priority. I could submit a PR if that would be easier.

**Comment by pascalkuthe** [comment]
Serde is not really meant for user friendly parsing (it's more aimed at automatic serialization where errors only need to be good enough to be dissected by a developer). I dont think you can get much better errors without investing significant effort.


We want to move to a scripting based configuration in the future anyway so the toml config is just a stopgap solution. Investing significant effort into that doesn't make sense. If you find some low hanging fruit where error message can be easily improved without much effort you can open a PR but I dont think larger changes make sense here.

**Comment by Jachdich** [comment]
Thanks for the explanation, yeah if it's going to be replaced in future then I won't bother.
