### ISSUE TITLE
Language server not active for current buffer

### ISSUE THREAD

**Issue by BaptouDev** [helix-editor/helix#6914]
Hello,
I have a windows machine,
I installed helix using chocolatey, re-installed llvm, and when i run `hx --health rust`, it gives me this : 
```
hx --health rust
Configured language server: rust-analyzer
Binary for language server: C:\Users\xu12c\.cargo\bin\rust-analyzer.exe
Configured debug adapter: lldb-vscode
Binary for debug adapter: C:\Program Files\LLVM\bin\lldb-vscode.exe
Highlight queries: ✓
Textobject queries: ✓
Indent queries: ✓
```
So, in theory, auto-complete should work. But when i try to edit a rust file, there is no autocomplete. And when I use space + K, it tells me 'Language server not active for current buffer',
Thanks in advance to anyone that can help me,

**Comment by nathan-at-least** [comment]
Hi, why did you close this? If you figured out a solution, could you post it here?

I have the exact same symptoms (also for rust), and I see many tickets for "Language server not active for current buffer".

**Comment by nathan-at-least** [comment]
See also #4053
