### ISSUE TITLE
The config option `editor.file-picker.hidden` is unintuitive

### ISSUE THREAD

**Issue by zummenix** [helix-editor/helix#6926]
The option's name suggests that the file picker will show hidden files if true, but actually it is backwards. This only becomes clear from the documentation where it correctly says: `Enables ignoring hidden files`.

While I'd prefer the option's name to stay and change its meaning to be backwards, I understand that it will be a breaking change. Therefore I'd like to suggest renaming this option to something more intuitive like `ignore-hidden` or `show-hidden`.

**Comment by the-mikedavis** [comment]
See https://github.com/helix-editor/helix/issues/3086

This is probably not worth the breaking change. Eventually we want to replace the TOML configuration format and that would be a good time to make a change like this.

**Comment by zummenix** [comment]
Ah, got it. Thanks! Closing this. Although it's not clear for me what would replace the toml configuration format.
