### ISSUE TITLE
`:cd` does not respect `.helix/`

### ISSUE THREAD

**Issue by mamins1376** [helix-editor/helix#6945]
### Summary

Helix ignores per-project configuration directory (`.helix/`) if the user uses editor's `:cd` command.

### Reproduction Steps

1. Clone [reproduction repo](https://github.com/mamins1376/helix-config-ignored).
2. Do *not* `$ cd` into it. Just `$ hx` from parent directory.
3. Now `:cd` to newly cloned repo from inside the editor.
4. Open `src/main.rs`
5. `rust-analyzer` complains about missing `test` crate. This would not have happened if `.helix` in the project was respected.

To make sure this is specifically about `:cd`, just run `$ hx` from inside the project directory. No error will happen.

### Platform

Linux

### Terminal Emulator

alacritty 0.12.0 (5a728195)

### Helix Version

helix 23.03

**Comment by pascalkuthe** [comment]
Calling `:config-reload` after `:cd` shkukd fix this. J am not sure if we automatically want ti reload the config on `:cd`. It might feel intuitive but we dont automatically reload the cinfig anywhere else so adding this one special case feels odd. Especially because its currently not possible to reload global and local configuration seperatly

**Comment by mamins1376** [comment]
Wasn't aware of `:config-reload`, unblocks `:cd` for me at least. Thanks!

I was assuming that doing `:cd` is just a short hand for closing the editor, and relaunching it in the destination directory, without a loss of currently open buffers. I guess this expectation is not off the norm?

**Comment by pascalkuthe** [comment]
No `:cd` does not relaunch the editor. It only changes the cwd but keeps everything else unchanged. I am closing this issue since requiring an explicit `:config-reload` is intentional
