### ISSUE TITLE
Provide way to verify AppImages / assets integrity?

### ISSUE THREAD

**Issue by jerabaul29** [helix-editor/helix#6946]
I would like to install helix on my linux box using the AppImage method (as described for example in https://docs.helix-editor.com/install.html pre-built binaries). When doing so, I would like to be able to check the integrity / "signature" of the AppImage file I download before running it. Typically this is done in other cases I have been familiar with by checking either:

- sha256sum of the file, where the reference sha256 is obtained from a "trusted, separate" source, for example the webpage of the project, or,
- some form of "signature" on the AppImage file.

Would it be possible to provide for example the sha256sum of the AppImages corresponding to releases somewhere (ideally distributed a bit "independently" of the present GH repo, for example on the projects website), so that users can verify the integrity of their images?

**Comment by David-Else** [comment]
Try the `GitHub CLI` command line tool to download the AppImage https://cli.github.com/manual/gh_release_download, I am pretty sure that forces you to login and be authenticated https://github.com/cli/cli/discussions/3820, but you would need to double check that.

**Comment by jerabaul29** [comment]
Thanks for the advice :) . A couple of thoughts:

- that requires me to install "yet another cli" (for now I use plain git), I would like to avoid this if possible :) .
- would this give the same kind of guarantee as checking a sha256 against a separate source? For example if some attacker takes control over the git repo to serve modified files or similar, I would not notice it? This is also the goal with a separate source with the sha256sum - have some added guarantee / additional barrier / make it harder to serve malicious files in case there is a successful attack against the GH repo for example?

**Comment by David-Else** [comment]
I agree with not wanting yet another CLI, but I like GitHub CLI so have it anyway.

I would imagine the most likely attacks would be:

1. A Helix dependency getting compromised.
2. A new Helix contributor sneaking in malicious code, but that is unlikely as there are many talented and regular code reviewers on the job here.
3. Someone gets control of this Github repo and puts out a modified version of Helix that looks official.
 
If 1 and 2 happen then no checksum will help you, if 3 happens then having a checksum on the official (not GitHub) Helix site would save you as the attacker would not have access to change that. Vigilant people such as yourself could always compare the checksum and sleep soundly.

It looks like you would be much happier using an official Linux repository version, then at least an independent organization has vetted it and can ring the alarm bells if something bad is reported.

It seems *very* unlikely anyone is going to target Helix as it is so niche, unless maybe a Neovim user is driven insane by spending years on their configuration and upon seeing Helix's zero config he decides to enact some kind of demented revenge on its users :)

Given Helix's niche market, it's unlikely to be a target for attacks. However, there's a slim possibility that a Neovim user, frustrated with years of configuration, may feel envious of Helix's zero-config approach and decide to enact some kind of demented revenge on its users :)

**Comment by jerabaul29** [comment]
Exactly regarding your analysis of 1 vs 2 vs 3 :) . The annoying thing using a Linux repo is that:

- if I use an official one, it will likely lag far behind the latest release
- if I use a custom PPA, then "who do I actually trust"? Then there is no more trust than the AppImage (except I just added a PPA and can potentially grab some stuff from there in my updates without noticing if I am not careful, which I do not like)

So I would like to use the AppImage method to install, but with the separate sha256sum, so that I am at least protected against 3. :) .

Btw (but that will go into another issue), I will run the AppImage, even after having checked its signature, with something like:

```
$ firejail --nosound --novideo --net=none --whitelist=~/Desktop/Current --appimage ./helix-23.03-x86_64.AppImage
```

I like to try to be a bit careful / security aware ^^ :) .

**Comment by pascalkuthe** [comment]
The website is controlled by a github repo (github pages) that is owned by the helix-editor organization. So if one of the maintainers/github are compromised the website is also comprised. You are protected from mim attacks by `https`. If that is compromised the website and github are compromised too.

The reason other projects provide checksums is that they host their release assets elsewhere (on potentially third party mirrors). There checksums make sense but for helix there is no additional security provided whatsoever and setting up the release CI to generate checksums is tedious.
