### ISSUE TITLE
Please consider allowing mouse activation of buffers when clicking the buffeline title

### ISSUE THREAD

**Issue by AddictArts** [helix-editor/helix#6950]
As the title says when already using the mouse within helix, example changing cursor location or scrolling, it is expected behavior that a file title can be clicked to activate. Thanks

Note: Helix has some mouse interaction, just want to add a little more. It is possibly an easy implementation.

**Comment by gabydd** [comment]
duplicate of https://github.com/helix-editor/helix/issues/4942

**Comment by AddictArts** [comment]
Oops, thanks glad I'm not alone in this thought, sorry for the dup.
