### ISSUE TITLE
lsp formatting options

### ISSUE THREAD

**Issue by megheaiulian** [helix-editor/helix#696]
`helix` passes defaults instead of the actual document options (indent sytyle?) to lsp in
https://github.com/helix-editor/helix/blob/fa4caf7e3d43a40073f6966d37f529d5197bd840/helix-view/src/document.rs#L394
If the document's format is different than the defaults it results in wrong formatting done by the lsp.

**Comment by archseer** [comment]
Slight improvement: c18de0e8f001041e234b2b9bb0f8fea122858ad3

**Comment by kirawi** [comment]
I think this can be closed since the original reason for the issue was resolved, and formatting config is done via the `config.format` subtable per language server.
