### ISSUE TITLE
Prevent Helix from scrolling too far past the EOF

### ISSUE THREAD

**Issue by pascalkuthe** [helix-editor/helix#6966]
### Discussed in https://github.com/helix-editor/helix/discussions/6965

<div type='discussions-op-text'>

<sup>Originally posted by **dist1ll** May  4, 2023</sup>
Between v22.12 and v23.03, the scrolling behavior at the bottom of a file changed. 
 Now when I scroll to the very bottom, instead of showing only ~8 lines past the end of the file, helix allows me to scroll down almost an entire terminal-height worth of lines. 
</div>

I was able to reproduce this (tested both 22.12 and 23.3 to compare),  this an unintended side-effect of #5420 that we missed. This might be a bit tricky to solve since we only use relative positions with #5420 but I might be able to come up with a heuristic that provides good performance regardless

**Comment by pascalkuthe** [comment]
We decided against reintroducong this. It's actually quite useful in practice to be able to scroll down

**Comment by rose-bouchayer** [comment]
Hi @pascalkuthe, I do understand that it's a useful feature but could this behaviour be configurable please? It would make everyone happy by letting users choose what they prefer.
