### ISSUE TITLE
Chaining the commands half_page_down+align_view_center doesn't work correctly

### ISSUE THREAD

**Issue by HansMartinJ** [helix-editor/helix#6967]
### Summary

I bind this operation to a key, e.g. "C-d" = ["half_page_down","align_view_center"]. 

Now I expect the cursor to go half page down then align the view to center. What actually happens is that the cursor moves around 5 to 10 places down instead of the required amount to go half a page down. Then it centers as expected.

### Reproduction Steps

 

I tried this:

1. `hx`
2. config-open
3. "C-d" = ["half_page_down","align_view_center"]. 
4. config-reload
5. type C-d

I expected this to happen:
cursor moves required amount to get down half a page, then centers

Instead, this happened:
cursor moves 5-10 places down, then centers

### Helix log

<details><summary>~/.cache/helix/helix.log</summary>

```
please provide a copy of `~/.cache/helix/helix.log` here if possible, you may need to redact some of the lines
```

</details>

### Platform

macOS

### Terminal Emulator

wezterm 20230408-112425-69ae8472

### Helix Version

helix 23.03 (3cf03723)

**Comment by pascalkuthe** [comment]
You misunderstand `half_page_down`. The command doesn't move the cursors half a page lower (in which case it would do what you want) but instead, it scrolls the view top half a page down. The cursor might not move at all (if the cursor is at the bottom of the screen) or it might move more than half a page (thanks to scrolloff). So the behavior you are seeing is intentional

**Comment by HansMartinJ** [comment]
You are right!

**Comment by HansMartinJ** [comment]
As a side note, is there any way to achieve what I hoped it to do? I.e. "nnoremap C-u C-uzz" in vim?

**Comment by mrfoxrocket** [comment]
This is what worked for me: 

```
C-d = ["page_cursor_half_down", "align_view_center"]
C-u = ["page_cursor_half_up", "align_view_center"]

```
