### ISSUE TITLE
`apply_workspace_edit` panic on Windows due to inconsistent letter case in file path

### ISSUE THREAD

**Issue by pppKin** [helix-editor/helix#698]
HI! Performing a code action on Windows would panic:
```
thread 'main' panicked at 'assertion failed: `(left == right)`
  left: `Url { scheme: "file", cannot_be_a_base: false, username: "", password: None, host: None, port: None, path: "/C:/path/to/project/src/main.rs", query: None, fragment: None }`,
 right: `Url { scheme: "file", cannot_be_a_base: false, username: "", password: None, host: None, port: None, path: "/c:/path/to/project/src/main.rs", query: None, fragment: None }`', helix-term\src\commands.rs:2486:21
stack backtrace:
   0: std::panicking::begin_panic_handler
             at /rustc/50171c310cd15e1b2d3723766ce64e2e4d6696fc\/library\std\src\panicking.rs:517
   1: core::panicking::panic_fmt
             at /rustc/50171c310cd15e1b2d3723766ce64e2e4d6696fc\/library\core\src\panicking.rs:101
   2: core::fmt::Arguments::new_v1
             at /rustc/50171c310cd15e1b2d3723766ce64e2e4d6696fc\/library\core\src\fmt\mod.rs:348
   3: core::panicking::assert_failed_inner
             at /rustc/50171c310cd15e1b2d3723766ce64e2e4d6696fc\/library\core\src\panicking.rs:183
   4: core::panicking::assert_failed
   5: helix_term::commands::apply_workspace_edit
...
```

Notice the upper case ```C:``` and lower case ```c:``` cause this.
Even though NTFS can be configured as case-sensitive, and [Windows CreateFile API provides a flag to enable posix behavior, eg, case-sensitive file path](https://docs.microsoft.com/en-us/windows/win32/api/fileapi/nf-fileapi-createfilea#FILE_FLAG_POSIX_SEMANTICS), I don't think they are widely used. Most people on windows seem to just stick with the default case-insensitive file system, and developers tend to do the same. So do we just convert that paths to all lower case on Windows before checking them or do we provide an entry in configuration, or do we detect what file system helix is working in and check accordingly?

**Comment by archseer** [comment]
@gbaranski looks like your assert triggered: https://github.com/helix-editor/helix/blob/7e1123680f474bff5113db189f63ca7f948781a5/helix-term/src/commands.rs#L2486

Note: I don't think this code should use `current!` and instead look up `editor.document_by_path()`
