### ISSUE TITLE
Add `formatter` to `hx --health`

### ISSUE THREAD

**Issue by kirawi** [helix-editor/helix#6992]
https://github.com/helix-editor/helix/blob/5ae30f1993180b2c043d13f83e16f8647f7ff129/helix-term/src/health.rs needs to be modified.

**Comment by Sammo98** [comment]
Apologies, I missed the above PR when I created mine, first attempt at OSS. I believe the above PR though would not show the formatter column when `hx --health` is run and only when `hx --health <lang>` is run.
