### ISSUE TITLE
Ubuntu 20.04 Install

### ISSUE THREAD

**Issue by rileyhawk1417** [helix-editor/helix#700]
Hi has anyone tried installing on a ubuntu based distro without using brew?
When I tried compiling from source came up Rust reported error E0658, so am not sure whats going on here. The pre-built binaries seem fine and run without any issue though.

**Comment by kirawi** [comment]
I'm guessing you're using an old version of Rust? What does `rustc --version` say?

**Comment by rileyhawk1417** [comment]
@kirawi its 1.51.0 is it old? This is the first time am using rust

**Comment by rileyhawk1417** [comment]
Let me try remove and install 1.54 just visited the docs.

**Comment by rileyhawk1417** [comment]
Thanks for the heads up @kirawi seems like my system used the ubuntu repository which is on 1.51. Installing from rust source was better managed to install helix. TIme to give it a test run :)
