### ISSUE TITLE
Change behaviour of Nj and Nk combinations, with enabled option soft-wrap 

### ISSUE THREAD

**Issue by mmaslyukov** [helix-editor/helix#7021]
Current behavior might be according to design, but for me, it is pretty frustrating.

Precondition:
- The soft-wrap is enabled
- Cursor is placed at `280:1`
- Switch to the SELECT MODE*
![image](https://github.com/helix-editor/helix/assets/13781447/21db531f-752b-49bb-8b5b-e15aa3ac4b4b)

Action:
- Type `3j`

Result according to the current implementation:
![image](https://github.com/helix-editor/helix/assets/13781447/676d19f8-981f-4997-8ae0-fe758b1d280f)

However, logically to expect this:
![image](https://github.com/helix-editor/helix/assets/13781447/fe0ea317-f261-40f0-81f9-d63b323ee776)
At least it makes sense if take into account relative line numbers

*The same behavior in the NORMAL MODE too

It's a small fix in a few lines, and if maintainers agree with my vision I can make a Pull request

**Comment by the-mikedavis** [comment]
You can use the count with `gj` and `gk` to move up/down actual lines rather than visual lines

**Comment by pascalkuthe** [comment]
See https://github.com/helix-editor/helix/issues/6819#issuecomment-1515030848

**Comment by mmaslyukov** [comment]
Hi @the-mikedavis and @pascalkuthe 

Hmm, I've got a point of having `gj` but for me, it seems like an artificial replacement of canonical `1j`. My proposition was to keep `j` and `k` for navigation including wrapped lines, but `Nj` make explicit line navigation.
One out of four changes as an example:
```diff
fn move_visual_line_up(cx: &mut Context) {
    move_impl(
        cx,
-        move_vertically_visual,
+        if cx.count.is_none() {
+            move_vertically_visual
+        } else {
+            move_vertically
+        },
         Direction::Backward,
         Movement::Move,
     )
```

**Comment by pascalkuthe** [comment]
See also https://github.com/helix-editor/helix/wiki/FAQ#can-the-jk-bindings-be-changed-to-ignore-soft-wrapping-when-using-a-count-like-3j

I am aware and you are far from the first person to propose this. It was discussed during the original soft wrap PR. Helix exposes the fundamental movements as core commands. Otherwise, it would not be possible to ever use counts with soft wrapped lines.  Once we have a scripting language/plugin system its easy to add the command you proposed but if we change the core commands as you suggest the inverse is no possible anymore

**Comment by mmaslyukov** [comment]
Thank you for the detailed explanations, I agree that differentiating the logic of `j/k` and `gj/gk` brings more flexibility. 
Although I'm just thinking if there was a configuration entry in `config.toml`, that defined behavior of `j/k`, something like "classic/wrapped/mixed", it might find fans out there. 
I'm not insisting at all, just thinking out loud.

Thank you for your time spent answering the same question again.
