### ISSUE TITLE
A`leading` and/or `trailing` value for the `editor.whitespace.render` configuration option.

### ISSUE THREAD

**Issue by RGBCube** [helix-editor/helix#7037]
Currently, when `editor.whitespace.render` is set to `all`, all of the whitespace gets represented as the character provided regardless of position. Most editors like VSCode, InteliJ IDEA and some NeoVim plugins don't do this and only represent the leading and trailing whitespace with the given character.

What I'm proposing is making the `editor.whitespace.render` configuration option allow values `leading`, `trailing` and a combination of them, perhaps `leading+trailing` which only represents leading and trailing whitespace as the given character.

**Comment by tqwewe** [comment]
Duplicate of https://github.com/helix-editor/helix/issues/2719

**Comment by RGBCube** [comment]
> Duplicate of https://github.com/helix-editor/helix/issues/2719

I'll close this in favour of that issue
