### ISSUE TITLE
Apostrophe (') while editing MATLAB not interpreted correctly.

### ISSUE THREAD

**Issue by handdara** [helix-editor/helix#7058]
### Summary

In MATLAB the apostrophe can be used both to denote a string as well as perform conjugation/transposition on Matrices. The latter is not recognized in the syntax highlighting and leads to odd highlighting. 

This is a common problem. [Here](https://github.com/sublimehq/sublime_text/issues/3155) is the same issue in another editor.

### Reproduction Steps

This is very easy to reproduce, simply load up the following code in helix.

```matlab
        K = [A+ Kse,     G   ;
                G.' ,  H + Kbt];
            
        nb = Kse*(v - [0;0;1]);
        mb = Kbt*u;
```
And you should get something that looks like
![image](https://github.com/helix-editor/helix/assets/24214913/b5d678c4-bdec-4f65-8c47-c0af9526dac5)

### Platform

linux

### Terminal Emulator

zellij

### Helix Version

helix 23.03 (c6228825)

**Comment by gabydd** [comment]
Closed by https://github.com/helix-editor/helix/pull/7388 See https://github.com/helix-editor/helix/issues/7386#issue-1763456264
