### ISSUE TITLE
Enhancement: allow a way to copy a diagnostic to clipboard

### ISSUE THREAD

**Issue by luccahuguet** [helix-editor/helix#7062]
I could not find a way to copy diagnostics to clipboard, not even selecting the diagnostic text was possible

and I think this feature could be very useful for many, since there lots of cases where one needs to copy one diagnostic and search it on google or similar

**Comment by kirawi** [comment]
https://github.com/helix-editor/helix/pull/3786

**Comment by kirawi** [comment]
Closed by https://github.com/helix-editor/helix/pull/9640
