### ISSUE TITLE
Panic in diff gutter worker

### ISSUE THREAD

**Issue by ZetaNumbers** [helix-editor/helix#7068]
### Summary

I am editing my https://github.com/ZetaNumbers/tigerbeetle-rs source code at `/src/lib.rs`. I enter insert mode via `i` key, then try to add a newline. And then this happens: 

![Снимок экрана 2023-05-19 в 00 41 29](https://github.com/helix-editor/helix/assets/53300196/b9ada011-8d0b-45bf-93d5-f28d8b9fec4f)

Corrupted panic message:

```
thread 'tokio-runtime-workertry_into()                                           , /Users/zeta/.cargo/registry/src/index.crates.io-6f17d22bba15001f/ropey-1.6.0/src/iter.rs:1371:25
stack backtrace:           .expect("address length is greater than `u32::MAX`"),
   0: _rust_begin_unwinconcurrent_packets,
   1: core::panicking::0,
   2: core::str::sl  e Some(on_completion),
   3: core::str::sl);e
   4: ropey::iter::ifulet Some(c) = NonZe_oU32::new(status) {
   5: <ropey::slice :  return Err(ClientCreationError(c)); y::slice::RopeSlice>>::eq
   6: imara_diff::i}         erner<T>::intern
   7: <alloc::vec::Ok(Self { s alloc::vec::spec_extend::SpecExtend<T,I>>::spec_extend
   8: helix_vcs::diff::raw,                    Lines::update_doc
   9: tokio::runtim  : pool: Mutex::new(pool),
  10: tokio::ru t  }) scheduler::multi_thread::worker::block_in_place
  11: helix v  } diff::worker::DiffWorker::run::{{closure}}
  12: t k  } loom::std::unsafe_cell::UnsafeCell<T>::with_mut
  13: t} io::runtime::task::core::Core<T,S>::poll
  14: t                               arness<T,S>::poll
  15: tokio::runtimee:dcheduler::multi_thread::worker::Context::run_task
  16: tunsafe impl Sync for Client {} _thread::worker::Context::run
  17: t                       s::ScopedKey<T>::set
  18: timpl Drop for Client {e  :multi_thread::worker::run
  19: tokiofnrdrop(&mutaself) {
  20: tokio :  unsafe { sys::tb_client_deinit(self.raw) }
  21: t k  } runtime::blocking::pool::Inner::run
note: Some details[+]e omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.                                                                                                                                                     2
```

Now i am stuck in insert mode and this corrupted state, i cannot leave with `ESC:q!` or someting, `ESC` is inserted too as a strange ansi like sequences. So i exit the terminal via `Cmd-Q`.

This happens even if i `:lsp_stop`.

### Reproduction Steps

I tried this:

1. `hx src/lib.rs`
2. `i` key then Enter key

I expected this to happen:

Added a newline

Instead, this happened:

Editor breaks

### Helix log

<details><summary>~/.cache/helix/helix.log</summary>

```2023-05-19T01:03:15.211 helix_view::clipboard [DEBUG] Using pbcopy+pbpaste to interact with the system clipboard
2023-05-19T01:03:15.266 helix_view::editor [ERROR] Failed to initialize the LSP for `source.rust` { cannot find binary path }
2023-05-19T01:03:15.267 helix_view::editor [DEBUG] editor status: Loaded 1 file.
2023-05-19T01:03:15.269 helix_tui::backend::crossterm [DEBUG] The keyboard enhancement protocol is not supported in this terminal (checked in 851.375µs)
2023-05-19T01:03:15.271 helix_view::document [DEBUG] id 1 modified - last saved: 0, current: 0
2023-05-19T01:03:15.614 helix_term::application [DEBUG] received editor event: IdleTimer
2023-05-19T01:03:18.779 helix_view::document [DEBUG] id 1 modified - last saved: 0, current: 0
2023-05-19T01:03:18.958 helix_vcs::diff::worker [INFO] Diff computation timed out, update of diffs might appear delayed
2023-05-19T01:03:18.959 helix_view::document [DEBUG] id 1 modified - last saved: 0, current: 0
2023-05-19T01:03:19.342 helix_term::application [DEBUG] received editor event: IdleTimer
2023-05-19T01:03:19.344 helix_view::document [DEBUG] id 1 modified - last saved: 0, current: 0
```

</details>

### Platform

macOS 13.3.1 (a) (22E772610a)

### Terminal Emulator

alacritty 0.12.0 (5a72819)

### Helix Version

helix 23.05 (7f5940be)

**Comment by ZetaNumbers** [comment]
If i delete `.git` directory, then editor no longer breaks.

**Comment by pascalkuthe** [comment]
Looks like a crash in the diff gutter, if a worker thread crashes then the runtime crashes so the issue is not that you are unable to exit insert mode but that there is a crash

**Comment by A-Walrus** [comment]
I'm unable to reproduce. Cloned the repo, opened the file and inserted a line and it worked completely fine.

**Comment by ZetaNumbers** [comment]
> Looks like a crash in the diff gutter, if a worker thread crashes then the runtime crashes so the issue is not that you are unable to exit insert mode but that there is a crash

Disabling diff gutter with `gutters = ["diagnostics", "spacer", "line-numbers", "spacer"]` under `[editor]` in the config doesn't help.

**Comment by pascalkuthe** [comment]
It doesn't it ships it's own git implementation. And the diff is computed even if diff gutters are disabled so that's not surprising

**Comment by ZetaNumbers** [comment]
Ok, so um i have replaced my `cargo install` version (hx binary and runtime dir) with version from the github releases, ran `hx --grammar fetch`, `hx --grammar build` and now it is fixed. I guess photons are at it again, messing with my setup. 🤷‍♀️
