### ISSUE TITLE
"config" key for languages.toml is still part of documentation

### ISSUE THREAD

**Issue by ondrej-ivanko** [helix-editor/helix#7074]
Hi,

after starting helix today I noticed an error informing me, that "config" key, that I had in languages.toml file is not valid anymore. I double checked the documentation and it is still present [there](https://docs.helix-editor.com/master/languages.html) and [here](https://github.com/helix-editor/helix/wiki/How-to-install-the-default-language-servers#python---pyright)

I noticed there was a new release yesterday. Is it possible to include documentation updates for posteriority. Some of us with bleeding edge updates would love to understand what has changed and why. This was not part of release notes. Or at least I couldn't find it.

Thank you.

**Comment by pascalkuthe** [comment]
There were no breaking changes as part of the last release. There were brwan changes to the LSP configuration in the multi  LSP PR but that was merged today (so after the release)

**Comment by jonathan-raines** [comment]
Didn't config move from `language` to `language-server`. I had to update my config. An example below.

```
[[language]]
name = "ruby"
auto-format = true
formatter = { command = "rubocop", args = ["--stdin", "%", "-a", "--stderr", "--fail-level", "fatal"] }

[language-server.solargraph.config.solargraph]
diagnostics = true
```

**Comment by archseer** [comment]
Yes, the config moved on the master branch, but not the last release. Regular docs still point to the old config, and the nightly docs contain updated documentation.

**Comment by archseer** [comment]
https://docs.helix-editor.com/master/languages.html

**Comment by ondrej-ivanko** [comment]
In that case sorry for that, I didn't realize this. I'm recompiling my helix everyday from master. I'm closing the issue than.
