### ISSUE TITLE
Language configuration docs are outdated, listing `config`

### ISSUE THREAD

**Issue by LeoniePhiline** [helix-editor/helix#7081]
### Summary

Docs at https://docs.helix-editor.com/master/languages.html#language-configuration are outdated.

### Reproduction Steps

- `config` is in config, but no longer in https://github.com/helix-editor/helix/blob/master/helix-core/src/syntax.rs#L76-L142 

### Context

`Add support for multiple language servers per language` https://github.com/helix-editor/helix/pull/2507

### Helix log

Startup error:
```
Bad language config: unknown field `config`, expected one of `name`, `language-id`, `scope`, `file-types`, `shebangs`, `roots`, `comment-token`, `text-width`, `soft-wrap`, `auto-format`, `formatter`, `diagnostic-severity`, `grammar`, `injection-regex`, `language-servers`, `indent`, `debugger`, `auto-pairs`, `rulers`, `workspace-lsp-roots`
in `language`

Press <ENTER> to continue with default language config
```

### Platform

Linux

### Terminal Emulator

Konsole

### Helix Version

ff442eecd054e67081158ef2f0eeab0ed9156ca5

**Comment by pascalkuthe** [comment]
> It's still here in the docs, in the typescript example : https://docs.helix-editor.com/languages.html#language-server-configuration
> 
> Docs seem not to have updated yet on the website.
> 
> Also what is the migration advice? I still want to pass some config params...

You are looking at the stable docs for 23.5. The multi LSP PR was merged after 23.5 and therefore only affects the master branch. The new config is documented in the master docs

**Comment by atagen** [comment]
>  The new config is documented in the master docs

But this doesn't cover migration, and unless I am misreading the new config doesn't include the `config` key we previously used to feed custom keys to the LSP.

For example,
```
[[language]]
name = "rust"

[language.config]
[language.config.cargo.buildScripts]
enable = true

[language.config.check]
command = "clippy"

[language.config.procMacro]
enable = true
```

This allows Rust to expand proc macros and run build.rs before parsing, which is critical for use of certain crates such as Tonic.

Could you advise how we can continue to use such keys in the new config format? If it is possible at all it is not obvious from the new docs.

**Comment by gabydd** [comment]
every part that says ``language.config`` should be ``language-server.rust-analyzer.config`` and you also don't need the
```rs
[[language]]
name = "rust"
```
anymore cause you configure the servers individual not by language anymore
