### ISSUE TITLE
Special env vars

### ISSUE THREAD

**Issue by uncomfyhalomacro** [helix-editor/helix#7105]
Hello. Long time helix user here. Not sure if this is in the scope of the project but I want helix to be able to have *special environmental variables*. This special environmental variables are quite helpful in creating scripts or help configure LSPs in `language.toml`. Kakoune does this. For example. with `kak_buffile`, an environmental variable that gives the whole path to the buffer or file, allows me to versatile scripts e.g. sending the buffer file to another kakoune instance. This also allows me to enhance my LSP experience with Julia with `kak-lsp` as seen in https://github.com/kak-lsp/kak-lsp/blob/52197dde1a1c5e997a3ad989a8dfdd8017056a3b/kak-lsp.toml#L168-L170. This way, if I open a file where I am *not within the root of the project*, the `kak_buffile` is an env var that allows me to get the full path to the project.

Not sure if there were any plans for this. But if it is okay to implement, will you give me a try to contribute?

**Comment by the-mikedavis** [comment]
This is already being worked on in https://github.com/helix-editor/helix/pull/6979 for command expansions and after that there is https://github.com/helix-editor/helix/pull/5626.

**Comment by uncomfyhalomacro** [comment]
Ah that's cool! Closing since this is a duplicate
