### ISSUE TITLE
Colorscheme Issues, FG and BG Swapped

### ISSUE THREAD

**Issue by 4tlc** [helix-editor/helix#7122]
### Summary

I upgraded to 23.05 and went back to editing and found that the fg and bg were swapped for most themes themes and some types of text. The text where I encountered the issue most is on comments but it exists in other places as seen in the image below.

Here is a screenshot:
<img width="285" alt="image" src="https://github.com/helix-editor/helix/assets/40186632/d5c70129-63e1-45fa-ac9c-adcc2f7dfff9">

### Reproduction Steps

I removed both my tmux and helix configuration files and the issue still existed so I believe it should work without any reproduction steps. Just open a file in tmux and set the theme to everforest_dark for example.

### Helix log

<details><summary>~/.cache/helix/helix.log</summary>

```
2023-05-23T11:39:08.793 helix_view::theme [WARN] Theme: malformed hexcode: statusline1
2023-05-23T11:39:08.793 helix_view::theme [WARN] Theme: malformed hexcode: statusline2
2023-05-23T11:39:08.793 helix_view::theme [WARN] Theme: malformed hexcode: statusline1
```

</details>

### Platform

macOS

### Terminal Emulator

Alacritty

### Helix Version

helix 23.05

**Comment by kirawi** [comment]
https://github.com/helix-editor/helix/issues/3099

**Comment by 4tlc** [comment]
None of those solutions are working. I know it's not really a helix issue now though.

Is there a way to just disable all italics, I wouldn't want them anyways.

**Comment by 4tlc** [comment]
Sorry did not mean to close wasn't sure how the interface worked.

I went to alacritty config and set it to not render italics but the issue still exists. Is there a way to either tell tmux or helix to render italics as normal text?

**Comment by kirawi** [comment]
You can disable italics in the theme you're using.

**Comment by 4tlc** [comment]
How? Do I have to edit the original theme file? Where are they held?

**Comment by kirawi** [comment]
https://docs.helix-editor.com/themes.html

**Comment by 4tlc** [comment]
Couldn't fin it on my system so I just copied over from [Helix/runtime/themes](https://github.com/helix-editor/helix/tree/8e2660b5cc86266f90926aefe1470f48c801f8bc/runtime/themes) to a custom theme. Deleted the italic styling though and everything works.

Thank you
