### ISSUE TITLE
Provide a mechanism to add selection to search and maintain selection status

### ISSUE THREAD

**Issue by dylrich** [helix-editor/helix#713]
#### Describe your feature request

I couldn't find a similar issue or workaround, apologies if this has already been brought up before!

I am looking to emulate Sublime Text's "Quick Add Next" functionality (Control-D) in Helix. What I'd like to do is have a word selected, then tap a button and have the next occurrence of that word get added to my selection. I can kinda get there today with `*` followed by `N`, but unfortunately when I hit `*` it moves my cursor to the next occurrence of the word without keeping it as part of my selection.  This makes it tricky  to build my selections interactively  -- ideally `*` would  "create" the search with my current word, but not advance the cursor, allowing me to `N` as many times as a I need without having to go through the whole document to get back to the selection that I wanted to use to start the search.

Somewhat unrelated to the above but it'd also be nice to have a keybind to remove the current word from the selection for when mistakes were made while selecting.

Also want to say thank you for making such a wonderful text editor; I build nightly and have been using Helix as my daily driver at work for a few months now!

**Comment by Omnikar** [comment]
I mentioned this on Matrix a while ago; I guess it still hasn't been addressed.  
https://matrix.to/#/!zMuVRxoqjyxyjSEBXc:matrix.org/$MHufh-7FyoqmvymnRSck0Dj429brTM7XnOwXUOPKC3c?via=matrix.org&via=tchncs.de&via=gruenhage.xyz

**Comment by Omnikar** [comment]
Oh, it's been addressed, just as part of a bigger unmerged PR.  
https://github.com/helix-editor/helix/pull/211/files#diff-d782c07f22492bcae17333aba5dc5b840fb30317727e71267ebf4863f84787fdL1105

**Comment by Omnikar** [comment]
@archseer could this maybe be added separately right now? It's such a simple change, and the current behavior is pretty annoying.

**Comment by archseer** [comment]
Done in https://github.com/helix-editor/helix/commit/3426285a6341702ace35817d38cefd2bb8b16437

> Somewhat unrelated to the above but it'd also be nice to have a keybind to remove the current word from the selection for when mistakes were made while selecting.

This would be similar to `<a-space>` in kakoune?

- `<space>` drops all selections but the main selection (`space+space` in helix, but I'm experimenting with moving it to `esc`)
- `alt+<space>` drops the main selection, keeping all other selections (no equivalent in helix yet)

> Also want to say thank you for making such a wonderful text editor; I build nightly and have been using Helix as my daily driver at work for a few months now!

That's great! 🎉 It's been amazing to see daily users pop up lately.

**Comment by dylrich** [comment]
> 
> Done in [3426285](https://github.com/helix-editor/helix/commit/3426285a6341702ace35817d38cefd2bb8b16437)
> 

Thanks so much for the fix! I am using it now and it feels much better to use.

> > Somewhat unrelated to the above but it'd also be nice to have a keybind to remove the current word from the selection for when mistakes were made while selecting.
> 
> This would be similar to `<a-space>` in kakoune?
> 
>     * `<space>` drops all selections but the main selection (`space+space` in helix, but I'm experimenting with moving it to `esc`)
> 
>     * `alt+<space>` drops the main selection, keeping all other selections (no equivalent in helix yet)
> 

Yes, I am looking for the equivalent of `alt+<space>` -- that would allow me to fix selection mistakes without having to rebuild the whole selection.
