### ISSUE TITLE
Use dev dependency formatter instead of one in PATH

### ISSUE THREAD

**Issue by ssiltanen** [helix-editor/helix#7136]
https://github.com/helix-editor/helix/wiki/External-binary-formatter-configuration states
> Helix can use external formatting programs available in the system $PATH.

However, this forces users to use the same version of the formatter in all projects. Instead we should support using the formatter provided by the project dependencies, eg. devDependency in typescript/javascript. This would allow us use the same version formatter as the rest of the developers in the repo without any extra tricks.

**Comment by archseer** [comment]
You can already accomplish this by adding a per project config in a .helix folder. Each language is unique and we don't intend to start parsing dependency files and config files.

**Comment by ssiltanen** [comment]
Another option that seems to work is to change the "prettier" command to npx and pass prettier as the first argument.

```
[[language]]
name = "javascript"
formatter = { command = "npx", args = ["prettier", "--parser", "typescript"] }
auto-format = true

[[language]]
name = "typescript"
formatter = { command = "npx", args = ["prettier", "--parser", "typescript"] }
auto-format = true

[[language]]
name = "tsx"
formatter = { command = "npx", args = ["prettier", "--parser", "typescript"] }
auto-format = true
```

This seems to work without a global prettier when it is installed in repo. However, now when closing the editor after editing .helix/languages.toml is slow and gives a timeout error:
> Error: Timed out waiting for language servers to shutdown.

**Comment by gabydd** [comment]
> This seems to work without a global prettier when it is installed in repo. However, now closing the editor after editing .helix/languages.toml is slow and gives a timeout error:

That's a known issue with the toml language server which the fix for should land in the next release.

Using npx or some other tool to run dependencies for your language is definitely the correct solution to this issue in my opinion
