### ISSUE TITLE
Getting this error event with an empty languages.toml configuration

### ISSUE THREAD

**Issue by aliade-consid** [helix-editor/helix#7137]
```
Async job failed: protocol error: InternalError: Request textDocument/codeAction failed with message: Cannot read properties of undefined (reading 'useFlatConfig')

```

Upon "SPC-a" which should show code actions I get this error instead, even if languages.toml is empty.

**Comment by gabydd** [comment]
It would be helpful to have more context here, such as which language and language server this is, some logs (you can see those with ``:log-open``) and which version of helix you are using
