### ISSUE TITLE
Editor crashes when gutters.line-numbers.min-width is too large

### ISSUE THREAD

**Issue by gyreas** [helix-editor/helix#7154]
### Problem
When I set the gutters' line width using `:set gutters.line-numbers.min-width 477`, the editor crashes (or more correctly, Rust panics) spitting out `index out of bounds` error.

### Reproduce
I'm guessing the array's, or whatever is used, size is dependent upon the host system, so just try some absurd number, say 123456.

### Outcome
Same panic message as above

### Potential fix
- the input can be truncated to less than the maximum allowed size should it be beyond that threshold
- then, the user is alerted to such illegal use (and possibly given a knock on the head)*

### Version
hx 23.05 (multi-lsp incl.)

### Host OS
- Fedora 37
- I don't remember the kernel version but it's >6

**Comment by kirawi** [comment]
https://github.com/helix-editor/helix/blob/3a8592abdb9f30c7ebb74f10fa5127e754d18bc6/helix-view/src/gutter.rs#L216

This needs to be bounded to the width of the terminal (`view.rect.width`).

**Comment by gyreas** [comment]
How do I invoke a red message at cmdline for complaints to the user?

**Comment by gyreas** [comment]
How do I invoke a red message at cmdline for complaints to the user?

**Comment by kirawi** [comment]
I'm not sure if a message should be returned because I could imagine the bounding also happening when the terminal is being resized.

**Comment by gyreas** [comment]
Command line toggling, yes. It'll provide a good UX.

**Comment by kirawi** [comment]
https://github.com/helix-editor/helix/blob/3a8592abdb9f30c7ebb74f10fa5127e754d18bc6/helix-term/src/commands/typed.rs#L1745
via `cx.set_error()`

**Comment by roberte777** [comment]
> https://github.com/helix-editor/helix/blob/3a8592abdb9f30c7ebb74f10fa5127e754d18bc6/helix-term/src/commands/typed.rs#L1745
> 
> via `cx.set_error()` or returning an error.

I don't think this function really provided an opportunity to return an error, because it's just a general lookup and there are no checks for setting any of the other values. 

I've got a basic PR open, let me know if we should start looking to add errors or if what I've implemented is enough.

**Comment by gyreas** [comment]
I was actually working on it but it's good that you're on it since I don't have the resources to do a PR. 

I'll keep an eye on this
