### ISSUE TITLE
Is there a breadcrumbs-like navigation ?

### ISSUE THREAD

**Issue by alibektas** [helix-editor/helix#7181]
I want to be able to see the scope I'm in. VSCode offers a breadcrumbs navigation. Is there something similar in Helix as well? I am looking for an answer to this particular question and if the answer is "No", which I believe what it is going to be, how do you know which function/class/scope/whatever you are in ?

**Comment by grv07** [comment]
@alibektas  I think this is kinda what you are asking https://github.com/helix-editor/helix/pull/6118

**Comment by alibektas** [comment]
A rather unexpected alternative but I liked it thanks @grv07

**Comment by gabydd** [comment]
Also duplicate of https://github.com/helix-editor/helix/issues/396

**Comment by Rudxain** [comment]
related #14593
