### ISSUE TITLE
Is there any tutorial materials on how to write extension for Helix?

### ISSUE THREAD

**Issue by alissa-tung** [helix-editor/helix#72]
This work seems very elegant :) For daily usage it would be better to create some customary key-bindings and some scripts to invoke command line  applications. I am wondering that if there is some contents describe the way to do so. Rust is indeed a good language, hope they can compose well

**Comment by kirawi** [comment]
I'm not a developer for this project, but I think there currently isn't any dynamic extensionality just yet. However, I think there's interest in using WASM modules for it, nothing confirmed though.

**Comment by archseer** [comment]
Keep an eye on #122, #75

Also #268 is landing soon :)
