### ISSUE TITLE
File picker crashes on huge files

### ISSUE THREAD

**Issue by iocron** [helix-editor/helix#7225]
### Summary

File picker crashes, because the files are too huge (I am not even opening any files), this could be related to the tree-sitter.

### Reproduction Steps

1. Using `hg` in a folder with huge files
2. Then opening the file picker (space+f)
3. => Crash (sometimes it hangs for a very long time instead of the crash)

### Platform

Ubuntu 20.04.6 LTS (WSL on Windows 10)

### Terminal Emulator

ubuntu windows wsl terminal

### Helix Version

helix 23.03

**Comment by pascalkuthe** [comment]
Update to helix 23.05 it should be fixed there

**Comment by the-mikedavis** [comment]
Yeah I believe the hanging should have been fixed by https://github.com/helix-editor/helix/pull/7028. What is the crash though? Please include the backtrace.

**Comment by pascalkuthe** [comment]
> Yeah I believe the hanging should have been fixed by #7028. What is the crash though? Please include the backtrace.

It was a freeze but if you run out of memory it can easily turn into a crash. I tested cases that led to a crash in the past but worked fine after that patch (well you didn't get any highlighting of course)

**Comment by iocron** [comment]
Thank you for all the infos. I was able to pinpoint the exact folder location, the folder contains only .tar and .sql files (the entire folder is only ~700MB), so that's a bit surprising to me. 

I'll have to install (or build) the new version manually, because the apt repo seems out of date (helix 23.03 is the latest on Ubuntu 20.04) and flatpak is not an option at the moment on my WSL Ubuntu 20.04 Installation. 

@the-mikedavis Sadly there is nothing in the error logs, it just hangs and eats up memory (and sometimes freezes after a while) and other times it works after a long time of waiting.

**Comment by pascalkuthe** [comment]
Since no additional information was provided and this was likely already fixed I am closing this as stale
