### ISSUE TITLE
[Crash] "thread 'main' panicked", empty file

### ISSUE THREAD

**Issue by 4164696f73** [helix-editor/helix#7237]
I opened an empty file, basically just typed "hx" in terminal to open Helix. I typed some text there, not code of any sort, just regular text in ASCII, and upon pressing esc (jumping out of insert mode), the editor crashed with following error (I don't know how to use Github formatting...):
> thread 'main' panicked at 'Position 8 is out of range for changeset len 1!', helix-core/src/transaction.rs:400:13

I do not have any modifications to my esc key in insert mode. [Here's my config.](https://pastebin.com/raw/jtsQEFu4) Version: helix 23.05, OS: Manjaro, up to date (updated yesterday).

**Comment by gabydd** [comment]
If you can replicate can you please run with a backtrace ``RUST_BACKTRACE=1 hx`` to help track down the bug

**Comment by 4164696f73** [comment]
All I did was just typing, so I don't think I can replicate it in any way.

**Comment by kirawi** [comment]
Unfortunately, this isn't actionable without reproduction steps or a backtrace.
