### ISSUE TITLE
Helix uses Windows settings under MSYS2

### ISSUE THREAD

**Issue by go2null** [helix-editor/helix#7239]
### Summary

I installed `helix` from within `MSYS2` and was very surprised that it behaves as if I had installed it natively in Windows
* it uses `%APPDATA%\helix\config.toml` instead of `$XDG_CONFIG_HOME/helix/config.toml`.  
  * This took me a while to figure out why `config-reload` was not working.
  * see related #6747
* it uses `%APPDATALOCAL%\helix\config.log` instead of `$XDG_CACHE_HOME/helix/helix.log`.  
* it uses `CRLF` instead of `LF` for default EOL.
  * `:line-ending lf` for each new file is kinda tedious.
  * see related #3945

### Reproduction Steps

 

I tried this:

1. 1helix`
1. `:new`
2. `:write abc.rb`

I expected this to happen:
* File with `LF` EOL be created

Instead, this happened:
* File with `CRLF` EOL be created

### Helix log

<details><summary>~/.cache/helix/helix.log</summary>

```
please provide a copy of `~/.cache/helix/helix.log` here if possible, you may need to redact some of the lines
```

</details>

### Platform

MSYS2 MinGW UCRT x64

### Terminal Emulator

mintty

### Helix Version

helix 23.05 (39d0d85d)

**Comment by the-mikedavis** [comment]
#5621 (#4378 / #3945) has been merged so I think this is now covered just by #6747. I'll close in favor of that but if the default behavior here is not correct we can re-open this / open a new issue
