### ISSUE TITLE
comment mode

### ISSUE THREAD

**Issue by llogiq** [helix-editor/helix#7284]
In VSCode, when I type "enter" in line comments, it extends the comment automatically, e.g.

Before
```rust
/// something something| (<- cursor is here)
```
After pressing the *enter* key
```rust
/// something something
/// | (<- cursor is here)
```

Unfortunately, helix doesn't seem to do that yet.

**Comment by the-mikedavis** [comment]
Duplicate of https://github.com/helix-editor/helix/issues/1730

**Comment by llogiq** [comment]
Oops, I somehow missed that, even with issue search for comment/comments. Sorry. I blame GitHub search.
