### ISSUE TITLE
Winget Path & Dependency Issues

### ISSUE THREAD

**Issue by themixednuts** [helix-editor/helix#7288]
Excuse me if I'm reporting this in the wrong location, but the winget pkg (23.05) doesn't set the correct path variable. 

Sets to: `AppData\Local\Microsoft\WinGet\Packages\Helix.Helix_Microsoft.Winget.Source_8wekyb3d8bbwe`
Should be?: `AppData\Local\Microsoft\WinGet\Packages\Helix.Helix_Microsoft.Winget.Source_8wekyb3d8bbwe\helix-23.05-x86_64-windows`

I then manually changed it to the correct path, but nothing happen. I ran hx.exe myself (clean install of windows) and got 
![image](https://github.com/helix-editor/helix/assets/118081862/ae35c009-1fc2-4239-9634-336ba0717853)

Installed the redistributable myself, and now with the correct path it works.

Just wanted to report this, let me know if this is in the wrong location. Thank you!

**Comment by kirawi** [comment]
You should post this upstream to winget. We don't package it.
