### ISSUE TITLE
Tokyonight Theme highlighting

### ISSUE THREAD

**Issue by shbfy** [helix-editor/helix#7306]
When I use the tokyonight theme, I get unexpected highlights. Other themes appear fine.

Is there some editor configuration required that I am missing?

<img width="533" alt="image" src="https://github.com/helix-editor/helix/assets/26031153/8180ee00-6379-4a46-bcfb-3da94361cd04">

**Comment by shbfy** [comment]
This was caused by tmux

**Comment by TheRealLorenz** [comment]
How did you fix it?
