### ISSUE TITLE
Options for rendering whitespace inside selections (differently).

### ISSUE THREAD

**Issue by 7ombie** [helix-editor/helix#7337]
It would be helpful to distinguish between whitespace generally and whitespace inside selections, in the user's configuration.

Personally, I'd find it helpful if newlines we're more obvious inside selections (but don't want to see newlines all the time).

**Comment by the-mikedavis** [comment]
This is the outstanding item on https://github.com/helix-editor/helix/issues/1068 so I will close in favor of that issue. Also see https://github.com/helix-editor/helix/pull/2208

**Comment by 7ombie** [comment]
@CptPotato - Nice! That's close enough for me while we're waiting. Thank you. Much appreciated.
