### ISSUE TITLE
Copy to clipboard error messages from LSP

### ISSUE THREAD

**Issue by ipochi** [helix-editor/helix#7346]
I was wondering if there is a facility to copy the error message shown by an LSP to the system clipboard.

I know I can press Space + d to see all the errors thrown by LSP in a separate buffer but I'd like to copy the error message for debugging/searching on the internet.

**Comment by CptPotato** [comment]
There currently isn't.

Also, this is a duplicate of #7062

**Comment by ipochi** [comment]
Ah , ok, sorry about the duplicate issue. I suppose this can then be closed.
