### ISSUE TITLE
Limit the size of the logfile

### ISSUE THREAD

**Issue by happysalada** [helix-editor/helix#735]
#### Describe your feature request

I left the editor overnight somehow, I woke up to a 4GB logfile.
It seems something went wrong, but the logfile is filled with 
`2021-09-09T10:20:04.104 helix_lsp::transport [ERROR] err <- `
the lines are truncated, so unfortunately I can't say much more.
How about limiting the size of the log file to 128 mb ? (just in case it gets out of control)

**Comment by kirawi** [comment]
Some alternative solutions may be to:
1. Not log empty errors.
2. Attempt to shutdown/kill the LSP process after a certain number of errors.
3. Have less being logged when logging is not turned on via `-v`.

**Comment by kirawi** [comment]
By the way, is this on master or `0.4.1`? I believe it should have been fixed on master.

**Comment by sudormrfbin** [comment]
There's some discussion on the issue of log size in #566. Raising the log level to warn or error by default would also keep the size in check.

**Comment by happysalada** [comment]
it's on `0.4.1`

**Comment by happysalada** [comment]
also perhaps not truncate the error (in terms of line size limit)? if it was a little longer, more information could be gathered I think.

**Comment by archseer** [comment]
There's no truncation happening, the error is just empty. If the LSP died we did not properly detect EOF and just kept reading 0 bytes and erroring. It's fixed on master https://github.com/helix-editor/helix/commit/41f1e8e4fb4b3b387f34ef5d2e913e7ebc7fd888

> Raising the log level to warn or error by default would also keep the size in check.

We actually do that already https://github.com/helix-editor/helix/blob/0b1bc566e4e3cfa88e23133fb018c998f2052c52/helix-term/src/main.rs#L12

**Comment by sudormrfbin** [comment]
> > Raising the log level to warn or error by default would also keep the size in check.
> 
> We actually do that already

Ah my log file was 20,000 lines long and there were `INFO` lines at the top from an older date, so I assumed they log level was unset.

> There's no truncation happening, the error is just empty. If the LSP died we did not properly detect EOF and just kept reading 0 bytes and erroring. It's fixed on master [41f1e8e](https://github.com/helix-editor/helix/commit/41f1e8e4fb4b3b387f34ef5d2e913e7ebc7fd888)

Then I think this issue can be closed ?

**Comment by happysalada** [comment]
I'll re-open if this happens again with master.
Thank you for taking the time to take a look!

**Comment by smores56** [comment]
> That specific bug was already fixed in master.
I installed from pacman, so I'll just compile from source this time.

**Comment by smores56** [comment]
Though this shouldn't be an issue for me, it still seems that having a non-truncating log file could be problematic here. `fern` doesn't currently have a way to auto-truncate, but it would be better IMO to add the functionality there rather than custom roll something here or change the entire logging library.

**Comment by pickfire** [comment]
Probably we need to custom roll one ourselves, probably can use tracing-subscriber and write a custom `MakeWriter`. https://docs.rs/tracing-subscriber/0.2.25/tracing_subscriber/fmt/writer/trait.MakeWriter.html

**Comment by archseer** [comment]
Before we go overboard with the implementation, all we need to do is use https://doc.rust-lang.org/std/fs/struct.OpenOptions.html#method.truncate
