### ISSUE TITLE
Option to not centre the cursor when switching between buffers

### ISSUE THREAD

**Issue by DerekLeach** [helix-editor/helix#7355]
When I switch between buffers the view is always moved up or down so that the cursor is vertically centred on the screen. When I rapidly flip back and forward between two buffers using gn and gp my eyes are anticipating a certain shape to the text on the screen but this is confused when the text keeps moving up or down a few lines so that it takes me a moment to reorient myself. This also happens when using the buffer picker.

It would be great if there were an option to keep the previous scroll location and not automatically centre the cursor vertically on the screen each time.

**Comment by t-monaghan** [comment]
I've had an attempt at this issue with #7414 

I just noticed that @DerekLeach mentions having this as an option. My experience is that this ViewPosition centering adds friction to my code comprehenesion, and I would have the preference that restoring the ViewPosition is the default behaviour. 

Again, I'm very green in this area, so I would appreciate some guidance.
