### ISSUE TITLE
Facing Problem while uninstalling Helix from Windows 11

### ISSUE THREAD

**Issue by postmeback** [helix-editor/helix#7358]
### Summary

Hi,

As per the given instruction, I opened the `powershell` and ran `winget install helix.helix`. As the directory was wrongly assigned, I thought of uninstalling and reinstalling. While uninstalling, I ran `winget uninstall helix.helix`. At first go, it was failing, asking me to add `--force` to execute the command. After uninstalling, I started reinstalling with the respective command, and an error appeared.

![Helix-Uninstall-Issue](https://github.com/helix-editor/helix/assets/14862687/5d8af593-ab60-43ef-888a-046f943ba72a)

However, I manually went to the mentioned path in the screenshot and deleted the folder and reinstalled.

It was successfull.

### Platform

Windows

### Terminal Emulator

Powershell

### Helix Version

Latest version

**Comment by kirawi** [comment]
We don't package it. This is an upstream issue.

**Comment by postmeback** [comment]
@kirawi , thanks for the reply, but as I am a novice, Requesting a explanation

**Comment by kirawi** [comment]
Post to https://github.com/microsoft/winget-pkgs
