### ISSUE TITLE
Disable LSP by default if running as `root`

### ISSUE THREAD

**Issue by notramo** [helix-editor/helix#7374]
### Summary

It's insecure to automatically run external processes as root (e.g. `svelte-server` or `tsserver` are NPM packages).

When running as `root` user, `hx` should disable LSP unless explicitly enabled in config.

### Platform

Linux, macOS

### Terminal Emulator

all

### Helix Version

latest

**Comment by kirawi** [comment]
https://github.com/helix-editor/helix/issues/7304

**Comment by kirawi** [comment]
Ah nevermind

**Comment by kirawi** [comment]
I don't think there is precedence for this. At any rate, this is already possible by setting a custom config when it's running as root.
