### ISSUE TITLE
Panic upon pressing `n` while search is set to an invalid regex

### ISSUE THREAD

**Issue by Omnikar** [helix-editor/helix#738]
### Reproduction steps
1. Press `/` or `s`.
2. Enter an invalid regex, such as `invalid(`.
3. Press `n` or `N`. Helix panics with an error unwrap.

**Comment by pppKin** [comment]
Can confirm. I don't think we need to `unwrap` the regex in `search_next_impl`, just do nothing and warn user of the invalid regex.
