### ISSUE TITLE
Change MATLAB parser

### ISSUE THREAD

**Issue by acristoffers** [helix-editor/helix#7386]
Hi,

I developed a new MATLAB parser ([acristoffers/tree-sitter-matlab](https://github.com/acristoffers/tree-sitter-matlab)) which is now being used in neovim too (nvim-treesitter/nvim-treesitter#4944).

However, I'm not an Helix user and don't know exactly what are your requirements, nor how to actually test things out. I have cloned this repo, changed the matlab entry to fetch the right repo and replaced the highlights.scm file for that of emacs and it kinda works, except it's not very colorful (I don't know if it is because of the theme - dracula - or wrong captures) and I noticed this (I don't know what's going on that only 2 of the exactly same things got highlighted):

![image](https://github.com/helix-editor/helix/assets/2191364/81a160ec-24af-492b-8e5a-e8442dcd7615)

Also, I could not get textobjects to work.

So, can someone point me out in the good direction to provide helix-specific queries? Do you have documentation on what is supported, what queries are available, which order the queries match (I guess first in the document gets priority)? I would love to work with you to make the parser support your editor, even if I don't use it.

Thank you.

P.S.: If you change to my parser, this issue will be resolved: #7058.

**Comment by the-mikedavis** [comment]
The scopes we use are here: https://docs.helix-editor.com/master/themes.html#syntax-highlighting. For example when rewriting neovim queries we often need to change `@integer` to `@constant.numeric.integer` and `@parameter` to `@variable.parameter`. I believe we have the same precedence as emacs' tree-sitter: the top-most pattern in the query file that matches gets precedence. Also see https://docs.helix-editor.com/master/guides/adding_languages.html#queries

**Comment by the-mikedavis** [comment]
Yeah we only support highlights (plus injections and locals), indent and textobject queries currently. I think it's fine to include the others since they might be nice starting points when we implement folding for example. The tags.scm queries though I'm not sure we'll ever use, those could probably be dropped from the repo.

**Comment by gabydd** [comment]
Closed by https://github.com/helix-editor/helix/pull/7388

**Comment by gabydd** [comment]
Closed by https://github.com/helix-editor/helix/pull/7388
