### ISSUE TITLE
[Question] How to override a specific lsp config 

### ISSUE THREAD

**Issue by midnightexigent** [helix-editor/helix#742]
Hi, 

I just found out about this project, very promising stuff

I am trying to customize the lsp config: I install `rust-analyzer` with the `rustup` nightly toolchain meaning that the command to run it is `rustup run nightly rust-analyzer`

Is there a way to configure `helix` so it runs that command for `rust-analyzer`?

**Comment by kirawi** [comment]
`rust-analyzer` needs to be present in your `PATH` environment variable. I don't think `rustup` adds it for you.

**Comment by midnightexigent** [comment]
Thanks for the reply, 

I tried that, but now I am encountering a different issue:

I put this in `languages.toml`
```toml
[[language]]
name = "rust"
language-server = { command = "rustup", args = ["run", "nightly", "rust-analyzer"] }
config = """
{
  "cargo": {
    "allFeatures": true,
  },
  "checkOnSave": {
    "command": "clippy",
  }
}
"""
```

But `helix` is not using the config I provided (I am not getting `cargo clippy` warnings)

**Comment by kirawi** [comment]
Try turning on logging via `-v` and then look at the log.

**Comment by midnightexigent** [comment]
I tried that, but the `config` payload is nowhere to be seen in the logs, there is just the capabilities. I also tried with `-vvv` but didn't get the information in the logs

**Comment by kirawi** [comment]
Seems like it doesn't work because the `rustup` process ends early.

**Comment by midnightexigent** [comment]
so is it a bug ?

**Comment by kirawi** [comment]
That's because `rust-analyzer` is not present in your `PATH` environment variable; `rustup install rust-analyzer` doesn't add it. You'll have to install it through some other method, such as a package manager or manually, because it's not yet possible to do with `rustup` (https://github.com/rust-lang/rustup/issues/2411).

**Comment by midnightexigent** [comment]
Sorry, I meant that I tried this 

```toml
language-server = { command = "rust-analyzer" }
```

with `rust-analyzer` in my `PATH` but the config wasn't being applied either. 

Anyhow, I figured out the problem: the json parsing of the provided config was failing silently due to **the trailing commas**. 

Since we're already in a `toml` file, shouldn't the `config` be passed in as a `toml::Value` rather than a json string ?

**Comment by kirawi** [comment]
No, it has to be JSON according to the LSP spec. As for trailing commas, we should probably be logging such errors https://github.com/serde-rs/json/blob/8604ef948bec5190db6fa23d362bd3368620990c/src/error.rs#L66

**Comment by midnightexigent** [comment]
yes, I meant read it as a `toml::Value` from the config, and the convert it to a `serde_json::Value`, something like [this](https://play.rust-lang.org/?version=stable&mode=debug&edition=2018&gist=c2593f7d3ff73728c14ab245da1bb82f)

```rust
let toml_value: toml::Value = toml::from_str(r#"
    [config.cargo]
    allFeatures = true
    [config.checkOnSave]
    command = "clippy"
  "#).unwrap();
let json_value: serde_json::Value = toml_value.try_into().unwrap();
  
println!("{}", serde_json::to_string_pretty(&json_value).unwrap())
}
```

**Comment by kirawi** [comment]
This goes outside of what I know (I haven't worked with the LSP code), but I suspect that it's because converting from JSON to Toml didn't really make sense. This was brought up before in the past before this was implemented, and I guess we decided to stick with JSON.
