### ISSUE TITLE
Ability to specify file type prefixes for language detection

### ISSUE THREAD

**Issue by klardotsh** [helix-editor/helix#7422]
A pattern I've seen or implemented in many repos is to have `Containerfile` alongside a `Containerfile.base` - the former bundles up the app code (which changes frequently), the latter installs "system level dependencies" which generally changes far less frequently (this would be where, say, `libfoo-devel` gets installed for `foo-gem` to build against).

My Neovim config appears to auto-detect `Containerfile.base` as a Dockerfile (not sure if that's by way of file name or by way of the `FROM blah` line at the top), but I can't so far figure out how to emulate this in Helix, and further, Vim modelines don't flip Helix into Dockerfile mode, so I can't even hint at "hey, here's what you should use to highlight this!".

I'd propose something like the following, though it's probably imperfect and open to all sorts of discussion:

```toml
file-types = ["Dockerfile", "dockerfile", "Containerfile", "containerfile", { prefix = "Containerfile." }]
```

or maybe `Containerfile.*`?

**Comment by the-mikedavis** [comment]
This would also be useful for Bazel which can have filenames like `BUILD.dep1`, `BUILD.dep2`. We already support path suffixes so I think prefixes or file stems could make sense to add as well https://docs.helix-editor.com/master/languages.html#file-type-detection-and-the-file-types-key

**Comment by klardotsh** [comment]
This is gonna be one of those "famous last words" things, but: I wonder if regex matching is a useful addition to the `file-types` matcher. I currently can't think of anything it would add that `prefix = "foo"` can't do, but (1) it's a more generalized solution for any weird filetypes that come up later, and (2) maybe someone has run into cases where it would be useful already, I dunno.

I agree though that `prefix = "foo"` is the simpler thing to implement for now, and almost certainly more performant.
