### ISSUE TITLE
Helix-specific ignore file

### ISSUE THREAD

**Issue by rcorre** [helix-editor/helix#7423]
I'm working in a project with lots of `.blend` files. These are committed to version control (so they're not in `.gitignore`). I also find it useful to type `blender <ctrl+t>`, using `fzf` to select a blend file to open, so I don't want to add `.blend` to `.ignore`. However, I don't want these files to show up in the helix file picker. Could we have helix respect an additional ignore file, `.helix/ignore`? This would contain patterns that should be ignored by helix, but not other tools that also use `.ignore`.

**Comment by rcorre** [comment]
Alternatively, an option to ignore binary files in the picker would also work here.

**Comment by pppKin** [comment]
> Alternatively, an option to ignore binary files in the picker would also work here.
 If we go with this, it should default to true IMO.

**Comment by PaulOlteanu** [comment]
Filtering the file picker seems to be done by file extension at the moment (for compressed files). Looking into how `ripgrep` filters binary files shows that it does so by finding a null byte in the file, and copying this behaviour would mean the file picker would have to start reading each file (which doesn't seem like a good solution imo)

We could try and create a big list of binary file extensions for this purpose.

I can take a look at adding support for a `.helix/ignore` solution though.
