### ISSUE TITLE
OneDarker are difficult to distinguish code and inlay hints based color

### ISSUE THREAD

**Issue by gobraves** [helix-editor/helix#7432]
It is difficult to differentiate between hints and code in the onedarker theme based on colors.

I I referenced #6503   and added  `"ui.virtual.inlay-hint" = { fg = "light-gray" }`

the original theme:
![image](https://github.com/helix-editor/helix/assets/9588311/ac52695a-b05d-41c4-833b-9000134e5e14)

the new theme:
![image](https://github.com/helix-editor/helix/assets/9588311/92737331-a742-47c5-8e4a-f7a36db6f4b2)

I could commit pr,  if the team agrees that this should be changed.

**Comment by the-mikedavis** [comment]
That change looks fine to me. What do you think @nuid64?

**Comment by nuid64** [comment]
That's cool. Thanks for asking, @the-mikedavis , and thanks for improvement, @gobraves .

**Comment by shbfy** [comment]
This issue is also present in the monokai, and monokai_aqua themes.

**Comment by lauglam** [comment]
> This issue is also present in the monokai, and monokai_aqua themes.此问题也存在于 monokai 和 monokai_aqua 主题中。

Yes, this issue comes up in many theme.

**Comment by lauglam** [comment]
> This issue is also present in the monokai, and monokai_aqua themes.

Yes, this issue comes up in many theme.
