### ISSUE TITLE
Failed to load language config: unknown field `language-server`

### ISSUE THREAD

**Issue by andradei** [helix-editor/helix#7438]
After adding the GDScript LSP config to my `languages.toml` I got this error. I also don't see any reference to `language-server` (plural) in the documentation despite it being in multiple places in the Wiki:

![image](https://github.com/helix-editor/helix/assets/2653546/4fecd6d2-4cdd-4c69-868c-3c3a0443226f)

**Comment by pascalkuthe** [comment]
There was a breaking change to to config on master. If you are still using 23.5 or older than that config doesn't work yet. Consult the stable docs.
