### ISSUE TITLE
use rust-analyzer macro expansion feature in helix

### ISSUE THREAD

**Issue by tdelabro** [helix-editor/helix#7447]
rust-analyzer lets you expand macros
On vscode it opens a new window where the code generated by your macro appears

How can I achieve a similar thing with helix?

The command already exist on [rust analyzer side](https://github.com/rust-lang/rust-analyzer/blob/master/docs/dev/lsp-extensions.md#expand-macro)

**Comment by the-mikedavis** [comment]
See https://github.com/helix-editor/helix/discussions/6166
