### ISSUE TITLE
Support configuring autocompletion to only fire when told to.

### ISSUE THREAD

**Issue by 7ombie** [helix-editor/helix#7450]
Language servers can be very useful in some contexts, but can really start to get in the way in others.

The current configuration supports setting the `idle-timeout` to `0` (milliseconds) to have autocompletions fire immediately, or some higher number to delay it. However, I'd like to disable the timer altogether, so completions never fire automatically, while I still have a keybinding for opening the completions dialog manually (so I cannot just disable the language server entirely). This does not appear to be supported.

API-wise, I was hoping for something like this:
 
``` toml
[editor]
lsp.enable = true
idle-timeout = false
```

**Comment by pascalkuthe** [comment]
completions popping up automatically is the *auto* part of autocompletions. There is already a setting to disable autocompletions. That ofcourse won't affect the manual completion trigger

**Comment by the-mikedavis** [comment]
Yeah, this configuration should be the behavior you're looking for:

```toml
[editor]
auto-completion = false
```

`C-x` can still be used to pull up the completion menu.

**Comment by 7ombie** [comment]
Thank you. Perfect.
