### ISSUE TITLE
Bug: A symlink that points to a file with with an unrecognizable file extension should fallback to the symlinks file extension

### ISSUE THREAD

**Issue by budde25** [helix-editor/helix#7458]
### Summary

The file extension of a symlink should be used as a file type hint, when the one on the destination file does not help.
This is in regards to syntax highlighting.

### Reproduction Steps

Minimum reproducible example:
I have two files, one real one name `test.c.1` with my c source code
and a symlink to that previous file named `test.c`.

When I open test.c.1 there is no syntax highlighting which is expected since there is not hint for the editor, however when I open test.c (symlink to test.c.1), I would expect it to open with c syntax highlighting (at least as a fallback).

This expected behavior is the current behavior of other popular editors (Ex: neovim)

### Helix log

<details><summary>~/.cache/helix/helix.log</summary>

```
please provide a copy of `~/.cache/helix/helix.log` here if possible, you may need to redact some of the lines
```

</details>

### Platform

Linux + MacOs

### Terminal Emulator

Iterm2 Build 3.4.19

### Helix Version

helix 23.05 (7f5940be)

**Comment by woojiq** [comment]
This would be a nice feature because I have often run into its lack, especially on NixOs. When you have a `~/.config/helix/config.toml` file which is a symlink to `/nix/store/blablabla-helix-config` (plain text), so I don't have syntax highlighting.
