### ISSUE TITLE
Attach to Container (VSCode style)

### ISSUE THREAD

**Issue by thomasaarholt** [helix-editor/helix#7472]
This is a feature request extension of #3002, I believe:

Our workflow is to run some image in Docker that contains all the required parts for developing a project (Python, pip packages ++), and then use the [VSCode `Attach to a Running Container` feature](https://code.visualstudio.com/docs/devcontainers/attach-container) in order to use VSCode as if it was running inside the container.

The particularly nice feature of VSCode is that a list of running containers appears when you call the above command as in the following screenshot, meaning that you don't need to edit configuration files each time you make a new project. 
<img width="907" alt="Screenshot 2023-06-28 at 12 13 40" src="https://github.com/helix-editor/helix/assets/2721423/92d9f3e9-36a6-49b1-9918-b879c8537a55">

Would something like this be possible to add to Helix?

**Comment by dead10ck** [comment]
Most likely this will not be a feature in the core editor. Could be a good plug-in when our plug-in system lands, but that's not going to be soon.
