### ISSUE TITLE
Diagnostic scopes

### ISSUE THREAD

**Issue by kirawi** [helix-editor/helix#748]
Not sure if this is already possible, but it would be nice to have `warning`, `error`, `info`, and `hint` scopes for the `diagnostic` scope.

**Comment by the-mikedavis** [comment]
I think this is implemented now, right?

https://github.com/helix-editor/helix/blob/c45fb08a9389e21d9694059819aed940ba446a0b/book/src/themes.md?plain=1#L231-L235

**Comment by sudormrfbin** [comment]
I believe those are for the gutter only (the color for the filled dots), whereas `diagnostic` is for styling the text itself. We still don't have `diagnostic.{warning,error,info,hint}` (also the naming is too confusing that probably needs a change too).

**Comment by sudormrfbin** [comment]
Closing in favor of #2157 which has a clearer description.
