### ISSUE TITLE
Add `:ra` alias for `:reload-all` command

### ISSUE THREAD

**Issue by adamkpickering** [helix-editor/helix#7485]
I find myself doing `:reload-all` frequently when I switch git branches. This is quite a bit to type for how frequently I do it. Can we add a `:ra` alias for `:reload-all`? There is a precedent for this: the `:write-all` command has the alias `:wa`.

**Comment by the-mikedavis** [comment]
This is aliased on master: https://github.com/helix-editor/helix/pull/7158

**Comment by adamkpickering** [comment]
Huh, I searched for existing issues and somehow missed that. Thanks!
