### ISSUE TITLE
Can't go to matching bracket in "for" loop brackets and array brackets

### ISSUE THREAD

**Issue by O136** [helix-editor/helix#7487]
### Summary

I'm editing cpp code and using clangd as the lsp server.

The following behaviour, applies to both `()` brackets belonging to the `for` loop and also array notation `[]`:
Typing `mim` selects the text as expected inside the `(` `)` brackets of the `for` (as well as `[]` brackets), but `mm` doesn't go to its matching bracket nor does it highlight it when the cursor is on the `(` (or `[` respectively))

![2023-06-29-171529_703x94_scrot](https://github.com/helix-editor/helix/assets/16740762/f06049f0-76db-4d99-be95-5e855cb39108)

![2023-06-29-171615_600x43_scrot](https://github.com/helix-editor/helix/assets/16740762/d7ab3fc9-3649-4318-8fab-460f0a956982)

### Platform

FreeBSD 13.2

### Terminal Emulator

wezterm 20230408-112425-69ae8472

### Helix Version

helix 23.05

**Comment by pascalkuthe** [comment]
Try the latest master there were some improvements recently

**Comment by O136** [comment]
Thanks ! will wait for the next release then, I tried the latest master and everything works as expected :)
