### ISSUE TITLE
External command support

### ISSUE THREAD

**Issue by QiBaobin** [helix-editor/helix#75]
Will there be any external command support? I think that would provide a way to do what internal command missing on early stage, like grep, git etc.

**Comment by itzmjauz** [comment]
I've always liked the vim way of ;
`:!{command}`

**Comment by archseer** [comment]
I think as a start, all the kakoune commands are applicable and should be easy to do:

```
|: pipe each selection through the given external filter program and replace the selection with it’s output.
<a-|>: pipe each selection through the given external filter program and ignore its output
!: insert command output before selection
<a-!>: append command output after selection
```

I'm not too opinionated on whether this should be a keymap or a `:pipe` command.
