### ISSUE TITLE
keep cursor position when scrolling

### ISSUE THREAD

**Issue by kirawi** [helix-editor/helix#750]
### Discussed in https://github.com/helix-editor/helix/discussions/718

<div type='discussions-op-text'>

<sup>Originally posted by **sekirocc** September  6, 2021</sup>
Hi, when scrolling using `C-d` `C-u`, the cursor is now sticking with same line number, which makes the cursor jump  back and forth in window.
How about add a config option(or even make it default) to set the cursor stay in same position relative to window.
Just like vim's `C-d` `C-u`.</div>

**Comment by kirawi** [comment]
Actually, I'm a bit confused. Isn't this what we already do?

**Comment by pascalkuthe** [comment]
#7639 was recently created which is about the same thing. That issue has a bunch more discussion (and an example implementation that is pretty good already) so I will close this issue in favour of that
