### ISSUE TITLE
Register `infobox` value only updated once.

### ISSUE THREAD

**Issue by gibbz00** [helix-editor/helix#7502]
### Summary

[Kooha-2023-07-01-20-45-03.webm](https://github.com/helix-editor/helix/assets/31696304/ec0e5f6e-c79f-42a1-9e40-cd4e796df12c)

### Platform

Linux

### Terminal Emulator

foot

### Helix Version

master

**Comment by gabydd** [comment]
Duplicate of https://github.com/helix-editor/helix/issues/5241
