### ISSUE TITLE
Support skim environment variables for file picker

### ISSUE THREAD

**Issue by thomasaarholt** [helix-editor/helix#7510]
From what I can tell, [`skim`](https://github.com/lotabout/skim) is used for the file picker. It's like [`fzf`](https://github.com/junegunn/fzf) but written in rust. It provides the file picker and preview functionality. (It would actually if it was mentioned in the readme/docs that helix uses skim, since I assumed at first that the picker was supplied by fzf, which is a bit more popular.)

I would like to be able to customize the skim commands used by helix, preferably by a `HELIX_SKIM_DEFAULT_COMMAND` and `HELIX_SKIM_DEFAULT_OPTIONS`.

One can customize `skim` itself using the environment variables `SKIM_DEFAULT_COMMAND` and `SKIM_DEFAULT_OPTIONS`. For instance, to by defult use `fd` instead of `find`, with some extra filtering, I can set the following variable:
`export FZF_DEFAULT_COMMAND='fd --type f --color=always --hidden --exclude .git --ignore-file ~/.gitignore'` 
And then to colorize the ansi strings inside skim, I can set the following variable:
 `export SKIM_DEFAULT_OPTIONS = '--ansi`.

<img width="1382" alt="Screenshot 2023-07-02 at 10 49 17" src="https://github.com/helix-editor/helix/assets/2721423/c8eca701-e3de-4e84-b589-8760a8f8fec9">

(I can also add the file preview with `alias skk="sk --preview 'bat --style=numbers --color=always --line-range :500 {}'"`, which incidentally supports mouse scrolling, which is desired in #4102 - it's not as smooth as fzf, but it's good enough)

**Comment by pascalkuthe** [comment]
helix does not shell out to skim or fzf (that would require an embedded terminal and generally a weird way to implement UI components) we only use the fuzzy matcher algorithm of the skim crate but the entire UI and plumbing is custom build. I don't think we will ever allow replacing a UI component with an external TUI like that.

**Comment by thomasaarholt** [comment]
Oh I see, I misunderstood then. Thanks for thr clarification.
