### ISSUE TITLE
lsp rename: doesn't send the correct word

### ISSUE THREAD

**Issue by sigmaSd** [helix-editor/helix#7515]
### Summary

symbols are sent incorrectly the lsp rename:
to reproduce:
- put the cursor on a symbol starting with hashtag (#)
- use lsp rename

expected output
- rename-to: #lib

actual behavior
- rename-to: lib

![image](https://github.com/helix-editor/helix/assets/22427111/140c916c-e63c-472f-a435-43188d298d9b)

this works as expected in neovim, neovim uses `vim.fn.expand('<cword>')` to get which word to send

I expect the bug to be somewhere on the word boundary detection, so here maybe vim.fn.expand('<cword>')

tested with helix 23.05

### Reproduction Steps

 

I tried this:

1. `hx`

I expected this to happen:

Instead, this happened:

### Helix log

<details><summary>~/.cache/helix/helix.log</summary>

```
please provide a copy of `~/.cache/helix/helix.log` here if possible, you may need to redact some of the lines
```

</details>

### Platform

linux

### Terminal Emulator

wezterm

### Helix Version

helix 23.05

**Comment by pascalkuthe** [comment]
Helix uses the current `word` under the cursors which is the same as `miw`. Furthermore the server may send a custom prefill (which is how we can prefill rust lifetimes correctly for example). 

If the server does not provide the correct prefill there is nothing we can do and I would expect that to match the nvim behavior (altough that's hard to to tell given how much behavior can change between configs)

**Comment by sigmaSd** [comment]
for the neovim point, it works correctly in clean neovim, it just uses `vim.fn.expand('<cword>')` and cword does take into account the hashtag

**Comment by sigmaSd** [comment]
Though now reading https://microsoft.github.io/language-server-protocol/specifications/lsp/3.17/specification/#textDocument_rename

Its clear that the original name doesn't matter, its just a convenient placeholder not specified by the spec

**Comment by pascalkuthe** [comment]
typing `#foobar:lua print(vim.fn.expand('<cword>'))<ret>` in a scratch beffer in stock nvim prints `foobar` instead of `#foobar` so that matches helix.
