### ISSUE TITLE
Vim-like `{` or `}` for easier navigation

### ISSUE THREAD

**Issue by gbaranski** [helix-editor/helix#753]
#### Describe your feature request

{ – Go to the beginning of the current paragraph. By pressing { again and again move to the previous paragraph beginnings.
} – Go to the end of the current paragraph. By pressing } again and again move to the next paragraph end, and again.

**Comment by Omnikar** [comment]
I presume that adding this should also add `mip` and `map` for selecting paragraphs?

**Comment by gbaranski** [comment]
> I presume that adding this should also add `mip` and `map` for selecting paragraphs?

Yes, that could be useful too.

Btw maybe instead of going to the end of current paragraph, maybe it'd be better to use tree-sitter, and jump to the end of current block/function/struct/enum.

**Comment by pickfire** [comment]
> I presume that adding this should also add mip and map for selecting paragraphs?

I was planning to add that but at the same time add the autoinfo, maybe I will just do a smaller change for that.

**Comment by archseer** [comment]
Resolved by #1580

**Comment by jamylak** [comment]
> Resolved by #1580

Not sure if that addresses why `{` and `}` don't seem to have a keybinding, seems like that was the main request in this PR. I would also be interested in the reason to leave these ones without a binding
