### ISSUE TITLE
Make format on save optional

### ISSUE THREAD

**Issue by CptPotato** [helix-editor/helix#756]
#### Describe your feature request

It seems like auto-formatting is performed every time the document is saved. I would like to be able to disable this (and instead use `:format` when I need it) since I save very frequently and I find it rather distracting. Auto-format also selects the whole document and moves the cursor to the very beginning, requiring me to always navigate the cursor back to where I left off after saving 😕

**Comment by kirawi** [comment]
This is configured in `languages.toml`

**Comment by CptPotato** [comment]
Thanks for the info, it works exactly as expected!

I wasn't aware that there's a second configuration file for language specific options. Maybe this could be hinted at in the documentation.

**Comment by sudormrfbin** [comment]
Maybe a global `auto-format` option in `config.toml` in addition to language specific configuration would be helpful.

**Comment by tadzik** [comment]
> Maybe a global `auto-format` option in `config.toml` in addition to language specific configuration would be helpful.

Yes please. Or maybe we could just specify it top-level in languages.toml and have it apply to all the languages? Typing out a `[[language]]` section for everything you use just to disable auto-format is a bit tedious.

**Comment by kirawi** [comment]
It was added a while ago.

**Comment by dogunbound** [comment]
Just wanted to say, that I just used this feature. Thanks.

**Comment by rahil627** [comment]
phew, this was a strange one. it was formatting on save for a ".txt" file!.. but it was interesting to see my to-do ordered by the alphabet..
