### ISSUE TITLE
missing command on Windows 

### ISSUE THREAD

**Issue by masriomarm** [helix-editor/helix#7579]
### Summary

command `"extend_to_first_nonwhitespace"` is missing from windows. It caused issues when copied my fedora config to windows.

### Reproduction Steps

 

I tried this:

1. `hx`
2. copy my fedora config

I expected this to happen:
commands should be the same.

Instead, this happened:
error while reloading configs that command `"extend_to_first_nonwhitespace"` is unknown

### Helix log

<details><summary>~/.cache/helix/helix.log</summary>

```
please provide a copy of `~/.cache/helix/helix.log` here if possible, you may need to redact some of the lines
```

</details>

### Platform

Windows

### Terminal Emulator

Windows Terminal

### Helix Version

helix 23.03 (3cf03723)

**Comment by pascalkuthe** [comment]
Commands are not platform dependent you likely just installed an old version since that command was added in the latest release
