### ISSUE TITLE
encoding windows-1252 is not correctly detected.

### ISSUE THREAD

**Issue by masriomarm** [helix-editor/helix#7581]
[DataMan.txt](https://github.com/helix-editor/helix/files/11994848/DataMan.txt)

@pascalkuthe Thanks for support. Here's the file that cause the issue. This file can be read normally wit Vim, Neovim and Emacs. Reading it with helix corrupts characters.

In helix, settting `:encoding windows-1252` then `:reload` solves the issue and display character normally.

Also, here's a ss shows the difference between helix on the left, neovim on the right.
![encoding_issue](https://github.com/helix-editor/helix/assets/77388732/1766f794-2cc6-4ca8-b614-6f18e68706e3)

_Originally posted by @masriomarm in https://github.com/helix-editor/helix/discussions/7580#discussioncomment-6395321_

**Comment by pascalkuthe** [comment]
I can open the file without issue with helix 23.5. If I change the extension to `DataMan.c` nothing changes either

**Comment by masriomarm** [comment]
It also gets detected as correct windows-1252. However, `:encoding utf-8` then `:reload` corrupts the characters.

Thanks for your help @pascalkuthe , I will consider `:encoding windows-1252` then `:reload` for now.
