### ISSUE TITLE
hx panics using the command "hx --health" on a fresh install

### ISSUE THREAD

**Issue by soufianeamini** [helix-editor/helix#7584]
### Summary

Program panicks when trying to check health instead of providing a helpful error message.

### Reproduction Steps

I have installed (fresh install for the first time) helix-editor from its sources following the installation guide, and when trying to install a language server using this: https://docs.helix-editor.com/lang-support.html I was told to check the language support with hx --health, and the program panicked, without providing an error message.

$hx --health
thread 'main' panicked at 'called `Option::unwrap()` on a `None` value', helix-loader/src/lib.rs:124:5
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

### Helix log

Log file:

2023-07-09T16:16:24.429 helix_view::editor [ERROR] editor error: 1 unsaved buffer(s) remaining: ["[scratch]"]
2023-07-09T16:17:17.501 helix_lsp::transport [ERROR] rust-analyzer err: <- StreamClosed
2023-07-09T16:19:50.267 helix_view::editor [ERROR] editor error: Failed to start debug session: cannot find binary path
2023-07-09T16:24:08.843 helix_view::editor [ERROR] editor error: no such command: 'Q'
2023-07-09T16:24:09.845 helix_view::editor [ERROR] editor error: 1 unsaved buffer(s) remaining: ["src/main.rs"]

### Platform

WSL2

### Terminal Emulator

Hyperjs

### Helix Version

helix 23.05 (828c7432)

**Comment by the-mikedavis** [comment]
Looks like this is a bug introduced in #7573. These config and log file initialization lines should be moved higher in `main`, above the `health` and probably all the other flags too https://github.com/helix-editor/helix/blob/550192826bd6ec1598ed209c84a78955b1b53bae/helix-term/src/main.rs#L112-L113

\cc @alevinval

**Comment by alevinval** [comment]
Unfortunately, you just hit this issue some minutes after it got introduced. I did not think about the `--health` command already requiring initialized configuration, here's a fix: https://github.com/helix-editor/helix/pull/7585

**Comment by soufianeamini** [comment]
Running this command after installation fixed it: 
```ln -s $PWD/runtime ~/.config/helix/runtime```
But I figured I'd still mention the panic as an issue. Thanks for the speedy response!
