### ISSUE TITLE
Feature request: Please add a solarized dark theme

### ISSUE THREAD

**Issue by blueray453** [helix-editor/helix#759]
#### Describe your feature request

Please add [solarized dark](https://en.wikipedia.org/wiki/Solarized) theme for helix.

**Comment by kirawi** [comment]
I can try to create a theme based on VSCode's version, and I guess it could be tweaked to match the Vim version by someone else.

**Comment by pickfire** [comment]
Isn't the current one dark theme based on vscode?

**Comment by kirawi** [comment]
Maybe. VSCode has a few subtle differences particularly in regards to the palette.
