### ISSUE TITLE
:sort not working

### ISSUE THREAD

**Issue by nshern** [helix-editor/helix#7620]
### Summary

:sort is not working as (presumably) intended

### Reproduction Steps

 

I tried this:

1. `hx` test.md
2. write the following:
```
B
C
A
```
3. Select the three lines using `x`
4. enter `:sort` and press enter

I expected this to happen:
The three lines to rearrange to:
```
A
B
C
```

Instead, this happened:
Nothing

### Helix log

<details><summary>~/.cache/helix/helix.log</summary>

```
please provide a copy of `~/.cache/helix/helix.log` here if possible, you may need to redact some of the lines
```

</details>

### Platform

macOS

### Terminal Emulator

kitty 0.29.0

### Helix Version

23.05

**Comment by pascalkuthe** [comment]
sort is working as intedend, it sorts selections not lines so you need to create multiple cursors. Either use  `C` instead of 'x' or (more generally) create one selection per line with `a-s` after selecting if you want to sort lines

**Comment by alphastrata** [comment]
> sort is working as _intended_, it sorts selections not lines so you need to create multiple cursors. Either use `C` instead of 'x' or (more generally) create one selection per line with `a-s` after selecting if you want to sort lines

this should be in the docs ey...

**Comment by Schweber** [comment]
@pascalkuthe is this behaviour also as intended? I select the whole lines with "extend_line_below" and they are all shown to be selected but `:sort` has no effect. The document is shown as modified afterwards though, which i also find strange.

https://asciinema.org/a/SF8vrBvVTQboQzFYpeaXGavTB
