### ISSUE TITLE
Block cursor stays solid in unfocused windows

### ISSUE THREAD

**Issue by Zapeth** [helix-editor/helix#7623]
When switching to a different program/window, the block cursor in helix stays solid/filled.

Other terminal programs usually hollow out the cursor block, which often helps me directly spot the currently focused window in my workspace.

But since helix doesn't behave like that I have to double check which window is currently in focus, which is somewhat annoying.

I'm not sure how other cursor styles are usually displayed when they are not in focus, but not displaying a cursor at all would also be a serviceable indicator.

**Comment by pascalkuthe** [comment]
See https://github.com/helix-editor/helix/pull/6858


We can not render hollow cursors (we render block cursors just by changing color instead of using the terminal) so that won't be posaible
