### ISSUE TITLE
In snnipets, add a key to jump to next comma.

### ISSUE THREAD

**Issue by So1aric** [helix-editor/helix#7634]
When LSP suggests a snnipet for function, it might look like:
```
func(, , ,)
```
And if I want to move to the next comma after I finished the first argument, I have to `ESC -> l -> l -> i`, which is a burnout.

**Comment by gabydd** [comment]
Snippets aren't fully implemented, I think we can track this in one issue so I am going to close this as a duplicate of https://github.com/helix-editor/helix/issues/395
