### ISSUE TITLE
ltex-ls language server code actions 'add to dictionary', 'hide false positive' and 'disable rule' don't work 

### ISSUE THREAD

**Issue by nshern** [helix-editor/helix#7636]
### Summary

The code actions 'add to dictionary', 'hide false positive' and 'disable rule' do not work

### Reproduction Steps

 

I tried this:

1. install ltex-ls
2. insert the following in `language.toml`:
```
[[language]]
name = "markdown"
language-server = { command = "ltex-ls"}
file-types = ["md", "txt"]
scope = "source.markdown"
roots = []
```
3. `hx test.md`
4.  write "madeupword" in document
5. do 'code actions' --> add to dictionary

I expected this to happen:
for "madeupword" to be added to dictionary and not show error. At least when the lsp is restarted.

Instead, this happened:
Nothing.

### Helix log

<details><summary>~/.cache/helix/helix.log</summary>

```
please provide a copy of `~/.cache/helix/helix.log` here if possible, you may need to redact some of the lines
```

</details>

### Platform

macOS

### Terminal Emulator

kitty 0.29.0

### Helix Version

helix 23.05

**Comment by pascalkuthe** [comment]
This is an issue with ltex-ls and well known. In VSCode they handle this with custom code in the extension but helix does not (and will never) contain language sowcufuc code so there is no way to implement this for us. 

Other esutira like emacs/vim/kakune exhibit the same behavior

**Comment by nilsherzig** [comment]
I know that's not the question, but I took me some time to find this "workaround": 

You can add this to your language.toml, It's not as convenient, but it works :)

```toml
[language-server.ltex-ls.config]
ltex.disabledRules = { "en-US" = [
  "PROFANITY",
], "de-DE" = [
  "PROFANITY",
] }

ltex.dictionary = { "en-US" = [
  "builtin",
], "de-DE" = [
  "builtin",
  "README",
  "TODO"
]} 

```

**Comment by nshern** [comment]
> I know that's not the question, but it took me some time to find this "workaround":
> 
> You can add this to your language.toml, It's not as convenient, but it works :)
> 
> ```toml
> [language-server.ltex-ls.config]
> ltex.disabledRules = { "en-US" = [
>   "PROFANITY",
> ], "de-DE" = [
>   "PROFANITY",
> ] }
> 
> ltex.dictionary = { "en-US" = [
>   "builtin",
> ], "de-DE" = [
>   "builtin",
>   "README",
>   "TODO"
> ]} 
> ```

Yes. I have been wanting to try to write a more convenient workaround that takes a selected word in Helix, adds it to the dictionary in the .toml and reloads the helix editor. This would essentially work as the 'add to dictionary' functionality.

**Comment by hnorkowski** [comment]
> I have been wanting to try to write a more convenient workaround

Have you ever did it?

**Comment by nshern** [comment]
> > I have been wanting to try to write a more convenient workaround
> 
> Have you ever done it?

Unfortunately no. I will update this thread if I ever do.
