### ISSUE TITLE
Apparent NFS issue

### ISSUE THREAD

**Issue by bikingcoder** [helix-editor/helix#7648]
Hi, I'm having trouble editing files over NFS. Specifically  I get the error: `File modified by an external process, use :w! to overwrite` when attempting to write a file for the second time.

This seems to be the same on NFS V3/4.

The NFS client is a VirtualBox machine, that is mounted using Vagrant, although this should probably be irrelevant. The guest OS is FreeBSD, which might be relevant.

Editing files outside the NFS mount is non-problematic.

Just wondering if there is some kind of known issue. I'm guessing it's in relation to the inotify library - is there anyway to override this file change detection?

Thanks for what looks likes a promising editor.

**Comment by pascalkuthe** [comment]
we use mtime to detect if a file is changed. Almost every os should have some reasonable notion of mtie. There are some tricks to check if the fs supports mtime (used by git/gitoxide). I guess we could implement some autodection but it seems like a pretty niche usecase
