### ISSUE TITLE
Support more key bindings in windows, including f13-f24

### ISSUE THREAD

**Issue by AsafMah** [helix-editor/helix#7669]
Windows has plenty of extra keys available in the virtual keycodes:
https://learn.microsoft.com/en-us/windows/win32/inputdev/virtual-key-codes

Which is useful for extended keyboards, or people like me who map CapsLock to F13 to avoid it.. capslocking.

Currently helix explicitly forbids F13 (there is a test for that).
It would be nice if it could support any virtual key, or at least F13-F24.

**Comment by christianholman** [comment]
submitted a PR for this and updated the test as well, saw you removed good first issue so let me know if there's anything more involved there  - mostly doing this to get setup with the repo:>

**Comment by christianholman** [comment]
> This should be a very small change to support. This bounds check just needs to be expanded to allow up to 24:
> 
> https://github.com/helix-editor/helix/blob/b47519ab11591b525132c5a13e464875b0c4f796/helix-view/src/input.rs#L382
> 
> I'm not sure the history of that line but supporting up to 24 seems fine to me.

submitted a PR for this and updated the test as well, saw you removed good first issue so let me know if there's anything more involved there - mostly doing this to get setup with the repo:>

**Comment by archseer** [comment]
Closed by #7672
