### ISSUE TITLE
<A-Enter> in the file picker jumps to a line in the current file instead of a new one

### ISSUE THREAD

**Issue by woojiq** [helix-editor/helix#7673]
### Summary

Bug was introduced by #4435
Demo: https://asciinema.org/a/yQdXysBaY8nBwoBSoam92efq7
I press `gr` (goto reference) two times.
As you can see, when I first open with `<Enter>`, it immediately shows me a line with the selected _goto reference_. The second time I press `Alt-Enter`, it opens but the cursor of the new file is on 1 line and the line of my current file is scrambled.

Also, whoever is going to fix this, I would like to see these key bindings somewhere in the documentation, as the only mention of it is the code in PR.

### Reproduction Steps

1. `hx helix-term/src/commands` + `g400g`.
2. `gr` + select second entry + `<Alt-Enter>`.

You will see that your cursor on the current file is on line 166. But it should actually open a new file on that line.

### Helix log

<details><summary>~/.cache/helix/helix.log</summary>

```
```

</details>

### Platform

Linux

### Terminal Emulator

wezterm 20230712-072601-f4abf8fd

### Helix Version

helix 23.05-230-g79a8fd62

**Comment by pascalkuthe** [comment]
I don't understnd the issue here, what do you mean with opening a new file. `<alt>ret` doesn't open a split. It just does the same thing as enter without closing the picker. In my testing that is exactly what it does

**Comment by woojiq** [comment]
@pascalkuthe have you tried `<alt>ret` with the default filepicker `<space>f` or a picker where the line number is appended to the filename (eg `gr` goto reference)?

**Comment by pascalkuthe** [comment]
I tried with `gr`

**Comment by woojiq** [comment]
example
1. I open the `main.rs` file.
2. `gr` for a function and see `lib.rs:130` in the picker. Before I open it, my main file is on line 20 (for example).
3. I press `alt-enter` to open `lib.rs` in a new buffer in the background.
4. I close the picker and the `main.rs` buffer gets focus as expected, but now the current line is 130 (expected 20)
5. I go to the next buffer (`lib.rs`) and it focused on line 1 (expected 130).

Do you understand my problem?

**Comment by pascalkuthe** [comment]
Hmm yeah thanks for clarifying I will try to reproduce again, I think I missunderstood your original description. K think I know what causes this.

**Comment by woojiq** [comment]
This [patch](https://github.com/helix-editor/helix/commit/09a971c891c31733c98a740e2717fd8f6d0304e8) fixes issue. Is it good enough for PR or should we come up with something better?

**Comment by pascalkuthe** [comment]
That probably works, you can post a PR and we can take a closer look during review. I was thinking of something else regarding complexity its probably ok like that
