### ISSUE TITLE
Inconsistent documentation about language specific settings

### ISSUE THREAD

**Issue by non-descriptive** [helix-editor/helix#7679]
Attempted to follow guide to setup ruff-lsp for helix and noticed that documentation on the site is
1. Outdated - It doesn't correspond to one in `book/src/languages.md`
2. Inconsistent - the key to setup a language-server is `language-servers` - in plural form. Also it requires an array, not a map. Don't know when this breaking change were introduced.

**Comment by the-mikedavis** [comment]
The master and latest release docs are published separately:

* master: https://docs.helix-editor.com/master/languages.html
* latest release: https://docs.helix-editor.com/languages.html
