### ISSUE TITLE
Ctrl + Left/Right Arrow Keys should jump entire words

### ISSUE THREAD

**Issue by PotatoesFall** [helix-editor/helix#7683]
# Description

When in normal, insert or selection mode, using arrow keys moves the cursor.

Holding Ctrl while using the left/right arrow keys does nothing, instead the cursor should move entire words, similar to the behavior in prompts: https://github.com/helix-editor/helix/blob/master/helix-term/src/ui/prompt.rs#L509

# Why is this useful

## different keyboard layouts make arrow keys preferable

Generally, navigation is done using hjkl or whatever the user has mapped. However, I (and maybe others) are often switching between keyboard layouts and have the arrow keys conveniently accessible on a second layer, making it easier to navigate using arrow keys, rather than switching keymap constantly.

## only useful in insert mode

In normal or selection mode, this would not be an improvement, since b, e, w etc. are around. However in insert mode this feature proves useful as we need to switch to normal mode to navigate, then back into insert mode, when we could simply use the arrow keys (for small movements)

## similar to most other text fields

As much as we might like to, we are not using helix all day. We have to use forms on websites, other text editors, etc. Ctrl + left/right arrow almost always moves entire words. In other words, most people already have this in their muscle memory.

**Comment by PotatoesFall** [comment]
I'm happy to code this myself if people like the idea but I'm not sure where to start. I was able to find where this happens in prompts but not in the editor itself.

**Comment by pascalkuthe** [comment]
the bindings were purposefully removed in #3671 and even though we added back arrow movements we purposefully did not add the ctrl-based keybindings back when that PR was partially reverted see https://github.com/helix-editor/helix/pull/3915#discussion_r975570546.

If you want to use these bindings you can add the bindings back yourself in your config. However,  movement in insert is generally not intended

**Comment by PotatoesFall** [comment]
Thanks for the quick response!

The reasoning there makes a lot of sense actually. Sorry to bring it up if it's already been discussed, I didn't find it in my initial search.

One small thing remains, rebinding this key works fine, but when used in insert mode it creates a selection which doesn't make sense. I can make another issue and maybe even a fix.

**Comment by gabydd** [comment]
Almost all commands make selections and that's by design if you don't want the selection you can add a ``"collapse_selection"`` to the custom command
