### ISSUE TITLE
Ctrl-c doesn't comment the line in OCaml, it uses (* ... *) style comments

### ISSUE THREAD

**Issue by jumpnbrownweasel** [helix-editor/helix#7694]
### Summary

For ocaml in languages.toml we have:

`comment-token = "(**)"`

This puts `(**)` at the start of the line, which has no effect. The line(s) must be surrounded with `(*` and `*)` instead, which isn't currently possible with Ctrl-c.

### Reproduction Steps

I tried this:

1. `Ctrl-c`

I expected this to happen:  Line is commented by surrounding with `(*` and `*)`.

Instead, this happened:

Line is prefixed with `(**)` which has no effect.

### Platform

Linux

### Terminal Emulator

Gnome terminal

### Helix Version

helix 23.05 (9ccca813)

**Comment by jumpnbrownweasel** [comment]
This may require a new feature, so perhaps this should be labeled differently.

One idea is to allow comment-token to be an array of two strings, in which case they are used to surround the line(s). That way an ocaml-specific fix is not needed. I would be willing to try implementing that, or whatever approach is the right way to do it.

**Comment by gabydd** [comment]
we don't currently support this kind of comments, I am working on it though

duplicate of https://github.com/helix-editor/helix/issues/1505

**Comment by jumpnbrownweasel** [comment]
> we don't currently support this kind of comments

Yes, I know.

> , I am working on it though
> duplicate of #1505

Oh, I saw that issue title but didn't realize it will address this. Thanks for working on it!
