### ISSUE TITLE
Building failed with error: "Failed to execute C compiler"

### ISSUE THREAD

**Issue by Alekhine51** [helix-editor/helix#773]
### Environment

- Platform: Fedora 34
- Helix version: v0.4.1

Bug:

```
  Caused by:
      No such file or directory (os error 2)', helix-syntax/build.rs:172:36
  thread '<unnamed>' panicked at 'called `Result::unwrap()` on an `Err` value: Failed to execute C compiler

  Caused by:
      No such file or directory (os error 2)', helix-syntax/build.rs:172:36
  thread 'main' panicked at 'assertion failed: `(left == right)`
    left: `0`,
   right: `28`', helix-syntax/build.rs:201:5

```

The first error was repeated in my terminal several times. The error on the bottom was not. `gcc` is installed and on my PATH. #642 had the same error, and it was fixed by installing `gcc`.

The issue seems to be at least related to the `build_library().unwrap()` function called in `helix-syntax/build.rs', but I don't know enough Rust to debug it.

Any help appreciated, would love to contribute.

**Comment by IceDragon200** [comment]
You may want to install a C++ compiler as well (g++ in your case), the error message is misleading, it may use a C or C++ compiler, but the error message always says C.

**Comment by Alekhine51** [comment]
@JKAnderson409 's answer fixed my issue. Thank you. Would be nice if the README was updated to account for this.
