### ISSUE TITLE
Hide lines without cursor (kakoune-focus)

### ISSUE THREAD

**Issue by Ordoviz** [helix-editor/helix#7746]
Feature request: Add a view mode where you can see all of your cursors even if they are scattered across a big file.

The Kakoune plugin [kakoune-focus](https://github.com/caksoylar/kakoune-focus) does this:

![showcase.gif](https://camo.githubusercontent.com/d589d4875fe203106ad7265f311e576488156a2a283041ca824a531775c5c0ad/68747470733a2f2f63616b736f796c61722e6769746875622e696f2f6b616b6f756e652d666f6375732f666f6375732e676966)

This could be a solution to #2103.

**Comment by woojiq** [comment]
Not exactly but similar to https://github.com/helix-editor/helix/issues/7603

**Comment by pascalkuthe** [comment]
yeah we are already tracking basically the same thing in https://github.com/helix-editor/helix/issues/7603 so I am closing this in favor of that so we don't have a bunch of issues for the same thing
