### ISSUE TITLE
Allow to discard the primary selection.

### ISSUE THREAD

**Issue by radical3dd** [helix-editor/helix#775]
When we have multiple selections, we have a command to `keep_primary_selection`, but not a command to discard the primary selection.

This can be useful when on a multiple selection we want to exclude some selection to the change we want to make.

Kakoune has the same command under `<a-space>`.

**Comment by kirawi** [comment]
I think this can be closed 2e0803c8d9ec0028c0d018be251c7c2b781247b3
cc @archseer
