### ISSUE TITLE
`clangd` doesn't find additional include directories

### ISSUE THREAD

**Issue by danielwolbach** [helix-editor/helix#778]
### Reproduction steps

I have a `clangd` config file that looks like this:

```yaml
CompileFlags:
  Add: [-Iinclude, -Isource, -Wall, -std=c++17]
```

Now I open Helix in my projects root using `hx .` and open a file. I get an error from the LSP because an included file was not found. The file lies in the `include` directory of my projects root, which should be added as an include path due to the `-Iinclude` flag.

I don't know why this happens, I thought it would be because of a wrong working directory but I checked the log and it says that `clangd` uses the correct working directory.

### Environment

- Platform: Fedora Linux
- Helix version: 0.4.1

**Comment by zancas** [comment]
@octowaddle it seems like, by default, `helix` might not be able to see files that are mentioned in project's `.gitignore`.   Could this be part of your issue?

**Comment by octowaddle** [comment]
I don't think so. I also got some errors because I used C++17 features and `clangd`, when not configured otherwise, assumes that you use a prior C++ standard. But after I added the configuration file with the `-std=c++17` flag the errors went away so it must have read the file.

**Comment by archseer** [comment]
It seems that the file should be named `.clangd`, not `clangd`?

> project configuration: a file named .clangd in the source tree. (clangd searches in all parent directories of the active file).

**Comment by archseer** [comment]
There also seems to be a `--enable-config` flag, can you test if adding the flag fixes it?

```
  --enable-config                 - Read user and project configuration from YAML files.
                                    Project config is from a .clangd file in the project directory.
                                    User config is from clangd/config.yaml in the following directories:
                                    	Windows: %USERPROFILE%\AppData\Local
                                    	Mac OS: ~/Library/Preferences/
                                    	Others: $XDG_CONFIG_HOME, usually ~/.config
                                    Configuration is documented at https://clangd.llvm.org/config.html
```

```toml
[[language]]
name = "c"

language-server = { command = "clangd", args = ["--enable-config"] }
```

Though I assume this should be on by default already.

**Comment by skewballfox** [comment]
hey, not sure if we were running into the same issue, but I managed to load my local headers by adding `-I./lib/` to my compile_flags.txt

try adding the dot prefix to the `-I` argument to see if this is a problem with how clang is searching for Include directories

**Comment by pascalkuthe** [comment]
Closing this issue as it's not a problem woth helix at all but rather an issue about configuring clangd correctly
