### ISSUE TITLE
Add indent queries for Java

### ISSUE THREAD

**Issue by pengshao** [helix-editor/helix#7789]
### Summary

The indentation works correct when pressing Enter in a closed {}, but in an already expanded {..}, the cursor aligns with { instead of { + 4 spaces.

For example. If I hit enter at this cursor location, it correctly places cursor at expanded location

(hit enter now)
![image](https://github.com/helix-editor/helix/assets/764148/be55713d-3486-41b9-bfaa-8a6c9b968384)
(all looks good)
![image](https://github.com/helix-editor/helix/assets/764148/d4e23f56-c372-4ac6-afac-ba3993808e29)

On the other hand, if I hit "o" at any where on the function definition line, the cursor however is placed at wrong location:
(hit o)
![image](https://github.com/helix-editor/helix/assets/764148/7c348392-e7b7-4379-ab0a-239509bd9474)
(it aligns with the function definition block, not the expected place)
![image](https://github.com/helix-editor/helix/assets/764148/c7d137ac-b74e-486b-bf88-eb67b067cf73)

This seems only happens to Java. For rust for example it works normally.

### Platform

Linux

### Terminal Emulator

kitty 0.29.2 

### Helix Version

helix 23.05 (57952c46)

**Comment by pascalkuthe** [comment]
the reason for this behavior is that Java is currently missing indent queries. Without indent queries indent is very limited and will have many rough edges. Adding indent queries shouldn't be hard, the indent queries for other languages can be used as an example
