### ISSUE TITLE
Can not start helix: Failed to initialize logging

### ISSUE THREAD

**Issue by glennDittmann** [helix-editor/helix#7790]
### Summary

When trying to run helix I get:
```
Error: failed to initialize logging

Caused by:
    No such file or directory (os error 2)
```

Installed with brew on macOS. I also tried reinstalling, but the problem persists.

So it appears to me that some (log) files are missing. But wouldn't helix create them if there are none?
Thanks for any help in advance.

### Reproduction Steps

 

I tried this:

1. `hx`

I expected this to happen:

Helix starts running.

Instead, this happened:

```
Error: failed to initialize logging

Caused by:
    No such file or directory (os error 2)
```

### Helix log

<details><summary>~/.cache/helix/helix.log</summary>

```
please provide a copy of `~/.cache/helix/helix.log` here if possible, you may need to redact some of the lines
```

</details>

### Platform

macOs

### Terminal Emulator

Alacritty (with Zellij)

### Helix Version

helix 23.05 (7f5940be)

**Comment by glennDittmann** [comment]
Okay manually creating a directory `~/.cache/helix` with an empty `helix.log` resolved this. But still it seems that helix should have done that, right?

**Comment by nikaro** [comment]
I had the same issue, for whatever reason the `~/.cache` and `~/.cache/helix` folders had been created with `root` as owner.

**Comment by Myortv** [comment]
Is it possible to alternatively try to create cache dir in the /tmp?

If I running user with no home directory, I can't run helix.

**Comment by spkane** [comment]
I also had this issue and it was related to ownership.

```
$ ls -lFa ~/.cache/helix
total 0
drwxr-xr-x@  3 root    staff   96 Feb  6 16:15 ./
drwxr-xr-x  21 spkane  staff  672 Feb  9 06:01 ../
-rw-r--r--@  1 root    staff    0 Feb  6 16:15 helix.log
```

- `sudo chown -R spkane:staff ~/.cache/helix` fixed it in my case.

It might make sense to expand the error a bit, with a few troubleshooting hints, since this appears to happen under at least a few occasions.

**Comment by adenoz** [comment]
Just wanted to thank those in this thread. I just setup a new system and was having this same problem. I suspect, like with @nikaro , the first thing I did was edit a system config as root. Doing the `chown` command as per @spkane fixed things for me too. A quick search and finding this thread sorted me, so again just leaving positive vibes to those random internet persons who have provided me a quick fix.
