### ISSUE TITLE
Cursor jumps between the center two lines with high scrolloff

### ISSUE THREAD

**Issue by jnowls** [helix-editor/helix#7824]
In vim, if you have a scrolloff value larger than the size of the viewport, you can basically emulate having the cursor at the center of the screen at all times (unless near the beginning of the file).

In helix, this is _almost_ possible, the only issue is that if the number of lines in the viewport is even, it bounces between the two. In vim, it seems to always pick the bottom line.

Would be really appreciated if it would be possible to emulate the behaivour we see in vim.

**Comment by gabydd** [comment]
see also https://github.com/helix-editor/helix/issues/3265
