### ISSUE TITLE
something eqivalent  to vim's c-p and c-n

### ISSUE THREAD

**Issue by human154** [helix-editor/helix#7902]
In vim I use c-n and c-p all the time to complete with existing words in the file. In helix, when i'm in insert mode c-x (autocomplete) does nothing. Maybe requires some setup, but it would be great if it could try to complete the word the way vim's c-n and c-p do.

**Comment by the-mikedavis** [comment]
Duplicate of https://github.com/helix-editor/helix/issues/1063

**Comment by human154** [comment]
Thanks for all your work @the-mikedavis !!!!
