### ISSUE TITLE
index out of bounds

### ISSUE THREAD

**Issue by elfeiin** [helix-editor/helix#7905]
### Summary

Index out of bounds when pressing return in edit mode. Running on tty under nix.

### Reproduction Steps

 

I tried this:

1. `hx file`
2. `A<return>`

I expected this to happen:
new line
Instead, this happened:
![IMG_20230810_153900](https://github.com/helix-editor/helix/assets/45273247/5a86c775-8eda-43e5-80b1-189982789684)

with RUST_BACKTRACE=1:
![IMG_20230810_155152](https://github.com/helix-editor/helix/assets/45273247/e626393e-5664-4650-9140-2ffca6cca0ae)

### Helix log

<details><summary>~/.cache/helix/helix.log</summary>

not much useful herehere i don't think

![IMG_20230810_155234](https://github.com/helix-editor/helix/assets/45273247/4d7b4d52-3ac6-4a49-b757-85629101587b)

</details>

### Platform

NixOS Linux

### Terminal Emulator

bash

### Helix Version

helix 23.05

**Comment by elfeiin** [comment]
I have no idea what caused this but it only happens when editing a file

**Comment by gabydd** [comment]
See: https://github.com/helix-editor/helix/issues/7896#issuecomment-1673230947
