### ISSUE TITLE
Support opening a folder with goto_file

### ISSUE THREAD

**Issue by cbr9** [helix-editor/helix#7906]
When the selection points to a folder and the user uses `goto_file` (gf), the editor will raise an error.

I would propose that it opens a file picker with the elements of the folder, similar to when you launch helix by passing it a folder name.

Thoughts?

(I could work on a PR, with some guidance)

**Comment by woojiq** [comment]
Sounds logical for me. Though I didn't get into situations where I might need it. Probably I just don't write a lot of raw text.
If you want to start this PR, you need to start looking for the code here:
https://github.com/helix-editor/helix/blob/929eb0c39e34f8046b5ec9ecfede4ec80b5e0c8a/helix-term/src/commands.rs#L1146-L1147
And here an error occurs:
https://github.com/helix-editor/helix/blob/929eb0c39e34f8046b5ec9ecfede4ec80b5e0c8a/helix-term/src/commands.rs#L1193-L1195
To find out how to "open a picker" you can look at impl of commands like "Open file picker".
