### ISSUE TITLE
Create an alternative default theme for 16 color terminals

### ISSUE THREAD

**Issue by Omnikar** [helix-editor/helix#791]
#699 is merged, so Helix now supports 16 color themes, but there currently don't exist any that ship with the editor. Since, if a user is using a 16 color terminal, they wouldn't be able to use the default theme, I think it could be a good idea to create a 16 color theme and embed it in the editor just like the default theme, and then, if the user doesn't have a theme configured, detect whether their terminal supports full color, and use the 16 color alternate default theme if it doesn't.

**Comment by pickfire** [comment]
A use case for this is when using helix in linux console (tty).

**Comment by raygervais** [comment]
I'd like to try this out, leveraging sources such as http://chriskempson.com/projects/base16/ I figure adding base16-default-dark and base16-eighties would make good additions. 

Will prob reach out regarding the best spot to look / update for the second ask, which is detecting the environment and switching themes.

**Comment by MaxVerevkin** [comment]
Another use case: if I understood correctly, changing terminal theme would immediately change the editor theme. For example, terminal can automatically switch to dark theme when needed, and it would be nice if helix switched too.

**Comment by archseer** [comment]
Fixed in #1078
