### ISSUE TITLE
[UX] Lag on closing file picker/buffer picker

### ISSUE THREAD

**Issue by fonol** [helix-editor/helix#7917]
Hi, 
I was wondering if anyone else was experiencing this. For context, I have a beefy machine, and helix generally feels very snappy. My projects where I use it are mostly small-ish, and the file picker or buffer picker open without any perceivable delay. However, closing either of them with `Esc` feels laggy. Nothing dramatic, but very perceivable compared to the rest of the editor interactions. I would guesstimate its somewhere in the 800-1200ms range until the UI is updated.

**Comment by pascalkuthe** [comment]
Does this also occur with #7814? That PR replaces all (performance sensitive) internals of f the picker so it doesn't make sense to investigate the perf of the master implementation.

If the issue still occurs I guess it might be that freeing the memory allocated by the picker takes some time. We could run the drop async instead I guess. 

Are you on windows? The allocator there tends to be a lit slower so this may also be solved by switching to mimalloc

**Comment by gabydd** [comment]
Is escape also laggy when going from insert mode to normal mode cause this could be: https://github.com/helix-editor/helix/wiki/Troubleshooting#when-using-tmux-or-screen-there-is-a-delay-after-hitting-escape-before-its-registered

**Comment by pascalkuthe** [comment]
yeah that's much more likely. I keep forgetting about that :D Drop taking too long would be pretty niche

**Comment by fonol** [comment]
> Is escape also laggy when going from insert mode to normal mode cause this could be: https://github.com/helix-editor/helix/wiki/Troubleshooting#when-using-tmux-or-screen-there-is-a-delay-after-hitting-escape-before-its-registered

That did it! Thank you so much. I suspected iTerm for a while, but didn't find any suspicious setting, but somehow it never occurred to me to check tmux.
