### ISSUE TITLE
Goto files should be relative to the path of the current file

### ISSUE THREAD

**Issue by michaelBelsanti** [helix-editor/helix#7949]
Currently, `goto files in selection` (gf by default) uses the current working directory when going to a selected file. Most files I have ever worked with are referring to other files based on the files position, not on the base of a project. I think changing this would make it much more intuitive.

**Comment by pascalkuthe** [comment]
duplicate of https://github.com/helix-editor/helix/issues/1701#issuecomment-1050468135
