### ISSUE TITLE
Hacktober Badge

### ISSUE THREAD

**Issue by raygervais** [helix-editor/helix#795]
#### Describe your feature request

Hey! I've been using Helix quite a bit recently (coming from a Vim background) and wanted to contribute some docs, themes and updates during Hacktober. Is it possible for you to add the tag to the repo, or even to individual PRs so it counts towards Hacktober? If you decline, I completely understand; PRs incoming anyways :man_technologist:

**Comment by pickfire** [comment]
I added the label to the repository but for issues where you want to work on you can just ask us to put a label for `hacktoberfest`.

**Comment by raygervais** [comment]
Thank you @pickfire
