### ISSUE TITLE
Consider support for Deno LSP. 

### ISSUE THREAD

**Issue by mindreframer** [helix-editor/helix#7978]
https://deno.com/, https://deno.land/ is an alternative JS runtime. It is also written in Rust and brings LSP support directly into the main binary file. 

It would be great to have it supported in Helix.

**Comment by woojiq** [comment]
Temporarily until it is added to `languages.toml` inside the helix repo, you can add it to your personal `languages.toml` configuration file.
Also see: https://docs.helix-editor.com/master/languages.html.

**Comment by mindreframer** [comment]
@woojiq Oh wow, interesting! Thanks for the suggestion!

**Comment by the-mikedavis** [comment]
You can switch the js/ts servers to Deno in your `~/.config/helix/languages.toml`: https://github.com/helix-editor/helix/wiki/How-to-install-the-default-language-servers#deno
