### ISSUE TITLE
A command to quickly copy current location

### ISSUE THREAD

**Issue by sh7dm** [helix-editor/helix#7980]
A command (proposal: `:loc`/`:l`) should copy current path and line number to the clipboard (either only primary or both clipboard and primary). Example use case: saving locations for future editing or setting breakpoints on debuggers not running in Helix

**Comment by lielfr** [comment]
Hi, is this available to work on?

**Comment by sh7dm** [comment]
Should be, but unsure whether maintainers approve the idea

**Comment by lielfr** [comment]
I see, thanks. if they approve, I'd happily work on this one :)

**Comment by pascalkuthe** [comment]
Hmm I don't really think I am really want an extra command here. I think I prefer the registers-based approach or command expansion based approach. I don't think I would want to see yet another set of dedicated commands. See also #7940


This is also a duplicate of #2985
