### ISSUE TITLE
Ability to add keyboard layouts working like other editors (VSCode, IntelliJ, etc)

### ISSUE THREAD

**Issue by mrkafk** [helix-editor/helix#7984]
Love the editor, but dislike VIM-like key bindings. Given the existence of normal/edit mode not everything can be mapped to work like elsewhere.

Say this:
```
[keys.normal]
C-s = ":w" 
```
does not work like in most editors, because I obviously have to exit edit mode to normal for this to work.

Plenty of people are not comfortable with vim modes, it imposes too much cognitive load and what it saves on advanced text operations it loses on trivial stuff like "Esc, :, w, Enter". Four keystrokes instead of one. 

I'd love to work using Helix with IntelliJ keyboard shortcuts.

Or at least another solution can be added: feature to add keyboard shortcuts that work in both modes. For now `Ctrl-s` in edit mode doesn't do anything.

**Comment by pascalkuthe** [comment]
https://github.com/helix-editor/helix/blob/master/docs/vision.md

Helix is fundamentally a modal editor. This is one of our core design values and we are not interested in supporting other editor paradigms. if you don't want to use modal editing then Helix is not the right editor for you
