### ISSUE TITLE
Wrong link in the documentation for building from source on Windows

### ISSUE THREAD

**Issue by bluthej** [helix-editor/helix#8011]
There are two "Windows" links in the toc of the [Installation page](https://docs.helix-editor.com/install.html) of the documentation, but they both link to the [same place](https://docs.helix-editor.com/install.html#windows).

That's because in the md file both sections have the same title and there is no way to distinguish between the two.

The fix is to either rename one of the sections, or (if it's allowed) to use HTML style headers which can be referenced using an arbitrary name:

```html
<h3 id="build-from-source-windows">Windows</h3>
```

**Comment by neduard** [comment]
Hey @bluthej I had a look and luckily this has recently been fixed in https://github.com/helix-editor/helix/pull/10619/files

Have a look at https://docs.helix-editor.com/master/ for the most recent docs - the installation has been split into two pages: "Package Managers" and "Building From Source"
