### ISSUE TITLE
Allow visualizing inlay hints on right-hand side of the code

### ISSUE THREAD

**Issue by Jarema** [helix-editor/helix#8025]
After playing for some time with

```toml
[editor.lsp]
display-inlay-hints = true
```

I think that inlay hints would work better if by default, or optionally, could be rendered on the right-hand side of the code, instead of being interleaved with it.

Beyond preference, that would also make it easier to not mess up the indentation and sometimes - the cursor.

[vim rust tools](https://github.com/simrat39/rust-tools.nvim) uses this approach.

example comparison from `asyn-nats` crate:
<img width="1671" alt="Screenshot 2023-08-21 at 08 16 21" src="https://github.com/helix-editor/helix/assets/7369771/717bef50-b4e3-435b-a5f9-7b1fe984049d">

**Comment by kirawi** [comment]
IIRC, they don't do it like we do because their virtual text is not robust enough to interleave. I'm not sure if there are blockers, but @pascalkuthe might know better.
