### ISSUE TITLE
Can't build master with rust-toolchain.toml

### ISSUE THREAD

**Issue by swarnimarun** [helix-editor/helix#8044]
### Summary

Can't build master with rust-toolchain.toml

### Reproduction Steps

```sh
git clone https://github.com/helix-editor/helix.git
cargo install --path helix-term
```

### Helix log

No logs.

### Why?

Well time is a dependency and it only supports two minor versions prior to latest stable, so we should have updated rust-toolchain.toml a while ago.

```sh
error: failed to compile `helix-term v0.6.0 (../helix/helix-term)`, intermediate artifacts can be found at `../helix/target`

Caused by:
  package `time v0.3.27` cannot be built because it requires rustc 1.67.0 or newer, while the currently active rustc version is 1.65.0
  Either upgrade to rustc 1.67.0 or newer, or use
  cargo update -p time@0.3.27 --precise ver
  where `ver` is the latest version of `time` supporting rustc 1.65.0
```

All paths have been shortened to be non-specific to my system.

### Platform

macOS

### Terminal Emulator

wezterm

### Helix Version

master

**Comment by pascalkuthe** [comment]
You must use the `--lockes ` flag as shown in the documentation
