### ISSUE TITLE
Bad language config: unknown field `language-servers`

### ISSUE THREAD

**Issue by pvamshi** [helix-editor/helix#8045]
### Summary

I get the following error when I open `hx`

```
Bad language config: unknown field `language-servers`, expected one of `name`, `scope`, `file-types`, `shebangs`, `roots`, `comment-token`, `text-width`, `soft-wrap`, `config`, `auto-format`, `formatter`, `diagnostic-severity`, `grammar`, `injection-regex`, `language-server`, `indent`, `debugger`, `auto-pairs`, `rulers`, `workspace-lsp-roots`
in `language`

Press <ENTER> to continue with default language config

```

### Reproduction Steps

Added `~/.config/helix/languages.toml` 

```
 [[language]]
 name = "typescript"
 language-servers = [  "typescript-language-server"]
```

Opening `hx` gives the above error. 
I am trying simplest config to emulate the error.

### Helix log

the log was blank 

### Platform

macOs

### Terminal Emulator

kitty

### Helix Version

helix 23.05 (7f5940be)

**Comment by CptPotato** [comment]
There was a change to how language servers are defined when support for multiple LSPs per language was added (#2507).

This happened *after* the latest release, so you're trying to use newer configuration options with an a version of helix that uses the old ones.

Your options are this:

- use the old syntax: `language-server = "typescript-language-server"`
- build helix' current master branch from source
- wait for the next release (which should not be *that* far off)

**Comment by pvamshi** [comment]
Installed from master. Working fine now thanks
