### ISSUE TITLE
Allow indent-guides to be enable in `languages.toml`

### ISSUE THREAD

**Issue by gozes** [helix-editor/helix#8054]
At the moment trying to set  `editor.indent-guides.render` to `true` but only for specific languages.  yaml and maybe python in my case.  Looking at the docs, and the helix src, I can't see a way for me to reach `indent-guides.render` in a `[[languages]]` table group. 

it would be great if it was possible to enable this at the language level instead of just globally so that I could enable indent guides only for languages where indentation is significant

**Comment by pascalkuthe** [comment]
This will be covered by https://github.com/helix-editor/helix/issues/8853 closing on favor of that
