### ISSUE TITLE
T<ret> on windows selects the previous newline

### ISSUE THREAD

**Issue by sicher** [helix-editor/helix#8057]
### Summary

Pressing `T<ret>` on a line of text has the same effect as pressing `F<ret>`, the previous newline is selected:

![image](https://github.com/helix-editor/helix/assets/65613/243ba293-190f-425a-904f-c286d67dff0f)

Note that setting line-ending to `lf` makes `T` behave correctly.

### Reproduction Steps

1. Put cursor on a line of text.
2. Press `T<ret>`

### Platform

Windows

### Terminal Emulator

Windows Terminal Version: 1.17.11461.0

### Helix Version

helix 23.05 (7f5940be)

**Comment by kirawi** [comment]
https://github.com/helix-editor/helix/blob/79c04251547e6c0c21366d322e268a6581c0f5dd/helix-term/src/commands.rs#L1270-L1276

**Comment by berserkin1337** [comment]
> https://github.com/helix-editor/helix/blob/79c04251547e6c0c21366d322e268a6581c0f5dd/helix-term/src/commands.rs#L1270-L1276

Can we do something like 
```rust
                let le = doc!(cx.editor).line_ending.as_str();
                if le.len() == 2 && Direction::Backward == direction {
                    le.chars().nth(1).unwrap()
                } else {
                    le.chars().next().unwrap()
                }

```
In here 
https://github.com/helix-editor/helix/blob/79c04251547e6c0c21366d322e268a6581c0f5dd/helix-term/src/commands.rs#L1359-L1375,
We could change the last line to 
```rust
        search::find_nth_prev(text, ch, pos, n)
            .map(|n| (n + 1).min(text.len_chars()))
            .map(|n| next_grapheme_boundary(text, n))
            .map(|n| prev_grapheme_boundary(text, n))

```
