### ISSUE TITLE
Expose "reset" color value in themes

### ISSUE THREAD

**Issue by chtenb** [helix-editor/helix#8075]
[The Color struct has a Reset value](https://github.com/helix-editor/helix/blob/e216e9621e73cda1968632cd20595231af5e07be/helix-view/src/graphics.rs#L215-L237), which should reset the color to the default terminal foreground or background. But this doesn't seem to be exposed to be used in themes, as far as I could find anyway.

Being able to access the default fg/bg colors in a theme is useful, because they may differ from the 16 colors/256 colors in the terminal color palette. In curses, the default color can be called with the number `-1`, while the colors are called with numbers `0..255`. I have no preference if helix should expose it like this or rather something else.

**Comment by the-mikedavis** [comment]
I believe we just need to add `reset.to_string() => Color::Reset` to the default palette:

https://github.com/helix-editor/helix/blob/aeaeb09f486c2bc7f8c563bceece03a0954576b9/helix-view/src/theme.rs#L358-L381
