### ISSUE TITLE
Wrong markdown rendering with clangd

### ISSUE THREAD

**Issue by aodhneine** [helix-editor/helix#808]
**Version**: latest `master`.

When using the "hover" functionality of LSP under clangd, the markdown is being rendered improperly:

![grim_1633335019](https://user-images.githubusercontent.com/11488344/135816090-04850d88-5e7c-474f-9a84-b0bba2ea5029.png)

The line breaks are missing, and text is rendered in wrong places (parameters inside the function sigature, for example.)

This is how [kakoune](https://github.com/mawww/kakoune) renders the documentation for that function, which is also the expected behaviour:

![grim_1633335031](https://user-images.githubusercontent.com/11488344/135816091-7f13dcc0-d8e9-4e5a-afa4-01bde777fcb1.png)

Note that the same issue doesn't occur with other languages, such as Rust:

![grim_1633335237](https://user-images.githubusercontent.com/11488344/135816551-52e1edc1-34ad-4e79-a07e-b864a0136e26.png)

This could be a bug in clangd though... not sure as I'm not familiar with the codebase of helix, so can't really check it. Possibly related to clangd/clangd#95?

**Comment by archseer** [comment]
The parameter list is probably missing because we don't handle bullet lists, logs should be able to tell you more: https://github.com/helix-editor/helix/blob/8925fdd6f3afa3532c928a5c6e1357bc15201d8a/helix-term/src/ui/markdown.rs#L180

For the missing line breaks I'll have to do some testing.

**Comment by gabydd** [comment]
this seems to have been fixed, I think in: https://github.com/helix-editor/helix/pull/2687
