### ISSUE TITLE
Highlight `.ignore` files (and other `\.(\w)*ignore` files)

### ISSUE THREAD

**Issue by yoav-lavi** [helix-editor/helix#8089]
[ripgrep](https://github.com/BurntSushi/ripgrep) allows the definition of `.ignore` files (see [here](https://github.com/BurntSushi/ripgrep/blob/master/GUIDE.md)) which take higher precedence over `.gitignore` files and share the same syntax. 

I propose using the same rules to highlight / same LSPs for both. 

(If Helix uses regex for file extensions the extension could be changed from `/\.gitignore/` to `/\.(git)?ignore/`)

**Comment by yoav-lavi** [comment]
There's also other various files like .prettierignore that could be considered

**Comment by pascalkuthe** [comment]
#8006 does not affect file extensions and this case doesn't need a regex either. You can just list out all variants manually: `[".gitignore", ".ignore"] `

**Comment by rossmanch** [comment]
Hey - not done any open source before so this looked like it might be an easy one to start with, so I opened that PR.
