### ISSUE TITLE
Allow file path highlighting / icons in the file picker by extension / type

### ISSUE THREAD

**Issue by yoav-lavi** [helix-editor/helix#8090]
May be useful to allow highlighting file paths or adding icons next to file paths (nerd font / unicode / emoji) in the file selector (space+f) based on extension or language type, for easier definition.

GUI file editors normally do this using icons.

TBD if this will be too messy visually, but thought I'd bring it up and see what people have to say about it.

I'm aware there's a new file tree being worked on, could be part of that as well.

**Comment by pascalkuthe** [comment]
ee https://github.com/helix-editor/helix/pull/2869 closing since I don't think we need another issue for this

**Comment by yoav-lavi** [comment]
@pascalkuthe that issue only refers to icons as an option and not colors, but as long as they're linked hopefully this is visible
