### ISSUE TITLE
Highlight CODEOWNERS files

### ISSUE THREAD

**Issue by yoav-lavi** [helix-editor/helix#8091]
Currently CODEOWNERS files (e.g. `.github/CODEOWNERS`) are not highlighted and treated as plain text

**Comment by pascalkuthe** [comment]
Any language suooer in helix needs its own tree sitter grammar. CODEOWNERS seems a bit niche to get its own file but it uses basically the same syntax as .gitignkre files so adding that as an additional filename there seems reasonable to me
