### ISSUE TITLE
Highlight `.env` / `.envrc` files

### ISSUE THREAD

**Issue by yoav-lavi** [helix-editor/helix#8092]
Both are currently treated as plain text.

For `.env` it would probably be best to include `\.env(\.(\w)+)?`, `.envrc` could do the same or just `.envrc.example` as a single addition to `.envrc`

**Comment by yoav-lavi** [comment]
(I *think* `.env` shares the same syntax as .ini and `.envrc` the same as `.sh` but TBD)

**Comment by dob9601** [comment]
I did some searching around and it seems vim, amongst other editors, treat `.env`s as a shell file too: https://github.com/vim/vim/blob/e5f7cd0a60d0eeab84f7aeb35c13d3af7e50072e/runtime/filetype.vim#L1974

I've been looking for an issue to get me started contributing to helix and will happily pick it up later today if it hasn't been done

**Comment by dob9601** [comment]
Hmm, env highlighting already seems to exist for .env and .envrc via the bash grammar:
https://github.com/helix-editor/helix/blob/13d4463e4146473391e37b7f75e99b731aa55878/languages.toml#L2262-L2270

I've opened up an editor and can also confirm that the highlighting is being applied.

@yoav-lavi is there any chance your local `languages.toml` is overriding the configuration of the default one?

**Comment by dob9601** [comment]
Looking into it, it doesn't seem like `.ini` and `.env`/`.envrc` share the same syntax - `.ini` supports sections - similar to TOML.

With Sublime, it looks like `.env` (and `.envrc`) are both treated as a subset

Might be that the `file-types` to be relaxed a bit

**Comment by yoav-lavi** [comment]
You're likely right, I must have looked at a `.env(rc)?.example` file, as I have `.env(rc?)` files ignored. I don't think the current mechanism supports wildcards though, maybe we could add the common variants manually

**Comment by dob9601** [comment]
I could see wildcard filename support being useful anytime you've got a file with a local override. It might be better to do the extra work to add wildcard support but open to opinions on that one

**Comment by pascalkuthe** [comment]
closed by #4536
