### ISSUE TITLE
Changing whole-line selection should keep original indentation

### ISSUE THREAD

**Issue by clo4** [helix-editor/helix#8124]
#7316 being merged is a great improvement, I think it was definitely the right choice! It's way more ergonomic most of the time.

There's one thing that consistently bothers me with it though, which is that it indents to the line *below* the one that you're editing. I'm frequently changing things at the bottom of a block of indentation, which means I need to indent every time I type `xc`.

An example of this behavior (`|` is the cursor)

```
begin
    This is line 1
    This is line 2|
end
```
Then after `xc`
```
begin
    This is line 1
|
end
```
What I think the correct behavior should be:
```
begin
    This is line 1
    |
end
```

The solution (I think) is to use the line's original leading whitespace instead of doing what `xcO` would have done before.

**Comment by pascalkuthe** [comment]
this is a bug in what ever language indent queries that is, this does not happen with rust on laste master

**Comment by clo4** [comment]
Interesting. I'll have a look at fixing the queries then.
