### ISSUE TITLE
Picker result count not being displayed

### ISSUE THREAD

**Issue by ArchUsr64** [helix-editor/helix#8153]
### Summary

The prompt in the picker box is supposed to have a right aligned field displaying the the number of matches to the total number of options (highlighted in red) but is not visible in the latest upstream.
### Helix 23.05 (working as expected):
![working](https://github.com/helix-editor/helix/assets/83179501/38e73f06-f84b-4e5a-b34b-bb40ec7f3df0)

### Latest Upstream:
![image](https://github.com/helix-editor/helix/assets/83179501/b1144302-1308-4c89-bea1-e92e3f398523)
Tested on the latest commit as of writing, a38ec6d6ca9e5dbbd2e313f3173f2e967ed71fc1

### Platform

Linux

### Terminal Emulator

Alacritty

### Helix Version

helix 23.05 (aa42eb6b)

**Comment by woojiq** [comment]
I can reproduce this on d6bb1092 but on a38ec6d6ca9e5dbbd2e313f3173f2e967ed71fc1 it looks ok for me. Are you sure you compile and run latest master?

**Comment by ArchUsr64** [comment]
Yeah, you're right. It was my git remotes being configured improperly.
