### ISSUE TITLE
Health check subcommand doesn't display multiple language servers

### ISSUE THREAD

**Issue by EpocSquadron** [helix-editor/helix#8156]
## Problem Statement

I have PHP configured with multiple language servers as follows:

```toml
[[language]]
name="php"
language-servers=["psalm", "intelephense"]

[language-server.psalm]
command="psalm"
args=["--language-server"]
```

When I run `hx --health php` only the first configured language sever shows up in the checks:

```
$ hx --health php
Configured language server: psalm
Binary for language server: /usr/bin/psalm
Configured debug adapter: None
Highlight queries: ✓
Textobject queries: ✓
Indent queries: ✓
```

## Possible Solutions

We should print all of the language servers configured and whether they are picking up the binary. This is more challenging when not filtering to a specific language, as we have the table view to deal with and probably don't want to display a pair of columns for every configured language server. This would be especially painful for things like Svelte, where there can be quite a few language servers defined for eslint, tailwind, svelte, typescript, and possibly others.

It might be best if we instead stacked them within the columns like so:

```
$ hx --health
Language                  LSP                       DAP                       Highlight                 Textobject                Indent                   
php                       ✓ psalm                   None                      ✓                         ✓                         ✓      
                          ✓ intelephense                   
rust                      ✓ rust-analyzer           ✘ lldb-vscode             ✓                         ✓                         ✓               
```

Github won't display them for me, but we could use box drawing characters to visually group the language servers for a single language to make the output easier to scan visually.

For output for a single language we could do like so:

```
$ hx --health php
Configured language servers and binary path: 
    ✓ psalm        /usr/bin/psalm
    ✓ intelephense /home/epocsquadron/.node_modules/bin/intelephense
Configured debug adapter: None
Highlight queries: ✓
Textobject queries: ✓
Indent queries: ✓
```

**Comment by kirawi** [comment]
https://github.com/helix-editor/helix/pull/7315

**Comment by mabasic** [comment]
Off topic, I have just tried psalm lsp for php and it is not usable for me. I got it working but whatever I do it does not support. Can't go to definition, no hover documentation, no documents symbols, ... is there anything that is working in psalm lsp?

It has the potential to be a great lsp for php, but seems broken atm.

**Comment by kirawi** [comment]
Can you create a separate discussion thread for that? And in it, include what `:log-open` says after running `hx -v` and opening a PHP project.
