### ISSUE TITLE
Can't remap `.` (dot/period key)

### ISSUE THREAD

**Issue by kmicklas** [helix-editor/helix#8158]
### Summary

With this in my config:

```toml
[keys.normal]
"." = "rotate_view"
M = "rotate_view"
```

The `M` binding (or presumably most other keys) works, but `.` retains its default behavior.

### Reproduction Steps

 

I tried this:

1. `hx`
2. Split the window.
3. Press `.`.

I expected this to happen:
* Moving focus to the other window.

Instead, this happened:
* It repeats the last insert.

### Helix log

No relevant output is produced in `~/.cache/helix/helix.log`.

### Platform

Linux

### Terminal Emulator

alacritty 0.12.0

### Helix Version

helix 23.05

**Comment by kmicklas** [comment]
This is related to https://github.com/helix-editor/helix/issues/1488, but not exactly the same thing, since I have no need to put the original behavior of `.` on a different key.

**Comment by the-mikedavis** [comment]
It's the same as #1488, just a different use-case. `.` and repeating the last command are hard-coded together and separating them would allow rebinding `.` to another command and remapping `repeat_last_command` to another key.
