### ISSUE TITLE
Add support for unison language

### ISSUE THREAD

**Issue by A-Walrus** [helix-editor/helix#8208]
> Unison is a friendly programming language from the future: statically-typed, functional, and a lot of fun 😄 

https://www.unison-lang.org/

tree-sitter: https://github.com/kylegoetz/tree-sitter-unison

LSP: https://github.com/unisonweb/unison/blob/trunk/docs/language-server.markdown

**Comment by the-mikedavis** [comment]
I believe this was already added in https://github.com/helix-editor/helix/pull/7724 except for the language server since it only supports TCP and we only support stdio
