### ISSUE TITLE
The helix editor crash when used in splitted edit mode

### ISSUE THREAD

**Issue by erihsu** [helix-editor/helix#8229]
### Summary

The helix-editor crash and exit with 
```
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Char index out of bounds: char index 18288, Rope/RopeSlice char length 2579', /build/helix-pMThJr/helix-23.03/vendor/ropey/src/slice.rs:360:41
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```
I occur this crash twice when I use editor in split edit mode.

### Reproduction Steps

Not really easy to reproduce

### Platform

5.15.0-76-generic/x86_64 x86_64 x86_64 GNU/Linux

### Terminal Emulator

macOS Terminal

### Helix Version

helix 23.03

**Comment by pascalkuthe** [comment]
Without a reproduction case or a full backtrace this is not actionable. The helix version us also pretty old. You are using 23.3, the latest release is 23.5 and there have been many more bugfixes on master

**Comment by the-mikedavis** [comment]
Yeah, please re-open, comment or create a new issue if you can narrow down the reproduction steps to something concrete and if this is still reproducible on master or the latest release. I suspect this was a jumplist bug fixed somewhere between 23.03 and 23.05

**Comment by erihsu** [comment]
@pascalkuthe @the-mikedavis It's not really easy to reproduce the crash. I have use helix 23.03 for nearly two months and occur this situation only 3 times. I try collect helix log file if this crash come up again next time.

**Comment by vgwidt** [comment]
I'm running helix 23.05 (7f5940be) and just had the same crash
```
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Char index out of bounds: char index 12427, Rope/RopeSlice char length 11768', C:\Users\runneradmin\.cargo\registry\src\index.crates.io-6f17d22bba15001f\ropey-1.6.0\src\slice.rs:360:41
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

I believe I hit `/` to search, upon which it immediately crashed.  I'll work on the same two files again and see if I can reproduce it.

**Comment by the-mikedavis** [comment]
That might be https://github.com/helix-editor/helix/issues/5632. If you can figure out some concrete reproduction steps that are different from #5632 please open up a new issue
