### ISSUE TITLE
~~appending with `a` while cursor at EOL should behave as `A`~~While traversing words in a line with `w`, if `line-ending crlf`, selecting the last word with `w` causes the selection to include EOL. While `line-ending lf` doesn't cause that issue.

### ISSUE THREAD

**Issue by masriomarm** [helix-editor/helix#8257]
### Discussed in https://github.com/helix-editor/helix/discussions/7701

<div type='discussions-op-text'>

<sup>Originally posted by **masriomarm** July 22, 2023</sup>
while cursor at EOL, appending with `a` moves the cursor to the beginning of the next line.
recovering is a bit frustrating. I suggest while cursor is at EOL, appending wiht `a` should behave as appending to the end of line `A`. </div>

**Comment by pascalkuthe** [comment]
You already opened  #8246 for this, which also has a clearer titel so closing this as duplicate
