### ISSUE TITLE
Render line-width indicator line

### ISSUE THREAD

**Issue by lunacd** [helix-editor/helix#8267]
It would be great to have an option to render a line-width indicator line. Something like vim's `:set colorcolumn=80`.

This is really helpful for languages whose formatters don't reflow everything, e.g. rustfmt doesn't reflow comments.

**Comment by gabydd** [comment]
this is already available in helix with rulers: https://docs.helix-editor.com/configuration.html?highlight=rulers#editor-section you can set them for the whole editor or just for a certain language so for rust you could do:
```toml
[[language]]
name = "rust"
rulers = [80]
```
in you ``languages.toml``
another thing to note is if you are not seeing the rulers after they are configured some themes might not style the rulers
