### ISSUE TITLE
Support `formatOnType` feature of LSPs

### ISSUE THREAD

**Issue by poliorcetics** [helix-editor/helix#8269]
VS Code supports ["on type"](https://code.visualstudio.com/docs/editor/codebasics#_formatting). This is formatting sent by the LSP when a trigger sequence matches, for example with [Rust Analyzer](https://github.com/rust-lang/rust-analyzer/blob/15e13561499dbe90ef07cf37a90c1cedafc53e28/crates/ide/src/typing.rs#L42)

Note: for opening brackets (`(`, `{`, `[`), helix would probably need to defer to the LSP for a split second before inserting its own matching end-bracket, to avoid entering `(` in `( my, tuple, variables` (note the space) and getting `() my, tuple, variables)`

**Comment by pascalkuthe** [comment]
that request is a non-standardised LSP extension. We don't support those in core.

I also think this is not necessarily a good thing. We usually don't block the UI on waiting for a LS. Implementing this would block the UI thread whenever any single key is pressed. 

Most of what RA does here is also covered by autopairs/autoindent in helix. The only thing I don't see covered by helix currently is insterting an `=` after typing `let foo` (and then inserting a space) and inserting a space after typing a right arrow `fn foo() ->` automatically.

This will also not play well with multicursors (RA doesn't really support those)
