### ISSUE TITLE
helix command working directory option

### ISSUE THREAD

**Issue by Vulpesx** [helix-editor/helix#8290]
When starting helix you can provide a directory or files but not both, i want both so that i dont have to change my working directory every time i open a file from another program when i want to edit multiple files. also an option to set the dir the file is in as the working directory either from in the editor or from the terminal or both. doesnt seem too hard since you already set the working directory when you only provide a directory

**Comment by archseer** [comment]
`:cd` already exists, https://github.com/helix-editor/helix/pull/8223

**Comment by pascalkuthe** [comment]
Closed by #8223
