### ISSUE TITLE
Add Rio terminal to wiki Terminal-Support

### ISSUE THREAD

**Issue by raphamorim** [helix-editor/helix#8312]
Hey there,

First of all, really love the helix editor. I saw the terminal wiki regarding support https://github.com/helix-editor/helix/wiki/Terminal-Support, I believe Rio (https://github.com/raphamorim/rio) users use helix and I would love to add it to that list (if is possible).

Rio does contain support to kitty keyboard protocol, but please let me know anything is missing to add there :)

**Comment by pascalkuthe** [comment]
The wiki is community editable if you want to add a terminal emulator. Feel free to do that yourself, no need to open an issue

**Comment by raphamorim** [comment]
Thank you @pascalkuthe
