### ISSUE TITLE
x should only select one line even if it is a blank line

### ISSUE THREAD

**Issue by pozix604** [helix-editor/helix#8344]
### Summary

When the cursor is on a blank line, typing "x" will select that line + the next line. This is counter to the tutorial which teaches "Type x to select a whole line".

What this means is that if I wanted to delete the current line, I can't just "xd", because this might delete two lines if the current line is blank. I now need to know if its blank and then do either "d" or "xd". 

It's even worse if the line is not actually blank but has whitespace. Now it's trial-and-error which command would do the right thing.

"x" should select the current line whether it is blank or not.

### Reproduction Steps

Hit "x" on a blank line. The blank line + next line are both selected.

Hit "x" on a non-blank line. Only that line is selected.

### Helix log

<details><summary>~/.cache/helix/helix.log</summary>

```
please provide a copy of `~/.cache/helix/helix.log` here if possible, you may need to redact some of the lines
```

</details>

### Platform

Linux

### Terminal Emulator

KDE Terminal

### Helix Version

23.05

**Comment by gabydd** [comment]
See https://github.com/helix-editor/helix/issues/3077 and some of the linked issues, you probably want ``X`` in this case, it's not planned to change the behaviour of ``x``
