### ISSUE TITLE
Enhance tutorial to clarify what 'x' does

### ISSUE THREAD

**Issue by pozix604** [helix-editor/helix#8346]
The tutorial states:

> Type x to select a whole line. Type x again to select the next.

This is incorrect according to https://github.com/helix-editor/helix/issues/3077, and there is no plan to change the existing behavior. The tutorial should be updated to clearly state the actual behavior to properly set new user expectations.

Suggested wording:

> Type x to select a whole line, unless it is a blank line, in which case it selects the current line and next line. Type x again to select the next after that.

**Comment by pascalkuthe** [comment]
If you have a specific suggestion to improve the docs just open a PR, cresting an issue for a oneline change is uneccesary.

Your understanding I sincorrect tough there is no spwcical case for empty lines. The line terminator is part of the line.

If the current selection is already aligned to line boundaries pressing `x` will add the next line to the current selection, otherwise the selection is extended to line boundaries.

If a line is "empty" that means that the line terminator is selected and therefore the entire line is selected.

Your text makes is sound as tough "empty" lines are somehow spwcical, which is not the case

**Comment by pozix604** [comment]
Your explanation of what x does sounds great. I think we should put that into the tutorial.

**Comment by musjj** [comment]
This is actually a really annoying problem. Let's say you see a (visually) empty line and you want to erase it. 

You'd think the `xd` would just do the trick, but as mentioned previously, this doesn't work for (actually) empty lines. So you have to be a psychic and guess whether you should use `xd` or `d` to remove that one line. Or more realistically, spam undo every 2-3 line operations.

A real line-wise operation mode would fix this, but alas we failed to learn from our predecessors.

**Comment by pozix604** [comment]
> This is actually a really annoying problem. Let's say you see a (visually) empty line and you want to erase it.
> 
> You'd think the `xd` would just do the trick, but as mentioned previously, this doesn't work for (actually) empty lines. So you have to be a psychic and guess whether you should use `xd` or `d` to remove that one line. Or more realistically, spam undo every 2-3 line operations.
> 
> A real line-wise operation mode would fix this, but alas we failed to learn from our predecessors.

I've returned to Vim as a result. Helix favours dogmatic algorithms over ergonomics in multiple ways that many people have complained about but ignore.

**Comment by musjj** [comment]
Yep, I've returned to neovim too. 

I love how fast Helix is; everything feels a lot smoother compared to my neovim setup. The multi-cursor paradigm is also amazing. But in the end I've realized that the core editing primitives is the most important part of the editor for me, and Helix is just not there yet on that aspect.

Note that I'm not saying "why can't helix just be vim" or something like that. I've actually tried seriously learning Helix's editing philosophy from first principles, while holding back any vim biases that I probably have. There are some cool ideas in it, but overall, I just can't shake the feeling of how janky everything is.

And it's not just an issue of muscle memory either. I've poured some serious time brainstorming over the current state of Helix, but there are just some aspects of the editing experience that are objectively inconsistent, unpredictable and inelegant (e.g. this very issue). Unfortunately, fixing them will require real fundamental changes that will probably never happen, considering the direction of this project.

Maybe once there's a flexible-enough plugin API, the user can have better control over the editing experience. Perhaps we can even have a vim emulation layer ala Emacs' `evil-mode`.

**Comment by dead10ck** [comment]
This issue isn't really helpful for tracking any specific issues or units of work. And the criticisms herein are too vague and full of generalisms to be constructive.

Saying the "core editing primitives aren't there yet" is pretty absurd in my opinion, given the number of users who successfully daily drive with Helix. If you have any specific feedback, you are welcome to open a discussion.

And if you'd like to improve the wording of the docs or tutor, PRs are welcome.

**Comment by archseer** [comment]
> I love how fast Helix is; everything feels a lot smoother compared to my neovim setup.

I would suggest that changing the very core of how helix is designed is probably more difficult and unlikely to happen than investing time to make your vim setup faster by improving vim performance.

If our model doesn't fit with you I think that's perfectly fine, there's nothing wrong with using vim.
