### ISSUE TITLE
Support Rust's "open external docs" LSP extension

### ISSUE THREAD

**Issue by paul-hansen** [helix-editor/helix#8348]
https://github.com/rust-lang/rust-analyzer/blob/master/docs/dev/lsp-extensions.md#open-external-documentation

This feature is extremely useful for collaboration as I can just open docs.rs for the thing I'm looking at and share the link. It's also nice when exploring the API of a library to be able to open docs.rs, it has a lot of useful features like showing what traits are implemented that just isn't shown in the normal LSP docs.

**Comment by paul-hansen** [comment]
I'm pretty familiar with Rust but not the Helix codebase or writing LSP support. If anyone familar can point me in the right direction for where this would need to be implemented I'd be willing to take a stab at a PR for this.

**Comment by pascalkuthe** [comment]
We don't allow any LSP extensions in core so thus will have to wait for plugins.
