### ISSUE TITLE
Language-specific configuration

### ISSUE THREAD

**Issue by Omnikar** [helix-editor/helix#836]
#### Describe your feature request

The ability to set specific configuration options which only take effect for files of a specific language, like VSCode's `"[language]"` in `settings.json`.

**Comment by kirawi** [comment]
I think we already have this: [`[languages.config]`](https://github.com/helix-editor/helix/pull/807)

**Comment by Omnikar** [comment]
> I think we already have this: [`[languages.config]`](https://github.com/helix-editor/helix/pull/807)

That is language server config. I am talking about editor configuration specific to files of a certain language.

**Comment by SecretPocketCat** [comment]
I wanted to take a stab at this, but I've encountered a few blockers though.

### Themes

- splits can't be themed on there own, so language-specific themes wouldn't cover everything. Should I create an issue for that or should that be a part a PR for this?

### Editor config

 - `arc_swap` [does not allow a way](https://github.com/vorner/arc-swap/issues/92) to get a way a guarded map entry and I haven't figured out a nice way to get a lang-specific config with a fallback to the default one
 - the lang-specific config should be just a subset of the regular config, right? (E.g. having global search config in a lang-specific config probly doesn't make much sense.

**Comment by SecretPocketCat** [comment]
@pascalkuthe Any pointers or is this just low prio and/or I should take the removal of the easy label as a hint to find something easier to look into 🙂?

**Comment by the-mikedavis** [comment]
Yeah, I don't think it will be very easy to solve this and we may want to wait until we switch from toml to scheme with scripting for configuration: language-specific config could be solved by making config a function of the language or by overriding the configuration by taking the old configuration as a function parameter. Whatever work we would commit for toml-based configuration would probably not fit well with how we would solve this with scheme-based config

**Comment by pascalkuthe** [comment]
closing in favor #8853
