### ISSUE TITLE
`Page Down`/`Page Up` Hide a Line of Code

### ISSUE THREAD

**Issue by sno2** [helix-editor/helix#841]
I am using WezTerm in the images shown, however I can also reproduce this on Windows Terminal (New Version) and CMD.

### Reproduction steps

1. Open Helix
2. Create a text file that spans an area that consumes the height of the terminal
3. Move cursor to top of text
4. Press `{{ Page Down }}`
![image](https://user-images.githubusercontent.com/43641633/137250729-b1eded4b-6552-4a88-9b68-e1448415f27b.png)
5. Press `{{ Page Up }}`
![image](https://user-images.githubusercontent.com/43641633/137250790-11874e6a-b18c-4f69-b323-7c3ba44024f2.png)

Notice how line 33 is never shown as it is hidden by the bottom diagnostic bar.

### Environment

- Platform: Windows
- Helix version: 0.4.1

**Comment by sno2** [comment]
> I am unable to reproduce this on my computer.

What OS/term were you on?

**Comment by Omnikar** [comment]
> What OS/term were you on?

MacOS, iTerm2

**Comment by matoous** [comment]
This sesms to be fixed in latest versions. I couldn't find the commit that addressed this though.
