### ISSUE TITLE
hx crash 

### ISSUE THREAD

**Issue by waalge** [helix-editor/helix#8418]
### Summary

console looked like this: 
```sample
$hx flake.nix
thread 'main' panicked at 'byte_slice(): Byte range does not align with char boundaries: range 227..233', /build/helix-23.05-vendor.tar.gz/ropey/src/slice.rs:703:23
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

### Reproduction Steps

Had helix running fine. Was doing some editting fine. And then it crashed as I was typing

### Helix log

I cannot see any log output from today. 

### Platform

nixos

### Terminal Emulator

alacritty

### Helix Version

helix 23.05 (7f5940be)

**Comment by woojiq** [comment]
Try on the master branch. There have been many bug fixes.

**Comment by pascalkuthe** [comment]
also without a reproduction case this is not actionable.  panic like this could be caused by many many different things. Please provide a reproduction case or this is not actionable.

**Comment by waalge** [comment]
Regarding reproducibility, I was just editing a file. I have re-opened the file and can edit it, and it hasn't crashed. Is there anyway to establish which action caused this?

Given that the version of  helix is out-of-date, we can leave the suggested fix as "bump version". 
If it persists i'll open a new issue.

**Comment by gabydd** [comment]
I believe this was probably fixed by https://github.com/helix-editor/helix/pull/7621, if you had a shell script string in the file it would make sense

**Comment by waalge** [comment]
Thanks - yeah, this does look like a duplicate. Apologies. I tried searching the whole error. Too specific.
