### ISSUE TITLE
feature request: support separate .../config.d/foo.toml and .../languages.d/foo.toml files

### ISSUE THREAD

**Issue by jokeyrhyme** [helix-editor/helix#8425]
Howdie, thanks so much for sharing this project! <3

I've noticed this configuration file convention/pattern adopted by other tools (e.g. PAM, systemd, sudo, TLP, etc) where:
- they might have a single primary configuration file, but
- there'll also be a similarly-named ".d" directory that is a sibling of that file, containing much smaller files that have configuration snippets
- the app/tool, when it read the configuration, merges all the ".d" snippets together, overriding values in the primary configuration file

For me, this allows parts of the configuration to be committed to version control, or generated on the fly, or symbolic links, etc without necessarily having to treat the entire configuration the same way

I'm happy to try implemented this myself, but before starting, I was wondering if there was appetite for such a thing in helix? It would work something like this:
- when reading <config_dir>/helix/config.toml , also read <config_dir>/helix/config.d/*.toml with the latter taking precedence
- when reading <config_dir>/helix/languages.toml , also read <config_dir>/helix/languages.d/*.toml with the latter taking precedence

**Comment by jokeyrhyme** [comment]
It would also be possible to implement such a thing using the upcoming plugin system ( https://github.com/helix-editor/helix/discussions/3806 ) so perhaps it would not be desirable for this to be core functionality?

**Comment by kirawi** [comment]
Yeah, the existing config is just a stopgap until the plugin system lands.
