### ISSUE TITLE
Cannot input certain unicode characters on windows

### ISSUE THREAD

**Issue by chtenb** [helix-editor/helix#8458]
### Summary

It's impossible to input the 🎉 character into helix, either through pasting or directly inserting (using something like wincompose).
The character ✅ poses no problem however.

### Reproduction Steps

Copy the 🎉 from here and try to paste it into helix using whatever method.

### Helix log

The log contains no warnings

### Platform

Windows

### Terminal Emulator

Tried several, including WezTerm, Windows Terminal, cmd.exe

### Helix Version

Custom build based on a recent commit

**Comment by chtenb** [comment]
Possibly related issue due to shared dependencies: https://github.com/nushell/nushell/issues/10578

**Comment by the-mikedavis** [comment]
Looks like an issue upstream in [crossterm](https://github.com/crossterm-rs/crossterm) as they say in the nushell issue

**Comment by pascalkuthe** [comment]
yeah temrinal input (particuarly unicode) on windows is simply a mess and very hard to implement, there are other open issues about that (https://github.com/crossterm-rs/crossterm/issues/820, https://github.com/helix-editor/helix/issues/7129). i don't think the crossterm folks would work on this themselves. I considered fixing https://github.com/helix-editor/helix/issues/7129 myself but I don't ever use windows and don't have access to a windows machine for testing (and don't care enough to setup a VM just for this).

**Comment by CptPotato** [comment]
> I considered fixing [crossterm-rs/crossterm#820](https://github.com/crossterm-rs/crossterm/issues/820), myself but I don't ever use windows and don't have access to a windows machine for testing (and don't care enough to setup a VM just for this).

I'd be happy to test on windows, in case anyone decides to take this on.

**Comment by satorkain** [comment]
Works for me on win10. But only in WezTerm.

![изображение](https://github.com/helix-editor/helix/assets/15098779/d7013382-08ba-47d0-a0d0-3c0e2d626899)

**Comment by chtenb** [comment]
Could it be that somehow you have a different conpty version? I don't really know how this all works, but I've read somewhere that some applications ship their own version of conpty while others depend on the system installed version.
FWIW I'm on windows 11.

**Comment by satorkain** [comment]
I don't know, I have the most stripped down build of win10 that doesn't have a store or even a calculator.

**Comment by kirawi** [comment]
Wezterm packages a version of conpty with it.

**Comment by kirawi** [comment]
I can replicate it on Windows 11 but not Windows 10.

**Comment by pascalkuthe** [comment]
this likely should be reported against crossterm. They developed their windows handling against windows 10 I think.

**Comment by kirawi** [comment]
I will. I also rechecked and I can actually replicate this in both 10 and 11. However, Alacritty on both versions works as expected compared to Windows Terminal and Wezterm.

**Comment by pascalkuthe** [comment]
yeah wezterm uses a different API. I don't really know the ins and outs fo windows input handling but my understanding is that wezterm is the first terminal emulator besides windows terminal to use a certain API so its likely related to that API.

**Comment by kirawi** [comment]
Two possibly related issues I found were https://github.com/microsoft/terminal/issues/190 and https://github.com/PowerShell/PSReadLine/issues/1329

**Comment by chtenb** [comment]
> this likely should be reported against crossterm. They developed their windows handling against windows 10 I think.

Should I create an issue in the crossterm issue tracker for this?

**Comment by chtenb** [comment]
This issue does not reproduce anymore for me on the latest release. Not sure if fixed by windows updates or crossterm updates.

**Comment by chtenb** [comment]
Still occurs on wezterm, I created https://github.com/wez/wezterm/issues/5260 for that
