### ISSUE TITLE
macOS segmentation fault

### ISSUE THREAD

**Issue by Siebjee** [helix-editor/helix#8462]
### Summary

`hx my_package/main.py` produces an segmentation fault upon entering insert mode and adding content. Eg pressing `o`,

### Reproduction Steps

 

I tried this:

1. `hx <my python file>`
2. presing `o`

I expected this to happen:
Entering insert mode on a new line below cursor.

Instead, this happened:
Segmentation fault.

### Helix log

<details><summary>~/.cache/helix/helix.log</summary>

```
2023-10-04T12:34:20.128 helix_view::editor [ERROR] Failed to initialize the LSP for `source.python` { cannot find binary path }
```

</details>

### Platform

macOS 14.0

### Terminal Emulator

iTerm2 Build 3.4.20

### Helix Version

helix 23.05 (7f5940be)

**Comment by Siebjee** [comment]
Even after installing `python-lsp-server` it segfaults.
```
❯ hx --health
Config file: default
Language file: default
Log file: /Users/siebjee/.cache/helix/helix.log
Runtime directories: /Users/siebjee/.config/helix/runtime;/opt/homebrew/Cellar/helix/23.05/libexec/runtime;/opt/homebrew/Cellar/helix/23.05/libexec/bin/runtime
Runtime directory does not exist: /Users/siebjee/.config/helix/runtime
Runtime directory does not exist: /opt/homebrew/Cellar/helix/23.05/libexec/bin/runtime
Clipboard provider: pbpaste+pbcopy
System clipboard provider: pbpaste+pbcopy

Language                         LSP                              DAP                              Highlight                        Textobject                       Indent
python                           ✓ pylsp                          None                             ✓                                ✓                                ✓
```

**Comment by cd-a** [comment]
what does `hx --health python` say? Do you have overrides in your language toml?

**Comment by pascalkuthe** [comment]
Likely duplicate of #8415 if you installed from homebrew

**Comment by gabydd** [comment]
some more info that could be helpful to us: is the file it's segfaulting on in a git repo, what is the panic message you get when helix crashes, does it not segfault if you remove the .git directory.

I'd also suggest using a build that is from the current master branch of git.

**Comment by Siebjee** [comment]
> Likely duplicate of #8415 if you installed from homebrew

Oh, i missed this one. It is indeed a duplicate. My apologies.
