### ISSUE TITLE
Opening helix with a directory as the first argument does not load .helix/config.toml correctly

### ISSUE THREAD

**Issue by bjorn-ove** [helix-editor/helix#8469]
### Summary

The config is loaded before the working directory is changed during load, hence the wrong directory is checked for .helix/config.toml

https://github.com/helix-editor/helix/blob/68fce3e160c64c488567f0e80f8d57bbbdd9dd82/helix-term/src/main.rs#L118

I can fix this, but wanted to know if there are some caveats first.

### Reproduction Steps

I tried this:

1. `hx <dir>` where the directory contains .helix/config.toml

I expected this to happen:

The config is loaded

Instead, this happened:

The config is not loaded

### Helix log

Link to where the bug is in the source code is provided in the description

### Platform

All

### Terminal Emulator

All

### Helix Version

master (68fce3e160c64c488567f0e80f8d57bbbdd9dd82)

**Comment by the-mikedavis** [comment]
Closed by https://github.com/helix-editor/helix/pull/8498
