### ISSUE TITLE
file picker freezes on big binary files

### ISSUE THREAD

**Issue by adsick** [helix-editor/helix#847]
so when I am in my Downloads folder and use my Up and Down arrows to navigate the menu I experience full freeze when something like Linux distribution 1.9Gb iso image is selected.

one thing it does not even need to preview these types of files, the second: preview is implemented in a wrong way so it (supposedly) tries to read the file entirely when only the first "page" is enough.

**Comment by Omnikar** [comment]
> also I don't quite understand why file picker works the way it does - I would expect it to list only current working dir files, but it lists every imaginable file on my desktop.

What displays when you `:pwd`?

**Comment by archseer** [comment]
We should skip rendering both binary files and files over a certain limit (10-20MB)

**Comment by archseer** [comment]
Fixed by #939

**Comment by omgmajk** [comment]
This is still a thing with files ending in .aura

I was browsing the jazz2-native source from github, it contains a large amount of binary files with the .aura extension.

https://github.com/deathkiller/jazz2-native

It will not do it with (a few test) binary files I have renamed to .aura, but it does for the ones in this repo, unclear why. 

Helix version 25.07.1

<img width="1920" height="1080" alt="Image" src="https://github.com/user-attachments/assets/c0d052c6-b12d-4692-9da8-97944b82591a" />
<img width="1920" height="1080" alt="Image" src="https://github.com/user-attachments/assets/73ced59a-b7bb-409c-9864-4cfdceee7985" />
