### ISSUE TITLE
Implement "extend_to_file_end" function

### ISSUE THREAD

**Issue by specterops-avongluck** [helix-editor/helix#8479]
It would be nice (tm) if there was a ```extend_to_file_end``` function in addition to ```extend_to_line_end```
This would allow selection + deletion of the lines in the file to the end like vi's ```d1G``` macro

**Comment by specterops-avongluck** [comment]
nevermind :-)   Figured it out.

```
["select_mode", "extend_to_line_bounds", "goto_last_line", "extend_to_line_bounds",
```

**Comment by the-mikedavis** [comment]
There's also a `goto_file_end` command

**Comment by specterops-avongluck** [comment]
yeah.  I was missing "select_mode" for that so it just jumped to the end of the file within selecting anything :-)

Thanks!
