### ISSUE TITLE
Inline color preview and color picker akin to VS Code.

### ISSUE THREAD

**Issue by aspizu** [helix-editor/helix#8483]
Various methods to display color preview:
 - Display a block character with the background color next to a hexadecimal color code.
 - Display the hexadecimal color code with the background color and an appropriate text color such that it's readable.

Color picker:
 - Pressing `Ctrl`+`K` would bring up a color picker which could be controlled by the mouse or `hjkl` keys.

**Comment by woojiq** [comment]
https://github.com/helix-editor/helix/issues/1115

**Comment by pascalkuthe** [comment]
Closing as duplicate

**Comment by Android789515** [comment]
The PR that closed https://github.com/helix-editor/helix/issues/1115 only adds displaying colors and does not add a color picker.
