### ISSUE TITLE
Splitting terminal breaks navigation

### ISSUE THREAD

**Issue by musjj** [helix-editor/helix#8493]
### Summary

In a kitty terminal, if you try to open a new window split, buffer navigation will no longer work. You can also see the line numbers being a little bugged out. For some reason, pressing `<Esc>` will make everything work again.

### Reproduction Steps

[![asciicast](https://asciinema.org/a/eEgVhQxiKIvML4kY68hTmy6eu.svg)](https://asciinema.org/a/eEgVhQxiKIvML4kY68hTmy6eu)

I tried this:

1. `hx <file>`
2. `:sh kitty @ launch` (alternatively, `:sh kitty @ launch --location hsplit`)
3. Close the new window (`<C-d>`, etc.)

I expected this to happen: Everything works fine

Instead, this happened: Buffer navigation stops working

### Helix log

My log file is empty.

### Platform

Linux

### Terminal Emulator

kitty 0.30.0

### Helix Version

23.05-466-gbdf7937a

**Comment by CptPotato** [comment]
I this is actually the command's stdout output (try `:sh echo hi`). After a quick search I didn't find a "silent" variant of `:sh`.

**Comment by musjj** [comment]
Oh wow you're right. The "weird line number" was actually the output of the command (a window ID). The solution for my particular case is to use `kitty @ launch --no-response`. But a silent version of `:sh` would definitely be helpful.

I'm going to open a new issue, but what's the right place for a feature request? There's an issue template for a feature request, but it seems that feature requests tend to be moved to discussions. A clearer policy would be helpful.

**Comment by CptPotato** [comment]
> I'm going to open a new issue, but what's the right place for a feature request? There's an issue template for a feature request, but it seems that feature requests tend to be moved to discussions. A clearer policy would be helpful.

Feature requests in this repo are fine, though it's best to search before (silent `:sh` version PR is here #3247). I guess requests are sometimes converted to discussions when they don't quite align with the repo owner's vision (requiring further discussion about the feature or possible workarounds) or are already implemented.

**Comment by musjj** [comment]
Alright, thanks for the info, closing this issue for now.
