### ISSUE TITLE
Keymap for :format or other TypableCommands

### ISSUE THREAD

**Issue by Nehliin** [helix-editor/helix#852]
#### Describe your feature request
Unless I'm missing something it doesn't seem possible to define keyremaps for `TypableCommands` which would be very useful. I usually have a keybinding to format the entire buffer in neovim and use it frequently. AFAIK it's not even possible to create a keybinding for `select_all` + `format_selections` since it only seems possible to map to a single action.

**Comment by archseer** [comment]
@Omnikar had a PR here for sequences: https://github.com/helix-editor/helix/pull/589

Maybe rather than making `TypableCommand`s mappable, we should extract the functional bodies so they can be accessible as a `Command` as well.

**Comment by Nehliin** [comment]
FYI didn't have time to work on helix for some time but I've started looking into this again with another approach. Should have a pr up soon.

**Comment by archseer** [comment]
We were discussing about potentially allowing mappings like these: `a = [":command", "arg1", "arg2"]`. We can tell it apart from multi key mappings based on the `:` prefix on the first arg.

**Comment by Nehliin** [comment]
Yeah that's basically what I'm doing in the pr I am working on
