### ISSUE TITLE
move autocompletion suggestion with j k instead of arrows

### ISSUE THREAD

**Issue by PixelSymbols** [helix-editor/helix#8523]
i reread keymap tutorial several times but still didn't get it. I don't know is this a visual or insert mode. How do i change movement from arrows to j k when suggestion pop up appears, in config.toml?

**Comment by kirawi** [comment]
These are hard-coded for now, but you can alternative use `C-p` and `C-n` to go up and down respectively.

**Comment by PixelSymbols** [comment]
🤦‍♂️why its hardcoded, why the editor itself have hjkl by default for navigation, but autocompletion suggestion is hardcoded to arrows?
who thought of that, why it doesn't make any sense...

**Comment by kirawi** [comment]
It requires extensive changes to make them rebindable. We're already tracking this general issue.
