### ISSUE TITLE
Laravel Blade support

### ISSUE THREAD

**Issue by inmanturbo** [helix-editor/helix#8562]
Blade is a templating language for php by the laravel framework which also supports raw or inline php.

Here is an example for vim: https://github.com/alexandersix/vim-blade

**Comment by EpocSquadron** [comment]
All language support requires a corresponding tree-sitter grammar. There’s one in progress here: [EmranMR/tree-sitter-blade](https://github.com/EmranMR/tree-sitter-blade)

Aside from either waiting on it to be completed or contributing to it to help it along, once it’s complete enough you would then need to write queries specific to helix. Fortunately that repo seems to actually document how!

**Comment by inmanturbo** [comment]
Thanks for adding the link. I had starred that repo awhile ago but then I forgot about it (gh's new dashboard/feed algorithm is a mess). I'll have to keep an eye on it and see if there's anything I can do to help it along!

**Comment by lelgenio** [comment]
Maybe this issue should still be open, my previous PR only added syntax highlighting.

Maybe we could get completion working by using this: https://github.com/haringsrob/laravel-dev-tools
