### ISSUE TITLE
Badly documented :goto_file

### ISSUE THREAD

**Issue by nandoflorestan** [helix-editor/helix#8563]
The :goto_file command (gf) is documented as:

"Go to files in the selection"

https://docs.helix-editor.com/keymap.html?highlight=goto#goto-mode

The same string is present in the helix editor itself.

**The problem is the plural.** The command only opens a single file, not multiple files. This gave me the wrong idea, I thought I would be able to select multiple lines of text and open multiple files from that.  When it didn't work I tried multiple separators: comma, colon, semicolon... I finally realized it wouldn't do what I wanted.

That "s" cost me a long time.  Please remove it.

That's all for the bug report.  Now just a bit of further discussion:

I usually open the same files every day.  I thought of opening them all from the command line, but then I can't open the project at the same time in helix with "hx .".  It seems to be either project or file(s).  That's also bad, I suppose.

**Comment by the-mikedavis** [comment]
It can open multiple files if you have multiple selections so a better wording could be "Go to file in each selection". For example if you have multiple file names separated by lines, select all of the files and then use `A-s` to split on newlines and then use `gf` you will open each file under each selection. Or if they're separated by `,` you can select them all and use `S,<ret>` to split by commas.

Docs are [here](https://github.com/helix-editor/helix/blob/master/book/src/keymap.md#goto-mode) and [here](https://github.com/helix-editor/helix/blob/fc16449efe58a49c15e19c9fde6584d8625493fd/helix-term/src/commands.rs#L334) if you'd like to change them, please send a PR.
