### ISSUE TITLE
Remove comment token when joining two comment lines

### ISSUE THREAD

**Issue by NomisIV** [helix-editor/helix#8565]
Example of current behaviour:
```hs
-- Foo
-- Bar
```
turns into
```hs
-- Foo -- Bar
```
---
Example of desired behaviour:
```hs
-- Foo
-- Bar
```
turns into
```hs
-- Foo Bar
```
---
Since helix is aware of the comment tokens, it should be possible to detect if the user is joining two comment lines, and remove the comment token (including succeeding whitespace).

A subtlety here is that this should only ever happen if both lines are comments.

Any thoughts on this feature?

I could try implementing this myself sometime soon if I find the time.

**Comment by David-Else** [comment]
https://github.com/helix-editor/helix/pull/4718
