### ISSUE TITLE
Add option to disable listing of files in file-picker when no query has been made

### ISSUE THREAD

**Issue by cjohansson** [helix-editor/helix#8570]
My problem is that I am often working on projects with 100,000+ files and when pressing Space + f everything freezes for about 10+ seconds before all files are listed, I think it would be nice if files were listed once a minimum of characters has been entered into the file query, maybe you could adjust that setting yourself in the configuration

**Comment by pascalkuthe** [comment]
We use nucleo on master so helix doesn't Freizeit anymore.

This would not have been the right solution anywayas it would habe just causwd the picker to Freizeit when you start typing.
