### ISSUE TITLE
Panicked (out of range) - tokio-runtime-worker

### ISSUE THREAD

**Issue by spe888** [helix-editor/helix#8571]
### Summary

When changing some text I get a panick error, maybe it has something to do with the current macOS Update (14.0), not sure. 

```
thread 'tokio-runtime-worker' panicked at 'range end index 18446744073709551615 out of range for slice of length 0', /Users/brew/Library/Caches/Homebrew/cargo_cache/registry/src/index.crates.io-6f17d22bba15001f/ropey-1.6.0/src/tree/node_children.rs:312:21
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

### Reproduction Steps

 

I tried this:

1. `hx`
2. toggling comments or inserting text (happens only sometimes)

I expected this to happen:
changing text

Instead, this happened:
thread tokio-runtime-worker panicked as explained

### Helix log

<details><summary>~/.cache/helix/helix.log</summary>

```
the file `~/.cache/helix/helix.log` does not have any recent errors/messages
```

</details>

### Platform

macOS 14.0

### Terminal Emulator

default terminal, bash, zsh, warp

### Helix Version

helix 23.05 (7f5940be)

**Comment by spe888** [comment]
Seems like the same problem: https://github.com/helix-editor/helix/issues/8415

If I remove the .git folder then everything works on macOS 14. I never had the problem on macOS 13.

**Comment by pascalkuthe** [comment]
It's because you are compilig with a too new version of rust. The problem has been fixes on master for a lang time.

**Comment by spe888** [comment]
@pascalkuthe I used `brew install helix`, I didn't do a manual compilation to get this bug/behavior. 

But I did compile it manually now and it works, but for some reason the target build does not read the configuration and languages properly, even when I use the --config flag `/Users/<username>/Projects/helix/target/release/hx --config ~/.config/helix/config.toml`

**Comment by pascalkuthe** [comment]
yeah the brew package is broken. We don't maintain that, so you will need to report that to them and not us

**Comment by spe888** [comment]
@pascalkuthe okay thanks, I'll forward it to them.

**Comment by spe888** [comment]
I've opened a issue on [homebrew](https://github.com/Homebrew/homebrew-core/issues/151893). The only workaround  I've found (for now) is to install the latest version `brew install --HEAD helix`
