### ISSUE TITLE
Cursor not visible on the first column on the first line

### ISSUE THREAD

**Issue by kevinsjoberg** [helix-editor/helix#86]
The cursor becomes invisible whenever you're at the beginning of the first line in a given file.

**Environment**
- hx v0.0.9
- helix-term 0.1.0

**Video**
https://asciinema.org/a/NdbwogdBq8Psqgn1TEoiBCdGm

**Steps to reproduce**
1. Open an existing file.
2. Go the beginning of the first line

**Comment by archseer** [comment]
Was fixed in https://github.com/helix-editor/helix/commit/661dbdca57f76cbd22f3e62f8b87ee2146a50bab but isn't in a tagged release yet.

**Comment by kevinsjoberg** [comment]
@archseer ah, thanks for that!
