### ISSUE TITLE
Master branch docs are a 404

### ISSUE THREAD

**Issue by NukeManDan** [helix-editor/helix#8615]
### Summary

https://docs.helix-editor.com/master

![image](https://github.com/helix-editor/helix/assets/35669742/9553e291-633f-4ae0-bd37-53df28336f0b)

### Platform

All

### Terminal Emulator

Any

### Helix Version

N/A

**Comment by the-mikedavis** [comment]
I believe this happens every time we cut a release: the new release wipes out the master directory. In the short term, pushing a new commit to master should fix this but long term we should preserve that master directory

**Comment by archseer** [comment]
Resolved on latest master
