### ISSUE TITLE
Alignment indentation fails when more than two tree nodes are nested in the same row.

### ISSUE THREAD

**Issue by halazi1** [helix-editor/helix#8650]
### Summary

``` scheme
; The resulting indentation:

(let ((a (begin a
        |))
 a)

; Expected format:

(let ((a (begin a
               |))
 a)
```

### Reproduction Steps

```scheme
; indents.scm
(list . (symbol) @item @anchor (#eq? @item "let")) @align
(list . (symbol) @item (_) @anchor (@not-eq? @item "let")) @align
```

### Platform

Ubuntu 22.04 (WSL)

### Terminal Emulator

Windows Terminal

### Helix Version

helix 23.10 (f992c3b5)

**Comment by Triton171** [comment]
Nice catch! Until now, there haven't really been any situations where multiple `@align` captures occur on the same line, so this bug was never triggered. #8659 should fix the issue.
