### ISSUE TITLE
Add syntax highlight for fountain

### ISSUE THREAD

**Issue by IsotoxalDev** [helix-editor/helix#8662]
Fountain is a markdown - like markup language for writing screenplays.

There seems to be a tree sitter implementation already: https://github.com/UserNobody14/tree-sitter-fountain

There is also a vim extention for it: https://www.vim.org/scripts/script.php?script_id=3880

**Comment by kirawi** [comment]
It seems like an obscure language, so I don't think it would be a good addition.

**Comment by IsotoxalDev** [comment]
Is there an option for a user who want it have it locally without rebuilding helix?

**Comment by kirawi** [comment]
If you have a C/C++ compiler on your system, yes.
Follow https://docs.helix-editor.com/guides/adding_languages.html and then run `hx --grammar fetch && hx --grammar build`

**Comment by IsotoxalDev** [comment]
Oh nice thanks!!
