### ISSUE TITLE
:format moves cursor and selects entire buffer [Windows]

### ISSUE THREAD

**Issue by Nehliin** [helix-editor/helix#869]
Sorry if this already has been reported I couldn't find any previous issue when doing a quick search.

### Reproduction steps
I've only tested this when using Rust + rust-analyzer on windows but everytime I format my cursor is moved to the bottom of the buffer with the entire content selected. Simply saving a file does not produce the same issue it's only format or format + save (as one would expect).

### Environment

- Platform:  Windows
- Helix version: master commit: 2c0468ffd16de1f835ac9c4e39692a682273fb7b

**Comment by kirawi** [comment]
It's not really a bug per se, but rather because for whatever reason when auto-formatting, Rust-Analyzer decided to delete all the text and insert it again. This happened to me when the line-ending was different than the line-ending Rust-Analyzer expected.
