### ISSUE TITLE
Debugger, how to look into locals, etc.

### ISSUE THREAD

**Issue by elevenhsoft** [helix-editor/helix#8690]
Hi

I have setup debugger correctly with wiki support. Everything seems to works ok. I'm able to set breakpoints, run debugger and check the popup. Unfortunately I'm not able or I don't know how to jump into popup to scroll through information, look into variables etc.

![obraz](https://github.com/helix-editor/helix/assets/114903054/20c4ae88-e8e6-495c-a638-9b423d54d6bd)

From screen you can see I have `processes` variable with Vec of size 374. I wish to see each value in this vector. How to?

**Comment by elevenhsoft** [comment]
Ok, I see what's wrong there. My python script returns exception:
```Traceback (most recent call last):
  File "/usr/local/etc/lldb_vscode_rustc_primer.py", line 11, in <module>
    lldb.debugger.HandleCommand(f"""command script import "{rustlib_etc / 'lldb_lookup.py'}" """)
AttributeError: module 'lldb' has no attribute 'debugger'```

This is script from https://github.com/helix-editor/helix/wiki/Debugger-Configurations#rust
And I have llvm installed from https://apt.llvm.org/

**Comment by woojiq** [comment]
Iirc it's not possible to observe variables now. https://github.com/helix-editor/helix/issues/5950
