### ISSUE TITLE
Support 256 ANSI colour set

### ISSUE THREAD

**Issue by kirawi** [helix-editor/helix#870]
https://docs.rs/crossterm/0.21.0/crossterm/style/enum.Color.html#variant.AnsiValue
Like we have for the base 16 colours:
https://github.com/helix-editor/helix/blob/e216e9621e73cda1968632cd20595231af5e07be/helix-view/src/graphics.rs#L215-L237

**Comment by chtenb** [comment]
Is this feature actually documented anywhere? I'm trying to figure out how to use the 256 colors in a theme, and almost created an issue for it when I stumbled upon this thread.

**Comment by the-mikedavis** [comment]
Parsing for this was added in https://github.com/helix-editor/helix/pull/5119 (after the 22.05 release, so you will need to run on master). It looks like there aren't any docs for it yet.
