### ISSUE TITLE
Swapped special register keys

### ISSUE THREAD

**Issue by benhsm** [helix-editor/helix#8702]
Hi, I've been enjoying the enhanced register support in release 23.10, but there's a minor issue that's bothering me. Coming from Vim, `+` was used to refer the system clipboard, and `*` was used to refer to the primary selection, but in Helix these are currently swapped with each other. This isn't a big deal, but it works against my muscle memory, and I imagine that might also be true for other ex-vim users with a habit of using those register keys.

Is this an intentional difference? If it makes sense to swap these keys to be consistent with Vim's, and if it would help, I could open a pull request to change the relevant code and documentation. I suppose there's also the possibility of making this behavior configurable, but I don't have a good sense of what that might take.

**Comment by the-mikedavis** [comment]
Ah this looks like an oversight by me in #6985. Yeah, we should probably swap them as they were introduced to be similar to the registers from vim
