### ISSUE TITLE
Some popular themes

### ISSUE THREAD

**Issue by kirawi** [helix-editor/helix#872]
- [ ] [Dracula](https://github.com/dracula/dracula-theme)
- [ ] [PaperColor](https://github.com/NLKNguyen/papercolor-theme)
- [ ] [ayu](https://github.com/dempfi/ayu)
- [ ] [Tokyo Night](https://github.com/folke/tokyonight.nvim)

**Comment by aral** [comment]
Looks like common themes are part of Helix now (https://github.com/helix-editor/helix/tree/master/runtime/themes).
