### ISSUE TITLE
Lsp in termux 

### ISSUE THREAD

**Issue by Gul7333** [helix-editor/helix#8729]
Plz help me how can I enable lsp in Termux.....
I used " pkg install helix"
..
hx command is working...
I also installed Grammer and build it ...
Now I want lsp.... But there are no file like language.toml in >>> .config/helix in
Termux only runtime folder 
![Screenshot_20231106-093234.png](https://github.com/helix-editor/helix/assets/106809902/cc66b564-11ab-49ef-96b8-74ff93f66e02)

**Comment by dead10ck** [comment]
It does not get created for you. You have to make it.
