### ISSUE TITLE
Stopping Helix from appending '\n' to all files 

### ISSUE THREAD

**Issue by alxpettit** [helix-editor/helix#8746]
As it stands, as of Helix 23.10, if you write a blank file, it adds a newline. While this can be useful in some cases, I think it breaks more things than it fixes

**Comment by the-mikedavis** [comment]
It's configurable, see the `editor.insert-final-newline` option in the config docs: https://docs.helix-editor.com/master/configuration.html#editor-section

**Comment by alxpettit** [comment]
Ah, thanks! I missed that.
