### ISSUE TITLE
e moves to newline graphemes in CRLF files

### ISSUE THREAD

**Issue by chtenb** [helix-editor/helix#8765]
### Summary

The e movement behaves differently for LF and CRLF files.
For LF files it behaves correctly and jumps to the end of the next word.
Not for CRLF: 
![image](https://github.com/helix-editor/helix/assets/1030961/e617204c-dbeb-47b2-95ac-0ad1d2827328)

Possibly related: https://github.com/helix-editor/helix/issues/8246

### Platform

Windows

### Terminal Emulator

wezterm 20230828-220414-99c96139

### Installation Method

cargo

### Helix Version

recent custom build (23.10-36-g7d78b0ec)

**Comment by pascalkuthe** [comment]
This is the same bug as #8246 it's the same codepath internally. Closing as duplicate
