### ISSUE TITLE
Repeat insert `.` doesn't work as expected when insertion was done with `c`

### ISSUE THREAD

**Issue by basile-henry** [helix-editor/helix#8781]
### Summary

I would expect `.` to replicate the way the last insertion was done, but when replacing text with `c`, it seems to only replace 1 character, not the whole selection that got replaced.

I can get what I want if I repeat the selection before doing `.`, so maybe it is the intended behavior? It does make `.` not as useful in my view and definitely unexpected when coming from `vim`/`neovim`.

### Reproduction Steps

[![asciicast](https://asciinema.org/a/620292.svg)](https://asciinema.org/a/620292)

Key sequence: `ec_replaced[ESC]` then move followed by `.`

### Platform

Linux

### Terminal Emulator

alacritty 0.12.3

### Installation Method

nixpkgs

### Helix Version

helix 23.05 (7f5940be)

**Comment by pascalkuthe** [comment]
that is working as intended, its replacing the current selection. which collpases to a single char after pressing c but if you select some text again and then press `.` it will replace the entire selection

**Comment by basile-henry** [comment]
Right I see. And is there another command that would repeat the selection before doing the insertion? And if there's not, would the project be open to someone (maybe me) adding the feature?
I used to do this a lot in vim/neovim when doing repetitive edits, but in helix repeating the (sometimes complex selection) make `.` kind of useless :sweat_smile:

**Comment by pascalkuthe** [comment]
you can use `A-.` to repeat the last motion. This probably isn't as useful as in vim tough since the selection action may sometimes be complex. There is also the option to record and replay marcros which would likely work better.

In general helix favour editing multiple things at once with multicursor instead of repreating actions multiple times so I doubt that we would accept more complexity here

**Comment by basile-henry** [comment]
Alright, thanks for you explanation! :smile:  I'll try to get used to `A-.` and multi-cursors then :+1:
