### ISSUE TITLE
tokyonight theme does not show main selection

### ISSUE THREAD

**Issue by mikkelfj** [helix-editor/helix#8783]
### Summary

In hx --tutor chapter 10.1 main selection is moved with ( and ) keys.
With tokyonight theme, the motion is invisible, although it does take effect. Changing to another theme such as night_owl does not have this problem.

Note: This is MacOS testet with both Kitty and Alacritty terminals.
Also: cursor shape for select is set to "underline", but I do not see any underlines in either terminal, though maybe this is more of a theme thing where underline means a specific background color?

### Reproduction Steps

 

I tried this:

1. `hx --tutor`
navigate to chapter 10.1
Follow instructions.
See effect of ( ) navigation. Change theme to tokyonight. See no visible change.

Maybe also set cursor shape to underline for select.

### Platform

macOS Sonoma, Intel & Apple Silicon

### Terminal Emulator

alacritty 0.12.3, kitty

### Installation Method

brew

### Helix Version

23.10

**Comment by mikkelfj** [comment]
The theme "material_deep_ocean" is very similar to tokyonight but darker background, and multi-selection works.

**Comment by the-mikedavis** [comment]
This is tracked in https://github.com/helix-editor/helix/issues/3842
