### ISSUE TITLE
file_picker_in_current_buffer_directory not working

### ISSUE THREAD

**Issue by BobbyByrne** [helix-editor/helix#8814]
### Summary

This command doesn't do anything. It simply closes the command panel.

The PR for this feature has another user experiencing the same issue back in April. 
https://github.com/helix-editor/helix/pull/4666#issuecomment-1509037354

I'm also experiencing the same issue with `<space>f` and `<space>F` doing the same thing. 

### Reproduction Steps

 

I tried this:

1. Opened helix in a project root dir. example `/projects/foo`
2. Opened a file buffer in a nested dir `/projects/foo/bar/baz.rs`
3. Attempted all three commands starting with `file_picker`

I expected this to happen:

- `file_picker`
  - ?
- `file_picker_in_current_directory`
  - I would expect the file picker to open in `/projects/foo`
- `file_picker_in_current_buffer_directory`
  - I would expect the file picker to open in `/projects/foo/bar`
  - I think I would expect this to be the same behavior as `file_picker`, but I'm not sure what the actual default behavior is.

Instead, this happened:

- `file_picker` using space f
  - opens file picker in `/projects/foo`
- `file_picker_in_current_directory` using space F
  - opens file picker in `/projects/foo`
- `file_picker` using command window `<space>?`
  - closes command window and does nothing...
- `file_picker_in_current_directory` using command window `<space>?`
  - closes command window and does nothing...
- `file_picker_in_current_buffer_directory` using command window `<space>?`
  - closes command window and does nothing...

### Platform

Windows (WSL)

### Terminal Emulator

Windows Terminal Version: 1.18.2822.0

### Installation Method

releases page

### Helix Version

helix 23.10 (f6021dd0)

**Comment by gabydd** [comment]
The pickers not working from the command palette is: https://github.com/helix-editor/helix/issues/4508 if you want the picker in current buffer directory then at the moment you need to bind it to key
