### ISSUE TITLE
Keep LSP diagnostics at least until some new ones arrive.

### ISSUE THREAD

**Issue by dpc** [helix-editor/helix#8858]
I'm working on a large Rust project. I make some refactoring changes that break existing callers. I hit `:w` and CPU's temperature rapidly increases. I wait and wait... I get over 9000 errors.

I fix some in one file and `:w`. LSP makes my laptop fan go jet engine mode again. I wait. I could be fixing some other errors already, because I know there's still plenty off them, but Helix decided to reset the previous list and `<space>D` shows an empty picker. Bummer.

I wish Helix kept the previous LSP diagnostics longer. At least until new LSP run doesn't complete or start returning something actionable again.

**Comment by pascalkuthe** [comment]
There is nothing we can do about this, raise an issue with rust-analyzer. We absolutely do keep diagnostics until the next publishDiagnostic arrives (and map them trough the changes something that vscode doesn't do and that #6447 improves upon further). It's just that RA immidietly discards all  checkOnSave diagnostics on save and therefore sends an empty list.

This is indistinguishable for us from the diagnostics actually being fixed.
