### ISSUE TITLE
Something strange happened when using auto completion

### ISSUE THREAD

**Issue by WindSoilder** [helix-editor/helix#886]
### Reproduction steps

 

Sorry for that I don't know how to describe it in a good way, you can look the upload video please.

It seems that when I:
1. type `os.read_` and then
2. delete two character `os.rea` and then
3. select the auto completion item, the result is `os.rearead`, which should be `os.read`

https://user-images.githubusercontent.com/22256154/138198289-9dd36317-c5a2-48c4-aec7-706ab256e253.mov

### Environment

- Platform:  macOS
- Helix version:  v0.4.1-248-g0fa8baf

<details><summary>~/.cache/helix/helix.log</summary>

```
please provide a copy of `~/.cache/helix/helix.log` here if possible, you may need to redact some of the lines
```

</details>

**Comment by archseer** [comment]
I think this is 4) here: https://github.com/helix-editor/helix/issues/822

It's likely got something to do with the hack we do here

https://github.com/helix-editor/helix/blob/b1ebd7a07e55f8ff5b8ef9fcbf09940a9f4a4f39/helix-term/src/ui/completion.rs#L127-L139
