### ISSUE TITLE
Searching in selection mode should extend the selection until the search term

### ISSUE THREAD

**Issue by cole-h** [helix-editor/helix#8866]
This is essentially a duplicate of https://github.com/helix-editor/helix/issues/6964. However, that issue was itself closed as a duplicate of https://github.com/helix-editor/helix/issues/5672, which I think was due to a misinterpretation of the original issue (5672 talks about "In select mode (`v/`) this can be used to add matches of the search pattern as new cursors." (searching in select mode adding cursors for search results), while 6964 talks about "It changes the selection to the searched-for text., rather than extending it." (searching in select mode extending the selection until the search result)).

My imagined workflow would be:

1. Enter selection mode at some specific location `asdf` in a document with `v`
2. Search for e.g. `fn` with `/fn`
3. Have the selection _extend_ from `asdf` to `fn` (and _NOT_ add another cursor at `fn`)

**Comment by pascalkuthe** [comment]
that is part of #5672, the issue was correctly closed as duplicate

> this search would replace or extend the current selection(s) (depending on normal or select mode).

**Comment by cole-h** [comment]
My eyes really are failing me... I could have sworn I had read that ticket multiple times to try and not look silly, and here I am. Oops. Thanks for the sanity check.
