### ISSUE TITLE
Unable to set editor whitespace to render all when config states a selective rendering

### ISSUE THREAD

**Issue by wojexe** [helix-editor/helix#8885]
### Summary

I've been always been using `render = { tab = "all" }`, since that's what was most useful to me. Today I tried to set a custom rendering, to render all whitespace characters in a certain file in which the number of spaces mattered. I was suprised when I saw that this did not work as I expected. See below for reproduction steps.

### Reproduction Steps

 

1. In `config.toml` set the following:
```toml
[editor.whitespace]
render.tab = "all"
```
2. `hx`
3. `:set whitespace.render "all"`
4. Error shows up in the status line: "Could not parse field `all`"

I expected the setting to be overriden.

### Helix log

<details><summary>~/.cache/helix/helix.log</summary>

2023-11-23T00:54:57.011 helix_view::editor [ERROR] editor error: Could not parse field `all`

</details>

### Platform

macOS

### Terminal Emulator

iTerm 2 3.5.0beta6

### Installation Method

brew

### Helix Version

helix 23.10 (f6021dd0)

**Comment by pascalkuthe** [comment]
This is a general limitation of `:set` being based on json. This will be solved once we revamb the config system, see #8853
