### ISSUE TITLE
Completion with local filenames

### ISSUE THREAD

**Issue by squalou** [helix-editor/helix#8893]
Hi,

I may have missed it in case the feature/enhancement already exists I'm really sorry.

I have this situation when, using vim (and can't remember what setting), the editor will suggest autocompletion based on local filesystem.

This is useful for instance in a Dockerfile when you want to `ADD` something that is near the dockerfile itself, or in any script file where you read a local file for instance.

**Comment by 0x61nas** [comment]
I don't think that we have any equivalent to this. But I think that it can be done via the LSP.

**Comment by the-mikedavis** [comment]
This is tracked under https://github.com/helix-editor/helix/issues/1015

Also see https://github.com/helix-editor/helix/pull/2608
