### ISSUE TITLE
Automatically extend doc/comment when going to next line.

### ISSUE THREAD

**Issue by TornaxO7** [helix-editor/helix#8896]
You have opened the following file `test.rs`:
```rust
/// doc comment|
                         ^ Cursor
```
and now you press enter. It would be nice if `helix` adds the leading `///` for you:
```rust
/// doc comment
/// |
    ^ Cursor
```
but the current behaviour is currently:
```rust
/// doc comment
|
^ Cursors
```

**Comment by kirawi** [comment]
Duplicate of https://github.com/helix-editor/helix/issues/1730
