### ISSUE TITLE
Undo more than a single change

### ISSUE THREAD

**Issue by kevinsjoberg** [helix-editor/helix#89]
I'd like to undo all changes that were made to a document since it was loaded into memory. Currently, pressing `u` does only undo the latest change.

**Environment**
- hx v0.0.9
- helix-term 0.1.0

**Comment by archseer** [comment]
Hmm, this used to work. It seemed to stop working after f5f46b1fed242f0b5a206753f7f977299fb2ff65, \cc @pickfire

**Comment by jbaa** [comment]
It also seems like `U` for redoing the undone change doesn't work anymore.

**Comment by jbaa** [comment]
It also seems like `U` for redoing the undone change doesn't work anymore.
