### ISSUE TITLE
Emoji character causes cursor unexpected behaviour

### ISSUE THREAD

**Issue by heldrida** [helix-editor/helix#8911]
### Summary

While writing bash, put a small text message preceded by an emoji info character. It caused Helix Editor to show the cursor in odd places, and also some characters such as double quote to show/hide as I moved around hjkl or cursor keys.

Thus, when putting some emoji characters in-memory it causes Helix unexpected behaviour.

### Reproduction Steps

 

I tried this:

1. Open a typescript file `hx fooba.ts`
2. Insert emoji ℹ️
3. Yank text/emoji selection
4. Paste text/emoji line
5. Move cursor around

I expected this to happen:

Work as regular character/text.

Instead, this happened:

https://github.com/helix-editor/helix/assets/236752/3836c726-7130-49b0-aa35-e4d689ab7031

### Helix log

<details><summary>~/.cache/helix/helix.log</summary>

```
please provide a copy of `~/.cache/helix/helix.log` here if possible, you may need to redact some of the lines
```

</details>

### Platform

macOS

### Terminal Emulator

kitty 0.27.0

### Installation Method

brew

### Helix Version

helix 23.10 (f6021dd0)

**Comment by pascalkuthe** [comment]
This falls under #6012
