### ISSUE TITLE
line numbers cannot be seen with onedark colour scheme.

### ISSUE THREAD

**Issue by LollipopFt** [helix-editor/helix#892]
![image](https://user-images.githubusercontent.com/62802897/138440341-5fae21dd-e26c-486b-abc3-125ded7af92a.png)
only when it is highlighted can it be seen clearly. however, if you squint really closely you can see that the other line numbers are coloured in a very slightly different colour from the background.

**Comment by BigThxBrigde** [comment]
I've encountered the same problem, any solutions?

**Comment by LollipopFt** [comment]
> I've encountered the same problem, any solutions?

@BigThxBrigde i updated windows terminal (used the preview build), just kept updating helix editor, and somehow one day it just started working so...
