### ISSUE TITLE
LSP: Use `workspace/willRenameFiles` to handle rename resource operations

### ISSUE THREAD

**Issue by the-mikedavis** [helix-editor/helix#8942]
With the addition of LSP renaming in https://github.com/helix-editor/helix/pull/8584 we now declare `willRename` support - that we will send a [`workspace/willRenameFiles`](https://microsoft.github.io/language-server-protocol/specifications/lsp/3.17/specification/#workspace_willRenameFiles) before renaming a file. The spec says that this should be used for workspace edits as well as user commands (emphasis mine):

> The will rename files request is sent from the client to the server before files are actually renamed as long as the rename is triggered from within the client either by a user action **or by applying a workspace edit**.

Currently we just rename the file when receiving a workspace edit that attempts to rename a file (which was the proper behavior when we didn't declare willRename support): https://github.com/helix-editor/helix/blob/b023faacf898e2f393fa8f7f91e685547080442c/helix-term/src/commands/lsp.rs#L827-L837

But this needs to be updated to use willRenameFiles.

This causes a bug with rust analyzer for example, see https://github.com/helix-editor/helix/discussions/8923.

**Comment by the-mikedavis** [comment]
@pascalkuthe I know that you have been looking at this block recently. Is this something you are interested in solving? If not we could add the `E-help-wanted` label

**Comment by pascalkuthe** [comment]
Yeah I will try to do it all in one go (otherwise the PRs would just conflict). That's actually a useful pointer, great fine! I really need to find where VScode Handels all of this but I can't find the right place in the codebase.

**Comment by pascalkuthe** [comment]
this feels like a job for the event system TBH but until that is merged having a workaround would be nice I guess. I think I will start out just fixing this issue (and the related PR) so we can get rid of the regression. A general system like that seems perfect for the event system once that lands.
