### ISSUE TITLE
SCP (Secure Copy Protocol) support.

### ISSUE THREAD

**Issue by woojiq** [helix-editor/helix#8954]
> Secure copy protocol (SCP) is a means of securely transferring computer files between a local host and a remote host or between two remote hosts. It is based on the Secure Shell (SSH) protocol.

I think this is best suited for a plugin system as there are other protocols that can be handled as well, like ftp.

By "support" I mean you can run helix like this: `hx scp://user@myserver[:port]//path/to/file.txt` and on save it will transfer edited file via ssh in the background (to not block ui).

https://unix.stackexchange.com/a/202920/580115:
> This is handled by vim's [netrw.vim](http://www.vim.org/scripts/script.php?script_id=1075) standard plugin. Several other protocols are supported.

**Comment by pascalkuthe** [comment]
This can be handeled by sshfs, no need to integrate it into helix.

Also duplicate of #3721
