### ISSUE TITLE
Specify a file to use as `language.toml`

### ISSUE THREAD

**Issue by dschrempf** [helix-editor/helix#8955]
Hi!

We can set the main configuration file using `-c <file>`, but to my knowledge, there is no way to set the main `language.toml` file in a similar way (e.g., `-l <file>`).

Should we support such an option?

How do you load a `language.toml` file that is not in the main configuration directory?

Thanks for considering this issue!

**Comment by the-mikedavis** [comment]
Duplicate of https://github.com/helix-editor/helix/issues/7102
