### ISSUE TITLE
Soft wrap adds an empty line although text fits into the original line completely

### ISSUE THREAD

**Issue by Schweber** [helix-editor/helix#8973]
### Summary

I don't know if this is a bug or a feature but in the following example, the text fits into the line with no space to spare but soft wrap still adds an (empty) line below:

![image](https://github.com/helix-editor/helix/assets/64630479/995407f9-3f93-4fc6-a598-fd3933f45e22)

I would prefer if it did not do that.

### Reproduction Steps

My soft wrap settings are:
```
[editor.soft-wrap]
enable = true
max-wrap = 40 # increase value to reduce forced mid-word wrapping
max-indent-retain = 100
wrap-indicator = " "
```

Reproduce akin to the picture i posted above. File type is `.nix` if this is relevant.

### Helix log

<details><summary>~/.cache/helix/helix.log</summary>

```
2023-12-02T19:21:56.526 helix_view::theme [WARN] Theme: malformed ANSI: base4
2023-12-02T19:21:56.526 helix_view::theme [WARN] Theme: malformed ANSI: base4
2023-12-02T19:21:56.526 helix_view::theme [WARN] Theme: malformed ANSI: dark_blue
2023-12-02T19:22:08.680 helix_lsp::transport [ERROR] nil err: <- StreamClosed
```

</details>

### Platform

Linux

### Terminal Emulator

kitty 0.31.0

### Installation Method

Nixos unstable

### Helix Version

helix 23.10 (f6021dd0)

**Comment by pascalkuthe** [comment]
This is the case of the newline character being wrapped to the next line. The newline character is always selectable in helix (which is a core Design choice) so it must also always be visible/not off-screen when softwrap is active.

This behavior is an intentional Design choice

**Comment by jean-dao** [comment]
Follow up question regarding soft wrapping:
![image](https://github.com/helix-editor/helix/assets/1405645/ea65a988-3643-48c7-b93f-3974e838141a)
It behaves differently whether the last word is alphanumeric (`[0-9a-zA-Z_]`) or not, is that intended?

I would prefer that it never wraps a single 'newline' character, but always wraps it along with the last word (like on first line) delimited by space characters only. Is this behavior change be acceptable?
