### ISSUE TITLE
Fatal error on replace string with cyrillic characters

### ISSUE THREAD

**Issue by ImperatorMarsa** [helix-editor/helix#8984]
### Summary

When i try to change the selected text with the text that was recently copied, the editor crashes. The copied and replaced text contains Cyrillic characters (Russian letters). Judging by the text of the error, the editor does not like the presence of the letter «к» in the text 🤷‍♀️.

### Reproduction Steps

 

I tried this:
1. select the text (which contains Cyrillic characters)
2. replace other selected text (which also contains Cyrillic characters)

I expected this to happen:
replase text

Instead, this happened:
edditor crash wiht error:
```log
thread 'main' panicked at C:\Users\runneradmin\.cargo\registry\src\index.crates.io-6f17d22bba15001f\unicode-segmentation-1.10.1\src\grapheme.rs:553:27:
byte index 486 is not a char boundary; it is inside 'к' (bytes 485..487) of `жны пересикаться`'
                        );
                        return true;
                    }
                }
                $datePassing[] = [
                    'endDate'   => $endDate,
                    'startDate' => $st`[...]
stack backtrace:
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
```
Error massege has sume variants, like this:
```log
thread 'main' panicked at C:\Users\runneradmin\.cargo\registry\src\index.crates.io-6f17d22bba15001f\unicode-segmentation-1.10.1\src\grapheme.rs:553:27:
byte index 519 is not a char boundary; it is inside 'к' (bytes 518..520) of `х испытаний не должны пересикаться`'
                        );
                        return true;
```

![GIF 04 12 2023 11-42-05](https://github.com/helix-editor/helix/assets/30154703/b0c88b9a-c8e2-4cd7-8047-55cb786f0b2d)

### Helix log

<details><summary>~/.cache/helix/helix.log</summary>

[hx.log](https://github.com/helix-editor/helix/files/13544156/hx.log)

</details>

### Platform

Windows

### Terminal Emulator

wezterm 20230712-072601-f4abf8fd

### Installation Method

releases page

### Helix Version

helix 23.10 (f6021dd0)

**Comment by the-mikedavis** [comment]
I believe this is the same problem as https://github.com/helix-editor/helix/issues/7273 so I'll close in favor of that one
