### ISSUE TITLE
autocomplete not working on windows

### ISSUE THREAD

**Issue by LollipopFt** [helix-editor/helix#901]
auto-completion does not work.
tried on alacritty, windows terminal and base command prompt.
compiled from source.

### Reproduction steps
when typing in a text file:
https://user-images.githubusercontent.com/62802897/138602991-e5df41d5-f569-40a0-a377-c404c01b901c.mp4
you may not notice it. but i had done ```ctrl-x``` to try to invoke the autocomplete to no avail. when typing in 'hello' for the second time, autocomplete should have worked at least.
 

### Environment

- Platform: Windows 10 Pro
- Helix version: v0.4.1-272-g42eee9d

<details><summary>AppData\Local\helix\helix.log:</summary>

```
2021-10-25T00:16:29.695 helix_view::editor [ERROR] Failed to initialize the LSP for `source.rust` { IO Error: The system cannot find the file specified. (os error 2) }
```

</details>
 this was the only thing in my log file.

**Comment by dead10ck** [comment]
It would be very useful to have a purely lexical autocomplete. Some languages do not have good language servers, and sometimes you're not editing code. Are feature requests accepted?

**Comment by sudormrfbin** [comment]
> It would be very useful to have a purely lexical autocomplete. Some languages do not have good language servers, and sometimes you're not editing code. Are feature requests accepted?

@dead10ck That's a useful feature, could you open a separate issue ?
