### ISSUE TITLE
Jump between git edits

### ISSUE THREAD

**Issue by Euphrasiologist** [helix-editor/helix#9035]
Hello, 

Love Helix, thanks for all your hard work. I can't see this anywhere in the documentation, but I'd love to be able to jump to the next git gutter using a keybinding. Is there support for this currently?

**Comment by CptPotato** [comment]
See this relevant PR: #5645

**Comment by Euphrasiologist** [comment]
Will be cool to see git changes picker land!

@woojiq thanks - `[g`/`]g` are good for the moment, should have read the docs on those! Thanks for the info :)

**Comment by the-mikedavis** [comment]
Let's close this in favor of https://github.com/helix-editor/helix/issues/5362
