### ISSUE TITLE
When I use append mode everything I type is highlighted

### ISSUE THREAD

**Issue by tripleducky** [helix-editor/helix#9036]
### Summary

If I enter insert mode by appending,  everything I type is highlighted, as if I was selecting it to copy paste. This does not happen if I insert before selection, only if I insert after selection. This is easily reproduced and I could make a little video of it happening if absolutely necessary.

I am assuming this is some kind of bug, but because it is so benign I wonder if I turned something on I shouldn't have? although it seems like a pointless feature.

I am on linux. I actually have the program installed on a windows computer, and iirc it didn't happen there last time I used it, although I'm not entirely sure of that.

### Reproduction Steps

 

I tried this:

1. append_mode

I expected this to happen: I would be able to append my code

Instead, this happened: Everything I typed showed up highlighted, although I was still able to append.

### Helix log

<details><summary>~/.cache/helix/helix.log</summary>

```
please provide a copy of `~/.cache/helix/helix.log` here if possible, you may need to redact some of the lines
```

</details>

### Platform

Linux

### Terminal Emulator

Bash

### Installation Method

package manager

### Helix Version

23.10

**Comment by the-mikedavis** [comment]
This is intentional, see https://github.com/helix-editor/helix/discussions/2924
