### ISSUE TITLE
Python code snippets

### ISSUE THREAD

**Issue by kmafeni04** [helix-editor/helix#9041]
I have the python lsp set up and I receive diagnostics but I was wondering if there's any code snippets for the language since there are none when typing

**Comment by dead10ck** [comment]
Snippets are a feature supported by LSP, so the language server must provide them.

**Comment by kmafeni04** [comment]
Does the python lsp support snippets?

**Comment by dead10ck** [comment]
You seem perfectly capable of searching this.
