### ISSUE TITLE
readme request: Why Helix?

### ISSUE THREAD

**Issue by RedEmberCat** [helix-editor/helix#905]
Please include a section on what is motivating the project or what would motivate someone to switch to Helix. What advantages exist in Helix or are planned to exist that will differentiate it from Kakoune? Even the website lacks this type of explanation (https://helix-editor.com), other than battery life, which isn't terribly motivating.

**Comment by pinpox** [comment]
> Duplicate of #241, though it's partially answered in https://github.com/helix-editor/helix/blob/master/docs/vision.md

Could you expand on the differences from Kakoune? How does an editor include a window manager?

**Comment by sudormrfbin** [comment]
A window manager in the sense that you can create split windows within helix itself and edit multiple files side by side in the same helix instance, whereas in kakoune you have to open multiple terminals and connect to the kakoune server as client to get the same functionality.
