### ISSUE TITLE
Keybind for Extend/shrink selection up and down

### ISSUE THREAD

**Issue by EmiOnGit** [helix-editor/helix#9079]
Currently helix seem to lack a lack a intuitive way to extend/shrink the selection down or up based on direction of selection.

With  extend/shrink a line down I'm basically speaking about the default x-key with the change that it shrinks the selection if the direction is reversed.

Besides that I also would love to have a counterpart to the 'changed' x-key described above.
This would extend/shrink the line above dependent on the direction of selection.

I would suggest to implement the commands without binding them by default, especially to give people the opportunity to test them out properly.
Personally, I would love these two commands to be bound to the J,K keys since it works very intuitively.
  
I've seen a wish for this behavior a couple of times already in the help-forums as well as in the keymap discussion e.g.:
[1](https://github.com/helix-editor/helix/issues/165#issuecomment-1817779737)
[2](https://github.com/helix-editor/helix/issues/165#issuecomment-1817577770)
[3](https://github.com/helix-editor/helix/issues/165#issuecomment-1847299066)
[4](https://github.com/helix-editor/helix/issues/165#issuecomment-1771544419)

**Comment by david-crespo** [comment]
This is closed by #9080, right? It didn't auto-close because the message didn't say "closes" or "fixes".
