### ISSUE TITLE
Inconsistent split behavior

### ISSUE THREAD

**Issue by ygabuev** [helix-editor/helix#9112]
### Summary

When performing multiple vertical splits, the split ratios depend on whether horizontal splits were performed before. When doing two vertical splits in sequence, the ratios are 1:1:1. When a horizontal split has been performed (and then the split was closed), the splits are 2:1:1.

### Reproduction Steps

[![asciicast](https://asciinema.org/a/AlpxVmztBXQwudLgX3SKd2Gdg.svg)](https://asciinema.org/a/AlpxVmztBXQwudLgX3SKd2Gdg)

### Platform

Linux

### Terminal Emulator

alacritty

### Installation Method

Arch Linux package

### Helix Version

23.10

**Comment by pascalkuthe** [comment]
closed by #10004
