### ISSUE TITLE
Support for LLM-ls from huggingface

### ISSUE THREAD

**Issue by KhazAkar** [helix-editor/helix#9129]
Hello!
Since rise of LLMs in coding space is inevitable, I just found quite nice language server, which leverages LLMs for coding, from huggingface. LLM-LS, written in rust :)

https://github.com/huggingface/llm-ls

Inclusion of support for it might help a lot for helix users. :)

**Comment by dead10ck** [comment]
If it does not use any nonstandard LSP extensions, then it should already be supported. If it does, then it never will be.
