### ISSUE TITLE
Partial highlighting when moving by half screen height

### ISSUE THREAD

**Issue by EpocSquadron** [helix-editor/helix#915]
When utilizing `Ctrl-U` and `Ctrl-D` to move up and down one half screen height at a time, I notice that half of the screen does not receive highlights. Moving the cursor in any direction with `hjkl` or the arrow keys usually applies the highlights, while selection-motions like `e` and `x` do not. Motions that cause scrolling (eg moving up such that scrolloff kicks in) always applies the highlights.

For example, the below is what I see when I move one half screen down. Notice the bottom half of the screen is not highlighted.
![image](https://user-images.githubusercontent.com/414963/138952530-db54cd9c-2763-44b9-ad6e-5bcb5f4d46c2.png)

.. And that same section of code after moving around:
![image](https://user-images.githubusercontent.com/414963/138952924-49b965d6-12d0-4267-9e60-282253756f99.png)

Aside: Apologies for the ginormous images, couldn't figure out how to resize uploads.

**Comment by kirawi** [comment]
I'm not sure, it's possible that this bug is being caused by a separate issue.

**Comment by sudormrfbin** [comment]
> I'm not sure, it's possible that this bug is being caused by a separate issue.

Can it be reproduced in a language without injections ? Python for example ?

**Comment by EpocSquadron** [comment]
I'll test today.

**Comment by EpocSquadron** [comment]
@sudormrfbin I tried with long python and rust code samples, and could not reproduce the issue.

**Comment by sudormrfbin** [comment]
Rust has injections for macros, but python doesn't have any at all. So I guess it's a problem with certain kinds of injections ? Not sure.

**Comment by kirawi** [comment]
I guess we'll find out once #434 is addressed.

**Comment by EpocSquadron** [comment]
Got around to trying these files out with the `incremental` branch, and the issue is indeed resolved there. Closing in favor of #434.
