### ISSUE TITLE
Unable to configure "text" language

### ISSUE THREAD

**Issue by ModProg** [helix-editor/helix#9165]
### Summary

I want to configure an LSP for plain text, but if I try to add it to `text` I get an error that the language definition for `text` is incomplete.

The issue seems to be, that I am not actually modifying the `text` language but adding a new `text` language. Because when I set all the mandatory fields, I have two identical options `text` for `:set-language`.

### Reproduction Steps

 

I tried this:

1. `cat ~/.config/helix/languages.toml`
  ```toml
  [[language]]
  name = "text"
  language-servers = ["my-lsp"]
  ```
2. `hx`
  ```
  Bad language config: missing field `scope`
  in `language`
  ```

I expected this to happen:

helix starts up and executes `my-lsp` for any file that is not assigned a specific language.

Instead, this happened:

Helix doesn't start and prints error, due to `language` "text" having missing fields.

### Platform

Linux

### Installation Method

AUR

### Helix Version

helix 23.10 (5ce1c30f)

**Comment by woojiq** [comment]
Since there is no entry with `name = "text"` in the languages.toml file, you need to add the full configuration of your custom language. https://docs.helix-editor.com/master/languages.html

> Bad language configuration: missing `scope` field

It just says you need to add a _scope_ field because of what I said earlier.

**Comment by ModProg** [comment]
yeah, but what I actually want, is to modify the "text" language, that does exist as it is the default chosen for any file.

It is special, apparently not only in it's applying to any undetected file, but also in not actually being a full language.

I'd consider this not the correct behavior though.

How would I even get a language that applies to any file if I cannot use the default "text"?

**Comment by ModProg** [comment]
when I actually fully define my language there is also the strange behavior of having two "text" languages:

![Screenshot_20231227_005452_Termux.jpg](https://github.com/helix-editor/helix/assets/11978847/9689ec42-e07f-4ea0-bda2-daaac111fac8)

**Comment by daaku** [comment]
This would be nice, and additionally would be good to have #8850 include the default text file type as well.

**Comment by pascalkuthe** [comment]
will be fixed in the config refactor where all config options can be cofnigured globally , per lang and per doc (so you can configure global fallbacks/for the text language for all language options). Closing in favor of #8853
