### ISSUE TITLE
Scrolling view using view mode or mouse removes additional cursors

### ISSUE THREAD

**Issue by Omnikar** [helix-editor/helix#917]
### Reproduction steps

1. Create additional cursors.
2. Scroll the view using `zj`, `zk`, `zu`, `zd`, `zb`, `zf`, or mouse scroll (`zt`, `zz`, and `zb` do not cause the issue).
3. Additional cursors/selections other than primary will disappear.

**Comment by academician** [comment]
Looked into this a little and found [the TODO](https://github.com/helix-editor/helix/blob/master/helix-term/src/commands.rs#L1291) that I think would fix this, at least. Need to read more of the cursor code to understand the right way to fix it, but doesn't seem too hard.
