### ISSUE TITLE
Diagnostic flickering with rust-analyzer

### ISSUE THREAD

**Issue by MaxVerevkin** [helix-editor/helix#9175]
### Summary

Diagnostics are flickering each time I type the next character. This did not happen before #6447.

### Reproduction Steps

https://asciinema.org/a/7ryNepzYg8HYXCxF5VRvehmgX

### Platform

Arch Linux

### Terminal Emulator

Alacritty

### Installation Method

chaotic-aur/helix-git

### Helix Version

helix 23.10 (783ff27b)

**Comment by the-mikedavis** [comment]
What does the log say when running in verbose mode? `hx -v --log log.txt` and attach `log.txt`

**Comment by MaxVerevkin** [comment]
[log.txt](https://github.com/helix-editor/helix/files/13780520/log.txt)

**Comment by pascalkuthe** [comment]
I think I know roughly what's causing this nit I am away without a computer for a while
