### ISSUE TITLE
Helix not refreshing UI after insert-output

### ISSUE THREAD

**Issue by Kaporos** [helix-editor/helix#9181]
### Summary

I currently have this simple keymap configuration:

`"backspace" =  l=[":hnew", ":insert-output man 3 printf","goto_file_start"]}`

when i press backspace-l it opens a new buffer, correctly insert man output, but then the goto_file_start do not move my view to top of the file. I mean, i think it does but the ui is not refreshing, because if i then type on any key, then the helix view updates and i'm taken to the top of the file.

### Reproduction Steps

In this gif i'm just pressing backspace-l , then i just press "g" key to show goto menu but as you can see, i'm only getting to the top of the file when pressing g

![demo](https://github.com/helix-editor/helix/assets/34960023/cd1b476e-6449-42af-aebc-110932510407)

### Helix log

none pertinent i guess

### Platform

Linux

### Terminal Emulator

wezterm 20230712-072601-f4abf8fd

### Installation Method

pacman

### Helix Version

helix 23.10

**Comment by gyreas** [comment]
I'm able to reproduce this. Apparently, `:insert-output` doesn't "normalise" the buffer after dumping the output.

It's the same for tools that dump output larger than the relevant view

**Comment by prometheus-8** [comment]
@Kaporos what happens if you append `:reload` to the keymap?

**Comment by Kaporos** [comment]
> @Kaporos what happens if you append `:reload` to the keymap?

I got an error "can't find file to reload from "[scratch]"" 

I also tried :redraw but didn't change anything

**Comment by gyreas** [comment]
I don't get this issue on the Android build.
