### ISSUE TITLE
Support for Treesitter Textobjects , Auto Indent for HTML and CSS.

### ISSUE THREAD

**Issue by kamlendras** [helix-editor/helix#9194]
It's been a while (8 months) I'm regularly checking  helix language support documentation
to support Treesitter Textobjects , Auto Indent for HTML and CSS.
Sadly it's not been added yet.

I tried to do it myself but I'm a JavaScript developer I read contributing documentation & looked at language queries directory but I understand nothing.

Can anyone do it or if not guide me further so maybe I can add it myself :)

**Comment by kirawi** [comment]
You can read https://tree-sitter.github.io/tree-sitter/using-parsers#pattern-matching-with-queries for how to write queries

**Comment by kamlendras** [comment]
Sure.
