### ISSUE TITLE
Zero-width selection, "between" rather than "on" cursor

### ISSUE THREAD

**Issue by Ericson2314** [helix-editor/helix#9216]
Helix (and Kakuone) seem to work like Vim in that the cursor is always "on" a character". In contrast, Emacs and most windows/mac GUI editors have a notion of the cursor being "between" a character (or before the first / after the last character).

Yes, this sort of philosophical points are a bit subjective. For example, Helix seems to have a pseudo final newline for files without a trailing newline. Like the "between" approach, this ensures _n + 1_ cursor positions for _n_ characters.

To make it more concrete, I think would I'd like to make this issue a more concrete request for a "zero width" selection, instead of a "'between' cursor semantics". I hope that as an additional feature rather than change in approach, it is more likely to coexist with the current UI / not be invasive in the code or a breaking change.

The easiest way to see what this would like is to change ones cursor for "box" to "bar" in selection mode. With a zero-width selection, the character with cursor would *not* be highlighted; moving the cursor to either the right or the left would extend the cursor into a one-character selection.

In addition (and perhaps by a setting) it would be customary for the cursor character to *never* be highlighted, even with non-empty selections. The vertical bar at the left of the cursor would be rendering the right edge of the selection, and the highlighting should go up to (from the left) but never *past* the vertical bar.

(These semantics do make sense regardless of how the cursor is display; e.g. Emacs has a box cursor by default. But I think the "on"-character semantics are easier to intuit with a box cursor, while the "between"-character semantics are easier to intuit with a bar cursor. The implementation of a terminal bar cursor which is still on a character is ultimately just doing the best we can with a TUI. With a GUI and no inherent character grid for all UI elements, it is more natural still to render a between cursor, something I would hope to take advantage of after #312.)

**Comment by the-mikedavis** [comment]
This is an important part of the select-then-act paradigm: you always have at least a 1-width selection at the cursor which is used when you delete with `d` for example.

You can configure a different cursor shape depending on the mode like a bar, see https://docs.helix-editor.com/master/configuration.html, but this is cosmetic only. Internally we always expand zero width selections to be a minimum width of one.

**Comment by Ericson2314** [comment]
> This is an important part of the select-then-act paradigm

As a matter of opinion, sure, but as a matter of fact?

Note that I didn't talk about changing normal mode: I am OK if the normal mode cursor stays as a 1-width election. I just would like in selection mode to get the zero width selections. I don't think this has to be so invasive at a user level / make things that are fewer keystrokes today more.

I indeed changed my cursor to be a bar already... but it only makes the issues I bring up more salient. Having the selection go one character pass the bar (since the bar is trying to look between characters even if it isn't) does not look or act right.

**Comment by kirawi** [comment]
I believe https://github.com/helix-editor/helix/issues/362 did talk about this

**Comment by Ericson2314** [comment]
Thanks!

**Comment by the-mikedavis** [comment]
Gap indexing makes it technically possible to represent zero-width selections but we ensure that they have a minimum width as part of ensuring range invariants: https://github.com/helix-editor/helix/blob/a6ed104ea2787b523379895b7eb23998aae121f4/helix-core/src/selection.rs#L616-L625

You can try removing the part of that function that `min_width_1` part but because it's an invariant we assume throughout the codebase that it's true, so things will probably break in unintuitive ways.

We aren't interested in a PR to change this. If anything we want to make select mode less special and basically just an extra set of keymaps.

**Comment by Ericson2314** [comment]
OK thanks!
