### ISSUE TITLE
Insufficient information in `--version` to distinguish between release and development instances

### ISSUE THREAD

**Issue by zancas** [helix-editor/helix#922]
### Reproduction steps
1. [Build helix from source.](https://github.com/helix-editor/helix/#installation)

2. Invoke `helix --version` against the instance built from source, e.g.:

```bash
${GITREPO_ROOT}/target/debug/hx --version
helix 0.4.1
```
3. Invoke `helix --version` against the instance installed from a release, e.g. (on Arch):

```bash
/usr/bin/helix --version
helix 0.4.1
```

Fix:
   Make `--version` report more specific version information, perhaps:

`$(RELEASETAG)-$(BUILD_CANDIDATE)_$(10CHARSBUILDHASH)`

e.g.

`0.4.1-rc1-8442e653f5`

for a development build instance, and:

`0.4.1` for a released instance.

**Comment by pickfire** [comment]
> @pickfire Looks like we could do this in build.rs without complicated proc macros, what was the problem with this again? I remember there was some issues:

I did what you did there. Also, note that we may want `git describe --dirty` since we don't know whether or not files are changed locally.
