### ISSUE TITLE
thread 'main' panicked at 'called `Option::unwrap()` on a `None` value'

### ISSUE THREAD

**Issue by webdev23** [helix-editor/helix#9255]
### Summary

`thread 'main' panicked at 'called `Option::unwrap()` on a `None` value', /build/helix-2Yvm31/helix-23.10/helix-view/src/handlers/dap.rs:231:57`

Experiencing this bug randomly, while launching a debugger session. May lead to loss of data. 

### Reproduction Steps

I tried this:

1. `hx` myfile.php

2. `Space g l ` Launch debugger

3. `php myscript.php` in another shell

Helix crash at point 3, when launching a PHP debugging session with php-xdebug and inteliphense. The debugger **setup is fine and is running, into Helix two times out of three.**

`hx --health php `

```
Configured language servers:                   
  ✓ intelephense: /usr/local/bin/intelephense  
Configured debug adapter: node                 
Binary for debug adapter: /usr/bin/node        
Highlight queries: ✓                           
Textobject queries: ✓                          
Indent queries: ✓             
```

I understand it's the early stages of debugging integrations, as warned it's experimental, thanks for the great work already, it's almost there!            

### Helix log

<details><summary>~/.cache/helix/helix.log</summary>

```
 helix_view::editor [ERROR] editor error: Currently active thread is not stopped. Switch the thread.
 helix_dap::transport [ERROR] Tried sending response into a closed channel (id=3), original request likely timed out
 helix_dap::transport [ERROR] err: <- StreamClosed
 helix_dap::transport [ERROR] err: <- IO(Os { code: 32, kind: BrokenPipe, message: "Broken pipe" })
 helix_view::editor [ERROR] editor error: Async job failed: server closed the stream
[ERROR] received malformed notification from Language Server: Unhandled
[ERROR] editor error: Debugger does not support session restarts
[ERROR] editor error: Async job failed: request 9 timed out 
[ERROR] Tried sending response into a closed channel (id=9), original request likely timed out 
[ERROR] err: <- StreamClosed 

```

</details>

### Platform

Linux

### Terminal Emulator

zsh

### Installation Method

source

### Helix Version

23.10

**Comment by gabydd** [comment]
I believe this is the same bug as https://github.com/helix-editor/helix/issues/8625 we aren't properly handling the breakpoint changed event

**Comment by webdev23** [comment]
Also had this crash error, using the debugger: 

`thread 'main' panicked at 'no entry found for key', /build/helix-2Yvm31/helix-23.10/helix-view/src/handlers/dap.rs:40:17`
