### ISSUE TITLE
Provide a way to move several buffers back or forth

### ISSUE THREAD

**Issue by jerabaul29** [helix-editor/helix#9258]
If I have several buffers open and I want to move "2 forward" I need to type ```:bn``` twice. Would it be possible to parse these commands to allow a number of "next" moves, for example ```:2bn```, ```:3bn``` etc? Same with ```:bp```.

**Comment by gyreas** [comment]
That's right. Did you know you can achieve the same with `gn` goto-next-buffer | `gp` goto-previous-buffer which can take a number prefix?

**Comment by pascalkuthe** [comment]
> That's right. Did you know you can achieve the same with `gn` goto-next-buffer | `gp` goto-previous-buffer ~which can take a number prefix~? Edit: I checked again, don't.

I think adding support for count to those two commands would be a reasonable way to adress this

**Comment by gyreas** [comment]
That would make there be at least two classes of commands, profitable and non-prefixable. This is a useful feature. I will look into the implementation of `move_line_*`. Where should I tackle?

**Comment by woojiq** [comment]
What's the advantage of this method instead of opening buffer picker or creating key bindings for the next|previous buffer? And if you still want to implement it, I think "count" should be an argument (as all the other commands do) instead of a prefix.

**Comment by woojiq** [comment]
If you want to modify `:bn`, "count" must be an argument, not a prefix. This is how all typed commands work.

**Comment by woojiq** [comment]
`:bn <x>` (with space), like `:w <filename>`. But that's from a personal point of view, I'm not core maintainer.
It would be easier for you to just change your muscle memory and use `<x>gn` when this is fixed.

**Comment by blinxen** [comment]
Another useful feature would be the ability to switch to a buffer at a specific position. Instead of typing `<space> + b + 3 + <enter>`, you could create a key mapping to switch directly to the specified buffer. I like to use `<Alt> + buffer_position`, where the position starts at 1.

**Comment by pascalkuthe** [comment]
closing in favor of https://github.com/helix-editor/helix/issues/10400#issuecomment-2053783942
