### ISSUE TITLE
Workspace symbol picker select result

### ISSUE THREAD

**Issue by nilsherzig** [helix-editor/helix#9261]
I think the workspace symbol picker should also select the result (like the document symbol picker) to create a more consistent feeling between them.

**Comment by the-mikedavis** [comment]
The document symbol picker and workspace symbol picker already use the same code when you select something in the picker: https://github.com/helix-editor/helix/blob/77ab792ac72698189120b2c62e26d2a26807a9ca/helix-term/src/commands/lsp.rs#L244-L256

We select the range of the symbol that the language server gives, so if you see a difference between the document and workspace symbol picker selections, your language server must be sending different ranges.
