### ISSUE TITLE
The whole editor just hangs after pasting a nested HTML and traversing it

### ISSUE THREAD

**Issue by mzfr** [helix-editor/helix#9273]
### Summary

I opened a markdown file and posted the following code:

```html
<p float="left">
  <img src="/img1.png" width="100" />
  <img src="/img2.png" width="100" /> 
  <img src="/img3.png" width="100" />
</p>
```

and after that, when I tried to one character at a time(using right arrow key) on 2nd line(or any of the <img> tag line) the editor hangs when you reach the first equalsto sign.

The same hangs also happens with following payloads:

* Single <img> tag
```html
<p float="left">
  <img src="/img1.png" width="100" />
</p>
```

* Path without "/"
```html
<p float="left">
  <img src="img1.png" width="100" />
</p>
```

The hang **doesn't** occur if the `<img>` tag isn't nested i.e if you just paste `<img src="/img1.png" width="100" />` and start to move with right arrow key no "hang" will occur.

I was working inside a tmux session, and the only way to get out of it was to kill the tmux pane and start a new one.

I also tested this by disabling both the config.toml and languages.toml file and running vanilla helix.

### Reproduction Steps

 

I tried this:

1. `hx filename.md`
2. Paste the following code:

```html
<p float="left">
  <img src="/img1.png" width="100" />
  <img src="/img2.png" width="100" /> 
  <img src="/img3.png" width="100" />
</p>
```
3. On 2nd line, use right arrow key to move right and everything will hang when you reach the first "=" sign.

I expected the editor to NOT hang

Instead, it hang(ed).

### Helix log

<details><summary>~/.cache/helix/helix.log</summary>

```
  90440  2024-01-08T11:36:40.275 helix_lsp::transport [ERROR] marksman err <- "[11:36:40 INF] <LSP Entry> Starting Marksman LSP server: {}\n"
  90441  2024-01-08T11:37:25.887 helix_lsp::transport [ERROR] marksman err <- "[11:37:25 INF] <LSP Entry> Starting Marksman LSP server: {}\n"
  90442  2024-01-08T11:40:34.169 helix_lsp::transport [ERROR] marksman err <- "[11:40:34 INF] <LSP Entry> Starting Marksman LSP server: {}\n"
      ~
```

</details>

These are the only relevant logs which are generated during/after the hang.

### Platform

macOS

### Terminal Emulator

iterm2

### Installation Method

brew

### Helix Version

helix 23.10 ((f6021dd0))

**Comment by sicher** [comment]
> I opened a markdown file and posted the following code:
> 
> ```
> <p float="left">
>   <img src="/img1.png" width="100" />
>   <img src="/img2.png" width="100" /> 
>   <img src="/img3.png" width="100" />
> </p>
> ```
> and after that, when I tried to one character at a time(using right arrow key) on 2nd line(or any of the  tag line) the editor hangs when you reach the first equalsto sign.

I can reproduce this.

**Comment by woojiq** [comment]
I can reproduce on f6021dd0cdd8cf6795f024e396241cb0af2ca368 but on more recent version 85fce2f5b6c9f35ab9d3361f3933288a28db83d4 - I can't.
