### ISSUE TITLE
Jump between vertically split buffers

### ISSUE THREAD

**Issue by kevinsjoberg** [helix-editor/helix#93]
It would be nice to be able to jump between open vertical buffers similar to how Vim allow you to do `C-w w` to jump to the next buffer and `C-w h` and `C-w l` would allow you to choose the direction (either left or right).

**Comment by kevinsjoberg** [comment]
Realised this is already possible at limited capacity using `<Tab>`. Closing for now.

**Comment by pickfire** [comment]
I am going to reopen this. I think `<tab>` is not good enough, we should follow vim for this.
