### ISSUE TITLE
Python "and" operator defined as both a keyword and keyword.operator

### ISSUE THREAD

**Issue by jlhamilton777** [helix-editor/helix#9334]
### Summary

I was trying to set the style of keywords for Python code in my custom theme, and I noticed that `and` was being styled too, even though the other Boolean operators were not. It turns out to be both a `keyword` and a `keyword.operator`.

https://github.com/helix-editor/helix/blob/17dd102e5cccbb2a9a0f0224af63e52f3dab846b/runtime/queries/python/highlights.scm#L206-L222

### Platform

Linux

### Terminal Emulator

alacritty

### Installation Method

source

### Helix Version

helix 23.10

**Comment by aspizu** [comment]
It's weird because this should be the case with `in` as the `in` word is used as a operator and also as a keyword in the `for` `in` loop.
