### ISSUE TITLE
Handle `Unsupported` errors when enabling bracketed paste

### ISSUE THREAD

**Issue by kirawi** [helix-editor/helix#9336]
The error comes from here when we setup the terminal: https://github.com/helix-editor/helix/blob/f27fdb2bf4da1e9b1e0a0c8e7688e738379ba33b/helix-tui/src/backend/crossterm.rs#L134-L139

To prevent the exit on startup we could handle the `Unsupported` error from crossterm (https://github.com/crossterm-rs/crossterm/blob/08762b3ef4519e7f834453bf91e3fe36f4c63fe7/src/event.rs#L390-L395) instead and log that helix won't be able to use bracketed paste

_Originally posted by @the-mikedavis in https://github.com/helix-editor/helix/discussions/9025#discussioncomment-7879769_

**Comment by jigypeper** [comment]
I have made an attempt, but no permissions to push to a branch

**Comment by jigypeper** [comment]
need to fork it?

**Comment by kirawi** [comment]
Closed by #9353
