### ISSUE TITLE
Alt-Enter in the picker does not open selected file

### ISSUE THREAD

**Issue by MuratOzsoyler** [helix-editor/helix#9373]
### Summary

`Alt-Enter` should open selected file while file picker remains open. But no files are opened.

### Reproduction Steps

 

I tried this:

1. `hx .`
2. Enterd `Space` then `f`
3. Selected an entry.
4. `Alt-Enter`

I expected the file opened and file picker remained open.

Instead, this happened:
File picker stayed open but no file is opened in the background.

### Helix log

<details><summary>~/.cache/helix/helix.log</summary>
No log entries related to this bug, except may be this:
```
2024-01-17T22:36:05.154 helix_tui::backend::crossterm [DEBUG] The keyboard enhancement protocol is not supported in this terminal (checked in 1.956676ms)
```

</details>

### Platform

Windows 11 wsl archlinux

### Terminal Emulator

alacritty for Windows

### Installation Method

from AUR helix-git package

### Helix Version

helix 23.10 (3f88a3f4)

**Comment by David-Else** [comment]
It works here on the latest master, the file appears in the buffer list.
