### ISSUE TITLE
Option to dissable/toggle underlines

### ISSUE THREAD

**Issue by MaxVerevkin** [helix-editor/helix#9383]
Sometimes diagnostic underlines can become too distracting and annoying. Most of the time I want underlines, but in cases like this I want to just temporarily hide them.

I found `editor.undercurl` option, but apparently it can only force-enable them. Adding a third setting (e.g. `"off"`) to force-disable is probably sub-optimal because (I assume) it will not work with `toggle-option`.

**Comment by kirawi** [comment]
You could define a theme without undercurls and switch to it when you don't want them.

**Comment by kirawi** [comment]
Closed as inactive

**Comment by MaxVerevkin** [comment]
> You could define a theme without undercurls and switch to it when you don't want them.

I already have to define my theme which symlinks to another theme to implement light/dark toggle. Doing the same for undercurls would require a weird hierarchy of symlinks. And an external script to toggle it, as if I understand correctly, there is no way to toggle between two themes right now.

Also this approach is not scalable. If I also want to toggle, say, italics, I will have to have 8 custom themes.

I think the best solution is to have a boolean option to enable/disable them. Similar to lsp.display-inlay-hints.
