### ISSUE TITLE
link does not exist

### ISSUE THREAD

**Issue by mbaneshi** [helix-editor/helix#9391]
### Summary

hx -g fetch
Fetching 163 grammars
162 up to date git grammars
Failure 1/1: gemini Git command failed.
Stdout: 
Stderr: fatal: unable to access 'https://git.sr.ht/~sfr/tree-sitter-gemini/': The requested URL returned error: 403

Error: 1 grammars failed to fetch
macbookair@pan ~/a [1]> 
<img width="1440" alt="Screenshot 2024-01-20 at 19 20 32" src="https://github.com/helix-editor/helix/assets/21130612/c16209f5-3f39-42ee-a0b9-010a711ed94f">
<img width="1440" alt="Screenshot 2024-01-20 at 19 20 25" src="https://github.com/helix-editor/helix/assets/21130612/85e00856-e79b-49e1-a879-848cd34ff573">

### Reproduction Steps

 

I tried this:

1. `hx`

I expected this to happen:

Instead, this happened:

### Helix log

<details><summary>~/.cache/helix/helix.log</summary>

```
please provide a copy of `~/.cache/helix/helix.log` here if possible, you may need to redact some of the lines
```

</details>

### Platform

macos

### Terminal Emulator

kitty

### Installation Method

brew

### Helix Version

helix 23.10 (f6021dd0)

**Comment by kirawi** [comment]
Already fixed by https://github.com/helix-editor/helix/pull/9316
