### ISSUE TITLE
nvim-colorizer like color highlighting

### ISSUE THREAD

**Issue by throwaway-squared** [helix-editor/helix#9394]
hello, ive been using helix for some days/weeks now and ive really enjoyed it. while i know im not yet using some of its utilities correctly, im certain this one just doesnt exist yet.

i would like for hex color tags (ie #6f16b4) or other color-related things (ie "red" or 0x123159 or smth similar) to be highlighted in the background, like with nvim-colorizer:

![image](https://github.com/helix-editor/helix/assets/145593137/ef743616-beba-404a-80b5-e620cb1a4644)

to do this, there could be a new highlighting element added for themes, like `color-tag`

putting this in your theme.toml, it could look like this:
```toml
"color-tag" = { modifiers = ["reversed"] }
```

**Comment by woojiq** [comment]
https://github.com/helix-editor/helix/issues/1115
