### ISSUE TITLE
Language server config is not updated for `:lsp-restart` after `:config-reload`

### ISSUE THREAD

**Issue by kirawi** [helix-editor/helix#9398]
### Summary

This behavior seems to stem from how`syn_loader` is replaced rather than the interior value being replaced:

https://github.com/helix-editor/helix/blob/9c56afeff36489ff73a9b160fe7d57360a3f9952/helix-term/src/application.rs#L383-L388

combined with us not updating the value for `Registry` as well. I think we could use `ArcSwap` here like we do for the config.

### Reproduction Steps

1. Open the helix repo in Helix and open a document.
2. Add a custom language config for rust-analyzer.
3. `:config-reload` and `:lsp-restart`

### Helix Version

9c56afeff36489ff73a9b160fe7d57360a3f9952

**Comment by rgunindi** [comment]
I had the problem that lsp reactivated many times after `:lsp-restart` command, so I was looking for issues.

**Comment by ferntheplant** [comment]
I'm still running into this issue with reloading the [`ltex-ls`](https://valentjn.github.io/ltex/ltex-ls/installation.html) LSP server. If I update my `languages.toml` manually to add a new word like "asdfg" to the spellcheck dictionary. Then when I run `:config-reload` followed by :lsp-restart` the LSP server still warns me about misspelling "asdfg". However if I quit helix and reopen the file then the spell check config is applied correctly
