### ISSUE TITLE
silent deletion of log files generated with `helix -vvv ir.cpp`, when opening them with helix

### ISSUE THREAD

**Issue by matu3ba** [helix-editor/helix#941]
### Reproduction steps

 
```sh
wget https://github.com/ziglang/zig/blob/master/src/stage1/ir.cpp
hx -vvv ir.cpp
```

### Environment

- Platform:  Linux pc 5.14.14
- Helix version:  v0.5.0-16-g592fba1

The log file is 1.2 MB, so I compressed it.

What is happening:
```txt
[user@pc stage1]$ hx -vvv ir.cpp
[user@pc stage1]$ cd ~/.cache/helix/
[user@pc helix]$ l
helix.log
[user@pc helix]$ du
 1.2M   ┌── helix.log
 1.2M ┌─┴ .
[user@pc helix]$ cp helix.log helix_back.log
[user@pc helix]$ hx helix.log
[user@pc helix]$ du .
   0B   ┌── helix.log
 1.2M   ├── helix_back.log
 1.2M ┌─┴ .
 ```

[accidentically I opened the issue as question in tree-sitter repo](https://github.com/tree-sitter/tree-sitter/discussions/1467), but at least I also filed there one bug.

**Comment by matu3ba** [comment]
[helix_back.zip](https://github.com/helix-editor/helix/files/7449023/helix_back.zip)

**Comment by kirawi** [comment]
#735 I didn't consider that would happen, hmm. Maybe that change should just be reverted.

**Comment by archseer** [comment]
Yeah, we should get rid of truncation. Helix doesn't log much anymore unless ran with `-v` so it should be fine.

**Comment by WindSoilder** [comment]
What about truncate only user run with `-v`, otherwise keep the log there?

**Comment by WindSoilder** [comment]
What about truncate only when run with `-v`, otherwise keep the log open?  If no truncate and run with -v again and again, the log file can be large
