### ISSUE TITLE
match bracket wrong in `<style>` tag of html

### ISSUE THREAD

**Issue by jqhr** [helix-editor/helix#9423]
### Summary

match bracket position wrong for style tag in html file.
```html
<style>
.example { // <- I want to move to here by `mm` cmd.
   box-sizing: border-box;
} // <- cursor here
</style> 
```
But position was at <kbd>></kbd> of `</style>` when I press `mm`.

### Reproduction Steps

![图片](https://github.com/helix-editor/helix/assets/23305067/d670164d-f553-4757-89b2-4569b0d4ba41)

https://github.com/helix-editor/helix/assets/23305067/a822e7bd-45d1-4ab2-a156-c1951f4c5447

### Platform

macOS

### Terminal Emulator

wezterm-20230712-072601-f4abf8fd

### Installation Method

brew

### Helix Version

23.10

**Comment by woojiq** [comment]
I'm not sure, but I changed the `mm' behavior a bit here: https://github.com/helix-editor/helix/pull/8294.
It is unlikely that this will be merged soon, since helix-core needs to be refactored.

**Comment by jqhr** [comment]
Maybe.

https://github.com/helix-editor/helix/assets/23305067/9ec99209-04df-4559-b7b0-6a6e3d1b0c23

I have try `mi{`, it works.

**Comment by jqhr** [comment]
For vim, the `%` works well, whatever current filetype has treesitter.
I think it was a bug
