### ISSUE TITLE
Odd behaviour with `append_mode` `collapse_selection`

### ISSUE THREAD

**Issue by wmstack** [helix-editor/helix#9443]
### Summary

I use helix, and I map <kbd> a </kbd> to `append_mode` `collapse_selection`. There is an odd bug where the selection comes up again after pressing enter even though the last command collapsed the selection.

### Reproduction Steps

```toml
# ~/.config/helix/config.toml
keys.normal.a = ["append_mode", "collapse_selection"]
```

![image](https://github.com/helix-editor/helix/assets/58462210/4c97f1c1-a46b-4732-aa5f-7b213339275f)

Write some text and then add a left parenthesis to generate a pair
![image](https://github.com/helix-editor/helix/assets/58462210/daba8a3f-d253-47d9-9030-1e7abbf8b9fb)

Then press <kbd> esc </kbd> then <kbd> a </kbd> (which is mapped as above)
![image](https://github.com/helix-editor/helix/assets/58462210/0f7af106-80e3-4cb7-a097-83ae39a93657)

Now press <kbd> enter </kbd>
![image](https://github.com/helix-editor/helix/assets/58462210/6d1dd1cd-837a-4d78-a2b4-439b6d42522a)

I expected this to happen:
![image](https://github.com/helix-editor/helix/assets/58462210/57d777d3-5f1f-46e5-bf5d-45629565d23b)

Instead, this happened:
![image](https://github.com/helix-editor/helix/assets/58462210/8dcc49f6-271a-4935-8f66-0ecb53cc2c4a)

### Helix log

<details><summary>~/.cache/helix/helix.log</summary>

```
please provide a copy of `~/.cache/helix/helix.log` here if possible, you may need to redact some of the lines
```

</details>

### Platform

Windows

### Terminal Emulator

Windows Terminal

### Installation Method

Scoop

### Helix Version

helix 23.10 (f6021dd0)

**Comment by the-mikedavis** [comment]
This is intentional: appending with `a` will add any new text to the selection and the newline character is selectable in Helix.

**Comment by wmstack** [comment]
> This is intentional: appending with `a` will add any new text to the selection and the newline character is selectable in Helix.

There is no way this is intentional, because after the `collapse_selection` command, there is nothing that is selected, even if I use the mouse to move the cursor elsewhere, a selection forms when I press enter.

If after presseing `esc a` you use the mouse to put the cursor in the middle and press enter, the selection will start again.

**Comment by the-mikedavis** [comment]
Oh I see, I skipped over the part about `collapse_selection`. I've added that to the reproduction steps. Yeah, `insert_newline` is uniquely trying to detect `a` here: https://github.com/helix-editor/helix/blob/2661e05b3405c216a2303c20e71830b4bde7ac35/helix-term/src/commands.rs#L3654-L3659

Ideally it should not rely on that field and just figure out whether it needs to extend by looking only at the current selection.

**Comment by wmstack** [comment]
Well, I don't know if this helps, but I have found a psuedo-fix by adding an `insert_mode` command after the `collapse_selection`. This makes it so one <kbd> enter </kbd> does not cause a selection but pressing it twice causes a selection.

**Comment by wmstack** [comment]
I also want to add another odd behavior of the `append_mode` command. I don't actually dislike it because it is a *really* edge behaviour and it isn't clear it is a *wrong decision* but   It causes the next escape to move *backward* if you are on the last character of the file. It doesn't bother me that much but it is another one of these hidden state issues:

<img width="180" alt="image" src="https://github.com/helix-editor/helix/assets/58462210/feb28ccc-c29c-4619-94a5-799c53830a33">

After pressing append mode

<img width="175" alt="image" src="https://github.com/helix-editor/helix/assets/58462210/3774ae34-54fb-4537-944b-a13441330738">

Now after escaping

<img width="173" alt="image" src="https://github.com/helix-editor/helix/assets/58462210/4a457fce-58b1-48b7-876d-60ec4baac17a">

If you instead run `insert_mode`, this doesn't happen.

**Comment by the-mikedavis** [comment]
That is also with the custom `["append_mode", "collapse_selection"]` binding, right? With regular `append_mode` the cursor should go to the next line, and `esc` should return the cursor to its original position. That's also a consequence of the `restore_cursor` field (it's actually the intended purpose of that field and `insert_newline` is improperly using the field).

If you're trying to avoid the selection behavior of `a` then you should bind it to the equivalent of `li` instead of using `collapse_selection`. You should also consider not remapping `a` at all: the selection behavior is there by design and is useful when using multiple cursors.

**Comment by wmstack** [comment]
Well, the cursor is not going to go to the next line because there is no next line. This is where both insert mode and append mode have the same behavior. It doesn't seem to be affected by `collapse_selection`. I have tried it without and the behaviour is the same.

**Comment by pascalkuthe** [comment]
> Append mode will cause the next escape to move backward, while insert mode will cause the escape to return to the same position. I have tried it without and the behaviour is the same.

that is intentional
 

> There was a helix configuration I saw a while ago where some Vim programmer recommended the bindings append_mode collapse_selection and insert_mode collapse_selection and I felt like they were in some sense optimal. So I adopted them.


these vim like binding are very explicitly not supported. You can change keybindings but you can't change helixes editing model and selection being sticky with regards to movement is part of that core model. Its not a different keymap its a different internal selection model that is fundamentally incompatible

**Comment by the-mikedavis** [comment]
Oh I see, yeah if the buffer is empty then we can't move the selection over by one, and `esc` mistakenly moves you back one anyways. Kakoune solves this by adding the newline when you `a` at the end of the buffer and that seems reasonable to me - I may add a PR later to add that behavior.

> the selection looks jarring while I am typing

Yeah, this is a common complaint. Other editors tend to punish you for having a selection (e.g. typing while you have a selection deletes the selection contents) but it's really important to the editing paradigm so I'd suggest trying it for a while (maybe a few weeks) and seeing if you can adjust.

**Comment by wmstack** [comment]
> that is intentional

Wel it might be but I think the problem is that the behaviour of escape depends on what the last command was. That's alright, but why should helix really care whether you returned to insert mode by `append_mode` or `insert_mode`. If you return by `insert` the next escape doesn't move backwards as I said.

So there is some hidden state that determines the behaviour of the next `escape`. I think it is a quirk, but most of the time nobody is really typing at the edge of the document.

**Comment by wmstack** [comment]
Well I seem to have found the code for the behaviour of going to normal. To be honest it makes zero sense to me because this behaviour only manifests at the end of the buffer? It seems from the code that `escape` always moves the cursor back by 1?

https://github.com/helix-editor/helix/blob/2661e05b3405c216a2303c20e71830b4bde7ac35/helix-view/src/editor.rs#L1903-L1915

**Comment by the-mikedavis** [comment]
When you enter insert mode with `append_mode` the cursor gets moved one to the right, so moving back by one resets the positioning: https://github.com/helix-editor/helix/blob/2661e05b3405c216a2303c20e71830b4bde7ac35/helix-term/src/commands.rs#L2689-L2694

**Comment by wmstack** [comment]
I see, when using `collapse_selection`, pressing `a` and `esc` will just keep moving the cursor forward.
