### ISSUE TITLE
Add option to treat soft-wrap line as one (like in vim)

### ISSUE THREAD

**Issue by nando-digital** [helix-editor/helix#9444]
It would be nice to have the option to treat long lines (with soft-wrap activated) as one when moving the cursor, especially when moving the cursor in a repeated motion. I can easily jump to a specific line (with relative line numbering) by looking at the line number. (E.g. `10j` to go to the line with the relative line number 10). But if there's a soft-wrapped line between, that doesn't work because I need (at least) two `j` to get across this one long line. It would be nice if one `j` is enough to move the cursor to the next real line and you could still use `gj` to go down one (terminal) line. This behavior is the default in vim and I think it's more intuitive.

**Comment by kirawi** [comment]
https://github.com/helix-editor/helix/wiki/FAQ#can-the-jk-bindings-be-changed-to-ignore-soft-wrapping-when-using-a-count-like-3j
