### ISSUE TITLE
Project compilation or other longer-lived shell commands

### ISSUE THREAD

**Issue by schell** [helix-editor/helix#9450]
First off - thanks for this cool, snappy editor. I am enjoying it. 

My workflow is simplified by having the ability to compile my project without leaving my editor. I'm coming from spacemacs where I would hit `SPACE p c` and then type my build command, or hit enter if nothing had changed. This brings up a new compilation buffer (or switches to the open one) where the build output is written. Errors are linked back into the source.

Forgive me if there's already a way to accomplish this, I've been playing around and haven't found a solution yet. It seems `sh {my_build_command}` kinda works - but I can't see the output. For example if I run `sh cargo build` I can't tell anything has happened until finally "Command succeeded" shows up in the status bar.

**Comment by the-mikedavis** [comment]
See https://github.com/helix-editor/helix/issues/2934 or https://github.com/helix-editor/helix/issues/1976 - `:sh` isn't meant to be used for long-lived shell commands

**Comment by schell** [comment]
Thanks for the pointer @the-mikedavis :)
