### ISSUE TITLE
Vue language server has been deprecated in favor of vls

### ISSUE THREAD

**Issue by achenet** [helix-editor/helix#9465]
As the title says, `vue-language-server` has been deprecated in favor of `vls`. It may be wise to update the default `languages.toml` to reflect this.

**Comment by archseer** [comment]
Please open a PR!

**Comment by Siilwyn** [comment]
I don't think this is true, the vue-language-server binary comes from the `@vue/language-server` package which is maintained at https://github.com/vuejs/language-tools/

**Comment by achenet** [comment]
huh... it's possible I've misunderstood something then.
My source for the deprecation was this web page:
https://www.npmjs.com/package/@volar/vue-language-server
where it says the package is deprecated, but perhaps that's a different binary than `@vue/language-server`... thanks for clearing that up :)

**Comment by Siilwyn** [comment]
Ah yeah it is confusing but that's a different package.
