### ISSUE TITLE
Greek symbols, mathematics unicode and emojies

### ISSUE THREAD

**Issue by henrysheehy** [helix-editor/helix#9506]
Great editor!

I'd like to ask if it's possible to implement Greek symbols, mathematics unicode and emojies? If not, I will do so at at the level of the keyboard input, but I would prefer Helix, for its autocompletion and hints.

Thanks!

**Comment by pascalkuthe** [comment]
Duplicate of #1438 I personally do think this is better solved at the keyboard level or potentially snippets/abnreviations in the future
