### ISSUE TITLE
bash: hx: command not found

### ISSUE THREAD

**Issue by Android789515** [helix-editor/helix#9507]
Followed the install instructions.

1. yay -S helix
2. enter password
3. configure runtime in `~/.bashrc`:
```
HELIX_RUNTIME=~/src/helix/runtime
```
4. run `hx --health`

I get `bash: hx: command not found`

**Comment by pascalkuthe** [comment]
* The archlinux package isn't maintained by js this is not the right place to report this
* archlinux rename the helix binary (usually hx) to helix
* Yöu shouldn't manually configure the runtime directory if you are installing from a package manager

**Comment by Android789515** [comment]
This should be in the install instructions.
