### ISSUE TITLE
Infinite loop when trying to edit `-->` in a markdown document with multiple cursors

### ISSUE THREAD

**Issue by jbethune** [helix-editor/helix#9547]
### Summary

Helix crashes when I change two end of comment markers at the same time using two cursors

### Reproduction Steps

Given `foo.md` with contents:

```txt
<!--
beginning of comment

some ASCII arrows that we need to defuse for the time being
-->
-->

actual end of comment
-->
```

I want to add a space before the `>` arrowheads because they are otherwise treated like end of comment markers.

I tried this:

1. Position the cursor over the first arrowhead (`>` character) on line 5
2. Press `C` to get a second cursor on the second arrowhead
3. Press `i` to enter insert mode with both cursors

I expected this to happen:
1. I could insert a space or press any other key to insert a character

Instead, this happened:
1. Helix froze
2. The CPU usage went to 100% and didn't stop until I killed `-9` the helix process

### Helix log

<details><summary>~/.cache/helix/helix.log</summary>

```
2024-02-06T09:58:38.651 helix_view::editor [ERROR] Failed to initialize the language servers for `source.md` - `marksman` { cannot find binary path }
```

</details>

### Platform

Linux

### Terminal Emulator

alacritty

### Installation Method

apt

### Helix Version

helix 23.10 (f6021dd0)

**Comment by pascalkuthe** [comment]
This is a known issues with the old tree sitter version used in the last release. This us fixed on mastee
