### ISSUE TITLE
No way to execute static commands from the command line.

### ISSUE THREAD

**Issue by 7ombie** [helix-editor/helix#9559]
There are static commands that are not used often enough to remember the keybinding, that are useful occasionally. Unless I'm missing something, there's no way to access stuff like `switch_to_uppercase` from the command line.

**Comment by the-mikedavis** [comment]
Yeah they can't be executed from command mode (`:`) but you can use the command picker (`<space>?`)

**Comment by 7ombie** [comment]
Ahh, of course. That makes sense. I'm an idiot! Thanks!
