### ISSUE TITLE
Make `m` a special textobject identifier representing pair under cursor

### ISSUE THREAD

**Issue by EpocSquadron** [helix-editor/helix#956]
I got used to kakoune's `m` selecting everything in-between and including the brackets. Doing the same in helix requires using `ma` (since `mm` goes to the matching brace), which isn't so bad in and of itself. However it does require stopping to think which textobject is needed, as you might be on the character of any pair helix understands. 

I propose adding `m` as a special textobject indicating whichever textobject is recognized under cursor. The result is one can reliably `mam` (or `mim`) from any pair character and get the intended result without reaching for the appropriate textobject identifier, improving the ergonomics of match mode for little cost.

If used inside a set of recognized nested textobjects, it would choose the closest. If none, it would do nothing.

**Comment by sudormrfbin** [comment]
This was actually a left over todo from #320 (vim-sandwich's `b` pretty much does what you described). The relevant code for surround matching is [here](https://github.com/helix-editor/helix/blob/c9cbc344fc28dee5a0a5d3a7662c5c223067ab23/helix-core/src/surround.rs#L151-L171) if anyone wants to take a look.

**Comment by pickfire** [comment]
I did a similar patch but for paragraph instead https://github.com/helix-editor/helix/pull/784, maybe sooner or later when I need this I might write a patch for it.
