### ISSUE TITLE
avoid creation of closing quotation marks

### ISSUE THREAD

**Issue by piertoni** [helix-editor/helix#9568]
Hi,
in some cases creating a quotation mark `"` the editor adds a second closing one.
But when I am editing the code this is often wrong.
Is there an option to avoid the creation?
Thanks

**Comment by poliorcetics** [comment]
Is https://docs.helix-editor.com/configuration.html?highlight=auto%20pais#editorauto-pairs-section what you wanted ?

**Comment by piertoni** [comment]
yes, exactly! Thanks
