### ISSUE TITLE
Add commands for everything that's currently hardcoded.

### ISSUE THREAD

**Issue by 7ombie** [helix-editor/helix#9571]
There're a bunch of items in [the Keymap doc][keymap] that have `N/A` as their documented command. As a result, users can only customize a subset of their bindings.

For example, there's currently no way to assign a new keybinding for debugging. We must use `g` inside Space Mode. As my debugger is usually LLDB, I'd prefer to use `l` (inside Space Mode), but there's no `debug` command to bind to.

[keymap]: https://docs.helix-editor.com/keymap.html#space-mode

**Comment by the-mikedavis** [comment]
Those `N/A`s are there because the key opens a "minor mode" (another set of keybindings). Also see https://docs.helix-editor.com/keymap.html#minor-modes which is a set of bindings that do the same thing. The N/A for repeat last insert on that page is covered by https://github.com/helix-editor/helix/issues/1488

**Comment by 7ombie** [comment]
Why does Helix treat minor mode bindings any differently? For example, if the user added this to their config...

``` toml
[keys.normal.space]
l = "debug"
g = "no_op"
```

... couldn't the Space Mode be updated to remove `g` and add `l` etc?

It's not the end of the world, but it keeps coming up (I can't rebind the dot or colon, and have limits with minor modes). I just wondered if there was a reason to not support it (or if it just hadn't been implemented).

**Comment by the-mikedavis** [comment]
Minor modes are really just groups of keybinds. For example `<space>g` and `<space>w` are defined as: https://github.com/helix-editor/helix/blob/a1272bdb17a63361342a318982e46129d558743c/helix-term/src/keymap/default.rs#L227-L269

If you want to remap entire modes you need to move the commands in that mode:

```toml
[keys.normal.space]
g = "no_op"
[keys.normal.space.l]
l = "dap_launch"
r = "dap_restart"
# ... etc ...
```

I've reopened https://github.com/helix-editor/helix/issues/5734 which talks about finding a convenient way to remap those.

> I can't rebind the dot or colon

Colon isn't special-cased as far as I'm aware. You can rebind the `command_mode` command to another key and remap `:`.

**Comment by 7ombie** [comment]
Thanks for taking the time.

> Colon isn't special-cased as far as I'm aware. You can rebind the command_mode command to another key and remap :.

I didn't know that. I just assumed, based on the docs.

> I've reopened https://github.com/helix-editor/helix/issues/5734 which talks about finding a convenient way to remap those.

Thank you. Much appreciated.
