### ISSUE TITLE
Expand Arch Linux Install Instructions

### ISSUE THREAD

**Issue by Android789515** [helix-editor/helix#9573]
### [Arch Linux extra](https://docs.helix-editor.com/install.html#arch-linux-extra)

Releases are available in the extra repository:
```
sudo pacman -S helix
```
Additionally, a [helix-git](https://aur.archlinux.org/packages/helix-git/) package is available in the AUR, which builds the master branch.

## What's missing?

It's not clear that the command to run Helix is changed from `hx` to `helix` when installing from AUR.

I think this should be documented right below the install instructions for Arch Linux.

**Comment by the-mikedavis** [comment]
That documentation lives here: https://github.com/helix-editor/helix/blob/master/book/src/install.md#arch-linux-extra

Feel free to send a PR

**Comment by keilmillerjr** [comment]
It is a shame that you can not make comments on official arch packages. However, helixbinhx package from the AUR addresses this issue and makes helix work as expected.
