### ISSUE TITLE
Yank error messages from LSP

### ISSUE THREAD

**Issue by Luv-Ray** [helix-editor/helix#9598]
Currently, error messages from LSP are displayed in the upper right corner, but they cannot be selected or yanked.

Sometimes it is necessary to search for the corresponding error message, but it can only be manually retold. Therefore, it would be much more convenient if it was possible to yank the error message from the LSP.

![image](https://github.com/helix-editor/helix/assets/111646748/74e487d6-c6e9-42db-b3ce-2a06c2cb7506)

**Comment by woojiq** [comment]
https://github.com/helix-editor/helix/issues/9527

**Comment by pascalkuthe** [comment]
closing as duplicate
