### ISSUE TITLE
Rust Leptos view! macro html highligting.

### ISSUE THREAD

**Issue by SofusA** [helix-editor/helix#9622]
[Leptos](https://github.com/leptos-rs/leptos) uses `view!` macro for html instead of `html!`.
Syntax highlighting is therefore not switched to html.

It could be solved like #8603.

Issue for `html!` macro: #4466

**Comment by pascalkuthe** [comment]
While the name `html` is unambigous `view!` macros are absolutely used for other purposes aswell so I don't think just injection html into every macro named view is a good idea. You can modify the query locally but I don't think we should be doing this by default

**Comment by SofusA** [comment]
Yeah i agree. The problem is with Leptos' macro naming and not with Helix. 

I have added the following block in `~/.config/helix/runtime/queries/rust/injections.scm` so solve this locally:
```
((macro_invocation
   macro:
     [
       (scoped_identifier
         name: (_) @_macro_name)
       (identifier) @_macro_name
     ]
   (token_tree) @injection.content)
 (#eq? @_macro_name "view")
 (#set! injection.language "html")
 (#set! injection.include-children))
```
