### ISSUE TITLE
Where is local diagnostics for rust?

### ISSUE THREAD

**Issue by noktoborus** [helix-editor/helix#9628]
### Summary

When I edit the code in rust, I do not see rust-analyzer errors for an open file (space+d), but the list of errors can be viewed in the 'workspace diagnostics picker' (space+D). Is that what it's supposed to be?

### Reproduction Steps

 

I tried this:

1. `hx`
2. open rust's source code with many errors
3. press space+d

I expected this to happen:
see rust-analyzer messages for current buffer

Instead, this happened:
nothing

### Platform

Windows

### Terminal Emulator

Alacritty

### Installation Method

cargo install

### Helix Version

helix 23.10 (a1272bdb)

**Comment by woojiq** [comment]
Duplicate of https://github.com/helix-editor/helix/issues/3267

**Comment by noktoborus** [comment]
> Duplicate of #3267

thanks, https://github.com/helix-editor/helix/pull/7367 fixes it
