### ISSUE TITLE
Use Patience diff for git gutter

### ISSUE THREAD

**Issue by gyreas** [helix-editor/helix#9645]
Patience diff algorithm essentially shows human-readable diffs, for example given:
```c
int original() {
    // whatnot
}
```
making some changes, we get with the current version:
```c
int original() {
    // whatnot
   addition();  // >>>
}              // >>>
//            // >>>
int addition() { // >>>
  // nah        // >>>
}
```
where this is (arguably) more informative/readable:
```c
int original() {
    // whatnot
   addition();  // >>>
}
//                // >>>
int addition() { // >>>
  // nah        // >>>
}              // >>>
```
`// >>>` presents line with gutter highlight

PS: I know git supports patience diff, but does gix?

**Comment by kirawi** [comment]
The patience algorithm is separate, but this case seems to be a dupe of https://github.com/helix-editor/helix/issues/9072

**Comment by kirawi** [comment]
Actually, the histogram method implementede in `imara-diff` is a variant of the patience diff so this is likely something else.

**Comment by pascalkuthe** [comment]
Yeah histogram is an optimized patience diff. That is just a slider and fundamentally ambiguous. Has nothing to do with the diffing algorithm. Closing as duplicate
