### ISSUE TITLE
Show register contents when typed

### ISSUE THREAD

**Issue by EpocSquadron** [helix-editor/helix#965]
One of the goals of helix is to emulate and improve upon the interactive visual feedback that kakoune brought to the vim model. One feature that hasn't seen improvement is with registers. What if typing `"` brings up a list of all occupied registers? This can help the user recall which identifiers they are juggling in a given session. 

Further imagine that typing the identifier for one of those occupied registers shows the contents in a pop-up. Obviously some contents will be too large, but even a short truncated version can cue the user on what was stored, and we could print the number of stored selections as well. The user will then have confidence that they are using the right register for the command they are about to type.

There is even potential that we could reuse the picker ui, treating `"` as the trigger for the ui.

**Comment by sudormrfbin** [comment]
We can reuse the infobox for this, which would show a nice little popup similar to what we have for keybindings now.

**Comment by archseer** [comment]
👍🏻 from me, I used https://github.com/junegunn/vim-peekaboo in my neovim setup
