### ISSUE TITLE
Mint Language Server

### ISSUE THREAD

**Issue by jgarte** [helix-editor/helix#968]
https://www.mint-lang.com/

`mint ls` was merged into nvim-lspconfig recently.

There is an open pull request for mint in emacs [here](https://github.com/joaotavora/eglot/pull/750).

Mint's language server is built into the cli interface of mint itself.

Here are the features that are currently supported by the mint language server:

https://github.com/mint-lang/mint/blob/master/src/ls/README.md

**Comment by kirawi** [comment]
Added this: https://github.com/helix-editor/helix/wiki/FAQ#adding-a-language
