### ISSUE TITLE
Delete and move/rename buffer and associated file commands

### ISSUE THREAD

**Issue by Kim-Dewelski** [helix-editor/helix#9682]
I personally find it somewhat annoying that Helix is able to create new files via the `open` command, but lacks the ability to delete a buffer and its associated file, or move/rename a file associated with a buffer to a different location. If I remove a file externally via something like `rm`, the buffer remains alive and it is very easy to accidentally create the old file from the buffer again. This is great and all in a lot of cases, but sometimes I just want to close a buffer and delete its associated file, so I believe helix would benefit from these additions.

**Comment by kirawi** [comment]
Move is supported on master via the LSP spec. We can also support deleting files (and opening files) through the LSP spec. I'm not sure how Blaz feels about having a non-LSP implementation.

**Comment by Kim-Dewelski** [comment]
What are some of the reason to not include a `:delete` command which just closes the buffer, and deletes the associated underlying file? Is there a technical or opinionated reason mainly? I would gladly love to make a PR if I know it would be considered.
