### ISSUE TITLE
Can't add existing grammar to custom language entry in `languages.toml`

### ISSUE THREAD

**Issue by ggsvr** [helix-editor/helix#9700]
### Summary

Adding an existing grammar to a custom language in `languages.toml` does not work. I tried adding the `html` grammar to a html templating language, but `tree-sitter` doesn't seem to start when I open the relevant source files.

### Reproduction Steps

 

I tried adding the following entry to my `languages.toml` file:
```
[[language]]
name = "gotmpl"
scope = "text.tmpl.basic"
file-types = ["tmpl"]
roots = ["go.mod"]
auto-format = true
grammar = "html"
indent = { tab-width = 2, unit = "  "}
```

and opened a `index.tmpl` file:

```
<!DOCTYPE html>
<html lang='en'>

</html>
```

I expected the highlitghting and other tree-sitters to work, but I get some error in the helix log file,
and the `tmpl` file is not processed.

### Helix log

<details><summary>~/.cache/helix/helix.log</summary>

```
2024-02-22T16:25:37.466 helix_view::clipboard [DEBUG] Using wl-copy+wl-paste to interact with the system and selection (primary) clipboard
2024-02-22T16:25:37.468 helix_core::syntax [ERROR] Could not parse queries for language "gotmpl". Are your grammars out of sync? Try running 'hx --grammar fetch' and 'hx --grammar build'. This query could not be parsed: QueryError { row: 3, column: 3, offset: 20, message: "field", kind: NodeType }

```

</details>

### Platform

Linux

### Terminal Emulator

Konsole

### Installation Method

archlinux package manager

### Helix Version

helix 23.05

**Comment by woojiq** [comment]
Make sure you read the docs: https://docs.helix-editor.com/master/guides/index.html and check out a bunch of similar questions/discussions.

**Comment by the-mikedavis** [comment]
See https://github.com/helix-editor/helix/discussions/9530#discussioncomment-8361369 - you also need queries for the new language and you can inherit them from `html`
