### ISSUE TITLE
Too high RAM usage in tests

### ISSUE THREAD

**Issue by mo8it** [helix-editor/helix#9706]
After running `cargo t --workspace`, all of my RAM is used and my OOM starts killing processes. I have 16 GB of RAM. The tests that cause that are those of `helix-tui`. I tried using the `-j 1` option, but it didn't help.
I can skip the tests of `helix-tui` for now. But are you planning to address this issue? A unit test shouldn't require 16 GB of RAM.

**Comment by mo8it** [comment]
After running `cargo t --workspace --exclude helix-tui`, the unit tests run to completion, but my RAM was at about 95% until the end. It might be worth reducing the memory usage of all tests if possible.

**Comment by kirawi** [comment]
I can't replicate. The highest it ever went was 1gb.
