### ISSUE TITLE
Add normal mode shortcuts to insert mode

### ISSUE THREAD

**Issue by italomaia** [helix-editor/helix#9716]
While using helix and coming from a non-vim exposed environment, I felt adding normal mode selection shortcuts greatly improved the "insert mode" experience. By doing so, I managed to edit files while changing between modes way less often then usual. Here are some example shortcuts that greatly help with this:

```
[keys.insert]

C-u = ["undo"]
A-u = ["redo"]
C-y = ["yank"]
C-d = ["delete_selection"] # delete selection
A-up = ["extend_to_line_bounds", "delete_selection", "move_line_up", "paste_before", "move_line_up"] # moves line up; like vscode
A-down = ["extend_to_line_bounds", "delete_selection", "paste_after", "move_line_down"] # move line down; like vscode
C-left = ["move_prev_word_start"] # jump and select word left
C-right = ["move_next_word_end"] # jump and select word right
C-s = ["normal_mode",":w"] # save file
```

Those are just some examples, but in general, adding more shortcuts really helps here, specially if they are very similar to what is available in normal mode (got lots of remapping in normal mode too, but that is another topic)

**Comment by pascalkuthe** [comment]
Helix is a model editor. You are supposed to switch modes and using it in the way you described is explicitly not supported (and known to lead to crashes). If you want to avoid changing modes you are not using helix as intended. Helix is fundamentally a modal editor and we have no intentions to cover nom-modal usage patterns

**Comment by italomaia** [comment]
Will test it some more. Did not experience crashes so far (just some weird behaviors here and there). 
Just wanted to bring to the party the idea that changing modes only when needed could make things a bit more efficient. 
Feels like a waste to not let insert tap into normal modes power.
