### ISSUE TITLE
Support "plus" key

### ISSUE THREAD

**Issue by fnuttens** [helix-editor/helix#9759]
There’s already the "minus" key (see [doc](https://docs.helix-editor.com/remapping.html#special-keys-and-modifiers)), so why not add the `+` one?

**Comment by fnuttens** [comment]
This would useful for me since my keyboard layout uses AltGr to type the `-` and `+` signs :)

**Comment by the-mikedavis** [comment]
`"minus"` is a special key so that it's easier to distinguish from how it's used in key chords like `C-c` (<kbd>Ctrl</kbd>+<kbd>c</kbd>). You can bind `+` with `"+" = "some_command"`
