### ISSUE TITLE
Escaping from repetitions conflicts with the Escape key when it's rebound.

### ISSUE THREAD

**Issue by 7ombie** [helix-editor/helix#9784]
### Summary

I have <kbd>Esc</kbd> bound to `select_mode` in Normal Mode (so I can toggle between Normal and Select Mode, and can double-tap <kbd>Esc</kbd> to go from Insert Mode to Select Mode).

The binding works almost perfectly, but there is a minor bug. If I enter any digits (in Normal Mode) to repeat something, then hit <kbd>Esc</kbd> to cancel the operation, the binding also fires (incorrectly activating Select Mode).

I can't find any other cases like this. I can escape from the command line, file picker, command palette etc, without the event bubbling up.

### Platform

macOS

### Terminal Emulator

iTerm2

### Installation Method

brew

### Helix Version

23.10

**Comment by pascalkuthe** [comment]
Esc ist not special with regard to repetition. You can hit any unbound key so the is working as expected

**Comment by 7ombie** [comment]
> Esc ist not special with regard to repetition.

@pascalkuthe - Sorry. You're correct. I originally thought this was an issue with how I rebound the key, but it's not. It actually affects every user.

I get what you're saying about the way it works (it's just doing what it's meant to do), but that doesn't work in practice (at least as well as it could). If the user tries to enter `23` while in Select Mode, but accidentally enters `233`, then hits <kbd>Esc</kbd> to back out of the operation, does it really *make sense* to activate Normal Mode two-hundred and thirty-three times?

Given how <kbd>Esc</kbd> is used in Helix, particularly with regard to escaping from pickers and prompts etc, I think it should be special-cased with regard to repetitions, so it behaves conventionally in that context too.

We can safely assume that the user will never need to use repetitions to escape from something repeatedly. And it doesn't matter if the user customizes the binding, as they'll still use <kbd>Esc</kbd> to escape from things (that's not even configurable).

If Helix just said that the current situation will never change (<kbd>Esc</kbd> inside pickers and prompts is bound to `escape`, and cannot be rebound), then <kbd>Esc</kbd> could be hardcoded to escape from repetitions as well. User could still rebind <kbd>Esc</kbd> in general (outside pickers and prompts) without this conflict.

**Comment by 7ombie** [comment]
The current behavior isn't what the user expects, but I understand why it works that way. I misunderstood the issue. Sorry.

**Comment by 7ombie** [comment]
It'd be nice if there was some way to configure what <kbd>Esc</kbd> is bound to during a repetition, so it could be explicitly bound to `no_op` in that context, while still permitting it to be bound to other things in other contexts.

**Comment by 7ombie** [comment]
Never mind. I'll open a new issue.
