### ISSUE TITLE
completion-replace problem

### ISSUE THREAD

**Issue by AndreaMonzini** [helix-editor/helix#9799]
### Summary

When i enable the completion-replace option, using the cursor hover, the replace miss the last character of the previous word.

### Reproduction Steps

I tried this:

1. when i hover on a word the autocomplete replace all the word but not the last character of the previous word.

I expected this to happen:

the completion-replace should replace the entire previous word.

I am using helix 23.10 (f6021dd0) and pylsp

config.toml:
preview-completion-insert = true
completion-replace = true

### Platform

Linux Fedora 39

### Terminal Emulator

GNOME terminal

### Installation Method

dnf

### Helix Version

helix 23.10 (f6021dd0)
![hx](https://github.com/helix-editor/helix/assets/12413409/7155ee77-367b-4f9e-9d40-d3f3bfe0daed)

**Comment by pascalkuthe** [comment]
please attach a log file these kinds of issues are often hard to reproduce since we don't select the replaced word but rather the server does

**Comment by AndreaMonzini** [comment]
Hello, here the helix.log:
[helix.log](https://github.com/helix-editor/helix/files/14482933/helix.log)

i have similar problem with completion "insert" ( completion-replace = false ), better to open another issue ?
Thank you
