### ISSUE TITLE
Add ability to provide indent size of current document to formatter

### ISSUE THREAD

**Issue by daedroza** [helix-editor/helix#9821]
At the moment, the formatter's capacity to provide information seems limited. There are some workarounds like '{}' to get file_path and so on which aren't merged.

Instead of this, I would like to propose a standardized set of APIs like command expansions that also provide information about current document to be usable inside args of formatters.

Huge projects like chromium/AOSP have multiple programming style. Having a dynamic way to set these properties during runtime of ":format" command would be super helpful.

**Comment by kirawi** [comment]
https://github.com/helix-editor/helix/pull/6979

**Comment by pascalkuthe** [comment]
Will be covered by #10389 or https://github.com/helix-editor/helix/pull/6979 so closing in favor of those
