### ISSUE TITLE
Making minor modes (and their menus) fully customizable.

### ISSUE THREAD

**Issue by 7ombie** [helix-editor/helix#9829]
As an enduser, if you attempt to customize the existing minor modes, you quickly run into a number of limitations which prevent you from producing menus that function like the built in menus. Trying to create new minor modes is even more limiting.

Rather than preemptively open half a dozen issues, it seemed better to open one general issue to establish what needs doing, and separate issues can be opened later, if required:

+ There's no way to assign new titles (`Match`, `Space` etc) to existing menus.
+ There's no way to assign titles to new menus.
+ Commands that are added to menus do not infer their descriptions (from those used by Command Palette).
+ There's no way to add/edit the descriptions used by commands within a menu.
+ The order of the commands within a given menu cannot be set or described (alphanumerical, descending etc) by the user.

There's also #9814 (some minor-mode-commands have no names, so cannot be rebound), but that's already an open issue.

**Comment by 7ombie** [comment]
It would be nice if we could arbitrarily define a menu's content with a block of text (multiline string or a separate file or whatever). The format would be simple: The first line is the title, and the remaining lines form the body. The width would be inferred as the length of the longest line, while the height would be inferred from the number of lines.

For example, we could provide something like this:

```
New Menu
o Open the thing
O Open the thing, then do another
  thing, with a hard break to preserve
  the desired line width
d Do the thing 
```

I don't think much more is *required*. There are other features that'd be nice to have, like inferring menu descriptions from the Command Palette entries, but they'd be pure conveniences, if you can make your own menus. This leaves #9814 open, but it addresses all of the bullet points (with the freedom to do other things as well).

**Comment by kirawi** [comment]
The descriptions are covered by https://github.com/helix-editor/helix/issues/1474

**Comment by 7ombie** [comment]
What does #1474 do that couldn't be achieved with a simple block of text? An arbitrary block of text solves other problems too. To be honest, #1474 just seems complicated and limited at the same time.

**Comment by kirawi** [comment]
Sorry, that was the wrong issue. It's actually https://github.com/helix-editor/helix/issues/1752

**Comment by 7ombie** [comment]
Cool. No worries, @kirawi. Thanks for correcting that.

You're right (#1752 does cover descriptions), and there are a bunch of other issues that #1752 links to that roughly cover the bullet-points above.

I'm not sure (I'm literally 50/50) whether there's any merit in summarizing a bunch of open, related issues in a separate issue, just to look at more general solutions. In any case, it's probably not my place to do that here, and this issue doesn't really achieve that very well anyway.

Thanks for your time and patience, @kirawi. Much appreciated.

BTW - I've been heavily customizing Helix lately, and came across a few issues I wanted to address. I'm not looking to constantly spam the issue tracker.
