### ISSUE TITLE
Wrong syntax for XML comment

### ISSUE THREAD

**Issue by ndtoan96** [helix-editor/helix#9842]
### Summary

Helix is currently using C style comment for XML. But that's wrong. XML comment should be like this: `<!--Your comment-->`

### Reproduction Steps

1. open an XML document
2. press `Ctrl+c` to comment a line

### Platform

Windows

### Terminal Emulator

wezterm 20240203-110809-5046fc22

### Installation Method

winget

### Helix Version

helix 23.10 (f6021dd0)

**Comment by kirawi** [comment]
Fixed on master https://github.com/helix-editor/helix/pull/4718
