### ISSUE TITLE
Rename Symbol

### ISSUE THREAD

**Issue by EmranMR** [helix-editor/helix#9844]
### Summary

Hello!
I am encountering a bug when using the `lsp` feature in `java` but I presume it could possibly be universal and because of Helix core implementation.
Basically when you use `rename symbol` which is `space + r` the LSP successfully renames the symbol all over, it also correctly renames the Java file to match the new class name. However Helix gets confused, as the buffer is still associated with the _**old file name**_ of the _renamed_ `class` 

### Reproduction Steps

 

I tried this:
- Have the `jdtls` installed via homebrew for java
- run the `hx --health java` java to make sure all good
-  `java version 17`

1. `hx .` to open the project
2. Make sure you are using a class that already exists such as `Test.java`
3. open the Test.java
4. go to the class name and once `Test` is highlighted press `spare+r` to rename the symbol
5. once that is done you will see the lsp is highlighting errors
6. do `:sh ls <the folder the file is in>` and you will see the file name is changed
7. try `:reload` and you get this error `can't find file to reload from xxx` 
8. `:lsp-restart` no change

9. bottom left you can see the buffer is the deleted/renamed file

I expected this to happen:
I expect for Helix to move on to the new renamed file.

Instead, this happened:
It stays on to the old deleted file

### Helix log

<details><summary>~/.cache/helix/helix.log</summary>

```
please provide a copy of `~/.cache/helix/helix.log` here if possible, you may need to redact some of the lines
```

</details>

### Platform

MacOS

### Terminal Emulator

iTerm/Prompt

### Installation Method

brew

### Helix Version

23.10 (f6021dd0)

**Comment by EmranMR** [comment]
Actually it might also be the case with renaming the file using `code action`.

**Comment by pascalkuthe** [comment]
Try again with master. We added support for additional LSP features

**Comment by EmranMR** [comment]
Hi @pascalkuthe both issues have indeed been fixed on the Master! :) 

Just out of curiosity as I am new to Helix, how does the release cycle work for Helix? Am I better  off to periodically just build from the Master myself rather than waiting for `brew` or etc?
