### ISSUE TITLE
Shell command output insert/append introduces newline

### ISSUE THREAD

**Issue by fnuttens** [helix-editor/helix#9845]
### Summary

`shell_insert_output` (`!`) and `shell_append_output` (`A-!`) add a newline after the output.

### Reproduction Steps

https://asciinema.org/a/646233

### Helix log

Not relevant

### Platform

Linux Fedora 39

### Terminal Emulator

Konsole 23.08.5

### Installation Method

source

### Helix Version

helix 23.10 (00653c77)

**Comment by the-mikedavis** [comment]
`echo` adds a trailing newline to its content. You can use `echo -n` to trim it
