### ISSUE TITLE
Cannot Fetch Grammars

### ISSUE THREAD

**Issue by Carlo-Monte** [helix-editor/helix#9864]
### Summary

hx -g fetch fails

### Reproduction Steps

How to reproduce: 

```
$ hx -g fetch
Fetching 163 grammars
162 up to date git grammars
Failure 1/1: gemini Git command failed.
Stdout: 
Stderr: fatal: unable to access 'https://git.sr.ht/~sfr/tree-sitter-gemini/': The requested URL returned error: 403

Error: 1 grammars failed to fetch

```

### Helix log

<details><summary>~/.cache/helix/helix.log</summary>

```
please provide a copy of `~/.cache/helix/helix.log` here if possible, you may need to redact some of the lines
```

</details>

### Platform

Alpine Linux on AMD64 and on ARM64

### Terminal Emulator

none (=framebuffer) and Sakura

### Installation Method

apk add

### Helix Version

23.10

**Comment by kirawi** [comment]
This is fixed on master: https://github.com/helix-editor/helix/pull/9316
