### ISSUE TITLE
Count handling no longer accepts numbers containing zero

### ISSUE THREAD

**Issue by trink** [helix-editor/helix#9871]
Attempt to move 10 lines down `10j`.   When the zero is typed the count is cleared.

PR #8471 broke this functionality with the if expression in the match. https://github.com/helix-editor/helix/blob/3915b04bd91084477b3076952e6ad6cfdd414e72/helix-term/src/ui/editor.rs#L921

**Comment by trink** [comment]
The reason for this is a key mapping.  Will this no longer be allowed?
```
[keys.normal]
"0" = "goto_line_start"
```

**Comment by the-mikedavis** [comment]
We should be able to support the bindings #8471 was trying to enable and also the one you posted. I believe we just need to split the count handling into two branches:

* When the count has been started (`cxt.editor.count.is_some()`), any number always continues the count.
* When the count hasn't been started (`cxt.editor.count.is_none()`), `key!('1'..='9')` starts the count if that key isn't bound to a command.

I'll post a patch
