### ISSUE TITLE
No typst support on main repos from: Arch, Termux, Alpine, Void? (maybe more).

### ISSUE THREAD

**Issue by Disonantemus** [helix-editor/helix#9872]
### Summary

I did install helix in the following **distros**:
- Arch
- Termux
- Alpine
- Void

Using the package manager from each **distro**, and none show any support for `typst`.

Searching this repo shows that, there are _some kind_ of `typst` support.  
I did try [Building from Source from official Documentation](https://docs.helix-editor.com/install.html#building-from-source), with no success.  
With some [Issues](https://github.com/helix-editor/helix/discussions/8401) I was able to install, and get correct `health` output, but in the end, **no syntax highlighting** at all for `typst`.  

Shouldn't this be by default without any tinkering? or need to build from source? (No programmer here).

### Reproduction Steps

Arch Linux:
~~~ocaml
$ sudo pacman -S helix

$ hx
bash: hx: command not found

$ helix --version
helix 23.10

$ helix --health typst
Language 'typst' not found
Did you mean one of these: toml, typescript, tsx, twig, tsq, tablegen, tfvars, task, t32, todotxt, templ ?

$ ls -1d /usr/lib/helix/runtime/queries/ty*
/usr/lib/helix/runtime/queries/typescript
/usr/lib/helix/runtime/queries/typst

$ echo $HELIX_RUNTIME

$ export HELIX_RUNTIME=/usr/lib/helix/runtime

$ helix --health typst
Language 'typst' not found
Did you mean one of these: toml, typescript, tsx, twig, tsq, tablegen, tfvars, task, t32, todotxt, templ ?
~~~

Termux:
~~~ocaml
$ pkg install helix

$ hx --version
helix 23.10 (f6021dd0)

$ hx --health typst
Language 'typst' not found
Did you mean one of these: toml, typescript, tsx, twig, tsq, tablegen, tfvars, task, t32, todotxt, templ ?

$ ls -1d /data/data/com.termux/files/usr/opt/helix/runtime/queries/ty*
/data/data/com.termux/files/usr/opt/helix/runtime/queries/typescript
~~~
No typst folder inside: `/helix/runtime/queries/`.

&nbsp;

Alpine (distrobox, latest):
~~~ocaml
$ sudo apk add helix

$ hx --version
helix 23.10

$ hx --health typst
Language 'typst' not found
Did you mean one of these: toml, typescript, tsx, twig, tsq, tablegen, tfvars, task, t32, todotxt, templ ?
~~~

Void (distrobox, latest):
~~~ocaml
$ sudo xbps-install helix

$ hx --version
helix 23.10 (f6021dd0)

$ hx --health typst
Language 'typst' not found
Did you mean one of these: toml, typescript, tsx, twig, tsq, tablegen, tfvars, task, t32, todotxt, templ ?

$ ls -1d /usr/lib/helix/runtime/queries/ty*
/usr/lib/helix/runtime/queries/typescript/
~~~
No typst folder inside: `/helix/runtime/queries/`.

### Helix log

Many logs, see: Reproduction Steps

### Platform

Linux

### Terminal Emulator

Bash

### Installation Method

Main package manager for each distro.

### Helix Version

See: Reproduction Steps.

**Comment by the-mikedavis** [comment]
Support for typst was added in https://github.com/helix-editor/helix/pull/7474 which was merged after the 23.10 release. It'll be included in the next release
