### ISSUE TITLE
Svelte's expansion in <script> tag doesn't work properly

### ISSUE THREAD

**Issue by DoctorRyner** [helix-editor/helix#9889]
When using selection expand / shrink inside <script> tag to select JS construction, it just selects the entire tag

**Comment by the-mikedavis** [comment]
Duplicate of https://github.com/helix-editor/helix/issues/4618

**Comment by DoctorRyner** [comment]
@the-mikedavis oh, 2 years without an updates on these, I'm crying T-T

**Comment by the-mikedavis** [comment]
You can test drive https://github.com/helix-editor/helix/pull/5176 which should fix this for `expand_selection` / `shrink_selection`

**Comment by DoctorRyner** [comment]
@the-mikedavis oh, thanks, I merged it to my fork
