### ISSUE TITLE
Comments in multi language files

### ISSUE THREAD

**Issue by DoctorRyner** [helix-editor/helix#9917]
In such files as svelte we need to properly handle comments, e.g. :toggle_comments should work properly in proper places.

For Svelte when I put a comment it display syntax errors

```svelte
<script>
  // ..
</script>

<!-- ... -->

<style>
  // ...
</style>
```

**Comment by the-mikedavis** [comment]
Duplicate of https://github.com/helix-editor/helix/issues/7364
