### ISSUE TITLE
Invalid comment token in PKGBUILD files

### ISSUE THREAD

**Issue by hnorkowski** [helix-editor/helix#9942]
### Summary

When using the comment command (Ctrl+c for me) in PKGBUILD `//` is used as comment token. In previous versions the correct token `#` was used. 

Could be related to #9909

### Reproduction Steps

 

I tried this:

1. `hx PKGBUILD`
2. comment a line

I expected this to happen:
Line gets prefixed with `#`

Instead, this happened:
Line gets prefixed with `//`

### Platform

Linux

### Terminal Emulator

alacritty

### Installation Method

source

### Helix Version

bcf7b26

**Comment by pascalkuthe** [comment]
That filetype simply doesn't have a comment tokens defined. Adding one in the languages.toml is trivial. Feel free to send a PR

**Comment by c0rydoras** [comment]
I completely forgot about adding the comment token 😅
