### ISSUE TITLE
Panic in statusline update #9122

### ISSUE THREAD

**Issue by trink** [helix-editor/helix#9948]
Debug
----
`thread 'main' panicked at 'attempt to subtract with overflow', helix-term/src/ui/statusline.rs:98:36`

Release
----
`thread 'main' panicked at 'capacity overflow', library/alloc/src/raw_vec.rs:524:5`
Current master: b8e79c0ef52e71136712959af426f318d674fc96

Steps to Reproduce
----
1. stty rows 24 cols 110
2. hx helix-term/src/commands.rs
3. /deserialize&lt;ret&gt; # search
4. gd # goto_definition

**Comment by the-mikedavis** [comment]
I can't reproduce this. Do you have configuration for the statusline?

**Comment by trink** [comment]
@the-mikedavis everything is default

**Comment by trink** [comment]
sorry... this one wasn't the default
```
[editor.statusline]
left = ["mode", "file-name"]
center = ["diagnostics", "spinner"]
right = ["selections", "position", "file-encoding", "position-percentage"]
```
