### ISSUE TITLE
Alternative Python type-checking via pylsp-mypy

### ISSUE THREAD

**Issue by rakshasha-medhi** [helix-editor/helix#9952]
I was having issues with pyright, tried the usual suggestions here but to no avail.
Then I was looking for Python type-checking alternative and found pylsp-mypy.
it's working well and could serve as a great alternative for those want type-checking but having problems with pyright.

I think Helix users need to know this option hence an update to the "How to install the default LSP" for pylsp section would be great!

**Comment by the-mikedavis** [comment]
The wiki can be edited by anyone. Feel free to edit in a section for pylsp-mypy

**Comment by rakshasha-medhi** [comment]
> The wiki can be edited by anyone. Feel free to edit in a section for pylsp-mypy

Done!
I've added a section about pylsp-mypy for Python.

Cheers!
