### ISSUE TITLE
Change background color for each mode

### ISSUE THREAD

**Issue by italomaia** [helix-editor/helix#9982]
One thing that I find myself doing often while working with helix is keeping a eye at the left bottom corner to keep track of which mode is actively on. Would it be possible to change the color of the editor (alter the theme) based on the mode it is actively on? Maybe change the color of the cursor?

**Comment by kirawi** [comment]
See https://github.com/helix-editor/helix/discussions/8519

**Comment by woojiq** [comment]
You can also change a cursor shape based on a mode. It's actually very helpful I don't look at the statusbar anymore.
```toml
[editor.cursor-shape]
insert = "underline"
```

**Comment by danillos** [comment]
Check the [documentation](https://docs.helix-editor.com/themes.html), it is already possible to change the cursor color based on the mode.

**Comment by jgardona** [comment]
With respect, changing the entire background color is not a good deal. A cursor may be changed, and the color mode in status bar already do this. I think its preatty neat as it is.

**Comment by italomaia** [comment]
![bar](https://github.com/helix-editor/helix/assets/14670/03545f4f-fbba-4bce-9a43-e9dc601a9298)
As can be seen above, the cursor as a bar changes color depending on the cursor position.

![block](https://github.com/helix-editor/helix/assets/14670/f19a8a6e-9f28-4704-bc05-7106585f44b8)
As can be seen above, the cursor as a block does not change its color depending on the cursor position. 

While making the screenshots, I noticed that my terminal (fish + xfce4-terminal) does change the cursor color (block) when moving positions, so I assume allowing the cursor to change its color is configurable.

**Comment by ftonneau** [comment]
A belated comment (as I am not a Helix user): as @jgardona noted, changing the background color to signal mode changes may not be a good idea. Some relevant discussion here:

https://discuss.kakoune.com/t/avoiding-insert-normal-mode-confusion/2558

Don't miss the monkey-business video!
