### ISSUE TITLE
Replace with adjacent cursors moves cursor over

### ISSUE THREAD

**Issue by emilyyyylime** [helix-editor/helix#9987]
### Reproduction Steps

```
$ echo ab | hx
xs.<ret>r0
```
Now there is a gap between the two cursors (`[0]0[\n]` rather than `[0][0]\n`)

### Platform

Arch Linux

### Terminal Emulator

Kitty

### Installation Method

source

### Helix Version

helix 23.10 (8f65bfe0)

**Comment by pascalkuthe** [comment]
Duplicate of #5910
